### ISSUE TITLE
Deprecate the usage of the ossec-init.conf file from the whole qa repository

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1007]
### Description 

As part of the epic https://github.com/wazuh/wazuh/issues/7054, we have the main goal of removing the `/etc/ossec-init.conf` file from the Wazuh installations. Having said that, the next set of files should be updated to stop making use of that file in this Wazuh QA repository.

```
    - deps/wazuh_testing/wazuh_testing/tools/__init__.py
    - tests/integration/test_wpk/test_wpk_agent.py
    - tests/integration/test_wpk/test_wpk_manager.py
    - tests/integration/test_sca/test_basic_usage/data/sca_directories_test_suite.yml
```

If the information provided by `ossec-init.conf` is mandatory for the tests, this can be obtained from the `wazuh-control` script as it is explained in the issue https://github.com/wazuh/wazuh/issues/7081.

**Comment by DProvinciani** [comment]
Here a summary of the tests failures generated in the automated tests because of the removal of the `ossec-init.conf` file.

- Services test cases (for both manager and agent)

```
[2021-01-15T13:58:10.663Z] [0;31mImportError while loading conftest '/wazuh-qa/tests/integration/conftest.py'.[0m
[2021-01-15T13:58:10.663Z] [0;31m/wazuh-qa/tests/integration/conftest.py:19: in <module>[0m
[2021-01-15T13:58:10.663Z] [0;31m    from wazuh_testing.tools import LOG_FILE_PATH, WAZUH_CONF, WAZUH_SERVICE, ALERT_FILE_PATH[0m
[2021-01-15T13:58:10.663Z] [0;31mE   ImportError: cannot import name 'WAZUH_SERVICE'[0m
```

This is because of the import of `WAZUH_SERVICE`. It will try to read the `ossec-init.conf` file and will fail.

- Version check test cases

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.9.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /install_manager
collecting ... collected 14 items

install_manager_test.py::test_check_version FAILED                       [  7%]
install_manager_test.py::test_check_process_clusterd PASSED              [ 14%]
install_manager_test.py::test_check_process_modulesd PASSED              [ 21%]
install_manager_test.py::test_check_process_monitord PASSED              [ 28%]
install_manager_test.py::test_check_process_logcollector PASSED          [ 35%]
install_manager_test.py::test_check_process_remoted PASSED               [ 42%]
install_manager_test.py::test_check_process_syscheckd PASSED             [ 50%]
install_manager_test.py::test_check_process_analysisd PASSED             [ 57%]
install_manager_test.py::test_check_process_maild PASSED                 [ 64%]
install_manager_test.py::test_check_process_execd PASSED                 [ 71%]
install_manager_test.py::test_check_process_wazuhdb PASSED               [ 78%]
install_manager_test.py::test_check_log_errors PASSED                    [ 85%]
install_manager_test.py::test_check_ossec_conf PASSED                    [ 92%]
install_manager_test.py::test_connection_manager PASSED                  [100%]

=================================== FAILURES ===================================
______________________________ test_check_version ______________________________
install_manager_test.py:42: in test_check_version
    f = open('/var/ossec/etc/ossec-init.conf', 'r')
E   FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/ossec-init.conf'
=========================== short test summary info ============================
FAILED install_manager_test.py::test_check_version - FileNotFoundError: [Errn...
========================= 1 failed, 13 passed in 0.08s =========================
```

**Comment by SpotHound** [comment]
I'm working on this. 

We will start by reviewing the failures present in this PR: https://github.com/wazuh/wazuh/pull/7175/checks until they're solved.

We will be working on the `1007-init-conf1007-init-conf` branch.

**Comment by SpotHound** [comment]
We've detected some problems in the wazuh-packages branch https://github.com/wazuh/wazuh-packages/pull/609

I'm going to fix them and notify to the development team to continue with this issue.

**Comment by SpotHound** [comment]
# Required testing
- [ ] Installation test
- [ ] Upgrade test
- [ ] WPK test
- [ ] Service test
- [ ] Unattended install

**Comment by SpotHound** [comment]
After the last changes, I've tested again:

Integration: https://ci.wazuh.info/view/Tests/job/test_integration/1095/console
Install: https://ci.wazuh.info/job/Test_install/40324/ 
Service: https://ci.wazuh.info/job/Test_service/1016/

**Comment by SpotHound** [comment]
We've merged last changes from master and make a required fix.

Testing manager: https://ci.wazuh.info/job/test_integration/1183/console
