### ISSUE TITLE
Reports errors on vulnerability detector tests status (master branch)

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1017]
Hi all,

We need to check and sanitize the status of Vulnerability Detector tests in the master branch.

**Comment by SpotHound** [comment]
## Checking test_integration status

We need to launch some integration tests to see which checks are failing right now and find a solution for whatever error that appears.

Tier 0: https://ci.wazuh.info/view/Tests/job/test_integration/1079/console
Tier 1: https://ci.wazuh.info/view/Tests/job/test_integration/1080/console
Tier 2: https://ci.wazuh.info/view/Tests/job/test_integration/1081/console

**Comment by SpotHound** [comment]
# Vulnerability detector integration tests
## Tier 2
Build: https://ci.wazuh.info/job/test_integration_vulnerability_detector/292/console
![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/1b5bd873-f8df-45b6-9bd5-28208f0ddb81)
## Tier 2
Build: https://ci.wazuh.info/job/test_integration_vulnerability_detector/291/
![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/764a4f60-8342-4fce-9ac3-0d59062c05fa)
