### ISSUE TITLE
Review vulnerability detector tests: test_window_version_indexing fails 

### ISSUE THREAD

**Issue by SpotHound** [wazuh/wazuh-qa#1031]
![image](https://user-images.githubusercontent.com/15269938/106911109-28f9ff00-6702-11eb-8e63-2255f54d894c.png)

Another problem found on integration tests for vulnerability detector is with `test_window_version_indexing` test.

This tests look for the following (formated) message:

```
rf"The CPE 'o:microsoft:{mock_system['index_name']}:(-|r2|{mock_system['os_release']}):" +
            rf"({mock_system['os_release']})?:::::{mock_system['architecture']}:' from the agent '.*' was indexed."
```
It seems that that CPE is not being indexed on the master branch. We need to investigate why.

Build: https://ci.wazuh.info/job/test_integration_vulnerability_detector/291/
![image](https://user-images.githubusercontent.com/15269938/106911297-45963700-6702-11eb-851e-5621ae1dff22.png)

**Comment by SpotHound** [comment]
Debugging at: https://ci.wazuh.info/job/test_integration_vulnerability_detector/297/console

**Comment by SpotHound** [comment]
Testing here: https://ci.wazuh.info/job/test_integration/1139/console

**Comment by SpotHound** [comment]
The problem seems to be with an outdated path for wazuh_db: 

```
2021/02/04 05:40:05 wazuh-modulesd:database[15283] wm_database.c:665 at wm_inotify_start(): DEBUG: Waiting for event notification...
2021/02/04 05:40:05 wazuh-modulesd[15283] wazuhdb_op.c:42 at wdbc_connect(): ERROR: Unable to connect to socket '/var/ossec/queue/db/wdb'.
2021/02/04 05:40:05 wazuh-modulesd[15283] wazuhdb_op.c:124 at wdbc_query_ex(): ERROR: Unable to connect to socket '/queue/db/wdb'.
2021/02/04 05:40:05 wazuh-modulesd:task-manager[15283] wm_task_manager_commands.c:468 at wm_task_manager_send_message_to_wdb(): ERROR: (8209): Tasks DB Cannot execute SQL query: err database 'queue/tasks/tasks.db'
2021/02/04 05:40:06 wazuh-modulesd[15283] wazuhdb_op.c:33 at wdbc_connect(): INFO: Cannot find '/var/ossec/queue/db/wdb'. Waiting 2 seconds to reconnect.
2021/02/04 05:40:07 wazuh-modulesd:vulnerability-detector[15283] wm_vuln_detector.c:7212 at wm_vuldet_get_wdb_socket(): DEBUG: (5441): Unable to connect to socket '/var/ossec/queue/db/wdb'. Waiting '4' seconds.
2021/02/04 05:40:08 wazuh-modulesd[15283] wazuhdb_op.c:33 at wdbc_connect(): INFO: Cannot find '/var/ossec/queue/db/wdb'. Waiting 3 seconds to reconnect.
2021/02/04 05:40:09 wazuh-analysisd[15115] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
2021/02/04 05:40:11 wazuh-modulesd[15283] wazuhdb_op.c:42 at wdbc_connect(): ERROR: Unable to connect to socket '/var/ossec/queue/db/wdb'.
2021/02/04 05:40:11 wazuh-modulesd[15283] wazuhdb_op.c:124 at wdbc_query_ex(): ERROR: Unable to connect to socket '/queue/db/wdb'.
2021/02/04 05:40:11 wazuh-modulesd:database[15283] wm_database.c:319 at wm_sync_agents(): DEBUG: Agent sync completed.
2021/02/04 05:40:11 wazuh-modulesd:database[15283] wm_database.c:322 at wm_sync_agents(): DEBUG: wm_sync_agents(): 6004.350 ms (4.166 clock ms).
2021/02/04 05:40:11 wazuh-modulesd[15283] wazuhdb_op.c:33 at wdbc_connect(): INFO: Cannot find '/var/ossec/queue/db/wdb'. Waiting 1 seconds to reconnect.
2021/02/04 05:40:12 wazuh-monitord: ERROR: Cannot send message: (32) 'Broken pipe'.
2021/02/04 05:40:12 wazuh-monitord: ERROR: Connection with wazuh-db lost. Reconnecting.
2021/02/04 05:40:12 wazuh-monitord: INFO: Cannot find '/queue/db/wdb'. Waiting 1 seconds to reconnect.
2021/02/04 05:40:12 wazuh-modulesd[15283] wazuhdb_op.c:33 at wdbc_connect(): INFO: Cannot find '/var/ossec/queue/db/wdb'. Waiting 2 seconds to reconnect.
```

**Comment by SpotHound** [comment]
Today we've been researching about this and other vulnerability-detector related problems on integration tests.


The conclusion extracted for this failure is that there is a problem while modifying the wazuh database to mock values for windows simulated agents:

![image](https://user-images.githubusercontent.com/15269938/106901643-504bce80-66f8-11eb-9f79-9502f7182bf4.png)

We currently restart modulesd, wait 5 seconds and then restart wazuh_db (after making the required changes to the database) and this could lead to failures due to modulesd not being operative when wazuh_db starts.

One solution would be to increase the pause between this restart and the start of wazuh_db.

Also, @danimegar told us that there seems to be another modulesd restart previous to that one, in the tests fixture, so maybe we could also remove it.

## First attempt

If we remove the modulesd restart at the beginning of the tests and increase the wait time to at least 15 seconds, only the first tests pass, but not the rests. We need to keep that restart and increase the sleep amount to at least 15 seconds.

We're still working in a better approach for this problem to avoid "tricky" sleeps on our tests and gain reliability.

**Comment by SpotHound** [comment]
## Second attempt

We've realized that it is not required to perform the problematic sleep if we replace the modulesd restart by a stop, then, wazuh_db is mocked and modulesd is started **after the mocking has finished**

![image](https://user-images.githubusercontent.com/15269938/106910937-fcde7e00-6701-11eb-9619-0f0e1fc30cf7.png)
![image](https://user-images.githubusercontent.com/15269938/106910967-05cf4f80-6702-11eb-8a70-9f03bc9e0915.png)

With these changes, we reduce the time required by the test 2.5 seconds and improve reliability.

**Comment by SpotHound** [comment]
Testing changes on Jenkins at https://ci.wazuh.info/job/test_integration/1152/console

**Comment by SpotHound** [comment]
With these changes the tests still failing, now due to missing tables on vulnerabilities database.

After a little investigation, we've concluded that we need to restart modulesd at least one time to allow vulnerability detector to create the missing tables.

Ad vulnerability detector would need a few seconds to do this, we will need to add a sleep after this restart. To avoid execution that sleeps too many times we will include it in a try/except block:

![image](https://user-images.githubusercontent.com/15269938/107045755-2e208200-67c6-11eb-9056-6a8ee22c5dcd.png)

This way, it should be executed just the first time that the vulnerabilities table is missed.

I've tested this fix here: https://ci.wazuh.info/job/test_integration_vulnerability_detector/308/console

And here: https://ci.wazuh.info/job/test_integration_vulnerability_detector/309/console

**Comment by SpotHound** [comment]
The last build failed due to another tests problem (MSU) but this fix seems to works!

I've launched another isolated test to make sure it works: https://ci.wazuh.info/job/test_integration_vulnerability_detector/310/console

The check that is failing (apart from the one described in this issue) is this one:

![image](https://user-images.githubusercontent.com/15269938/107055117-4053ed80-67d1-11eb-83e6-3d79e50b9189.png)

**Comment by SpotHound** [comment]
![image](https://user-images.githubusercontent.com/15269938/107056650-d89ea200-67d2-11eb-8e7c-d1948b99206c.png)
:+1:

**Comment by BraulioV** [comment]
Fixed in https://github.com/wazuh/wazuh-qa/pull/1047
