### ISSUE TITLE
Add new ambiguous confs integration test for FIM

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1033]
Hi team!

After doing some research in https://github.com/wazuh/wazuh/issues/7263 we have realized that there is not any integration test that checks the behavior with the following configuration estructure:

```xml
<directories ="realtime">/some/dir</directories>
<directories ="whodata">/some/dir/subdir</directories>
```

If an event is triggered in `/some/dir/subdir`, two events will be generated:
- One for `realtime` in the folder `/some/dir/` 
- Other one for `whodata` in the folder `/some/dir/subdir`

Kind regards

**Comment by damarisg** [comment]
We decided to close them.
