### ISSUE TITLE
Add option to save logs even when a test pass

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1035]
Hi team!

At this moment, the logs are saved only when the test fails. It will be nice to add an option to the integration tests in order to select the exit conditions to save the logs in the report zip.

The logs that we want to save are:
- `ossec.log`
- `ossec.conf`
- `test parameters` 

The logic that saves these logs is already done, but as I mentioned, these files are only saved in the reports only when a test fails. This is done because there are a lot of tests and saving the logs for every test will make huge reports, but we have been discussing this and we think that in some times, it will be necessary to be able to check the logs even when a test pass or due to an error.

Kind regards.

**Comment by damarisg** [comment]
We decided to close them.
