### ISSUE TITLE
3.10 tests: LogCollector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#104]
# Logcollector test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.10.0 | 31006 | 3.10 |

## Configuration

- [x] Add log.
- [x] Delete all localfile entries and start Logcollector.
- [x] Test Logcollector internal options.
- [x] Increase both `logcollector.max_files` and `logcollector.rlimit_nofile` and check if everything works with the maximum number of files allowed.
- [x] Check that the agent bookmarks Eventchannel logs.
- [x] Set `<only-future-events>` to `yes` and check that the agent is not bookmarking Eventchannel logs.

## Logs

- [x] Solve the reading of a file when changing its inode.
- [x] Check that Eventlog/Eventchannel logs are read in all supported versions of Windows.
- [x] Truncate file.
- [x] Check for new paths that match a wildcards after starting Logcollector.
- [x] Check **all the tests** changing the order of the parameters in combination with normal and daily wildcards.
- [x] Check that labels are added to JSON files.
- [x] Check that the multi-line logs are taken correctly.
- [x] Check that no duplicate files are scanned (entered multiple times).
- [x] Check that the agent sends the Windows Eventchannel events generated when it was stopped. (https://github.com/wazuh/wazuh/issues/3475)

## Performance

- [x] Monitor the memory wasted by Logcollector in the previous operations.

## Sockets

- [x] Configure one and multiple sockets output as target. (https://github.com/wazuh/wazuh/pull/395)
- [x] Test the `out_format` option for different socket targets. (https://github.com/wazuh/wazuh/pull/863)

## Commands

- [x] Prevent remote commands, with `command` or `full_command`, if `logcollector.remote_commands` is disabled.
- [x] Check that the output of a command is captured line by line (with `command`) and completely (with `full_command`)
- [x] Check the correct output of *netstat* commands.

**Comment by daescar** [comment]
Possibly memory leak detected in `logcollector.c` : 
```
Error #26: LEAK 20 direct bytes 0x02a89548-0x02a8955c + 0 indirect bytes
# 0 replace_malloc                     [d:\drmemory_package\common\alloc_replace.c:2577]
# 1 libwinpthread-1.dll!mutex_impl_init [/build/mingw-w64-_1w3Xm/mingw-w64-4.0.4/mingw-w64-libraries/winpthreads/src/mutex.c:70]
# 2 libwinpthread-1.dll!pthread_mutex_lock [/build/mingw-w64-_1w3Xm/mingw-w64-4.0.4/mingw-w64-libraries/winpthreads/src/mutex.c:99]
# 3 OSRegex_Execute_ex                 [os_regex/os_regex_execute.c:90]
# 4 OSRegex_Execute                    [os_regex/os_regex_execute.c:30]
# 5 OS_Regex                           [os_regex/os_regex.c:30]
# 6 check_pattern_expand               [logcollector/logcollector.c:1341]
# 7 LogCollectorStart                  [logcollector/logcollector.c:89]
# 8 local_start                        [win32/win_agent.c:362]
# 9 main                               [win32/win_agent.c:104]
```

However, this memory leak could be fixed with the next pull request: [PR-3533](https://github.com/wazuh/wazuh/pull/3533)

**Comment by daescar** [comment]
* The log labels are not adding to JSON files 
Windows config file: 
```
...
<localfile>
    <log_format>json</log_format>
    <location>C:\Users\Administrator\Desktop\folderA\*.json</location>
    <label key="@mylabel">Testing3.10</label>
  </localfile>
...
```
JSON achieved : 
```
{"timestamp":"2019-08-19T13:23:06.946+0000","rule":{"level":8,"description":"Log file size reduced.","id":"592","firedtimes":3,"mail":false,"groups":["ossec","attacks"],"pci_dss":["10.5.2","11.4"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.9","SC.7"]},"agent":{"id":"006","name":"WIN-CAM7O7RC0JN","ip":"10.0.2.15"},"manager":{"name":"wazuhManager"},"id":"1566220986.343715","cluster":{"name":"wazuh","node":"node01"},"full_log":"ossec: File size reduced (inode remained): 'C:\\Users\\Administrator\\Desktop\\folderA\\newLog.json'.","decoder":{"name":"ossec"},"location":"ossec-logcollector"}
```
Ubuntu config file:
```
<localfile>
    <log_format>json</log_format>
    <location>/var/log/myCustomLog.json</location>
    <label key="@mylabel">Test3.10</label>
    <label key="agent.type">LinuxAgent</label>
  </localfile>
```
JSON achieved:
```
{"timestamp":"2019-08-19T13:29:59.347+0000","rule":{"level":8,"description":"Log file size reduced.","id":"592","firedtimes":5,"mail":false,"groups":["ossec","attacks"],"pci_dss":["10.5.2","11.4"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.9","SC.7"]},"agent":{"id":"001","name":"wazuh-linuxAgentOne","ip":"10.0.2.15"},"manager":{"name":"wazuhManager"},"id":"1566221399.349080","cluster":{"name":"wazuh","node":"node01"},"full_log":"ossec: File size reduced (inode remained): '/var/log/myCustomLog.json'.","decoder":{"name":"ossec"},"location":"ossec-logcollector"}
```


* The `<only-future-events>` works that it is expected: setting to `no` the bookmarks are updated otherwise the bookmarks are not updated. 
* When the above option is set to `no` value, the agent sends the Windows Eventchannel logs which are generated when the agent was stopped

**Comment by daescar** [comment]
The `remote_commands` option it seems that it does not work.
To test this option the next steps have been followed:
1) Configure a `localfile` section in the shared config file from the manager's side.
2) Restart the manager and the agents (by auto_restart option enabled) will be restarted and updated with the configuration shared before.
4) Previously, in the agent side the next options have been set : 
     - `logcollector.remote_commands = 1`  ---> `/var/ossec/etc/internal_options.conf`
     - `agent.remote_conf = 1'  ---> `/var/ossec/etc/internal_options.conf`

However, the remote commands are not being launched.

**Comment by daescar** [comment]
The option `logcollector.max_lines' is being ignored since in Unix systems more lines than specified at the above option are being read. 
This option is also ignored in Windows XP because the maximum line number it can read from a logfile is 86.

**Comment by daescar** [comment]
Finally, testing with **Sockets**: 
We would like to highlight that the socket must be configured before the localfile sections which will use this socket. Otherwise, the socket will be ignored. We can see this in the next example:

`ossec.conf`:
```
  <localfile>
    <location>/home/vagrant/customLogs/*.log</location>
    <log_format>syslog</log_format>
  </localfile>

  <socket>
     <name>demo</name>
     <location>/var/run/demo.sock</location>
     <mode>tcp</mode>
     <prefix>\<13\></prefix>
  </socket>

  <localfile>
    <location>/home/vagrant/mylog.log</location>
    <log_format>syslog</log_format>
    <target>agent,demo</target>
  </localfile>
```
Any .log file inside  `/home/vagrant/customLogs/` will not output by the socket. 
However, we will get the output by the demo socket when any change is made in `/home/vagrant/mylog.log` file.

On the other hand, if two different stanzas for the same log file with the option `out_format` for two different sockets only works for the last one. 

```
<localfile>
    <location>/home/vagrant/mylog.log</location>
    <log_format>syslog</log_format>
    <target>agent,demo</target>
    <out_format target="demo">demo: $(log)</out_format>
  </localfile>

  <localfile>
    <location>/home/vagrant/mylog.log</location>
    <log_format>syslog</log_format>
    <target>agent,demo</target>
    <out_format target="agent">agent: $(log)</out_format>
  </localfile>
```

Socket output:
```
<13>Hi! I'm testing!
```
archives output:
2019 Aug 21 10:40:27 (wazuh-linuxAgentOne) 192.168.70.11->/home/vagrant/mylog.log agent: Hi! I'm testing!

**Comment by chemamartinez** [comment]
> The option `logcollector.max_lines` is being ignored since in Unix systems more lines than specified at the above option are being read.
> This option is also ignored in Windows XP because the maximum line number it can read from a logfile is 88.
> Other Windows versions also ignore this internal option but do not truncate to 88 lines.

Hi @daescar, this option refers to the maximum lines of a file read in a single iteration. If that limit is reached, the LogCollector let the file in a stand-by mode and goes to read another file. But, in the next iteration will continue reading the file. https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#logcollector

Have you taken this into account to check its behavior?

Regards.

**Comment by Skeptor** [comment]
> The `remote_commands` option it seems that it does not work.
> To test this option the next steps have been followed:
> 
> 1. Configure a `localfile` section in the shared config file from the manager's side.
> 2. Restart the manager and the agents (by auto_restart option enabled) will be restarted and updated with the configuration shared before.
> 3. Previously, in the agent side the next options have been set :
>    
>    * `logcollector.remote_commands = 1`  ---> `/var/ossec/etc/internal_options.conf`
>    * `agent.remote_conf = 1'  ---> `/var/ossec/etc/internal_options.conf`
> 
> However, the remote commands are not being launched.

Hi @daescar, I tried to run remote commands in my environment and it works fine.
This is my localfile block in the `agent.conf`
```
<agent_config>
<localfile>
    <log_format>command</log_format>
    <command>ps -A</command>
    <alias>List of opened processes</alias>
    <frequency>15</frequency>
  </localfile>
</agent_config>
```

Here is the output from the agent `ossec.log`
`2019/08/28 07:47:04 ossec-logcollector: INFO: Monitoring output of command(15): ps -A`

Here is the output from the `archives.log`
```
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 15419 ?        00:00:00 ossec-logcollec
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 15429 ?        00:00:00 wazuh-modulesd
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 15462 ?        00:00:00 kworker/0:1
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 16445 ?        00:00:00 kworker/u2:0
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 16877 ?        00:00:00 kworker/0:2
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 17155 ?        00:00:00 kworker/0:0
2019 Aug 28 09:57:42 (c7-agent-151) any->List of opened processes ossec: output: 'List of opened processes': 17180 ?        00:00:00 ps
```

Have you checked the `archives.log`?

Regards.

**Comment by daescar** [comment]
Hi @Skeptor, 
Thank you for your reply. I have tested this option again and it works fine.
The next configuration have been tested : 

```
<agent_config>
    <localfile>
          <log_format>command</log_format>
          <command>ps -A</command>
          <alias>List of opened processes</alias>
          <frequency>20</frequency>
  </localfile>

   <localfile>
         <log_format>command</log_format>
         <command>df -P</command>
         <alias>my remote command</alias>
         <frequency>10</frequency>
  </localfile>
</agent_config>
```
The output from the `archives.log`:
```
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  1310 ttyS0    00:00:00 agetty
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  1807 ?        00:00:03 VBoxService
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  2969 ?        00:00:00 systemd
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  2971 ?        00:00:00 (sd-pam)
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  3057 ?        00:00:01 kworker/u2:0
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes':  9218 ?        00:00:00 kworker/u2:1
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 20117 ?        00:00:00 kworker/0:2
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 20477 ?        00:00:00 sshd
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 20512 ?        00:00:00 sshd
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 20513 pts/1    00:00:00 bash
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 22352 pts/1    00:00:00 su
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 22353 pts/1    00:00:00 bash
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 23689 ?        00:00:00 kworker/0:3
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 24448 ?        00:00:00 ossec-execd
2019 Aug 28 09:35:37 (wazuh-linuxAgentOne) 192.168.70.11->List of opened processes ossec: output: 'List of opened processes': 24455 ?        00:00:01 ossec-agentd
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': Filesystem     1024-blocks      Used Available Capacity Mounted on
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': udev                498672         0    498672       0% /dev
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': tmpfs               101592      3148     98444       4% /run
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': /dev/sda1         10098468   4696496   5385588      47% /
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': tmpfs               507944         0    507944       0% /dev/shm
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': tmpfs                 5120         0      5120       0% /run/lock
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': tmpfs               507944         0    507944       0% /sys/fs/cgroup
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': vagrant          183104652 140757784  42346868      77% /vagrant
2019 Aug 28 09:35:46 (wazuh-linuxAgentOne) 192.168.70.11->my remote command ossec: output: 'my remote command': tmpfs               101592         0    101592       0% /run/user/1000
```

**Comment by daescar** [comment]
> Hi @daescar, this option refers to the maximum lines of a file read in a single iteration. If that limit is reached, the LogCollector let the file in a stand-by mode and goes to read another file. But, in the next iteration will continue reading the file. https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#logcollector
> 
> Have you taken this into account to check its behavior?
> 
> Regards.

Hi @chemamartinez, 
As you well said, the file will continue being read in the next iteration. In the previous test, I was testing a single log file, so I didn't see the effect produced by the `max_lines` option. 
Therefore, when I tested two logfiles by exceeding the `max_lines` established (more than 100).
The logcollector behavior was as expected:
* Read first 100 lines from log1.log
* Read first 100 lines from log2.log
* Read the remaining lines from log1.log
* Read the remaining lines from log2.log

However, in the following iterations the first line is not being read, as we can see below.
The `archives.log` output: 
```
...
# file log1: line99
# file log1: line100
# file log2: line1
...
# file log2: line99
# file log2: line100
# file log1: line102
# file log1: line103
...
# file log2: line102
# file log2: line103
``` 
It is was tested in: Ubuntu16.04, Centos7, WindowsXP, WindowsVista and WindowsServer2012.

Looking for the reason of this behaviour I think the bug could be in this [line](https://github.com/wazuh/wazuh/blob/725b55191e769dbf45981895bec3f5b9d23024a7/src/logcollector/read_syslog.c#L38)

In this issue, # ,you can found more information about this.
