### ISSUE TITLE
Add a new check in vuln detector scan tests for checking the number of alerts generated

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1041]
Currently, for the vulnerability detector integration tests, we are only checking the `ossec.log` output with `DEBUG=2`.

Sometimes we are also interested in checking other files such as `alerts.json` to verify that the corresponding alerts are being reported.

I propose in this issue to add a new check in scan tests for checking the number of alerts generated in `alerts.json` and check if this number is the expected one.

To do this, we can set a custom wazuh environment that only has vulnerability detector rules or disabling everything that is not necessary in `ossec.conf`.

We can get the number of alerts in `alerts.json` with the following command:

```
wc -l /var/ossec/logs/alerts/alerts.log | cut -d " " -f 1
```

Regards.

**Comment by BraulioV** [comment]
Deprecated with the changes implemented in #1261
