### ISSUE TITLE
3.10 tests: Syscollector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#105]
# Syscollector test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.10.0 | 31006 | 3.10 |

## Scan

Run a complete Syscollector scan:
- Operating system.
- Hardware.
- Packages.
- Network interfaces.
- Ports.
- Processes.

Test on:
- [x] Debian.
- [x] RPM.
- [x] Centos 5.
- [x] macOS.
- [x] Windows.
- [x] Windows XP/2003.

## Configuration

- [x] Check interval option runs as expected more than the very first time.
- [x] Send a Syscollector configuration by the shared conf (*agent.conf*).

## Database

- [x] Upgrade from a version older than v3.8.0. The databases at *queue/db/* must be updated.
- [x] Check that Syscollector info has been stored in the DB of the agent (*queue/db/xxx.db*).
- [x] Check that a new scan deletes the previous scan from the DB. [Search by `scan_id`]
- [x] Delete the DB of an agent (file *001.db* for example) and send a new scan. Is the scan received? Is the DB restored when the manager is restarted?

**Comment by carlocas** [comment]
**Failed - Tier 2: Upgrade from sources v3.7**

At upgrading the agent from version 3.7 to 3.10., the `ossec.log` show an error with the socket `queue/ossec/control`, this socket doesn't exits:
```
2019/08/16 11:16:24 ossec-agentd: ERROR: Unable to bind to socket '/queue/ossec/control': (2) No such file or directory.
```
If we view thew content of the folder, we can see that the socket control is not there. 
```
ls -la /var/ossec/queue/ossec/
total 4
drwxrwx---. 2 ossec ossec 117 ago 16 11:00 .
drwxr-x---. 7 root  ossec  71 ago 16 10:58 ..
-rw-r--r--. 1 ossec ossec  41 ago 16 11:00 .agent_info
srw-rw----. 1 root  ossec   0 ago 16 11:00 com
srw-rw----. 1 root  ossec   0 ago 16 11:00 download
srw-rw----. 1 root  ossec   0 ago 16 11:00 logcollector
srw-rw----. 1 ossec ossec   0 ago 16 11:00 queue
srw-rw----. 1 root  ossec   0 ago 16 11:00 syscheck
srw-rw----. 1 root  ossec   0 ago 16 11:00 wmodules
```
Also, the socket download exits in this folder, when if you install 3.10 directly, doesn't appear:

```
 ls -la /var/ossec/queue/ossec/
total 16
drwxrwx--- 2 ossec ossec 4096 Aug 16 10:57 .
drwxr-x--- 6 root  ossec 4096 Aug 16 09:03 ..
-rw-r--r-- 1 ossec ossec   43 Aug 16 10:28 .agent_info
srw-rw---- 1 root  ossec    0 Aug 16 10:28 com
srw-rw---- 1 root  ossec    0 Aug 16 10:28 control
srw-rw---- 1 root  ossec    0 Aug 16 10:28 logcollector
srw-rw---- 1 ossec ossec    0 Aug 16 10:28 queue
srw-rw---- 1 root  ossec    0 Aug 16 10:28 syscheck
-rw-r--r-- 1 ossec ossec    1 Aug 16 10:57 .wait
srw-rw---- 1 root  ossec    0 Aug 16 10:28 wmodules
```

**Comment by Skeptor** [comment]
> **Failed - Tier 1: Upgrade from sources v3.7**
> 
> At upgrading the agent from version 3.7 to 3.10., the `ossec.log` show an error with the socket `queue/ossec/control`, this socket doesn't exits:
> 
> ```
> 2019/08/16 11:16:24 ossec-agentd: ERROR: Unable to bind to socket '/queue/ossec/control': (2) No such file or directory.
> ```
> 
> If we view thew content of the folder, we can see that the socket control is not there.
> 
> ```
> ls -la /var/ossec/queue/ossec/
> total 4
> drwxrwx---. 2 ossec ossec 117 ago 16 11:00 .
> drwxr-x---. 7 root  ossec  71 ago 16 10:58 ..
> -rw-r--r--. 1 ossec ossec  41 ago 16 11:00 .agent_info
> srw-rw----. 1 root  ossec   0 ago 16 11:00 com
> srw-rw----. 1 root  ossec   0 ago 16 11:00 download
> srw-rw----. 1 root  ossec   0 ago 16 11:00 logcollector
> srw-rw----. 1 ossec ossec   0 ago 16 11:00 queue
> srw-rw----. 1 root  ossec   0 ago 16 11:00 syscheck
> srw-rw----. 1 root  ossec   0 ago 16 11:00 wmodules
> ```
> 
> Also, the socket download exits in this folder, when if you install 3.10 directly, doesn't appear:
> 
> ```
>  ls -la /var/ossec/queue/ossec/
> total 16
> drwxrwx--- 2 ossec ossec 4096 Aug 16 10:57 .
> drwxr-x--- 6 root  ossec 4096 Aug 16 09:03 ..
> -rw-r--r-- 1 ossec ossec   43 Aug 16 10:28 .agent_info
> srw-rw---- 1 root  ossec    0 Aug 16 10:28 com
> srw-rw---- 1 root  ossec    0 Aug 16 10:28 control
> srw-rw---- 1 root  ossec    0 Aug 16 10:28 logcollector
> srw-rw---- 1 ossec ossec    0 Aug 16 10:28 queue
> srw-rw---- 1 root  ossec    0 Aug 16 10:28 syscheck
> -rw-r--r-- 1 ossec ossec    1 Aug 16 10:57 .wait
> srw-rw---- 1 root  ossec    0 Aug 16 10:28 wmodules
> ```

Hi @carlocas, the module `download` is only available for the Wazuh manager: https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/wm_download.c#L193

I did upgrade the agent from 3.7 to 3.10 and I didn't have any trouble:

**3.7.3**
```
root@ubuntu-agent-152:/home/vagrant/wazuh/src# ls -la /var/ossec/queue/ossec/
total 16
drwxrwx--- 2 ossec ossec 4096 Aug 28 06:28 .
drwxr-x--- 7 root  ossec 4096 Aug 28 06:27 ..
-rw-r--r-- 1 ossec ossec   53 Aug 28 06:28 .agent_info
-rw-r--r-- 1 ossec ossec    1 Aug 28 06:28 .wait
srw-rw---- 1 root  ossec    0 Aug 28 06:28 com
srw-rw---- 1 root  ossec    0 Aug 28 06:28 logcollector
srw-rw---- 1 ossec ossec    0 Aug 28 06:28 queue
srw-rw---- 1 root  ossec    0 Aug 28 06:28 syscheck
srw-rw---- 1 root  ossec    0 Aug 28 06:28 wmodules
```

**3.10**
```
root@ubuntu-agent-152:/home/vagrant/wazuh/src# ls -la /var/ossec/queue/ossec/
total 12
drwxrwx--- 2 ossec ossec 4096 Aug 28 06:37 .
drwxr-x--- 7 root  ossec 4096 Aug 28 06:27 ..
-rw-r--r-- 1 ossec ossec   53 Aug 28 06:37 .agent_info
srw-rw---- 1 root  ossec    0 Aug 28 06:37 com
srw-rw---- 1 root  ossec    0 Aug 28 06:37 control
srw-rw---- 1 root  ossec    0 Aug 28 06:37 logcollector
srw-rw---- 1 ossec ossec    0 Aug 28 06:37 queue
srw-rw---- 1 root  ossec    0 Aug 28 06:37 syscheck
srw-rw---- 1 root  ossec    0 Aug 28 06:37 wmodules
```

Was it a clean installation? Maybe an older installation wasn't completely removed.

Regards

**Comment by carlocas** [comment]
I just tried to upgrade from wazuh 3.7 to 3.10 and everything works as expected. So, I suppose that the error with the socket `control` it was because I  didn't have a clean installation at the time to upgrade wazuh.

Thanks, @Skeptor for the reply.
