### ISSUE TITLE
Wazuh App v4.1.0-7.10.0-4101-2 RC package testing

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1055]
We need to test all the checks defined in https://github.com/wazuh/wazuh-kibana-app/issues/2803 in the following OS and browsers:

|OS/Browser   | ToDo  | In progress  | OK  | KO  | Total  | Coverage  |
|---|---|---|---|---|---|---|
| Firefox Linux  | 13 | 7  | 149  | 0 | 171 | 88.30% |
| Chrome Linux  | 17 | 6 | 146  | 0 | 171 | 86.55% |
| Firefox Windows  | 17 | 3 | 149 | 0 | 171 | 88.3% |
| Chrome Windows  | 17 | 3 | 149 | 0 | 171 | 88.3% |
| Safari macOS  | 92 | 29 | 46 | 0 | 171 | 29.23% |
| Edge Windows  | 27 | 1 | 141 | 0 | 171 | 83.62% |

In this [page](https://docs.google.com/spreadsheets/d/1HJPeuEPjaPNXIppu2t9P16htiZSi_6RPQEO5qAu2rdc/edit#gid=233428767) you can see the current status of the testing process.

**Comment by s-ocando** [comment]
## Report 2/12/2021
- [Non-stop error messages when trying to manage agents on an unauthorized group](https://github.com/wazuh/wazuh-kibana-app/issues/2963)

**Comment by MiguelCasaresRobles** [comment]
Report ops 2/12/2021

- [Wazuh plugin not able to recognize a manually created index pattern](https://github.com/wazuh/wazuh-kibana-app/issues/2958)
- [FIM and SCA inventory content showing UTC timestamp](https://github.com/wazuh/wazuh-kibana-app/issues/2960)
- [SCA refresh button located in SCA dashboard is not refreshing the last scan date](https://github.com/wazuh/wazuh-kibana-app/issues/2962)
