### ISSUE TITLE
Remoted tier 0: manager -> agent communication

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1062]
These tests will check if remoted can properly send messages to the agent and collect the agent's response. 

To do so, we will use the socket used by the API to request information about the agent. To give more info about this, when the user runs an API request that needs to communicate or collect info from the agent, the API writes its request in this socket `$DIR/queue/ossec/request` and then, remoted forwards this query to the agent using the `secure` socket bound to the port 1514. 

Finally, the agent sends its response to remoted and it forwards it to the API. Here you can see the messages flow:
![image.png](https://images.zenhubusercontent.com/5d91c1bf3ab6b200010aecd1/d3ab1079-6d5a-48b9-8dd9-a9259e0961d4)

With this, the test must perform these checks:
- [x] Write a request in `$DIR/queue/ossec/request` and check if remoted forwards it to the agent, collects the response, and writes it in the socket.
- [x] Write a request in `$DIR/queue/ossec/request` to collect statistics from the agent, check if remoted forwards it to the agent, collects the response, and writes it in the socket.
- [x] Write a request in `$DIR/queue/ossec/request` for a disconnected agent. remoted must respond with a message showing that the agent is not connected.

**Comment by SpotHound** [comment]
Hello team, 

I'm working on this at `1062-agent-communication`.

I'm stating with the disconnected agent test as it should be easier to implement.

**Comment by SpotHound** [comment]
Ping example

```
msg = '#ping'
msg_size = len(bytearray(msg, 'utf-8'))
ping_msg = msg_size.to_bytes(4, 'little') + msg.encode()
s.send(ping_msg)
response = s.recv(len(ping_msg))
```

**Comment by SpotHound** [comment]
### pip freeze 
```
asn1crypto==0.24.0
attrs==20.3.0
backcall==0.2.0
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
configobj==5.0.6
cryptography==3.4.6
dbus-python==1.2.4
decorator==4.2.1
filetype==1.0.7
gpg==1.10.0
idna==2.5
importlib-metadata==3.4.0
iniconfig==1.1.1
ipython==7.16.1
ipython-genutils==0.2.0
isc==2.0
jedi==0.18.0
lockfile==0.12.2
netifaces==0.10.6
packaging==20.9
parso==0.8.1
pciutils==2.3.6
perf==0.1
pexpect==4.8.0
pickleshare==0.7.5
pluggy==1.0.0.dev0
ply==3.9
prompt-toolkit==3.0.16
ptyprocess==0.7.0
py==1.10.0
pycairo==1.16.3
pycparser==2.14
pycryptodome==3.9.8
Pygments==2.8.0
pygobject==3.28.3
pyOpenSSL==19.1.0
pyparsing==2.1.10
pytest==6.2.2
python-dateutil==2.6.1
python-dmidecode==3.12.2
python-linux-procfs==0.6
pyudev==0.21.0
PyYAML==3.12
requests==2.23.0
rhnlib==2.8.6
rpm==4.14.2
schedutils==0.6
selinux==2.9
sepolicy==1.1
setools==4.2.2
setroubleshoot==1.1
six==1.11.0
slip==0.6.4
slip.dbus==0.6.4
sos==3.7
SSSDConfig==2.2.0
syspurpose==1.25.17
systemd-python==234
testinfra==5.0.0
toml==0.10.2
traitlets==4.3.3
typing-extensions==3.7.4.3
urllib3==1.25.11
wazuh-testing==4.2.0
wcwidth==0.2.5
zipp==3.4.0
```

**Comment by SpotHound** [comment]
## Add a simulated agent
```
import wazuh_testing.tools.agent_simulator as ag
manager_address = "localhost"
agent = ag.Agent(manager_address, "aes", os="debian8", version="4.2.0")
sender = ag.Sender(manager_address, protocol="tcp")
injector = ag.Injector(sender, agent)
injector.run()
```

**Comment by SpotHound** [comment]
We've not been able to intercept the secure messages between agent and manager to check the format of the agent answer to remoted after the last-mentioned message. Nevertheless, with help of the core team, we've got a valid answer:

```
#!-req 12345 ok {"internal":{"agent":{"debug":0,"warn_level":90,"normal_level":70,"tolerance":15,"recv_timeout":60,"state_interval":5,"min_eps":50,"remote_conf":1},"monitord":{"rotate_log":1,"compress":1,"keep_log_days":31,"day_wait":10,"size_rotate":512,"daily_rotations":12},"remoted":{"request_pool":1024,"request_rto_sec":1,"request_rto_msec":0,"max_attempts":4,"comp_average_printout":19999,"recv_counter_flush":128,"verify_msg_id":0}}}
```

# Example of the whole flow

## Api call
We make the following API call
```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -X GET "https://localhost:55000/agents/001/config/agent/client" -H "Authorization: Bearer $TOKEN"
```

## Remoted request

API writes to `/var/ossec/queue/ossec/requests` and remoted reads:

```
b'\x1a\x00\x00\x00001 agent getconfig client'
```

## Agent config request

Remoted send to agent the same message, only header and format changes to:

```
ececac937b8e5dead15e9096e8bd5215214970000000002:3090:#!-req c2b2c9e3 agent getconfig client
```

## Agent response

Agent answer to remoted with:

```
#!-req 12345 ok {"internal":{"agent":{"debug":0,"warn_level":90,"normal_level":70,"tolerance":15,"recv_timeout":60,"state_interval":5,"min_eps":50,"remote_conf":1},"monitord":{"rotate_log":1,"compress":1,"keep_log_days":31,"day_wait":10,"size_rotate":512,"daily_rotations":12},"remoted":{"request_pool":1024,"request_rto_sec":1,"request_rto_msec":0,"max_attempts":4,"comp_average_printout":19999,"recv_counter_flush":128,"verify_msg_id":0}}}
```

## API result

And finally, remoted send the relevant information to the API:

```
Out[25]: b'\xbb\x01\x00\x00ok {"client":{"config-profile":"centos, centos8, centos8.3","notify_time":10,"time-reconnect":60'
```

**Comment by SpotHound** [comment]
## Bug in agent_simulator

![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/615d5351-cf95-4e30-94b5-4c9282c6aa4e)
![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/566e5536-f15b-4b31-848e-0867409b685d)
![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/1683094c-7530-46a4-a327-1a1e9e0a30d4)
Sometimes a message can be received ending with one of the words expected for agent command. If that happens, the message will me processed as a command and could lead to an error.

**Comment by SpotHound** [comment]
The first check is already working although we've experimented with some problems with the agent simulator which have derivated in long testing time for this check. We will improve that in the next iteration.

![image](https://user-images.githubusercontent.com/15269938/109180388-1c117e00-778b-11eb-9768-1820f4a46b1c.png)

**Comment by SpotHound** [comment]
Regarding the second check:
*  Write a request in $DIR/queue/ossec/request to collect statistics from the agent, check if remoted forwards it to the agent, collects the response, and writes it in the socket.

```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -X GET "https://localhost:55000/agents/001/getstate/agentd" -H "Authorization: Bearer $TOKEN"
```

**Comment by SpotHound** [comment]
All the tests are working now
![image](https://user-images.githubusercontent.com/15269938/109292693-0d7aa380-782b-11eb-8ee4-9a007ca3608c.png)


Just two problems to solve in the future:
- The test need the Wazuh manager to consider mocked agent as active but, we cannot mock them into the global db without stopping wazuh_db and modulesd, so we need to wait for the manager to add them after the registration (this can take up to 1 min) this makes the test very slow and could be improved
- Sometimes remoted answer with an empty message in the "disconnect agent" tests when the query is made too early. We've solved this problem by adding some retries to the query if the answer is empty.
