### ISSUE TITLE
Rename users and group according to the Wazuh standard

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#1093]
Hi team!

After doing some research in wazuh/wazuh#7646, we have observed that it is necessary to make several changes according to the default users and groups:

- [x] Modify users `ossec`, `ossecr` and `ossecm`, by a single `wazuh` user.

- [x] Change the `ossec` group, by the `wazuh` group.

Some references I have found are the following:

- By using the **_getpwnam_** and **_getgrnam_** functions -> `pwd.getpwnam ("ossec"). Pw_uid`

- Calls to **_owner_** and **_group_** -> `set_file_owner_and_group (socket_path, 'ossec', 'ossec')`

- Some references in **_chown_** calls -> `chown ossec: ossec`

- References to **_ossecm_** in email settings -> `<email_from> ossecm@example.wazuh.com </email_from>`

- Check more existing references.

For more information, check out epic issue: wazuh/wazuh#7646.

Kind regards.

**Comment by alromeros** [comment]
Devel branch: https://github.com/wazuh/wazuh-qa/tree/1093-rename-users-and-groups
