### ISSUE TITLE
Update Python dependencies for integration tests

### ISSUE THREAD

**Issue by pacoqack** [wazuh/wazuh-qa#1095]
Gcloud integration tests are failing on Jenkins due to missing dependencies, we need to check it out and fix it.

Example of a failed build. https://ci.wazuh.info/job/test_integration/

![image](https://user-images.githubusercontent.com/15269938/109623241-3b1e6000-7b3d-11eb-9358-a0e0e2b19f49.png)

**Comment by BraulioV** [comment]
This is related to #1072
