### ISSUE TITLE
Performance tests for the leaky bucket of the Wazuh Agent

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1108]
To avoid network congestion and flooding the manager with events, the agent has a "leaky bucket" to control the number of events (EPS) sent to a manager. Recently, it was discovered this bug https://github.com/wazuh/wazuh/issues/7304 where the Windows agent didn't honor its configuration for the leaky bucket.

To avoid issues like this, we must create a test:
- [ ] Collects the EPS sent by the agent.
- [ ] Generate a data visualization showing the evolution of those EPS along time. 
- [ ] Check if the EPS sent by the agent to the manager are equal to the value set in the configuration within a margin of +/- 100 EPS (we will estimate this margin better once the test is fully implemented.
- [ ] This test must run in different OS:
    - [ ] Linux.
    - [ ] Windows.
    - [ ] macOS.
- [ ] Must be automated in Jenkins.
- [ ] The test must detect changes in the state of the queue. If the queue is at 100% for 15 seconds, it will show a warning and an alert. Then, the queue usage will go down and it must show a message notifying about it.

## Resources
- https://documentation.wazuh.com/current/learning-wazuh/survive-flood.html
- https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client_buffer.html

## CHANGELOG
- [Tue Mar  9 01:53:14] [Add some minor required changes to remoted simulator](https://github.com/wazuh/wazuh-qa/commit/541d0c22bf53899c610b5046f9c0c9e77718c4ae)

**Comment by Pac0x73706f74686f756e64** [comment]
We will watch the content of `/var/ossec/var/run/wazuh-agentd.state` file which has information about the number of event in the buffer. For example:

```
[root@centos-8a vagrant]# cat /var/ossec/var/run/wazuh-agentd.state 
# State file for wazuh-agentd

# Agent status:
# - pending:      waiting to get connected.
# - connected:    connection established with manager in the last 10 seconds.
# - disconnected: connection lost or no ACK received in the last 60 seconds.
status='connected'

# Last time a keepalive was sent
last_keepalive='2021-03-08 15:48:44'

# Last time a control message was received
last_ack='2021-03-08 15:48:44'

# Number of generated events
msg_count='4939'

# Number of messages (events + control messages) sent to the manager
msg_sent='4252'

# Number of events currently buffered
# Empty if anti-flooding mechanism is disabled
msg_buffer='740'
```

**Comment by Pac0x73706f74686f756e64** [comment]
# Simulating a manager using authd and remoted simulators

We need to send our agent's messages to someplace, preferably one where we could handle the received messages and count them for making statistics.  To do this, we will use the remoted simulator. 

Nevertheless, the remoted simulator required a `client.keys` file to work. To create it we will use the authd simulator and we will register the agent.

Here an example:

### Set up authd simulator
```
from wazuh_testing.tools import WAZUH_PATH
import os
SERVER_ADDRESS="127.0.0.1"
CLIENT_KEYS_PATH = os.path.join(WAZUH_PATH, 'etc', 'client.keys')
SERVER_KEY_PATH = os.path.join(WAZUH_PATH, 'etc', 'manager.key')
SERVER_CERT_PATH = os.path.join(WAZUH_PATH, 'etc', 'manager.cert')
from wazuh_testing.tools.authd_sim import AuthdSimulator
authd_simulator = AuthdSimulator(server_address=SERVER_ADDRESS,
                                     enrollment_port=1515,
                                     key_path=SERVER_KEY_PATH,
                                     cert_path=SERVER_CERT_PATH)
authd_simulator.start()
```

After that we could simply register the agent:

**Comment by Pac0x73706f74686f756e64** [comment]
# Flodding messages sent to the manager

On the manager side, an alert for the agent queue being flooded should appear when this event occurs. 

As our manager would be simulated, we need a way to confirm that the manager could, in fact, generate that alert.

To do this we will check if the following messages are received by the simulated remoted:

```
CRITICAL:root:Remoted simulator received: d65c6ab851876494b2a0e843b3645937321700000000000:4209:1:wazuh-agent:wazuh: Agent buffer: '90%'.
CRITICAL:root:Remoted simulator received: a43a0bc89664468e175c31af7a668d65134520000000000:4210:1:wazuh-agent:wazuh: Agent buffer: 'full'.
CRITICAL:root:Remoted simulator received: ad2d38265f5ede9c0ec68d2d751d59ec263210000000000:4373:1:wazuh-agent:wazuh: Agent buffer: 'normal'.
```
