### ISSUE TITLE
Integration tests for Vulnerability Detector: Arch Linux support

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1119]
### Description

This issue is part of https://github.com/wazuh/wazuh/issues/7075.

Since a new OS will be supported in Vulnerability Detector, tests have to cover this new platform. The following tests have to be extended:

- **Feed tests**: These tests have to cover the addition of the new feed for Arch Linux
- **Provider tests**: Here we will test the settings for the new provider
- **Scan results tests**: Here we have to add the tests that ensure Arch Linux agents are scanned properly

**Comment by pacoqack** [comment]
Hello team,

I'm working on this. Development branch: `1119-vd-arch`

**Comment by pacoqack** [comment]
# Feed tests

There are 2 kinds of feed tests. The generic ones (common for every provider) and the specific ones.

We're starting with the generic ones.

## Generic tests

### Test download feeds

We need to check that Wazuh is able to download the arch linux feeds.

**Comment by spothound** [comment]
We've built rpm manage packages with development branch `7767-archlinux-support-vd` to start working on this.

**Comment by spothound** [comment]
Today we've finished the development of the new tests. As these changes will be merged into 4.2 instead of master (the base branch of our `1119-vd-arch` development branch), I've created a new branch with base at 4.2: `1119-vulnerability-archlinux`.

Tomorrow, I will review everything, test and open a Pull Request.

**Comment by spothound** [comment]
We're waiting for the core team to finish the required changes in order to ultimate testing and merge the new code.

**Comment by spothound** [comment]
![Uploading image.png…]()

**Comment by spothound** [comment]
![image](https://user-images.githubusercontent.com/15269938/114897094-370a8100-9e11-11eb-98b3-8c738e353e91.png)

**Comment by spothound** [comment]
We've been talking about the failures in tests with core team. We've required to change some tests to adapt them to the vulnerability detector requirements for Ach Linux.

# Testing 
## tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
![image](https://user-images.githubusercontent.com/15269938/115353289-a3da9e00-a1b8-11eb-8e02-271733af5812.png)
