### ISSUE TITLE
Performance test: Infrastructure definition

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1135]
This issue aims to define an infrastructure for the testing, which instances types depending on the input of the test. To complete this issue, it is necessary to get info about how the agent simulator scales in a single host and info about the AWS instances.

**Comment by jmv74211** [comment]
After studying and comparing the different performances and costs associated with the use of different AWS machines, the following has been decided **in terms of the resources used in agent simulation and event generation per second**:

- For tests that exceed a duration of **<= 45 minutes**, it has been decided to use `t2.medium` instances. This has been decided because it has been found that the optimal CPU performance is in the [0-45]min range, since beyond that point the machine runs out of CPU credits and its performance drops considerably. Priority was also given to this type of instance, since it is the one with the best performance/price ratio among the types of instances investigated.

    Specifically, the data obtained for this type of instance are the following:

    - Max eps/simulated_agent: 4000
    - Max number of agents = 100/agent_host.
    - The maximum number of eps with the largest number of agents is 100 agents each reporting to 40 eps.

    From these data, the following estimations have been made depending on whether we want to maximize the number of simulated agents, or the maximum number of evps that can be sent per instance.

    **Maximization of the number of events per second**

    | Max eps    | N agents    | N instances | Price/h  |
    |------------|-------------|-------------|----------|
    |  1         | 1           | 1           | 0.0464$  |
    |  1000      | 1           | 1           | 0.0464$  |
    |  5000      | 5           | 2           | 0.0928$  |
    |  10000     | 10          | 3           | 0.1392$  |
    |  25000     | 25          | 7           | 0.3248$  |
    |  50000     | 50          | 13          | 0.6032$  |
    |  100000    | 100         | 25          | 1.16$    |
    |  250000    | 250         | 63          | 2.9232$  |
    |  500000    | 500         | 125         | 5.8$     |
    |  1000000   | 1000        | 250         | 11.6$    |

    **Maximization of the number of connected and reporting agents**

    | N agents   | Max eps    | N instances |Price/h  |
    |------------|------------|-------------|---------|
    |    1       |  4000      |   1         | 0.0464$ |
    |    100     |  4000      |   1         | 0.0464$ |
    |    500     |  20000     |   5         | 0.232$  |
    |    1000    |  40000     |   10        | 0.464$  |
    |    5000    |  200000    |   50        | 2.32$   |
    |    10000   |  400000    |   100       | 4.64$   |
    |    25000   |  1000000   |   250       | 11.6$   |
    |    50000   |  2000000   |   500       | 23.2$   |
    |    100000  |  4000000   |   1000      | 46.4$   |

- For tests that exceed a duration of **> 45 minutes**, it has been decided to use `c5.xlarge` instances since **it has presented the best performance/cost for long durations**.

    Specifically, the data obtained for this type of instance are the following:

    - Max eps/simulated_agent: 7000
    - Max number of agents = 200/agent_host (20 margin has been left for possible improvements in agent simulator that may increase memory usage).
    - The maximum number of eps with the largest number of agents is 200 agents each reporting to 15 eps.

    From these data, the following estimations have been made depending on whether we want to maximize the number of simulated agents, or the maximum number of evps that can be sent per instance.

    **Maximization of the number of events per second**

    | Max eps    | N agents    | N instances | Price/h  |
    |------------|-------------|-------------|----------|
    |  1         | 1           | 1           | 0.17$    |
    |  1000      | 1           | 1           | 0.17$    |
    |  5000      | 5           | 1           | 0.17$    |
    |  10000     | 10          | 2           | 0.34$    |
    |  25000     | 25          | 4           | 0.68$    |
    |  50000     | 50          | 8           | 1.36$    |
    |  100000    | 100         | 15          | 2.55$    |
    |  250000    | 250         | 36          | 6.12$    |
    |  500000    | 500         | 72          | 12.24$   |
    |  1000000   | 1000        | 143         | 24.31$   |

    **Maximization of the number of connected and reporting agents**

    | N agents   | Max eps    | N instances |Price/h  |
    |------------|------------|-------------|---------|
    |    1       |  7000      |   1         | 0.17$   |
    |    200     |  3000      |   1         | 0.17$   |
    |    500     |  7500      |   3         | 0.51$   |
    |    1000    |  15000     |   5         | 0.85$   |
    |    5000    |  75000     |   25        | 4.25$   |
    |    10000   |  150000    |   50        | 8.5$    |
    |    25000   |  3750000   |   125       | 21.25$  |
    |    50000   |  750000    |   250       | 42.5$   |
    |    100000  |  1500000   |   500       | 85$     |
