### ISSUE TITLE
Some failures in the test_agentd due to messages received from Remoted simulator

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1145]
# Description

Hi team,
After running the test_agentd tests several times, we have encountered the following errors:
- Local integration test with wazuh and QA master branchs:
    - bento/ubuntu-18.04 [agentd_integration_report.zip](https://github.com/wazuh/wazuh-qa/files/6141643/agentd_integration_report.zip) 
    - ubuntu/bionic64 [agentd_info_connection_test.zip](https://github.com/wazuh/wazuh-qa/files/6141851/agentd_info_connection_test.zip)

After analyzing them, we have come to the conclusion that the messages are not being received correctly through the `receive_msg()` function. There must be a problem with the way RemotedSimulator sends messages.

# Examples
## test_agentd_multi_server 
It fails at the third sub-test:
`# 3. 3 Server - TCP protocol.`
[code](https://github.com/wazuh/wazuh-qa/blob/f62b79bcebc6588a768ff8be8c4376b1057f1fed/tests/integration/test_agentd/test_agentd_multi_server.py#L93-L121)

Report:
```
E       AssertionError: Error found in logs: 2021/03/15 11:30:09 wazuh-agentd[23498] receiver.c:66 at receive_msg(): ERROR: Connection socket: Connection reset by peer (104)
E         
E       assert '2021/03/15 11:30:09 wazuh-agentd[23498] receiver.c:66 at receive_msg(): ERROR: Connection socket: Connection reset by peer (104)\n' == None
```

It expects to receive:
`Lost connection with manager. Setting lock.`
[code](https://github.com/wazuh/wazuh/blob/4e64bdf0ba27efce89c37afbabeaa536a2ac3fec/src/client-agent/agentd.c#L202-L204)

However it receives:
`Server unavailable. Setting lock.`
[code](https://github.com/wazuh/wazuh/blob/4e64bdf0ba27efce89c37afbabeaa536a2ac3fec/src/client-agent/notify.c#L106)

## test_agentd_recconnection
It fails in `test_agentd_connection_retries_pre_enrollment[get_configuration0]`

Report:
```
E       AssertionError: Error found in logs: 2021/03/15 11:35:41 wazuh-agentd[20335] agentd.c:204 at AgentdStart(): ERROR: (1137): Lost connection with manager. Setting lock.
E
E       assert '2021/03/15 11:35:41 wazuh-agentd[20335] agentd.c:204 at AgentdStart(): ERROR: (1137): Lost connection with manager. Setting lock.\n' == None
```

**Comment by damarisg** [comment]
We decided to close them.
