### ISSUE TITLE
3.10 tests: SCA

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh-qa#115]
# SCA test

| Version | Revision | Branch |
| --- | --- | --- |
| x.y.z | rev | branch |

Checks for every OS
---------------------

- [x] Debian based distributions

- [x] RHEL/CentOS 7

- [x] RHEL/CentOS 6

- [x] RHEL/CentOS 5

- [x] Suse 11/12

- [x] Windows XP/Server 2003

- [x] Windows Server 2012

- [x] Windows > Vista

- [x] macOS

### Agents

- [x] Fresh installation. Check the correct policies for each OS are installed at `ruleset/configuration-assessment`.
- [x] Check the configuration template contains the module block with the correct policies.
- [x] Check the rootcheck configuration doesn't contain any setting for policy monitoring.
- [x] Try to run a policy whose requirements fail.
- [x] Set an absolute path for a policy out of the default directory.
- [x] Run scans for every available policy.
- [x] The second scan just sends differences and summaries.
- [x] Restart the agent. The whole scan should be sent to the manager but no repeated alerts must appear.
- [x] Disable a policy (use the attribute `enabled`) and rerun the scan.

### Manager

- [x] Check results of the first scan:
  - [x] The DB has been filled with all the information.
  - [x] Alerts about new checks and summaries appear in the `alerts.log` and `alerts.json`.
  - [x] The API returns information about policies and checks.
  - [x] See alerts on the Kibana Discover and information about the whole scan in the Conf. Assessment tab for the agent.

- [x] Check results of subsequent scans:
  - [x] The DB is updated.
  - [x] Alert about the different state of a check and summary alert (when any difference)
  - [x] When no differences between scans: Check that no alerts are triggered.
  - [x] The Configuration Assessment tab is updated.

- [x] Check results when a policy is disabled:
  - [x] The DB must purge the policy information and its checks.
  - [x] No alerts about the disabled policy.
  - [x] The Configuration Assessment tab is updated.

- [x] Check the configuration on demand:
  - [x] API call.
  - [x] Wazuh App.

Integrity
---------

- [x] Check the scan results are resend in a random interval between 5 seconds and `configuration_assessment.request_db_interval` when the integrity check fails.
- [x] No alerts about a resend are shown.
- [x] Check the database is updated correctly after a recovery.

Upgrade
---------

- [x] A warning message appears when Rootcheck is configured for policy monitoring.
- [x] Wazuh DB must upgrade agent databases including the new tables for Configuration Assessment.
- [x] Check the correct policies for each OS are installed at `ruleset/configuration-assessment`.
- [x] The ruleset upgrade script updates the Configuration Assessment policies.

Memory checks
----------------

- [x] Windows agent. Monitor memory usage and run Dr. Memory.
- [x] Linux agent. Valgrind in `wazuh-modulesd` and `agentd`
- [x] Manager. Valgrind in `remoted`, `analysisd` and `wazuh-modulesd`.

**Comment by SalvaMilenario** [comment]
Hi team 

In the check `The ruleset upgrade script updates the Configuration Assessment policies`, when restarting wazuh the manager not init and it notified the next error:

``` log
[root@centos6-manager2 vagrant]# /var/ossec/bin/update_ruleset -n 3.10
### Wazuh ruleset ###

The following rules will be updated:
	0020-syslog_rules.xml
	0095-sshd_rules.xml
	0245-web_rules.xml
	0250-apache_rules.xml
	0260-nginx_rules.xml
	0285-systemd_rules.xml
	0585-vipre_rules.xml
	0585-win-application_rules.xml
	0625-cisco-asa_rules.xml

The following decoders will be updated:
	0064-cisco-asa_decoders.xml
	0170-nginx_decoders.xml
	0220-postfix_decoders.xml
	0350-unix_decoders.xml
	0380-windows_decoders.xml
	0450-openvas_decoders.xml
	0470-perdition_decoders.xml

The following rootchecks will be updated:
	rootkit_trojans.txt

OSSEC requires a restart to apply changes.
Do you want to restart OSSEC now? [y/N]: y
2019/08/28 10:31:58 ossec-analysisd: CRITICAL: rules_list: Signature ID '60600' not found. Invalid 'if_sid'.
ossec-analysisd: Configuration error. Exiting
ERROR: OSSEC restart failed
```
This manager has the default configuration, it has only been updated.  

Regards

**Comment by snaow** [comment]
Hi @SalvaMilenario,

It was an issue related to two files with a duplicated file name.
Rule files loads according to file name alphabetic order, `0585-vipre_rules.xml` rules were loading before `0585-win-application_rules.xml`.
Vipre makes uses of Windows rules and it was referencing the 60600 rule ID.

Rule name was fixed here (https://github.com/wazuh/wazuh-ruleset/commit/afd404e0012a81786925b23917b8d814b0a3430c)

upgrade_ruleset is working now:

```
[root@manager-centos7 vagrant]# /var/ossec/bin/update_ruleset -n 3.10
### Wazuh ruleset ###

The following rules will be updated:
	0020-syslog_rules.xml
	0095-sshd_rules.xml
	0245-web_rules.xml
	0250-apache_rules.xml
	0260-nginx_rules.xml
	0285-systemd_rules.xml
	0585-win-application_rules.xml
	0601-win-vipre_rules.xml
	0625-cisco-asa_rules.xml
	0675-panda-paps_rules.xml
	0680-checkpoint-smart1_rules.xml

The following decoders will be updated:
	0051-checkpoint-smart1_decoders.xml
	0064-cisco-asa_decoders.xml
	0170-nginx_decoders.xml
	0220-postfix_decoders.xml
	0295-sonicwall_decoders.xml
	0350-unix_decoders.xml
	0380-windows_decoders.xml
	0450-openvas_decoders.xml
	0470-panda-paps_decoders.xml
	0470-perdition_decoders.xml

The following rootchecks will be updated:
	rootkit_trojans.txt

OSSEC requires a restart to apply changes.
Do you want to restart OSSEC now? [y/N]: Y
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing ossec-monitord...
Killing ossec-logcollector...
Killing ossec-remoted...
Killing ossec-syscheckd...
Killing ossec-analysisd...
ossec-maild not running...
Killing ossec-execd...
Killing wazuh-db...
Killing ossec-authd...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
Wazuh v3.10.0 Stopped
Starting Wazuh v3.10.0...
Started ossec-csyslogd...
Started ossec-dbd...
2019/08/28 12:20:43 ossec-integratord: INFO: Remote integrations not configured. Clean exit.
Started ossec-integratord...
Started ossec-agentlessd...
Started ossec-authd...
Started wazuh-db...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-remoted...
Started ossec-logcollector...
Started ossec-monitord...
Started wazuh-modulesd...
Completed.

Ruleset v3.10.0 updated to v3.10.0 successfully
[root@manager-centos7 vagrant]#
```
