### ISSUE TITLE
Include logic to collect TASAN and ASAN logs.

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1164]
Hi team.

We have been investigating how to integrate sanitizers like ThreadSanitzer or AddressSanitizer into the integration tests. This will help us to detect race conditions or memory leaks while testing the code. 

At this moment, some changes need to be done in the Wazuh code (https://github.com/wazuh/wazuh/issues/7952).

Once this is solved (and this is the main purpose of this issue), is to add the necessary logic to the integration test suite in order to get these logs and store them.

One approach is to use environment variables to set the path where the sanitizers will store the reports. A full list of the options can be found here: 

- ***TSAN***: https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags
- ***ASAN***: https://github.com/google/sanitizers/wiki/AddressSanitizerFlags

One important thing to bear in mind is that these sanitizers will impact the performance, so increasing the timeouts of the tests when using these sanitizers may be necessary.

**Comment by damarisg** [comment]
We decided to close them.
