### ISSUE TITLE
Add a module to stress upgrade queue using agent simulator

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1171]
Related to https://github.com/wazuh/wazuh-qa/issues/1168

We need to add an agent_simulator submodule to stress the upgrade queue defined by `#define UPGRADE_MQ      'u'` 

- [ ] Find an example of a valid log typically sent to this queue.
- [ ] Add a new way to generate different valid messages for the queue.
- [ ] Add the new submodule for the agent simulator.

**Comment by pacoqack** [comment]
The objective of this issue is not clear enough as we're not sure how and why we would like to stress this queue.

From now, we're going to let it on backlog.
