### ISSUE TITLE
Wazuh QA migration to core repository

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1189]
This change will allow us to centralized the development in a single repository, improve versioning and collaboration with other teams. To migrate this repository we must complete these tasks:

**Jenkins**
- [ ] Modify the deployment of the Wazuh QA repository and tools in these pipelines:
  - [ ] Test integration.
  - [ ] Nightly tests.
  - [ ] Service tests.
  - [ ] Performance tests.
  - [ ] Stress tests.
  - [ ] System tests.
  - [ ] Devops toolset tests.

**Documentation**
- [ ] In the docs of documentation.wazuh.com there're several references to this repository that must be removed.

**Wazuh QA repository**
- [ ] Analyze and transfer the issues from this repository to the new one.
- [ ] Move the codebase to the new repository. Since we can't transfer the PRs, we must transfer the code base, keep merging the "still-in-progress" issues in this repository and merge with the new one periodically.
- [ ] Remove references to this repository. This repository is referenced in several tests in the mocking functions, data, examples, etc. We must remove this.
- [ ] Update the docs and the script to generate them.

**Other tasks**
- [ ] Adapt the Wazuh QA changelog
- [ ] Set up Dependabots configuration for the Wazuh QA requirements.txt.

**Comment by damarisg** [comment]
We decided to close them.
