### ISSUE TITLE
3.10 tests: Windows MSI

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh-qa#119]
# Windows MSI

| Version | Revision | Branch |
| --- | --- | --- |
| x.y.z | rev | branch |

## Installation

To check in every test:

- Correct version.
- WUI doesn't show any strange information.
- Service is running correctly.
- No errors in ossec.log.

- [x] Successful installation by UI
- [x] Unattended installation
- [x] Unattended installation with registration parameters
- [x] Check the options "PEM" and "KEY" with absolute paths. (1)
- [x] Check the options "PEM" and "KEY" with relative paths.
- [x] Check the option "CERTIFICATE" with absolute paths. (1)
- [x] Check the option "CERTIFICATE" with relative paths.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Uninstall

To check in every test:

- It only remains the `client.keys`, `ossec.conf` and `local_internal_options.conf` files.
- The package and service are removed.

- [x] Successful uninstallation by running the MSI
- [x] Successful uninstallation by the Windows control panel

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Upgrade

To check in every test:

- It does not overwrite the `client.keys`, `ossec.conf` and `local_internal_options.conf`.
- WUI doesn't show any strange information.
- Service is restarted correctly.
- No errors in ossec.log.
- No duplicated package when upgrading from the EXE.

- [x] Upgrade MSI from 3.X.X
- [x] Upgrade from the current MSI
- [x] Upgrade MSI from EXE installation 2.X.X
- [x] Upgrade MSI from EXE installation 3.X.X
- [x] Check an unattended installation with PEM and KEY from a previous version.
- [x] Check an unattended installation with CERTIFICATE from a previous version.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Post-installation

- [x] Administrator user has full control on the folder.
- [x] Any administrator user must confirm UAC to access the folder.
- [x] Non administrator user can not access the folder unless he introduces an administrator password.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

(1) Use MS-DOS scaping form for paths with spaces. ( "C:\Program Files\sslagent.cert" would be "C:\Progra\~1\sslagent.cert" and "C:\Program Files x86\sslagent.cert" would be "C:\Progra\~2\sslagent.cert")

**Comment by carlocas** [comment]
**Failed Tier2: Unattended installation**

At the moment when I installed wazuh-agent in windows xp with the following command:
`wazuh-agent-3.10.0-0.31006.20190826.msi /q ADDRESS="172.16.1.22" AUTHD_SERVER="172.16.1.1" `
The msi registries the agent, but don't change `ossec.conf`, keeping the previous IP address 0.0.0.0. This prevents the agent from connecting with the manager except for the registry of the agent.

**Comment by carlocas** [comment]
**Failed Tier: 2 Upgrade from 2.1** 

When upgrading from OSSEC 2.1 to wazuh 3.10 the file `ossec.conf` is not upgraded in the section client. in ossec 2.1 has the next form:
```
 <client>  
    <server-ip>172.16.1.1</server-ip>
 </cliente>
```

While if we install 3.10 directly, without upgrading, obtain the following configuration:
```
  <client>
    <server>
      <address>172.16.1.1</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
´´´

**Comment by carlocas** [comment]
I found a problem installing wazuh in windows server 2003, by getting the following message: 

![image](https://user-images.githubusercontent.com/50922228/64170589-c5a2d800-ce50-11e9-964a-7d8d6f634db9.png)

I run this command `msiexec /l*v "log.log" /i "installer.msi"` to locate the DLL. At the log reported below we can find the missed DLL:
```
Action start 1:01:33: SchedSecureObjectsRollback.
MSI (s) (D4:B4): Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI2C.tmp, Entrypoint: SchedSecureObjectsRollback
MSI (s) (D4:30): Generating random cookie.
MSI (s) (D4:30): Created Custom Action Server with PID 1396 (0x574).
MSI (s) (D4:98): Running as a service.
MSI (s) (D4:98): Hello, I'm your 32bit Impersonated custom action server.
MSI (s) (D4:A8): Note: 1: 1723 2: SchedSecureObjectsRollback 3: SchedSecureObjectsRollback 4: C:\WINDOWS\Installer\MSI2C.tmp 
Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor.  Action SchedSecureObjectsRollback, entry: SchedSecureObjectsRollback, libr
ary: C:\WINDOWS\Installer\MSI2C.tmp 
MSI (s) (D4:A8): Product: Wazuh Agent -- Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor.  Action SchedSecureObjectsRollback
, entry: SchedSecureObjectsRollback, library: C:\WINDOWS\Installer\MSI2C.tmp 
```
This test have been performed in different windows server 2003 isos to ensure the results achieved.
This error only happens in this version of Windows.
