### ISSUE TITLE
Rename ossec.log to wazuh.log and ossec.json to wazuh.json in IT

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#1195]
The purpose of this issue is to rename `ossec.log` to `wazuh.log` and `ossec.json` to `wazuh.json` in Wazuh integration tests according to https://github.com/wazuh/wazuh/issues/8086.

**Comment by juliamagan** [comment]
We want to rename ossec.log to wazuh.log. 

### Estimated tasks

- [ ] Rename ossec.log to wazuh.log: https://github.com/wazuh/wazuh-qa/commit/7f5077fd69a54b78c2ed49c50eecf9a7ce141903
- [ ] Check the performance of the integration tests

> - [ ] test_active_response
> - [ ] test_agentd
> - [ ] test_analysisd
> - [ ] test_api
> - [ ] test_authd
> - [ ] test_cluster
> - [ ] test_fim
> - [ ] test_gcloud
> - [ ] test_log test
> - [ ] test_remoted
> - [ ] test_rids
> - [ ] test_rootcheck
> - [ ] test_vulnerability_detector
> - [ ] test_wazuh_db
> - [ ] test_wpk
