### ISSUE TITLE
wazuh-qa 5.0 agent process unification compliant.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-qa#1199]
## Description
This issue aims to modify the way in which verifications are made or Wazuh core processes are used in the internal workings of this repository, given the epic: https://github.com/wazuh/wazuh/issues/7981

For this, the following repository occurrences are listed so that they can be analyzed, modified, and/or adapted based on the requirement.

**Current:** execd, logcollector and syscheckd exist in the Wazuh ecosystem.
**Expected:** unify the old process behavior under the guardianship of wmodulesd. 
**Versions in which it should be applied:** >= 5.0 

Occurrences **EXAMPLES**: 
https://github.com/wazuh/wazuh-qa/search?p=1&q=logcollector
https://github.com/wazuh/wazuh-qa/search?p=1&q=syscheckd       -> a lot of modifications required.
https://github.com/wazuh/wazuh-qa/search?p=1&q=logcollector

**Comment by Dwordcito** [comment]
Hi @BraulioV I am writing to ask if they could analyze these changes and for what estimated date could they have them?

**Comment by BraulioV** [comment]
We will start this sprint to develop the changes. For now, these are the daemons:
- [ ] `execd`. 
- [ ] `logcollector`. These tests are currently being developed, so they will be the last ones to change.
- [ ] `syscheckd`.

**Comment by snaow** [comment]
Closed by: https://github.com/wazuh/wazuh-qa/pull/1457/
