### ISSUE TITLE
Integration tests for macOS logcollector module

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh-qa#1200]
|Linked Issue|
|---|
| wazuh/wazuh#4572 |

Hi Team!

As described in Epic wazuh/wazuh#4572, we are working in order to adapt the way Wazuh collects the logs on macOS systems, as they use their own way to store the logs (**[unified logging system](https://developer.apple.com/documentation/os/logging)**). This will require some new integration tests in order to verify that Wazuh is working as expected and without errors.

**Comment by spothound** [comment]
# Interesting information about macOS logcollector features.

They use log stream macOS utility.
```
log stream -h
log: usage:
    log stream [ --system | --process (pid|process) | --parent (pid|process) ]
	[ --level default|info|debug][ --predicate <predicate> ]
	[ --source ][ --style (syslog|json) ]
	[ --timeout <num>[m|h|d] ][ --type activity|log|trace ]
Usage:
	Stream stream activities, log data or trace messages from a given process
	or the system. By default, the command assumes system-wide streaming.  
	Specifying a process id with the --process option will narrow the results.
Examples:
log stream --level=info
log stream --predicate examples:
	--predicate 'eventMessage contains "my message"'
	--predicate 'eventType == logEvent and messageType == info'
	--predicate 'processImagePath endswith "d"'
	--predicate 'not processImagePath contains[c] "some spammer"'
	--predicate 'processID < 100'
	--predicate 'senderImagePath beginswith "my sender"'
	--predicate 'eventType == logEvent and subsystem contains "com.example.my_subsystem"'
```

## Configuration
There are new values for `log_format`and `location` (`macos`), also a new `query` tag have been added for them on localfile configuration. 
```
  <localfile>
    <log_format>macos</log_format>
    <location>macos</location>
    <query type="trace" level="debug">processImagePath CONTAINS[c] "com.apple.geod"</query>
  </localfile>
```

**Comment by snaow** [comment]
Duplicated Epic.
Progress tracking and future changes at: https://github.com/wazuh/wazuh-qa/issues/1329
