### ISSUE TITLE
Wazuh Core - execd as part of wazuh-modulesd

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh-qa#1204]
## Description
This issue aims to analyze the needed updates based on the work being done in Wazuh-Core repo about `execd` service (Issue https://github.com/wazuh/wazuh/issues/8028). From Wazuh version `5.0` onwards, `execd` service will be part of `wazuh-modulesd` one. 

## DoD
- [x] Analyze impacted places where updates are needed.
- [x] QA tests passed.
- [x] Check that the changes don't affect other modules/components.

**Comment by damarisg** [comment]
### 20-06-21

- Some changes were applied by Core.
- The package created generated problems with the tests.

### 21-06-21

- Working on the fails of the tests.

### 26-06-21 

- New changes were applied by Core.
- The package created generated problems with the tests.
![imagen](https://user-images.githubusercontent.com/3978434/119980800-2b26e880-bf93-11eb-8c56-8264bd8f5483.png)

### 27-06-21 
- The package created generated problems with the tests.
- Working on the fails of the tests.

### 28-06-21
- New changes were applied by Core.
- New package and some changes on the firewall-drop tests  

![imagen](https://user-images.githubusercontent.com/3978434/119980369-8efce180-bf92-11eb-8649-f5163a4f327d.png)

![imagen](https://user-images.githubusercontent.com/3978434/120004753-8534a780-bfad-11eb-852d-7c9f1dec897f.png)

**Comment by damarisg** [comment]
### 20-06-21

- Some changes were applied by Core.
- The package created generated problems with the tests.

### 21-06-21

- Working on the fails of the tests.

### 26-06-21 

- New changes were applied by Core.
- The package created generated problems with the tests.
![imagen](https://user-images.githubusercontent.com/3978434/119980800-2b26e880-bf93-11eb-8c56-8264bd8f5483.png)

### 27-06-21 
- The package created generated problems with the tests.
- Working on the fails of the tests.

### 28-06-21
- New changes were applied by Core.
- New package and some changes on the firewall-drop tests  

![imagen](https://user-images.githubusercontent.com/3978434/119980369-8efce180-bf92-11eb-8649-f5163a4f327d.png)

![imagen](https://user-images.githubusercontent.com/3978434/120004753-8534a780-bfad-11eb-852d-7c9f1dec897f.png)

### 31-05-21

Generate documentation without errors:
![imagen](https://user-images.githubusercontent.com/3978434/120205676-9d503500-c200-11eb-8eb0-cac6a63f61b4.png)

**Comment by spothound** [comment]
Closed by https://app.zenhub.com/workspaces/wazuh---qa-6013ee7425d3d80017069c76/issues/wazuh/wazuh-qa/1389
