### ISSUE TITLE
Add tests to check that the registry syncronization messages are correctly parsed

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1210]
|wazuh core issue|
|---|
|https://github.com/wazuh/wazuh/issues/7836|

Hi team!

This issue aims to add new integration tests to check if the synchronization messages are correctly parsed in windows agents: 
- The test will look for this message: 
```
DEBUG: (6317): Sending integrity control message: {"component":"fim_registry","type":"state","data":{"timestamp":1617886746,"path":"HKEY_LOCAL_MACHINE\\SOFTWARE\\random_key","arch":"[x64]","value_name":":test","attributes":{"type":"registry_value","value_type":"REG_SZ","size":1,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"4ca7b88b201728c31afb691707c41d35a984317d"},"version":"2.0"}}
```
- The test will check if the key path (of keys and subkeys) and value names are correct. 
- The test will perform changes in the DB (without triggering alerts) and will check that the synchronization is correct.

**Comment by Molter73** [comment]
Closing this issue since the associated PR was already merged
