### ISSUE TITLE
 Logcollector integration tests T0: Test only-future-events option

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1229]
It is necessary to add tests for the logcollector source location option as part of https://github.com/wazuh/wazuh-qa/issues/1027

# Objectives
- [x] Test only-future-events option: start the manager, turn it off and send logs. Now, you have two possible scenarios:
   -  yes: the daemon will continue reading from the end.
   - no: the daemon will continue reading from the same line where it was stopped and both logs must be read and reported.

# Steps
1. Change wazuh conf to monitorize a file
2. Write some lines in the file (more than 10MB, for example)
2. Restart logcollector
3. Write some logs to the file and confirm that it has been collected by logcollector
4. Stop logcollector
5. Write another logs to the file
6. Start logcollector. If `only-future-events` is set to `yes`, check that the log has not been analyzed, check that the log has been analyzed elsewhere. 
7. Write a new log and confirm that it is collected.

# Planification
- We will use logcollector debug mode 2 to check the vents collected by the module.
- It is not required to check if alerts are generated, we will only check if logcollector y reading the logs written to the file.

**Comment by spothound** [comment]
Hello, 

We've been informed that these tests must also work in other platforms apart from Windows. 

We've modified the basic_configuration test for this option to make it work on Linux/Unix systems.

**Comment by mdengra** [comment]
## 2021/05/06
- I have been analyzing the behavior of the `only-future-events` option along with its `max-size` parameter by performing multiple tests for test development.

## 2021/05/07
- I am developing the code part of the test.
