### ISSUE TITLE
 Logcollector integration tests T0: Test command/full_command option

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1236]
It is necessary to add tests for the logcollector command and full_command options as part of https://github.com/wazuh/wazuh-qa/issues/1027

# Objectives
- [x] Test command  and Test full_command options.
- [x] The command tested must be available on **Linux/MacOS/** or use different commands for each one.
- [x] Test command with empty output.
- [x] Test command not found.
- [x] Test command that doesn't end. `tail -f /var/ossec/logs/ossec.log` 
- [x] Test command with too long output.
- [x] Test command that fail `cat doesntexists.txt`
- [x] Test command that took few seconds and is killed by the system/test
- [x] Test command with arguments
- [x] Test command including special characters and "foreign" language characters ("ñ", "テスト", "ИСПЫТАНИЕ", "测试", "اختبار") `echo ***`
- [x] Check that the log "Read ... lines from command '...'" appear with debug=2
- [x] Check that the log "Running command ..." appear with debug=2
- [x] Check that the log "Reading command message ... " appear with debug=2 and the output coincides with the expected one. For example for an `echo "hello world"`, "hello world" must appear in `ossec.log`
- [x] Test the [alias option](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#alias)

## Tests modules
- [x] Test execution frequency -> seconds, minutes, hours...
   - set frequency to n
   - wait n/2
   - check that the command is not executed again
   - wait n/2 
   - check that the command is executed 
- [x] Test command execution

**Comment by mdengra** [comment]
## 2021/04/20
- Working on test command execution module (Linux):
  - Command not found.
  - Command that doesn't end.
  - Command with too long output.
  - Command that fails.
  - Commands including special characters and "foreign" language characters.
