### ISSUE TITLE
Integrate API performance test with the cluster performance test

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1245]
It is necessary to add the performance API tests to the cluster testing process.

The idea is to add a new parameter that allows enabling a new check in the test, which performs a series of requests to the cluster API and checks if the requests are indeed answered within an expected time.

To do this, it will be necessary to add a new parameter in the Jenkins UI, and to create a new ECSTask that will be in charge of launching this process. Finally, the test results should be collected and attached as Jenkins artifacts.

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-jenkins/pull/2518
