### ISSUE TITLE
Add test to ensure only one modify event is being generated from windows registries with same name but different capitalization

### ISSUE THREAD

**Issue by JoseAntonioMHerrera** [wazuh/wazuh-qa#1246]
|wazuh core issue|
|---|
|[wazuh/wazuh/#6797](https://github.com/wazuh/wazuh/issues/6797)|

Hi qa-team!

I opened this issue due to the necessity of a new integration test for windows agent, due to being case insensitive. The registration of registries with the same name_value but different capitalization should end in only one of them being monitored. The test integration should look for **Sending FIM event:** with type **modify**  appearing only once after make a modification in one of the two registries created with the above restrictions.

The test will do:
* Create two registries with the said restrictions and modify one of them
* Call to the log monitor to grab the modify event
* Call a second time to the log monitor and catch the Timeout exception error

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1247
