### ISSUE TITLE
Integration tests for Vulnerability Detector: Amazon Linux support

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1248]
### Description

This issue is part of wazuh/wazuh#6734

We will include support for the Amazon Linux OS, including two new feeds, one for Amazon Linux and another one for Amazon Linux 2.

The following tests should cover the new supported OS:

- Feed tests: These tests have to cover the addition of the new feeds for Amazon Linux
- Provider tests: Here we will test the settings for the new provider
- Scan results tests: Here we have to add the tests that ensure Amazon Linux agents are scanned properly

**Comment by mdengra** [comment]
I have found a possible segmentation fault in `modulesd`.

**Comment by mdengra** [comment]
While performing the vulnerability detector tests, Windows tests (`test_cpe_indexing.py`) are giving some errors. There is an open issue (#1484), which is in PR, so as soon as the merge is done I will add in this branch the fix.

### 2021/06/23
- Fixed errors in:
  - test_missing_tags_alas_feed.py
  - test_general_settings_ignore_time.py
  - Performed offline vulnerability detector tests

**Comment by mdengra** [comment]
To speed up the development I have applied the commit of issue #1484, I have tested the `vulnerability detector` tests for Windows in a local environment and they work correctly, so I remove the dependency that blocked this issue.
