### ISSUE TITLE
Integration tests for Vulnerability Detector: SUSE support

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1249]
### Description

This issue is part of wazuh/wazuh#7171

We will include support for the SUSE OS, including new feeds for every supported platform, which are mentioned at wazuh/wazuh#8373.

The following tests should cover the new supported OS:

- Feed tests: These tests have to cover the addition of the new feeds for SUSE
- Provider tests: Here we will test the settings for the new provider
- Scan results tests: Here we have to add the tests that ensure SUSE agents are scanned properly

**Comment by MarcelKemp** [comment]
## TO DO LIST

For _`SLES 11, 12, 15`_ and _`SLED 11, 12, 15`_:
- [ ] Add SUSE to download feeds test
- [ ] Add SUSE to invalid type custom feed
- [ ] Add SUSE to invalid type URL feeds
- [ ] Add SUSE to validate feed content
- [ ] Add SUSE's extra tag tests
- [ ] Add SUSE's invalid syntax feed test
- [ ] Add SUSE's invalid values tests
- [ ] Add SUSE's missing fields test

We're working with the core development branch: https://github.com/wazuh/wazuh/tree/7171-suse-vdt
QA branch: `1249-vd-suse`

**Comment by chemamartinez** [comment]
The development done for this issue has been reworked at https://github.com/wazuh/wazuh-qa/issues/2792
