### ISSUE TITLE
Add custom labels for the keep-alive messages in the cluster performance test pipeline

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1260]
It is wanted to specify a series of custom labels in the cluster performance tests.

To do so, the following changes need to be made:

- [x] **1**:  Collect a list of labels and their values through the Jenkins UI.
- [x] **2**:  Parse the labels to a String format `label1:value1 label2:value2 label3:value3`...
- [x] **3**:  Add in the simulate-agent script a new parameter to accept the custom label list.
- [x] **4**: Parse the String into a dictionary format by `label:value`, and pass it to the `Agent` object for its use.
- [x] **5**: Test the made changes .

**Comment by BraulioV** [comment]
Closed by: 
- https://github.com/wazuh/wazuh-qa/pull/1276
- https://github.com/wazuh/wazuh-jenkins/pull/2532
