### ISSUE TITLE
Env monitoring not working after managers are restarted

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1267]
## Description

Hey team!

We are starting to test big environments in the `Test_cluster_performance` Jenkins pipeline. 

In the process, we found out that the tools used to monitor the resources consumption of the different Wazuh processes stop working correctly after being restarted. For example, in this graph we see that from ~9:01:30, CPU usage is 0 for all services during the remaining monitoring time. 
![image](https://user-images.githubusercontent.com/23361101/116683258-9e970380-a9af-11eb-83b7-e3d7c48af7f3.png)

This happens at the same time as the reboot of the cluster nodes: 
```
2021/04/30 09:01:30 INFO: wazuh 172.31.77.19 "PUT /cluster/restart" with parameters {} and body {} done in 0.074s: 200
```

Process PIDs change after restarting Wazuh but it seems that the tool is not taking this into account right now. 

Regards,
Selu.

**Comment by jmv74211** [comment]
Closed because no case like this has occurred anymore.
