### ISSUE TITLE
Add missing INTERNAL OPTIONS to logtest integration test

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1272]
We need to force analysisd.debug=2 to be set in our internal options configuration file for integration test.

We will discuss if do it on Jenkins or in the python code.

Best regards.

**Comment by BraulioV** [comment]
For now, let's add this option to our Jenkins pipeline. It is planned to change how the tests are configured and all of them will autoconfigure the manager internal's options.

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-jenkins/pull/2539
