### ISSUE TITLE
Performance test: parse the info from `cluster_control`

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1287]
`wazuh-clusterd` logs useful information with the `cluster_control` binary as the health check, info from the node, the agents in the cluster, etc. 

We must keep tracking of this info in a file to know the status of the cluster at any time during the test.

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

After analyzing the results, we have determined that it is better to parse the logs after the test is run. This way we do not add extra load to the cluster.

On the other hand, we need to extract the information from the **integrity check and sync** and **agent-info** processes. Once the data has been extracted we will make some graphs to make the comparisons.

**Comment by AdriiiPRodri** [comment]
## Status update

We have added a new script in charge of parse the cluster.log file. 

This file will generate as many CSVs as operations that the cluster has performed (Agent-info sync, Integrity check and Integrity sync). 

Once these CSVs are generated, the data_visualizations.py script will be able to generate the plots where the information of the CSVs generated by the previous script.

## Configuration options

```
adriiiprodri@wazuh wazuh-log-metrics -h
usage: wazuh_log_metrics.py [options]

Wazuh log parser

optional arguments:
  -h, --help            show this help message and exit
  -l LOG, --log LOG     Log file to be analyzed.
  -t {cluster}, --target {cluster}
                        Log type to be parsed. Default cluster.
  -o OUTPUT, --output OUTPUT
                        Folder where the extracted data will be dumped (csv).
```

Added new "cluster" option to target argument:
```
adriiiprodri@wazuh data-visualizer -h
usage: data-visualizer [options]

Script to generate data visualizations

optional arguments:
  -h, --help            show this help message and exit
  -s CSV_LIST [CSV_LIST ...], --sources CSV_LIST [CSV_LIST ...]
                        Paths to the CSV files separated by whitespace.
  -t {binary,analysis,remote,agent,logcollector,cluster}, --target {binary,analysis,remote,agent,logcollector,cluster}
                        Generate data visualizations for a specific target. Default binary.
  -d DESTINATION, --destination DESTINATION
                        Directory to store the images. Default /tmp
  -n NAME, --name NAME  Base name for the images. Default None.
```

## CSV example

### Agent-info
```csv
node_name,activity,time_spent(s)
manager_3,Agent-info sync,0.002
manager_1,Agent-info sync,0.002
manager_8,Agent-info sync,0.002
manager_9,Agent-info sync,0.002
manager_4,Agent-info sync,0.002
manager_2,Agent-info sync,0.002
manager_7,Agent-info sync,0.002
manager_6,Agent-info sync,0.002
manager_10,Agent-info sync,0.004
manager_5,Agent-info sync,0.002
manager_3,Agent-info sync,0.002
manager_1,Agent-info sync,0.002
manager_8,Agent-info sync,0.003
manager_9,Agent-info sync,0.002
manager_4,Agent-info sync,0.002
manager_2,Agent-info sync,0.002
manager_7,Agent-info sync,0.002
```

## Plots example
### Agent-info
![agent_info](https://user-images.githubusercontent.com/15522808/117129553-1f367500-ad9f-11eb-9965-140951709815.png)

### Integrity check
![integrity_check](https://user-images.githubusercontent.com/15522808/117129605-307f8180-ad9f-11eb-82a8-712995e1ae14.png)


### Integrity sync
![integrity_sync](https://user-images.githubusercontent.com/15522808/117129582-29587380-ad9f-11eb-8fab-69ed3f2dfe9c.png)

**Comment by AdriiiPRodri** [comment]
## Status update

Added mean and median:

![image](https://user-images.githubusercontent.com/15522808/117283511-24122c00-ae66-11eb-9aac-f20db279491b.png)

![image](https://user-images.githubusercontent.com/15522808/117283548-2d9b9400-ae66-11eb-8645-6f9a6fd4b914.png)

![image](https://user-images.githubusercontent.com/15522808/117283584-35f3cf00-ae66-11eb-8245-bb7f5a25273a.png)
