### ISSUE TITLE
GCP integration tests errors

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1291]
There're several tests for this component that fails with the 4.2 and master branches of Wazuh. 

- `test_rules[get_configuration0]`: _TimeoutError: Did not receive expected Sending gcp event_
- `test_day_wday[get_configuration2-tags_to_apply2]`: _TimeoutError: Did not receive expected "Starting fetching of logs" event_
- `test_day_wday[get_configuration1-tags_to_apply1]`: _TimeoutError: Did not receive expected "Starting fetching of logs" event_
- `test_day_wday[get_configuration0-tags_to_apply0]`: _TimeoutError: Did not receive expected "Starting fetching of logs" event_

`test_rules` fails because the timeout set for this test is not enough and sometimes, the event appears. However, `test_day_wday` fails always and this is caused by an error in the test itself. The error is related to how the events are expected in the log.

**Comment by damarisg** [comment]
We decided to close them.
