### ISSUE TITLE
Sudden drops of TCP sessions in Test_cluster_performance. 

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1294]
## Description

Hi team!

Another problem explained [here](https://github.com/wazuh/wazuh/issues/8439#issuecomment-831853458) and maybe related to the issue #1292 is that the number of TCP sessions seems to drop multiple times in the stats of `wazuh-remoted` gathered in the `Test_cluster_performance` piepline.

In this graph (wazuh-remoted TCP sessions, worker1, build 185), we can see some strange peaks at `11:12:00`, ~`11.19:20` and ~`11:22:00`:
![image](https://user-images.githubusercontent.com/23361101/117018289-a844a200-acf4-11eb-8e93-926dd3fbec6c.png)

In this case, the API tests have not been launched since they cause reboots in the cluster managers and could distort the data. It means that those drops don't seem to be related with any Wazuh restart, which makes them even weirder. 

Furthermore, it seems that after each drop in connections, the number of reconnections is less than expected, causing fewer and fewer agents to be connected. 

Regards,
Selu.

**Comment by Selutario** [comment]
## Description

Hey team,

We found again this problem in the build 230 https://github.com/wazuh/wazuh/issues/8439#issuecomment-838306848:
![imagen](https://user-images.githubusercontent.com/23361101/117964245-ac3e7880-b321-11eb-81ac-f806d46d9290.png)

The first drop is at `9:04:03`. We thought at first that it was the consequence of the ECS hosts being destroyed, since it happened 16 minutes after the first agents were connected (`08:48:10`) and `TEST_TIME` was 900 seconds (15 minutes). However, it makes no sense since almost all agents are reconnected shortly after the drop (unlike what happened in the original post).

The graph is from worker1 but it follows the same pattern in all workers. 

Regards,
Selu.

**Comment by mcarmona99** [comment]
Hi team,

When working on [this issue](https://github.com/wazuh/wazuh/issues/8562), I have run the build 234 to test a cluster environment with:

- 50.000 agents
- 25 workers

In that build, I have found the problem reported in this issue. In this case, the environment has less agents but more workers. There are also more TCP sessions dropping, as it can be seen in this plot example:

![image](https://user-images.githubusercontent.com/57481331/117974064-6d162480-b32d-11eb-8011-c473375f0ffb.png)


The plot is the worker2 one but all workers' plots follow the same pattern.

Regards,
Manuel.
