### ISSUE TITLE
Logcollector integration tests T1: Test internal options state_interval

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1302]
#### Issue information
| Epic 	| target-branch 	| Wazuh version 	|
|-	|-	|-	|
| https://github.com/wazuh/wazuh-qa/issues/1028 	| master 	| 4.2 or higher 	|

## Issue definition
![image](https://user-images.githubusercontent.com/15269938/117267845-fbcf0100-ae56-11eb-9723-708550a03f4d.png)
We need to test internal options for logcollector módule, in concrete, the `state_interval` option which defines "Statistics generation interval, in seconds" (See [dev docs](https://documentation-dev.wazuh.com/current/user-manual/reference/internal-options.html?highlight=internal%20options). This option is available from version 4.2 or higher (wazuh branch).

This option modifies the frequency for updates of [logcollector statistic files](https://documentation-dev.wazuh.com/current/user-manual/reference/statistics-files/wazuh-logcollector-state.html). We need to check that the option works right!

### Allowed values
- [x] Set `logcollector.state_interval` to less than 0. It must return: `Invalid definition for 'logcollector.state_interval: ‘-10’`.
- [x] Set `logcollector.state_interval` to more than maximum allowed (eg: 99800). It must return: `Invalid definition for 'logcollector.state_interval: ‘99800’`.
- [x] Set `logcollector.state_interval` to a dummy value (eg: `test`). It must return: `Invalid definition for 'logcollector.state_interval: ‘dummy’`.
### Operation
- [x] Measure time between statistic generation file updates and confirm that it correspond with the selected value.

### Test plan
1. Monitorice an empty file with logcollector and set a value for the state interval option, for example, 10 seconds.
2. Make a change in the monitored log file and wait until the statistic file changes
![image](https://user-images.githubusercontent.com/15269938/117268655-d098e180-ae57-11eb-9790-15b8069a1524.png)
3. Save the current time, make another change and wait until it appears in the file.
4. Save the current time, calculate the modification interval and compare it with the state interval defined.
5. Assert that the difference is equal or less than one second.

**Comment by juliamagan** [comment]
### 05/07/2021

The first approach to the test would be:
The use cases will be found in local_internal_options, it is necessary to study if it is necessary to change the function of get_local_internal_options.
We create the file to monitor.
We check that the entered value is valid, that is, if they are not numbers, we will look for the error callback.
If they are numbers but they are less than 0 or greater than 3600, we again look for the error callback.
Create a function to check that the file `/ var / ossec / var / run / wazuh-logcollector.state` has changed and start counting the time.
We make changes in the monitored file and when `/ var / ossec / var / run / wazuh-logcollector.state` changes again we stop counting the time, or we count and calculate the difference with the previous one.
Finally, we check that the time is approximately the same (margin of one second).

**Comment by juliamagan** [comment]
### 05/12/2021
I have been considering how the code could be developed. Also, I have been studying the code to get the interval from `/var/ossec/var/run/wazuh-logcollector.state` instead of monitoring the file and noting when it changes.

**Comment by juliamagan** [comment]
### 05/13/2021
Finished checking valid values. It remains to monitorize the file and check if the time elapsed equals the interval.

**Comment by juliamagan** [comment]
### 05/17/2021
Finished the test and passed in Linux agent and manager. It remains to pass in a windows agent, but it fails because it can't restart correctly.

**Comment by juliamagan** [comment]
### 05/18/2021
Changing the code of the test, we could see that the `logcollector.state` file changes before the interval is completed. I'll have to create a specific fixture for my test that changes the `local_internal_options` even there is an error.

**Comment by juliamagan** [comment]
### 05/19/2021
I have created a specific `get_local_intenal_options` fixture for the test and a `wait_statistics_file` common fixture in `logcollector.py` because in every test that we need the `/var/ossec/var/run/logcollector.state` file, we will need to wait after the restart of Wazuh. The tests seem to work correctly in Linux (both manager and agent), but in Windows, the Wazuh agent is having some problems.

**Comment by juliamagan** [comment]
### 05/20/2021
Opened an issue because Windows agent wasn't showing error messages. Now, for Windows, the test will check if the wazuh service is stopped when an invalid value is given. It remains to fix the problem with the time in Windows.

**Comment by juliamagan** [comment]
### 05/21/2021
Trying to check that wazuh service wasn't running, we noticed that the function `check_daemon_status` doesn't work for Debian because the output is different. We thought about update this function so it runs `/var/ossec/bin/wazuh-control status` but permission is denied.

**Comment by juliamagan** [comment]
### 05/24/2021
Refactor `check_daemon_status()` function in `services.py`, but the test keeps failing in Windows because of the restarts. It checks the status before restarting wazuh, so the condition is wrong.
