### ISSUE TITLE
Adjust launch times and task monitoring in the cluster performance test.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1303]
In order to better monitor the cluster environment in the cluster performance test, it is necessary to adjust the times of each task according to its dependencies and the deployment time of the environment.

It is requested to perform an analysis on the timeline of each task and to adjust the environment monitoring time according to variables such as the environment time, preparation time of an ECSTask ...

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-jenkins/pull/2549
