### ISSUE TITLE
 Logcollector integration tests T1: Test location with custom sockets

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1304]
#### Issue information
| Epic 	| target-branch 	| Wazuh version 	|
|-	|-	|-	|
| https://github.com/wazuh/wazuh-qa/issues/1028 	| master 	| 4.2 or higher 	|

## Issue definition

![image](https://user-images.githubusercontent.com/15269938/117271926-f5db1f00-ae5a-11eb-900f-c60b5a085826.png)

The localfile tag for logcollector accepts an option called ['target'](https://documentation-dev.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=localfile#target) which specifies the name of a socket where the output will be redirected. The socket must be defined previously. 

In 4.2 we've added a  [logcollector statistic file](https://documentation-dev.wazuh.com/current/user-manual/reference/statistics-files/wazuh-logcollector-state.html) file for logcollector. In this file there is a file called `drops` when the redirection to a socket is defined. This field count event dropped by a communication error with the socket.
![image](https://user-images.githubusercontent.com/15269938/117270688-c24bc500-ae59-11eb-8742-0ea398008d3c.png)

## Test requirements
- [ ] Set `location` with a custom socket. Create this socket, send a log to the file and check if the `drops` value for that localfile doesn't change in the interval nor globally.
- [ ] Set `location` with a custom socket. Don't create the socket, send a log to that location file and check if the down counter is increased for the interval and globally.

### Test plan
1. Set location to a custom path with a custom socket
2. Create the socket.
3. Send logs to the file and check that the `drops` value in the statistics file doesn't change in the interval nor globally.
4. Close the socket.
5. Send more logs to the file and check that the `drops` value counter increases for the interval and globally.

![image](https://user-images.githubusercontent.com/15269938/117278497-1dcd8100-ae61-11eb-9cd0-e2a77f68015c.png)
![image](https://user-images.githubusercontent.com/15269938/117278564-2a51d980-ae61-11eb-9015-37fcdd33dd5d.png)

**Comment by mdengra** [comment]
## 2021/05/10
- I am performing manual tests to study the behavior of logcollector when using custom sockets.
