### ISSUE TITLE
Creating registries already created in test_basic_usage_registry_changes

### ISSUE THREAD

**Issue by JoseAntonioMHerrera** [wazuh/wazuh-qa#1306]
Hi team!

The execution of \test_fim\test_registry\test_registry_basic_usage\test_basic_usage_registry_changes.py fails sometimes due to an added event expected not founded in logs. The thing is in the create_registry call sometimes try to create registries already created, so the return of `win32api.RegCreateKeyEx(key, subkey, win32con.KEY_ALL_ACCESS | arch)` returns the key and a flag with value 1 if the registry has been created or 2 if the registry was already created. I added the following code to create_registry function to see if the registry exists before is created in the function:

```        
            try: 
                key_h = win32api.RegOpenKeyEx(key, subkey, 0, win32con.KEY_ALL_ACCESS | arch)
                logger.info("[CREATE REGISTRY] Registry found!")
            except pywintypes.error as e: 
                pass
```

If the register doesn't exists, it raises a pywintypes.error alerting that the register wasn't found in the system. This could be the reason for the added event not showing in the logs, but there is other executions where the register already exists and the test pass correctly. Is this some kind of expected behaviour?

Report: [registries_already_created_report.zip](https://github.com/wazuh/wazuh-qa/files/6433646/registries_already_created_report.zip)

**Comment by JoseAntonioMHerrera** [comment]
Update:

The call to create_registry with existing registry keys looks like an expected behaviour. The two that are being recreated ("SOFTWARE\\Classes\\testkey" and "SOFTWARE\\testkey") acts as root keys. The two of them will hold subkeys that are the ones triggering the required events. The call to create_registry with keys already created doesn't have any effect on this tests due to win32api.RegCreateKeyEx(key, subkey, win32con.KEY_ALL_ACCESS | arch) returning two different flag numbers to clarify if the registry was previously created or if it was created in this call but the flag is ignored in the return.

**Comment by damarisg** [comment]
We decided to close them.
