### ISSUE TITLE
Auth integration tests error

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1316]
![image](https://user-images.githubusercontent.com/15269938/117800901-f3f6ce80-b253-11eb-9a97-05909d1b1c00.png)

There is an error in our auth integration tests when running on the master branch.

The problem is that the `configure_sockets_environment` function calls to `check_daemon_status` after stopping wazuh and this function has a timeout (by default) of 10 seconds. As some daemons (in this case, clusters) have not stopped in these 10 seconds. The test fails before even start.

We need to increase the timeout of `check_daemon_status` function and check fi this sovles the problem.

**Comment by spothound** [comment]
Failed build: https://ci.wazuh.info/job/Test_integration/3223/

**Comment by mdengra** [comment]
Increasing the timeout even to 10m still causes the problem.
