### ISSUE TITLE
Not all agents connected in Test_cluster_performance pipeline environment

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-qa#1318]
Hello team,

As explained in [this issue update (finding 1)](https://github.com/wazuh/wazuh/issues/8439#issuecomment-836673950). After testing the Test_cluster_performance pipeline, we have seen that not all agents were connected to the cluster.

In an environment with these characteristics (build 227):

- 1 master node
- 10 workers
- 50.000 agents (agents only connect to workers)
- Kibana API requests

there were 2 agents missing.

In the worker TCP sessions plots, there are no problems but if we see the raw data, we can see the tcp sessions decrease from 5000 to 4999. It happens in almost all workers. The sessions decrease from 5000 to 4999, 4999 to 4998, 5002 to 5001; and 5001 to 5000. This can be an expected behaviour regarding the load balancer but when we see the total of TCP sessions, there are `49998` active agents (2 missing).

![image](https://user-images.githubusercontent.com/57481331/117802510-d9bdf000-b255-11eb-8f72-3a5ee8371c5c.png)

We can also see this in the master `cluster.log`. The expected number of metadata files is `50011` and the actual value is `50009`:

```
2021/05/10 13:33:03 INFO: [Master] [Local integrity] Starting.
2021/05/10 13:33:06 INFO: [Master] [Local integrity] Finished in 2.702s. Calculated metadata of 50009 files.
```

First, we though some agents could be trying to register (and registering) with an existant ID (possible with force). This would replace one agent with a new one, so the insertion wouldn't be done.

We have proved that this is not happening since we have 50000 unique keys in our master `ossec.log`.

```
Number of registration requests: 50000
Number of UNIQUE keys: 50000
```

Regards,
Manuel.

**Comment by Selutario** [comment]
## Issue update

## Description

Hi guys!

In the build 230 of Test_cluster_pipeline, with these parameters:
- 75000 agents
- 15 workers
- test_time: 900s

In addition to what is reported in https://github.com/wazuh/wazuh-qa/issues/1325 (75k agents should have been registered, but finally only 72577 are), here some agents are not going active too. 

Looking at the master's `cluster.log` file, this log message is repeated starting on `9:10:50` (master is up until `9:19:18`):
```
2021/05/11 09:10:50 INFO: [Master] [Local integrity] Finished in 3.886s. Calculated metadata of 72086 files.
```

It means that, if we compare this value (72086) with the number of registered agents (72577), there are 491 agent-group files that were never created: those agents did never connect to any worker. It is already reported in the original post, but there it happened with only 2 agents.

Regards,
Selu.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
