### ISSUE TITLE
Wrong behavior in the load balancer used in Test_cluster_performance 

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-qa#1323]
Hello team,

When working on [this issue](https://github.com/wazuh/wazuh/issues/8562), I have run the build 233 to test a cluster environment with 10 workers and 25k agents.

I have seen the agents have not been connected to the workers properly. After having a look to the plots and data, I have found that:

- Workers 1 to 9 have 2644, 2645, 2645, 2646, 2644, 2645, 2646, 2646 and 2622 agents connected, respectively.
- Worker 10 has 717 agents connected.

The plots also show this error:

- Worker 2 TCP sessions plot:

![image](https://user-images.githubusercontent.com/57481331/117972309-4525c180-b32b-11eb-97d8-2fdc3654de26.png)

- Worker 10 TCP sessions plot:

![image](https://user-images.githubusercontent.com/57481331/117972371-5969be80-b32b-11eb-8ff0-87c1c48c7242.png)

This error does not depend on the environment size as we have tested bigger envs (10 wk, 50k agents, for example) and this did not happen. It appears to be an error caused by a LB race condition.

Regards,
Manuel.

**Comment by davidjiglesias** [comment]
This issue seems to be fixed in the latest runs.
