### ISSUE TITLE
Not all agents are being registered in Test_cluster_pipeline

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1325]
| Related issue |
|--|
| https://github.com/wazuh/wazuh/issues/8439#issuecomment-838306848 |

## Description

Hi guys!

In the build 230 of `Test_cluster_pipeline`, with these parameters:
- 75000 agents
- 15 workers
- test_time: 900s 

We found out that not all agents are being registered. If we parse the master's `ossec.log` file to count all logs like `Received request for a new agent (1-POGkSJAq7zwZKQyB-debian10) from`, we get this:
```
Number of registration requests: 72577
Number of UNIQUE keys: 72577
```

The log is truncated right after the last registration requests, which could lead us to think that the hosts have been destroyed before all the agents could register. 
```
2021/05/11 09:00:30 wazuh-authd: INFO: Received request for a new agent (1-T5dV8eCE6U4vZMws-debian10) from: 172.31.29.87
2021/05/11 09:00:30 wazuh-authd: INFO: Agent key generated for '1-T5dV8eCE6U4vZMws-debian10' (requested by any)
2021/05/11 09:00:43 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2021/05/11 09:00:43 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

We see that the last log is at `9:00:43`. However, in this master's CPU graph it can be seen that it is up and running until `9:17:00`, although authd stopped using CPU at `9:00:30`:
![imagen](https://user-images.githubusercontent.com/23361101/117967450-58359300-b325-11eb-94e8-45a877dd02e2.png)

Eventually, many logs (below) are shown reporting that too many connections to `wazuh-authd` are taking place and those are rejected. I think this is already expected and correctly handled in the pipeline, but just in case:
```
2021/05/11 08:59:08 wazuh-authd: ERROR: Too many connections. Rejecting.
2021/05/11 08:59:08 wazuh-authd: ERROR: Too many connections. Rejecting.
2021/05/11 08:59:08 wazuh-authd: ERROR: Too many connections. Rejecting.
```

Regards,
Selu.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
