### ISSUE TITLE
Authd integration tests for remote_enrollment option

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#1326]
As described in https://github.com/wazuh/wazuh/issues/8616, it was necessary to introduce a new configuration option in Authd daemon that allows to enable/disable remote enrollment.

By default, remote enrollment is enabled. When disabled, Authd TLS port (1515 by default) won't be listening to new connection, but requests to local socket will still be attended.

To complete this issue, it is necessary to add some IT that will test this new option:

- Test when remote enrollment is enabled in a stand alone manager.
- Test when remote enrollment is enabled in a master node.
- Test when remote enrollment is enabled in a worker node.
- Test when remote enrollment is disabled in a stand alone manager.
- Test when remote enrollment is disabled in a master node.
- Test when remote enrollment is disabled in a worker node.

**Comment by spothound** [comment]
## 05/25/21

We've been working on this.

- An added a new test called test_remote_enrollment.py
- Check that remote enrollment works when it is enabled in the configuration.
- Check that remote enrollment fails (connection refused) when trying to connect to 1515 socket if it is disabled on configuration.
- Check that logs `Port 1515 was set as disabled` or `Accepting connections on port 1515. No password required.` appear depending on the configuration.
- Add support for cluster worker and master configuration as well as stand-alone server configuration. 
- Manual testing on local environment.

![image](https://user-images.githubusercontent.com/15269938/119505504-529c6c00-bd6d-11eb-8990-f2fddd382b7b.png)
