### ISSUE TITLE
Improving wazuh-db integration tests documentation and comments

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#1346]
### Description

The changes introduced in Wazuh DB integration tests [#1243](https://github.com/wazuh/wazuh-qa/pull/1243) and [#1336](https://github.com/wazuh/wazuh-qa/pull/1336) for the new commands are not fully covered in the documentation. 

It should be added information for:

* Test case for socket connection timeout
* Test cases for agent messages related to the vuln_cves, sys_programs, sys_hotfixes, and sys_osinfo tables.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/1347 was merged.
