### ISSUE TITLE
Add managers ECS deployment in the cluster performance test

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1353]
In order to evaluate the smallest possible wazuh environment, it is necessary to perform deployments using docker on AWS. To do this, the following tasks need to be performed:

- [x] 1. Create dockerfile and entrypoint needed to be able to install wazuh and access via ssh
- [x] 2. Create a new ECSTask that allows us to deploy as many instances as necessary.
- [x] 3. Add the possibility of deploying managers using ECS in the performance test pipeline.
- [x] 4. Add a new parameter in the pipeline UI that allows us to select the type of deployment for EC2 or ECS managers.
- [x] 5. Add a new AWS load balancer of network type.
- [x] 6. Add a load balancer health check before launching the monitoring processes.

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-jenkins/pull/2594
