### ISSUE TITLE
Systems tests automation on Jenkins

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1358]
The system tests are currently executed manually instead of being run by Jenkins in each PR or the nightly tests. 

## Tasks
- [ ] Tests stabilization.
- [ ] Create a new Jenkins pipeline to run these tests.
- [ ] Execute the pipeline automatically: this task can be a bit tricky since the time and resources to run the tests are quite significant compared to the integration tests. It is required to analyze these tests and consider if they must be run with the nightly tests or in specific PR to optimize the costs.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
