### ISSUE TITLE
Integration Tests VD CVEs alerts test and functions review 

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1360]
#### Issue information
| Epic 	| target-branch 	| Wazuh version 	|
|-	|-	|-	|
| https://github.com/wazuh/wazuh-qa/issues/1261  	| dev-8529-vul-det-atomic-query 	| dev-8529-vul-det-atomic-query	|

## Issue definition

In this issue, we will track the process of reviewing the status of integration tests for vulnerability detector on the development branch described above. 

We will try to make queries like those defined in the tests added in this pull request: https://github.com/wazuh/wazuh-qa/pull/1243/files [1] 

Notice that wdb queries accept different kind of 'actors' such as 'agent' or 'global'. See [2] for more info.

#### Test general settings
- [x] test_enabled
![image](https://user-images.githubusercontent.com/15269938/119116081-31afe000-ba28-11eb-9bfe-2021c6ad7ccf.png)
This test work without any problem, no need changes.
- [ ] test_ignore_time
This test uses some functions that must be reviewed to use Wazuh db queries instead of direct SQLite queries to agent db and adapt them to the new fields.
    - [x] vd.clean_vd_tables <- about this point, we were supposed to change all db table modifications to wazuh db queries. Nevertheless, it seems that wazuh db doesn't support cve.db changes yet, so we will keep those queries intact from now and we will upgrade them in the future. This is supposed to be done soon as it is part of this [[3] ](https://github.com/wazuh/wazuh/issues/8315)epic issue.
    - [ ] vd.insert_package
    - [ ] vd.insert_vulnerability
    - [ ] vd.clean_vuln_and_sys_programs_tables
    - [ ] vd.update_last_scan
- [ ] test_interval
- [ ] test_run_on_start

## References

- [1] https://github.com/wazuh/wazuh-qa/pull/1243/files examples of agent Wazuh db queries
- [2] https://github.com/wazuh/wazuh/blob/d944cf154c5aad9bf3f4b8ec2677372e97c0759e/src/wazuh_db/wdb_parser.c wdb parser, here you have examples of different available actors for wazuh db queries.
- [3] https://github.com/wazuh/wazuh/issues/8315 epic mentioning the necessity of add wdb and API queries for cve database.

**Comment by spothound** [comment]
```
def clean_vd_tables(agent="000"):
    """Clean the tables involved with vulnerability detector packages and feeds

    Args:
        agent (str): id of the agent
    """
    tables = [
        {"name": "sys_programs", "path": os.path.join(DB_PATH, f"{agent}.db")},
        {"name": "sys_hotfixes", "path": os.path.join(DB_PATH, f"{agent}.db")},
        {"name": "sys_osinfo", "path": os.path.join(DB_PATH, f"{agent}.db")},
        {"name": "vulnerabilities", "path": CVE_DB_PATH},
        {"name": "vulnerabilities_info", "path": CVE_DB_PATH},
        {"name": "references_info", "path": CVE_DB_PATH},
        {"name": "bugzilla_references_info", "path": CVE_DB_PATH},
        {"name": "advisories_info", "path": CVE_DB_PATH},
        {"name": "metadata", "path": CVE_DB_PATH},
        {"name": "variables", "path": CVE_DB_PATH}
    ]

    # Clean providers and sys_programs tables
    for item in tables:
        try:
            clean_table(item['path'], item['name'])
        except sqlite3.OperationalError:
            pass

    # Clean NVD tables
    for item in NVD_TABLES:
        try:
            clean_table(item['path'], item['name'])
        except sqlite3.OperationalError:
            pass
```

This method uses direct queries to agent dbs to clean data from vd tables. This could be changed to use wazuh db queries like:

```
def clean_agent_table(table, agent='000'):
    query_wdb(f'agent {agent} sql SELECT * FROM {table}')
```

and be simplified into something like:

**Comment by davidjiglesias** [comment]
This issue is obsolete.
