### ISSUE TITLE
Performance tests: add a new option to choose EBS type

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1361]
One of the most important metrics is the disk performance of the different binaries under different conditions. For our test, we can simulate different scenarios and different disks by selecting the volume's type used in the instance.

In our environment, we always deploy instances with 32GB of `gp2` SSD. The objective is to modify our Terraform library to add a new parameter to select the type of the volume used in the instance.

# Tasks
- [ ] Modify the Terraform templates to select one type of volume on-demand.
- [ ] Modify the Jenkins pipeline to select one of the different types: `standard`, `gp2`, `gp3`, `io1`, `io2`, `sc1`, or `st1`.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
