### ISSUE TITLE
Integration test revision for vulnerability detector and Wazuh DB insert/update command.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#1362]
### Description

As part of epic [#8727](https://github.com/wazuh/wazuh/issues/8727) the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. Having said that it is necessary to perform a full revision of the integration tests that affect the behavior of vulnerability detector and Wazuh DB insert/update command.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/1407 was merged.
