### ISSUE TITLE
Fix Vulnerability Detector IT

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1383]
### Description

The following Vulnerability Detector tests are failing in the master branch:

**Tier 0**

- `test_run_on_start`

```
_____________________ test_run_on_start[run_on_start_yes] ______________________
test_vulnerability_detector/test_general_settings/test_general_settings_run_on_start.py:67: in test_run_on_start
    error_message='Could not find vulnerability scan finished log')
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:196: in start
    error_message=error_message).result()
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:456: in start
    raise TimeoutError(error_message)
E   TimeoutError: Could not find vulnerability scan finished log
---------------------------- Captured stderr setup -----------------------------
2021/05/27 13:01:58 wazuh-modulesd[31840] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/05/27 13:01:58 wazuh-modulesd[31840] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/05/27 13:01:58 wazuh-modulesd[31840] wmodules-vuln-detector.c:639 at wm_vuldet_read_provider(): DEBUG: Added nvd feed. Interval: 86400s | Multi path: '/tmp/Test_integration_B4470_20210527175032/t
ests/integration/test_vulnerability_detector/test_general_settings/data/feeds/custom_nvd_feed.json' | Multi url: 'none' | Update since: 2010 | Timeout: 300s
----------------------------- Captured stderr call -----------------------------
2021-05-27 13:02:59,627 - wazuh_testing - ERROR - Could not find vulnerability scan finished log
2021-05-27 13:02:59,627 - wazuh_testing - ERROR - Results accumulated: 0
2021-05-27 13:02:59,627 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:452 Could not find vulnerability scan finished log
ERROR    wazuh_testing:monitoring.py:453 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:455 Results expected: 1
```

**Tier 1**

- `test_invalid_type_url_feeds`

```
---------------------------- Captured stderr setup -----------------------------
2021/05/27 13:31:41 wazuh-modulesd[18000] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/05/27 13:31:41 wazuh-modulesd[18000] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/05/27 13:31:41 wazuh-modulesd[18000] wmodules-vuln-detector.c:639 at wm_vuldet_read_provider(): DEBUG: Added msu feed. Interval: 3600s | Multi path: 'none' | Multi url: 'https://www.customfeed.co
m/feed.jpg' | Update since: 0 | Timeout: 300s
2021/05/27 13:31:41 wazuh-modulesd[18000] wmodules-vuln-detector.c:677 at wm_vuldet_provider_enable(): ERROR: Invalid content 'ARCH_ENABLED' for tag 'enabled' at module 'vulnerability-detector'
----------------------------- Captured stderr call -----------------------------
2021-05-27 13:32:11,592 - wazuh_testing - ERROR - Could not find the log event: ERROR: \(\d+\): CVE database could not be updated.
2021-05-27 13:32:11,592 - wazuh_testing - ERROR - Results accumulated: 0
2021-05-27 13:32:11,593 - wazuh_testing - ERROR - Results expected: 1
```

- `test_arch_linux_vulnerabilities_report`

```
2021/05/27 14:01:59 wazuh-modulesd[9433] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/05/27 14:01:59 wazuh-modulesd[9433] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/05/27 14:01:59 wazuh-modulesd[9433] wmodules-vuln-detector.c:639 at wm_vuldet_read_provider(): DEBUG: Added arch feed. Interval: 3600s | Multi path: '/tmp/Test_integration_B4471_20210527175032/te
sts/integration/test_vulnerability_detector/test_scan_results/data/custom_archlinux_feed.json' | Multi url: 'none' | Update since: 0 | Timeout: 300s
2021/05/27 14:01:59 wazuh-modulesd[9433] wmodules-vuln-detector.c:639 at wm_vuldet_read_provider(): DEBUG: Added nvd feed. Interval: 86400s | Multi path: '/tmp/wazuh-qa/tests/integration/test_vulnerab
ility_detector/test_scan_results/data/custom_nvd_feed.json' | Multi url: 'none' | Update since: 2010 | Timeout: 300s
----------------------------- Captured stderr call -----------------------------
2021-05-27 14:02:39,453 - wazuh_testing - ERROR - The expected number of OVAL vulnerabilities have not been found
2021-05-27 14:02:39,453 - wazuh_testing - ERROR - Results accumulated: 0
2021-05-27 14:02:39,453 - wazuh_testing - ERROR - Results expected: 1
```

We have to find out the cause of these failures and fix them.

**Comment by spothound** [comment]
Regarding to the `test_invalid_type_url_feeds` issue. It is possible that is a performance issue: there is a timeout while waiting for a log to appear and it sometimes could not be enough. Especially if we consider that those tests are being run in vagrant virtual machines on our own server.

This could be probably fixed by increasing the timeout. We have made some tests locally and everything seems to work.

Nevertheless, [we are finishing a development that will allow us to launch the tests in ec2 instances](https://github.com/wazuh/wazuh-qa/issues/1311), improving the performance and avoiding possible problems of overloading the server that hosts the vagrant virtual machines.

We have decided to launch multiple builds of the problematic tests with the development branch of the mentioned issue to check if the tests cause problems in those instances. If the problem disappears that means it is a performance issue on our black mini server and that would explain why the tests only fail sometimes.


https://ci.wazuh.info/view/Tests/job/Test_integration/4637/console
https://ci.wazuh.info/view/Tests/job/Test_integration/4638/console
https://ci.wazuh.info/view/Tests/job/Test_integration/4639/console
https://ci.wazuh.info/view/Tests/job/Test_integration/4640/console
https://ci.wazuh.info/view/Tests/job/Test_integration/4641/console

**Comment by MarcelKemp** [comment]
Updating the comment of my coworker @spothound, after modifying the code to avoid an error with the `ARCH_ENABLED` flag, we have re-launched the tests on EC2 instances (with the timeout set to 60) and it seems to work correctly:

https://ci.wazuh.info/view/Tests/job/Test_integration/4656/console SUCCESS :large_blue_circle: 
https://ci.wazuh.info/view/Tests/job/Test_integration/4657/console SUCCESS :large_blue_circle: 
https://ci.wazuh.info/view/Tests/job/Test_integration/4658/console SUCCESS :large_blue_circle: 
https://ci.wazuh.info/view/Tests/job/Test_integration/4659/console SUCCESS :large_blue_circle: 
https://ci.wazuh.info/view/Tests/job/Test_integration/4660/console SUCCESS :large_blue_circle:

**Comment by MarcelKemp** [comment]
After the fixes, all the tests pass correctly:
- Tier 0:
`=========== 67 passed, 1931 skipped, 1 warning in 703.88s (0:11:43) ============`
- Tier 1:
`==== 289 passed, 1684 skipped, 25 xfailed, 1 warning in 3644.87s (1:00:44) =====`
- Tier 2:
`==== 1593 passed, 383 skipped, 22 xfailed, 1 warning in 15414.25s (4:16:54) ====`
