### ISSUE TITLE
Sanitize tests and code documentation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1404]
## Description

There are multiple errors in repository documentation. These are not critical errors, however, multiple areas of the documentation do not work properly. 

## List of errors

Some of the errors are the following:

- Not included documentation in the navigation menu

![docu error1](https://user-images.githubusercontent.com/11089305/120345073-7118df00-c2fa-11eb-916f-9b23927beedd.png)

- Unexistence documentation sections in the navigation menu

![docu error 2](https://user-images.githubusercontent.com/11089305/120345240-960d5200-c2fa-11eb-87df-8751cfcbea2f.png)

 - No type annotation for parameters

![docu error3](https://user-images.githubusercontent.com/11089305/120345564-dff63800-c2fa-11eb-994c-3cf064849015.png)

- Wrong links

![docu error4](https://user-images.githubusercontent.com/11089305/120345651-f56b6200-c2fa-11eb-8f5e-b1e65d57be2a.png)

- Bad docstrings

![docu error4](https://user-images.githubusercontent.com/11089305/120345651-f56b6200-c2fa-11eb-8f5e-b1e65d57be2a.png)

**Comment by jmv74211** [comment]
Closed in favor of https://github.com/wazuh/wazuh-qa/issues/1536. In this new issue, we will rework the docu to take into account the treatment of all the factors reported in this issue.
