### ISSUE TITLE
Adapt current tools for macos ULS format to create eventchannel log type tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1405]
## Description

Currently, using `authd` and `remoted` simulators we have created some tests for `macos` log format. It should be desirable to investigate if these tools work similarly for eventchannel format for Wazuh Windows agent. 

Using these tools will facilitate the development of new tests for eventchannel log types. Also, it will allow adapting existent tests, like `reconnect_time` test, to check if sent event is correct.

**Comment by damarisg** [comment]
We decided to close them.
