### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector - Rework of the test_scan_results

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1408]
As part of issue #1261, we need to review the status of test_scan_results integration tests for the vulnerability detector and make the required changes in order to adapt them to the new scan workflow.

These tests now must check by running a query to the vuln_cves table if the vulnerability was added to the inventory. These tests must run in a FULL scan scenario.

### Stabilization 
- [x] test_debian_inventory_debian_feed.py
- [x] test_redhat_duplicate_vulns.py
- [x] test_scan_nvd_feed.py
- [x] test_macos_inventory.py
- [x] test_redhat_inventory_redhat_feed.py
- [x] test_scan_providers_and_nvd_feed.py
- [x] test_archliux_inventory_archlinux_feed.py
- [x] test_msu_inventory_msu_feed.py
- [x] test_scan_different_cves.py
- [x] test_ubuntu_inventory_canonical_feed.py

### Addition of checks for vulnerabilities addition to de inventory
- [x] test_debian_inventory_debian_feed.py
- [x] test_redhat_duplicate_vulns.py
- [x] test_scan_nvd_feed.py
- [x] test_macos_inventory.py
- [x] test_redhat_inventory_redhat_feed.py
- [x] test_scan_providers_and_nvd_feed.py
- [x] test_archliux_inventory_archlinux_feed.py
- [x] test_msu_inventory_msu_feed.py
- [x] test_scan_different_cves.py
- [x] test_ubuntu_inventory_canonical_feed.py

**Comment by spothound** [comment]
There seems to be a problem with agent database mocking for tests:

```
2021/06/04 12:38:49 wazuh-modulesd[77202] wdb_agents_helpers.c:37 at wdb_get_agent_sys_osinfo(): ERROR: Agents DB (1) Error querying Wazuh DB to get OS information
```

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/1489 was merged.
