### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector: Test baseline type scans

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1409]
As part of issue #1261, a test should be developed to verify that the `BASELINE` type scan of Vulnerability Detector works correctly. 

This scan type will be triggered the first time after Vulnerability Detector is enabled. It performs a full scan for every single package installed as well as the operating system. As a result, the CVEs inventory will have the information of the vulnerabilities detected but no alerts will be generated.

# Objectives
- [x] Test `BASELINE` scan type. 

# Steeps:
- Simulate the update of the CVEs database to force the scan:
  - To ensure that it is of `BASELINE` type scan, the agent must meet certain requirements:
    - It must have in its `VULN_METADATA` table the `LAST_FULL_SCAN` column with value `0`.
    - It must have at least one package's data in its `SYS_PROGRAMS` table.
    - In its `SYNC_INFO` table, `LAST_COMPLETION >= LAST_ATTEMPT` and `LAST_COMPLETION > 0`. 
- Verify that entries have been created in the CVEs database for the tested agent (`vuln_cves` table).
- Verify that no alerts have been generated for the vulnerabilities detected for the tested agent.

# Planification
- We will use `wazuh_modules.debug` mode 2 to check the vents collected by the module.
- We will use `monitord.rotate_log` mode 0 to disable the log rotation.

**Comment by mdengra** [comment]
## Analysis
The test will consist of configuring the manager to use custom feeds with a vulnerability associated with a test package. This package will be inserted in a simulated agent and, after this, the necessary conditions will be provoked to launch a `BASELINE` scan. 

Once the scan is completed, it will be verified that the vulnerability is added to the CVEs database and that it has not generated any alert.

## Manual testing


## Estimated tasks
- [ ] Develop a fixture that adds a simulated agent and then adds a test package to its database.
- [ ] Develop custom feeds containing a vulnerability for a test package.
- [ ] Try running the test with the corresponding pipeline in Jenkins.
- [ ] Build test documentation.

## 2021/06/02
- I am performing manual tests to study the behavior of `BASELINE` scan.

**Comment by BraulioV** [comment]
closed by #1424
