### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector: Test partial scan type

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1425]
As part of issue #1261, a test should be developed to verify that the `PARTIAL_SCAN` scan type of Vulnerability Detector works correctly. 

When the `BASELINE` scan has been completed, the `PARTIAL_SCAN` is, in general, the one that will be performed most frequently. In this case, only new packages that are installed will be scanned and, if so, the vulnerabilities detected will generate alerts.

# Objectives
- [x] Test `PARTIAL_SCAN` scan type. 

# Steeps:
- Update the CVEs database with offline feeds that are customized for the test packages that will be used. 
- Adding a simulated agent with a test package in its `SYS_PROGRAMS` table to start a `BASELINE` scan.
- When the `BASELINE` scan is complete,
add an additional test package to the agent's `SYS_PROGRAMS` table, this package will have a vulnerability associated with it.
- Wait for the `PARTIAL_SCAN`:
  - To ensure that it is of `PARTIAL_SCAN` type, the agent must meet certain requirements:
    - The feeds must not be updated, or the time set in `min_full_scan_interval` must not have expired.
    - In its `SYNC_INFO` table, `LAST_COMPLETION >= LAST_ATTEMPT` and `LAST_COMPLETION > 0`. 
- Verify that entries have been created in the CVEs database for the tested agent (`vuln_cves` table).
- Verify that alerts have been generated for the vulnerabilities detected for the tested agent.

# Planification
- We will use `wazuh_modules.debug` mode 2 to check the vents collected by the module.
- We will use `monitord.rotate_log` mode 0 to disable the log rotation.

**Comment by mdengra** [comment]
## Analysis
The test will consist of configuring the manager to use custom feeds with a vulnerability associated with a test package. This package will be inserted in a simulated agent and, after this, the necessary conditions will be provoked to launch a `PARTIAL_SCAN` scan type. 

Once the scan is completed, we will verify that the vulnerability is added to the CVEs database and that it has generated alerts. This will be verified by checking the logs and alerts files respectively.

## Manual testing

## Estimated tasks
- [ ] Develop a fixture that adds a simulated agent and then adds a test package to its database.
- [ ] Try running the test with the corresponding pipeline in Jenkins.
- [ ] Build test documentation.

## 2021/06/08
- I am performing manual tests to study the behavior of the `PARTIAL_SCAN` type.

**Comment by BraulioV** [comment]
Closed by #1428
