### ISSUE TITLE
Logcollector integration tests: Tier 2

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#1432]
Hello team,

We need to develop new tests for logcollector daemon to extend the test coverage of non-basic functionality. These tests will be enclosed in tier 2.

Tier 2:
- [ ] Check that option `<only-future-events>yes</only-future-events>` not send content when starting the agent with a localfile bigger than 2GB for Windows 32 and 64 bits.
- [ ] Check that option `<only-future-events>no</only-future-events>` when starting the agent the logs that were written when it was off, with a localfile bigger than 2GB for Windows 32 and 64 bits are sent.

Regards

**Comment by mauromalara** [comment]
Use `test_only_future_events/test_only_future_events.py` as a template:

- [ ] Add more test cases
- [ ] Configure Wazuh using QA-CTL
- [ ] Refactor the test
- [ ] Modify the integration test pipeline to allow the use of Windows (32 bits) agents

**Comment by damarisg** [comment]
We decided to close them.
