### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector: Test full scan type

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1437]
As part of issue #1261, a test should be developed to verify that the `FULL_SCAN` scan type of Vulnerability Detector works correctly. 

In this scan type, every single package installed as well as the operating system are scanned. It runs only when the `BASELINE` scan has been completed, the configured `min_full_scan_interval` expires and the CVEs database is updated with new information. As a result, the newly detected vulnerabilities and the ones that no longer affect the agent will be alerted.

# Objectives
- [x] Test `FULL_SCAN` scan type. 

# Steeps:
- Update the CVEs database with offline feeds that are customized for the test packages that will be used. 
- Adding a simulated agent with two test packages in its SYS_PROGRAMS table to start a BASELINE scan.
- Verify that vulnerabilities have been detected and wait for the `BASELINE` scan to complete.
- Add an additional test package to the agent's `SYS_PROGRAMS` table.
- Update the second package installed on the tested agent to a version not affected by the vulnerability, by modifying the `SYS_PROGRAMS` table (`version` column).
- Wait for the `FULL_SCAN`:
  - To ensure that it is of `FULL_SCAN` type, the agent must meet certain requirements:
    - The feeds must be updated and the time set in `min_full_scan_interval` must not have expired.
    - In its `SYNC_INFO` table, `LAST_COMPLETION >= LAST_ATTEMPT` and `LAST_COMPLETION > 0`. 
- Verify that after the `FULL_SCAN` there are two entries left in the CVEs database for the tested agent (`vuln_cves` table).
- Verify that two alerts have been generated (one for the added vulnerability and another for the removed one) for the tested agent.

# Planification
- We will use `wazuh_modules.debug` mode 2 to check the vents collected by the module.
- We will use `monitord.rotate_log` mode 0 to disable the log rotation.

**Comment by mdengra** [comment]
## Analysis
The test will consist of configuring the manager to use custom feeds with vulnerabilities associated with three test packages. Two packages will be inserted before adding the simulated agent,  so those packages will be scanned during the `BASELINE` scan, its vulnerability will be detected and no alerts will be generated due to this kind of scan.

When the above scan has been performed, an additional package will be inserted and the second package installed on the tested agent will be updated to a non-vulnerable version, then the necessary conditions to launch a `FULL_SCAN` scan will be triggered.

Once the scan is complete, we will verify that two vulnerabilities have been added to the `vuln_cves` table and three alerts have been generated (two for the vulnerabilities detected and one for the vulnerability removed by the update). This will be confirmed by checking the log and alert files respectively.

## Manual testing

## Estimated tasks
- [ ] Develop a fixture that adds a simulated agent and then adds a test package to its database.
- [ ] Try running the test with the corresponding pipeline in Jenkins.
- [ ] Build test documentation.

## 2021/06/10
- I am performing manual tests to study the behavior of the `PARTIAL_SCAN` type.

**Comment by BraulioV** [comment]
Closed by #1440
