### ISSUE TITLE
Fix `test_files/test_audit/test_audit.py` in 4.2

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1441]
## Description

| Related issue |
|--|
| #1516 #1539 |

| Development branch |
|:--:|
| 1441-audit-test-fix |

When it comes to starting with the test fixture, there is some information that can help you:
```
Module: File Integrity Monitoring
Target: Manager and Agent   
OS: Linux
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_fim/test_files/test_audit/test_audit.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed |   [get_configuration1-tags_to_apply0-True] [get_configuration2-tags_to_apply1-False]
| Summary | `test_audit.py` is not checking properly the audisp plugin when audit 3 is installed instead of audit 2
| Error message |  " FileNotFoundError: [Errno 2] No such file or directory: '/etc/audisp/plugins.d/af_wazuh.conf'"

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: The test needs to consider different paths for the plugin.
- [x] Full Green/Yellow in `test_files/test_audit/test_audit.py`. 
- [ ] Merge with `1539-full-yellow-fix-fim-tests`

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1586
