### ISSUE TITLE
Logcollector integration tests T1: Tests wazuh-logcollector.state values

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1446]
Currently, there are tests to ensure that the `wazuh-logcollector.state` file is updated when a monitored file is removed. However, It is necessary to add new tests to ensure all values for `wazuh-logcollector.state` works as expected.

## Tests to create
- [ ] Test location value is updated when a new file is been monitored.
- [ ] Test global and interval keys have defined all monitored files, including command monitoring.
- [ ] Test `events` value is updated correctly.
- [ ] Test `bytes` value is updated correctly.
- [ ] Test `targets` value is updated correctly.
- [ ] Test `only-future-events` value is updated correctly.

**Comment by damarisg** [comment]
We decided to close them.
