### ISSUE TITLE
Add new cases for wildcard integration tests

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1447]
### Description

Hi team, there are already some integration tests that we have created to check some basic cases of wildcards and how they work inside the syscheck directories, here:
https://github.com/wazuh/wazuh-qa/issues/1008
https://github.com/wazuh/wazuh-qa/issues/1263

We want to add some more cases that we have discovered during the development.
For example:
- Test that wildcards work correctly in conjunction with symbolic links.
- Test that wazuh starts correctly if you have only configured some directories with wildcards, which do not expand any paths at the moment. 
- Test that multiple ambiguous configurations (some wildcards and some normal ones) expand the same paths, that they are overwritten correctly, and that when those paths no longer exist, they are deleted from the configuration only if necessary.
- Test that the audit rules are added and removed correctly when the path comes from a wildcard and is removed.
- Check that the fallback to real-time when Audit is not available works with wildcarded directories.

**Comment by damarisg** [comment]
We decided to close them.
