### ISSUE TITLE
Fix `test_files/test_prefilter_cmd/test_prefilter_cmd.py` in 4.2

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1448]
## Description

| Related issue |
|--|
| #1516 #1539 |

| Development branch |
|:--:|
|1448-test-prefilter-cmd-fix|

When it comes to starting with the test fixture, there is some information that can help you:
```
Module: File Integrity Monitoring
Target: Manager and Agent   
OS: Linux
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_fim/test_files/test_prefilter_cmd/test_prefilter_cmd.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed |   [get_configuration0-tags_to_apply0] [get_configuration1-tags_to_apply0]
| Summary | `test_prefilter_cmd.py` is not installing prelink properly
| Error message |  "TimeoutError: Did not receive expected "Folders monitored with real-time engine..." event"

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: The test needs to install prelink correctly and if the installation fails, we need to get an error message.
   We have fixed the test, but we need to consider if we should rework or delete it instead of fix it.
- [x] Full Green/Yellow in `test_files/test_prefilter_cmd/test_prefilter_cmd.py`. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
I am performing tests with CentOS 8 and 7 systems to find the source of this issue. 
In the CentOS 8 version, the `prelink` package is no longer available in the repositories of this distribution, so it is not possible to install it.

In CentOS 7 the `prelink` package is available and is installed correctly by the test, although during the test running, the use case `[get_configuration0-tags_to_apply0]` still produces the described error.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1597

Check PR to read details about the fix.
