### ISSUE TITLE
Addition of detection timestamp, severity, and score to the CVEs alerts inventory for Vulnerability Detector - Vulnerability Detector Integration Tests

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-qa#1461]
### Description 

As part of epic [8727](https://github.com/wazuh/wazuh/issues/8727) the alert's inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. 

These new fields that now are inserted in the vulnerabilities inventory need to be tested inside the `scan_results` tests for Vulnerability Detector.

#### Tests to update

- [x] test_alert_vulnerability_removal
- [x] test_archlinux_inventory_archlinux_feed.py
- [x] test_debian_inventory_debian_feed.py
- [x] test_macos_inventory.py
- [x] test_msu_inventory_msu_feed.py
- [x] test_redhat_inventory_redhat_feed.py
- [x] test_scan_different_cves.py
- [x] test_scan_nvd_feed.py
- [x] test_scan_providers_and_nvd_feed.py
- [x] test_ubuntu_inventory_canonical_feed.py

**Comment by DProvinciani** [comment]
As the epic https://github.com/wazuh/wazuh/issues/8727 is just an enhancement over the epic https://github.com/wazuh/wazuh/issues/7749, we decided to merge all the 8727 related PRs into the 7749 branches and finalize all the remaining QA work over the epic https://github.com/wazuh/wazuh/issues/7749.

Closing the issue.
