### ISSUE TITLE
Logcollector integration tests T1: Tests wazuh-logcollector.state for macos

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#1463]
Hello team !

Tests are needed to ensure that the `wazuh-logcollector.state` file is updated with information from the macOS logs. Although it is not a localfile that collects logs from a file, there should be informed about the events that are collected from the `log stream` command.

- [x] Test to check `wazuh-logcollector.state` contain macOS information without macOS localfile.

Regards

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1476
