### ISSUE TITLE
LogCollector test: Update about check for wazuh-modulesd instead of logcollector.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1467]
The function `SendMSGtoSCKdoes` not belong to `logcollector` module at all the tests should be updated to check for `wazuh-modulesd` instead of `logcollector`.

While executing logcollector test on 5.0, we've detected the problem with the prefix of the log. The test affected are:
- test_location_custom_sockets/test_location_custom_sockets.py
- test_configuration/test_basic_configuration_only_future_events.py
- test_configuration/test_basic_configuration_reconnect_time.py (Windows)

Taking into account the changes being done as part of the process unification work, some tests need to change the module considering the new logging tag: `wazuh-modulesd`.

First, we created this issue to **Core Team** [here](https://github.com/wazuh/wazuh/issues/8927)  with more examples, but it is an issue of **QA-Team**.

## Example of one of the affected tests
To `test_location_custom_sockets/test_location_custom_sockets.py`

On Wazuh 4.3 version execution, the following results can be seen:
![imagen](https://user-images.githubusercontent.com/3978434/122499411-464fab80-cfc7-11eb-9f10-05a1e1768137.png)

On Wazuh 5.0 version execution, the following not expected results were seen:
![imagen](https://user-images.githubusercontent.com/3978434/122499476-63847a00-cfc7-11eb-9544-ef37fb6919b2.png)

## Estimated tasks

- [ ] **1**: Modify module that needs to appear on tests affected.
- [ ] **2**: Testing and debugging process.
- [ ] **3**: Modify test documentation

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
