### ISSUE TITLE
Monitoring tool: Differentiate what values to collect depending on target OS

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1479]
The CICD team has reported that the file descriptor monitor tool does not work properly.

It is used in the stress tests and it is necessary that it works to test de `4.2.0` pre-release packages.

It is requested to check that tool and fix whatever is necessary.

Regards.

**Comment by okynos** [comment]
Hello!

This errors comes from the PSS/USS monitoring changes and Windows agent is the only affected one.
Here I put some screenshots of the FD behaviour among other monitoring values:
## FD
![image](https://user-images.githubusercontent.com/10661307/122723553-64d9cf00-d273-11eb-94ba-137a6a9efcc3.png)

## PSS
![image](https://user-images.githubusercontent.com/10661307/122723603-7327eb00-d273-11eb-8d43-3899177bf2fe.png)

## Write ops (previously working)
![image](https://user-images.githubusercontent.com/10661307/122723683-86d35180-d273-11eb-99b2-ec39614fae0d.png)

## Disk read
![image](https://user-images.githubusercontent.com/10661307/122723760-9b174e80-d273-11eb-98b7-3837533c85c8.png)

## Data CSV
[monitor-winagent-Test_stress_B1438_agent_windows-pre-release.csv](https://github.com/wazuh/wazuh-qa/files/6684879/monitor-winagent-Test_stress_B1438_agent_windows-pre-release.csv)


Regards!

**Comment by jmv74211** [comment]
Hi,

I have been researching this and the main problem was that values not allowed for Windows, such as `PSS` and `SWAP`  (see https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_full_info), were being measured, causing errors in the monitoring.

This has been solved by taking into account the system when obtaining these metrics, so they will only be measured in the case of Linux. Also, data retrieval from wazuh `*.state` statistics files has been fixed for Linux and Windows.

This has caused chain changes in the `graphics_generator`, `monitor` and `stress test` that can be seen in this commit https://github.com/wazuh/wazuh-jenkins/commit/8e830f2becd347cc0b05eee9357014fcf81a4041

**Comment by snaow** [comment]
Locally tested. Working properly. 
Pending @wazuh/cicd to confirm that it works on Jenkins before closing.

**Comment by alberpilot** [comment]
It works. Thanks team.
