### ISSUE TITLE
Logcollector integration tests T0 macos: active-configuration

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1482]
### Issue information
|QA base branch 	| Wazuh branch 	|
|-	|-	|
|  1482-active-conf-logcollector-it	|  4572-dev-uls-logs-enhancement |

This test needs to check correct active-configuration retrieving. 

The active configuration test has been developed in the 1329_test_active-configuration branch.

The current state of this test will ensure that the location and log_format fields received by active configuration correspond to the Wazuh agent/manager real configuration. In ULS log_format case, only check the log_fomat field due to this format does not require a file value.

In addition, it is necessary to add the documentation for this test

[ Time estimation: 2 hours]

**Comment by spothound** [comment]
## 06/22/21

Today we've reviewed the status of this issue (branch left by Victor before going on vacation) and have been testing everything and discussing with the core team in a meet.

- We've added a test for `ignore_binaries`
- We've made some minor changes to macOS `only-future-events `
- We've made some fixes for the `active-configuration` test.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1505/files
