### ISSUE TITLE
Addition of detection timestamp, severity, and score to the CVEs alerts inventory for Vulnerability Detector - Wazuh DB Integration Tests

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#1497]
As part of the epic [#8727](https://github.com/wazuh/wazuh/issues/8727),  we added the following fields into the CVEs alerts inventory as an improvement to include more information that would be relevant for the users:

- timestamp of the vulnerability first detection.
- Vulnerability severity.
- Vulnerability score v2 (cvss2).
- Vulnerability score v3 (cvss3).

This required the revision of Wazuh DB commands already implemented as part of [#7749](https://github.com/wazuh/wazuh/issues/7749).

This is a tracking purposes issue to reflect the changes needed for the Wazuh DB commands as part of the issue [#1362](https://github.com/wazuh/wazuh-qa/issues/1362)

**Comment by DProvinciani** [comment]
As the epic https://github.com/wazuh/wazuh/issues/8727 is just an enhancement over the epic https://github.com/wazuh/wazuh/issues/7749, we decided to merge all the 8727 related PRs into the 7749 branches and finalize all the remaining QA work over the epic https://github.com/wazuh/wazuh/issues/7749.

Closing the issue.
