### ISSUE TITLE
Integration tests for Vulnerability Detector: SUSE support dependencies

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1526]
### Description

The goal of this issue is to add the tests that cover the use case described at https://github.com/wazuh/wazuh/issues/9091 to the SUSE integration tests created at https://github.com/wazuh/wazuh-qa/issues/1249.

### Tests to create

- [ ] Parse a custom feed where dependencies are satisfied -> trigger an alert
- [ ] Parse a custom feed where dependencies are **not** satisfied -> no alert is triggered

**Comment by juanmanuelug** [comment]
### TO DO LIST
---

For `SLES 11, 12, 15` and `SLED 11, 12, 15`:

- [ ] Modify `test_scan_result data` for SUSE to add dependencies for each package.
- [ ] Modify `custom feed SUSE` to add the full trace of the CVE

We're working with the core development branch: https://github.com/wazuh/wazuh/tree/9091-suse-dependencies
QA branch: `1526-vd-suse-deps`

**Comment by chemamartinez** [comment]
Before retaking this issue we have to talk to the core Bugman team (@palaciosjeremias, @DProvinciani, @MiguelazoDS, and @pereyra-m) who implemented tests to detect discarded vulnerabilities in other development.
