### ISSUE TITLE
Full Yellow Local - Fix WPK tests in 4.2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1528]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1516. After the research #1493, it has been detected errors in `wpk` tests for Wazuh manager and agents in Linux and Windows systems. In order to sanitize current tests is necessary to fix wpk tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Execution Results

| **Linux manager**  |  **Local** | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|:--:|
|**Test Execution 1**|  [Results](https://github.com/wazuh/wazuh-qa/files/6753267/r1_wpk_manager_1.log)   | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/892/)   |  🔴
|**Test Execution 2**|  [Results](https://github.com/wazuh/wazuh-qa/files/6753270/r2_wpk_manager.log)  |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/928/)  |  🔴
|**Test Execution 3**|  [Results](https://github.com/wazuh/wazuh-qa/files/6753274/r3_wpk_manager.log) |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/963/)  |  🔴

| **Linux agent**  |  **Local** | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|:--:|
|**Test Execution 1**|   [Results](https://github.com/wazuh/wazuh-qa/files/6753265/r1_wpk_agent_linux.log)  |  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/891/) |  🔴
|**Test Execution 2**|  [Results](https://github.com/wazuh/wazuh-qa/files/6753269/r2_wpk_agent_linux.log)   | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/931/)  |  🔴
|**Test Execution 3**|   [Results](https://github.com/wazuh/wazuh-qa/files/6753273/r3_wpk_agent_linux.log)   | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/964/)  |  🔴

| **Windows Agent**  |  **Local** |   **Jenkins**  |   **Status** 
|:--:|:--: |:--:|:--:|
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/6753268/r1_wpk_windows.log) | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/891/)  | 🔴 | 
|**Test Execution 2**| [Results](https://github.com/wazuh/wazuh-qa/files/6753271/r2_wpk_windows.log) |  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/931/)  | 🔴 |
|**Test Execution 3**| [Results](https://github.com/wazuh/wazuh-qa/files/6753276/r3_wpk_windows.log) | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/964/)   | 🔴 |   

### Development

This fix should be developed in a branch from 4.2, and it must be merged in the epic issue full-green branch `1516-4.2.0-full-green`

In order to finish this issue the following tasks should be fulfilled:

- [x] Fix `wpk` integration tests

   - **Linux manager**
     - [x] test_wpk_manager:
     - [x] test_wpk_manager_task_states
 
  - **Linux agent**
     - [x] test_wpk_agent

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_agent.py
| Consistent | Yes 
| Test Execution | 1/3 executions failed
| Cases |   get_configuration1
| Cases Fails | 1
| Summary |  Expected error does not match. Could not chmod is received.
| Error message |  "AssertionError: Expected error message does not match"
```
E           AssertionError: Expected error message does not match
E           assert '{"error":17,...d","data":[]}' == 'Could not chmod'
E             - Could not chmod
E             + {"error":17,"message":"Could not chmod","data":[]}
```
<hr>

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_agent.py
| Consistent | Yes 
| Test Execution | 1/3 executions failed
| Cases |   get_configuration0
| Cases Fails | 1
| Summary |  upgrade_exec_message has not expected length
| Error message |  "IndexError: list index out of range"

```
        if upgrade_process_result:
            upgrade_result_code = None
            if expected['result_code'] == 0 and _agent_version == version_to_upgrade:
                exp_json = json.loads(upgrade_exec_message)
                upgrade_result_code = int(exp_json['message'])
            else:
>               upgrade_result_code = int(upgrade_exec_message.split(' ')[1])
E               IndexError: list index out of range

```

  - **Windows agent**
     - [ ] test_wpk_agent

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_agent.py
| Consistent | Yes 
| Test Execution | 1/3 executions failed
| Cases |   get_configuration0
| Cases Fails | 1
| Summary |  Upgrade process result was not the expected
| Error message | AssertionError

```   
        upgrade_process_result, upgrade_exec_message = \
            remoted_simulator.wait_upgrade_process(timeout=240)
>       assert upgrade_process_result == expected['upgrade_ok'], \
               'Upgrade process result was not the expected'
E       AssertionError: Upgrade process result was not the expected
E       assert False == True
E         +False
E         -True
```

<hr>

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_agent.py
| Consistent | Yes 
| Test Execution | 1/3 executions failed
| Cases |   get_configuration1
| Cases Fails | 1
| Summary |  Expected error message does not match
| Error message | AssertionError

```
        if upgrade_process_result:
            upgrade_result_code = None
            if expected['result_code'] == 0 and _agent_version == version_to_upgrade:
                exp_json = json.loads(upgrade_exec_message)
                upgrade_result_code = int(exp_json['message'])
            else:
                upgrade_result_code = int(upgrade_exec_message.split(' ')[1])
            assert upgrade_result_code == expected['result_code'], \
                   f'Expected upgrade result code was {expected["result_code"]} ' \
                   f'but obtained {upgrade_result_code} instead'
        else:
            if _agent_version == version_to_upgrade and not metadata['simulate_interruption']:
                exp_json = json.loads(upgrade_exec_message)
                upgrade_exec_message = str(exp_json['message'])
>           assert upgrade_exec_message == expected['error_message'], \
                   f'Expected error message does not match'
E           AssertionError: Expected error message does not match
E           assert None == 'Error executing command'
E             +None
E             -'Error executing command'
```

<hr>

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_agent.py
| Consistent | No 
| Test Execution | 1/3 executions failed
| Cases |   get_configuration2
| Cases Fails | 1
| Summary |  Expected error message does not match. Expected Request configuration never arrived but None is received
| Error message | AssertionError

```
            if _agent_version == version_to_upgrade and not metadata['simulate_interruption']:
                exp_json = json.loads(upgrade_exec_message)
                upgrade_exec_message = str(exp_json['message'])
>           assert upgrade_exec_message == expected['error_message'], \
                   f'Expected error message does not match'
E           AssertionError: Expected error message does not match
E           assert None == 'Request conf...never arrived'
E             +None
E             -'Request confirmation never arrived'

test_wpk\test_wpk_agent.py:359: AssertionError
```

  - **General errors**
    - [x] Error in socket managing
   
|  Type | Description  |
|--|--|
|Test Path | test_feeds/test_download_feeds
| Consistent | No 
| Test Execution | 2/3 executions failed
| Cases |   Any
| Cases Fails | None, probably related to other fails in WPK tests
| Summary | 
| Error message |  "BrokenPipeError: [Errno 32] Broken pipe"
   
 ```
Traceback (most recent call last):
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 1488, in send_event
    self.socket.send(length + event)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 1666, in run
    self.run_module(self.module)
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 1647, in run_module
    self.sender.send_event(event)
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 1493, in send_event
    self.socket.connect((self.manager_address, int(self.manager_port)))
ConnectionRefusedError: [Errno 111] Connection refused

Exception in thread Thread-170receive_messages:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 1664, in run
    self.agent.receive_message(self.sender)
  File "/home/vagrant/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py", line 398, in receive_message
    rcv = sender.socket.recv(4)
OSError: [Errno 107] Transport endpoint is not connected
```
 

- [x] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `1516-4.2.0-full-green`

**Comment by Rebits** [comment]
## 07/07/2021

After fixing some errors in tests provision We obtained the following errors:

### Test WPK manager

New error appears, It looks like a minor error in callback creation

```
>               assert expected_status[index] == response['data'][0]['status'], \
                    f'Upgrade status did not match expected! ' \
                    f'Expected {expected_status[index]} obtained {response["data"][0]["status"]} at index {index}'
E               AssertionError: Upgrade status did not match expected! Expected Legacy upgrade:check the result manually since the agent cannot report the result of the task obtained Legacy upgrade: check the result manually since the agent cannot report the result of the task at index 0
E               assert 'Legacy upgra...t of the task' == 'Legacy upgra...t of the task'
E                 - Legacy upgrade: check the result manually since the agent cannot report the result of the task
E                 ?                -
E                 + Legacy upgrade:check the result manually since the agent cannot report the result of the task

test_wpk/test_wpk_manager.py:1048: AssertionError
======================================= short test summary info ========================================
FAILED test_wpk/test_wpk_manager.py::test_wpk_manager[get_configuration12] - AssertionError: Upgrade ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 1 failed, 12 passed in 1229.22s (0:20:29) ===============================
```

### Test WPK agent (centos)

This error appears in the last case of the test wpk agent. Notification was expected but was not received.

```
        if upgrade_process_result and expected['receive_notification']:
            result = remoted_simulator.wait_upgrade_notification(timeout=180)
            if result is not None:
                status = result['status']
                assert status == expected['status'], \
                       'Notification status did not match expected'
            else:
>               assert not expected['receive_notification'], \
                       'Notification was expected but was not received'
E               AssertionError: Notification was expected but was not received
E               assert not True

test_wpk/test_wpk_agent.py:370: AssertionError
============================================================================================= short test summary info =============================================================================================
FAILED test_wpk/test_wpk_agent.py::test_wpk_agent[get_configuration3] - AssertionError: Notification was expected but was not received
```

**Comment by Rebits** [comment]
### Update 08/07/2021

#### Manager

After change some minor error in `test_wpk_manager`, this test fail in the following cases:
- [ ] Case get_configuration8
- [ ] Case get_configuration10
- [ ] Case get_configuration11

```
--------------- Captured log setup ----------------
WARNING  root:agent_simulator.py:1489 Broken Pipe error while sending event. Creating new socket...
WARNING  root:agent_simulator.py:1489 Broken Pipe error while sending event. Creating new socket...
============= short test summary info =============
FAILED test_wpk/test_wpk_manager.py::test_wpk_manager[get_configuration8]
FAILED test_wpk/test_wpk_manager.py::test_wpk_manager[get_configuration10]
FAILED test_wpk/test_wpk_manager.py::test_wpk_manager[get_configuration11]
==== 3 failed, 25 passed in 3748.01s (1:02:28) ====
```
#### Agent

##### Linux

There were errors in message formatting in `test_agents_wpk`. After fixing this issue, these tests fail in the following cases:
- [ ] Case `get_configuration3`

##### Windows

Pending fixes in Windows agents.

**Comment by Rebits** [comment]
### Update 15/07/2021

- [x] Linux agent 
WPK tests for Linux agent present some errors in the  `agent_version == version_to_upgrade` case. Upgrade listener of remoted simulator uses a timeout with harcoded value of 100. In this tests case, the agent should rollup when after restarts check that it has no connection with the manager. This time is variable so in order to fix this false positive case, the test now ensure upgrade results using logs provided by the agent.

- [x] Linux WPK manager
After fixing some socket response parser these tests works correctly

- [ ] Windows WPK agent
A misconfigured client.keys caused that agent neve connect properly to remote. This have been solved, but new error log appears in every test cases:

```
2021/07/15 13:18:48 wazuh-agent[2544] receiver-win.c:128 at receiver_thread(): DEBUG: Received message: '#!-req 385 upgrade {"command": "upgrade", "parameters": {"file": "wazuh_agent_v4.2.0_windows.wpk", "installer": "upgrade.bat"}}'
2021/07/15 13:18:48 wazuh-agent[2544] signature.c:72 at w_wpk_unsign(): WARNING: No root CA defined to verify file 'incoming\wazuh_agent_v4.2.0_windows.wpk'.
2021/07/15 13:18:48 wazuh-modulesd:agent-upgrade[2544] wm_agent_upgrade_com.c:351 at wm_agent_upgrade_com_upgrade(): ERROR: (8131): At upgrade: 'Could not clean up upgrade directory'
```
 
Further investigation is required

**Comment by Rebits** [comment]
### Update 15/07/2021

WPK test for Windows agent, failed gathering client. keys and it has minor errors. Now it works correctly. This fix has been developed in `1528-full-green-wpk-agent-manager-fix` branch. Pending further testing in order to ensure this test works properly again.

**Comment by Rebits** [comment]
### Update 27/07/2021

After some testing using https://github.com/wazuh/wazuh-qa/pull/1614 fix, it has been detected an error in `test_wpk_manager`:

```
Module: WPK
Target: Manager   
OS: Linux
```

|  Type | Description  |
|--|--|
|Test Path | test_wpk/test_wpk_manager.py
| Consistent | No
| Test Execution | 1/3 failed
| Cases Failed | [get_configuration3]
| Summary | Send lock restart error
| Error message |  Send lock restart error

**Comment by Rebits** [comment]
There is a false positive case for `get_configuration3`, multiple agents case.
If the environment is not properly clean it could produce the following error message:
```
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_manager.c:149 at wm_agent_upgrade_listen_messages(): DEBUG: (8155): Incomming message: '{"command":"upgrade_update_status","parameters":{"error":2,"message":"Upgrade failed","status":"Failed","agents":[80]}}'
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_commands.c:187 at wm_agent_upgrade_process_agent_result_command(): INFO: (8164): Received upgrade notification from agent '80'. Error code: '2', message: 'Upgrade failed'
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_tasks.c:211 at wm_agent_send_task_information_master(): DEBUG: (8157): Sending message to task_manager module: '{"origin":{"name":"node01","module":"upgrade_module"},"command":"upgrade_update_status","parameters":{"agents":[80],"status":"Failed","error_msg":"Upgrade procedure exited with error code"}}'
2021/07/29 12:50:11 wazuh-modulesd:task-manager[145689] wm_task_manager.c:47 at wm_task_manager_dispatch(): DEBUG: (8204): Incomming message: '{"origin":{"name":"node01","module":"upgrade_module"},"command":"upgrade_update_status","parameters":{"agents":[80],"status":"Failed","error_msg":"Upgrade procedure exited with error code"}}'
2021/07/29 12:50:11 wazuh-modulesd:task-manager[145689] wm_task_manager.c:89 at wm_task_manager_dispatch(): DEBUG: (8205): Response to message: '{"error":0,"data":[{"error":0,"message":"Success","agent":80}],"message":"Success"}'
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_tasks.c:229 at wm_agent_send_task_information_master(): DEBUG: (8158): Receiving message from task_manager module: '{"error":0,"data":[{"error":0,"message":"Success","agent":80}],"message":"Success"}'
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_upgrades.c:612 at wm_agent_upgrade_send_command_to_agent(): DEBUG: (8165): Sending message to agent: '080 upgrade {"command":"clear_upgrade_result","parameters":{}}'
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_upgrades.c:625 at wm_agent_upgrade_send_command_to_agent(): DEBUG: (8166): Receiving message from agent: 'ok '
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_parsing.c:488 at wm_agent_upgrade_parse_agent_upgrade_command_response(): ERROR: (8117): Unknown error from agent.
2021/07/29 12:50:11 wazuh-modulesd:agent-upgrade[145689] wm_agent_upgrade_manager.c:196 at wm_agent_upgrade_listen_messages(): DEBUG: (8156): Response message: '{"error":0,"data":[{"error":0,"message":"Success","agent":80}],"message":"Success"}'
2021/07/29 12:50:26 wazuh-modulesd:task-manager[145689] wm_task_manager.c:47 at wm_task_manager_dispatch(): DEBUG: (8204): Incomming message: '{"origin": {"module": "api"}, "command": "upgrade_result", "parameters": {"agents": [80]}}'
2021/07/29 12:50:26 wazuh-modulesd:task-manager[145689] wm_task_manager.c:89 at wm_task_manager_dispatch(): DEBUG: (8205): Response to message: '{"error":0,"data":[{"error":0,"message":"Success","agent":80,"task_id":74,"node":"node01","module":"upgrade_module","command":"upgrade","status":"Error","error_msg":"Upgrade procedure exited with error code","create_time":"2021/07/29 12:49:56","update_time":"2021/07/29 
```

**Comment by snaow** [comment]
Closd by https://github.com/wazuh/wazuh-qa/pull/1614
