### ISSUE TITLE
Full Yellow Local - Fix GCloud tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1532]
## Description

This issue found while working on [Research: Check the integration tests status in 4.2.0-RC8](https://github.com/wazuh/wazuh-qa/issues/1493). We detect that GCloud Tests aren't working successfully.
It's required to investigate the root cause of each Failed. 

### Test Execution - Results

| Manager  |  **Local** | **Jenkins**  |  **Status**|
|:--:|:--: |:--:|:--:|
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/6750323/Test_gcloud_r1.log)| https://devel.ci.wazuh.info/view/Tests/job/Test_integration/876/  |    🔴  | 
|**Test Execution 2**| [Results](https://github.com/wazuh/wazuh-qa/files/6750379/Test_gcloud_r2.log)| https://devel.ci.wazuh.info/view/Tests/job/Test_integration/918/  |    🔴  | 
|**Test Execution 3**| [Results](https://github.com/wazuh/wazuh-qa/files/6750395/Test_gcloud_r3.log) | https://devel.ci.wazuh.info/view/Tests/job/Test_integration/950/ |    🔴  | 

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
analysisd.debug=2
wazuh_modules.debug=2
monitord.rotate_log=0  
```

## Development 

In order to finish this issue the following tasks should be fulfilled:

- [x] Fix `GCloud` integration tests.
  - [x] Fix `test_configuration/test_invalid` for cases:
       - [x] `get_configuration15`
       - [x] `get_configuration16`
       - [x] `get_configuration19`       
       - [x] `get_configuration20`
       - [x] `get_configuration21`             
       - [x] `get_configuration22`
       - [x] `get_configuration23`
       - [x] `get_configuration24`       
       - [x] `get_configuration25`
       
   <hr>

  - [x] Fix `test_functioning/test_day_wday` for cases:
       - [x] `get_configuration0-tags_to_apply0`
       - [x] `get_configuration1-tags_to_apply1`
       - [x] `get_configuration2-tags_to_apply2`

|  Type | Description  |
|--|--|
|Test Path | test_gcloud/test_functioning/test_day_wday.py
| Consistent | Yes 
| Test Execution | 3/3 executions failed
| Cases |   get_configuration0-tags_to_apply0, get_configuration1-tags_to_apply1, get_configuration2-tags_to_apply2
| Cases Fails | 3
| Summary |  Did not receive expected "Starting fetching of logs" event
| Error message |  Timeout
```
        wazuh_log_monitor.start(timeout=global_parameters.default_timeout + 120,
                                callback=callback_detect_start_fetching_logs,
                                accum_results=1,
                               error_message='Did not receive expected '
                                              '"Starting fetching of logs" event').result()
```
<hr>

  - [x] Fix `test_functioning/test_max_messages` for cases:
       - [x] `get_configuration0-30`
       - [x] `get_configuration0-100`
       - [x] `get_configuration0-120`

|  Type | Description  |
|--|--|
|Test Path | test_gcloud/test_functioning/test_max_messages.py
| Consistent | Yes 
| Test Execution | 3/3 executions failed
| Cases |   get_configuration0-30, get_configuration0-100, get_configuration0-120
| Cases Fails | 3
| Summary |  Did not receive expected - INFO - Received and acknowledged x messages
| Error message |  Timeout

```
        if nmessages <= max_messages:
            number_pulled = wazuh_log_monitor.start(timeout=global_parameters.default_timeout + time_interval + 5,
                                                    callback=callback_received_messages_number,
                                                    accum_results=1,
                                                  error_message='Did not receive expected - INFO - Received and acknowledged x messages').result()
```

<hr>

  - [x] Fix `test_functioning/test_rules` for cases:
       - [x] `get_configuration0`

|  Type | Description  |
|--|--|
|Test Path | test_gcloud/test_functioning/test_rules.py
| Consistent | Yes 
| Test Execution | 3/3 executions failed
| Cases |   get_configuration0
| Cases Fails | 1
| Summary |  "Resource not found (resource=wazuh-pubsub).","grpc_status":5}"
| Error message |  google.api_core.exceptions.NotFound: 404 Resource not found (resource=wazuh-pubsub).
```
	status = StatusCode.NOT_FOUND
	details = "Resource not found (resource=wazuh-pubsub)."
	debug_error_string = "{"created":"@1626085199.275600532","description":"Error received from peer ipv4:142.250.201.74:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Resource not found (resource=wazuh-pubsub).","grpc_status":5}"
```

- [x] Full Yellow in `GCloud` tests for Manager.
- [x] Documentation of any important change done for these tests or the used tools.
- [ ] Merge with `1516-4.2.0-full-green`.

**Comment by Rebits** [comment]
### Update 08/07/2021


## Research about gcloud tests
Tras un proceso de investigación, se ha determinado que no se lanzaron todos los tests de gcloud. Tras un breve análisis podemos determinar que el estado acutal de los tests es el siguiente:
- [ ] test_day_wday
   - [ ] Case get_configuration0-tags_to_apply0
   - [ ] Case get_configuration1-tags_to_apply1
   - [ ] Case get_configuration2-tags_to_apply1
- [ ] test_max_messages:
   - [ ] Case get_configuration0-30
   - [ ] Case get_configuration0-100
   - [ ] Case get_configuration0-120
```
FAILED test_gcloud/test_functioning/test_day_wday.py::test_day_wday[get_configuration0-tags_to_apply0]
FAILED test_gcloud/test_functioning/test_day_wday.py::test_day_wday[get_configuration1-tags_to_apply1]
FAILED test_gcloud/test_functioning/test_day_wday.py::test_day_wday[get_configuration2-tags_to_apply2]
FAILED test_gcloud/test_functioning/test_max_messages.py::test_max_messages[get_configuration0-30]
FAILED test_gcloud/test_functioning/test_max_messages.py::test_max_messages[get_configuration0-100]
FAILED test_gcloud/test_functioning/test_max_messages.py::test_max_messages[get_configuration0-120]
[root@centos3 integration]# 
============ 7 failed, 51 passed, 30 skipped in 3926.06s (1:05:26) ============
```

## Fixed tests
Some minor errors have been solved in tests_invalid tests. Now, these tests run without errors.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1621
