### ISSUE TITLE
Full-Green - Delete Cluster tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1538]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1516. After the research #1493, it has been detected that `cluster` tests are being skipped. In order to sanitize current tests is necessary to fix `cluster` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Execution Results

| **Linux Agent**  |  **Local** | **Jenkins**  |  
|:--:|:--: |:--:|
|**Test Execution 1**|  [Results](https://github.com/wazuh/wazuh-qa/files/6746941/test_agentd_r1.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/868/)   |  
|**Test Execution 2**|  [Results](https://github.com/wazuh/wazuh-qa/files/6746944/test_agentd_r2.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/909/)   |  
|**Test Execution 3**|  [Results](https://github.com/wazuh/wazuh-qa/files/6746947/test_agentd_r3.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/942/)  |  

| **Windows Agent**  |  **Local** |   **Jenkins**  |   
|:--:|:--: |:--:|
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/6742237/test_cluster_r1.log) | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/872/)   |
|**Test Execution 2**| [Results](https://github.com/wazuh/wazuh-qa/files/6742206/test_cluster_r2.log) | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/913/)   |
|**Test Execution 3**| [Results](https://github.com/wazuh/wazuh-qa/files/6742149/test_cluster_r3.log) | [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/946/)  | 

## Development

These tests are being skipped because of issue https://github.com/wazuh/wazuh/issues/4387. This issue has been closed and updated in issue https://github.com/wazuh/wazuh/issues/9092, that still in progress. We need to delete the `cluster` tests from `4.2` because the features that need to be testest aren't finished. When the development is done, we will create new ones.

- [x] Delete `cluster` tests
- [x] Delete `cluster` tests documentation

**Comment by snaow** [comment]
LGTM. Closed by: https://github.com/wazuh/wazuh-qa/pull/1540
