### ISSUE TITLE
Full Yellow Local - Fix FIM tests in 4.2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1539]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1516. After the research #1493, it has been detected fails in `FIM` tests for Wazuh manager and agents. In order to sanitize current tests is necessary to fix `FIM` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi
Agent | macOS | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.pkg
Agent | solaris | i386 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent_v4.2.0-1.1493-sol11-i386.p5p

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`
### Test Execution - Results

|   |  **Local** | **Jenkins**  |  **Status**|
|:--:|:--: |:--:|:--:|
|**Test Execution 1**| [Linux-Manager](https://github.com/wazuh/wazuh-qa/files/6755610/r1_fim_linux_manager.log), [Linux-Agent](https://github.com/wazuh/wazuh-qa/files/6755618/r1_linux_agent_fim.log), [Windows-Agent](https://github.com/wazuh/wazuh-qa/files/6770512/test_fim_win_r1.log),  [Solaris-Agent](https://github.com/wazuh/wazuh-qa/files/6755617/r1_fim_solaris.log), [macOS-Agent](https://github.com/wazuh/wazuh-qa/files/6755614/r1_fim_macos.log)|  [Build-Manager](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/873/), [Build-Linux-Agent](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/874/), [Build-Linux-macOS/Solaris](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/875/), [Build-Windows](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/874/)  |  🔴 |
|**Test Execution 2**| [Linux-Manager](https://github.com/wazuh/wazuh-qa/files/6755612/r2_fim_linux_manager.log),[Linux-Agent](https://github.com/wazuh/wazuh-qa/files/6755619/r2_linux_agent_fim.log), [Windows-Agent](https://github.com/wazuh/wazuh-qa/files/6770520/test_fim_win_r2.log), [Solaris-Agent](https://github.com/wazuh/wazuh-qa/files/6755621/r2_fim_solaris.log), [macOS-Agent](https://github.com/wazuh/wazuh-qa/files/6755620/r2_fim_macos.log)|  [Build-Manager](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/914/), [Build-Linux-Agent](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/916/), [Build-Linux-macOS/Solaris](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/917/), [Build-Windows](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/916/)  |  🔴 | 
|**Test Execution 3**| [Linux-Manager](https://github.com/wazuh/wazuh-qa/files/6755615/r3_fim_linux_manager.log), [Linux-Agent](https://github.com/wazuh/wazuh-qa/files/6755622/r3_linux_agent_fim.log), [Windows-Agent](https://github.com/wazuh/wazuh-qa/files/6770523/test_fim_win_r3.log), [Solaris-Agent](https://github.com/wazuh/wazuh-qa/files/6755625/r3_fim_solaris.log), [macOS-Agent](https://github.com/wazuh/wazuh-qa/files/6755623/r3_fim_macos.log)|  [Build-Manager](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/947/), [Build-Linux-Agent](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/948/), [Build-Linux-macOS/Solaris](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/965/), [Build-Windows](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/948/)  |  🔴 | 

### Development

This fix should be developed in a branch from 4.2, and it must be merged in the epic issue full-green branch `1516-4.2.0-full-green`

In order to finish this issue the following tasks should be fulfilled:

#### Linux 
  - [x] https://github.com/wazuh/wazuh-qa/issues/1441
  - [x] https://github.com/wazuh/wazuh-qa/issues/1582
  - [x] https://github.com/wazuh/wazuh-qa/issues/1448
  - [x] `test_fim/test_files/test_ambiguous_confs/test_ambiguous_complex.py` **False positive**
  - [x]  https://github.com/wazuh/wazuh-qa/issues/1648
 
    We have launched these tests three times in Jenkins and more than three times in two different local environments and the tests passed.
    > test_fim/test_files/test_ambiguous_confs/test_ambiguous_complex.py::test_ambiguous_complex[get_configuration0-tags_to_apply0]

#### Windows 

  - [ ] https://github.com/wazuh/wazuh-qa/issues/1593
  - [x]  https://github.com/wazuh/wazuh-qa/issues/1648
  
Tests in Windows are failing randomly. The main problem is that `control_service` is failing due to the OS. When executing `net stop WazuhSvc` we got two types of messages:

```
System error 109 has occurred.
The pipe has been ended.
```

```
The service is not responding to the control function.
More help is available by typing NET HELPMSG 2186.
```

**PRs merged**

- https://github.com/wazuh/wazuh-qa/pull/1752
- https://github.com/wazuh/wazuh-qa/pull/1669
- https://github.com/wazuh/wazuh-qa/pull/1597
- https://github.com/wazuh/wazuh-qa/pull/1646
- https://github.com/wazuh/wazuh-qa/pull/1670
- https://github.com/wazuh/wazuh-qa/pull/1661
- https://github.com/wazuh/wazuh-qa/pull/1667
- https://github.com/wazuh/wazuh-qa/pull/1667
     
- [x] Full yellow local in each test
- [x] Documentation of any important change done for these tests or the used tools
- [x] Merge with `1516-4.2.0-full-green`

**Comment by fernandolojano** [comment]
FIM tests results for Windows Agent

||Windows Agent |Reports|
|:--:|:--:|:--:|
|R1|  :red_circle:   | [Tests results](https://github.com/wazuh/wazuh-qa/files/6929469/r1_fim_fernando.zip)
|R2|  :red_circle:   | [Tests results](https://github.com/wazuh/wazuh-qa/files/6929470/r2_fim_fernando.zip)
|R3|  :red_circle:   | [Tests results](https://github.com/wazuh/wazuh-qa/files/6929471/r3_fim_fernando.zip)

**Comment by fernandolojano** [comment]
FIM test results for CentOS Manager

||CentOS Manager |Reports|
|:--:|:--:|:--:|
|R1|  :green_circle:   | [Tests results](https://github.com/wazuh/wazuh-qa/files/6936677/r1_fim_manager_fernando.zip)

**Comment by fernandolojano** [comment]
FIM test results for CentOS Agent

||CentOS Agent |Reports|
|:--:|:--:|:--:|
|R1|  :red_circle:   | [Tests results](https://github.com/wazuh/wazuh-qa/files/6936708/r1_fim_agent_fernando.zip)

**Comment by juliamagan** [comment]
> FIM test results for CentOS Agent
> 
> CentOS Agent	Reports
> R1	🔴	[Tests results](https://github.com/wazuh/wazuh-qa/files/6936708/r1_fim_agent_fernando.zip)

After ten rounds, I wasn't able to reproduce this error.

||R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|Reports|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|CentOS 8 Agent| 🟢 |🟢|🟢|🟢|🟢|🟢|🟢|🟢|🟢|🟢|[Test results](https://github.com/wazuh/wazuh-qa/files/6938390/centos_agent_test_disk_quiota_disabled.zip)|

**Comment by juliamagan** [comment]
I'll be launching three rounds of complete FIM tests in a CentOS 8 agent:

||CentOS8 Agent|Reports|
|:--:|:--:|:--:|
|R1| 🟢 | [Tests results](https://github.com/wazuh/wazuh-qa/files/6943556/centos_agent_test_fim_r1.zip)|
|R2| 🔴 |[Tests results](https://github.com/wazuh/wazuh-qa/files/6943564/centos_agent_test_fim_r2.zip)|
|R3| 🔵 ||

**Comment by juliamagan** [comment]
The following tests were launched with everything disabled.

**Comment by juliamagan** [comment]
|  | Windows Agent | More info |
|:--:|:--:|:--:|
|R1| [🟢](https://github.com/wazuh/wazuh-qa/files/7012321/win_agent_test_fim_r1.zip) | |
|R2|[🔴 ](https://github.com/wazuh/wazuh-qa/files/7012324/win_agent_test_fim_r2.zip)|
|R3| 🔵  |

**Comment by snaow** [comment]
Closed by: https://github.com/wazuh/wazuh-qa/pull/1765

FIM tests are far away from being stable.
We did major improvements in this effort but further development is required.

Whodata/realtime modes tests are 95% functional but scheduled mode needs still tons of work.
