### ISSUE TITLE
Fix 'test_feeds/test_invalid_type_url_feeds' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1544]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_feeds/test_invalid_type_url_feeds
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases |   feed.avi, feed.jpg, feed.mp3, feed.zip
| Cases Fails | 24 
| Summary | On `test_invalid_type_url_feeds` when it called to `check_failure_when_importing_feed`. It could be a problem with the log parser when verifying the message.
| Error message |  "Could not find the log event: ERROR: \(\d+\): CVE database could not be updated."

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix on the Test.
- [ ] Full Green/ Full Yellow in `test_feeds/test_invalid_type_url_feeds` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-19

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_invalid_type_url_feeds_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6840829/test_invalid_type_url_feeds_local_dm_r1.log)| 2021-07-19 | Miguel | :yellow_circle: 
|[test_invalid_type_url_feeds_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6840830/test_invalid_type_url_feeds_local_dm_r2.log)| 2021-07-19 | Miguel | :yellow_circle: 
|[test_invalid_type_url_feeds_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6840891/test_invalid_type_url_feeds_local_dm_r3.log)| 2021-07-19 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
This issue is closed by #1605

**Comment by damarisg** [comment]
## Test Results from `1531-full-yellow-vuln-det`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowResultsInvalidTypeURLFeed4.log](https://github.com/wazuh/wazuh-qa/files/6856658/YellowResultsInvalidTypeURLFeed4.log)| 2021-07-21| Seyla| 🟡 
| [YellowResultsInvalidTypeURLFeed2.log](https://github.com/wazuh/wazuh-qa/files/6856546/YellowResultsInvalidTypeURLFeed2.log)| 2021-07-21| Seyla| 🟡 
|[YellowResultsInvalidTypeURLFeed3.log](https://github.com/wazuh/wazuh-qa/files/6856547/YellowResultsInvalidTypeURLFeed3.log)| 2021-07-21| Seyla| 🟡 


| Reference | Status | 
|--|--|
| 🟡 | Pass with Warnings |

### Note 
This issue fails sometimes by the bug  https://github.com/wazuh/wazuh/issues/9309

**Comment by mdengra** [comment]
### 2021-07-22

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_invalid_type_url_feeds_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6860824/test_invalid_type_url_feeds_local_r1.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_invalid_type_url_feeds_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6860827/test_invalid_type_url_feeds_local_r2.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_invalid_type_url_feeds_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6860828/test_invalid_type_url_feeds_local_r3.log)| 2021-07-22 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
This issue is closed because the test was disabled by wazuh/wazuh#9309.
