### ISSUE TITLE
Fix 'test_feeds/canonical/test_extra_tags_canonical_feed' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1545]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_feeds/canonical/test_extra_tags_canonical_feed
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases Fails | 117 
| Summary | - On `modify_feed` method when it called to `read_xml_file`. The problem seems to be a Parser error when reading the file.
|   |  - On `test_extra_tags_canonical_feed` method when it called to `check_failure_when_importing_feed`. In this case, we need to see if there are a problem to import the file or if it's a Parser error in log event.
| Error message |  "Could not find the log event: ERROR: \\(\\d+\\): CVE database could not be updated."

## Case 2:

|  Type | Description  |
|--|--|
|Test Path | test_feeds/canonical/test_extra_tags_canonical_feed
| Consistent | yes
| Test Execution | 1/3 executions failed
| Cases | test_no_feed_changes |
| Cases Fails | 1
| Summary | On `check_feed_imported_successfully` method the problem could be a Parser error when checking in the log or a problem when a file is imported.
| Error message |  "Could not find the message: 'Ubuntu Bionic' feed finished successfully"

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix on the Test to **CASE 1**.
- [ ] Apply Fix on the Test to **CASE 2**.
- [ ] Full Green/ Full Yellow in `test_feeds/canonical/test_extra_tags_canonical_feed` for 3 times.
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-19

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_extra_tags_canonical_feed_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6841575/test_extra_tags_canonical_feed_local_dm_r1.log)| 2021-07-19 | Miguel | :yellow_circle: 
|[test_extra_tags_canonical_feed_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6841576/test_extra_tags_canonical_feed_local_dm_r2.log)| 2021-07-19 | Miguel | :yellow_circle: 
|[test_extra_tags_canonical_feed_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6841750/test_extra_tags_canonical_feed_local_dm_r3.log)| 2021-07-19 | Miguel | :yellow_circle:

**Comment by mdengra** [comment]
### 2021-07-22

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_extra_tags_canonical_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6860984/test_extra_tags_canonical_feed_local_r1.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_extra_tags_canonical_feed_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6860986/test_extra_tags_canonical_feed_local_r2.log)| 2021-07-22 | Miguel | :yellow_circle:
|[test_extra_tags_canonical_feed_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6860987/test_extra_tags_canonical_feed_local_r3.log)| 2021-07-22 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [YellowResultsExtraTagsCanonicalFeed.log](https://github.com/wazuh/wazuh-qa/files/6864535/YellowResultsExtraTagsCanonicalFeed.log)| 2021-07-22 | Seyla | 🟡 
|[YellowResultsExtraTagsCanonicalFeed2.log](https://github.com/wazuh/wazuh-qa/files/6864532/YellowResultsExtraTagsCanonicalFeed2.log)| 2021-07-22 | Seyla | 🟡
|[YellowResultsExtraTagsCanonicalFeed3.log](https://github.com/wazuh/wazuh-qa/files/6864533/YellowResultsExtraTagsCanonicalFeed3.log)| 2021-07-22 | Seyla | 🟡

**Comment by mdengra** [comment]
This issue is open because we detect that is affected by wazuh/wazuh#9309.

**Comment by damarisg** [comment]
This issue is closed because the test was disabled by  wazuh/wazuh#9309.
