### ISSUE TITLE
Fix 'test_feeds/debian/test_extra_tags_debian_feed' tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1546]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_feeds/debian/test_extra_tags_debian_feed
| Consistent | no
| Test Execution | 2/3 executions failed
| Cases Fails | 34
| Summary |On `test_extra_tags_debian_feed` when it called `check_feed_imported_successfully` method is called. The problem seems to be when imported a file, but also should see if there is a Parser error when reading the log.
| Error message |  "Could not find the message: 'Debian Buster' feed finished successfully"

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix.
- [ ] Full Green/ Full Yellow in `test_feeds/debian/test_extra_tags_debian_feed` for 3 times.
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-13
I am currently running tests to reproduce the error in my testing environment:
  - [test_extra_tags_debian_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6808043/test_extra_tags_debian_feed_local_r1.log)

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results1_ExtraDebian.log](https://github.com/wazuh/wazuh-qa/files/6811065/Results1_ExtraDebian.log) | 2021-07-13| Seyla | 🟢
| [Results2_ExtraDebian.log](https://github.com/wazuh/wazuh-qa/files/6811161/Results2_ExtraDebian.log) | 2021-07-13| Seyla | 🟢
| [Results3_ExtraDebian.log](https://github.com/wazuh/wazuh-qa/files/6811358/Results3_ExtraDebian.log) | 2021-07-13| Seyla | 🟢

**Comment by pereyra-m** [comment]
Results for `test_feeds/debian/test_extra_tags_debian_feed`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[centos_test_extra_tags_debian_feed_1.log](https://github.com/wazuh/wazuh-qa/files/6812625/centos_test_extra_tags_debian_feed_1.log)| 2021-07-13| Matias | :green_circle:
|[centos_test_extra_tags_debian_feed_2.log](https://github.com/wazuh/wazuh-qa/files/6812624/centos_test_extra_tags_debian_feed_2.log) | 2021-07-13| Matias | :green_circle:
|[centos_test_extra_tags_debian_feed_3.log](https://github.com/wazuh/wazuh-qa/files/6812623/centos_test_extra_tags_debian_feed_3.log) | 2021-07-13| Matias | :green_circle:

**Comment by damarisg** [comment]
This issue is closed, after executes for a lot of times and see that works.
We couldn't reproduce the error.
