### ISSUE TITLE
Fix 'test_feeds/redhat/test_extra_fields_redhat_feed' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1555]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

I will create 3 cases for the same test because fails on different methods.
The idea is that you can analyze and fix both.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_feeds/redhat/test_extra_fields_redhat_feed 
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases Fails | 123
| Summary | On `test_invalid_syntax_canonical_feed` method when it called to `check_failure_when_importing_feed`.  We need to see if there is a problem to import a file or if it's a Parser error in log event.
| Error message |  "Could not find the log event: ERROR: \\(\\d+\\): CVE database could not be updated."

## Case 2:

|  Type | Description  |
|--|--|
|Test Path | test_feeds/redhat/test_extra_fields_redhat_feed 
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases Fails | 123
| Summary |On `modify_feed` when it called `read_xml_file` method is called. The problem seems to be a Parser error when reading the file.
| Error message |  "ERROR at setup of test_extra_fields_redhat_feed[REDHAT_configuration-tag"

## Case 3:

|  Type | Description  |
|--|--|
|Test Path | test_feeds/redhat/test_extra_fields_redhat_feed 
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases Fails | 123
| Summary | On `test_extra_fields_redhat_feed` when `check_failure_when_importing_feed` method is called.
| Error message |  "Could not find the log event: ERROR: \\(\\d+\\): CVE database could not be updated."

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_feeds/redhat/test_extra_fields_redhat_feed ` for 3 times.
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [YellowResultsExtraFieldRedhatFeed.log](https://github.com/wazuh/wazuh-qa/files/6864615/YellowResultsExtraFieldRedhatFeed.log)| 2021-07-22 | Seyla | 🟡 
|[YellowResultsExtraFieldRedhatFeed2.log](https://github.com/wazuh/wazuh-qa/files/6864616/YellowResultsExtraFieldRedhatFeed2.log)| 2021-07-22 | Seyla | 🟡 
|[YellowResultsExtraFieldRedhatFeed3.log](https://github.com/wazuh/wazuh-qa/files/6864617/YellowResultsExtraFieldRedhatFeed3.log)| 2021-07-22 | Seyla | 🟡 

I can't reproduce the fail.

**Comment by mdengra** [comment]
### 2021-07-23

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

### Case 1
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_extra_fields_redhat_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6867366/test_extra_fields_redhat_feed_local_r1.log)| 2021-07-23 | Miguel | :yellow_circle: 
|[test_extra_fields_redhat_feed_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6867368/test_extra_fields_redhat_feed_local_r2.log)| 2021-07-23 | Miguel | :yellow_circle: 
|[test_extra_fields_redhat_feed_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6867369/test_extra_fields_redhat_feed_local_r3.log)| 2021-07-23 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
Closed because we can't reproduce it.
