### ISSUE TITLE
Fix 'test_general_settings/test_general_settings_interval' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1557]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_general_settings/test_general_settings_interval
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 12
| Summary | It should to do research with more details because in the logs doesn't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_general_settings/test_general_settings_interval` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-13
Test results :green_circle::
  - [test_general_settings_interval_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809716/test_general_settings_interval_local_r1.log)
  - [test_general_settings_interval_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809717/test_general_settings_interval_local_r2.log)
  - [test_general_settings_interval_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809718/test_general_settings_interval_local_r3.log)

**Comment by damarisg** [comment]
This issue is closed, after executes for a lot of times and see that works.
We couldn't reproduce the error. 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_interval_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809716/test_general_settings_interval_local_r1.log) | 2021-07-13| Miguel| :green_circle:
|[test_general_settings_interval_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809717/test_general_settings_interval_local_r2.log) | 2021-07-13| Miguel| :green_circle:
| [test_general_settings_interval_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809718/test_general_settings_interval_local_r3.log) | 2021-07-13| Miguel| :green_circle:
| [Results1_IntervalSetting.log](https://github.com/wazuh/wazuh-qa/files/6810616/Results1_IntervalSetting.log) | 2021-07-13| Seyla | :green_circle:
| [Results2_IntervalSetting.log](https://github.com/wazuh/wazuh-qa/files/6810614/Results2_IntervalSetting.log) | 2021-07-13| Seyla | :green_circle:
 |[Results3_IntervalSetting.log](https://github.com/wazuh/wazuh-qa/files/6810615/Results3_IntervalSetting.log) | 2021-07-13| Seyla | :green_circle:

**Comment by pereyra-m** [comment]
This test was covered in this [comment](https://github.com/wazuh/wazuh-qa/issues/1556#issuecomment-878794672).
All the local tests were green:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [centos1.log](https://github.com/wazuh/wazuh-qa/files/6811729/centos.log) | 2021-07-12| Matias | :green_circle:
| [centos2.log](https://github.com/wazuh/wazuh-qa/files/6811730/centos2.1.log) | 2021-07-12| Matias | :green_circle:
 |[centos3.log](https://github.com/wazuh/wazuh-qa/files/6811732/centos3.1.log) | 2021-07-12| Matias | :green_circle:
