### ISSUE TITLE
Fix 'test_providers/test_providers_os' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1562]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_providers/test_providers_os
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 11
| Summary | It should to do research with more details because in the logs doesn't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_providers/test_providers_os` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by pereyra-m** [comment]
Results for `test_providers/test_providers_os`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[centos_test_providers_os_1.log](https://github.com/wazuh/wazuh-qa/files/6812203/centos_test_providers_os_1.log)| 2021-07-13| Matias | :green_circle:
| [centos_test_providers_os_2.log](https://github.com/wazuh/wazuh-qa/files/6812202/centos_test_providers_os_2.log)| 2021-07-13| Matias | :green_circle:
| [centos_test_providers_os_3.log](https://github.com/wazuh/wazuh-qa/files/6812201/centos_test_providers_os_3.log)| 2021-07-13| Matias | :green_circle:

**Comment by mdengra** [comment]
### 2021-07-14

Test results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_os_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6816876/test_providers_os_local_r1.log)| 2021-07-14 | Miguel | :yellow_circle: 
|[test_providers_os_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6816879/test_providers_os_local_r2.log)| 2021-07-14 | Miguel | :yellow_circle: 
|[test_providers_os_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6816883/test_providers_os_local_r3.log)| 2021-07-14 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ProviderOS1.log](https://github.com/wazuh/wazuh-qa/files/6818387/ProviderOS1.log)| 2021-07-14 | Seyla| :yellow_circle: 
|[ProviderOS2.log](https://github.com/wazuh/wazuh-qa/files/6818385/ProviderOS2.log)| 2021-07-14 | Seyla| :yellow_circle: 
|[ProviderOS3.log](https://github.com/wazuh/wazuh-qa/files/6818386/ProviderOS3.log)| 2021-07-14 | Seyla| 🟢  


| Reference | Status | 
|--|--|
| 🟢 | Pass without warnings|
| 🟡 | Pass with Warnings |

**Comment by damarisg** [comment]
This issue is closed, after executes for a lot of times and see that works.
We couldn't reproduce the error.

**Comment by damarisg** [comment]
This issue is open because we detect that is affected by https://github.com/wazuh/wazuh/issues/9309
