### ISSUE TITLE
Fix 'test_providers/test_providers_update_interval' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1564]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_providers/test_providers_update_interval
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 20
| Summary | It should do research with more details because the logs don't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_providers/test_providers_update_interval` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by pereyra-m** [comment]
Results for `test_providers/test_providers_update_interval`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[centos_test_update_interval_1.log](https://github.com/wazuh/wazuh-qa/files/6812243/centos_test_update_interval_1.log)| 2021-07-13| Matias | :green_circle:
|[centos_test_update_interval_2.log](https://github.com/wazuh/wazuh-qa/files/6812242/centos_test_update_interval_2.log) | 2021-07-13| Matias | :green_circle:
| [centos_test_update_interval_3.log](https://github.com/wazuh/wazuh-qa/files/6812241/centos_test_update_interval_3.log)| 2021-07-13| Matias | :green_circle:

**Comment by mdengra** [comment]
### 2021-07-14

Test results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_update_interval_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6816906/test_providers_update_interval_local_r1.log)| 2021-07-14 | Miguel | :green_circle: 
|[test_providers_update_interval_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6816976/test_providers_update_interval_local_r2.log)| 2021-07-14 | Miguel | :green_circle: 
|[test_providers_update_interval_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6816980/test_providers_update_interval_local_r3.log)| 2021-07-14 | Miguel | :green_circle:

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ProviderUpdateInterval1.log](https://github.com/wazuh/wazuh-qa/files/6817863/ProviderUpdateInterval1.log)| 2021-07-14 | Seyla| :green_circle: 
|[ProviderUpdateInterval2.log](https://github.com/wazuh/wazuh-qa/files/6817864/ProviderUpdateInterval2.log)| 2021-07-14 | Seyla| :green_circle: 
|[ProviderUpdateInterval3.log](https://github.com/wazuh/wazuh-qa/files/6817862/ProviderUpdateInterval3.log) | 2021-07-14 | Seyla| :green_circle: 


This issue is closed, after executes for a lot of times and see that works.
We couldn't reproduce the error.
