### ISSUE TITLE
Fix 'test_scan_results/test_inventory_feed' tests for debian, redhat and canonical in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1566]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

In this case, We add 3 cases because the tests are similar and the error is the same. We believe that when solving one of the cases, the same fix could be applied to the other cases.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_scan_results/test_debian_inventory_debian_feed
| Consistent | yes
| Test Execution | 3/3 executions failed
|Cases| BUSTER
|| STRETCH
| Cases Fails | 2
| Summary | On `test_debian_vulnerabilities_report` when `check_detected_vulnerabilities_number` is called. it requires research to know if there is a problem with parser error or if we don't detect log.
|Error message| 'The expected number of OVAL vulnerabilities have not been found'

## Case 2:

|  Type | Description  |
|--|--|
|Test Path | test_scan_results/test_redhat_inventory_redhat_feed
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases | redhat_scan_configuration-RHEL5      
|| redhat_scan_configuration-RHEL6           
||redhat_scan_configuration-RHEL7     
||redhat_scan_configuration-RHEL8   
| Cases Fails | 4
| Summary | On `test_redhat_vulnerabilities_report` when `check_detected_vulnerabilities_number` is called. it requires research to know if there is a problem with parser error or if we don't detect log.
|Error message| "The expected number of {feed_source} vulnerabilities have not been found"

## Case 3:

|  Type | Description  |
|--|--|
|Test Path | test_scan_results/test_ubuntu_inventory_canonical_feed
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases | ubuntu_scan_configuration-FOCAL
|| ubuntu_scan_configuration-BIONIC          
|| redhat_scan_configuration-XENIAL      
|| redhat_scan_configuration-TRUSTY
| Cases Fails | 4
| Summary | On `test_ubuntu_vulnerabilities_report` when `check_detected_vulnerabilities_number` is called. it requires research to know if there is a problem with parser error or if we don't detect log.
|Error message| "The expected number of {feed_source} vulnerabilities have not been found"

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_scan_results/test_debian_inventory_debian_feed` for 3 times. 
- [ ] Full Green/ Full Yellow  in `test_scan_results/test_redhat_inventory_redhat_feed` for 3 times. 
- [ ] Full Green/ Full Yellow  in `test_scan_results/test_ubuntu_inventory_canonical_feed` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by pereyra-m** [comment]
These are the results for the different cases, all of them with `sca`, `syscollector` and `rootcheck` disabled

## Case 1 

Results for `test_scan_results/test_debian_inventory_debian_feed.py`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_debian_inventory_debian_feed_modules_off_1.log](https://github.com/wazuh/wazuh-qa/files/6818934/test_debian_inventory_debian_feed_modules_off_1.log)| 2021-07-14| Matias | :green_circle:
|[test_debian_inventory_debian_feed_modules_off_2.log](https://github.com/wazuh/wazuh-qa/files/6818933/test_debian_inventory_debian_feed_modules_off_2.log) | 2021-07-14| Matias | :green_circle:
| [test_debian_inventory_debian_feed_modules_off_3.log](https://github.com/wazuh/wazuh-qa/files/6818931/test_debian_inventory_debian_feed_modules_off_3.log)| 2021-07-14| Matias | :green_circle:

## Case 2

Results for `test_scan_results/test_redhat_inventory_redhat_feed.py`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_redhat_inventory_redhat_feed_modules_off_1.log](https://github.com/wazuh/wazuh-qa/files/6818950/test_redhat_inventory_redhat_feed_modules_off_1.log)| 2021-07-14| Matias | :green_circle:
|[test_redhat_inventory_redhat_feed_modules_off_2.log](https://github.com/wazuh/wazuh-qa/files/6818949/test_redhat_inventory_redhat_feed_modules_off_2.log) | 2021-07-14| Matias | :green_circle:
| [test_redhat_inventory_redhat_feed_modules_off_3.log](https://github.com/wazuh/wazuh-qa/files/6818946/test_redhat_inventory_redhat_feed_modules_off_3.log)| 2021-07-14| Matias | :green_circle:

## Case 3

Results for `test_ubuntu_inventory_canonical_feed.py`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_ubuntu_inventory_canonical_feed_modules_off_1.log](https://github.com/wazuh/wazuh-qa/files/6818971/test_ubuntu_inventory_canonical_feed_modules_off_1.log)| 2021-07-14| Matias | :green_circle:
| [test_ubuntu_inventory_canonical_feed_modules_off_2.log](https://github.com/wazuh/wazuh-qa/files/6818970/test_ubuntu_inventory_canonical_feed_modules_off_2.log)| 2021-07-14| Matias | :green_circle:
|[test_ubuntu_inventory_canonical_feed_modules_off_3.log](https://github.com/wazuh/wazuh-qa/files/6818969/test_ubuntu_inventory_canonical_feed_modules_off_3.log) | 2021-07-14| Matias | :green_circle:

**Comment by mdengra** [comment]
### 2021-07-15

Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

### Case 1
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_debian_inventory_debian_feed_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6822967/test_debian_inventory_debian_feed_local_dm_r1.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_debian_inventory_debian_feed_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6822969/test_debian_inventory_debian_feed_local_dm_r2.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_debian_inventory_debian_feed_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6822971/test_debian_inventory_debian_feed_local_dm_r3.log)| 2021-07-15 | Miguel | :yellow_circle: 

### Case 2
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_redhat_inventory_redhat_feed_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6822987/test_redhat_inventory_redhat_feed_local_dm_r1.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_redhat_inventory_redhat_feed_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6822988/test_redhat_inventory_redhat_feed_local_dm_r2.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_redhat_inventory_redhat_feed_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6822992/test_redhat_inventory_redhat_feed_local_dm_r3.log)| 2021-07-15 | Miguel | :yellow_circle: 

### Case 3
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_ubuntu_inventory_canonical_feed_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6822999/test_ubuntu_inventory_canonical_feed_local_dm_r1.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_ubuntu_inventory_canonical_feed_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6823001/test_ubuntu_inventory_canonical_feed_local_dm_r2.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_ubuntu_inventory_canonical_feed_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6823004/test_ubuntu_inventory_canonical_feed_local_dm_r3.log)| 2021-07-15 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
Test Results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

### Case 1
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ScanDebian1.log](https://github.com/wazuh/wazuh-qa/files/6823276/ScanDebian1.log)| 2021-07-15 | Seyla| :yellow_circle: 
|[ScanDebian2.log](https://github.com/wazuh/wazuh-qa/files/6823274/ScanDebian2.log) | 2021-07-15 | Seyla| :yellow_circle: 
| [ScanDebian3.log](https://github.com/wazuh/wazuh-qa/files/6823275/ScanDebian3.log)| 2021-07-15 | Seyla | :yellow_circle: 


### Case 2
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results_ScanRedHat1.log](https://github.com/wazuh/wazuh-qa/files/6823395/ScanRedHat1.log)| 2021-07-15 | Seyla| 🟢  
|[Results_ScanRedHat2.log](https://github.com/wazuh/wazuh-qa/files/6823393/ScanRedHat2.log)| 2021-07-15 | Seyla| 🟢 
|[Results_ScanRedHat3.log](https://github.com/wazuh/wazuh-qa/files/6823394/ScanRedHat3.log)| 2021-07-15 | Seyla| :yellow_circle: 


### Case 3
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ResultsUbuntuInventoryCanonical1.log](https://github.com/wazuh/wazuh-qa/files/6823465/ResultsUbuntuInventoryCanonical1.log)| 2021-07-15 | Seyla| :yellow_circle: 
|[ResultsUbuntuInventoryCanonical2.log](https://github.com/wazuh/wazuh-qa/files/6823464/ResultsUbuntuInventoryCanonical2.log)| 2021-07-15 | Seyla| :yellow_circle: 
|[ResultsUbuntuInventoryCanonical3.log](https://github.com/wazuh/wazuh-qa/files/6823472/ResultsUbuntuInventoryCanonical3.log)| 2021-07-15 | Seyla| :yellow_circle: 


| Reference | Status | 
|--|--|
| 🟢 | Pass without warnings|
| 🟡 | Pass with Warnings |

**Comment by damarisg** [comment]
This issue is closed, after executes for a lot of times and see that works. The solved applied was disabling `sca`, `syscollector` and `rootcheck` modules.

**Comment by damarisg** [comment]
## Test Results from `1531-full-yellow-vuln-det`

| Test Executions | Tests | Date  | By  | Status | 
|--|--|--|--|--|
|[YellowResultsScanDebianInventoryFeed.log](https://github.com/wazuh/wazuh-qa/files/6857608/YellowResultsScanDebianInventoryFeed.log)| test_scan_results/test_debian_inventory_debian_feed |2021-07-21| Seyla| 🟡 
|[YellowResultsScanDebianInventoryFeed2.log](https://github.com/wazuh/wazuh-qa/files/6857606/YellowResultsScanDebianInventoryFeed2.log) | 2021-07-21| Seyla| 🟡
| [YellowResultsScanDebianInventoryFeed3.log](https://github.com/wazuh/wazuh-qa/files/6857607/YellowResultsScanDebianInventoryFeed3.log)|test_scan_results/test_debian_inventory_debian_feed| 2021-07-21| Seyla|  🟡
| [YellowResultsScanRedhatInventoryFeed1.log](https://github.com/wazuh/wazuh-qa/files/6857702/YellowResultsScanRedhatInventoryFeed1.log) | test_scan_results/test_redhat_inventory_redhat_feed |2021-07-21| Seyla| 🟡
| [YellowResultsScanRedhatInventoryFeed2.log](https://github.com/wazuh/wazuh-qa/files/6857707/YellowResultsScanRedhatInventoryFeed2.log) |test_scan_results/test_redhat_inventory_redhat_feed|2021-07-21| Seyla| 🟡
|[YellowResultsScanRedhatInventoryFeed3.log](https://github.com/wazuh/wazuh-qa/files/6857712/YellowResultsScanRedhatInventoryFeed3.log)  |test_scan_results/test_redhat_inventory_redhat_feed| 2021-07-21| Seyla|  🟡
| [YellowResultsScanUbuntuInventoryFeed.log](https://github.com/wazuh/wazuh-qa/files/6857718/YellowResultsScanUbuntuInventoryFeed.log) | test_scan_results/test_ubuntu_inventory_canonical_feed |2021-07-21| Seyla| 🟡
| [YellowResultsScanUbuntuInventoryFeed2.log](https://github.com/wazuh/wazuh-qa/files/6857721/YellowResultsScanUbuntuInventoryFeed2.log) |test_scan_results/test_ubuntu_inventory_canonical_feed|2021-07-21| Seyla| 🟡
| [YellowResultsScanUbuntuInventoryFeed3.log](https://github.com/wazuh/wazuh-qa/files/6857726/YellowResultsScanUbuntuInventoryFeed3.log)  |test_scan_results/test_ubuntu_inventory_canonical_feed| 2021-07-21| Seyla|  🟡


| Reference | Status | 
|--|--|
| 🟡 | Pass with Warnings |


### Note
This issue fails sometimes by the bug  https://github.com/wazuh/wazuh/issues/9309

**Comment by mdengra** [comment]
### 2021-07-22

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

### Case 1
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_debian_inventory_debian_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6861005/test_debian_inventory_debian_feed_local_r1.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_debian_inventory_debian_feed_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6861007/test_debian_inventory_debian_feed_local_r2.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_debian_inventory_debian_feed_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6861010/test_debian_inventory_debian_feed_local_r3.log)| 2021-07-22 | Miguel | :yellow_circle: 


### Case 2
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_redhat_inventory_redhat_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6861032/test_redhat_inventory_redhat_feed_local_r1.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_redhat_inventory_redhat_feed_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6861033/test_redhat_inventory_redhat_feed_local_r2.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_redhat_inventory_redhat_feed_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6861034/test_redhat_inventory_redhat_feed_local_r3.log)| 2021-07-22 | Miguel | :yellow_circle: 


### Case 3
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_ubuntu_inventory_canonical_feed_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6861085/test_ubuntu_inventory_canonical_feed_local_r1.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_ubuntu_inventory_canonical_feed_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6861088/test_ubuntu_inventory_canonical_feed_local_r2.log)| 2021-07-22 | Miguel | :yellow_circle: 
|[test_ubuntu_inventory_canonical_feed_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6861090/test_ubuntu_inventory_canonical_feed_local_r3.log)| 2021-07-22 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
This issue is closed because the test was disabled by https://github.com/wazuh/wazuh/issues/9309
