### ISSUE TITLE
Fix 'test_remoted/test_manager_messages/test_manager_ack' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1572]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_manager_messages/test_manager_ack
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases Fails | 4
|Summary | On `test_manager_ack` when it called to `check_manager_ack`. 
|Error message| 'Could not find the remoted key loading log'

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_manager_messages/test_manager_ack` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-27

Used Wazuh-QA branch: `1530-full-yellow-remoted`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--| 
|[test_manager_ack_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6886806/test_manager_ack_local_r1.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_manager_ack_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6886809/test_manager_ack_local_r2.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_manager_ack_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6886811/test_manager_ack_local_r3.log)| 2021-07-27 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
This issue will be closed because we can't reproduce it.

Test Results:
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowManagerACK.log](https://github.com/wazuh/wazuh-qa/files/6887482/YellowManagerACK.log)| 2021-07-27 | Seyla | :yellow_circle:  
|[YellowManagerACK2.log](https://github.com/wazuh/wazuh-qa/files/6887480/YellowManagerACK2.log)| 2021-07-27 | Seyla| :yellow_circle:  
[YellowManagerACK3.log](https://github.com/wazuh/wazuh-qa/files/6887481/YellowManagerACK3.log)| 2021-07-27 | Seyla| :yellow_circle:
