### ISSUE TITLE
Fix 'test_remoted/test_configuration' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1573]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```

I add some information obtained while researched the logs that failed.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases Fails | 6
|Summary | On `test_invalid_protocol` when it called to `log_callback`. Check if shows in the log monitor or there is another problem. 
|Error message| 'The expected error output has not been produced'

__________________________________________________________________________________________
## Case 2:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_configuration/test_basic_configuration_connection_valid
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases Fails | 8
|Summary | On `test_connection_valid` when it called to `log_callback`. Check if shows in the log monitor or there is another problem. 
|Error message| 'The expected error output has not been produced'

__________________________________________________________________________________________
## Case 3:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases Fails | 1
|Summary | On `test_denied_ips_syslog` when it called to `log_callback`. Check if shows in the log monitor or there is another problem. 
|Error message| 'The expected output for denied-ips has not been produced'

__________________________________________________________________________________________

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_configuration/test_basic_configuration_connection_valid` for 3 times. 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips` for 3 times. 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by damarisg** [comment]
I can't reproduce.

| Test Executions | Date  | By  | Tests | Status | 
|--|--|--|--|--|
|[RemotedBasicConfConnValid.log](https://github.com/wazuh/wazuh-qa/files/6843150/RemotedBasicConfConnValid.log) | 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_connection_valid |🟡
| [RemotedBasicConfConnValid2.log](https://github.com/wazuh/wazuh-qa/files/6843151/RemotedBasicConfConnValid2.log)| 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_connection_valid |🟡 
| [RemotedBasicConfConnValid3.log](https://github.com/wazuh/wazuh-qa/files/6843152/RemotedBasicConfConnValid3.log)| 2021-07-19 | Seyla|test_remoted/test_configuration/test_basic_configuration_connection_valid | 🟡 
|[ConfSyslogDeniedIp.log](https://github.com/wazuh/wazuh-qa/files/6843201/ConfSyslogDeniedIp.log) | 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips | 🟡
| [ConfSyslogDeniedIp2.log](https://github.com/wazuh/wazuh-qa/files/6843202/ConfSyslogDeniedIp2.log)| 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips | 🟡
| [ConfSyslogDeniedIp3.log](https://github.com/wazuh/wazuh-qa/files/6843203/ConfSyslogDeniedIp3.log)| 2021-07-19 | Seyla|test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips | 🟡
|[ResultConfigurationConInvProtocol.log](https://github.com/wazuh/wazuh-qa/files/6843247/ResultConfigurationConInvProtocol.log) | 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol | 🟡
| [ResultConfigurationConInvProtocol2.log](https://github.com/wazuh/wazuh-qa/files/6843248/ResultConfigurationConInvProtocol2.log)| 2021-07-19 | Seyla| test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol | 🟡
| [ResultConfigurationConInvProtocol3.log](https://github.com/wazuh/wazuh-qa/files/6843249/ResultConfigurationConInvProtocol3.log) | 2021-07-19 | Seyla|test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol | 🟡

**Comment by mdengra** [comment]
### 2021-07-20

Used Wazuh-QA branch: `1516-4.2.0-full-green`
Test results with the default modules enabled in the `ossec.conf`: 

### Case 1
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_basic_configuration_connection_invalid_protocol_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6847447/test_basic_configuration_connection_invalid_protocol_local_r1.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_connection_invalid_protocol_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6847448/test_basic_configuration_connection_invalid_protocol_local_r2.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_connection_invalid_protocol_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6847449/test_basic_configuration_connection_invalid_protocol_local_r3.log)| 2021-07-20 | Miguel | :yellow_circle: 


### Case 2
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_basic_configuration_connection_valid_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6847456/test_basic_configuration_connection_valid_local_r1.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_connection_valid_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6847457/test_basic_configuration_connection_valid_local_r2.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_connection_valid_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6847458/test_basic_configuration_connection_valid_local_r3.log)| 2021-07-20 | Miguel | :yellow_circle: 


### Case 3
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_basic_configuration_syslog_denied_ips_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6847463/test_basic_configuration_syslog_denied_ips_local_r1.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_syslog_denied_ips_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6847465/test_basic_configuration_syslog_denied_ips_local_r2.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_basic_configuration_syslog_denied_ips_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6847466/test_basic_configuration_syslog_denied_ips_local_r3.log)| 2021-07-20 | Miguel | :yellow_circle:

**Comment by DProvinciani** [comment]
Considering the comment https://github.com/wazuh/wazuh-qa/issues/1530#issuecomment-884924516, I decided to isolate the `test_remoted/test_configuration` and run all of them in a clean environment.

The same as @mdengra and @damarisg, I was not able to reproduce the issue. This means that probably the failures are caused because of the previous execution of other tests.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_configuration-r1.log](https://github.com/wazuh/wazuh-qa/files/6863146/test_configuration-r1.log)| 2021-07-22 | Diego | :yellow_circle:|
|[test_configuration-r2.log](https://github.com/wazuh/wazuh-qa/files/6863156/test_configuration-r2.log)| 2021-07-22 | Diego | :yellow_circle:|
|[test_configuration-r3.log](https://github.com/wazuh/wazuh-qa/files/6863157/test_configuration-r3.log)| 2021-07-22 | Diego | :yellow_circle:|

**Comment by DProvinciani** [comment]
Considering the comment https://github.com/wazuh/wazuh-qa/issues/1530#issuecomment-884924516, I decided to combine the `test_remoted/test_configuration` run with the `test_remoted/test_active_response` and `test_remoted/test_agent_communication` to determine which combination causes the failures.

The execution sequence was always:

- python3 -m pytest -vvx wazuh-qa/tests/integration/test_remoted/test_active_response
- python3 -m pytest -vvx wazuh-qa/tests/integration/test_remoted/test_configuration
- python3 -m pytest -vvx wazuh-qa/tests/integration/test_remoted/test_agent_communication
- python3 -m pytest -vvx wazuh-qa/tests/integration/test_remoted/test_configuration

**Result:** All the tests passed successfully in all the executions.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_ar_configuration_communication_configuration-r1.log](https://github.com/wazuh/wazuh-qa/files/6865416/test_ar_configuration_communication_configuration-r1.log)| 2021-07-22 | Diego | :yellow_circle:|
|[test_ar_configuration_communication_configuration-r2.log](https://github.com/wazuh/wazuh-qa/files/6865417/test_ar_configuration_communication_configuration-r2.log)| 2021-07-22 | Diego | :yellow_circle:|
|[test_ar_configuration_communication_configuration-r3.log](https://github.com/wazuh/wazuh-qa/files/6865419/test_ar_configuration_communication_configuration-r3.log)| 2021-07-22 | Diego | :yellow_circle:|

**Comment by damarisg** [comment]
Closed because we can't reproduce it.
