### ISSUE TITLE
Fix 'test_remoted/test_agent_communication/test_invalid_protocol_communication' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1575]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_agent_communication/test_invalid_protocol_communication
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases | UDP_1514 - UDP_56000
|Cases Fails | 2
|Summary | On `test_invalid_protocol_communication` when it called to `validate_agent_manager_protocol_communication`. 
 ||It requires research if it is a timeout error to load log, or if it an error has do the communication or what happens with the remoted key when is loading.
|Error message| 'Could not find the remoted key loading log'

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_agent_communication/test_invalid_protocol_communication` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-20

I was unable to reproduce the described error in my testing environment.
Used Wazuh-QA branch: `1516-4.2.0-full-green`
Test results with the default modules enabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_invalid_protocol_communication_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6847627/test_invalid_protocol_communication_local_r1.log)| 2021-07-20 | Miguel | :yellow_circle:  
|[test_invalid_protocol_communication_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6847628/test_invalid_protocol_communication_local_r2.log)| 2021-07-20 | Miguel | :yellow_circle:  
|[test_invalid_protocol_communication_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6847630/test_invalid_protocol_communication_local_r3.log)| 2021-07-20 | Miguel | :yellow_circle:

**Comment by juliamagan** [comment]
## Tests results

||CentOS 8 Manager |Reports|
|:--:|:--:|:--:|
|R1|  🟢    | [Tests results](https://github.com/wazuh/wazuh-qa/files/6876678/centos_manager_test_invalid_protocol_communication_r1.zip)| 
|R2|   🟢    | [Tests results](https://github.com/wazuh/wazuh-qa/files/6876680/centos_manager_test_invalid_protocol_communication_r2.zip)|
|R3|  🟢    | [Tests results](https://github.com/wazuh/wazuh-qa/files/6876682/centos_manager_test_invalid_protocol_communication_r3.zip)|

**Comment by damarisg** [comment]
This issue will be closed because we can't reproduce it.
Test Results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowInvalidProtocolCommunication.log](https://github.com/wazuh/wazuh-qa/files/6886205/YellowInvalidProtocolCommunication.log)| 2021-07-27 | Seyla| :yellow_circle:  
|[YellowInvalidProtocolCommunication2.log](https://github.com/wazuh/wazuh-qa/files/6886203/YellowInvalidProtocolCommunication2.log)| 2021-07-27 | Seyla| :yellow_circle:  
|[YellowInvalidProtocolCommunication3.log](https://github.com/wazuh/wazuh-qa/files/6886204/YellowInvalidProtocolCommunication3.log)| 2021-07-27 | Seyla| :yellow_circle:
