### ISSUE TITLE
Fix 'test_remoted/test_agent_communication/test_shared_configuration' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1578]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_agent_communication/test_shared_configuration
|Consistent | yes
|Test Execution | 3/3 executions failed
|Cases Fails | 3
|Summary | On `test_push_shared_config` when it called to `check_push_shared_config`. 
|Error message| 'Could not find the remoted key loading log'

__________________________________________________________________________________________________________________________

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_agent_communication/test_shared_configuration` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-20

I was unable to reproduce the described error in my testing environment.
Used Wazuh-QA branch: `1516-4.2.0-full-green`
Test results with the default modules enabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_shared_configuration_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6847951/test_shared_configuration_local_r1.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_shared_configuration_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6847953/test_shared_configuration_local_r2.log)| 2021-07-20 | Miguel | :yellow_circle: 
|[test_shared_configuration_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6847955/test_shared_configuration_local_r3.log)| 2021-07-20 | Miguel | :yellow_circle:

**Comment by juliamagan** [comment]
## Tests results

||CentOS 8 Manager |Reports|
|:--:|:--:|:--:|
|R1|  🟢    |  [Tests results](https://github.com/wazuh/wazuh-qa/files/6876454/centos_manager_test_shared_configuration_r1.zip) | 
|R2|   🟢    |  [Tests results](https://github.com/wazuh/wazuh-qa/files/6876462/centos_manager_test_shared_configuration_r2.zip)  | 
|R3|  🟢    |   [Tests results](https://github.com/wazuh/wazuh-qa/files/6876465/centos_manager_test_shared_configuration_r3.zip)  |

**Comment by damarisg** [comment]
This issue will be closed because we can't reproduce it.

Test Results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowSharedConfiguration.log](https://github.com/wazuh/wazuh-qa/files/6885984/YellowSharedConfiguration.log)| 2021-07-27 | Seyla| :yellow_circle: 
|[YellowSharedConfiguration2.log](https://github.com/wazuh/wazuh-qa/files/6885982/YellowSharedConfiguration2.log)| 2021-07-27 | Seyla| :yellow_circle: 
|[YellowSharedConfiguration3.log](https://github.com/wazuh/wazuh-qa/files/6885983/YellowSharedConfiguration3.log)| 2021-07-27 | Seyla| :yellow_circle:
