### ISSUE TITLE
Full Yellow Local - Fix Agent simulator Rootcheck class in 4.2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1580]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1516. After some research on https://github.com/wazuh/wazuh-qa/issues/1520, we have detected some errors in the `rootcheck` class in the agent simulator module.

### Description of the error

The rootcheck class did not have its initializer correctly defined, in addition to containing an error in the setup method

### Development

This fix should be developed in a branch from 4.2, and it must be merged in the epic issue full-green branch `1516-4.2.0-full-green`. It will be only necessary to achieve a full green in rootcheck tests due to this change in shared libraries only affect to these tests.

In order to finish this issue the following tasks should be fulfilled:

- [x] Full green in rootcheck tests for every supported OS:
  - [x] test_rootcheck 
- [x] Documentation of any important change done for these tests or the used tools
- [x] Merge with `1516-4.2.0-full-green`

**Comment by snaow** [comment]
Merged in https://github.com/wazuh/wazuh-qa/pull/1581

Closing.
