### ISSUE TITLE
Fix `test_files/test_report_changes/test_disk_quota_values.py` in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1582]
## Description

| Related issue |
|--|
| #1516  #1539 |

|Development branch|
|:--:|
|1582-disk-quota-fix|

When it comes to starting with the test fixture, there is some information that can help you:
```
Module: File Integrity Monitoring
Target: Manager and Agent   
OS: Linux
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_fim/test_files/test_report_changes/test_disk_quota_values.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed |   [get_configuration25-tags_to_apply0] [get_configuration29-tags_to_apply0]
| Summary | `test_disk_quota_values.py` does not work properly for values of 7MB or higher 
| Error message |  "TimeoutError: Did not receive expected "The maximum configured size for the ... folder has been reached, ..." event."

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
   We have found out that test assumes that the folder being monitored has a size greater than the size limit entered. We need that the test creates a file with a bigger size.
- [x] Fix the test: The test needs to work for values of 7MB or higher.
- [x] Full Green/Yellow in `test_files/test_report_changes/test_disk_quota_values.py`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1613
