### ISSUE TITLE
ITs logtest use of verbose mode

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#1584]
Hello team,

In order to test the new feature of Logtest that allows it to use the `verbose` mode to debug the rules (see [Wazuh-logtest: verbose mode #9204](https://github.com/wazuh/wazuh/pull/9204), we will create the following Integration tests:

- [x] Test rule match case if the `rules_debug` option is omitted
- [x] Test rule match case  if the `rules_debug` option is set to `true`
- [x] Test rule match case  if the `rules_debug` option is set to `false`
- [x] Test rule match case  if the `rules_debug` option is erroneous (string)
- [x] Test rule match case  if the `rules_debug` option is erroneous (number)
- [x] Test rule match case  if the `rules_debug` option is erroneous (object)
- [x] Test rule match case  if the `rules_debug` option is erroneous (array)
- [x] Test rule match case  if the `options` field is erroneous (boolean)
- [x] Test rule match case  if the `options` field is erroneous (array)
- [x] Test rule match case  if the `options` field is erroneous (number)
- [x] Test rule match case  if the `options` field is erroneous (string)

Regards,
Juan Cabrera

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1587
