### ISSUE TITLE
Full Yellow Local - Deprecate use of `authd_sim.py`

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1585]
## Description

| Related issue |
|--|
| #1516 #1521  |

During research #1493, we found out that `agentd` tests were failing. In issue #1521 we can see more information about the tests that are failing. 

We could see that the tests are using `authd_sim.py` to simulate the connection with the manager. This is not correct, we should check the connection to a real manager. In this issue, we are going to modify the tests that use `authd_sim.py`.

### Affected tests

| Active Response | Agentd | WPK |
|:--:|:--:|:--:|
| `test_active_response\test_execd\test_execd_firewall_drop.py`| `test_agentd\test_agent_auth_enrollment.py` | `test_wpk\test_wpk_agent.py`|
| `test_active_response\test_execd\test_execd_restart.py`| `test_agentd\test_agentd_enrollment_params.py`| |
| | `test_agentd\test_agentd_multi_server.py` | |
| | `test_agentd\test_agentd_parametrized_reconnections.py` | |
| | `test_agentd\test_agentd_reconnection.py` | |

## Development

- [ ] Create a method for the agent to connect to a real manager.
- [ ] Change affected tests.
- [ ] Full Green/Yellow in affected tests.
- [ ] Documentation  of any important change done for these tests or the used tools.
- [ ] Merge with `1516-4.2.0-full-green`.

**Comment by juliamagan** [comment]
Until refactoring and this issue are done, we have decided to delete `TLSv1_1` test case as it is described in issue #1521 and PR https://github.com/wazuh/wazuh-qa/pull/1629.

**Comment by damarisg** [comment]
We decided to close them.
