### ISSUE TITLE
Fix `test_agentd/test_agentd_state_config.py`

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1588]
## Description

| Related issue |
|--|
| #1516 #1521 |

|Development branch|
|:--:|
|1588-agentd-state-config-test-fix|

When it comes to starting with the test fixture, there is some information that can help you:
```
Module: Agentd
Target: Agent   
OS: Windows
```
I add some information obtained while researched the logs that failed.

|  Type | Description  |
|--|--|
|Test Path | test_agentd/test_agentd_state_config.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed |   All (invalid values and one valid value)
| Summary | `test_agentd_state_config.py` is not starting the Wazuh service properly
| Error message |  " AssertionError: assert False is not False where False = check_if_process_is_running('wazuh-agentd')'"

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: The test needs to expect ValueError when it tries to start Wazuh with invalid values.
- [x] Full Green/Yellow in `test_agentd/test_agentd_state_config.py`. 

   The tests are fixed. However, they might fail because Wazuh is not showing error messages. There is an issue opened to fix this: https://github.com/wazuh/wazuh/issues/8746

- [x] Merge with `1521-full-green-agentd-fix`

**Comment by juliamagan** [comment]
Once we solved the problem of managing the `control_service` error, the test only fails in the `Default value` test case, it can't connect to the server.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1592
