### ISSUE TITLE
Create a tool to launch the integration tests and get the results

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1590]
We want to develop a tool to launch wazuh-qa tests. To do so, we are going to start from an already deployed and provisioned environment, in which it is only necessary to launch the tests, obtain the results and format them to give an output easily readable by the end-user.

This execution will be remote since it has to be launched in an environment. To do this, we will use the Ansible module, implemented during the qa_provisioning stage.

We propose to implement the following design:

![running_test_class_diagram](https://user-images.githubusercontent.com/23462183/125955580-750d477b-6068-4cda-a3d8-e647b0b591fd.png)

**Comment by jmv74211** [comment]
## First conceptual model

With the following design, we propose to build a class structure that is versatile when it comes to launching different types of tests. Currently, we are only using pytest, but in the future, we may use some additional testing framework.

The goal is to be able to launch a process that receives information about the tests we want to run, executes those tests and returns the results in an easy to understand format.

![running_test_class_diagram](https://user-images.githubusercontent.com/23462183/125954601-ca3b8443-d0e9-4abf-8d48-a1b3f09e6b8a.png)

**Comment by JoseAntonioMHerrera** [comment]
State update: right now the implementation has achieved the execution of one set of tests in the remote host and the storage of the result in an html file.
