### ISSUE TITLE
Create qa-ctl tool to launch the process of infrastructure deployment, provisioning and test execution.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1591]
The flow diagram of the `qactl` tool will look like the following picture:
![image](https://user-images.githubusercontent.com/22987701/127351175-fdc00a7d-91a2-4746-b2a6-b9dee6172f84.png)

The tool will read a `yaml` file with all the VMs and containers to create, the Wazuh components to install, and which tests are going to be executed.

**Comment by antoniomanuelfr** [comment]
We have to approach to solve the problem:

- Use a combination of scripts that will read smaller configuration files created with the contents of the main configuration file. The script will execute the `infrastructure`, `provisioning` and/or `qa_run_test` scripts. 
 
- Use the objects developed in the issues and let `qactl` be the only one in charge of executing the different tasks. 

We are going to start with the second one, as it's easier to develop, and if we detect that there is a scalability problem using this approach, we will move to the first.

**Comment by antoniomanuelfr** [comment]
Right now, we have a first working tool in the following branch: https://github.com/wazuh/wazuh-qa/tree/qa-ctl
We have found the following issues that need to be fixed in this first iteration:

- [ ] Docker assigns IP dinamically
- [ ] When a VM is destroyed, the SSH fingerprint is not removed from `authorized_hosts`, causing the following failure:
 ```
TASK [Create None/wazuh path] **************************************************
fatal: [10.2.0.3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: 
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:O7NzwSNf0OvmtyQajn74u7ktz7177CvkJ90LfuAq68k.
Please contact your system administrator.
Add correct host key in /home/antoniomanuelfr/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/antoniomanuelfr/.ssh/known_hosts:10
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
UpdateHostkeys is disabled because the host key is not trusted.
vagrant@10.2.0.3: Permission denied (publickey,password).", "unreachable": true}
 ```

**Comment by antoniomanuelfr** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1696
