### ISSUE TITLE
Create Wazuh provisioning elements and flow to QACTL

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1594]
## Description
This issue aims to create all elements, classes, methods, etc. related to the Wazuh provisioning. 
Using the design shown in the main [issue](https://github.com/wazuh/wazuh-qa/issues/1534#issuecomment-874877973), we are going to implement with python everything we need.

![image](https://user-images.githubusercontent.com/60003131/125426780-48731b97-f6c3-4940-9bf3-6c038b18b85b.png)

## To do list

- [x] WazuhDeployment
  - [x] ManagerDeployment
  - [x] AgentDeployment
- [x] WazuhInstallation
  - [x] WazuhSources
  - [x] WazuhPackage
    - [x] LocalPackage
    - [x] S3Package

This last part is not really necessary at this stage because the tests already have tools to modify the Wazuh configuration, but in order to have a good design, we want to implement the possibility to be able to manage the configuration also from here, for example, to configure a cluster in the future:
- WazuhConfiguration
  - ManagerConfiguration
  - AgentConfiguration

**Comment by jotacarma90** [comment]
I have pushed some files containing the WazuhDeployment class, which is in charge of deploying to the instantiated machines. At the moment it is possible to generate a complete flow to have ready the playbooks that make the deployment of a manager and an agent.
I have created a small test file, to generate a complete flow with a virtual machine and an inventory already set up.
https://github.com/wazuh/wazuh-qa/commit/67dfaa4b53bc69939395c75b762868bf6d289775

**Comment by jotacarma90** [comment]
### Test for WazuhDeployment

We have already finished the WazuhDeployment module for a base case. 
Commit with this changes: https://github.com/wazuh/wazuh-qa/commit/c52bb8b1348708348608d2af02e92b39766e36e7
The steps and requirements to see how it works are:
- You need to have the inventory file already generated (the qa_provisioning.py is taken care of by making use of the AnsibleInventory module). For this test:
```
all:
  children:
    agent:
      hosts: 
        10.2.0.12
    server:
      hosts: 
        10.2.0.13
  hosts:
      10.2.0.12:
        ansible_connection: ssh
        ansible_host: 10.2.0.12
        ansible_password: vagrant
        ansible_port: 22
        ansible_user: vagrant

      10.2.0.13:
        ansible_connection: ssh
        ansible_host: 10.2.0.13
        ansible_password: vagrant
        ansible_port: 22
        ansible_user: vagrant
```

- We raise the machines we are going to use (the qa_deployment.py module takes care of it), in this case I will use two vagrant machines:

```
vagrant up ubuntumanager
vagrant up ubuntutest
```
Vagrantfile:
```

config.vm.define :ubuntutest do |ubuntutest|
    ubuntutest.vm.box = "bento/ubuntu-18.04"
    ubuntutest.vm.network :private_network, ip: ip_ubuntu_test
    ubuntutest.vm.hostname = "ubuntutest"
    ubuntutest.vm.synced_folder './', '/vagrant',
      type: "nfs",
      linux__nfs_options: ['rw','no_subtree_check','no_root_squash','async']
    ubuntutest.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1]
    end
  config.vm.define :ubuntumanager do |ubuntumanager|
    ubuntumanager.vm.box = "bento/ubuntu-20.04"
    ubuntumanager.vm.network :private_network, ip: ip_ubuntu_manager
    ubuntumanager.vm.hostname = "ubuntumanager"
    ubuntumanager.vm.synced_folder "./", "/vagrant",
      type: "nfs",
      linux__nfs_options: ['rw','no_subtree_check','no_root_squash','async']
    ubuntumanager.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
      vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1]
    end
```
   
- We also need to have the path with the installation files (package or sources) already downloaded in the machine where the deploy is going to be done. I manually copied the packages needed for both installations (This is taken care of by WazuhInstallation):
```
/home/vagrant/wazuh-agent_4.1.5-1_amd64.deb
/home/vagrant/wazuh-manager_4.1.5-1_amd64.deb
```

- Now I have created a small script that calls WazuhDeployment to install a manager and an agent:
```
from wazuh_testing.provisioning.wazuh_install.ManagerDeployment import ManagerDeployment
from wazuh_testing.provisioning.wazuh_install.AgentDeployment import AgentDeployment


my_wazuh_server_deployment = ManagerDeployment('/home/vagrant/wazuh-manager_4.1.5-1_amd64.deb', None, 'linux', '/tmp/ansible_inventory.yaml', 'package', '/var/ossec', '10.2.0.13', 'server')
my_wazuh_server_deployment.install()

my_wazuh_agent_deployment = AgentDeployment('/home/vagrant/wazuh-agent_4.1.5-1_amd64.deb', None, 'linux', '/tmp/ansible_inventory.yaml', 'package', '/var/ossec', '10.2.0.12', 'agent')
my_wazuh_agent_deployment.install()
```

- Output:
```
PLAY [server] ******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.2.0.13]


ASK [Install Wazuh Agent from .deb packages] **********************************
changed: [10.2.0.13]


LAY RECAP *********************************************************************
10.2.0.13                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [agent] *******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.2.0.12]

ASK [Install Wazuh Agent from .deb packages] **********************************
[WARNING]: Updating cache and auto-installing missing dependency: python-apt

changed: [10.2.0.12]


LAY RECAP *********************************************************************
10.2.0.12                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1683
