### ISSUE TITLE
Create QA framework provisioning module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1595]
## Description
We need to create and adapt a tool that allows us to generate the QA framework required, for this, we need to deploy it in the indicated environment. More info in the main [issue](https://github.com/wazuh/wazuh-qa/issues/1534) QACTL.

![image](https://user-images.githubusercontent.com/60003131/125435909-00b8a666-3146-4436-8b0f-7fb87d038214.png)

## To do list

- [x] QAFramework
  - [x] (func) install_dependencies
  - [x] (func) install_framework
  - [x] (func) download_qa_repository

**Comment by JoseAntonioMHerrera** [comment]
The current state of the module allows to install dependencies stored in the requirements.txt and as a previous step installs pip3. Also allows to install the wazuh_testing framework and set the environment to execute the tests.

**Comment by JoseAntonioMHerrera** [comment]
Update: the QAFramework.py that holds the class definition and his methods have been pushed to this branch: 1596-ansible-inventory-generation [QAFramework](https://github.com/wazuh/wazuh-qa/commit/4bc72be2c3a94cadadfe0291a1238541010623b2)

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1683
