### ISSUE TITLE
[Staging/Developing] Possible leak/segfault on Windows with vuln-detector (Manager and Windows)

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-qa#160]
# Testing: Vulnerability detector

| Version | Revision | Branch |
| --- | --- | --- |
| 3.11.0 | 31100 | [vuln-windows](https://github.com/wazuh/wazuh/tree/vuln-windows) |

Hello team,

We have launched stress test over this PR https://github.com/wazuh/wazuh/pull/2787 with custom configuration on manager side that I will paste below, this test results in a broken windows agent.

### Manager
**Configuration**
[managerConf.txt](https://github.com/wazuh/wazuh-qa/files/3713355/managerConf.txt)

#### CPU
![image](https://user-images.githubusercontent.com/10661307/65951089-9ecfc580-e43f-11e9-99cc-bc1b4d9bff15.png)

#### FD
![image](https://user-images.githubusercontent.com/10661307/65951102-a4c5a680-e43f-11e9-9966-a17a74eaa85b.png)

#### RSS
![image](https://user-images.githubusercontent.com/10661307/65951135-b0b16880-e43f-11e9-9b9c-26fb3ae539c1.png)

### Example of RSS on 3.10.2 (Comparing memory consumption) (Default stress configuration).
![image](https://user-images.githubusercontent.com/10661307/65951218-e8b8ab80-e43f-11e9-84f8-43647d861343.png)

### Agent CentOS
**Configuration**
[centosAgentConf.txt](https://github.com/wazuh/wazuh-qa/files/3713359/centosAgentConf.txt)

#### CPU
![image](https://user-images.githubusercontent.com/10661307/65952463-3b936280-e442-11e9-9e5a-e83d22e413ab.png)

#### FD
![image](https://user-images.githubusercontent.com/10661307/65952478-451cca80-e442-11e9-8339-fdb71363990c.png)

#### RSS
![image](https://user-images.githubusercontent.com/10661307/65952497-49e17e80-e442-11e9-9f4d-6c0f4c0b1560.png)

### Agent Ubuntu
**Configuration**
[ubuntuAgentConf.txt](https://github.com/wazuh/wazuh-qa/files/3713365/ubuntuAgentConf.txt)

#### CPU
![image](https://user-images.githubusercontent.com/10661307/65952523-52d25000-e442-11e9-8fad-3b4f4b52c1a1.png)

#### FD
![image](https://user-images.githubusercontent.com/10661307/65952531-57970400-e442-11e9-8642-5b4e5036749b.png)

#### RSS
![image](https://user-images.githubusercontent.com/10661307/65952539-5bc32180-e442-11e9-9caa-a0aa242fa6c0.png)

### Agent Windows
**Configuration** (All modules stressed)
[winAgentConf.txt](https://github.com/wazuh/wazuh-qa/files/3713373/winAgentConf.txt)

#### CPU
![image](https://user-images.githubusercontent.com/10661307/65948211-17338800-e43a-11e9-9cbc-e949cb6facb9.png)

#### FD
![image](https://user-images.githubusercontent.com/10661307/65948192-0daa2000-e43a-11e9-9c1b-1fb06413dd0f.png)

#### RSS
![image](https://user-images.githubusercontent.com/10661307/65948185-07b43f00-e43a-11e9-9294-1d56beff3ccc.png)

### Summary
We could deduce three things on such graphics:
- Modulesd manager increases x20 its memory consumption, doesn't seem a leak but its kind a lot ~200MB.
- Modulesd manager increases x80 its memory consumption in a specific period of time, it's quite memory around ~800MB .
- Windows agent stops working after some hours of being launched (we need to do more research about that).

Regards.

**Comment by crolopez** [comment]
Please, repeat the test by disabling all components except Syscollector. 

Configuration example:

``` XML
<ossec_config>
  <client>
    <server>
      <address>0.0.0.0</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>
  <rootcheck>
    <disabled>yes</disabled>
  </rootcheck>
  <sca>
    <enabled>no</enabled>
  </sca>
  <syscheck>
    <disabled>yes</disabled>
  </syscheck>
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>30</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>
  <wodle name="cis-cat">
    <disabled>yes</disabled>
  </wodle>
  <wodle name="osquery">
    <disabled>yes</disabled>
  </wodle>
  <active-response>
    <disabled>yes</disabled>
  </active-response>
  <logging>
    <log_format>plain</log_format>
  </logging>
</ossec_config>
```

The PR only make changes in Syscollector for Windows. If there is an error, it will be here.

**Comment by okynos** [comment]
Hello team,

We have repeated the test of vulnerability detector with the configuration of @crolopez, the agent now seems to keep connected, but the manager still consuming more memory than analysisd.
We attach some charts:
### Windows agent RSS
![image](https://user-images.githubusercontent.com/10661307/66028132-bde05d00-e4fc-11e9-98d2-43e45e937380.png)

### Manager RSS
![image](https://user-images.githubusercontent.com/10661307/66028145-c0db4d80-e4fc-11e9-84f5-a650434a2dfe.png)

We will still testing on Windows to find the possible error.

Regards.

**Comment by okynos** [comment]
We attach the errors found on manager side [ossecError.log](https://github.com/wazuh/wazuh-qa/files/3680235/ossecError.log).
On agent side we only found the following error 
```
wazuh-modulesd:syscollector[5992] syscollector_windows.c:1348 at sys_hw_windows(): ERROR: Serial Num
ber not available in SMBIOS firmware table.
```

Regards.

**Comment by okynos** [comment]
Hello team,

We have noticed that Windows agent of branch 3.11 stops in some cases that we are trying to reproduce, below we attach all data that we have to try to solve such problem:
[logsAndConfs.zip](https://github.com/wazuh/wazuh-qa/files/3685245/logsAndConfs.zip)

We are trying to find the problem with drmemory and debug compiled agent.

Regards.

**Comment by okynos** [comment]
Hello team,

We will add here our last tests over `3.11` branch and `3.10.2` to compare:

#### RSS manager 3.11, Vulnerability detector + Logcollector
![image](https://user-images.githubusercontent.com/10661307/66198342-7e507700-e69c-11e9-87cc-9d20f5809516.png)

#### RSS winagent 3.11, Logcollector
![image](https://user-images.githubusercontent.com/10661307/66198380-91fbdd80-e69c-11e9-96fd-011f84c2a12b.png)

----
#### RSS manager 3.11, Syscheck
![image](https://user-images.githubusercontent.com/10661307/66198438-b8217d80-e69c-11e9-8929-d6cef31528f4.png)

#### RSS winagent 3.11, Syscheck
![image](https://user-images.githubusercontent.com/10661307/66198429-b35cc980-e69c-11e9-8a69-be4c1518fc74.png)

---
#### RSS manager 3.11, Rootcheck
![image](https://user-images.githubusercontent.com/10661307/66198529-e606c200-e69c-11e9-9471-e47554e8b507.png)

#### RSS winagent 3.11, Rootcheck
![image](https://user-images.githubusercontent.com/10661307/66198513-ddae8700-e69c-11e9-9783-2042cf68d994.png)

---
#### RSS manager 3.11, SCA
![image](https://user-images.githubusercontent.com/10661307/66199014-05eab580-e69e-11e9-8d1f-7d8fc89afe31.png)

#### RSS winagent 3.11, SCA
![image](https://user-images.githubusercontent.com/10661307/66199007-02572e80-e69e-11e9-8e34-533cf5000c32.png)

---
#### RSS manager 3.11, The rest
![image](https://user-images.githubusercontent.com/10661307/66199066-2155c080-e69e-11e9-8bbb-2acf3bfb213e.png)

#### RSS winagent 3.11, The rest
![image](https://user-images.githubusercontent.com/10661307/66199060-1d29a300-e69e-11e9-8d3c-18890268f1d7.png)

----
#### RSS manager 3.11, All
![image](https://user-images.githubusercontent.com/10661307/66199142-4813f700-e69e-11e9-9eca-6fc423436cd9.png)

#### RSS winagent 3.11, All
![image](https://user-images.githubusercontent.com/10661307/66199132-43e7d980-e69e-11e9-8b73-89dd3252443e.png)

---
#### RSS manager 3.11, last changes from 3 October, All modules
![image](https://user-images.githubusercontent.com/10661307/66199264-81e4fd80-e69e-11e9-8ecf-28159d36d5d9.png)

#### RSS winagent 3.11, last changes from 3 October, All modules
![image](https://user-images.githubusercontent.com/10661307/66199254-7e517680-e69e-11e9-8617-d2b78cdd718e.png)

#### RSS agent ubuntu 3.11, last changes from 3 October, All modules
![image](https://user-images.githubusercontent.com/10661307/66199282-8d382900-e69e-11e9-907e-f952254a491f.png)

#### RSS agent centos 3.11, last changes from 3 October, All modules
![image](https://user-images.githubusercontent.com/10661307/66199308-9aedae80-e69e-11e9-9d98-87c5e0a7c401.png)

---
#### RSS manager 3.10.2, All modules
![image](https://user-images.githubusercontent.com/10661307/66199352-b35dc900-e69e-11e9-97f0-3699ba182791.png)

#### RSS winagent 3.10.2, All modules
![image](https://user-images.githubusercontent.com/10661307/66199345-b062d880-e69e-11e9-9652-605243426ed6.png)

Regards.

**Comment by okynos** [comment]
Hello team,

After last fixes on `vuln-windows` we launched another test with the following results:

#### CPU manager 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319455-70f5ef80-e91d-11e9-8285-2e578c6177cb.png)

#### FD manager 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319367-473cc880-e91d-11e9-90a2-0906098d4420.png)

#### RSS manager 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319297-25dbdc80-e91d-11e9-8860-d84df80c9a31.png)

---

#### CPU CentOS agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319653-cc27e200-e91d-11e9-9a8b-710349110fa8.png)

#### FD CentOS agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319630-c16d4d00-e91d-11e9-84d6-028719f6747c.png)

#### RSS CentOS agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319615-b87c7b80-e91d-11e9-9c0d-b359820e62cb.png)

---

#### CPU Ubuntu agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319680-d813a400-e91d-11e9-9cbe-ad8adb4c2dc6.png)

#### FD Ubuntu agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319709-e2ce3900-e91d-11e9-8cda-92baf5b2a504.png)

#### RSS Ubuntu agent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319742-ed88ce00-e91d-11e9-813b-797b64d5cf13.png)

---

#### CPU winagent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319771-f7aacc80-e91d-11e9-8570-986b9b0fcbe8.png)

#### FD winagent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319790-00030780-e91e-11e9-9303-797a3fbfbb9d.png)

#### RSS winagent 3.11.0, vuln-windows
![image](https://user-images.githubusercontent.com/10661307/66319824-085b4280-e91e-11e9-81b4-f07ecc37cb97.png)

---

**Summary**
We can see on manager memory that modulesd have too much memory in use, around 200MB, this memory sounds quite big.

Regards.

**Comment by okynos** [comment]
Hello team,

We will paste here the results of stress test with commit `7aa6c9b`:

#### CPU manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576385-eceb7400-eb77-11e9-80fb-8d73bf03e304.png)

#### FD manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576399-f248be80-eb77-11e9-93dc-6bdb7a4cc63b.png)

#### RSS manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576406-f5dc4580-eb77-11e9-88e3-688bb68d9b67.png)

---

#### CPU CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576319-d47b5980-eb77-11e9-95b2-48cc49b1b044.png)

#### FD CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576327-d80ee080-eb77-11e9-8933-291edf8066e7.png)

#### RSS CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576311-cf1e0f00-eb77-11e9-8fd3-3c699b549e85.png)

---

#### CPU Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576245-a85fd880-eb77-11e9-8b8a-67cad1e52ea6.png)

#### FD Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576255-ad248c80-eb77-11e9-958b-326251c16dc3.png)

#### RSS Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576267-b281d700-eb77-11e9-86b9-921bb0259b76.png)

---

#### CPU winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576104-68005a80-eb77-11e9-8793-d9101d792c30.png)

#### FD winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576072-5ae36b80-eb77-11e9-84e8-1488f10d19ab.png)

#### RSS winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66576060-5454f400-eb77-11e9-8545-c6b327d8a8e7.png)

---

**Summary**
On manager and winagent graphics we could see one break point, this point is when we loaded the configuration of this issue, to stress only vulnerability detector, we could see that manager consumes lot of memory among a long period of time, I think that such behaviour is undesirable. 

We will post later tests with special stress script designed to stress vuln-detector on manager side.

Regards.

**Comment by okynos** [comment]
Hello team,

We will paste here the results of stress test with commit `4e06357`, in this test we have launched a special script that stress vuln-detector with the following process:
1. Register agent with agent-auth.
2. Restart agent (It will ask for vulnerability database).
3. Wait one minute.
4. Repeat from point 1.

#### CPU manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66641044-42785d00-ec1a-11e9-9d9b-ce3a60afdc25.png)

#### FD manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66641079-515f0f80-ec1a-11e9-8679-0eae21ed3e33.png)

#### RSS manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66641118-62a81c00-ec1a-11e9-827e-0b1c0a73cd43.png)

---

#### CPU CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66647023-0fd56100-ec28-11e9-892f-e2c569f0e001.png)

#### FD CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66647005-0946e980-ec28-11e9-81a3-ce3ecde502c9.png)

#### RSS CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66647001-02b87200-ec28-11e9-9862-6ded71cc4481.png)

---

#### CPU Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646991-fd5b2780-ec27-11e9-8202-35d357c55c88.png)

#### FD Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646977-f502ec80-ec27-11e9-8378-b9d58ad1405c.png)

#### RSS Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646968-f03e3880-ec27-11e9-9b88-38751e097cb0.png)

---

#### CPU winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646951-e6b4d080-ec27-11e9-8fd0-6a05fd9df650.png)

#### FD winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646945-e0265900-ec27-11e9-8880-19ffee078e73.png)

#### RSS winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/66646934-d866b480-ec27-11e9-8878-10f139c9de72.png)

---

**Summary**
The manager seems to consumes less memory than other tests, we will launch another standard test to confirm such behaviour.
The memory increase on agent matches with the moment that the script stops, so it's normal behaviour.

Regards.

**Comment by okynos** [comment]
Hello team,

We have done `3.11.0-rc2` tests (stress vuln-detector avoided to stress syscheck) and we have obtained the following charts:


#### CPU manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077484-a4434480-f18f-11e9-897c-985d38bda926.png)

#### FD manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077429-8d045700-f18f-11e9-99d5-1b72312eb463.png)

#### RSS manager 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077401-807ffe80-f18f-11e9-9bb9-cdcaf14139a0.png)

---
---
---

#### CPU CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077666-fd12dd00-f18f-11e9-9d8e-c9a1921de2f1.png)

#### FD CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077635-f1271b00-f18f-11e9-8207-7744948cff80.png)

#### RSS CentOS agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077609-e40a2c00-f18f-11e9-94ab-978169233e0d.png)

---
---
---

#### CPU Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077570-cfc62f00-f18f-11e9-87b7-1b8e81a70598.png)

#### FD Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077548-c4730380-f18f-11e9-9562-85b9d985119a.png)

#### RSS Ubuntu agent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67077518-b6bd7e00-f18f-11e9-9bb5-4e8b36a7c003.png)

---
---
---

#### CPU winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67076195-f9318b80-f18c-11e9-8005-471c3a05febc.png)

#### FD winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67076176-ecad3300-f18c-11e9-9ca6-64fc9d029068.png)

#### RSS winagent 3.11.0
![image](https://user-images.githubusercontent.com/10661307/67076152-e028da80-f18c-11e9-82ab-fdcea906fad7.png)


---
---
---

**Summary**
We could see that the memory consumption on manager side decreases a lot, it's part on the great job of @crolopez and @wazuh/core great job on this way, congrats.
We also couldn't see any descriptor or memory leak on the rest of components, yay!.


Regards.

**Comment by alberpilot** [comment]
Hello team

  The stress test had an improvement that consists of stopping the stress scripts. We launched a new test on Friday, 08 Nov. The test runs over 80% of the test time and the other 20% occurs when the stress scripts are stopped. Our goal is to see how the CPU, FD and memory graphics decrease due to the free resources. 

  The following graphics show the Windows agent:

### Windows agent CPU

![monitor-winagent-ID0_B9_Test_stress_windows_Agent-staging_CPU(%)](https://user-images.githubusercontent.com/3830293/68612917-e4ab8f00-04bd-11ea-92bd-dd36b97addac.png)

### Windows agent FD

![monitor-winagent-ID0_B9_Test_stress_windows_Agent-staging_FD](https://user-images.githubusercontent.com/3830293/68613127-5d125000-04be-11ea-97d1-e3cde83446b7.png)


### Windows agent RSS

![monitor-winagent-ID0_B9_Test_stress_windows_Agent-staging_RSS(KB)](https://user-images.githubusercontent.com/3830293/68613128-5daae680-04be-11ea-8712-3efe5363ec72.png)

We see the CPU usage as normal. But the memory grows after the script stopping and the file descriptors are not released. We will investigate this. 

Best regards, 
Alberto R

**Comment by alberpilot** [comment]
Hello team

  We made two test executions, this time, with a one-hour duration. Bellow the details:

### Windows agent: ~45 minutes stressed, ~15 non-stressed

![example1](https://user-images.githubusercontent.com/3830293/68772175-a29f5c00-0629-11ea-8d82-e043f5abf4d4.png)

As we can see in the graphic, the Wazuh agent uses a constant amount of memory even if the agent is not stressed (the scripts that force the stress are stopped the final ~15 minutes).

The Wazuh agent releases the used memory, but once freed it can remain as residual memory assigned to the process.

We wanted to see if we could force the memory deallocation, force the OS to claim that memory. We executed the same test but, this time, when the scripts stopped, this Python command would be executed: `python -c "import time; a = [None]*66666666; time.sleep(3600)"`. This python process allocates about 4GB of memory. The VM used had **4GB** of memory. 

**Second test results:**

![example2](https://user-images.githubusercontent.com/3830293/68772872-d9c23d00-062a-11ea-82f9-48c0cf6964eb.png)

In the period in which the Wazuh agent is supposed to free up the memory, after the python command execution, it looks like if claim the same memory amount that it had several times. 

We need to investigate this behavior. 
Best regards, 
Alberto R
