### ISSUE TITLE
Implement the documentation tree generator logic

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1606]
As part of the epic [Overall improvements for integration tests documentation](https://github.com/wazuh/wazuh-qa/issues/1536) we need to implement a logic to create the tree logic of the corresponding groups.
This logic must:

- Walk each folder and create an equivalent structure for the test documentation
  - Only the folder that match with a search list must be considered.
  - Floders that match with an ignore list must be ignored.

- Parse, if exists, the README file of each folder.
  - For each README file a Group will be created
    - The group will be dumped into a json and yaml file.
    - A group can belong to other group
    - The group will contain ID, name, belong_group and description.

- Call the module parser for each test file found.
    - It must hand the group name/id to the module parser

**Comment by MiguelazoDS** [comment]
As a first approach, we generated a docs tree that will contain all the files with the information extracted from markdown and python script files.

![image](https://user-images.githubusercontent.com/13010397/125869667-aa02c7cc-c61b-40c7-a1c0-1a4bad2a117b.png)
 
As it is now, the JSON files that can be seen in the screenshot are meant to be the main file that contains information about a group name and subgroups related to this major group. For this particular example, some dummy readme.md was created (most of them empty) to generate a JSON file with the following content.
 
![image](https://user-images.githubusercontent.com/13010397/125870029-8ceed185-ca49-4cd9-9b19-fc7e7e1af9c8.png)

The purpose of tracking the subgroup information is to create a relationship between the documentation of the tests avoiding duplicated information and provide an easy way to feed index into the UI.
