### ISSUE TITLE
Develop an automatic test/tool to detect new security flaws in the embedded python or dependencies

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1612]
Hi team,

We are looking to develop a tool or test that allows us to automate the process of analyzing security flags in the Python embedded with Wazuh and in the installed deps.

The goal is to be able to launch this tool or test manually every X days at first and finally automate this process for each PR in the main repo.

For the development of this tool or test, we can use tools such as [Safety](https://pypi.org/project/safety/) or any other that allows us to automate the process and generate a report to later analyze it and determine if there is any new vulnerability.

The tool should review the requeriments.txt file for possible vulnerabilities, in addition to the current Python version, to determine if there is any type of warning.

Regards

**Comment by Kondent** [comment]
# Update
I'm currently waiting for the related issue to be approved and merged (https://github.com/wazuh/wazuh-qa/issues/1615) so I can continue as we discussed with the team.
Current status: **blocked**
