### ISSUE TITLE
Fix 'test_remoted/test_agent_communication/test_multi_agent_protocols_communication' tests in 4.2

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1618]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530 |

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case 1:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_agent_communication/test_multi_agent_protocols_communication
|Consistent | no
|Test Execution | 3/6 executions failed
|Cases Fails | 6
|Summary | On `test_multi_agents_protocols_communication` when it called to `check_queue_socket_event`. It fails intermitently when the tests are executed quickly after finishing a successful execution.
|Error message| 'Could not find the expected event in queue socket'

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_agent_communication/test_multi_agent_protocols_communication` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by DProvinciani** [comment]
I spent some time trying to reproduce the issue. It seems to happen when the `test_multi_agent_protocols_communication` tests are executed repeatedly (check the image).

![image](https://user-images.githubusercontent.com/5703274/126489645-c04b177c-3128-4f3c-8ee1-12c557df39ab.png)

Doing some root cause analysis, I identified that the test implements a `man in the middle` mechanism to monitor the messages that are sent by the simulated agents to the manager's `queue` socket. This socket is monitored by the Wazuh daemons as well. So, the socket ends up being used by: `analysisd`, `remoted`, `logcollector`, and `test_multi_agent_protocols_communication`.

Apart from that, is good to mention that during the `man in the middle` initialization, the socket is duplicated in order to have a backup of the original socket. After that, the components mentioned before will try to use the `queue` socket, except `analysisd` because the daemon is stopped by the test.

![image](https://user-images.githubusercontent.com/5703274/126492054-17df7c22-aeb5-43d4-9ee8-6eebbdffee37.png)

So, it is at this point wherein the Wazuh logs appear some messages reporting errors to use the socket.

```
2021/07/20 18:44:04 wazuh-logcollector: ERROR: socketerr (not available).
2021/07/20 18:44:04 wazuh-logcollector: ERROR: Unable to send message to 'queue/sockets/queue' (wazuh-analysisd might be down). Attempting to reconnect.
2021/07/20 18:44:04 wazuh-logcollector: INFO: Successfully reconnected to 'queue/sockets/queue'
```

I'm researching to see whether this usage of the socket by multiples daemons could be causing the issue.

**Comment by damarisg** [comment]
After merging #1625, it works successfully.

Test Results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowMultiAgentProtocolComunication.log](https://github.com/wazuh/wazuh-qa/files/6878250/YellowMultiAgentProtocolComunication.log)| 2021-07-26 | Seyla| 🟢 
|[YellowMultiAgentProtocolComunication2.log](https://github.com/wazuh/wazuh-qa/files/6878251/YellowMultiAgentProtocolComunication2.log)| 2021-07-26 | Seyla| 🟢
|[YellowMultiAgentProtocolComunication3.log](https://github.com/wazuh/wazuh-qa/files/6878252/YellowMultiAgentProtocolComunication3.log)| 2021-07-26 | Seyla| 🟢
