### ISSUE TITLE
Full Yellow in 'test_scan_results' tests of Vulnerability Detector

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1635]
# Description 

After that every test was fixed, we need to check if it on the group works, or needs a fix. 

It should work successfully but you could happen some fails on 
 - test_scan_results/test_debian_inventory_debian_feed
 - test_scan_results/test_redhat_inventory_redhat_feed 
 - test_scan_results/test_ubuntu_inventory_canonical_feed
 - test_scan_results/test_macos_inventory 
 - test_scan_results/test_scan_different_cves
 - test_scan_results/test_scan_nvd_feed 
 - test_scan_results/test_scan_providers_and_nvd_feed 
 
for the issues #1602  and https://github.com/wazuh/wazuh/issues/9309

However, the rest should work successfully

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

## Development
In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_scan_results` for 3 times.

**Comment by mdengra** [comment]
### 2021-07-26

#### Test group: `test_scan_results`

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_scan_results_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6877263/test_scan_results_local_r1.log)| 2021-07-26 | Miguel | :yellow_circle: 
|[test_scan_results_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6877264/test_scan_results_local_r2.log)| 2021-07-26 | Miguel | :yellow_circle: 
|[test_scan_results_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6877266/test_scan_results_local_r3.log)| 2021-07-26 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowScan.log](https://github.com/wazuh/wazuh-qa/files/6884944/YellowScan.log)| 2021-07-27 | Seyla| 🟢 
|[YellowScan2.log](https://github.com/wazuh/wazuh-qa/files/6884945/YellowScan2.log)| 2021-07-27 | Seyla| 🟡 
|[YellowScan3.log](https://github.com/wazuh/wazuh-qa/files/6884946/YellowScan3.log)| 2021-07-27| Seyla| 🟡
