### ISSUE TITLE
 Full Yellow in 'test_providers' tests of Vulnerability Detector 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1637]
# Description 

Once time that every test was fixed, we need to check if it on the 'test_providers' group works, or needs a fix.

We need to know that it could have some fails on
 - 'test_providers/test_providers_update_from_year' 
 - 'test_providers/test_providers_os'

for issues #1602 and wazuh/wazuh#9309

However, the rest should work successfully

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

## Development
In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_providers` for 3 times.

**Comment by mdengra** [comment]
I have had problems of the kind:
```
E   yaml.scanner.ScannerError: mapping values are not allowed here
E     in "/home/vagrant/wazuh-qa/tests/integration/test_vulnerability_detector/test_providers/data/wazuh_providers_multiple_providers.yaml", line 39, column 15
```
Due to improper formatting of the `wazuh_providers_multiple_providers.yaml` file.

**Comment by damarisg** [comment]
Test Results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowProviders.log](https://github.com/wazuh/wazuh-qa/files/6881410/YellowProviders.log)| 2021-07-26 | Seyla| :yellow_circle: 
|[YellowProviders2.log](https://github.com/wazuh/wazuh-qa/files/6881405/YellowProviders2.log)| 2021-07-26 | Seyla| :yellow_circle: 
|[YellowProviders3.log](https://github.com/wazuh/wazuh-qa/files/6881406/YellowProviders3.log)| 2021-07-26 | Seyla| :yellow_circle: 

The tests that failed are [test_providers/test_providers_os](https://github.com/wazuh/wazuh-qa/issues/1562)  and [test_providers/test_providers_update_from_year](https://github.com/wazuh/wazuh-qa/issues/1563) that are blocked by  [FileMonitor because of inconsistent behavior when heavy log activity](https://github.com/wazuh/wazuh-qa/issues/1602) and [Database is locked using Vulnerability Detector](https://github.com/wazuh/wazuh/issues/9309).

Therefore, we have a yellow as a result.

| Status | Reference |
|--|--|
| 🟡 | Passes with warnings AND only tests that are blocked fail |

**Comment by mdengra** [comment]
### 2021-07-27

#### Test group: `test_providers`

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6884278/test_providers_local_r1.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_providers_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6884280/test_providers_local_r2.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_providers_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6884282/test_providers_local_r3.log)| 2021-07-27 | Miguel | :yellow_circle:
