### ISSUE TITLE
 Full Yellow in 'test_feeds' tests of Vulnerability Detector

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1638]
# Description 

Once time that every test was fixed, we need to check if it on the 'test_feeds' group works, or needs a fix.

We need to know that it could have some fails on
 - 'test_feeds/test_download_feeds' 
 - 'test_feeds/test_invalid_type_url_feeds'
 

by the issues #1602 and wazuh/wazuh#9309

However, the rest should work successfully

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

## Development
In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_feeds` for 3 times.

**Comment by mdengra** [comment]
### 2021-07-27

#### Test group: `test_feeds`

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_feeds_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6883599/test_feeds_local_r1.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_feeds_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6883602/test_feeds_local_r2.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_feeds_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6883605/test_feeds_local_r3.log)| 2021-07-27 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
The fails are related to https://github.com/wazuh/wazuh-qa/issues/1542 that is blocked, for that the results is yellow.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ResultsYellowFeeds.log](https://github.com/wazuh/wazuh-qa/files/6893295/ResultsYellowFeeds.log)| 2021-07-28 | Seyla| :yellow_circle: 
|[ResultsYellowFeeds2.log](https://github.com/wazuh/wazuh-qa/files/6893296/ResultsYellowFeeds2.log)| 2021-07-28 | Seyla| :yellow_circle: 
|[ResultsYellowFeeds3.log](https://github.com/wazuh/wazuh-qa/files/6893297/ResultsYellowFeeds3.log)| 2021-07-28 | Seyla| :yellow_circle:
