### ISSUE TITLE
DocGenerator exploratory testing

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1641]
As part of the Epic [1536 ](https://github.com/wazuh/wazuh-qa/issues/1536)we have implemented DocGenerator, a tool capable of finding test files and test functions to parse its documentation blocks comments. We need to perform a complete exploratory testing cycle to validate the correct behavior of the tool.
At least, the following items must be validated:
- Documentation content with text stylizers.
- Different options for the include paths and include regexes.
- Different options for the Ignore paths
- SanityCheck module identifies every Mandatory field missing
- CodeParser field bypass every field not mandatory or optional

**Comment by palaciosjeremias** [comment]
During the exploratory testing the following errors were found that must be fixed:
- [ ] The default output folder isn´t under the git ignore list
- [ ] The configuration file refers to a deprecate option "recursive" for include and ignore paths
- [ ] The output folder isn´t cleaned on each parser run.
- [ ] Empty results after parsing are generating an empty file.
- [ ] Terminal output of the script is too verbose, which makes the warning messages to get lost

**Comment by palaciosjeremias** [comment]
It was identified that the keys in the output structure must avoid white spaces to simplify the parsing into SearchUI. I will be better to:
- [] Change documentation key names to snake_case.

**Comment by MiguelazoDS** [comment]
Some consideration that appears during the implementation of 
- [ ] Evaluate the possibility to move the helper modules to a `lib` directory. 
- [ ] Revise the function is_valid_file. Some conditions may never occur and the return value must be unassigned.
