### ISSUE TITLE
Full Yellow Local - Fix scheduled mode tests

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1648]
## Description

We have noticed that while investigating #1493, all FIM tests were executed in realtime and whodata modes. In order to achieve a full green/yellow when running the tests locally, scheduled mode needs to be investigated and fixed too.

## Research results

|QA branch|
|--|
|[fim-full-yellow-temporary](https://github.com/wazuh/wazuh-qa/tree/fim-full-yellow-temporary)|

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi
Agent | macOS | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.pkg
Agent | solaris | i386 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent_v4.2.0-1.1493-sol11-i386.p5p

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### pytest_args
`--tier 0 --tier 1 --tier 2 --fim_mode=scheduled`

All tests were run on VMs with 2 cores and 2GB of RAM. No tests were ran on managers since FIM tests make no distinctions between agent and manager.

|   |  **Local** |  **Status**|
|:--:|:--: |:--:|
|**Test Execution 1**| [Centos agent](https://github.com/wazuh/wazuh-qa/files/6878330/fim-0.zip) [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6884271/fim-0.zip) |  🔴 |
|**Test Execution 2**| [Centos agent](https://github.com/wazuh/wazuh-qa/files/6878334/fim-1.zip) [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6884273/fim-1.zip) |  🔴 |
|**Test Execution 3**| [Centos agent](https://github.com/wazuh/wazuh-qa/files/6879593/fim-2.zip) [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6884274/fim-2.zip) |  🔴 |

The first execution for Centos has a couple of false positives due to an agent disconnection (the `time_reconnect` was configured to 60 seconds when it should have been higher).

### Development

This fix should be developed in a branch from 4.2, and it must be merged in the epic issue full-green branch 1516-4.2.0-full-green

In order to finish this issue the following tasks should be fulfilled:

### Centos
- [x] #1654 
- [x] #1655
- [x] https://github.com/wazuh/wazuh-qa/issues/1751

### Windows
- [x] #1343 
- [x] #1657
- [x] #1658
- [x] #1660

**Comment by snaow** [comment]
Everything merged into `1539-full-yellow-fim-fix`. 
Continuing in https://github.com/wazuh/wazuh-qa/issues/1539
