### ISSUE TITLE
Fix `test_fim/test_files/test_skip/test_skip.py`

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1654]
|Related Issue|
|--|
|#1516 #1539|

```
Module: File Integrity Monitoring
Target: Manager and Agent   
OS: Linux
```

|  Type | Description  |
|--|--|
|Test Path | test_fim/test_files/test_skip/test_skip.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed | [get_configuration3-/nfs-mount-point-tags_to_apply0]
| Summary | `test_skip.py` is not restarting the nfs server correctly
| Error message |  AssertionError: No events should be detected.

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: In CentOS 8, the script that configures the nfs server must use `systemctl restart nfs-server`.
- [x] Full Green/Yellow in `test_fim/test_files/test_skip/test_skip.py`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/issues/1654
