### ISSUE TITLE
Fix `test_registry/test_registry_restrict/test_registry_restrict.py`

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1657]
|Related Issue|
|--|
|#1516 #1539|

```
Module: File Integrity Monitoring
Target: Agent   
OS: Windows
```

|  Type | Description  |
|--|--|
|Test Path | test_registry/test_registry_restrict/test_registry_restrict.py
| Consistent | No
| Test Execution | 3/3 executions failed
| Cases Failed | [get_configuration0-HKEY_LOCAL_MACHINE-SOFTWARE\Classes\testkey-256-value_list0] 
| Summary | `test_registry_restrict.py` expects 4 added events (3 values and 1 key), but if the test is fast enough (actions taken within the same second) the modification time of the key is unchanged and no event is generated.
| Error message |  TimeoutError: Did not receive expected "Sending FIM event: ..." event

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: Do not expect registry key events when testing values.
- [x] Full Green/Yellow in `test_registry/test_registry_restrict/test_registry_restrict.py`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by Rebits** [comment]
Fixed with https://github.com/wazuh/wazuh-qa/issues/1660

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1670
