### ISSUE TITLE
Fix `test_registry/test_registry_basic_usage/test_long_registry_path.py`

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1658]
|Related Issue|
|--|
|#1516 #1539 #1648|

```
Module: File Integrity Monitoring
Target: Agent   
OS: Windows
```

|  Type | Description  |
|--|--|
|Test Path | test_registry/test_registry_basic_usage/test_long_registry_path.py
| Consistent | Yes
| Test Execution | 3/3 executions failed
| Cases Failed | [get_configuration0]
| Summary | The key and value being used by the test can be seen in the synchronization mechanism, it seems they are both created before the test starts and no changes are made to them.
| Error message |  TimeoutError: TimeoutError was raised because a single 'added' event was expected for ['HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\aaaaaaaaaaaaaaaaaa...'] but was not detected.

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: Delete the registry when the test is finished, even if it fails.
- [x] Full Green/Yellow in `test_registry/test_registry_basic_usage/test_long_registry_path.py`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1669
