### ISSUE TITLE
Fix registry alerts timing out on events that are not triggered

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1660]
|Related Issue|
|--|
|#1516 #1539|

```
Module: File Integrity Monitoring
Target: Agent   
OS: Windows
```

|  Type | Description  |
|--|--|
|Test Path | At random
| Consistent | No
| Summary | Some registry tests are failing due to a combination of how Windows handles modification time and our tests.
| Error message |  TimeoutError: Did not receive expected "Sending FIM event: ..." event

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: Modify registry tests to wait for an event on the specific element being modified and not their parent key.
- [x] Full Green/Yellow in `test_registry/`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1670
