### ISSUE TITLE
Integration Tests: Reliable Full Yellow Jenkins for 4.2.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1677]
| Wazuh QA: Commit| Wazuh QA: Branch | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| https://github.com/wazuh/wazuh-qa/commit/43a6d78fe572c145e1f5a7328960e7236822f0ab | 1677-4.2.0-full-yellow-jenkins |v4.2.0-rc8 | https://github.com/wazuh/wazuh/commit/a594dcdee78aa115050d0455adb6eacec558445d |

It is necessary to get a reliable full yellow on the integration tests of the `wazuh-qa` repository. We will need to do research to check the status of the integration tests. If any problem is found during the research, we will need to fix it in order to achieve the reliable full green.

**Note**:  The branch `1677-4.2.0-full-yellow-jenkins` has all changes apply on this `1516-4.2.0-full-green` branch until the change https://github.com/wazuh/wazuh-qa/commit/43a6d78fe572c145e1f5a7328960e7236822f0ab. Also, there have new changes fixing some warnings.

### Disabled by Core Issue
- Agentd: 
       - test_agentd_state_config (Only on window by Core issue)
       - test_agent_agentd_enrollment (Only on window by Core issue)
       
 - WPK:
        - test_wpk_agent (Only on Linux Agent by Core issue)
---

#### Research
   - #1493 
  
#### Integration tests fixing
   - #1678
   - #1706  > Blocked by #1539
   - https://github.com/wazuh/wazuh-qa/issues/1697
   - #1682
   - https://github.com/wazuh/wazuh-qa/issues/1688
   - #1684
   - https://github.com/wazuh/wazuh-qa/issues/1747
   - https://github.com/wazuh/wazuh-qa/issues/1748    
   - https://github.com/wazuh/wazuh-qa/issues/1746
   - #1705 
   
#### Product issues reported

   - https://github.com/wazuh/wazuh/issues/9309(Affecting Vulnerability Detector tests)
   - https://github.com/wazuh/wazuh/issues/9298 (Affecting Agentd tests)
   - https://github.com/wazuh/wazuh/issues/8746 (Affecting Agentd tests)
   - https://github.com/wazuh/wazuh/issues/9763 (Affecting Agentd tests)
   
#### QA framework issues reported

- https://github.com/wazuh/wazuh-qa/issues/1602
- https://github.com/wazuh/wazuh-qa/issues/1698

#### QA framework enhancement propositions

- https://github.com/wazuh/wazuh-qa/issues/1690
  
   
### Metrics
---
### Conclusions
---

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1841
