### ISSUE TITLE
Full Yellow Jenkins - Fix Agentd tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1678]
## Description

This issue is part of the [full-yellow epic issue](https://github.com/wazuh/wazuh-qa/issues/1677). After the research #1493, we could see that `agentd` tests aren't working properly. In order to sanitize current tests is necessary to fix `agentd` tests. 

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi

#### Agent
```
agent.debug=2
execd.debug=2
monitord.rotate_log=0
```

### Test Results - Research

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/868/)   |  🔴
|**Test Execution 2**|   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/909/)   |  🔴
|**Test Execution 3**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/942/)  |  🔴

        
## Development

Since we have solved some problems in #1521, we will start testing in a temporal branch `1677-4.2.0-full-yellow-jenkins` to check if those fixed solved problems in Jenkins too.

### Test Results -  After local fixes
|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/973/)   |  🔴
|**Test Execution 2**|   [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/8957/)   |  🔴  
|**Test Execution 3**|    [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/8960/)  |  🔴  

These tests are failing due to known problems as https://github.com/wazuh/wazuh/issues/8746 and https://github.com/wazuh/wazuh/issues/9298

- [ ] Full yellow in `agentd` tests for every supported OS

**Comment by juliamagan** [comment]
Results in branch `1516-4.2.0-full-green`

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build]()   |     
|**Test Execution 2**|   [Build]()   |      
|**Test Execution 3**|    [Build]() |

**Comment by MizugorouZ** [comment]
Test results in branch `1677-4.2.0-full-yellow-jenkins`

|   CentOS 8 Agent | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9873/) | :green_circle: |
|**Test Execution 2**| [Build]() | - |
|**Test Execution 3**| [Build]() | - |

|   Windows Agent | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9874/) | :red_circle: |
|**Test Execution 2**| [Build]() | - |
|**Test Execution 3**| [Build]() | - |

**Comment by damarisg** [comment]
I re-launch all test of Windows and all execution works successfully.

| **Jenkins**  |  **Status** |  **By** | **Date**|
|:--:|:--:|:--:|:--:|:--:|
|[Windows Agent - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9931/) | :green_circle:  | Seyla | 25-08-21
|[Windows Agent - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9932/) | :green_circle: |Seyla | 25-08-21
| [Windows Agent - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9933/) | :green_circle: |Seyla | 25-08-21
