### ISSUE TITLE
Full Yellow Jenkins - Fix Rootcheck tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1682]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected errors in `rootcheck` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix rootcheck tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Results - Research

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/881/)   |  🔴
|**Test Execution 2**|   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/925/)  |  🔴
|**Test Execution 3**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/954/)  |  🔴 

### Development

Since we have solved some problems in #1520, we will start testing in a temporal branch `1677-4.2.0-full-yellow-jenkins` to check if those fixed solved problems in Jenkins too.

### Test Results -  After local fixes
|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/974/)   |  🟢 
|**Test Execution 2**|   [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9009/)   |   🟢  
|**Test Execution 3**|    [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9010/)  | 🟢 

- [x] Full green in `rootcheck` tests for every supported OS

**Comment by juliamagan** [comment]
Results in branch `1516-4.2.0-full-green`

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9552/)   |  🔵  
|**Test Execution 2**|   [Build]()   |     
|**Test Execution 3**|    [Build]() |

**Comment by Rebits** [comment]
Results in branch `1516-4.2.0-full-green`

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1052/console)   |  🟢   
|**Test Execution 2**|   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1051/console)   |   🟢 
|**Test Execution 3**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1050/console) |  🟢
