### ISSUE TITLE
Full Yellow Jenkins - Fix WazuhDB tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1684]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected that  `wazuh_db` tests do not properly autoconfigure the testing environment. These tests do not start automatically `wazuh_db` daemon. In an environment where the Wazuh manager has not started for the first time, these tests will fail in some cases.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Results - Research

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/883/)   |  🟢 
|**Test Execution 2**|   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/927/)  |  🟢 
|**Test Execution 3**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/956/)  |  🟢  

### Development

Since we have solved some problems in #1520, we will start testing in a temporal branch `1677-4.2.0-full-yellow-jenkins` to check if those fixed solved problems in Jenkins too.

### Test Results -  After local fixes
|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/975/)   |  🟢 
|**Test Execution 2**|   [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/8987/)   |   🟢  
|**Test Execution 3**|    [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/9007/)  |  🟢  

- [x] Full green in `wazuh_db` tests for every supported OS

**Comment by juliamagan** [comment]
Results in branch `1516-4.2.0-full-green`

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build]()   |     
|**Test Execution 2**|   [Build]()   |      
|**Test Execution 3**|    [Build]() |

**Comment by Rebits** [comment]
Results in branch `1516-4.2.0-full-green`

|    | **Jenkins**  |  **Status** 
|:--:|:--:|:--:|
|**Test Execution 1**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1060/console   | 🟢     
|**Test Execution 2**|   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1061/console   |  🟢  
|**Test Execution 3**|    [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1062/console) |  🟢  

Local fixes do not affect to a clean environment and it seems that wazuhdb tests still working correctly.
