### ISSUE TITLE
 Full Yellow Jenkins - Fix Vulnerability Detector tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1688]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected errors in `Vulnerability Detector` tests for Wazuh manager. 

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Results - Research

| **Jenkins**  |  **Status** 
|:--:|:--:|
|[Test Execution 1](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/882/)   |  🔴
|[Test Execution 2](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/926/)  |  🔴
|[Test Execution 3](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/955/)  |  🔴 

### Development

Since we have solved some problems in #1531, we will start testing in a temporal branch `1531-full-yellow-vuln-det` to check if those fixed solved problems in Jenkins too.

- [ ] Full green in Vulnerability Detector tests
- [ ] Merge with `1516-4.2.0-full-green`

**Comment by damarisg** [comment]
# Execution by TIERs - JENKINS

### 1. Results Full Vulnerability (tier=0)

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/8990/)| 04-08-21| Seyla| 🟡 
|[Results1](https://ci.wazuh.info/view/Tests/job/Test_integration/8992/)| 04-08-21| Seyla| 🟡 
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/8991/)| 04-08-21| Seyla| 🟡


### 2. Results Full Vulnerability (tier=1) 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9011/)| 05-08-21| Seyla| 🟡 
|[Results1](https://ci.wazuh.info/view/Tests/job/Test_integration/8994/)| 05-08-21| Seyla| 🟡 
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/8995/)| 05-08-21| Seyla| 🟡


### 3. Results Full Vulnerability (tier=2) 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/8998/)| 05-08-21| Seyla| 🟡
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/8997/)| 05-08-21| Seyla| 🟡
|[Results3](https://ci.wazuh.info/view/Tests/job/Test_integration/8996/)| 05-08-21| Seyla| 🟡

## Full Execution - JENKINS

### Results Full Vulnerability 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9012/console)| 05-08-21| Seyla| 🟡 (It fails but they are due to the issues that have already been reported or blocked, otherwise the rest works. )
|[Results1](https://ci.wazuh.info/view/Tests/job/Test_integration/9013/console)| 05-08-21| Seyla| 🟡(It fails but they are due to the issues that have already been reported or blocked, otherwise the rest works. )
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/9014/console)| 05-08-21| Seyla| 🟡 (It fails but they are due to the issues that have already been reported or blocked, otherwise the rest works. )

**Comment by damarisg** [comment]
Full Execution- 06-08-21 (WIP) 


| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9046/)| 06-08-21| Seyla| 
|[Results1](https://ci.wazuh.info/view/Tests/job/Test_integration/9048/)| 06-08-21| Seyla| 
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/9049/)| 06-08-21| Seyla|

**Comment by damarisg** [comment]
**Full Execution**

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[Results](https://ci.wazuh.info/view/Tests/job/Test_integration/9281/)| 12-08-21| Seyla|  TO DO
|[Results1](https://ci.wazuh.info/view/Tests/job/Test_integration/9279/)| 12-08-21| Seyla| TO DO
|[Results2](https://ci.wazuh.info/view/Tests/job/Test_integration/9280/)| 12-08-21| Seyla| TO DO

**Comment by mdengra** [comment]
### 2021-08-19

## Full running

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`

| Test Executions | Date  | By  | Status
|--|--|--|--|
|[Results 1](https://devel.ci.wazuh.info/job/Test_integration/982)| 2021-08-19 | Miguel | :green_circle:
|[Results 2](https://devel.ci.wazuh.info/job/Test_integration/983)| 2021-08-19 | Miguel | :green_circle:
|[Results 3](https://devel.ci.wazuh.info/job/Test_integration/984)| 2021-08-19 | Miguel | :green_circle:
