### ISSUE TITLE
QACTL fixes 

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#1695]
After testing the development of the QACTL we found the following issues:

Right now, we have a first working tool in the following branch: https://github.com/wazuh/wazuh-qa/tree/qa-ctl
We have found the following issues that need to be fixed in this first iteration:

1. [x] Docker assigns IP dynamically.
2. [x] When a VM is destroyed, the SSH fingerprint is not removed from `known_hosts`, causing the following failure:
 ```
TASK [Create None/wazuh path] **************************************************
fatal: [10.2.0.3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: 
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:O7NzwSNf0OvmtyQajn74u7ktz7177CvkJ90LfuAq68k.
Please contact your system administrator.
Add correct host key in /home/antoniomanuelfr/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/antoniomanuelfr/.ssh/known_hosts:10
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
UpdateHostkeys is disabled because the host key is not trusted.
vagrant@10.2.0.3: Permission denied (publickey,password).", "unreachable": true}
 ```

3. [x] Finish testing the test module.
4. [x] If a box deployed with qa-ctl has the same name that an existing one, an exception is raised aborting the execution.
This one is a bit problematic, as the `python-vagrant` module is doing all the operations calling using the `subprocess` command, and when the command fails, the only information that is returned is that it returned with a non-zero exit status, but not the reason why the command failed. 
5. [x] Also, the containers deployed with docker are also failing when an existing container has the same name as the one deployed with qa-ctl
6. [x] To download installation sources files, we are doing a git clone. This is not efficient enough and also generates problems when the repository is already cloned before. Instead, we will download the files directly.
7. [x] Remove vagrantfile folder when destroying the box
8. [x] Some minor problems regarding ossec.log and ossec.conf not showing as plain text in browser. It shows as URL data with the following scheme: data:<mediatype>:<base64 encoded data>. Maybe it needs to be changed to fetch the assets folder as well instead of using --self-contained-html flag.
9. [x] The remove option in the docker section is not taking the default value

Implement WazuhS3Package class to allow package downloads from Wazuh packages repository, this will be added in this issue: https://github.com/wazuh/wazuh-qa/issues/1701
It would be a good idea to show all the pytest output when running test, to see the progress, and if any of them have failed or not. (Edit: This can't be completed, explication below in the comments)

The purpose of this issue is to collect all the detected problems and fix them, so the above list may increase while we detect new problems

**Comment by antoniomanuelfr** [comment]
The second issue has been fixed in https://github.com/wazuh/wazuh-qa/pull/1696/commits/ed7495d2818fef801a89203a3df08a351c20c6c2. 

After testing the tool with this change, ansible can connect properly when a VM is created with a previously used IP.

**Comment by antoniomanuelfr** [comment]
This commit https://github.com/wazuh/wazuh-qa/commit/39bf2744ea8e2f646e2ed54a113eb8d297a1a3bb adds the necessary logic to the VagrantWrapper class to remove the directory that was created when building the vagrantfile if the destroy method is called.

**Comment by antoniomanuelfr** [comment]
After investigating how to solve the first issue, we have two options:
- Create a new network and assign a static IP to the container.
- Get the assigned IP in runtime.

Both options have their drawbacks:
- The first option is the easier, as the network can be easily created, but this will imply that the user needs to be careful to not create a big quantity of networks. Also a logic to remove the networks after their use is mandatory.
- The second one doesn't need to create any network, but needs to modify the information that was read previously, adapting the information retrieved by QAInfraestructure.

For now, we are going to start testing the first one.

**Comment by jotacarma90** [comment]
Use of curl instead of git clone to download the installation files:
7e396e1d5ab06104b4112223232abb1c5cb470b1

**Comment by antoniomanuelfr** [comment]
The first problem is fixed in https://github.com/wazuh/wazuh-qa/commit/1849d70e358d2b9d26e84b0ac1dbe571fb53fe29

**Comment by antoniomanuelfr** [comment]
After talking with the team, we have decided that when a container/VM deployed with qactl has the same name that one already created, we are going to raise an error and abort the execution, as the container/VM may have another purpose

**Comment by JoseAntonioMHerrera** [comment]
The problem regarding the ossec.log and ossec.conf files not showing in browser for the failed tests is fixed in [c7f0286](https://github.com/wazuh/wazuh-qa/commit/c7f0286811eb7fd521c60c27be85884bae480add) . I have tried some alternatives to see which could be the best way to fetch the whole directory. The one used in the fix depends on ansible.posix.synchronize . Also another two tasks have been added to check if the assets folder exists in the local machine and create it if the folder doesn't exists.

**Comment by jotacarma90** [comment]
Let's create a new issue for the enhancement to be able to use S3 packages in qactl.

**Comment by jotacarma90** [comment]
It seems that it is not possible to display the output of pytest while it is running since ansible does not display anything while it is performing a task.
