### ISSUE TITLE
Full Yellow Jenkins - Fix FIM tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1706]
## Description

This issue is part of the full-yellow epic issue (https://github.com/wazuh/wazuh-qa/issues/1677). After the research #1493, we could see that `fim` tests aren't working properly. In order to sanitize current tests is necessary to fix `fim` tests. In Jenkins, these tests are launched just with `realtime` and `whodata`.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi
Agent | macOS | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.pkg
Agent | solaris | i386 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent_v4.2.0-1.1493-sol11-i386.p5p

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

### Test Results - Research

| **Linux manager**   | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/873/)  |  🟢 
|**Test Execution 2**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/914/)  |  🟢 
|**Test Execution 3**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/947/)  |  🟢 

| **Linux Agent**  | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/874/) |   🟢 
|**Test Execution 2**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/916/)  |  🟢 
|**Test Execution 3**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/948/)  |  🟢 

| **Windows Agent**  |  **Jenkins**  |   **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/874/)  |   🔴 
|**Test Execution 2**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/916/)  |  🔴 
|**Test Execution 3**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/948/)   |  🟢 

| **Solaris Agent**  |  **Jenkins**  |   **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/875/)  |   🟢 
|**Test Execution 2**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/917/)  |  🟢 
|**Test Execution 3**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/965/)   |  🟢 

| **macOS Agent**  |  **Jenkins**  |   **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/875/)  |   🟢 
|**Test Execution 2**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/917/)  |  🟢 
|**Test Execution 3**| [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/965/)   |  🟢 

        
## Development

Since we have solved some problems in #1539, we will start testing in a temporal branch `1677-4.2.0-full-yellow-jenkins` to check if those fixed solved problems in Jenkins too.

- [ ] Full yellow in `fim` tests for every supported OS
- [ ] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `1677-4.2.0-full-yellow-jenkins`

**Comment by snaow** [comment]
Still have problems with Windows agent, detect as well in local yellows. To be reviewed later.

**Comment by damarisg** [comment]
This issue continue on [FIM - Windows Agent in 4.2.1](https://github.com/wazuh/wazuh-qa/issues/1873)
