### ISSUE TITLE
Research and update repository dependency management.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1709]
We need to change the way we manage python dependencies in the `wazuh-qa` repository.

So far, we have a file called [requirements.txt](https://github.com/wazuh/wazuh-qa/blob/master/requirements.txt), which contains dependencies and versions. The way to install all these dependencies is through `pip install -r requirements.txt`, but depending on the operating system where they are installed may give errors or not.

In this issue, I propose to find a better way to install the dependencies, since not in all scenarios it is necessary to install each of the dependencies contained in that file, in addition to the possible conflicts that may exist between different versions of dependencies.

Specifically, you are asked to:

- Investigate some tool or technology to be able to manage python dependencies from the repository, that allows us to make groups for operating systems, scenarios....
- Resolve possible conflicts between versions of the dependencies. It is conflicting that some dependencies have a version `==` and others `>=` . It is requested to find a way to solve this.
- Test that this dependency management system is compatible with all systems: Linux, Windows, macOS and Solaris.

Best regards.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
