### ISSUE TITLE
Remote upgrading for MacOS agents

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#1724]
### Description

Support for remote upgrading of MacOS agents needs to be considered in WPK integration tests.

Some things to consider:

- Remove MacOS from case of failure in WPK manager tests.
- Adapt WPK agent tests to be able to run on MacOS agents.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1853
