### ISSUE TITLE
Full Green Local - Fix Vulnerability Detector tests in 4.2

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1733]
## Description

This issue is created to solve the problems that prevent the `full green` in the **Vulnerability Detector** tests and that appear in the issue https://github.com/wazuh/wazuh-qa/issues/1531.

### Test Execution - Results

| Manager  |  **Local** | **Jenkins**  |  **Status**|
|:--:|:--: |:--:|:--:|
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7008789/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9468/ |  :yellow_circle:  | 
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7009182/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9466/ |  :yellow_circle:  | 
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7008790/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9467/ |  :yellow_circle:  | 

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Development 

In order to finish this issue the following tasks should be fulfilled:

- [x] Fix `Vulnerability Detector` integration tests.
  - [x] https://github.com/wazuh/wazuh-qa/issues/1731
- [x] Full Green in `Vulnerability Detector` tests for Manager.

**Comment by mdengra** [comment]
### 2021-08-20

I attach the test results of the PR https://github.com/wazuh/wazuh-qa/pull/1735, which solves all the warnings related to the `vulnerability detector` tests.

## Full running

Used Wazuh-QA branch: `1731-deprecation-warnings-vuln-det`
Test results with the default settings in the `ossec.conf`: 

### Test results:
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_vulnerability_detector_local_r1.log](https://github.com/wazuh/wazuh-qa/files/7019505/test_vulnerability_detector_local_r1.log)| 2021-08-19 | Miguel | :green_circle: 
|[test_vulnerability_detector_local_r2.log](https://github.com/wazuh/wazuh-qa/files/7019508/test_vulnerability_detector_local_r2.log)| 2021-08-19 | Miguel | :green_circle: 
|[test_vulnerability_detector_local_r3.log](https://github.com/wazuh/wazuh-qa/files/7019510/test_vulnerability_detector_local_r3.log)| 2021-08-19 | Miguel | :green_circle:

**Comment by danisan90** [comment]
### Test results:
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[ResultsVulnerability1.log](https://github.com/wazuh/wazuh-qa/files/7085749/ResultsVulnerability1.log)| 31-08-21 | Daniela | :green_circle: 
|[ResultsVulnerability2.log](https://github.com/wazuh/wazuh-qa/files/7085752/ResultsVulnerability2.log)| 31-08-21| Daniela | :green_circle: 
|[ResultsVulnerability3.log](https://github.com/wazuh/wazuh-qa/files/7085753/ResultsVulnerability3.log)|31-08-21| Daniela | :green_circle:
