### ISSUE TITLE
Full Green Jenkins - Fix Remoted tests in 4.2

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1737]
This issue is created to solve the problems that prevent the `full green` in the **remoted** tests 

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Development

Since we have solved some problems in #1530, and the `1530-full-yellow-remoted` branch has already been merged with the `1516-4.2.0-full-green` branch, the latter will be used to check if those fixed solved problems in Jenkins too.

- [ ] Full green in Remoted tests

**Comment by mdengra** [comment]
### 2021-08-19

## Full running

Used Wazuh-QA branch: `1516-4.2.0-full-green`

| Test Executions | Date  | By  | Status
|--|--|--|--|
|[Results 1 (In progress)]()| 2021-08-19 | Miguel | 
|[Results 2 (In progress)]()| 2021-08-19 | Miguel |
|[Results 3 (In progress)]()| 2021-08-19 | Miguel |

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Status |
|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10345/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10346/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10347/) | :green_circle: |
