### ISSUE TITLE
 Full Green Jenkins - Fix Vulnerability Detector tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1741]
## Description

This issue is created to solve the warnings that prevent the `full green` in the **Vulnerability Detector** tests and that appear in the issue https://github.com/wazuh/wazuh-qa/issues/1531.

### Test Execution - Results

| Manager  |  **Local** | **Jenkins**  |  **Status**|
|:--:|:--: |:--:|:--:|
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7008789/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9468/ |  :yellow_circle:  | 
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7009182/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9466/ |  :yellow_circle:  | 
|**Test Execution 1**| [Results](https://github.com/wazuh/wazuh-qa/files/7008790/FullYellowVuln.log)|  https://ci.wazuh.info/view/Tests/job/Test_integration/9467/ |  :yellow_circle:  | 

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Development 

In order to finish this issue the following tasks should be fulfilled:
- [ ] Full Green in `Vulnerability Detector` tests for Manager.

**Comment by mdengra** [comment]
### 2021-08-20

## Full running

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`

| Test Executions | Date  | By  | Status
|--|--|--|--|
|[Results 1](https://devel.ci.wazuh.info/job/Test_integration/982)| 2021-08-19 | Miguel | :green_circle:
|[Results 2](https://devel.ci.wazuh.info/job/Test_integration/983)| 2021-08-19 | Miguel | :green_circle:
|[Results 3](https://devel.ci.wazuh.info/job/Test_integration/984)| 2021-08-19 | Miguel | :green_circle:

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Status |
|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10339/) | In execution... |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10340/) | In execution... |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10341/) | In execution... |
