### ISSUE TITLE
 Full Yellow Jenkins - Fix GCloud tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1746]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected errors in `GCloud` tests for Wazuh manager. In order to sanitize current tests is necessary to fix `GCloud` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### local_internal_options.conf

```
analysisd.debug=2
wazuh_modules.debug=2
monitord.rotate_log=0  

```

### Test Results - Research

| **Linux manager**   | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/876/)   |  🔴
|**Test Execution 2**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/918/)  |  🔴
|**Test Execution 3**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/950/)  |  🔴

## Development

Since we have solved some problems in #1532, we will start testing in a temporal branch `1677-4.2.0-full-yellow-jenkins` to check if those fixed solved problems in Jenkins too. Also, this issue was blocked for Jenkins by https://github.com/wazuh/wazuh-jenkins/issues/2649.

- [ ] Full yellow in `GCloud` tests for every supported OS

**Comment by damarisg** [comment]
I start to research fails. First, I will launch on Jenkins 3 times the execution.  

Test results in branch `1677-4.2.0-full-yellow-jenkins`

| **Jenkins**  |  **Status** 
|:--:|:--: |
| [Linux manager - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/10218/) | WIP |
| [Linux manager - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/10215/) | 🟢|
| [Linux manager - Results](https://ci.wazuh.info/view/Tests/job/Test_integration/10162/) | 🟢 |

Also, I will setup a VM to start with execution local.
