### ISSUE TITLE
Full Yellow Jenkins - Fix API tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1748]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected errors in `API` tests for Wazuh manager. In order to sanitize current tests is necessary to fix `API` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### local_internal_options.conf

```
monitord.rotate_log=0 
```

### Test Results - Research

| **Linux manager**   | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/878/)   |  🔴
|**Test Execution 2**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/920/)  |  🔴
|**Test Execution 3**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/951/)  |  🔴

## Development

This issue was blocked for Jenkins by https://github.com/wazuh/wazuh-jenkins/issues/2648.

### Test Results -  After local fixes

| **Linux manager**   | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/897/)   |    🔴
|**Test Execution 2**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/911/)  |   🔴 
|**Test Execution 3**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/943/)  |  🔴  

- [x] Full yellow in `API` tests for every supported OS

**Comment by MizugorouZ** [comment]
### Test Results

Latest test resutls in Jenkins

| **Linux manager**   | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|
|**Test Execution 1**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1075/)  | :green_circle: |
|**Test Execution 2**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1076/)  | :green_circle: |
|**Test Execution 3**|  [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/1077/)  | :green_circle: |
