### ISSUE TITLE
Full Yellow local - Remove test_response_timeout from integration tests 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1751]
## Description

| Related issue |
|--|
| #1516  #1539 |

|Development branch|
|:--:|
|1539-full-yellow-remove-response-timeout-test|

Is necessary to remove this test from the integration tests suite. This change is motivated due to:
- Test logic uses a hardcoded agent IP.
- This test belongs to the system tests suite.
- A refactor is required.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1752
