### ISSUE TITLE
Coverage Analysis - Phase 1

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1769]
# Description
Wazuh-QA provides a great set of tests for many Wazuh modules. It is necessary to research and perform an analysis of coverage of this suite. After this process, we will know precisely the status of the quality assurance process in Wazuh, and it will help to aim for future developments.

## Main objectives
Analyze test coverage of every Wazuh component.
Summarize main errors in test suites that may affect the quality assurance process.

## General notes

- This issue is related to [Coverage Analysis for 4.3](https://github.com/wazuh/wazuh-qa/issues/1851)

- This issue will analyze the test suite coverage in `4.3/master` branch. 

# Coverage Analysis

<details>
   <summary> Total </summary>
   <table style="height: 306px;">
<thead>
<tr style="height: 18px;">
<th style="height: 18px; width: 154px;">Capabilities</th>
<th style="height: 18px; width: 107px;">Covered</th>
<th style="height: 18px; width: 165px;"> Key Capabality. </th>
</tr>
</thead>
<tbody>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Active Response</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Integration with Yara and VirusTotal</ul></li></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents connection service</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Centralized configuration management</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agent key polling</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents Labels</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents Anti-flooding system</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agentless monitoring</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents Registration service (Authd)</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Analysis engine (Analysisd) </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Certificate Deployment </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;">wazuh-cert-tool</td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Amazon AWS </td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"> <ul><li>AWS CloudTrail</li><li>Amazon VPC</li><li>AWS Config</li><li>Amazon ALB</li><li>Amazon CLB</li><li>AWS KMS</li><li>Amazon Macie</li><li>AWS Trusted Advisor</li><li>Amazon GuardDuty</li><li>Amazon WAF</li><li>Amazon NLB</li><li>Amazon Inspector</li><li>Amazon NLB</li><li>AWS CloudWatch Logs</li><li>Cisco Umbrella</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Azure</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Azure Active Directory</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Google GCP</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 165px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cluster</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Master node</li><li>Worker node</li><li>Configuration</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Command Execution</td>
<td style="height: 18px; width: 165px;">❌</td>
<td style="height: 18px; width: 107px;"><ul><li>Bash </li><li>Powershell</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Command Monitoring</td>
<td style="height: 18px; width: 165px;">✔️</td>
<td style="height: 18px; width: 107px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Compliance</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 107px;"><ul><li>Using Wazuh for PCI DSS</li><li>Using Wazuh for GDPR</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configuration assesment (SCA)</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Hardening checks</li><li>CIS baselines</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configuration emails alerts</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configure database output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>MySQL</li><li>PostgreSQL</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Containers Security</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Docker </li><li>Kubernetes</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Creation of Packages</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Deployment</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>With Puppet</li><li>With Ansible</li><li>Virtual Machine</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Elasticsearch tuning</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>change user's password</li><li>memory locking</li><li>shards and replicas</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">FIM</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Critical Files</li><li>Audit Files</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">csyslogd</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Forwarding alerts through Syslog</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">fluentd</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Generating automatic reports</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Installation</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li> Unnatended Method </li><li>Deployments (Puppet, Ansible, OVA) </li><li>Types (Laptop - Desktop - Servers - Cloud instances - VMs)</li><li>All platforms and version supported</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Integration Daemon </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Integration with external APIs  </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>VirusTotal</li><li>PagerDuty</li><li>Slack</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">LogCollector</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Log Messages</li><li>Windows Events</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Logtest</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Test rules and decoders</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Mitre ATT&CK </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Osquery</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Regulatory Compliance</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Remoted</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">RESTful API </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection + CISC-SAT</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection + OpenSCAP</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection - Rootcheck</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rules and Decoders</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Custom Rules and Decoders</li><li>CDB Lists</li> <li>Enhancing with MITRE</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Setting Syslog output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>send alerts to syslog</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Setting Database output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Syscheck </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>whodata</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">System Inventory (syscollector) </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Tools</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>agent-auth</li><li>agent_control</li><li>manage_agents</li><li>wazuh-control</li><li>wazuh-logtest</li><li>clear-stats</li><li>wazuh-regex</li><li>verify-agent-conf</li><li>agent_groups</li><li>agent_upgrade</li><li>cluster_control</li><li>fim_migrate</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Upgrade</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Elasticsearch (Open Distro, Licence Basic) </li><li> Manager </li><li>Kibana </li><li>Filebeat</li><li>Wazuh agent</li><li>All ways</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Uninstall</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Elasticsearch (Open Distro, Licence Basic) </li><li> Manager </li><li>Kibana </li><li>Filebeat</li><li>Wazuh agent</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Using Wazuh to monitor Office365</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Using Wazuh to monitor Github</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Vulnerability Detector</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">WazuhDB</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Wazuh Cloud</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
</tbody>
</table>
</details>

--------------------------------------------------------------------------------------------------------------------------------

<details>
   <summary> Total </summary>
   <table style="height: 306px;">
<thead>
<tr style="height: 18px;">
<th style="height: 18px; width: 154px;">Capabilities</th>
<th style="height: 18px; width: 107px;">Covered</th>
<th style="height: 18px; width: 165px;"> Key Capabality. </th>
</tr>
</thead>
<tbody>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Active Response</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Integration with Yara and VirusTotal</ul></li></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agent key polling</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents Registration service (Authd)</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Analysis engine (Analysisd) </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Google GCP</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 165px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cluster</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Master node</li><li>Worker node</li><li>Configuration</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Command Monitoring</td>
<td style="height: 18px; width: 165px;">✔️</td>
<td style="height: 18px; width: 107px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">FIM</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Critical Files</li><li>Audit Files</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">LogCollector</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Log Messages</li><li>Windows Events</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Logtest</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Test rules and decoders</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Mitre ATT&CK </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Remoted</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">RESTful API </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection - Rootcheck</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Syscheck </td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>whodata</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Upgrade</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"><ul><li>Elasticsearch (Open Distro, Licence Basic) </li><li> Manager </li><li>Kibana </li><li>Filebeat</li><li>Wazuh agent</li><li>All ways</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Using Wazuh to monitor Office365</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Using Wazuh to monitor Github</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Vulnerability Detector</td>
<td style="height: 18px; width: 107px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">WazuhDB</td>
<td style="height: 18px; width: 52px;">✔️</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
</tbody>
</table>
</details>

--------------------------------------------------------------------------------------------------------------------------------

<details>
   <summary> Total </summary>
   <table style="height: 306px;">
<thead>
<tr style="height: 18px;">
<th style="height: 18px; width: 154px;">Capabilities</th>
<th style="height: 18px; width: 107px;">Covered</th>
<th style="height: 18px; width: 165px;"> Key Capabality. </th>
</tr>
</thead>
<tbody>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents connection service</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Centralized configuration management</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agents Anti-flooding system</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Agentless monitoring</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Certificate Deployment </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;">wazuh-cert-tool</td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Amazon AWS </td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"> <ul><li>AWS CloudTrail</li><li>Amazon VPC</li><li>AWS Config</li><li>Amazon ALB</li><li>Amazon CLB</li><li>AWS KMS</li><li>Amazon Macie</li><li>AWS Trusted Advisor</li><li>Amazon GuardDuty</li><li>Amazon WAF</li><li>Amazon NLB</li><li>Amazon Inspector</li><li>Amazon NLB</li><li>AWS CloudWatch Logs</li><li>Cisco Umbrella</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Cloud Security - Azure</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Azure Active Directory</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Command Execution</td>
<td style="height: 18px; width: 165px;">❌</td>
<td style="height: 18px; width: 107px;"><ul><li>Bash </li><li>Powershell</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Compliance</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 107px;"><ul><li>Using Wazuh for PCI DSS</li><li>Using Wazuh for GDPR</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configuration assesment (SCA)</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Hardening checks</li><li>CIS baselines</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configuration emails alerts</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Configure database output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>MySQL</li><li>PostgreSQL</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Containers Security</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Docker </li><li>Kubernetes</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Creation of Packages</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Deployment</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>With Puppet</li><li>With Ansible</li><li>Virtual Machine</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Elasticsearch tuning</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>change user's password</li><li>memory locking</li><li>shards and replicas</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">csyslogd</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Forwarding alerts through Syslog</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">fluentd</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Generating automatic reports</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Installation</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li> Unnatended Method </li><li>Deployments (Puppet, Ansible, OVA) </li><li>Types (Laptop - Desktop - Servers - Cloud instances - VMs)</li><li>All platforms and version supported</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Integration Daemon </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Integration with external APIs  </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>VirusTotal</li><li>PagerDuty</li><li>Slack</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Osquery</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Regulatory Compliance</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection + CISC-SAT</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rootkits Detection + OpenSCAP</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Rules and Decoders</td>
<td style="height: 18px; width: 107px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Custom Rules and Decoders</li><li>CDB Lists</li> <li>Enhancing with MITRE</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Setting Syslog output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>send alerts to syslog</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Setting Database output</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">System Inventory (syscollector) </td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Tools</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>agent-auth</li><li>agent_control</li><li>manage_agents</li><li>wazuh-control</li><li>wazuh-logtest</li><li>clear-stats</li><li>wazuh-regex</li><li>verify-agent-conf</li><li>agent_groups</li><li>agent_upgrade</li><li>cluster_control</li><li>fim_migrate</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Uninstall</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"><ul><li>Elasticsearch (Open Distro, Licence Basic) </li><li> Manager </li><li>Kibana </li><li>Filebeat</li><li>Wazuh agent</li></ul></td>
</tr>
<tr style="height: 18px;">
<td style="height: 18px; width: 154px;">Wazuh Cloud</td>
<td style="height: 18px; width: 52px;">❌</td>
<td style="height: 18px; width: 52px;"></td>
</tr>
</tbody>
</table>
</details>

**Comment by damarisg** [comment]
### Draft  - 2021/09/02  (Seyla)

|List | Section |Covered| Note | 
|--|--|--|--|
| Installation | | Servers - Cloud instances - VMs  (on all platforms supported)
| Agent Modules | Command Execution| | Bash - Powershell |
| Agent Modules | Configuration assesment | 
| Agent Modules | Containers Security |
| Agent Modules | Cloud Secuurity | 
| Agent Modules | FIM | | Critical Files - Audit Files 
| Agent Modules | Vulnerability Detector | 
| Agent Modules | LogCollector|| Log Messages - Windows Events| 
| Agent Modules | Malware Detection | 
| Agent Modules |System Inventory |
| Agent Modules | Threat Intelligence|
| Agent Modules | Regulatory Compliance | 
| Agent Daemon | Modules Management | |Agent Registartion Service |
| Agent Daemon | Remote Configuration|
| Agent Daemon |  |
|Upgrade||
|Uninstall||

**Comment by Deblintrake09** [comment]
### Draft  2021/09/02  (Seyla)

|List | Section |Covered| Note | 
|--|--|--|--|
| Installation | Manager |  |
| Installation | Agent | |
|Upgrade|Manager|
|Upgrade|Agent|
|Uninstall|Manager|
|Uninstall|Agent|
| AGENT RELATED |
| Agent Modules | Command Execution| |Bash, Powershell|
| Agent Modules | Configuration assesment | | Hardening Checks, CIS Baselines
| Agent Modules | Containers Security | | Runtime monitoring, APIs
| Agent Modules | Cloud Secuurity |  |AWS, Azure
| Agent Modules | FIM | | Critical files, Audit data
| Agent Modules | Vulnerability Detector | | Detect vulnerable Applications
| Agent Modules | LogCollector| | Log messages, windows events, agentless
| Agent Modules | Malware Detection | | Detect Rootkit & anomalies
| Agent Modules |System Inventory | |Applications installed, Running Proccesses, System hardware
| Agent Modules | Active Response | | Block network connections, Stop proccesses
| Agent Daemon | Modules Management | |Agent Registartion Service |
| Agent Daemon | | | Remote Configuration, Data encryption, Modules management, Data flow Control
| SERVER Related |
| Server Daemon | Threat Intelligence|
| Server Daemon | Regulatory Compliance |

**Comment by danisan90** [comment]
### Draft  - 2021/09/02  (Dani)
#### **Wazu Server**
|List | Note | Covered| 
|--|--|--|
| Remote Service| | |
|Alert Level Threshold||
|Integration with external Api||
|Configuring Data Base outpu|||
|Generating Automating Reports||

**Comment by MizugorouZ** [comment]
### Draft - 2021/09/03 (Antonio)

### User Manual

#### Overview
- Wazuh server
   - Receiving logs and analyzing data
   - Trigger alerts, match rules
   - Register agents
   - Send data to Elastic Stack server
- Wazuh agent
   - Rootcheck
   - Log monitoring and analysis
   - Syscheck

#### Wazuh server administration
- Remote service
- Defining an alert level threshold
- Integration with external APIs: Slack/PagerDuty/VirusTotal/Custom
- Syslog output: Alerts sent to syslog
- Database output: Alerts into a DB
- Automatic reports
- Email alerts

#### Certificates deployment
