### ISSUE TITLE
Authd tests for the agent key validation logic

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1772]
### Description

As part of this issue, we should implement a set of integration tests to validate the right behavior of **authd** in the agents' keys validation mechanism. This work includes:

Extend the yaml files with new test cases to cover the K option:
- _test_authd.py_ -> Extend enroll_messages.yaml with **K:**
- _test_authd_local.py_ -> Extend _local_enroll_messages.yaml_ with **key_hash** (in the JSON payload)
- _test_authd_name_ip.py_ -> Extend _name_ip_pass_tests.yaml_ with **K:** and try to integrate with  _test_authd.py_.
- _test_authd_worker.py_ -> Extend _worker_messages.yaml_ with **K:**. This is a two points test, the test cases has what needs to be sent to main-server and what we must response to it.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1771
