### ISSUE TITLE
Agentd tests for the agent key validation logic

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1773]
### Description

As part of this issue, we should implement a set of integration tests to validate the right behavior of **agentd** in the agents' keys validation mechanism. This work includes:

Deprecate the old tests because they are based on simulators and implement the following tests:
**test_agentd_enrollment_params.py.**
- Must: 
      - Consume a yaml file _wazuh_enrollment_test.yaml_
      - Open port 1515 to listen to the agent's requests.
      - Configure the agent with the yaml configuration 
       - Clean keys if necessary.
       - Start the agent and wait for the key request to arrive (It may take a few seconds (configurable) if they are tests with a key)
       - Compare the request received with the expected one from the .yaml.

**test_agent_auth_enrollment.py**
- Must: 
      - Consume a yaml wazuh_enrollment_test.yaml
      - Open port 1515 to listen for Agent-Auth requests
      - Use the Agent-auth-parser with the yaml configuration to build the correct agent-auth command
      - Clean keys if necessary.
      - Run agent-auth and wait for the key request
      - Compare the received request with the expected one from the .yaml.

**Implement the complete battery of tests in wazuh_enrollment_test.yaml**
- Must: 
      - Cover all key and combination request scenarios.
      - Build on contemplated authd scenarios
        - With specific name.
        -  With group.
        - With specific IP
        - With key / without key

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1824
