### ISSUE TITLE
Integration Tests: Reliable Full Green Local for 4.2.0

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1774]
## Description

It is necessary to get a reliable Full Green Local on the integration tests of the `wazuh-qa` repository.
After researching, and fix all fails. We will fix all warnings showed of the integration tests. 
If any problem is found during the research, we will need to fix it in order to achieve the reliable full green.

**Notes**: 

> The branch `1774-4.2-full-green-local` was created from `1516-4.2.0-full-green` as base. After that we applied last changes of  `1677-4.2.0-full-yellow-jenkins` with commit https://github.com/wazuh/wazuh-qa/commit/43a6d78fe572c145e1f5a7328960e7236822f0ab. Also, we merge last changes from `1731-deprecation-warnings-vuln-det` branch with commit  https://github.com/wazuh/wazuh-qa/commit/87b5129a5b4c83396585edc0ca1029dbb3d5a750 that fix some warnings.

## Package Details

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 1774-4.2-full-green-local | https://github.com/wazuh/wazuh-qa/commit/87b5129a5b4c83396585edc0ca1029dbb3d5a750 |v4.2.0-rc8 | https://github.com/wazuh/wazuh/commit/a594dcdee78aa115050d0455adb6eacec558445d |

## Research

- #1493 
- #1516 

## Integration Tests 

- https://github.com/wazuh/wazuh-qa/issues/1733
- https://github.com/wazuh/wazuh-qa/issues/1740
- https://github.com/wazuh/wazuh-qa/issues/1775
- https://github.com/wazuh/wazuh-qa/issues/1776
- https://github.com/wazuh/wazuh-qa/issues/1777
- https://github.com/wazuh/wazuh-qa/issues/1778
- https://github.com/wazuh/wazuh-qa/issues/1779
- https://github.com/wazuh/wazuh-qa/issues/1780
- https://github.com/wazuh/wazuh-qa/issues/1858

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1842/files

**Comment by damarisg** [comment]
API tests merged this issue is closed.
