### ISSUE TITLE
Full Green Local - Fix Agentd tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1776]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1774. It has been detected warnings in `Agentd` tests for Wazuh in Linux/Windows systems. 

It requires fix all warnings showed.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1774-4.2.0-full-green-local |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi

#### Agent
```
agent.debug=2
execd.debug=2
monitord.rotate_log=0
```

## Test Execution - Results

|  ** Results**  |  **Status** 
|:--:|:--:|
|**CentOS 8 Agent**| 🟠 |
|  **Windows Agent** | 🔴 

### Development

In order to finish this issue the following tasks should be fulfilled:

- [x] Full green in Agentd tests in branch `1774-4.2.0-full-green-local`

**Comment by Deblintrake09** [comment]
## Test Execution - Results

|  ** Results**  |  **Status** | **Results**|
|:--:|:--:|:--:|
|**CentOS 8 Agent**| 🟢  |  [ResultsAgentd.zip](https://github.com/wazuh/wazuh-qa/files/7085881/ResultsAgentd.zip)
|**CentOS 8 Agent**| 🟢  | [ResultsAgend3.zip](https://github.com/wazuh/wazuh-qa/files/7085882/ResultsAgend3.zip)
|**CentOS 8 Agent**| 🔵  |
|  **Windows Agent** | ⚫  
|  **Windows Agent** | ⚫  
|  **Windows Agent** | ⚫

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Test result | Date | Executed by | Status |
|:--:|:--:|:--:|:--:|
| [R1](https://github.com/wazuh/wazuh-qa/files/7090347/r1_agentd_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
| [R2](https://github.com/wazuh/wazuh-qa/files/7090348/r2_agentd_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
| [R3](https://github.com/wazuh/wazuh-qa/files/7090349/r3_agentd_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
