### ISSUE TITLE
Full Green Local - Fix WPK tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1777]
## Description

This issue is part of the [Integration Tests: Reliable Full Green Local for 4.2.0](https://github.com/wazuh/wazuh-qa/issues/1774). After fixing [Full Yellow Local - Fix WPK tests in 4.2](https://github.com/wazuh/wazuh-qa/issues/1528), we need to have all results in Green without Warnings and Fails.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1774-4.2.0-full-green | 4.2  |  1.1493 | 

#### Linux Manager
```
wazuh_modules.debug=2
```

#### Linux Agent
```
wazuh_modules.debug=2
```

#### Windows Agent
```
windows.debug=2
```

### pytest args
`--wpk_version=v4.2.0`

## Test Results 

|Execution |Status|
|:--:|:--:|
|Manager|  :green_circle: |
|Agent/Linux|  :green_circle: | 
|Agent/Windows|  :green_circle: |

## Development

In order to finish this issue the following tasks should be fulfilled:

- [x] Full green in WPK tests on branch `1774-4.2.0-full-green-local` .

**Comment by Deblintrake09** [comment]
## Test Results 

|Execution |Status|Run By | Results
|:--:|:--:|:--:|:--:|
|Manager|  :green_circle: | @Deblintrake09 | [wpk-manager1.zip](https://github.com/wazuh/wazuh-qa/files/7078312/wpk-manager1.zip)
|Manager|  :green_circle: | @Deblintrake09 | [wpk-manager2.zip](https://github.com/wazuh/wazuh-qa/files/7078315/wpk-manager2.zip)
|Manager|  :green_circle: | @Deblintrake09 | [wpk-manager3.zip](https://github.com/wazuh/wazuh-qa/files/7078317/wpk-manager3.zip)

|Agent/Linux|  :blue_circle: : | 
|Agent/Windows|  :black_circle: |

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Test result | Date | Executed by | Status |
|:--:|:--:|:--:|:--:|
| [R1](https://github.com/wazuh/wazuh-qa/files/7090578/r1_wpk_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
| [R2](https://github.com/wazuh/wazuh-qa/files/7090579/r2_wpk_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
| [R3](https://github.com/wazuh/wazuh-qa/files/7090580/r3_wpk_windows.zip) | 01/09/2021 | @MizugorouZ | :green_circle: |
