### ISSUE TITLE
Full Green Local - WazuhDB tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1779]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1774. It has been detected warnings in `WazuhDB` tests for Wazuh manager in Linux systems. 

It requires fix all warnings showed.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Execution 
|Execution |Status|
|:--:|:--:|
|manager/linux| 🟡  

## Development

In order to finish this issue the following tasks should be fulfilled:

- [ ] Full green in WazuhDB tests.
- [ ] Merge with `1774-4.2.0-full-green-local`

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Results | Status |
|:--:|:--:|
| [R1](https://github.com/wazuh/wazuh-qa/files/7082326/r1_wazuh_db.zip) | :green_circle: |
| [R2](https://github.com/wazuh/wazuh-qa/files/7082332/r2_wazuh_db.zip) | :green_circle: |
| [R3](https://github.com/wazuh/wazuh-qa/files/7082337/r3_wazuh_db.zip) | :green_circle: |
