### ISSUE TITLE
Full Green Jenkins - Fix Rootcheck tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1785]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected errors in `rootcheck` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix rootcheck tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Results - Research

| **Jenkins**  |  **Status** 
|:--:|:--:|
|**Results Manager **| 🟢 

- [x] Full green in `rootcheck` tests for every supported OS

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Status |
|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10351/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10352/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10353/) | :green_circle: |
