### ISSUE TITLE
Full Green Jenkins - Fix WazuhDB tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1786]
## Description

This issue is part of the https://github.com/wazuh/wazuh-qa/issues/1677. After the research #1493, it has been detected that  `wazuh_db` tests do not properly autoconfigure the testing environment. These tests do not start automatically `wazuh_db` daemon. In an environment where the Wazuh manager has not started for the first time, these tests will fail in some cases.

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Test Results - Research

|  **Jenkins**  |  **Status** 
|:--:|:--:|
|**Test Execution 1**|  🟢 

### Development

We will start testing in a temporal branch `1782-4.2.0-full-green-jenkins`.

- [ ] Full green in `wazuh_db` tests for every supported OS

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Status |
|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10328/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10329/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10330/) | :green_circle: |
