### ISSUE TITLE
Full Green Jenkins - Fix Logtest tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1787]
## Description

This issue is part of the [Integration Tests: Reliable Full Yellow Jenkins for 4.2.0](https://github.com/wazuh/wazuh-qa/issues/1677). After the [Research: Check the integration tests status in 4.2.0-RC8](https://github.com/wazuh/wazuh-qa/issues/1493), it has been detected errors in `logtest` tests in the Jenkins environment. 

After some research, it has been determined that the error in the provision step in the Jenkins environment was due to a typo in local internal options, a white space added at the end of the configuration. 

If we launch the tests again with the correct local internal configuration they work correctly.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |  1774-4.2-full-green-local | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### local_internal_options.conf

```
analysisd.debug=2
```

### Test Results - Research

| **Jenkins**  |  **Status** 
|:--:|:--:|
|**Results - Manager**  |   :green_circle: 

- [x] Full Green in `logtest` tests for every supported OS on branch `1774-4.2-full-green-local`.

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Status |
|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10348/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10349/) | :green_circle: |
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10350/) | :green_circle: |
