### ISSUE TITLE
Full Green Jenkins - Fix GCloud tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1790]
## Description

This issue is created to verify that all warnings was fixed to the **GCloud** tests that appear in the issue[ Full Yellow Local - Fix GCloud tests in 4.2](https://github.com/wazuh/wazuh-qa/issues/1532).

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  4.2 |   1774-4.2-full-green-local | 4.2  |  1.1493 | 

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### local_internal_options.conf

```
analysisd.debug=2
wazuh_modules.debug=2
monitord.rotate_log=0  

```
- [x] Full yellow in `GCloud` tests from branch `1774-4.2-full-green-local`

**Comment by MizugorouZ** [comment]
Test results in branch `1774-4.2-full-green-local`

| Jenkins | Date | Executed by | Status |
|:--:|:--:|:--:|:--:|
| [Build](https://ci.wazuh.info/view/Tests/job/Test_integration/10360/) | 31/08/2021 | @MizugorouZ | In execution... |
| [Build]() | xx/xx/2021 | @ | - |
| [Build]() | xx/xx/2021 | @ | - |
