### ISSUE TITLE
QACTL : Create a new QACTL documentation

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#1793]
There are several comments where the user can found the avaliable information given for the qact tool. There is a qactl tool documentation but it's outdated.
The objective of this issue is to create a new QACTL documentation containing all the information avaliable for this tool with the purpose of providing all the possible help & support for a user of this tool.

- [x] Read current documentation.
- [x] Write a new updated documentation.

**Comment by jmv74211** [comment]
The first version of the documentation has been finished. It is available here https://github.com/wazuh/wazuh-qa/wiki/QACTL-tool-documentation
