### ISSUE TITLE
Update API config integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1802]
## Description

A new API configuration option named `max_upload_size` was added in https://github.com/wazuh/wazuh/issues/9054. Said option lets the user choose how big can the body be in the API requests. If the limit is exceeded, a 413 code (Request Entity Too Large) is returned:

```JSON
{
  "title": "Request Entity Too Large",
  "detail": "Maximum request body size 10 exceeded, actual body size 41"
}
```

The following can be specified so there is no limit on the body size:

```YAML
# Maximum body size that the API can accept, in bytes (0 -> limitless)
max_upload_size: 0 
```

## To do
It is necessary to add new API integration tests inside [tests/integration/test_api/test_config](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_config) in order to check that the new feature works as expected.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1494
