### ISSUE TITLE
Improve the configuration options for Authd during agents replacement - IT development

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-qa#1823]
### Description

This is a tracking purposes issue to reflect the work that should be done on Integration Testing for the epic https://github.com/wazuh/wazuh/issues/9550.

After this implementation, the replacement of an agent during the registration process has new configurable constraints.
These are some of the requirements of the new tests

- Fix any test that fails after the implementation
- `test_authd_local`:
    - Create new test cases for the added configurations for a cluster scenario (master)
- `test_authd_force_options` (`test_authd_name_ip_pass.py`):
    - All the different cases of allowing/rejecting the agent's registration should be covered for repeated name and IP (agent's status, agent's inactivity time, etc.)

**Comment by DProvinciani** [comment]
Closing the issue as this is going to be implemented as part of https://github.com/wazuh/wazuh-qa/issues/2050.
