### ISSUE TITLE
QA release: v3.11.0-rc1 - Windows MSI

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#183]
# Windows MSI

| Version | Revision | Branch |
| --- | --- | --- |
| 3.11.0 | rc1 | 3.11 |

## Installation

To check in every test:

- Correct version.
- WUI doesn't show any strange information.
- Service is running correctly.
- No errors in ossec.log.

- [x] Successful installation by UI
- [x] Unattended installation
- [x] Unattended installation with registration parameters
- [x] Check the options "PEM" and "KEY" with absolute paths. (1) "WAZUH_REGISTRATION_CERTIFICATE" and  "WAZUH_REGISTRATION_KEY" **since 3.10**
- [x] Check the options "PEM" and "KEY" with relative paths.
- [ ] Check the option "CERTIFICATE" with absolute paths. (1) "WAZUH_REGISTRATION_CA" **since 3.10**
- [ ] Check the option "CERTIFICATE" with relative paths.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Uninstall

To check in every test:

- It only remains the `client.keys`, `ossec.conf` and `local_internal_options.conf` files.
- The package and service are removed.

- [x] Successful uninstallation by running the MSI
- [x] Successful uninstallation by the Windows control panel

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Upgrade

To check in every test:

- It does not overwrite the `client.keys`, `ossec.conf` and `local_internal_options.conf`.
- WUI doesn't show any strange information.
- Service is restarted correctly.
- No errors in ossec.log.
- No duplicated package when upgrading from the EXE.

- [x] Upgrade MSI from 3.X.X
- [x] Upgrade from the current MSI
- [x] Upgrade MSI from EXE installation 2.X.X
- [x] Upgrade MSI from EXE installation 3.X.X
- [x] Check an unattended installation with PEM and KEY from a previous version.
- [ ] Check an unattended installation with CERTIFICATE from a previous version.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

## Post-installation

- [x] The administrator user has full control on the folder.
- [ ] Any administrator user must confirm UAC to access the folder.
- [ ] Non-administrator user can not access the folder unless he introduces an administrator password.

**Please, see** https://github.com/wazuh/wazuh-qa/issues/183#issuecomment-544422127.

### Versions

- [x] Windows XP
- [x] Windows Server 2003
- [x] Windows Vista
- [x] Windows Server 2008
- [x] Windows 7
- [x] Windows Server 2012
- [x] Windows 8/8.1
- [x] Windows Server 2016
- [x] Windows 10
- [x] Windows Server 2019

(1) Use MS-DOS scaping form for paths with spaces. ( "C:\Program Files\sslagent.cert" would be "C:\Progra\~1\sslagent.cert" and "C:\Program Files x86\sslagent.cert" would be "C:\Progra\~2\sslagent.cert")

**Comment by sergiovp** [comment]
## Tests Windows Server 2019

### Installation

+ Successful installation by UI:
![image](https://user-images.githubusercontent.com/36703917/66913804-b1d4bf00-f015-11e9-9c88-27ddfcc805e8.png)

+ Unattended installation:
![image](https://user-images.githubusercontent.com/36703917/66914010-332c5180-f016-11e9-904d-1287a2e10b36.png)

+ Unattended installation with registration parameters:

**Comment by sergiovp** [comment]
When I install Wazuh 3.7 in Windows Server 2003 I get the following error
`2019/10/21 10:25:57 ossec-agent: ERROR: Unable to add directory to real time monitoring: '%programdata%\microsoft\windows\start menu\programs\startup'.`
If I update to Wazuh 3.11, the error is inherited 
`2019/10/21 10:30:15 ossec-agent: ERROR: (6617): Unable to add directory to real time monitoring: '%programdata%\microsoft\windows\start menu\programs\startup'.`
You have to restart the system in addition to get updated the agent, but the error persists
`2019/10/21 10:32:04 ossec-agent: ERROR: (6617): Unable to add directory to real time monitoring: '%programdata%\microsoft\windows\start menu\programs\startup'.`

I have tried a clean installation of Wazuh 3.11 and we don't have this error.
It means that when we update from 3.7 to 3.11 we get the error.

I'll check if we get the error with others Wazuh versions.

**Comment by sergiovp** [comment]
### Post-installation
+ The administrator user has full control on the folder.
**It worked as expected.**
+ Any administrator user must confirm UAC to access the folder.

Any administrator access the folder without UAC confirmation. Also, we don't have enought permissions to read some files or write some files:

![image](https://user-images.githubusercontent.com/36703917/67081597-bb863000-f197-11e9-9a5d-fbe2800f6cf7.png)

![image](https://user-images.githubusercontent.com/36703917/67081639-d5c00e00-f197-11e9-9425-c7f3d9d9e534.png)

**It does't work as expected.**

+ Non-administrator user can not access the folder unless he introduces an administrator password.
A non-administrator user can access the folder witouth an administrator password.
This non-administrator user has the same permissions than a user belonging to the Administrators group except the Administrator user.

It doesn't work as expected.

This permission errors have been fixed in https://github.com/wazuh/wazuh/pull/3593.
