### ISSUE TITLE
Add a test to check the 'multi-groups' shared file content

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#1852]
|Installation|Component|Version|Related issue|
|---|---|---|---|
|Manager|Remoted|4.2.2+|https://github.com/wazuh/wazuh/issues/9919|

The issue above raises the need to check the content of the _merged.mg_ files that Remoted compiles for multi-groups.

## Test preparation

- Create a new group.
```sh
bin/agent_groups -qag test
```

- Register an agent and add it to the new group (in addition to default)
```sh
bin/manage_agents -a any -n agent1
echo default,test > queue/agent-groups/001
chown ossecr:ossec queue/agent-groups/001
chmod 640 queue/agent-groups/001
```

- Optionally, set `remoted.shared_reload` to a low value:
```sh
echo "remoted.shared_reload=1 >> etc/local_internal_options.conf
pkill remoted
sleep 1
bin/wazuh-remoted
```

### Action

```
touch etc/shared/test/ping
```

### Check

- Wait `remoted.shared_reload` + 1 seconds.
- File `ping` must exist in the multi-group's folder:
```sh
[ -f var/multigroups/2ce0beec/ping ] && echo OK
```

- That file must exist in the file `merged.mg`:
```
[ "$(grep '^!0 ping$' var/multigroups/2ce0beec/merged.mg)" = '!0 ping' ] && echo OK
```

### Action

```
rm etc/shared/test/ping
```

### Check

- Wait `remoted.shared_reload` + 1 seconds.
- File `ping` must not exist in the multi-group's folder:
```sh
[ ! -f var/multigroups/2ce0beec/ping ] && echo OK
```

- That file must not exist in the file `merged.mg`:
```
[ -z "$(grep '^!0 ping$' var/multigroups/2ce0beec/merged.mg)" ] && echo OK
```

## Known versions where this test would fail

- From 3.8 to 4.2.1.

**Comment by mauromalara** [comment]
Working branch: [1852-test-the-multi-groups-shared-file-content](https://github.com/wazuh/wazuh-qa/tree/1852-test-the-multi-groups-shared-file-content)
