### ISSUE TITLE
Daemon handler fixture for test cases

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1855]
### Description

We have created a fixture (https://github.com/wazuh/wazuh-qa/issues/1825) that restarts the required daemons on our tests. However, this fixture is using `get_configuration`, and when we have the same configuration, it won't restart the daemons in every test case. We need to create a fixture that restarts the required daemons without using `get_configuration`.

Furthermore, it is necessary to create different fixtures with different scopes for the cases that have different daemons running, but just one of them needs to be restarted every test case and the rest just need to be started at the beginning and stopped at the end.

### Development

- [x] Create daemon handler fixture with `scope = 'function'`
- [x] Create daemon handler fixture with `scope = 'module'`

**Comment by Rebits** [comment]
### 21/02/202

The structure of the framework has changed a lot since this issue was raised. 

It is necessary to rethink this development to take into account new developments and repository standards.
