### ISSUE TITLE
Fix logic of  'GCloud tests - Logging'

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#1857]
## Description

While working on Issue [#1849 - Coverage Analysis - Phase 2](https://github.com/wazuh/wazuh-qa/issues/1849)  on `master/4.3` branch, an error was found on GCloud test suite. To be specific the error is on the [test_logging](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_gcloud/test_functioning/test_logging.py).

To start, the test description says: 

> _"When a logging option is used, it cannot be an event that has another logging option. For example, events from gcp-pubusb will only have '- INFO -' if logging = info."_.

So, It should be checking for all options available, but there is a repeated option (warning) , and one that is missing (critical). 

Currently, We can see in the code:
> 
>     if logging_opt == 'info':
> 
>         key_words = ['- DEBUG -', '- WARNING -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'debug':
>     
>         key_words = ['- INFO -', '- WARNING -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'warning':
>     
>         key_words = ['- INFO -', '- DEBUG -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'warning':
>     
>         key_words = ['- INFO -', '- DEBUG -', '- WARNING -', '- CRITICAL -']
>         
>     else:
>     
>         key_words = ['- INFO -', '- DEBUG -', '- WARNING -', '- ERROR -']

But, the last `elif`, has a repeated condition, and that needs to be fixed to check what happens when `logging_opt` is set to 'critical'. Also the value for key_words should be checked to be correct in all options. In each option the value that is equal to `logging_opt` should not be present.

I suggest this fix: 

> 
>     if logging_opt == 'info':
> 
>         key_words = ['- DEBUG -', '- WARNING -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'debug':
>     
>         key_words = ['- INFO -', '- WARNING -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'warning':
>     
>         key_words = ['- INFO -', '- DEBUG -', '- ERROR -', '- CRITICAL -']
>         
>     elif logging_opt == 'critical':
>     
>         key_words = ['- INFO -', '- DEBUG -', '- WARNING -', '- ERROR -']
>         
>     else:
>     
>         key_words = ['- INFO -', '- DEBUG -', '- WARNING -', '- CRITICAL -']

**Comment by Rebits** [comment]
This issue is not relevant after https://github.com/wazuh/wazuh-qa/pull/2743.
