### ISSUE TITLE
Full Green Local - Fix API tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1858]
## Description

This issue is created to solve warnings that prevent the `full green` local in the **API** tests.

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1774-4.2-full-green-local| 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### local_internal_options.conf

```
monitord.rotate_log=0 
```

### Test Results - Research

| **Linux manager**   | **Status** 
|:--:|:--: |
|**Test Execution 1**|  🟡 

- [x] Full Green in `API` tests.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1866/files
