### ISSUE TITLE
 FIM Windows Agent  - Case: Apply different configurations properly between subdirectories 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1862]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages details

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

## Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | "gusztavvargadr/windows-10" | Windows | 2 | 2048|

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `tests\integration\test_fim\test_files\test_ambiguous_confs\test_ambiguous_complex.py`  to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [x] Research about the Test Case.
- [x] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [x] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by Deblintrake09** [comment]
### Tests results:
| Name  |  Type  | Result |Test Executions | Note
|--|--|--|--|--|
| test_ambiguous_complex | Windows | :red_circle: | [test_ambiguous_complex - Run1.zip](https://github.com/wazuh/wazuh-qa/files/7177230/test_ambiguous_complex.-.Run1.zip) | Got **Timeout** and **File Not Found** errors
| test_ambiguous_complex | Manager | :green_circle:  |  [TestAmbiguousComplex.zip](https://github.com/wazuh/wazuh-qa/files/7177193/TestAmbiguousComplex.zip) | 
| test_ambiguous_complex | Windows | :green_circle:  |  [TestAmbiguousComplex - Manager.zip](https://github.com/wazuh/wazuh-qa/files/7177204/TestAmbiguousComplex.-.Manager.zip)  | 
| test_ambiguous_complex | Windows | :red_circle: :red_circle:  | [Test_Ambiguous - Run 3 & 4.zip](https://github.com/wazuh/wazuh-qa/files/7177214/Test_Ambiguous.-.Run.3.4.zip) | Removed/deactivated unused modules, **Got only File Not Found error**.

**Comment by Deblintrake09** [comment]
The Test has realtime, scheduled and whodata test cases, they can be ran using all arguments, or with none of them and it will run all tests, either way.

**Comment by Deblintrake09** [comment]
All test pass after fixing jq dependency.

### Tests results:
| Name  |  Type  | Result |Test Executions | Date |
|--|--|--|--|--|
| test_ambiguous_complex | Windows | :green_circle:  | [ResultsAmbiguousComplex.zip](https://github.com/wazuh/wazuh-qa/files/7195450/ResultsAmbiguousComplex.zip) | 2021/09/19
| test_ambiguous_complex | Windows | :green_circle: | [ResultsAmbiguousComplex2.zip](https://github.com/wazuh/wazuh-qa/files/7195452/ResultsAmbiguousComplex2.zip)| 2021/09/19
| test_ambiguous_complex | Windows |:green_circle: | [ResultsAmbiguousComplex3.zip](https://github.com/wazuh/wazuh-qa/files/7195453/ResultsAmbiguousComplex3.zip)| 2021/09/19

**Comment by damarisg** [comment]
The results after to merge continue to be successful. 

## Test Results 
| Results | Date | By | Status |
|--|--|--|--|
[ResultsAmbiguousComplex.zip](https://github.com/wazuh/wazuh-qa/files/7219970/ResultsAmbiguousComplex.zip)  | 2021/09/23 | Seyla | 🟢 

It is closed by  #1909.
