### ISSUE TITLE
Disable not used modules during tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1867]
### Description

According to the [repository standard](https://github.com/wazuh/wazuh-qa/wiki/Development-guidelines), only necessary modules should be enabled in the `ossec.conf`. It is necessary to create a fixture that gets the configuration from the test and set the modules in the `ossec.conf` to enabled or disabled.

### Development

- [ ] Create `modules_handler` fixture

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
