### ISSUE TITLE
QA release: v3.11.0-rc1 - Communication

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#187]
# Communication test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.11.0 | rc1 | 3.11 |

## Manager - agent

- [x] Connect an agent by UDP successfully and verify alerts and services work properly. (1)
- [x] Connect an agent by TCP successfully and verify alerts and services work properly. (1)
- [x] Connect an agent with a different port. (1)
- [x] Agent re-connects successfully after a manager recovery.
- [x] Test both crypto methods available (AES and blowfish).
- [x] Configure several managers to an agent, check if it works. (1)
- [x] Test large messages (up to 64K) (3).
- [x] Test large labels (up to 20K).
- [x] Connect to a manager by resolving its domain with DNS. (1)
- [x] Use legacy configuration (server-ip, server-hostname, protocol, port).
- [x] Check statistics files for analysisd, remoted and agentd.
- [x] Check if the agent-info file contains the agent IP. 
- [x] Stop Modulesd and check that the agent-info file does not contain the agent IP.
- [x] Test the agent doesn't start with the default IP address (MANAGER_IP, 0.0.0.0 or empty).

(1) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/client.html
(3) You have to write the alert in a monitorized log, for example: **active-response.log**

## Syslog events

- [x] Send syslog events from an agent to the manager (UDP/TCP). (2)
- [x] Deny the IP of an agent and check that is not allowed to send events. (2)
- [x] Specify a local_ip in the manager for receive syslog events. (2)

(2) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/remote.html

**Comment by Lopuiz** [comment]
## The agent-info file contains the agent IP.

```
[root@agent2 ossec]# pkill -9 modulesd
[root@agent2 ossec]# ps aux | grep wazuh
ossec    24631  5.6  0.6 636244  6692 ?        Sl   10:52   0:03 /var/ossec/bin/wazuh-db
root     25471  0.0  0.0 112712   952 pts/0    S+   10:53   0:00 grep --color=auto wazuh
[root@agent2 ossec]# cat queue/agent-info/agent-10.0.0.5 
Linux |agent |5.0.0-32-generic |#34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 |x86_64 [Ubuntu|ubuntu: 19.04 (Disco Dingo)] - Wazuh v3.11.0 / ab73af41699f13fdd81903b5f23d8d00
276b7a745ee8e6f187f8d26879afe48d merged.mg
#"_agent_ip":10.0.2.15

#"_manager_hostname":agent2
#"_node_name":node01
```
