### ISSUE TITLE
FIM Windows Agent - Case: Check number of inotify watches when renaming and deleting a directory

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1887]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages details

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```
## Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  "gusztavvargadr/windows-10" | Windows | 2 | 2048|

## pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `test_fim\test_files\test_inotify\test_num_watches.py` to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [x] Research about the Test Case.
- [x] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [x] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by Deblintrake09** [comment]
** Test Results ** 
Test| System | Date | Results | Status | Notes
--|--|--|--|--|--|
| test_num_watches.py  | 2021/09/17 | [ResultsInotify.zip](https://github.com/wazuh/wazuh-qa/files/7185864/ResultsInotify.zip) | :green_circle: 
| test_num_watches.py | Windows | 2021/09/17 | [ResultsInotify2.zip](https://github.com/wazuh/wazuh-qa/files/7185873/ResultsInotify2.zip)  | :green_circle:
| test_num_watches.py | Windows | 2021/09/17 | [ResultsInotify3.zip](https://github.com/wazuh/wazuh-qa/files/7185874/ResultsInotify3.zip) | :green_circle: 
| test_inotify Folder | Windows | 2021/09/17 | [ResultsInotifyFolder.zip](https://github.com/wazuh/wazuh-qa/files/7185887/ResultsInotifyFolder.zip) | :red_circle: | test_num_watches.py passes, test_remove_rename_folder fails.

**Comment by Deblintrake09** [comment]
**Test Results ** 
| Result | Date | Executed by | Status |  Note |
|:--:|:--:|:--:|:--:|:--:|
| [ResultsTestRemoveRenameFolder1.zip](https://github.com/wazuh/wazuh-qa/files/7195405/ResultsTestRemoveRenameFolder1.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test run with machine set up using setup.py with modification.
| [ResultsTestRemoveRenameFolder2.zip](https://github.com/wazuh/wazuh-qa/files/7195407/ResultsTestRemoveRenameFolder2.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test run with machine set up using setup.py with modification.
|[ResultsTestRemoveRenameFolder3.zip](https://github.com/wazuh/wazuh-qa/files/7195408/ResultsTestRemoveRenameFolder3.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test run with machine set up using setup.py with modification.
| [ResultsInotifyFolder1.zip](https://github.com/wazuh/wazuh-qa/files/7195416/ResultsInotifyFolder1.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test results for the whole /test_inotify folder
| [ResultsInotifyFolder2.zip](https://github.com/wazuh/wazuh-qa/files/7195417/ResultsInotifyFolder2.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test results for the whole /test_inotify folder
| [ResultsInotifyFolder3.zip](https://github.com/wazuh/wazuh-qa/files/7195418/ResultsInotifyFolder3.zip) | 2021/09/17 | @Deblintrake09 | :heavy_check_mark:  | Test results for the whole /test_inotify folder

**Comment by damarisg** [comment]
The results after to merge continue to be successful. 

## Test Results 
| Results | Date | By | Status |
|--|--|--|--|
|[ResultsInotify.zip](https://github.com/wazuh/wazuh-qa/files/7220262/ResultsInotify.zip)|  2021/09/23 | Seyla | 🟢 

It is closed by  #1909.
