### ISSUE TITLE
FIM Windows Agent - Case: Registry 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1888]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```
### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | "gusztavvargadr/windows-10" | Windows | 2 | 2048 |

### pytest_args
`-v --fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`

## Development

It requires that all `test_fim/test_registry/` folder works successfully on Windows. For that reason, you need to fix all failures found on it, specifically, the tests that fail are:
    - `test_fim/test_registry/test_registry_basic_usage/test_basic_usage_registry_duplicated_entries.py`. 
    - `test_fim/test_registry/test_registry_multiple_registries/test_multiple_keys.py` 
    
If the test works successfully after 2 times, you should see if another member could verify that it works successfully. 

| Resuts | Date | By | Status
|--|--|--|--|
[ResultsRegistry.zip](https://github.com/wazuh/wazuh-qa/files/7227708/ResultsRegistry.zip) | 2021/09/24 | Andres | 🔴 

## Tasks
- [x] Research about the Test Case.
- [x] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [x] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by danisan90** [comment]
**Local Results** 

These are the results of executing  `test_fim\test_files\test_registry/` with the parameters `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`
| Results |Date| By | Status |
|:--:|:--:|:--:|:--:|
| [ResultsRegistry](https://github.com/wazuh/wazuh-qa/files/7251366/ResultsRegistryall.log) | 2021/09/26 |@danisan90|  🔴 

In order to detect the problem with the tests, these modules were disabled for the folder: `Rootcheck`, `Sca`, `Syscollector`, `Active Response`. Some tests passed but others failed because they uses `Syscollector`. 
|:--:|:--:|:--:|:--:|
|[ResultsRegistry2.zip](https://github.com/wazuh/wazuh-qa/files/7251511/ResultsRegistry2.zip)| 2021/09/27 |@danisan90|  🔴

**Comment by MizugorouZ** [comment]
Tests results for `test_fim/test_registry/` in Windows agent with the parameters `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`:

| Round | OS - Manager/Agent - Module | Date | By | Reports | Notes |
|:--:|:--:|:--:|:--:|:--:|:--:|
| R1 | Windows 10 - Agent - `test_fim/test_files/test_tags` | 2021/10/04 | @MizugorouZ | [:red_circle:](https://github.com/wazuh/wazuh-qa/files/7286137/R1-1888.zip) | Executed without disabling any component |
| R2 | Windows 10 - Agent - `test_fim/test_files/test_tags` | 2021/10/04 | @MizugorouZ | [:red_circle:](https://github.com/wazuh/wazuh-qa/files/7286175/R2-1888.zip) | Components disabled manually (sca, rootcheck, syscollector) |
