### ISSUE TITLE
QA release: v3.11.0-rc1 - Logcollector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#189]
# Logcollector test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.11.0 | rc1 | 3.11 |

## Configuration

- [x] Add log.
- [x] Delete all localfile entries and start Logcollector.
- [x] Test Logcollector internal options.
- [x] Increase both `logcollector.max_files` and `logcollector.rlimit_nofile` and check if everything works with the maximum number of files allowed.
- [x] Check that the agent bookmarks Eventchannel logs.
- [x] Set `<only-future-events>` to `yes` and check that the agent is not bookmarking Eventchannel logs.
- [x] Add localfile blocks with wildcards or time templates.

## Logs

- [x] Solve the reading of a file when changing its inode.
- [x] Check that Eventlog/Eventchannel logs are read in all supported versions of Windows.
- [x] Truncate file.
- [x] Check for new paths that match a wildcards after starting Logcollector.
- [x] Check **all the tests** changing the order of the parameters in combination with normal and daily wildcards.
- [x] Check that labels are added to JSON files.
- [x] Check that the multi-line logs are taken correctly.
- [x] Check that no duplicate files are scanned (entered multiple times).
- [x] Check that no duplicate inodes are scanned (hard and soft links).
- [x] Check logcollector functionality with already created files that match configured wildcards or templates and creating them after logcollector starts (they will be contemplated after reloading).
- [x] Check that the agent sends the Windows Eventchannel events generated when it was stopped. (https://github.com/wazuh/wazuh/issues/3475)

## Performance

- [x] Monitor the memory wasted by Logcollector in the previous operations.

## Sockets

- [x] Configure one and multiple sockets output as target. (https://github.com/wazuh/wazuh/pull/395)
- [x] Test the `out_format` option for different socket targets. (https://github.com/wazuh/wazuh/pull/863)

## Commands

- [x] Prevent remote commands, with `command` or `full_command`, if `logcollector.remote_commands` is disabled.
- [x] Check that the output of a command is captured line by line (with `command`) and completely (with `full_command`)
- [x] Check the correct output of *netstat* commands.

**Comment by Lopuiz** [comment]
## Issue
 
When Wazuh start if file doesn't exist it should be remove from Logcollector immediately but it doesn't.

As show following logs it take too long to be removed:

```
2019/10/15 13:15:36 ossec-logcollector: ERROR: (1103): Could not open file '/var/ossec/logs/active-responses.log' due to [(2)-(No such file or directory)].
2019/10/15 13:15:36 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2019/10/15 13:15:36 ossec-logcollector: INFO: (1950): Analyzing file: '/home/prueba_json.txt'.
2019/10/15 13:15:36 ossec-logcollector: INFO: (1950): Analyzing file: '/home/prueba_snort.txt'.
2019/10/15 13:15:36 ossec-logcollector: INFO: (1950): Analyzing file: '/home/prueba_nmapg.txt'.
2019/10/15 13:15:36 ossec-logcollector: INFO: Started (pid: 6641).
2019/10/15 13:15:56 ossec-logcollector: INFO: Agent is now online. Process unlocked, continuing...
2019/10/15 13:19:58 ossec-logcollector: INFO: (1904): File not available, ignoring it: '/var/ossec/logs/active-responses.log'.
```

**Comment by Lopuiz** [comment]
## Issue: Log format option

1.  Value `mysql_log` doesn't work
2. Value `postgresql_log` doesn't work

*Issue:* [4056](https://github.com/wazuh/wazuh/issues/4056)

**Comment by Lopuiz** [comment]
## Issue: Windows agent doesn't execute commands

Windows agent doesn't execute commands when they come from `agent.conf`.

The manager sends the configuration to the agent and it can be shown in the agent's `agent.conf` but the commands don't execute.

**Comment by Lopuiz** [comment]
## Issue:  Logcollector sends old contents of the scanned file
Every time agent restart Logcollector, it read al log from the file and send to the manager. There is open Github issue about it.
*Issue:* [4030](https://github.com/wazuh/wazuh/issues/4030)

**Comment by Lopuiz** [comment]
## Issue: There are inconsistencies in wildcards

While Linux agent (or manager) accepts wildcards like `oss??.log` or `fa[!o]l.txt`, the Windows agent doesn't accept (only accept `*`).

In Windows agent we obtain erro messages as follow:
```
2019/10/17 07:23:28 ossec-agent: INFO: (1957): New file that matches the 'C:\Users\Administrator\Documents\t*.log' pattern: 'C:\Users\Administrator\Documents\tjson.log'.
2019/10/17 07:23:28 ossec-agent: INFO: (1957): New file that matches the 'C:\Users\Administrator\Documents\t*.log' pattern: 'C:\Users\Administrator\Documents\tjson2.log'.
2019/10/17 07:23:28 ossec-agent: INFO: (1957): New file that matches the 'C:\Users\Administrator\Documents\t*.log' pattern: 'C:\Users\Administrator\Documents\tsyslog.log'.
2019/10/17 07:23:28 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2019 Standard Evaluation [Ver: 10.0.17763] - Wazuh v3.10.2).
2019/10/17 07:23:28 ossec-agent: INFO: (1951): Analyzing event log: 'Application'.
2019/10/17 07:23:28 ossec-agent: INFO: (1951): Analyzing event log: 'Security'.
2019/10/17 07:23:28 ossec-agent: INFO: (1951): Analyzing event log: 'System'.
2019/10/17 07:23:28 ossec-agent: INFO: (1950): Analyzing file: 'active-response\active-responses.log'.
2019/10/17 07:23:28 ossec-agent: ERROR: (1103): Could not open file 'C:\Users\Administrator\Documents\fa[!o]l.txt' due to [(2)-(The system cannot find the file specified.)].
2019/10/17 07:23:28 ossec-agent: INFO: (1950): Analyzing file: 'C:\Users\Administrator\Documents\fa[!o]l.txt'.
2019/10/17 07:23:28 ossec-agent: INFO: (1950): Analyzing file: 'C:\Users\Administrator\Documents\tjson.log'.
2019/10/17 07:23:28 ossec-agent: INFO: (1950): Analyzing file: 'C:\Users\Administrator\Documents\tjson2.log'.
2019/10/17 07:23:28 ossec-agent: INFO: (1950): Analyzing file: 'C:\Users\Administrator\Documents\tsyslog.log'.
2019/10/17 07:23:28 ossec-agent: INFO: Started (pid: 1588).
```
