### ISSUE TITLE
Rework of FIM integration/system tests due to new synchronization mechanism

### ISSUE THREAD

**Issue by JoseAntonioMHerrera** [wazuh/wazuh-qa#1915]
Due to the implementation of **rsync** as the new engine for FIM db synchronization the following tests need to be reworked to adapt to the new sync messages coming from rsync.

## Test synchronization

* test_registry_responses_win32.py
* test_response_timeout.py
* test_sync_disabled_win32.py

All the above tests look for synchronization events messages that now will be deleted.

## Test files

* test_max_eps_synchronization.py
 
The above test assesses the max sync events per second defined in syscheck configuration for the synchronization process.

## Test limits

The new design implies that the DB limits are now separated in:

- Limit for the number of entries in the files table
- Limit for the number of entries in the registry table

The following tests would be affected by the changes introduced at https://github.com/wazuh/wazuh/issues/10224:

```
/wazuh-qa/tests/integration/test_fim# find . -name "*limit*"
./test_registry/test_registry_file_limit
./test_registry/test_registry_file_limit/test_registry_limit_values.py
./test_registry/test_registry_file_limit/test_registry_limit_capacity_alerts.py
./test_registry/test_registry_file_limit/test_registry_limit_full.py
./test_registry/test_registry_report_changes/test_registry_diff_size_limit_values.py
./test_registry/test_registry_report_changes/test_registry_all_limits_disabled.py
./test_registry/test_registry_report_changes/data/wazuh_registry_report_changes_limits_quota.yaml
./test_files/test_report_changes/test_diff_size_limit_configured.py
./test_files/test_report_changes/test_diff_size_limit_default.py
./test_files/test_file_limit
./test_files/test_file_limit/test_file_limit_values.py
./test_files/test_file_limit/test_file_limit_no_limit.py
./test_files/test_file_limit/test_file_limit_full.py
./test_files/test_file_limit/test_file_limit_default.py
./test_files/test_file_limit/test_file_limit_delete_full.py
./test_files/test_file_limit/test_file_limit_capacity_alerts.py
```

**Comment by damarisg** [comment]
During Sprint 2, the tests were analyzed and it was decided to create sub-issues because being a TDD job this would take more than one Sprint and it is necessary to carry out the analysis of the entire process.

**Comment by damarisg** [comment]
Each change is located on `1915-fim-rsync-new-synchronization-mechanism`

**Comment by damarisg** [comment]
In addition, this issue contains the new changes applied by [3036](https://github.com/wazuh/wazuh-qa/issues/3036)

**Comment by Deblintrake09** [comment]
### Update 2022/11/28

- Start fixing conflicts with master
- Fix failing tests

### Update 2022/11/29
 
- Continue fixing tests style and spacing
- Debug `test_registry_responses_win32.py` that fails but expected message is read in logs.

**Comment by Deblintrake09** [comment]
## Update 03/01/2023
- Update branch
- Launch Jenkins Instances
- Debug and fix failing tests
- Ask Core about errors found

**Comment by Deblintrake09** [comment]
## Update 05/01/2023
- Created new pachages after Core's FIX
- Launched Jenkins IT
- Debug failing test cases for test_max_eps
- Found possible bug: whodata mode misses events. 
- Asked Core about errors found https://wazuh-team.slack.com/archives/C019A838R6Y/p1672943668207489

**Comment by Deblintrake09** [comment]
## Update 11/01/23
- Research failing tests
- Launch Jenkins ITs
- Ready to review

**Comment by Deblintrake09** [comment]
## Update 13/01/2023
- Added skip mark to `test_max_eps.py`, caused by @wazuh/wazuh Issue #15844
- Created Issue https://github.com/wazuh/wazuh-qa/issues/3749 to track, and enable test after [#15844](https://github.com/wazuh/wazuh/issues/15844) is done.

**Comment by Deblintrake09** [comment]
### Update 26/01/2023
- Generate packages
- Fix conflicts with master

**Comment by Deblintrake09** [comment]
### Update 27/01/2023
- Debug failing IT `test_restrict_valid`
- Found possible Bug on branch on Windows
- Running Windows master instance to validate.

**Comment by Deblintrake09** [comment]
## Update 30/01/2023
- Finish fixing `test_restrict_valid`
- Launched Jenkins instances
