### ISSUE TITLE
Develop a tool to create a report based on cluster statistics

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1938]
In this issue, we want to create a tool that parses the data from the CSV files that we obtain from the pipeline execution and based on this data generates a report that can be used for a manual analysis as well as for the performance and behavior test itself.

We can take the following CSV files as an example:

#### Cluster's tasks
- [agent-info_sync.csv](https://github.com/wazuh/wazuh-qa/files/7245650/agent-info_sync.csv)
- [integrity_check.csv](https://github.com/wazuh/wazuh-qa/files/7245648/integrity_check.csv)
- [integrity_sync.csv](https://github.com/wazuh/wazuh-qa/files/7245646/integrity_sync.csv)

#### Resources consumption
- [wazuh-clusterd.csv](https://github.com/wazuh/wazuh-qa/files/7245656/wazuh-clusterd.csv)

**Comment by Selutario** [comment]
## Issue update

To carry out this development, I am creating a class called (for now), CSVParser. This class will accept as a parameter the path to an artifacts folder with the logs and CSVs of each node.

Since the CSVs already contains just the right information and are not very large, I am storing them all at the beginning inside a dictionary. This avoids loading and parsing the same files multiple times at different parts, so it should speed up the performance.

To parse and work with the data, the Pandas library is being used.

**Comment by Selutario** [comment]
## Issue update

I continue with the development of the class / tool that will parse the CSV with information from the environment and obtain statistics from it. At the moment, the tool is already capable of doing the following things:
- Load in a dictionary both the CSVs with information on cluster tasks (`artifacts/node_name/data/logs/*.csv`) and on resources such as RAM, CPU, etc. (`artifacts/node_name/data/binaries/wazuh-clusterd.csv`) as dataframes.
- Determine where the setup phase begins and ends in each dataframe.
- Work with each dataframe dividing it into phases.
- Group and concatenate the dataframes of all workers (phases and tasks) to collect statistics of grouped data.


The biggest difficulty is that the CSVs of the tasks and those of the resources are not the same (they have different columns). Therefore, although at the moment the development is done entirely under a class called ClusterCSVParser, it may be necessary to divide it and use inheritance.

**Comment by Selutario** [comment]
## Issue update

The tools is complete and it is working correctly. It is capable of loading all the CSVs, calculating the mean and regression coefficient of each column and returning which is the maximum value of all the nodes. In addition, this data is returned divided by phases. This is an example result:

**TASKS**
```PYTHON
{
    "setup_phase": {
        "integrity_check": {
            "workers": ("worker_4", 2.882842105263158),
            "master": ("master", 1.7251713780918725),
        },
        "integrity_sync": {
            "workers": ("worker_3", 0.8801250000000002),
            "master": ("master", 3.7857918149466196),
        },
        "agent-info_sync": {
            "workers": ("worker_4", 2.0509978833333333),
            "master": ("master", 0.4447335640138408),
        },
    },
    "stable_phase": {
        "integrity_check": {
            "workers": ("worker_8", 1.6634466019417473),
            "master": ("master", 0.726184287099903),
        },
        "agent-info_sync": {
            "workers": ("worker_8", 0.7170288461538461),
            "master": ("master", 0.2620988372093024),
        },
    },
}
```

**RESOURCES**
```PYTHON
{
    "setup_phase": {
        "wazuh-clusterd": {
            "USS(KB)": {
                "mean": {
                    "workers": ("worker_9", 75079.43661971831),
                    "master": ("master", 163284.44755244756),
                },
                "reg_cof": {
                    "workers": ("worker_9", 489.7276436479312),
                    "master": ("master", 1759.8759644111753),
                },
            },
            "CPU(%)": {
                "mean": {
                    "workers": ("worker_8", 8.525352112676055),
                    "master": ("master", 52.511888111888105),
                },
                "reg_cof": {
                    "workers": ("worker_5", 0.04679342234032074),
                    "master": ("master", 0.28662464296267104),
                },
            },
            "FD": {
                "mean": {
                    "workers": ("worker_6", 14.195804195804195),
                    "master": ("master", 42.61538461538461),
                },
                "reg_cof": {
                    "workers": ("worker_3", 0.0024418070192718387),
                    "master": ("master", -0.03370924849798087),
                },
            },
        }
    },
    "stable_phase": {
        "wazuh-clusterd": {
            "USS(KB)": {
                "mean": {
                    "workers": ("worker_9", 106824.18433179724),
                    "master": ("master", 218785.16129032258),
                },
                "reg_cof": {
                    "workers": ("worker_1", 9.019405572231445),
                    "master": ("master", -70.75089840612243),
                },
            },
            "CPU(%)": {
                "mean": {
                    "workers": ("worker_8", 10.96589861751152),
                    "master": ("master", 41.93041474654378),
                },
                "reg_cof": {
                    "workers": ("worker_4", 0.0013146089056121396),
                    "master": ("master", -0.002096750705806691),
                },
            },
            "FD": {
                "mean": {
                    "workers": ("worker_5", 14.055299539170507),
                    "master": ("master", 24.341013824884794),
                },
                "reg_cof": {
                    "workers": ("worker_6", 0.0001952869169673985),
                    "master": ("master", -0.014530691432141685),
                },
            },
        }
    },
}
```

## TO DO
- Try to avoid redundancies in the code by using inheritance.
- Investigate some way to iterate through the dictionaries with several levels of nesting without nesting loops, but with other more elegant solution.
