### ISSUE TITLE
Integration test for Agent Key polling port to Authd

### ISSUE THREAD

**Issue by juanmanuelug** [wazuh/wazuh-qa#1979]
## Description

This issue is part of [wazuh/wazuh#10399](https://github.com/wazuh/wazuh/issues/10399).

The [Agent Key Polling](https://documentation.wazuh.com/current/user-manual/capabilities/agent-key-polling.html) module is going to be ported to Authd.

The following tests should cover the port of the module:

## Configuration test

A new configuration block is added to support the new integration. It is defined at https://github.com/wazuh/wazuh/issues/10430.

A test should be created to ensure the configuration is applied properly.

## Operational tests

The goal of these tests is to verify the operation of the component in different situations.

**Basic behavior**

This test checks how Authd works when receiving an agent key request with the following parameters:
- Key Request enabled/disabled

When enabled, the agent key is requested to the external integration. Otherwise, a log message should indicate that the agent is not available in the key storage.

- Master or worker

In both cases, the agent key is requested to the external integration when the Key Request is enabled. On success, the master node will register the agent and the worker node will forward the registration request to the cluster daemon.

- Executable path or external socket

The agent key request should be forwarded to any of these two options depending on the configuration.

## Limits

Extremes of the configurable settings should be tested to ensure they work.

**Timeout**

Simulate a timeout (according to the `timeout` setting) when requesting the agent key and catch the return error.

**Queue size**

Reach the queue size (see the `queue_size` setting) when requesting agent keys and catch the return error.

### Tests progress

- [x] Success request and registration with ID and IP agent (operational)
- [x] Success request and forward in worker node (operational)
- [x] Failed response from the external integration (operational)
- [x] Error when running external integration (operational)
- [x] Error when missing external script (operational)
- [x] Timeout error (limits)
- [x] Queue size reached (limits)

**Comment by MarcelKemp** [comment]
Devel branch: https://github.com/wazuh/wazuh-qa/tree/1979-key-request-IT
