### ISSUE TITLE
System tests to cover the Agent Key Polling port to Authd

### ISSUE THREAD

**Issue by alromeros** [wazuh/wazuh-qa#1981]
## Description

The functionalities corresponding to the [Agent Key Polling](https://documentation.wazuh.com/current/user-manual/capabilities/agent-key-polling.html) module are going to be ported to **Authd**, meaning that all related **system tests** will also have to be adapted accordingly.

The diagram above shows the design of the new Key Request implementation:

![image](https://user-images.githubusercontent.com/29475387/136371166-2f82ed50-316b-45cf-a8f9-9b758784c14e.png)

More details at https://github.com/wazuh/wazuh/issues/10399.

Currently, the system test for the agent key polling runs two managers (master and worker) and a single agent. It simulates a failed connection and a request to the module, after that it checks the agent is connected again.

This issue should make this test work over Authd instead of the Agent Key Polling module which is deprecated from now on.

Best regards.

**Comment by juanmanuelug** [comment]
Devel branch: https://github.com/wazuh/wazuh-qa/tree/1981-system-tests-for-Key-Polling-port-to-Authd
