### ISSUE TITLE
Fix requirements markers for MacOS and Solaris

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2001]
## Description

While executing the test from #1474, we could see that the tests failed in the local environment because we needed to install `jq` externally. (The test passes in Jenkins because the environment is provided with `jq` already installed).
https://github.com/wazuh/wazuh-qa/blob/5450c1423e626f94c7d276a36982ac9d137b1459/deps/wazuh_testing/wazuh_testing/fim.py#L1575-L1579
Install external programs should be an exception, we should install them with `pip` and then import the library as it is done here:
https://github.com/wazuh/wazuh-qa/blob/5450c1423e626f94c7d276a36982ac9d137b1459/deps/wazuh_testing/wazuh_testing/fim.py#L37-L38

We tried to implement this change and the test passed in the local environment, but it failed in [Jenkins](https://ci.wazuh.info/view/Tests/job/Test_integration/12962/). It couldn't be executed because there was an error importing the `jq` module. 

Finally, we saw that `jq` wasn't being installed (as other requirements) because of the markers:

https://github.com/wazuh/wazuh-qa/blob/5450c1423e626f94c7d276a36982ac9d137b1459/requirements.txt#L33

MacOS marker isn't correct and Solaris  is not even contemplated.

```
>>> import platform
>>> platform.system()
'Darwin'
```

```
>>> import platform
>>> platform.system()
'SunOS'
```

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
