### ISSUE TITLE
 QA release: v3.11.0-rc1 -  OSQuery integration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#201]
# osquery test

| Version | Revision | Branch | OSQuery version
| --- | --- | --- | --- |
| 3.11.0 | rc1 | 3.11 | 4.0.2 (current) |

[OSQuery 4.0.2](https://osquery.io/downloads/official/4.0.2) is out. We have to ensure this new version is still supported by the Wazuh integration.

## On Linux

- [x] Enable / disable daemon.
- [x] Check invalid configuration. The module should log a warning and continue.
- [x] Pack file definitions.
- [x] Pack folder definition: `<pack name="*">/usr/share/osquery/packs/*</pack>`.
- [x] Enrich existing decorators with agent labels.
- [x] Add labels, no previous decorators defined.
- [x] Combine `<add_labels>` and `<pack>` options.
- [x] Invalid permissions (owner) for *osqueryd* binary. It **should log an error and stop**.
- [x] *osqueryd* already running when agent is started. It should log a message every minute.
- [x] If it tries to start *osqueryd* before the previous dies on restart, t should reattempt to run one minute later.
- [x] Try an Invalid path for `<log_path>` or unexisting log file. The module should reattempt up to one minute delay.
- [x] Truncate results log (`echo -n > osquery.results.log`). The module should go back to the file begin, no data lost.
- [x] Remove results log. The module should finish reading the current file and reload the new one, no data lost.
- [x] Add query pack folder to a shared folder. That folder should appear in the agent.
- [x] Agent labels with single quotes: `<label key="node">Node for 'nginx'</label>`. No SQL code injection.
- [ ] Insert C/C++ comments to JSON configuration. The module should be able to insert decorators and packs.
- [x] Kill *osqueryd* while being run by the agent. The module should restart it only if it ran during 10 seconds at less.
- [x] Unexisting folder */var/osquery*. The module **should report the error** and the manager should create an alert.
- [x] Declaring osquery module multiple times (*ossec.conf* and another in *agent.conf*). Only the last one applies
- [ ] Unexisting configuration with `<add_labels>` disabled and no `<pack>`. The module should log it, wait 10 minutes and retry.

## On Windows

- [ ] Invalid permissions (owner) for *osqueryd* binary. It **should log an error and stop**.
- [x] *osqueryd* already running when agent is started. It should log a message every minute.
- [ ] If it tries to start *osqueryd* before the previous dies on restart, t should reattempt to run one minute later.
- [ ] Truncate results log (`echo -n > osquery.results.log`). The module should go back to the file begin, no data lost.
- [ ] Remove *results log*. The module should finish reading the current file and reload the new one, no data lost.
- [ ] Add query pack folder to a shared folder. That folder should appear in the agent.
- [ ] Kill *osqueryd* while being run by the agent. The module should restart it only if it ran during 10 seconds at less.

**Comment by Lopuiz** [comment]
## Issue: Warning messages when adding C/C++ comments in Osquery configuration

Respecto al check: *Insert C/C++ comments to JSON configuration. The module should be able to insert decorators and packs.*

We don't consider the packs could be in the Osquery configuration file.
If it happens and there aren't any pack in Wazuh configuration, We can't add C/C++ comments in Osquery configuration.

If do it, these messages apear in `ossec.log`:
```
2019/10/23 07:47:01 wazuh-modulesd:osquery: WARNING: E1023 07:46:41.377693  4731 config.cpp:774] updateSource failed to parse config, of source: /etc/osquery/osquery.conf and content: /* Osquery configuration */
2019/10/23 07:47:02 wazuh-modulesd:osquery: WARNING: W1023 07:46:41.377753  4731 init.cpp:691] Error reading config: Error parsing the config JSON
``` 

And the following messages are sent to analysisd:
```
2019 Oct 23 09:46:57 (agent) 10.0.0.5->ossec ossec: Agent started: 'agent->10.0.0.5'.
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery I1023 07:46:41.376497  4731 database.cpp:570] Checking database version for migration
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery E1023 07:46:41.377693  4731 config.cpp:774] updateSource failed to parse config, of source: /etc/osquery/osquery.conf and content: /* Osquery configuration */
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery     "options": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "config_plugin": "filesystem",
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "logger_plugin": "filesystem",
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "utc": "true"
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery     },
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery     "schedule": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "system_info": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "interval": 3600
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         },
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "high_load_average": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "query": "SELECT period, average, '70%' AS 'threshold' FROM load_average WHERE period = '15m' AND average > '0.7';",
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "interval": 900,
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "description": "Report if load charge is over 70 percent."
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         },
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "low_free_memory": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "query": "SELECT memory_total, memory_free, CAST(memory_free AS real) / memory_total AS memory_free_perc, '10%' AS threshold FROM memory_info WHERE memory_free_perc < 0.1;",
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "interval": 1800,
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "description": "Free RAM is under 10%."
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         }
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery     },
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery     "packs": {
2019 Oct 23 09:47:01 (agent) 10.0.0.5->osquery         "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery         "incident-response": "/usr/share/osquery/packs/incident-response.conf",
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery         "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery         "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery         "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf",
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery         "ossec-rootkit": "/usr/share/osquery/packs/ossec-rootkit.conf"
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery     }
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery }
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery W1023 07:46:41.377753  4731 init.cpp:691] Error reading config: Error parsing the config JSON
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery I1023 07:46:41.377934  4731 events.cpp:863] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
2019 Oct 23 09:47:02 (agent) 10.0.0.5->osquery I1023 07:46:41.378182  4731 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configuration
```
And following alert is repeated a lot of times:
```json
{"timestamp":"2019-10-23T09:47:02.092+0200","rule":{"level":3,"description":"osquery warning message","id":"24002","firedtimes":4,"mail":false,"groups":["osquery"]},"agent":{"id":"011","name":"agent","ip":"10.0.2.15"},"manager":{"name":"lopezziur"},"id":"1571816822.408404","decoder":{},"location":"osquery"}
```

**Comment by Lopuiz** [comment]
##  Osquery module works without error messages although it haven't packs configured

I think it is the behavior expected because the packs can be added in the Osquery configuration.

**Comment by Lopuiz** [comment]
## Osquery module doesn't work in Windows

The new Osquery version is installed in `C:\Program File` directory instead of `C:\ProgramData`. So we must update the `osquery_monitor->bin_path`, `osquery_monitor->log_path` and `osquery_monitor->config_path`.

Also, the command to start Osquery must have double quotes in the config path. If we won't do it, the path file will be cut to `C:\Program`

Once it done the following error messages appears:
```
2019/10/24 02:18:31 wazuh-modulesd:osquery: WARNING: Results file 'C:\Program Files\osquery\log\osqueryd.results.log' not available: No error (0). Retrying in 1 sec.
2019/10/24 02:18:31 ossec-agent: INFO: Started (pid: 4144).
2019/10/24 02:18:32 wazuh-modulesd:osquery: WARNING: E1024 02:18:32.089233   984 processes.cpp:312] Failed to lookup path information for process 4
2019/10/24 02:18:32 wazuh-modulesd:osquery: WARNING: E1024 02:18:32.089233   984 processes.cpp:332] Failed to get cwd for 4 with 31
2019/10/24 02:18:32 wazuh-modulesd:osquery: WARNING: E1024 02:18:32.089233   984 processes.cpp:312] Failed to lookup path information for process 68
2019/10/24 02:18:32 wazuh-modulesd:osquery: WARNING: E1024 02:18:32.089233   984 processes.cpp:332] Failed to get cwd for 68 with 31
2019/10/24 02:18:32 wazuh-modulesd:osquery: WARNING: osqueryd has unsafe permissions.
2019/10/24 02:18:32 wazuh-modulesd:osquery: ERROR: Osquery exited with code 1. Closing module.
2019/10/24 02:18:32 wazuh-modulesd:osquery: INFO: Closing module.
```
And the events send to Analysisd are as follow:
```
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->ossec ossec: Agent started: 'WIN-6UJQ4IGFLK2->10.0.0.1'.
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->osquery E1024 02:28:30.249171  3584 processes.cpp:312] Failed to lookup path information for process 4
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->osquery E1024 02:28:30.249171  3584 processes.cpp:332] Failed to get cwd for 4 with 31
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->osquery E1024 02:28:30.249171  3584 processes.cpp:312] Failed to lookup path information for process 68
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->osquery E1024 02:28:30.249171  3584 processes.cpp:332] Failed to get cwd for 68 with 31
2019 Oct 24 11:28:30 (WIN-6UJQ4IGFLK2) 10.0.0.1->osquery E1024 02:28:30.249171  3584 watcher.cpp:567] [Ref #1382] osqueryd has unsafe permissions: C:\Program Files\osquery\osqueryd\osqueryd.exe
```

It causes five alerts reporting the errors.

The Osquery configuration is:
[osquery.conf.txt](https://github.com/wazuh/wazuh-qa/files/3766717/osquery.conf.txt)
