### ISSUE TITLE
Extend Authd existent tests with new scenarios from the force options configuration

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2051]
As part of https://github.com/wazuh/wazuh-qa/issues/2050 we need to extend the existing tests with new scenarios:
As we identified, we need to extend the test cases of:
- test_authd_local.py
- test_authd_worker.py
And add testcases for:
- Agents key hash.
  - Key_hash enabled
    - Agents with existing key
    - Agents without existing key
  - Key_hash disabled
- Verify that a worker sends a force_option block in null to delegate the configuration to the manager.
- Key requests on local_server with a specified force_option block.
- Key requests on local_server without a specified force_option block.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/2091 was merged.
