### ISSUE TITLE
Adapt the existing Authd tests configurations to deprecate the legacy force_insert and force_time

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2052]
As part of https://github.com/wazuh/wazuh-qa/issues/2050 we need to deprecate the old usage of **force_insert** and **force_time** into the Authd configuration files.
- We need to analyze the content of wazuh_authd_configuration.yaml
- Eliminate the legacy configurations if they are not required.
- Translate the legacy configurations into the new force block if required.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/2105 was merged.
