### ISSUE TITLE
Add integration test to check if ignore and restrict are working properly

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#2066]
## Description
Hello team,
we want to add some integration tests to check that the **ignore** and **restrict** options do not continue to process the directories inside a folder that is set to be ignored.

The problem is detailed in this issue:
https://github.com/wazuh/wazuh/issues/10555

A possible solution could be to monitor a /testignored directory, and inside it create some more directories. Then configure that directory to be ignored.
It is necessary to think of some way to check that inside that configured directory no other directory is still being traversed.

**Comment by damarisg** [comment]
We decided to close them.
