### ISSUE TITLE
Improve pull request template

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2083]
## Description

It is necessary to create a standard PR template to facilitate the task of QA by external reviewers.  Some of the points that this new template should incorporate are the following:

- Related wazuh-qa issue.
- Description
  - Wazuh development information
  - Wazuh branch
  - Version
  - Package link if applicable

- Testing
The author of the PR should include a full report, proving that new development works correctly. This should follow developer [guidelines standards](https://github.com/wazuh/wazuh-qa/wiki/Development-guidelines)

- Other information necessary to correctly run new developments

**Comment by damarisg** [comment]
I propose a new template after last changes in our team.

**Comment by QU3B1M** [comment]
LGTM!

**Comment by QU3B1M** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
LGTM
