### ISSUE TITLE
Integration tests: Reliable full green for 4.3.0

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2084]
## Description 
| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 2040-4.3-full-green | https://github.com/wazuh/wazuh-qa/commit/966476a0008797c4b61a14efe0f73c8ab995af7b |v4.3.0 | [c7fb1e8](https://github.com/wazuh/wazuh/commit/c7fb1e8c3f305d56ddf0a31fe28f31d2e80b7d14)|

We are going to check that the integration tests of the `4.3` branch of `wazuh-qa` work correctly using the `4.3.0` version of `wazuh`.

We will need to do research to check the status of the integration tests. If any problem is found during the research, we will need to fix it in order to achieve the reliable full green.

The tests will be performed both in the local environment and in Jenkins using `CentOS` as the manager OS. As for the agents, `Linux`, `Windows` and `macOS` will be used as required. 

It is required to have the latest `FIM `changes, so a new merge was added in this branch to continue working on that. 

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 2040-4.3-full-green | https://github.com/wazuh/wazuh-qa/commit/1104bc3bd8809c2b2acea4ed3dfab1f040cda062 |v4.3.0 | [c7fb1e8](https://github.com/wazuh/wazuh/commit/c7fb1e8c3f305d56ddf0a31fe28f31d2e80b7d14)|

## Research
-  https://github.com/wazuh/wazuh-qa/issues/2040 

## Integration tests to do fixing 

- https://github.com/wazuh/wazuh-qa/issues/2087
- https://github.com/wazuh/wazuh-qa/issues/2088
- https://github.com/wazuh/wazuh-qa/issues/2089 
- https://github.com/wazuh/wazuh-qa/issues/2090
- https://github.com/wazuh/wazuh-qa/issues/2092
- https://github.com/wazuh/wazuh-qa/issues/2093
- https://github.com/wazuh/wazuh-qa/issues/2094 
- https://github.com/wazuh/wazuh-qa/issues/2095 
- https://github.com/wazuh/wazuh-qa/issues/2096
- https://github.com/wazuh/wazuh-qa/issues/2097 
- https://github.com/wazuh/wazuh-qa/issues/2098 
- https://github.com/wazuh/wazuh-qa/issues/2099

**Comment by snaow** [comment]
If you need more info about work done, remember to pass by the PR: Integration tests: Reliable full green for 4.3.0
