### ISSUE TITLE
Fix Logtest tests in 4.3

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2088]
## Description

This issue is part of the [Integration tests: Reliable full green for 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2084) . After the research [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040), it has been detected errors in `logtest` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix logtest tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  master |  2040-4.3-full-green | v4.3.0  |  4.3.2040 | 

### Execution results

This test is only available for Linux managers.

| Test Path |  Type |  OS | Status | 
|--|--|--|--|
test_logtest| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380822/resultsLogtest.log) 
test_logtest| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380825/resultsLogtest3.log) 
test_logtest| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380824/resultsLogtest2.log) 
test_logtest| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13562/) 
test_logtest| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13564/) 
test_logtest| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13563/) 

### Development

In order to finish this issue the following tasks should be fulfilled:

- [ ] Full green in api tests for every supported OS:
  - [ ] test_logtest local.
    - [ ] test_logtest jenkins.
- [ ] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `2040-4.3-full-green`

**Comment by fedepacher** [comment]
### Execution results

This test is only has been run in a Linux managers 4.3.0.

| Test Path |  Type |  OS | Status | 
|--|--|--|--|
test_api| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7385615/PS1-2088-centos8-manager.tar.gz) 

This test has 17 failed, 33 passed and 29 skipped.
