### ISSUE TITLE
Fix Wazuh_db tests in 4.3

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2089]
## Description

This issue is part of the [Integration tests: Reliable full green for 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2084) . After the research [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040), it has been detected errors in `wazuh_db` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix wazuh_db tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  master |  2040-4.3-full-green | v4.3.0  |  4.3.2040 | 

### Execution results

This test is only available for Linux managers.

| Test Path |  Type |  OS | Status | 
|--|--|--|--|
test_wazuh_db| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380858/R1-test_WazuhDB.zip) 
test_wazuh_db| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380859/R2-test_WazuhDB.zip) 
test_wazuh_db| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7380860/R3-test_WazuhDB.zip) 
test_wazuh_db| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13659/) 
test_wazuh_db| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13660/) 
test_wazuh_db| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13661/) 

### Development

In order to finish this issue the following tasks should be fulfilled:

- [ ] Full green in api tests for every supported OS:
  - [ ] test_wazuh_db local
  - [ ] test_wazuh_db jenkins
- [ ] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `2040-4.3-full-green`

**Comment by Deblintrake09** [comment]
### test_wazuh_db

|  OS  | Local  | Date
|---   |---   |---  |
| Run1 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7452927/ResultsWazuhDB.zip) | 2021/10/29
| Run2 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7452929/ResultsWazuhDB2.zip) | 2021/10/29
| Run3 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7452930/ResultsWazuhDB3.zip) | 2021/10/29

**Comment by danisan90** [comment]
### 2021/11/1

### test_wazuh_db

Test launched from Centos clean machines

|  rounds  | Local  | Date
|---   |---   |---  |
| Run1 | [ 🔴  ](https://github.com/wazuh/wazuh-qa/files/7455011/ResultsWazuhdb.zip) | 2021/11/1
| Run2 | [ 🔴  ](https://github.com/wazuh/wazuh-qa/files/7455018/ResultsWazuhdb2.zip) | 2021/11/1
|Run3| [ 🔴  ](https://github.com/wazuh/wazuh-qa/files/7455035/R1-ResultsWazuh_db-2040.tar.gz) | 2021/11/1
|Run4| [ 🔴  ](https://github.com/wazuh/wazuh-qa/files/7455042/R2-ResultsWazuh_db-2040.tar.gz)| 2021/11/1
|Run5| [ 🔴  ](https://github.com/wazuh/wazuh-qa/files/7455049/R3-ResultsWazuh_db-2040.tar.gz )| 2021/11/1

**Comment by juliamagan** [comment]
# 02/11/2021
## Package
| Version | Revision | Link|
|---|---|---|
|4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-2089.wazuhdb.x86_64.rpm|


## Testing

### test_wazuh_db

|  OS  | Local  - Features team environment | Local - Maintenance team environment    | Notes
|---   |--   |---    |---   |
 PS1 | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461066/PS1-2089-features-environment.tar.gz)| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461095/PS1-2089-maint-environment.tar.gz) |
| PS2 | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461072/PS2-2089-features-environment.tar.gz) |[🟢 ](https://github.com/wazuh/wazuh-qa/files/7461096/PS2-2089-maint-environment.tar.gz) |  
| PS3   |[🟢 ](https://github.com/wazuh/wazuh-qa/files/7461077/PS3-2089-features-environment.tar.gz) | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461097/PS3-2089-maint-environment.tar.gz)|  |
| PS4  |[🟢 ](https://github.com/wazuh/wazuh-qa/files/7461088/PS4-2089-features-environment.tar.gz) | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461098/PS4-2089-maint-environment.tar.gz)|  |
| PS5  |[🟢 ](https://github.com/wazuh/wazuh-qa/files/7461089/PS5-2089-features-environment.tar.gz) | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7461099/PS5-2089-maint-environment.tar.gz)|  |




* * * 
- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by damarisg** [comment]
This issue will be closed because with new changes applied on the master that includes 1502 and wazuh/wazuh#9093 it works successfully.

 I attach the results.

## Package
| Version | Revision | Link|
|---|---|---|
|v4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-2089.wazuhdb.x86_64.rpm| 

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 2048|


Test Results:


| Test Path | Status | Type |  Date | By 
|--|--|--|--|--|
test_wazuh_db/ | [🟢](https://github.com/wazuh/wazuh-qa/files/7463082/PS1-manager-wazuhdb-2089-2.zip) | Local | 2021/11/02 | Seyla
test_wazuh_db/ | [🟢](https://github.com/wazuh/wazuh-qa/files/7463081/PS3-manager-wazuhdb-2089-3.zip) | Local | 2021/11/02 | Seyla
test_wazuh_db/ | [🟢](https://github.com/wazuh/wazuh-qa/files/7463080/PS1-manager-wazuhdb-2089.zip) | Local | 2021/11/02 | Seyla
