### ISSUE TITLE
Fix Logcollector tests in 4.3

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2096]
## Description

This issue is part of the [Integration tests: Reliable full green for 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2084) . After the research [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040), it has been detected errors in `logcollector` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix `logcollector` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  master |  2040-4.3-full-green | v4.3.0  |  4.3.2040 | 

### Execution results

This test is only available for Linux managers.

| Test Path |  Type |  OS | Status | 
|--|--|--|--|
test_logcollector| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13675/) 
test_logcollector| Jenkins| Agent- Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13679/) 
test_logcollector| Jenkins| Agent- Windows| [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13682/) 
test_logcollector| Jenkins| Agent- Solaris| [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13685/) 
test_logcollector| Jenkins| Agent- Macos| [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13689/) 

Note: 

- You could find more logs of execution failed on [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040)

- It is necessary to remove all warnings of logcollector.

![imagen](https://user-images.githubusercontent.com/3978434/138753901-d88b3581-1aa3-4fa8-a6ec-63872251dfce.png)

### Development

In order to finish this issue the following tasks should be fulfilled:

- [ ] Full **green** in api tests for every supported OS:
  - [ ] test_logcollector local
  - [ ] test_logcollector jenkins
- [ ] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `2040-4.3-full-green`

**Comment by juliamagan** [comment]
## 03/11/2021

I'll be working on the manager tests in branch `2096-logcollector-manager-tests`. This is the status:

### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-2096.test.logcollector.x86_64.rpm|


## Testing

### tests/integration/test_logcollector

|  OS  | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| PS1   | 🔵 |  [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14865/)  |
| PS2   | 🔵 | [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14866/)  | |
| PS3   | 🔵  |  [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14867/)  | |


* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by snaow** [comment]
After tons of work, Logcollector is now in green status, check the latest pipeline results in PR: 

- https://github.com/wazuh/wazuh-qa/pull/2185#issue-774405329

Notice the issue will continue as well in: https://github.com/wazuh/wazuh-qa/issues/2286
