### ISSUE TITLE
Fix WPK tests in 4.3

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2099]
## Description

This issue is part of the [Integration tests: Reliable full green for 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2084) . After the research [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040), it has been detected errors in `wpk` tests for Wazuh manager in Linux systems. In order to sanitize current tests is necessary to fix `wpk` tests.

### Pipeline parameters

|  Jenkins branch  | QA branch   |  Version 	|   Revision |
|- |- |- |- |
|  master |  2040-4.3-full-green | v4.3.0  |  4.3.2040 | 

### Execution results

This test is only available for Linux managers.

| Test Path |  Type |  OS | Status | 
|--|--|--|--|
test_wpk| Local | Manager - Linux | [🔴](https://github.com/wazuh/wazuh-qa/files/7383772/ResutsWpk1.log) 
test_wpk| Local | Agent- Linux | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7383774/ResutsWpk1.1.log) 
test_wpk| Local | Agent - Windows| ⚫
test_wpk| Jenkins| Manager - Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13701/) 
test_wpk| Jenkins| Agent- Linux | [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13721/) 
test_wpk| Jenkins| Agent- Windows| [🔴](https://ci.wazuh.info/view/Tests/job/Test_integration/13720) 

Note: You could find more logs of execution failed on [Research: Check the integration tests status in 4.3.0](https://github.com/wazuh/wazuh-qa/issues/2040)

### Development

In order to finish this issue the following tasks should be fulfilled:

- [x] Full green in api tests for every supported OS:
  - [x] test_wpk local
  - [x] test_wpk jenkins
- [ ] Documentation of any important change done for these tests or the used tools
- [x] Merge with `2040-4.3-full-green`

**Comment by Deblintrake09** [comment]
Date| Type| Repo | wpk param | Result | Notes
|:--:|:--:|:--:|:--:|:--:|:--:|
| 2021/11/08|  Manager | 4.2 | 4.2.4 | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15334/) | Version 4.2.4-0.10557
| 2021/11/08|  Windows Agent | 4.2 | 4.2.4 | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/15336) | Version 4.2.4-0.10557
| 2021/11/08|  Linux Agent | 4.2 | 4.2.4 | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15337) | Version 4.2.4-0.10557

**Comment by Deblintrake09** [comment]
During research it was found that the tests were not able to get the correct wpk file if revision was not passed in, but if it was passed as part of the wpk_version parameter, tests would fail when comparing versions.

Added --wpk_revision parameter and fixed `test_wpk_agent.py`

Date| Type| Repo | wpk param | Result | Version| Notes|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| 2021/11/09|  Windows Agent -  Local| 2040-4.3-fix-wpk-revision | 4.3.0 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7513209/ResultsWPK-windows.zip) | Version 4.3.0-0.fullgreen | 
| 2021/11/09|  Windows Agent -  Local| 2040-4.3-fix-wpk-revision | 4.3.0 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7513210/ResultsWPK-windows2.zip) | Version 4.3.0-0.fullgreen | 
| 2021/11/09|  Windows Agent -  Local| 2040-4.3-fix-wpk-revision | 4.3.0 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7513211/ResultsWPK-windows3.zip) | Version 4.3.0-0.fullgreen |

**Comment by damarisg** [comment]
Closed by #2204 and #2161
