### ISSUE TITLE
Improve override_authd_force_conf logic

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2153]
As part of https://github.com/wazuh/wazuh-qa/issues/2050, we created **override_authd_force_conf()** fixture in charge of changing an specific part of the configuration extracted from each one of the test cases.
This method is strictly reserved to overwrite the force_option block.
Making this fixture generic will be useful for other tests and will bring the capability to test invalid configuration content on the test too.

**Comment by DProvinciani** [comment]
Closing as invalid as it is not required for these tests.
