### ISSUE TITLE
Document all the methods and fixtures developed for force_options configuration tests

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2154]
As part of https://github.com/wazuh/wazuh-qa/issues/2050, several methods and fixtures were developed and they must be documented following the DocGenerator schema v2.0 (https://github.com/wazuh/wazuh-qa/issues/1694)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/2176 was merged.
