### ISSUE TITLE
Adapt WazuhDB tests to handle the new disconnection_time column in global DB

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2167]
As part of https://github.com/wazuh/wazuh-qa/issues/2050, we need to add disconnection_time as part of the response that WazuhDB returns.
The core development added this new column and some tests ask for the complete global DB content, which makes now these tests fail.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/2170 was merged.
