### ISSUE TITLE
Tests Vulnerability Detector - Refactor for tests skipped 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2178]
# Description

Vulnerability Detector has a lot of tests to refactor, but some take precedence because they show random failures. Additionally, each test requires maintenance and research.

This list contains all the tests that were skipped for Windows in 4.3. The priority list for refactoring are:

Test | path | Note
|-- | -- | -- |
|test_extra_tags_canonical_feed | test_feeds/canonical/test_extra_tags_canonical_feed.py | Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
|test_providers|test_providers/test_providers_os.py | | Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
|test_download_feeds|test_feeds/test_download_feeds.py |
| test_invalid_type_url_feeds | test_vulnerability_detector/test_feeds/test_invalid_type_url_feeds.py|Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
|test_enabled|test_feeds/test_invalid_type_custom_feeds.py | Connection issue - Fails erratically based on download times.
| test_extra_fields_redhat_feed | test_vulnerability_detector/test_feeds/redhat/test_extra_fields_redhat_feed.py| 
|test_providers_no_os|test_providers/test_providers_no_os.py|
|test_update_from_year|test_providers/test_providers_update_from_year.py
|test_debian_vulnerabilities_report|test_scan_results/test_debian_inventory_debian_feed.py | Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
|test_macos_vulnerabilities_report|test_scan_results/test_macos_inventory.py |
|test_vulnerabilities_report|test_scan_results/test_msu_inventory_msu_feed.py |
| test_redhat_duplicate_vulns| test_scan_results/test_redhat_duplicate_vulns.py |
|test_redhat_vulnerabilities_report| test_scan_results/test_redhat_inventory_redhat_feed.py | | Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
| test_vulnerabilities_report | test_scan_results/test_scan_different_cves.py| 
| test_vulnerabilities_report | test_scan_results/test_scan_nvd_feed.py |
| test_vulnerabilities_report | test_scan_results/test_scan_providers_and_nvd_feed.py |
| test_ubuntu_vulnerabilities_report | test_scan_results/test_ubuntu_inventory_canonical_feed.py |  Database gets locked - Need to improve database management - Previously issue # 9309 was generated |
| test_window_version_indexing | test_windows/test_cpe_indexing.py| | Database gets locked - Need to improve database management - Previously issue # 9309 was generated |

Also,  a priority for VD is to achieve a full green locally because it has only been achieved in Jenkins.

# Task to do

- Refactor cases related to how use DB.
- Research and Refactor the other cases in the list.
- Achieve a reliable local green

**Comment by jmv74211** [comment]
This issue will be studied and further developed here https://github.com/wazuh/wazuh-qa/issues/2453
