### ISSUE TITLE
Adapt the metrics scripts to the new Cluster/API processes

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#2197]
Due to the changes that we are going to introduce in the cluster and the API, it is necessary that we carefully review and update if necessary the script in charge of collecting the information about the processes (https://github.com/wazuh/wazuh-qa/tree/master/deps/wazuh_testing/wazuh_testing/scripts).

In case the update is necessary, we will have to evaluate how we will calculate the use of resources. Since now we will have several child processes of the main process of the cluster and the API, we will have to decide whether to measure them separately or to sum up the resource usage of all the child processes plus the parent.

More information about these changes here: https://github.com/wazuh/wazuh/issues/10765, https://github.com/wazuh/wazuh/issues/10770, and https://github.com/wazuh/wazuh/issues/10780

**Comment by davidjiglesias** [comment]
Already done in https://github.com/wazuh/wazuh-qa/pull/2278
