### ISSUE TITLE
Tests Logcollector - Refactor for tests skipped 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2209]
| Related to |
|--|
| #2096 |

# Description

Logcollector has some tests to review with some failures. Additionally, each test requires research.

This list contains all the tests that were skipped in 4.3. The priority list to fix  are:

Test | Path | Note
|-- | -- | -- |
| test_age | test_logcollector/test_age/test_age_datetime_changed.py | - |
| test_configuration | test_logcollector/test_configuration/test_basic_configuration_age.py | - |
| test_configuration | test_logcollector/test_configuration/test_basic_configuration_alias.py | - |
| test_configuration | test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py | - |
| test_log_format | test_logcollector/test_log_format/test_log_format_values.py | - |
| test_options | test_logcollector/test_options/test_options_state_interval.py | - |
| test_configuration | test_logcollector/test_configuration/test_basic_configuration_log_format.py | - |
| test_command_monitoring | test_logcollector/test_command_monitoring/test_command_execution.py::test_command_execution_dbg | - |
| test_configuration | test_logcollector/test_configuration/test_basic_configuration_only_future_events.py | - |

# Task to do
- Research and Refactor the other cases in the list.
- Achieve a reliable local green

**Comment by juliamagan** [comment]
We are closing this issue since we are fixing these tests in #2096.
