### ISSUE TITLE
Wazuh DB chunks test is failing due to socket size

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2217]
## Description

While testing Wazuh DB module in #1243, we could see that `test_wazuh_db_chunks.py` is failing depending on the OS. It seems that when the test checks the second message, it is receiving the last part of the first one. I'll attach executions from different boxes, `centos/8` and `generic/centos8`. Also, when this test fails, `test_wazuh_db_timeout.py` is affected.

### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.0-0.commit3799ec1.x86_64.rpm|

### centos/8 - test_wazuh_db.py

|  OS    | Local     | Notes
|---      |---    |---    |
| PS1   | [🟢 ](https://github.com/wazuh/wazuh-qa/files/7540840/PS1-2217-centos-manager-not-updated.tar.gz)   | Before `yum update -y`
| PS2 | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7540827/PS1-2217-centos-manager-updated.tar.gz) | After `yum update -y`

### generic/centos8 - test_wazuh_db.py

|  OS    | Local     | Notes
|---      |---    |---    |
| PS1   |  [🟢 ](https://github.com/wazuh/wazuh-qa/files/7540550/PS1-2217-centos-manager.tar.gz)  |

**Comment by damarisg** [comment]
We decided to close them.
