### ISSUE TITLE
Support IPv6 for agents

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2224]
## Description

This issue is associated with https://github.com/wazuh/wazuh/issues/4243. The goal of this set of issues is to investigate, design, and create automatic tests for the IPv6 support.

## Tasks

- #2225
- Development I: Adapt existing tests:
  - #2252
  - #2253 
  - #2257 
- Development II: Design and create new tests:
  - #2254 
  - #2284 
  - #2266

**Comment by Rebits** [comment]
### 24/11/21

After talking with @cborla and @TomasTurina we have agreed on the following tier classification. We should ensure that the tier 0 tests are completed at the end of the `Sprint: Nov 29 - Dec 13`.

### Tier 0

#### Integration

- authd: https://github.com/wazuh/wazuh-qa/issues/2252
    - Key request (write message in socket) by IPv6 address connection is accepted; Manager; Linux; Use log, client keys or request result to validate it.
    - Key request (write message in socket) by compressed IPv6 address connection is accepted; Manager; Linux; Use log, client keys or request result to validate it.
    - Key request (write message in socket) by not valid IPv6 address connection is refused; Manager; Linux; Use log, client keys or request result to validate it.

- enrollment: https://github.com/wazuh/wazuh-qa/issues/2253 
    - Configuration with IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration with compressed IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration with not valid IPv6 address is refused; Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration specifying local IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.
     - Configuration with IPv6 address is accepted (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration with compressed IPv6 address is accepted (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration with not valid IPv6 address is refused (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration specifying local IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.
    - Configuration specifying an update time interval for the IP address works as expected; Agent; Linux/Windows/Others; Use log to validate it.
- remoted: https://github.com/wazuh/wazuh-qa/issues/2257 
   -  Validate keepalive message (write message in socket) with IPv6 address; Manager; Linux; Use log and check that the IPv6 is stored in the agent's DB to validate it.


#### System
System tests only will be implemented for Linux in a local environment based on docker in this sprint, future estimation should be necessary to migrate these new tests using QACTL/Jenkins tools and give them support for other OS

-   Use agent-auth to register an agent and establish a connection with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.
    - Use an IPv4 manager to register an IPv6 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.
    - Use an IPv6 manager to register an IPv4 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.
    - Use an IPv6 manager to register an IPv6 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.
- Use autoenrollment to connect an agent with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.


### Tier 1
- remoted https://github.com/wazuh/wazuh-qa/issues/2257
   - test_basic_configuration_ipv6.py
   - test_basic_configuration_local_ip_invalid.py
   - test_basic_configuration_local_ip_valid.py
   - test_basic_configuration_syslog_allowed_denied_ips_valid.py
   - test_basic_configuration_syslog_allowed_ips_invalid.py
   - test_basic_configuration_syslog_denied_ips_invalid.py
   - test_basic_configuration_syslog_denied_ips.py
   - test_basic_configuration_syslog_no_allowed_ips.py

- analysisd
    - Configuration with an IPv6 address listed in the Active Response whitelist; Manager; Linux; Execute and AR with that IPv6, action must not be triggered.
    - Configuration with an IPv6 address not listed in the Active Response whitelist; Manager; Linux; - - Execute and AR with that IPv6, action must be triggered.
    - Configure a rule that use source IP field configured as IPv6 address; Manager; Linux; Validate that an IPv6 alert is triggered.
    - Configure a rule that use destination IP field configured as IPv6 address; Manager; Linux; Validate that an IPv6 alert is triggered.

- csyslogd: 2 días
    Configuration for server must support IPv6 address format; Manager; Linux; Use log to validate it.

### Tier 2
- manage_agents (tool): 
     - Add an IPv6 address agent, use -a option; Manager; Linux; Validate agent added.
     - Add a compressed IPv6 address agent, use -a option; Manager; Linux; Validate agent added.
     - Add a group of agents from a file, use -f <file_name>, the file must contain a mix of IPv6 and IPv4 addresses; Manager; Linux; Validate agents added.
