### ISSUE TITLE
Research: Check the integration tests affected by the implementation of IPv6 support

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2225]
## Description

| Wazuh QA: Branch | Wazuh QA: Commit | 
|:--:|:--:|
| master | cc712b04e766969eacd421b0ba044752fefcbc13  |

We are going to check the modules and integration tests that could be affected by the implementation of IPv6 support.

### Add test cases

In this section, we can find existing tests that need to implement valid, compressed, and invalid IPv6 cases.

**Authd**

- `test_authd_valid_name_ip.py`
- `test_authd_use_source_ip.py`

**Enrollment**

- `test_agent_auth_enrollment.py`
- `test_agentd_enrollment.py`

**Remoted**

- `test_basic_configuration_ipv6.py`
- `test_basic_configuration_local_ip_invalid.py`
- `test_basic_configuration_local_ip_valid.py`
- `test_basic_configuration_syslog_allowed_denied_ips_valid.py`
- `test_basic_configuration_syslog_allowed_ips_invalid.py`
- `test_basic_configuration_syslog_denied_ips_invalid.py`
- `test_basic_configuration_syslog_denied_ips.py`
- `test_basic_configuration_syslog_no_allowed_ips.py`

### New tests to implement

**Agentd**

We need to implement new tests for the following configuration: 

- Test that we can add IPv4 or IPv6 [server address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#server)
- Test that IP stills correct after [updates](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#ip-update-interval)
- Test we can specify IPv4 or IPv6 [agent address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#local-ip)

## System tests 
These tests will be implemented in https://github.com/wazuh/wazuh-qa/issues/2266.

 - Use agent-auth to register an agent and establish a connection with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.
 - Use autoenrollment to connect an agent with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.

**Comment by TomasTurina** [comment]
## Integration tests proposal

The following list is sorted by component, where each component contains a set of tests following a prioritized order.

Test format: Description; Device; Platform/OS; Validation

### Integration tests

#### authd

1. Key request (write message in socket) by IPv6 address connection is accepted; Manager; Linux; Use log, client keys or request result to validate it.
2. Key request (write message in socket) by compressed IPv6 address connection is accepted; Manager; Linux; Use log, client keys or request result to validate it.
3. Key request (write message in socket) by not valid IPv6 address connection is refused; Manager; Linux; Use log, client keys or request result to validate it.

#### agentd

- _[Enrollment](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment)_

1. Configuration with IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#manager-address) is accepted; Agent; Linux/Windows/Others; Use log to validate it.
2. Configuration with compressed IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#manager-address) is accepted; Agent; Linux/Windows/Others; Use log to validate it.
3. Configuration with not valid IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#manager-address) is refused; Agent; Linux/Windows/Others; Use log to validate it.
4. Configuration specifying [local](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#agent-address) IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.

- _[Server](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#server)_

1. Configuration with IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#address) is accepted (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
2. Configuration with compressed IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#address) is accepted (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
3. Configuration with not valid IPv6 [address](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#address) is refused (TCP and UDP); Agent; Linux/Windows/Others; Use log to validate it.
4. Configuration specifying [local](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#local-ip) IPv6 address is accepted; Agent; Linux/Windows/Others; Use log to validate it.
5. Configuration specifying an [update time interval](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#ip-update-interval) for the IP address works as expected; Agent; Linux/Windows/Others; Use log to validate it.

#### remoted

1. Validate keepalive message (write message in socket) with IPv6 address; Manager; Linux; Use log and check that the IPv6 is stored in the agent's DB to validate it.
2. Configuration with [allowed](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#allowed-ips) IPs list including IPv6 addresses; Manager; Linux; Use log to validate it.
3. Configuration with [denied](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#denied-ips) IPs list including IPv6 addresses; Manager; Linux; Use log to validate it.
4. Configuration specifying [local](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#local-ip) IPv6 address to listen to connections; Manager; Linux; Use log to validate it.

#### analysisd

1. Configuration with an IPv6 address listed in the Active Response [whitelist](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#white-list); Manager; Linux; Execute and AR with that IPv6, action must not be triggered.
2. Configuration with an IPv6 address not listed in the Active Response [whitelist](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#white-list); Manager; Linux; Execute and AR with that IPv6, action must be triggered.
3. Configure a rule that use [source](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#srcip) IP field configured as IPv6 address; Manager; Linux; Validate that an IPv6 alert is triggered. 
4. Configure a rule that use [destination](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#dstip) IP field configured as IPv6 address; Manager; Linux; Validate that an IPv6 alert is triggered. 

#### csyslogd

1. Configuration for [server](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syslog-output.html#server) must support IPv6 address format; Manager; Linux; Use log to validate it.

#### manage_agents (tool)

1. Add an IPv6 address agent, use -a option; Manager; Linux; Validate agent added.
2. Add a compressed IPv6 address agent, use -a option; Manager; Linux; Validate agent added.
4. Add a group of agents from a file, use -f <file_name>, the file must contain a mix of IPv6 and IPv4 addresses; Manager; Linux; Validate agents added.
	
#### API Registration

1. Add an IPv6 address agent; Manager; Linux; Validate agent added.
2. Add a compressed IPv6 address agent; Manager; Linux; Validate agent added.

### System tests
	
#### authd, remoted, agentd

1. Use agent-auth to register an agent and establish a connection with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.
2. Use autoenrollment to connect an agent with a manager; Agent/Manager; Linux/Windows/Others; Validate the connection.

#### agent-auth (tool)

1. Use an IPv4 manager to register an IPv6 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.
2. Use an IPv6 manager to register an IPv4 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.
3. Use an IPv6 manager to register an IPv6 Agent; Agent/Manager; Linux/Windows/Others; Validate agent added and connected.

**Comment by Rebits** [comment]
After talking with @vicferpoy  we have decided that we should develop more registration API tests:

- _Wazuh API IT_
    - Add an IPv6 address agent; Manager; Linux; Validate agent added.
    - Add a compressed IPv6 address agent; Manager; Linux; Validate agent added.
    - Add an invalid IPV6 address agent.
- _Wazuh QA API tests_
    - API registration System/Integration test
