### ISSUE TITLE
Design and implement API integration tests for multiprocessing

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-qa#2227]
This issue is part of the epic https://github.com/wazuh/wazuh/issues/10780.

The epic issue mentioned aims to make the Wazuh API capable of running both local and distributed API requests in parallel.

For this development, we will need to design and implement new QA integration tests to check that the multiprocessing will be performed correctly in the DAPI module. 

We should test that child processes are being created when it is needed, API requests are not waiting for others to finish, etc.

We will also need to take into account that some endpoints will have critical sections that cannot be run in parallel. This is going to be reviewed in the issue https://github.com/wazuh/wazuh/issues/10792. We should consider testing these sections.

**Comment by damarisg** [comment]
We decided to close them.
