### ISSUE TITLE
Research on modules and wazuh-daemons tested by QA

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2230]
In order to test more effectively, it is necessary for QA developers to have a good understanding of the modules they are testing. The objective of this issue is to research into and learn the main fundamentals of the modules or wazuh-daemons mentioned below:

- [x] Vulnerability detector
- [x] Wazuh DB
- [x] Integrator
- [x] Log rotation
- [x] Labels
- [ ] Office 365
- [x] RIDS

It is requested that for each module an investigation be carried out, basic configurations are tested and that documentation of said investigation be provided that may be useful for the rest of the members.

**Comment by fedepacher** [comment]
### Update

- Collected vulnerability detector information 
- Collecting Integrator information
