### ISSUE TITLE
System check-files test: Design the data structure that will store the information of the system check-files.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2232]
The objective of this issue is to propose an efficient design that allows us to store the information obtained by the check-files of the system, to be later processed and compared.

Initially, I propose something like the following:

```
[
    {
        "id": 0,
        "name": "<file_path>",
        "description": {
            "class": "static",
            "user": "root"
            "group": "ossec",
            "mode": "0750",
            "prot": "drwxr-x---",
            "type": "directory",
        }
    },
    ...
]
```

**Comment by fedepacher** [comment]
My proposal to store information obtained by the check-files of the system is the following:

[
    {
        "id": 0,
        "name": "<file_path>",
        "description": {
            "user": "root"
            "group": "ossec",
            "mode": "0750",
            "prot": "drwxr-x---",
            "type": "directory",
        }
    },
    ...
]

Removed the "class" field because it has no relevance for this process

**Comment by jmv74211** [comment]
Okay, for now we make use of that design. If any modification is needed, it will be discussed later.

**Comment by jmv74211** [comment]
Finally, the data structure has been optimized and is as follows:

```json
{
    "file_path": {
        "type": "directory",
        "user": "root"
        "group": "ossec",
        "mode": "0750",
        "prot": "drwxr-x---"
    },
    ...
}
```
