### ISSUE TITLE
Centralized configuration IT: Force reconnect interval

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2238]
## Description

|Wazuh version| Wazuh QA version|
|:--:|:--:|
|v4.4.0||

After the development done in https://github.com/wazuh/wazuh/issues/10848, we need to implement a test that checks if `force_reconnect_interval` is configurable thru centralized configuration and it works correctly.

For this development, we are going the create a new test module so we can create more tests for centralized configuration in the future.

**Comment by damarisg** [comment]
We decided to close them.
