### ISSUE TITLE
Add test cases for IPv6 to Authd tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2252]
|QA Branch|Component|
|:--:|:--:|
|[2252-ipv6-authd-tests](https://github.com/wazuh/wazuh-qa/tree/2252-ipv6-authd-tests)|Manager|

## Description

After the research done in #2225, we are going to implement new test cases for the following tests:
- `test_authd_valid_name.py`
- `test_authd_use_source_ip.py`

These tests will add support for the https://github.com/wazuh/wazuh/issues/4243 development.

**Comment by Rebits** [comment]
Merged https://github.com/wazuh/wazuh-qa/pull/2435
