### ISSUE TITLE
Add test cases for IPv6 to Enrollment tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2253]
|QA Branch|Component|
|:--:|:--:|
|[2253-ipv6-enrollment-tests](https://github.com/wazuh/wazuh-qa/tree/2253-ipv6-enrollment-tests) |Agent|

## Description

After the research done in #2225, we are going to implement new test cases for the following tests:
- `test_agent_auth_enrollment.py`
- `test_agentd_enrollment.py`

These tests will add support for the https://github.com/wazuh/wazuh/issues/4243 development.

**Comment by Rebits** [comment]
Merged https://github.com/wazuh/wazuh-qa/pull/2435
