### ISSUE TITLE
Create test for `ip_update_interval` configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2255]
|QA Branch|Component|
|:--:|:--:|
||Agent|

## Description

After the research done in #2225, we need to create a test for the [`ip_update_interval` configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#ip-update-interval) in the agent. We need to check that interval between the updates matches with the expected one, and the IP is correct.

These tests will add support for the https://github.com/wazuh/wazuh/issues/4243 development.

**Comment by damarisg** [comment]
We decided to close them.
