### ISSUE TITLE
Create test for `local_ip` configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2256]
|QA Branch|Component|
|:--:|:--:|
||Agent|

## Description

After the research done in #2225, we need to create a test for the [`local_ip` configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#local-ip) in the agent. We need to verify we can use IPv4 and IPv6 addresses.

These tests will add support for the https://github.com/wazuh/wazuh/issues/4243 development.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
