### ISSUE TITLE
Create test for `logging` configuration

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2260]
|QA Branch|
|:--:|
||

## Description

We need to support and verify that the `logging` functionalities work correctly.

To do this, we must check some variables such as `enabled` or `format`.

### Tasks to check
- [ ] Functionality when `enabled` and “disabled”.
- [ ] File `format`.
- [ ] Invalid configuration.
- [ ] Default values.

**Comment by damarisg** [comment]
We decided to close them.
