### ISSUE TITLE
Create test for `log rotation` compression

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2262]
|QA Branch|
|:--:|
||

## Description

We need to support and verify that the file compression functionalities of the `log rotation` work correctly.

To do this, we must check some variables inside the `<rotation>` configuration block, like `enabled` or `format`.

### Tasks to check
- [ ] Compress successfully.
- [ ] Rotation not `enabled` but keeps log files.
- [ ] Rotate without compression.
- [ ] Invalid configuration.

**Comment by damarisg** [comment]
We decided to close them.
