### ISSUE TITLE
Create test for removing `log rotation` files

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2263]
|QA Branch|
|:--:|
||

## Description

We need to support and verify that the file deletion functionalities of the `log rotation` work correctly.

To do this, we must check some variables inside the `<rotation>` configuration block like `rotate` or `maxage`.

### Tasks to check
- [ ] Force `rotate` and `maxage` to delete files.
- [ ] `rotate` simulating several months and years.
- [ ] Invalid configuration.
- [ ] Nonexistent configuration.

**Comment by damarisg** [comment]
We decided to close them.
