### ISSUE TITLE
API IPV6 agent registration test

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2284]
### Description

After the research about required IPV6 tests https://github.com/wazuh/wazuh-qa/issues/2225#issuecomment-976378329, we agree that should be necessary to implement an integration test to ensure an IPV6 agent is registered correctly using the API.

### Test requirements

- Ensure API validate correctly IPV6 IPs:
    - Add an IPv6 address agent; Manager; Linux; Validate agent added.
    - Add a compressed IPv6 address agent; Manager; Linux; Validate agent added.
    - Add an invalid IPV6 address agent.
- `client.keys` is updated correctly

There are no API tests that check these processes so it should be necessary to add a basic test case for IPV4 format also.

**Comment by juliamagan** [comment]
Merged into #2435

**Comment by juliamagan** [comment]
Merged into #2435
