### ISSUE TITLE
Syscheck automated tests: 'frequency' option

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#229]
## Description

This issue is part of the roadmap in #7.

When restarting `wazuh-manager`  with a `real-time` monitored directory that does not exists and creating it later no alerts will be raised until the time specified on the `<frequency>` option has passed.

A test to check that the newly created directory will be monitored once `frequency` time has passed is needed. The test will consist on restarting the service without the directory, create it later and advance the clock with the TimeTravel utility to see if alerts are being raised now.

## Subtasks
- Realtime
  - [x] Check if events are raised after the time specified on frequency' has passed.

- Whodata
  - [x] Check if events are raised after the time specified on frequency' has passed.

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished. All tests fail because this does not work yet. It was reported to core-team.

## Tests performed
### Linux
```
========================================== test session starts ==========================================
platform linux -- Python 3.6.8, pytest-5.2.3, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 8 items                                                                                       

test_frequency.py FFFFFFFF                                                                        [100%]

=============================================== FAILURES ================================================
```

### Windows
```
================================================================= test session starts ================================================================== 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 8 items

test_frequency\test_frequency.py FFFFFFFF                                                                                                         [100%]

======================================================================= FAILURES =======================================================================
```
