### ISSUE TITLE
Release 4.3.0 - Release candidate 1 - Analysis: Integration tests

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2290]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| master | https://github.com/wazuh/wazuh-qa/commit/45e74cbe3ef8e414dbcb29e7ffd6e91c568a1a98  |v4.3.0-rc1 |https://github.com/wazuh/wazuh/commit/d436859822246afdf1a542e333905be4c39f25ff |

We are going to check that the integration tests of the `master` branch of `wazuh-qa` work correctly using the `4.3.0-rc1` version of `wazuh`.

The tests will be performed both in the local environment and in Jenkins using `CentOS` as the manager OS. As for the agents, `Linux`, `Windows` and `macOS` will be used as required. 

## Package info 

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 |v4.3.0 |40302|  v4.3.0-rc1 | wazuh-manager-4.3.0-1.x86_64.rpm |
| Agent | rpm | x86_64 | v4.3.0 | 40302| v4.3.0-rc1 | wazuh-agent-4.3.0-1.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.3.0 |40302| v4.3.0-rc1 | wazuh-agent-4.3.0-1.msi|
| Agent | wpk Windows | x86_64 |v4.3.0 |40302| v4.3.0-rc1 |  wazuh_agent_v4.3.0_windows.wpk |
| Agent | wpk Linux | x86_64 | v4.3.0|40302|  v4.3.0-rc1 | wazuh_agent_v4.3.0_linux_x86_64.wpk  |
| Agent | wpk MacOS| x86_64 | v4.3.0|40302|  v4.3.0-rc1 | wazuh_agent_v4.3.0_macos_x86_64.wpk  |
| Agent | pkg (macOS) | x86_64 | v4.3.0 |40302| v4.3.0-rc1 | wazuh-agent-4.3.0-1.pkg |
|Agent | p5p (Solaris 11) | x86_64 |v4.3.0 | 40302| v4.3.0-rc1 | wazuh-agent_v4.3.0-sol11-i386.p5p |

#### References

| Color | Status |
|:--:|:--:|
| 🟢  | All tests passed successfully |
| 🟡  | All tests passed but there are some warnings |
| 🔴 | Some tests have failures or errors |
| 🔵 | Test execution in progress |
| ⚫ | To Do

## Test Integration - Results 

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16769/">🟢</a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16774/">🟢</a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16775/">🟢</a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr> 
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16770/">🟢</a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16782/">🟢</a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16771/">🟢</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16772/"> 🔴 </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16773/">🟢</a></td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>FIM </strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16776/">🟢</a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16777//">🟢</a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16778/">🟢</a></td>
<td style="width: 97px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16816/">🟢</a></td>
<td style="width: 97px;" colspan="2"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16817/">🟢</a></td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud <br /></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16783/">🔴</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github <br /></strong></td>
<td style="width: 103px;"> <a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16784/">🟢</a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16785/">🟢</a></td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>Logcollector</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/16788/">🟢</td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/16789/">🟢</td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/16790/">🟢</td>
<td style="width: 97px;"><a href="https://ci.wazuh.info/job/Test_integration/16790/">🟢</td>
<td style="width: 97px;" colspan="2"><a href="https://ci.wazuh.info/job/Test_integration/16790/">🟢</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest <br /></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16870/">🟢</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16796/">🟢</a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16798/">🟢</a></td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16800/">🟢</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16801/">🟢</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16802/">🟢</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16803/">🔴</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/view/Tests/job/Test_integration/16804/">🔴</a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wpk</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/16808/"> 🟢 </td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/16811/"> 🟢 </td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/16812/"> 🟢 </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
</tr>
</tbody>
</table>

--------------------------------------------------------------------------------------------------------------------------------

### Versions Status

| Capabilities | Type | 4.2.2-rc1  |4.2.4-rc1 |4.3.0-rc1| 
|--|--|--|--|--|
| Api | Manager - Linux |  [🟢](https://github.com/wazuh/wazuh-qa/issues/1880) | [🟢](https://github.com/wazuh/wazuh-qa/issues/2060)|  🔴 
| GCloud | Manager - Linux |  [🔴](https://github.com/wazuh/wazuh-qa/issues/1880) | [⚫](https://github.com/wazuh/wazuh-qa/issues/2060) | 🔴 
| Vulnerability_detector | Manager - Linux |  [🟢](https://github.com/wazuh/wazuh-qa/issues/1880) |  [🟢](https://github.com/wazuh/wazuh-qa/issues/2060)| 🔴 
| wazuh_db | Manager - Linux |  [🟢](https://github.com/wazuh/wazuh-qa/issues/1880) |  [🟢](https://github.com/wazuh/wazuh-qa/issues/2060)| 🔴 

--------------------------------------------------------------------------------------------------------------------------------

### Failures Description 

| Capabilities |Notes
|--|--|
| Api | Failed by #233, It will be fix on [Remove deprecated test_use_only_authd API tests](https://github.com/wazuh/wazuh-qa/issues/2293) by `qa-team`.
| GCloud | The failure is not by the module, It's a machine performance problem. The test requires a refactor.
|Vulnerability_detector| The failure is not due to the module. It is a problem that some PRs are missing to merge and refactor these tests.
| wazuh_db | There is a failed test in module test_wazuh_db/ because #1242 hasn't been merged yet in master.

**Comment by snaow** [comment]
API integration tests working locally, the problem resides on Jenkins side, even after merging https://github.com/wazuh/wazuh-qa/issues/2293

Execution reports:

- [4.2.5 success](https://github.com/wazuh/wazuh-qa/files/7733794/test_add_old_resource_4.2.5_ok.txt)
- [4.3.0-RC1 success](https://github.com/wazuh/wazuh-qa/files/7733793/test_add_old_resource_4.3.0_ok.txt)
