### ISSUE TITLE
Research and Fix failures of Windows FIM  tests with  "scheduled" mode on Jenkins.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2305]
## Description

It consists of investigating and resolving issues when the scheduled mode is enabled for Windows executions in FIM integration tests.
We must ensure that it not only works locally but also in Jenkins.

This problem was found in 4.2 and continues in future releases.

**Comment by Deblintrake09** [comment]
| Version | Type | Modes | Results | Date | By | Notes |
|--|--|--|--|--|--|--|
| 4.2.2 | Jenkins | Scheduled | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/17500)  | 2021/12/15 | @Deblintrake09 
| 4.2.5 | Jenkins | Scheduled | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/17499)  | 2021/12/15 | @Deblintrake09 
| 4.3.0 | Jenkins | Scheduled | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/17498) | 2021/12/15 | @Deblintrake09

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
