### ISSUE TITLE
Add a Warning list to the system `check-files` test

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2312]
We want to add a list of "warnings" for the system check-files test, where all files and directories that can change some of their attributes of the check-files without causing the test to fail are added.

In short, this list will contain all possible files and directories that can cause false positives from the test, since their check-files can be altered over time without Wazuh having anything to do with it (for example, a system log).

If a check-file of a file or directory included in this list has changed, then an output with the changes will be generated. In the end, we will have to manually review these changes, and decide whether to accept the test or not.

In this issue we propose to do the following:

- Make the design of such a list
  - Where will it be stored? 
  - Will it be included in the test_launcher process or in pytest itself? 
  - How will the output resulting from the files included in the warnings list be generated?

- Agree on each of the files and directories that have changed over time due to Wazuh's action or not to add them to the list.

As a result, we will have a clean execution of the check-files test with the following states:

- 🟢 : No check-file has changed (unlikely, since there are check-files that change over time).
- 🟡 : The test has not failed, but you have to manually check the changes in the check-files to evaluate them and decide whether the test is OK or not.
-  🔴 : Some check-files of files or directories not included in the warnings list have changed.

**Comment by roronoasins** [comment]
The actual warning list obtained due to this research https://github.com/wazuh/wazuh-qa/issues/2291 has been stored in the repo in `tests/check_file_system_integrity/data`.

This list will be updated after the testing phase.

**Comment by roronoasins** [comment]
# Test execution state

| OS                 | INSTALL MANAGER | UNINSTALL MANAGER | UPGRADE MANAGER |
|--------------------|----------------|----------------|----------------|
| CentOS 8 | :green_circle: | :green_circle: | :green_circle: |
| CentOS 7 |          :red_circle:       |          :red_circle:      |         :red_circle:        |
| Ubuntu Focal | :red_circle:   | :red_circle:  | :red_circle:   |

- When uninstalling in `CentOS7` and `Ubuntu Focal`:
An error is given when `gid` doesn't map to an entry in `/etc/group`, and a `KeyError` is raised.
- When upgrading in `CentOS7` and `Ubuntu Focal`:
There is a `/tmp` entry in the `dictionary_item_removed`
