### ISSUE TITLE
Integration tests:  Rework of synchronization tests on Windows to the new synchronization mechanism (1/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2315]
Due to the implementation of rsync as the new engine for FIM db synchronization the following tests need to be reworked to adapt to the new sync messages coming from rsync.

## Test synchronization

- test_synchronization/test_registry_responses_win32.py
- test_synchronization/test_sync_disabled_win32.py
- test_synchronization/test_sync_enabled_win32.py
- test_synchronization/test_sync_registry_disabled_win32.py
- test_synchronization/test_sync_registry_enabled_win32.py

All the above tests look for synchronization events messages that now will be deleted.

## Development stage

- [x] In research
- [x] Planning and estimating
- [x] In development
- [x] In testing phase

**Comment by CamiRomero** [comment]
This Issue will be blocked until there is a working build with the final messages.

**Comment by damarisg** [comment]
> 2022/03/22

- **Branch**: 2315-fim-sync-on-win-registry
- **Failed**: 
   - `test_synchronization\test_registry_responses_win32.py `
           **Status**:  Errors with value_name > Core team researching.
   - ` test_synchronization\test_sync_enabled_win32.py  `
           **Status**:  Errors when we wait for the events, it didn't appear events fim_files > Core team researching.
   - `test_synchronization\test_sync_registry_disabled_win32.py`          
           **Status**:  Removed skips and Errors when we wait for the events, it didn't appear events fim_files > Core team researching.
- **Fixed**:    
   - `test_synchronization\test_sync_interval_win32.py` 
         **Status**: Modified message and removed XFails.
   - `test_synchronization\test_synchronize_integrity_32.py`  
          **Status**: Modified message

**Comment by Deblintrake09** [comment]
### Update 2022/04/18
- Fixed test test_registry_responses_win32.py, but got different response on local than on jenkins, with same package.
- Asked core about fails
- Messages will be affected by issue [#2773 ](https://github.com/wazuh/wazuh-qa/issues/2773), put issue on Blocked until that issue is Closed

**Comment by Deblintrake09** [comment]
## Update 2022/04/19
- More debugging
- The keys are being deleted and the message is sent by the agent, but the WazuhDB is not updated.
- Opened Wazuh Issue [#13118](https://github.com/wazuh/wazuh/issues/13188)
- Blocked **test_registry_responses_win32.py** by Issue #13118

**Comment by Deblintrake09** [comment]
- After the latest changes applied, only test that still fails is **test_registry_responses_win32.py**. It was found during debugging, that when it fails the expected **`fim_registry_value`** log  log appears before the registry_key logs, and when it passes it appears under them.
- Even though the appears, the test fails.
- Asked Core team to research the behaviour.

**Comment by damarisg** [comment]
It continue on https://github.com/wazuh/wazuh-qa/issues/2988
