### ISSUE TITLE
Refactor Tests Files to new synchronization mechanism

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2316]
Due to the implementation of rsync as the new engine for FIM db synchronization the following tests need to be reworked to adapt to the new sync messages coming from rsync.

## Test files

* test_max_eps_synchronization.py
 
The above test assesses the max sync events per second defined in syscheck configuration for the synchronization process.

**Comment by damarisg** [comment]
Note: Changes of each test refactored applied on `new-synchronization-mechanism` temp branch.

**Comment by Deblintrake09** [comment]
### Update 2022/04/08

- Run tests on manager, Linux and Windows
- Fails on Windows and Linux
- Do manual testing
Ask Core team for information https://wazuh-team.slack.com/archives/C019A838R6Y/p1649447731151189

**Comment by Deblintrake09** [comment]
### Update 2022/04/18 - 2022/04/20
- Debugged and fixed test
- Test fails on new package
- Core Team opened new Issue based on research done
- Move to blocked

**Comment by CamiRomero** [comment]
I am going to start working today on this Issue since they have been closed [12456](https://github.com/wazuh/wazuh/issues/12456) and [13189](https://github.com/wazuh/wazuh/issues/13189)

**Comment by damarisg** [comment]
It was merged to `1915-fim-rsync-new-synchronization-mechanism` branch.
