### ISSUE TITLE
Refactoring tests related to limits caused by the new synchronization mechanism

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2317]
Due to the implementation of **rsync** as the new engine for FIM db synchronization the following tests need to be reworked to adapt to the new sync messages coming from rsync.

## Test limits

The new design implies that the DB limits are now separated in:

- Limit for the number of entries in the files table
- Limit for the number of entries in the registry table

The following tests would be affected by the changes introduced at https://github.com/wazuh/wazuh/issues/10224:

```
             FILES

- test_files/test_report_changes/test_diff_size_limit_configured.py    ok
- test_files/test_report_changes/test_diff_size_limit_default.py    ok
- test_files/test_file_limit/test_file_limit_capacity_alerts.py   ok
- test_files/test_file_limit/test_file_limit_default.py  ok
- test_files/test_file_limit/test_file_limit_delete_full.py  ok
- test_files/test_file_limit/test_file_limit_full.py  ok
- test_file_limit/test_file_limit_no_limit.py  ok
- test_files/test_file_limit/test_file_limit_values.py  ok

             REGISTRY

- test_registry/test_registry_limit/test_registry_limit_values.py  ok 
- test_registry/test_registry_limit/test_registry_limit_capacity_alerts.py    ok 
- test_registry/test_registry_limit/test_registry_value_limit_full.py      ok
- test_registry/test_registry_limit/test_registry_key_limit_full.py      ok
- test_registry/test_registry_report_changes/test_registry_diff_size_limit_values.py
- test_registry/test_registry_report_changes/test_registry_all_limits_disabled.py
- test_registry/test_registry_report_changes/test_registry_file_size_values.py
- test_registry/test_registry_report_changes/test_registry_disk_quota_values.py

```

**Comment by damarisg** [comment]
`test_file_limit:` Changes config, there are new log to File(WARNING: (6926): File database is 100%% full.) and Registry(WARNING: (6927): Registry database is 100%% full.). 

**Details**:

- https://github.com/wazuh/wazuh/pull/11959
- https://github.com/wazuh/wazuh-documentation/issues/4767

`test_registry:` The limit specified in the config should be in the registry with the new configuration (https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_fim/test_registry/test_registry_file_limit/data/wazuh_conf.yaml)

`test related to sync`: wazuh_response_conf.yaml -> 
response_timeout is deprecated because it works from the RSync library.

**Comment by Deblintrake09** [comment]
During testing it was found that registry diff files are not being generated, because of a bug on how diff temp files are generated.

An [Issue](https://github.com/wazuh/wazuh/issues/12692) and [PR](https://github.com/wazuh/wazuh/pull/12693) have been already created. Blocking Issue until it's merged into branch 9103

**Comment by CamiRomero** [comment]
## Tests Results
| Test  | OS - type | Execution Type | Results | Date | By |
|--|--|--|--|--|---|
| Files| CentOS - Manager | Jenkins | [:green_circle:](https://ci.wazuh.info/job/Test_integration/25045)| 13/04/2022 |  @CamiRomero  |
| Files | CentOS - Agent | Jenkins | [:green_circle:](https://ci.wazuh.info/job/Test_integration/25068/)| 13/04/2022 |  @CamiRomero  |
| Files | Solaris - Agent | Jenkins | [:green_circle:](https://ci.wazuh.info/job/Test_integration/25068/)| 13/04/2022 |  @CamiRomero  |
| Registry| Windows - Agent | Jenkins | [:green_circle:](https://ci.wazuh.info/job/Test_integration/25063/)| 13/04/2022 |  @CamiRomero  |

**Comment by damarisg** [comment]
It was merged on `[1915-fim-rsync-new-synchronization-mechanism](https://github.com/wazuh/wazuh-qa/tree/1915-fim-rsync-new-synchronization-mechanism)` branch.
