### ISSUE TITLE
Stabilize test_logging from GCloud suite tests

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#2340]
As for now, the `test_logging` test is getting successful executions and failed executions as well.  It is needed to stabilize this test in order to get only successful results and change its logic, due to the fact that there is a duplicated condition implemented (#1857). This issue will refactor and stabilize the current `test_logging` implementation.

**Comment by mauromalara** [comment]
@snaow was in charge of stabilizing the GCloud suite.
