### ISSUE TITLE
Analysisd - Test that the json_null_field and json_array_structure options work properly

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2342]
Installation | Component | Version | Related issue
-- | -- | -- | --
Manager | Analysisd | 4.3.0 | wazuh/wazuh#7486

# Description

We need to test that the ```json_null_field``` and ```json_array_structure``` options work as is described in the documentation ([here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html?highlight=decoders#json-null-field) and [here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html?highlight=decoders#json-array-structure)). We design the tests based on [this PR](https://github.com/wazuh/wazuh/pull/7711).

# Tests

- [ ] Check that the ```json_null_field``` and ```json_array_structure``` options take effect when configured with different values
- [x] Check that invalid values for ```json_null_field``` and ```json_array_structure``` are not taken
- [x] Check that ```json_null_field``` and ```json_array_structure``` configuration is case-insensitive
- [x] Check that ```empty``` value in ```json_null_field option``` is not valid anymore

**Comment by fernandolojano** [comment]
The working branch for this issue will be: [2342-analysisd-test-decoder-syntax](https://github.com/wazuh/wazuh-qa/tree/2342-analysisd-test-decoder-syntax).

**Comment by fernandolojano** [comment]
As for now, the part of checking that the json_null_field and json_array_srtucture aren't taking any invalid values is implemented. The case-insensitive and the deprecated values checking are also implemented. It remains to check if these two options take the right effect when are configured in a decoder.
