### ISSUE TITLE
Remoted tests fix to support IPv6

### ISSUE THREAD

**Issue by MizugorouZ** [wazuh/wazuh-qa#2363]
### Description
Remoted tests need to be fixed in accordance with IPv6 development ([wazuh/wazuh#4243](https://github.com/wazuh/wazuh/issues/4243)). Until now, a warning error was searched in IPv6 basic configuration, but with the new development it should be allowed.

**Comment by Rebits** [comment]
Merged in https://github.com/wazuh/wazuh-qa/pull/2439
