### ISSUE TITLE
Add test cases for IPv6 to Remoted tests - Local IP valid

### ISSUE THREAD

**Issue by MizugorouZ** [wazuh/wazuh-qa#2373]
| Related issue |
|:--:|
| #2257 |

### Description
After the research done in #2257, `test_basic_configuration_local_ip_valid.py` needs to add cases to support IPv6.

**Comment by Rebits** [comment]
Merged in https://github.com/wazuh/wazuh-qa/pull/2439

**Comment by Rebits** [comment]
Due to https://github.com/wazuh/wazuh-qa/pull/2379#issuecomment-1005640450, `local_ip` test will not be ampliated for ipv6 tests cases for the moment.
