### ISSUE TITLE
Add test cases for IPv6 to Remoted tests - Syslog allowed IPs invalid

### ISSUE THREAD

**Issue by MizugorouZ** [wazuh/wazuh-qa#2375]
| Related issue |
|:--:|
| #2257 |

### Description
After the research done in #2257, `test_basic_configuration_syslog_allowed_ips_invalid.py` needs to add cases to support IPv6.

**Comment by Rebits** [comment]
Merged in https://github.com/wazuh/wazuh-qa/pull/2439
