### ISSUE TITLE
FIM Files Events: System test for FIM synchronization process (1)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2389]
While developing https://github.com/wazuh/wazuh/issues/9103 we are planning to develop some system tests to check that the FIM database agent and the manager database are synchronized. 

After some analysis, we have the following tests:

 ## fim_file_event
This test will check that when an event is triggered in the agent. the manager updates the inventory properly.

1. Monitor a folder (preferably, create several cases for each monitorization mode)
2. Create events in the monitored folder: add, modify and delete.
3. Check that the agent sends the event and the manager receives it.
4. Finally, check that the manager updates the inventory with the new results

**Comment by CamiRomero** [comment]
This Issue will be working on branch 2345-refactor-fim-limits-test-of-test-report-changes. We add 3 test:
