### ISSUE TITLE
Logcollector - Test Wazuh behavior's when setting an invalid <localfile>  configuration.

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2391]
Installation | Component | Version | Related issue
-- | -- | -- | --
Manager/Agent | Logcollector | 4.3.0 | wazuh/wazuh#6463

# Objective

1. Create a test that checks the manager or agent behavior when they have an invalid ```<localfile>```  configuration.

# Scope

**"Logcollector" and "Agentd" must be tested on the Manager and the Agent, respectively.**

## Logcollector (Manager)

- [x] CentOS
- [x] Ubuntu

## Agentd (Agent)

- [x] Windows
- [x] CentOS
- [x] Ubuntu
- [x] MacOS
- [x] Solaris

# Context

The Logcollector's **configuration parser** reads each ```<localfile>``` stanza in ```ossec.conf``` and ```agent.conf```. After that, it performs some extra checks:

1. On Windows, ```<location>``` must be either "Application", "System" or "Security" when ```<log_format>``` is "eventchannel".
2. Expand ```<location>``` if it is a glob pattern.
3. ```<log_format>``` and ```<location>``` must exist.

> The **configuration parser** used to check that ```<location>``` exists after checking points 1 and 2, throwing a memory error if ```<location>``` was missing.

# Tests

- [x] Given that the `location` option is not present in the `localfile` section in the `ossec.conf` file. When the `manager` is restarted, the `manager` refuses to restart and the expected messages are in the log file.
- [x] Given that the `log_format` option is not present in the `localfile` section in the `ossec.conf` file. When the `manager` is restarted, the `manager` refuses to restart and the expected messages are in the log file.
- [x] Given that the `location` option is not present in the `localfile` section in the `ossec.conf` file. When the `agent` is restarted, the `agent` refuses to restart and the expected messages are in the log file.
- [x] Given that the `log_format` option is not present in the `localfile` section in the `ossec.conf` file. When the `agent` is restarted, the `agent` refuses to restart and the expected messages are in the log file.
- [x] Given that the `location` option is not present in the `localfile` section in the `agent.conf` file. When the `agent` is restarted, the `agent` continues running and the expected messages are in the log file.
- [x] Given that the `log_format` option is not present in the `localfile` section in the `agent.conf` file. When the `agent` is restarted, the `agent` continues running and the expected messages are in the log file.

### Expected result when trying to restart Wazuh after an invalid config

```
2021/12/22 16:14:47 wazuh-logcollector: ERROR: (1902): Missing 'location' element.
2021/12/22 16:14:47 wazuh-logcollector: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
2021/12/22 16:14:47 wazuh-logcollector: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-logcollector: Configuration error. Exiting
```

**Comment by danisan90** [comment]
**Update:**

- Worked on agent.conf backup: added a new function to do a backup of the original agent.conf. It's not working properly yet.

**Comment by danisan90** [comment]
**Update**:
#### Style guide
| Command | Status |
| --- | --- |
| `pycodestyle --max-line-length=120 <FILE-PATH>` |  :green_circle: |

#### Reports
| OS | Type | Results | Date |
|--|--|--|--|
|Centos|Manager| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7916334/2391ManagerCentos.zip)| 01/21/2022
|Centos|Agent| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7916338/2391AgentCentos.zip)| 01/21/2022

**Comment by danisan90** [comment]
**Update**
A refactor is needed.
The code needs some improvement as the use of the fixture `configure_environment` and the addition of a data yaml. At the moment the code it's not using some useful tools that already exist causing an unstable test.
