### ISSUE TITLE
Generate generic skip marker on cloud

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#2410]
During work on Issue [#2305](https://github.com/wazuh/wazuh-qa/issues/2305), it was requested the generation of a generic skip marker that can be added to tests to be skipped on cloud environments.

This marker can be generated by taking advantage of the new `could_config.yaml` file and the `skip_cloud` flag that are added in Issue #2305.

The proposed marker could be added on the general `test/integration/conftest.py` file with something like this:

> if global_parameters.cloud_config is not None:
>      mark_skip_cloud = pytest.mark.skipif( global_parameters.cloud_config[skip_cloud]== 'yes', reason="test skipped on cloud instances - Issue #").
> 
 then the mark can be added to a test with the simple decorator before the test:

> @mark_skip_cloud

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
