### ISSUE TITLE
QA Docs: Add general values to mandatory fields

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2424]
## Description

While developing system tests, we tried to implement the test documentation following the [QA-Docs Schema 2.0](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0). However, there are some mandatory fields, like `modules` or `daemons`, that need tags like `general` or `all`, so we can complete the documentation in system tests.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
