### ISSUE TITLE
Vulnerability detector test module refactor: `test_providers_update_from_year`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2465]
It is asked to refactor the test module named `test_providers_update_from_year.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [x] Make a study of the objectives of the test, and what is being tested.
- [x] Refactor the test. Clean and modularizable code.
- [x] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [x] Review test documentation, and modify if necessary.
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Test in 5-10 rounds of execution that the test always shows the same result.

## Checks

- [x] The code complies with the standard PEP-8 format.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is processed by `qa-docs` tool without errors.

**Comment by fedepacher** [comment]
## Test design

### Name

`test_providers_update_from_year.py`

---

### Objective

Check if the vulnerability detector download feeds from the correct year based on `<update_from_year>`.

---

### Test checks

- Check that the feeds downloaded start from `<update_from_year>` year.

---

### Initial stage (setup)

- All modules except vulnerability detector must be disabled
- `cve.db` tables must be empty.
- Clean the `ossec.log` file

---

### Test phases

**Diferent providers cases**

- Update `ossec.conf` configuration
- Restart `wazuh-modulesd` daemon
- Monitor `ossec.log` and check the provider update log.
- Monitor `ossec.log` and wait until the provider database is updated.
- Query the vulnerabilities table rows number for that provider (must be >0).

---

### Final stage (teardown)

- `cve.db` tables must be empty.
- Initial `ossec.conf` file must be restored.
- Clean the `ossec.log` file

---

### Test cases (14 total):

- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 1998}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2001}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2002}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2005}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2010}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2015}`
- `{'PROVIDER': 'redhat', 'UPDATE_FROM_YEAR': 2020}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 1998}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2001}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2002}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2005}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2010}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2015}`
- `{'PROVIDER': 'nvd', 'UPDATE_FROM_YEAR': 2020}`
