### ISSUE TITLE
Add a test to check that the Pagerduty integration does not allow curl arguments in the hook URL

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#2466]
|Related PR|
|---|
|https://github.com/wazuh/wazuh/pull/11835|

We've fixed a bug in the Pagerduty integration script that allowed injecting arguments for the `curl` command in the option `<hook_url>`. For instance:

```xml
<ossec_config>
   <integration>
    <name>pagerduty</name>
    <api_key>topsecret</api_key>
    <hook_url>example.org\ -o\ /var/ossec/etc/some_file</hook_url>
  </integration>
</ossec-config>
```

The configuration above would make the script execute:
```sh
curl -H "Content-type: application/json" -X POST --data "@/tmp/pagerduty-1642752784-559630727.alert" example.org -o /var/ossec/etc/some_file
```

Which would dump the result from `curl` into _/var/ossec/etc/some_file_. This would allow a malicious user to overwrite files that the integration should not change.

## Expected behavior

The configuration above should be rejected by the Pagerduty integration, so Integratord shall print the following errors into the log:
```
2022/01/21 09:13:04 wazuh-integratord: ERROR: Unable to run integration for pagerduty -> integrations
2022/01/21 09:13:04 wazuh-integratord: ERROR: While running pagerduty -> integrations. Output: Error sending the alert to pagerduty
2022/01/21 09:13:04 wazuh-integratord: ERROR: Exit status was: 1
```

If we run the underlying script, it would print:
```sh
root@: /var/ossec # integrations/pagerduty /tmp/pagerduty-1642752784-559630727.alert topsecret example.org\ -o\ /var/ossec/etc/some_file debug
curl: (3) URL using bad/illegal format or missing URL
Error sending the alert to pagerduty
```

**Comment by damarisg** [comment]
We decided to close them.
