### ISSUE TITLE
Update cluster CSV parser tool and test thresholds

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#2468]
In https://github.com/wazuh/wazuh-qa/pull/2032, a tool was developed in charge of iterating, loading and processing CSVs with data on the use of resources of the `wazuh-clusterd` process.

However, multiple developments (https://github.com/wazuh/wazuh/pull/10767, https://github.com/wazuh/wazuh/pull/10807, https://github.com/wazuh/wazuh/issues/10920, https://github.com/wazuh/wazuh/pull/11364) have been carried out on the Wazuh cluster that provides it with multiprocessing capabilities.

This has been a boost in its performance. However, it involves creating new child processes that also use resources. These child processes are not taken into account by this tool, hence the need to update it.

Also, when the tool is updated to aggregate information from all processes, the resource thresholds that were set in the performance test (https://github.com/wazuh/wazuh-qa/issues/1939) will probably fall far short. Therefore, it will be necessary to update it.

- [x] Update CSV parser tool.
- [x] Update cluster performance test.

**Comment by yanazaeva** [comment]
## Issue update

A method was added to the CSVParser class in order to sum up the parent and children processes.

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh-qa/2468?planning-poker) with ZenHub @AdriiiPRodri @Selutario @yanazaeva

**Comment by yanazaeva** [comment]
## Issue update

The threshold was updated accordingly to these results:
[50000A10w.zip](https://github.com/wazuh/wazuh-qa/files/8207215/50kA10w.zip)
[50000A25W.zip](https://github.com/wazuh/wazuh-qa/files/8207221/50000A25W.zip)
