### ISSUE TITLE
Test the new multi-group generation mechanism

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2471]
| Related issue |
|---|
| wazuh/wazuh#11054 |

| Type | Target/s |
|---|---|
| Integration | Manager (master node) |

## Description
The previous behavior was the following:
- The wazuh-remoted daemon used to regenerate in the master node all multi-groups (/var/ossec/var/multigroups) every 10 seconds, whether they would have changed or not.

The new generation mechanism is the following:
- The `wazuh-remoted` daemon in the master node only regenerates the multi-groups related to groups that have recently changed.

## Tests

- [x] Check that only the appropriate multi-groups are generated when any file in `/var/ossec/etc/shared/{group-name}` changes.
- [x] Check that no multi-group is generated when no files have changed.
- [x] Check the generation of new multi-groups.
- [x] Check that no folder exists when the multi-group doesn't longer exist (no agents associated with them).

## DoD

- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [ ] QA-Docs executed from branch `1864-qa-docs-fixes`
- [x] Prove that the tests fail when they have to
- [x] Prove that the tests pass when they have to
- [x] 3 local executions (Generate the report)
- [ ] 3 Jenkins executions (Link the job in Jenkins)

**Comment by Selutario** [comment]
## Status update

I will develop 3 tests:
1. The first test will verify that neither the `merged.mg` nor any other group file are recreated or reloaded every 10 seconds as happened before.
2. The second test will check if, when adding or modifying a file, the `merged.mg` is correctly regenerated.
3. Finally, the third test will check if when deleting the group or the agent assignment, the multigroup disappears as it should.

Some of these tests may need to include different use cases, such as creating new files or deleting existing ones. 

At the moment, the first test (check that the files are not re-created if nothing has changed) is almost done.

**Comment by Selutario** [comment]
## Status update

The following tests have already been developed:
- Check that the expected multigroups are created when assigning agents to groups.
- Check that the multigroup and `merged.mg` files are not regenerated if no files were added/changed/deleted.
- Check that the expected multigroups are regenerated when adding/modifying/deleting files.

### To do
- Add test to check that expected multigroups are deleted when unassigning agents or deleting groups.

**Comment by Selutario** [comment]
## Status updat

All test are now developed. However, I'm finding an strange behavior: the `mtime` of a file is being modified even when it shouldn't. I could not deep into it yet, but I will.

**Comment by Selutario** [comment]
| Working branch |
|--|
|[dev-2471-multigroups-system-test](https://github.com/wazuh/wazuh-qa/tree/dev-2471-multigroups-system-test)|

## Status update

Fixed the issue that caused the test to fail sometimes. It already works correctly in all the rounds that I have run it.
