### ISSUE TITLE
System Test - Wazuh DB (T0): Agent never_connected connects

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2505]
# Description

This test aims to verify that the agent connects correctly to the cluster and that when it has no specific configuration, the agent belongs to the default group.

# Test Details

## Case 1:

**Given** a configured master
**And** two workers configured
**When** an agent connects to the master node
**Then** the agent changes its `never_connected` state to `Active`
**And** each node has the agent with its `default group` after `X` seconds

## Case 2:

**Given** a configured master
**And** two workers configured
**When** an agent connects to the worker nodes
**Then** the agent changes its `never_connected` state to `Active`
**And** each node has the agent with its `default group` after `X` seconds

## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by Deblintrake09** [comment]
### Updates 2022/01/31
- Read Wazuh_db documentation and changes to test

**Comment by Deblintrake09** [comment]
- Development Finished
- Blocked by Wazuh/Wazuh Issue [#10751](https://github.com/wazuh/wazuh/issues/10751)

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
