### ISSUE TITLE
System Test - Wazuh DB (T0): Agent registered with group Y (agent_authd - disconnected)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2508]
# Description

The aim here is to verify that a registered agent is in with a "Y" group when the registration is with agent-auth and the status of the agent is never_connected.

# Test Details

## Case 1:

**Given** a configured master
**AND** two workers configured
**AND** the status of the agent is never_connected
**When** an agent registers with group Y to the `master` node using agent-auth
**Then** each node has the agent with its `Y` group in no less than `X` seconds.

## Case 2:

**Given** a configured master
**AND** two workers configured
**AND** the status of the agent is never_connected
**When** an agent registers with group Y to the `worker` node using agent-auth
**Then** each node has the agent with its `Y` group in no less than `X` seconds.
   
## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)
- Registration is with authd specifying the group and, this does not connect, for example when leaving it without configure.

**Comment by CamiRomero** [comment]
These tests were applied on the [2508_system_test_assign_agent_with_agent_auth](https://github.com/wazuh/wazuh-qa/tree/2508_system_test_assign_agent_with_agent_auth) branch. The issue will be moved to the blocking state until the merge of core branch to master

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
