### ISSUE TITLE
System Test - Wazuh DB (T0): Adds a new node to a synchronized environment.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2511]
# Description

The aim here is to verify that in a synchronized environment with N agents belonging to different groups, a new node is added and contains information from all agents.

# Test Details

## Case 1:

**Given** a configured master
**And** two workers configured
**And** the agent `AA` registers with group `A` to the master node
**And** the agent `AB` registers with group `B` to the master node
**And** the agent `AC` registers with group `C` to the master node
**And** the cluster is synchronized
**When** a new worker `worker3` is configured
**Then**  the `worker3` has an `AA` agent with group `A`  in no less than `X` seconds.
**And**  the `worker3` has an `AB` agent with group `A`  in no less than `X` seconds.
**And**  the `worker3` has an `AC` agent with group `A`  in no less than `X` seconds.

## Case 2:

**Given** a configured master
**And** two workers configured
**And** the agent `AA` registers with group `A` to the `worker2` worker node
**And** the agent `AB` registers with group `B` to the `worker1` worker node
**And** the cluster is synchronized
**When** a new worker `worker3` is configured
**Then**  the `worker3` has an `AA` agent with group `A`  in no less than `X` seconds.
**And**  the `worker3` has an `AB` agent with group `A`  in no less than `X` seconds.

## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by Deblintrake09** [comment]
These tests were applied on the `tmp-2511_test_agent_groups_new_cluster_node` branch. The issue will be moved to the blocked state until the merge of core branch to master

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
