### ISSUE TITLE
System Test - Wazuh DB (T0): Agent forced to change group

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2512]
# Description

The aimhere is to verify that in a synchronized environment with N agents belonging to different groups, we force the group change of an agent in a worker node (wdb).

# Test Details

## Case 1:

**Given** a configured master  
**And** a `worker1` worker configured  
**And** a `worker2` worker configured  
**And** the agent `AA` registers with group `A` to the master node  
**And** the agent `AB` registers with group `B` to the master node  
**And** the agent `AC` registers with group `C` to the master node  
**And** the cluster is synchronized  
**When** the agent `AA` registered is force to change group `B` (force with wdb command) 
**Then** the `master` has an `AA` agent with group `B` after `X` seconds  
**And** the `worker1` has an `AA` agent with group `B` after `X` seconds  
**And** the `worker2` has an `AA` agent with group `B` after `X` seconds

## Case 2:

**Given** a configured master  
**And** a `worker1` worker configured  
**And** a `worker2` worker configured  
**And** the agent `AA` registers with group `A` to the `worker2` worker node
**And** the agent `AB` registers with group `B` to the `worker1` worker node
**And** the agent `AC` registers with group `C` to the `worker1` worker node
**And** the cluster is synchronized  
**When** the agent `AA` registered is force to change group `B` (force with wdb command) 
**Then** the `master` has an `AA` agent with group `B` after `X` seconds  
**And** the `worker1` has an `AA` agent with group `B` after `X` seconds
**And** the `worker2` has an `AA` agent with group `B` after `X` seconds

## Case 3:

**Given** a configured master
**And**  a `worker1` worker configured
**And**  a `worker2` worker configured
**And** the agent `AA` registers with group `A` to the `worker2` worker node
**And** the agent `AB` registers with group `B` to the `worker1` worker node
**And** the agent `AC` registers with group `D` to the `worker1` worker node
**And** the cluster is synchronizing
**When** the agent `AA` registered is force to change group `B` (force with wdb command) 
**And**  the agent `AA` registered is force to change group `C` (force with wdb command) 
**And** the cluster is synchronized after `Z` seconds
**Then**  the `worker1` has an `AA` agent with group `C`  after `X` seconds
**And**  the `worker2` has an `AA` agent with group `C`  after `X` seconds
**And**  the `master` has an `AA` agent with group `C`  after `X` seconds

## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by Deblintrake09** [comment]
## Update 2022/02/11
- Designed and blocked in the tests
- On Hold waiting for command to use from Core Team

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
