### ISSUE TITLE
System Test - Wazuh DB (T2): Sync of agents registered on nodes after seconds

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2514]
# Description

The aim of this test is to verify that every Z/2 seconds an agent is registered without specifying a group to each node, this happens during 20Z. Where all agents registered after 20Z + X seconds are kept in the database of all nodes with the correct information.

# Test Details

## Case 1:

**Given** a configured master `master`
**And** a configured worker `worker1`
**And** a configured worker `worker2`
**And** During 20Z an agent `agent-N` connects to the master node every Z/2 seconds. (40 agents)
**Then** each node has all the 40 agents with its `default` group in no less than `20Z + X` seconds in the db..

## Case 2:

**Given** a configured master `master`
**And** a configured worker `worker1`
**And** a configured worker `worker2`
**And** During 20Z an agent `agent-N` connects to the master node every Z/2 seconds. (40 agents)
**Then** each node has all the 40 agents with its `default` group in no less than `20Z + X` seconds in the db..
   
## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by Deblintrake09** [comment]
### Progress done 2022/02/18
- Worked on Branch `tmp-2514-test-group-synchro-default`
- Read Issue and plan test
- Created test based off of test in Issue #2515 
- On Hold while waiting for reply from Core Team about extending sync time since test architecture doesn't allow for test to run in proposed time. (Same problem than #2515)

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
