### ISSUE TITLE
 System Test - Wazuh DB (T2): Sync of agents registered with group on nodes after seconds

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2515]
# Description

The objective is to verify that every Z/2 seconds, an agent is registered specifying group (or groups) to each node, this happens during 20Z.

# Test Details

## Case 1:

**Given** a configured master `master`
**And** a configured worker `worker1`
**And** a configured worker `worker2`
**And** 40 agents have registered to the master node following the pattern `agent-N` with `N` group.
**And** During 20Z an agent `agent-N` connects to the master node every Z/2 seconds. (40 agents)
**Then** each node has all the 40 agents with its `default` group in no less than `20Z + X` seconds in the db.

## Case 2:

**Given** a configured master `master`
**And** a configured worker `worker1`
**And** a configured worker `worker2`
**And** 40 agents have registered to the master node following the pattern `agent-N` with `N` group.
**And** During 20Z an agent `agent-N` connects to the master node every Z/2 seconds. (40 agents)
**Then** each node has all the 40 agents with its `default` group in no less than `20Z + X` seconds in the db.

   
## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by Deblintrake09** [comment]
### Progress done 2022/02/16
- After Call with Core Team, the test environment changed and the Issue was modified
- Research on Ansible parametrization

### Progress done 2022/02/15
- Read up on test and design tests
- Created test Enviroment
- Blocked In Test

**Comment by damarisg** [comment]
It was merged on `qa-10771-agent-groups-files-to-wazuh-db` branch and closed.
