### ISSUE TITLE
System Test - Wazuh DB (T2): Agent never_connected connects (guesses a different group by default)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2516]
# Description

Here we want to verify that when the guessing mechanism is activated, the group of a new agent is guessed (comparison of cks), the guessed group is different from the default, this change in the DB is synchronized to all nodes. To activate the guess, the Core team can help us.

 
# Test Details

## Case 1:

**Given** a master set to `master`
**AND** a configured worker `worker1`
**AND** a configured worker `worker2`
**When** the guessing mechanism is activated
**AND** an agent `agent1` connects to the master node
**AND** Agent 'agent1' registers with a different 'Guess' group than the 'default' group.
**Then** each node has agent `agent1` with its group `Guess` in no less than `X` seconds. 

## Case 2:

**Given** a master set to `master`
**AND** a configured worker `worker1`
**AND** a configured worker `worker2`
**When** the guessing mechanism is activated
**AND** an agent `agent1` connects to the `worker1` worker node
**AND** Agent 'agent1' registers with a different 'Guess' group than the 'default' group.
**Then** each node has agent `agent1` with its group `Guess` in no less than `X` seconds. 
   
## Note:
- X: Estimated time for complete information synchronization, minimum 2*Z --- worker1 -> master -> worker1/2
- Z: Cluster synchronization period (default 10 seconds)

**Comment by CamiRomero** [comment]
Blocked by [Issue 13054](https://github.com/wazuh/wazuh/issues/13054)

**Comment by Deblintrake09** [comment]
## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_agent_to_a_group.py  | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8446611/R1.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8446611/R1.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8446612/R2.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8446613/R3.zip)| 07/04/2022 |  @Deblintrake09   |

**Comment by damarisg** [comment]
This issue is blocked by https://github.com/wazuh/wazuh/issues/13172, once a time that it is resolved we need to run the test from the  branch `qa-10771-agent-groups-files-to-wazuh-db`

**Comment by CamiRomero** [comment]
## Tests Results
| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
| test/system/test_cluster/test_agent_groups/test_assign_groups_guess.py  | CentOS - Manager | Local | [:large_blue_circle:](https://ci.wazuh.info/job/Test_system/58/)| 21/04/2022 |  @CamiRomero    |
