### ISSUE TITLE
System Test - Wazuh DB (T0): Agents syncronization in cluster environments

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2559]
# Description
As part of https://github.com/wazuh/wazuh/issues/12075, it is required to define, estimate and create a set of system tests that checks the integrity of the client keys information in the global.db.

# Test Details
These tests must:
- Cover a cluster synchronization of the keys.
- Cover the addition of new agents.
- Cover the correct connection of the new agents
- Cover the removal of agents and the connection deny of deleted agents.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
