### ISSUE TITLE
Integration Test - Wazuh DB (T0): Adaptation of existing tests after client.keys migration

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#2561]
# Description
As part of https://github.com/wazuh/wazuh/issues/12075, it is required to define, estimate and work on the fix of every Wazuh test that handles the client.keys file directly now that this information is migrated to global.db and the file is deprecated.

# Test Details
These tests must:
- Fix every Wazuh test to handle the keys information directly from WDB.

**Comment by damarisg** [comment]
We decided to close them.
