### ISSUE TITLE
System Tests - Fix test_active_response_log_format

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#2566]
## Description
During research for PR #2557  it was found that the test test_active_response_log_format was failing. It was found that the Rule that was activated by the log passed in by the test, changed from `5710` to `5760` causing no active response to be fired and no logs to be shown. 

The test passed in Master with the changes shown below, but failed in from the branch `2509-system-host-monitor`

## To Do
- changes in manager's  `ossec.conf`:
Change both active responses from `5710` a `5760`
- Changes to `messages_415_or_lower.yml` file:
Change the regex value for active_response.log from `5710` to `5760`

**Comment by juliamagan** [comment]
This fix shouldn't be necessary since the rule ID should be the same as in the previous versions. This is being fixed in https://github.com/wazuh/wazuh/pull/12328
