### ISSUE TITLE
Refactor `check_daemon_status`

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2567]
## Description

Now, `check_daemon_status` is checking if the desired daemon is running and if its sockets are ready. However, if we stop `wazuh-remoted` and change the configuration so there is no `<connection>secure</connection>`, the `request` socket won't be created when Wazuh or `wazuh-remoted` is started again, since this socket is only used for secure connections.

We need to change the function so it doesn't check the `request` socket if there is no secure connection in the configuration. We could generalize the `check_daemon_status` function and change it into a fixture since it could be useful in every test. It could check the daemons, the sockets, and the started logs.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
