### ISSUE TITLE
Add QA integration tests for the API JSON log support

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh-qa#2580]
## Description
As a part of https://github.com/wazuh/wazuh/issues/11308, we should consider adding new QA integration tests for this new feature.

This issue aims to tests API log configuration since in the related development our API is able to log into the following file types:
* Plain files.
* JSON files.
* Both files.

## API logging configuration - `/var/ossec/api/configuration/api.yaml`.

```yaml
logs:
  level: "info"
  format: "plain"
```
_NOTE: format allowed values are `json`, `plain`, `json,plain` and `plain,json`_.

* More information can be found here: https://github.com/wazuh/wazuh/pull/11171.

## Tests cases
* Set the logging format as `plain`, API running in background => verify it's logging in plain format at `/var/ossec/logs/api.log`.
* Set the logging format as `json`, API running in background => verify it's logging in json format at `/var/ossec/logs/api.json`.
* Set the logging format as `plain,json` or `json,plain`, API running in background => verify it's logging in plain format at `/var/ossec/logs/api.log` and json format at `/var/ossec/logs/api.json`. Compare the log values since they should match (timestamp, message, log level, etc).
* Set the logging format as `plain`, API running in foreground => verify it's logging in plain format at `/var/ossec/logs/api.log` and foreground.
* Set the logging format as `json`, API running in foreground => verify it's logging in json format at `/var/ossec/logs/api.json` and plain format in foreground.
* Set the logging format as `plain,json` or `json,plain`, API running in foreground => verify it's logging in plain format at `/var/ossec/logs/api.log` and json format at `/var/ossec/logs/api.json`. It should be logging in plain format in foreground.
* Set the logging format as `plain,json` or `json,plain`, API running in background => verify both log files are properly rotated.

**Comment by mauromalara** [comment]
## 2022/02/22
### Test cases
In first place, we create a decision table to analyze the possible test cases:

<table>
<thead>
  <tr>
    <th rowspan="5">Conditions</th>
    <th>format: json</th>
    <th>F</th>
    <th>T</th>
    <th>T</th>
    <th>F</th>
    <th>T</th>
    <th>T</th>
  </tr>
  <tr>
    <th>format: plain</th>
    <th>T</th>
    <th>F</th>
    <th>T</th>
    <th>T</th>
    <th>F</th>
    <th>T</th>
  </tr>
  <tr>
    <th>mode: background</th>
    <th>T</th>
    <th>T</th>
    <th>T</th>
    <th>F</th>
    <th>F</th>
    <th>F</th>
  </tr>
  <tr>
    <th>mode: foreground mode</th>
    <th>F</th>
    <th>F</th>
    <th>F</th>
    <th>T</th>
    <th>T</th>
    <th>T</th>
  </tr>
  <tr>
    <th>? condition to rotate the<br>log files</th>
    <th>?</th>
    <th>?</th>
    <th>?</th>
    <th>?</th>
    <th>?</th>
    <th>?</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="5">Resulting<br>Actions</td>
    <td>log to log file, plain format</td>
    <td>X</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td>X</td>
  </tr>
  <tr>
    <td>log to json file, json format</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td>X</td>
    <td>X</td>
  </tr>
  <tr>
    <td>log with same values<br>in the fields</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td>X</td>
  </tr>
  <tr>
    <td>log to foreground, plain format</td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
  </tr>
  <tr>
    <td>both logs are rotated</td>
    <td>?</td>
    <td>?</td>
    <td>?</td>
    <td>?</td>
    <td>?</td>
    <td>?</td>
  </tr>
</tbody>
</table>

As Alexis said, the necessary test cases are:
1. Check that Wazuh is logging correctly into the `api.log` file when the format is `plain` and the mode is `background`
2. Check that Wazuh is logging correctly into the `api.json` file when the format is `JSON` and the mode is `background`
3. Check that Wazuh is logging correctly into the `api.log` and `api.json` files when the format is `JSON-plain` and the mode is `background` (and the values match)
4. Check that Wazuh is logging correctly into the `api.log` file and into `fg` when the format is `plain` and the mode is `foreground`
5. Check that Wazuh is logging correctly into the `api.json` file and into `fg` when the format is `JSON` and the mode is `foreground`
6. Check that Wazuh is logging correctly into the `api.log` and `api.json` files, and into `fg` when the format is `JSON-plain` and the mode is `foreground` (and the values match)

### Possible set up
1. Stop the `wazuh-apid` daemon via `daemon_handler`
2. Change the API logging configuration in `/var/ossec/api/configuration/api.yaml` according to the YAML
3. Run the `wazuh-apid` daemon via `daemon_handler` in the specified mode
4. ¿configure rotation?
### Possible tear down
1. Restore API configuration
2. Restart `wazuh-apid` via `daemon_handler`
3. Delete the logs from `api.log` and `api.json`

**Comment by mauromalara** [comment]
# Update: 2022/02/25
## Analysis
<table>
<thead>
  <tr>
    <th rowspan="3">Conditions</th>
    <th>format</th>
    <th>json</th>
    <th>json</th>
    <th>json</th>
    <th>plain</th>
    <th>plain</th>
    <th>json,plain</th>
    <th>json,plain</th>
    <th>plain,json</th>
  </tr>
  <tr>
    <th>mode</th>
    <th>foreground</th>
    <th>background</th>
    <th>background</th>
    <th>foreground</th>
    <th>background</th>
    <th>foreground</th>
    <th>background</th>
    <th>background</th>
  </tr>
  <tr>
    <th>level</th>
    <th>info</th>
    <th>info</th>
    <th>error</th>
    <th>info</th>
    <th>info</th>
    <th>info</th>
    <th>info</th>
    <th>disabled</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="7">Resulting<br>Actions</td>
    <td>log to log file,<br>plain format</td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td></td>
  </tr>
  <tr>
    <td>log to json file,<br>json format</td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
  </tr>
  <tr>
    <td>log with same<br>values in the fields</td>
    <td>X</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
  </tr>
  <tr>
    <td>log to foreground,<br>plain format</td>
    <td>X</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>matched log-1 (error)</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>matched log-2 (info)</td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td></td>
  </tr>
  <tr>
    <td>no log files exist</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
  </tr>
</tbody>
</table>

## Design
### Data
#### Log-1: `error` level
```
{
   "timestamp":"(\d+(:|\/)){2}\d+",
   "levelname":"ERROR",
   "data":{
      "type":"informative",
      "payload":"2010 - Error while attempting to bind on address: address already in use."
   }
}
```
#### Log-2: `info` level
```
{
  "timestamp": "(\d+(:|\/)){2}\d+",
  "levelname": "INFO",
  "data": {
    "type": "informative",
    "payload": "Listening on (\d+(\.?))+.*"
  }
}
```
### Test cases
#### 2 tests will be created:

##### test_api_logs_formats.py
1. Given that the configured format is `json`, and the level is set to `info`; When the `wazuh-apid` is started in `foreground` mode; Then the `log-2` is in the json log in `json` format, and the `log-2` is displayed in the CLI in `plain` format, and the values of the log in the file and in the CLI matched.
2. Given that the configured format is `json`, and the level is set to `info`; When the `wazuh-apid` is started in `background` mode; Then the `log-2` is in the json log in `json` format.
3. Given that the configured format is `json`, and the level is set to `error`, and the `wazuh-apid` is started in `background` mode; When the `wazuh-apid` is started again in `background` mode; Then the `log-1` is in the json log in `json` format.
4. Given that the configured format is `plain`, and the level is set to `info`; When the `wazuh-apid` is started in `foreground` mode; Then the `log-2` is in the log in `plain` format, and the `log-2` is displayed in the CLI in `plain` format, and the values of the log in the file and in the CLI matched.
5. Given that the configured format is `plain`, and the level is set to `info`; When the `wazuh-apid` is started in `background` mode; Then the `log-2` is in the log in `plain` format.
6. Given that the configured format is `json,plain`, and the level is set to `info`; When the `wazuh-apid` is started in `foreground` mode; Then the `log-2` is in the log in `plain` format, and the `log-2` is in the json log in `json` format, and the values of both logs matched, and the `log-2` is displayed in the CLI in `plain` format.
7. Given that the configured format is `json,plain`, and the level is set to `info`; When the `wazuh-apid` is started in `background` mode; Then the `log-2` is in the log in `plain` format, and the `log-2` is in the json log in `json` format, and the values of both logs matched.
8. Given that the configured format is `plain,json`, and the level is set to `disabled`; When the `wazuh-apid` is started in `background` mode; Then no log files exist.

##### test_api_log_rotation.py
1. Given that the configured format is `json`, and the level is set to `info`, and the `wazuh-apid` is started; When the machine time is `midnight`; Then the json log file is rotated.
2. Given that the configured format is `plain`, and the level is set to `info`, and the `wazuh-apid` is started; When the machine time is `midnight`; Then the log file is rotated.
3. Given that the configured format is `json,plain`, and the level is set to `info`, and the `wazuh-apid` is started; When the machine time is `midnight`; Then both log files are rotated.

**Comment by mauromalara** [comment]
Working branch: [2580-dev-support-api-json-log](https://github.com/wazuh/wazuh-qa/compare/2580-dev-support-api-json-log)

**Comment by mauromalara** [comment]
The tests mentioned above have different approaches, so we decided to separate them into 2 different issues: the current one and issue #2636.
