### ISSUE TITLE
ST - Timeout in `test_agent_enrollment`

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2581]
## Description

While testing #2557, we could see that `test_cluster/test_agent_enrollment` was failing randomly because it couldn't find some logs. I attach some examples:

| | Result | Notes|
|:--:|:--:|:--:|
|R1|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8087772/R1-test-agent-enrollment.zip) | |
|R2|[🔴 ](https://github.com/wazuh/wazuh-qa/files/8087776/R2-test-agent-enrollment.zip) | |
|R3|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8087779/R3-test-agent-enrollment.zip)| |
|R4|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8087782/R4-test-agent-enrollment.zip) | |
|R5|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8087784/R5-test-agent-enrollment.zip)| |
|R6|[🔴 ](https://github.com/wazuh/wazuh-qa/files/8087786/R6-test-agent-enrollment.zip) | |
|R7|[🟢 ](https://github.com/wazuh/wazuh-qa/files/8087789/R7-test-agent-enrollment.zip)| |
|R8| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8087792/R8-test-agent-enrollment.zip)| |
|R9| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8087793/R9-test-agent-enrollment.zip)| |

After some debugging, we could see that the log was being produced, but it took more than 60 seconds to appear since the last log found.

### Example
 
The log `.*Processing file etc\/client\.keys.*` should appear after `.*Agent key generated for.*` log appeared. We can see that the first log appeared and was found by the test:

```
DEBUG    root:monitoring.py:432 2022/02/17 10:28:05 wazuh-authd[38613] main-server.c:651 at run_dispatcher(): INFO: Agent key generated for 'wazuh-agent1' (requested by any)

DEBUG    root:monitoring.py:434 MATCH 2022/02/17 10:28:05 wazuh-authd[38613] main-server.c:651 at run_dispatcher(): INFO: Agent key generated for 'wazuh-agent1' (requested by any)

DEBUG    wazuh_testing:monitoring.py:980 Finishing QueueMonitor for wazuh-worker1 and message: .*Agent key generated for.*
```
If we check `/var/ossec/logs/cluster.log`, we can see that the expected log appeared, but it took more than one minute.

```
2022/02/17 10:30:26 DEBUG2: [Worker wazuh-worker1] [Integrity sync] Processing file etc/client.keys
```

## To do

We have to check if it is normal for the log to take more than a minute to appear. If so, we can increase the timeout, if not, we will have to investigate what may be happening.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
