### ISSUE TITLE
IT FIM: Check 'max_fd_win_rt' behaviour

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#2585]
# Description

While analyzing the skipped test `test_inotify/test_max_fd_rt.py:test_max_fd_win_rt`, it was found that a refactor is necessary, for that we will define a series of basic cases to test.

#### Local_internal_options

> syscheck.debug=2
> agent.debug=2
> monitord.rotate_log=0
> windows.debug=2

--- 

## Case 1: Check default configuration behaviour (max_fd_win_rt = 256)

**Given** ossec.conf with realtime/whodata="yes" :   <directories realtime="yes">/test1 - test256</directories>
**And** the agent is restarted
**When** the 256 configured folders are created
**Then** we verify on ossec.log shows the 256 "Directory added for realtime/whodata ..." events

---

### T(0): max_fd_win_rt = 1 and 1 folder created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1</directories>
**And** max_fd_win_rt is set to 1 in `local_internal_options`
**And** the agent is restarted
**When** the 1 configured folder is created
**Then** we verify on ossec.log shows the  "Directory added for realtime/whodata ..." event

### T(0): max_fd_win_rt = 1024 and 1024 folder created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1</directories>
**And** max_fd_win_rt is set to 1024 in `local_internal_options`
**And** the agent is restarted
**When** the 1024 configured folder are created
**Then** we verify on ossec.log shows the 1024  "Directory added for realtime/whodata ..." events

### T(1): max_fd_win_rt = 1 and 2 folders created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1 /test2</directories>
**And** max_fd_win_rt is set to 1 in `local_internal_options`
**And** the agent is restarted
**When** the 2 configured folder are created
**Then** we verify on ossec.log shows 1 folder  "Directory added for realtime/whodata ..." event 

### T(1): max_fd_win_rt = 1024 and 1025  folders created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1 - /test1025</directories>
**And** max_fd_win_rt is set to 1024 in `local_internal_options`
**And** the agent is restarted
**When** 1025 configured folders are created
**Then** we verify on ossec.log shows 1024 folder  "Directory added for realtime/whodata ..." event 

### T(1): max_fd_win_rt = 10 and 5  folders created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1 - /test5</directories>
**And** max_fd_win_rt is set to 10 in `local_internal_options`
**And** the agent is restarted
**When** 5 configured folders are created
**Then** we verify on ossec.log shows 5 folder  "Directory added for realtime/whodata ..." events 

---

### T(0): max_fd_win_rt = 0 and 1 folders created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1 </directories>
**And** max_fd_win_rt is set to 0 in `local_internal_options`
**And** the agent is restarted
**When** the 1 configured folder is created
**Then** we verify on ossec.log shows the actual minimum default folders to monitor.

### T(0): max_fd_win_rt = 1025 and 1026 folders created: 

**Given** `ossec.conf` with realtime/whodata="yes" :   <directories realtime="yes">/test1 - /test1026 </directories>
**And** max_fd_win_rt is set to 1 in `local_internal_options`
**And** the agent is restarted
**When** the 1026 configured folder are created
**Then** we verify on ossec.log shows the actual maximum default folders to monitor.

----------------

#### DoD

- [ ] Each test handles it's own configuration in local_internal_options
- [ ] Each test must run on Realtime and Whodata
- [ ] Each test must run on Windows.
- [ ] Each one must be tested folder creation, deletion and renaming.

**Comment by damarisg** [comment]
We decided to close them.
