### ISSUE TITLE
Test new API method feature: enable ordering by agents count in /groups method

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-qa#2603]
Related to issue https://github.com/wazuh/wazuh/issues/12432 and the issue https://github.com/wazuh/wazuh-kibana-app/issues/3819 we need to check whether this change behaves appropriately. 

We need to check whether the method `/groups` with the sort field to `count` produces a sorted list of groups by the agent count instead of an error. Currently, sorting is only possible by the field `name`.

**Comment by davidjiglesias** [comment]
To be done in https://github.com/wazuh/wazuh/issues/12432
