### ISSUE TITLE
Test new Core functionality: agent configuration sync status present in global.db

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-qa#2604]
Related to the issues:
 - https://github.com/wazuh/wazuh-kibana-app/issues/3402
 - https://github.com/wazuh/wazuh/issues/9334
 - https://github.com/wazuh/wazuh/issues/12361

We need to design a way to test whether the status of the synchronization of the agent configuration is in `global.db`. The functional design is being worked on by the teams assigned to the issues.

**Comment by damarisg** [comment]
We decided to close them.
