### ISSUE TITLE
Research possible bug in QueueMonitor

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2609]
### Description

In https://github.com/wazuh/wazuh-qa/pull/2435 development, some system test fails in the @juliamagan environment. Using the debug verbose we find out that infrequently, the QueueMonitor does not read correctly the temporal log file, resulting in the failing of the tests, even if the logs have been produced in the hosts.

Further investigation is precise to ensure the precision of the system tests.

**Comment by damarisg** [comment]
We decided to close them.
