### ISSUE TITLE
VD test: Add Windows Server 2022 and Windows 11 cases

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2632]
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/12472|
|https://github.com/wazuh/wazuh/issues/12444|

## Description

For 4.3, support has been added for two new versions of Windows: **Windows Server 2022** and **Windows 11**. 

Support for _WS2022_ was added in the next PR: https://github.com/wazuh/wazuh/pull/10168, but apparently they have stopped supporting the previously created CPE and a fix had to be applied to avoid creating false negatives (https://github.com/wazuh/wazuh/pull/12482).
And support for _W11_, has been added in the next PR: https://github.com/wazuh/wazuh/pull/12446

In QA there are ITs that test the correct generation of the CPE for each supported Windows version ([test_cpe_indexing](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_vulnerability_detector/test_windows/test_cpe_indexing.py)). So it would be necessary to modify the test to add these two new cases.

## Objective

The objective is to check that the CPEs are generated correctly.

## Technical specifications

For the case of `Windows 11`, the field that should be checked would be the `product`, changing it to `windows_11` and obtaining the `version` that the agent has in the DB.
Ex: `o:microsoft:windows_11:21h2::::::x64:`

The case of `Windows Server 2022` is a bit more complicated, due to the fact that two CPEs are generated for this agent, so it is necessary to check that both are created correctly.
- The first one is simple, modify the `product` to match with `windows_server_2022`, using the `version` that is available in the DB. 
Ex: `o:microsoft:windows_server_2022:21h2::::::x64:`

- While the second one, you use as product: `windows_server`, and in the `version` field use: `2022`. And in the next field (`update`), there should be either the version of the DB, or it should be empty.
Ex: `o:microsoft:windows_server:2022:21h2:::::x64:`

**Comment by roronoasins** [comment]
# Cases
- TCase with `windows_11` as name:
```
2022/03/11 11:16:18 wazuh-modulesd:vulnerability-detector[17474] wm_vuln_detector.c:6186 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_11:::::::x64:' from the agent '001' was indexed.
```
- TCase with `windows_server_2022` as name:
```
2022/03/11 11:17:30 wazuh-modulesd:vulnerability-detector[18166] wm_vuln_detector.c:6186 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_server_2022:::::::x64:' from the agent '001' was indexed.
2022/03/11 11:17:30 wazuh-modulesd:vulnerability-detector[18166] wm_vuln_detector.c:6186 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_server:2022::::::x64:' from the agent '001' was indexed.

```
- TCase with `windows_server` as name:
```
2022/03/11 11:17:38 wazuh-modulesd:vulnerability-detector[18240] wm_vuln_detector.c:6186 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_server_2022:::::::x64:' from the agent '001' was indexed.
2022/03/11 11:17:38 wazuh-modulesd:vulnerability-detector[18240] wm_vuln_detector.c:6186 at wm_vuldet_insert_agent_data(): DEBUG: (5446): The CPE 'o:microsoft:windows_server:2022::::::x64:' from the agent '001' was indexed.
```
# Run sample
```
======================================== test session starts =========================================
platform linux -- Python 3.6.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /mnt/qa/tests/integration, configfile: pytest.ini
plugins: metadata-1.11.0, testinfra-5.0.0, html-3.1.1
collected 18 items                                                                                   

test_vulnerability_detector/test_feeds/test_cpe_indexing.py ..................                 [100%]

=================================== 18 passed in 142.34s (0:02:22) ===================================
```
