### ISSUE TITLE
Update functions and tests after agent-groups changes

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#2643]
Now all group assignment information is stored only in `global.db`. Agent-groups files (`/var/ossec/queue/agent-groups/`) no longer exist after changes made in: 
- https://github.com/wazuh/wazuh/issues/10771

As a result, it is important to review and update all those functions and tests that interacted with `queue/agent-groups/`. It includes these files:
- [ ] [**add_agents_to_default_group**](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/add_agents_to_default_group.py): This script writes to the agent-groups files.
- [ ] [**test_authd_agents_ctx**](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_authd/test_authd_agents_ctx.py): 
  - [ ] Files are created or deleted inside `queue/agent-groups/` (on lines [136](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/integration/test_authd/test_authd_agents_ctx.py#L136), [172](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/integration/test_authd/test_authd_agents_ctx.py#L172))
  - [ ] Update docstrings.

There are some system tests which also need to be updated ([test_integrity_sync](https://github.com/wazuh/wazuh-qa/blob/master/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py), [test_agent_files_deletion](https://github.com/wazuh/wazuh-qa/blob/master/tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py)), but that's already being done in https://github.com/wazuh/wazuh-qa/issues/2479.

**Comment by damarisg** [comment]
Duplicated by [IT Authd/Wazuh DB: Refactor for failures caused by new development of Wazuh DB.](https://github.com/wazuh/wazuh-qa/issues/2584)
