### ISSUE TITLE
Fix Agentd IT:  `test_agentd_multi_server`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2671]
### Description

The agentd integration tests fail for the 4.4.0 branch. The affected test is `test_agentd_multi_server` in all its cases.
```
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[refuse_remoted_accept_enrollment]
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[only_enrollment_and_only_remoted]
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[server_down_fallback_tcp]
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[server_down_fallback_udp]
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[only_one_server_available]
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[unique_available_server_disconnects]
```

**Build**: https://devel.ci.wazuh.info/job/Test_integration/1281/

These errors have appears after the merge of the [IPV6 connection support](https://github.com/wazuh/wazuh-qa/pull/2435).
The detection of these not earlier due to agentd and logcollector tests are not included in [PR Wazuh and Nightly](https://github.com/wazuh/wazuh-jenkins/pull/3354).

### To Do

Change current callback
```
Trying to connect to server (testServer1/127.0.0.1:1514)
```

to

```
Trying to connect to server ([testServer1/127.0.0.1]:1514/udp).
```

**Comment by juliamagan** [comment]
We will need to refactor this test in the future because of:
https://github.com/wazuh/wazuh-qa/blob/4bc41378503fe0a12d6c2b99ec7fe2c1770b10d1/tests/integration/test_agentd/test_agentd_multi_server.py#L162
This log appears randomly. If it doesn't appear, we will find the following log:
```
Server unavailable. Setting lock.
```
