### ISSUE TITLE
Test the fixes introduced in the validation and copying of group subfolders.

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-qa#2681]
| Related issue |
|---|
| wazuh/wazuh#8593 |

## Description
The `wazuh-remoted` daemon had a problem when adding subfolders to group configs, for example `etc/shared/{group-name}/subfolder`, these `subfolders` were not copied when a `multigroup` was generated, which caused the `agent` not to receive those `files`. Additionally, if an` invalid (binary) file` was added into a subfolder and the group did not belong to a multigroup, the `merged.mg` file was created and the invalid file was wrongly included.

This PR includes a solution that fixes this issue: [wazuh/wazuh/#12516](https://github.com/wazuh/wazuh/pull/12516)

To prevent this from happening again in the future, it is necessary to create tests. These are the requirements to take into account:

- Create subfolder in groups folders and add valid and invalid files.
- Create multigroups.
- The multigroup folder must contain the subfolder and only the valid files.
- The agent should receive the merged.mg file with the subfolder and only the valid files.
- The maximum size of a group file path is 200 characters `(etc/shared/group-name/subfolder/file)`.

**Comment by damarisg** [comment]
We decided to close them.
