### ISSUE TITLE
Vulnerability detector test: Vulnerability scan correlation feeds

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2690]
When a vulnerability scan is launched, it is used several sources to decide if a package/system is vulnerable or not. In this case, the NVD and provider feed are used.

The objective of this issue is to test the expected behavior when the provider and NVD feed contradict each other or contain different information.

It is requested to carry out a study on the possible combinations and to develop a testing module for checking the different combinations between provider and NVD feeds.

**Comment by davidjiglesias** [comment]
Obsolete as there is a VD refactor in the works.
