### ISSUE TITLE
Report Generator: Customize report using deployment configuration file

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2709]
| Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/2694 |

### Description

The report generator tool allows the creation of a JSON file that describes the environment during its uptime. However, it does not allow customize the report for different phases of the environment. This is required for automatizing stress test results https://github.com/wazuh/wazuh-qa/issues/2694.

### To Do
The report generation tool should accept two variables:
- **Artifact path**: Currently developed
- **Configuration file**: JSON or YAML file, in which it will describe several factors to generate the report. Some of the following: 
    - Different environment phases
    - Group of hosts to take into account in the report

**Comment by Rebits** [comment]
### 22/03/2022

In order to test this new report feature with `test_stress` results, currently, the different phases of the environment are calculated in https://github.com/wazuh/wazuh-jenkins/blob/28436ad4ebf1cbb01e7929b8bbb7a8be23384d5b/quality/python-packages/jenkins_utils/jenkins_utils/graphics_generator.py#L226
These should be included in the configuration file including that logic into the pipeline, making that function more versatile.

Also, in the future, it should be recommended to unified the Jenkins tool  with [data visualization](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/data_visualizations.py) QA tool

**Comment by juliamagan** [comment]
Development branch: [2709-report-generator-conf-file](https://github.com/wazuh/wazuh-qa/tree/2709-report-generator-conf-file)
