### ISSUE TITLE
Fix QACTLConfigGenerator: Adapt IP generation to new VirtualBox validations

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2710]
| Related issue |
|--- |
| https://github.com/wazuh/wazuh-qa/issues/2482, https://github.com/wazuh/wazuh-qa/issues/2231 |

### Description

QACTL task feature created for https://github.com/wazuh/wazuh-qa/issues/2482 development needs to be adapted in order to follow new [VirtualBox validation to host-only networks](https://github.com/hashicorp/vagrant/pull/12564).

I suggest replacing https://github.com/wazuh/wazuh-qa/blob/e36cf487667e77994a54b892045be805c32703f9/deps/wazuh_testing/wazuh_testing/qa_ctl/configuration/config_generator.py#L246
by 
```
HOST_NETWORK = '192.168.56.x'

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
