### ISSUE TITLE
FIM IT: Skip unstable tier 2 tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2711]
| Related issue|
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2174 |

### Description
After talking with @damarisg, it seems that tier 2 FIM tests are unstable. However, some of them are not skipped, for example, `test_validate_win32_analysisd_registry_alerts.py`. 

Due to the [new inclusion of this tier into the nightly pipeline](https://github.com/wazuh/wazuh-jenkins/issues/3357), it is required to temporally skip every unstable test.

**Comment by damarisg** [comment]
This issue does not affect the `FIM tests` so the _title does not apply_. 
This issue affects the TIER 2 _ANALYSISD integration tests_.
After looking at the last runs of our **Nightly**, we can see that this test is not failing, so this issue will be closed and we decide not to skip the test.
