### ISSUE TITLE
System test optimization: Reuse of common provisioning environments

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2720]
To optimize the cost of launching system tests, you want to be able to reuse the same provisioning environments so that you can launch all tests using the same environment without having to deploy an instance for each test.

For example, given the following information:

```
[
    'agentless_cluster': [
            'test_jwt_invalidation/test_change_rbac_mode.py',
            'test_jwt_invalidation/test_change_security_resources.py',
            'test_jwt_invalidation/test_disconnected_nodes.py',
            'test_jwt_invalidation/test_revoke_endpoint.py',
            'test_jwt_invalidation/test_update_password.py',
            'test_cluster/test_agent_info_sync/test_integrity_sync.py'
    ],
    'basic_cluster': [
        'test_cluster/test_agent_files_deletion/test_agent_files_deletion.py',
        'test_cluster/test_agent_info_sync/test_agent_info_sync.py',
        'test_cluster/test_agent_key_polling/test_agent_key_polling.py'
    ],
    'basic_environment': [
        'test_agent_auth/test_agent_auth.py',
        'test_enrollment/test_integrity_sync.py'
    ],
    'enrollment_cluster': [
        'test_cluster/test_agent_enrollment/test_agent_enrollment.py'
    ],
    'manager_agent': [
        'test_active_response_log_format/test_active_response_log_format.py'
    ],
    'one_manager_agent': [
        'test_fim/test_files/test_files_cud.py',
        'test_fim/test_synchronization/test_synchronization.py'
    ]
]
```

If we wanted to launch all the system tests, we would have to create **15 instances** (1 for each test). However, if we group the tests by provisioning types, we would only need to deploy **6 instances** (1 per provisioning group).

At the moment, it is not possible to do this, since after launching a test the environment is not completely clean for the execution of the next one.

It is requested to review these cases and to modify the necessary in the system tests so that all tests can be launched reusing provisioning environments.

**Comment by roronoasins** [comment]
Many tests such as `jwt` let the cluster connection break after service restart on each test run.
This issue will be avoided in the system tests refactor.

We have to make sure that the environment is kept clean and capable of being reused by each Tcase for each test and module.
