### ISSUE TITLE
Improvement and integration of reliability tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2780]
## Description

Once #2241 was closed, we realized that we could add some improvements and integrate the reliability tests to the weekly correctly. The pending issues to close this development are:

- https://github.com/wazuh/wazuh-qa/issues/2709
- https://github.com/wazuh/wazuh-jenkins/issues/3421
- https://github.com/wazuh/wazuh-jenkins/issues/3418
- https://github.com/wazuh/wazuh-jenkins/issues/3407

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
