### ISSUE TITLE
GCloud IT: Parallel testing induces false positives

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2783]
### Description
Google Cloud integration tests required the credentials of the GCP QA account. This account is used for all the testing modules, of the suite.
If multiple testing processes launch these tests parallelly, it will produce false positives:
- [R1](https://ci.wazuh.info/job/Test_integration/25006/console) - :red_circle: 
- [R2](https://ci.wazuh.info/job/Test_integration/25007/console) - :red_circle:

**Comment by damarisg** [comment]
We decided to close them.
