### ISSUE TITLE
Logcollector IT: Create time change tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2784]
### Description

A [bug]( https://github.com/wazuh/wazuh/issues/12923) has been detected in the Wazuh agents that caused the logcollector to become unusable after a time change. It is required to create a test to detect all possible anomalous behavior when a time change is performed.

### Test description
- **OS**:  **Windows, Linux, Solaris, macOS**
- **Tier**: 0
- **Cases**: Applied to syslog, macOS (4.3 and forward) and eventchannel `log_format` option when proceed
   - Change to a later date and then to an earlier date
   - Change to a later time and then to an earlier time
   - Change to an earlier date and then to a later date
   - Change to an earlier time and then to a later time
   - Change to a different time zone. For example
      - `Africa/Abidjan`
      -  `Pacific/Midway`
      - `America/El_Salvador`
      - `Asia/Dhaka`
      - `Australia/Lord_Howe`
      - `Europe/Helsinki`

  
#### Syslog format
- Add the following configuration block to the agent configuration
```
  <localfile>
    <log_format>syslog</log_format>
    <location>TESTING_LOG</location>
  </localfile>

```
- Add the following `local_internal_option`:
```
logcollector.debug=2
```
- Restart the agent
- Perform date/time/timezone changes
- Insert a custom message in the `TESTING_LOG` file
- Ensure the logcollector gather the event by checking the `ossec.log` file

I need to consider the [reconnect_time](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#reconnect-time
) option 
#### Eventchannel format
- Use the default Windows configuration
- Perform date/time/timezone changes
- Generate a eventchannel Application event in the agent
- Ensure the logcollector gather the event by checking the `ossec.log` file

#### macos format
- Add the following configuration block to the agent:
```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="log,trace" level="debug">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>
```
- Restart the agent
- Perform date/time/timezone changes
- Generate macOS log events
- Ensure the logcollector gathers the event by checking the `ossec.log` file

**Comment by damarisg** [comment]
We decided to close them.
