### ISSUE TITLE
IT Wazuh DB: Deprecate unused wazuh-db helpers and commands

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2786]
## Description

After working on [Migrate agent-group files to wazuh-db](https://github.com/wazuh/wazuh/issues/10771), some wazuh-db helpers are not used.
This issue requires checking if  the wazuh-db commands called by the helpers are deprecated.

| Related to |
|--|
| https://github.com/wazuh/wazuh/issues/12356 |

Notes: 
 - The PR that contains the core changes is [here](https://github.com/wazuh/wazuh/pull/12370/files#diff-6dbb9b99c36aeb7ad12f1c4866794c9d22f02ba8388899804fbc698d51b50e2d). 
- You can find the commands deprecated on `src/wazuh_db/wdb_parser.c` file.

## To do

- [x] Check tests affected.
- [x] Remove tests affected.

**Comment by Deblintrake09** [comment]
# Task 1 - Check affected tests
Changes need to be applied to the `global_messages.yaml` that specifies the test cases for the `set-labels` and `select-keepalive` globaldb commands.

**Comment by Deblintrake09** [comment]
# Task 2 - Remove affected tests
- removed the deprecated test cases
- need to generate packages for testing, but branch needs rebasing
- Moved issue to On Hold until branch is rebased
