### ISSUE TITLE
Release 4.3.0 - Manual tests - Wazuh UI (Demo environment)

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2795]
| Wazuh Version | Wazuh App Revision | Browser |
|:--:|:--:|:--:|
|v4.3.0-rc6|4301-1|Firefox|

We want to perform a manual test on the Wazuh App to check its correct behavior in demo environments.

## Estimated tasks

- [x] (**T1**): Create a list of different test cases 
- [x] (**T2**):  Manual testing

## Conclusion 🟡 

While performing the tests found [here](https://docs.google.com/spreadsheets/d/1HlIK7cbvPIUmVlc7qwCSmGWAkURuQHL4qlSWNBkf1Kk/edit?usp=sharing), we have encountered some problems, for which the following issues have been opened. In addition, they can be viewed sorted by severity [here](https://github.com/wazuh/wazuh-qa/issues/2795#issuecomment-1105099043).

### Open issues

- https://github.com/wazuh/wazuh-kibana-app/issues/4050
- https://github.com/wazuh/wazuh-kibana-app/issues/4051
- https://github.com/wazuh/wazuh-kibana-app/issues/4052
- https://github.com/wazuh/wazuh-kibana-app/issues/4048
- https://github.com/wazuh/wazuh-kibana-app/issues/4057
- https://github.com/wazuh/wazuh-kibana-app/issues/4058
- https://github.com/wazuh/wazuh-kibana-app/issues/4044
- https://github.com/wazuh/wazuh-kibana-app/issues/4045
- https://github.com/wazuh/wazuh-kibana-app/issues/4046
- https://github.com/wazuh/wazuh-kibana-app/issues/4047
- https://github.com/wazuh/wazuh-kibana-app/issues/4056
- https://github.com/wazuh/wazuh-kibana-app/issues/4059
- https://github.com/wazuh/wazuh-kibana-app/issues/4060
- https://github.com/wazuh/wazuh-kibana-app/issues/4061
- https://github.com/wazuh/wazuh-kibana-app/issues/4062
- https://github.com/wazuh/wazuh-kibana-app/issues/4064
- https://github.com/wazuh/wazuh-kibana-app/issues/4065
- https://github.com/wazuh/wazuh-kibana-app/issues/4067
- https://github.com/wazuh/wazuh-kibana-app/issues/4069
- https://github.com/wazuh/wazuh-kibana-app/issues/4071
- https://github.com/wazuh/wazuh-kibana-app/issues/4072
- https://github.com/wazuh/wazuh-kibana-app/issues/4073
- https://github.com/wazuh/wazuh-kibana-app/issues/4077
- https://github.com/wazuh/wazuh-kibana-app/issues/4078
- https://github.com/wazuh/wazuh-kibana-app/issues/4081
- https://github.com/wazuh/wazuh-kibana-app/issues/4082
- https://github.com/wazuh/wazuh-kibana-app/issues/4083
- https://github.com/wazuh/wazuh-kibana-app/issues/4049
- https://github.com/wazuh/wazuh-kibana-app/issues/4086
- https://github.com/wazuh/wazuh-kibana-app/issues/4087
- https://github.com/wazuh/wazuh-kibana-app/issues/4088
- https://github.com/wazuh/wazuh-kibana-app/issues/4089
- https://github.com/wazuh/wazuh-kibana-app/issues/4090
- https://github.com/wazuh/wazuh-kibana-app/issues/4091
- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-kibana-app/issues/4093
- https://github.com/wazuh/wazuh-kibana-app/issues/4095
- https://github.com/wazuh/wazuh-kibana-app/issues/4094

**Comment by mauromalara** [comment]
# Update: 19/04/2022

I test 44 test cases, 5 test cases left to finish with the Management module.

I added a couple of tests in the Ruleset section (excel).

**Comment by BelenValdivia** [comment]
**2022/04/19**
- I added some tests in filter checks 
- Finished query bar tests
-Almost finished filter tests

**Comment by juliamagan** [comment]
## Task 1: Test cases

We have created the following test cases for manual testing:

[Test cases list](https://docs.google.com/spreadsheets/d/1HlIK7cbvPIUmVlc7qwCSmGWAkURuQHL4qlSWNBkf1Kk/edit?usp=sharing)

**Comment by BelenValdivia** [comment]
2022/04/19

- Tests finished:
1. Filter checks
2. Visualizations
3. Events related checks
4. Overview ui
5. Reporting

**Comment by jmv74211** [comment]
## Classification of reported issues according to severity

| Issue | Type | Component | Reported by | Severity (1-10) | Description | 
|-------|------|-----------|-------------|-----------------|-------------|
|https://github.com/wazuh/wazuh-kibana-app/issues/4073|Unexpected behavior | App | Julia | 8 | Permission errors when trying to change wazuh app options.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4071| Unexpected error | App | Mauro | 7 | Error when changing Wazuh configuration for the first time |
|https://github.com/wazuh/wazuh-kibana-app/issues/4052|Unexpected behavior | App | Julia | 6 | Unable to access security events after filtering by time range| 
|https://github.com/wazuh/wazuh-kibana-app/issues/4046| Error message | App | Mauro | 6 | After restarting the cluster and changing the environment, an error appears in the log display view. |
| https://github.com/wazuh/wazuh-kibana-app/issues/4047| Unexpected behavior | App | Mauro | 5 | When displaying the content of a ruler and pressing the back button redirects to the wrong view.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4051|Unexpected behavior | App | Julia | 5 | When selecting text in the API console it becomes unreadable.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4059|Missing info to the user| App | Mauro | 4 | When uploading an empty rule file, error 500 is generated and the user is not warned. | 
|https://github.com/wazuh/wazuh-kibana-app/issues/4050|Improvement proposal | App | Julia | 4 | Suggest required parameters when using an endpoint in the API console |
|https://github.com/wazuh/wazuh-kibana-app/issues/4069|Unexpected behavior | App | Belén | 3 |Pressing the back button does not take you to the previous view (event stack).|
|https://github.com/wazuh/wazuh-kibana-app/issues/4045| Missing element | App | Mauro | 3 | A filter cannot be deleted. The button does not appear. |
|https://github.com/wazuh/wazuh-kibana-app/issues/4048|Unexpected behavior| App | Belén | 3 | 'Back to top' button in alert display does not work correctly. |
|https://github.com/wazuh/wazuh-kibana-app/issues/4057|Visualization improvement | App | Belén | 3 | The popover is cut off when the mouse approaches the end of the graphic.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4060|Missing info to the user| App | Mauro | 3 | No load spinner is displayed to show the action of exporting the rules.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4061| Unexpected behavior | App | Mauro | 3 | The environment option is not updated when switching from another tab, until the page is reloaded. |
| https://github.com/wazuh/wazuh-kibana-app/issues/4062|Unexpected behavior| App | Mauro | 3 | When removing a group for an agent, the group continues to appear in the list until the view is reloaded.|
|https://github.com/wazuh/wazuh-kibana-app/issues/4056| Missing info to the user | App | Mauro | 2 | Alert the user when uploading a rules file that already exists |
|https://github.com/wazuh/wazuh-kibana-app/issues/4064|Invalid element|App |Mauro | 2 | Wrong icon when modifying group files |
|https://github.com/wazuh/wazuh-kibana-app/issues/4058|Visualization improvement | App | Belén | 2 | Delete the red line at the end of the graph|
|https://github.com/wazuh/wazuh-kibana-app/issues/4072|Unexpected behavior | App | Julia | 2 | Agent table is not sorted correctly using IP as filter |
|https://github.com/wazuh/wazuh-kibana-app/issues/4044| Typo  | App | Mauro | 1 | Typo in `Date add` |
|https://github.com/wazuh/wazuh-kibana-app/issues/4065|Improvement proposal |App |Mauro | 1 | Option to deselect all is not useful in a particular case | 
|https://github.com/wazuh/wazuh-kibana-app/issues/4067|Improvement proposal |App |Mauro | 1 | Separate OS information into several fields |
