### ISSUE TITLE
System tests: AMI and ECR creation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2800]
| Related issues| 
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2787 |

### Description
As part of https://github.com/wazuh/wazuh-qa/issues/2788, is required to research current AMIS and ECR for system tests.
In case of no suite instances, we need to create custom ones, in order to allow launch system tests.

### Tasks
- [ ] #2827
- [ ] #2828

**Comment by roronoasins** [comment]
Issue moved to [wazuh/wazuh-jenkins #3512](https://github.com/wazuh/wazuh-jenkins/issues/3512) via [**ZenHub**](https://www.zenhub.com/)
