### ISSUE TITLE
Remoted IT: Nightly report - Tier 0 - `test_invalid_protocol_communication fail`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2812]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/2811| 

| **Date** |  **Commit** | Build | Notes |
| --- | --- |--- | --- |
| 2022-04-21 | 552a428 | https://ci.wazuh.info/job/test_nightly/1011/console/ | Build error https://github.com/wazuh/wazuh-jenkins/issues/3464|

# Test_agent_communitcation
### UDP_1514

```
test_remoted/test_agent_communication/test_invalid_protocol_communication.py:204: in test_invalid_protocol_communication
    validate_agent_manager_protocol_communication(sender_protocol, manager_port)
test_remoted/test_agent_communication/test_invalid_protocol_communication.py:121: in validate_agent_manager_protocol_communication
    rd.wait_to_remoted_key_update(wazuh_log_monitor)
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/remote.py:480: in wait_to_remoted_key_update
    check_remoted_log_event(wazuh_log_monitor, callback_pattern, error_message, timeout=20)
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/remote.py:434: in check_remoted_log_event
    error_message=error_message
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:203: in start
    error_message=error_message).result()
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError: Could not find the remoted key loading log
 -----------------------------Captured stdout setup------------------------------ 
2022-04-21T00:50:22.1650502222
```

### UDP_56000

```
test_remoted/test_agent_communication/test_invalid_protocol_communication.py:204: in test_invalid_protocol_communication
    validate_agent_manager_protocol_communication(sender_protocol, manager_port)
test_remoted/test_agent_communication/test_invalid_protocol_communication.py:121: in validate_agent_manager_protocol_communication
    rd.wait_to_remoted_key_update(wazuh_log_monitor)
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/remote.py:480: in wait_to_remoted_key_update
    check_remoted_log_event(wazuh_log_monitor, callback_pattern, error_message, timeout=20)
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/remote.py:434: in check_remoted_log_event
    error_message=error_message
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:203: in start
    error_message=error_message).result()
/usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError: Could not find the remoted key loading log
 -----------------------------Captured stdout setup------------------------------ 
```

**Full report**: [manager_html_report_Test_integration_B25282_20220421013554.zip](https://github.com/wazuh/wazuh-qa/files/8529838/manager_html_report_Test_integration_B25282_20220421013554.zip)
**Build**: https://ci.wazuh.info/job/Test_integration/25282/

**Comment by CamiRomero** [comment]
The reason of the failures of these test was that can't connect to 'queue/sockets/queue'. All the test in module `remoted` is running with the last version of Wazuh and we can note that the error does not occur.

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | remoted | Manager | [Packages](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.5.0-0.40500.20220518.x86_64.rpm) | CentOS-8 |
## Tests Results

| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
|  test/integration/test_remoted | CentOS - Manager | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8730483/R1.tar.gz)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8730485/R2.tar.gz)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8730487/R3)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8730488/R4.tar.gz)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8730490/R5.tar.gz)|  |  @CamiRomero  |

**Comment by damarisg** [comment]
Wazuh version|Component|Install type | Package Version | Platform|
|---|---|---|---|---|
| 4.5.0 | Remoted | Manager |  [20220519](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.5.0-0.40500.20220519.x86_64.rpm) | CentOS-8 |

## Tests Results

| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
|  test/integration/test_remoted | CentOS - Manager | Local | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26631/)[:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/26632/)| 2022/05/20 |  Seyla | 

This issue is closed because we can't reproduce this bug.
