### ISSUE TITLE
Integration tests for Vulnerability Detector: Amazon Linux 2022 support

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2813]
### Description

This issue is part of wazuh/wazuh#13034

We will include support for the Amazon Linux 2022 OS, including a new feed – ALAS 2022.

The following tests should cover the new supported OS version:

- [Feed tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_vulnerability_detector/test_feeds): These tests have to cover the addition of the new feed for `Amazon Linux 2022`
- [Provider tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_vulnerability_detector/test_providers): Here we will test the settings for `Amazon Linux` with OS version `2022`
- [Scan results tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_vulnerability_detector/test_scan_results): Here we have to add the tests that ensure `Amazon Linux 2022` agents are scanned properly

**Comment by damarisg** [comment]
It will be released in Jenkins when the `CICD` team finalizes https://github.com/wazuh/wazuh-jenkins/issues/3466 that is in charge of the Jenkins pipelines for uploading feeds to both `S3` and production `feed.wazuh`

**Comment by Deblintrake09** [comment]
Move Issue to Blocked because of Jenkins Issue  # https://github.com/wazuh/wazuh-jenkins/issues/3466
