### ISSUE TITLE
Fix test_remoted cases for failures caused by new development of Wazuh DB

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2825]
### Description
Working on [Migrate agent-group files to wazuh-db](https://github.com/wazuh/wazuh/issues/10771), the core team detected that there are affected tests by the new changes.

The objective of this issue is to perform the refactor of each affected test.

**Failure output:**

> FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/036'

### To Do 

- [x] Investigate why the test fails
- [x] Fix each test of Remoted that show any error related to Wazuh_DB

**Comment by CamiRomero** [comment]
## Task 1 - Fix each test of Remoted that show any error related to Wazuh_DB

The changes are in branch `2825_fix_multigroups`.

The changes are: adding an agent to a default groups and a specific group (multigroup) using agent_groups tool

**Comment by CamiRomero** [comment]
## Task  2 - Fix each test of Remoted that show any error related to Wazuh_DB

The changes are in branch `2825_fix_multigroups`.

The changes are: adding an agent to a default groups and a specific group (multigroup) using agent_groups tool
