### ISSUE TITLE
Design of the necessary tests to check the limitation of event processing by `analysisd`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2826]
We want to develop the necessary tests to test the new development related to the limitation of events per second to be processed by `analysisd`.

For this, it is necessary to investigate in depth everything related to such development and design the necessary set of tests to guarantee its correct operation.

More information can be found at the following issue https://github.com/wazuh/wazuh/issues/12696.

**Comment by damarisg** [comment]
We decided to close them.
