### ISSUE TITLE
System tests: Create AMIs for the deployment tool

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2827]
## Description

As we are providing EC2 support(https://github.com/wazuh/wazuh-jenkins/issues/3448) for the new deployment tool development(https://github.com/wazuh/wazuh-qa/issues/2788), we need to have some AMIs for each OS.

This issue aims to have a collection of the AMIs that the tool needs to deploy instances.

## Tasks
- [x] Get a list of the required AMIs to be created
- [ ] Create every AMI

**Comment by fedepacher** [comment]
# Update 2022/04/26

EC2-AMI
------------
Inside EC2 we have Amazon Machine Images (AMIs) that contain entire systems with custom configurations to fill our needs and requirements like (OVAs/VBoxes/...).

The first approach to a list of AMIs that we may need in a near future is the following:

* Ubuntu
     * Jammy-20220101
* Centos
     * 8
* Debian
     * 11
* Solaris
     * 11
* Macos
     * 12
* Winserver
     * 2019
* Redhat
     * 8
* Amazon Linux 
     * 2
 
 In the case in the future we need any other AMI, it will be added to the list and it will be created.

**Comment by roronoasins** [comment]
Issue moved to [wazuh/wazuh-jenkins #3513](https://github.com/wazuh/wazuh-jenkins/issues/3513) via [**ZenHub**](https://www.zenhub.com/)
