### ISSUE TITLE
E2E tests for demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2830]
We want to add a new E2E test suite for demo environments. To achieve this, we will perform the following estimated tasks:

## Preparatory tasks

- [x] #2831
- [x] #2832

## Development tasks

- [x] #2872
- [x] #3142
- [x] #3144
- [x] #2983
- [x] #3156
- [x] #3165 
- [x]  #3187 
- [x] #3166
- [x] #3193
- [x] #3274
- [x] #3275

**Comment by damarisg** [comment]
We decided to close them.
