### ISSUE TITLE
Demo environment research: Design and components

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2831]
We want to know what the demo environment consists of, how it is deployed, what its components are, and what it is intended to be used for.

With the information obtained we will be able to know the requirements for the implementation of the tests for this environment.

## Conclusion

| Instances   |    Wazuh cluster      | AWS characteristics| Characteristics  |
|--------|-----------------|--------|------------|
| Master node | Env 1                 |  t3a.medium              | CPU: 2 - RAM: 4 GB - Amazon Linux release 2 (Karoo) |
| Worker node | Env 1                |   t3a.medium             |  CPU: 2 - RAM: 4 GB - Amazon Linux release 2 (Karoo)|
| Debian Agent |Env 1                |   t3a.micro                 | CPU: 2 - RAM: 1 GB - Debian GNU/Linux 9 |
| RHEL7 Agent | Env 1                |  t3a.medium              | CPU: 2 - RAM: 4 GB - Red Hat Enterprise Linux Server 7.5 |
| Centos Agent | Env 1               |   t3a.micro                 | CPU: 2 - RAM: 1 GB - Centos Linux 7.6 |
| Windows       | Env 1                |   t3a.medium             |  CPU: 2 - RAM: 4 GB - Windows Server 2019|
| Master node  | Env 2                |   t3a.medium             |  CPU: 2 - RAM: 4 GB - Amazon Linux release 2 (Karoo)|
| Amazon agent| Env 2               |   t3a.micro                |   CPU: 2 - RAM: 1 GB - Amazon Linux 2|
| Ubuntu           | Env 2                |   t3a.micro               |   CPU: 2 - RAM: 1 GB - Ubuntu 18.04.2 LTS|
| Splunk            | -----                |   t3a.medium             |  CPU: 2 - RAM: 4 GB - Amazon Linux release 2 (Karoo) |
| Dashboard     | -----                |   t3a.large                  | CPU: 2 - RAM: 8 GB - Amazon Linux release 2 (Karoo)|
| Indexer Bootstrap| -----          |   t3a.large                  | CPU: 2 - RAM: 8 GB - Amazon Linux release 2 (Karoo) |
| Indexer MasterB| -----          |   t3a.large                  | CPU: 2 - RAM: 8 GB - Amazon Linux release 2 (Karoo) |
| Indexer MasterC| -----          |   t3a.large                  | CPU: 2 - RAM: 8 GB - Amazon Linux release 2 (Karoo)|

**Architecture:** https://github.com/wazuh/wazuh-qa/issues/2831#issuecomment-1112154142

**Comment by BelenValdivia** [comment]
**27/04**

Researched:
**Wazuh Cluster Env1:**

-Master node
-Worker node

Endpoints:

-Debian: 
         OS: Debian GNU/Linux 9
         cluster node: worker_01

-RHEL7: 
        OS: Red Hat Enterprise Linux Server 7.9
        cluster node: master

-Centos: 
         OS: Centos Linux 7.6
         cluster node: worker_01

-Windows: 
          OS: Windows Server 2019
          cluster node: master
          

**Wazuh Cluster Env2:**

-Master node

Endpoints:

-Amazon: 
        OS: Amazon Linux 2
        cluster node: master

-Ubuntu: 
        OS: Ubuntu 18.04.2 LTS
        cluster node: master 

Indexer cluster:
- indexer node 1
- indexer node 2
- indexer node 3

- Splunk
- Dashboard

**Comment by BelenValdivia** [comment]
Deploy code: https://github.com/wazuh/wazuh-automation/tree/master/aws/demo-environment

**Comment by BelenValdivia** [comment]
Architecture diagram:
![arquitectura demo](https://user-images.githubusercontent.com/26927338/165753863-abee6234-3039-4099-932d-f5dd240543cb.png)
