### ISSUE TITLE
Integration test to verify no solved alert is fired when a package is updated

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#2858]
### Description

The goal of this issue is to create an integration test for Vulnerability Detector that covers the case described at https://github.com/wazuh/wazuh/issues/13354.

Having a vulnerable package, when it is updated and still vulnerable to the same package, no alert should appear reporting that the vulnerability for the older version is solved.

See the related issue for more information.

**Comment by davidjiglesias** [comment]
This issue is obsolete.
