### ISSUE TITLE
Windows 7 error with command to install Wazuh Agent due to PowerShell version

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2869]
# Windows 7 error Wazuh Agent installation

|Related issue|
|------|
| https://github.com/wazuh/wazuh-kibana-app/issues/4085 |          

When you want to add a new `Wazuh-agent` from the `Wazuh-dashboard`, the `Wazuh-dashboard` gives you the following command to install and register the agent in Windows OS:

```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.2.6-1.msi -OutFile ${env:tmp}\wazuh-agent-4.2.6.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.2.6.msi /q WAZUH_MANAGER='192.168.0.81’ WAZUH_REGISTRATION_SERVER='192.168.0.81' WAZUH_AGENT_GROUP='default'
```

Where in this case, the IP **192.168.0.150** is the IP of the manager.

When this command is launched in Windows 7 an error comes up like it is shown in the following picture:

![Screenshot from 2022-05-05 00-09-33](https://user-images.githubusercontent.com/28990973/167143803-bab48820-ab6d-42ea-8d76-605f84b6c35d.png)

By default Windows 7 comes with PowerShell version 2.0 installed. The `Invoke-WebRequest` cmdlet was introduced in PowerShell version 3.0, so the current command to install Wazuh-Agent fails.

**Comment by fedepacher** [comment]
# Update 2022/05/06

## Windows 7 :green_circle:   
- [x] Run command in C:\windows\system32 path
- [x] No errors/warnings in the agent log
- [x] Windows agent service is running
- [x] Windows agent generates alerts
- [x] Agent appear as connected to the manager
- [x] Installation path
- [x] Uninstall process

<details>

### Run command in C:\windows\system32 path

![install_cmd](https://user-images.githubusercontent.com/28990973/167146903-799016eb-480b-4d7c-a30c-176252179d37.png)


### Logs 

[ossec.log](https://github.com/wazuh/wazuh-qa/files/8641198/ossec.log)



### Wazuh service
```
PS C:\Users> Get-Service Wazuhsvc

Status   Name               DisplayName
------   ----               -----------
Running  Wazuhsvc           Wazuh
```

### Agent status

![agent_status](https://user-images.githubusercontent.com/28990973/167147002-2ac3417b-276c-4896-a90e-965354bb788a.png)

```
[root@centos-manager1 vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centos-manager1 (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP-G6KK08C, IP: any, Disconnected
   ID: 004, Name: DESKTOP-9QHFQ7B, IP: any, Disconnected
   ID: 005, Name: IE11WIN8_1, IP: any, Disconnected
   ID: 007, Name: WWJD, IP: any, Active

```

### Alert generation
```
** Alert 1651840327.1202: - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,nist_800_53_AU.14,nist_800_53_AU.5,tsc_CC7.2,tsc_CC7.3,tsc_CC6.8,
2022 May 06 12:32:07 (WWJD) any->wazuh-remoted
Rule: 506 (level 3) -> 'Ossec agent stopped.'
ossec: Agent stopped: 'WWJD->any'.

** Alert 1651840327.1520: - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,nist_800_53_AU.14,nist_800_53_AU.5,tsc_CC7.2,tsc_CC7.3,tsc_CC6.8,
2022 May 06 12:32:07 (WWJD) any->ossec
Rule: 503 (level 3) -> 'Ossec agent started.'
ossec: Agent started: 'WWJD->any'.

```

### Installation path

![install_path](https://user-images.githubusercontent.com/28990973/167193402-2b836072-21fc-4493-9942-21716ccddea4.png)



### Uninstall

![uninstall](https://user-images.githubusercontent.com/28990973/167193434-2fadeb4f-5213-483a-9531-c930243e2901.png)



</details>

**Comment by fedepacher** [comment]
# Update 2022/05/06

## Windows 7 :green_circle:   
- [x] Run command in C:\windows\system32 path
- [x] No errors/warnings in the agent log
- [x] Windows agent service is running
- [x] Windows agent generates alerts
- [x] Agent appear as connected to the manager
- [x] Installation path
- [x] Uninstall process

<details>

### Run command in C:\windows\system32 path

![install_cmd](https://user-images.githubusercontent.com/28990973/167146903-799016eb-480b-4d7c-a30c-176252179d37.png)


### Logs 

[ossec.log](https://github.com/wazuh/wazuh-qa/files/8641198/ossec.log)



### Wazuh service
```
PS C:\Users> Get-Service Wazuhsvc

Status   Name               DisplayName
------   ----               -----------
Running  Wazuhsvc           Wazuh
```

### Agent status

![agent_status](https://user-images.githubusercontent.com/28990973/167147002-2ac3417b-276c-4896-a90e-965354bb788a.png)

```
[root@centos-manager1 vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centos-manager1 (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP-G6KK08C, IP: any, Disconnected
   ID: 004, Name: DESKTOP-9QHFQ7B, IP: any, Disconnected
   ID: 005, Name: IE11WIN8_1, IP: any, Disconnected
   ID: 007, Name: WWJD, IP: any, Active

```

### Alert generation
```
** Alert 1651840327.1202: - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,nist_800_53_AU.14,nist_800_53_AU.5,tsc_CC7.2,tsc_CC7.3,tsc_CC6.8,
2022 May 06 12:32:07 (WWJD) any->wazuh-remoted
Rule: 506 (level 3) -> 'Ossec agent stopped.'
ossec: Agent stopped: 'WWJD->any'.

** Alert 1651840327.1520: - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,nist_800_53_AU.14,nist_800_53_AU.5,tsc_CC7.2,tsc_CC7.3,tsc_CC6.8,
2022 May 06 12:32:07 (WWJD) any->ossec
Rule: 503 (level 3) -> 'Ossec agent started.'
ossec: Agent started: 'WWJD->any'.

```

### Installation path

![install_path](https://user-images.githubusercontent.com/28990973/167193402-2b836072-21fc-4493-9942-21716ccddea4.png)



### Uninstall

![uninstall](https://user-images.githubusercontent.com/28990973/167193434-2fadeb4f-5213-483a-9531-c930243e2901.png)



</details>

**Comment by fedepacher** [comment]
# Update 2022/05/12

After deep research into updating **PowerShell** to the lowest version that contains the  `Invoke-WebRequest` command available, it has been found that after upgrading Windows 7 with SP1, SP2, and updating packages from the Control Panel, the working packages that contain `Windows Management Framework 3.0` is the following:

- Windows6.1-KB2506143-x86 / 64

And can be found in the following [link](https://www.microsoft.com/en-us/download/details.aspx?id=34595).

![Screenshot from 2022-05-12 16-32-04](https://user-images.githubusercontent.com/28990973/168155861-9d5a6ecf-cbfb-4e59-8d8f-c1fbf6e3683a.png)

After installation it has the following:

![Screenshot from 2022-05-12 16-44-58](https://user-images.githubusercontent.com/28990973/168155996-c06ffa88-7a58-411f-b998-158b25211c76.png)

Getting an active status as a result in the manager:

```
[root@centos-manager1 vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centos-manager1 (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP-G6KK08C, IP: any, Disconnected
   ID: 004, Name: DESKTOP-9QHFQ7B, IP: any, Disconnected
   ID: 005, Name: IE11WIN8_1, IP: any, Disconnected
   ID: 008, Name: WWJD, IP: any, Active
```

**Comment by jmv74211** [comment]
After the tests performed by @fedepacher [here](https://github.com/wazuh/wazuh-qa/issues/2869#issuecomment-1125364026), we can conclude that on Windows the command:

```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.0-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.0.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.0.msi /q WAZUH_MANAGER='xxx.xxx.xxx.xxx' WAZUH_REGISTRATION_SERVER='xxx.xxx.xxx.xxx' WAZUH_AGENT_GROUP='default'
```


works for powershell versions >= 3.0
