### ISSUE TITLE
Logcollector IT build fails due to `wazuh-agent` is not found

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2874]
Occasionally, builds of logcollector integration tests fail due to the following error:

```
TASK [install_wazuh_repo : Installing wazuh-agent APT] *************************
....
E: Version '4.5.0-0.40500.20220509' for 'wazuh-agent' was not found
```

> Example build: https://ci.wazuh.info/job/Test_integration/26221/console

It is requested to investigate the reason and fix it.

**Comment by Rebits** [comment]
### 12/05/202

Logcollector ITs seem to be launched before Debian agent packages creation.
This should be fixed change Check Links to the following:

```
    amd64_integration_test_logcollector_agent_0: [ 'amd64_build_centos_manager', 'amd64_build_debian_agent', 'amd64_build_centos_agent', 'amd64_build_macos_agent', 'i386_build_solaris_11_agent' ],
    amd64_integration_test_logcollector_agent_1: [ 'amd64_build_centos_manager', 'amd64_build_debian_agent', 'amd64_build_centos_agent', 'amd64_build_macos_agent', 'i386_build_solaris_11_agent' ],
```

Adding `amd64_build_debian_agent` in order to avoid this error

**Comment by Rebits** [comment]
Issue moved to [wazuh/wazuh-jenkins #3516](https://github.com/wazuh/wazuh-jenkins/issues/3516) via [**ZenHub**](https://www.zenhub.com/)
