### ISSUE TITLE
Solaris FIM IT : `test_realtime_unsupported` fail

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2881]
### Description

During https://github.com/wazuh/wazuh-qa/issues/2879 nightly, `test_basic_usage_realtime_unsupported` FIM IT test fails in Solaris system.
Is required further research to determine the cause of the error.

### Error output
```
test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py:150: in test_realtime_unsupported
    event_mode="scheduled")
/opt/python3/lib/python3.7/site-packages/wazuh_testing-4.3.0-py3.7.egg/wazuh_testing/fim.py:2425: in regular_file_cud
    event_mode=event_mode)
/opt/python3/lib/python3.7/site-packages/wazuh_testing-4.3.0-py3.7.egg/wazuh_testing/fim.py:1487: in fetch_and_check
    self.events = self.fetch_events(min_timeout, triggers_event, extra_timeout, error_message=error_msg)
/opt/python3/lib/python3.7/site-packages/wazuh_testing-4.3.0-py3.7.egg/wazuh_testing/fim.py:1535: in fetch_events
    error_message=error_message).result()
/opt/python3/lib/python3.7/site-packages/wazuh_testing-4.3.0-py3.7.egg/wazuh_testing/tools/monitoring.py:203: in start
    error_message=error_message).result()
/opt/python3/lib/python3.7/site-packages/wazuh_testing-4.3.0-py3.7.egg/wazuh_testing/tools/monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError: TimeoutError was raised because a single 'added' event was expected for ['/dir/testfile.txt'] but was not detected.
```

**Build**: https://ci.wazuh.info/job/Test_integration/26288/
**Report**:  [report.html](https://github.com/wazuh/wazuh-qa/files/8677398/agent_solaris_html_report_Test_integration_B26288_20220512005708.zip)

**Comment by Deblintrake09** [comment]
# Research 2022/05/19

- Launched Fim Suite. Test fails randomly. 6 Runs - [:green_circle::red_circle::green_circle::red_circle::green_circle::red_circle:](https://app.zenhub.com/files/170350910/5bf158e6-2f03-434e-9bc3-6b5d647083b0/download)
- Launched test alone 10+ times - Test passed all the times

**Comment by Rebits** [comment]
Solaris IT failure persists. Reopen issue

### Nightly

|  Version  |   Commit  |  Date   | 
| --- | --- | --- |
| 4.4 | https://github.com/wazuh/wazuh/commit/c0295b79e070dddfbb31f17d1d948d1a3ded6aaf |  Thu Feb 09 17:05:36 UTC 2023 |


### Evidence

Build: https://ci.wazuh.info/job/Test_integration/36565/
Report HTML: [agent_solaris_html_report_Test_integration_B36565_20230210011333.zip](https://github.com/wazuh/wazuh-qa/files/10706254/agent_solaris_html_report_Test_integration_B36565_20230210011333.zip)
