### ISSUE TITLE
E2E design and implementation: Netcat

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2890]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2848). So, in this issue, we will design and develop the E2E test to cover those use cases.

| Develoment branch|
|:--:|
|[2890-e2e-test-netcat](https://github.com/wazuh/wazuh-qa/tree/2890-e2e-test-netcat)|

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

WIP.

**Comment by BelenValdivia** [comment]
## Task 1: Design test
### Design

1. Get the test cases defined in:
```
end_to_end/
└ test_netcat/
    └ test_netcat.py
    └ data/
        └ playbooks/
           └ configuration.yaml
           └ generate_events.yaml
        └ test_cases/ 
	     ├ cases_file.yml
             .
             .
```

2. Configure the environment (install netcat, configure localfile, configure local rules) 
3. Get the alerts (if they were generated) from the wazuh-indexer API
4. Check if the expected alert matched one of the alerts obtained from the API
