### ISSUE TITLE
E2E design and implementation: IP Reputation

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2895]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2875). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion
Test implemented locally. Manager-> Centos8, Attacker-> Windows server 2019

**Comment by BelenValdivia** [comment]
1/8
- Added configuration yaml
-  Worked on generate events yaml
-  Problems wuth web server
-  Added attacker ip to the inventory

**Comment by BelenValdivia** [comment]
2/8
PR opened https://github.com/wazuh/wazuh-qa/pull/3141
