### ISSUE TITLE
Add test_scan_results cases for SUSE Linux Enterprise (2/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2899]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2792 |

### Description

As part of https://github.com/wazuh/wazuh-qa/issues/2792, it is necessary to add cases in the test_scan_results suite related to SUSE Linux Enterprise support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan provider and NVD vulnerabilities`: Test that vulnerable packages are reported using the OVAL and NVD feed.
- `Test scan provider vulnerabilities`: Test that vulnerable packages are reported using the OVAL feed (NVD contains different vulnerabilities).
- `Test scan vulnerability removal`: Check that it generates vulnerability alert fixed after removing or updating a vulnerable package.

### To Do 

- [x] Add scan provider and NVD vulnerabilities tests
- [x] Add scan vulnerability removal tests.

**Comment by Deblintrake09** [comment]
# Task 1 - Add scan provider and NVD vulnerabilities tests

Add test cases for `test_scan_provider_vulnerabilites` and `test_scan_provider_and_nvd_vulnerabilities`

![Captura de pantalla de 2022-05-16 12-45-31](https://user-images.githubusercontent.com/14501079/168636195-8afd99b9-629a-4e77-92a3-11016a11267b.png)

**Comment by Deblintrake09** [comment]
# Task 2 - Add case for Test scan vulnerability removal

Reworked test to make it generic so it can accept a custom Agent's OS. Added test case for Suse Linux Server 15.
![Captura de pantalla de 2022-05-17 08-34-42](https://user-images.githubusercontent.com/14501079/168803848-cae308db-7f62-4ce2-bb09-74e233c90e70.png)

**Comment by damarisg** [comment]
It was merge to 2792-add-support-for-SUSE-OVAL-in-Vulnerability-Detector branch.
