### ISSUE TITLE
Add test_providers cases for Amazon Linux 2022  (2/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2900]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2813 |

### Description

As part of [Integration tests for Vulnerability Detector: Amazon Linux 2022 support](https://github.com/wazuh/wazuh-qa/issues/2813), it is necessary to add cases in the test_providers suite related to Amazon Linux 2022 support for the Wazuh Vulnerability Detector module.

**Suite test_providers**

- `Test enabled/disabled`: Check that the provider's feeds start downloading when activated.
- `Test missing os`: Test the behavior when the <os> tag is omitted. Check failure if the tag is required, and in case it is not, it starts downloading the feeds as normal
- `Test OS`: Test that it starts downloading the feeds of the specified OS.
- `Test update from year`: Test if the feed is updated from a specific date. If the option does not apply, check warning warning.
- `Test update interval`: Test that the feed is updated at the specified interval

### To Do 

- [x] Test that it works correctly.

**Comment by Deblintrake09** [comment]
# Task 1 - Add Case for Test Enabled/Disabled
![Captura de pantalla de 2022-05-17 16-41-30](https://user-images.githubusercontent.com/14501079/168902842-f135a36b-43cf-468e-b9f7-1905cb6e2cd2.png)

**Comment by Deblintrake09** [comment]
# Task 1 - Add Case for Test Missing OS
![1](https://user-images.githubusercontent.com/14501079/168902930-332e4f26-fa4c-489b-899f-52f06a9bdd92.png)

**Comment by Deblintrake09** [comment]
# Task 3 - Add Case for Test OS
![Captura de pantalla de 2022-05-17 16-52-44](https://user-images.githubusercontent.com/14501079/168903064-cde6dc0b-42ce-4aba-8967-766603ad718b.png)

**Comment by Deblintrake09** [comment]
# Task 4 - Add Case for Update from Year
This  variable is not used on Amazon Linux Provider, so no test is added.

**Comment by Deblintrake09** [comment]
# Task 5 - Add Case for Test Update Interval

- Added Test case for Amazon Linux 2 y Amazon Linux 2022

![Captura de pantalla de 2022-05-17 17-13-33](https://user-images.githubusercontent.com/14501079/168903271-6777aadc-ee15-47c6-b775-486aee2accc2.png)

**Comment by damarisg** [comment]
Note: Merged into 2813-support-for-amazon-linux-2022-vdt branch.
