### ISSUE TITLE
System tests in 4.3 are unstable

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh-qa#2904]
System tests in 4.3 are unstable. 3 runs were executed in Jenkins where failures can be observed in:

- test_cluster/test_agent_enrollment/test_agent_enrollment.py
- test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
- test_cluster/test_agent_key_polling/test_agent_key_polling.py
- test_cluster/test_integrity_sync/test_integrity_sync.py

**Branch QA**: 2885-add-libssl-dev-dependency-4.3

Builds:

- https://ci.wazuh.info/job/Test_system/69/
- https://ci.wazuh.info/job/Test_system/70/
- https://ci.wazuh.info/job/Test_system/71/

**Comment by damarisg** [comment]
We decided to close them.
