### ISSUE TITLE
Fix GCloud IT: `test_max_messages` error (1/2)

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2907]
### Description

GCloud IT suite fails in the [nightly](https://github.com/wazuh/wazuh-qa/issues/2906) pipeline.
Is required further research to determine the cause of the error.

### Failed cases
- `test_gcloud/test_functionality/test_max_messages.py::test_max_messages[get_configuration0-publish_messages1]`
- `test_gcloud/test_functionality/test_max_messages.py::test_max_messages[get_configuration0-publish_messages2]`

<details>
test_max_messages[get_configuration0-publish_messages1]:

```
test_gcloud/test_functionality/test_max_messages.py:183: in test_max_messages
    assert int(number_pulled) >= publish_messages
E   AssertionError: assert 0 >= 100
E    +  where 0 = int('0')
```

test_max_messages[get_configuration0-publish_messages2]

```
test_gcloud/test_functionality/test_max_messages.py:199: in test_max_messages
    assert int(number_pulled) >= remainder
E   AssertionError: assert 0 >= 20
E    +  where 0 = int('0')
```

</details>

### Build
https://ci.wazuh.info/job/Test_integration/26273/

### Report 
 [report.html](https://github.com/wazuh/wazuh-qa/files/8677359/manager_html_report_Test_integration_B26273_20220512005724.1.zip)

---------
- [x]  analyze test_max_messages[get_configuration0-publish_messages1]
- [x]  analyze test_max_messages[get_configuration0-publish_messages2]

**Comment by damarisg** [comment]
It was worked on https://github.com/wazuh/wazuh-qa/pull/3006
