### ISSUE TITLE
Fix Agentd Windows IT: `test_agentd_state` error

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2908]
### Description

Windows agentd IT suite fails in the [nightly](https://github.com/wazuh/wazuh-qa/issues/2906) pipeline.
Is required further research to determine the cause of the error.

## Failed cases
- `test_agentd/test_agentd_state.py::test_agentd_state[-Successful connection with remoted]`
<details>
```
================================== FAILURES ===================================
___________ test_agentd_state[-Successful connection with remoted] ____________
test_agentd\test_agentd_state.py:183: in test_agentd_state
    check_fields(expected_output)
test_agentd\test_agentd_state.py:248: in check_fields
    assert checks[field].get('handler')(expected_value, get_state_callback=get_state)
test_agentd\test_agentd_state.py:290: in check_last_keepalive
    current_value = get_state_callback()['last_keepalive']
E   KeyError: 'last_keepalive'
---------------------------- Captured stdout call -----------------------------
```
</details>

- `test_agentd/test_agentd_state.py::test_agentd_state[-Only remote request available]`
<details>

```
______________ test_agentd_state[-Only remote request available] ______________
test_agentd\test_agentd_state.py:183: in test_agentd_state
    check_fields(expected_output)
test_agentd\test_agentd_state.py:248: in check_fields
    assert checks[field].get('handler')(expected_value, get_state_callback=get_state)
test_agentd\test_agentd_state.py:347: in check_status
    current_value = get_state_callback()['status']
test_agentd\test_agentd_state.py:218: in remoted_get_state
    response = json.loads(remoted_server.request_answer)
C:\Python37\lib\json\__init__.py:341: in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
E   TypeError: the JSON object must be str, bytes or bytearray, not NoneType
---------------------------- Captured stdout call -----------------------------
```

</details>

### Build
https://ci.wazuh.info/job/Test_integration/26446/

### Report 
[report.html](https://github.com/wazuh/wazuh-qa/files/8714180/agent_windows_html_report_Test_integration_B26446_20220518021017.zip)

**Comment by CamiRomero** [comment]
Wazuh version|Component|Install type | Package Version | Platform|
|---|---|---|---|---|
| 4.5.0 | Agentd | Agent |  [0.40500.20220520](https://packages-dev.wazuh.com/staging/windows/wazuh-agent-4.5.0-0.40500.20220520.msi) | Windows |

## Tests Results

| Test Path | Os/Type | Execution Type | Results | Date | By |
|--|--|--|--|--|--|
|  test/integration/test_agentd | Windows - Agent | Jenkins | [:green_circle:](https://ci.wazuh.info/job/Test_integration/26718/)[:green_circle:](https://ci.wazuh.info/job/Test_integration/26728/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/26727/)| 23/05/2022 |  @CamiRomero  | 
|  test/integration/test_agentd | Windows - Agent | Local | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8762987/R1.zip)[:green_circle:](https://github.com/wazuh/wazuh-qa/files/8762991/R2.zip) [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8762992/R3.zip)| 23/05/2022 |  @CamiRomero  | 

we cannot reproduce the failure.

**Comment by damarisg** [comment]
|Version | Revision | 
|--|--|
| 4.5.0 | 0.40500.20220523 | 

| Test Path | Os/Type | Jenkins| Date | By | 
|--|--|--|--|--|
| test_agentd/ | CentOS- Agent | [:green_circle:](https://ci.wazuh.info/job/Test_integration/26859/)  | 2022/05/24|  Seyla
| test_agentd/ | Windows - Agent |  [:green_circle:](https://ci.wazuh.info/job/Test_integration/26860/) | 2022/05/24|  Seyla

This issue was closed because we couldn't reproduce it.
