### ISSUE TITLE
Fix Logcollector Windows IT: `test_age_datetime_changed` error

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2909]
### Description

Windows Logcollector IT suite fails in the [nightly](https://github.com/wazuh/wazuh-qa/issues/2906) pipeline.
Is required further research to determine the cause of the error.

## Failed cases
- `test_logcollector/test_age/test_age_datetime_changed.py::test_configuration_age_datetime[C:\\Users\\Jenkins\\AppData\\Local\\Temp\\wazuh_testing_age\\*_syslog_9h--43d]`

<details>

```
================================== FAILURES ===================================
_ test_configuration_age_datetime[C:\\Users\\Jenkins\\AppData\\Local\\Temp\\wazuh_testing_age\\*_syslog_9h--43d] _
test_logcollector\test_age\test_age_datetime_changed.py:217: in test_configuration_age_datetime
    error_message=f"{name} was not detected")
C:\Python37\lib\site-packages\wazuh_testing-4.3.0-py3.7.egg\wazuh_testing\tools\monitoring.py:203: in start
    error_message=error_message).result()
C:\Python37\lib\site-packages\wazuh_testing-4.3.0-py3.7.egg\wazuh_testing\tools\monitoring.py:469: in start
    raise TimeoutError(error_message)
E   TimeoutError: testing_age_dating.log was not detected
---------------------------- Captured stdout setup ----------------------------
```

</details>

### Build
https://ci.wazuh.info/job/Test_integration/26450/

### Report 
[report.html](https://github.com/wazuh/wazuh-qa/files/8714208/agent_windows_html_report_Test_integration_B26450_20220518021018.zip)

**Comment by damarisg** [comment]
Duplicated by https://github.com/wazuh/wazuh-qa/issues/2818
