### ISSUE TITLE
Wazuh-Dashboard Manual testing: TypeError in Github/AWS/GCP

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2910]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-kibana-app/issues/4095|

### Description
It is required to provide more information about https://github.com/wazuh/wazuh-kibana-app/issues/4095.

In order to provide more information the following steps are going to be followed:
- [x] Deploy an all-in-one 4.3.0 environment
- [x] Enable GCP module in the wazuh-dashboard
- [x] Check GCP module menu for console errors
- [x] Add GCP configuration and produce some events
- [x] Check GCP module menu for console errors

**Comment by Rebits** [comment]
_Issue in progress_

**Comment by Rebits** [comment]
## Check GCP module menu for console errors
The expected typeError was not produced. Only the following alerts were generated:

- `Some cookies are misusing the recommended “SameSite“ attribute 254`
- `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [wazuh:352:1](https://192.168.56.2/app/wazuh)`
- `This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [bootstrap.js:89:20](https://192.168.56.2/bootstrap.js)`
- `The "manifestServiceUrl" parameter is deprecated in v7.6.0.
        Consider using "tileApiUrl" and "fileApiUrl" instead.`

We are going to enable the rest of the modules and check if the `Uncaught (in promise) TypeError` appears

**Comment by Rebits** [comment]
### Check GCP module menu for console errors
After configuring gcp and generated a single alerts, the expected error is generated
![google_cloud_error](https://user-images.githubusercontent.com/11089305/169025220-e818e8cb-8136-4b75-b3fa-ea33fe728a39.png)

There are no strict steps to reproduce this error. In this case, it was generated following these actions:
- Configure and generate some gcp events
- Go to Modules > Google Clouds Platform > Events
- Wait 10 minutes
- Go to Modules Directory
- Go again to Modules > Google Clouds Platform > Events

Also, during the same session another `TypeError` appear: `TypeError Uncaught TypeError: bounds is null`
![bounds_null](https://user-images.githubusercontent.com/11089305/169025807-b036b698-fcf5-4cb3-b027-c550435d60dc.png)

**Comment by damarisg** [comment]
We decided to close them.
