### ISSUE TITLE
Research of coverage for FIM tests 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2928]
## Description

So far, the QA framework module for FIM has a lot of confused and unmaintained tests.

This task requires an investigation of the FIM test suite, to understand our coverage and remove outdated tests.

Also, if we verify that some test requires refactoring, we need to create an issue to work on that.

## Tasks

- [ ] Research the test suite.
- [ ] Manual testing of each test.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
