### ISSUE TITLE
Vulnerability detector: Fix Ubuntu Bionic XML parsing 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#2937]
# Description 

As described in the following issue https://github.com/wazuh/wazuh/issues/13556 while parsing the OVAL feed from Bionic, the Vulnerability detector ends with an error due to a string limitation. 

The fix proposed here truncates strings with more than 20480 characters https://github.com/wazuh/wazuh/pull/13566

# Steps to reproduce

Enable vulnerability detector and Bionic feed for Ubuntu. 

During the parse of the OVAL file, the following error shows up

`ERROR: (5502): Could not load the CVE OVAL for 'BIONIC'. 'XMLERR: String overflow.'`

```
2022/05/23 12:52:05 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4557 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Ubuntu Bionic' database update.
2022/05/23 12:52:05 wazuh-modulesd:download[18591] wm_download.c:230 at wm_download_dispatch(): DEBUG: Downloading 'https://security-metadata.canonical.com/oval/com.ubuntu.bionic.cve.oval.xml.bz2' to 'tmp/req-1668375730'
2022/05/23 12:52:08 wazuh-modulesd:download[18591] wm_download.c:250 at wm_download_dispatch(): DEBUG: Download of 'https://security-metadata.canonical.com/oval/com.ubuntu.bionic.cve.oval.xml.bz2' finished.
2022/05/23 12:52:09 wazuh-modulesd[18591] url.c:418 at wurl_request_uncompress_bz2_gz(): DEBUG: File from URL 'https://security-metadata.canonical.com/oval/com.ubuntu.bionic.cve.oval.xml.bz2' was successfully uncompressed into 'tmp/vuln-temp'
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4313 at wm_vuldet_fetch_oval(): DEBUG: (5407): The feed 'Ubuntu Bionic' is outdated. Fetching the last version.
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4095 at wm_vuldet_oval_process(): DEBUG: (5411): Starting preparse step of feed 'BIONIC'
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4100 at wm_vuldet_oval_process(): DEBUG: (5412): Starting parse step of feed 'BIONIC'
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4102 at wm_vuldet_oval_process(): ERROR: (5502): Could not load the CVE OVAL for 'BIONIC'. 'XMLERR: String overflow.'
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4258 at wm_vuldet_index_feed(): DEBUG: remove(tmp/vuln-temp.bz2): No such file or directory
2022/05/23 12:52:09 wazuh-modulesd:vulnerability-detector[18591] wm_vuln_detector.c:4565 at wm_vuldet_check_feed(): DEBUG: (5521): Failed when updating 'canonical BIONIC' database. Retrying in '300' seconds.
```

**Comment by Deblintrake09** [comment]
# Testing on Centos
<details>
<summary>Fresh Install of 4.3.3 - Reproduced Error :green_circle:</summary>

</details>
Install Wazuh Manager
Enable VDT and Canonical feed in ossec.conf
Start Wazuh
Check Logs
<details>
<summary>Fresh Install of 4.3.4 package- Error not appearing  :green_circle:</summary>

</details>

<details>
<summary>Upgrade from 4.3.3 to 4.3.4 - Error not appearing after upgrade  :green_circle: </summary>

</details>

**Comment by Deblintrake09** [comment]
## Integration tests on 4.3.4  

| Target tests | OS - System | Result | Date | By |
|--|--|--|--|--|
| test_vulnerability_detector/test_feeds_/test_download_feeds.py | Centos Manager | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/27288/)| 2022/06/02 | @Deblintrake09 
| test_vulnerability_detector/ | Centos Manager | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/27293/)| 2022/06/02 | @Deblintrake09 
| test_vulnerability_detector/test_feeds_/test_download_feeds.py | Debian Manager | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/27292/)| 2022/06/02 | @Deblintrake09 
| test_vulnerability_detector/ | Debian Manager | [:large_blue_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/27290/)| 2022/06/02 | @Deblintrake09
