### ISSUE TITLE
QA testing - Add test to check debug symbols

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#2939]
|Epic|
|---|
|wazuh/wazuh#9913|

## Description
The main goal of this issue is to validate wazuh/wazuh#9913 implementation.

### Epic scope
- OS and Wazuh installation
  - Wazuh manager: Linux on amd64/x86_64 arch
  - Wazuh Agent: Linux, Windows and macOS on every supported arch
- Installations
  - From sources (Linux, macOS)
  - From packages (Linux, Windows and macOS)
  - WPK  (Linux, Windows and macOS)
### Epic compatibility
- Wazuh Agent on other OSes: AIX, HP-UP, Solaris 1X

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
