### ISSUE TITLE
New integration tests development: API option to rotate logs depending on file size

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#2949]
## Description

As part of https://github.com/wazuh/wazuh/issues/13665, we need to add new integration tests for the API configuration file to test this new feature.

## Configuration options

```yaml
logs:
  max_size:
    enabled: true
    size: [ 1m | 1k ]
```

### `enabled` option
1. Check default configuration. As this is disabled by default, the API logs must rotate at midnight after one entry.
2. Check that after enabling this option the API logs will not rotate at midnight.

### `size` option
> Assuming `enabled` is set to `true`

1. Check that using an invalid unit (i.e. "5P") will make the Wazuh API return a proper message and not initialize.
2. Check that using a size smaller than 1MB will make the Wazuh API return a proper message and not initialize.
3. Check that as long as a valid unit is used, this option is not case sensitive.
4. Check that after configuring a valid `size`, the API log will rotate to the correct path.
5. Check that the rotated logs suffixes are correct.

## Considerations

- By default, `enabled` will be `False`. If this option is enabled, the time based rotation (at midnight) will be disabled.
- The `size` option allows any integer followed by one of the valid units: K for kilobytes and M for megabytes (not case sensitive). In addition, there is a restriction for a minimum value. It must be greater than 1MB.
- Rotated logs based on time will follow this format: `/var/ossec/logs/api/<YEAR>/<MONTH>/api.log-<DAY>`
- Rotated logs based on file size will follow this format: `/var/ossec/logs/api/<YEAR>/<MONTH>/api.log-<DAY>_<ITERATION>`. `ITERATION` will begin at 1 and will increase if more logs are rotated in the same day.
- Rotation occurs after a new entry is added to the API log, having triggered the selected method. For instance, in the time based rotation, it will rotate after a new entry is added past midnight. Not at midnight automatically.

**Comment by RamosFe** [comment]
## Test cases

### `enabled` option
- [ ]  Check default configuration. As this is disabled by default, the API logs must rotate at midnight after one entry.
- [ ]  Check that after enabling this option the API logs will not rotate at midnight.

### `size` option
> Assuming `enabled` is set to `true`

- [ ] Check that using an invalid unit (i.e. "5P") will make the Wazuh API return a proper message and not initialize.
- [ ]  Check that using a size smaller than 1MB will make the Wazuh API return a proper message and not initialize.
- [ ] Check that as long as a valid unit is used, this option is not case sensitive.
- [ ] Check that after configuring a valid `size`, the API log will rotate to the correct path.
- [ ]  Check that the rotated logs suffixes are correct.

**Comment by RamosFe** [comment]
## Update

Created the Integration Tests related to the `size` option in https://github.com/wazuh/wazuh/pull/21776.

**Comment by RamosFe** [comment]
## Update

Because the functionalities for time-based testing have not yet been migrated to the `qa-integration-framework` repository and the code responsible for log rotation has already been tested, it was decided not to develop the first 2 cases:
- Check default configuration. As this is disabled by default, the API logs must rotate at midnight after one entry.
- Check that after enabling this option the API logs will not rotate at midnight.


## Tests

```
(venv) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh$ sudo -E python3 -m pytest tests/integration/test_api/test_config/test_logs_rotation/
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-0.13.1
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, html-3.1.1, asyncio-0.15.1, cov-2.12.0
collected 8 items                                                                                                                                                                                                                       

tests/integration/test_api/test_config/test_logs_rotation/test_logs_rotation_by_size.py ..                                                                                                                                        [ 25%]
tests/integration/test_api/test_config/test_logs_rotation/test_logs_size_option.py ......                                                                                                                                         [100%]

========================================================================================================== 8 passed in 35.05s ===========================================================================================================
``
