### ISSUE TITLE
Test the fix for a segmentation fault in Wazuh DB

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#2951]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13657|https://github.com/wazuh/wazuh/pull/13666|

## Use case

- [x] Wazuh DB must not crash even if it fails to open a database.

### How to reproduce

```shell
cd /var/ossec/queue/db
service wazuh-manager start

# Wait for Wazuh DB to create the manager's database
while [ ! -f 000.db ]; do sleep 1; done

# Tamper the file's permissions
chown root:root 000.db

service wazuh-manager restart
```

### Expected logs

```
2022/06/02 11:10:28 wazuh-db: ERROR: Couldn't create SQLite database 'queue/db/000.db'
2022/06/02 11:10:28 wazuh-db: ERROR: Couldn't open DB for agent '000'
```

**Comment by juliamagan** [comment]
| Type | OS | Package|
|:--:|:--:|--- |
|Manager|CentOS 8| https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.4-0.commit526b789.x86_64.rpm|
|Manager| Ubuntu 20.04|https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.4-0.commit526b789_amd64.deb
