### ISSUE TITLE
Test Office365 and GitHub integration query timeout

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#2952]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13592|https://github.com/wazuh/wazuh/pull/13626|

As explained at https://github.com/wazuh/wazuh/pull/13626, we've added a timeout to the GitHub and Office365 integrations, in order to prevent them from hanging indefinitely if the API doesn't respond.

While this problem has been detected in production systems, we've been unable to simulate that in testing environments. So, we propose to mock the corresponding APIs and simulate a delay greater than 1 minute.

# Use cases

## Bug To reproduce

- [x] 4.3.3: If a query to the Azure's API for Office365 gets delayed more than one minute, the agent not abort. (Reproduce the bug)
- [x] 4.3.3: If a query to the  GitHub API for Audit gets delayed more than one minute, the agent not abort. (Reproduce the bug)

## Tier 0

- [x] 4.4.4: If a query to the Azure's API for Office365 gets delayed more than one minute, the agent must abort and make the query again.
- [x] 4.4.4: If a query to the GitHub API for Audit gets delayed more than one minute, the agent must abort and make the query again.
- [x] Upgrade 4.3.3 to 4.3.4: If a query to the Azure's API for Office365 gets delayed more than one minute, the agent must abort and make the query again.
- [x] Upgrade 4.3.3 to 4.3.4: If a query to the GitHub API for Audit gets delayed more than one minute, the agent must abort and make the query again.

## Automated Tests

- [x] 4.4: Integration Tests

**Comment by damarisg** [comment]
## If a query to the Azure's API for Office365 gets delayed more than one minute, the agent must abort and make the query again.

<details>
<summary>Tester Seyla - <code>Ubuntu / Package</code> 🔵</summary>

```

```

</details>


<details>
<summary>Tester Seyla - <code>CentOS/ Package</code> 🔵</summary>

```

```

</details>

**Comment by damarisg** [comment]
## If a query to the GitHub API for Audit gets delayed more than one minute, the agent must abort and make the query again.

<details>
<summary>Tester Seyla - <code>Ubuntu / Package</code> 🔵</summary>

```

```

</details>


<details>
<summary>Tester Seyla - <code>CentOS/ Package</code> 🔵</summary>

```

```

</details>

**Comment by damarisg** [comment]
## Upgrade 4.3.3 to 4.3.4: If a query to the Azure's API for Office365 gets delayed more than one minute, the agent must abort and make the query again.


<details>
<summary>Tester Seyla - <code>CentOS/ Sources</code> 🟢 </summary>

```
2022/06/02 19:33:52 wazuh-modulesd[83006] url.c:522 at wurl_http_request(): DEBUG: curl_easy_perform() failed: Timeout was reached
2022/06/02 19:33:52 wazuh-modulesd:office365[83006] wm_office365.c:547 at wm_office365_get_access_token(): DEBUG: Unknown error while getting access token.       
2022/06/02 19:34:52 wazuh-modulesd:office365[83006] wm_office365.c:289 at wm_office365_execute_scan(): DEBUG: Scanning tenant: 'test'
2022/06/02 19:34:52 wazuh-modulesd:office365[83006] wm_office365.c:516 at wm_office365_get_access_token(): DEBUG: Office 365 API access token URL: 'http://192.168.68.105:3001/test/oauth2/v2.0/token'

2022/06/02 19:35:52 wazuh-modulesd[83006] url.c:522 at wurl_http_request(): DEBUG: curl_easy_perform() failed: Timeout was reached
2022/06/02 19:35:52 wazuh-modulesd:office365[83006] wm_office365.c:547 at wm_office365_get_access_token(): DEBUG: Unknown error while getting access token.       
2022/06/02 19:36:52 wazuh-modulesd:office365[83006] wm_office365.c:289 at wm_office365_execute_scan(): DEBUG: Scanning tenant: 'test'
2022/06/02 19:36:52 wazuh-modulesd:office365[83006] wm_office365.c:516 at wm_office365_get_access_token(): DEBUG: Office 365 API access token URL: 'http://192.168.68.105:3001/test/oauth2/v2.0/token'
2022/06/02 19:37:52 wazuh-modulesd[83006] url.c:522 at wurl_http_request(): DEBUG: curl_easy_perform() failed: Timeout was reached
```

</details>

**Comment by damarisg** [comment]
## If a query to the GitHub API for Audit gets delayed more than one minute, the agent not abort. (Reproduced on 4.3.3)

<details>
<summary>Tester Seyla - <code>CentOS/ Sources</code> 🟢 </summary>

```
2022/06/02 20:09:15 wazuh-modulesd:github[97516] wm_github.c:222 at wm_github_execute_scan(): DEBUG: Scanning organization: 'test'
2022/06/02 20:09:15 wazuh-modulesd:github[97516] wm_github.c:269 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'http://192.168.68.105:3001/orgs/test/audit-log?phrase=created:2022-06-02T20:08:15Z..2022-06-02T20:09:14Z&include=git&order=asc&per_page=100'
2022/06/02 20:11:25 wazuh-modulesd[97516] url.c:514 at wurl_http_request(): DEBUG: curl_easy_perform() failed: Couldn't connect to server
2022/06/02 20:12:25 wazuh-modulesd:github[97516] wm_github.c:222 at wm_github_execute_scan(): DEBUG: Scanning organization: 'test'
2022/06/02 20:12:25 wazuh-modulesd:github[97516] wm_github.c:269 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'http://192.168.68.105:3001/orgs/test/audit-log?phrase=created:2022-06-02T20:08:15Z..2022-06-02T20:12:24Z&include=git&order=asc&per_page=100'
2022/06/02 20:14:33 wazuh-modulesd[97516] url.c:514 at wurl_http_request(): DEBUG: curl_easy_perform() failed: Couldn't connect to server
```

</details>

**Comment by damarisg** [comment]
## Upgrade 4.3.3 to 4.3.4: If a query to the GitHub API for Audit gets delayed more than one minute, the agent must abort and make the query again.



<details>
<summary>Tester Seyla - <code>CentOS/ Sources</code> 🟢 </summary>

  ![imagen](https://user-images.githubusercontent.com/3978434/171733859-583d4326-fe7a-495d-b310-cebf3e7dba15.png)


</details>
