### ISSUE TITLE
Enhancement - Refactor system tests of environment `one_manager_agent`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2993]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `one_manager_agent` environment.

### List of tests
- [ ] Refactor system test `test_files_cud`
- [ ] Refactor system test `test_synchronization`

**Comment by Rebits** [comment]
### 09/08/2022

In order to allow the use current system test with the new Jenkins libraries, we have refactored inventory handling.
Currently, system tests were launched in a Docker environment, so, the inventory was explicitly defined in the repository. Now after changes this will be sent as a pytest attribute.
After this change,  @fedepacher  and I have several issues were detected:

### QA user does not have permission to edit critical files 
Deployed instances use a testing user, named `qa`. This required sudo before accessing critical files of the system. This could be implemented in system tests using the following approach:

```
        with self.get_host(host).sudo():
            return self.get_host(host).file(file_path).content_string
```

### Local internal options and other configurations are set at provision time
In order to not affect another test module that uses the same environment, is required to remove configuration logic from the provisioning phase.

<hr> 

I have a meeting with @juliamagan, in order to check if E2E test structure could be used in order to refactor system tests. Further research is required.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
