### ISSUE TITLE
IT FIM - Refactor FIM fixture wait_for_fim_start

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#2994]
# Description

During work on Issue #2315, it was found that the fixture `wait_for_fim_start` presented what appeared to be an unnecessary variable, as well as being repeated in three conftest files (test_files/conftest.py, test_registry/conftest.py and test_synchronization/conftest.py), being all of them identical in code.

A refactor of this fixture is needed, but since it affects the majority of tests in the `test_fim` suite, it should be handled as a separate Issue.

This issue is opened for this fix.

### Afected modules:
- test_files/conftest.py
- test_registry/conftest.py
- test_synchronization/conftest.py

### Proposed fix
Move the function from `test_files` (it has been reworked into a function and two fixtures with `module` and `function` scope) into the `test_fim/conftest.py` file.

**Comment by damarisg** [comment]
We decided to close them.
