### ISSUE TITLE
Check the correct removal of the local_ip option for the agent configuration.

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-qa#3002]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/12744|https://github.com/wazuh/wazuh/pull/13878|

### Description

This issue is intended to validate the implementation of [wazuh/wazuh#13878](https://github.com/wazuh/wazuh/pull/13878) which removes local_ip as an agent configuration option.

### Tests

- [x] A warning message will appear when the [local_ip](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#local-ip) option is set. 
- [x] A warning message will not appear when the `local_ip` option is set using a branch without the fix

**Comment by QU3B1M** [comment]
Tests on branch Master
1. Install wazuh-agent using a package of master
2. check the ossec.conf file
```
<ossec_config>
  <client>
    <server>
      <address>192.168.56.10</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>debian, debian10</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>

```
The file doesnt come with the local_ip tag
3.  Add the local_ip tag

**Comment by QU3B1M** [comment]
## A warning message will appear when the [local_ip](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#local-ip) option is set.

<details>
<summary>Debian  :green_circle:</summary> 

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/pull/13878 | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) | Agent | [Packages](https://packages-dev.wazuh.com/warehouse/test/4.5/deb/var/wazuh-manager_4.5.0-3002.local.ip.test_amd64.deb) | Debian-10 |


## Test Execution
1. Deploy a agent using a package on a Debian machine
2. Check the agent's file `/var/ossec/etc/ossec.conf` to verify the tag `local_ip` is not there:
   ```
   <ossec_config>
   <client>
     <server>
       <address>1xx.xxx.xx.xx</address>
       <port>1514</port>
       <protocol>tcp</protocol>
     </server>
     <config-profile>debian, debian10</config-profile>
     <notify_time>10</notify_time>
     <time-reconnect>60</time-reconnect>
     <auto_restart>yes</auto_restart>
     <crypto_method>aes</crypto_method>
   </client>
   ```
3. Add the local_ip tag on the agents's `ossec.conf`
   ```
   <ossec_config>
    <client>
     <server>
       <address>1xx.xxx.xx.xx</address>
       <port>1514</port>
       <protocol>tcp</protocol>
     </server>
     <config-profile>debian, debian10</config-profile>
     <notify_time>10</notify_time>
     <time-reconnect>60</time-reconnect>
     <auto_restart>yes</auto_restart>
     <crypto_method>aes</crypto_method>
     <local_ip>1xx.xxx.xx.xx</local_ip>
   </client>

   ```
4. Restart the wazuh agent.

5. Check the agent's `/var/ossec/logs/ossec.log` to verify the warning is raised
   ```
   2022/06/30 19:24:30 wazuh-agentd: WARNING: The <local_ip> tag is useless.
   ```

</details>
<details>
<summary>Centos  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/pull/13878 | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) | Agent | [Packages](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-agent-4.5.0-3002.local.ip.test.x86_64.rpm) | Centos-8 |


## Test Execution
1. Deploy a agent using a rpm package on a Centos machine
2. Check the agent's file `/var/ossec/etc/ossec.conf` to verify the tag `local_ip` is not there:
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>centos, centos8, centos8.5</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	  </client>
   ...
   ```
3. Add the local_ip tag on the agents's `ossec.conf`
   ```
	   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>centos, centos8, centos8.5</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	    <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
    ```
4. Restart the wazuh agent.

5. Check the agent's `/var/ossec/logs/ossec.log` to verify the warning is raised
   ```
	2022/07/01 12:49:13 wazuh-agentd: WARNING: The <local_ip> tag is useless.
   ```
</details>

<details>
<summary>MacOs  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/pull/13878 | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html) | Agent | [Packages](https://github.com/wazuh/wazuh-qa/files/9031321/wazuh-agent-4.5.0-3002.local.ip.test.zip) | MacOs |


## Test Execution
1. Deploy a agent using a pkg package on a MacOs machine
2. Check the agent's file `/Library/Ossec/etc/ossec.conf` to verify the tag `local_ip` is not there:
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>darwin, darwin19</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	  </client>

   ...
   ```
3. Add the local_ip tag on the agents's `ossec.conf`
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>darwin, darwin19</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
            <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
    ```
4. Restart the wazuh agent.

5. Check the agent's `/Library/Ossec/logs/ossec.log ` to verify the warning is raised
   ```
	  2022/07/01 09:16:47 wazuh-agentd: WARNING: The <local_ip> tag is useless.
   ```
</details>


<details>
<summary>Windows  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/pull/13878 | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html) | Agent | [Packages](https://packages-dev.wazuh.com/warehouse/test/4.5/windows/wazuh-agent-4.5.0-3002.local.ip.test.msi) | Windows Server 2016 |


## Test Execution
1. Deploy a agent using a msi package on a Windows machine
2. Check the agent's file `C:\Program Files (x86)\ossec-agent\ossec.conf` to verify the tag `local_ip` is not there:
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
	    <crypto_method>aes</crypto_method>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	  </client>
   ...
   ```
3. Add the local_ip tag on the agents's `ossec.conf`
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
	    <crypto_method>aes</crypto_method>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    
        <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
    ```
4. Restart the wazuh agent.

5. Check the agent's `C:\Program Files (x86)\ossec-agent\ossec.log` to verify the warning is raised
   ```  
	2022/07/01 12:16:44 wazuh-agent: WARNING: The <local_ip> tag is useless.
   ```
</details>

## A warning message will not appear when the local_ip option is set using a branch without the fix


<details>
<summary>Centos  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/tree/master | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) | Agent | [Packages](https://github.com/wazuh/wazuh-qa/files/9031372/wazuh-agent-4.5.0-3002.local.ip.master.x86_64.zip) | Centos-8 |


## Test Execution
1. Deploy a agent using a rpm package on a Centos machine
2. Eddit the file  `/var/ossec/etc/ossec.conf` adding the tag `local_ip`
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>centos, centos8, centos8.5</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	    <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
   ```

4. Restart the wazuh agent.

5. Check the agent's `/var/ossec/logs/ossec.log` to verify the warning is not there
</details>

<details>
<summary>MacOs  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/tree/master | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html) | Agent | [Packages](https://github.com/wazuh/wazuh-qa/files/9031329/wazuh-agent-4.5.0-3002.local.ip.test.master.zip) | MacOs |


## Test Execution
1. Deploy a agent using a rpm package on a Macos machine
2. Eddit the file  `/Library/Ossec/etc/ossec.conf` adding the tag `local_ip`
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>darwin, darwin19</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
            <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
   ```

4. Restart the wazuh agent.

5. Check the agent's `/Library/Ossec/logs/ossec.log ` to verify the warning is not there
</details>

<details>
<summary>Windows  :green_circle:</summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| v4.5.0 | 40500 | https://github.com/wazuh/wazuh/tree/master | [agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html) | Agent | [Packages](https://github.com/wazuh/wazuh-qa/files/9031386/wazuh-agent-4.5.0-3002.local.ip.master.windows.zip)
 | Windows Server 2016 |


## Test Execution
1. Deploy a agent using a msi package on a Windows machine
2. Eddit the file  `C:\Program Files (x86)\ossec-agent\ossec.conf` adding the tag `local_ip`
   ```
   ...
	  <client>
		  <server>
	      <address>1xx.xxx.xx.xx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
		  </server>
		  <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
		  <crypto_method>aes</crypto_method>
		  <notify_time>10</notify_time>
		  <time-reconnect>60</time-reconnect>
		  <auto_restart>yes</auto_restart>
		  <local_ip>1xx.xxx.xx.xx</local_ip>
	  </client>
   ...
    ```
3. Restart the wazuh agent.

4. Check the agent's `C:\Program Files (x86)\ossec-agent\ossec.log` to verify the warning is not there

</details>

**Comment by QU3B1M** [comment]
# Enhancement of Warning message

As the code changes in commit [92fb381](https://github.com/wazuh/wazuh/pull/13878/commits/92fb381b85343049e8933967062294323b50d178) to apply this update were minimal (only one string was modified) and the previous changes have already been tested on different OS, the tests on Windows and MacOs are omitted.


## Test Execution - Package with the improvement  :green_circle:
1. Deploy a agent using a rpm package on a Centos machine
2. Edit the file  `/var/ossec/etc/ossec.conf` adding the tag `local_ip`
   ```
   ...

   <client>
     <server>
       <address>192.168.56.15</address>
       <port>1514</port>
       <protocol>tcp</protocol>
     </server>
     <config-profile>centos, centos8, centos8.5</config-profile>
     <notify_time>10</notify_time>
     <time-reconnect>60</time-reconnect>
     <auto_restart>yes</auto_restart>
     <crypto_method>aes</crypto_method>
     <local_ip>192.168.56.10</local_ip>
   </client>

   ...
   ```

4. Restart the wazuh agent.

5. Check the agent's `/var/ossec/logs/ossec.log` and verify the updated warning message appears.
   ```
   2022/07/26 16:30:30 wazuh-agentd: WARNING: The <local_ip> tag has no functionality, so it will have no effect.
   ```

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
