### ISSUE TITLE
E2E design and implementation: Brute Force - Third iteration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3004]
|Preivous issue| Develoment branch|
|:--:|:--:|
|#2889, #2932 |[2872-e2e-brute-force](https://github.com/wazuh/wazuh-qa/tree/2872-e2e-brute-force)|

## Description

This issue aims to finish the development started in https://github.com/wazuh/wazuh-qa/issues/2889.

## Tasks

- [x] PR Review
- [x] Apply requested changes
- [x] Merge

**Comment by BelenValdivia** [comment]
2022/06/15

- Requested changes in PR done

- Tests passed [here](https://github.com/wazuh/wazuh-qa/pull/2938#issuecomment-1156664722)
