### ISSUE TITLE
Check wazuh-authd random password generation

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3007]
| Related issue |
|---|
| wazuh/wazuh#13774|

# Description

It's desirable that wazuh-authd (Wazuh Manager) could generate random password and show it properly on ossec.log as fallback mechanism when [use_password](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#use-password) is set by password file (`/var/ossec/etc/authd.pass`) does not exist.

# Check
- Validate that password authentication still works if https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#use-password is set and the password file exists
- Validate that fallback random password generation works if https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#use-password is set and the password file does not exist
- No WARNING/ERROR messages should be generated

# Test cases

- [x] (**T1**): Manager with password file - Agent with deployment variable - Enrollment
- [x] (**T2**): Manager without password file - Agent with deployment variable - Enrollment
- [x] (**T3**): Manager with password file - Agent with password file - Enrollment
- [x] (**T4**): Manager without password file - Agent with password file - Enrollment
- [x] (**T5**): Manager with password file - Agent with password file - agent-auth
- [x] (**T6**): Manager without password file - Agent with password file - agent-auth
- [x] (**T7**): Manager with password file - Agent with password through console - agent-auth
- [x] (**T8**): Manager without password file - Agent with password through console - agent-auth
- [x] (**T9**): Manager with password file - Agent with deployment variable - agent-auth
- [x] (**T10**): Manager without password file - Agent with deployment variable - agent-auth

# Configuration details
PR: https://github.com/wazuh/wazuh/pull/13863

| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/13863/commits/38e3a76d7058890f4576c361795544eb1274713b| https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.4-0.commit38e3a76.x86_64.rpm| https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.4-0.commit38e3a76.x86_64.rpm |

**Comment by juliamagan** [comment]
| Type | OS | Package|
|:--:|:--:|--- |
|Manager|CentOS 8|https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.4-0.commita5d3e4e.x86_64.rpm|
|Manager| Ubuntu 20.04|https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.4-0.commita5d3e4e_amd64.deb


<details>

 <summary> Tester @juliamagan - <code>CentOS 8/Packages - File doesn't exist</code>  </summary>


Before upgrading - **4.3.4**


- `/var/ossec/logs/ossec.log`
```
2022/06/17 08:34:45 wazuh-authd: INFO: Started (pid: 60338).
2022/06/17 08:34:45 wazuh-authd: WARNING: String may be truncated because it is too long.
2022/06/17 08:34:45 wazuh-authd: INFO: Accepting connections on port 1515. Random password chosen for agent authentication: 12e6f7be080015150502f21c025b3a48
```

- Check `/var/ossec/etc/authd.pass`

```
[root@localhost vagrant]# cat /var/ossec/etc/authd.pass
cat: /var/ossec/etc/authd.pass: No such file or directory
[root@localhost vagrant]# find / -name authd.pass
[root@localhost vagrant]# 
```

After upgrading - **4.3.5**

- `/var/ossec/logs/ossec.log`

```
2022/06/17 08:56:03 wazuh-authd: INFO: Started (pid: 63989).
2022/06/17 08:56:03 wazuh-authd: INFO: Accepting connections on port 1515. Random password chosen for agent authentication: 152453e9ae65a47db6988311420bd1b1
```

- Check `/var/ossec/etc/authd.pass`
```
[root@localhost vagrant]# cat /var/ossec/etc/authd.pass
cat: /var/ossec/etc/authd.pass: No such file or directory
[root@localhost vagrant]# find / -name authd.pass
```

</details>


<details>

 <summary> Tester @juliamagan - <code>CentOS 8/Packages - File does exist</code> 🟢 </summary>


Before upgrading - **4.3.4**


- `/var/ossec/logs/ossec.log`
```
2022/06/17 09:15:43 wazuh-authd: INFO: Started (pid: 60277).
2022/06/17 09:15:43 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass
```

- Check `/var/ossec/etc/authd.pass`

```
[root@localhost vagrant]# cat /var/ossec/etc/authd.pass 
testingpassword
[root@localhost vagrant]# find / -name authd.pass
/var/ossec/etc/authd.pass
```

After upgrading - **4.3.5**

- `/var/ossec/logs/ossec.log`

```
2022/06/17 09:25:15 wazuh-authd: INFO: Started (pid: 63796).
2022/06/17 09:25:15 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass
```

- `/var/ossec/bin/wazuh-control status`
```
[root@localhost vagrant]# cat /var/ossec/etc/authd.pass 
testingpassword
[root@localhost vagrant]# find / -name authd.pass
/var/ossec/etc/authd.pass
```

</details>


 <details>

 <summary> Tester @juliamagan - <code>Ubuntu 20.04/Packages - File doesn't exist</code>  </summary>


Before upgrading - **4.3.4**


- `/var/ossec/logs/ossec.log`
```
2022/06/17 10:18:51 wazuh-authd: INFO: Started (pid: 142248).
2022/06/17 10:18:51 wazuh-authd: WARNING: String may be truncated because it is too long.
2022/06/17 10:18:51 wazuh-authd: INFO: Accepting connections on port 1515. Random password chosen for agent authentication: 11963f3fb5323dd88c254b935a97fb12
```

- Check `/var/ossec/etc/authd.pass`

```
root@test:/home/vagrant# cat /var/ossec/etc/authd.pass
cat: /var/ossec/etc/authd.pass: No such file or directory
root@test:/home/vagrant# find / -name authd.pass
root@test:/home/vagrant# 
```

After upgrading - **4.3.5**

- `/var/ossec/logs/ossec.log`

```
2022/06/17 10:46:13 wazuh-authd: INFO: Started (pid: 183140).
2022/06/17 10:46:13 wazuh-authd: INFO: Accepting connections on port 1515. Random password chosen for agent authentication: 3f6519f0425110306ceba907a399b969
```

- Check `/var/ossec/etc/authd.pass`
```
root@test:/home/vagrant# cat /var/ossec/etc/authd.pass 
cat: /var/ossec/etc/authd.pass: No such file or directory
root@test:/home/vagrant# find / -name authd.pass
root@test:/home/vagrant# 
```

</details>


 <details>

 <summary> Tester @juliamagan - <code>Ubuntu 20.04/Packages - File does exist</code> 🟢 </summary>


Before upgrading - **4.3.4**


- `/var/ossec/logs/ossec.log`
```
2022/06/17 11:19:26 wazuh-authd: INFO: Started (pid: 181786).
2022/06/17 11:19:26 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass
```

- Check `/var/ossec/etc/authd.pass`

```
root@test:/home/vagrant# cat /var/ossec/etc/authd.pass 
testingpassword
root@test:/home/vagrant# find / -name authd.pass
/var/ossec/etc/authd.pass
```

After upgrading - **4.3.5**

- `/var/ossec/logs/ossec.log`

```
2022/06/17 11:27:15 wazuh-authd: INFO: Started (pid: 222446).
2022/06/17 11:27:15 wazuh-authd: INFO: Accepting connections on port 1515. Using password specified on file: etc/authd.pass
```

- Check `/var/ossec/etc/authd.pass`
```
root@test:/home/vagrant# cat /var/ossec/etc/authd.pass 
testingpassword
root@test:/home/vagrant# find / -name authd.pass
/var/ossec/etc/authd.pass
```

</details>

**Comment by juliamagan** [comment]
## Check that the enrollment is still working

### Ubuntu 20.04

<details>
<summary>Tester @juliamagan - <code>(<b>T1</b>): Manager with password file - Agent with deployment variable - Enrollment </code> 🟢 </summary>

**Agent**

- `/var/ossec/logs/ossec.log`:

```
2022/06/20 15:56:03 wazuh-agentd: INFO: Started (pid: 4444).
2022/06/20 15:56:03 wazuh-agentd: INFO: Server IP Address: 172.17.1.12
2022/06/20 15:56:03 wazuh-agentd: INFO: Requesting a key from server: 172.17.1.12
2022/06/20 15:56:03 wazuh-agentd: INFO: Using password specified on file: etc/authd.pass
2022/06/20 15:56:03 wazuh-agentd: INFO: Using agent name as: c3
2022/06/20 15:56:03 wazuh-agentd: INFO: Waiting for server reply
2022/06/20 15:56:03 wazuh-agentd: INFO: Valid key received
.
.
.
2022/06/20 15:56:23 wazuh-agentd: INFO: Trying to connect to server (172.17.1.12:1514/tcp).
2022/06/20 15:56:23 wazuh-agentd: INFO: (4102): Connected to the server (172.17.1.12:1514/tcp).
```


**Manager**

- `/var/ossec/logs/ossec.log`:

```
2022/06/20 15:19:14 wazuh-authd: INFO: New connection from 172.17.1.18
2022/06/20 15:19:14 wazuh-authd: INFO: Received request for a new agent (c3) from: 172.17.1.18
2022/06/20 15:19:14 wazuh-authd: INFO: Agent key generated for 'c3' (requested by any)
2022/06/20 15:19:24 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/06/20 15:19:24 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

- `/var/ossec/bin/agent_control -l`:

```
root@test:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: test (server), IP: 127.0.0.1, Active/Local
   ID: 004, Name: c3, IP: any, Active
```

</details>
