### ISSUE TITLE
Validate `integrity_clear` 4.4 backport

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3008]
| Related issue |
|---|
| wazuh/wazuh#13876|

## Description

We have seen that the `integrity_clear` command isn't sent by syscollector when the database is empty. 

# Steps to reproduce
- Install only one hotfix.
- Start the Wazuh agent and wait until the manager database is updated.
- Shutdown the Wazuh agent and uninstall the service pack (hotfix).
- Start the Wazuh agent and check that the command is sent.
- Also, check the manager database the entries are removed.

## Configuration details
PR: https://github.com/wazuh/wazuh/pull/13877
| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/13877/commits/121f0b4a740ceb9a574ce297742f076e0b045674| https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit121f0b4.x86_64.rpm | https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit121f0b4.el5.x86_64.rpm |

**Comment by QU3B1M** [comment]
# Testing using unfixed wazuh-agent :red_circle: 

<details>
<summary>Details</summary>

- On a Windows XP machine with an unfixed wazuh-agent and no hotfixes installed, stop the wazuh-agent and install **one** hotfix
- Start the wazuh-agent and check the manager database is updated:
   ```sql
   sqlite> select * from sys_hotfixes;
   0|2022/08/26 12:56:55|KB4024323|3dcb55dc0cad431a6d9645475f4eb0a7d5b724e6
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%"
   0|2022/08/26 12:56:55|win|Security Update for Windows XP (KB4024323)|||0|Microsoft Corporation|20220826|1|x86_64|||||0|||b1297de883a250f011b2683d0cd8f0c0b74773fc|f462ed3df1399acce4a6da6ac3e28b97eb49215c
   ```
- Stop the wazuh-agent and delete the hotfix
- Start the wazuh-agent and check in the wazuh-manager database the hotfix is not listed :red_circle:  
   ```sql
   sqlite> select * from sys_hotfixes;
   0|2022/08/26 12:56:55|KB4024323|3dcb55dc0cad431a6d9645475f4eb0a7d5b724e6
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%"
   ```

</details>

**Comment by QU3B1M** [comment]
# Testing the wazuh-agent upgrade to the fixed version :green_circle: 

<details>
<summary>Details</summary>

- On a Windows XP machine with an unfixed wazuh-agent and no hotfixes installed, stop the wazuh-agent and install **one** hotfix
- Start the wazuh-agent and check the manager database is updated:
   ```sql
   sqlite> select * from sys_hotfixes;
   0|2022/08/26 14:06:15|KB4024323|3dcb55dc0cad431a6d9645475f4eb0a7d5b724e6
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%";
   0|2022/08/26 14:06:15|win|Security Update for Windows XP (KB4024323)|||0|Microsoft Corporation|20220826|1|x86_64|||||0|||b1297de883a250f011b2683d0cd8f0c0b74773fc|f462ed3df1399acce4a6da6ac3e28b97eb49215c
   ```
- Stop the wazuh-agent and delete the hotfix
- Start the wazuh-agent and check in the wazuh-manager database the hotfix is not listed :green_circle: :  
   ```sql
   sqlite> select * from sys_hotfixes;
   sqlite> 
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%";
   sqlite> 
   ```

</details>

**Comment by QU3B1M** [comment]
# Testing the wazuh-agent upgrade to the fixed version :green_circle: 

<details>
<summary>Details</summary>


On a Windows XP machine with a fixed  wazuh-agent and no hotfixes installed
 - Stop the wazuh-agent and install **one** hotfix
 - Start the wazuh-agent and check the manager database is updated:
   ```sql
   sqlite> select * from sys_hotfixes;
   0|2022/08/26 15:02:59|KB4024323|3dcb55dc0cad431a6d9645475f4eb0a7d5b724e6
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%";
   0|2022/08/26 15:02:59|win|Security Update for Windows XP (KB4024323)|||0|Microsoft Corporation|20220826|1|x86_64|||||0|||b1297de883a250f011b2683d0cd8f0c0b74773fc|f462ed3df1399acce4a6da6ac3e28b97eb49215c
   ```
 - Stop the wazuh-agent and delete the hotfix
 - Start the wazuh-agent and check in the wazuh-manager database the hotfix is not listed :green_circle: :  
   ```sql
   sqlite> select * from sys_hotfixes;
   sqlite> 
   ```
   ```sql
   sqlite> select * from sys_programs where name like "%Update%";
   sqlite> 
   ```

</details>
