### ISSUE TITLE
tests/integration/README.md is outdated

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh-qa#3010]
Setting up a test environment on CentOS 8 following the instructions at tests/integration/README.md, I have run into some problems with missing packages and modules.

The steps that worked for me were:

- Install dependencies:
yum install make gcc **policycoreutils-python-utils** automake autoconf libtool epel-release git which sudo wget -y

- Install development dependencies for jq library
yum groupinstall "Development Tools" -y

- Install Python3
yum install python36 **python3-pip** python36-devel -y

- Clone repository
**- Install requirements
python3 -m pip install -r requirements.txt**

- Install framework
python3 deps/wazuh_testing/setup.py install

**Suggestions:**
- Under “Add some internal options” refer to the Parameters Guide on the Wiki.
- On “FIM integration tests examples” the path to the test is wrong, it should be test_fim/test_files/test_basic_usage/test_basic_usage_create_scheduled.py

**Comment by damarisg** [comment]
We decided to close them.
