### ISSUE TITLE
Manual testing - Github integration scan messages enrichment

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-qa#3013]
|Related issue|Branch|Documentation|
|---|---|---|
|https://github.com/wazuh/wazuh/issues/13784|[dev-github-first-scan-message](https://github.com/wazuh/wazuh/tree/dev-github-first-scan-message)|https://github.com/wazuh/wazuh-documentation/pull/5357|

### Description

In order to validate the changes of the branch [dev-github-first-scan-message](https://github.com/wazuh/wazuh/pull/13898), some manual testing of the feature is required.
The goal of this change is encrease the information about how Github integration works.
2 new messages are added, one when first scan runs, with the legend Bookmark updated to '2022-06-16T18:21:58Z', waiting '60' seconds to run first scan, where the first date is the UTC date as the API request to Github server, and the '60' seconds are the interval time. Second message is similar than first, it only change the word next instead the word first, and it shows when bookmark is updated. Bookmark updated to '2022-06-16T18:21:58Z', waiting '60' seconds to run next scan

```
<github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>30s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>dummy</org_name>
        <api_token>dummy</api_token>
    </api_auth>
    <api_parameters>
        <event_type>all</event_type>
    </api_parameters>
</github>
```

**Comment by Rebits** [comment]
|Wazuh Branch| Wazuh Package |OS|
|--|--|--|
| [dev-github-first-scan-message ](https://github.com/wazuh/wazuh/tree/dev-github-first-scan-message)|[RPM](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.4-vr.qa.3013.x86_64.rpm)|Centos8|

### Preconditions


<details>

<summary> ossec.conf </summary>

```
<github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name><ORG_NAME></org_name>
        <api_token><API_TOKEN></api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
</github>
```

</details>

**Comment by jmv74211** [comment]
Everything seems to work properly 🟢 . It has been proposed a suggestion [here](https://github.com/wazuh/wazuh/issues/13944#issuecomment-1164168755)
