### ISSUE TITLE
Manual testing - Modify Amazon Linux 2 SCA policy to resolve typo on control 1.1.22 and EMPTY_LINE conditions

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3014]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13744 | https://github.com/wazuh/wazuh/pull/13781 |

## Test cases

Using an Amazon Linux 2 system running a wazuh-agent we need to verify at least:

- [x] Ensure list of controls works properly   
  - [x] 1.1.22 Ensure sticky bit is set on all world-writable directories.
  - [x] 1.5.2 Ensure XD/NX support is enabled.
  - [x] 3.5.2.4 Ensure iptables are flushed with nftables.
  - [x] Policy doesn't create the ```/dev/nul``` file

**Comment by Rebits** [comment]
|Wazuh Branch| Wazuh Package |OS|
|--|--|--|
| [4.3 ](https://github.com/wazuh/wazuh/tree/4.3)|[RPM](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-agent-4.3.5-qa.vr.3014.x86_64.rpm)|Centos8|

# Preconditions

<details>


- Wazuh manager in amazonlinux2 host
- Wazuh agent in amazonlinux2 host
- Enable the SCA module in the Wazuh agent
```
  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>
``` 


</details>

# Test Cases
## Ensure sticky bit is set on all world-writable directories :large_blue_circle: 
## Ensure XD/NX support is enabled :large_blue_circle: 
## Ensure iptables are flushed with nftables :large_blue_circle: 
## Policy doesn't create the /dev/nul file :large_blue_circle:

**Comment by jmv74211** [comment]
New changes have been tested [here](https://github.com/wazuh/wazuh/pull/13950#issuecomment-1164267230). Tested changes are approved 🟢 .
