### ISSUE TITLE
Manual testing - Abort the enrollment process if the manager couldn't be verified.

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#3016]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13772|https://github.com/wazuh/wazuh/pull/13907|

## Description

The goal of this issue is to manually test the change in `wazuh-authd` to cancel the enrollment process in case the agent couldn't verify the manager. 

## Test cases

- [x] Check that the agent connects to the manager without verifying its identity.
- [x] Check that the agent connects to the manager verifying its identity.
- [x] Check that the agent doesn't connect to the manager if it cannot verify the manager's identity.

## Configuration and considerations

To enable the manager's identity, I have followed this guide https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/manager-identity-verification.html.

**Comment by jmv74211** [comment]
The following issue  https://github.com/wazuh/wazuh/issues/13936 has been opened to propose an improvement in the description of log `wazuh-authd: ERROR: SSL Error (-1)`, as it is quite confusing.
