### ISSUE TITLE
Check fix to the race condition in wazuh-modulesd

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3018]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13805|https://github.com/wazuh/wazuh/pull/13883|

As detailed in the issue, the current version of wazuh-modulesd is susceptible to crashing if it gets stopped while Vulnerability Detector is fetching a feed. The race condition always occurs, but the process very rarely crashes.

We need to confirm that this patch works and has no collateral effects.

**Comment by CamiRomero** [comment]
@vikman90 According to the research that we did, we know that the issue does not occur every time. So, it would be very helpful if you can share with us which steps you follow to reproduce the issue (at less one time). We try to reproduce it on 4.3.4 but we couldn't reproduce it.

Also, we will test some modules like:

- Fluent Forwarder
- Agent Upgrade
- GitHub Integration
- Office365 Integration

**Comment by CamiRomero** [comment]
# Test Agent Upgrade tool

### Validate the correct operation of Agent Upgrade tool on `13805-fix-segfault-modulesd`

<details>
<summary>Package details</summary>

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| [4.3.5](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.5-0.commited336e1.x86_64.rpm) | 40317 | [Agent-Upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Manager | Packages | CentOS-8 |
| [4.3.3 ](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.5-0.commited336e1.x86_64.rpm)| 40315 | [Agent-Upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Agent | Packages | CentOS-8 |

</details>
<details>
<summary>Test Virus total integration :red_circle: </summary>

1. Check version of Wazuh agent

    ```
    /var/ossec/bin/wazuh-control info
    WAZUH_VERSION="v4.3.3"
    WAZUH_REVISION="40315"
    WAZUH_TYPE="agent"
    ```

3. List outdated agents on manager:
    ```
      /var/ossec/bin/agent_upgrade -l
     ID    Name                                Version                  
     002   centos-agent1                       Wazuh v4.3.3             
     
     Total outdated agents: 1
    ```

4. Upgrade agent:
    ```
    var/ossec/bin/agent_upgrade -a 002
      
    Upgrading...
    
    Failed upgrades:
	    Agent 002 status: The version of the WPK does not exist in the repository
    ``

**Comment by CamiRomero** [comment]
# Test Fluentd forwarder

### Validate the correct operation of Fluentd forwarder  on `13805-fix-segfault-modulesd`

<details>
<summary>Package details</summary>

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| [4.3.5](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.5-0.commited336e1_amd64.deb) | 40317 | [Fluentd forwarder](https://documentation.wazuh.com/current/user-manual/capabilities/fluent-forwarder.html?highlight=fluent%20forwarder#fluentd-forwarder) | Manager | Packages | Ubuntu |

</details>
<details>
<summary>Test Fluentd forwarder :green_circle: </summary>

1. Enable Fluent Forwarder in `/var/ossec/etc/ossec.conf`:
    ```
    <fluent-forward>
      <enabled>yes</enabled>
      <tag>debug.test</tag>
      <socket_path>/var/run/fluent.sock</socket_path>
      <address>localhost</address>
      <port>24224</port>
    </fluent-forward>
    ```
2. Set up the socket for logcollector:
    ```
    <socket>
      <name>fluent_socket</name>
      <location>/var/run/fluent.sock</location>
      <mode>udp</mode>
    </socket>
    ```
3. Set up a localfile to read from:
    ```
    <localfile>
      <log_format>syslog</log_format>
      <location>PATH_TO_LOG</location>
      <target>fluent_socket</target>
    </localfile>
    ```
4. Run on a terminal to set up and run  `Fluentd server`:
    ```
    apt-get install -y ruby ruby-dev
    gem install fluentd
    fluentd -s conf
    fluentd -c conf/fluent.conf
    ```
5. Restart the Wazuh manager:
6. Write a string to your log file:
    ```
    echo "Test Fluentd forwarder" >> PATH_TO_LOG
    ```
7. See the message on the Fluentd server:
    ```
    2022-06-22 14:53:09.000000000 +0000 debug.test: {"message":"Test Fluentd forwarder"
    ```
8. Check if `modulesd` is running:
    ```
    /var/ossec/bin/wazuh-control status
    wazuh-clusterd not running...
    wazuh-modulesd is running...
    ```

**Comment by Rebits** [comment]
# Test Github Integration :green_circle: 
Using the same configuration than https://github.com/wazuh/wazuh-qa/issues/3018#issuecomment-1163349735, Github integration seems to work correctly.

<details>

<summary> ossec.conf </summary>

```
<github>
    <enabled>yes</enabled>
    <interval>10s</interval>
    <time_delay>30s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name>ORG</org_name>
        <api_token>TOKEN</api_token>
    </api_auth>
    <api_parameters>
        <event_type>all</event_type>
    </api_parameters>
</github>
```

</details>

The error presented in [this](https://github.com/wazuh/wazuh-qa/issues/3018#issuecomment-1163349735) commentary is produced because the organization is not [GitHub Enterprise Cloud](https://docs.github.com/en/enterprise-cloud@latest/get-started/signing-up-for-github/setting-up-a-trial-of-github-enterprise-cloud). This requirement is specified in the Github Integration [documentation page](https://documentation.wazuh.com/current/github/monitoring-github-activity.html?highlight=github)

**Comment by jmv74211** [comment]
No related problems have been found. Approved 🟢
