### ISSUE TITLE
E2E design and implementation: Vulnerability Detector

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3038]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2863). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion
Tests implemented locally (Linux and Windows)

**Comment by BelenValdivia** [comment]
7/11
Worked on this [branch](https://github.com/wazuh/wazuh-qa/tree/3038-e2e-test-vulnerability-detetctor)
Linux(Ubuntu):
- Configuration yaml -> DONE
- Generate events yaml -> DONE
- Cases yaml -> DONE
Test passed on Ubuntu.

**Comment by BelenValdivia** [comment]
7/12
- Test linux improved

**Comment by BelenValdivia** [comment]
7/13
- Started VDT Windows test
- Reseatched hoy to generate event in windiws with ansible

**Comment by BelenValdivia** [comment]
7/14
PR to review: https://github.com/wazuh/wazuh-qa/pull/3090
