### ISSUE TITLE
Tests development - WazuhDB: Clean artifacts function wrongly deletes diff folder.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3041]
| Target version | Component | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|----------|
| 4.4.0              | |https://github.com/wazuh/wazuh/issues/13875                       |https://github.com/wazuh/wazuh/pull/13892                  |

## Description

The module `wm_database` during the synchronization deletes artifacts from old agents. The artifacts include agent database at `/var/ossec/var/db/agents/<agent_db>` and information at `/var/ossec/queue/diff/<agent_hostname>`
The `clean_artifacts()` function verifies the non-existence of an agent in the `global.db` to perform the cleaning, but when it does not exist, it uses that agent name value (empty string) to delete the previously mentioned files deleting the diff folder.

Type | Value
-- |-- |
**Debug mode** | 2

## Proposed test cases

<details>
  <summary>Case 1: Attempt to clean artifacts when the agent exists in global database (nothing should be removed)</summary>

### Settings 
  
        ```
        <!-- On the manager side -->
        
      <remote>
          <connection>secure</connection>
          <port>1514</port>
          <protocol>tcp</protocol>
          <queue_size>131072</queue_size>
          <local_ip>192.168.0.12</local_ip>
        </remote>
        ```
         
  Note: I set local_ip, in the remote section of the admin, to the ip of the second network interface.
      
  In the address section of the server block of the agent configuration, I configured the ip of the first interface of the manager, in this way the agent will be able to register but not connect
      
      ```
      <server>
          <address>10.0.0.2</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
      ```
 
   ### Steps 

    - The agent register for the first time.
    - If the agent tries to connect and fails, it will ask for a new password
    - Check the manager logs the message: 
    - The agent requested the key again the queue/diff directory will be deleted
        `WARNING: Duplicate name 'agent-ubuntu', rejecting enrollment. Agent 'xxx' doesn't comply ....`
    - Remove the agent using the manage-agent tool
    
   ### Check 

  - The following errors are NOT displayed.

      ```  
        2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
        2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
        2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
        2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
      ```

</details>  

<details>
  <summary>Case 2: Attempt to clean artifacts when the agent is not present in the global database (artifacts should be removed without analysis errors and keeping the root diff folder intact) </summary>

### Settings 
  
        ```
        <!-- On the manager side -->
        
      <remote>
          <connection>secure</connection>
          <port>1514</port>
          <protocol>tcp</protocol>
          <queue_size>131072</queue_size>
          <local_ip>192.168.0.12</local_ip>
        </remote>
        ```
         
  Note: I set local_ip, in the remote section of the admin, to the ip of the second network interface.
      
  In the address section of the server block of the agent configuration, I configured the ip of the first interface of the manager, in this way the agent will be able to register but not connect
      
      ```
      <server>
          <address>10.0.0.2</address>
          <port>1514</port>
          <protocol>tcp</protocol>
        </server>
      ```
 
   ### Steps 

- Let the agent register for first time
- Stop Wazuh service
- Delete entry in global database for the agent
- Delete entry in client.keys for the agent
- Start Wazuh service
   
  
### Check 

  - The following errors are NOT displayed.
    ```  
      2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
      2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
      2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
      2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
    ```

The steps in the second approach explicitly force the non-existence of an agent in the global database which returns the empty string causing the issue.  

</details>  

# Development stage

- [ ] In research
- [ ] In development
    - [ ] Linux
- [ ] In testing phase
    - [ ] Linux
- [ ] In Review
- [ ] Completed

**Comment by davidjiglesias** [comment]
The issue is about ensuring that the wm_database module correctly deletes artifacts related to old agents. The test case aims to validate the behavior of the overall system under specific scenarios, such as the existence or non-existence of an agent in the global database. It doesn't focus on the interaction between the wm_database module and other individual components of the system, which would be the case in integration testing.

The test cases are not looking at specific interactions between components, but rather, they are verifying the system's expected behavior under certain scenarios. The test case also includes setting specific configurations and validating the behavior of the whole system in response to these configurations. Hence, it fits into the category of system testing.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
