### ISSUE TITLE
QA testing - Remoted statistics - sent_bytes

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh-qa#3046]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.5        | https://github.com/wazuh/wazuh/issues/13953 | https://github.com/wazuh/wazuh/pull/13979 |

## Description

A manager with version 4.3.x sending messages to agents using **UDP** protocol does not increment the value of `sent_bytes` in the state file for wazuh-remoted. After every sent message this value should be incremented by the actual amount of bytes sent to the agent.
This [PR](https://github.com/wazuh/wazuh/pull/13979) fixes this issue. 

## Proposed checks

- [x] The value of sent_bytes never increases when sending messages through UDP with manager v4.3.x.
- [x] Validate that the proposed fix updates sent_bytes correctly.

## Steps to reproduce

1. Configure manager to communicate with agents using **UDP** protocol.
2. Configure agent to communicate with manager using **UDP** protocol. Use only one agent to see the effect more clearly.
3. Check that the agent connects to the manager.
4. Check the wazuh-remoted state file at var/ossec/var/run/wazuh-remoted.state
![Screenshot from 2022-06-22 15-23-40](https://user-images.githubusercontent.com/7939712/175115990-6ff2825a-36ea-409c-89b6-d36c0d9fe424.png)
5. The value of sent_bytes remains at '0', it never increases. By comparison recv_bytes increases regularly.

## Expected results

 The value of sent_bytes increases with every UDP message sent to an agent.

## Configuration and considerations

PR: https://github.com/wazuh/wazuh/pull/13979
| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/13979/commits/f9aa5464d1aaa96eecf702d10527c03a308309fd | https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-agent_4.5.0-0.commitf9aa546_amd64.deb | https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commitf9aa546_amd64.deb https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/rpm/var/wazuh-manager-4.5.0-0.commitf9aa546.x86_64.rpm |

#### Manager configuration
/var/ossec/etc/ossec.conf 
```
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>udp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```

#### Agent configuration
/var/ossec/etc/ossec.conf 
```
  <client>
    <server>
      <address>MANAGER_IP</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    ...
  </client>
```

### Systems Details
| RPM OS | Vagrant Box | Deb OS | Vagrant Box|
|--|--|--|--|
| Centos 8 | qactl/centos8 | Ubuntu2022 | qactl/ubuntu20_04 |

**Comment by Deblintrake09** [comment]
<details>
<summary>Check that the value for sent_bytes does not increase in v4.3.5 :green_circle: </summary>

- Start manager with no agent
- Check state file
   ```
   cat /var/ossec/var/run/wazuh-remoted.state 
   # State file for wazuh-remoted
   # Updated every 5 seconds.

   # Queue size
   queue_size='0'

   # Total queue size
   total_queue_size='131072'

   # TCP sessions
   tcp_sessions='0'

   # Events sent to Analysisd
   evt_count='0'

   # Control messages received
   ctrl_msg_count='0'

   # Discarded messages
   discarded_count='0'

   # Messages queued
   queued_msgs='0'

   # Total number of bytes sent
   sent_bytes='0'

   # Total number of bytes received
   recv_bytes='0'

   # Messages dequeued after the agent closes the connection
   dequeued_after_close='0'
   ```
- Start agent
   ```
   [root@c3 vagrant]# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.3.5...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
- Check that agent is communicating with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l

   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: Linux1, IP: any, Active
   ```
- Check remoted.state file
   ```
   [root@c3 vagrant]# cat /var/ossec/var/run/wazuh-remoted.state 
   # State file for wazuh-remoted
   # Updated every 5 seconds.
   
   # Queue size
   queue_size='0'

   # Total queue size
   total_queue_size='131072'

   # TCP sessions
   tcp_sessions='0'

   # Events sent to Analysisd
   evt_count='3009'

   # Control messages received
   ctrl_msg_count='23'

   # Discarded messages
   discarded_count='0'

   # Messages queued
   queued_msgs='0'

   # Total number of bytes sent
   sent_bytes='0'

   # Total number of bytes received
   recv_bytes='1284016'

   # Messages dequeued after the agent closes the connection
   dequeued_after_close='0'
   ```
</details>

<details>
<summary></summary>

- Start manager with no agent
- Check state file
```
cat /var/ossec/var/run/wazuh-remoted.state 
# State file for wazuh-remoted
# Updated every 5 seconds.

# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='0'

# Events sent to Analysisd
evt_count='0'

# Control messages received
ctrl_msg_count='0'

# Discarded messages
discarded_count='0'

# Messages queued
queued_msgs='0'

# Total number of bytes sent
sent_bytes='0'

# Total number of bytes received
recv_bytes='0'

# Messages dequeued after the agent closes the connection
dequeued_after_close='0'
```
- Start agent
```
[root@c3 vagrant]# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.5...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```
- Check that agent is communicating with manager
```
[root@c3 vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: Linux1, IP: any, Active
```
- Check remoted.state file
```
[root@c3 vagrant]# cat /var/ossec/var/run/wazuh-remoted.state 
# State file for wazuh-remoted
# Updated every 5 seconds.

# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='0'

# Events sent to Analysisd
evt_count='3009'

# Control messages received
ctrl_msg_count='23'

# Discarded messages
discarded_count='0'

# Messages queued
queued_msgs='0'

# Total number of bytes sent
sent_bytes='0'

# Total number of bytes received
recv_bytes='1284016'

# Messages dequeued after the agent closes the connection
dequeued_after_close='0'
```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
