### ISSUE TITLE
Tests development - Backport the integration tests for supporting Ubuntu 22 in Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#3047]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|         4.3.6               |      https://github.com/wazuh/wazuh/issues/14084                  |       https://github.com/wazuh/wazuh/pull/14085             |

## Description

Hi team,

The goal of this issue is to backport the integration tests defined at
- https://github.com/wazuh/wazuh-qa/issues/2836
Included in this pull request:
- https://github.com/wazuh/wazuh-qa/pull/2957

The development was originally merged for 4.4 but it has been requested to backport it to 4.3.6.

Here are the corresponding issues in the product repository:
- https://github.com/wazuh/wazuh/issues/14084
- https://github.com/wazuh/wazuh/pull/14085

## Configurations

N/A

## Proposed test cases

N/A

## Considerations

N/A

**Comment by jmv74211** [comment]
All the requested changes has been added in the branch `4.3-vulnerability-detector` of this repository, in this commit 8fa8b649ef641632ef3eb93c4845934c6036360d.

The Jenkins ITs has been passed successfully, so this issue is done 🟢
