### ISSUE TITLE
QA testing - Duplicate entries in syscollector tables agent database (manager side)

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3055]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
| 4.3.6                      |https://github.com/wazuh/wazuh/issues/13886                        | https://github.com/wazuh/wazuh/pull/14061                   |

## Description
Under some circumstances, the system inventory tables in the agent database show duplicate information. As consequence, the vulnerability detector module fails with synchronization error messages when attempts to get information from  `sys_hotfixes` and `sys_programs`.

`"(5473): Hotfixes data not synchronized in agent '%.3d' database."`
`"(5507): The software of the agent '%.3d' could not be obtained after %d attempts. Skipping agent until the next scan."`

But all the tables that receive "integrity_check_global" data may suffer the same problem.

![image](https://user-images.githubusercontent.com/13010397/176899825-b9c47d62-df40-437d-82a1-6ecfba6c6661.png)

The changes are the following:

- Removed `scan_time` attribute from `sys_hotfixes` PK.
- Delete duplicate information if we get multiple checksums when only one is expected.
- Delete information prior `insert or replace`. This is because SQLite doesn't understand a replace action should be performed when NULL values are part of the PK and it adds a new duplicate register.

## Configurations

Enable vulnerability detector to verify it works.

Check the issue to find the steps to reproduce this behavior. Also in the PR there are some manual tests.

## Proposed test cases

- [x] Duplicate entries in syscollector tables agent database on 4.3.5
- [x] Duplicate entries in syscollector tables agent database on 4.3.6
- [x] Duplicate entries in syscollector tables agent database after upgrade Wazuh from 4.3.5 to 4.3.6

**Comment by CamiRomero** [comment]
## Review data

| Tester | PR commit               | Conclusion                   |
|--------|-------------------------|------------------------------|
| @CamiRomero  |   [88648](https://github.com/wazuh/wazuh/pull/14061/commits/8864891d919627339c691f2f1e77b6e1e6b2356f)  | :yellow_circle: (In Progress) |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|    [4.3.6 ](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit8864891.x86_64.rpm)           |     [4.3.6 ](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.6-0.commit8864891.x86_64.rpm)         |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by CamiRomero** [comment]
## Duplicate entries in syscollector tables agent database on 4.3.6

<details>
<summary>Duplicate entries in syscollector tables agent database on 4.3.6 :green_circle: </summary>

1. Configure a vulnerability detector in the Wazuh Manager
    ```
    <vulnerability-detector>
        <enabled>yes</enabled>
        <interval>5m</interval>
        <min_full_scan_interval>6h</min_full_scan_interval>
        <run_on_start>yes</run_on_start>
        ... 
    ```
2. Restart Wazuh Manager in order to apply the changes:
    ```
    /var/ossec/bin/wazuh-control restart
    ```
    Output:
    ```
    wazuh-clusterd not running...
    Killing wazuh-modulesd...
    Killing wazuh-monitord...
    Killing wazuh-logcollector...
    Killing wazuh-remoted...
    Killing wazuh-syscheckd...
    Killing wazuh-analysisd...
    wazuh-maild not running...
    Killing wazuh-execd...
    Killing wazuh-db...
    Killing wazuh-authd...
    wazuh-agentlessd not running...
    wazuh-integratord not running...
    wazuh-dbd not running...
    wazuh-csyslogd not running...
    Killing wazuh-apid...
    Wazuh v4.3.5 Stopped
    Starting Wazuh v4.3.5...
    Started wazuh-apid...
    Started wazuh-csyslogd...
    Started wazuh-dbd...
    2022/06/03 14:46:35 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
    Started wazuh-integratord...
    Started wazuh-agentlessd...
    Started wazuh-authd...
    2022/06/03 14:46:36 wazuh-db[52233] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
    2022/06/03 14:46:36 wazuh-db[52233] main.c:101 at main(): DEBUG: Wazuh home directory: /var/ossec
    Started wazuh-db...
    Started wazuh-execd...
    Started wazuh-analysisd...
    Started wazuh-syscheckd...
    Started wazuh-remoted...
    Started wazuh-logcollector...
    Started wazuh-monitord...
    Started wazuh-modulesd...
    Completed.
    ```

3. Install Microsoft SQL Server 2014 software on Windows agent:
     ```
    choco install mssqlserver2014express
     ```
    Output:
    ```
    The install of mssqlserver2014express was successful.
    ```

4. Restart the Wazuh Agent to trigger a Syscollector scan:
5. Check sys_program table:
    ```
    sqlite3 001.db '.mode line' 'select count(*) from sys_programs where version is null'
    ```

    Output:
    ```
    count(*) = 1
    ```
6. Obtain all the info of sys_programs table:
    ```
    sqlite3 001.db '.mode line' 'select * from sys_programs where version is null'
    ```

    Output:
     ```
     scan_id = 0
       scan_time = 2022/06/15 19:40:36
          format = win
            name = Microsoft SQL Server 2014 (64-bit)
        priority = 
         section = 
            size = 0
          vendor = Microsoft Corporation
    install_time = 
         version = 
    architecture = x86_64
       multiarch = 
          source = 
     description = 
        location = 
         triaged = 0
             cpe = 
        msu_name = 
        checksum = 2d4009216d12de6cd8c724ee7ea7ac26c9c9a248
         item_id = 8f5ddd791086145b57fa32ccd02c15ed4952698a
    ```
7. Stop the Wazuh Manager:
    ```
    /var/ossec/bin/wazuh-control stop
    ```
    Output:
    ```
    wazuh-clusterd not running...
    wazuh-modulesd: Process 52431 not used by Wazuh, removing...
    wazuh-modulesd not running...
    Killing wazuh-monitord...
    Killing wazuh-logcollector...
    Killing wazuh-remoted...
    Killing wazuh-syscheckd...
    Killing wazuh-analysisd...
    wazuh-maild not running...
    Killing wazuh-execd...
    Killing wazuh-db...
    Killing wazuh-authd...
    wazuh-agentlessd not running...
    wazuh-integratord not running...
    wazuh-dbd not running...
    wazuh-csyslogd not running...
    Killing wazuh-apid...
    Wazuh v4.3.5 Stopped
    ```
8. Executing the query to duplicate entry using the information obtained in step 7:
    ```
    INSERT INTO sys_programs (scan_id, scan_time, format, name, priority, section, size, vendor, install_time, version, architecture, multiarch, source, description, location, triaged, checksum, item_id) VALUES (0, "2022/07/12 23:21:46", "win", "Microsoft SQL Server 2014 (64-bit)", null, null, 0, "Microsoft Corporation", null, null, "x86_64", null, null, null, null, 0, "2d4009216d12de6cd8c724ee7ea7ac26c9c9a248", "8f5ddd791086145b57fa32ccd02c15ed4952698a");
    ```
9. Restart the Wazuh Manager:
10. Check sys_program table to check if the information was inserted:
    ```
    sqlite3 /var/ossec/queue/db/001.db '.mode line' 'select count(*) from sys_programs where version is null'
    ```
    ```
    Output:
    count(*) = 2
    ```
11. Restart  the Wazuh Agent to force a synchronization.
12. Check sys_program table to check if the information was duplicated:
    ```
    sqlite3 /var/ossec/queue/db/001.db '.mode line' 'select count(*) from sys_programs where version is null'
    ```
    ```
    Output:
    count(*) = 1
    ```
13. Check for error/warning logs in `/var/ossec/logs/ossec.log`:
    ```
    [root@centos-manager3 vagrant]# cat /var/ossec/logs/ossec.log | grep "Hotfixes data not synchronized in agent"
    [root@centos-manager3 vagrant]# cat /var/ossec/logs/ossec.log | grep "The software of the agent"
    [root@centos-manager3 vagrant]# 

    ```


</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
