### ISSUE TITLE
Get memory usage metrics for File Integrity Monitoring

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#306]
|Version|Branch|
|---|---|
|3.11 + FIM rework|[3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)|
|3.10.2|[stable](https://github.com/wazuh/wazuh/tree/stable)|

## Goals

- How much does the number of files impact on memory?
- How does the configuration impact on memory?

## Configuration

- Disable every component in the agent but Syscheck.

## Matrix

- Number of 10 KiB files:
  - 0 files.
  - 10K files.
  - 20K files. 
  - 50K files.
  - 100K files.
  - 200K files.
  - 500K files.
  - 1M files.
- Size of the path:
  - 8 byte paths: `/x/yyyyy`.
  - ~4000 byte paths.
- Attributes:
  - Check nothing.
  - Check size.
  - Check status: size + permissions + owner + group + mtime + inode.
  - Check status + MD5.
  - Check status + MD5 + SHA1.
  - Check everything: status + MD5 + SHA1 + SHA256.
- Platforms:
  - Linux.
  - macOS.
  - Windows.

## Target

Datasheet including the memory used by the process (_Syscheckd_ on Linux/macOS, and _ossec-agent.exe_ on Windows), at the moment when the scan finishes.

**Comment by DaveVG1** [comment]
In sum, this is the memory comparisons between new FIM, 3.10.2 FIM and new FIM without `fim_inode` table:
![resident3](https://user-images.githubusercontent.com/10405193/70536269-b1146100-1b5e-11ea-8108-f4372a549f3c.png)
![virtual3](https://user-images.githubusercontent.com/10405193/70536281-b376bb00-1b5e-11ea-9dfc-046a1f862809.png)
As seen in those graphics, the new FIM consumes a significant amount of memory compared to old 3.10.2 FIM even disabling the `fim_inode` table.
We must perform a deeper research on why this is happening and if it's justified.
I've performed a scan with massif tool (Valgrind) and this is the result:
![massif2](https://user-images.githubusercontent.com/10405193/70537196-5bd94f00-1b60-11ea-8ec8-986c3aa7a93d.png)
It seems like most of the memory is being allocated within the `fim_get_data` function. This could be related to the `fim_entry_data` structure:

https://github.com/wazuh/wazuh/blob/3319-fim-rework/src/syscheckd/create_db.c#L519
