### ISSUE TITLE
QA testing - Agent shutdown hang.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-qa#3066]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.3.6                        |13314                        |13941                    |

## Description
Agent hangs during the process shutdown, when a large set of information is sent to the manager.

## Proposed checks
- [x] Verify that the shutdown is fast and effective (4.3.5-1).
- [x] Verify that the shutdown is fast and effective (Dev Branch).

## Steps to reproduce
- Stop agent and manager
- Remove agent database (on manager side)
- Start manager
- Start Agent
- Wait to syscollector scan finish.
- Trigger manual shutdown. wazuh-ui or wazuh-control

## Expected results
Shutdown is fast and effective(No crashes during shutdown).

## Configuration and considerations
Default.

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
