### ISSUE TITLE
Fix Remoted IT: test_agent_communication messages not found

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3071]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-06| [c62d985](https://github.com/wazuh/wazuh/commit/c62d985f729591fb2f7b0026ec08bb1756dd031b) | disable filebeat metrics (https://github.com/wazuh/wazuh/pull/14121) | [#28639](https://ci.wazuh.info/job/Test_integration/28639) | 4.3.6 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 1 | Manager |  CentOS 

### Description

```
09:39:11  FAILED test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[TCP]
09:39:11  FAILED test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[UDP]
09:39:11  FAILED test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[TCP,UDP]
09:39:11  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_new_file_is_added]
09:39:11  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_old_file_is_deleted]

```
- [x] Run tests in Jenkins
- [ ] If it fails in Jenkins, run tests in local environment
- [ ] If it fails in Jenkins, Read test code & docs and run tests manually
- [ ] If it fails (Local/Jenkins), Fix failures

### Package
[RPM Manager](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.6-3071.fix.remoted.it.x86_64.rpm)

**Comment by juliamagan** [comment]
Most of the problems are due to the tests not being launched correctly. For this reason, this issue has been opened: https://github.com/wazuh/wazuh-jenkins/issues/3780

The rest of the tests that were still failing will be fixed in: #3088

**Comment by damarisg** [comment]
# Update 2022/07/18

## Run tests using Jenkins


Test Path | Os | Build | Date | By | Notes
-- | -- | -- | -- | -- | --
test_remoted/ | CentOS - Manager|  [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29329/) [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29333/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29330/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29331/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29332/) | 2022/07/18 | @damarisg |  


This issue was closed because we couldn't reproduce it after this [fix](https://github.com/wazuh/wazuh-jenkins/issues/3780).

**Comment by TomasTurina** [comment]
Some of these tests are still failing in 4.4: https://github.com/wazuh/wazuh/pull/13713/checks?check_run_id=7412534976
```
ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_new_file_is_added]
ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_old_file_is_deleted]
```
