### ISSUE TITLE
Check FIM database synchronization metrics

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#308]
|Version|Branch|
|---|---|
|3.11 + FIM rework|[3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)|
|3.11 + FIM rework-sqlite|[3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)|

## Goals

- Compare the synchronization protocol in both the best and the worst case.
- Know how the synchronization time depends on the number of files.
- Compare RBTree implementation vs. SQLite version

## Configuration

- Disable every component in the agent except FIM.
- Set the synchronization interval short so we will know when the database is synced faster.

```xml

<syscheck>
  <inventory>
    <sync_interval>10</sync_interval>
  </inventory>
</syscheck>
```

- Set the limit of opened databases to 10:
```
wazuh_db.open_db_limit=10
```

## Matrix

- Protocol:
  - UDP, 1000 EPS (`<client_buffer>` and `<syscheck>`).
  - TCP, 1000 EPS.
  - TCP, 1000000 EPS (FIM), client buffer disabled.
 - Number of files:
   - 0 files.
   - 10K files.
   - 20K files.
   - 50K files.
   - 100K files.
   - 200K files.
   - 500K files.
   - 1M files.
- Cases:
  - Best case: the database in the manager is empty.
  - Worst case: the database is full but checksums are wrong:
```sh
wazuh-tools/utils/wdb-query.py 001 "UPDATE fim_entry SET checksum = ''"
```
- Number of agents:
  - One single agent.
  - 10 agents synchronizing simultaneously. 
  - 30 agents synchronizing simultaneously. 

## Target

Datasheet including:

1. The number of attempts.
2. The time since the first synchronization attempt to the first completion time.

**Comment by jesusjimsa** [comment]
I have created two Python scripts to check these metrics: 
- One will run in the _agent_ and will write in the `local_internal_options.conf` file to enable the debug mode for syscheck and wazuh-db. It will also create a number of files that will be monitored by FIM
- The second one will run in the _manager_ to check the integrity following these steps:
	1. Remove all database files inside `/var/ossec/queue/db`.
	2. Replace configuration written in `agent.conf` with a custom one for the test (the ones explained in the matrix in this issue).
	3. Start measuring time once the first attempt to save the integrity has been done.
	4. Get stats (cpu, ram, disk reads, disk writes) while the integrity has not been completed.
	5. Write in a `.csv` file all these stats when integrity completes.

These scripts will be added to the repository when wazuh/wazuh#4495 gets fixed.

**Comment by jesusjimsa** [comment]
This test now checks the integrity synchronisation time with `n` agent connected to the manager, waiting for all of them to end the synchronisation.
It also changes the configuration based on parameters using pytest and a template that the script will edit.

**Comment by jesusjimsa** [comment]
I have added the total disk read/write info to the results. This will be added only to the last row of the csv file.

**Comment by jesusjimsa** [comment]
I have created a script to generate graphics based on the test results. It will generate a graphic with all CPU results combined and separately.
