### ISSUE TITLE
E2E design and implementation: Emotet

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3084]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2870). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

WIP.

**Comment by BelenValdivia** [comment]
21/7
Tried to generate event without success:
Test:
- Executed in one task trigger-emotet.exe and in other task close the pop-ups(using ansible.windows._win_shell):

 ```
$wshell = New-Object -ComObject wscript.shell; 
$wshell.AppActivate('trigger-emotet.exe') 
Sleep 1 
$wshell.SendKeys('%C')
$wshell.AppActivate('trigger-emotet.exe') 
Sleep 1 
$wshell.SendKeys('{ENTER}')
```

- Executed all in one task (trigger-emotet.exe and commans to close pop ups)
- Executed in one task trigger-emotet.exe and in other task close the pop-ups(using ansible.windows._win_command)
- Excuted using `runas` to change user (Administrator, System)
- Tasks run on backroung so the pop ups are not displayed when the tests run.
- Executed same test manually and it works
- Disabled Windows Errors reporting
- Executed using community windows
