### ISSUE TITLE
Syscheck automated tests: Check FIM doesn't report any event until the baseline generation

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#309]
|Working branch|Platform|
|---|---|
||Linux/Windows/macOS|

**This test has to be added to the basic cases.**

## Description

The first Syscheck scan generates the baseline (the initial state for every monitored file). Until that first scan is not finished, no event should be reported by Syscheck (neither scheduled, real-time or who-data).

This message informs about the end of the scan.

```
2019/12/03 08:45:58 ossec-syscheckd[125541] create_db.c:81 at fim_scan(): INFO: (6009): File integrity monitoring scan ended.
```

No message of type event can appear before the previous one. Events look like the following one:

```
2019/12/03 08:45:54 ossec-syscheckd[125541] run_check.c:77 at send_syscheck_msg(): DEBUG: (6321): Sending event: {"type":"event","data":{"path":"/etc/test","mode":"scheduled","type":"added","timestamp":1575391554,"attributes":{"type":"file","size":0,"perm":"rw-r--r--","uid":"0","gid":"0","user_name":"root","group_name":"root","inode":1052309,"mtime":1575391423,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"02548cdf11896f9931d12939d6e6c6c6e64695b4"}}}
```

## Subtasks

- [x] Check that no event appears in the log before the first "end scan" message.

**Comment by cristgl** [comment]
Using branch [309-no-events-until-baseline](https://github.com/wazuh/wazuh-qa/tree/309-no-events-until-baseline).
