### ISSUE TITLE
Add reconnect capability to agent-simulator

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#3093]
## Description
Due to the recent development of [Agents reconnect](https://github.com/wazuh/wazuh/issues/13195), we need to add the reconnect capability to the agent simulator. This new functionality will allow us to perform several tests necessary to verify the correct functioning of `Agents reconnect`.

We need to replicate the behavior of the Wazuh agents when they receive the `HC_FORCE_RECONNECT (force_reconnect)` command, in order to replicate the loss of connection with the manager and the reconnection to the same manager or a different one (depending on the load balancer configuration).

### Current behavior
Agent-simulator does not have the capability to reconnect when requested from a manager.

### Expected behavior
Agent-simulator is able to receive and correctly process (close the connection and establish it again) the reconnection request.

**Comment by vicferpoy** [comment]
I'm reopening this issue to further investigate why the `agent-simulator` sometimes fails to reconnect.
