### ISSUE TITLE
QA testing - IPv6 syslog messages handled

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-qa#3094]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4|[13708](https://github.com/wazuh/wazuh/issues/13708)|[14083](https://github.com/wazuh/wazuh/pull/14083)|

## Description

Syslog messages received by the Wazuh Syslog server (remoted) via IPv6 are not correctly handled, so the `location` and `full_log` fields can not be correctly parsed (splitted).

## Use case 

Remote Syslog messages are received on the Wazuh manager, from a device which address is of the IPv6 format.

### Configuracion

```xml
  <global>
       ...
       <logall_json>yes</logall_json>
       ...
  </global>
  
  <remote>
    <connection>syslog</connection>
    <port>5050</port>
    <protocol>tcp</protocol>
    <ipv6>yes</ipv6>
    <allowed-ips>any</allowed-ips>
  </remote>
```
## Steps to reproduce

Send a Syslog message from an IPv6 address (in this case, through the loopback interface).

```bash
echo "IPv6 test msg" | nc -v -w 0 -6 "::1"  5050
```
or running wazuh-logtest
```bash
/var/ossec/bin/wazuh-logtest -l "0000:0000:0000:0000:0000:0000:0000:0001" -d
Enter any message as: 'IPv6 test msg'
```
The result will return following struct, where location field will capture a section of IPv6 not full IP. 

```json
{
    "timestamp": "2022-06-03T16:50:16.660+0000",
    "agent": {
        "id": "000",
        "name": "200-u20-dev-manager"
    },
    "manager": {
        "name": "200-u20-dev-manager"
    },
    "id": "1654275016.1163645",
    "full_log": "0000:0000:0000:0000:0000:0000:0001:IPv6 test msg",
    "decoder": {},
    "location": "0000"
}
```
## Proposed test cases

- [x] Proposed test case 2: with IPv6
```json
{
    "timestamp": "2022-06-03T16:50:16.660+0000",
    "agent": {
        "id": "000",
        "name": "200-u20-dev-manager"
    },
    "manager": {
        "name": "200-u20-dev-manager"
    },
    "id": "1654275016.1163645",
    "full_log": "IPv6 test msg",
    "decoder": {},
    "location": "0000:0000:0000:0000:0000:0000:0000:0001"
}
```
- [x] Proposed test case 2: with IPv4

```bash
echo "IPv4 test msg" | nc -v -w 0 localhost 505
```
```json
{
    "timestamp": "2022-06-03T16:50:16.660+0000",
    "agent": {
        "id": "000",
        "name": "200-u20-dev-manager"
    },
    "manager": {
        "name": "200-u20-dev-manager"
    },
    "id": "1654275016.1163645",
    "full_log": "IPv4 test msg",
    "decoder": {},
    "location": "127.0.0.1"
}
```

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [81074ad](https://github.com/wazuh/wazuh/pull/14083/commits/81074adabab3077f2b42fc6c2727b1051bdfbae5)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Debian | 10 | ` LOCAL \|  Vagrant` | [generic/debian10](https://app.vagrantup.com/generic/boxes/debian10)
|  Centos  | 8 | ` LOCAL \|  Vagrant` | [bento/centos-8](https://app.vagrantup.com/bento/boxes/centos-8) |       |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [Centos](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit81074ad.x86_64.rpm) - [Ubuntu](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit81074ad_amd64.deb) | [Centos](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit81074ad.x86_64.rpm) - [Ubuntu](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit81074ad_amd64.deb)  |

### Status

- [ ] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by QU3B1M** [comment]
# Syslog message location field will capture a section of IPv6 not full IP. :red_circle: 

<details>
<summary><strong>Centos IPv6 :red_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [4.4](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-3094.no.fix.x86_64.rpm)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>yes</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv6 test msg" | nc -v -w 1 -6 "::1"  5050`
- Check the location (IPv6) of the event generated.
![image](https://user-images.githubusercontent.com/44633633/182227737-e691952e-678a-47b0-a9c6-78baf6fdb0c1.png)
  result: `"location":"0000"`
</details>

<details>
<summary><strong>Centos IPv4 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [4.4](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-3094.no.fix.x86_64.rpm)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>no</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv4 test msg" | nc -v -w 1 localhost 5050`
- Check the event is created and has the location (IPv4) correctly.
![image](https://user-images.githubusercontent.com/44633633/182229129-5eba4ba6-d098-4323-8516-6a1efb5f63e2.png)
  _result: `"location": "127.0.0.1"`_

</details>

<details>
<summary><strong>Ubuntu IPv6 :red_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [4.4](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3094.no.fix_amd64.deb)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>yes</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv6 test msg" | nc -v -w 1 -6 "::1"  5050`
- Check the location (IPv6) of the event generated.
![image](https://user-images.githubusercontent.com/44633633/182229588-2ffe805c-6e4c-4df9-8d38-ea8436229847.png)
  _result: `"location":"0000"`_ 
</details>

<details>
<summary><strong>Ubuntu IPv4 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [4.4](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3094.no.fix_amd64.deb)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>no</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv4 test msg" | nc -v -w 1 localhost 5050`
- Check the event is created and has the location (IPv4) correctly.
![image](https://user-images.githubusercontent.com/44633633/182230238-2f6179d4-5370-4e07-8e08-1236ed678815.png)
  _result: `"location": "127.0.0.1"`_

</details>




# Fixed: Syslog message location field will capture full IP :green_circle: 
<details>
<summary><strong>Centos IPv6 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [commit81074ad](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit81074ad.x86_64.rpm)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>yes</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv6 test msg" | nc -v -w 1 -6 "::1"  5050`
- Check the event is created and has the location (IPv6) correctly.
![image](https://user-images.githubusercontent.com/44633633/182200322-3db410ae-e929-4cf5-b4de-c3e8257085ca.png)
  _result: `"location": "0000:0000:0000:0000:0000:0000:0000:0001"`_
</details>

<details>
<summary><strong>Centos IPv4 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [commit81074ad](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit81074ad.x86_64.rpm)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>no</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv4 test msg" | nc -v -w 1 localhost 5050`
- Check the event is created and has the location (IPv4) correctly.
![image](https://user-images.githubusercontent.com/44633633/182219932-23139fdf-65d6-42f5-a1f0-45c1c456aa58.png)
  _result: `"location": "127.0.0.1"`_

</details>

<details>
<summary><strong>Ubuntu IPv6 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [commit81074ad](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit81074ad_amd64.deb)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>yes</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv6 test msg" | nc -v -w 1 -6 "::1"  5050`
- Check the event is created and has the location (IPv6) correctly.
![image](https://user-images.githubusercontent.com/44633633/182199439-cabd39fe-73cf-4618-8b9a-e081e7c403c3.png)
  _result: `"location": "0000:0000:0000:0000:0000:0000:0000:0001"`_

</details>

<details>
<summary><strong>Ubuntu IPv4 :green_circle: </strong></summary>

## Test Execution
- Install wazuh manager from the package [commit81074ad](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit81074ad_amd64.deb)
- Edit the config file `/var/ossec/etc/ossec.conf`:
   ```
   ...
   <global>
     ...
     <logall_json>yes</logall_json>
   </global>
   ...
   <remote>
     <connection>syslog</connection>
     <port>5050</port>
     <protocol>tcp</protocol>
     <ipv6>no</ipv6>
     <allowed-ips>any</allowed-ips>
   </remote>
   ...
  ```
- Send a syslog message using loopback Interface: `echo "IPv4 test msg" | nc -v -w 1 localhost 5050`
- Check the event is created and has the location (IPv4) correctly.
![image](https://user-images.githubusercontent.com/44633633/182218408-92b82bbc-366d-4a23-b015-673383ab4014.png)
  _result: `"location": "127.0.0.1"`_

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
