### ISSUE TITLE
Tests development - Add test_feeds cases for Red Hat 9

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3097]
| Related issue|
| --- |
| https://github.com/wazuh/wazuh-qa/issues/3040 |

### Description

As part of [Integration tests for Vulnerability Detector: Red Hat 9 support](https://github.com/wazuh/wazuh-qa/issues/3040), it is necessary to add cases in the test_feeds suite related to Red Hat 9 support for the Wazuh Vulnerability Detector module.

**Suite test_feeds**

- `Test download feeds`: Prove that it is downloaded, and that the update date is recent.
- `Test duplicate feeds`: Test that after downloading the feed again, the vulnerabilities of the feeds are not duplicated
- `Test import invalid feed type`: Test behavior when an invalid feed URL is entered
- `Test validate feed content`: It downloads the feed files and checks that they are parseable (XML or JSON).

### To Do 

- [ ] Apply changes requested in the revision.
- [ ] Test that it works correctly.

**Comment by davidjiglesias** [comment]
Obsolete as there is a VD refactor in the works.
