### ISSUE TITLE
Tests development - Add test_scan_results cases for Red Hat 9 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3098]
| Related issue|
| --- |
| https://github.com/wazuh/wazuh-qa/issues/3040 |

### Description

As part of [Integration tests for Vulnerability Detector: Red Hat 9 support](https://github.com/wazuh/wazuh-qa/issues/3040), it is necessary to add cases in the test_feeds suite related to Red Hat 9 support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan provider and NVD vulnerabilities`: Test that vulnerable packages are reported using the OVAL and NVD feed.
- `Test scan provider vulnerabilities`: Test that vulnerable packages are reported using the OVAL feed (NVD contains different vulnerabilities).
- `Test scan vulnerability removal`: Check that it generates vulnerability alert fixed after removing or updating a vulnerable package.

### To Do 

- [ ] Verify that the requested revision changes are applied.
- [ ] Test that it works correctly.

**Comment by davidjiglesias** [comment]
Obsolete as there is a VD refactor in the works.
