### ISSUE TITLE
Tests development - Add test_providers cases for Red Hat 9

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3099]
| Related issue|
| --- |
| https://github.com/wazuh/wazuh-qa/issues/3040 |

### Description

As part of [Integration tests for Vulnerability Detector: Red Hat 9 support](https://github.com/wazuh/wazuh-qa/issues/3040), it is necessary to add cases in the test_feeds suite related to Red Hat 9 support for the Wazuh Vulnerability Detector module.

**Suite test_providers**

- `Test enabled/disabled`: Check that the provider's feeds start downloading when activated.
- `Test missing os`: Test the behavior when the <os> tag is omitted. Check failure if the tag is required, and in case it is not, it starts downloading the feeds as normal
- `Test OS`: Test that it starts downloading the feeds of the specified OS.
- `Test update from year`: Test if the feed is updated from a specific date. If the option does not apply, check warning warning.
- `Test update interval`: Test that the feed is updated at the specified interval

### To Do 

- [ ] Add enabled/disabled tests
- [ ] Add  missing os tests.
- [ ] Add OS tests.
- [ ] Add update from year tests.
- [ ] Add update interval tests.
- [ ] Add Red Hat 9 OS to the test documentation (Add on each Tests)

**Comment by davidjiglesias** [comment]
Obsolete as there is a VD refactor in the works.
