### ISSUE TITLE
QA testing - report's inputs and usernames sanitation

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-qa#3100]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.3.6             |   https://github.com/wazuh/wazuh-kibana-app/issues/4329         |  https://github.com/wazuh/wazuh-kibana-app/pull/4330                   |

## Description

We need to ensure our reports functionality work as expected in the app.

## Proposed checks

- [x] Check API Endpoints
   - [x] Generate report - Post modules report `'/reports/modules/{moduleID}'`
   - [x] Generate Reports - Post groups report `'/reports/groups/{groupID}'`
   - [x] Generate Reports - Post agents report `'/reports/agents/{agentsID}'`
   - [x] Generate Reports - Post agents' inventory report `'/reports/agents/{agentsID}/inventory'`
   - [x] Get reports list `'/reports'`
   - [x] Get a specific report `'/reports/{name}'`
   - [x] Delete a specific report `'/reports/{name}'`
- [x]  Upgrading the app updates the folder layouts and reports are still accessible
- [x] Username schema works as expected, and backend reports about invalid names appropriately
- [x]  old names in a migrated schema work
- [x] no file collision is possible for read or write

## Scenarios

We need to test the following scenarios.

- [x] Clean install of Elastic Stack and the wazuh kibana app
- [x] Upgrade of an already installed wazuh kibana app on Elastic Stack
- [x]  Clean install of wazuh-dashboard
- [x]  Upgrade of an already installed wazuh-dashboard

## Expected results

All tests passed successfully, and no new issues were found on exploratory tests.

## Conclusion :yellow_circle: 
New bugs have been found when testing. The bug was already present in 4.3.5. In kibana-app and dashboard. 

#### New Issues
- https://github.com/wazuh/wazuh-kibana-app/issues/4348

**Comment by Deblintrake09** [comment]
## Clean Dashboard v 4.3.6 install

<details>
<summary>Generate reports :yellow_circle: </summary>

1. Generate Resports using Web application button - Check reports have been generated :green_circle: 



2. Generate report from API endpoint with Postman :yellow_circle: 
</details>

<details>
<summary>Get a users' reports :green_circle: </summary>

1. View from web application :green_circle: 


2. View reports from API endpoint with Postman :green_circle: 

</details>


<details>
<summary>Download reports :green_circle: </summary>

1. Download report from Web application :green_circle: 

2. Download report hitting API endpoint with Postman :green_circle: 

</details>


<details>
<summary>Delete reports :green_circle: </summary>

1. Download report from Web application :green_circle: 


2. Download report hitting API endpoint with Postman :green_circle: 

</details>


<details>
<summary>Path traversal by using invalid username :green_circle: </summary>

1. hit reports endpoint with invalid username, to read data from another folder
```
curl -k https://localhost/reports/..%2f..%2f..%2fconfig%2Fwazuh.yml -u admin:<UserPassword>
---

```
2. Hit another endpont to check results
```
# curl -k https://localhost/reports/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2Fpasswd -u admin:<UserPassword>

```
4.- Hit the endpoint from the API with postman


</details>

**Comment by Deblintrake09** [comment]
reporte Agente Inventario Postman
![imagen](https://user-images.githubusercontent.com/14501079/179772978-3c270cec-8542-477b-9a9d-627e6355f7b8.png)

**Comment by Deblintrake09** [comment]
![imagen](https://user-images.githubusercontent.com/14501079/179777765-519863db-4135-4aa3-9298-cab2c34fdb9d.png)


{"statusCode":500,"error":"Internal Server Error","message":"5029 - Reporting was aborted (Cannot read property 'length' of undefined)"}


```
scheme
	https
host
	172.31.2.65
filename
	/reports/groups/TestGroup1
Dirección
	172.31.2.65:443
Estado
500
Internal Server Error
VersiónHTTP/1.1
Transferido1,01 KB (tamaño 136 B)
Política de referenciastrict-origin-when-cross-origin
Prioridad de solicitudHighest

	
cache-control
	private, no-cache, no-store, must-revalidate
Connection
	keep-alive
content-length
	136
content-type
	application/json; charset=utf-8
Date
	Tue, 19 Jul 2022 14:38:37 GMT
keep-alive
	timeout=120
osd-name
	ip-172-31-2-65.ec2.internal
set-cookie
	security_authentication=Fe26.2**c006388ae586a4ef8ddf26182dfa610ff267d99132aab266687553ddcc446996*894jtiMYUHm96yzvaetmtw*v5KSxKIJUWCGteWr32bVe-o6f5JkXX-dkTUerOocfmP5FkCLOKNPRYTeusahSYOQyDJ2gVoeiCJpkO1VyeBN519_dcyTwMaXFwAu_sKlufCOm4LeW0HpczZIt4QpcpbxSZ4aRRvQBmdK3WzA6njOtJlmJdK9dEbY1bhXWBKJ57fnlYP3frNRlc2YqPCuehlhycpGeZMXRMPLZi-m9gNApLe4366QOVd2tS7P4GFyTKEw81CGnVL6ukA3vYsUXktLNdVKHppllerqq2IYpemc200ZORzF8dNkWiPOh1VyT1ljwghVkDNqNpww7T8ydK5Y**e79cbcf39f184ca8335989839dea8fc607c8e068bd8badb71d6e246e728fc310*7j7hqcymLdTmgcvnFr-GNXxKr0CwmhOSPz3P51NwS2w; HttpOnly; Path=/
x-frame-options
	sameorigin
	
Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3
Connection
	keep-alive
Content-Length
	134
Content-Type
	application/json
Cookie
	wz-token=eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjU4MjQwNDkxLCJleHAiOjE2NTgyNDEzOTEsInN1YiI6IndhenVoLXd1aSIsInJ1bl9hcyI6ZmFsc2UsInJiYWNfcm9sZXMiOlsxXSwicmJhY19tb2RlIjoid2hpdGUifQ.ANGjBdOpeeo4VpSGAkhIINQHH4g_L7j3eZJ7OZuZ6YhvYpsPlZI7V3PuysMkY0eXZ45kjamXj_hMlNIxjp0TSTmyAU3reFxWYzHmrkK7aIinWKrC8zrj0EgpE4THpiVKzTT0YGySdIma2Qnrd_vIetkgBJEa1CGEujD9OSOxqnrEEG7a; wz-user=../../../../../../../../etc/passwd; wz-api=default; security_authentication=Fe26.2**f7e26…11e87f283674d116b7c587536534454815e47c2356b4b5ecd473d80be*W8BQ1WY6ug0NCY8Xg5o2OQ*vVEoXWRAELmlHJy7Oxj_Ij8P7PoG9rVxJXtJuAI0Co8wJcym4ylCwe9aFu_mHsjICI5jhPFtoAjoSONXZ_TZDIScuvhgitIfk_WK6iCZhTUSqnsL5msdPbjCrzHB38krlhAUMwYMf_0V5c1m1XNjag9BZphUM51Nedi4ns-cGfY5tUWJBUWJEgDp6JcY7om1ZyBejcAhbg3dp5aYI4mDtAvhB3KWN-vJjgjUjMFc0mcb-o_MZiutW7bmthDhbpQ4mpJ09lzA-snh8L0L233UIa3PWS3w-GGW-ON2mK-160IEVxmVm8eJtnCO8F116MTl**2e7e669923d503edff7c5b7c60813f48358b94565ee9cfc4a140bd7c7268dbb6*SkMQSgF8-QkMOP4ZShgVCUNN3CsjFfnVzn16g2a5-oI
Host
	172.31.2.65
Origin
	https://172.31.2.65
osd-xsrf
	kibana
Referer
	https://172.31.2.65/app/wazuh
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
User-Agent
	
```

**Comment by Deblintrake09** [comment]
## Tests on Dashboard v4.3.5 install

<details>
<summary>Generate Reports - Post agents report <code>/reports/agents/{agentsID}</code> :green_circle: </summary>

1. Generate Resports using Web application button
![imagen](https://user-images.githubusercontent.com/14501079/179824678-ba1d4d89-51f3-41fc-9873-f7a85f60b860.png)

2. Generate report from API endpoint with Postman 
![imagen](https://user-images.githubusercontent.com/14501079/179825333-3d7013e4-b9a4-4a93-9ed6-584534600393.png)

</details>



<details>
<summary>Generate Reports - Post agents' inventory report <code>/reports/agents/{agentsID}/inventory</code> :green_circle: </summary>

1. Generate Resports using Web application button
![imagen](https://user-images.githubusercontent.com/14501079/179825573-ad2d4670-4091-4afe-b053-6a26ee43e0d6.png)


2. Generate report from API endpoint with Postman 
![imagen](https://user-images.githubusercontent.com/14501079/179825941-6947dfbb-75a9-4307-925c-303ecf7604d9.png)
</details>



<details>
<summary>Generate reports-  Post modules report <code>/reports/modules/{moduleID}</code> :green_circle: </summary>

1. Generate Resports using Web application button - Check reports have been generated 
![imagen](https://user-images.githubusercontent.com/14501079/179826166-c5ad1972-5df6-4bc1-a942-ab8b84c3175f.png)

2. Generate report from API endpoint with Postman 
![imagen](https://user-images.githubusercontent.com/14501079/179827334-be34d36b-cde7-42fb-89f6-0432ebc7b5ad.png)
</details>


<details>
<summary>Generate Reports - Post groups report <code>/reports/groups/{groupID}</code> :green_circle: </summary>

1. Create a group and assign agents to it
![imagen](https://user-images.githubusercontent.com/14501079/179827457-60224898-c243-46f9-a60c-7e3e3521e9b8.png)

2. Generate report from Web application 
![imagen](https://user-images.githubusercontent.com/14501079/179827546-5724f24f-4804-4ad7-aeaa-14a47e9cd5c7.png)

3. Generate report hitting API endpoint with Postman :yellow_circle: 

- Generate reports with both components
![imagen](https://user-images.githubusercontent.com/14501079/179827864-4fd00a91-26a3-4480-912c-f15c49b360e0.png)

- Generate reports with agent information only
![imagen](https://user-images.githubusercontent.com/14501079/179827971-b79179c9-5555-4370-8442-b5c3411117de.png)

- Generate reports with configuration information only
![imagen](https://user-images.githubusercontent.com/14501079/179828058-b6ab25d5-ae5b-432d-96b0-e5a7855cb624.png)

- Generate reports with no component information
![imagen](https://user-images.githubusercontent.com/14501079/179828179-406ed7b1-7905-4005-bc05-f3ddcd9fb045.png)
</details>



<details>
<summary>Get a users' reports list <code>/reports</code> :green_circle: </summary>

1. View from web application :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179828708-f1838627-7809-48ef-bff6-320aae3157d7.png)

2. View reports from API endpoint with Postman :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179828600-a748ca09-fb1e-4c50-ae69-99c93b1ec922.png)


3. Check the report's folder location
   ```
   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/admin/
   wazuh-agent-001-configuration-1658255962.pdf
   wazuh-agent-001-configuration-1658256051.pdf
   wazuh-agent-001-syscollector-1658256292.pdf
   wazuh-group-TestGroup-configuration-1658256954.pdf
   wazuh-group-TestGroup-configuration-postman.pdf
   wazuh-overview-general-1658256490.pdf
   wazuh-overview-general-1658256831.pdf
   ```

</details>


<details>
<summary>Get (Download) a specific report <code>/reports/{name}</code> :green_circle: </summary>

1. Download report from Web application :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179828942-f7464c6e-ae5e-4684-8bce-eec08854bd5e.png)

2. Download report hitting API endpoint with Postman :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179829026-66d6a1cf-cc93-41fd-93ab-06fc07bc21d7.png)

</details>


<details>
<summary>Delete reports <code>/reports/{name}</code> :green_circle: </summary>

1. Delete report from Web application :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179829266-201fa607-de96-430f-a255-4fc76db70bb8.png)
![imagen](https://user-images.githubusercontent.com/14501079/179829298-fef5dc02-8ec6-4c14-a54f-f563e506f0da.png)

2. Delete report hitting API endpoint with Postman :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179829216-8b5327a4-f9cc-4fc5-a964-adef59299e1b.png)

3. Check the report's folder location
   ```
   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/admin/
   wazuh-agent-001-configuration-1658255962.pdf
   wazuh-agent-001-configuration-1658256051.pdf
   wazuh-agent-001-syscollector-1658256292.pdf
   wazuh-group-TestGroup-configuration-1658256954.pdf
   wazuh-overview-general-1658256490.pdf
   ```
</details>


<details>
<summary>File collision is possible for read or write - Error reproduced  :red_circle: </summary>

1. hit reports endpoint with invalid username, to read data from another folder
```
curl -k https://localhost/reports/..%2f..%2f..%2fconfig%2Fwazuh.yml -u admin:<UserPassword>
---
#
# Wazuh dashboard - App configuration file
# Copyright (C) 2015-2022 Wazuh, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Find more information about this on the LICENSE file.
#
# ======================== Wazuh dashboard configuration file ========================
#
# Please check the documentation for more information on configuration options:
# https://documentation.wazuh.com/current/installation-guide/index.html
#
# Also, you can check our repository:
# https://github.com/wazuh/wazuh-kibana-app
#
# ------------------------------- Disable roles -------------------------------
.
.
.
```
2. Hit another endpoint to check results
```
# curl -k https://localhost/reports/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2Fpasswd -u admin:<UserPassword>
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
```
5. Hit the endpoint from the API with postman to get file
![imagen](https://user-images.githubusercontent.com/14501079/179830005-8818500c-d923-4e79-8805-ca1997e43321.png)
- Saving response to file, and opening as plain text
![imagen](https://user-images.githubusercontent.com/14501079/179830792-847a8193-5277-4889-ae9f-24114ca709fe.png)
</details>

<details>
<summary>File collision is possible for read or write between users - Error reproduced  :red_circle: </summary>

1. Create new user `TestUser1`
2. Create reports for user `TestUser1`
![imagen](https://user-images.githubusercontent.com/14501079/179836714-87009dba-0553-458e-9e56-8ad10e1f347a.png)
3. Check `TestUser1` reports folder and that it shows only the user's reports
   ```
   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/TestUser1/
   wazuh-agent-001-configuration-1658259456.pdf
   wazuh-agent-001-general-1658260354.pdf
   wazuh-agent-001-syscollector-1658259446.pdf
   wazuh-overview-general-1658260339.pdf
   ```

4. Check that the `TestUser1`'s  reports are not present in `admin`'s reports folder
   ```
   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/admin/
   wazuh-agent-001-configuration-1658255962.pdf  wazuh-group-TestGroup-configuration-1658256954.pdf
   wazuh-agent-001-configuration-1658256051.pdf  wazuh-overview-general-1658256490.pdf
   wazuh-agent-001-syscollector-1658256292.pdf
   ```
5.- Hit the endpoint from the API with postman - Try to read from one agent's folder from the other agent (read TestUser1 files from with admins credentials) :red_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/179837701-e43b7d3d-b815-468b-adaa-351d964ec1c7.png)

</details>

## Update 4.3.5 Dashboard to 4.3.6
<details>
<summary>Upgrade to 4.3.6 and validate reports are still accessible</summary>

1. Upgrade Dashboard and restart
   ```
     Verificando         : wazuh-dashboard-4.3.6-1.x86_64                                                  1/2 
     Verificando         : wazuh-dashboard-4.3.5-1.x86_64                                                  2/2 

    Actualizado:
   wazuh-dashboard-4.3.6-1.x86_64                                                                            

   ¡Listo!
   # systemctl restart wazuh-dashboard
   # systemctl status wazuh-dashboard
   ● wazuh-dashboard.service - wazuh-dashboard
      Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
      Active: active (running) since Tue 2022-07-19 20:05:33 UTC; 1min 29s ago
    Main PID: 10204 (node)
   ```
2. Check reports for `admin` and `TestUser1` users
   ```
   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/
   21232f297a57a5a743894a0e4a801fc3/ d5537295be1d5a93bfe54f8992d06bda/ 

   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/21232f297a57a5a743894a0e4a801fc3/    (admin)
   wazuh-agent-001-configuration-1658255962.pdf  wazuh-group-TestGroup-configuration-1658256954.pdf
   wazuh-agent-001-configuration-1658256051.pdf  wazuh-overview-general-1658256490.pdf
   wazuh-agent-001-syscollector-1658256292.pdf

   # ls /usr/share/wazuh-dashboard/data/wazuh/downloads/reports/d5537295be1d5a93bfe54f8992d06bda/   (TestUser1)
   wazuh-agent-001-configuration-1658259456.pdf  wazuh-agent-001-syscollector-1658259446.pdf
   wazuh-agent-001-general-1658260354.pdf        wazuh-overview-general-1658260339.pdf
   ```
</details>

<details>
<summary>File collision is not possible for read or write - Error does not reproduce  :green_circle: </summary>

1. hit reports endpoint with invalid username, to read data from another folder
```
curl -k https://localhost/reports/..%2f..%2f..%2fconfig%2Fwazuh.yml -u admin:<UserPassword>
{"statusCode":400,"error":"Bad Request","message":"[request params.name]: must be A-z, 0-9, _, ., and - are allowed. It must end with .pdf."}
```
2. Hit another endpoint to check results
```
# curl -k https://localhost/reports/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2Fpasswd -u admin:<UserPassword>
{"statusCode":400,"error":"Bad Request","message":"[request params.name]: must be A-z, 0-9, _, ., and - are allowed. It must end with .pdf."}
```
3. Hit the endpoint with postman to try to get files from other agent's reports folder
![imagen](https://user-images.githubusercontent.com/14501079/179839980-24deb337-57c9-49ce-9962-23e40ab8994a.png)
![imagen](https://user-images.githubusercontent.com/14501079/179840209-8d6ed495-6d8e-4614-a143-4f6a05809ded.png)

4. Hit the endpoint with postman to generate a report inside the other agent's reports folder
![imagen](https://user-images.githubusercontent.com/14501079/179840422-87352a0f-57db-4833-baa8-28a80ef043a0.png)

</details>
