### ISSUE TITLE
Syscheck automated tests: 'max_eps' option

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#311]
|Working branch|Platform|
|---|---|
||Linux/Windows/macOS|

## Description

The ``max_eps`` option is used to limit the throughput of events from the FIM module, avoiding the flooding of the network and the manager.

- Default value: 200
- Allowed values: Any integer from 1 to 100000

To test this option, the simplest way is to monitor a large number of files. That way, when creating the baseline for the first scan, each monitored file is sent as a `state` event to the manager.

## Subtasks

- [x] Check that the EPS limitation is respected during stressing Syscheck.

- [x] Create the test for several values of EPS (10, 100, 400, 1000, 10000...)

**Comment by crd1985** [comment]
## Status
A test has been written to check that `max_eps` is always the actual top event rate. Values tested are 10, 50, 100, 200 and 500.
We are also working to ensure that no events are lost.

**Comment by crd1985** [comment]
## Status
I will try to check the new branch `fim-duplicate-messages` and adapt all callbacks with the new message format. In case of success, it would unlock this issue and tests under Windows platform should work.
