### ISSUE TITLE
Enhancement - Update on Warning message when using tag <local_ip> on agent configuration

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3118]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | Configuration | agent | Packages | Any |

## Description

In the PR [13878](https://github.com/wazuh/wazuh/pull/13878) was added a Warning message when the tag `<local_ip>` is declared on the agent configuration, the message is `WARNING: The <local_ip> tag is useless.` witch feels informal and could be replaced with something like `WARNING: The <local_ip> tag has been deprecated, so it will have no effect.`

## Evidences

Using the tag local_ip on a agent configuration and then checking the logs: 
``` 
2022/07/01 12:49:13 wazuh-agentd: WARNING: The <local_ip> tag is useless.
```
## Steps to reproduce

1. Deploy a agent using a rpm package (using the code from the PR [13878](https://github.com/wazuh/wazuh/pull/13878)) on a Centos machine
2. Check the agent's file `/var/ossec/etc/ossec.conf` to verify the tag `local_ip` is not there:
   ```
   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xxx.xxx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>centos, centos8, centos8.5</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	  </client>
   ...
   ```
3. Add the local_ip tag on the agents's `ossec.conf`
   ```
	   ...
	  <client>
	    <server>
	      <address>1xx.xxx.xxx.xxx</address>
	      <port>1514</port>
	      <protocol>tcp</protocol>
	    </server>
	    <config-profile>centos, centos8, centos8.5</config-profile>
	    <notify_time>10</notify_time>
	    <time-reconnect>60</time-reconnect>
	    <auto_restart>yes</auto_restart>
	    <crypto_method>aes</crypto_method>
	    <local_ip>1xx.xxx.xxx.xxx</local_ip>
	  </client>
   ...
    ```
4. Restart the wazuh agent.

5. Check the agent's `/var/ossec/logs/ossec.log` to verify the warning is raised

---
- **Current Result**
   ```
	2022/07/01 12:49:13 wazuh-agentd: WARNING: The <local_ip> tag is useless.
   ```
- **Expected Result**
   ```
	2022/07/01 12:49:13 wazuh-agentd: WARNING: The <local_ip> tag has been deprecated, so it will have no effect.
   ```

---

## Labels

- `qa/report` 
- `core/configuration` 
- `enhancement request`

**Comment by damarisg** [comment]
It is duplicated here.
