### ISSUE TITLE
QA testing - Fix Coverity error in VD

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#3120]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.3.7         |          https://github.com/wazuh/wazuh/issues/14365              |        https://github.com/wazuh/wazuh/pull/14366            |

## Description

There was a new error while running coverity. This PR https://github.com/wazuh/wazuh/pull/14366 aims to fix this error for future executions

## Proposed checks

- [x] Check that the coverity error is fixed
...

## Steps to reproduce

Run a coverity scan in the 4.3 branch:
`BRANCH=4.3 TARGET=server ./coverity.sh --ossec`

## Expected results

```
ew defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)


** CID 1518942:    (FORWARD_NULL)
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 4006 in wm_vuldet_oval_xml_parser()
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 3924 in wm_vuldet_oval_xml_parser()


________________________________________________________________________________________________________
*** CID 1518942:    (FORWARD_NULL)
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 4006 in wm_vuldet_oval_xml_parser()
4000                         }
4001                     }
4002                 }
4003             }
4004             else if ((dist == FEED_UBUNTU || dist == FEED_REDHAT) && !strcmp(node[i]->element, XML_CRITERION)) {
4005                 // To avoid a RHSA with no CVEs
>>>     CID 1518942:    (FORWARD_NULL)
>>>     Dereferencing null pointer "parsed_oval->vulnerabilities".
4006                 if (!parsed_oval->vulnerabilities->cve_id) {
4007                     goto end;
4008                 }
4009                 for (j = 0; node[i]->attributes[j]; j++) {
4010                     // Checks if the package isn't vulnerable
4011                     if (!strcmp(node[i]->attributes[j], XML_COMMENT)) {
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 3924 in wm_vuldet_oval_xml_parser()
3918             else if (!strcmp(node[i]->element, XML_REFERENCE)) {
3919                 for (j = 0; node[i]->attributes[j]; j++) {
3920                     if (!strcmp(node[i]->attributes[j], XML_REF_ID) &&
3921                         strstr(node[i]->values[j], "CVE")) {
3922                         // Create new CVE structure when a new reference appears.
3923                         // Append the new CVE name to the already existing vulnerability.
>>>     CID 1518942:    (FORWARD_NULL)
>>>     Dereferencing null pointer "parsed_oval->vulnerabilities".
3924                         if (parsed_oval->vulnerabilities->cve_id) {
3925                             info_cve *new;
3926                             os_calloc(1, sizeof(info_cve), new);
3927                             new->prev = parsed_oval->info_cves->prev;
3928                             parsed_oval->info_cves->prev = new;
3929                             os_strdup(node[i]->values[j], new->cveid);

```

**Comment by QU3B1M** [comment]
# Update 25/07/2022

## Check the error in Coverity

- Find error in Coverity before fix (**`CID 275227`**)
![cidcodenofixed](https://user-images.githubusercontent.com/44633633/180835550-8d5cd885-57bd-4dff-9e6e-a50894648c26.png)
- Search CID 275227 and check status is fixed
![cidfixeds](https://user-images.githubusercontent.com/44633633/180835931-f18508c1-efad-4ce0-98bd-b2ba2f2220c4.png)
- Check CID 275227 error disappeared after fix
![cidcodefixed](https://user-images.githubusercontent.com/44633633/180836166-bb162860-f3a3-4bbe-891c-d18f0c3355ee.png)

##  Run VD tests in Jenkins

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_remoted/  | Centos |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29605/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29612/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29613/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29614) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29615/))  |  25/07/2022 |  Kevin |  |

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
