### ISSUE TITLE
E2E design and implementation: Slack

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3126]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2876). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

**Comment by mauromalara** [comment]
## Update 27/07/2022

I developed the test but it fails; I was doing some manual tests but I could not find why it happens manually but fails when the automation is executed.
