### ISSUE TITLE
E2E design and implementation: Windows Defender

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3127]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2878). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

**Comment by BelenValdivia** [comment]
27/7
- Created test structure
- Test it manually
- Worked on configuration yaml

**Comment by BelenValdivia** [comment]
28/7
- Worked on generate event
- Improved tasks in configuration yaml

**Comment by BelenValdivia** [comment]
PR Opened: https://github.com/wazuh/wazuh-qa/pull/3138
