### ISSUE TITLE
QA testing - Fix a segmentation fault in wazuh-maild when parsing alerts exceeding the nesting limit

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3128]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.3.7                      |  https://github.com/wazuh/wazuh/issues/8934                      |   https://github.com/wazuh/wazuh/pull/14417                 |

## Description

As explained in the issue above, we're fixing wazuh-maild to prevent it from crashing when having an alert with an object that exceeds the nesting limit and has no siblings.

## Proposed checks
They're specified at https://github.com/wazuh/wazuh/pull/14417.

## Steps to reproduce

- Set up wazuh-maild to parse _alerts.json_.
- Run wazuh-maild only (without wazuh-analysisd).
- Inject the proposed alerts.

## Expected results

wazuh-maild must not crash when parsing these alerts. However, no alert should cause wazuh-maild to crash.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake  | [1f04a5c](https://github.com/wazuh/wazuh/pull/14417/commits/1f04a5c5f89803d3da0c7f319dfcdc9a3a770f8b)  | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Linux   |  Centos8 | `LOCAL\| Vagrant` | qactl/centos8 |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [RPM Manager](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.7-3128.maild.segfault.fix.x86_64.rpm
)  | ---- |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Tasks Results on dev Branch

<details>
</details>

**Comment by Deblintrake09** [comment]
## Tasks Results on dev Branch

<details>
</details>

**Comment by Deblintrake09** [comment]
<directories realtime="yes">/testfolder</directories>





# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild is running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
