### ISSUE TITLE
Manual testing - Fix permission error in JSON alert

### ISSUE THREAD

**Issue by FrancoRivero** [wazuh/wazuh-qa#3133]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5.0|https://github.com/wazuh/wazuh/issues/12073|https://github.com/wazuh/wazuh/pull/14019|

## Description

The goal of this issue is to manually test the change in `analysisd` to fix a bug which discards events when these events have a bad format in their permission. This bug was found in a stress test and this was tested in unit tests and it could not be reproduced manually.

## Proposed checks

- [x] Create a stress tests for 24 hours and check that the error won't show in the logs.

## Steps to reproduce

We could not reproduce this error manually because this error is generated in the Windows system when Wazuh has a lot of stress applied to it. 
However we could detect a format inside a Windows permission which generates a error to reproduce it. this would be:

`USER (allowed or denied): permission_1|permission_2|permission_3,USER2 (allowed or denied): permission_1|permission_2|permission_3` 

If the permission does not have this format then this permission is skipped and the next one is searched in this case if USER fails to have the format then this permission is skipped and USER2 is searched.

## Expected results
The error `wazuh-analysisd: ERROR: The new permissions could not be added to the JSON alert.`  
should not be seen in the log but, depending on the error, we should see a message in debug1 such as :

`Uncontrolled condition when parsing the username from 'USERNAME'. Skipping permission.` or 
`Uncontrolled condition when parsing the permission type from 'PERM_TYPE'. Skipping permission.`

## Configuration and considerations

This bug can be reproduced with [this configuration](https://github.com/wazuh/wazuh/issues/12073#issuecomment-1165931629)

**Comment by chemamartinez** [comment]
Hi @wazuh/qa, this issue cannot be started until PR https://github.com/wazuh/wazuh/pull/14019 is ready. We still have to reach 100% green in Jenkins and complete the review.

Sorry for the inconvenience.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 | [850faee]{https://github.com/wazuh/wazuh/commit/850faee0145b8dab2cf3d0d66509ea39f8c9f91a)    | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<JENKINS \| Stress Pipeline` |          |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|     [.rpm Manager](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-3133.permission.error.fix.x86_64.rpm)  - [.deb Manager](https://packages-dev.wazuh.com/warehouse/test/4.5/deb/var/wazuh-manager_4.5.0-3133.permission.error.fix_amd64.deb)          |  [.rpm Agent](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-agent-4.5.0-3133.permission.error.fix.x86_64.rpm) - [.deb Agent](https://packages-dev.wazuh.com/warehouse/test/4.5/deb/var/wazuh-agent_4.5.0-3133.permission.error.fix_amd64.deb)      |

### Conclusion 



### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Update 2022/08/10

- Research Issue
- Generate packages
- Launch Stress test instances :red_circle:

**Comment by Deblintrake09** [comment]
# Task Results

|Test run | duration | results | Debug Level |
|---|---|---|---|
| R1 | 2.5 days| [:green_circle:](https://ci.wazuh.info/job/Test_stress/3545/) | Debug 2
| R2 | 2.5 days| [:green_circle: ](https://ci.wazuh.info/job/Test_stress/3448/) | Debug1
| R3 | 2.5 days| [:green_circle: ](https://ci.wazuh.info/job/Test_stress/3449/) | Debug1
| R4 | 2.5 days| [:green_circle: ](https://ci.wazuh.info/job/Test_stress/3450/) | Debug1
| R5 | 1 day | [:green_circle:](https://ci.wazuh.info/job/Test_stress/3546/) | Debug 2
| R6 | 1 day | [:green_circle:](https://ci.wazuh.info/job/Test_stress/3547/) | Debug 2
| R7 | 1 day | [:green_circle:](https://ci.wazuh.info/job/Test_stress/3548/) | Debug 2
| R8 | 1 day | [:green_circle:](https://ci.wazuh.info/job/Test_stress/3549/) | Debug 2

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
