### ISSUE TITLE
QA testing -  Fix wrong condition in WXS

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#3139]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.3.7             |            https://github.com/wazuh/wazuh/issues/13928            |          https://github.com/wazuh/wazuh/pull/14447          |

## Description

We found an incorrect condition in the WXS file that caused the MSI installation to get stuck.

## Proposed checks

- [x] Windows 2012R2
    - [x] Reproduce failure on 4.3.6
    - [x] Clean installation of the new package
    - [x] Upgrade from 3.x with the service stopped
    - [x] Upgrade from 4.0.x with the service stopped
    - [x] Upgrade from 4.3.x with the service stopped
    - [x] Upgrade from 3.x with the service started
    - [x] Upgrade from 4.0.x with the service started
    - [x] Upgrade from 4.3.x with the service started
- [x] Windows XP
    - [x] Reproduce failure on 4.3.6
    - [x] Clean installation of the new package
    - [x] Upgrade from 3.x with the service stopped
    - [x] Upgrade from 4.0.x with the service stopped
    - [x] Upgrade from 4.3.x with the service stopped
    - [x] Upgrade from 3.x with the service started
    - [x] Upgrade from 4.0.x with the service started
    - [x] Upgrade from 4.3.x with the service started
- [x] Windows Server 2016
    - [x] Reproduce failure on 4.3.6
    - [x] Clean installation of the new package
    - [x] Upgrade from 3.x with the service stopped
    - [x] Upgrade from 4.0.x with the service stopped
    - [x] Upgrade from 4.3.x with the service stopped
    - [x] Upgrade from 3.x with the service started
    - [x] Upgrade from 4.0.x with the service started
    - [x] Upgrade from 4.3.x with the service started
- [x] Windows server 2022
    - [x] Reproduce failure on 4.3.6
    - [x] Clean installation of the new package
    - [x] Upgrade from 3.x with the service stopped
    - [x] Upgrade from 4.0.x with the service stopped
    - [x] Upgrade from 4.3.x with the service stopped
    - [x] Upgrade from 3.x with the service started
    - [x] Upgrade from 4.0.x with the service started
    - [x] Upgrade from 4.3.x with the service started
- [x] validate basic behavior of alerts
## Steps to reproduce

In a Windows machine with low resources (1 core and 500 MB of memory) install wazuh agent 4.3.0 and update to 4.3.6. The installation will take a long time in the `starting services` step and in the end it will probably return the following error:
![image](https://user-images.githubusercontent.com/19505384/182107975-9ad6e956-6a91-456c-b993-4a969d2e29bb.png)

## Expected results

Installation and upgrade work properly and the service remains running if it was running before the upgrade.

**Comment by CamiRomero** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @CamiRomero   |  [0ae763](https://github.com/wazuh/wazuh/pull/14447/commits/0ae763fc7c038b96f5db35d534802ba87ae93806)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Windows  |  Windows Server 2016        | Local |    jacqinthebox/windowsserver2016         |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  []()               | -     |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by CamiRomero** [comment]
## Windows 2012R2

<details>
<summary> Reproduce the failure - Upgrade from 4.3.0 to 4.3.6 :red_circle: (error reproduced) </summary>

1. Dowload Wazuh agent:
    
    [Wazuh Agent 4.3.0](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi)
    
2. Install Wazuh Agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182222668-4f2261e7-f87c-4c91-9aca-d428d9f3e322.png)

4. Download Wazuh 4.3.6 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182222348-89a93a9d-17e7-41c0-80a6-89aaeb559bda.png)

</details>

<details>
<summary> Clean installation of the new package :green_circle: </summary>

1. Dowload Wazuh agent: 
   [4.3.7](https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.7-qa.3139.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to installl the Wazuh agent:
        ![imagen](https://user-images.githubusercontent.com/37776796/182223235-1ef1d0db-e622-490c-8938-06179ba82fb2.png)

</details>

<details>
<summary> Upgrade from 4.0.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182227479-3f21d610-7914-405d-96c5-de77ca4a05b9.png)

4. Stop Wazuh Agent using the GUI installer:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182227536-5dff1727-7054-4c8c-94f9-be692d690b23.png)

5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182229162-1f6a0006-e16c-451c-a121-22b65edc6702.png)

6. Start the Wazuh Agent using the GUI installer:
    ![imagen](https://user-images.githubusercontent.com/37776796/182227674-47feeabf-9923-4d2a-8d1b-e1d3f2e870ac.png)
</details>

<details>
<summary> Upgrade from 4.3.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182229636-83e809d6-37a8-4250-867e-b270e85df591.png)

4. Stop Wazuh Agent using the GUI installer:
    ![imagen](https://user-images.githubusercontent.com/37776796/182229666-f24d7fae-b921-48ae-87a3-6db6f32d6be2.png)

5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    ![imagen](https://user-images.githubusercontent.com/37776796/182229748-7f0831eb-c894-41a8-9a9e-e6caa23a10cf.png)

6. Start the Wazuh Agent using the GUI installer:
    ![imagen](https://user-images.githubusercontent.com/37776796/182229812-56ce1397-c831-4656-8456-053febce225d.png)

</details>


<details>
<summary> Upgrade from 4.0.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
    ![imagen](https://user-images.githubusercontent.com/37776796/182230145-c059fcb5-5725-44bc-a2bf-f4dafda3333e.png)
    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    ![imagen](https://user-images.githubusercontent.com/37776796/182230226-49f515d1-0a37-40e7-8f26-9202f9252538.png)

</details>

<details>
<summary> Upgrade from 4.3.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
    ![imagen](https://user-images.githubusercontent.com/37776796/182230505-b215bdd7-cfc6-4be0-9500-7bea7b437627.png)
    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    ![imagen](https://user-images.githubusercontent.com/37776796/182230585-5d887a6e-7a26-4783-b79b-6e977f4feed1.png)

</details>

**Comment by CamiRomero** [comment]
## Windows XP
<details>
<summary> Reproduce the failure - Upgrade from 4.3.0 to 4.3.6 :red_circle: (error reproduced) </summary>

1. Dowload Wazuh agent:
    
    [Wazuh Agent 4.3.0](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi)
    
2. Install Wazuh Agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
    ![imagen](https://user-images.githubusercontent.com/37776796/182417979-3f324aa6-97f6-42f8-bde4-0886c8a4615b.png)



4. Download Wazuh 4.3.6 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182417915-6fd3cfdb-4a89-47e5-9608-5fb906bf2e35.png)


</details>

<details>
<summary> Clean installation of the new package :green_circle: </summary>

1. Dowload Wazuh agent: 
   [4.3.7](https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.7-qa.3139.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to installl the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182419242-66daeaa4-4c8c-48a2-837b-e3b4f146e2ab.png)


</details>

<details>
<summary> Upgrade from 4.0.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182420204-04ccb168-a491-4c6f-8c2f-1e5e72104c4d.png)


4. Stop Wazuh Agent using the GUI installer:
        
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182420282-8dc4a6be-647d-4ea1-8e86-f1556a67e4ff.png)


5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182420377-cbd53757-1bb5-4a6a-b706-ab56c1e36e54.png)

   


6. Start the Wazuh Agent using the GUI installer:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182420457-bb87ede8-288a-462c-98fd-86b7537f5ead.png)

</details>

<details>
<summary> Upgrade from 4.3.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)

2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182419553-17098a1b-0d70-4f72-ac8d-dc4b106a9526.png)


4. Stop Wazuh Agent using the GUI installer:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182419600-9b5ce648-35a6-43a2-b3f4-74116f23b226.png)

5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    
    ![imagen](https://user-images.githubusercontent.com/37776796/182419771-1eeb1b03-c50d-447e-8daa-3c1ef8b3cce0.png)


6. Start the Wazuh Agent using the GUI installer:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182419911-a805fb51-0321-42a8-b6bf-9075d36c0bbb.png)


</details>


<details>
<summary> Upgrade from 4.0.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
   
    ![imagen](https://user-images.githubusercontent.com/37776796/182420735-b56a7488-3602-4302-99e2-b331ad2c8d7f.png)

    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    ![imagen](https://user-images.githubusercontent.com/37776796/182420912-7de96f9a-aa27-492a-a1c2-0d4b0793dd90.png)


</details>

<details>
<summary> Upgrade from 4.3.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182421144-6a1713ef-6031-4f8e-85ef-c7f9a79c20cf.png)

    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    ![imagen](https://user-images.githubusercontent.com/37776796/182421216-1af51fc2-6903-44a4-b4e5-355147c1f178.png)


</details>

**Comment by CamiRomero** [comment]
## Windows Server 2016 
<details>
<summary> Reproduce the failure - Upgrade from 4.3.0 to 4.3.6 :red_circle: (error reproduced) </summary>

1. Dowload Wazuh agent:
    
    [Wazuh Agent 4.3.0](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi)
    
2. Install Wazuh Agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
  
    ![imagen](https://user-images.githubusercontent.com/37776796/182426546-fb183072-5aa0-443a-bffb-9cdc7eaf1bdd.png)


4. Download Wazuh 4.3.6 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182426601-276ab0ca-0016-431c-8ddf-1218d3a69def.png)



</details>

<details>
<summary> Clean installation of the new package :green_circle: </summary>

1. Dowload Wazuh agent: 
   [4.3.7](https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.7-qa.3139.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to installl the Wazuh agent:
        
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182426829-2d842a13-26d4-4c38-bbee-062f1cf451c8.png)



</details>

<details>
<summary> Upgrade from 4.0.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182426951-9768ec57-31f8-4026-8b5d-77e4adf5b043.png)



4. Stop Wazuh Agent using the GUI installer:
        
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182427001-ada51780-762a-4dff-9c56-26245ca293f5.png)



5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182427076-5595527b-ac64-420f-b2b3-fff3633c7d17.png)

    

   


6. Start the Wazuh Agent using the GUI installer:
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182427140-d0710752-b37d-4d84-8cf2-24915cb2f315.png)


</details>

<details>
<summary> Upgrade from 4.3.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)

2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182431107-2830a38c-2967-4d36-8bae-d6efff493778.png)

    
4. Stop Wazuh Agent using the GUI installer:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182431163-1cd85fc2-bc76-4d97-a738-fb82632144d9.png)

5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    
    ![imagen](https://user-images.githubusercontent.com/37776796/182431449-45616f7d-d84b-47ff-8f7f-512c7eac9dbb.png)


6. Start the Wazuh Agent using the GUI installer:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182431520-242ac67c-0ef5-4004-a396-1199fc1885cc.png)

   


</details>


<details>
<summary> Upgrade from 4.0.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
   
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182433481-6410f70e-b82f-46aa-9d2e-ba47121a4ff1.png)


    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182433580-68dd409b-8e24-48ba-b58c-0d4904499538.png)



</details>

<details>
<summary> Upgrade from 4.3.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
    ![imagen](https://user-images.githubusercontent.com/37776796/182434528-292450dd-0f75-4a60-8136-0928406bbd58.png)

3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    ![imagen](https://user-images.githubusercontent.com/37776796/182434611-4fab8dc3-674c-4aa9-babb-bc979b391cef.png)


</details>

**Comment by CamiRomero** [comment]
## Windows Server 2022 
<details>
<summary> Reproduce the failure - Upgrade from 4.3.0 to 4.3.6 :red_circle: (error reproduced) </summary>

1. Dowload Wazuh agent:
    
    [Wazuh Agent 4.3.0](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.0-1.msi)
    
2. Install Wazuh Agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
 
  
    ![imagen](https://user-images.githubusercontent.com/37776796/182449086-d05602f8-762b-4a40-a2ef-8fe2e8042757.png)



4. Download Wazuh 4.3.6 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182450430-42ade34b-2e8c-4ef9-be97-0cc0f003bf8e.png)

   



</details>

<details>
<summary> Clean installation of the new package :green_circle: </summary>

1. Dowload Wazuh agent: 
   [4.3.7](https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.7-qa.3139.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to installl the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182450681-7bd3236c-7a3d-41e3-824d-b4c5a370d252.png)

</details>


<details>
<summary> Upgrade from 4.0.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182451605-15618f5f-dc05-4914-a642-ef3843f9265e.png)


4. Stop Wazuh Agent using the GUI installer:
        
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182451659-3c34cd13-5b56-4c95-937b-aabb311951fb.png)





5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:
    
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182451741-85494186-9d40-4908-8590-d6bc4da92824.png)



    

   


6. Start the Wazuh Agent using the GUI installer:
    
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182451788-6e85a141-07b1-414f-a373-e51bdb6077e7.png)



</details>

<details>
<summary> Upgrade from 4.3.x with the service stopped :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)

2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
        
    ![imagen](https://user-images.githubusercontent.com/37776796/182486146-be22eba5-a194-434c-899b-cc37e95a10d7.png)

    
    

    
4. Stop Wazuh Agent using the GUI installer:
    
  
    ![imagen](https://user-images.githubusercontent.com/37776796/182486166-13590eaf-1929-4d2f-b403-3c874bf47682.png)


5. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

    
    ![imagen](https://user-images.githubusercontent.com/37776796/182486231-b3240913-ab72-44b2-b087-5ef74ce0dd67.png)



6. Start the Wazuh Agent using the GUI installer:
    
  
    ![imagen](https://user-images.githubusercontent.com/37776796/182486262-4260f71b-41ce-4d29-9c0f-8808871d8149.png)

   


</details>


<details>
<summary> Upgrade from 4.0.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.0.0]( https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.0.0-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
   
    ![imagen](https://user-images.githubusercontent.com/37776796/182487721-c5fba135-4cf2-4cd5-9fc6-8059640dea6f.png)

    
3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182489526-6c4c325c-aac8-4008-9b9a-d7613bb84937.png)

</details>

<details>
<summary> Upgrade from 4.3.x with the service started :green_circle: </summary>

1. Dowload Wazuh agent:
   [4.3.6](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.6-1.msi)
2. Install and register Wazuh agent using the GUI installer. Open the installer and follow the instructions to install the Wazuh agent:
    
    ![imagen](https://user-images.githubusercontent.com/37776796/182488258-7e4e911c-0c92-46b8-bd90-5e9b98afb0aa.png)


3. Download Wazuh 4.3.7 and upgrade agent using the GUI installer. Open the installer and follow the instructions to upgrade the Wazuh agent:

   
    ![imagen](https://user-images.githubusercontent.com/37776796/182489332-45e58082-f32c-44a3-9133-a4158b8c6c2f.png)



</details>

**Comment by CamiRomero** [comment]
## validate basic behavior of alerts

<details>
<summary> Clean installation of the new package :green_circle: </summary>

1. Edit `osec.conf` on Wazuh Agent:
    ```
   <directories realtime="yes">C:\testingFolder</directories>
    ```
2. Create the folder to monitor
3. Restart the Wazuh Agent in order to apply changes

    ![imagen](https://user-images.githubusercontent.com/37776796/182605761-40cd4bc6-208f-4c01-b8fc-24c89c6010c3.png)

5. Check in the logs of Wazuh Agent that the folder is being monitored:

    ```
    2022/08/03 12:06:58 wazuh-agent: INFO: (6003): Monitoring path: 'c:\testingfolder', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
    ```
7. Create a file inside the monitored folder and review the manager's logs:
    ```
    ** Alert 1653676363.784639: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
    2022 May 27 18:32:43 (WIN-A1B99BSBJF0) any->syscheck
    Rule: 554 (level 5) -> 'File added to the system.'
    File 'c:\testingfolder\testfile.txt' added
    Mode: realtime
    
    Attributes:
     - Size: 0
     - Permissions: SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Administrators (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Users (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES
     - Date: Wed Aug  3 12:01:05 2022
     - Inode: 0
     - User: Administrators (S-1-5-32-544)
     - MD5: d41d8cd98f00b204e9800998ecf8427e
     - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
     - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
     - File attributes: ARCHIVE
    ```

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
