### ISSUE TITLE
E2E tests: Define Ansible roles to encapsulate common tasks

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3144]
## Description

The E2E tests have been developed in #2872 with the goal of being run manually. However, after such development, we have picked up a number of necessary changes that are common or impact all E2E tests.

This task aims to define Ansible roles to encapsulate common tasks, either for all E2E tests or for a group of E2E tests.

## Ansible Roles

The Ansible roles will be as follows
- manage_wazuh
- get alert json
- Truncate alert json
- Configure ossec.conf
- Configure local rules

**Comment by BelenValdivia** [comment]
16/8
- Meet with Mauro to unify structure
- Updated conftest.py to read roles folder in configuration_environment (configuration.yaml and teardown.yaml) and generate_events (generate_events.yaml)
- Created role to restart wazuh manager and wazuh agents validating OS

**Comment by BelenValdivia** [comment]
17/8
- Created role to manage alerts: get_alert_json.yaml and truncate_alert_json.yaml
- Created role to manage wazuh configurations: ossec.conf and local rules
- Tested roles in sql injection test and windows defender test

**Comment by BelenValdivia** [comment]
18/8

- Updated tests with new roles:

1. Tests updated:

- Test audit
- Test AWS
- Test brute force
- Test detecting suspicious binaries
- Test docker
- Test fim
- Test SQL injection
- Test virustotal
- Test windows defender

**Comment by BelenValdivia** [comment]
Executed some tests in 4.4:
- OSQuery integration
- Virustotal integration
- Suricata integration
- Yara integration
