### ISSUE TITLE
QA testing - Updated Amazon Linux SCA texts, YML formatting and OS detection rule bug 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3148]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.3.7                        |  https://github.com/wazuh/wazuh/pull/14483                      |         https://github.com/wazuh/wazuh/pull/14483          |

## Description
Amazon Linux SCA policy was not working due to a wrong OS detection rule. This Issue solves that problem. 

## Proposed checks

- [x]  Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System on 4.3.6
- [x]  Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System on 4.3.7
...

## Expected results

When using an Amazon Linux platform, our wazuh-agent will run the Amazon Linux SCA policy

## Configuration and considerations

Use wazuh-agent 4.3.7

**Comment by CamiRomero** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @CamiRomero   |  [e3ea98](https://github.com/wazuh/wazuh/pull/14483/commits/e3ea982c770224b1c53d20834534f80ca87f6911)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  amazonlinux_2   |   amazonlinux_2        | AWS |       ami-01936b10279237c85      |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  []()               | -     |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by CamiRomero** [comment]
## Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System on 4.3.6

<details>
<summary> Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System :red_circle: (error reproduced) </summary>

1. Install Wazuh Agent

2. Check logs located in `/var/ossec/logs/ossec.log`:
    ```
    2022/08/05 15:32:14 sca: INFO: Starting Security Configuration Assessment scan.
    2022/08/05 15:32:14 wazuh-modulesd:syscollector: INFO: Module started.
    2022/08/05 15:32:14 wazuh-modulesd:syscollector: INFO: Starting evaluation.
    2022/08/05 15:32:14 sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_amazon_linux_1.yml': 'Check Amazon Linux version.'
    2022/08/05 15:32:14 sca: INFO: Security Configuration Assessment scan finished. Duration: 0 seconds.
    ```


</details>

**Comment by CamiRomero** [comment]
## Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System on 4.3.7

<details>
<summary> Verify Amazon Linux SCA policy is loaded when starting the agent in an Amazon Linux System :green_circle: </summary>

1. Download and upgraded Wazuh Agent:
2. Check logs located in `/var/ossec/logs/ossec.log`:
    ```
    curl -LO https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-agent-4.3.7-qa.3148.x86_64.rpm

    yum upgrade wazuh-agent-4.3.7-qa.3148.x86_64.rpm
    ```
3. Check logs located in `/var/ossec/logs/ossec.log`:
    ```
    2022/08/05 16:22:34 sca: INFO: Starting Security Configuration Assessment scan.
    2022/08/05 16:22:34 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
    2022/08/05 16:22:34 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
    2022/08/05 16:22:34 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
    2022/08/05 16:22:34 wazuh-modulesd:syscollector: INFO: Module started.
    2022/08/05 16:22:34 wazuh-modulesd:syscollector: INFO: Starting evaluation.
    2022/08/05 16:22:34 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_amazon_linux_1.yml'
    2022/08/05 16:22:34 wazuh-modulesd:syscollector: INFO: Evaluation finished.
    2022/08/05 16:22:42 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_amazon_linux_1.yml'
    2022/08/05 16:22:42 sca: INFO: Security Configuration Assessment scan finished. Duration: 8 seconds.

    ```
4. Get result of Scan on Wazuh Manager:
    ```
        curl --location --request GET 'https://HOST_IP:55000/sca/AGENT_ID' \
    --header 'Authorization: Bearer TOKEN'
    ```

    Output:
    ```
        {
        "data": {
            "affected_items": [
                {
                    "total_checks": 179,
                    "hash_file": "180c6e24103ddb7d9a5b093e2a98186d2bca7b8d79019337842e65e453d3de3a",
                    "invalid": 3,
                    "description": "This document provides prescriptive guidance for establishing a secure configuration posture for Amazon Linux systems running on x86 and x64 platforms. This document was tested against CentOS 6.",
                    "score": 27,
                    "fail": 127,
                    "start_scan": "2022-08-05T16:22:39Z",
                    "name": "CIS Benchmark for Amazon Linux 1",
                    "policy_id": "cis_amazon_linux_1",
                    "pass": 49,
                    "references": "https://www.cisecurity.org/cis-benchmarks/",
                    "end_scan": "2022-08-05T16:22:39Z"
                }
            ],
            "total_affected_items": 1,
            "total_failed_items": 0,
            "failed_items": []
        },
        "message": "All selected sca information was returned",
        "error": 0
    }
    ```

5. Check alerts on `/var/ossec/logs/alerts.log`:
    ```
    ** Alert 1659716091.1566807: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
    2022 Aug 05 16:14:51 (amazonlinux) any->sca
    Rule: 19004 (level 7) -> 'SCA summary: CIS Benchmark for Amazon Linux 1: Score less than 50% (38)'
    {"type":"summary","scan_id":1763775767,"name":"CIS Benchmark for Amazon Linux 1","policy_id":"cis_amazon_linux_1","file":"cis_amazon_linux_1.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Amazon Linux systems running on x86 and x64 platforms. This document was tested against CentOS 6.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":68,"failed":108,"invalid":3,"total_checks":179,"score":38.6363639831543,"start_time":1659716067,"end_time":1659716076,"hash":"bf43d52afc762e1ec37db46bec4559677d3f38453b9109595830493c3ca6796a","hash_file":"180c6e24103ddb7d9a5b093e2a98186d2bca7b8d79019337842e65e453d3de3a","force_alert":"1"}
    sca.type: summary
    sca.scan_id: 1763775767
    sca.policy: CIS Benchmark for Amazon Linux 1
    sca.description: This document provides prescriptive guidance for establishing a secure configuration posture for Amazon Linux systems running on x86 and x64 platforms. This document was tested against CentOS 6.
    sca.policy_id: cis_amazon_linux_1
    sca.passed: 68
    sca.failed: 108
    sca.invalid: 3
    sca.total_checks: 179
    sca.score: 38
    sca.file: cis_amazon_linux_1.yml
    ```
    

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly. The policy for AL1 is loaded correctly, although 3 checks come up as not applicable. The developers tell us that they have to do a review and rework later.
