### ISSUE TITLE
QA testing - Improve Amazon Linux 2 filter for control 1.5.2

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3149]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|              4.3.7          |            https://github.com/wazuh/wazuh/pull/14484            |          https://github.com/wazuh/wazuh/issues/13949          |

## Description

This improves the filtering options for the rule in check 1.5.2 of Amazon Linux 2.

## Proposed checks

- [x] Verify that SCA policy on Amazon Linux 2 with old command options works
- [x] Upgrade 4.3.6 to 4.3.7: Verify new command options works
- [x] Fresh Install: Verify new command options works

## Expected results

The check works as expected

## Configuration and considerations

Use wazuh-agent 4.3.7

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @QU3B1M    |  [22bcb48](https://github.com/wazuh/wazuh/pull/14484/commits/22bcb482f8fa95fe7442aa83a211d524d854e75f)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Amazon Linux  |    2      | Local - Vagrant |       [bento/amazonlinux-2](https://app.vagrantup.com/bento/boxes/amazonlinux-2)      |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [4.3.7](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.7-0.commit22bcb48.x86_64.rpm )             | [4.3.7](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.7-0.commit22bcb48.x86_64.rpm  )   |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by QU3B1M** [comment]
# SCA policy on Amazon Linux 2 with old command

<details>
  <summary><strong>Verify SCA policy with id 20529 runs the old command and it is not precise enough</strong></summary>

- Install Wazuh Agent 
- Setup debug mode for sca
- Check logs (`/var/ossec/logs/ossec.log`)
```
2022/08/05 17:22:41 sca[6332] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:sh -c "journalctl | grep \"protection: \" | tail -1" -> r:protection: active'
2022/08/05 17:22:41 sca[6332] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "journalctl | grep \"protection: \" | tail -1" -> r:protection: active': 1
2022/08/05 17:22:41 sca[6332] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 1
2022/08/05 17:22:50 sca[6332] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'passed'
```
- Disable the XD/NX support
```
grubby --update-kernel=ALL --args="noexec=off"
```
- Reboot the host
- Run SCA scan and check that check `20529` do not update as failed.
```
2022/08/05 17:25:06 sca[5535] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 1
2022/08/05 17:25:11 sca[5535] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'passed'

```
</details>

**Comment by QU3B1M** [comment]
# Verify new command options works

<details>
<summary><strong>Upgrade & Verify SCA policy with id 20529 runs the new command and it is precise </strong></summary>

- With Wazuh Agent 4.3.6 installed upgrade it to [4.3.7 with fix](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.7-0.commit22bcb48.x86_64.rpm)
- Setup debug mode for sca
- Check logs (`/var/ossec/logs/ossec.log`) and verify the new command is used
```
2022/08/08 11:32:58 sca[5316] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:protection: active)(sh -c "journalctl -k --boot | grep \"protection: \" | tail -1") -> 1
2022/08/08 11:32:58 sca[5316] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "journalctl -k --boot | grep \"protection: \" | tail -1" -> r:protection: active': 1
2022/08/08 11:32:58 sca[5316] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 1
2022/08/08 11:33:02 sca[5316] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'passed'
```
- Disable the XD/NX support
- Reboot the host
- Run SCA scan and check that check `20529` updates as failed.
```
2022/08/08 11:36:57 sca[5302] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:protection: active)(sh -c "journalctl -k --boot | grep \"protection: \" | tail -1") -> 0
2022/08/08 11:36:57 sca[5302] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "journalctl -k --boot | grep \"protection: \" | tail -1" -> r:protection: active': 0
2022/08/08 11:36:57 sca[5302] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 0
2022/08/08 11:37:02 sca[5302] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'failed'

```

</details>

**Comment by QU3B1M** [comment]
# Verify new command options works - Fresh Install

<details>
<summary><strong>On a fresh installation verify SCA policy with id 20529 runs the new command :green_circle:  </strong></summary>

- Install Wazuh Agent using a package[4.3.7 with fix](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.7-0.commit22bcb48.x86_64.rpm)
- Setup debug mode for sca
- Check logs (`/var/ossec/logs/ossec.log`) and verify the new command is used
   ```
    2022/08/09 17:31:28 sca[6390] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:protection: active)(sh -c "journalctl -k --boot | grep \"protection: \" | tail -1") -> 1
    2022/08/09 17:31:28 sca[6390] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "journalctl -k --boot | grep \"protection: \" | tail -1" -> r:protection: active': 1
    2022/08/09 17:31:28 sca[6390] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 1
    2022/08/09 17:31:32 sca[6390] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'passed'

   ```
- Disable the XD/NX support
- Reboot the host
- Run SCA scan and check that check `20529` updates as failed.
   ```
    2022/08/09 17:40:04 sca[3568] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:protection: active)(sh -c "journalctl -k --boot | grep \"protection: \" | tail -1") -> 0
    2022/08/09 17:40:04 sca[3568] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "journalctl -k --boot | grep \"protection: \" | tail -1" -> r:protection: active': 0    
    2022/08/09 17:40:04 sca[3568] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 20529 'Ensure XD/NX support is enabled.' -> 0
    2022/08/09 17:40:14 sca[3568] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 20529; Result: 'failed'

   ```

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
