### ISSUE TITLE
Enhancement - Refactor system tests of environment `big_cluster_40_agents`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3152]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `agentless_cluster` environment.

### List of tests
- [x] wazuh/wazuh-qa#3327
- [ ] Refactor system test `test_groups_sync_time`

**Comment by davidjiglesias** [comment]
As part of all the changes for 5.0.0 these tests are deprecated.
