### ISSUE TITLE
Enhancement - Refactor system tests of environment `basic_environment`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3153]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `agentless_cluster` environment.

### List of tests
- [ ] Refactor system test `test_agent_auth`
- [ ] Refactor system test `test_enrollment`

**Comment by davidjiglesias** [comment]
As part of all the changes for 5.0.0 these tests are deprecated.
