### ISSUE TITLE
QA testing - Standardize time zone in InstallDate field in Windows package information

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3158]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| master                       | https://github.com/wazuh/wazuh/issues/13884                       | https://github.com/wazuh/wazuh/pull/14161                   |

## Description

Currently, SysInfo in Windows agents is reporting the `install_time` field with the system's local time. It would be great if the time in this field could be in a standard format such as UTC to synchronize with the same time zone the `install_time` field in all agents.

## Proposed checks

- Fresh Install to reproduce the bug

- Fresh install with the bug fixed:
  
  - [x] Check that packages that have the `installDate` entry in the registry and the value differ from the key modification time, assign the time as 00:00:00
  - [x] Check that packages that don't have the `installDate` entry in the registry use the key modification time in UTC format.

- Upgraded Install with the new fix: 
  
  - [x] Check that packages that have the `installDate` entry in the registry and the value differ from the key modification time, assign the time as 00:00:00
  - [x] Check that packages that don't have the `installDate` entry in the registry use the key modification time in UTC format.

## Steps to reproduce

- Download the 7-Zip installer or download Telegram from the Windows Store.
- Install it and check the current time of installation.
- Run the test tool or scan the packages with the agent and validate the `install_time` of the installed package.

## Expected results

The `install_time` field shows the time in UTC format

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [6ebc88a](https://github.com/wazuh/wazuh/pull/14499/commits/6ebc88a5b819b8900207fee1424c9accb1ee1403)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Windows | Server 2016 | `LOCAL \| VBox` | [evalcenter/windows-server-2016](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2016)

### Tested Packages

| wazuh-manager | wazuh-agent |
|-----------------------|-------------------|
| [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commit6ebc88a_amd64.deb) | [win](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/windows/wazuh-agent-4.5.0-0.commit6ebc88a.msi)
### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by QU3B1M** [comment]
# Execute tests using wazuh-agent 4.5 (master)

<details>
<summary>Check that packages that have the installDate entry</summary>

- Install Xbox package from the Microsoft Store 
![no-fix-xbox-installation](https://user-images.githubusercontent.com/44633633/186230934-fb561971-e8d9-43cc-8aae-9e68689025e5.png)
- Check the `install_time` collected by `syscollector`
![no-fix-xbox-datetime](https://user-images.githubusercontent.com/44633633/186231136-6416b45e-e805-407f-9665-5b5e39fdd350.png)

</details>


<details>
<summary>Check that packages that doesn't have the installDate entry</summary>

- Install 7zip package from binary
![no-fix-7zip-installation](https://user-images.githubusercontent.com/44633633/186232224-d047fae7-369a-405b-8d93-eee623506757.png)

- Check the `install_time` collected by `syscollector`
![image](https://user-images.githubusercontent.com/44633633/186232463-3f9201b4-b1af-44d8-9b5f-35fab9f0fa2c.png)

</details>

**Comment by QU3B1M** [comment]
# Execute tests using wazuh-agent Fixed (Upgrade) :green_circle: 

<details>
<summary>Check that packages that have the installDate entry</summary>

- Install Xbox package from the Microsoft Store 
![fix-xbox-installation](https://user-images.githubusercontent.com/44633633/186236224-3bee18f8-a72f-49e1-a980-0b2e6fb11ed3.png)

- Check the `install_time` collected by `syscollector` uses UTC datetime
![fix-xbox-install-date](https://user-images.githubusercontent.com/44633633/186236332-dca54f54-17a6-4aca-b15f-4d53e31462bf.png)


</details>


<details>
<summary>Check that packages that doesn't have the installDate entry</summary>

- Install 7zip packag
![fix-7zip-installation](https://user-images.githubusercontent.com/44633633/186240798-6175a996-7608-4790-987f-8ac93374a67e.png)
e from binary

- Check the `install_time` collected by `syscollector` uses UTC datetime
![fix-7zip-installation-date](https://user-images.githubusercontent.com/44633633/186241009-105ecac4-b74c-413e-af14-bcb270a6a9bf.png)


</details>

**Comment by QU3B1M** [comment]
# Execute tests using wazuh-agent Fixed (Fresh Install) :green_circle: 

<details>
<summary>Check that packages that have the installDate entry</summary>

- Install Xbox package from the Microsoft Store 
![fresh-install-xbox](https://user-images.githubusercontent.com/44633633/186248769-9b6e6943-c408-43fa-9830-42a542f37e19.png)


- Check the `install_time` collected by `syscollector` uses UTC datetime
![fresh-install-xbox-date](https://user-images.githubusercontent.com/44633633/186248768-12c986c2-f94e-44ac-8343-15f95754934d.png)



</details>


<details>
<summary>Check that packages that doesn't have the installDate entry</summary>

- Install 7zip package from binary
![fresh-install-7zip](https://user-images.githubusercontent.com/44633633/186248893-e76d22e2-779a-42eb-8af6-1fb9ee19838b.png)


- Check the `install_time` collected by `syscollector` uses UTC datetime
![fresh-install-7zip-date](https://user-images.githubusercontent.com/44633633/186248897-46cbe015-c7bf-4d50-9a81-0197973cb9b5.png)


</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
