### ISSUE TITLE
QA testing - Invalid calling convention for stop functions

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-qa#3159]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4                       | https://github.com/wazuh/wazuh/issues/13077                       | https://github.com/wazuh/wazuh/pull/14486                   |

## Description
Segmentation fault during shutdown on Windows.

## Proposed checks
- [x] Fresh Install 4.4: Check that no segfault is caused when stopping Windows Agent.
- [x] Update - Check that no segfault is caused when stopping Windows Agent 🟢
- [x] Fresh Install on brach with fix - Check that no segfault is caused when stopping Windows Agent 🟢 
- [x] Check AR IT

## Steps to reproduce
- [x] Install and register agent.
- [x] Shutdown agent service through manage_agent.exe application. 
- [x] Check Application Event log.

## Expected results
1. No segfault and error log in application event log..

## Configuration and considerations
- Default.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 |  [d6e6d0b](https://github.com/wazuh/wazuh/commit/d6e6d0b48cbbb9ba089ea01ae95187a7e78f3782)  | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |
| Windows | Server 2019 | `<LOCAL \| Vagrant` |   qactl/windows_server2019        |       |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [master .rpm Manager](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.5.0-0.40500.20220805.x86_64.rpm)  ---   [dev branch .rpm Manager](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-3147.cpe.helper.fix.x86_64.rpm)            |  [.rpm agent]()      |

### Conclusion 



### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Test on 4.4
<details>
<summary>Check that no segfault is caused when stopping Windows Agent :red_circle: </summary>

1. Install and Start windows Agent
![imagen](https://user-images.githubusercontent.com/14501079/183736034-c02e8035-e54f-4820-8a32-22993ca9f6e7.png)

2. Check Event Viewer for Application Errors - no application errors present :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/183736470-3a48ceca-09cd-43bb-929b-a8bd03791ed4.png)
3. Stop Windows Agent
4. Check Event Viewer that No Application Error has been caused :red_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/183737836-9178408d-a695-4165-bea2-ad2a13baf768.png)
5. Check alert in alerts.json
   ```
   # tail -f /var/ossec/logs/alerts/alerts.json | grep "Application Error"
   {"timestamp":"2022-08-09T18:47:41.342+0000","rule":{"level":9,"description":"Windows application error event.","id":"60602","firedtimes":1,"mail":false,"groups":["windows","windows_application","system_error"],"gdpr":["IV_35.7.d"],"gpg13":["4.3"]},"agent":{"id":"005","name":"WIN-JLGVA4CR4VI"},"manager":{"name":"c3"},"id":"1660070861.3143502","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Application Error","eventID":"1000","level":"2","task":"100","keywords":"0x80000000000000","systemTime":"2022-08-09T18:47:43.229327400Z","eventRecordID":"1390","channel":"Application","computer":"WIN-JLGVA4CR4VI","severityValue":"ERROR","message":"\"Faulting application name: wazuh-agent.exe, version: 0.0.0.0, time stamp: 0x62f2711c\r\nFaulting module name: sechost.dll, version: 10.0.17763.1, time stamp: 0xec52cb01\r\nException code: 0xc0000005\r\nFault offset: 0x00015896\r\nFaulting process id: 0x2f4\r\nFaulting application start time: 0x01d8ac2080b576ce\r\nFaulting application path: C:\\Program Files (x86)\\ossec-agent\\wazuh-agent.exe\r\nFaulting module path: C:\\Windows\\System32\\sechost.dll\r\nReport Id: f92bab6b-ba92-4b22-a0d0-90765a58884c\r\nFaulting package full name: \r\nFaulting package-relative application ID: \""},"eventdata":{"data":"wazuh-agent.exe, 0.0.0.0, 62f2711c, sechost.dll, 10.0.17763.1, ec52cb01, c0000005, 00015896, 2f4, 01d8ac2080b576ce, C:\\\\Program Files (x86)\\\\ossec-agent\\\\wazuh-agent.exe, C:\\\\Windows\\\\System32\\\\sechost.dll, f92bab6b-ba92-4b22-a0d0-90765a58884c"}}},"location":"EventChannel"}
   ```
</details>

## Test on dev branch
<details>
<summary>Check that no segfault is caused when stopping Windows Agent</summary>

1. Install and Start windows Agent
![imagen](https://user-images.githubusercontent.com/14501079/183736034-c02e8035-e54f-4820-8a32-22993ca9f6e7.png)

2. Check Event Viewer for Application Errors - no application errors present :green_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/183736470-3a48ceca-09cd-43bb-929b-a8bd03791ed4.png)
3. Stop Windows Agent
4. Check Event Viewer that No Application Error has been caused :red_circle: 
![imagen](https://user-images.githubusercontent.com/14501079/183737836-9178408d-a695-4165-bea2-ad2a13baf768.png)
5. Check alert in alerts.json
   ```
   # tail -f /var/ossec/logs/alerts/alerts.json | grep "Application Error"
   {"timestamp":"2022-08-09T18:47:41.342+0000","rule":{"level":9,"description":"Windows application error event.","id":"60602","firedtimes":1,"mail":false,"groups":["windows","windows_application","system_error"],"gdpr":["IV_35.7.d"],"gpg13":["4.3"]},"agent":{"id":"005","name":"WIN-JLGVA4CR4VI"},"manager":{"name":"c3"},"id":"1660070861.3143502","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Application Error","eventID":"1000","level":"2","task":"100","keywords":"0x80000000000000","systemTime":"2022-08-09T18:47:43.229327400Z","eventRecordID":"1390","channel":"Application","computer":"WIN-JLGVA4CR4VI","severityValue":"ERROR","message":"\"Faulting application name: wazuh-agent.exe, version: 0.0.0.0, time stamp: 0x62f2711c\r\nFaulting module name: sechost.dll, version: 10.0.17763.1, time stamp: 0xec52cb01\r\nException code: 0xc0000005\r\nFault offset: 0x00015896\r\nFaulting process id: 0x2f4\r\nFaulting application start time: 0x01d8ac2080b576ce\r\nFaulting application path: C:\\Program Files (x86)\\ossec-agent\\wazuh-agent.exe\r\nFaulting module path: C:\\Windows\\System32\\sechost.dll\r\nReport Id: f92bab6b-ba92-4b22-a0d0-90765a58884c\r\nFaulting package full name: \r\nFaulting package-relative application ID: \""},"eventdata":{"data":"wazuh-agent.exe, 0.0.0.0, 62f2711c, sechost.dll, 10.0.17763.1, ec52cb01, c0000005, 00015896, 2f4, 01d8ac2080b576ce, C:\\\\Program Files (x86)\\\\ossec-agent\\\\wazuh-agent.exe, C:\\\\Windows\\\\System32\\\\sechost.dll, f92bab6b-ba92-4b22-a0d0-90765a58884c"}}},"location":"EventChannel"}
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
