### ISSUE TITLE
QA testing - Fixing regex in check 5.1.1 of Ubuntu 20.04 SCA

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3160]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.3.7              |          https://github.com/wazuh/wazuh/issues/14235              |           https://github.com/wazuh/wazuh/pull/14513         |

## Description

This issue solves one of the problems found in ubuntu 20.04 SCA. 
There is a rework process that will manage the other issues. 

This will solve: https://github.com/wazuh/wazuh/issues/14235#issuecomment-1195434435

## Proposed checks

- [x] Test on 4.3.6: Verify that control - id: 19137 works properly 
- [x] Upgrade - Check SCA check #19137 passes

## Expected results

Control works after solution.

## Configuration and considerations

Use Wazuh-agent 4.3.7

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake  | [caaad2c](https://github.com/wazuh/wazuh/commit/caaad2c5a3dd632e76805621c0b8678483d1c586) | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Linux   |  Centos8 | `LOCAL\| Vagrant` | qactl/ubuntu20_04 |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [.db Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.7-0.commitcaaad2c_amd64.deb)  | ---- |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Test on 4.3.6

## Test on dev branch

<details>
<summary>Check SCA check #19137 passes :green_circle: </summary>

1. Start manager

2. Wait for initial sca scan
3. Check SCA alerts
   ```
   ** Alert 1660048221.380208: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
   2022 Aug 09 12:30:21 test->sca
   Rule: 19008 (level 3) -> 'CIS benchmark for Ubuntu Linux 20.04 LTS: Ensure cron daemon is enabled and running.'
{"type":"check","id":756660480,"policy":"CIS benchmark for Ubuntu Linux 20.04 LTS","policy_id":"cis_ubuntu20-04","check":{"id":19137,"title":"Ensure cron daemon is enabled and running.","description":"T>
   sca.type: check
   sca.scan_id: 756660480
   sca.policy: CIS benchmark for Ubuntu Linux 20.04 LTS
   sca.check.id: 19137
   sca.check.title: Ensure cron daemon is enabled and running.
   sca.check.description: The cron daemon is used to execute batch jobs on the system.
   sca.check.rationale: While there may not be user jobs that need to be run on the system, the system does have maintenance jobs that may include security monitoring that have to run, and cron is used to >
   sca.check.remediation: Run the following command to enable cron: systemctl --now enable cron
   sca.check.compliance.cis: 5.1.1
   sca.check.compliance.cis_csc: 6
   sca.check.compliance.pci_dss: 2.2.4
   sca.check.compliance.nist_800_53: CM.1
   sca.check.compliance.tsc: CC5.2
   sca.check.command: ["systemctl is-enabled cron", "systemctl status cron"]
   sca.check.result: passed
   ```
4. Check that cron is actually enabled
   ```
   # systemctl is-enabled cron
   enabled

   # systemctl status cron
   :green_circle:  cron.service - Regular background program processing daemon
        Loaded: loaded (/lib/systemd/system/cron.service; enabled; vendor preset: enabled)
        Active: active (running) since Tue 2022-08-09 12:10:08 UTC; 48min ago
          Docs: man:cron(8)
      Main PID: 684 (cron)
      Tasks: 1 (limit: 7028)
        Memory: 1.1M
        CGroup: /system.slice/cron.service
                └─684 /usr/sbin/cron -f

   Aug 09 12:10:08 test systemd[1]: Started Regular background program processing daemon.
   Aug 09 12:10:08 test cron[684]: (CRON) INFO (pidfile fd = 3)
   Aug 09 12:10:08 test cron[684]: (CRON) INFO (Running @reboot jobs)
   Aug 09 12:17:01 test CRON[1509]: pam_unix(cron:session): session opened for user root by (uid=0)
   Aug 09 12:17:01 test CRON[1516]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
   Aug 09 12:17:01 test CRON[1509]: pam_unix(cron:session): session closed for user root
   ```
</details>

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
