### ISSUE TITLE
Investigate `test_agentd_multi_server` integration test error

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3183]
While running the integration tests for the `4.3.7-rc1` release using the `4.3` branch of `wazuh-qa`, a problem was detected related to `agentd` on Windows. The same test has been rerun for several times and all other times it has passed successfully.

| Round 1 | Round 2 | Round 3 | Round 4 | Round 5 |
|--|--|--|--|--|
|🔴| 🟢 | 🟢 | 🟢 | 🟢 |

The reported problem is the [following](https://ci.wazuh.info/job/Test_integration/30644/artifact/windows_agent_tests_Test_integration_B30644_20220816115016.txt)

```
AssertionError: Expected message Requesting a key from server: testServer1 never arrived! Stage: 0, message number: 0

=========================== short test summary info ===========================
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[server_down_fallback_tcp]
======= 1 failed, 27 passed, 6 skipped, 1 warning in 2241.80s (0:37:21) =======
```

The same behavior has also been observed in the `4.4` branch, where this test [has also failed](https://ci.wazuh.info/job/Test_integration/30788/artifact/windows_agent_tests_Test_integration_B30788_20220817104344.txt):

| Round 1 | Round 2 | Round 3 |
|--|--|--|
|🔴| 🔴 | 🟢 |

```
AssertionError: Expected message 'Requesting a key from server: testServer1' never arrived! Stage: 1, message number: 1

=========================== short test summary info ===========================
FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[server_down_fallback_tcp]
======= 1 failed, 27 passed, 6 skipped, 1 warning in 2222.02s (0:37:02) =======
```

It is requested to investigate this case, to know if there is any fix to be applied in this test or in the `remoted/authd` simulator.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09    |  v4.3.7-2   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Windows    |  Server     | `REMOTE/Test_Integration Pipeline` |         |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by damarisg** [comment]
This issue was closed because we couldn't reproduce it.
