### ISSUE TITLE
QA testing - Solve OS detection rule bug on SCA Ubuntu 22.04

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3186]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.3.7               |          https://github.com/wazuh/wazuh/issues/14663              |       https://github.com/wazuh/wazuh/pull/14678             |

## Description

Solves a bug in Ubuntu Linux 22.04 SCA policy that prevents a wazuh-agent from running the Policy if version is a patch version of 22.04 
 
## Proposed checks

- [x] SCA Ubuntu 22.04 policy runs automatically on an Ubuntu Linux 22.04.1 system

## Expected results
Policy is executed 

## Configuration and considerations

None

**Comment by Deblintrake09** [comment]
## Task Results on 4.3.7-1
<details>
<summary>Check SCA scan runs for Ubuntu 22.04 agent</summary>
- Setup manager
- Setup agent and start
- Check manager's logs
- Check SCA alerts in alerts.json
</details>

## Task Results on dev branch

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
