### ISSUE TITLE
Tests development - Backport cluster zip size system test

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#3200]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|4.3|https://github.com/wazuh/wazuh/issues/14742|https://github.com/wazuh/wazuh/pull/14746|

## Description
The system test below was developed for the changes performed at https://github.com/wazuh/wazuh/issues/12504. However, those changes will be backported to 4.3 so the system test should also be moved:
- https://github.com/wazuh/wazuh-qa/pull/2582

**Comment by davidjiglesias** [comment]
Change reverted in https://github.com/wazuh/wazuh-qa/pull/3291
