### ISSUE TITLE
E2E tests: Add markers to specify supported OS

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3204]
## Description

After the debugging and testing done in https://github.com/wazuh/wazuh-qa/issues/3166 we could see that the test couldn't be executed depending on the OS because there were no markers.

- [x] (**T1**) Add markers depending on the supported OS.

**Comment by BelenValdivia** [comment]
## T1: Add markers depending on the supported OS.

### Linux
1. Run test as follows:

```
python -m pytest tests/end_to_end/test_basic_cases/ -m linux --inventory_path=/home/belen/Repositories/wazuh-qa/tests/end_to_end/general_playbooks/inventory_jenkins.yaml --html=3204-T1-R${i}-e2e-belenvaldivia.html --self-contained-html
```

### Windows
1. Run test as follows:

```
python -m pytest tests/end_to_end/test_basic_cases/ -m win32 --inventory_path=/home/belen/Repositories/wazuh-qa/tests/end_to_end/general_playbooks/inventory_jenkins.yaml --html=3204-T1-R${i}-e2e-belenvaldivia.html --self-contained-html
```
