### ISSUE TITLE
E2E tests: Research Brute Force tests failures

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3208]
## Description

After the debugging and testing achieved in https://github.com/wazuh/wazuh-qa/issues/3166, we could see that the tests in test_brute_force were failing, so we must find the reason for the failure and a solution for it.

### Executions

- https://github.com/wazuh/wazuh-qa/issues/3166#issuecomment-1228250975
- https://github.com/wazuh/wazuh-qa/issues/3166#issuecomment-1228386460

**Comment by juliamagan** [comment]
The RDP failure seems to be produced by the hydra version because it just fails in @BelenValdivia environment. Her error message has `passwords` in plural, while we expect `password`. We should install a specific hydra version.

My current hydra version is:

```
hydra -v
Hydra v9.2 (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
```

**Comment by BelenValdivia** [comment]
I execute the rdp test with Hydra v9.0

**Comment by BelenValdivia** [comment]
I upgraded to Ubuntu 22.04 and Hydra v9.2 and the test passed

**Comment by mauromalara** [comment]
I fixed the `test_brute_force_rdp` test by specifying the version of Hydra to be installed (v9.2).

Also, I added a role to search for the alert before fetching the `alerts.json`.
