### ISSUE TITLE
Refactor/Fix flaky tests on windows and Ubuntu

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3218]
## Description
During testing and research done for Issue #3195, it was found that some tests had flaky behaviour on Windows and Linux. This tests have been skipped and require further research and to be refactor/fix before the skip can be removed.

The tests failed mainly on jenkins, and replicating the error locally was not achieved. On repeated testing instances on Jenkins the following tests failed as detailed:

- Windows
   - `test_logcollector/test_configuration/test_basic_configuration_age.py` - Failed 1 time
   - `test_logcollector/test_configuration/test_basic_configuration_query.py`- Failed 1 time
   - `test_logcollector/test_command_monitoring/test_command_execution_freq.py ` - Failed 4 times
   - `test_logcollector/test_configuration/test_basic_configuration_only_future_events.py` - Failed 1 time
- Linux (Ubuntu)
   - `test_logcollector/test_command_monitoring/test_command_execution_dbg.py` - Failed 1 time
   - `tests/integration/test_logcollector/test_age/test_age_datetime_changed.py` - https://github.com/wazuh/wazuh-jenkins/issues/4986

### Test evidence
| Tests path | OS | Results |
|---|---|---|
| test_logcollector| Windows, Centos & Ubuntu | [:green_circle:](https://ci.wazuh.info/job/Test_integration/31045/parameters/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31067) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31068) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31069) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31070) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31077) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31078) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31079) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31082/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31086) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31115/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31116/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31117/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31123) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31124) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31125) [:green_circle:](https://ci.wazuh.info/job/Test_integration/31126/) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31076) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31080) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31083) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31084) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31085) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/31121) [:red_circle:](https://ci.wazuh.info/job/Test_integration/31122) |

### Current behavior
The tests fail randomly on Windows/Ubuntu

### Expected behavior
The tests are no longer flaky.

**Comment by Deblintrake09** [comment]
## Research done during #3195 

- `test_logcollector/test_configuration/test_basic_configuration_age.py:` seems to have a timeout issue regarding when the expected message appears. On PR #3127 the timeout has been increased and the test failed only once (it failed with more regularity before.
- `test_logcollector/test_command_monitoring/test_command_execution_freq.py`: This test structure has a conflicting structure, It is not clear when it fails what is the actual cause, since it uses a `Filemonitor` that does not wait for it to end and the rest of the test continues, having superimposed monitors and a monitor that would not be launched with the current structure.
- The rest of the tests have not had enough research about the possible cause.

**Comment by fedepacher** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @fedepacher  |  []() |



### Testing environment


| OS | OS version | Deployment | Image/AMI | Architecture |
|-- |-- |-- |-- | --- |
| Ubuntu |   |  EC2 | `` | amd64 |
| Centos |   |  EC2 | `` | amd64 |
| Windows |   |  EC2 | `` | amd64 |
| Macos |   |  EC2 | `` | amd64 |




### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211


### Conclusion :yellow_circle:

As tests fail randomly it has decided to refactor tests and add the new structure.
The new structure implemented is based on:
- configuration_template: Contains `yaml` file with each test configuration.
- test_cases: Contains `yaml` file with the group of cases to be tested for each test

Furthermore, a bug on QA Framework was found. The `_win_set_time` static function of `TimeMachine` class parses the date
as `%d/%m/%Y %H:%M:%S` but it should be parsed as `%m/%d/%Y %H:%M:%S`.

**Comment by fedepacher** [comment]
# Update 2022/10/13

In order to avoid date format failure in the `Windows` test, it has created a `Module scope` fixture to change the date format when it is needed and restored after finishing the test.
