### ISSUE TITLE
E2E: Adapt Vulnerability Detector test for Ubuntu Jammy

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3219]
## Description

Vulnerability Detector test was designed for Ubuntu Focal in local executions, but in Jenkins, the available AMI is Ubuntu Jammy, so  we must change the test to look for vulnerabilities of this OS. In the future, we will have to consider expanding the supported OS.

**Comment by juliamagan** [comment]
While testing the changes, we could see that the same problem found in #3199 was happening. This test will be marked as `xfail` until https://github.com/wazuh/wazuh/issues/14736 is solved.

**Comment by juliamagan** [comment]
## Update 28/06/2023

Investigating why some executions fail. When they are launched locally they do not fail, but when several are launched in Jenkins, some of them fail, but it does not make sense that it is because they are launched at the same time since each one is launched from a different node and with a different environment, so they are independent. It always fails because it does not find the alert, it could be a timeout problem, but it is weird because it is looking for the alerts in a file that is not updated, and previously, it has checked that the vulnerability scan has finished, so the alert should have appeared.

**Comment by juliamagan** [comment]
### Update

We need to change the base version to meet the expected dates.

**Comment by BelenValdivia** [comment]
LGTM!
