### ISSUE TITLE
QA Planning: Research on Alpine Linux support 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3223]
## Description

This problem aims to investigate [Wazuh Agent package for Alpine Linux](https://github.com/wazuh/wazuh/issues/4592) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Task results

## Researched the applied change

Applied changes only affect the installation script and logcollector module. 

##  Research if we have a test for this case

- There is logcollector ITs for Linux agents, related to the  specific module affected. 
- All agent test suites should be checked for this new OS to see if they work correctly.
