### ISSUE TITLE
QA Planning: The new support of PCRE2 regex for SCA policies 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3228]
## Description

This problem aims to investigate [Feature request: PCRE2 regex for SCA policies](https://github.com/wazuh/wazuh/issues/13931) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Research results

The changes applied allow for SCA to use PCRE2 or OS-Regex as regex engines. This can be changed on a per-check basis by adding the `regex-time` parameter in the yaml policy file.

## Current testing
There is a set of tests for SCA located in `test/legacy/sca` but the python test files are missing. They only contain the yaml files for configuration. So they are not currently working.

## Define testing

This could be tested manually, but it would require require the generation of rules for it. So it would be advised to do either Integration testing, using the manager to test the SCA rules on the manager. System tests could be generated to test SCA on the agent.
