### ISSUE TITLE
FIM v2.0: Jenkins pipelines for metrics

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#323]
## Description

This issue covers the creation of pipelines to automate the FIM testing, in particular, to generate metrics in order to detect performance issues (usage of CPU and memory, synchronization and scan times).

**Common requirements**

- Generate CSV reports and graphics for all pipelines.
- Include all system specs in every report:
  - Operating system: name and version.
  - CPU: Processor, available cores, and clock speed.
  - Memory: amount and speed.
  - Disk: type (SSD|HDD), available space, and file system
- All pipelines must be configurable in terms of FIM attributes (size, sha256, permissions, owner, group, mtime…)
- All pipelines must be available for supported platforms (Linux, Windows, macOS)

# Metrics for memory usage

|Related issue|Implied teams|
|---|---|
|https://github.com/wazuh/wazuh-qa/issues/306| @wazuh/core , @wazuh/cicd | 
|https://github.com/wazuh/wazuh-jenkins/issues/1052 | @wazuh/core , @wazuh/cicd | 

The goal of the memory usage test is to determine how the FIM configuration and monitored files affect the memory usage during the FIM module is working.

**Requirements**

- Reports have to contain information about the memory usage during the test.
- The pipeline must be configurable in terms of monitored files: path size (8-4000 bytes), and the total number of files (0, 10k,20k,50k,100k,200k,500k,1M)

_Current status:_ To be developed. Currently, the metrics are collected by hand.
_Progress:_ 0%
_ETA:_ 25 days
_Completion date:_ 01/23/2020

# Metrics for CPU impact

|Related issue|Implied teams|
|---|---|
|https://github.com/wazuh/wazuh-qa/issues/307| @wazuh/core , @wazuh/cicd | 
|https://github.com/wazuh/wazuh-jenkins/issues/1052 | @wazuh/core , @wazuh/cicd | 

The goal of the CPU usage test is to get metrics about the CPU impact and time scan depending on the scenario (system resources and monitored files size).

**Requirements**

- Reports have to contain the CPU usage for the _syscheckd_ process during the scans, as well as the time the scans take.
- The pipeline must be configurable in terms of monitored files: path size (8-4000 bytes), and the total number of files (0, 10k,20k,50k,100k,200k,500k,1M)

_Current status:_ To be developed. Currently, the metrics are collected by hand.
_Progress:_ 0%
_ETA:_ 25 days
_Completion date:_ 01/23/2020

# Metrics of FIM synchronization time

|Related issue|Implied teams|
|---|---|
|https://github.com/wazuh/wazuh-qa/issues/308| @wazuh/core , @wazuh/cicd | 
|https://github.com/wazuh/wazuh-jenkins/issues/1053 | @wazuh/core , @wazuh/cicd | 

The goal of this test is to answer the following questions:
- Compare the synchronization protocol in both the best and the worst case.
- Know how the synchronization time depends on the number of files.

**Requirements**

- The pipeline must be configurable in terms of:
  - Performance options (max_eps, sync_interval, sync_queue_size)
  - Number of FIM files
  - Number of agents
  - Protocol (UDP/TCP)
  - Best and worst cases (clean DB vs full DB)

_Current status:_ To be developed. Currently, the metrics are collected by hand.
_Progress:_ 0%
_ETA:_ 16 days
_Completion date:_ 01/17/2020

**Comment by Molter73** [comment]
Closing this issue since this functionality has already being developed.
