### ISSUE TITLE
QA planning: Logcollector events wrongly parsed for filenames with colons

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3230]
## Description

This problem aims to investigate [Logcollector events wrongly parsed for filenames with colons (:) ](https://github.com/wazuh/wazuh/issues/10489) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
# Task results

<details><summary>Research the applied change.</summary>

This change affects the module `logcollector`, before this fix, the wazuh-manager is not correctly parsing the data that comes from files with a `:` on its name. More specifically the issue is that the "location" comes only with the _path_ and the part of the filename that comes after the `:`, the rest of the filename is attached in the `full_log` section.
> The event data before this change:
> ```JSON
> {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"filename-with:{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/colons.log"}
> ```

> The expected event data after this change:
> ```JSON
> {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/filename-with:colons.log"}
> ```

</details>

<details><summary>Research if we have a test for this case.</summary>

For now, in our automated tests, we are not testing this specific case, anyway we have tests for this particular module, those tests can be found inside `tests/integration/test_logcollector/test_localfile` where the new test cases should be added.
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

<details><summary>Test cases - Tier 0</summary>

- <details><summary>Logfile with a ":"</summary> 

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78:9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78:9.log"}
        > ```
    </details>


- <details><summary>Logfile with no ":"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78-9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
    > expected:
    > ```JSON
    > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78-9.log"}
    > ```
    </details>


- <details><summary>Logfile with ":" captured by matching</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/123-*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78:9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
    > expected:
    > ```JSON
    > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78:9.log"}
    > ```
    </details>

- <details><summary>Logfile captured by matching with ":" in the location tag </summary> 

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/123:*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123:456-78-9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123:456-78-9.log"}
        > ```
    </details>
</details>

<details><summary>Test cases - Tier 2</summary>

- <details><summary>Logfile with two ":"</summary> 

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456:78:9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456:78:9.log"}
        > ```
    </details>

- <details><summary>Logfile starts with ":"</summary> 

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `:123-456-78-9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/:123-456-78-9.log"}
        > ```

    </details>



- <details><summary>Logfile with multiple "."</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456.78.9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456.78.9.log"}
        > ```
    </details>


- <details><summary>Logfile with "&"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78&9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78&9.log"}
        > ```
    </details>

- <details><summary>Logfile with "<"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78<9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78<9.log"}
        > ```
    </details>


- <details><summary>Logfile with "/"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78/9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78/9.log"}
        > ```
    </details>

- <details><summary>Logfile with "|"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78|9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78|9.log"}
        > ```
    </details>
</details>
</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.</summary>

</details>
