### ISSUE TITLE
Tests development - Fix and improves the Wazuh-Logtest IT

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-qa#3231]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|      4.4             | https://github.com/wazuh/wazuh/issues/14767 | https://github.com/wazuh/wazuh/pull/14772 |

## Description

PR https://github.com/wazuh/wazuh/pull/14772 not only fixes the memory problems but also proposes a change in the requirements in the behavior of the `if_sid` option. The [if_sid](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=if_sid#if-sid) only accepts rule ids separated by spaces ('` `') or commas ('`,`'). 

Prior to the RP, all parents had to exist or the rule was ignored. Now, the rule is not ignored if it has at least one parent that exists because it can be added to the rule tree.
 
It is necessary to fix the logtest integration test, adjusting to the new warning messages and test the new cases. In the PR there are multiple use cases and their outputs.
Multiple use cases, with examples of logtest results, can be found https://github.com/wazuh/wazuh/pull/14772 and  https://github.com/wazuh/wazuh-qa/issues/3224

## Configurations

They can be tested with the following decoder, rule and log configurations, just changing the if_sid:

#### Rule
```xml
<rule id="100001" level="5">
  <if_sid>XXXXX</if_sid>
  <program_name>asd|ssh</program_name>
  <srcip>1.1.1.1</srcip>
  <description>sshd: authentication failed from IP 1.1.1.1.</description>
  <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
</rule>
```

#### Decoder
```xml
<decoder name="asdasd">
    <program_name>asd</program_name>
    <regex>(\d+.\d+.\d+.\d+)</regex>
    <order>srcip</order>
</decoder>
```
#### Test logs

```
Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
Dec 10 01:02:02 host asd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

## Proposed test cases

- [ ] Proposed test case 1
- [ ] Proposed test case 2
...

## Considerations
These tests should always be validated with a log that attempts to trigger the ignored rules and his parent.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
