### ISSUE TITLE
Prevent Wazuh agents from connecting to a lower Wazuh manager version

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3238]
## Description

This problem aims to investigate [Prevent Wazuh agents from connecting to a lower Wazuh manager version](https://github.com/wazuh/wazuh/issues/11011) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
<details><summary>Research the applied change</summary>

With this modifications, the `wazuh-manager` wont allow an agent with higher version than it to connect, preventing compatibility issues. Although this was not supported before, there was no mechanism to avoid it.

Note: There are modifications in the manager and in the agent, so to test it we should change the versions of the packages with the fix.
</details>

<details><summary>Research if we have a test for this case</summary>

We dont have test cases for this cases
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2</summary>

  > As the fix is in both manager and agent, the testing with agents that doesnt has this modifications may not pass.

  - <details><summary>Manager let the older version agent <strong>with fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

  - <details><summary>Manager let the older version agent <strong>without fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

  - <details><summary>Manager wont let the newer version agent <strong>with fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

  - <details><summary>Manager wont let the newer version agent <strong>without fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

  - <details><summary>Manager let the equal version agent <strong>with fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

  - <details><summary>Manager let the equal version agent <strong>without fix</strong> connect</summary>

    1. Install `wazuh-manager` (4.4) and `wazuh-agent` (4.5)
    2. Start the `wazuh-manager`
    3. Prepare the `wazuh-agent` to connect to the manager
    4. Start the `wazuh-agent`
    5. Check the logs the wazuh-agent is not connected due its version

    </details>

</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues</summary>

We should generate systems testing
</details>
