### ISSUE TITLE
QA Planning: Update netsh Active response for Windows

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3239]
## Description

This problem aims to investigate [Update netsh Active response for Windows](https://github.com/wazuh/wazuh/issues/14504) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
<details><summary>Research the applied change</summary>

This change fixes an error `Host Blocked by route-null` that is trigered on windows when the firewall is disabled. With this modifications, Wazuh will only raise an Alert warning the user that the firewall is down. 
</details>

<details><summary>Research if we have a test for this case</summary>
We don't have tests for this case, this tests should be in the integration, active response category
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2</summary>

The tests execution should be reproduced at least in one Windows version above Windows Server 2012 and one previous to Windows Server 2012.

### Tier 1

- <details><summary>All firewall profiles activated</summary>

  - Install wazuh-manager and a windows wazuh-agent
  - Ensure all the windows firewall profiles are activated
  - Edit the agent's ossec.conf and restart it
    ```xml
    <localfile>
      <location>C:\Users\vagrant\Documents\test.txt</location>
      <log_format>syslog</log_format>
    </localfile>  
    ```  
  - Edit the manager's ossec.conf and restart it
    ```xml
    <active-response>
      <command>netsh</command>
      <location>local</location>
      <rules_id>5716</rules_id>
      <timeout>60</timeout>
    </active-response>
    ```
  - Create the file `test.txt` and inside it put an log string that triggers `active response`
    ```
    Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
    ```
  - Check the `Firewall is disabled` alert is not generated
    > example 
    > ```
    > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.log
    > 
    > ```
  </details>

- <details><summary>Firewall public profile deactivated</summary>

  - Install wazuh-manager and a windows wazuh-agent
  - Deactivate the firewall's public profile 
  - Edit the agent's ossec.conf and restart it
    ```xml
    <localfile>
      <location>C:\Users\vagrant\Documents\test.txt</location>
      <log_format>syslog</log_format>
    </localfile>  
    ```  
  - Edit the manager's ossec.conf and restart it
    ```xml
    <active-response>
      <command>netsh</command>
      <location>local</location>
      <rules_id>5716</rules_id>
      <timeout>60</timeout>
    </active-response>
    ```
  - Create the file `test.txt` and inside it put an log string that triggers `active response`
    ```
    Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
    ```
  - Check the alert generated
    > example 
    > ```
    > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.log
    > 
    > Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PUBLIC'
    > 2022/09/05 15:16:31 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PUBLIC","status":"inactive"}
    > message: Firewall is disabled
    > ```

  </details>

### Tier 2

- <details><summary>All firewall profiles deactivated</summary>

  - Install wazuh-manager and a windows wazuh-agent
  - Deactivate the all firewall profiles (Domain, Private, Public) 
  - Edit the agent's ossec.conf and restart it
    ```xml
    <localfile>
      <location>C:\Users\vagrant\Documents\test.txt</location>
      <log_format>syslog</log_format>
    </localfile>  
    ```  
  - Edit the manager's ossec.conf and restart it
    ```xml
    <active-response>
      <command>netsh</command>
      <location>local</location>
      <rules_id>5716</rules_id>
      <timeout>60</timeout>
    </active-response>
    ```
  - Create the file `test.txt` and inside it put an log string that triggers `active response`
    ```
    Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
    ```
  - Check the alert generated
    > example 
    > ```
    > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.log
    > 
    > Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_DOMAIN'
    > 2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_DOMAIN","status":"inactive"}
    > message: Firewall is disabled
    > Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PRIVATE'
    > 2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PRIVATE","status":"inactive"}
    > message: Firewall is disabled
    > Rule: 658 (level 5) -> 'Active response: Firewall is disabled , status: inactive, profile: FIREWALL_PUBLIC'
    > 2022/09/05 15:17:57 active-response/bin/netsh.exe: {"message":"Firewall is disabled","profile":"FIREWALL_PUBLIC","status":"inactive"}
    > message: Firewall is disabled
    > ```
  </details>

</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues</summary>

The necessary test type here is integration 
</details>
