### ISSUE TITLE
QA Planning: Replace FIM DB implementation with dbsync and rsync

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3242]
## Description

[Replace FIM DB implementation with dbsync and rsync](https://github.com/wazuh/wazuh/issues/9103) started in the past, but the Core team is still working on it. We need to identify if any new test case is needed to add, or to advance with the implementations made.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

**Comment by Deblintrake09** [comment]
# Research conclusion

During research for this changes, it has been considered that most changes and behaviour are already covered by the current fim test suite. The needed changes to the tests are being tracked and done in the following issues:

- #1915 (In progress)
- #3036 (In progress)
- #3053  (New development - In progress)

No further cases need to be proposed or generated so this Issue can be closed.
