### ISSUE TITLE
Tests development - Improve location message colons parsing

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3246]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4          |   [#13708](https://github.com/wazuh/wazuh/issues/13708) [#10489](https://github.com/wazuh/wazuh/issues/10489) |  [#14706](https://github.com/wazuh/wazuh/pull/14706 )  |

## Description

This change affects the module `logcollector`, before this fix, the wazuh-manager is not correctly parsing the data that comes from files with a `:` on its name. More specifically the issue is that the "location" comes only with the _path_ and the part of the filename that comes after the `:`, the rest of the filename is attached in the `full_log` section.\
Same behavior applies with Wazuh Syslog (remoted) via IPv6. 
> The event data before this change:
> ```JSON
> {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"filename-with:{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/colons.log"}
> ```

> The expected event data after this change:
> ```JSON
> {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/filename-with:colons.log"}
> ```

## Proposed checks

> Note: 
> The logcollector's test cases must be reproduced on Windows & Linux
> Also, a segmentation fault was detected on https://github.com/wazuh/wazuh/issues/14923. It would be good to validate that this does not happen.

- [ ] Logcollector filenames as location are correctly parsed

- <details><summary>Test cases - Tier 1</summary>
  
  - <details><summary>Logfile with no special characters</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78-9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78-9.log"}
      > ```
      </details>
  
  - <details><summary>Logfile with a ":"</summary> 
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78:9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78:9.log"}
          > ```
      </details>
  
  - <details><summary>Logfile with "|"</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78|9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78|9.log"}
          > ```
      </details> 

  - <details><summary>Logfile with "\"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
        ```
        ...
        <!-- Log analysis -->
        <localfile>
            <location>{SOME_PATH}/*.log</location>
            <log_format>syslog</log_format>
        </localfile>
        ...
        ```
    3. Create a file `123-456-78\9.log` in the path indicated previously in the config.
    4. Inside the recently created file put the following line:
        ```
        Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
        ```
    5. Check in the wazuh-manager the event is created and the location is correct
        > expected:
        > ```JSON
        > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78\9.log"}
        > ```
    </details>  

 
  </details>

- <details><summary>Test cases - Tier 2</summary>
 
  - <details><summary>Logfile with ":" captured by matching</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/123-*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78:9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78:9.log"}
      > ```
      </details>
 
  - <details><summary>Logfile captured by matching with ":" in the location tag </summary> 
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/123:*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123:456-78-9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123:456-78-9.log"}
          > ```
      </details>
 
  - <details><summary>Logfile with two ":"</summary> 
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456:78:9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456:78:9.log"}
          > ```
      </details>
  
  - <details><summary>Logfile starts with ":"</summary> 
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `:123-456-78-9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/:123-456-78-9.log"}
          > ```
  
      </details>
  
  
  
  - <details><summary>Logfile with multiple "."</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456.78.9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456.78.9.log"}
          > ```
      </details>
  
  
  - <details><summary>Logfile with "&"</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78&9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78&9.log"}
          > ```
      </details>
  
  - <details><summary>Logfile with "<"</summary>
  
      1. Install wazuh-manager and wazuh-agent
      2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
          ```
          ...
          <!-- Log analysis -->
          <localfile>
              <location>{SOME_PATH}/*.log</location>
              <log_format>syslog</log_format>
          </localfile>
          ...
          ```
      3. Create a file `123-456-78<9.log` in the path indicated previously in the config.
      4. Inside the recently created file put the following line:
          ```
          Feb 14 12:19:04 localhost sshd[25474]: Accepted password for testie from 192.168.1.133 port 49765 ssh2
          ```
      5. Check in the wazuh-manager the event is created and the location is correct
          > expected:
          > ```JSON
          > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"{SOME_PATH}/123-456-78<9.log"}
          > ```
      </details>

  </details>

- [ ] RSyslog IP location is correctly parsed
 - <details><summary>IPv6 syslog location correctly handled</summary>

    - Install wazuh manager 
    - Edit the config file `/var/ossec/etc/ossec.conf`:
    ```
    ...
    <global>
        ...
        <logall_json>yes</logall_json>
    </global>
    ...
    <remote>
        <connection>syslog</connection>
        <port>5050</port>
        <protocol>tcp</protocol>
        <ipv6>yes</ipv6>
        <allowed-ips>any</allowed-ips>
    </remote>
    ...
    ```
    - Send a syslog message using loopback Interface: `echo "IPv6 test msg" | nc -v -w 1 -6 "::1"  5050`
    - Check the location (IPv6) of the event generated.
        ```JSON
        {
            "timestamp": "2022-06-03T16:50:16.660+0000",
            "agent": {
                "id": "000",
                "name": "200-u20-dev-manager"
            },
            "manager": {
                "name": "200-u20-dev-manager"
            },
            "id": "1654275016.1163645",
            "full_log": "0000:0000:0000:0000:0000:0000:0001:IPv6 test msg",
            "decoder": {},
            "location": "0000"
        }
        ```
   </details>

- <details><summary>IPv4 syslog location correctly handled</summary>

    - Install wazuh manager
    - Edit the config file `/var/ossec/etc/ossec.conf`:
    ```
    ...
    <global>
        ...
        <logall_json>yes</logall_json>
    </global>
    ...
    <remote>
        <connection>syslog</connection>
        <port>5050</port>
        <protocol>tcp</protocol>
        <ipv6>no</ipv6>
        <allowed-ips>any</allowed-ips>
    </remote>
    ...
    ```
    - Send a syslog message using loopback Interface: `echo "IPv4 test msg" | nc -v -w 1 localhost 5050`
    - Check the event is created and has the location (IPv4) correctly.
        ```JSON
        {
            "timestamp": "2022-06-03T16:50:16.660+0000",
            "agent": {
                "id": "000",
                "name": "200-u20-dev-manager"
            },
            "manager": {
                "name": "200-u20-dev-manager"
            },
            "id": "1654275016.1163645",
            "full_log": "IPv4 test msg",
            "decoder": {},
            "location": "127.0.0.1"
        }
        ```
    </details>

- [ ] Logcollector commands as location are correctly parsed
  <details><summary>Test cases - Tier 2</summary> 

  - <details><summary>Command without special characters</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>command</log_format>
        <command>echo "test :"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test :"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test :\""}
      > ```
    </details>

  - <details><summary>Command with no ":"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>command</log_format>
        <command>echo "test"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test\""}
      > ```
    </details>

  - <details><summary>Command with "|"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test |"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test |"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test |\""}
      > ```
    </details>

  - <details><summary>Command with "\"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test \"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test \"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test \\\""}
      > ```
    </details>

  - <details><summary>Command with "/"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test /"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test /"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test /\""}
      > ```
    </details>

  - <details><summary>Command with "&"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test &"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test &"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test &\""}
      > ```
    </details>

  - <details><summary>Command with "$"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test $"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test $"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test $\""}
      > ```
    </details>

  - <details><summary>Command with "<"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test <"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test <"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test <\""}
      > ```
    </details>

  - <details><summary>Command with ">"</summary>

    1. Install wazuh-manager and wazuh-agent
    2. Edit the wazuh-agent config file `/var/ossec/etc/ossec.conf`:
      ```
      ...
      <localfile>
        <log_format>full_command</log_format>
        <command>echo "test >"</command>
      </localfile>
      ...
      ```
    3. Run the command `echo "test >"`
    4. Check in the wazuh-manager the event is created and the location is correct
      > expected:
      > ```JSON
      > {"timestamp":"2021-10-12T21:42:13.283+0000","agent":{"id":"001","name":"agent-one","ip":"192.178.56.15"},"manager":{"name":"wazuh-manager"},"id":"1634074933.555919","full_log":"{JSON RECORD}","decoder":{},"location":"echo \"test >\""}
      > ```
    </details>
  </details>

# Development stage
- [x] In research
- [x] In development
    - [x] Linux
    - [ ] Windows _(Only for logcollector)_
- [ ] In testing phase
    - [ ] Linux
    - [ ] Windows _(Only for logcollector)_
- [ ] In Review

**Comment by JorgeMarinoDev** [comment]
Started Research.
Checking wazuh-qa repo to find suitable locations for new tests.

**Comment by JorgeMarinoDev** [comment]
Status Update 29/11
* Setting up local dev  environment on Vagrant Ubuntu 22 VM.
  * Issues:
    * Failed building wazuh-qa/deps . Problem with pip-dev-req. Could not fix. Switching to Centos9 as [here](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/README.md)

**Comment by JorgeMarinoDev** [comment]
Status Update 30/11
* Setting up local dev  environment on Centos9 VM.
  * WIP

**Comment by cborla** [comment]
Let's put this issue on-hold until we complete 4.7.1 tasks.

**Comment by nmkoremblum** [comment]
We put this issue on hold in favor of https://github.com/wazuh/wazuh/issues/21345 which has a higher priority

**Comment by cborla** [comment]
We move it to on hold until by footprint release assignments.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
