### ISSUE TITLE
QA testing - Clusterd in worker nodes waiting asynchronously for wazuh-db data

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#3258]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4.0|https://github.com/wazuh/wazuh/issues/14765|https://github.com/wazuh/wazuh/pull/14843|

## Description
In a cluster, the agent database of the master node (`global.db`) must always contain the updated information of all the agents, even those that are reporting to a different node. 

There is a task in the clusterd process that is responsible for sending the most up-to-date information from the workers' global.db to the master. This task is known as [Agent-info sync](https://documentation.wazuh.com/current/development/wazuh-cluster.html#agent-info-thread), it is always started on the worker side and its workflow is as follows:
1. The worker asks for permission to start the `Agent-info sync` task.
2. When permission is granted, task is started (`[Agent-info sync] Starting.` log is printed in the worker).
3. Worker requests its local `wazuh-db` service for all updated information from `global.db`.
4. Worker sends to master the data in chunks.
5. Master updates its local `global.db` with the data received from worker.
6. This task is repeated every 10 seconds.

However, there was a problem. In step `3.`, the entire `clusterd` process of the worker was waiting for a response from `wazuh-db`. This usually takes a short time, but when wdb is very busy, it can keep the worker locked for several seconds. While the worker is stuck on the socket waiting for a response, it cannot do any other tasks, including syncing files or answering distributed API calls (for example, if the master asks the worker what its `ossec.conf` file is). It can be seen in better detail in the description of this PR: https://github.com/wazuh/wazuh/pull/14843.

To solve this, an asynchronous socket has been implemented which lets the worker do other tasks until the response is ready. This is also described in https://github.com/wazuh/wazuh/pull/14843.

## Proposed checks

- [x] Verify that multiple tasks take place while waiting for WDB response. For it, check `cluster.log` and make sure that multiple tasks take place in the worker between these two logs when delaying wdb response for 30 seconds:
     ```
      ... INFO: [Worker worker1] [Agent-info sync] Starting.
      ... DEBUG [Worker worker1] [Agent-info sync] Obtained N chunks of data in Xs.
     ```

- [x] Make sure that distributed API requests are answered on time while waiting for wdb response in worker. For it, after this log is printed:
     ```
      ... INFO: [Worker worker1] [Agent-info sync] Starting.
     ```
     And before this
     ```
      ... DEBUG [Worker worker1] [Agent-info sync] Obtained N chunks of data in Xs.
     ```
     Make a distributed API request to the worker (running this in the master's API, for example: `GET /cluster/api/config?wait_for_complete=true&nodes_list=worker1`) and verify that the response is obtained on time even if the worker is waiting for a wdb response.

## Steps to reproduce
Wazuh must be deployed using this branch that comes from `4.3`: `feature/14765-async-wdb-cluster`

A cluster environment is needed with:
```
- 1 Master node.
- 1 Worker node
- Some agents reporting to worker node.
```

Follow this steps:
1. Inside the worker node, stop the `wazuh-clusterd` process.
2. You will need to make wazuh-db responses very slow. To do this, you can run the script I've added in the `Configuration and considerations` section.
3. Edit this file: `/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.8-py3.9.egg/wazuh/core/wdb.py`
4. Change [this line](https://github.com/wazuh/wazuh/blob/41231f7658a9ff989d3defb8acccc77f967de247/framework/wazuh/core/wdb.py#L34) inside the `AsyncWazuhDBConnection` class of the file mentioned in `step 3` so it looks like this:
   ```
          self.socket_path = '/tmp/wdb'
   ```
6. Start `wazuh-clusterd` process in the worker in debug=1 mode.
7. Run `tail -f /var/ossec/logs/cluster.log` and review the logs.

## Expected results

The worker should be able to perform other tasks and respond to API requests while waiting for a response from WDB. If these tests are performed on Wazuh v4.3.7, the API requests would be delayed as long as the response from WDB and all other tasks will be also blocked until then.

## Configuration and considerations
You can use this script to make a proxy of `wdb`. It will create a new socket to which `wazuh-clusterd` will connect, obtain data from original wdb and send it back to the cluster but adding a delay in the response.
- [wdb_proxy.zip](https://github.com/wazuh/wazuh-qa/files/9494805/wdb_proxy.zip)

Send/create the script inside the worker node and add execution permissions. Then, you can run it this way:
```
# /scratches/wdb_proxy.py -t 10
2022-09-06 08:17:32,592 - Socket created at "/tmp/wdb".
2022-09-06 08:17:37,597 - Client connected.
2022-09-06 08:17:47,604 - Received message: bytearray(b'global sync-agent-info-get ') (27 Bytes)
2022-09-06 08:17:47,605 - Delaying response 10 seconds.
2022-09-06 08:17:57,612 - Response sent (10.01 s).
```

Use `/scratches/wdb_proxy.py -h` to get more information.

**Comment by roronoasins** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @roronoasins   |  [aa5c8e7](https://github.com/wazuh/wazuh/pull/14843/commits/aa5c8e72b06e2136c8cf68f14799a938f434d296)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Amazon Linux  | 2 | `AWS` | `ami-003530de8839921c4`| Deployed and provisioned with internal pipeline |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [4.4.0 - deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/)  | [4.4.0 - deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/)  | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved
- [ ] Development team leader approved

### Conclusion :large_blue_circle:

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
