### ISSUE TITLE
E2E Tests - Fix unstable tests

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3287]
## Description
After [testing and local debugging](https://github.com/wazuh/wazuh-qa/issues/3166), we found that some E2E tests were unstable. [So the tests were skipped](https://github.com/wazuh/wazuh-qa/issues/3275) after a [research](https://github.com/wazuh/wazuh-qa/issues/3274).

And those tests are:

- `test_aws_infrastructure_monitoring`
- `test_docker_monitoring`
- `test_fim_linux`
- `test_fim_windows`
- `test_slack_integration`

So, this issue aims to fix those tests to achieve a full green in the E2E test suite.

### Tasks

- [ ] #3207
- [ ] #3210
- [ ] #3211
- [ ] #3286

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
