### ISSUE TITLE
Tests development - Update netsh Active response for Windows

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3296]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.5         | [ #14504](https://github.com/wazuh/wazuh/issues/14504) | [#14804](https://github.com/wazuh/wazuh/pull/14804) |

## Description

This PR solves the issue https://github.com/wazuh/wazuh/issues/14504, the proposed solution was to generate an alert when the firewall is disabled, it is verified if the firewall is down and if so, it is written in the active response log in order to be able to generate the alert. A rule (658) for active response is also added.

## Proposed test cases

  > The tests should be executed at least in one Windows version above Windows Server 2012 and one version previous to it 

- [x] Tier 1

  <details><summary>Active response IP drop works properly</summary>

  - <details><summary>Active response blocks ip with firewall enabled</summary>

    - Install wazuh-manager and a windows wazuh-agent
    - Ensure all the windows firewall profiles are activated
    - Edit the manager's ossec.conf and restart it
      ```xml
      <active-response>
        <command>netsh</command>
        <location>local</location>
        <rules_id>5716</rules_id>
        <timeout>60</timeout>
      </active-response>
      ```
    - From another machine (any OS) ping the windows agent to check there is connectivity between them:
      ```
      ping <windowsAgentIP>
      ```
      > Expected:
      > ```
      > PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
      > 64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.602 ms
      > 64 bytes from 10.0.0.5: icmp_seq=2 ttl=64 time=0.774 ms
      > ```
    - From this third machine try to connect multiple times to the windows agent with invalid credentials
      ```
      ssh test@<windowsAgentIP>
      ```
    - Check the third machine's IP is blocked
      ```
      ping <windowsAgentIP>
      ```
      > Expected:
      > ```
      > PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
      > ^C
      > --- 10.0.0.5 ping statistics ---
      > 12 packets transmitted, 0 received, 100% packet loss, time 11000ms
      > ```
    - Check after 60 seconds the ip is not blocked anymore
      ```
      ping <windowsAgentIP>
      ```
      > Expected:
      > ```
      > PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
      > 64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.602 ms
      > 64 bytes from 10.0.0.5: icmp_seq=2 ttl=64 time=0.774 ms
      > ```
    </details>

  - <details><summary>Active response doesn't blocks ip with firewall disabled</summary>

    - Install wazuh-manager and a windows wazuh-agent
    - Deactivate the all firewall profiles (Domain, Private, Public) 
    - Edit the manager's ossec.conf and restart it
      ```xml
      <active-response>
        <command>netsh</command>
        <location>local</location>
        <rules_id>5716</rules_id>
        <timeout>60</timeout>
      </active-response>
      ```
    - From another machine (any OS) ping the windows agent to check there is connectivity between them:
      ```
      ping <windowsAgentIP>
      ```
      > Expected:
      > ```
      > PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
      > 64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.602 ms
      > 64 bytes from 10.0.0.5: icmp_seq=2 ttl=64 time=0.774 ms
      > ```
    - From this third machine try to connect multiple times to the windows agent with invalid credentials
      ```
      ssh test@<windowsAgentIP>
      ```
    - Check the third machine's IP is not blocked
      ```
      ping <windowsAgentIP>
      ```
      > Expected:
      > ```
      > PING 10.0.0.5 (10.0.0.5) 56(84) bytes of data.
      > 64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.602 ms
      > 64 bytes from 10.0.0.5: icmp_seq=2 ttl=64 time=0.774 ms
      > ```
    </details>

  </details>

- [x] Tier 2
  <details><summary>Alert is raised when firewal is deactivated</summary>

  - <details><summary>All firewall profiles activated</summary>

    - Install wazuh-manager and a windows wazuh-agent
    - Ensure all the windows firewall profiles are activated
    - Edit the agent's ossec.conf and restart it
      ```xml
      <localfile>
        <location>C:\Users\vagrant\Documents\test.txt</location>
        <log_format>syslog</log_format>
      </localfile>  
      ```  
    - Edit the manager's ossec.conf and restart it
      ```xml
      <active-response>
        <command>netsh</command>
        <location>local</location>
        <rules_id>5716</rules_id>
        <timeout>60</timeout>
      </active-response>
      ```
    - Create the file `test.txt` and inside it put an log string that triggers `active response`
      ```
      Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
      ```
    - Check the `Firewall is disabled` alert is not generated
      > example 
      > ```JSON
      > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.log
      > 
      > ```
    </details>

  - <details><summary>Firewall public profile deactivated</summary>

    - Install wazuh-manager and a windows wazuh-agent
    - Deactivate the firewall's public profile 
    - Edit the agent's ossec.conf and restart it
      ```xml
      <localfile>
        <location>C:\Users\vagrant\Documents\test.txt</location>
        <log_format>syslog</log_format>
      </localfile>  
      ```  
    - Edit the manager's ossec.conf and restart it
      ```xml
      <active-response>
        <command>netsh</command>
        <location>local</location>
        <rules_id>5716</rules_id>
        <timeout>60</timeout>
      </active-response>
      ```
    - Create the file `test.txt` and inside it put an log string that triggers `active response`
      ```
      Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
      ```
    - Check the `Firewall is disabled` alert is generated
      > example 
      > ```JSON
      > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.json
      >
      >{
      >  "timestamp": "2022-12-13T13:56:56.107+0000",
      >  "rule": {
      >    "level": 5,
      >    "description": "Active response related to netsh has been activated, but may not have an effect because the firewall is inactive",
      >    "id": "658",
      >    "firedtimes": 1,
      >    "mail": false,
      >    "groups": ["ossec", "active_response"],
      >    "pci_dss": ["11.4"],
      >    "gdpr": ["IV_35.7.d"],
      >    "nist_800_53": ["SI.4"],
      >    "tsc": ["CC6.1", "CC6.8", "CC7.2", "CC7.3", "CC7.4"]
      >  },
      >  "agent": {
      >    "id": "001",
      >    "name": "windows2022",
      >    "ip": "FE80:0000:0000:0000:D9AD:2A10:B7F1:D00A"
      >  },
      >  "manager": { "name": "manager" },
      >  "id": "1670939816.2056326",
      >  "full_log": "2022/12/13 13:56:56 active-response/bin/netsh.exe: {\"message\":\"Active response may not have an effect\",\"firewall\":{\"profile1\":\"FIREWALL_DOMAIN\",\"status1\":\"active\",\"profile2\":\"FIREWALL_PRIVATE\",\"status2\":\"active\",\"profile3\":\"FIREWALL_PUBLIC\",\"status3\":\"inactive\" },\"status\":\"inactive\",\"script\":\"netsh\"}",
      >  "decoder": { "parent": "ar_log_json", "name": "ar_log_json" },
      >  "data": {
      >    "status": "inactive",
      >    "message": "Active response may not have an effect",
      >    "firewall": {
      >      "profile1": "FIREWALL_DOMAIN",
      >      "status1": "active",
      >      "profile2": "FIREWALL_PRIVATE",
      >      "status2": "active",
      >      "profile3": "FIREWALL_PUBLIC",
      >      "status3": "inactive"
      >    },
      >    "script": "netsh"
      >  },
      >  "location": "active-response\\active-responses.log"
      >}
      > ```

    </details>

  - <details><summary>All firewall profiles deactivated</summary>

    - Install wazuh-manager and a windows wazuh-agent
    - Deactivate the all firewall profiles (Domain, Private, Public) 
    - Edit the agent's ossec.conf and restart it
      ```xml
      <localfile>
        <location>C:\Users\vagrant\Documents\test.txt</location>
        <log_format>syslog</log_format>
      </localfile>  
      ```  
    - Edit the manager's ossec.conf and restart it
      ```xml
      <active-response>
        <command>netsh</command>
        <location>local</location>
        <rules_id>5716</rules_id>
        <timeout>60</timeout>
      </active-response>
      ```
    - Create the file `test.txt` and inside it put an log string that triggers `active response`
      ```
      Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.15 port 1066 ssh2
      ```
    - Check the `Firewall is disabled` alerts are generated
      > example 
      > ```JSON
      > grep "Firewall is disabled" /var/ossec/logs/alerts/alerts.json
      > 
      >{
      >  "timestamp": "2022-12-13T13:56:56.107+0000",
      >  "rule": {
      >    "level": 5,
      >    "description": "Active response related to netsh has been activated, but may not have an effect because the firewall is inactive",
      >    "id": "658",
      >    "firedtimes": 1,
      >    "mail": false,
      >    "groups": ["ossec", "active_response"],
      >    "pci_dss": ["11.4"],
      >    "gdpr": ["IV_35.7.d"],
      >    "nist_800_53": ["SI.4"],
      >    "tsc": ["CC6.1", "CC6.8", "CC7.2", "CC7.3", "CC7.4"]
      >  },
      >  "agent": {
      >    "id": "001",
      >    "name": "windows2022",
      >    "ip": "FE80:0000:0000:0000:D9AD:2A10:B7F1:D00A"
      >  },
      >  "manager": { "name": "manager" },
      >  "id": "1670939816.2056326",
      >  "full_log": "2022/12/13 13:56:56 active-response/bin/netsh.exe: {\"message\":\"Active response may not have an effect\",\"firewall\":{\"profile1\":\"FIREWALL_DOMAIN\",\"status1\":\"active\",\"profile2\":\"FIREWALL_PRIVATE\",\"status2\":\"active\",\"profile3\":\"FIREWALL_PUBLIC\",\"status3\":\"inactive\" },\"status\":\"inactive\",\"script\":\"netsh\"}",
      >  "decoder": { "parent": "ar_log_json", "name": "ar_log_json" },
      >  "data": {
      >    "status": "inactive",
      >    "message": "Active response may not have an effect",
      >    "firewall": {
      >      "profile1": "FIREWALL_DOMAIN",
      >      "status1": "inactive",
      >      "profile2": "FIREWALL_PRIVATE",
      >      "status2": "inactive",
      >      "profile3": "FIREWALL_PUBLIC",
      >      "status3": "inactive"
      >    },
      >    "script": "netsh"
      >  },
      >  "location": "active-response\\active-responses.log"
      >}
      > ```
    </details>

  </details>

**Comment by fedepacher** [comment]
# Update 29/11/2022

- At this point, It has created a test (tier 1), that checks in the `active-responses.log` file the following content when the firewall profiles are disabled:

   ```
   2022/12/29 14:08:34 active-response/bin/netsh.exe: {"message":"Active response may not have an effect","firewall": {"profile1":"FIREWALL_DOMAIN","status1":"inactive","profile2":"FIREWALL_PRIVATE","status2":"inactive","profile3":"FIREWALL_PUBLIC","status3":"inactive" },"status":"inactive","script":"netsh"}
   ```
- For the tier 2 test, it is creating a test that gets the alerts when the firewall is disabled but It could not reach it as it is mentioned in the issue description yet. For some unknown reason, the alerts are not raised.

**Comment by fedepacher** [comment]
# Update 2022/12/30

After analyzing the ansible commands, the following sentence inserts a  log into a `test.txt` file but the alerts are not generated:

```
myfile: 'C:\temp\test.txt'
log: "Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.11 port 1066 ssh2`n"

win_shell: Add-Content '{{ myfile }}' "{{ log }}"
```

In the `archives.log` file it shows the log arriving but no alerts were generated. The same procedure makes it manually works perfectly.

**Comment by fedepacher** [comment]
# Update 2023/01/03

It has detected that the following ansible sentence creates the specified file in the folder but after creating the file Wazuh is not able to detect the log inserted into it. As the log is not detected the alerts do not rise.

```
   - name: Create test.txt file
     win_file:
       path: C:\temp\test.txt
       state: touch
```

Removing this sentence the test works correctly but the file test.txt has to be created before launching the test.

**Comment by fedepacher** [comment]
# Update 2023/01/18

After analyzing log insertion into a `test.txt` file I have achieved that the best way to run an ansible playbook that do this task is the following:

```
- name: Generate events
  hosts: windows-agent
  vars:
    myfile: 'C:\temp\test.txt'
    log: "Dec 10 01:02:02 host sshd[1234]: Failed none for root from 192.168.56.11 port 1066 ssh2"
  tasks:

....

    - name: Insert log into test.txt file
      win_shell:  |
        "{{ log }}" | Out-File "{{ myfile }}" -Append -Encoding ASCII
```
