### ISSUE TITLE
The integration test `test_integratord_read_json_file_deleted` is failing

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3298]
## Description

In the nightly for  `4.3` version and  `20220915` revision, Integratord module fails.

</details>

### Current behavior
It seems that `test_integratord_read_json_file_deleted` test fails consistently for `4.3` version (not tested in higher versions)

<details>

<summary> Integratord pytest error output </summary>

```
---------------------------- Captured stdout setup -----------------------------
Restarting wazuh-manager (via systemctl):  [  OK  ]
---------------------------- Captured stderr setup -----------------------------
2022-09-15 00:46:54,768 - wazuh_testing - DEBUG - Set local_internal_option to {'integrator.debug': '2'}
------------------------------ Captured log setup ------------------------------
DEBUG    wazuh_testing:conftest.py:882 Set local_internal_option to {'integrator.debug': '2'}
----------------------------- Captured stderr call -----------------------------
2022-09-15 00:47:19,427 - wazuh_testing - ERROR - Did not recieve the expected "...Could not retrieve information/open file"
2022-09-15 00:47:19,428 - wazuh_testing - ERROR - Results accumulated: 0
2022-09-15 00:47:19,428 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:458 Did not recieve the expected "...Could not retrieve information/open file"
ERROR    wazuh_testing:monitoring.py:459 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:461 Results expected: 1
- generated html file: file:///tmp/Test_integration_B31860_20220915013518/report.html -
=========================== short test summary info ============================
FAILED test_integratord/test_integratord_read_json_file_deleted.py::test_integratord_read_json_file_deleted[Cannot read alerts - Json File Deleted]
=================== 1 failed, 4 passed in 109.55s (0:01:49) ====================
```

**Comment by mauromalara** [comment]
## Update 21/09/2022

### Local executions

| OS | R1 | R2 | R3
|-- | -- |-- |--
| Ubuntu | [🔴](https://github.com/wazuh/wazuh-qa/files/9617313/R1-manager-ubuntu.html.zip) | [🔴](https://github.com/wazuh/wazuh-qa/files/9617314/R2-manager-ubuntu.html.zip) | [🔴](https://github.com/wazuh/wazuh-qa/files/9617315/R3-manager-ubuntu.html.zip)

**Comment by fedepacher** [comment]
# Update 2022/10/21

After analyzing [PR 3362](https://github.com/wazuh/wazuh-qa/pull/3362#issuecomment-1260327420), and launched on the Jenkins platform and a local environment the following results have been achieved:

### Local environment

| OS | R1 | R2 | R3
|-- | -- |-- |--
| Ubuntu | [🟢](https://github.com/wazuh/wazuh-qa/files/9840143/report_1.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9840153/report_2.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9840160/report_3.zip)

### Jenkins environment

| OS | R1 | R2 | R3
|-- | -- |-- |--
| Ubuntu | [🟢](https://github.com/wazuh/wazuh-qa/files/9840193/manager_html_report_Test_integration_B33080_20221021145522.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9840211/manager_html_report_Test_integration_B33081_20221021150411.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9840213/manager_html_report_Test_integration_B33082_20221021150435.zip)

**Comment by fedepacher** [comment]
# Update 2022/10/21

After analyzing [PR 3362](https://github.com/wazuh/wazuh-qa/pull/3362#issuecomment-1260327420), and launched on the Jenkins platform and a local environment the following results have been achieved:

### Local environment

| OS | R1 | R2 | R3
|-- | -- |-- |--
| Ubuntu | [🟢](https://github.com/wazuh/wazuh-qa/files/9841380/1-3362-test-integratord-read-json-file-delete.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9841383/2-3362-test-integratord-read-json-file-delete.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9841386/3-3362-test-integratord-read-json-file-delete.zip)


### Jenkins environment

| OS | R1 | R2 | R3
|-- | -- |-- |--
| Ubuntu | [🟢](https://github.com/wazuh/wazuh-qa/files/9841388/manager_html_report_Test_integration_B33083_20221021184924.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9841499/manager_html_report_Test_integration_B33084_20221021190212.zip) | [🟢](https://github.com/wazuh/wazuh-qa/files/9841502/manager_html_report_Test_integration_B33085_20221021190216.zip)

**Comment by mauromalara** [comment]
## Update 02/03/23

- Debugging
- Multiple changes applied
- Tests refactored

**Comment by mauromalara** [comment]
## Update 02/06/23

- Called a teammate who was involved with Integratord
- I applied several changes to the code

**Comment by mauromalara** [comment]
These tests were merged successfully. But they cannot be launched in Jenkins.

Remaining task: https://github.com/wazuh/wazuh-jenkins/issues/3838#issuecomment-1594543456
