### ISSUE TITLE
QA Planning: A race condition in Remoted is blocking agent connections

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3304]
# Description

This problem aims to investigate https://github.com/wazuh/wazuh/issues/12776 to define the test cases to be carried out.

## Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
<details><summary>Research the applied change</summary>

</details>

<details><summary>Research if we have a test for this case</summary>

</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2</summary>  

  - <details><summary>Configurations</summary>

    </details>


  - <details><summary>test case 1</summary>


    </details>

</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues</summary>

</details>
