### ISSUE TITLE
Implement auto-defragmentation functionality in wazuh-db

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3305]
# Description

This problem aims to investigate https://github.com/wazuh/wazuh/issues/14968 to define the test cases to be carried out.

## Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
<details><summary>Research the applied change</summary>

This issue [#14968](https://github.com/wazuh/wazuh/issues/14968) is the second part of the development of [#12930](https://github.com/wazuh/wazuh/issues/12930), it implements the `auto-defragmentation` functionality in `wazuh-db` affecting both the global db and the agent's db. 

</details>

<details><summary>Research if we have a test for this case</summary>

As it is a new functionality, we dont have any tests for this case

</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2</summary>  

  


  - <details><summary>test case 1</summary>


    </details>

</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues</summary>

To test the most "natural" cases were we validate that the agent runs the auto-defragmentation, check the logs and db, we can develop integration tests. Also we can add some stress testing, running several agents executing auto-defragmentation 
</details>
