### ISSUE TITLE
QA testing - Add unit tests to json_op.c

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3311]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5|https://github.com/wazuh/wazuh/pull/14758|https://github.com/wazuh/wazuh/pull/14784|

## Description
It's desirable to validate new json_op.c unit tests.

Developed test
- src/unit_tests/shared/test_json_op.c

Improved unit test misc (mocks and stuff)
- src/unit_tests/wrappers/wazuh/shared/file_op_wrappers.c/h
- src/unit_tests/wrappers/wazuh/shared/json_op_wrappers.c/h

Target file
- src/shared/json_op.c

THIS TEST DOES NOT CHANGE ANY FUNCIONAL ASPECT of Wazuh

## Proposed checks

- [ ] Run unit test for Wazuh server
- [ ] Run unit test for Wazuh agent

Useful reference https://github.com/wazuh/wazuh/tree/master/src/unit_tests#readme

## Steps to reproduce
- Compile proposed targets for TEST
- Compile src/unit_tests unit tests
- Execute those unit tests
- Execute coverage analysis for this tests

## Expected results
- Project was compiled successfully
- Unit test were successfully compiled
- Unit test were successfully executed
- Coverage analysis shows that src/shared/json_op.c file have coverage

**Comment by damarisg** [comment]
We can launch the automated builds and show the reports, but the core team did that, so there's no point in duplicating it.

Closed by [comment](https://github.com/wazuh/wazuh/pull/14784#issuecomment-1253593641).
