### ISSUE TITLE
QA testing - Improve C++ unit test coverage

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3312]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5|https://github.com/wazuh/wazuh/issues/14474|https://github.com/wazuh/wazuh/pull/14476|

## Description
It's desirable to validate the improved unit tests for C++ code

- To increase the UT coverage on src/shared_modules/utils files, I added a new UT for stringHelper.h.
- To increase the UT coverage on src/shared_modules/dbsync files, I added a new UT for sqlite_wrapper.cpp.

## Proposed checks

- [ ] Run unit test for Wazuh server
- [ ] Run unit test for Wazuh agent
- [ ] Run unit test for Wazuh winagent

## Steps to reproduce
- Compile proposed targets for TEST
- Compile C++ unit tests
- Execute those unit tests
- Execute coverage analysis for these tests

## Expected results
- Project was compiled successfully
- Unit tests were successfully compiled
- Unit tests were successfully executed
- Coverage analysis shows that src/shared/json_op.c file have coverage

**Comment by damarisg** [comment]
We can launch the automated builds and show the reports, but the core team did that, so there's no point in duplicating it.

Closed by [comment](https://github.com/wazuh/wazuh/pull/14476#issuecomment-1253593124).
