### ISSUE TITLE
QA Planning: PagerDuty and Slack integrations don't work at the same time

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3316]
## Description

This problem aims to investigate [PagerDuty and Slack integrations don't work at the same time](https://github.com/wazuh/wazuh/issues/4264) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
<details><summary>Research the applied change</summary>

This change fixes the issue where PagerDuty and Slack integration are not working at the same time.
</details>

<details><summary>Research if we have a test for this case</summary>

We dont have test cases for this scenario
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2</summary>  

  - <details><summary>Configurations</summary>
    
    - Manager `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxx</hook_url>
        <alert_format>json</alert_format>
      </integration>


      <integration>
        <name>pagerduty</name>
        <api_key>xxxxxxxxxxxxxxxxxx</api_key> 
      </integration>
      ```
    </details>

  - <details><summary>Slack integration works properly</summary>

    </details>

  - <details><summary>PagerDuty integration works properly</summary>

    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time</summary>

    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in PagerDuty</summary>
    
    `<rule_id>5402</rule_id>`
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in Slack</summary>
    
    `<rule_id>5402</rule_id>`
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in both</summary>
    
    `<rule_id>5402</rule_id>`
    </details>
</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues</summary>

</details>
