### ISSUE TITLE
QA testing - Review new framework, API and wodles code vulnerabilities and dependencies vulnerabilities

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-qa#3319]
| Target version | 
|--------------------|
|        4.5                |   

## Description

After creating the pull request https://github.com/wazuh/wazuh-jenkins/pull/3862 to automate the execution of the [scans tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans), new possible code and deps vulnerabilities were found.

We should review these possible vulnerabilities. 

Use this issue to update the [known_flaws](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans/code_analysis/known_flaws) directory in case the new code vulnerabilities found are considered false positives. We also need to update the known deps vulnerabilities file in case deps vulnerabilities are going to be fixed in the future (to_fix, python for instance) or cannot be solved (known). The deps file does not exist right now, it will be developed in https://github.com/wazuh/wazuh-qa/issues/3325 (this issue is blocked until https://github.com/wazuh/wazuh-qa/issues/3325 is solved)

Consider opening new issues in the `wazuh/wazuh` repository if there are vulnerabilities that need a fix or dependencies that need an update.

[new_flaws_api_master.json.txt](https://github.com/wazuh/wazuh-qa/files/9606193/new_flaws_api_master.json.txt)
[new_flaws_framework_master.json.txt](https://github.com/wazuh/wazuh-qa/files/9606195/new_flaws_framework_master.json.txt)
[new_flaws_wodles_master.json.txt](https://github.com/wazuh/wazuh-qa/files/9606197/new_flaws_wodles_master.json.txt)
[deps_master.json.txt](https://github.com/wazuh/wazuh-qa/files/9606246/deps_master.json.txt)

Also, use this issue to update the following code snippet in `tests/scans/conftest.py` (the options' descriptions are wrong):

```python
def pytest_addoption(parser):
    parser.addoption("--branch", action="store", default=DEFAULT_BRANCH,
                     help=f"Set the repository used. Default: {DEFAULT_REPOSITORY}")
    parser.addoption("--repo", action="store", default=DEFAULT_REPOSITORY,
                     help=f"Set the repository branch. Default: {DEFAULT_BRANCH}")
    parser.addoption("--commit", action="store", default=None,
                     help=f"Set the repository commit. Default: None")
```

## Proposed checks

- [ ] Review code vulnerabilities - `master`
- [ ] Review deps vulnerabilities - `master`
- [ ] Minor change to scans `conftest.py`

## Expected results
The [scans tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans) must be passed without errors in the **master** (4.5) branch.

**Comment by GGP1** [comment]
## Update

- Created two issues to fix vulnerabilities in dependencies:
    - hiredis: https://github.com/wazuh/wazuh/issues/16680
    - SQLAlchemy: https://github.com/wazuh/wazuh/issues/16679
- Opened a [pull request](https://github.com/wazuh/wazuh-qa/pull/4083) with changes to the files containing known vulnerabilities.
