### ISSUE TITLE
Design and implement tests to verify alerts integrity between Wazuh versions

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#332]
## Motivation

The main objective of the issue is to guarantee that the alerts saved in a specific version of Wazuh are compatible with newer ones. This would add a lot of integrity to the upgrade process and would avoid undesired errors related to alerts indexation.

This process aims to verify the alert in ES after it's indexed. This way, we guarantee the whole alert flow from the Agent where it was generated to Elasticsearch where it's indexed.

### Functional

- Deploy a fresh Wazuh Manager installation from sources and packages

- Upgrade a Wazuh Manager installation

- Install and configure Filebeat and Elasticsearch to communicate between them to index the Wazuh Manager alerts

- Inject an `alerts.json` file into a Wazuh Manager

- Monitor the indexing process until finished.

- Run queries to Elasticsearch to verify every alert has been indexed applying different filters like total hits, rule.groups or rule ids.

- Run defined tests to verify if the alerts indexation was successful or not.

### Non Functional

- The Wazuh Environment must be provisioned automatically

- The injection of alerts and it's monitoring must be automatic.

- The tests to verify the integrity of the alerts must be automatic.

- The deployed environment must be accessible from outside

- The Jenkins pipeline could notify on failed test using email

### General diagram

![Alerts](https://user-images.githubusercontent.com/46649922/70714636-d46b1780-1ce8-11ea-8c24-6042cc014cd9.png)

### Software dependencies

The technologies used in the solution is:

- Wazuh Manager
- Elasticsearch
- Filebeat
- Kibana
- Ansible
- Jenkins
- Pytest
- Paramiko
- Testinfra

The whole execution process will be orchestrated by Jenkins. A Pipeline will use Ansible technology to execute required tasks

### Data sample

The data sample (`alerts.json`) will be extracted from a manually deployed environment which will generate the alerts. 

To consider the data representative enough, the sample must contain alerts from:

- A wide diversity of Agents (Ubuntu, CentOS, Fedora, Solaris, Rhel...)
- Every wodle (aws-s3, vulnerability-detector, docker-listener....)
- Wazuh Managers and Agents
- Integrations
- Every rule group

### General flow

1. A user relative to Wazuh will trigger the Jenkins Pipeline using its interface

2. A playbook will deploy the required resources in AWS using `AWS CLI` to deploy a  Cloudformation template.

3. A playbook executes provision tasks that will install and configure Wazuh Manager, Elasticsearch and Filebeat. Also, any other configuration change will be done in this phase.

4. Any previous alert is removed and our sample file `alerts.json` is injected in the Wazuh Manager. The indexation process is monitored by an asynchronous task in Ansible.

5. After finishing, the battery of tests (implemented in Pytest) is launched. It will perform queries to Elasticsearch in order to check if injected alerts were properly indexed among other tests.

#### Deploy AWS Resources

AWS Resources will be defined in a CloudFormation template. The Jenkins node that executes this task must have AWS CLI configured and with privileges to launch CF resources.

The CF template upload and Stack creation will be executed and monitored by an Ansible playbook which will asynchronously check until the Stack creation is complete.

#### Provision and configuration

Wazuh Manager, Elasticsearch and Filebeat will be installed and configured and any other configuration change required by the instance will be performed.

Service's tests will be launched to ensure they are running and there are no connectivity issues between them.

#### Inject alerts and monitor the process

All alerts in the Wazuh Manager will be removed and the `alerts.json` will be loaded into the Wazuh Manager. Trying different approaches for this may be required depending on the `alerts.json` size.

Different ansible tasks will ensure the Manager service is running and properly processing the alerts.

#### Launch tests and retrieve data

Tests will analyze the `alerts.json` file and extract data from it: total number of alerts, number of alerts per group, etc using Python scripts.

Then, queries to ES will be performed to extract the same kind of data from the `wazuh-alerts` index.

In both processes, the data must be formatted following a key-value structure or similar to ease the testing process.

Pytest tests will parse extracted data from `alerts.json` and Elasticsearch.

Results will be stored in one or multiple files and uploaded to S3 using AWS CLI

## Documentation

The whole implementation process will be documented through GitHub issues which will granulate every task of the implementation.

A wiki page must be created to keep track of:

- Tested Managers versions and upgrades
- Detailed info of Agents and configurations involved in the environment that generated the data

## Tests

Some of the guidelines that the tests will follow are:

- Check if the alerts.json was properly handled in the manager.

- Check alerts metrics: total hits, hits per group, hits per ids...

- If alerts are not indexed for some reason, it's a must to delimit the origin of the alert (this will ease a lot the diagnostic process to check which alerts were not indexed)

**Comment by davidjiglesias** [comment]
This will be done in the future via functionality testing.
