### ISSUE TITLE
Enhancement - Refactor system tests of environment `agentless_cluster`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3320]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `agentless_cluster` environment.

### List of tests
- [ ] Refactor system test `test_change_rbac_mode`
- [ ] Refactor system test `test_change_security_resources`
- [ ] Refactor system test `test_disconnected_nodes`
- [ ] Refactor system test `test_revoke_endpoint`
- [ ] Refactor system test `test_update_password`
- [ ] Refactor system test `test_integrity_sync`

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
