### ISSUE TITLE
Enhancement - Refactor system tests of environment `basic_cluster`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3321]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `basic_cluster` environment.

### List of tests
- [ ] Refactor system test `test_agent_groups`
- [ ] Refactor system test `test_agent_files_deletion`
- [ ] Refactor system test `test_agent_info_sync`
- [ ] Refactor system test `test_agent_key_polling`
- [ ] Refactor system test `test_multigroups`
- [ ] Refactor system test `test_agent_groups_forced_change`

**Comment by davidjiglesias** [comment]
As part of all the changes for 5.0.0 these tests are deprecated.
