### ISSUE TITLE
Enhancement - Refactor system tests of environment `enrollment_cluster`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3322]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `agentless_cluster` environment.

### List of tests
- [ ] Refactor system test `test_agent_enrollment`
- [ ] Refactor system test `test_agent_default_group_added`
- [ ] Refactor system test `test_assign_agent_group_with_enrollment`
- [ ] Refactor system test `test_assign_agent_never_connected_to_group`
- [ ] Refactor system test `test_assign_agent_to_a_group_api`
- [ ] Refactor system test `test_assign_agent_to_a_group_by_tool`
- [ ] Refactor system test `test_assign_groups_guess`

**Comment by davidjiglesias** [comment]
As part of all the changes for 5.0.0 these tests are deprecated.
