### ISSUE TITLE
Enhancement - Refactor system tests of environment  `manager_agent`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3324]
## Description

As specified in https://github.com/wazuh/qa-system-framework/issues/34, it is required to refactor all system tests that belong to the `one_manager_agent` environment.

### List of tests
- [ ] Refactor system test `test_active_response_log_format`

**Comment by davidjiglesias** [comment]
As part of all the changes for 5.0.0 these tests are deprecated.
