### ISSUE TITLE
Add AWS Inspector integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#3345]
As part of https://github.com/wazuh/wazuh-qa/issues/3333 we need to Implement the integration test cases related to `AWS Inspector` defined in https://github.com/wazuh/wazuh-qa/issues/3334.

# Test cases list

## Tier 0

- <details><summary>Inspector integration works properly using the default configuration</summary>

    ### Pre-conditions

    * There are already configured credentials for the `qa` profile
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Use a configured inspector service</td>
    <td>The module is invoked with the expected parameters and no error occurs</td>
    <td>

    <details><summary>ossec.conf</summary>

    ```XML
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <service type="inspector">
            <aws_profile>qa</aws_profile>
        </service>
    </wodle>
    ```

    </details>

    </td>
    </tr>
    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check no error messages are present in the `ossec.log`

</details>

- <details><summary>Inspector integration works properly with only_logs_after option</summary>

    ### Pre-conditions

    * There are already configured credentials for the `qa` profile.
    * Debug mode is enabled in the internal_configuration file.
    * There are already generated tests events for a period of 14 days

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Set a date for which there are logs available in the bucket</td>
    <td>All events with a timestamp greater than the only_logs_after value are processed</td>
    <td>

    <details><summary>ossec.conf</summary>

    ```XML
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <service type="inspector">
            <aws_profile>qa</aws_profile>
            <only_logs_after>date-to-test</only_logs_after>
        </service>
    </wodle>
    ```

    </details>
    </td>
    </tr>
    </table>

    ### Steps

    1. Delete the `aws_services.db` file using a fixture
    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check the expected number of events were sent to analysisd. Only the events whose timestamp is greater than the date specified in the configuration should be processed
    1. Check the database was created and updated accordingly

</details>

- <details><summary>Inspector integration works properly with regions option</summary>

    ### Pre-conditions

    * There are already configured credentials for the `qa` profile.
    * Debug mode is enabled in the internal_configuration file.
    * There are already generated tests events for a period of 14 days

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Use a region with data</td>
    <td>Only the logs for the specified region are processed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <service type="inspector">
            <aws_profile>qa</aws_profile>
            <only-logs-after>date-to-test</only-logs-after>
            <regions>region-1</regions>
        </service>
    </wodle>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Use multiple regions with data</td>
    <td>Only the logs for the specified regions are processed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <service type="inspector">
            <aws_profile>qa</aws_profile>
            <only-logs-after>date-to-test</only-logs-after>
            <regions>region-1,region-2</regions>
        </service>
    </wodle>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Use an non-existant region</td>
    <td>No logs should be processed. A message warning that the region does not exist should be displayed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <service type="inspector">
            <aws_profile>qa</aws_profile>
            <only-logs-after>date-to-test</only-logs-after>
            <regions>fake-region-1</regions>
        </service>
    </wodle>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Delete the `aws_services.db` file using a fixture
    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. If a region that does not exist was specified, make sure that a message is displayed in the `ossec.log` warning the user
    1. Check the expected number of events were forwarded to analysisd, only events stored in the log group for the specified region
    1. Check the database was created and updated accordingly

## Tier 1

- <details><summary>Inspector integration don't fetch logs that already were processed </summary>

    ### Pre-conditions

    * There are already configured credentials for the `qa` profile.
    * There are already generated tests events, for a period of 14 days.

    ### Cases

    |Case|Expected Result|
    |----|-----------|
    |Call the AWS module multiple times with different `only_logs_after` values|No duplicates were processed|

    ### Steps

    1. Delete the `aws_services.db` file using a fixture
    1. Call the module without `only_logs_after` and check that no logs were processed:

        ```bash
        /var/ossec/wodles/aws/aws-s3 --service inspector \
            --aws_profile qa \
            --debug 2
        ```

    1. Generate logs for the day of the test execution
    1. Call the module with the same parameters in `2` and check that the generated logs were processed
    1. Call the module with the same parameters in `2` and check that no logs were processed, there were no duplicates
    1. Call the module with `only_logs_after` set in the past and check that the expected number of logs were processed:

        ```bash
        /var/ossec/wodles/aws/aws-s3 --service inspector \
            --only_logs_after <date-to-test> \
            --aws_profile qa \
            --debug 2
        ```

    1. Call the module with the same parameters in `6` and check there were no duplicates
    1. Call the module with `only_logs_after` set with an older date than setted in `6` and check that old logs were processed without duplicates:

        ```bash
        /var/ossec/wodles/aws/aws-s3 --service inspector \
            --only_logs_after <older-date-than-step-6> \
            --aws_profile qa \
            --debug 2
        ```

    1. Call the module with `only_logs_after` set with an early date than setted in `6` and check that no logs were processed, there were no duplicates:

        ```bash
        /var/ossec/wodles/aws/aws-s3 --service inspector \
            --only_logs_after <early-date-than-step-6> \
            --aws_profile qa \
            --debug 2
        ```
    1. Delete the generated logs. This must be done even if the test fails

</details>

**Comment by nico-stefani** [comment]
I was looking for a way to generate findings from `Inspector` service.
I choose to use a lambda function that uses an old version of the  `requests` library with a CVE, resulting in:
![image](https://user-images.githubusercontent.com/7127104/215171476-753deaee-e46c-4f7b-ad40-a6473982f966.png)
