### ISSUE TITLE
Add Azure integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#3354]
| Development branch | 
|-----------------------------|
| TBC |

As explained in https://github.com/wazuh/wazuh-qa/issues/3332, we need to create new integration tests for the Azure module. Check the issue for more details.

Related issues:

- https://github.com/wazuh/wazuh-qa/issues/3356
- https://github.com/wazuh/wazuh-qa/issues/3357
- https://github.com/wazuh/wazuh-qa/issues/3358
- https://github.com/wazuh/wazuh-qa/issues/3359

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
