### ISSUE TITLE
Add Azure Graph integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#3356]
As part of https://github.com/wazuh/wazuh-qa/issues/3354 we need to Implement the integration test cases related to `Azure Graph` defined in https://github.com/wazuh/wazuh-qa/issues/3355.

## Test cases list
_Pending https://github.com/wazuh/wazuh-qa/issues/3355_

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
