### ISSUE TITLE
QA testing - Fix remote policy detection in SCA

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3368]
| Target version |Related PR |
|-------------------------------|---|
|  4.3.9  |https://github.com/wazuh/wazuh/pull/15007|

## Description

SCA should skip executing commands defined in files transmitted via shared configuration. However, we've detected and fixed multiple cases where the agent was not detecting that the path points to the shared folder.

## Proposed checks

- [x] The Windows agent rejects command execution in a shared folder defined with slashes (`/`).
- [x] The Windows agent rejects command execution in a shared folder defined with backslashes (`\`).
- [x] The Windows agent rejects command execution in a shared folder defined with an absolute path.
- [x] The Linux agent rejects command execution in a shared folder defined with an absolute path, even if it does not follow the exact pattern.

## Steps to reproduce

The configuration below contains two cases where the agent does not detect that the path points to a shared file.

## Expected results

We expect that, if these two conditions meet:
1. `<policy>` defines a path (absolute or relative) to the agent's shared folder.
2. The internal option `sca.remote_commands` is set to `0`.

Then, when the policy contains a command rule (`c: ...`), the agent must skip the command and print a log like this:
```
sca: WARNING: Ignoring check for policy '...'. The internal option 'sca.remote_commands' is disabled.
```

## Configuration and considerations

```xml
<agent_config>
  <sca>
    <policies>
      <policy>C:\Program Files (x86)\ossec-agent\./shared/test_windows.yml</policy>
      <policy>/var/ossec/etc/./shared/test_unix.yml</policy>
    </policies>
  </sca>
</agent_config>
```

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [cc286db](https://github.com/wazuh/wazuh/pull/15007/commits/cc286dbf8c69f3c3e341fae5fd17912022d38043) | 

### Testing environment

| OS | OS version | Deployment | Image/AMI 
|-- |-- |-- |-- 
| Ubuntu |  | 22 | [master](https://ci.wazuh.info/job/Wazuh_QA_environment/13/console)
| Ubuntu | 22 | Vagrant | [agent1](https://ci.wazuh.info/job/Wazuh_QA_environment/13/console)
| Windows Server | 2022 | Vagrant | [agent2](https://ci.wazuh.info/job/Wazuh_QA_environment/13/console)

### Tested packages

| OS | Package
|-- |--
| Ubuntu | [Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-agent_4.3.9-0.commitcc286db_amd64.deb) - [Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.9-0.commitcc286db_amd64.deb)
| Windows | [Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/windows/wazuh-agent-4.3.9-0.commitcc286db.msi)


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved
- [ ] Development team leader approved

**Comment by Rebits** [comment]
## Agent Ubuntu :large_blue_circle:
### Reproduce the error in production (4.3.8) :large_blue_circle: 
### Upgrade to the fixed version :large_blue_circle: 
### Fresh install :large_blue_circle:

**Comment by Rebits** [comment]
## Agent Windows Server :large_blue_circle:
### Reproduce the error in production (4.3.8)
### Upgrade to the fixed version
### Fresh install

**Comment by Rebits** [comment]
## Ubuntu Agent  - Out of the box cases

### Invalid Cases



<details>

<summary><code>etc/shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy>etc/shared/test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>
```
2022/09/30 08:21:31 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/test_unix.yml'
2022/09/30 08:21:31 sca: WARNING: Ignoring check for policy 'Testing policy - Unix'. The internal option 'sca.remote_commands' is disabled.
```

</details>



</blockquote>

</details>





<details>

<summary><code>etc/shared/../shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy>etc/shared/../shared/test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
```

</details>



</blockquote>

</details>



<details>

<summary><code>etc/shared/../shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy>etc\./shared\test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:35:10 sca: WARNING: Ignoring check for policy 'TESTING policy'. The internal option 'sca.remote_commands' is disabled.
```

</details>



</blockquote>

</details>





<details>

<summary><code>/var/ossec/ruleset/../etc/shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy enabled="yes">/var/ossec/ruleset/../etc/shared/test_unix.yml</policy>
        </policies>
  </sca>
</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/29 16:50:07 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/test_unix.yml'
2022/09/29 16:50:07 sca: WARNING: Ignoring check for policy 'CIS Benchmark for Debian/Linux 10'. The internal option 'sca.remote_commands' is disabled.
2022/09/29 16:50:07 sca: WARNING: Ignoring check for policy 'CIS Benchmark for Debian/Linux 10'. The internal option 'sca.remote_commands' is disabled.
```

</details>



</blockquote>

</details>




<details>

<summary><code>/var/ossec/ruleset/../etc/.././etc//./././././././shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy enabled="yes">/var/ossec/ruleset/../etc/.././etc//./././././././shared/test_unix.yml</policy>
        </policies>
  </sca>
</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:27:24 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/test_unix.yml'
2022/09/30 08:27:24 sca: WARNING: Ignoring check for policy 'Testing policy - Unix'. The internal option 'sca.remote_commands' is disabled.
```

</details>



</blockquote>

</details>



### Valid cases - Disable `sca.remote_commands`




<details>

<summary><code>etc/shared/../test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
          <policy>etc/shared/../test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:31:37 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/test_unix.yml'
2022/09/30 08:31:40 sca: INFO: Evaluation finished for policy '/var/ossec/etc/test_unix.yml'

```

</details>



</blockquote>

</details>



<details>

<summary>Disable <code>ruleset/sca/cis_ubuntu22-04.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="no">ruleset/sca/cis_ubuntu22-04.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:33:40 sca: INFO: Policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml' disabled by configuration.

```

</details>


</details>

<details>

<summary>Disable <code>/var/ossec/ruleset/sca/cis_ubuntu22-04.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="no">/var/ossec/ruleset/sca/cis_ubuntu22-04.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:34:33 sca: INFO: Policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml' disabled by configuration.

```

</details>



</blockquote>

</details>





<details>

<summary> <code>/tmp/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">tmp/test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:36:39 sca: INFO: Starting evaluation of policy: '/tmp/test_unix.yml'
2022/09/30 08:36:42 sca: INFO: Evaluation finished for policy '/tmp/test_unix.yml
```

</details>



</blockquote>

</details>







### Valid cases - Enable `sca.remote_commands`


<details>

<summary> <code>etc/shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">etc/shared/test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:40:58 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/test_unix.yml'
2022/09/30 08:41:01 sca: INFO: Evaluation finished for policy '/var/ossec/etc/shared/test_unix.yml'

```

</details>



</blockquote>

</details>




<details>

<summary> <code>/var/ossec/etc/shared/test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">/var/ossec/etc/shared/test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:41:41 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2022/09/30 08:41:41 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/test_unix.yml'

```

</details>



</blockquote>

</details>



<details>

<summary> <code>/var/ossec/etc/./shared/./test_unix.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">/var/ossec/etc/./shared/./test_unix.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:42:24 sca: INFO: Loaded policy '/var/ossec/etc/shared/test_unix.yml'
...
2022/09/30 08:42:37 sca: INFO: Evaluation finished for policy '/var/ossec/etc/shared/test_unix.yml'

```

</details>



</blockquote>

</details>

**Comment by Rebits** [comment]
## Windows Agent - Out of the box


### Invalid Cases

<details>

<summary> <code>shared\..\shared\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">shared\..\shared\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>              
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:54:33 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 08:54:33 sca: WARNING: Ignoring check for policy 'Testing policy - Windows'. The internal option 'sca.remote_commands' is disabled.
2022/09/30 08:54:36 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'

```

</details>



</blockquote>

</details>








<details>

<summary> <code>c:/Program Files (x86)/ossec-agent/../ossec-agent/./shared/test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:/Program Files (x86)/ossec-agent/../ossec-agent/./shared/test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>
            
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:55:52 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 08:55:52 sca: WARNING: Ignoring check for policy 'Testing policy - Windows'. The internal option 'sca.remote_commands' is disabled.
2022/09/30 08:55:55 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'


```

</details>



</blockquote>

</details>






<details>

<summary> <code>c:\Program Files (x86)\ossec-agent\..\ossec-agent\.\shared\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\Program Files (x86)\ossec-agent\..\ossec-agent\.\shared\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```

2022/09/30 08:57:12 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 08:57:12 sca: WARNING: Ignoring check for policy 'Testing policy - Windows'. The internal option 'sca.remote_commands' is disabled.
2022/09/30 08:57:15 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'

```

</details>



</blockquote>

</details>






<details>

<summary> <code>ruleset/../shared/test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">ruleset/../shared/test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 08:59:05 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 08:59:05 sca: WARNING: Ignoring check for policy 'Testing policy - Windows'. The internal option 'sca.remote_commands' is disabled.

```

</details>



</blockquote>

</details>



### Valid Cases - Disable `sca.remote_command`

<details>

<summary> <code>shared\..\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">shared\..\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:06:27 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\test_windows.yml'
2022/09/30 09:06:30 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\test_windows.yml'


```

</details>



</blockquote>

</details>





<details>

<summary> Disable <code>ruleset/sca/cis_win2022.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="no">ruleset/sca/cis_win2022.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:09:08 sca: INFO: Policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml' disabled by configuration.

```

</details>



</blockquote>

</details>






<details>

<summary> Disable <code>c:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="no">c:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:12:18 sca: INFO: Policy 'c:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml' disabled by configuration.

```

</details>



</blockquote>

</details>







<details>

<summary>  <code>c:\Program Files (x86)\ossec-agent\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\Program Files (x86)\ossec-agent\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:14:20 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\test_windows.yml'
2022/09/30 09:14:23 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\test_windows.yml'


```

</details>



</blockquote>

</details>






<details>

<summary>  <code>c:\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>
```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:17:01 sca: INFO: Loaded policy 'c:\test_windows.yml'

```

</details>



</blockquote>

</details>




### Valid Cases - Enable `sca.remote_command`











<details>

<summary> <code>shared\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">shared\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:22:25 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 09:22:28 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'

```

</details>



</blockquote>

</details>





<details>

<summary> <code>shared/test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">shared/test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:23:46 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 09:23:49 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
```

</details>



</blockquote>

</details>









<details>

<summary> <code>c:\Program Files (x86)\ossec-agent\shared\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\Program Files (x86)\ossec-agent\shared\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:24:55 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 09:24:58 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'


```

</details>



</blockquote>

</details>




<details>

<summary> <code>c:\Program Files (x86)\ossec-agent\.\shared\.\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\Program Files (x86)\ossec-agent\.\shared\.\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:26:16 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'
2022/09/30 09:26:19 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\shared\test_windows.yml'


```

</details>



</blockquote>

</details>





<details>

<summary> <code>c:\Program Files (x86)\ossec-agent\shared\subfolder\test_windows.yml</code> :green_circle:</summary>

<blockquote>

<details>

<summary> agent.conf </summary>

```
<agent_config>
  <sca>
        <policies>
                <policy enabled="yes">c:\Program Files (x86)\ossec-agent\shared\subfolder\test_windows.yml</policy>
        </policies>
  </sca>

</agent_config>

```

</details>




<details>

<summary> ossec.log </summary>

```
2022/09/30 09:31:09 sca: INFO: Starting evaluation of policy: 'c:\Program Files (x86)\ossec-agent\shared\subfolder\test_windows.yml'
2022/09/30 09:31:12 sca: INFO: Evaluation finished for policy 'c:\Program Files (x86)\ossec-agent\shared\subfolder\test_windows.yml'

```

</details>



</blockquote>

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
