### ISSUE TITLE
test remoted process is not at 100% of CPU usage in a Wazuh master node without agents

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3370]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|4.5|[#14733](https://github.com/wazuh/wazuh/issues/14733)| [#15074](https://github.com/wazuh/wazuh/pull/15074) |

## Description

This change should fix a `remoted` performance issue where when the cluster has a lot of multigroups configured the cluster synchronization consumes a lot of CPU taking a lot of time to finish
## Proposed checks

- [x] Benchmark
- [x] Performance with 2500 multigroups
  <details><summary>Test cases</summary>
  
  1. Configure a `wazuh-cluster`
  2. Setup 2500 groups, + 2000 multigroups and + 50000 shared files
  3. Check how long takes to update shared files sums
      ```log
      grep "c_files()" /var/ossec/logs/ossec.log 

      ```
</details>

- [x] The cluster syncronization should work properly 
  <details><summary>Test cases</summary>

  - <details><summary>Cluster doesn't re-synchronize multigroups files when a worker node is restarted </summary>

    1. Configure a `wazuh-cluster` with a master and two workers.
        ```sql
        /var/ossec/bin/cluster_control -l
        ```
    2. Connect 10 `wazuh-agents` and generate multigroups.
    3. Desconnect the `wazuh-agents`
    4. Check the multigroups files generated in all nodes.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    5. Restart any worker and verify it doesn't re-synchronize multigroups files.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    </details>

  - <details><summary>Cluster doesn't re-synchronize multigroups files when a the master node is restarted </summary>

    1. Configure a `wazuh-cluster` with a master and two workers.
        ```sql
        /var/ossec/bin/cluster_control -l
        ```
    2. Connect 10 `wazuh-agents` and generate multigroups.
    3. Desconnect the `wazuh-agents`
    4. Check the multigroups files generated in all nodes.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    5. Restart the master node and verify the cluster doesn't re-synchronize multigroups files.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    </details>

  - <details><summary>Cluster re-synchronize a multigroup files when a change is detected </summary>

    1. Configure a `wazuh-cluster` with a master and two workers.
        ```sql
        /var/ossec/bin/cluster_control -l
        ```
    2. Connect 10 `wazuh-agents` and generate multigroups.
    3. Desconnect the `wazuh-agents`
    4. Check the multigroups files generated in all nodes.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    5. Create a new file inside a group's folder.
        
        `echo "testing" > /var/ossec/etc/shared/g1/test.txt`

    6. Restart the master node and verify the cluster doesn't re-synchronize multigroups files.
        ```log
        ll /var/ossec/var/multigroups/
        ```
    </details>

</details>

### Required installation methods
- [x] Fresh install
- [x] Upgrade

## Expected results

The module `remoted` should not make the clusters systems CPUs collapse nor consume a lot of resources

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [712fd56](https://github.com/wazuh/wazuh/pull/15074/commits/712fd562c59ad61a1d0c8c8f9ddf5cc98fdb2935)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commit712fd56_amd64.deb)||       

### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Testing Results
## Work in Progress
Using the python script to generate `groups` and `multigroups`
```python
import requests
import signal
import sys
import os
import json
import urllib3
import random
import shutil

from pwn import *
from time import sleep
from requests.auth import HTTPBasicAuth


def def_handler(sig, frame):
    print("\n[!] Saliendo...\n")
    sys.exit(1)


# Ctrl+C
signal.signal(signal.SIGINT, def_handler)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Variable globales
token_url = "https://192.168.56.10:55000/security/user/authenticate?raw=true"
create_group_url = "https://192.168.56.10:55000/groups?pretty=true"


def getToken():
    response = requests.get(token_url, auth=('wazuh', 'wazuh'), verify=False)
    token = response.text
    return token


def createGroupRequest(group_name, token=None):
    if token == None:
        auth_token = getToken()
    else:
        auth_token = token

    hed = {'Authorization': 'Bearer ' + auth_token}
    data = {'group_id': group_name}
    response = requests.post(
        create_group_url, json=data, headers=hed, verify=False)
    # print(response)
    # print(response.json())
    if response.status_code == 200:
        copyGroupsFiles(group_name)

    return response


def copyGroupsFiles(group_name):
    src = '/var/ossec/etc/shared/default'
    trg = '/var/ossec/etc/shared/{}'.format(group_name)

    files = os.listdir(src)

    # iterating over all the files in
    # the source directory
    for fname in files:
        if "merged" not in fname:
            # copying the files to the
            # destination directory
            shutil.copy2(os.path.join(src, fname), trg)
            os.chown(os.path.join(trg, fname), 998, 998)


def assginAgentToGroupRequest(agent_id, group_name, token=None):
    if token == None:
        auth_token = getToken()
    else:
        auth_token = token

    hed = {'Authorization': 'Bearer ' + auth_token}

    assign_group_url = 'https://localhost:55000/agents/{}/group/{}?pretty=true'.format(
        agent_id, group_name)

    response = requests.put(assign_group_url, headers=hed, verify=False)

    return response
    # print(response)
    # print(response.json())


def removeAgentsFromGroupRequest(group_name, token=None):
    if token == None:
        auth_token = getToken()
    else:
        auth_token = token

    hed = {'Authorization': 'Bearer ' + auth_token}

    remove_agent_group_url = 'https://localhost:55000/agents/group?agents_list=all&group_id={}&pretty=true'.format(
        group_name)

    response = requests.delete(
        remove_agent_group_url, headers=hed, verify=False)

    return response


def deleteGroupRequest(group_name, token=None):
    if token == None:
        auth_token = getToken()
    else:
        auth_token = token

    hed = {'Authorization': 'Bearer ' + auth_token}

    remove_group_url = 'https://localhost:55000/groups?groups_list={}&pretty=true'.format(
        group_name)

    response = requests.delete(remove_group_url, headers=hed, verify=False)

    return response


def deleteAgentRequest(agent_id, token=None):
    if token == None:
        auth_token = getToken()
    else:
        auth_token = token

    hed = {'Authorization': 'Bearer ' + auth_token}

    remove_agent_url = 'https://localhost:55000/agents?pretty=true&older_than=0s&agents_list={}&status=all'.format(
        agent_id)

    response = requests.delete(remove_agent_url, headers=hed, verify=False)

    return response


def createGroups(min, max):
    p1 = log.progress("Create groups")
    token = getToken()
    for i in range(min, max):
        p1.status("Creating group: ID: %d", i)
        group_name = 'g{}'.format(i)
        # sleep(0.5)
        r = createGroupRequest(group_name, token)
        if r.status_code != 200:
            print(r.json())
        sleep(0.1)
    p1.success("Create group finished")


def assginAgentToGroup(agent_min, agent_max, group_min, group_max, groups_per_agents):
    p1 = log.progress("Assign groups to agent")
    token = getToken()
    for id in range(agent_min, agent_max):
        agent = str(id).zfill(3)
        p1.status("Assigning group to agent: ID: %s", agent)

        for i in range(groups_per_agents):
            n = random.randint(group_min, group_max-1)
            group = 'g{}'.format(n)
            r = assginAgentToGroupRequest(agent, group, token)
            if r.status_code != 200:
                print(r.json())
            sleep(0.3)
    p1.success("Assign group finished")


def removeAgentsFromGroup(group_min, group_max):
    p1 = log.progress("Remove agents from group")
    token = getToken()

    for i in range(group_min, group_max):
        group = 'g{}'.format(i)
        p1.status("Removing agent from group: ID: %s", group)
        r = removeAgentsFromGroupRequest(group, token)
        if r.status_code != 200:
            print(r.json())
        sleep(0.5)
    p1.success("Remove agents from group finished")


def removeGroup(group_min, group_max):
    p1 = log.progress("Remove group")
    token = getToken()

    for i in range(group_min, group_max):
        group = 'g{}'.format(i)
        p1.status("Removing group: ID: %s", group)
        r = deleteGroupRequest(group, token)
        if r.status_code != 200:
            print(r.json())
        sleep(0.5)
    p1.success("Remove group finished")


def removeAllGroups():
    p1 = log.progress("Remove group")
    token = getToken()

    p1.status("Removing group: ID: %s", group)
    r = deleteGroupRequest("all", token)

    p1.success("Remove group finished")


def deletaAgents(agent_min, agent_max):
    p1 = log.progress("Remove agent")
    token = getToken()
    for id in range(agent_min, agent_max):
        agent = str(id).zfill(3)
        p1.status("Removing agent: ID: %s", agent)

        r = deleteAgentRequest(agent, token)
        if r.status_code != 200:
            print(r.json())
        sleep(0.3)
    p1.success("Removing finished")


if __name__ == '__main__':
    removeAllGroups()
    sleep(2)
    createGroups(1, 2500)  # Create groups g1, g2, g3.... g10
    sleep(2)
    # For each agent between 001 and 006 assigns 2 random groups between g1 and g11
    assginAgentToGroup(1000, 1500, 1, 2500, 3)
    # deletaAgents(30,518)
    #removeAgentsFromGroup(6, 399)
    #removeGroup(1, 5)
    #removeAllGroups()
    # sleep(1)
    #createGroups(1, 151)

```

**Comment by QU3B1M** [comment]
# Update 28/11/2022
It is needed to add and execute extra  `performance tests` for this PR as the changes have impact in the whole `multigroups` generation process, it is being analyzed what and how to test.

**Comment by QU3B1M** [comment]
# Update 02/01/2023

**Comment by QU3B1M** [comment]
# Update 03/01/2023
- Benchmark test started
- The results from this PR will be compared against `master` (4.5.0)

**Comment by QU3B1M** [comment]
# Update 05/01/2023
- Prepared scripts to make the test arrangement
- Executed benchmark tests as in the issue [#3269](https://github.com/wazuh/wazuh-qa/issues/3269#issuecomment-1241878358):
    It was noticed that using the same amount of groups and agents that Victor used is not that representative, so the same tests with more agents and multigroups is being done

**Comment by QU3B1M** [comment]
# Update 06/01/2023
- Finishing execution

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
