### ISSUE TITLE
PagerDuty and Slack integrations working at the same time

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3375]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5|[#4264](https://github.com/wazuh/wazuh/issues/4264)|[#14848](https://github.com/wazuh/wazuh/pull/14848)|

## Description

This change aims to fix the bug where PagerDuty and Slack integration are not working correclty when both are declares at the same time.

## Proposed checks

- [x] Upgrade - Only one integration at the time works correcly
  <details><summary>Test cases</summary>

  - <details><summary>Slack integration works properly</summary>

    1. Create a [Slack webhook](https://api.slack.com/messaging/webhooks)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to Slack
    </details>

  - <details><summary>PagerDuty integration works properly</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to PagerDuty
    </details>

  </details>

- [x] Upgrade - Both integrations at the same time works correcly
  <details><summary>Test cases</summary>

  - <details><summary>PagerDuty and Slack integrations at the same time</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time declaring PagerDuty first</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in PagerDuty</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
        <rule_id>5402</rule_id>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in Slack</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in both</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <rule_id>5402</rule_id>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>
  </details>

- [x] Fresh Install - Only one integration at the time works correcly
  <details><summary>Test cases</summary>

  - <details><summary>Slack integration works properly</summary>

    1. Create a [Slack webhook](https://api.slack.com/messaging/webhooks)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to Slack
    </details>

  - <details><summary>PagerDuty integration works properly</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to PagerDuty
    </details>

  </details>

- [x] Fresh Install - Both integrations at the same time works correcly
  <details><summary>Test cases</summary>

  - <details><summary>PagerDuty and Slack integrations at the same time</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time declaring PagerDuty first</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in PagerDuty</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
        <rule_id>5402</rule_id>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in Slack</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in both</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <rule_id>5402</rule_id>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>
  </details>

## Expected results

Both integrations should work correctly at the same time

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [6dba7df](https://github.com/wazuh/wazuh/pull/14848/commits/6dba7df01c4813270474d18d3158b344176b691e)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commit6dba7df_amd64.deb)|-|       

### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
## Fresh install

<details><summary>Using one integration at the time works correcly :green_circle:</summary>

  - <details><summary>Slack integration works properly :green_circle:</summary>

    1. Create a [Slack webhook](https://api.slack.com/messaging/webhooks)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
        ```XML
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
        </integration>
        ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    5. Check the generated alert is forwarded to Slack :green_circle:
        ![fresh-install-slack](https://user-images.githubusercontent.com/44633633/193472853-0724a974-ad7d-4af4-9c5c-e0c7ca24c5a6.png)

    </details>

  - <details><summary>PagerDuty integration works properly :green_circle:</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
        ```XML
        <integration>
          <name>pagerduty</name>
          <api_key>PAGERDUTY_API_KEY</api_key> 
        </integration>
        ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    5. Check the generated alert is forwarded to PagerDuty :green_circle:
        ![fresh-pager-duty](https://user-images.githubusercontent.com/44633633/193472868-fa8acf40-c16d-4051-8d66-a4b02a3bf581.png)
    </details>

  </details>

<details><summary>Both integrations at the same time works correcly :green_circle:</summary>

  - <details><summary>PagerDuty and Slack integrations at the same time :green_circle:</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
        ```XML
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
        </integration>
        
        <integration>
          <name>pagerduty</name>
          <api_key>PAGERDUTY_API_KEY</api_key> 
        </integration>
        ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack :green_circle:
        `Slack`
![fresh-01-slack](https://user-images.githubusercontent.com/44633633/193472936-6083d1c9-d4ef-47a5-a2e1-05b19746df94.png)

        `PagerDuty`
![fresh-01-pagerduty](https://user-images.githubusercontent.com/44633633/193472932-efa42053-66a3-4c63-924d-2ebbddcb3a8f.png)


    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time declaring PagerDuty first :green_circle:</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
        ```XML
        <integration>
          <name>pagerduty</name>
          <api_key>PAGERDUTY_API_KEY</api_key> 
        </integration>
        
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
        </integration>
        ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack :green_circle:
        `Slack`
![fresh-02-slack](https://user-images.githubusercontent.com/44633633/193472992-088982b5-9c43-4b21-adaa-a497746750d7.png)

        `PagerDuty`
![fresh-02-pager](https://user-images.githubusercontent.com/44633633/193472985-b6187009-1acb-43bd-84df-3a4d9ef30e9b.png)

    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in PagerDuty :green_circle:</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
        ```XML
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
        </integration>

        <integration>
          <name>pagerduty</name>
          <api_key>PAGERDUTY_API_KEY</api_key>
          <rule_id>5402</rule_id>
        </integration>
        ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack :green_circle:
        `Slack`
![fresh-03-slack](https://user-images.githubusercontent.com/44633633/193473003-8cf14d78-f665-4ff6-975c-782a23b5212d.png)

        `PagerDuty`
![fresh-03-pager](https://user-images.githubusercontent.com/44633633/193472999-8085b4e6-0d1c-4394-af3a-8570ec2f1c7a.png)

    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in Slack :green_circle:</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
        ```XML
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
          <rule_id>5402</rule_id>
        </integration>
        
        <integration>
          <name>pagerduty</name>
          <api_key>PAGERDUTY_API_KEY</api_key> 
        </integration>
        ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
        > This is just to generate an easy alert
        `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack :green_circle:
        `Slack`
![fresh-04-slack](https://user-images.githubusercontent.com/44633633/193473013-1392c11c-e4c7-4d50-af87-6f43415cb354.png)

        `PagerDuty`
![fresh-04-pager](https://user-images.githubusercontent.com/44633633/193473011-a1a5006b-d501-4859-92b9-f549141ae6f6.png)

    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in both :green_circle:</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
        ```XML
        <integration>
          <name>slack</name>
          <hook_url>SLACK_WEBHOOK</hook_url>
          <alert_format>json</alert_format>
          <rule_id>5402</rule_id>
        </integration>
        
        <integration>
          <name>pagerduty</name>
          <rule_id>5402</rule_id>
          <api_key>PAGERDUTY_API_KEY</api_key> 
        </integration>
        ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack :green_circle:
        `Slack`
![fresh-05-slack](https://user-images.githubusercontent.com/44633633/193473088-3c7bacf8-f7c0-4c71-923c-9d4cf4c1b705.png)

        `PagerDuty`
![fresh-05-pager](https://user-images.githubusercontent.com/44633633/193473084-013fcab3-5cd2-4a11-b442-f209fc1e871f.png)

    </details>
  </details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
