### ISSUE TITLE
Tests development - PagerDuty and Slack integrations working at the same time

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3376]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5|[#4264](https://github.com/wazuh/wazuh/issues/4264)|[#14848](https://github.com/wazuh/wazuh/pull/14848)|

## Description

This change aims to fix the bug where PagerDuty and Slack integration are not working correclty when both are declares at the same time.

## Proposed test cases

- [ ] PagerDuty and Slack integrations works correcly
  <details><summary>Tier 1 test cases</summary>

  - <details><summary>Slack integration works properly</summary>

    1. Create a [Slack webhook](https://api.slack.com/messaging/webhooks)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to Slack
    </details>

  - <details><summary>PagerDuty integration works properly</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Install wazuh-manager and add the integration config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    3. Restart wazuh-manager
    4. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    5. Check the generated alert is forwarded to PagerDuty
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>
  </details>

  <details><summary>Tier 2 test cases</summary>

  - <details><summary>PagerDuty and Slack integrations at the same time declaring PagerDuty first</summary>
  
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in PagerDuty</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
        <rule_id>5402</rule_id>
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in Slack</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  - <details><summary>PagerDuty and Slack integrations at the same time specifying rule in both</summary>
    
    1. Get the [PagerDuty API key](https://support.pagerduty.com/docs/api-access-keys)
    2. Create a [Slack webhook](https://api.slack.com/messaging/webhooks) 
    3. Install wazuh-manager and add both integrations config to the `ossec.conf`
      ```XML
      <integration>
        <name>slack</name>
        <hook_url>SLACK_WEBHOOK</hook_url>
        <alert_format>json</alert_format>
        <rule_id>5402</rule_id>
      </integration>
      
      <integration>
        <name>pagerduty</name>
        <rule_id>5402</rule_id>
        <api_key>PAGERDUTY_API_KEY</api_key> 
      </integration>
      ```
    4. Restart wazuh-manager
    5. In the wazuh-manager system use `sudo` to log with the user root
      > This is just to generate an easy alert
      `sudo su`
    6. Check the generated alert is forwarded to PagerDuty and Slack
    </details>

  </details>

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
