### ISSUE TITLE
A race condition in Remoted is blocking agent connections

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3382]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4|[#12776](https://github.com/wazuh/wazuh/issues/12776) [#10172](https://github.com/wazuh/wazuh/issues/10172) |[#15165](https://github.com/wazuh/wazuh/pull/15165)|

## Description

This change should fix an error where when a lot of agents are connecting and disconnecting at the same time, it starts dropping packages and generates issues with the agent keys generation/validation.\
It will also fix one more issue [#10172](https://github.com/wazuh/wazuh/issues/10172) where an error is raised when the same key is configured in two agents

## Proposed checks

- [x] Multiple agents re-connecting at the same time
  <details><summary>Test cases</summary>  

    - <details><summary>Re-connect 200 agents at the same time</summary>

      1. Install a `wazuh-manager` and start it
      2. Setup 200 agents to connect to the manager
      3. Start the agents and check that all of the are connecting to the manager
        ```
        cat /var/ossec/logs/ossec.log
        ```
      4. Restart the agents 
      5. Check that the agents were disconnected and connected correcly 
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      </details>

    - <details><summary>Re-connect 400 agents at the same time</summary>

      1. Install a `wazuh-manager` and start it
      2. Setup 400 agents to connect to the manager
      3. Start the agents and check that all of the are connecting to the manager
        ```
        cat /var/ossec/logs/ossec.log
        ```
      4. Restart the agents 
      5. Check that the agents were disconnected and connected correcly 
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      </details>

    - <details><summary>Re-connect 100 agents and later connect other 100</summary>

      1. Install a `wazuh-manager` and start it
      2. Setup 100 agents to connect to the manager
      3. Start the agents and check that all agents are connecting to the manager
        ```
        cat /var/ossec/logs/ossec.log
        ```
      4. Stop those agents 
      5. Setup and connect other 100 agents
      6. Check that the agents were connected correctly
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      7. Stop the agents and restart all 200 agents together
      8. Check that all agents were connected correctly
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      </details>

    - <details><summary>Connect 200 agents at the same time and restart the manager</summary>

      1. Install a `wazuh-manager` and start it
      2. Setup 200 agents to connect to the manager
      3. Start the agents and check that all of the are connecting to the manager
        ```
        cat /var/ossec/logs/ossec.log
        ```
      4. Restart the manager and check that all agents are connected correcly 
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      </details>

    - <details><summary>On a cluster setup re-connect 200 agents at the same time</summary>

      1. Setup a wazuh `cluster`
      2. Setup 200 agents to connect to the cluster
      3. Start the agents and check that all of the are connecting to the cluster
        ```
        cat /var/ossec/logs/ossec.log
        ```
      4. Restart the agents 
      5. Check that the agents were disconnected and connected correcly 
        > There should not be any WARNING of `agent key already in use` nor `Package dropped`
        ```
        grep "WARNING" /var/ossec/logs/ossec.log
        ```
      </details>

    - <details><summary>On a cluster setup with 200 agents connected restart the master node</summary>

      1. Configure a `wazuh-cluster`
      2. Setup 200 agents and connect them to the cluster
      3. Restart the master node
      4. Check the WARNING message is not being raised

      </details>
  </details>

- [x] Generate alerts from two agents with the same key
  <details><summary>Test cases</summary>  

    - <details><summary>Connect two agents with the same <code>client.key</code></summary>

        1. Install a `wazuh-manager-4.4.0`  
        2. Install a `wazuh-agent` and extract the `client.key`.
        3. Install another `wazuh-agent` and set the `client.key` from the other agent into this one.
        4. Generate alert in both agents
        5. Check that only the alerts from one of the agents is received
          ```bash
          tail /var/ossec/logs/alerts/alerts.json
          ```
        6. Check the WARNING message appears.
          > There should be a WARNING of `agent key already in use
          ```
          grep "WARNING" /var/ossec/logs/ossec.log
          ```
      </details>

    - <details><summary>Connect two agents with the same <code>client.key</code> to a cluster, same worker</summary>

        1. Setup a `wazuh-cluster` 
        2. Install a `wazuh-agent` and extract the `client.key`.
        3. Install another `wazuh-agent` and set the `client.key` from the other agent into this one.
        4. Connect both agents to the same worker
        5. Generate alert in both agents
        6. Check that only the alerts from one of the agents is received
          ```bash
          tail /var/ossec/logs/alerts/alerts.json
          ```
        7. Check the WARNING message appears.
          > There should be a WARNING of `agent key already in use
          ```
          grep "WARNING" /var/ossec/logs/ossec.log
          ```
      </details>

    - <details><summary>Connect two agents with the same <code>client.key</code> to a cluster, different worker</summary>

        1. Setup a `wazuh-cluster` 
        2. Install a `wazuh-agent` and extract the `client.key`.
        3. Install another `wazuh-agent` and set the `client.key` from the other agent into this one.
        4. Connect agents to different workers
        5. Generate alert in both agents
        6. Both alerts are received
        7. The WARNING message won't appears.

      </details>
  </details>

### Required installation methods
- [x] Fresh install
- [x] Upgrade

## Expected results

Wazuh should support multiple agents connecting and disconnecting at the same time without generating any error with the agent keys.

## Configuration and considerations

The following zip file includes a docker image and a `sh` to execute multiple agents and connect them to a manager. It could be helpful

[agents-army.zip](https://github.com/wazuh/wazuh-qa/files/9675423/agents-army.zip)

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [1e36ecd](https://github.com/wazuh/wazuh/pull/15165/commits/1e36ecd998d51deee9c0b37965759d3b9d3e415c)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit1e36ecd_amd64.deb)|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit1e36ecd_amd64.deb)|       

### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Testing results :white_circle:

## Unfixed

<details><summary>Error repoduction</summary>
  
  1. Install and start `wazuh-manager-4.4.0` 
  2. Install and start 200 `wazuh-agents`
  3. Create a file `testfile.txt` inside the default group folder
    > This is to the manager to restart all the agents "at the same time"
    ```bash
    echo "test" > /var/ossec/etc/shared/default/testfile.txt
    ```
  4. Check the managers logs :red_circle:
    ```log
    grep "WARN" /var/ossec/logs/ossec.log

    2022/10/31 14:44:42 wazuh-remoted: WARNING: Package dropped. Could not append data into buffer.
    2022/10/31 14:44:44 wazuh-remoted: WARNING: Agent key already in use: agent ID '190'
    ```
  </details>


## Upgrade :white_circle:




## Fresh install :white_circle:

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: The changes for https://github.com/wazuh/wazuh/issues/12776 and https://github.com/wazuh/wazuh/issues/10172 were applied to the same branch(https://github.com/wazuh/wazuh/pull/15165) and are tested in this issue. Both work correctly.
    
    Currently, there are no warnings or packages loss when many agents connect at the same time, and warning logs are generated when connecting two agents configured with the same key every 10 seconds.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
