### ISSUE TITLE
QA testing - Remove default Windows Audit SCA file

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3386]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.3.9         |           https://github.com/wazuh/wazuh/issues/14497             |            https://github.com/wazuh/wazuh/pull/14498        |

## Description
Wazuh currently has a generic Windows Audit SCA that is not based on a CIS document.
Remove it and prevent it from being deployed on Agent and Manager installs.

How to make the change:
Delete file sca_win_audit.yml and references to that file in sca.manager.files and wazuh-installer.wxs

## Proposed checks

- [x] Install windows 10, windows 11, and windows 2022 agents and verify the yml file is not deployed anymore.
- [x] Verify each agent runs the expected SCA policy

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [a4402aa](https://github.com/wazuh/wazuh/pull/14498/commits/a4402aab731ff7d29e371df536ef59f5c4f18710) | 



### Testing environment

| OS | OS version | Deployment | Image/AMI 
|-- |-- |-- |-- 
| Ubuntu |  | 22 | Vagrant(Manager for W11 and W10 agents)/[master](https://ci.wazuh.info/job/Wazuh_QA_environment/20/console) (Manager for WS2022)
| Windows Server | 2022 | EC2 | [agent2](https://ci.wazuh.info/job/Wazuh_QA_environment/13/console)
| Windows  | 10 | Vagrant | |
| Windows  | 10 | Vagrant | |


### Tested packages

| OS | Package
|-- |--
| Ubuntu |  [Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.9-0.commita4402aa_amd64.deb)
| Windows | [Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/windows/wazuh-agent-4.3.9-0.commita4402aa.msi)



### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved
- [ ] Development team leader approved

**Comment by Rebits** [comment]
## Windows 11 Agent :large_blue_circle:

<details>


<summary> Install windows 10, windows 11, and windows 2022 agents and verify the yml file is not deployed anymore.   :large_blue_circle:
</summary>


</details>



<details>


<summary>  Verify each agent runs the expected SCA policy  :large_blue_circle:</summary>


</details>

**Comment by Rebits** [comment]
## Windows 10 Agent :large_blue_circle:

<details>


<summary> Install windows 10, windows 11, and windows 2022 agents and verify the yml file is not deployed anymore.   :large_blue_circle:
</summary>


</details>



<details>


<summary>  Verify each agent runs the expected SCA policy  :large_blue_circle:</summary>


</details>

**Comment by Rebits** [comment]
## Out of the box

<details>

<summary> Windows 11 Upgrade (4.3.8 -> 4.3.9 ) :green_circle: </summary>

<br>

Upgrade seems to remove default Windows Audit SCA file

![image](https://user-images.githubusercontent.com/11089305/193305081-5fcd2e1a-550f-4ff1-821f-b6b5878ef1b9.png)

</details>


<details>

<summary> Windows 10 Upgrade (4.3.8 -> 4.3.9 ) :red_circle:  </summary> <blockquote>

During the upgrade process, the SCA folder gets empty and the following error is produced

<details>

<summary> ossec.log </summary>

```
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:42 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
2022/09/30 16:06:43 wazuh-agent: ERROR: Error in LookupAccountSid.
```

</details>

### How to reproduce

-  Install 4.3.8 Windows agent.
-  Register the agent to the manager.
-  Upgrade manually to v4.3.9 when the agent is running.

<details>

<summary> Mark ok to the upgrade process </summary>

![reb](https://user-images.githubusercontent.com/11089305/193313902-963a337e-ae94-4f19-a3c8-f9ce0f066fdb.png)

</details>




<details>

<summary> Mark yes to restart host now </summary>

![reb2](https://user-images.githubusercontent.com/11089305/193314448-a168805d-ed7d-456f-92b5-0da4015af18b.png)


</details>




<details>

<summary> After reboot, sca directory is empty, and errors appears in the windows agent log </summary>


![reb3](https://user-images.githubusercontent.com/11089305/193314732-e31978be-cece-4d3b-b814-b91b06dc796b.png)

</details>



</blockquote>

**Comment by jmv74211** [comment]
It has been verified that the Windows audit policy is removed, but during testing a bug was detected (not introduced in the new development) which has been reported [here](https://github.com/wazuh/wazuh/issues/15064), and will be investigated and fixed in future versions.
