### ISSUE TITLE
FIM v2.0: Analysisd Integration tests: Scan messages

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-qa#339]
## Description

This issue covers the integration test for scan messages handling by Analysisd. We will treat Analysisd as a black box that receives integrity events by its input Unix socket, checking that the correct output is forwarded to the desired socket (simulating Wazuh DB).

Two use cases have been defined to check that the scan messages are handled properly. These cases should be implemented in the same test.

- [ ] Scan start
- [ ] Scan end

A scan message in the `analysisd` socket must provoke the writing of a query in the `wazuh-db` socket by `analysisd`. There are two types of scan message: `scan_start` and `scan_end`.

## Scan start

**Input location**

The `analysisd` socket:
```
/var/ossec/queue/ossec/queue
```

**Input message**:

```
8:[001] (vm-ubuntu-agent) 192.168.57.2->syscheck:{"type":"scan_start","data":{"timestamp":1575442712}}
```

**Output location**:
The `wazuh-db` socket:
```
/var/ossec/queue/db/wdb
```

**Output message**:

```
agent 001 syscheck scan_info_update start_scan 1575442712
```

## Scan end

**Input location**

The `analysisd` socket:
```
/var/ossec/queue/ossec/queue
```

**Input message**:

```
8:[001] (vm-ubuntu-agent) 192.168.57.2->syscheck:{"type":"scan_end","data":{"timestamp":1575442712}}
```

**Output location**:
The `wazuh-db` socket:
```
/var/ossec/queue/db/wdb
```

**Output query**:
```
agent 001 syscheck scan_info_update end_scan 1575442712
```

## Validation

The next steps are required to validate this test:
- The agent ID indicated in the input message must be matched in the query.
- The timestamp indicated in the input message must be matched in the query.
- The query command must be `scan_info_update` in both cases.
- If the `type` field is `scan_start`, `start_scan` must be matched in the query. If the `type` field is `scan_end`, `end_scan` must be matched in the query.

**Comment by davidjiglesias** [comment]
**Updated test results:**
root@wazuh-master:/wazuh-qa/test_wazuh# python3 -m pytest -vvx test_analysisd/test_scan_messages/test_scan_messages.py 
============================== test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /wazuh-qa/test_wazuh, inifile: pytest.ini
collected 2 items                                                               

test_analysisd/test_scan_messages/test_scan_messages.py::test_scan_messages[message_0] PASSED [ 50%]
test_analysisd/test_scan_messages/test_scan_messages.py::test_scan_messages[message_1] PASSED [100%]

=============================== 2 passed in 5.24s ===============================
