### ISSUE TITLE
Remove wrong Fedora Linux SCA default policies

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3392]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.0               |                https://github.com/wazuh/wazuh/issues/14781      |                    |

## Description

This PR removes SCA support for fedora systems that don't have the proper CIS Benchmark implementation. 
Each Fedora platform will be covered in subsequent releases with good SCA policies. 

- [x] Install a Fedora system, verify /var/ossec/ruleset/sca/ folder is empty
- [x] Verify /var/ossec/logs/ossec.log doesn't show any errors related to SCA and has an output similar to: 

```
2022/11/04 10:19:13 sca: INFO: Module started.
2022/11/04 10:19:13 sca: INFO: No policies defined. Exiting
```

**Comment by fedepacher** [comment]
# Update 2022/11/04

## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @fedepacher | [bd25f66](https://github.com/wazuh/wazuh/pull/15251/commits/a9e8641ae759d2eeb4da3766b38dbc141bd25f66)    | 

### Testing environment

| OS | OS version | Deployment                                     | Notes |
|----|------------|-----------------------------------------------|-----------|
|  Fedora  | 34/35/36/37 | Vagrant box | 

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------| 
| - |[rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commita9e8641.x86_64.rpm)|

### Status

- [x] In progress
- [x] Pending Review
- [ ] Team leader approved (@Rebits )
- [ ] QA team manager approved (@jmv74211)
- [ ] DEV team leader approved (@72nomada)


### Conclusion 🟢 

It has checked the `ruleset/sca` folder of the agents and it is empty as expected and, the /var/ossec/logs/ossec.log file doesn't show any errors related to SCA.

**Comment by fedepacher** [comment]
# Testing results :green_circle:

## Unfixed

<details><summary>Install unfixed package</summary>

  1. Install `wazuh-agent`
  2. Check Wazuh version

     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.3.9"
     WAZUH_REVISION="40322"
     WAZUH_TYPE="agent"
     ```

  3. Check `ruleset\sca` folder

      ```
      # ls /var/ossec/ruleset/sca/
      cis_rhel8_linux.yml
      ```
      
  4. Check `/var/ossec/logs/ossec.log` file for error, warning and SCA logs
   
      ```
      cat /var/ossec/logs/ossec.log | egrep -i "err|warn|Module started|No policies defined|sca"
      ```
      ```
      2022/11/04 15:24:43 sca: INFO: Module started.
      2022/11/04 15:24:43 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_rhel8_linux.yml'
      2022/11/04 15:24:43 sca: INFO: Starting Security Configuration Assessment scan.
      2022/11/04 15:24:43 sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_rhel8_linux.yml': 'Check RHEL8 family platform'
      2022/11/04 15:24:43 sca: INFO: Security Configuration Assessment scan finished. Duration: 0 seconds.
      ```

  </details>

## Upgrade

<details><summary>Upgrade process :green_circle:</summary>

  1. Upgrade `wazuh-agent` :green_circle:

     ```
     yum install wazuh-agent-4.4.0-0.commita9e8641.x86_64.rpm
     ```

     ```
     Upgraded:
       wazuh-agent-4.4.0-0.commita9e8641.x86_64 
     ```

  2. Check Wazuh version

     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.4.0"
     WAZUH_REVISION="40400"
     WAZUH_TYPE="agent"
     ```

  3. Check `ruleset\sca` folder

     ```
     # ls /var/ossec/ruleset/sca/
     # 
     ```
      
  4. Check `/var/ossec/logs/ossec.log` file for error, warning and SCA logs
   
     ```
     cat /var/ossec/logs/ossec.log | egrep -i "err|warn|Module started|No policies defined|sca"
     ```
     ```
     2022/11/04 15:32:24 sca: INFO: Module started.
     2022/11/04 15:32:24 sca: INFO: No policies defined. Exiting.

</details>

## Fresh install

<details><summary>Fresh install :green_circle:</summary>

  1. Check Wazuh version

     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.4.0"
     WAZUH_REVISION="40400"
     WAZUH_TYPE="agent"

     ```

  2. Check `ruleset\sca` folder

     ```
     # ls /var/ossec/ruleset/sca/
     # 
     ```
      
  3. Check `/var/ossec/logs/ossec.log` file for error, warning and SCA logs
   
     ```
     cat /var/ossec/logs/ossec.log | egrep -i "err|warn|Module started|No policies defined|sca"
     ```
     ```
     2022/11/04 14:21:31 sca: INFO: Module started.
     2022/11/04 14:21:31 sca: INFO: No policies defined. Exiting.
     ```

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
