### ISSUE TITLE
Detect an Audit Policy Change

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3407]
## Description

This problem aims to investigate [FIM Whodata: Detect an Audit Policy Change](https://github.com/wazuh/wazuh/issues/14507) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Research results

This development adds a new feature to FIM whodata monitoring, that detects Audit policy changes on Windows systems. 

When a folder is being monitored in Whodata mode, and the Audit policies for it change, the monitoring will be changed to realtime for the given folder without needing to restart the manager, showing the following messages:

```
2022/08/30 00:52:45 wazuh-agent[5656] win_whodata.c:1049 at state_checker(): ERROR: (6681): Audit policy change detected. Switching directories to realtime.
2022/08/30 00:52:45 wazuh-agent[5656] run_realtime.c:706 at realtime_adddir(): DEBUG: (6227): Directory added for real time monitoring: 'c:\test'
```

## Test support

Given this is a new feature, there is no automated test support for this. Currently there is test support for whodata monitoring on windows on the `tests/integration/test_fim` test suite.

## Define test cases

This cases are not base whodata cases. They are already covered in the `test_fim/test_files/test_basic_usage` test suite. The tests to be developed will be all Tier 2.

- IT test cases
   - Check that Windows FIM Whodata monitoring detects policy changes

## Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

The IT development will be handled in Issue #3414
