### ISSUE TITLE
Process to open ports in syscollector (Linux)

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3409]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0               | https://github.com/wazuh/wazuh/issues/3859                       |https://github.com/wazuh/wazuh/pull/15000                    |

## Description

 Increase the information provider by the `sys_ports` inventory by including process id and name

#### Ubuntu
- [ ] Check process id appears with default syscollector config (ports all="yes")
- [ ] Check process name appears with default syscollector config ports all="yes")
- [ ] Check process id appears with ports all="no" in  syscollector config
- [ ] Check process name appears with ports all="no" in syscollector config
- [ ] Check if the data of the process id or process name don't appear it's because it's NFS
- [ ] Modify process ports information and force a new scan and verify the changes are reflected in the inventory.

#### CentOS
- [ ] Check process id appears with default syscollector config (ports all="yes")
- [ ] Check process name appears with default syscollector config ports all="yes")
- [ ] Check process id appears with ports all="no" in  syscollector config
- [ ] Check process name appears with ports all="no" in syscollector config
- [ ] Check if the data of the process id or process name don't appear it's because it's NFS

#### Ubuntu
- [ ] Check process id appears with default syscollector config (ports all="yes")
- [ ] Check process name appears with default syscollector config ports all="yes")
- [ ] Check process id appears with ports all="no" in  syscollector config
- [ ] Check process name appears with ports all="no" in syscollector config
- [ ] Check if the data of the process id or process name don't appear it's because it's NFS

#### CentOS
- [ ] Check process id appears with default syscollector config (ports all="yes")
- [ ] Check process name appears with default syscollector config ports all="yes")
- [ ] Check process id appears with ports all="no" in  syscollector config
- [ ] Check process name appears with ports all="no" in syscollector config
- [ ] Check if the data of the process id or process name don't appear it's because it's NFS
- [ ] Modify process ports information and force a new scan and verify the changes are reflected in the inventory.

## Steps to reproduce

Execute `Syscollector` on any Linux distribution

Process and PID don't have any useful information

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/13010397/193681415-e3acec8a-8e9c-4430-bca6-f283f5acf93b.png)

</details>

## Expected results

We get some information that can be obtained by parsing the proc filesystem. NFS and overall services that rely on RPC don't have information easily parseable.

- Agent:
   Process name and process id are in /var/ossec/queue/syscollector/db/local.db

- Manager:
  Process name and process id are in /var/ossec/queue/syscollector/db/centos_agent.db or /var/ossec/queue/syscollector/db/ubuntu_agent.db

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/13010397/193681769-5e3cebe0-c9f3-4d61-a9c0-1e1f28c7bdb8.png)

</details>

## Configuration and considerations

Verify `Syscollector` ports scan is enabled.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
