### ISSUE TITLE
QA testing - Update protobuf dependency to 3.19.6

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#3410]
| Target version |Related PR |
|-------------------------------|---|
|  4.3.9  | TBD |

## Description
The protobuf dependency has been updated to version 3.19.6.

## Proposed checks

- [x] Fresh v4.3.9 install (manager only) in all methods (amd64, aarch64, sources with python compiling)
- [x] Upgrade from v4.3.X to v4.3.9 (manager only) using all methods (amd64, aarch64, sources with python compiling)
- [x] Test google cloud module basic behaviour

## Expected results
Wazuh should start and run OK, check the protobuf version in the embedded python is appropiate.

## Configuration and considerations
`DEPS_VERSION` in the Makefile has to be updated to 17-3996 to download the new deps for all testing purposes of this issue.

From Wazuh documentation, for the [sources installation](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/?highlight=python%20source#installing-the-wazuh-manager-from-sources).

`Optional. Install the following dependencies only when compiling the CPython from sources. Since v4.2.0, make deps TARGET=server will download a portable version of CPython ready to be installed. Nevertheless, you can download the CPython sources by adding the PYTHON_SOURCE flag when running make deps.`

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [a6372c0](https://github.com/wazuh/wazuh/pull/15067/commits/a6372c041eb8d24b0b628045a985d2a23911ebd7) | 

	

### Testing environment

| OS | OS version | Deployment | Image/AMI | Architecture | 
|-- |-- |-- |-- | --- |
| Ubuntu |  22 |  EC2 | `ami-003530de8839921c4` | amd64 |
| Ubuntu |  22 |  EC2 | `ami-003530de8839921c4` | arm |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @davidjiglesias

**Comment by Rebits** [comment]
## ARM :large_blue_circle: 

<details>


<summary> Fresh install  :green_circle:  </summary><blockquote> 

<details>

<summary>Installation details</summary> 


```
root@ip-172-31-3-56:/home/ubuntu/wazuh# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="server"
root@ip-172-31-3-56:/home/ubuntu/wazuh# /var/ossec/framework/python/bin/python3 -m pip freeze | grep proto
googleapis-common-protos==1.51.0
proto-plus==1.19.0
protobuf==3.19.6
root@ip-172-31-3-56:/home/ubuntu/wazuh# uname -m
aarch64
```

</details>



<details>

<summary>GCloud testing basic :green_circle:  </summary> 

For this task, we are going to use defined IT. These seems to work correctly for this case with slight


```
root@ip-172-31-3-56:~/wazuh-qa# python3 -m pytest tests/integration/test_gcloud/ --html=report.arm --ff -x
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /root/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: metadata-2.0.2, html-3.1.1, testinfra-5.0.0
collected 88 items                                                                                                                                                                                                
run-last-failure: rerun previous 3 failures first

tests/integration/test_gcloud/test_functionality/test_max_messages.py ...                        [  3%]
tests/integration/test_gcloud/test_configuration/test_invalid.py ...........................     [ 34%]
tests/integration/test_gcloud/test_configuration/test_remote_configuration.py ...                [ 37%]
tests/integration/test_gcloud/test_configuration/test_schedule.py .........                      [ 47%]
tests/integration/test_gcloud/test_functionality/test_day_wday.py .ssssss.ssssss.ssssss.ssssss.ssssss. [ 88%]
tests/integration/test_gcloud/test_functionality/test_interval.py ..                             [ 90%]
tests/integration/test_gcloud/test_functionality/test_logging.py .....                           [ 96%]
tests/integration/test_gcloud/test_functionality/test_pull_on_start.py ..                        [ 98%]
tests/integration/test_gcloud/test_functionality/test_rules.py .                                 [100%]

=========================================== warnings summary ===========================================
../../usr/local/lib/python3.10/dist-packages/google/pubsub_v1/services/publisher/client.py:19
  /usr/local/lib/python3.10/dist-packages/google/pubsub_v1/services/publisher/client.py:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils import util

test_gcloud/test_functionality/test_max_messages.py: 5 warnings
test_gcloud/test_functionality/test_logging.py: 5 warnings
test_gcloud/test_functionality/test_rules.py: 39 warnings
  /usr/local/lib/python3.10/dist-packages/urllib3/connection.py:407: DeprecationWarning: ssl.match_hostname() is deprecated
    match_hostname(cert, asserted_hostname)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
------------------------ generated html file: file:///root/wazuh-qa/report.arm -------------------------
======================= 58 passed, 30 skipped, 50 warnings in 581.05s (0:09:41) ========================

```

</details>






<details>


<summary>Upgrade 4.3.8 -> 4.3.9 :large_blue_circle:  </summary>


</blockquote>

</details>
</details>

**Comment by Rebits** [comment]
## AMD :large_blue_circle: 

<details>


<summary> Fresh install  :large_blue_circle:  </summary><blockquote> 

<details>

<summary>Installation details</summary> 




</details>



<details>

<summary>GCloud testing basic :green_circle:  </summary> 



</details>


</blockquote>

</details>

<details>


<summary>Upgrade 4.3.8 -> 4.3.9 :large_blue_circle:  </summary>


</blockquote>

</details>
