### ISSUE TITLE
WPK update in Fedora 33

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3416]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4.0             |  https://github.com/wazuh/wazuh/issues/14986                    |    Awaiting development                |

## Description
This development fixes WPK upgrade process for Fedora 33 agents. Testing needs to be done in order to verify it works properly.

## Proposed checks

- [ ] Update with WPK built from Sources

## Steps to reproduce

1. Install the 4.3.8-1 agent
2. Install 4.4.0 Manager
3. Build WPK (from sources/Jenkins)
4. Update agent with WPK file
5. Check agent has been properly updated
6. Check agent is working

## Expected results

Agent upgrades to 4.4.0 and works properly.

## Considerations

After the development is completed, determine if testing in other OSs (Windows and Linux) is needed

**Comment by damarisg** [comment]
Fixed at https://github.com/wazuh/wazuh-documentation/pull/5701 
**Note**: No testing required.
