### ISSUE TITLE
VDT partial scan detects vulnerabilites when Triaged value is NULL

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3421]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|    4.4.0            |  https://github.com/wazuh/wazuh/issues/14736 |  https://github.com/wazuh/wazuh/pull/14998 |

## Description

This development aims to fix vulnerability detection for packages that have no **triaged**  value  given by syscollector and it is read as NULL. This issue aims to do manual testing to verify it is working correctly.

## Proposed test cases

- [x] Insert package with Triaged = NULL and verify that alerts are generated

## Steps to reproduce

The steps to reproduce the behavior are as follows:

1. Apply the configuration to the manager:

```
<vulnerability-detector>
          <enabled>yes</enabled>
          <interval>2m</interval>
          <min_full_scan_interval>10s</min_full_scan_interval>
          <run_on_start>yes</run_on_start>

          <!-- Windows OS vulnerabilities -->
          <provider name="msu">
          <enabled>yes</enabled>
          <update_interval>1h</update_interval>
          </provider>

          <!-- Aggregate vulnerabilities -->
          <provider name="nvd">
          <enabled>yes</enabled>
          <update_from_year>2021</update_from_year>
          <update_interval>1h</update_interval>
          </provider>
</vulnerability-detector>
```

2. Set `wazuh-modules` in debug to have more information.

3. Restart the manager

4. Register a Windows agent with syscollector enabled.

5. Once the feeds are updated and have passed a vulnerability scan, install a vulnerable package. You can find the one to use [here](https://s3.amazonaws.com/ci.wazuh.com/qa/testing_files/end_to_end/vulnerability_detector/firefox_vulnerable_package.exe).

6. Check in the db for the agent that the triaged field is null - It is located in `sys_programs` table, the column after the package installation location. It is an empty column.
`
select * FROM sys_programs where name like  '%mozilla%';
0|2022/10/18 15:24:13|win|Mozilla Firefox (x64 en-US)||||Mozilla||92.0|x86_64||||C:\Program Files\Mozilla Firefox||.....
`
7. Wait for another scan and look for vulnerabilities related to the installed package
8. Check that the triaged field in the `sys_programs` table has been updated to `1` after the scan.
`
select * FROM sys_programs where name like  '%mozilla%';
0|2022/10/18 15:24:13|win|Mozilla Firefox (x64 en-US)||||Mozilla||92.0|x86_64||||C:\Program Files\Mozilla Firefox|1|.....
`
## Expected results
The package/s added should have vulnerability detected and alerts should be generated.

**Comment by Deblintrake09** [comment]
# Review Data

**Comment by Deblintrake09** [comment]
# Task Results

## Tests on 4.3.9-1
<details><summary>Check inserted package generates alerts on Windows</summary>
1. Install Manager and agent
2. Configure VDT
3. Install vulnerable package with Triaged=null
4. Start Agent and manager and wait for VDT scan
5. Check that alerts are generated
6. Check agent's db in manager
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work properly.
