### ISSUE TITLE
Add IT support for WPK upgrade from Sources

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3423]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|    4.4.0            |    https://github.com/wazuh/wazuh/issues/14986      |   pending development                 |

## Description
Currently our test suite supports testing WPK upgrade from packages, but does not test that it is supported the upgrade by building packages from Sources. Also Our current testing suite does not support systems like Fedora33 or ALAS2022, It is important that the support is added so we can properly test all the OSs that are in the documentation of our framework as supported.

## Proposed test cases

- [ ] Build WPK package from sources and upgrade successfuly.
- [ ] Add support for Fedora33 and ALAS2022.

## Considerations

This development request aims to verify that when building from sources the WPK packages. This could be handled either by IT or System tests.

**Comment by damarisg** [comment]
We decided to close them.
