### ISSUE TITLE
Fix control_service to work on non systemd OSs

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3425]
| Target version | Related issue | 
|--------------------|--------------------|
|     4.4.0           |   https://github.com/wazuh/wazuh-qa/issues/3261|

## Description

During testing done on Issue #3261, it was found that the IT tests failed because the `control_service` function used to stop/start/restart the wazuh application uses the `service` command it will fail with:
```
                else:
                    err_filename = orig_executable
                if errno_num != 0:
                    err_msg = os.strerror(errno_num)
>               raise child_exception_type(errno_num, err_msg, err_filename)
E               FileNotFoundError: [Errno 2] No such file or directory: 'service'
```
The error is caused by:

https://github.com/wazuh/wazuh-qa/blob/21595fe4a344bd3cd0c6e52a48c50767bc93a53d/deps/wazuh_testing/wazuh_testing/tools/services.py#L106

This should be fixed to enable the tests to run on systems that do not have `systemd` or `service`

## Expected results

The tests run properly on all current working systems, and can be run in Alpine Linux os and other systems that do not have the service command.

**Comment by mauromalara** [comment]
## Update


- I was trying to find an alternative to detect that the host is "Alpine" and I found this function very useful: https://docs.python.org/es/3/library/platform.html#platform.freedesktop_os_release
- In order to try the proposed alternative I started preparing an environment: 1 agent (Alpine) and 1 manager with Docker

**Comment by mauromalara** [comment]
## Update

- Yesterday I could run a Manager (Ubuntu) + Agent (Alpine) using Docker
- I had several issues while trying to install Python dependencies for `wazuh-qa` but I found that the required OS dependencies are:
  - Python (< 3.11)
  - gcc
  - libffi-dev
  - automake
  - g++
  - make
  - libressl-dev
  - musl-dev
  - openblas-dev
  - pkgconfig
  - gfortran
- I created a docker-compose file to automatically build the environment in any machine

**Comment by mauromalara** [comment]
## Update

- I modified some dependencies and added new ones (to the Agent's Dockerfile)
- Files required to build an environment with 1 manager and 1 agent (Alpine): [alpine_agent+manager.zip](https://github.com/wazuh/wazuh-qa/files/11600829/alpine_agent%2Bmanager.zip)

**Comment by mauromalara** [comment]
## Conclusion

I applied a different solution than the one proposed [here](https://github.com/wazuh/wazuh-qa/issues/3425#issuecomment-1562047977) because it was compatible with Python >3.10. I could not test the solution because there is a lot of issues with the dependencies and the version of Alpine.

**This should be checked and corrected if Alpine is automatized, but for now it will not be automatized.**

Here my proposed solution:

```Python
# deps/wazuh_testing/wazuh_testing/tools/utils.py
def get_os_id():
    """Get OS identification from the os-release file as a dict.

    Returns:
        release_info (dict): OS ID information.
    """
    release_info = {}
    with open('/etc/os-release', 'r') as f:
        for line in f.readlines():
            if line != '':
                key,value = line.split('=')
                value = value.rstrip().replace('"', '')
                release_info[key] = value

    return release_info
```


```Python
# deps/wazuh_testing/wazuh_testing/tools/services.py

from wazuh_testing.tools.utils import get_os_id
.
.
def control_service(action, daemon=None, debug_mode=False):
    .
    .
    else:  # Default Unix
        if daemon is None:
            if sys.platform == 'darwin' or sys.platform == 'sunos5' or get_os_id()['ID'] == 'alpine':
                result = subprocess.run([f'{WAZUH_PATH}/bin/wazuh-control', action]).returncode
            else:
                result = subprocess.run(['service', get_service(), action]).returncode
            action == 'stop' and delete_sockets()
    .
    .
```
