### ISSUE TITLE
 Get `force_reconnect` response

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3426]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.5    | [#14797](https://github.com/wazuh/wazuh/issues/14797) |             |

## Description

This issue implement a response to the `force_reconnect` request that lets the framework know to which agents a reconnection request has actually been sent after 

## Proposed checks

> This [testing socket client](https://github.com/wazuh/wazuh-qa/files/9923851/socket_client.zip) could help the testing process

- [ ] A socket message should be received from the agent
    
    <details><summary>Test cases</summary>

    - <details><summary>Send the request <code>force_reconnect</code> to a connected agent</summary>

        1. Install a `wazuh-manager` 
        2. Install a `wazuh-agent` and connect it to the `wazuh-manager` 
        3. Using the test socket client send the `force_reconnect` message
        4. Check an `ack` message is received in the socket client from `wazuh-agent`  
        5. Check the `wazuh-agent` gets reconnected
            ```bash
            watch -n 1 /var/ossec/bin/agent_control -l
            ```
        </details>

    - <details><summary>Send the request <code>force_reconnect</code> to a correctly disconnected agent</summary>

        1. Install a `wazuh-manager` 
        2. Install a `wazuh-agent`, connect it to the `wazuh-manager` and gracefully stop it
            > It should be deactivate "naturally" by running `systemctl stop wazuh-agent`
        3. Using the test socket client send the `force_reconnect` message
        4. Check there is no ERROR raised in the logs
            > As the manager sees the agent deactivated it wont do anything.
        </details>

    - <details><summary>Send the request <code>force_reconnect</code> to a suddenly disconnected agent</summary>

        1. Install a `wazuh-manager` 
        2. Install a `wazuh-agent`, connect it to the `wazuh-manager` and turn off the agent's system
            > If its on a VM just force turn off the machine, so the manager "wont know" that the agent is offline 
        3. Using the test socket client send the `force_reconnect` message
        4. Check an ERROR raised in the logs
            ```bash
            grep "ERROR" /var/ossec/logs/ossec.log
            ```
        5. Check the socket client receives an error message (`err Cannot send request`)
        </details>
    </details>

### Required installation methods
- [ ] Fresh install
- [ ] Upgrade
 
## Expected results

The framework should receive a response that lets it know which agent has an reconnection request

**Comment by QU3B1M** [comment]
This issue will remain on hold. Core will redesign the implementation to improve solution performance.

**Comment by TomasTurina** [comment]
Won't do.
