### ISSUE TITLE
Unstable GCloud test_day_wday 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3428]
| Version | Commit | Report
| --- | --- | --- |
| 4.5.0 | 240ea86 | [manager_html_report_Test_integration_B32602_20221008004911.zip](https://github.com/wazuh/wazuh-qa/files/9744016/manager_html_report_Test_integration_B32602_20221008004911.zip)
 | 
### Description
GCloud `test_day_wday_multiple` recently fails for `v4.5`
```
=================================== FAILURES ===================================
__________ test_day_wday_multiple[get_configuration4-tags_to_apply1] ___________
test_gcloud/test_functionality/test_day_wday.py:278: in test_day_wday_multiple
    assert next_scan_time.day == (today + datetime.timedelta(weeks=time_interval)).day
E   assert 14 == 28
E     +14
E     -28
__________ test_day_wday_multiple[get_configuration5-tags_to_apply2] ___________
test_gcloud/test_functionality/test_day_wday.py:281: in test_day_wday_multiple
    assert next_scan_time.day == (today + datetime.timedelta(days=time_interval)).day
E   assert 12 == 11
E     +12
E     -11
- generated html file: file:///tmp/Test_integration_B32602_20221008004911/report.html -
=========================== short test summary info ============================
FAILED test_gcloud/test_functionality/test_day_wday.py::test_day_wday_multiple[get_configuration4-tags_to_apply1]
FAILED test_gcloud/test_functionality/test_day_wday.py::test_day_wday_multiple[get_configuration5-tags_to_apply2]
============= 2 failed, 52 passed, 30 skipped in 629.27s (0:10:29) =============
```

**Comment by fedepacher** [comment]
# Update 2022/10/25


Based on the analysis of the test and the `ossec.log` file provided by the Jenkins environment, the following conclusion has been achieved:

### test_gcloud/test_functionality/test_day_wday.py::test_day_wday_multiple[get_configuration5-tags_to_apply2]

#### Error 

```
test_gcloud/test_functionality/test_day_wday.py:281: in test_day_wday_multiple
    assert next_scan_time.day == (today + datetime.timedelta(days=time_interval)).day
E   assert 12 == 11
E     +12
E     -11
```

#### ossec.conf

```
<gcp-pubsub>
    <project_id>wazuh-dev-258815</project_id>
    <subscription_name>qa_integration_tests-sub</subscription_name>
    <credentials_file>gcp_credentials.json</credentials_file>
    <max_messages>100</max_messages>
    <interval>4d</interval>
  </gcp-pubsub>
```

#### Conclusion

The `test_day_wday_multiple` gets the following message of the `ossec.log` to proceed with the test:

```
2022/10/08 00:02:32 wazuh-modulesd:gcp-pubsub[14363] wm_gcp.c:141 at wm_gcp_pubsub_main(): DEBUG: Sleeping until: 2022/10/12 00:02:12
```

Before being executed, the test gets the following value:

```
today = datetime.date.today() = 2022/10/07
day = today.day = 7
```

That means, this test depends on the time and date to pass successfuly.
In this case, if we check the log timestamp `2022/10/08 00:02:32` it can conclude that the test got the variables `today` and `day` the previous day, 2022/10/07 (note that the execution time is `00:02:32` and the test waits more than 60 seconds to get the log).

```
next_scan_time_log = wazuh_log_monitor.start(timeout=global_parameters.default_timeout + 60,
                                             callback=callback_detect_start_gcp_sleep,
                                             error_message='Did not receive expected '
                                             '"Sleeping until ..." event').result()
```

Once the test was executed, the `day` had already changed to `2022/10/08` making the following sentence fail:

```
assert next_scan_time.day == (today + datetime.timedelta(days=time_interval)).day
```

Where `next_scan_time.day` = 12 and `(today = 7 + datetime.timedelta(days=time_interval) = 4)` = 11


#### Possible solution

Before starting the test, create a fixture to change the machine time.

**Comment by fedepacher** [comment]
# Update 2022/10/26


### test_gcloud/test_functionality/test_day_wday.py::test_day_wday_multiple[get_configuration0-tags_to_apply0]

This test depends on the execution date and time to pass. The following error is achieved when the test executes at 23:59 at night.

#### Error

```
__________ test_day_wday_multiple[get_configuration4-tags_to_apply1] ___________
test_gcloud/test_functionality/test_day_wday.py:278: in test_day_wday_multiple
    assert next_scan_time.day == (today + datetime.timedelta(weeks=time_interval)).day
E   assert 14 == 28
E     +14
E     -28
```


#### ossec.conf

```
<gcp-pubsub>
  <project_id>wazuh-dev-258815</project_id>
  <subscription_name>qa_integration_tests-sub</subscription_name>
  <credentials_file>gcp_credentials.json</credentials_file>
  <wday>Friday</wday>
  <interval>3w</interval>
  <max_messages>100</max_messages>
</gcp-pubsub>

```

#### Conclusion

This test gets the following variables that depend on the date and time before test cases execution:

```
weekDays = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
today = datetime.date.today()
day = today.day
wday = weekDays[today.weekday()]
```

If those variables are got at 23:59 and the test cases execute after that date, the date will be changed and the test will fail.

The log message that it will get is the following:

```
2022/10/08 00:00:29 wazuh-modulesd:gcp-pubsub[51583] wm_gcp.c:141 at wm_gcp_pubsub_main(): DEBUG: Sleeping until: 2022/10/14 00:00:00
```

But, as the `ossec.conf` file is configured with `<interval>3w</interval>`, the following log would be the right one:

```
2022/10/08 00:00:29 wazuh-modulesd:gcp-pubsub[51583] wm_gcp.c:141 at wm_gcp_pubsub_main(): DEBUG: Sleeping until: 2022/10/29 00:00:00
```

Note that the date of sleeping time in the first case is `2022/10/14` and the date of the log is `2022/10/08`, this means that just only 6 days will be sleep but it should be 21 days (3w as it was configured).



### Step to reproduce

Modify the test `test_day_wday.py` and add a `sleep(60)` after the global variables get their values and before the test cases execution. 
Before running the test, modify the date and time of the environment where the test will be launched. To do so run:

```
date --set="Fri Oct 07 23:59:10 CST 2022"
```

Check the date with the following command:

```
date
```
You will get the following output:

```
Fri Oct  7 23:59:17 UTC 2022
```

Run the test as follow:

```
python3 -m pytest -svx tests/integration/test_gcloud/test_functionality/test_day_wday.py
```

**Comment by jmv74211** [comment]
The tests have been set to `xfailed` and this issue [wazuh#15255](https://github.com/wazuh/wazuh/issues/15255) has been opened in `wazuh/wazuh` to report the bug.
