### ISSUE TITLE
Ubuntu Linux 20.04 SCA Policy rework - checks 1.2 to 1.5.4

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3432]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.0               |         #3391               |         https://github.com/wazuh/wazuh/pull/15070           |

|Check ID | Check Name | implemented | Ready for review | QA review |
|---|---|---|---|---|
|1.2 | Configure Software Updates  | ⚫  | |  |
|1.2.1 | Ensure package manager repositories are configured (Manual)  | 🔴  |Not implemented |  |
|1.2.2 | Ensure GPG keys are configured (Manual)  | 🔴  | Not implemented |  |
|1.3 | Filesystem Integrity Checking | ⚫   | |  |
|1.3.1 | Ensure AIDE is installed (Automated)  | 🟢  | 🟢 |  |
|1.3.2 | Ensure filesystem integrity is regularly checked (Automated)  | 🟢  | 🟢 |  |
|1.4 | Secure Boot Settings  |🟢  | 🟢 |  |
|1.4.1 | Ensure permissions on bootloader config are not overridden (Automated) | 🟢  | 🟢 |  |
|1.4.2 | Ensure bootloader password is set (Automated) |🟢   | 🟢 |  |
|1.4.3 | Ensure permissions on bootloader config are configured (Automated) | 🟢  |🟢  |  |
|1.4.4 | Ensure authentication required for single user mode (Automated)  | 🟢  | 🟢 |  |
|1.5 | Additional Process Hardening  | ⚫   | |  |
|1.5.1 | Ensure XD/NX support is enabled (Manual) | 🟢  | 🟢 |  |
|1.5.2 | Ensure address space layout randomization (ASLR) is enabled (Automated)  | 🟢  |🟢  |  |
|1.5.3 | Ensure prelink is not installed (Automated) | 🟢  | 🟢 |  |
|1.5.4 | Ensure core dumps are restricted (Automated) | 🟢  | 🟢 |  |

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/15070/commits/d3dea11fd25d566efce58731170b9d90f17dee0f |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | Vagrant |    qactl/ubuntu_20_04     |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3431.sca_amd64.deb)    |   

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion


<details>
<summary>Results summary</summary>
<br>

|**Check ID**| **ID** | **Title** | **Description**|**Rationale**|**Remediation**|**Compliance**|**Rules**|**Expected scan result**|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|1.3.1|  |   |    |   |    |   |   | |
|1.3.2|   |    |    |   |    |   |   | |
|1.4|   |    |    |   |    |   |   | |
|1.4.1|   |    |    |   |    |   |   | |
|1.4.2|   |    |    |   |    |   |   | |
|1.4.3|   |    |    |   |    |   |   | |
|1.4.4|   |    |    |   |    |   |   | |
|1.5.1|   |    |    |   |    |   |   | |
|1.5.2|   |    |    |   |    |   |   | |
|1.5.3|   |    |    |   |    |   |   | |
|1.5.4|   |    |    |   |    |   |   | |

</details>

**Comment by juliamagan** [comment]
## Testing results

### Checks

<details>
<summary> 1.3.1 Ensure AIDE is installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :yellow_circle:
    The command to initialize AIDE is different
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>

<details>
<summary> 1.3.2 Ensure filesystem integrity is regularly checked (Automated) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :red_circle:
    ```
    - "c:systemctl is-enabled aidecheck.enabled -> r:enabled"
    - "c:systemctl status aidecheck.enabled -> r:Active: active"
    ```
    These rules are incorrect, it should be `aidecheck.timer`. This error causes the check to always pass. In addition, the first three rules and the last three should be satisfied at the same time (between them), but having the `any` condition, as soon as one passes, the rest will not be checked.
- **Expected scan result**: `FAIL` -> :red_circle:

</details>

<details>
<summary> 1.4.1 Ensure permissions on bootloader config are not overridden (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :yellow_circle:
    
    Command output:
    ```
    if [ "x${grub_cfg}" != "x" ] && ! grep "^password" ${grub_cfg}.new >/dev/null; then
        chmod 444 ${grub_cfg}.new || true
    fi
    ```
    It fails due to `&& ! grep "^password" ${grub_cfg}.new >/dev/null`

</details>
<details>
<summary> 1.4.2 Ensure bootloader password is set (Automated) </summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: 

</details>
<details>
<summary> 1.4.4 Ensure authentication required for single user mode (Automated) </summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**:

</details>
<details>
<summary> 1.5.1 Ensure XD/NX support is enabled (Manual) </summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: 

</details>
<details>
<summary> 1.5.2 Ensure address space layout randomization (ASLR) is enabled (Automated)  </summary>
<br>

- **id**: :
- **title**: 
- **description**: 
- **rationale**: 
- impact: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: 

</details>
<details>
<summary> 1.5.3 Ensure prelink is not installed (Automated)  </summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: 

</details>
<details>
<summary> 1.5.4 Ensure core dumps are restricted (Automated) </summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: 

</details>

### Deployment

<details>
<summary>If the policy it's new, it must be added to the <code>sca.files</code> templates :green_circle:</summary>
<br>

This policy isn't new. It is present in the `sca.files` templates:

https://github.com/wazuh/wazuh/blob/d3dea11fd25d566efce58731170b9d90f17dee0f/etc/templates/config/ubuntu/20/04/sca.files#L1
</details>

<details>
<summary>If the OS has many supported SCA policies, a policy must be set as the default policy :green_circle:</summary>
<br>
https://github.com/wazuh/wazuh/blob/a3ec35d13bbc5e3fa7c08a368a493191b219a118/etc/templates/config/ubuntu/sca.files#L1
</details>

### Documentation

<details>
<summary>Documentation SCA list includes the created or updated SCA :green_circle:</summary>
<br>

Verified in the `4.4` branch of https://github.com/wazuh/wazuh-documentation/. The file can be found [here](https://github.com/wazuh/wazuh-documentation/blob/4.4/source/user-manual/capabilities/sec-config-assessment/how-to-configure.rst).

</details>

**Comment by 72nomada** [comment]
check - 1.4.1 

- The command ```&& ! grep "^password" ${grub_cfg}.new >/dev/null``` must not be in the file to pass, the password check is set by default and must be removed as part of the remedition.

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15070/commits/d5a0c2fee3a0dbe3d70106f61fff3cbbd28ced46

***

### Results


<details>
<summary> 1.3.1 Ensure AIDE is installed (Automated) :green_circle:</summary>
<br>

- **remediation**: :green_circle:
- **compliance**: :green_circle:

</details>

<details>
<summary> 1.3.2 Ensure filesystem integrity is regularly checked (Automated) :yellow_circle:</summary>
<br>

- **compliance**: :green_circle:
- **rules**: :yellow_circle:
    The first three rules and the last three should be satisfied at the same time (between them), but having the `any` condition, as soon as one passes, the rest will not be checked.
- **Expected scan result**: `FAIL` -> :green_circle:

</details>

<details>
<summary> 1.4.1 Ensure permissions on bootloader config are not overridden (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:
    

</details>
<details>
<summary> 1.4.2 Ensure bootloader password is set (Automated) :yellow_circle:</summary>
<br>

- **compliance**: :yellow_circle:
    `pci_dss_v3.2.1: ["2,2"]` should be `"2.2"`

</details>
<details>
<summary> 1.4.3 Ensure permissions on bootloader config are configured (Automated) :yellow_circle:</summary>
<br>

- **compliance**: :yellow_circle:
    `pci_dss_v3.2.1: ["2,2"]` should be `"2.2"`

</details>
<details>
<summary> 1.4.4 Ensure authentication required for single user mode (Automated) :yellow_circle:</summary>
<br>

- **compliance**: :yellow_circle:
    `pci_dss_v3.2.1: ["2,2"]` should be `"2.2"`

</details>
<details>
<summary> 1.5.1 Ensure XD/NX support is enabled (Manual) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 1.5.2 Ensure address space layout randomization (ASLR) is enabled (Automated) :red_circle:</summary>
<br>

- **remediation**: :yellow_circle: -> Not fixed
    Extra blank spaces between regex
- **compliance**: :green_circle:
- **rules**: :yellow_circle:
    Why are the rules negated now?
- **Expected scan result**: `PASS` -> :red_circle:

</details>
<details>
<summary> 1.5.3 Ensure prelink is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 1.5.4 Ensure core dumps are restricted (Automated) :yellow_circle:</summary>
<br>

- **compliance**: :yellow_circle:
    `pci_dss_v3.2.1: ["2,2"]` should be `"2.2"`
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15070/commits/7a273d56b6acfba2f9941450301de452525961f9

***

### Results



<details>
<summary> 1.3.2 Ensure filesystem integrity is regularly checked (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:
   


</details>



<details>
<summary> 1.4.2 Ensure bootloader password is set (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 1.4.3 Ensure permissions on bootloader config are configured (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 1.4.4 Ensure authentication required for single user mode (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>

<details>
<summary> 1.5.2 Ensure address space layout randomization (ASLR) is enabled (Automated) :green_circle:</summary>
<br>

- **remediation**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>

<details>
<summary> 1.5.4 Ensure core dumps are restricted (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>


## Conclusion :green_circle:

Everything has been fixed
