### ISSUE TITLE
Ubuntu Linux 20.04 SCA Policy rework - checks 2 to 2.3

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3434]
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          | #3391         | https://github.com/wazuh/wazuh/pull/15070 |

| Check ID | Check Name                                                               | implemented | Ready for review | QA review |
| -------- | ------------------------------------------------------------------------ | ----------- | ---------------- | --------- |
| 2        | Services                                                                 | ⚫           |                  |           |
| 2.1      | Special Purpose Services                                                 | ⚫           |                  |           |
| 2.1.1    | Time Synchronization                                                     | ⚫           |                  |           |
| 2.1.1.1  | Ensure time synchronization is in use (Automated)                        | 🟢           | 🟢                |           |
| 2.1.1.2  | Ensure systemd-timesyncd is configured (Automated)                       | 🟢           | 🟢                |           |
| 2.1.1.3  | Ensure chrony is configured (Automated)                                  | 🟢           | 🟢                |           |
| 2.1.1.4  | Ensure ntp is configured (Automated)                                     | 🟢           | 🟢                |           |
| 2.1.2    | Ensure X Window System is not installed (Automated)                      | 🟢           | 🟢                |           |
| 2.1.3    | Ensure Avahi Server is not installed (Automated)                         | 🟢           | 🟢                |           |
| 2.1.4    | Ensure CUPS is not installed (Automated)                                 | 🟢           | 🟢                |           |
| 2.1.5    | Ensure DHCP Server is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.1.6    | Ensure LDAP server is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.1.7    | Ensure NFS is not installed (Automated)                                  | 🟢           | 🟢                |           |
| 2.1.8    | Ensure DNS Server is not installed (Automated)                           | 🟢           | 🟢                |           |
| 2.1.9    | Ensure FTP Server is not installed (Automated)                           | 🟢           | 🟢                |           |
| 2.1.10   | Ensure HTTP server is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.1.11   | Ensure IMAP and POP3 server are not installed (Automated)                | 🟢           | 🟢                |           |
| 2.1.12   | Ensure Samba is not installed (Automated)                                | 🟢           | 🟢                |           |
| 2.1.13   | Ensure HTTP Proxy Server is not installed (Automated)                    | 🟢           | 🟢                |           |
| 2.1.14   | Ensure SNMP Server is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.1.15   | Ensure mail transfer agent is configured for local-only mode (Automated) | 🟢           | 🟢                |           |
| 2.1.16   | Ensure rsync service is not installed (Automated)                        | 🟢           | 🟢                |           |
| 2.1.17   | Ensure NIS Server is not installed (Automated)                           | 🟢           | 🟢                |           |
| 2.2      | Service Clients                                                          | ⚫           |                  |           |
| 2.2.1    | Ensure NIS Client is not installed (Automated)                           | 🟢           | 🟢                |           |
| 2.2.2    | Ensure rsh client is not installed (Automated)                           | 🟢           | 🟢                |           |
| 2.2.3    | Ensure talk client is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.2.4    | Ensure telnet client is not installed (Automated)                        | 🟢           | 🟢                |           |
| 2.2.5    | Ensure LDAP client is not installed (Automated)                          | 🟢           | 🟢                |           |
| 2.2.6    | Ensure RPC is not installed (Automated)                                  | 🟢           | 🟢                |           |
| 2.3      | Ensure nonessential services are removed or masked (Manual)              | 🔴           | Not implemented  |           |

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/15070/commits/e41608c613efc3b6a80c88ded56cfa6c2bd392ca |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | Vagrant |    qactl/ubuntu_20_04     |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3431.sca_amd64.deb)    |   

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion 

<details>
<summary>Results summary</summary>
<br>

|**Check ID**| **ID** | **Title** | **Description**|**Rationale**|**Remediation**|**Compliance**|**Rules**|**Expected scan result**|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|2.1.1.1|   |   |   |  |   |  |  ||
|2.1.1.2|   |   |   |  |   |  |  ||
|2.1.1.3|   |   |   |  |   |  |  ||
|2.1.1.4|   |   |   |  |   |  |  ||
|2.1.2|   |   |   |  |   |  |  ||
|2.1.3|   |   |   |  |   |  |  ||
|2.1.4|   |   |   |  |   |  |  ||
|2.1.5|   |   |   |  |   |  |  ||
|2.1.6|   |   |   |  |   |  |  ||
|2.1.7|   |   |   |  |   |  |  ||
|2.1.8|   |   |   |  |   |  |  ||
|2.1.9|   |   |   |  |   |  |  ||
|2.1.10|   |   |   |  |   |  |  ||
|2.1.11|   |   |   |  |   |  |  ||
|2.1.12|   |   |   |  |   |  |  ||
|2.1.13|   |   |   |  |   |  |  ||
|2.1.14|   |   |   |  |   |  |  ||
|2.1.15|   |   |   |  |   |  |  ||
|2.1.16|   |   |   |  |   |  |  ||
|2.1.17|   |   |   |  |   |  |  ||
|2.2.1|   |   |   |  |   |  |  ||
|2.2.2|   |   |   |  |   |  |  ||
|2.2.3|   |   |   |  |   |  |  ||
|2.2.4|   |   |   |  |   |  |  ||
|2.2.5|   |   |   |  |   |  |  ||
|2.2.6|   |   |   |  |   |  |  ||

</details>

**Comment by juliamagan** [comment]
## Testing results

### Checks

<details>
<summary> 2.1.1.1 Ensure time synchronization is in use (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>

<details>
<summary> 2.1.1.2 Ensure systemd-timesyncd is configured (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :yellow_circle:
    Missing rules for `/etc/systemd/timesyncd.conf` and `timedatectl status`
- **Expected scan result**: `PASS` -> :yellow_circle:

</details>
<details>
<summary> 2.1.1.3 Ensure chrony is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 2.1.1.4 Ensure ntp is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 2.1.2 Ensure X Window System is not installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :yellow_circle:
    Extra `core` in command
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 2.1.3 Ensure Avahi Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 2.1.4 Ensure CUPS is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.5 Ensure DHCP Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.6 Ensure LDAP server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>

<details>
<summary> 2.1.7 Ensure NFS is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.8 Ensure DNS Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:


</details>
<details>
<summary> 2.1.9 Ensure FTP Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:


</details>
<details>
<summary> 2.1.10 Ensure HTTP server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.11 Ensure IMAP and POP3 server are not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.12 Ensure Samba is not installed (Automated) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :red_circle:
    Missing `rules`
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.13 Ensure HTTP Proxy Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.14 Ensure SNMP Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:


</details>
<details>
<summary> 2.1.15 Ensure mail transfer agent is configured for local-only mode (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.1.16 Ensure rsync service is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 2.1.17 Ensure NIS Server is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 2.2.1 Ensure NIS Client is not installed (Automated) :green_circle:</summary>
<br>



- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle: 

</details>
<details>
<summary> 2.2.2 Ensure rsh client is not installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle: 

</details>
<details>
<summary> 2.2.3 Ensure talk client is not installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle: 

</details>
<details>
<summary> 2.2.4 Ensure telnet client is not installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle: 

</details>
<details>
<summary> 2.2.5 Ensure LDAP client is not installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle: 

</details>

<details>
<summary> 2.2.6 Ensure RPC is not installed (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :yellow_circle:
    `mitre_techniques` doesn't follow the format
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle: 

</details>

### Deployment

<details>
<summary>If the policy it's new, it must be added to the <code>sca.files</code> templates :green_circle:</summary>
<br>

This policy isn't new. It is present in the `sca.files` templates:

https://github.com/wazuh/wazuh/blob/d3dea11fd25d566efce58731170b9d90f17dee0f/etc/templates/config/ubuntu/20/04/sca.files#L1
</details>

<details>
<summary>If the OS has many supported SCA policies, a policy must be set as the default policy :green_circle:</summary>
<br>
https://github.com/wazuh/wazuh/blob/a3ec35d13bbc5e3fa7c08a368a493191b219a118/etc/templates/config/ubuntu/sca.files#L1
</details>

### Documentation

<details>
<summary>Documentation SCA list includes the created or updated SCA :green_circle:</summary>
<br>

Verified in the `4.4` branch of [wazuh/wazuh-documentation](https://github.com/wazuh/wazuh-documentation/). The file can be found [here](https://github.com/wazuh/wazuh-documentation/blob/4.4/source/user-manual/capabilities/sec-config-assessment/how-to-configure.rst).

![image](https://user-images.githubusercontent.com/80041853/196181479-8dc60c6b-1c91-4ef6-a06f-b0baa39eda32.png)


</details>

**Comment by 72nomada** [comment]
- 2.1.1.2 - Rule for /etc/systemd/timesyncd.conf and timedatectl status need manual work. can't be implemented
- 2.1.2 - Solved
- 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.2.6
  Can't find the issue. sometimes array will come with a comma as the last char, and in others, no. 
- 2.1.12 - Solved

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15070/commits/0e46f9463e19ea64607717153baad01561a3f9e4


***

### Results


<details>
<summary> 2.1.1.2 Ensure systemd-timesyncd is configured (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>


<details>
<summary> 2.1.2 Ensure X Window System is not installed (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:

</details>
<details>
<summary> 2.1.3 Ensure Avahi Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:


</details>
<details>
<summary> 2.1.4 Ensure CUPS is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.5 Ensure DHCP Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.6 Ensure LDAP server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>

<details>
<summary> 2.1.7 Ensure NFS is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.8 Ensure DNS Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:


</details>
<details>
<summary> 2.1.9 Ensure FTP Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:


</details>
<details>
<summary> 2.1.10 Ensure HTTP server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.11 Ensure IMAP and POP3 server are not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.12 Ensure Samba is not installed (Automated) :green_circle:</summary>
<br>


- **compliance**: :green_circle:
- **rules**: :green_circle:

</details>
<details>
<summary> 2.1.13 Ensure HTTP Proxy Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.14 Ensure SNMP Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:


</details>
<details>
<summary> 2.1.15 Ensure mail transfer agent is configured for local-only mode (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.16 Ensure rsync service is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>
<details>
<summary> 2.1.17 Ensure NIS Server is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:
</details>



<details>
<summary> 2.2.6 Ensure RPC is not installed (Automated) :green_circle:</summary>
<br>

- **compliance**: :green_circle:

</details>



## Conclusion :green_circle:

Everything has been fixed

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly after the proposed fixes. Thank you @juliamagan
