### ISSUE TITLE
Ubuntu Linux 20.04 SCA Policy rework - checks 3.5 to 3.5.3.3.4

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3436]
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          | #3391         | https://github.com/wazuh/wazuh/pull/15070 |

| Check ID  | Check Name                                                                    | implemented | Ready for review | QA review |
| --------- | ----------------------------------------------------------------------------- | ----------- | ---------------- | --------- |
| 3.5       | Firewall Configuration                                                        | ⚫           |                  |           |
| 3.5.1     | Configure UncomplicatedFirewall                                               | ⚫           |                  |           |
| 3.5.1.1   | Ensure ufw is installed (Automated)                                           | 🟢           | 🟢                |           |
| 3.5.1.2   | Ensure iptables-persistent is not installed with ufw (Automated)              | 🟢           | 🟢                |           |
| 3.5.1.3   | Ensure ufw service is enabled (Automated)                                     | 🟢           | 🟢                |           |
| 3.5.1.4   | Ensure ufw loopback traffic is configured (Automated)                         | 🟢           | 🟢                |           |
| 3.5.1.5   | Ensure ufw outbound connections are configured (Manual)                       | 🔴           | Not implemented  |           |
| 3.5.1.6   | Ensure ufw firewall rules exist for all open ports (Manual)                   | 🔴           | Not implemented  |           |
| 3.5.1.7   | Ensure ufw default deny firewall policy (Automated)                           | 🟢           | 🟢                |           |
| 3.5.2     | Configure nftables                                                            | ⚫           |                  |           |
| 3.5.2.1   | Ensure nftables is installed (Automated)                                      | 🟢           | 🟢                |           |
| 3.5.2.2   | Ensure ufw is uninstalled or disabled with nftables (Automated)               | 🟢           | 🟢                |           |
| 3.5.2.3   | Ensure iptables are flushed with nftables (Manual)                            | 🟢           | 🟢                |           |
| 3.5.2.4   | Ensure a nftables table exists (Automated)                                    | 🟢           | 🟢                |           |
| 3.5.2.5   | Ensure nftables base chains exist (Automated)                                 | 🟢           | 🟢                |           |
| 3.5.2.6   | Ensure nftables loopback traffic is configured (Automated)                    | 🟢           | 🟢                |           |
| 3.5.2.7   | Ensure nftables outbound and established connections are configured (Manual)  | 🔴           | Not implemented  |           |
| 3.5.2.8   | Ensure nftables default deny firewall policy (Automated)                      | 🟢           | 🟢                |           |
| 3.5.2.9   | Ensure nftables service is enabled (Automated)                                | 🟢           | 🟢                |           |
| 3.5.2.10  | Ensure nftables rules are permanent (Automated)                               | 🔴           | Not implemented  |           |
| 3.5.3     | Configure iptables                                                            | ⚫           |                  |           |
| 3.5.3.1.1 | Ensure iptables packages are installed (Automated)                            | 🟢           | 🟢                |           |
| 3.5.3.1.2 | Ensure nftables is not installed with iptables (Automated)                    | 🟢           | 🟢                |           |
| 3.5.3.1.3 | Ensure ufw is uninstalled or disabled with iptables (Automated)               | 🟢           | 🟢                |           |
| 3.5.3.2.1 | Ensure iptables loopback traffic is configured (Automated)                    | 🟢           | 🟢                |           |
| 3.5.3.2.2 | Ensure iptables outbound and established connections are configured (Manual)  | 🔴           | Not implemented  |           |
| 3.5.3.2.3 | Ensure iptables default deny firewall policy (Automated)                      | 🟢           | 🟢                |           |
| 3.5.3.2.4 | Ensure iptables firewall rules exist for all open ports (Automated)           | 🔴           | Not implemented  |           |
| 3.5.3.3.1 | Ensure ip6tables loopback traffic is configured (Automated)                   | 🟢           | 🟢                |           |
| 3.5.3.3.2 | Ensure ip6tables outbound and established connections are configured (Manual) | 🔴           | Not implemented  |           |
| 3.5.3.3.3 | Ensure ip6tables default deny firewall policy (Automated)                     | 🟢           | 🟢                |           |
| 3.5.3.3.4 | Ensure ip6tables firewall rules exist for all open ports (Automated)          | 🔴           | Not implemented  |           |

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/15070/commits/e6d1b80690de4beb5a4d87167aa3107c9d7c3b6e|

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | Vagrant |    qactl/ubuntu_20_04     |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3431.sca_amd64.deb)    |   

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion 


<details>
<summary>Results summary</summary>
<br>

|**Check ID**| **ID** | **Title** | **Description**|**Rationale**|**Remediation**|**Compliance**|**Rules**|**Expected scan result**|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|3.5.1.1|   |   |   |  |   |  |  |   |
|3.5.1.2|   |   |   |  |   |  |  |   |
|3.5.1.3|   |   |   |  |   |  |  |   |
|3.5.1.4|   |   |   |  |   |  |  |   |
|3.5.1.7|   |   |   |  |   |  |  |   |
|3.5.2.1|   |   |   |  |   |  |  |   |
|3.5.2.2|   |   |   |  |   |  |  |   |
|3.5.2.3|   |   |   |  |   |  |  |   |
|3.5.2.4|   |   |   |  |   |  |  |   |
|3.5.2.5|   |   |   |  |   |  |  |   |
|3.5.2.6|   |   |   |  |   |  |  |   |
|3.5.2.8|   |   |   |  |   |  |  |   |
|3.5.2.9|   |   |   |  |   |  |  |   |
|3.5.3.1.1|   |   |   |  |   |  |  |   |
|3.5.3.1.2|   |   |   |  |   |  |  |   |
|3.5.3.1.3|   |   |   |  |   |  |  |   |
|3.5.3.2.1|   |   |   |  |   |  |  |   |
|3.5.3.2.3|   |   |   |  |   |  |  |   |
|3.5.3.3.1|   |   |   |  |   |  |  |   |
|3.5.3.3.3|   |   |   |  |   |  |  |   |

</details>

**Comment by juliamagan** [comment]
## Testing results

### Checks

<details>
<summary> 3.5.1.1 Ensure ufw is installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>

<details>
<summary> 3.5.1.2 Ensure iptables-persistent is not installed with ufw (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 3.5.1.3 Ensure ufw service is enabled (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.1.4 Ensure ufw loopback traffic is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.1.7 Ensure ufw default deny firewall policy (Automated) :yellow_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :yellow_circle:
    Why is `disabled` accepted?
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.2.1 Ensure nftables is installed (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.2.2 Ensure ufw is uninstalled or disabled with nftables (Automated) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :red_circle:
    Missing rule that checks if nftables is installed
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.2.3 Ensure iptables are flushed with nftables (Manual) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :red_circle:
    Wrong description
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :red_circle:
    Missing rule for ip6tables
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.2.4 Ensure a nftables table exists (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>

<details>
<summary> 3.5.2.5 Ensure nftables base chains exist (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.2.6 Ensure nftables loopback traffic is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:


</details>
<details>
<summary> 3.5.2.8 Ensure nftables default deny firewall policy (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **impact** :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:


</details>
<details>
<summary> 3.5.2.9 Ensure nftables service is enabled (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.3.1.1 Ensure iptables packages are installed (Automated) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :red_circle:
    Missing rule for iptables-persistent. Maybe we don't need to check if nftables or ufw are installed, it will be checked in the following checks.
- **Expected scan result**: `FAIL` -> :yellow_circle:

</details>
<details>
<summary> 3.5.3.1.2 Ensure nftables is not installed with iptables (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>

<details>
<summary> 3.5.3.1.3 Ensure ufw is uninstalled or disabled with iptables (Automated) :red_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :red_circle:
    Wrong command to check if ufs is enabled and missing `c:`
- **Expected scan result**: `PASS` -> :green_circle:


</details>
<details>
<summary> 3.5.3.2.1 Ensure iptables loopback traffic is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.3.2.3 Ensure iptables default deny firewall policy (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.3.3.1 Ensure ip6tables loopback traffic is configured (Automated) :green_circle:</summary>
<br>

- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle:

</details>
<details>
<summary> 3.5.3.3.3 Ensure ip6tables default deny firewall policy (Automated) :green_circle:</summary>
<br>



- **id**: :green_circle:
- **title**: :green_circle:
- **description**: :green_circle:
- **rationale**: :green_circle:
- **remediation**: :green_circle:
- **compliance**: :green_circle:
- **rules**: :green_circle:
- **Expected scan result**: `FAIL` -> :green_circle: 

</details>


### Deployment

<details>
<summary>If the policy it's new, it must be added to the <code>sca.files</code> templates :green_circle:</summary>
<br>

This policy isn't new. It is present in the `sca.files` templates:

https://github.com/wazuh/wazuh/blob/d3dea11fd25d566efce58731170b9d90f17dee0f/etc/templates/config/ubuntu/20/04/sca.files#L1
</details>

<details>
<summary>If the OS has many supported SCA policies, a policy must be set as the default policy :green_circle:</summary>
<br>
https://github.com/wazuh/wazuh/blob/a3ec35d13bbc5e3fa7c08a368a493191b219a118/etc/templates/config/ubuntu/sca.files#L1
</details>

### Documentation

<details>
<summary>Documentation SCA list includes the created or updated SCA :green_circle:</summary>
<br>

Verified in the `4.4` branch of [wazuh/wazuh-documentation](https://github.com/wazuh/wazuh-documentation/). The file can be found [here](https://github.com/wazuh/wazuh-documentation/blob/4.4/source/user-manual/capabilities/sec-config-assessment/how-to-configure.rst).

![image](https://user-images.githubusercontent.com/80041853/196181479-8dc60c6b-1c91-4ef6-a06f-b0baa39eda32.png)


</details>

**Comment by 72nomada** [comment]
Solved:
-  Checks 3.5.2.2, 3.5.2.3, 3.5.3.1.1 an 3.5.3.1.3: Issues found in rules 🔴 (Rules) 
-  Check 3.5.1.7: Issues found in rules 🟡 (Rules)
-  Check 3.5.2.3: Issues found in description and rules 🔴 (Content + Rules)

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15070/commits/841246748a7cd0f4436002d329b02d75bb6ca227

***

### Results



<details>
<summary> 3.5.1.7 Ensure ufw default deny firewall policy (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:

</details>

<details>
<summary> 3.5.2.2 Ensure ufw is uninstalled or disabled with nftables (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:

</details>
<details>
<summary> 3.5.2.3 Ensure iptables are flushed with nftables (Manual) :green_circle:</summary>
<br>

- **description**: :green_circle:
- **rules**: :green_circle:

</details>
<details>
<summary> 3.5.3.1.1 Ensure iptables packages are installed (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:
- **Expected scan result**: :green_circle:

</details>
<details>
<summary> 3.5.3.1.3 Ensure ufw is uninstalled or disabled with iptables (Automated) :green_circle:</summary>
<br>

- **rules**: :green_circle:

</details>



## Conclusion :green_circle:

Everything has been fixed

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly after the proposed fixes.
