### ISSUE TITLE
Ubuntu Linux 22.04 SCA Policy - Update and rework - checks 1.8 to 1.9

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3444]
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          |  #3390| https://github.com/wazuh/wazuh/pull/15051 |

| Check ID | Check Name                                                                               | Implemented | Ready for review | QA review |
| -------- | ---------------------------------------------------------------------------------------- | ----------- | ---------------- | --------- |
| 1.8      | GNOME Display Manager                                                                    |             |                  |           |
| 1.8.1    | Ensure GNOME Display Manager is removed (Automated)                                      |             |                  |           |
| 1.8.2    | Ensure GDM login banner is configured (Automated)                                        |             |                  |           |
| 1.8.3    | Ensure GDM disable-user-list option is enabled (Automated)                               |             |                  |           |
| 1.8.4    | Ensure GDM screen locks when the user is idle (Automated)                                |             |                  |           |
| 1.8.5    | Ensure GDM screen locks cannot be overridden (Automated)                                 |             |                  |           |
| 1.8.6    | Ensure GDM automatic mounting of removable media is disabled (Automated)                 |             |                  |           |
| 1.8.7    | Ensure GDM disabling automatic mounting of removable media is not overridden (Automated) |             |                  |           |
| 1.8.8    | Ensure GDM autorun-never is enabled (Automated)                                          |             |                  |           |
| 1.8.9    | Ensure GDM autorun-never is not overridden (Automated)                                   |             |                  |           |
| 1.8.10   | Ensure XDCMP is not enabled (Automated)                                                  |             |                  |           |
| 1.9      | Ensure updates, patches, and additional security software are installed (Manual)         |             |                  |           |

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15051/commits/4cac289aeb0f2daa7309cd8840793409e0f24019 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages


| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Ubuntu | [Manager](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-qa.vr.3443_amd64.deb)|



### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@72nomada )

**Comment by Rebits** [comment]
## Testing review :red_circle:


<details>

<summary> 1.8.1 :red_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


It should be added  rule `"c:dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3 -> r:gdm3\\s*\\t*unknown\\s*\\t*ok\\s*\\t*not-installed\\s*\\t*not-installed|no packages found matching gdm3"`


Output:
```
root@ip-172-31-7-190:/home/qa# dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3 
dpkg-query: no packages found matching gdm3

```

Expected Passed - :green_circle:
```
{"type":"check","id":1356623917,"policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","policy_id":"cis_ubuntu22-04","check":{"id":28543,"title":"Ensure GNOME Display Manager is removed.","description":"The GNOME Display Manager (GDM) is a program that manages graphical display servers and handles graphical user logins.","rationale":"If a Graphical User Interface (GUI) is not required, it should be removed to reduce the attack surface of the system.","remediation":"Run the following command to uninstall gdm3: # apt purge gdm3.","compliance":{"cis":"1.8.1","cis_csc_v7":"9.2","cis_csc_v8":"4.8","mitre_techniques":"T1543,T1543.002","mitre_tactics":"TA0002","cmmc_v2.0":"CM.L2-3.4.7,CM.L2-3.4.8,SC.L2-3.13.6","pci_dss_v3.2.1":"1.1.6,1.2.1,2.2.2,2.2.5","pci_dss_v4.0":"1.2.5,2.2.4,6.4.1","soc_2":"CC6.3,CC6.6"},"rules":["c:dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3 -> r:gdm\\s+unknown\\s+ok\\s+not-installed"],"condition":"all","command":"dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3","result":"failed"}}
```


</details>


<details>

<summary> 1.8.10 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:


Maybe is better to mark as Passed this check if gdm3 is not installed. In case this is the default behaviours we should ensure every check fit the standard.

Expected Not applicable/Passed- :green_circle:
```
{"type":"check","id":1356623917,"policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","policy_id":"cis_ubuntu22-04","check":{"id":28544,"title":"Ensure XDCMP is not enabled.","description":"X Display Manager Control Protocol (XDMCP) is designed to provide authenticated access to display management services for remote displays.","rationale":"XDMCP is inherently insecure. XDMCP is not a ciphered protocol. This may allow an attacker to capture keystrokes entered by a user XDMCP is vulnerable to man-in-the-middle attacks. This may allow an attacker to steal the credentials of legitimate users by impersonating the XDMCP server.","remediation":"Edit the file /etc/gdm3/custom.conf and remove the line: Enable=true Default Value: false (This is denoted by no Enabled= entry in the file /etc/gdm3/custom.conf in the [xdmcp] section.","compliance":{"cis":"1.8.10","cis_csc_v7":"9.2","cis_csc_v8":"4.8","mitre_techniques":"T1040,T1056,T1056.001,T1557","mitre_tactics":"TA0002","mitre_mitigations":"M1050","cmmc_v2.0":"CM.L2-3.4.7,CM.L2-3.4.8,SC.L2-3.13.6","pci_dss_v3.2.1":"1.1.6,1.2.1,2.2.2,2.2.5","pci_dss_v4.0":"1.2.5,2.2.4,6.4.1","soc_2":"CC6.3,CC6.6"},"rules":["not f:/etc/gdm3/custom.conf -> r:^\\s*Enable\\s*=\\s*true"],"condition":"all","file":"/etc/gdm3/custom.conf","status":"Not applicable","reason":"Could not open file '/etc/gdm3/custom.conf'"}}

```


</details>


## Conclusions :red_circle: 

- Incomplete `1.8.1` audit :red_circle:
- In case vulnerable software is not installed, related configuration checks should be marked as passed :yellow_circle:

**Comment by Rebits** [comment]
### Update - 02/11/2022
- [First policy review](https://github.com/wazuh/wazuh-qa/issues/3444#issuecomment-1300274913)

**Comment by fabamatic** [comment]
Implemented requested changes

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15051/commits/cdd8c21e3c0ad4d3c0dcb1b7a275661db34b8108


***

### Results

<details>

<summary> 1.8.1 🟢 </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
root@ip-172-31-10-66:/home/qa# dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3
gdm3	install ok installed	installed
```

Expected Failed - :green_circle:
```
{"timestamp":"2022-11-07T16:49:41.257+0000","rule":{"level":9,"description":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.: Ensure GNOME Display Manager is removed.: Status changed from passed to failed","id":"19011","firedtimes":1,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["1.8.1"],"cis_csc_v7":["9.2"],"cis_csc_v8":["4.8"],"mitre_techniques":["T1543","T1543.002"],"mitre_tactics":["TA0002"],"soc_2":["CC6.3","CC6.6"]},"agent":{"id":"000","name":"ip-172-31-10-66"},"manager":{"name":"ip-172-31-10-66"},"id":"1667839781.1136190","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1733114389","policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","check":{"id":"28543","title":"Ensure GNOME Display Manager is removed.","description":"The GNOME Display Manager (GDM) is a program that manages graphical display servers and handles graphical user logins.","rationale":"If a Graphical User Interface (GUI) is not required, it should be removed to reduce the attack surface of the system.","remediation":"Run the following command to uninstall gdm3: # apt purge gdm3.","compliance":{"cis":"1.8.1","cis_csc_v7":"9.2","cis_csc_v8":"4.8","mitre_techniques":"T1543,T1543.002","mitre_tactics":"TA0002","cmmc_v2":{"0":"CM.L2-3.4.7,CM.L2-3.4.8,SC.L2-3.13.6"},"pci_dss_v3":{"2":{"1":"1.1.6,1.2.1,2.2.2,2.2.5"}},"pci_dss_v4":{"0":"1.2.5,2.2.4,6.4.1"},"soc_2":"CC6.3,CC6.6"},"command":["dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' gdm3"],"result":"failed","previous_result":"passed"}}},"location":"sca"}

```


</details>

**Comment by Rebits** [comment]
### Update - 07/11/2022
- [Second manual testing iteration](https://github.com/wazuh/wazuh-qa/issues/3444#issuecomment-1305904322)

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved | 

The development has been approved taking into account the following considerations:

**(1) Incomplete rule for 1.8.1 audit implementation.** 🟢

This has been solved in this current development https://github.com/wazuh/wazuh/pull/15051/commits/136d41b676ef1fd966187f8761854ed43d58602f

**(2) In case vulnerable software is not installed, related configuration checks should be marked as passed** 🟢

This has been solved in this current development https://github.com/wazuh/wazuh/pull/15051/commits/136d41b676ef1fd966187f8761854ed43d58602f
