### ISSUE TITLE
Ubuntu Linux 22.04 SCA Policy - Update and rework - checks 2.3 to 2.4

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3446]
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          |  #3390         | https://github.com/wazuh/wazuh/pull/15051 |

| Check ID | Check Name                                                  | Implemented | Ready for review | QA review |
| -------- | ----------------------------------------------------------- | ----------- | ---------------- | --------- |
| 2.3      | Service Clients                                             |             |                  |           |
| 2.3.1    | Ensure NIS Client is not installed (Automated)              |             |                  |           |
| 2.3.2    | Ensure rsh client is not installed (Automated)              |             |                  |           |
| 2.3.3    | Ensure talk client is not installed (Automated)             |             |                  |           |
| 2.3.4    | Ensure telnet client is not installed (Automated)           |             |                  |           |
| 2.3.5    | Ensure LDAP client is not installed (Automated)             |             |                  |           |
| 2.3.6    | Ensure RPC is not installed (Automated)                     |             |                  |           |
| 2.4      | Ensure nonessential services are removed or masked (Manual) |             |                  |           |

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15051/commits/c95fd71a25a0eedecbaf094136228e7681998472 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Ubuntu | [Manager](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-qa.vr.3443_amd64.deb)|


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved ()

**Comment by Rebits** [comment]
## Testing results :red_circle:

<details>

<summary>  2.3 .1 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' nis -> r:no packages found matching nis|deinstall|not-installed"
```

Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' nis -> no packages found matching nis|deinstall|not-installed"
```


Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' nis
nis\tunknown ok not-installed\tnot-installed\nroot@ip-172-31-1-41:/home/qa# dpkg-query -s nis
dpkg-query: package 'nis' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```

Expected Passed - :red_circle:

</details>


<details>

<summary>2.3.2  :red_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :red_circle: - Extra white spaces: `or rsh , rcp and rlogin  .`
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rsh-client -> r:no packages found matching rsh-client|deinstall|not-installed"
```

Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rsh-client ->r:no packages found matching rsh-client|deinstall|not-installed"
```  

Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -s rsh-client
dpkg-query: package 'rsh-client' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rsh-client
rsh-client\tunknown ok not-installed\tnot-installed\nroot@ip-172-31-1-41:/home/qa# 
```

Expected Passed - :red_circle:

</details>

<details>

<summary> 2.3.3 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' talk -> r:no packages found matching talk|deinstall|not-installed"
```
Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' talk -> no packages found matching talk|deinstall|not-installed"
```


Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -s talk
dpkg-query: package 'talk' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' talk
dpkg-query: no packages found matching talk
root@ip-172-31-1-41:/home/qa# 
```

Expected Passed - :red_circle:

</details>

<details>

<summary> 2.3.4 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' telnet -> r:no packages found matching telnet|deinstall|not-installed"
```

Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' telnet -> no packages found matching telnet|deinstall|not-installed"
```


Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -s telnet
Package: telnet
Status: install ok installed
Priority: standard
Section: net
Installed-Size: 154
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: netkit-telnet
Version: 0.17-44build1
Replaces: netstd
Provides: telnet-client
Depends: libc6 (>= 2.34), libstdc++6 (>= 5), netbase
Description: basic telnet client
 The telnet command is used for interactive communication with another host
 using the TELNET protocol.
 .
 For the purpose of remote login, the present client executable should be
 depreciated in favour of an ssh-client, or in some cases with variants like
 telnet-ssl or Kerberized TELNET clients.  The most important reason is that
 this implementation exchanges user name and password in clear text.
 .
 On the other hand, the present program does satisfy common use cases of
 network diagnostics, like protocol testing of SMTP services, so it can
 become handy enough.
Homepage: http://www.hcs.harvard.edu/~dholland/computers/netkit.html
Original-Maintainer: Debian QA Group <packages@qa.debian.org>
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' telnet
telnet\tinstall ok installed\tinstalled\nroot@ip-172-31-1-41:/home/qa# 

```

Expected - :green_circle:

</details>




<details>

<summary> 2.3.5 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' ldap-utils -> r:no packages found matching ldap-utils|deinstall|not-installed"
```

Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' ldap-utils -> no packages found matching ldap-utils|deinstall|not-installed"
```

Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -s ldap-utils
dpkg-query: package 'ldap-utils' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' ldap-utils
ldap-utils\tunknown ok not-installed\tnot-installed\nroot@ip-172-31-1-41:/home/qa# 
```

Expected Failed - :green_circle:

</details>

<details>

<summary> 2.3.6 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

Expected:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rpcbind -> r:no packages found matching rpcbind|deinstall|not-installed"
```

Current:
```
- "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rpcbind -> no packages found matching rpcbind|deinstall|not-installed"
```


Output:
```
root@ip-172-31-1-41:/home/qa# dpkg-query -s rpcbind
dpkg-query: package 'rpcbind' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
root@ip-172-31-1-41:/home/qa# dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' rpcbind
dpkg-query: no packages found matching rpcbind
root@ip-172-31-1-41:/home/qa# 
```

Expected Passed - :red_circle:

</details>

**Comment by Rebits** [comment]
### Update - 03/11/2022
- [Check 2.3.1-2.3.6](https://github.com/wazuh/wazuh-qa/issues/3446#issuecomment-1302476624)

**Comment by fabamatic** [comment]
Implemented requested changes

**Comment by Rebits** [comment]
## Testing after requested changes :green_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15051/commits/f1967aa144ec4537fa4eb68f4d9c00241cf065f3

***

### Results

<details>

<summary>  2.3.1 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

</details>


<details>

<summary> 2.3.2 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>


<details>

<summary> 2.3.3 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

</details>


<details>

<summary> 2.3.4 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

</details>

<details>

<summary> 2.3.5 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>

<details>

<summary> 2.3.6 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved |

All bugs encountered and reported have been solved in this development.

**(1) Error in rules and checks** 🟢

- 2.3.1: Malformed rule
- 2.3.2: Malformed rule and rationale.
- 2.3.3: Malformed rule.
- 2.3.4: Malformed rule.
- 2.3.5: Malformed rule.
- 2.3.6: Malformed rule.
