### ISSUE TITLE
Ubuntu Linux 22.04 SCA Policy - Update and rework - checks 5.5 to 5.5.5

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3453]
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          | #3390         | https://github.com/wazuh/wazuh/pull/15051 |

| Check ID | Check Name                                                             | Implemented | Ready for review | QA review |
| -------- | ---------------------------------------------------------------------- | ----------- | ---------------- | --------- |
| 5.5      | User Accounts and Environment                                          |             |                  |           |
| 5.5.1    | Set Shadow Password Suite Parameters                                   |             |                  |           |
| 5.5.1.1  | Ensure minimum days between password changes is configured (Automated) |             |                  |           |
| 5.5.1.2  | Ensure password expiration is 365 days or less (Automated)             |             |                  |           |
| 5.5.1.3  | Ensure password expiration warning days is 7 or more (Automated)       |             |                  |           |
| 5.5.1.4  | Ensure inactive password lock is 30 days or less (Automated)           |             |                  |           |
| 5.5.1.5  | Ensure all users last password change date is in the past (Automated)  |             |                  |           |
| 5.5.2    | Ensure system accounts are secured (Automated)                         |             |                  |           |
| 5.5.3    | Ensure default group for the root account is GID 0 (Automated)         |             |                  |           |
| 5.5.4    | Ensure default user umask is 027 or more restrictive (Automated)       |             |                  |           |
| 5.5.5    | Ensure default user shell timeout is 900 seconds or less (Automated)   |             |                  |           |

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |https://github.com/wazuh/wazuh/pull/15051/commits/0641c40c9406974729e2a7f98c89ec48fb9f0646|

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |

### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3453.sca_amd64.deb)             

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion

**Comment by juliamagan** [comment]
## Testing results

### Checks

<details>
<summary> 5.5.1.1 Ensure minimum days between password changes is configured (Automated)</summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: `` -> 

</details>

<details>
<summary> 5.5.1.2 Ensure password expiration is 365 days or less (Automated)</summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: `` -> 

</details>

<details>
<summary> 5.5.1.3 Ensure password expiration warning days is 7 or more (Automated)</summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: `` -> 

</details>
<details>
<summary> 5.5.1.4 Ensure inactive password lock is 30 days or less (Automated)</summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: `` -> 

</details>
<details>
<summary> 5.5.3	Ensure default group for the root account is GID 0 (Automated)</summary>
<br>

- **id**: 
- **title**: 
- **description**: 
- **rationale**: 
- **remediation**: 
- **compliance**: 
- **rules**: 
- **Expected scan result**: `` -> 

</details>



### Deployment

<details>
<summary>If the policy it's new, it must be added to the <code>sca.files</code> templates </summary>
<br>

This policy isn't new. It is present in the `sca.files` templates:

https://github.com/wazuh/wazuh/blob/0641c40c9406974729e2a7f98c89ec48fb9f0646/etc/templates/config/ubuntu/22/04/sca.files#L1

</details>

<details>
<summary>If the OS has many supported SCA policies, a policy must be set as the default policy </summary>
<br>

https://github.com/wazuh/wazuh/blob/0641c40c9406974729e2a7f98c89ec48fb9f0646/etc/templates/config/ubuntu/sca.files#L1

</details>

### Documentation

<details>
<summary>Documentation SCA list includes the created or updated SCA </summary>
<br>

Verified in the `4.4` branch of [wazuh/wazuh-documentation](https://github.com/wazuh/wazuh-documentation/). The file can be found [here](https://github.com/wazuh/wazuh-documentation/blob/4.4/source/user-manual/capabilities/sec-config-assessment/how-to-configure.rst).



</details>

**Comment by 72nomada** [comment]
5.5.1.1 Solved
5.5.1.3 Solved
5.5.1.4 Solved
5.5.3 
- T1548.000 is a wrong technique, is a pdf typo
- NIST CSF - not implemented
- NIST SP 800-53 Revision 5 Low Baseline, implemented Moderate level.

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15051/commits/a79ab79b9dfd9b209b1dc71fbf378e5cf9ad1773

***

### Results


<details>
<summary> 5.5.1.1 Ensure minimum days between password changes is configured (Automated) :yellow_circle:</summary>
<br>


- **remediation**: :yellow_circle:
    `Default value` shouldn't be here
- **rules**: :green_circle:

</details>

<details>
<summary> 5.5.1.2 Ensure password expiration is 365 days or less (Automated) :yellow_circle:</summary>
<br>


- **remediation**: :yellow_circle:
    `Default value` shouldn't be here
- **rules**: :green_circle:
</details>

<details>
<summary> 5.5.1.3 Ensure password expiration warning days is 7 or more (Automated) :yellow_circle:</summary>
<br>


- **remediation**: :yellow_circle:
    `Default value` shouldn't be here
- **rules**: :green_circle:
- **Expected scan result**: `PASS` -> :green_circle:

</details>
<details>
<summary> 5.5.1.4 Ensure inactive password lock is 30 days or less (Automated) :green_circle:</summary>
<br>


- **remediation**: :green_circle:
- **rules**: :green_circle:

</details>
<details>
<summary> 5.5.3	Ensure default group for the root account is GID 0 (Automated) :green_circle:</summary>
<br>


- **compliance**: :green_circle:

</details>




## Conclusion :yellow_circle:

`Default Value` has not been removed from some rules

**Comment by 72nomada** [comment]
5.5.1.1 Solved
5.5.1.2 Solved
5.5.1.3 Solved

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/15051/commits/fe2469ada66b73c26702be39684d38e31e31c268

***

### Results


<details>
<summary> 5.5.1.1 Ensure minimum days between password changes is configured (Automated) :green_circle:</summary>
<br>


- **remediation**: :green_circle:

</details>

<details>
<summary> 5.5.1.2 Ensure password expiration is 365 days or less (Automated) :green_circle:</summary>
<br>


- **remediation**: :green_circle:
</details>

<details>
<summary> 5.5.1.3 Ensure password expiration warning days is 7 or more (Automated) :green_circle:</summary>
<br>


- **remediation**: :green_circle:

</details>





## Conclusion :green_circle:

Everything has been fixed

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved |

All the proposed fixes and improvements have been implemented in this current development, so development is approved taking into account:

- Check 5.5.1.1: Missing rule and tabulations not considered. 🟢
- Checks 5.5.1.2, 5.5.1.3 and 5.5.1.4: Tabulations not considered and wrong regex. 🟢
- Checks 5.5.1.1 - 5.5.1.4: Issues found in remediation. 🟢
- Check 5.5.3: Issues found in compliance. 🟢
- Default Value has not been removed from some rules. 🟢
