### ISSUE TITLE
Adding support for new sysmon events

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3458]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|                4.4.0        |            https://github.com/wazuh/wazuh-qa/issues/3396            |         https://github.com/wazuh/wazuh/pull/13594           |

This issue is part of the global addition of APT emulation rules.

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [1c5fe38](https://github.com/wazuh/wazuh/pull/13594/commits/1c5fe387216d4562e66cff861905b612e01e4f20) | 



### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| Ubuntu              | 22         | EC2        | `ami-003530de8839921c4` |
| Windows Server  |      2022      |       EC2     |   `ami-047e29beecff33db0`                      |


### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Ubuntu | [Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commitecc41dd_amd64.deb) |
| Windows Server       |           [Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/windows/wazuh-agent-4.4.0-0.commitecc41dd.msi)                                                                          |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @72nomada

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:  


<details>

<summary> Sysmon - Event 1</summary>

<blockquote>

<details> 

<summary> Event generation </summary>

Install and run `mimikatz` as especified in [blog](https://wazuh.com/blog/learn-to-detect-threats-on-windows-by-monitoring-sysmon-events/)

</details>

<details>

<summary> Event </summary>

```
** Alert 1665674699.2360655: mail  - windows, sysmon, sysmon_process-anomalies,
2022 Oct 13 15:24:59 (EC2AMAZ-N9OLJ1L) any->EventChannel
Rule: 100000 (level 12) -> 'Sysmon - Suspicious Process - mimikatz.exe'
{"win":{"system":{"providerName":"Microsoft-Windows-Sysmon","providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","eventID":"1","version":"5","level":"4","task":"1","opcode":"0","keywords":"0x8000000000000000","systemTime":"2022-10-13T15:24:58.1781709Z","eventRecordID":"5","processID":"2832","threadID":"3612","channel":"Microsoft-Windows-Sysmon/Operational","computer":"EC2AMAZ-N9OLJ1L","severityValue":"INFORMATION","message":"\"Process Create:\r\nRuleName: -\r\nUtcTime: 2022-10-13 15:24:58.177\r\nProcessGuid: {3bd4f97a-2dca-6348-6701-000000009500}\r\nProcessId: 6044\r\nImage: C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\mimikatz.exe\r\nFileVersion: 2.2.0.0\r\nDescription: mimikatz for Windows\r\nProduct: mimikatz\r\nCompany: gentilkiwi (Benjamin DELPY)\r\nOriginalFileName: mimikatz.exe\r\nCommandLine: \"C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\mimikatz.exe\" \r\nCurrentDirectory: C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\\r\nUser: EC2AMAZ-N9OLJ1L\\qa\r\nLogonGuid: {3bd4f97a-2cac-6348-4dd1-030000000000}\r\nLogonId: 0x3D14D\r\nTerminalSessionId: 2\r\nIntegrityLevel: High\r\nHashes: MD5=29EFD64DD3C7FE1E2B022B7AD73A1BA5\r\nParentProcessGuid: {3bd4f97a-2cae-6348-9000-000000009500}\r\nParentProcessId: 5216\r\nParentImage: C:\\Windows\\explorer.exe\r\nParentCommandLine: C:\\Windows\\Explorer.EXE\r\nParentUser: EC2AMAZ-N9OLJ1L\\qa\""},"eventdata":{"utcTime":"2022-10-13 15:24:58.177","processGuid":"{3bd4f97a-2dca-6348-6701-000000009500}","processId":"6044","image":"C:\\\\Users\\\\qa\\\\Downloads\\\\mimikatz_trunk\\\\x64\\\\mimikatz.exe","fileVersion":"2.2.0.0","description":"mimikatz for Windows","product":"mimikatz","company":"gentilkiwi (Benjamin DELPY)","originalFileName":"mimikatz.exe","commandLine":"\\\"C:\\\\Users\\\\qa\\\\Downloads\\\\mimikatz_trunk\\\\x64\\\\mimikatz.exe\\\"","currentDirectory":"C:\\\\Users\\\\qa\\\\Downloads\\\\mimikatz_trunk\\\\x64\\\\","user":"EC2AMAZ-N9OLJ1L\\\\qa","logonGuid":"{3bd4f97a-2cac-6348-4dd1-030000000000}","logonId":"0x3d14d","terminalSessionId":"2","integrityLevel":"High","hashes":"MD5=29EFD64DD3C7FE1E2B022B7AD73A1BA5","parentProcessGuid":"{3bd4f97a-2cae-6348-9000-000000009500}","parentProcessId":"5216","parentImage":"C:\\\\Windows\\\\explorer.exe","parentCommandLine":"C:\\\\Windows\\\\Explorer.EXE","parentUser":"EC2AMAZ-N9OLJ1L\\\\qa"}}}
win.system.providerName: Microsoft-Windows-Sysmon
win.system.providerGuid: {5770385f-c22a-43e0-bf4c-06f5698ffbd9}
win.system.eventID: 1
win.system.version: 5
win.system.level: 4
win.system.task: 1
win.system.opcode: 0
win.system.keywords: 0x8000000000000000
win.system.systemTime: 2022-10-13T15:24:58.1781709Z
win.system.eventRecordID: 5
win.system.processID: 2832
win.system.threadID: 3612
win.system.channel: Microsoft-Windows-Sysmon/Operational
win.system.computer: EC2AMAZ-N9OLJ1L
win.system.severityValue: INFORMATION
win.system.message: "Process Create:
RuleName: -
UtcTime: 2022-10-13 15:24:58.177
ProcessGuid: {3bd4f97a-2dca-6348-6701-000000009500}
ProcessId: 6044
Image: C:\Users\qa\Downloads\mimikatz_trunk\x64\mimikatz.exe
FileVersion: 2.2.0.0
Description: mimikatz for Windows
Product: mimikatz
Company: gentilkiwi (Benjamin DELPY)
OriginalFileName: mimikatz.exe
CommandLine: "C:\Users\qa\Downloads\mimikatz_trunk\x64\mimikatz.exe" 
CurrentDirectory: C:\Users\qa\Downloads\mimikatz_trunk\x64\
User: EC2AMAZ-N9OLJ1L\qa
LogonGuid: {3bd4f97a-2cac-6348-4dd1-030000000000}
LogonId: 0x3D14D
TerminalSessionId: 2
IntegrityLevel: High
Hashes: MD5=29EFD64DD3C7FE1E2B022B7AD73A1BA5
ParentProcessGuid: {3bd4f97a-2cae-6348-9000-000000009500}
ParentProcessId: 5216
ParentImage: C:\Windows\explorer.exe
ParentCommandLine: C:\Windows\Explorer.EXE
ParentUser: EC2AMAZ-N9OLJ1L\qa"
win.eventdata.utcTime: 2022-10-13 15:24:58.177
win.eventdata.processGuid: {3bd4f97a-2dca-6348-6701-000000009500}
win.eventdata.processId: 6044
win.eventdata.image: C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\mimikatz.exe
win.eventdata.fileVersion: 2.2.0.0
win.eventdata.description: mimikatz for Windows
win.eventdata.product: mimikatz
win.eventdata.company: gentilkiwi (Benjamin DELPY)
win.eventdata.originalFileName: mimikatz.exe
win.eventdata.commandLine: \"C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\mimikatz.exe\"
win.eventdata.currentDirectory: C:\\Users\\qa\\Downloads\\mimikatz_trunk\\x64\\
win.eventdata.user: EC2AMAZ-N9OLJ1L\\qa
win.eventdata.logonGuid: {3bd4f97a-2cac-6348-4dd1-030000000000}
win.eventdata.logonId: 0x3d14d
win.eventdata.terminalSessionId: 2
win.eventdata.integrityLevel: High
win.eventdata.hashes: MD5=29EFD64DD3C7FE1E2B022B7AD73A1BA5
win.eventdata.parentProcessGuid: {3bd4f97a-2cae-6348-9000-000000009500}
win.eventdata.parentProcessId: 5216
win.eventdata.parentImage: C:\\Windows\\explorer.exe
win.eventdata.parentCommandLine: C:\\Windows\\Explorer.EXE
win.eventdata.parentUser: EC2AMAZ-N9OLJ1L\\qa
```

</details>


</blockquote>


</details>

**Comment by Rebits** [comment]
## 13/10/2022

- Research SysmonSimulator
- Follow [Sysmon Events with Wazuh blog](https://wazuh.com/blog/learn-to-detect-threats-on-windows-by-monitoring-sysmon-events/)
- Perform Check: `Symon - Event 1`

**Comment by Rebits** [comment]
## 14/10/2022
- Perform Checks: [`Symon - Event 2` - `Sysmon - Event 26`](https://github.com/wazuh/wazuh-qa/issues/3458#issuecomment-1277910151)

**Comment by fabamatic** [comment]
Fixed Sysmon rules for events 2 and 9. Added rule for event 255

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Requested improvements :yellow_circle:
- **Comments**: During this testing, some issues and improvements have been detected. These are as follows:
    - *(1)* Symon event 2 rule for creation time changing use `win.eventdata.sourceImage` instead of `win.eventdata.image`, making the description incomplete (cc @wazuh/threat-intel).
    - *(2)* Sysmon event 9 for RawAccessRead use `win.eventdata.sourceImage` instead of `win.eventdata.image`, making the description incomplete (cc @wazuh/threat-intel).
    - *(3)* Sysmon error event (255) is not included in the ruleset(cc @wazuh/threat-intel).
    - *(4)* Improve blog documentation "[Learn to detect threats on Windows by monitoring Sysmon events](https://wazuh.com/blog/learn-to-detect-threats-on-windows-by-monitoring-sysmon-events/)" (cc @wazuh/content)
       - Update `sysconfig.xml` schema, including new Sysmon events IDs
       - Enrich `sysconfig.xml`, increasing the use cases presented in the blog, and explaining how to customize sysconfig.xml for each use case.

All of this will be discussed with the development team, and approved or not based on these findings.

**Comment by Rebits** [comment]
## Testing after requested changes

- Tester: @Rebits 
- PR commit: 

***

### Results :large_blue_circle:
