### ISSUE TITLE
FIM v2.0: Wazuh DB Integration tests

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-qa#346]
## Description

This issue covers the integration test for the FIM related queries handling by Wazuh DB. We will treat Wazuh DB as a black box that receives the aforementioned queries by its input Unix socket, checking that the correct output is shown.

Sixteen use cases have been defined to check that the queries are handled properly. These cases should be implemented in the same test.

- [x] FIM_LOAD
- [x] FIM_FIND_ENTRY
- [x] FIM_INSERT_ENTRY
- [x] FIM_INSERT_ENTRY2
- [x] FIM_UPDATE_ENTRY
- [x] FIM_DELETE
- [x] FIM_UPDATE_DATE
- [x] FIM_FIND_DATE_ENTRIES
- [x] FIM_GET_ATTRIBUTES
- [x] FIM_UPDATE_ATTRIBUTES
- [x] FIM_SELECT_CHECKSUM_RANGE
- [x] FIM_DELETE_AROUND
- [x] FIM_DELETE_RANGE
- [x] FIM_CLEAR
- [x] SYNC_UPDATE_ATTEMPT
- [x] SYNC_UPDATE_COMPLETION

## FIM LOAD

**Query**:
`wdb 000 "SELECT changes, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, date, attributes, symbolic_path FROM fim_entry WHERE file = '/home/test/file'"`

**Output**:
```
    {
        "changes": 1,
        "size": 7,
        "perm": "rw-r--r--",
        "uid": "0",
        "gid": "0",
        "md5": "4d3dc0121643ca3974208d8b84fa04ef",
        "sha1": "64d0216b46c7df2d79ca469334a8d27fd18eabf1",
        "uname": "root",
        "gname": "root",
        "mtime": 1576494254,
        "inode": 24379394,
        "sha256": "1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d",
        "date": 1576507571
    }
```

## FIM FIND ENTRY

**Query**:
`wdb 000 "SELECT 1 FROM fim_entry WHERE file = '/home/test/file'"`

**Output**:
```
    {
        "1": 1
    }
```

- If the file does not exist or is not monitored, the output will be:
```
[]
```

## FIM INSERT ENTRY

**Query**:
`wdb 000 "INSERT INTO fim_entry (file, type, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, attributes, symbolic_path) VALUES ('/home/test/non_existent', 'file', 10, 'ww-w--w--', 1, 1, '4d3dc0121643ca3974208d8b84fa04ef', '64d0216b46c7df2d79ca469334a8d27fd18eabf1', 'wazuh', 'wazuh', 1576509789, 11119999, '1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d', 'attr', '/home/realpath')"
`

**Output**:
```
[]
```

- To verify that the entry has been successfully added, execute the first test (changing the file name for the one that has been added), the output should be like this:
```
    {
        "changes": 1,
        "size": 10,
        "perm": "ww-w--w--",
        "uid": "1",
        "gid": "1",
        "md5": "4d3dc0121643ca3974208d8b84fa04ef",
        "sha1": "64d0216b46c7df2d79ca469334a8d27fd18eabf1",
        "uname": "wazuh",
        "gname": "wazuh",
        "mtime": 1576509789,
        "inode": 11119999,
        "sha256": "1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d",
        "date": 1576572791,
        "attributes": "attr",
        "symbolic_path": "/home/realpath"
    }
```

## FIM INSERT ENTRY 2

**Query**:
`wdb 000 "INSERT OR REPLACE INTO fim_entry (file, type, date, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, attributes, symbolic_path, checksum) VALUES ('/home/test/non_existent', 'file', 3, 10, 'ww-w--w--', 1, 1, '4d3dc0121643ca3974208d8b84fa04ef', '64d0216b46c7df2d79ca469334a8d27fd18eabf1', 'wazuh', 'wazuh', 1576509789, 11119999, '1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d', 'attr', '/home/realpath', 'asdfghijklmn')"
`

**Output**:
```
[]
```

- To verify that the entry has been successfully added, execute the first test (changing the file name for the one that has been added and adding the `checksum` field to the query), the output should be like this:
```
    {
        "changes": 1,
        "size": 10,
        "perm": "ww-w--w--",
        "uid": "1",
        "gid": "1",
        "md5": "4d3dc0121643ca3974208d8b84fa04ef",
        "sha1": "64d0216b46c7df2d79ca469334a8d27fd18eabf1",
        "uname": "wazuh",
        "gname": "wazuh",
        "mtime": 1576509789,
        "inode": 11119999,
        "sha256": "1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d",
        "date": 3,
        "attributes": "attr",
        "symbolic_path": "/home/realpath",
        "checksum": "asdfghijklmn"
    }
```

## FIM UPDATE ENTRY

**Query**:
`wdb 000 "UPDATE fim_entry SET date = 1984, changes = 3, size = 78, perm = 'rr-r--r--', uid = 4, gid = 3, md5 = 'md5', sha1 = 'sha1', uname = 'wazuh_2', gname = 'wazuh_2', mtime = 1984, inode = 437, sha256 = 'sha256', attributes = 'attr2', symbolic_path = '/home/test/realpath2' WHERE file = '/home/test/file'"`

**Output**:
```
[]
```

- To verify that the entry has been successfully updated, execute the first test (changing the file name for the one that has been updated and adding the `checksum` field to the query), the output should be like this:
```
    {
        "changes": 3,
        "size": 78,
        "perm": "rr-r--r--",
        "uid": "4",
        "gid": "3",
        "md5": "md5",
        "sha1": "sha1",
        "uname": "wazuh_2",
        "gname": "wazuh_2",
        "mtime": 1984,
        "inode": 437,
        "sha256": "sha256",
        "date": 1984,
        "attributes": "attr2",
        "symbolic_path": "/home/test/realpath2",
        "checksum": "c95f12466521ee41eaf737ce53a7f5c977738767"
    }
```

## FIM DELETE

**Query**:
`wdb 000 "DELETE FROM fim_entry WHERE file = '/home/test/file'"`

**Output**:
```
[]
```

## FIM UPDATE DATE

**Query**;
`wdb 000 "UPDATE fim_entry SET date=3 WHERE file='/home/test/file'"`

**Output**:
```
[]
```

- To verify that the `date` field has been successfully changed, execute the first test, the output should be like this (check the `date` field only):
```
    {
        "changes": 1,
        "size": 7,
        "perm": "rw-r--r--",
        "uid": "0",
        "gid": "0",
        "md5": "4d3dc0121643ca3974208d8b84fa04ef",
        "sha1": "64d0216b46c7df2d79ca469334a8d27fd18eabf1",
        "uname": "root",
        "gname": "root",
        "mtime": 1576509346,
        "inode": 24379394,
        "sha256": "1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d",
        "date": 3,
        "attributes": "7"
    }
```

## FIM FIND DATE ENTRIES

**Query**:
`wdb 000 "SELECT file, changes, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, date, attributes, symbolic_path FROM fim_entry WHERE date < 78755414"`

**Output**:
```
    {
        "file": "/home/test/file",
        "changes": 1,
        "size": 7,
        "perm": "rw-r--r--",
        "uid": "0",
        "gid": "0",
        "md5": "4d3dc0121643ca3974208d8b84fa04ef",
        "sha1": "64d0216b46c7df2d79ca469334a8d27fd18eabf1",
        "uname": "root",
        "gname": "root",
        "mtime": 1576509346,
        "inode": 24379394,
        "sha256": "1b7db9a166a04682498768eaecbce0c310927dedb57d1106f4616741cd2aa25d",
        "date": 78755412
    }
```

- All the files with which date` field is less than the indicated in the query should appear.

## FIM GET ATTRIBUTES

**Query**:
`wdb 000 "SELECT file, attributes from fim_entry WHERE attributes IS NOT '0'"`

**Output**:
```
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file"
        "attributes": "123"
    }
```

## FIM UPDATE ATTRIBUTES

**Query**:
`wdb 000 "UPDATE fim_entry SET attributes='asdf' WHERE file='/home/test/file'"`

**Output**:
```
[]
```

- To verify that the `attributes` field has been successfully changed, execute the previous test, the output should be like this (check the `attributes` field only):
```
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file",
        "attributes": "asdf"
    }
```

## FIM SELECT CHECKSUM RANGE

**Query**:
`wdb 000 "SELECT checksum FROM fim_entry WHERE file BETWEEN '/home/test/file' and '/home/test/non_existent' ORDER BY file"`

**Output**:
```
    {
        "checksum": "c95f12466521ee41eaf737ce53a7f5c977738767"
    },
    {
        "checksum": "64e932b7aa9ec4484da3926c39cce88f93091e19"
    },
    {
        "checksum": "4e06a65a8f7784e8dbf842b901e9483ca469b89b"
    },
    {
        "checksum": "21b11c94f8525fa8d85edf9716cd277dbbf983ec"
    },
    {
        "checksum": "asdfghijklmn"
    }
```

- The output should display the checksum of every file (in the database) between the two indicated (ordered by file)

## FIM DELETE AROUND

If we have the following files in the database:
```
    {
        "file": "/home/test/file"
    },
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file3"
    },
    {
        "file": "/home/test/file4"
    },
    {
        "file": "/home/test/non_existent"
    }
```

**Query**:
` wdb 000 "DELETE FROM fim_entry WHERE file < '/home/test/file2' OR file > '/home/test/file4'"`

**Output**
```
[]
```

- The following files will remain in the database after the aforementioned query is executed:
```
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file3"
    },
    {
        "file": "/home/test/file4"
    }
```

## FIM DELETE RANGE

- If we have the following files in the database:
```
    {
        "file": "/home/test/file"
    },
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file3"
    },
    {
        "file": "/home/test/file4"
    },
    {
        "file": "/home/test/non_existent"
    }
```

**Query**:
`wdb 000 "DELETE FROM fim_entry WHERE file > '/home/test/file2' AND file < '/home/test/file4'"`

**Output**:
```
[]
```

- The following files will remain in the database after the aforementioned query is executed:
```
    {
        "file": "/home/test/file"
    },
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file4"
    },
    {
        "file": "/home/test/non_existent"
    }
```

## FIM CLEAR

- If we have the following files in the database:
```
    {
        "file": "/home/test/file"
    },
    {
        "file": "/home/test/file2"
    },
    {
        "file": "/home/test/file3"
    },
    {
        "file": "/home/test/file4"
    }
```

**Query**:
`wdb 000 "DELETE FROM fim_entry"`

**Output**:
```
[]
```

- No files should remain after the aforementioned query.

## SYNC UPDATE ATTEMPT

- Check the current status of the `sync_info` table by executing the next query:
`wdb 000 "select * from sync_info"`

The output should look like this:
```
    {
        "component": "fim",
        "last_attempt": 1576576012,
        "last_completion": 1576574958,
        "n_attempts": 82,
        "n_completions": 73
    }
```

**Query**:
`wdb 000 "UPDATE sync_info SET last_attempt = 5, n_attempts = 2 WHERE component = 'fim'"`

**Output**:
```
[]
```

- Check that the `sync_info` table has been correctly updated by executing the first query:
```
    {
        "component": "fim",
        "last_attempt": 5,
        "last_completion": 1576574958,
        "n_attempts": 2,
        "n_completions": 73
    }
```

## SYNC UPDATED COMPLETION

- Check the current status of the `sync_info` table:
```
    {
        "component": "fim",
        "last_attempt": 5,
        "last_completion": 1576574958,
        "n_attempts": 2,
        "n_completions": 73
    }
```

**Query**:
`wdb 000 "UPDATE sync_info SET last_attempt = 7, last_completion = 4, n_attempts = 3, n_completions = 50 WHERE component = 'fim'"`

**Output**:
```
[]
```

- Check that the `sync_info` table has been correctly updated:
```
    {
        "component": "fim",
        "last_attempt": 7,
        "last_completion": 4,
        "n_attempts": 3,
        "n_completions": 50
    }
```

**Comment by davidjiglesias** [comment]
I have finished neccesary fixtures and tools for the wazuh-db tests in 33fc73ddfad1423c20cad971be852f049f01bb49. I am now awaiting for @wazuh/core team to update the test cases `queries` to appropiate wazuh-db inputs from analysisd instead of sql queries.

**Comment by bah07** [comment]
Hi team,
these are the use cases with inputs and outputs of file integrity monitoring events.

### agent [agent_id] syscheck load [file]
- agent_id: `001, 123678, 032, 123...`
- file: `/etc/passwd`

Output
- case Success: "ok size:perm:uid:gid:md5:sha1:username:gname:mtime:inode:sha256:attributes!changes:date_alert"
- case Fail: "err Cannot load Syscheck"
- case Invalid syntax: "err Invalid Syscheck query syntax, near [xxx]"

query: `[WDB_STMT_FIM_LOAD] = "SELECT changes, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, date, attributes, symbolic_path FROM fim_entry WHERE file = ?;"`

### agent [agent_id] syscheck delete [file]
- agent_id: `001, 123678, 032, 123...`
- file: `/etc/passwd`

Output
- case Success: "ok"
- case Fail: "err Cannot delete Syscheck"
- case Invalid syntax: "err Invalid Syscheck query syntax, near [xxx]"

query: `[WDB_STMT_FIM_DELETE] = "DELETE FROM fim_entry WHERE file = ?;",`

### agent [agent_id] syscheck save2 [json]
- agent_id: `001, 123678, 032, 123...`
- json: 
```json
{
    "data": {
        "path": "file",
        "timestamp": "date",
        "attributes": {
            "size": "size",
            "mtime": "mtime",
            "inode": "inode",
            "type": "type",
            "perm": "perm",
            "uid": "uid",
            "gid": "gid",
            "hash_md5": "hash_md5",
            "hash_sha1": "hash_sha1",
            "user_name": "user_name",
            "group_name": "group_name",
            "hash_sha256": "hash_sha256",
            "symbolic_path": "symbolic_path",
            "checksum": "checksum",
            "attributes": "attributes"
        }
    }
}
```

Output
- case Success: "ok"
- case Fail: "err Cannot save Syscheck"
- case Invalid syntax: "err Invalid Syscheck query syntax, near [xxx]"

query: `[WDB_STMT_FIM_INSERT_ENTRY2] = "INSERT OR REPLACE INTO fim_entry (file, type, date, size, perm, uid, gid, md5, sha1, uname, gname, mtime, inode, sha256, attributes, symbolic_path, checksum) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);",`

### agent [agent_id] syscheck [command] [payload]
- agent_id: `001, 123678, 032, 123...`
- command: `integrity_check_global, integrity_check_left`
- payload: `integrity_check_global`
```json
{
    "begin": "",
    "end": "",
    "checksum": "",
    "id": "timestamp"
}
```

- payload: `integrity_check_left`
```json
{
    "begin": "",
    "end": "",
    "checksum": "",
    "id": "timestamp",
    "tail": ""
}
```

Output
- case Success:
return 0 "ok no_data" (no range checksum)
return 1 "ok checksum_fail" "Checksum failure"
return 2 "ok " (Data is synchronized)
- case Fail:
return -1 "err Cannot perform range checksum"
- case Invalid syntax: "err Invalid Syscheck query syntax, near [xxx]"

### agent [agent_id] syscheck integrity_clear [payload]
- agent_id: `001, 1267, 032, 123...`
- payload
```json
{
    "id": "timestamp"
}
```

Output
- case Success: "ok "
- case Fail: "err Cannot perform range checksum"
- case Invalid syntax: "err Invalid Syscheck query syntax, near [xxx]"

query: `[WDB_STMT_FIM_CLEAR] = "DELETE FROM fim_entry;"`
