### ISSUE TITLE
Adding new PowerShell ScriptBlock detection rules 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3466]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.0               |          https://github.com/wazuh/wazuh-qa/issues/3396              |         https://github.com/wazuh/wazuh/pull/13638           |

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |https://github.com/wazuh/wazuh/pull/13638/commits/e6c1df5dd147822c1888d01839ddfb3a21f5d353|

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  CentOS |   CentOS 8   | Vagrant |    qactl/centos_8   |

### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commite6c1df5.x86_64.rpm)             

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion

**Comment by juliamagan** [comment]
## Testing results

<details>
<summary>Changes reflected in PR description :green_circle: </summary>
<br>

![image](https://user-images.githubusercontent.com/80041853/200615739-a5179333-35e4-4861-a2f1-83f392eb98b1.png)


</details>


<details>
<summary><code>runtests.py</code> :green_circle:</summary>
<br>

|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1218   |   4154   |  29.32%  |
| Decoders |   120    |   165    |  72.73%  |


|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/sysmon.ini       |    25    |    0     |   ✅    |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/test_expr_negation.ini|    56    |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/iptables.ini     |    8     |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/test_osregex_regex.ini|    28    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |
|./tests/powershell.ini   |    32    |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/api.ini          |    21    |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/test_pcre2_regex.ini|    33    |    0     |   ✅    |
|./tests/fortiddos.ini    |    1     |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/test_osmatch_regex.ini|    6     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/overwrite.ini    |    10    |    0     |   ✅    |
|./tests/sshd.ini         |    48    |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/test_features.ini|    5     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/test_static_filters.ini|    28    |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |

</details>

<details>
<summary>Rule 91801 :green_circle: </summary>
<br>

Added rule `60010` to `if_sid`. 

First appeared In PowerShell v5 and Windows 8.1/2012R2 with KB3000850; Automatically log code blocks if the block’s contents match on a list of suspicious commands, even if script block logging is not enabled. These suspicious blocks are logged at the “warning” level in EID 4104, unless script block logging is explicitly disabled. If script block logging is enabled, the blocks that are not considered suspicious will also be logged to EID 4104, but with “verbose” or “information” levels

- Description: :green_circle:

</details>

<details>
<summary>Rule 91807 :yellow_circle:</summary>
<br>


Why is this rule level 0?

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:

</details>

<details>
<summary>Rule 91808 :yellow_circle:</summary>
<br>

Why is this rule level 0?

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:

</details>

<details>
<summary>Rule 91809 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:


</details>

<details>
<summary>Rule 91810 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91811 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91812 :yellow_circle:</summary>
<br>

Why is this rule level 0?

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91813 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period


</details>

<details>
<summary>Rule 91814 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91815 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91816 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:


</details>

<details>
<summary>Rule 91817 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91818 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91819 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91820 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91821 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91822 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91823 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:

</details>

<details>
<summary>Rule 91824 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:

</details>

<details>
<summary>Rule 91825 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91826 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91827 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91828 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:


</details>

<details>
<summary>Rule 91829 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period


</details>

<details>
<summary>Rule 91830 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91831 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period


</details>

<details>
<summary>Rule 91832 :yellow_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :yellow_circle:
    Extra period



</details>

<details>
<summary>Rule 91833 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91834 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91835 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91836 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91837 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91838 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91839 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91840 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91841 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91842 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91843 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:


</details>

<details>
<summary>Rule 91844 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91845 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91846 :green_circle:</summary>
<br>

- Fields:
    - `scriptBlockText`: green_circle:

- Description: :green_circle:


</details>

**Comment by fabamatic** [comment]
Implemented requested changes:

Comments:

- 91807:  Doing a query using Get-ItemProperty is not alertable per se, it depends on the item that's being queried. This rule could have been merged with 91808 but it's good to have the flexibility if we ever want to use it with something other than registry keys
- 91808: Will rise level to 3
- 91812: Similar to 91807, invoking Remove-Item is not an alertable action, depends on target item or path

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/13638/commits/f6c2df678f0498decc4f9419e226412feb67e86c

***

### Results



<details>
<summary>Rule 91807 :green_circle:</summary>
<br>


Level 0 expected :green_circle:

</details>

<details>
<summary>Rule 91808 :green_circle:</summary>
<br>

Raised level to 3 :green_circle:

</details>



<details>
<summary>Rule 91812 :green_circle:</summary>
<br>

Level 0 expected :green_circle:

- Description: :green_circle:



</details>

<details>
<summary>Rule 91813 :green_circle:</summary>
<br>



- Description: :green_circle:


</details>

<details>
<summary>Rule 91814 :green_circle:</summary>
<br>



- Description: :green_circle:



</details>



<details>
<summary>Rule 91817 :green_circle:</summary>
<br>


- Description: :green_circle:



</details>



<details>
<summary>Rule 91827 :green_circle:</summary>
<br>


- Description: :green_circle:



</details>



<details>
<summary>Rule 91829 :green_circle:</summary>
<br>



- Description: :green_circle:

</details>

<details>
<summary>Rule 91830 :green_circle:</summary>
<br>


- Description: :green_circle:



</details>

<details>
<summary>Rule 91831 :green_circle:</summary>
<br>


- Description: :green_circle:


</details>

<details>
<summary>Rule 91832 :green_circle:</summary>
<br>


- Description: :green_circle:


</details>







## Conclusion :green_circle:

Everything has been fixed

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved |

All the proposed fixes and improvements have been implemented in this current development, so development is approved taking into account:

- Improve some description rules. 🟢
- Increase the alert level for some rules. 🟢
