### ISSUE TITLE
Add coverage of auto-defragmentation functionality implementation

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3472]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4          |[#14968](https://github.com/wazuh/wazuh/issues/14968)|  [#15183](https://github.com/wazuh/wazuh/pull/15183)|

## Description

This issue [#14968](https://github.com/wazuh/wazuh/issues/14968) is the second part of the development of [#12930](https://github.com/wazuh/wazuh/issues/12930), it implements the `auto-defragmentation` functionality in `wazuh-db` affecting both the global db and the agent's db. 

## Proposed test cases

- [ ] Validate auto-defragmentation functionality
  <details><summary>Tier 1 test cases</summary>

    - <details><summary>Auto defragmentation works correctly for global db</summary>

        1. Install `wazuh-manager`
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>
      
    - <details><summary>Auto defragmentation works correctly for global and agent db</summary>

        1. Install `wazuh-manager` and a wazuh-agent
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>

  </details>
  
  <details><summary>Tier 2 test cases</summary>

    - <details><summary>Auto defragmentation works correctly for global and multiple agents dbs</summary>

        1. Install `wazuh-manager` and four `wazuh-agents`
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent1_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent2_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent3_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent4_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step in each db
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value` in each db
      </details>

  </details>
  
  <details><summary>Tier 3 test cases</summary>

    - <details><summary>Auto defragmentation running in a lot of agent dbs doesn't have a big negative performance impact</summary>

        1. Install `wazuh-manager` and more than 500 `wazuh-agents`
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent1_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent2_id>.db`
          `...`
          `...`
        4. Check the CPU and RAM usage of the `manager` system
        5. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        6. Check the CPU and RAM usage of the `manager` system is not all consumed by `vaccum`
      </details>

  </details>

- [ ] Validate warning log
  <details><summary>Tier 2 test cases</summary>
    - <details><summary>Warning log is raised when current fragmentation is higher than the last one</summary>

          1. Install `wazuh-manager`
          2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
              > It could be 1 minute or 3, or any, I used 2 because it is confortable
          3. Modify the value of `current_fragmentation` to 0 in the global db
            `sqlite3 /var/ossec/queue/db/global.db`
          4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
          5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
            `sqlite3 /var/ossec/queue/db/global.db`
          6. Check the `current_fragmentation` is higher than the `last_fragmentation_value`
          7. Check the Warning log is raised
              `grep "WARN" /var/ossec/logs/ossec.log`
        </details>

      - <details><summary>Warning log is not raised when current fragmentation is lower than the last one</summary>

          1. Install `wazuh-manager`
          2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
              > It could be 1 minute or 3, or any, I used 2 because it is confortable
          3. Modify the value of `current_fragmentation` to 100 in the global db
            `sqlite3 /var/ossec/queue/db/global.db`
          4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
          5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
            `sqlite3 /var/ossec/queue/db/global.db`
          6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
          7. Check the Warning log is not raised
              `grep "WARN" /var/ossec/logs/ossec.log`
        </details>

      - <details><summary>Warning log is not raised when current fragmentation is equal than the last one</summary>

          > Im not sure that this will works, because we need to ensure that two times we will have the same fragmentation result.

          1. Install `wazuh-manager`
          2. Configure the `local_internal_options` to execute auto-defragmentation every 30 secconds
              > It could be 1 minute or 3, or any, I used 2 because it is confortable
          3. Let the `auto-defragmentation` to be executed 4 times *(wait 2 minutes)*
          4. Check the value of `current_fragmentation` in the global db
            `sqlite3 /var/ossec/queue/db/global.db`
          5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
            `sqlite3 /var/ossec/queue/db/global.db`
          6. Check the Warning log is not raised
              `grep "WARN" /var/ossec/logs/ossec.log`
        </details>

  </details>

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
