### ISSUE TITLE
Add engine event inputs tests

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3474]
| Target version | Related issue | Related PR/dev branch | QA Epic
|--------------------|--------------------|-----------------|--|
|           5.0             |          https://github.com/wazuh/wazuh-qa/issues/3470              |          https://github.com/wazuh/wazuh/issues/11334          | https://github.com/wazuh/wazuh/issues/15083

## Description

Since the team is reworking the engine, we need to cover this new engine rework. This issue will add the new tests to the qa framework and if it was necessary, the manual testing.

First of all, the engine module should be added to the framework so we could start adding modules, their tests and their cases.

## Proposed test cases

- [x] We want to test a correct event input returns a valid result, an incorrect input returns an error and an unexpected input doesn't crash the program. The module to test are:
  - [x] AWS sample logs
  - [x] JSON sample logs 
  - [x] Sample logs that contain unicode characters

## Considerations

After the research and when the first module approach is created, we will add a module for each type(input, resources, output) and a test for each scenario(events, api, etc.) and its specific Tcases.

**Comment by roronoasins** [comment]
The epic branch contains a first module that allows us to start with the engine testing design and development. So we can start from that point.

| Working branch |
| ------------------|
|       [3474-engine-input-tests](https://github.com/wazuh/wazuh-qa/tree/3474-engine-input-tests)           |

## Considerations

This first approach that has been added is not definitive, so it will change as we progress within the development process. After we design the whole modules, tests, and cases it may change. Besides, when we start with the development we need to add some missing features such as cleaning the kvdb output file between tests execution, for example. After the tests design, we will need to waste some time in add some required features and reworking some of them. Currently, the engine and the related features are handled with their binary after being compiled manually, this will change when analysisd is replaced by the engine in a testing environment.

**Comment by roronoasins** [comment]
## Modules, tests and cases list
For the tests development, we can use this list to create the modules, tests and cases:

- Events
  - Few modules logs will be sent and their output will be verified (passing is expected)
  - Wrong formatted logs will be sent and their output will be verified (failing is expected)
  - Logs with special characters will be sent (passing and failing is expected, depending with the log used)
- API (waiting for development)
- Configuration files (ruleset)
  - Few correct configuration templates
  - Wrong configuration templates: expecting to fail with proper error logging
- Cmd parameters
  - Wrong assets path
  - Wrong socket data
  - Wrong output folder (path with no permissions?)
  - Invalid environment

This list is not definitive, need some feedback and more time researching each feature that will be tested.

**Comment by roronoasins** [comment]
## 19/10/22

Some types of log has been tested today
- Flat logs
- JSON logs
- Logs with unicode values

Tomorrow this will be tested again but injecting logs in agents via localfile. It is necessary to test things like an user would do. When the environment is set up for this, more cases will be added.

**Comment by roronoasins** [comment]
## 2022/10/20

Could not see any log within the engine output using localfile feature in CentOS agent. Tomorrow will try to fix this and do it with a windows agent.

**Comment by roronoasins** [comment]
## 2022/10/21

Could set up new engine vagrant environment using API's branch. With this set up could send events to the manager via script but agents stop being able to connect or communicate. Both agent that was already connected and reporting and new ones.

**Comment by roronoasins** [comment]
## 2022/10/24
After the latest changes from the dev team, it is required to change the fixtures and modules to be able to use the engine with the pytest module. Besides, the engine now accepts messages using Unix datagrams instead of TCP. This rework and more tests and cases addition will be done after the manual testing required for these features(that block this issue).

**Comment by roronoasins** [comment]
## 20022/12/19

After the new engine's protocol research, the module testing can again send events to the socket and be able to catch them within the `alerts-ECS.json`.

AWS and Unicode logs pass the event test, but JSON doesn't. More logs types were tested from repos like:
- https://github.com/elastic/beats/tree/main/filebeat/module

Need to find out the `re` error and yaml parse one.

**Comment by roronoasins** [comment]
# 2022/12/20

Today some log cases have been added to the yaml and some python code refac was done, so now the fixtures clean/restore the environment in a better way. Now, fixtures like `control_service` and `truncate_engine_files` are used instead of using the custom fixtures we had because the engine was not integrated in the previous iteration.

Now, we have a minimal module testing structure with an `engine` testing module within the `modules` dir and some cases in `test_engine/test_events` with its conftest, test and data.

```
root@engine:/media/sf_qa/wazuh-qa/tests/integration/test_engine/test_events# python3 -m pytest test_events.py -v
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-126-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '6.2.5', 'pluggy': '1.0.0'}, 'Plugins': {'testinfra': '5.0.0', 'html': '3.1.1', 'metadata': '2.0.4'}}
rootdir: /media/sf_qa/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-2.0.4
collected 5 items                                                                                                                                                                        

test_events.py::test_engine_events[Verify AWS logs] PASSED                                                                                                                         [ 20%]
test_events.py::test_engine_events[UNICODE logs] PASSED                                                                                                                            [ 40%]
test_events.py::test_engine_events[cisco ios logs] PASSED                                                                                                                          [ 60%]
test_events.py::test_engine_events[JSON logs] PASSED                                                                                                                               [ 80%]
test_events.py::test_engine_events[logs that could break kvdb] PASSED                                                                                                              [100%]

=================================================================================== 5 passed in 9.54s ====================================================================================
root@engine:/media/sf_qa/wazuh-qa/tests/integration/test_engine/test_events#
```

> Need to verify with the dev team the last added cases `logs that could break kvdb`, they should break the engine so maybe something is wrong with the proposed samples

More cases like elasticsearch, auditd will be added so we have some extra cases.

**Comment by roronoasins** [comment]
```
root@engine:/media/sf_qa/update/wazuh-qa/tests/integration/test_engine/test_events# python3 -m pytest test_events.py -v
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-126-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '6.2.5', 'pluggy': '1.0.0'}, 'Plugins': {'testinfra': '5.0.0', 'html': '3.1.1', 'metadata': '2.0.4'}}
rootdir: /media/sf_qa/update/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-2.0.4
collected 6 items                                                                                                                                                                        

test_events.py::test_engine_events[Verify AWS logs] PASSED                                                                                                                         [ 16%]
test_events.py::test_engine_events[UNICODE logs] PASSED                                                                                                                            [ 33%]
test_events.py::test_engine_events[cisco ios logs] PASSED                                                                                                                          [ 50%]
test_events.py::test_engine_events[JSON logs] PASSED                                                                                                                               [ 66%]
test_events.py::test_engine_events[elasticsearch logs] PASSED                                                                                                                      [ 83%]
test_events.py::test_engine_events[auditd logs] PASSED                                                                                                                             [100%]

=================================================================================== 6 passed in 12.91s ===================================================================================
root@engine:/media/sf_qa/update/wazuh-qa/tests/integration/test_engine/test_events#
```

**Comment by damarisg** [comment]
Blocked by https://github.com/wazuh/wazuh-jenkins/issues/4674
