### ISSUE TITLE
Add engine resources tests

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3476]
| Target version | Related issue | Related PR/dev branch | QA Epic
|--------------------|--------------------|-----------------|--|
|           5.0             |          https://github.com/wazuh/wazuh-qa/issues/3470              |          https://github.com/wazuh/wazuh/issues/11334          | https://github.com/wazuh/wazuh/issues/15083

## Description

Since the team is reworking the engine, we need to cover this new engine rework. This issue will add the new tests to the qa framework and if it was necessary, the manual testing.

First of all, the engine module should be added to the framework so we could start adding modules, their tests and their cases.

## Proposed test cases

- [ ] We want to prove that the program’s resource utilization remains stable over time. The resources we have to check are:
  - [ ] CPU
  - [ ] Memory
  - [ ] Disk utilization (I/O saturation)
  - [ ] EPS

## Considerations

After the research and when the first module approach is created, we will add a module for each type(input, resources, output) and a test for each scenario(events, api, etc.) and its specific Tcases.

**Comment by pro-akim** [comment]
Researching about the issue and engine resources

**Comment by pro-akim** [comment]
# Update
Engine resources were under development, so preliminary tests had been conducted.
It is being asked if there was any progress in development to proceed with the tests.

It will remain on hold until further updates.

**Comment by pro-akim** [comment]
# Update
Tasks related to the engine have not made any progress yet to proceed with new testing schema.
For this reason, I'm returning the status to backlog.
