### ISSUE TITLE
VD download feed IT fails for Arch Linux 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3485]
### 4.5

| Module                | First Failure                                                                                     | Last success                                                                                        | OS    | Manager/Agent |  Report   | 
| --------------------- | ------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- | ----- | ------------- | --- |
| `test_download_feeds` | **CI**:Nightly <br> **Commit**: a3ec35d <br> **Pipeline**: Test_integration <br> **Build**: 32842 | **CI**: Nightly <br>  **Commit**: 8fec08a <br> **Pipeline**: Test_integration <br> **Build**: 32689 | CentOS | Manager       |   [Report](https://github.com/wazuh/wazuh-qa/files/981833/manager_html_report_Test_integration_B32842_20221015012612.zip) |

### 4.4

| Module                | First Failure                                                                                     | Last success                                                                                        | OS    | Manager/Agent |  Report   | 
| --------------------- | ------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- | ----- | ------------- | ------ |
| `test_download_feeds` | **CI**:Nightly <br> **Commit**: 840f754 <br> **Pipeline**: Test_integration <br> **Build**: 32944 | **CI**: Nightly <br>  **Commit**: dbdc5e9 <br> **Pipeline**: Test_integration <br> **Build**: 32794 | CentOS | Manager       | [Report](https://github.com/wazuh/wazuh-qa/files/9818349/manager_html_report_Test_integration_B32944_20221019023528.2.zip) |

## Description

The integration test `test_download_feeds` consistently fails for the Arch Linux test case:

```
----------------------------- Captured stderr call -----------------------------
2022-10-19 01:55:35,257 - wazuh_testing - ERROR - Could not find Arch Linux feed finished log
2022-10-19 01:55:35,257 - wazuh_testing - ERROR - Results accumulated: 0
2022-10-19 01:55:35,257 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call -------------------------------
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[ARCH]
======= 1 failed, 241 passed, 2 skipped, 2 xfailed in 3191.73s (0:53:11) =======
```

**Comment by Rebits** [comment]
### Update 24/10/2022

Arch Linux seems to fail using test configuration. Notice in https://github.com/wazuh/wazuh/issues/15180.
Workaround according to @MarcelKemp:
```
    <!-- Arch OS vulnerabilities -->
    <provider name="arch">
      <enabled>yes</enabled>
      <url>https://security.archlinux.org/issues/all.json</url>
      <update_interval>1h</update_interval>
    </provider>
```

**Comment by mauromalara** [comment]
## Update

### 4.4

I executed the tests in 4.4 at https://github.com/wazuh/wazuh-qa/issues/4156 and this failure is not present anymore.

### 4.5

In the last Nightly this failure is not present.

Build no.: 38464
Commit: 4cd8b7b
Build result: [manager_VD_nightly.zip](https://github.com/wazuh/wazuh-qa/files/11467397/manager_VD_nightly.zip)
Manager OS: CentOS

**Comment by damarisg** [comment]
I checked all the nightly runs of 4.4 and 4.5 and saw that VD failed the same tests.
The only difference is that changed the cases, but it is the same test.


I would like you to investigate these bugs, and fix it. You can check them in our last Nightlys.

**Comment by mauromalara** [comment]
On hold because VD is failing in the Nightly. Waiting for https://github.com/wazuh/wazuh-qa/issues/4156 to be solved

**Comment by mauromalara** [comment]
wazuh/wazuh-qa#4156 was merged, so the failures are solved. A new issue should be opened in wazuh/wazuh

**Comment by mauromalara** [comment]
wazuh/wazuh-qa#4156 was merged, so the failures are solved. A new issue should be opened in wazuh/wazuh
