### ISSUE TITLE
Check in the wazuh-dashboard app the correct OS format for macOS agents

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3494]
| Target version | Release candidate | Main release testing issue |
|--------------------|--------------------|--------------------|
|   4.4.0                 |    1            |     TBC               |

## Description

Some macOS OS versions (from Sierra to Catalina) show themselves (in the default OS information tool) as MacOS X, while their proper name is macOS. This inaccurate OS name is affecting both OS inventory information and Manager's agent list information

During the [testing performed](https://github.com/wazuh/wazuh-qa/issues/3363) for the fix introduced in `4.4.0` [Modify OS name's source for macOS](https://github.com/wazuh/wazuh/pull/14822), it was left pending (because we had no official app to test) to check that the macOS OS version appears correctly in the `wazuh-dashboard` app.

It is requested to check that all macOS agents appear with the following OS format: `macOS x.x.x`.

## Proposed checks

- [x] Check that all macOS agents (from Sierra to Monterey or Ventura if possible) are listed in the following OS format: `macOS x.x.x`.
    - [x] Check in agents overview view
    - [x] Check in inventory data view

## Expected results

All macOS agent OS should appear with the following OS format: `macOS x.x.x`.

**Comment by BelenValdivia** [comment]
17/03/2023
- Set up wazuh manager, indexer and dashboard
- Download macOS boxes (catalina and mojave)
- Research about the change

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   |  4.4 | 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS  8           | local | `generic/centos_8`|  |
| MacOS Catalina|  local | `macos_catalina`|  |
| MacOS Mojave|  local | `danimaetrix/macOS-mojave`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| CentOS  8           |  [rpm](https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.4.0-1.x86_64.rpm) |  | 
| MacOS|   |  [pkg](https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.4.0-1.pkg)|


## Status

- [x] In progress
- [ ] QA team leader approved @damarisg

**Comment by BelenValdivia** [comment]
## Testing results

### Before change
<details><summary>Incorrect OS name</summary>

1. Install the Wazuh agent and Wazuh manager prod version (4.3.10)
2. Check agent's overview view in the Wazuh dashboard

    ![macos name agent](https://user-images.githubusercontent.com/26927338/226603174-bf4139a9-86c4-41a0-b665-c6a326c988de.png)

3. Check inventory data view  in the Wazuh dashboard

    ![macos name inventory](https://user-images.githubusercontent.com/26927338/226603359-f13bf0f3-5fee-453e-b8b6-bfdb7a934f53.png)

</details>

**Comment by BelenValdivia** [comment]
### Conclusion

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
