### ISSUE TITLE
Windows MSI installer messages and WXS Warnings Review

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-qa#3500]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|        4.4.0        | https://github.com/wazuh/wazuh/issues/14716                       |                    |

## Description

The issue https://github.com/wazuh/wazuh/issues/14716 aims to minimize error messages improving the user experience. Those errors could happen when installing the Windows agent with the logging file option enabled. 

## Proposed checks

- [ ] Install the Wazuh agent using `/lv verbose.log` option and see no errors. 
- [ ] After no error check, review if the agent is installed correctly, connect and report to the manager.

**Comment by jmv74211** [comment]
This issue will be worked on https://github.com/wazuh/wazuh-qa/issues/3610
