### ISSUE TITLE
Add coverage for segmentation fault in Analysisd

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3507]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4   |    [#14923](https://github.com/wazuh/wazuh/issues/14923) |     [#15190](https://github.com/wazuh/wazuh/pull/15190)     |

## Description

This modification fixes a bug found during the PR [14138](https://github.com/wazuh/wazuh/pull/14138) validation, where `analysisd` raises a `segfault` during a log evaluation using `wazuh-logtest`.
## Proposed test cases

- [ ] Validate decoders with logtest
  
  <details><summary>test cases</summary>

  - <details><summary>logtest ssh decoder <code>disconnect(ed|ing) from user</code></summary>
    
    1. Install `wazuh-manager`
    2. Use the logtest tool to trigger the decoder
      ```
      /var/ossec/bin/wazuh-logtest
      
      2020-03-24 08:38:47.230409-0700 localhost sshd[2531]: Disconnected from user user 172.18.1.100 port 43042
      ```
    3. Check the logtest is executed correctly

    </details>

  - <details><summary>Logtest IPv6 decoder</code></summary>
    
    1. Install `wazuh-manager`
    2. Use the logtest tool to trigger the decoder
      ```
      /var/ossec/bin/wazuh-logtest -l "0000:0000:0000:0000:0000:0000:0000:0001" -d
      
      IPv6 test msg
      ```
    3. Check the logtest is executed correctly
   
    </details>

  </details>

- [ ] Validate real alert is raised
  <details><summary>test cases</summary>

  - <details><summary>SSH disconnect raise alert</code></summary>

    1. Install `wazuh-manager` 
    2. On another machine log into the manager's system by ssh
       `ssh user@MANAGER_IP` 
    3. Disconnect the ssh session to the manager's system
    4. Check the alert is raised correctly
    </details>

  </details>

**Comment by damarisg** [comment]
We decided to close them.
