### ISSUE TITLE
Create E2E tests to cover the Vulnerability Detector refactor

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3519]
| Target version | Related issue | Related PR/dev branch  | QA branch | PR QA |
|---|-------|---|--|--|
| - | #3306 | - |3456-e2e-tests-vuln-detector| https://github.com/wazuh/wazuh-qa/pull/3501

## Description

Once the test cases have been defined in the [planning process](https://github.com/wazuh/wazuh-qa/issues/3384), it is necessary to automate those by adding them to our repository.

## Proposed test cases

- [ ] Check that a vulnerable package is indexed after its upgrade
- [ ] Check that a vulnerable package is indexed after updating a feed
- [ ] Check that a vulnerable package is marked as `solved` in the Indexer when upgrading to a fixed version
- [ ] Check that the vulnerabilities are indexed correctly in the Master node when 2+ agents report those to the Worker nodes
- [ ] Check that the vulnerabilities are indexed in the Indexer node (arch: 1 Indexer + Dashboard, 1 Master, 2 Workers, 2 Agents)

First Instance: 
- [x] https://github.com/wazuh/wazuh-qa/issues/3456
- [x] #3521

Second Instance:

**Comment by BelenValdivia** [comment]
Testing will be redefined
