### ISSUE TITLE
Validate scans and database to VD

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3526]
| Target version | Related issue | Related PR/dev branch | QA branch | PR QA |
|---|-------|---|--|--|
| - | #3306 | - | 3309-vd-refactor-scan| https://github.com/wazuh/wazuh-qa/pull/3498

The tests that are proposed in the issue are related to event-driven scans in the Vulnerability detector refactor.

### Proposed tests (IT):

- New scan in each new package installed
- New scan in each updated package
- New scan on every package removed
- New scan in each hotfix installed
- New scan on every hotfix removed
- Validate that a new scan is done in each feed update
- Check that the scan result is indexed

## Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/3309
- [x] #3521
- [ ] Add issues ..

**Comment by BelenValdivia** [comment]
Testing will be redefined
