### ISSUE TITLE
Avoid usage of deployment variables on upgrade

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#3529]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.3.10              |        https://github.com/wazuh/wazuh/issues/15245                |           https://github.com/wazuh/wazuh/pull/15262         |

## Description

In https://github.com/wazuh/wazuh/issues/15245 we changed the conditions used to execute the script used to set the deployment variable.

## Proposed checks

- [x] Install package without deployment variables
- [x] Install package using deployment variables
- [x] Upgrade package without deployment variables
- [x] Upgrade package using deployment variable

## Steps to reproduce

Indicated here:
https://github.com/wazuh/wazuh/issues/15245#issue-1424247032
## Expected results

On installation, the package should work as it did before.
On upgrade, the `ossec.conf` should not change in any case.

**Comment by Rebits** [comment]
## Testing results :red_circle:


<details>


<summary> Bug replication:  Upgrade 4.3.8->4.3.9</summary

<blockquote>


As https://github.com/wazuh/wazuh/issues/15245 specified, multiple config-profiles configurations appears if an upgrade is performed. 

<details>


<summary> <code> ossec.conf </code></summary> 



```
  <client>
    <server>
      <address>0.0.0.0</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```

</details>


Also, the upgrade process allows deployment parameters (these parameters do not change the current configuration)
```
PS C:\Users\qa\Downloads> .\wazuh-agent-4.3.9-1.msi /q WAZUH_MANAGER="199.0.0.2" WAZUH_REGISTRATION_SERVER="10.0.0.2" WAZUH_REGISTRATION_PASSWORD="TopSecret" WAZUH_AGENT_GROUP="my"
```


<details>


<summary> <code> ossec.conf </code></summary> 

```
<client>
    <server>
      <address>10.0.0.2</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <enrollment>
        <enabled>yes</enabled>
        <manager_address>10.0.0.2</manager_address>
        <groups>my</groups>
    </enrollment>
  </client>
```
</details>

</blockquote>


</details>


<details>

  <summary> Config profile duplication after upgrade :red_circle: </summary>>
  
  <blockquote>

<details>

<summary> Upgrade 4.3.8->4.3.9 :green_circle:</summary> 

The `config-profile` is not duplicated anymore.

```
<client>
    <server>
      <address>10.0.0.2</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```

</details>


<details>

<summary> Upgrade 4.3.9->4.3.9 :red_circle:</summary> 

It is possible to upgrade to the same version using the quiet option `/q`: ` .\wazuh-agent-4.3.10-0.commite328665.msi /qn`

In case of an upgrade to the same package, the config-profile is duplicated. This is not replicable if the GUI is used.

```
<client>
    <server>
      <address>10.0.0.2</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```

</details>


</blockquote>

</details>


<details>

  <summary> Deployment variables for upgrade :green_circle: </summary>>
  
  <blockquote>


<details>

<summary> Upgrade 4.3.8->4.3.9 :green_circle:</summary> 

`ossec.conf` does not change after the upgrade with deployment parameters

**Commands**:
```
PS C:\Users\qa\Downloads> .\wazuh-agent-4.3.8-1.msi /q WAZUH_MANAGER="10.0.0.2"
PS C:\Users\qa\Downloads> .\wazuh-agent-4.3.10-0.commite328665.msi /q WAZUH_MANAGER="199.0.0.2" WAZUH_REGISTRATION_SERVE
R="10.0.0.2" WAZUH_REGISTRATION_PASSWORD="TopSecret" WAZUH_AGENT_GROUP="my"
```

```
  <client>
    <server>
      <address>10.0.0.2</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```
</details>


<details>

<summary> Upgrade 4.3.9->4.3.9 :red_circle:</summary> 

It is possible to upgrade to the same version using the quiet option `/q`: ` .\wazuh-agent-4.3.10-0.commite328665.msi /qn`

In case of an upgrade to the same package, deployment parameters change the configuration. This is not replicable if the GUI is used.

```
  <client>
    <server>
      <address>10.0.0.2</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <config-profile>windows, windows2016, windows-server, windows-server-2016</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <enrollment>
        <enabled>yes</enabled>
        <manager_address>10.0.0.2</manager_address>
        <groups>my</groups>
    </enrollment>
  </client>
```

</details>


</blockquote>




</details>

**Comment by Rebits** [comment]
### Update - 03/11/2022
- [First manual testing](https://github.com/wazuh/wazuh-qa/issues/3529#issuecomment-1302264666)

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15262/commits/cf6db3c56fa888a129d601c34993ab10e77de131

***

## Results


<details>

  <summary> Install: No deployment variables  :large_blue_circle: </summary>


</details>


<details>

  <summary> Install: Deployment variables :large_blue_circle:</summary>>


</details>


<details>

  <summary> Upgrade: No deployment variables :large_blue_circle: </summary>>
  
  <blockquote>

<details>

<summary> Upgrade 4.3.8->4.3.9 :large_blue_circle:</summary> 


</details>


<details>

<summary> Upgrade 4.3.9->4.3.9 :large_blue_circle:</summary> 



</details>


</blockquote>

</details>


<details>

  <summary> Upgrade: Deployment variables :large_blue_circle: </summary>>
  
  <blockquote>


<details>

<summary> Upgrade 4.3.8->4.3.9 :large_blue_circle:</summary> 


</details>


<details>

<summary> Upgrade 4.3.9->4.3.9 :large_blue_circle:</summary> 

</details>


</blockquote>




</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 

The development has been approved taking into account the following considerations:

***(1)*: Errors seem to persist in case of the upgrade using the same version.** 🟢 

This has been reported and fixed in this development https://github.com/wazuh/wazuh/pull/15262/commits/cf6db3c56fa888a129d601c34993ab10e77de131
