### ISSUE TITLE
Refactor Agentd IT for multi-server case

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#3536]
| Version | Related issue |
| --- | --- |
| 4.4.0 | [#3429](https://github.com/wazuh/wazuh-qa/issues/3429) | 

### Description

Agentd tests present an unstable behavior due to the use of simulators (see https://github.com/wazuh/wazuh-qa/issues/3429). This issue aims to refactor these tests as a `system` test instead of an `integration` test. At this point, it has decided to skip Agentd test till refactoring is done.

### Proposed checks

- [ ] Perform system test
- [ ] Replace socket server simulator

**Comment by damarisg** [comment]
We decided to close them.
