### ISSUE TITLE
Validate the logs modification in EPS `analysisd` 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3549]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.4    |   [#15188](https://github.com/wazuh/wazuh/issues/15188) | [#15278](https://github.com/wazuh/wazuh/pull/15278)  |

## Description

The goal of this pr is avoid multiple warnings come up, when starting the wazuh-manager with the EPS limitation block but without the `<maximum>` tag.

## Proposed checks

- [x] Different EPS logs should be raised in `ossec.log`
  <details><summary>Test cases</summary>

  - <details><summary>EPS limit disabled</summary>

    1. Install `wazuh-manager`
    2. Remove or comment the `EPS` block 
        ```xml
        <!--limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits-->
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        `expected`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/02 11:35:01 wazuh-analysisd: INFO: EPS limit disabled
        ```
    </details>

  - <details><summary>EPS limit enabled</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block correctly 
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        `expected`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/02 11:41:35 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '30'
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>maximum</code> tag</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block without the tag `<maximum>`
        ```xml
        <limits>
          <eps>
            <!-- <maximum>50</maximum> -->
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        `expected`
        ```log
        grep "WARNING" /var/ossec/logs/ossec.log

        2022/11/02 11:39:03 wazuh-analysisd: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>timeframe</code> tag</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block without the tag `<timeframe>`
        > In this case, it will use the default timeframe: 10
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <!-- <timeframe>30</timeframe> -->
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        `expected`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/02 11:42:26 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '10' 
        ```
    </details>

  </details>

### Required installation methods
- [x] Fresh install
- [x] Upgrade

## Expected results

All the logs are raised correctly

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [b68fd32](https://github.com/wazuh/wazuh/pull/15278/commits/b68fd325ea3e96939f707dbe21606cd4db6a0bb8)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commitb68fd32_amd64.deb)||       

### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Testing results

## Unfixed

<details><summary>Error repoduction</summary>
  
  1. Install `wazuh-manager` v4.4.0
  2. Config the `EPS` block without the tag `<maximum>`
      ```xml
      <limits>
        <eps>
          <!-- <maximum>50</maximum> -->
          <timeframe>30</timeframe>
        </eps>
      </limits>
      ```
  3. Restart the `wazuh-manager`
  4. Check the `ossec.log`
      ```log
      2022/11/03 14:16:53 wazuh-maild: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      2022/11/03 14:16:53 wazuh-maild: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      2022/11/03 14:16:53 wazuh-analysisd: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      2022/11/03 14:16:53 wazuh-remoted: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      2022/11/03 14:16:53 wazuh-monitord: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      2022/11/03 14:16:54 wazuh-testrule: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
      ```
</details>

## Upgrade

<details><summary>Upgrade process :green_circle:</summary>

- Upgrade `wazuh-manager `
  ```log  
  dpkg -i wazuh-manager_4.4.0-0.commitb68fd32_amd64.deb 

  dpkg: warning: downgrading wazuh-manager from 4.4.0-1 to 4.4.0-0.commitb68fd32
  (Reading database ... 91854 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commitb68fd32_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commitb68fd32) over (4.4.0-1) ...
  Setting up wazuh-manager (4.4.0-0.commitb68fd32) ...
  Processing triggers for systemd (245.4-4ubuntu3.17) ...
  ```
</details>

<details><summary>Different EPS logs should be raised in <code>ossec.log</code> :green_circle:</summary>

  - <details><summary>EPS limit disabled :green_circle:</summary>

    1. Remove or comment the `EPS` block 
        ```xml
        <!--limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits-->
        ```
    2. Restart the `wazuh-manager`
    3. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:27:43 wazuh-analysisd: INFO: EPS limit disabled
        ```
    </details>

  - <details><summary>EPS limit enabled :green_circle:</summary>

    1. Config the `EPS` block correctly 
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    2. Restart the `wazuh-manager`
    3. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:33:41 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '30'
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>maximum</code> tag :green_circle:</summary>

    1. Config the `EPS` block without the tag `<maximum>`
        ```xml
        <limits>
          <eps>
            <!-- <maximum>50</maximum> -->
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    2. Restart the `wazuh-manager`
    3. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "WARNING" /var/ossec/logs/ossec.log

        2022/11/03 14:35:26 wazuh-analysisd: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>timeframe</code> tag :green_circle:</summary>

    1. Config the `EPS` block without the tag `<timeframe>`
        > In this case, it will use the default timeframe: 10
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <!-- <timeframe>30</timeframe> -->
          </eps>
        </limits>
        ```
    2. Restart the `wazuh-manager`
    3. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:36:58 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '10'
        ```
    </details>

</details>



## Fresh install

<details><summary>Different EPS logs should be raised in <code>ossec.log</code> :green_circle:</summary>

  - <details><summary>EPS limit disabled :green_circle:</summary>

    1. Install `wazuh-manager`
    2. Remove or comment the `EPS` block 
        ```xml
        <!--limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits-->
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:39:59 wazuh-analysisd: INFO: EPS limit disabled
        ```
    </details>

  - <details><summary>EPS limit enabled :green_circle:</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block correctly 
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:41:09 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '30'
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>maximum</code> tag :green_circle:</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block without the tag `<maximum>`
        ```xml
        <limits>
          <eps>
            <!-- <maximum>50</maximum> -->
            <timeframe>30</timeframe>
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "WARNING" /var/ossec/logs/ossec.log

        2022/11/03 14:42:33 wazuh-analysisd: WARNING: EPS limit disabled. The maximum value is missing in the configuration block.
        ```
    </details>

  - <details><summary>EPS limit enabled without <code>timeframe</code> tag :green_circle:</summary>

    1. Install `wazuh-manager`
    2. Config the `EPS` block without the tag `<timeframe>`
        > In this case, it will use the default timeframe: 10
        ```xml
        <limits>
          <eps>
            <maximum>50</maximum>
            <!-- <timeframe>30</timeframe> -->
          </eps>
        </limits>
        ```
    3. Restart the `wazuh-manager`
    4. Check the `INFO` message is raised in `ossec.log`
        ```log
        grep "INFO" /var/ossec/logs/ossec.log

        2022/11/03 14:43:29 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '10'
        ```
    </details>

</details>

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.

**Comment by jmv74211** [comment]
There is an integration test that is failing (see [this checkrun](https://github.com/wazuh/wazuh/pull/15278/checks?check_run_id=9255479856)). 

```
=========================== short test summary info ============================
FAILED test_analysisd/test_limit_eps/test_configuration.py::test_missing_configuration[missing maximum]
========= 1 failed, 43 passed, 57132 deselected in 2355.22s (0:39:15) ==========
```

It is requested to be updated.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
