### ISSUE TITLE
Unstable GCloud test which depend on the system datetime

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#3552]
## Description
The test `test_gcloud/test_functionality/test_day_wday.py::test_day_wday_multiple[get_configuration5-tags_to_apply2]` presents an unstable behavior when it is executed around the time 23:59. 

### Current behavior

The test failed with the current error message:

```
test_gcloud/test_functionality/test_day_wday.py:281: in test_day_wday_multiple
    assert next_scan_time.day == (today + datetime.timedelta(days=time_interval)).day
E   assert 12 == 11
E     +12
E     -11
```
And, it is owing to the test before being executed, stores system Datetime in global variables which are used inside test cases. When the Datetime is around 23:59 and the test cases are executed after 00:00, the test cases fail.

### Expected behavior

As the following tests depend on the DateTime to configure the `ossec.conf` file, it is expected that a function fixture takes the DateTime to configure Wazuh and store the required variables.

**Comment by QU3B1M** [comment]
# Task result: No fix needed :rocket: 

The `test_day_wday.py` gcloud's Integration tests cases were executed locally resulting on success without any error. Anyway it is important to mention that there are 30 skipped cases and 3 xfailed.

## Executions

| Test path                 | OS     | Installation   | Executions                |
|---------------------------|-----------|-------------|-------------|
| `test_gcloud/test_functionality/test_day_wday.py`         | Ubuntu | manager    |        [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480613/report.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480615/report1.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480616/report2.zip)                    | 
|  `test_gcloud/test_functionality/test_day_wday.py`        | Ubuntu | agent  |  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480628/report.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480630/report1.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11480631/report2.zip)            |
