### ISSUE TITLE
Restrict agent upgrade module configuration to local settings

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3558]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.3.10                        |  |[wazuh#15259](https://github.com/wazuh/wazuh/pull/15259)|

## Description

This PR aims to prevent the agent from parsing <agent-upgrade> configuration from file agent.conf.

## Proposed checks
- [x] The `<agent-upgrade>` block is not parsed when defined at _agent.conf_.

## Steps to reproduce

- Put an `<agent-upgrade>` stanza into file _agent.conf_.
- Check that the agent applied that via API request or behavior change.

## Expected results

The agent must not parse `<agent-upgrade>` from _agent.conf_.

**Comment by juliamagan** [comment]
## Testing results

<details>
<summary><code>agent-upgrade</code> is parsed from <code>agent.conf</code> before the fix :green_circle:</summary>
<br>

- Initial configuration:

    - `curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H "Authorization: Bearer $TOKEN"`

    ```json
    {
        "agent-upgrade": {
           "enabled": "yes",
           "ca_verification": "yes",
           "ca_store": [
              "etc/wpk_root.pem"
           ]
        }
    }
    ```

- Configuration change:

    - `/var/ossec/etc/shared/default/agent.conf`:

    ```xml
    <agent-upgrade>
      <enabled>no</enabled>
    </agent-upgrade>
    ```

    - `curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H "Authorization: Bearer $TOKEN"`

    ```json
    {
        "agent-upgrade": {
           "enabled": "no",
           "ca_verification": "yes",
           "ca_store": [
              "etc/wpk_root.pem"
           ]
        }
    }
    ```

</details>

<details>
<summary><code>agent-upgrade</code> isn't parsed from <code>agent.conf</code> after the fix :green_circle:</summary>
<br>

- Initial configuration:

    - `curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H "Authorization: Bearer $TOKEN"`

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "etc/wpk_root.pem"
          ]
       }
    }
    ```

- Configuration change:

    - `/var/ossec/etc/shared/default/agent.conf`:

    ```xml
    <agent-upgrade>
      <enabled>no</enabled>
    </agent-upgrade>
    ```

    - `curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H "Authorization: Bearer $TOKEN"`

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "etc/wpk_root.pem"
          ]
       }
    }
    ```

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly after the proposed fixes.
