### ISSUE TITLE
Add test cases to Syscollector integration tests

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3561]
## Description

Test that all data gathered by Syscollector is correctly stored in a database by WazuhDB and sent to the manager.

## Tasks

- [x] Define test cases
- [ ] Create tests modules and functions

**Comment by mauromalara** [comment]
## Update 28/12/2022

- Created branch
- Started creating the test

**Comment by mauromalara** [comment]
## Update 16/01/2023

- Talked with Nico about Syscollector functioning
- Analyzed the fields of each scan to be tested

**Comment by mauromalara** [comment]
## Update 17/01/23

<details><summary>Analysis</summary>

<br>

Syscollector gathers information about the host and sends it to Wazuh DB:
- In the first scan it sends all fields for each type of scan (hardware, os, ports, etc.)
- In the second scan it sends only the fields that have changed from the previous scan. For instance: If a package is upgraded, then Syscollector will send certain fields to be "upserted" in the Packages table (not all the information about the upgraded package)

</details>

<details><summary>Design</summary>

<br>

```
Given that the Manager has Syscollector enabled
And the unnecessary modules are disabled
And the Manager had not been started previously
When the Manager is started for the first time
Then the first scan is started
When the scan finished
Then Syscollector sends all info to Wazuh DB to store it (for each scan)
And Wazuh DB stores all that info
```

```
Given that the Manager has Syscollector enabled
And the scan interval is 40 seconds
And the unnecessary modules are disabled
And a previous scan was done
And a package was upgraded
When 40 seconds have passed from the first scan
Then the second scan is started
When the scan finished
Then a delta is sent to Wazuh DB
And Wazuh DB updates the package's information
```

</details>

**Comment by mauromalara** [comment]
## Update 18/01/23

- Tried to pick changes from #3545 
- Talked with Damian and Victor for them to help me with git
  - Copied each change manually
- Create multiple callbacks to check the first scan of syscollector

**Comment by mauromalara** [comment]
## Update 19/01/23

- On hold due to a change in priorities

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
