### ISSUE TITLE
Ubuntu Linux 20.04 SCA Policy rework - corrected checks

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3567]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.0               |         #3391               |       https://github.com/wazuh/wazuh/pull/15070            |

### Changed checks

- 1.4.4 (l 654) - rule reduce ! and * to \p regexp to solve * as char.
- 1.5.4 (l 726-729) - rule improve grep command to avoid dark corners.
- 1.6.1.3 (l 788) - rule says r: but must be n:
- 5.5.1.1 (l 3642) - rule reduce ! and * to \p regexp to solve * as char.
- 5.5.1.2 (l 3663) - rule reduce ! and * to \p regexp to solve * as char.
- 5.5.1.3 (l 3681) - rule reduce ! and * to \p regexp to solve * as char.
- 5.5.1.4 (l 3701) - rule reduce ! and * to \p regexp to solve * as char.

**Comment by juliamagan** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |https://github.com/wazuh/wazuh/pull/15070/commits/cf102359b7427d905a0db1b9114336ed5aea3d9c|

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04    | Vagrant |    qactl/ubuntu_20_04   |

### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commitcf10235_arm64.deb)             

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion

**Comment by juliamagan** [comment]
## Testing results

<details>
<summary>1.4.4 Ensure authentication required for single user mode (Automated)</summary>
<br>


</details>

<details>
<summary>1.5.4 Ensure core dumps are restricted (Automated)</summary>
<br>


</details>

<details>
<summary>1.6.1.3 Ensure all AppArmor Profiles are in enforce or complain mode (Automated)</summary>
<br>


</details>

<details>
<summary>5.5.1.1 Ensure minimum days between password changes is configured (Automated)</summary>
<br>


</details>

<details>
<summary>5.5.1.2 Ensure password expiration is 365 days or less (Automated)</summary>
<br>


</details>

<details>
<summary>5.5.1.3 Ensure password expiration warning days is 7 or more (Automated)</summary>
<br>


</details>

<details>
<summary>5.5.1.4 Ensure inactive password lock is 30 days or less (Automated)</summary>
<br>


</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| ⚫ |Discarded |

Some improvements were reported, but after speaking with the development team, it has been verified that they do not apply, and that the initial state is correct:

**(1) Requested some improvements in rules** ⚫

- 1.4.4: Add `^root:\$\d.`check.
- 5.5.1.4: The rule for inactive has double quotes.
