### ISSUE TITLE
Add the integration tests for VD 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3574]
| Target version | Related PR/dev branch |Epic QA | QA branch | PR QA |
|---|-------|---|--|--|
| - | - |  https://github.com/wazuh/wazuh-qa/issues/3525 | 3491-vd-data-integrity| https://github.com/wazuh/wazuh-qa/pull/3518

## Description 

It is necessary to integration test the data integrity. 

**Cases**:

- Check that the package information in the scan result matches the information of the downloaded content
- Check that the hotfix information in the scan result matches the information of the downloaded content
- Check that only specific sections of the feed are updated (in the local DB) when some deltas are downloaded
- Check that the downloaded content is correctly saved in the manager's local database

**Comment by Dwordcito** [comment]
Since there is an imminent refactor, we are going to close this issue since it deals with legacy VD testing.
