### ISSUE TITLE
Check fix to Windows 11 agent installation error

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-qa#3578]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|     4.3.10         |   https://github.com/wazuh/wazuh/issues/15216                     |                    |

## Description

An error was reported while installing the Wazuh agent in Windows 11. The investigation founds that, in those hosts with an incorrect VMI status, the error can occur so the installation could fail. 

## Proposed checks

The following OS needs to be tested: Windows XP, 2003, Vista, 2008, 7, 2008R2, 8, 2012, 8.1, 2012R2, 10, 2016, 2019, 2022, 11
Two scenarios: 
- OS with disabled WMI permissions.
- OS with enabled WMI permissions.

Installation methods: Using GUI and quiet commands with logs should work fine.

## Steps to reproduce

Win+R, go to wmimgmt.msc, root/cimv2, Security, and mark Deny permissions in Authenticated users. 
![image](https://user-images.githubusercontent.com/3830293/201072924-27066fd2-1493-4e5d-8fb5-f38ceff9885c.png)
![image](https://user-images.githubusercontent.com/3830293/201072948-9b102310-9f30-4140-ba9b-5e2e0af3e39f.png)
![image](https://user-images.githubusercontent.com/3830293/201072982-d9bb0931-1d76-4681-a4b8-4f23f74ff553.png)
![image](https://user-images.githubusercontent.com/3830293/201073185-5f301f91-a1b7-435d-a94d-6d59831f4a5a.png)
Thanks, @okynos for the screenshots. 
## Expected results

Installation and upgrades should be completed without problems. Further, in the disabled WMI permissions scenario, the installation using logs should have lines explaining that the WMI implementation couldn't be fetched and the installation continues.

**Comment by Rebits** [comment]
### Update - 10/11/2022
- Waiting development
- Preparing testing environment: Windows7/10/11/Vista/XP

**Comment by fedepacher** [comment]
### Update - 10/11/2022
- Waiting development
- Preparing testing environment: Windows2003/2008/2008R2/8/8.1

**Comment by jmv74211** [comment]
This issue is no longer included in 4.3.10.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
