### ISSUE TITLE
QA Planning: Add protection for unstrusted libraries load

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3580]
## Description

This problem aims to investigate [Add protection for unstrusted libraries load](https://github.com/wazuh/wazuh/issues/15327) to define the test cases to be carried out.

There is a lack of functionality for Linux port inventory.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results (WIP)

<details><summary>Research the applied change.</summary>

- This issue aims to add protections, to prevent the loading of libraries that are not trusted. The main idea is that we only load libraries that are trusted by a CA. This change affects Windows OS.

</details>

<details><summary>Research if we have a test for this case.</summary>

 - We don't have installation tests in `wazuh-qa` repository

</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

  <details><summary>Test cases </summary>
  
 > Note I: Fresh install and upgrade must be tested with both package and from sources generated installers

 > Note II: We need to test this on all versions of Windows from Windows XP to now.
   
  - <details><summary>Upgrade from 4.4 to Core branch</summary>
  
      1.  Upgrade wazuh agent
      2.  Check that binaries are loading trusted libraries with  https://hshrzd.wordpress.com/pe-bear/
           
      </details>
  
  - <details><summary>Fresh install Windows- Core branch</summary> 
  
      1.  Install  wazuh-agent
      2. Check that binaries are loading trusted libraries with https://hshrzd.wordpress.com/pe-bear/ 
       
      </details>

   - <details><summary>Run regression tests to check all is working correrctly</summary> 
  
      1.  Run pipeline https://ci.wazuh.info/job/Test_integration_launcher/ 
       
      </details>
  </details>
</details>
   
<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues. </summary>

- Installation tests

</details>
