### ISSUE TITLE
Test Alpine compilation

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3586]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4.0             | https://github.com/wazuh/wazuh/issues/15224                       | https://github.com/wazuh/wazuh/pull/15339                  |

## Description
This Issue aims to test the fix done to ensure that the agent can be built properly on Alpine Linux on different architectures.

## Proposed checks
- [x] Agent tests
   - [x] Build Agent from sources on:
      - [x] amd64
      - [x] i386
      - [x] arm64 (arm64v8)
      - [x] arm32 (arm32v7)
      - [x] ppc64le
   - [x] Agent Clean installed 

## Steps to reproduce

1. Download repo

```
curl -Ls https://github.com/wazuh/wazuh/tarball/15224-fix-compilation-errors | tar xz
cd wazuh-wazuh-30ebff2/src/
```
2. Build Agent

```
make deps TARGET=agent EXTERNAL_SRC_ONLY=yes
make -j$(nproc) TARGET=agent
```
3. Start Agent/manger

## Expected results
Agent is built and installed sucessfully

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/commit/30ebff2c46598fafd3dbbfd48d0be0ff226d4c4a | 



### Testing environment

| OS | OS version | Architecture | Deployment | Image/AMI 
|-- |-- |-- |--|--|
|Alpine Linux | x86_64 | `Local \| Docker` | qactl/centos_8

### Tested packages

| Arch | Package
|-- |--|


### Conclusion 

### Status

- [ ] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @chemamartinez

**Comment by Deblintrake09** [comment]
<details><summary> Build and Install Agent x86_64 :green_circle: </summary>

1. Clone repository
```
curl -Ls https://github.com/wazuh/wazuh/tarball/15224-fix-compilation-errors | tar xz
cd wazuh-wazuh-30ebff2/src/
```
2. Build Agent
```
    CFLAGS            -pthread -Iexternal/libdb/build_unix/ -Iexternal/pacman/lib/libalpm/ -Iexternal/libarchive/libarchive -Wl,--start-group -Iexternal/audit-userspace/lib -DNDEBUG -O2 -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DLinux -DINOTIFY_ENABLED -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DALPINE -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_AUDIT -DCLIENT -pipe -Wall -Wextra -std=gnu99 -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include -Iexternal/bzip2/ -Ishared_modules/common -Ishared_modules/dbsync/include -Ishared_modules/rsync/include -Iwazuh_modules/syscollector/include  -Idata_provider/include  -Iexternal/libpcre2/include -Iexternal/rpm//builddir/output/include 
    LDFLAGS           '-Wl,-rpath,/../lib' -pthread -lrt -ldl -O2 -Lshared_modules/dbsync/build/lib -Lshared_modules/rsync/build/lib  -Lwazuh_modules/syscollector/build/lib -Ldata_provider/build/lib
    LIBS              -lintl -lrt -ldl -lm 
    CC                gcc
    MAKE              make
make[1]: Leaving directory '/wazuh/src'

Done building agent
```
3. Install Agent using script
```
# ./install.sh

    LIBS              -lintl -lrt -ldl -lm 
    CC                gcc
    MAKE              make
make[1]: Leaving directory '/wazuh/src'

Done building agent

Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


 - Unknown system. No init script added.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---
```
4. Check agent's status
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.0"
WAZUH_REVISION="40400"
WAZUH_TYPE="agent"


# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.4.0...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
```
> Check on Manager
```
# /var/ossec/bin/agent_control -i 004

Wazuh agent_control. Agent information:
   Agent ID:   004
   Agent Name: d41f583a9756
   IP address: any
   Status:     Active

   Operating system:    Linux |d41f583a9756 |5.14.0-1054-oem |#61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 |x86_64
   Client version:      Wazuh v4.4.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1668459823

   Syscheck last started at:  Mon Nov 14 21:02:56 2022
   Syscheck last ended at:    Mon Nov 14 21:02:56 2022

```

</details>

**Comment by Deblintrake09** [comment]
# Update 2022/11/18
- Try to build agent in ppcle64
- Fix CMake dependencies issue
- Try to build or install package 🔴 - Ask Core

**Comment by Deblintrake09** [comment]
### Update 2022/11/22
- CICD team gave ETA for 2022/11/25

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

Everything seems to be working properly.
