### ISSUE TITLE
Review and upgrade versions of specific dependencies

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3588]
We want to know the purpose of the [py](https://pypi.org/project/py/) dependency appearing explicitly in the [requirements.txt](https://github.com/wazuh/wazuh-qa/blob/4.4/requirements.txt#L20) file.

```
py~=1.10.0
```

It seems that this dependency can be used by pytest, but in version 7.2.0 it has been removed. In our case, we have the following versions:

```
pytest==6.2.2 ; python_version <= "3.9"
pytest==7.1.2 ; python_version >= "3.10"
```

It would be nice to study if we can bump the pytest version to `>=7.2.0`.

In general, it is requested to investigate the following:

- If we can remove the dependency on `py` (check that no test is broken)
- Study if we can upgrade the pytest version to `>=7.2.0` for python versions `>=3.6.0` (check that no test is broken for those versions, testing in our testing environments).

**Comment by davidjiglesias** [comment]
To be done in scheduled security scans.
