### ISSUE TITLE
QA Planning: Agents are wrongly reporting IPv6 as primary IP

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3590]
# Description

This problem aims to investigate [Agents are wrongly reporting IPv6 as primary IP](https://github.com/wazuh/wazuh/issues/14988) to define the test cases to be carried out.

## Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

The changes will be tested manually.

- [ ] #3611

**Comment by mauromalara** [comment]
## Update 17/11/2022

### Research if we have a test for this case
- Currently, we don't provide tests to check this behavior

### Define the test cases
- Test cases (tier 0):
  - Interface with IPv6 gateway (⚠️ **Sysinfo module doesn't support this, so can't test. Development issues**: [here](https://github.com/wazuh/wazuh/issues/11614) and [here](https://github.com/wazuh/wazuh/issues/11615))
    - IPv4 address configured
    - No IPv4 address configured
    - IPv6 address configured
  - Interface with IPv4 gateway
    - IPv6 address configured
    - No IPv6 address configured
    - IPv4 address configured
  - Interface with no gateway
    - IPv4 address configured
    - IPv6 address configured
    - Both types of IP addresses

### Test levels

- Integration tests:
  - Check that `wazuh-agentd` stores the correct IP provided by `wazuh-modulesd`

**Comment by mauromalara** [comment]
The changes will be tested manually.

- [ ] QA Testing - Agents are wrongly reporting IPv6 as primary IP
