### ISSUE TITLE
Investigate and fix `GCP` ITs failures

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3593]
During the `4.3.10` test integration results, the `GCP` tests failed (see https://github.com/wazuh/wazuh/issues/15376#issuecomment-1315198988) and after relaunching those tests, they failed again consistently.

A manual testing was done, and everything was working as expected, so we need to investigate why these tests are failing and fix them.

Based on the https://github.com/wazuh/wazuh/issues/15376#issuecomment-1315250753 results, it seems that there has been a problem in the integration test when uploading the messages during the execution or that these messages were consumed by a process outside the execution of the tests. It will be necessary to investigate exactly what the reason was.

**Comment by QU3B1M** [comment]
# Task result: No fix needed :rocket: 

The `test_gcloud/test_functionality/` Integration tests were executed locally on wazuh `v4.5.0` and `v4.3.11` resulting on success without any error, it may be fixed on a previous patch.

## Executions

| Test path                 |  Wazuh version        |  OS    | Executions                |
|---------------------------|-----------|-------------------|---------------------------|
| test_gcloud/test_functionality/  | v4.3.11    | Ubuntu 20.04           |   [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550007/report.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550008/report1.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550009/report2.zip)  |
| test_gcloud/test_functionality/  | v4.5.0    | Ubuntu 22.04           |  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550016/report.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550017/report1.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11550018/report2.zip)                                                     |
