### ISSUE TITLE
Add request remoted configuration test

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3603]
| Target version | Related issue | 
|--------------------|--------------------|
|            4.4            |           #3112             |           

## Description
We need to add a test that checks if the remoted configuration, requested with the API is the expected.

## Proposed test cases

- [x] Get and check the default configuration
- [x] Get and check custom configuration

**Comment by juliamagan** [comment]
## Update 25/11/2022

Worked on the test based on the `test_limits_eps` structure.

**Comment by juliamagan** [comment]
##Update 23/12/2022

Completed test with commented changes applied would crash because there are `internal_options` that do not match in the documentation, API response, or in the `internal_options.conf` file. Although the failed tests are marked as `xfail`, so it could be merged. Waiting for response from the development team.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
