### ISSUE TITLE
Add request wazuh-db configuration test 

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3605]
| Target version | Related issue | 
|--------------------|--------------------|
|            4.4            |           #3112             |           

## Description
We need to add a test that checks if the wazuh-db configuration, requested with the API is the expected.

## Proposed test cases

- [x] Get and check the default configuration
- [x] Get and check custom configuration

**Comment by juliamagan** [comment]
## Update 23/12/2022

Found expected endpoints in https://github.com/wazuh/wazuh/issues/14229. 
We need to implement this test when #3603 and #3604 are implemented.

**Comment by juliamagan** [comment]
## Update 13/01/2023

Missing internal options:
- wazuh_db.rlimit_nofile
- wazuh_db.debug

Could be related to: 
- https://github.com/wazuh/wazuh/issues/15694

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
