### ISSUE TITLE
Add manager remoted statistics test

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3608]
| Target version | Related issue | 
|--------------------|--------------------|
|            4.4            |           #3112             |           

## Description
We need to add a test that checks the manager remoted statistics.

## Proposed test cases

- [ ] API request
- [ ] Socket

**Comment by juliamagan** [comment]
## Update 13/01/2023

Missing internal options:
- wazuh_db.rlimit_nofile
- wazuh_db.debug

Could be related to: https://github.com/wazuh/wazuh/issues/15694

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
