### ISSUE TITLE
Bump Ansible and Puppet to 3.11.1_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#361]
Wazuh version: 3.11.1
Elastic version: 7.5.1

### Tasks

- [x] Update Ansible tests to 3.11.1_7.5.1

- [x] Udate Puppet tests to 3.11.1_7.5.1

**Comment by rshad** [comment]
Working branch: [feature-361-bump-tests](https://github.com/wazuh/wazuh-qa/tree/feature-361-bump-tests)

**Comment by jm404** [comment]
Done in #364
