### ISSUE TITLE
Avoid warnings during MSI building 

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#3610]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.4.0             |           https://github.com/wazuh/wazuh/issues/14716             |         https://github.com/wazuh/wazuh/pull/15422           |

## Description

In this [PR](https://github.com/wazuh/wazuh/pull/15422) we have modified the WXS file and the installations scripts used in the MSI to avoid some of the warnings that appeared when building the package.
 
## Proposed checks

|System|Installation | Upgrade from 3.13.6 |Upgrade from 4.3.9| Uninstall |
|---|---|---|---|---|
| XP |  | | | ||
| Vista | | | | ||
| 2008  |  | | | ||
| Windows 7   |  ||||
|2012 |  | | ||
|2016 |  | | ||
|2019 |  | | ||
|2022 |  | | ||
| 10 |  | | ||
|11|  | | ||

The 4.4.0 package should install the correct template for each version, to verify this check the ossec.conf
```
<!--
  Wazuh - Agent - Default configuration for Windows
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>

  <client>
    <server>
      <address>0.0.0.0</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windows10</config-profile>
....
```

After upgrading the service must be running if the service was previously running.

**Comment by juliamagan** [comment]
## Update 17/11/2022

Started with Windows Vista. Collected logs, [here](https://github.com/wazuh/wazuh-qa/files/10033510/verbose2.log).

**Comment by juliamagan** [comment]
## Testing results

### Windows Vista

<details>
<summary>4.3.2-1 install</summary>
<br>

- Logs:

- Confirguration template:

- Connection with manager:

</details>

<details>
<summary>4.4.0 install :yellow_circle:</summary>
<br>

- [Logs](https://github.com/wazuh/wazuh-qa/files/10033510/verbose2.log): :yellow_circle:
    - 2203: 0 
    - 1402: 26
    - 2262: 9
    - 2898: 1
    - 2205: 84
    - 2228: 5
    - 2727: 2
    - 2318: 35
    - 2265: 0
    - 1715: 0
    - 1717: 0

- [Confirguration template](https://github.com/wazuh/wazuh-qa/files/10040728/ossec.txt): :green_circle:

```xml
<!--
  Wazuh - Agent - Default configuration for Windows
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>

  <client>
    <server>
      <address>172.17.1.20</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows, windowsVista</config-profile>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```

- Connection with manager: :green_circle:

    - Agent logs:
        ```
        2022/11/18 10:08:14 wazuh-agent: INFO: Started (pid: 2964).
        2022/11/18 10:08:24 wazuh-agent: INFO: Closing connection to server ([172.17.1.20]:1514/tcp).
        2022/11/18 10:08:24 wazuh-agent: INFO: Trying to connect to server ([172.17.1.20]:1514/tcp).
        2022/11/18 10:08:24 wazuh-agent: INFO: (4102): Connected to the server ([172.17.1.20]:1514/tcp).
        ```

    - `/var/ossec/bin/agent_conrol -l
        ```
        [root@wazuh-manager vagrant]# /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
           ID: 000, Name: wazuh-manager (server), IP: 127.0.0.1, Active/Local
           ID: 001, Name: danimaetrix-w7, IP: any, Active
        ```

</details>

<details>
<summary>4.4.0 uninstall :red_circle:</summary>
<br>

Not uninstalled

- [Logs](https://github.com/wazuh/wazuh-qa/files/10040785/uninstall.log): :yellow_circle:
    - 2203: 0 
    - 1402: 5
    - 2262: 0
    - 2898: 0
    - 2205: 0
    - 2228: 0
    - 2727: 0
    - 2318: 0
    - 2265: 0
    - 1715: 0
    - 1717: 0


</details>

<details>
<summary>Upgrade from 3.13.6</summary>
<br>

- Logs:
    - 2203: 0 
    - 1402:
    - 2262:
    - 2898:
    - 2205:
    - 2228:
    - 2727:
    - 2318:
    - 2265:
    - 1715:
    - 1717:

- Confirguration template:

- Connection with manager:


</details>

<details>
<summary>Upgrade from 4.3.9</summary>
<br>

- Logs:
    - 2203: 0 
    - 1402:
    - 2262:
    - 2898:
    - 2205:
    - 2228:
    - 2727:
    - 2318:
    - 2265:
    - 1715:
    - 1717:

- Confirguration template:

- Connection with manager:


</details>

**Comment by jmv74211** [comment]
## QA Review 

- **Type**: Manual testing.

- **Status**: Pending decision to approve or disapprove 🟡 .

- **Comments**: In general, the objectives set out with the development that has been tested seem to have been met, but some things have been detected to be taken into account and to determine whether they are stoppers or not.
    - (1) In the configuration for Windows 11, `config-profile` is set as Windows 10.
    - (2) In the configuration for Windows 2022, there is no `config-profile`.
    - (3) Several error notes in `install.log` and `upgrade.log`

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

| 🔵 | Proposed to be fixed in future versions or developments | 
| ⚫ |Discarded |

The development has been approved taking into account the following reported issues:

**(1) In the configuration for Windows 11, `config-profile` is set as Windows 10.**

This was previoulsy reported in https://github.com/wazuh/wazuh/issues/15150. It will be fixed in the future.

**(2) In the configuration for Windows 2022, there is no `config-profile`.** 🔵

This was previoulsy reported in https://github.com/wazuh/wazuh/issues/15150. It will be fixed in the future.

**(3) Several error notes in `install.log` and `upgrade.log`** ⚫

After discussing with the CICD team, it has been determined that these notes are not relevant for now. More info in this issue [wazuh#14716](https://github.com/wazuh/wazuh/issues/14716)
