### ISSUE TITLE
Agents are wrongly reporting IPv6 as the primary IP

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3611]
Target version | Related issue | Related PR
-- | -- | --
4.4 | wazuh/wazuh#14988 | wazuh/wazuh#15407

## Description

In **Unix systems**, the `wazuh-agentd` process requests information from the `wazuh-modulesd` process to, among that information, obtain the agent's IP. But, if the gateway of the interface has an IPv6 address, then it will precede the IPv4 address (even if the gateway has an IPv4 address).

On the other hand, **in Windows systems**, the agent has only 1 process that gets the IP address from the system.

So, the proposed changes are the following:
1. If the agent has an IPv4 gateway, it will try to get any listed IPv4 address. If there's no IPv4 address, it will try to get any IPv6 address listed.
2. If the agent has an IPv6 gateway, it will try to get any listed IPv6 address. If there's no IPv6 address, it will try to get any IPv4 address listed (⚠️ **The Sysinfo module doesn't support this yet, so it [can be tested on Windows only](https://github.com/wazuh/wazuh/issues/11570#issuecomment-1003026681). Development issues**: [here](https://github.com/wazuh/wazuh/issues/11614) and [here](https://github.com/wazuh/wazuh/issues/11615))

## Proposed checks

The following checks will be run in the following operating systems:
- A Linux-based OS
- macOS
- Windows

<details><summary>Reproduce the bug in the unfixed version</summary>

- Interface with IPv4 gateway and IPv6 address configured

</details>

<details><summary>Fresh install and check that the bug doesn't appear</summary>

- Interface with IPv4 gateway and IPv6 address configured
- Interface with IPv4 gateway no IPv6 address configured, and IPv4 address configured
- Interface with IPv6 gateway and IPv4 address configured
- Interface with IPv6 gateway, no IPv4 address configured, and IPv6 address configured
- Interface with no gateway and IPv4 address configured
- Interface with no gateway and IPv6 address configured
- Interface with no gateway and both types of IP addresses

</details>

<details><summary>Upgrade to the fixed version and check that the bug is fixed</summary>

- Interface with IPv4 gateway and IPv6 address configured
- Interface with IPv4 gateway no IPv6 address configured, and IPv4 address configured
- Interface with IPv6 gateway and IPv4 address configured
- Interface with IPv6 gateway, no IPv4 address configured, and IPv6 address configured
- Interface with no gateway and IPv4 address configured
- Interface with no gateway and IPv6 address configured
- Interface with no gateway and both types of IP addresses

</details>

## Steps to reproduce

1. Setup a manager
2. Setup an agent (without starting it)
3. In the agent VM, configure the network as follows
   3.1. Interface with IPv4 gateway and IPv6 address configured
4. Start the agent
5. Check in the DB and UI the primary IP

**Comment by mauromalara** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @mauromalara | wazuh/wazuh@6ae29b7 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)
|  Windows Server | 2022 | ` LOCAL \|  Vagrant` | [gusztavvargadr/windows-server](https://app.vagrantup.com/gusztavvargadr/boxes/windows-server) |       |
|  macOS | BigSur | ` LOCAL \|  Vagrant` | `qactl/macos_big_sur` |       |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
| [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit6ae29b7_amd64.deb)  | [win](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/windows/wazuh-agent-4.4.0-0.commit6ae29b7.msi) [rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit6ae29b7.x86_64.rpm) [macos](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/macos/wazuh-agent-4.4.0-0.commit6ae29b7.pkg) |       

### Status

- [ ] In progress @mauromalara
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @jnasselle 

### Conclusion 🔵

**Comment by mauromalara** [comment]
## Windows

### Reproduce the bug in the unfixed version

<details><summary>Interface with IPv4 gateway and IPv6 address configured :black_circle:</summary>

<br>



</details>



<details><summary>Interface with IPv4 gateway, no IPv6 address configured, and IPv4 address configured :black_circle:</summary>

<br>



</details>


<details><summary>Interface with IPv6 gateway and IPv4 address configured :black_circle:</summary>

<br>



</details>

**Comment by mauromalara** [comment]
## CentOS 🔵

### Reproduce the bug in the unfixed version

### Upgrade to the fixed version and check that the bug is fixed

### Fresh install and check that the bug doesn't appear

**Comment by damarisg** [comment]
# QA review

- **Type**: Manual testing.
- **Status**: Improvements 🟡  
- **Comments**: Some improvements have been detected, which are the following:

     _(1)_ In the different OS (Windows, macOS, CentOS), for the cases:
    
     - Interface without a gateway and configured IPv4 address
     - Interface without a gateway and configured IPv6 address
     - Interface without a gateway and both types of IP addresses

    It is not present in the Keep-Alive message, and the database keeps the old IP.
    It should be displayed and maintained with the latest added values.
    The Core team will decide whether to apply the fix or if QA will create a new bug for this.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 

The development has been approved taking into account the following considerations:

**(1) In some cases, The IP is not present in the Keep-Alive message, and the database keeps an old IP**. 🔵

This has been reported in [wazuh#15491](https://github.com/wazuh/wazuh/issues/15491) and will be investigated and fixed in future versions.

**Comment by jnasselle** [comment]
Thanks @mauromalara @damarisg @jmv74211,

I agree with the results and the fact that https://github.com/wazuh/wazuh/issues/15491 is not blocking this issue, but behavior that will improve UX.
