### ISSUE TITLE
QA Planning: Enable HLP as function helpers 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3621]
# Description

After the minimum viable product engine's version that has been released by the dev team, is required to research the new changes and study the possible testing cases. 

# Tasks

- [x] Research https://github.com/wazuh/wazuh/issues/15421
- [x] Propose new cases to test.
- [x] Analyze and create cases after validating them.

**Comment by roronoasins** [comment]
## 2022/12/13

After some research within the HLP source code located in `source/hlp` and `source/hlp2`, this issue will be blocked until some documentation is provided.

**Comment by roronoasins** [comment]
Verify that the following High Level Parsers work as expected within different blocks (`logpar`, `check`, `map`, etc.)
- `literal`
- `quoted`
- `dsv`
- `csv`
- `json`
- `xml`
- `kv`
- `uri`
- `fqdn`
- `file`
- `ignore` (this one only applies to ` blocks)
