### ISSUE TITLE
QA Planning: Check and improve the description of error messages

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3622]
# Description

After the minimum viable product engine's version that has been released by the dev team, is required to research the new changes and study the possible testing cases. 

# Tasks

- [x] Research https://github.com/wazuh/wazuh/issues/15210
- [x] Propose new cases to test.
- [x] Analyze and create cases after validating them.

**Comment by roronoasins** [comment]
## Proposed checks

- Retest previous checks that verify basic engine features
- Check debugging messages

> We need to verify that logs are user-friendly, and errors/debug messages are useful.
> The related issue has improved the overall logging, so we need to test the more we can.
