### ISSUE TITLE
The default value of the interval field is not set when applying an empty configuration.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3628]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|      4.5                  | https://github.com/wazuh/wazuh/issues/15413                       | https://github.com/wazuh/wazuh/pull/15428                   |

## Description

When configuring Sycollector with an empty configuration block, the default values ([the ones specified in the documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html)) are expected to apply, but when doing so, the `interval` field gets the value of **0** instead of **3600**.

⚠️ This behavior occurs in both Manager and Agent (Linux and Windows).

## Proposed checks

- [x] Empty Syscollector configuration block.
- [x] Syscollector configuration with random interval scan time set.

## Steps to reproduce

Apply and restart the manager/agent
```
  <!-- System inventory -->
  <wodle name="syscollector">
  </wodle>
```

## Expected results

The expected value for the `interval` field is `3600`

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia    |   https://github.com/wazuh/wazuh/pull/15428/commits/e5fb1f9032c35959375c2e538b7d432737536e03  | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI |
|----|------------|-----------------------------------------------|-----------|
|  CentOS  | CentOS 8 | ` Vagrant` | `qactl/centos_8` |


### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| CentOS | [Manager](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-4.5.0.syscollectorinterval.x86_64.rpm) |
| CentOS      |  [Agent](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-agent-4.5.0-4.5.0.syscollectorinterval.x86_64.rpm)      

### Status

- [x] In progress @BelenValdivia 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved 

### Conclusion

**Comment by BelenValdivia** [comment]
# Testing results (WIP)

## Unfixed

<details><summary>Error repoduction</summary>
  
  1. Install and start `wazuh-manager-4.4.0` 
  2. Apply the following configuration in Syscollector  
      ```
      <!-- System inventory -->
      <wodle name="syscollector">
      </wodle>
      ```
  3. Configure the following internal options:
      ```
      windows.debug=2
      wazuh_modules.debug=2
     ```

  5. Check the manager logs `/var/ossec/logs/ossec.log`
      ```

        2022/12/19 13:04:37 wazuh-modulesd:syscollector[6953] wm_syscollector.c:117 at wm_sys_log_config(): DEBUG: {"syscollector":{"disabled":"no","scan-on-start":"yes","interval":0,"network":"yes","os":"yes","hardware":"yes","packages":"yes","ports":"yes","ports_all":"no","processes":"yes","sync_max_eps":10}}

      ```
  </details>

**Comment by BelenValdivia** [comment]
# Update 19/12/2022
- Research about the issue
- Set up environment Linux and Windows
- Generated packages Linux and Windows with bug
- Generated packages Linux and Windows with bug
- Reproduced bug

**Comment by BelenValdivia** [comment]
Update 21/12/2022

- Upgrade Linux and Windows with empty Syscollector block
- Upgrade Linux and Windows with random interval in syscollector block
- Fresh install with empty block and random interval

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.
