### ISSUE TITLE
Validate the number of active agents and number of TCP sessions match

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3629]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0 |  [#10665](https://github.com/wazuh/wazuh/issues/10665)  |  [#15283](https://github.com/wazuh/wazuh/pull/15283)_(draft)_   |

## Description

This issue aims to ensure the quantity of active agents and the number of tcp sessions are in sync after the modifications applied in the PR [#15283](https://github.com/wazuh/wazuh/pull/15283) fixin bug raised in the issue [#10665](https://github.com/wazuh/wazuh/issues/10665)

## Proposed checks

- [ ] TCP sessions should match the quantity of agents
  <details><summary>Test cases</summary>

  - <details><summary>Connect 50 agents</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>

  - <details><summary>Connect 50 agents and gracefully stop them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Stop the 50 `wazuh-agents`
        > This could be done by running `systemctl stop wazuh-agent` on each agent
    5. Check the `remoted.state` has the correct amount of TCP sessions (0)
    </details>

  - <details><summary>Connect 50 agents and forcibly stop them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Stop the 50 `wazuh-agents`
        > If the agents are on a vagrant VM power of the VMs using `vagrant halt`, or if they are on docker use `docker stop <CONTAINER_NAME`
    5. Check the `remoted.state` has the correct amount of TCP sessions (0)
    </details>

  - <details><summary>Connect 50 agents and gracefully restart them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Restart the 50 `wazuh-agents`
        > This could be done by running `systemctl restart wazuh-agent` on each agent or by creating a file inside the default group folder in the `wazuh-manager` system
    5. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>

  - <details><summary>Connect 50 agents and forcibly restart them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Restart the 50 `wazuh-agents` machines
        > If the agents are on a vagrant VM restart the VMs using `vagrant reload`, or if they are on docker use `docker restart <CONTAINER_NAME`
    5. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>
  </details>

### Required installation methods
- [ ] Fresh install
- [ ] Upgrade

## Expected results

The active TCP connection should match the active agents amount.

**Comment by damarisg** [comment]
The new approach was canceled.
