### ISSUE TITLE
Add coverage to validate the number of active agents and number of TCP sessions match

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3630]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0 |  [#10665](https://github.com/wazuh/wazuh/issues/10665)  |  [#15283](https://github.com/wazuh/wazuh/pull/15283)_(draft)_   |

## Description

This issue aims to develop test cases that ensure the quantity of active agents and the number of tcp sessions are in sync.
It is recommended to included these test cases in ` tests/integration/test_remoted/test_socket_communication/` as it is related to the socket communication, or in a new folder inside `test_remoted/` if the developer evaluates it necessary

## Proposed test cases

  <details><summary>Tier 1 test cases</summary>

  - <details><summary>Connect 50 agents</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>

  - <details><summary>Connect 50 agents and gracefully restart them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Restart the 50 `wazuh-agents`
        > This could be done by running `systemctl restart wazuh-agent` on each agent or by creating a file inside the default group folder in the `wazuh-manager` system
    5. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>
  </details>

  <details><summary>Tier 2 test cases</summary>

  - <details><summary>Connect 50 agents and gracefully stop them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Stop the 50 `wazuh-agents`
        > This could be done by running `systemctl stop wazuh-agent` on each agent
    5. Check the `remoted.state` has the correct amount of TCP sessions (0)
    </details>

  - <details><summary>Connect 50 agents and forcibly stop them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Stop the 50 `wazuh-agents`
        > If the agents are on a vagrant VM power of the VMs using `vagrant halt`, or if they are on docker use `docker stop <CONTAINER_NAME`
    5. Check the `remoted.state` has the correct amount of TCP sessions (0)
    </details>

  - <details><summary>Connect 50 agents and forcibly restart them</summary>
    
    1. Install and start `wazuh-manager`
    2. Connect 50 `wazuh-agents` to the `wazuh-manager`
    3. Check the `remoted.state` has the correct amount of TCP sessions (50)
    4. Restart the 50 `wazuh-agents` machines
        > If the agents are on a vagrant VM restart the VMs using `vagrant reload`, or if they are on docker use `docker restart <CONTAINER_NAME`
    5. Check the `remoted.state` has the correct amount of TCP sessions (50)
    </details>
  </details>

**Comment by fedepacher** [comment]
# 2022/01/23

It has studied the issue and it is creating the test cases to analyze
