### ISSUE TITLE
Add API endpoint to run a Vulnerability Detector scan on demand

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3631]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4.0 | https://github.com/wazuh/wazuh/issues/15002  | https://github.com/wazuh/wazuh/pull/15472 |

## Description

This PR aims to introduce an API endpoint to run a Vuln Detector scan on demand.

## Proposed checks

Run this API endpoint:

```
PUT /vulnerability
```

### On a single-node cluster

- [x] Success.
- [x] Run the query twice. Expected code: 8010.
- [x] Run the query with Vuln Detector disabled. Expected code: 8011.
- [x] Run the query having `<vulnerability-detector>` undeclared. Expected code: 8002.

### On a multiple-node cluster

- [x] Success.
- [x] Run the query twice. Expected code: 8010.
- [x] Run the query with Vuln Detector disabled. Expected code: 8011.
- [x] Run the query having `<vulnerability-detector>` undeclared. Expected code: 8002.

## Expected results

The expected codes are noted in the list above.

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15472/commits/26097f0bce35736911f2e019be4e0e4563618ce1 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|   [wazuh-manager_4.4.0-0.commit26097f0_amd64.deb](packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit26097f0_amd64.deb) , [wazuh-manager-4.4.0-0.commit26097f0.x86_64.rpm](packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit26097f0.x86_64.rpm) | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved ()

**Comment by Rebits** [comment]
### Update 24/11/2022
- Perform single-node tests cases
- Perform basic multiple-node cases

**Comment by Rebits** [comment]
## Testing results :large_blue_circle: 

<details>

  <summary> Single-node cluster :red_circle:  </summary>


For single-node cluster testing, we are going to use a centOS manager. In addition, we have performed the testing tasks proposed, after the first vulnerability scan is finished (and feeds were updated).

<details>

<summary> <code> ossec.conf </code> </summary>


```
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>400m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>no</run_on_start>

    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```


</details> 



<details>

<summary> <code> local_internal_configurations </code> </summary>

```
wazuh_modules.debug=1
```

</details>



<blockquote>


<details>

<summary> Basic case: Scan performed succesfully :green_circle: </summary>

A vulnerability scan is performed successfully using the new endpoint.

**API request **:
```
[root@c3 vagrant]# curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["manager"], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "A vulnerability detector scan was requested", "error": 0}[root@c3 vagrant]# 

```


**ossec.log**:
```
2022/11/25 10:45:04 wazuh-modulesd[6862] wm_vuln_detector.c:9265 at wm_vuldet_query(): DEBUG: Scan requested.
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:8245 at wm_vuldet_run_scan(): INFO: (5431): Starting vulnerability scan.
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:2726 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5439): A partial scan will be run on agent '000'
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:5465 at wm_vuldet_collect_agent_software(): DEBUG: (5437): Collecting agent '000' software.
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:2745 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '000' vulnerabilities.
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:2764 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5471): Finished vulnerability assessment for agent '000'
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:2765 at wm_vuldet_check_agent_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'scan' vulnerabilities in agent '000'
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:8260 at wm_vuldet_run_scan(): INFO: (5472): Vulnerability scan finished.
2022/11/25 10:45:05 wazuh-modulesd:vulnerability-detector[6862] wm_vuln_detector.c:8307 at wm_vuldet_run_sleep(): DEBUG: Sleeping for 300 seconds...
```

</details>


<details>

<summary> Run the query twice. Expected code: 8010 :green_circle:</summary>

The expected code is produced

**API request**:
```
curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 8010, "message": "A scan has already been requested"}, "id": ["manager"]}]}, "message": "No vulnerability detector scans were requested", "error": 1}
```

</details>



<details>

<summary> Run the query with Vuln Detector disabled. Expected code: 8011. :green_circle: </summary>

The expected code is produced:

**API request**:
```
[root@c3 vagrant]# curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 8011, "message": "This module is disabled"}, "id": ["manager"]}]}, "message": "No vulnerability detector scans were requested", "error": 1}[root@c3 vagrant]# 
```

</details>



<details>

<summary> Run the query having `vulnerability-detector` undeclared. Expected code: 8002.  :green_circle: </summary>


The expected code is produced:

**API request**:
```
[root@c3 vagrant]# curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 8002, "message": "Module not found or not configured"}, "id": ["manager"]}]}, "message": "No vulnerability detector scans were requested", "error": 1}[root@c3 vagrant]# 
```


</details>



<details>

<summary> E2E: Real vulnerability detected using VD scan, triggered by API endpoint. :red_circle: </summary>


**The vulnerability scan is not performed correctly using the endpoint after the manager is restarted.**

For this check, we have tested an actual use case. We have installed a vulnerable package, and we will try to detect it using the new endpoint:

- Install a vulnerable package. In this case, we are going to install `firefox91` in our system.
- Wait for the syscollector to detect the new vulnerable package. In this case, we have restarted the manager, so, with the `scan_on_start` enabled, it should run the syscollector scan after a few seconds after the restart:
```
2022/11/25 10:52:27 wazuh-modulesd:syscollector[11422] wm_syscollector.c:105 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_packages","data":{"attributes":{"architecture":"x86_64","checksum":"153c7f15a236e977062feda89bd140890d3e8fd0","description":"Mozilla Firefox Web browser","format":"rpm","groups":"Unspecified","install_time":"1669373486","item_id":"6d1da27ed83e24a905fe50f55bc7860da1932a0b","name":"firefox","scan_time":"2022/11/25 10:52:27","size":273979960,"vendor":"CentOS","version":"91.8.0-1.el8"},"index":"6d1da27ed83e24a905fe50f55bc7860da1932a0b","timestamp":""},"type":"state"}
```
- Detect the vulnerability using new endpoint


The vulnerability scan is never performed after restarting the manager. The log `Scan requested.
` is generated, although, it will never start correctly the scan. It is not possible to request a new scan due to `8010` error code:
```
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 8010, "message": "A scan has already been requested"}, "id": ["manager"]}]}, "message": "No vulnerability detector scans were requested", "error": 1}[root@c3 vagrant]# 
```

**API request**:
```
[root@c3 vagrant]# curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["manager"], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "A vulnerability detector scan was requested", "error": 0}[root@c3 vagrant]# 
```

**ossec.log**:
```
2022/11/25 10:54:10 wazuh-modulesd[12485] wm_vuln_detector.c:9265 at wm_vuldet_query(): DEBUG: Scan requested.
2022/11/25 10:54:16 rootcheck: INFO: Ending rootcheck scan.
...
```

After more than 10 minutes vulnerability scan is not performed

</details>



  </blockquote>


</details>

**Comment by Rebits** [comment]
### How to reproduce: VD endpoint does not work if the previous scan has not been launched

<details>

<summary> <code> ossec.conf </code> </summary>

```
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>400m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>no</run_on_start>

    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

</details>

<details>

<summary>  <code> local_internal_options.conf </code> </summary>

```
wazuh_modules.debug=2
```

</details>

- Use specified VD configuration. Notice that the  `run_on_start` is disabled
- Run VD on demand using `vulnerability` endpoint:
```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -X PUT "https://localhost:55000/vulnerability" -H "Authorization: Bearer $TOKEN"
```
- Check that no error was produced, but it is never triggered until the next scheduled scan.

**Comment by jmv74211** [comment]
## QA Review 

- **Type**: Manual testing.
- **Status**: Requested changes 🔴 
- **Comments**: Some improvements have been found and cases where the behavior is not as expected:
   - **(1): Vulnerability detector scan on demand does not work correctly if a scan has not been previously launched during uptime.**
     In this comment, you can find how to reproduce the error https://github.com/wazuh/wazuh-qa/issues/3631#issuecomment-1327610594
   - **(2): Typo in API message** `A vulnerability detector scan was requested in some nodes in all nodes`

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved 


Everything seems to work properly. The development has been approved taking into account the following considerations:

**(1): Vulnerability detector scan on demand does not work correctly if a scan has not been previously launched during uptime.** 🟢

This has been solved in this current development, see https://github.com/wazuh/wazuh/pull/15472/commits/dcf72f44eefcf680d709fa77a8b6a465b1d1c8a0 . It has been checked that now it works correctly.

**(2): Typo in API message A vulnerability detector scan was requested in some nodes in all nodes** 🟢

This has been solved in this current development, see https://github.com/wazuh/wazuh/pull/15472/commits/60be396b1e5bc563cccc27fb99bdec1c0b5ee1be . It has been checked that now it works correctly.
