### ISSUE TITLE
Test file-descriptors leak fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3632]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 |  https://github.com/wazuh/wazuh/issues/15426  | https://github.com/wazuh/wazuh/pull/15467   |

## Description
On the Test Stress pipeline showed that the resource usage for  `Analysisd` and `Remoted` daemons increased dramatically on 4.4.0. Upon research, it was found that some functions opened filedescriptors for each socket, but would not close them, causing memory leaks and increased resource usage.

This Issue aims to test the fix done. 

## Proposed checks
- [x] Test file descriptors in manager

## Steps to reproduce

- Test file descriptors in manager
   - Setup manager
   - Install and connect agent
   - Check file descriptors and sockets in `analysisd` and `remoted`
   - Wait 2-3 minutes
   - Check file descriptors and sockets in `analysisd` and `remoted` (In fixed branch the size/amount of sockets stays consistent)

## Current results
As time passes the in the unfixed manager, the amount of open sockets will increase overtime, increasing the resource consumption of the application.

## Expected results
`Remoted` and `Analysisd` sockets are closed after they are used, so the amount of open sockets stays consistent and resource usage does not increase on the manager.

**Comment by Deblintrake09** [comment]
### Task results

| Package Type | Versions |
|--|--|
| Manager | [4.4.0 unfixed](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.4.0-0.40400.20221124.x86_64.rpm) - fixed manager |
| Agent | [4.4.0 unfixed](https://packages-dev.wazuh.com/staging/yum/wazuh-agent-4.4.0-0.40400.20221124.x86_64.rpm) - fixed agent |

**Comment by Deblintrake09** [comment]
# Testing results on Ubuntu 

## Testing on unfixed branch

<details><summary>Manager closes remoted and analysisd sockets :red_circle:  </summary>

- Install Manager and start
- Check file descriptors and sockets

   <details><summary>Check WazuhDB  </summary>

   ```
   # ps aux | grep wazuh-db
   wazuh      40995  1.4  0.1 771084 11748 ?        Sl   14:18   0:00 /var/ossec/bin/wazuh-db
   cd /proc/40995/fd
   ls 
   0   12  16  2   23  
   1   13  17  20  24  
   10  14  18  21 
   11  15  19  22 
   ```
   </details>

   <details><summary>Check analysisd  </summary>

   ```
   # ps aux | grep analysis
   wazuh      41039  4.7  0.4 1425804 28108 ?       Sl   14:18   0:00 /var/ossec/bin/wazuh-analysisd
   cd /proc/41039/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  9
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  6
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  8
   ```
   </details>
   <details><summary>Check remoted</summary>

   ```
   # ps aux | grep remote
   wazuh      41117  0.1  0.0 444364  4596 ?        Sl   14:18   0:00 /var/ossec/bin/wazuh-remoted
   cd /proc/41117/fd
   ls 
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  8
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  6   9
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  7
   ```
   </details>
- Connect Agent 
- Wait for some time for state files to update and generate sockets
- Check file descriptors and sockets
   <details><summary>Check WazuhDB  </summary>

   ```
   cd /proc/40995/fd
   ls 
   0   12  16  2   23  27  30  34  38  41  45  49  52  56  6   63  67  70  74  78  81  85  89
   1   13  17  20  24  28  31  35  39  42  46  5   53  57  60  64  68  71  75  79  82  86  9
   10  14  18  21  25  29  32  36  4   43  47  50  54  58  61  65  69  72  76  8   83  87  90
   11  15  19  22  26  3   33  37  40  44  48  51  55  59  62  66  7   73  77  80  84  88  91
   ```
   </details>

   <details><summary>Check analysisd </summary>

   ```
   cd /proc/41039/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  60  63  66  69  72
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  59  61  64  67  70  8
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  6   62  65  68  71  9
   ```
   </details>
   <details><summary>Check remoted  </summary>

   ```
   cd /proc/41117/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  60  63  66  69  9
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  59  61  64  67  7
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  6   62  65  68  8
   ```
   </details>
</details>

> NOTE: In the unfixed branch, we can see that the amount of open sockets in the list increases for `wazuh-db`, `remoted` and `analysisd`.


## Testing on unfixed branch

<details><summary>Upgrade Install - Manager closes remoted and analysisd sockets </summary>

- Install Manager and start
- Check file descriptors and sockets

   <details><summary>Check WazuhDB  </summary>

   ```
   # ps aux | grep wazuh-db
   wazuh      40995  1.4  0.1 771084 11748 ?        Sl   14:18   0:00 /var/ossec/bin/wazuh-db
   cd /proc/40995/fd
   ls 
   0   12  16  2   23  
   1   13  17  20  24  
   10  14  18  21 
   11  15  19  22 
   ```
   </details>

   <details><summary>Check analysisd  </summary>

   ```
   # ps aux | grep analysis
   wazuh      41039  4.7  0.4 1425804 28108 ?       Sl   14:18   0:00 /var/ossec/bin/wazuh-analysisd
   cd /proc/41039/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  9
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  6
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  8
   ```
   </details>
   <details><summary>Check remoted</summary>

   ```
   # ps aux | grep remote
   wazuh      41117  0.1  0.0 444364  4596 ?        Sl   14:18   0:00 /var/ossec/bin/wazuh-remoted
   cd /proc/41117/fd
   ls 
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  8
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  6   9
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  7
   ```
   </details>
- Connect Agent 
- Wait for some time for state files to update and generate sockets
- Check file descriptors and sockets
   <details><summary>Check WazuhDB  </summary>

   ```
   cd /proc/40995/fd
   ls 
   0   12  16  2   23  27  30  34  38  41  45  49  52  56  6   63  67  70  74  78  81  85  89
   1   13  17  20  24  28  31  35  39  42  46  5   53  57  60  64  68  71  75  79  82  86  9
   10  14  18  21  25  29  32  36  4   43  47  50  54  58  61  65  69  72  76  8   83  87  90
   11  15  19  22  26  3   33  37  40  44  48  51  55  59  62  66  7   73  77  80  84  88  91
   ```
   </details>

   <details><summary>Check analysisd </summary>

   ```
   cd /proc/41039/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  60  63  66  69  72
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  59  61  64  67  70  8
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  6   62  65  68  71  9
   ```
   </details>
   <details><summary>Check remoted  </summary>

   ```
   cd /proc/41117/fd
   ls
   0   11  14  17  2   22  25  28  30  33  36  39  41  44  47  5   52  55  58  60  63  66  69  9
   1   12  15  18  20  23  26  29  31  34  37  4   42  45  48  50  53  56  59  61  64  67  7
   10  13  16  19  21  24  27  3   32  35  38  40  43  46  49  51  54  57  6   62  65  68  8
   ```
   </details>
</details>

> NOTE: In the unfixed branch, we can see that the amount of open sockets in the list does not increase  for `wazuh-db`, `remoted` and `analysisd`.

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.
