### ISSUE TITLE
Adapt agent environment configuration to deal with a master only but not a client

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#365]
Hi all!

When testing Wazuh 3.11.1_7.5.1, the agent is failing with the following error message:
```bash
root@20366ba02275:/var/ossec# ./bin/ossec-control start
ossec-agentd: ERROR: (4112): Invalid server address found: ''
ossec-agentd: CRITICAL: (1215): No client configured. Exiting.
ossec-agentd: Configuration error. Exiting
``` 

After investigating, we found that the error is related to the  tag `<client>`  which could have two addresses, one for a _master manager_ and another one for a _client manager_; this is related to running Wazuh in cluster mode.

By default, we set the _manager client_ IP to `empty`, and this worked until Wazuh `3.10.*`, but it's not with Wazuh `3.11.1` .

On following, we can see the environment configuration part which corresponds to the info. mentioned above. 

`client manager`: `manager-client.wazuh-test.com`

https://github.com/wazuh/wazuh-qa/blob/afd6cacd11e8a0afb588f8e5a23812bcf4352534/kitchen/wazuh-chef/agent/development.json.template#L11-L15

A tested solution is to remove the `client manager` entry from the environment configuration as it's not required by default.

Tasks to Do:

- [x] Adapt the environment configuration for the agent.
- [x] Adapt the testing auxiliary script `run.sh`.
- [x] Verify the changes.

kr,

Rshad

**Comment by rshad** [comment]
Working branch: [fix-365-adapt-agent-env](https://github.com/wazuh/wazuh-qa/tree/fix-365-adapt-agent-env)

**Comment by jm404** [comment]
Done in #366
