### ISSUE TITLE
Exploratory test of the Content Migration tool

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3651]
| Related to | 
|--|
https://github.com/wazuh/wazuh-content/issues/149|

## Description

Test cases to be executed manually:

- [ ] Verify that the output format for each provider is the expected
- [ ] Verify that an error is displayed when one of the required fields is not present in the input
- [ ] Verify that the diffs are generated correctly
- [ ] Verify that the report is generated correctly
- [ ] Verify that a warning log is displayed when a field (not required) is not present
- [ ] Verify the snapshot content

**Comment by damarisg** [comment]
The details of this exploratory  are on https://github.com/wazuh/wazuh-content/issues/149

**Comment by mauromalara** [comment]
The first exploratory est over a development version was achieved [here](https://github.com/wazuh/wazuh-content/issues/149#issuecomment-1345141127). So, you can check all details there. I had to test manually the tool due to the refactoring of the tests developed in #3307 , so I spent a lot of time doing manual testing.

**Comment by damarisg** [comment]
Each bug was reported, in the future when a new exploratory is required, a new problem will be created.
