### ISSUE TITLE
Improve xfailed management in API performance tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#3665]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
| - | https://github.com/wazuh/wazuh/issues/15653 | - |

## Description
Currently, the way xfail is used in API performance tests prevents endpoint execution from even being attempted:
https://github.com/wazuh/wazuh-qa/blob/1333324d33b713631cde7bebfb9a1af63ef20d35/tests/performance/test_api/test_api_endpoints_performance.py#L35-L38

This makes it impossible to determine if any of the listed endpoints have worked correctly:
https://github.com/wazuh/wazuh-qa/blob/1333324d33b713631cde7bebfb9a1af63ef20d35/tests/performance/test_api/test_api_endpoints_performance.py#L15-L22

Sometimes, such as for the `PUT /agents/group` endpoint in the tests run in the issue below, it might be useful to know if it's still failing or not, without explicitly modifying the list:
- https://github.com/wazuh/wazuh/issues/15653

## Considerations
These tests are usually run inside a performance pipeline.

**Comment by RamosFe** [comment]
## Update

Passed to `on hold` due to Release 4.7.0 Integration tests.
