### ISSUE TITLE
Update automated tests related to Syscollector deltas to new format

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3673]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|v4.4| wazuh/wazuh#15639|wazuh/wazuh#15675|

## Description

This issue aims to update the integration tests related to syscollector deltas, which are

- https://github.com/wazuh/wazuh-qa/blob/4.4/tests/integration/test_analysisd/test_syscollector/test_syscollector_events.py
- https://github.com/wazuh/wazuh-qa/blob/4.4/tests/integration/test_wazuh_db/data/agent/syscollector_deltas_messages.yaml

Both integration tests were developed here https://github.com/wazuh/wazuh-qa/pull/2146

## Proposed updates

- Analysisd IT
  - Replace partial modified/inserted deltas to contain all the information
  - Alerts expected values (fields and rules numbers) should be the same, only updating values that may be changed according to the event input
- Wazuh-db IT
  - Replace partial modified/inserted deltas to contain all the information
  - Change format from pipe-separated masked values with JSON format
  - Change error return depending the proposed changes

**Comment by mauromalara** [comment]
## Update 29/12/2022

- Had issues with the environment (Windows)
- After debugging the test that was failing locally, we noticed that this behavior was only present in Ubuntu, while in CentOS the test passes. So, the issue has nothing to do with the current development.

**Comment by jnasselle** [comment]
Closed by #3695
