### ISSUE TITLE
Testing of AIX `wazuh-manager` local mode

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3676]
In a proposed development the development team is working on creating a kind of mix between `wazuh-agent` and `wazuh-agent` with the objective that the product itself is able to monitor, analyze and report alerts through remote syslog. 

The starting system is AIX, and the main requirements are the following:

- Wazuh must be able to monitor changes in log files and generate events accordingly.
- Wazuh must be able to programmatically monitor changes in the file system and generate events accordingly.
- Wazuh must be able to analyze each of the generated events, generating alerts based on the ruleset.
- Wazuh must be able to send the generated alerts through remote syslog.

Taking into account these main requirements, a priori what is going to be done is to start from a `wazuh-manager` version `3.1` (base version that is believed to be compatible with this approach), where a series of daemons such as `wazuh-remoted`, `wazuh-apid` and `wazuh-clusterd` will be disabled.

We want to perform the relevant tests to prove that this new development works correctly for these initial requirements. 

The initial tests that are proposed are:
  - Functional tests
  - Performance tests
  - Footprint tests.

> Related development issue [wazuh#15971](https://github.com/wazuh/wazuh/issues/15971)

## Sub-issues

- https://github.com/wazuh/wazuh-qa/issues/3678
- https://github.com/wazuh/wazuh-qa/issues/3679
- https://github.com/wazuh/wazuh-qa/issues/3680
- https://github.com/wazuh/wazuh-qa/issues/3681

**Comment by jmv74211** [comment]
# Test planning

## Functional testing

Functional testing will be focused on the two main modules to be used for event monitoring which are `logcollector` and `syscheck`, as well as ensuring that events are processed, stored and sent through syslog with `csyslogd`.

### Log data collection

Taking into account the available configuration of `logcollector` for a `3.1.0` version of Wazuh, it has been considered to perform a functional test manually for each of the following cases, represented by the following scheme:

- local_configuration:
    - `<location>`
        - wildcards:
            - wildcard-group: file.log-%Y-%m-%d
            - generic wildcard: /*.log
        - string_path:
    - `<command>`
        - command without arguments
        - command with arguments
    - `<alias>`
    - `<frequency>`
    - `<only-future-events>`
        - yes
        - no
    - `<label>`
    - `<log_format>`
        - syslog
        - json
        - command
        - full_command
        - multi-line
- internal_configuration:
    - logcollector.vcheck_files
    - logcollector.remote_commands
    - logcollector.max_lines
    - logcollector.loop_timeout


### File integrity monitoring

Taking into account the available `syscheck` configuration for a `3.1.0` version of Wazuh, it has been considered to perform a functional test manually for each of the following cases, represented by the following scheme:

- `<directories>`
    - report_changes
        - yes
        - no
    - check_all
        - yes
        - no
    - restrict
- `<ignore>`
- `<nodiff>`
- `<frequency>`
- `<scan_time>`
- `<scan_day>`
- `<alert_new_files>`
    - yes
    - no
- `<scan_on_start>`
    - yes
    - no

## Performance testing

The objective of this type of testing is to measure the performance and functionality of Wazuh when certain stresses occur. Basically it is to determine limits and provide a certain threshold below which the correct functioning of the product can be guaranteed.

> Note: To perform this type of tests, it will be necessary to design and implement a series of processes that allow us to generate the event load, measure the expected results and generate the reports.

### Log data collection

The performance tests that have been designed for this module are as follows:

- Add `n` entries to a `x` files simultaneosly.
- Add `n` entries to a `x` files simultaneosly using wildcards.
- Add `n` entries to a `x` files simultaneosly using json format.
- Add `n` entries to a `x` files simultaneosly using a variable size.

### File integrity monitoring

The performance tests that have been designed for this module are as follows:

- Monitor `n` paths and create `x` files
- Monitor `n` paths and update `x` files
- Monitor `n` paths and delete `x` files
- Monitor `n` paths and make multiple operations in `x` files

## Footprint testing

The objective of this type of testing is to measure the impact that the use of Wazuh has on the resources of the machine where it is running. The main resources that are measured are the following:

- CPU
- Memory
- Disk usage
- File descriptor usage

In our case, during each of the performance tests to be performed, each of these resources will be measured to try to detect possible anomalies or undesired impacts.

**Comment by Rebits** [comment]
Closed. The testing for AIX manager v4.3.10 will be tracked at https://github.com/wazuh/wazuh-qa/issues/4051
