### ISSUE TITLE
Create the list of bugs reported to the input of events 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3683]
# Description

After carrying out the corresponding validations, the QA suggested improvements and found errors.

This issue aims to create issues reported on the [conclusion](https://github.com/wazuh/wazuh-qa/issues/3533#issuecomment-1307312752) to add them at https://github.com/wazuh/wazuh-qa/issues/3619. After that, I will can to closed https://github.com/wazuh/wazuh-qa/issues/3533

**Comment by roronoasins** [comment]
The issues were added to the bug list https://github.com/wazuh/wazuh-qa/issues/3619#issue-1455175408, and some of them were added as cases to others already opened.
