### ISSUE TITLE
Validate shutdown message processing even though socket is closed

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3704]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0 | [#15153](https://github.com/wazuh/wazuh/issues/15153) | [#15518](https://github.com/wazuh/wazuh/pull/15518) |

## Description

In order to always process the agent's connection status correctly a functionality to let always through the shutdown messages, even after the socket is closed.

## Proposed checks

- <details><summary>Scenario outline: Agent status is updated correctly</summary>

    ```Gherkin
    Given 50 wazuh-agents connected to "<server-environment>".
    When "<action>" all the agents.
    Then the agents status is "<result>".
    
    Examples:
      | server-environment | action             | result        |
      |--------------------|--------------------|---------------|
      | single node server | gracefully stop    | disconnected  |
      | single node server | gracefully restart | active        |
      | single node server | suddenly stop      | disconnected  |
      | cluster's master   | gracefully stop    | disconnected  |
      | cluster's master   | gracefully restart | active        |
      | cluster's master   | suddenly stop      | disconnected  |
      | cluster's worker   | gracefully stop    | disconnected  |
      | cluster's worker   | gracefully restart | active        |
      | cluster's worker   | suddenly stop      | disconnected  |
    ```
</details>

### Required installation methods
- [x] Fresh install
- [x] Upgrade

**Comment by QU3B1M** [comment]
# Update 02/01/2023

**Comment by QU3B1M** [comment]
### Upgrade 03/03/2023
- Re-think test cases, this is needed as the proposed case was created in the first "version" of the solution and the actual has some other changes.

**Comment by QU3B1M** [comment]
### Update 06/03/2023
- New test cases added in Gherkin format

**Comment by QU3B1M** [comment]
### Update 07/02/2023
- Upgrade testing process finished
- Fresh install testing in progress

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [`0eaee11`](https://github.com/wazuh/wazuh/pull/15518/commits/0eaee11e82ee26249a1a829b194955c887e6efa5)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb]()||       

### Status

- [x] In progress @QU3B1M 
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @TomasTurina 

### Conclusion :green_circle:

Testing execution successful :green_circle:. The shutdown message is received in each case and there is no agent left on a incorrect status.

**Comment by QU3B1M** [comment]
# Testing results :green_circle:

## Unfixed

<details><summary>Error repoduction</summary>
  
  1. Connect 50 agents to the `wazuh-manager`.
  2. Gracefully stop all the agents
      `/var/ossec/bin/wazuh-control stop`
  3. Some agents are in state `active`
      ```log
      /var/ossec/bin/agent_control -l

      Wazuh agent_control. List of available agents:
        ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
        ID: 001, Name: 05gAgDWr9HINt, IP: any, Disconnected
        ID: 002, Name: Q17jdyGyUtgT5, IP: any, Disconnected
        ID: 003, Name: qfTfznElGZk65, IP: any, Disconnected
        ID: 004, Name: G270XlDIn5YSl, IP: any, Disconnected
        ID: 005, Name: nX3nwaM3CQNZG, IP: any, Disconnected
        ID: 006, Name: XsCxA2qZfc7cT, IP: any, Disconnected
        ID: 007, Name: ooJcMMG6q45EN, IP: any, Disconnected
        ID: 008, Name: YRLsXzSKcz4rK, IP: any, Disconnected
        ID: 009, Name: nmYom1qTcXnlo, IP: any, Disconnected
        ID: 010, Name: 6ULswDvBXgXAw, IP: any, Active
        ID: 011, Name: q7zlh3eQWILv0, IP: any, Disconnected
        ID: 012, Name: 2OJANCIiEfFAS, IP: any, Disconnected
        ID: 013, Name: eFibC2XvjwlXR, IP: any, Disconnected
        ID: 014, Name: HlfL5Qk5buPqT, IP: any, Disconnected
        ID: 015, Name: 2ZeNXH6QltaSO, IP: any, Disconnected
        ID: 016, Name: A8ta2AUdHyeNJ, IP: any, Disconnected
        ID: 017, Name: m3xuqvPFQ0j13, IP: any, Disconnected
        ID: 018, Name: 6dXYwQGwBlAFA, IP: any, Disconnected
        ID: 019, Name: Pnf9ZZ0VCF6iv, IP: any, Disconnected
        ID: 020, Name: somRxd7iR3CA2, IP: any, Disconnected
        ID: 021, Name: zJRdKOJUFAUnC, IP: any, Disconnected
        ...
      ```
  </details>

## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade wazuh-manager 
  ```log
  - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


    Thanks for using Wazuh.
    Please don't hesitate to contact us if you need help or find
    any bugs.

    Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

    More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

  - Update completed.

  ```

</details>

<details><summary>Scenario outline 1: Enroll agents to wazuh-manager :green_circle:</summary>

  > <details><summary>Gherkin description</summary>
  > 
  >    ```Gherkin
  >    Given 50 wazuh-agents connected to "<server-environment>".
  >    When "<action>" all the agents.
  >    Then the agents status is "<result>".
  >
  >    Examples:
  >      | server-environment | action             | result        |
  >      |--------------------|--------------------|---------------|
  >      | single node server | gracefully stop    | disconnected  |
  >      | single node server | gracefully restart | active        |
  >      | single node server | suddenly stop      | disconnected  |
  >      | cluster's master   | gracefully stop    | disconnected  |
  >      | cluster's master   | gracefully restart | active        |
  >      | cluster's master   | suddenly stop      | disconnected  |
  >      | cluster's worker   | gracefully stop    | disconnected  |
  >      | cluster's worker   | gracefully restart | active        |
  >      | cluster's worker   | suddenly stop      | disconnected  |
  >    ```
  > </details>

  - <details><summary>Case 1: <code>wazuh-manager</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: 05gAgDWr9HINt, IP: any, Disconnected
          ID: 002, Name: Q17jdyGyUtgT5, IP: any, Disconnected

          ...
          
          ID: 049, Name: f0JDERcxYEyC1, IP: any, Disconnected
          ID: 050, Name: pmH7jCGHnBhwx, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/07 19:27:49 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent htCTKKFWIMjrr sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/07 19:27:49 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent niEyaGfPNTxoM sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 2: <code>wazuh-manager</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: 05gAgDWr9HINt, IP: any, Active
          ID: 002, Name: Q17jdyGyUtgT5, IP: any, Active

          ...

          ID: 049, Name: f0JDERcxYEyC1, IP: any, Active
          ID: 050, Name: pmH7jCGHnBhwx, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/07 19:46:45 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent htCTKKFWIMjrr sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/07 19:46:45 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent niEyaGfPNTxoM sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 3: <code>wazuh-manager</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: 05gAgDWr9HINt, IP: any, Disconnected
          ID: 002, Name: Q17jdyGyUtgT5, IP: any, Disconnected

          ...

          ID: 049, Name: f0JDERcxYEyC1, IP: any, Disconnected
          ID: 050, Name: pmH7jCGHnBhwx, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>

  - <details><summary>Case 4: <code>master</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Disconnected
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Disconnected

          ...

          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Disconnected
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/07 20:03:09 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent htCTKKFWIMjrr sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/07 20:03:09 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent niEyaGfPNTxoM sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 5: <code>master</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Active
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Active

          ...

          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Active
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/07 20:05:30 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent htCTKKFWIMjrr sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/07 20:05:30 wazuh-remoted[211274] manager.c:285 at save_controlmsg(): DEBUG: Agent niEyaGfPNTxoM sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 6: <code>master</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Disconnected
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Disconnected

          ...
          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Disconnected
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>

  - <details><summary>Case 7: <code>master</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: hg3ATYWKP9pf0, IP: any, Disconnected
          ID: 002, Name: 2L6DFOSl1yT0m, IP: any, Disconnected

          ...

          ID: 049, Name: D5wFOQx1ZMj5u, IP: any, Disconnected
          ID: 050, Name: 1D89oRdxrB471, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 11:04:09 wazuh-remoted[17960] manager.c:285 at save_controlmsg(): DEBUG: Agent 2L6DFOSl1yT0m sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 11:04:09 wazuh-remoted[17960] manager.c:285 at save_controlmsg(): DEBUG: Agent hg3ATYWKP9pf0 sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 8: <code>master</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: hg3ATYWKP9pf0, IP: any, Active
          ID: 002, Name: 2L6DFOSl1yT0m, IP: any, Active

          ...

          ID: 049, Name: D5wFOQx1ZMj5u, IP: any, Active
          ID: 050, Name: 1D89oRdxrB471, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 11:08:25 wazuh-remoted[17960] manager.c:285 at save_controlmsg(): DEBUG: Agent 2L6DFOSl1yT0m sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 11:08:26 wazuh-remoted[17960] manager.c:285 at save_controlmsg(): DEBUG: Agent hg3ATYWKP9pf0 sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 9: <code>master</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Disconnected
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Disconnected

          ...
          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Disconnected
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>
</details>



## Fresh install


<details><summary>Scenario outline 1: Enroll agents to wazuh-manager :green_circle:</summary>

  > <details><summary>Gherkin description</summary>
  > 
  >    ```Gherkin
  >    Given 50 wazuh-agents connected to "<server-environment>".
  >    When "<action>" all the agents.
  >    Then the agents status is "<result>".
  >
  >    Examples:
  >      | server-environment | action             | result        |
  >      |--------------------|--------------------|---------------|
  >      | single node server | gracefully stop    | disconnected  |
  >      | single node server | gracefully restart | active        |
  >      | single node server | suddenly stop      | disconnected  |
  >      | cluster's master   | gracefully stop    | disconnected  |
  >      | cluster's master   | gracefully restart | active        |
  >      | cluster's master   | suddenly stop      | disconnected  |
  >      | cluster's worker   | gracefully stop    | disconnected  |
  >      | cluster's worker   | gracefully restart | active        |
  >      | cluster's worker   | suddenly stop      | disconnected  |
  >    ```
  > </details>

  - <details><summary>Case 1: <code>wazuh-manager</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: r5zOrnxkq5rEV, IP: any, Disconnected
          ID: 002, Name: mesgaSqQzUZs9, IP: any, Disconnected

          ...
          
          ID: 049, Name: H2iqPsnd2t27Z, IP: any, Disconnected
          ID: 050, Name: EbscKj3jqn8SH, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 11:33:08 wazuh-remoted[218683] manager.c:285 at save_controlmsg(): DEBUG: Agent mesgaSqQzUZs9 sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 11:33:08 wazuh-remoted[218683] manager.c:285 at save_controlmsg(): DEBUG: Agent r5zOrnxkq5rEV sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 2: <code>wazuh-manager</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: r5zOrnxkq5rEV, IP: any, Active
          ID: 002, Name: mesgaSqQzUZs9, IP: any, Active

          ...
          
          ID: 049, Name: H2iqPsnd2t27Z, IP: any, Active
          ID: 050, Name: EbscKj3jqn8SH, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 11:35:49 wazuh-remoted[218683] manager.c:285 at save_controlmsg(): DEBUG: Agent mesgaSqQzUZs9 sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 11:35:49 wazuh-remoted[218683] manager.c:285 at save_controlmsg(): DEBUG: Agent r5zOrnxkq5rEV sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 3: <code>wazuh-manager</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `wazuh-manager`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: r5zOrnxkq5rEV, IP: any, Disconnected
          ID: 002, Name: mesgaSqQzUZs9, IP: any, Disconnected

          ...
          
          ID: 049, Name: H2iqPsnd2t27Z, IP: any, Disconnected
          ID: 050, Name: EbscKj3jqn8SH, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>

  - <details><summary>Case 4: <code>master</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: r5zOrnxkq5rEV, IP: any, Disconnected
          ID: 002, Name: mesgaSqQzUZs9, IP: any, Disconnected

          ...
          
          ID: 049, Name: H2iqPsnd2t27Z, IP: any, Disconnected
          ID: 050, Name: EbscKj3jqn8SH, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 12:05:04 wazuh-remoted[219841] manager.c:285 at save_controlmsg(): DEBUG: Agent mesgaSqQzUZs9 sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 12:05:04 wazuh-remoted[219841] manager.c:285 at save_controlmsg(): DEBUG: Agent r5zOrnxkq5rEV sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 5: <code>master</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Active
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Active

          ...

          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Active
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 12:06:36 wazuh-remoted[219841] manager.c:285 at save_controlmsg(): DEBUG: Agent mesgaSqQzUZs9 sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 12:06:36 wazuh-remoted[219841] manager.c:285 at save_controlmsg(): DEBUG: Agent r5zOrnxkq5rEV sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 6: <code>master</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: niEyaGfPNTxoM, IP: any, Disconnected
          ID: 002, Name: htCTKKFWIMjrr, IP: any, Disconnected

          ...
          ID: 049, Name: kAv5ahBT9wp2F, IP: any, Disconnected
          ID: 050, Name: TJ54Nwoi3lK2x, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>

  - <details><summary>Case 7: <code>master</code> with 50 agents gracefully stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart and inmediately stop all the agents.
    3. All the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: N8qhCAo4h1TjO, IP: any, Disconnected
          ID: 002, Name: p5jDd5pzMOPeu, IP: any, Disconnected

          ...

          ID: 049, Name: VBZN3msTJ1nQe, IP: any, Disconnected
          ID: 050, Name: 1h97NbK8guCRR, IP: any, Disconnected

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 12:15:00 wazuh-remoted[20994] manager.c:285 at save_controlmsg(): DEBUG: Agent p5jDd5pzMOPeu sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 12:15:00 wazuh-remoted[20994] manager.c:285 at save_controlmsg(): DEBUG: Agent N8qhCAo4h1TjO sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 8: <code>master</code> with 50 agents gracefully restart :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Gracefully restart all the agents.
    3. All the agents are in `Active` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: N8qhCAo4h1TjO, IP: any, Active
          ID: 002, Name: p5jDd5pzMOPeu, IP: any, Active

          ...

          ID: 049, Name: VBZN3msTJ1nQe, IP: any, Active
          ID: 050, Name: 1h97NbK8guCRR, IP: any, Active

        List of agentless devices:
        ```
    4. Check the `shutdown` message is received.
        ```log
        egrep -i "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        ...
        2023/03/08 12:16:59 wazuh-remoted[20994] manager.c:285 at save_controlmsg(): DEBUG: Agent p5jDd5pzMOPeu sent HC_SHUTDOWN from '192.168.56.1'
        2023/03/08 12:17:00 wazuh-remoted[20994] manager.c:285 at save_controlmsg(): DEBUG: Agent N8qhCAo4h1TjO sent HC_SHUTDOWN from '192.168.56.1'
        ```
        
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        50
        ```
    </details>

  - <details><summary>Case 9: <code>master</code> with 50 agents suddenly stop :green_circle:</summary>

    1. Connect 50 agents to the `master`.
    2. Suddenly stop all the agents.
    3. After a minute all the agents are in `Disconnected` status.
        ```
        /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
          ID: 000, Name: master (server), IP: 127.0.0.1, Active/Local
          ID: 001, Name: N8qhCAo4h1TjO, IP: any, Disconnected
          ID: 002, Name: p5jDd5pzMOPeu, IP: any, Disconnected

          ...

          ID: 049, Name: VBZN3msTJ1nQe, IP: any, Disconnected
          ID: 050, Name: 1h97NbK8guCRR, IP: any, Disconnected

        List of agentless devices:
        ```
    4. There is no `shutdown` message in this case.
        ```log
        egrep -i -c "HC_SHUTDOWN" /var/ossec/logs/ossec.log 

        0
        ```
    </details>
</details>

**Comment by QU3B1M** [comment]
# Conclusion :green_circle:

[Testing execution](https://github.com/wazuh/wazuh-qa/issues/3704#issuecomment-1460075523) successful :green_circle:. The shutdown message is received in each case and there is no agent left on a incorrect status.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by damarisg** [comment]
## Closing conclusion
Everything seems to be working properly
