### ISSUE TITLE
Update c++ std compilation version

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3713]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|     4.5.0                   |    https://github.com/wazuh/wazuh/issues/15316                    |        https://github.com/wazuh/wazuh/pull/15727            |

## Description

This issue aims to increase the minimum version of the standard from C++14 to C++17.

## Proposed test cases

 <details><summary>Test cases </summary>
  
  >**Note:** The following test cases must be executed in each OS supported by Wazuh, except HP UX

  - <details><summary>Run regression about syscollector installing Wazuh from packages </summary>

     1.  Install wazuh agent using packages
     2. Check the syscollector database 
     3. Check libraries are loaded in the installation

    </details>

   
  - <details><summary>Run regression about syscollector installing Wazuh from sources  </summary>
  
      1.  Install wazuh agent from sources
      2. Check the syscollector database 
      3. Check libraries are loaded  in the installation

        
      </details>
  
     
     
  </details>

## Considerations

Execute the test cases in all OS supported by Wazuh, except HP UX

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
