### ISSUE TITLE
Add AlmaLinux VDT IT support

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3723]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|   4.6.0     |    https://github.com/wazuh/wazuh/issues/10774       |  https://github.com/wazuh/wazuh/pull/16343  |

## Description
Add test support for VDT AlmaLinux provider, by adding cases to the current test suite.

## Proposed test cases
The following is a list of the modules where cases will be added

- [x] test_vulnerability_detector/test_providers/test_enabled
- [x] test_vulnerability_detector/test_providers/test_disabled
- [x] test_vulnerability_detector/test_providers/test_missing_os
- [x] test_vulnerability_detector/test_providers/test_multiple_provider_feeds
- [x] test_vulnerability_detector/test_providers/test_os
- [x] test_vulnerability_detector/test_providers/test_update_interval
- [x] test_vulnerability_detector/test_scan_results/test_svan_nvd_vulnerabilities
- [x] test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities
- [x] test_vulnerability_detector/test_scan_results/test_sca_provider_vulnerabilities
- [x] test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal

## Considerations
A custom feed will need to be researched and developed for this new provider.

**Comment by davidjiglesias** [comment]
Due to the new vulnerability detector refactor we have decided to skip almost all these tests, except for configuration.
