### ISSUE TITLE
Test WPK rollback fix when chkconfig is missing

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3726]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.6.0              | https://github.com/wazuh/wazuh/issues/15613           |     https://github.com/wazuh/wazuh/pull/15829               |

## Description

This Issue aims to test the fix for the Warning message that appears when a WPK upgrade rollback happens and `chkconfig` is not present in the system.

## Proposed checks

- [x] Check that Warning message  does nor appear when `chkconfig` is not present
- [x] Validate rollback happens properly
- [x] Validate agent is properly enabled after rollback

## Steps to reproduce
- Setup Manager and Agent
- Upgrade agent using WPK
- Cause rollback during upgrade (block connection from agent to manager, etc).
- Check rollback results

## Expected results
After the rollback the agent should be in it's initial version, enabled and working properly. The Warning message should not appear, even if `chkconfig` is missing

**Comment by Deblintrake09** [comment]
## Testing results

### Testing in 4.3.10
<details><summary>Upgrade using wpk detects missing chkconfig</summary>

- Install Manager 4.3.10
- Install 4.3.10 and connect to manager
```
# /var/ossec/bin/agent_control -i 002
 
Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: Ubuntu
   IP address: any/any
   Status:     Active

   Operating system:    Linux |Arrakis |5.14.0-1056-oem |#63-Ubuntu SMP Fri Dec 16 14:32:59 UTC 2022 |x86_64
   Client version:      Wazuh v4.3.10
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1674152569

   Syscheck last started at:  Thu Jan 19 18:22:47 2023 (Scan in progress)
   Syscheck last ended at:    Thu Jan 19 18:22:41 2023

```
- Start WPK upgrade
```
# /var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.3.11-3726.wpk.rollback.fix_linux_x86_64.wpk 

Upgrading...
```
- Check upgrade started in agent
```
2023/01/19 17:32:17 wazuh-agentd[6139] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-req af8afc62 com lock_restart -1'
2023/01/19 17:32:17 wazuh-agentd[6139] request.c:281 at req_receiver(): DEBUG: req_receiver(): sending 'lock_restart -1' to socket
2023/01/19 17:32:17 wazuh-agentd[6139] request.c:334 at req_receiver(): DEBUG: req_receiver(): sending '#!-req af8afc62 ok ' to server
2023/01/19 17:32:18 wazuh-agentd[6139] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-req af8afc63 upgrade {"command":"open","parameters":{"mode":"wb","file":"wazuh_agent_v4.3.11-3726.wpk.rollback.fix_linux_x86_64.wpk"}}'
2023/01/19 17:32:18 wazuh-agentd[6139] request.c:281 at req_receiver(): DEBUG: req_receiver(): sending '{"command":"open","parameters":{"mode":"wb","file":"wazuh_agent_v4.3.11-3726.wpk.rollback.fix_linux_x86_64.wpk"}}' to socket
2023/01/19 17:32:18 wazuh-agentd[6139] request.c:334 at req_receiver(): DEBUG: req_receiver(): sending '#!-req af8afc63 {"error":0,"message":"ok","data":[]}' to server
2023/01/19 17:32:18 wazuh-agentd[6139] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-req af8afc64 upgrade {"command":"write","parameters":{"buffer":"V1BLMjU2AC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEYXpDQ0FsTUNFeEFXS1RPdGt1UFRFRVA4RHY2TnY5Q25vWHd3RFFZSktvWklodmNOQVFFTEJRQXdjakVMCk1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RVRBUEJnTlZCQWNNQ0ZOaGJpQksKYjNObE1SSXdFQVlEVlFRS0RBbFhZWHAxYUNCSmJtTXhGREFTQmdOVkJBc01DMFZ1WjJsdVpXVnlhVzVuTVJFdwpEd1lEVlFRRERBaFhZWHAxYUNCRFFUQWVGdzB5TWpBNE1UZ3hOVFF4TlRWYUZ3MHlOREE0TVRjeE5UUXhOVFZhCk1ITXhDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJREFwRFlXeHBabTl5Ym1saE1SRXdEd1lEVlFRSERBaFQKWVc0Z1NtOXpaVEVTTUJBR0ExVUVDZ3dKVjJGNmRXZ2dTVzVqTVJRd0VnWURWUVFMREF0RmJtZHBibVZsY21sdQpaekVTTUJBR0ExVUVBd3dKVjJGNmRXZ2dWMUJMTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBNHU5eENoYk1CK3Y4RFU=","length":512,"file":"wazuh_agent_v4.3.11-3726.wpk.rollback.fix_linux_x86_64.wpk"}}'
```
- Check Upgrade.log in manager
</details>


### Testing in Dev Branch
<details><summary>Upgrade using wpk detects missing chkconfig</summary>

- Install Manager 4.3.10
- Install 4.3.8 and connect to manager
- Start WPK upgrade
- Force WPK fail and rollback
- Check Upgrade.log in manager
</details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to work correctly.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work properly.
