### ISSUE TITLE
Test FIM case sensitivity fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3727]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|    4.5.0            | https://github.com/wazuh/wazuh/issues/15800    |   https://github.com/wazuh/wazuh/pull/15843                 |

## Description
This Issue aims to test the fix for the false positives generated by FIM because it's checks for group permissions are not case sensitive.  The fix changes all user groups in windows to lowercase, to avoid false positives.

## Proposed checks

- [ ] Monitor Folder - Verify owner is in lowercase.
   - [ ] Username in `UPPERCASE` format
   - [ ] Username in `CamelCase` format
   - [ ] Username in `lowercase` format

## Steps to reproduce

1. Monitor folder
2. Create file with a given Username.
3. Check username appears in lowercase.

## Expected results
No False positives are generated when creating a different group with same name but different casing.

## Configuration and considerations
More information is required

**Comment by Deblintrake09** [comment]
## Update 13/01/2023
- Research Issue.
- No known way to replicate error.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
