### ISSUE TITLE
Syscollector `netaddr` deltas alerts are properly handled

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3732]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|v4.4| wazuh/wazuh#15639|https://github.com/wazuh/wazuh/pull/15675|

## Description

During  wazuh/wazuh#15639 exploratory (wazuh/wazuh#15824), it was found that `netaddr` scan, an inner part of network scan and base for Addresses in inventory data, is triggering a WARN message during rsync in specific conditions
```
2023/01/04 12:14:10 wazuh-db[82892] wdb_integrity.c:140 at wdb_calculate_stmt_checksum(): WARNING: DB(001) syscollector-netaddress component has more than one element with the same PK value '90b933f783ba98ef61d6b8ab6d0da29b8850efcc'.
```
_The problem_

After a RCA, it was found that the problem was related to `proto` field and its `encoded`, meaning that:

- proto=0 means "ipv4"
- otherwise means "ipv6"

At the same time, `proto` is a PK of netaddr, so when a MODIFICATION delta arrives to the manager, upsert clause insert the element with the same idemid used by rsync.
Also, analysisd pupulates `proto` with the encoded value and not the string value

_The solution_

During `analysisd` delta handling, replace the numeric `proto` value to string `ipv6`/`ipv4`

## Proposed checks

- [ ] Regular syscollector workflow

## Steps to reproduce

1. Agent starts. First syscollector scan is sync using rsync
2. Disable an agent's network interface (not the one used to communicate with the manager)
3. Agent executes second syscollector scan and sync the results using deltas
4. Agente sync the second scan using rsync

## Expected results

3. wazuh-db delta's debug message show `proto` with string value `ipv4`/`ipv6` . No warning was shown. 
4 .wazuh-db rsync debug message does not need sync. No warning was shown. 

### Current results

3. wazuh-db delta's debug message show `proto` with numeric value 0/1. No warning was shown. 
4 .wazuh-db rsync debug message need sync. Warning was shown. 

> **Consideration**: Set the rules in each manager instance, and set wazuh_db in debug mode (in each manager). Turn off FIM, SCA, and all the modules that interact with wazuh-db.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
