### ISSUE TITLE
Auto causes copy - Coverity issue

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3740]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|          4.5              |     https://github.com/wazuh/wazuh/issues/14673                   |       https://github.com/wazuh/wazuh/pull/15608             |

## Description

Based on the execution delivered in https://github.com/wazuh/wazuh/issues/14657, some issues appear on this execution.
Check if syscollector is still working on Windows, Linux, and macOS

### MacOS
- [x] Upgrade to core-branch and check syscollector continue working
       1. Check `sys_processes` table has information
       2.  Check `sys_hwinfo` table has information
       3.  Check `sys_netaddr` table has information
       4.  Check `sys_netiface` table has information
       5. Check `sys_netproto` table has information
       6. Check `sys_osinfo` table has information
       7. Check `sys_ports` table has information
       8. Check `sys_programs` table has information
   
- [x] Fresh install core-branch and check syscollector continue working
      1. Check `sys_processes` table has information
      2.  Check `sys_hwinfo` table has information
      3.  Check `sys_netaddr` table has information
      4.  Check `sys_netiface` table has information
      5. Check `sys_netproto` table has information
      6. Check `sys_osinfo` table has information
      7. Check `sys_ports` table has information
      8. Check `sys_programs` table has information

### Linux
- [x] Upgrade to core-branch and check syscollector continue working
      1. Check `sys_processes` table has information
      2.  Check `sys_hwinfo` table has information
      3.  Check `sys_netaddr` table has information
      4.  Check `sys_netiface` table has information
      5. Check `sys_netproto` table has information
      6. Check `sys_osinfo` table has information
      7. Check `sys_ports` table has information
      8. Check `sys_programs` table has information

- [x] Fresh install core-branch and check syscollector continue working
      1. Check `sys_processes` table has information
      2.  Check `sys_hwinfo` table has information
      3.  Check `sys_netaddr` table has information
      4.  Check `sys_netiface` table has information
      5. Check `sys_netproto` table has information
      6. Check `sys_osinfo` table has information
      7. Check `sys_ports` table has information
      8. Check `sys_programs` table has information

### Windows
- [x] Upgrade to core-branch and check syscollector continue working
       1. Check `sys_processes` table has information
       2.  Check `sys_hwinfo` table has information
       3.  Check `sys_netaddr` table has information
       4.  Check `sys_netiface` table has information
       5. Check `sys_netproto` table has information
       6. Check `sys_osinfo` table has information
       7. Check `sys_ports` table has information
       8. Check `sys_programs` table has information
       
- [x] Fresh install core-branch and check syscollector continue working
       1. Check `sys_processes` table has information
       2.  Check `sys_hwinfo` table has information
       3.  Check `sys_netaddr` table has information
       4.  Check `sys_netiface` table has information
       5. Check `sys_netproto` table has information
       6. Check `sys_osinfo` table has information
       7. Check `sys_ports` table has information
       8. Check `sys_programs` table has information

...

**Comment by BelenValdivia** [comment]
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/15608/commits/2c0d699af198f55e2986c8e3fe503dee6b235965 | 



### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS             | CentOS 8        | vagrant       | `qactl/centos_8` |
| Windows |  Windows Server 2019 | vagrant | `qactl/windows_2019` |
| MacOS|   | vagrant | `` |



### Tested executable file

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Windows      |                                                                             |
| CentOS |                                                                             |
| MacOS |                                                                             |



## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @Dwordcito 


## Conclusion

**Comment by BelenValdivia** [comment]
# Test results

## Upgrade

<details><summary> Linux </summary>

</details>

<details><summary> Windows</summary>

</details>

<details><summary> MacOS</summary>

</details>

**Comment by BelenValdivia** [comment]
### 17/01/2023
- Downloaded macOS box
- Tested syscollector on linux: Upgrade

**Comment by BelenValdivia** [comment]
### 18/01/2023
- Set up macOS vm
- Tested syscollector on macos
- Set up centos manager vm

**Comment by BelenValdivia** [comment]
19/01/2023
- Set up Windows vm
- Tested syscollector on Windows
- Set up centos manager vm

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.  It will be verify if there are new failures in the next coverage scan run.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼 

Everything seems to be working properly.
