### ISSUE TITLE
Fix agent does not stop correctly after applying invalid configuration in Syscollector

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3741]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|        4.5.0              |      https://github.com/wazuh/wazuh/issues/15412    |         https://github.com/wazuh/wazuh/pull/15575           |

## Description

This issue fix the following error: the Wazuh agent does not stop correctly after applying an invalid configuration and
multiple logs are displayed on repeat in the ossec.log file.

## Proposed test cases

**Windows:**

  - <details><summary>Upgrade to core-branch</summary>

     1.  Install wazuh agent 
     2. With the agent stopped or running, apply an invalid configuration in Syscollector and start/restart.
     3. Stop the agent (through PS or UI)
     4. Check that there are no errors in the ossec.log
     5. No errors in EventViewer
     6. The agent must be stopped correctly

    </details>

  - <details><summary>Fresh install core-branch</summary>

     1. Install wazuh agent 
     2. With the agent stopped or running, apply an invalid configuration in Syscollector and start/restart.
     3. Stop the agent (through PS or UI)
     4. Check that there are no errors in the ossec.log
     5. No errors in EventViewer
     6. The agent must be stopped correctly

    </details>
    
   **Linux:**

  - <details><summary>Upgrade to core-branch</summary>

     1.  Install wazuh agent 
     2. With the agent stopped or running, apply an invalid configuration in Syscollector and start/restart.
     3. Stop the agent 
     4. Check that there are no errors in the ossec.log
     5. The agent must be stopped correctly

    </details>

  - <details><summary>Fresh install core-branch</summary>

     1. Install wazuh agent 
     2. With the agent stopped or running, apply an invalid configuration in Syscollector and start/restart.
     3. Stop the agent 
     4. Check that there are no errors in the ossec.log
     5. The agent must be stopped correctly

    </details>
    
...

**Comment by BelenValdivia** [comment]
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   |  https://github.com/wazuh/wazuh/pull/15575/commits/ed0cf575cc7996d476284d708d21755e48662c31 | 



## Testing environment

- CentOS 8
- Windows Server 2019

## Packages
- Windows: [msi](https://packages-dev.wazuh.com/warehouse/test/4.5/windows/wazuh-agent-4.5.0-11.1.0.invsyscollector.msi)
- CentOS agent: [rpm](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-agent-4.5.0-11.1.0.invsyscollector.x86_64.rpm)
- CentOS manager: [rpm 
](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-11.1.0.invsyscollector.x86_64.rpm)

## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @Dwordcito 


## Conclusion

**Comment by BelenValdivia** [comment]
## 13/01/2023

- Set up windows agent
- Reproduce bug
- Upgrade

**Comment by BelenValdivia** [comment]
## Reproduce the bug

<details><summary> Windows</summary>

1- Add invalid configuration
```
  <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>invalid</processes>
```

2- Restart the agent

3- Stop the agent 

4- Check ossec.log

```
 2023/01/11 07:40:38 wazuh-agent: INFO: Started (pid: 3816).
 2023/01/11 07:40:38 wazuh-agent: ERROR: Invalid content for tag 'processes' at module 'syscollector'.
 2023/01/11 07:40:38 wazuh-agent: ERROR: (1202): Configuration error at 'ossec.conf'.
```
5- Error when stopping via Powershell

```
PS C:\Windows\system32> net stop WazuhSvc
System error 109 has occurred.

The pipe has been ended.
```

6- Errors in ossec.log

```
07:42:49 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2023/01/11 07:42:49 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/01/11 07:42:49 wazuh-agent: INFO: Set pending exit signal.
2023/01/11 07:42:49 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/01/11 07:42:49 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2023/01/11 07:42:49 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/01/11 07:42:49 wazuh-agent: INFO: Set pending exit signal.
2023/01/11 07:42:49 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/01/11 07:42:49 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2023/01/11 07:42:49 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/01/11 07:42:49 wazuh-agent: INFO: Set pending exit signal.
2023/01/11 07:42:49 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/01/11 07:42:49 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2023/01/11 07:42:49 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/01/11 07:42:49 wazuh-agent: INFO: Set pending exit signal.
2023/01/11 07:42:49 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/01/11 07:42:49 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2023/01/11 07:42:49 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/01/11 07:42:49 wazuh-agent: INFO: Set pending exit signal.

```

7- Error in EventViewer

 
![Screenshot 2023-01-11 142849](https://user-images.githubusercontent.com/26927338/212755169-38fdc6ae-d15d-44cb-8f4e-a4946b1ba7ee.png)


</details>

## Fresh Install

<details><summary> Windows</summary>

</details>

<details><summary> Linux</summary>

</details>

## Upgrade

<details><summary> Windows</summary>

</details>

<details><summary> Linux</summary>

</details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: The testing verified that the fix is applied and works correctly on Windows. However, the QA found a new wrong behavior in Linux(https://github.com/wazuh/wazuh/issues/15951).

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

The new changes seem to work properly. However, it has been reported an issue (non-related with the made changes):

- **(1) After applying an invalid configuration and restarting Wazuh, it is stopped (syscollector - Linux)**

  This has been reported in this issue [#wazuh/15951](https://github.com/wazuh/wazuh/issues/15951) and will be fixed in future versions.
