### ISSUE TITLE
Fix some packages in Solaris OS can't be properly read by syscollector if their description contains invalid UTF-8 characters

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3743]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|    4.4.0                    |     https://github.com/wazuh/wazuh/issues/15838    |     https://github.com/wazuh/wazuh/pull/15868       |

## Description

This issue fix the following error: certain characters in the packages' description in Solaris might generate error messages

## Proposed test cases

- Upgrade to core-branch

    1.  Install Wazuh agent
    2. Install a package with invalid UTF-8 characters in the description.
    3. Start Wazuh.
    4. Check that there are no errors in the ossec.log.
    
- Fresh install core-branch

    1. Install Wazuh agent
    2. Install a package with invalid UTF-8 characters in the description.
    3. Start Wazuh.
    4. Check that there are no errors in the ossec.log.
...

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia    |   https://github.com/wazuh/wazuh/pull/15868/commits/a506fc097e2962afc0d18a03ac06b998fc270b6b | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI |
|----|------------|-----------------------------------------------|-----------|
|  CentOS  | CentOS 8 | ` Vagrant` | `qactl/centos_8` |
|  Solaris |  Solaris 11 | ` Vagrant` | `deployer pipeline version` |

### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Solaris 11|  [Agent](https://packages-dev.wazuh.com/warehouse/test/4.4/solaris/i386/11/wazuh-agent_v4.4.0-12.1.0.utfnobug-sol11-i386.p5p)      |


### Status

- [x] In progress @BelenValdivia 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @Dwordcito 

### Conclusion

**Comment by BelenValdivia** [comment]
# Testing results

## Unfixed

<details><summary>Error reproduction</summary>
  
  1. Install and start `wazuh-agent-4.4.0` 
  2. Install package with invalid character
  
      ```
      /opt/csw/bin/pkgutil -y -i schilybase
      ```

  3.Check package installed  `cat /var/sadm/pkg/CSWschilybase/pkginfo`

      ```
       CLASSES=none
       BASEDIR=/opt/csw
       INSTDATE=Jan 12 2023 16:59
       PKGSAV=/var/sadm/pkg/CSWschilybase/save
       PKGINST=CSWschilybase
       PSTAMP=joerg@unstable9x-20130619141117
       EMAIL=joerg@opencsw.org
       HOTLINE=http://www.opencsw.org/bugtrack/
       VENDOR=http://cdrecord.berlios.de/old/private/  packaged for CSW by J▒rg Schilling
       CATEGORY=application
       NAME=schilybase - A collection of common files from J. Schilling
       PKG=CSWschilybase
       VERSION=1.01,REV=2013.06.19
       ARCH=i386
       OAMBASE=/usr/sadm/sysadm
       PATH=/sbin:/usr/sbin:/usr/bin:/usr/sadm/install/bin
       TZ=localtime
       LANG=C
       LC_ALL=
       LC_MONETARY=
       LC_MESSAGES=
       LC_COLLATE=
       LC_TIME=
       LC_NUMERIC=
       LC_CTYPE=
      ```

  4. Check error log in  `/var/ossec/logs/ossec.log`
  
      ```
      2023/01/12 17:03:30 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_solaris11.yml'
      2023/01/12 17:03:31 wazuh-modulesd:syscollector: ERROR: [json.exception.type_error.316] invalid UTF-8 byte at index 62: 
      0xF6
      2023/01/12 17:03:31 wazuh-modulesd:syscollector: INFO: Evaluation finished.
      ```

  </details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
