### ISSUE TITLE
Remove test_max_eps skip mark

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3749]
## Description
During development on #1915, `test_fim/test_files/test_max_eps.py` was having flaky behavior on whodata mode. It was found that even though audits sends all logs to wazuh, when a lot of logs are sent in succession in the same second, some logs are skipped, causing logs to be missed on Wazuh's end. 

This will be handled in @wazuh/wazuh Issue #[15844](https://github.com/wazuh/wazuh/issues/15844). When it is completed, test_max_eps should be enabled.

### Current behavior
The module `test_fim/test_files/test_max_eps.py` is skipped.

### Expected behavior
The module `test_fim/test_files/test_max_eps.py` is enabled and works properly in realtime and whodata modes.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
