### ISSUE TITLE
Validate Resource leak reported by coverity is fixed

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3753]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 |   [#15908](https://github.com/wazuh/wazuh/issues/15908) | [#15909](https://github.com/wazuh/wazuh/pull/15909)   |

## Description

It must be validated the resource leak defect reported by coverity is fixed with PR [#15909](https://github.com/wazuh/wazuh/pull/15909)

## Proposed checks

- [x] Run coverity build script locally
  <details><summary>Test case</summary>
      
    1. Execute the tool aiming to the fixed branch.  
      `BRANCH=fix-coverity-4-4 TARGET=server ./coverity.sh --ossec`
    2. Check the build is done successfully.
     
       > Example
       > ```log
       > make[1]: Leaving directory '/home/quebim/Wazuh/wazuh-tools-master/coverity/wazuh/src'
       > 
       > Done building server
       > 
       > Emitted 482 C/C++ compilation units (100%) successfully
       > 
       > 482 C/C++ compilation units (100%) are ready for analysis
       > The cov-build utility completed successfully.
       > Version: v4.3.6-r40318
       > Branch: 14365-fix-coverity-error (ccfdcafc35b785c18258e2a17d874780718b2eab)
       > Project: wazuh%2Fossec-wazuh (3sQ--QTA0tHNvZNG5FH3IQ)
       > Target: server
       > ```    
    </details>

- [x] Validate the error is fixed in Coverity server
  <details><summary>Test case</summary>

    1. Find code with the error in Coverity before fix (`CID 307209`).
    2. Search the defect `CID 307209` and check the status is fixed.
    3. Check the defect `CID 307209` disappeared after fix.

    </details>

## Expected results

The defect is fixed and it could be validated in coverity

**Comment by QU3B1M** [comment]
# Testing results


<details><summary><strong>Run coverity build script locally</strong></summary>
    
 1. Execute the tool aiming to the fixed branch.
   
    `BRANCH=fix-coverity-4-4 TARGET=server ./coverity.sh --ossec`
 2. Check the build is done successfully.
    ```log
    Emitted 492 C/C++ compilation units (100%) successfully

    492 C/C++ compilation units (100%) are ready for analysis
    The cov-build utility completed successfully.
    Version: v4.4.0-r40402
    Branch: fix-coverity-4-4 (807c153c107146eb35fc67582f7f5dd95de15479)
    Project: wazuh%2Fossec-wazuh (3sQ--QTA0tHNvZNG5FH3IQ)
    Target: server
    ```
</details>


<details><summary><strong>Validate the error is fixed in Coverity server</strong></summary>

  1. Find code with the error in Coverity before fix (`CID 307209`).
    ![coverity-CID](https://user-images.githubusercontent.com/44633633/212780704-334fee2c-0826-4a76-8ca6-021a25aee8c2.png)

  2. Search the defect `CID 307209` and check the status is fixed.
    ![coverity-disappeared](https://user-images.githubusercontent.com/44633633/212780708-d2b2b3fc-9a02-481e-9b51-64367d85b7e4.png)

  3. Check the defect `CID 307209` disappeared after fix.
    ![coverity-fixed](https://user-images.githubusercontent.com/44633633/212780711-8d8ee69e-e7b0-45f8-9acc-9a5a1d5a5237.png)

</details>

**Comment by QU3B1M** [comment]
# Testing results


<details><summary><strong>Run coverity build script locally</strong></summary>
    
 1. Execute the tool aiming to the fixed branch.
   
    `BRANCH=fix-coverity-4-4 TARGET=server ./coverity.sh --ossec`
 2. Check the build is done successfully.
    ```log
    Emitted 492 C/C++ compilation units (100%) successfully

    492 C/C++ compilation units (100%) are ready for analysis
    The cov-build utility completed successfully.
    Version: v4.4.0-r40402
    Branch: fix-coverity-4-4 (807c153c107146eb35fc67582f7f5dd95de15479)
    Project: wazuh%2Fossec-wazuh (3sQ--QTA0tHNvZNG5FH3IQ)
    Target: server
    ```
</details>


<details><summary><strong>Validate the error is fixed in Coverity server</strong></summary>

  1. Find code with the error in Coverity before fix (`CID 307209`).
    ![coverity-CID](https://user-images.githubusercontent.com/44633633/212780704-334fee2c-0826-4a76-8ca6-021a25aee8c2.png)

  2. Search the defect `CID 307209` and check the status is fixed.
    ![coverity-disappeared](https://user-images.githubusercontent.com/44633633/212780708-d2b2b3fc-9a02-481e-9b51-64367d85b7e4.png)

  3. Check the defect `CID 307209` disappeared after fix.
    ![coverity-fixed](https://user-images.githubusercontent.com/44633633/212780711-8d8ee69e-e7b0-45f8-9acc-9a5a1d5a5237.png)

</details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be correct 🟢 .
