### ISSUE TITLE
Validate the optimization in agent key synchronization

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3755]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.1 | [#15437](https://github.com/wazuh/wazuh/issues/15437) | [#15883](https://github.com/wazuh/wazuh/pull/15883) |

## Description

This issue aims to validate the performance improvement in the new agent syncronization in database that was achieved by querying the db only for the new agents.
Also it must be validated that the deprecated folder `var/db/agents` is removed from all references and does not longer exist in `wazuh-manager` installation.

## Proposed checks

- [x] Deprecated folder is removed

   <details><summary>Test Cases</summary>

    - <details><summary>Folder does not exist in <code>wazuh-manager</code></summary>

      1. Install/upgrade to `wazuh-manager v4.4.1-fixed`.
      2. Check the folder `var/db/agents` does not exist.
      3. Check there is no **ERROR**/**WARNING** in logs. 
      </details>

    - <details><summary>Folder does not exist in any <code>wazuh-cluster</code> node</summary>

      4. Install/upgrade to `wazuh-cluster v4.4.1-fixed` with 1 master + 2 workers nodes.
      5. Check the folder `var/db/agents` does not exist in any node.
      6. Check there is no **ERROR**/**WARNING** in logs. 
      </details>
    </details>

- [x] Benchmark - Agent registration metrics

  <details><summary>Benchmark details</summary>

    This benchmark consists in executing the script [enrollment-benchmark](https://github.com/wazuh/wazuh/issues/15434#issuecomment-1319824499) while checking the amount of queries received by `wazuh-db` 
    > To check the queries amount use: `curl -k -X GET "https://localhost:55000/manager/daemons/stats?daemons_list=wazuh-db&pretty=true" -H "Authorization: Bearer $TOKEN"`
      
    **Benchmark cases:**
    - Benchmark register 500 agents
    - Benchmark with the previous 500 agents still registered, register another 500 agents.
    - Benchmark remove 100 agents x2 (remove 100 agents and then other 100 checking performance each time)
    > This way we can validate the performance difference between querying `wazuh-db` for new registered agents only instead of the old behavior.
      
    **Benchmark execution:**
    1. Execute the benchmark on `wazuh-cluster v4.4.0-beta` with 1 master + 2 workers nodes.
    2. Execute the benchmark on `wazuh-cluster v4.4.1-fixed` with 1 master + 2 workers nodes.
    3. Compare benchmarks, the manager `v4.4.1-fixed` should be better.
    </details>

- [x] Benchmark - Enrollment throughput
  <details><summary>Benchmark details</summary>

    This benchmark consist in checking the performance when enrolling a big amount of agents, similar to the tested in [this comment](https://github.com/wazuh/wazuh/issues/15434#issuecomment-1319841428).
    </details>

### Required installation methods
- [x] Fresh install
- [x] Upgrade

### Required OS
- [x] Linux

**Comment by QU3B1M** [comment]
# Testing results

## Unfixed

<details><summary>Deprecated folder still exists</summary>

  1. Install/upgrade to `wazuh-manager v4.4.1-fixed`.
  2. Connect a `wazuh-agent` to the `wazuh-manager`.
  3. Check the folder `var/db/agents` does not exist.
      ```bash
      [ -d /var/ossec/var/db/agents ] && echo "Directory exists."
      
      Directory exists.
      ```
  4. Check there is no **ERROR**/**WARNING** in logs. 
      ```bash
      egrep "ERR|WARN" /var/ossec/logs/ossec.log 
      ```
</details>

## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade `wazuh-manager `
  ```powershell
  dpkg -i wazuh-manager_4.4.0-0.commit7e77ca2_amd64.deb 
  
  (Reading database ... 123232 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commit7e77ca2_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commit7e77ca2) over (4.3.9-1) ...
  Setting up wazuh-manager (4.4.0-0.commit7e77ca2) ...
  Processing triggers for systemd (245.4-4ubuntu3.17) ...
  ```
</details>

<details><summary>Deprecated folder is removed :green_circle:</summary>

  - <details><summary>Folder does not exist in <code>wazuh-manager</code> :green_circle:</summary>

    1. Check the folder `var/db/agents` does not exist.
        ```bash
        [ -d /var/ossec/var/db/agents ] && echo "Directory exists."
        ```
    2. Check there is no **ERROR**/**WARNING** in logs. 
        ```bash
        egrep "ERR|WARN" /var/ossec/logs/ossec.log 

        ```
    </details>

  - <details><summary>Folder does not exist in any <code>wazuh-cluster</code> node :green_circle:</summary>

    1. With the cluster configuration of 1 master + 2 workers nodes.
    2. Connect a `wazuh-agent` to the `wazuh-manager`.
    3. Check the folder `var/db/agents` does not exist in any node.
        ```bash
        [ -d /var/ossec/var/db/agents ] && echo "Directory exists."
        ```
    4. Check there is no **ERROR**/**WARNING** in any node's logs. 
        ```bash
        egrep "ERR|WARN" /var/ossec/logs/ossec.log 

        ```
    </details>
</details>

## Fresh install

<details><summary>Deprecated folder is removed :green_circle:</summary>

  - <details><summary>Folder does not exist in <code>wazuh-manager</code> :green_circle:</summary>

    1. Install `wazuh-cluster v4.4.1-fixed`
    2. Connect a `wazuh-agent` to the `wazuh-manager`.
    3. Check the folder `var/db/agents` does not exist.
        ```bash
        [ -d /var/ossec/var/db/agents ] && echo "Directory exists."
        ```
    4. Check there is no **ERROR**/**WARNING** in logs. 
        ```bash
        egrep "ERR|WARN" /var/ossec/logs/ossec.log 

        ```
    </details>

  - <details><summary>Folder does not exist in any <code>wazuh-cluster</code> node :green_circle:</summary>

    1. Set a cluster configuration of 1 master + 2 workers nodes.
    2. Connect a `wazuh-agent` to the `wazuh-manager`.
    3. Check the folder `var/db/agents` does not exist in any node.
        ```bash
        [ -d /var/ossec/var/db/agents ] && echo "Directory exists."
        ```
    4. Check there is no **ERROR**/**WARNING** in any node's logs. 
        ```bash
        egrep "ERR|WARN" /var/ossec/logs/ossec.log 
        ```
    </details>
</details>

**Comment by QU3B1M** [comment]
# Benchmark

**Comment by QU3B1M** [comment]
## Enrollment throughput

### Enroll 1000 agents 

<details><summary>Results on <code>4.4.0-1</code></summary>

   **Success**
   ```
   Operations: 1000
     Success: 1000
     Failure: 0
   Time: 356.3021480003954 ms.
   Performance: 2806.6067117812895 ops/sec.
   ```

   **Duplicate without force**
   ```
   Operations: 1000
     Success: 0
     Failure: 1000
   Time: 412.2028589990805 ms.
   Performance: 2425.989966271027 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 1000
     Success: 0
     Failure: 1000
   Time: 298.10182199435076 ms.
   Performance: 3354.5584971934545 ops/sec.
   ```
</details>


<details><summary>Results on <code>4.4.0-0.commit7e77ca2</code></summary>

   **Success**
   ```
   Operations: 1000
     Success: 1000
     Failure: 0
   Time: 165.52023099939106 ms.
   Performance: 6041.557542314444 ops/sec.
   ```

   **Duplicate without force**
   ```
   Operations: 1000
     Success: 0
     Failure: 1000
   Time: 465.82465800020145 ms.
   Performance: 2146.7304978938396 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 1000
     Success: 0
     Failure: 1000
   Time: 430.8583499951055 ms.
   Performance: 2320.9484045310014 ops/sec.
   ```
</details>


|                   | `4.4.0-1` | `4.4.0-0.commit7e77ca2` (fix) |
|-------------------|-----------|-------------------------------|
|Success            |  2806.60 ops/sec       |6041.55 ops/sec   |
|Duplicate w/ force |  3354.55 ops/sec       |2320.94 ops/sec   |
|Duplicate w/o force|  2425.98 ops/sec       |2146.73 ops/sec   |





### Enroll 14000 agents

<details><summary>Results on <code>4.4.0-1</code></summary>

   **Success**
   ```
   Operations: 14000
     Success: 14000
     Failure: 0
   Time: 21919.157989002997 ms.
   Performance: 638.7106661224808 ops/sec.
   ```

   **Duplicate without force**
   ```
   Operations: 14000
     Success: 0
     Failure: 14000
   Time: 6577.487593000114 ms.
   Performance: 2128.472277910347 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 14000
     Success: 0
     Failure: 14000
   Time: 5396.192851003434 ms.
   Performance: 2594.4217314984708 ops/sec.
   ```
</details>


<details><summary>Results on <code>4.4.0-0.commit7e77ca2</code></summary>

   **Success**
   ```
   Operations: 14000
     Success: 14000
     Failure: 0
   Time: 10625.523868002347 ms.
   Performance: 1317.582095143519 ops/sec.
   ```

   **Duplicate without force**
   ```
   Operations: 14000
     Success: 0
     Failure: 14000
   Time: 5782.844141998794 ms.
   Performance: 2420.954059322272 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 14000
     Success: 0
     Failure: 14000
   Time: 6226.218204996258 ms.
   Performance: 2248.5559514707716 ops/sec.
   ```
</details>


|                   | `4.4.0-1` | `4.4.0-0.commit7e77ca2` (fix) |
|-------------------|-----------|-------------------------------|
|Success            |638.71 ops/sec    |  1317.58 ops/sec       |
|Duplicate w/ force |2594.42 ops/sec   |  2248.55 ops/sec       |
|Duplicate w/o force|2128.47 ops/sec   |  2420.95 ops/sec       |


### Enroll 90000 agents


<details><summary>Results on <code>4.4.0-1</code></summary>

   **Success**
   ```
   FAILS
   ```

   **Duplicate without force**
   ```
   Operations: 90000
     Success: 0
     Failure: 90000
   Time: 52763.43316699786  ms.
   Performance: 1705.7267618493909 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 90000
     Success: 0
     Failure: 90000
   Time: 24507.012348999524 ms.
   Performance: 3672.4182743423708 ops/sec.
   ```
</details>


<details><summary>Results on <code>4.4.0-0.commit7e77ca2</code></summary>

   **Success**
   ```
   Operations: 90000
     Success: 90000
     Failure: 0
   Time: 280379.80440400133 ms.
   Performance: 320.99316208352275 ops/sec.
   ```

   **Duplicate without force**
   ```
   Operations: 90000
     Success: 0
     Failure: 90000
   Time: 38350.107639998896 ms.
   Performance: 2346.799149688191 ops/sec.
   ```

   **Duplicate with force**
   ```
   Operations: 90000
     Success: 0
     Failure: 90000
   Time: 30458.206178002 ms.
   Performance: 2954.8686969294076 ops/sec.
   ```
</details>

|                   | `4.4.0-1` | `4.4.0-0.commit7e77ca2` (fix) |
|-------------------|-----------|-------------------------------|
|Success            |------ ops/sec    |  320.99 ops/sec        |
|Duplicate w/ force |3672.41 ops/sec   |  2954.86 ops/sec       |
|Duplicate w/o force|1705.72 ops/sec   |  2346.79 ops/sec       |

**Comment by QU3B1M** [comment]
## Enrollment flow validation :green_circle: 

> This is a "tipical" enrollment scenario, the idea of it is to check the full enrollment (agents + manager) still works correctly.

1. With the cluster configuration of 1 master + 1 worker node.
2. Connect a `wazuh-agent` to the `worker`.
3. Check the `wazuh-agent` is enrolled and connected successfully.
    ```JSON
    {"timestamp":"2023-02-06T22:34:31.526+0000","rule":{"level":3,"description":"New ossec agent connected.","id":"501","firedtimes":1,"mail":false,"groups":["ossec"],"pci_dss":["10.6.1"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6"],"tsc":["CC7.2","CC7.3"]},"agent":{"id":"001","name":"agent"},"manager":{"name":"worker"},"id":"1675722871.678891","cluster":{"name":"wazuh","node":"worker1"},"full_log":"ossec: Agent started: 'agent->any'.","decoder":{"parent":"ossec","name":"ossec"},"data":{"extra_data":"agent->any"},"location":"wazuh-agent"}
    ```
    ```
    cat /var/ossec/logs/ossec.log 
    2023/02/06 22:34:11 wazuh-authd: INFO: Received request for a new agent (agent) from: 192.168.56.13
    2023/02/06 22:34:11 wazuh-authd: INFO: Agent key generated for 'agent' (requested by any)
    ```
4. Restart the `worker` node.
5. Check the agent does not re-enroll and there is no **ERROR**/**WARNING** raised. 
    ```bash
    egrep "ERR|WARN" /var/ossec/logs/ossec.log 

    ```

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
