### ISSUE TITLE
Research agent groups system tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3775]
## Description

After performing some checks, it has been found that the performance of `agent-groups` is not as expected. It is necessary to verify that the existing system tests are stable and working correctly in order to continue with the release process.

The tests and their current environments are as follows:

|Test| Environment|
|--|--|
| test_multigroups/test_multigroups                                         | basic_cluster                  |
| test_cluster/test_agent_groups/test_agent_groups_forced_change            | basic_cluster                  |
| test_cluster/test_agent_groups/test_agent_default_group_added             | enrollment_cluster             |
| test_cluster/test_agent_groups/test_agent_groups_new_cluster_node         | four_manager_disconnected_node |
| test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment    | enrollment_cluster             |
| test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group | enrollment_cluster             |
| test_cluster/test_agent_groups/test_assign_agent_to_a_group_api           | enrollment_cluster             |
| test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool       | enrollment_cluster             |
| test_cluster/test_agent_groups/test_assign_agent_to_a_group               | enrollment_cluster             |
| test_cluster/test_agent_groups/test_assign_groups_guess                   | enrollment_cluster             |
| test_cluster/test_agent_groups/test_groups_sync_default                   | big_cluster_40_agents          |
| test_cluster/test_agent_groups/test_groups_sync_time                      | big_cluster_40_agents          |

The following issues will be carried out for research and stabilization:

- Research `test_multigroups`
- Research `test_agent_groups_forced_change`
- Research `test_agent_groups_forced_change`
- Research `test_agent_groups_forced_change`
- Research `test_agent_groups_forced_change`
- Research `test_agent_groups_forced_change`

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
