### ISSUE TITLE
Wrong resources on FIM integration tests

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#379]
Hello team,

The CICD team is working on integrating all fim testing in Jenkins. During this task, a number of possible failures have been detected, which are as follows:

**Timeout error**

First, the 'test_basic_usage' has been run on an agent and manager CentOS machine, and the following results have been obtained.

![imagen](https://user-images.githubusercontent.com/23462183/72363904-ee3bb800-36f5-11ea-9b76-7dcbd90797ca.png)

As you can see, there are several tests that have not passed, and even during different executions, different ones have failed.

Talking about it with @CarlosRS9  (framework team), we have assumed that the possible cause is that they are failing for timeout reasons. A possible solution to this is to increase machine resources or timeout.

*CentOS tests performed*

| RAM        | CPU           | TIMEOUT  |  Tests failed |
| ------------- |:-------------:| -----| -----|
| 256 mb      | 1 | 5 | 21 |
| 1024 mb  | 2     |   10 | 7 |
| 1024 mb | 2      |  15  | 6 |
 
  
It is suggested to increase the timeout set for Linux by about **15 seconds**.

**Basic usage tests failure**

Once the resources and timeout have been increased, a total of 84 tests have been passed and 6 failed.

![imagen](https://user-images.githubusercontent.com/23462183/72366972-a15ae000-36fb-11ea-8f63-b348ef7ece5e.png)

As I have been told, these failures are positive alerts, and @wazuh/core will have to fix.

**ossec.conf parser failure**

The tests carried out for the CentOS environment have been by means of a source installation.

After performing a package installation, and then running the tests, all tests have failed, with most reporting the following error:

```
File "<string>", line None
   xml.etree.ElementTree.ParseError: junk after document element: line 349, column 0
```
This error may be due to the `ossec.conf` generated after the package installation not being the same as after the source installation and that it cannot be read by the parser.

**Windows Test Failures**

When launching the basic test usage in Windows, a total of 47 passes and 42 fails were obtained.

As @CarlosRS9 (from the framework team) commented, it is possible that the modification events can be separated in 2 or 3 alerts.

Besides, another error detected is that in [syscheck_event_windows.json](https://github.com/wazuh/wazuh-qa/blob/master/packages/wazuh_testing/wazuh_testing/data/syscheck_event_windows.json) file has to be changed the [win_attributes](https://github.com/wazuh/wazuh-qa/blob/master/packages/wazuh_testing/wazuh_testing/data/syscheck_event_windows.json#L205) for `attributes` and add them to `changed_attributes`.

Best regards.

**Comment by jmv74211** [comment]
Hello team,

I've been running some additional tests regarding the failure to parser the `ossec.conf`.

I have discovered that in the `ossec.conf` that is generated in the installation via packages (agent and manager), there are two blocks `<ossec_config>`.

 The first block consists of the common configuration , and the second block corresponds to: 

```
<ossec_config>
  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
</ossec_config>
```

If this second block is removed, the tests are run normally.

I propose to update the parser so that it contemplates this second block `<ossec_config>`.

Best regards.

**Comment by CarlosRS9** [comment]
# Status Update

Hello Team,

The requested change to rename `win_attributes` to `attributes` to fix one of the reported `Windows Test Failures` will be applied with PR #380.

Regarding the `ossec.conf parser failure`, that error was raised because the `ossec.conf` generated by the package installation had an invalid xml structure and it caused an `xml.etree.ElementTree.ParseError`. As this is a problem with the xml format we will fix it by creating an auxiliary function that will transform the `ossec.conf` file to a valid xml format before it is parsed.

Best regards.
