### ISSUE TITLE
Research `test_agent_groups_new_cluster_node`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3797]
## Description

As part of #3776, in this issue, we will investigate the `test_agent_groups_new_cluster_node` test in particular. We must verify that the test is stable and passes correctly.

**Comment by Rebits** [comment]
### Update 20/01/2023

```
root@ip-172-31-6-112:/home/qa/wazuh-qa/tests# python3 -m pytest system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py 
========================================= test session starts ==========================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/qa/wazuh-qa/tests, configfile: pytest.ini
plugins: html-3.1.1, testinfra-5.0.0, metadata-2.0.4
collected 2 items                                                                                      

system/test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py ..                   [100%]

==================================== 2 passed in 601.24s (0:10:01) =====================================

```

**Comment by juliamagan** [comment]
## Update 25/01/2023

Gathered information on what the test does in order to have documentation.

**Comment by juliamagan** [comment]
## Update 27/01/2023

After several executions we have been able to verify that this test is stable, so we will close this issue. However, we can improve this module by deleting one test, since both tests do the same, but the first one with 3 agents, and the second one with 2. This will be performed in #3861.
