### ISSUE TITLE
Unexpected time_travel parameter in FIM IT `test_nodiff`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3806]
### Nightly details

| Day | Branch |  Commit | Report |
| ---- | ---- | ---- |---- |
| 23/01/2023| `master`| 3123b4d | [manager_fim_report.zip](https://github.com/wazuh/wazuh-qa/files/10488532/manager_html_report_Test_integration_B35881_20230124011543.zip)| 

### Description

FIM Integration test `test_nodiff` fails nightly. 
Development https://github.com/wazuh/wazuh-qa/pull/3627 change the `regular_file_cud` fim function, removing the time_travel attribute parameter. This framework change was not updated for the `test_nodiff.py`:

https://github.com/wazuh/wazuh-qa/blob/03c7e003f0bd0d8ac707c01f8e22bd5eddb93fc0/tests/integration/test_fim/test_files/test_env_variables/test_nodiff.py#L205

> **Note**
> This error affects to Linux's hosts for both manager and agents

**Comment by Deblintrake09** [comment]
This has been solved in `4.5` latest changes. When changes are brought to `master` it will be fixed.
