### ISSUE TITLE
Missing resources when retrieving the ruleset active configuration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3812]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5.0|https://github.com/wazuh/wazuh/issues/15996|https://github.com/wazuh/wazuh/pull/16000|

## Description

This PR aims to fix a bug in Analysisd that made it report an incomplete set of rules and decoders.

## Proposed checks

- [x] Check that missing rules (https://github.com/wazuh/wazuh/issues/15725) are now reported by the API.
- [x] Check that missing decoders (https://github.com/wazuh/wazuh/issues/15716) are now reported by the API.
- [x] Check that all rules in XML files are reported by the API (check the functional test at https://github.com/wazuh/wazuh/pull/16000)

## Steps to reproduce

Run the API endpoints `/manager/configuration/analysis/decoders` and `/manager/configuration/analysis/rules`, and check the result.

## Expected results

The API is expected to report all rules and decoders defined in the XML files. However, child decoders are renamed by their parents' names.

***

### Status

- [x] In progress (@juliamagan)
- [x] Pending Review
- [x] QA manager approved (@jmv74211)
- [x] Development team leader approved (@vikman90)

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/16000/commits/1ddf2fff1b8ddd86b26102ada98db27a929b587f |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  CentOS  | 8 | Vagrant | qactl/centos_8 |


### Tested packages

Manager was built from sources since Jenkins is down

**Comment by juliamagan** [comment]
## Testing results

### Reproduce the error in 4.3.10

<details>
<summary><b>Case 1:</b> Check missing rules</summary>
<br>

Check [obtained_rules.txt](https://github.com/wazuh/wazuh/files/10966798/obtained_rules.txt)


- [x] If a rule has children rules, one child won't appear.
- [x] If a rule has one child, the children list, will be empty.
- [x] Missing rules files.


</details>


<details>
<summary><b>Case 2:</b> Check missing decoders</summary>
<br>

Check [obtained_decoders.txt](https://github.com/wazuh/wazuh/files/10966801/obtained_decoders.txt)


- [x] If a decoder has children decoders, the last child won't appear.
- [x] If a decoder has one child, the children list, will be empty.
- [x] The name of the children decoders is the same as the parent's.

</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API</summary>
<br>

1. Run:

```bash
curl -w\\n -sk -H "Authorization: Bearer $(curl -u wazuh:wazuh -sk -X GET "https://localhost:55000/security/user/authenticate?raw=true")" -XGET "https://localhost:55000/manager/configuration/analysis/rules" | python3 -m json.tool | grep -Eo '\"sigid\": [0-9]+' | cut -d' ' -f2 | sort | uniq > rules.txt

grep "<rule" /var/ossec/ruleset/rules/*.xml | grep -Eo 'id="[0-9]+"' | cut -d\" -f2 | while read i
do
    grep ^$i$ rules.txt > /dev/null || echo WARNING: Missing rule $i
done
```

2. Result:

    [warnings.txt](https://github.com/wazuh/wazuh/files/10966807/warnings.txt)



</details>

### Fresh install

<details>
<summary><b>Case 1:</b> Check missing rules </summary>
<br>

- If a rule has children rules, every child rule appears. 
- If a rule has one child, the child appears. 
- No missing rules files. 


</details>


<details>
<summary><b>Case 2:</b> Check missing decoders </summary>
<br>

- If a decoder has children decoders, the last child won't appear. 
- If a decoder has one child, the children list, will be empty.
- The name of the children decoders is the same as the parent's. 

</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API </summary>
<br>


1. Run:

```bash
curl -w\\n -sk -H "Authorization: Bearer $(curl -u wazuh:wazuh -sk -X GET "https://localhost:55000/security/user/authenticate?raw=true")" -XGET "https://localhost:55000/manager/configuration/analysis/rules" | python3 -m json.tool | grep -Eo '\"sigid\": [0-9]+' | cut -d' ' -f2 | sort | uniq > rules.txt

grep "<rule" /var/ossec/ruleset/rules/*.xml | grep -Eo 'id="[0-9]+"' | cut -d\" -f2 | while read i
do
    grep ^$i$ rules.txt > /dev/null || echo WARNING: Missing rule $i
done
```

2. Result:

  ```
  ```


</details>



### Upgrade from 4.3.10 to 4.5.0

<details>
<summary><b>Case 1:</b> Check missing rules :green_circle:</summary>
<br>

- If a rule has children rules, every child rule appears. :green_circle:
- If a rule has one child, the child appears. :green_circle:
- No missing rules files. :green_circle::
	- `0215-policy_rules.xml`: Excluded in ossec.conf


</details>


<details>
<summary><b>Case 2:</b> Check missing decoders :green_circle:</summary>
<br>

- If a decoder has children decoders, the last child won't appear. :green_circle:
- If a decoder has one child, the children list, will be empty. :green_circle:
- The name of the children decoders is the same as the parent's. :green_circle:

</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API :green_circle:</summary>
<br>


1. Run:

```bash
curl -w\\n -sk -H "Authorization: Bearer $(curl -u wazuh:wazuh -sk -X GET "https://localhost:55000/security/user/authenticate?raw=true")" -XGET "https://localhost:55000/manager/configuration/analysis/rules" | python3 -m json.tool | grep -Eo '\"sigid\": [0-9]+' | cut -d' ' -f2 | sort | uniq > rules.txt

grep "<rule" /var/ossec/ruleset/rules/*.xml | grep -Eo 'id="[0-9]+"' | cut -d\" -f2 | while read i
do
    grep ^$i$ rules.txt > /dev/null || echo WARNING: Missing rule $i
done
```

2. Result:

  ```
  WARNING: Missing rule 7425      // Commented in the XML code
  WARNING: Missing rule 17101     // File excluded in ossec.conf
  WARNING: Missing rule 17102     // File excluded in ossec.conf
  WARNING: Missing rule 91513     // Commented in the XML code
  WARNING: Missing rule 91514     // Commented in the XML code
  ```


</details>
