### ISSUE TITLE
Red Hat Enterprise Linux 9 SCA policy rework - checks 4 to 4.1.4.10

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3820]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.x               |         #3391               |        https://github.com/wazuh/wazuh/pull/16016           |

|Check Id and Name| Status| Ready for QA|
|---|---|---|
||||
|4 Logging and Auditing|||
|4.1 Configure System Accounting (auditd)|🟢|🟢|
|4.1.1 Ensure auditing is enabled|||
|4.1.1.1 Ensure auditd is installed (Automated)|🟢|🟢|
|4.1.1.2 Ensure auditing for processes that start prior to auditd is enabled (Automated)|🟢|🟢|
|4.1.1.3 Ensure audit_backlog_limit is sufficient (Automated)|⚫||
|4.1.1.4 Ensure auditd service is enabled (Automated)|🟢|🟢|
||||
|4.1.2 Configure Data Retention|||
|4.1.2.1 Ensure audit log storage size is configured (Automated)|🟢|🟢|
|4.1.2.2 Ensure audit logs are not automatically deleted (Automated)|🟢|🟢|
|4.1.2.3 Ensure system is disabled when audit logs are full (Automated)|🟢|🟢|
||||
|4.1.3 Configure auditd rules|||
|4.1.3.1 Ensure changes to system administration scope (sudoers) is collected (Automated)|🟢|🟢|
|4.1.3.2 Ensure actions as another user are always logged (Automated)|⚫||
|4.1.3.3 Ensure events that modify the sudo log file are collected (Automated)|⚫||
|4.1.3.4 Ensure events that modify date and time information are collected (Automated)|⚫||
|4.1.3.5 Ensure events that modify the system's network environment are collected (Automated)|⚫||
|4.1.3.6 Ensure use of privileged commands are collected (Automated)|⚫||
|4.1.3.7 Ensure unsuccessful file access attempts are collected (Automated)|⚫||
|4.1.3.8 Ensure events that modify user/group information are collected (Automated)|⚫||
|4.1.3.9 Ensure discretionary access control permission modification events are collected (Automated)|⚫||
|4.1.3.10 Ensure successful file system mounts are collected (Automated)|⚫|||
|4.1.3.11 Ensure session initiation information is collected (Automated)|⚫||
|4.1.3.12 Ensure login and logout events are collected (Automated)|⚫||
|4.1.3.13 Ensure file deletion events by users are collected (Automated)|⚫||
|4.1.3.14 Ensure events that modify the system's Mandatory Access Controls are collected (Automated)|⚫||
|4.1.3.15 Ensure successful and unsuccessful attempts to use the chcon command are recorded (Automated)|⚫|||
|4.1.3.16 Ensure successful and unsuccessful attempts to use the setfacl command are recorded (Automated)|⚫||
|4.1.3.17 Ensure successful and unsuccessful attempts to use the chacl command are recorded (Automated)|⚫||
|4.1.3.18 Ensure successful and unsuccessful attempts to use the usermod command are recorded(Automated)|⚫||
|4.1.3.19 Ensure kernel module loading unloading and modification is collected (Automated)|⚫||
|4.1.3.20 Ensure the audit configuration is immutable (Automated)|🟢|🟢|
|4.1.3.21 Ensure the running and on disk configuration is the same (Manual)|⚫||
||||
|4.1.4 Configure auditd file access|||
|4.1.4.1 Ensure audit log files are mode 0640 or less permissive (Automated)|⚫||
|4.1.4.2 Ensure only authorized users own audit log files (Automated)|⚫||
|4.1.4.3 Ensure only authorized groups are assigned ownership of audit log files (Automated)|⚫||
|4.1.4.4 Ensure the audit log directory is 0750 or more restrictive (Automated)|⚫||
|4.1.4.5 Ensure audit configuration files are 640 or more restrictive (Automated)⚫||
|4.1.4.6 Ensure audit configuration files are owned by root (Automated)|⚫||
|4.1.4.7 Ensure audit configuration files belong to group root (Automated)|⚫||
|4.1.4.8 Ensure audit tools are 755 or more restrictive (Automated)|⚫||
|4.1.4.9 Ensure audit tools are owned by root (Automated)|⚫||
|4.1.4.10 Ensure audit tools belong to group root (Automated)|⚫||

**Comment by Rebits** [comment]
### Update 07/03/2023
- Work in automation script

**Comment by Rebits** [comment]
### Testing results :large_blue_circle: 

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16016/commits/b47b1486106d7008576e855c4b150d4783ef16b8 | 

***

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3820#issuecomment-1460482927

4.1.1.3 🔴 - Check has been implemented

4.1.3.1 🔴
    - Remediation Solved
    - Compliance - Solved
    - Rule - Solved

4.1.3.20 🔴
    - Description - Solved
    - Remediation - Solved

4.1.3.21 🟡 - Check has been implemented

4.1.4.8 🟡 - We cannot implement this check because sometimes the command can fail. Some files here may not exist causing grep to fail

```
[root@localhost rhel]# stat -c "%n %a" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules | grep -Pv -- '^\h*\H+\h+([0-7][0,1,4,5][0,1,4,5])\h*$'
[root@localhost rhel]# echo $?
1

```

4.1.4.9 🟡 - We cannot implement this check because sometimes the command can fail. Some files here may not exist causing grep to fail

```
[root@localhost rhel]# stat -c "%n %a" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules | grep -Pv -- '^\h*\H+\h+([0-7][0,1,4,5][0,1,4,5])\h*$'
[root@localhost rhel]# echo $?
1

```

4.1.4.10 🟡 - We cannot implement this check because sometimes the command can fail. Some files here may not exist causing grep to fail

```
[root@localhost rhel]# stat -c "%n %a" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules | grep -Pv -- '^\h*\H+\h+([0-7][0,1,4,5][0,1,4,5])\h*$'
[root@localhost rhel]# echo $?
1

```

https://github.com/wazuh/wazuh/commit/86fc6094f60ecbc45fae42b789507e8ad4b04538

**Comment by Rebits** [comment]
### Testing results - Second review



| Tester | PR commit |
| -- | --|
 |@Rebits | [wazuh/wazuh@b47b148](https://github.com/wazuh/wazuh/commit/86fc6094f60ecbc45fae42b789507e8ad4b04538) |

 	

***


<details>

<summary> 4.1.1.3 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
args="ro biosdevname=0 no_timer_check vga=792 nomodeset text crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap net.ifnames=0 audit=1 audit_backlog_limit=8191"

```

</details>


<details>

<summary> Alert </summary>

```
{"timestamp":"2023-03-13T11:45:31.497+0000","rule":{"level":7,"description":"CIS Benchmark for Red Hat Enterprise Linux 9.: Ensure audit_backlog_limit is sufficient.","id":"19007","firedtimes":38,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["4.1.1.3"],"cis_csc_v8":["8.2"],"cis_csc_v7":["6.2"],"nist_sp_800-53":["AU-2","AU-12","SI-5"],"iso_27001-2013":["A.12.4.1"],"hipaa":["164.312(b)"],"mitre_techniques":["T1562","T1562.001"],"mitre_tactics":["TA0005"]},"agent":{"id":"000","name":"rhel9"},"manager":{"name":"rhel9"},"id":"1678707931.286693","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1838090301","policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","check":{"id":"280800","title":"Ensure audit_backlog_limit is sufficient.","description":"The backlog limit has a default setting of 64.","rationale":"During boot if audit=1, then the backlog will hold 64 records. If more that 64 records are created during boot, auditd records will be lost and potential malicious activity could go undetected.","remediation":"Run the following command to add audit_backlog_limit=<BACKLOG SIZE> to GRUB_CMDLINE_LINUX: # grubby --update-kernel ALL --args 'audit_backlog_limit=<BACKLOG SIZE>' Example: # grubby --update-kernel ALL --args 'audit_backlog_limit=8192'.","compliance":{"cis":"4.1.1.3","cis_csc_v8":"8.2","cis_csc_v7":"6.2","nist_sp_800-53":"AU-2,AU-12,SI-5","iso_27001-2013":"A.12.4.1","cmmc_v2":{"0":"AU.L2-3.3.1"},"hipaa":"164.312(b)","pci_dss_3":{"2":{"1":"10.2,10.3"}},"pci_dss_4":{"0":"5.3.4,6.4.1,6.4.2,10.2.1,10.2.1.1,10.2.1.2,10.2.1.3,10.2.1.4,10.2.1.5,10.2.1.6,10.2.1.7,10.2.2"},"mitre_techniques":"T1562,T1562.001","mitre_tactics":"TA0005"},"command":["grubby --info=ALL"],"result":"failed"}}},"location":"sca"}
```

</details>

</blockquote>

</details>

</details>



<details>

<summary> 4.1.3.1 :green_circle: </summary>

- **Remediation**: :green_circle:
- **Compliance**: :green_circle:
- **Rules**: :green_circle:

Now, invalid configuration is correctly detected
```
{"timestamp":"2023-03-13T11:57:21.212+0000","rule":{"level":7,"description":"CIS Benchmark for Red Hat Enterprise Linux 9.: Ensure changes to system administration scope (sudoers) is collected.","id":"19007","firedtimes":75,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["4.1.3.1"],"cis_csc_v8":["8.5"],"cis_csc_v7":["4.8"],"nist_sp_800-53":["AU-3(1)","AU-7"],"iso_27001-2013":["A.12.4.3"],"soc_2":["CC5.2","CC7.2"],"mitre_techniques":["T1562","T1562.006"],"mitre_tactics":["TA0004"],"mitre_mitigations":["M1047"]},"agent":{"id":"000","name":"rhel9"},"manager":{"name":"rhel9"},"id":"1678708641.1171326","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1717798931","policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","check":{"id":"28085","title":"Ensure changes to system administration scope (sudoers) is collected.","description":"Monitor scope changes for system administrators. If the system has been properly configured to force system administrators to log in as themselves first and then use the sudo command to execute privileged commands, it is possible to monitor changes in scope. The file /etc/sudoers, or files in /etc/sudoers.d, will be written to when the file(s) or related attributes have changed. The audit records will be tagged with the identifier \"scope\".","rationale":"Changes in the /etc/sudoers and /etc/sudoers.d files can indicate that an unauthorized change has been made to the scope of system administrator activity.","remediation":"Edit or create a file in the /etc/audit/rules.d/ directory, ending in .rules extension, with the relevant rules to monitor scope changes for system administrators. Example: # printf \" -w /etc/sudoers -p wa -k scope -w /etc/sudoers.d -p wa -k scope \" >> /etc/audit/rules.d/50-scope.rules Merge and load the rules into active configuration: # augenrules --load Check if reboot is required. # if [[ $(auditctl -s | grep \"enabled\") =~ \"2\" ]]; then printf \"Reboot required to load rules\\n\"; fi.","compliance":{"cis":"4.1.3.1","cis_csc_v8":"8.5","cis_csc_v7":"4.8","nist_sp_800-53":"AU-3(1),AU-7","iso_27001-2013":"A.12.4.3","cmmc_v2":{"0":"AU.L2-3.3.1"},"pci_dss_3":{"2":{"1":"10.1,10.2.2,10.2.4,10.2.5,10.3"}},"pci_dss_4":{"0":"9.4.5,10.2,10.2.1,10.2.1.2,10.2.1.5"},"soc_2":"CC5.2,CC7.2","mitre_techniques":"T1562,T1562.006","mitre_tactics":"TA0004","mitre_mitigations":"M1047"},"directory":["/etc/audit/rules.d/"],"result":"failed"}}},"location":"sca"}
```


</details>



<details>

<summary> 4.1.3.20 :green_circle: </summary>

- **Description**: :green_circle:
- **Remediation**: :green_circle:

</details>


<details>

<summary> 4.1.3.21 :yellow_circle: </summary>

**ID**: Duplicated ID. This will be checked in the global policy review. Replaced by 280866 to proceed with the testing

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :black_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
[root@rhel9 vagrant]# augenrules --check
/sbin/augenrules: No change
```

</details>


<details>

<summary> Alert </summary>

```
{"timestamp":"2023-03-13T12:06:14.225+0000","rule":{"level":9,"description":"CIS Benchmark for Red Hat Enterprise Linux 9.: Ensure the running and on disk configuration is the same.: Status changed from passed to failed","id":"19011","firedtimes":1,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["4.1.3.21"],"cis_csc_v8":["8.5"],"cis_csc_v7":["6.3"],"nist_sp_800-53":["AU-3(1)","AU-7"],"iso_27001-2013":["A.12.4.1"],"soc_2":["CC5.2","CC7.2"]},"agent":{"id":"000","name":"rhel9"},"manager":{"name":"rhel9"},"id":"1678709174.1187122","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"537059484","policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","check":{"id":"280866","title":"Ensure the running and on disk configuration is the same.","description":"The Audit system have both on disk and running configuration. It is possible for these configuration settings to differ. Note: Due to the limitations of augenrules and auditctl, it is not absolutely guaranteed that loading the rule sets via augenrules --load will result in all rules being loaded or even that the user will be informed if there was a problem loading the rules.","rationale":"Configuration differences between what is currently running and what is on disk could cause unexpected problems or may give a false impression of compliance requirements.","remediation":"If the rules are not aligned across all three () areas, run the following command to merge and load all rules: # augenrules --load Check if reboot is required. if [[ $(auditctl -s | grep \"enabled\") =~ \"2\" ]]; then echo \"Reboot required to load rules\"; fi.","compliance":{"cis":"4.1.3.21","cis_csc_v8":"8.5","cis_csc_v7":"6.3","nist_sp_800-53":"AU-3(1),AU-7","iso_27001-2013":"A.12.4.1","cmmc_v2":{"0":"AU.L2-3.3.1"},"pci_dss_3":{"2":{"1":"10.1,10.2.2,10.2.4,10.2.5,10.3"}},"pci_dss_4":{"0":"9.4.5,10.2,10.2.1,10.2.1.2,10.2.1.5"},"soc_2":"CC5.2,CC7.2"},"command":["augenrules --check"],"result":"failed","previous_result":"passed"}}},"location":"sca"}

```

</details>

</blockquote>

</details>

</details>



<details>

<summary> 4.1.4.8 :red_circle: </summary>

What about this rule using condition none?
```
      - 'c:stat -c "%n %a" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules -> r:\w+ && !r:000|010|040|050|001|011|041|051|004|014|044|054|005|015|045|055|700|710|740|750|701|711|741|751|704|714|744|754|705|715|745|755'
```

</details>


<details>

<summary> 4.1.4.9 :red_circle: </summary>

Same as 4.1.4.8

</details>


<details>

<summary> 4.1.4.10 :red_circle: </summary>

Same as 4.1.4.8

</details>

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3820#issuecomment-1466344320

4.1.4.8 🔴 - Check has been implemented
4.1.4.9 🔴 - Check has been implemented
4.1.4.10 🔴 - Check has been implemented

https://github.com/wazuh/wazuh/commit/4f83a78c3bddb6f01b1e8f1c7f0e44446bd5f63b

**Comment by Rebits** [comment]
### Testing results


| Tester | PR commit |
| -- | --|
 |@Rebits | [wazuh/wazuh@b47b148](https://github.com/wazuh/wazuh/commit/4f83a78c3bddb6f01b1e8f1c7f0e44446bd5f63b) |

***

<details>

<summary>4.1.4.8 :red_circle: </summary>

**Rules**:  :red_circle:

The permissions that audit gives for invalid cases are those that correspond to those that do not patch this regex: `[0-7][0,1,4,5][0,1,4,5]`

Current regex only mark check as failed in case of the following permissions: `766|776|767|777`

Missing permissions: 775, 760,770,774, etc 

</details>


<details>

<summary>4.1.4.9 :red_circle: </summary>

**Rules**:  :red_circle:

The permissions that audit gives for invalid cases are those that correspond to those that do not patch this regex: `[0-7][0,1,4,5][0,1,4,5]`

Current regex only mark check as failed in case of the following permissions: `766|776|767|777`

Missing permissions: 775, 760,770,774, etc 



Also, second command is invalid. Expected:
```
- 'not c:sh -c "stat -c \"%n %U\" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules" -> r:^/sbin && !r:root'
```

</details>


<details>

<summary>4.1.4.10 :red_circle: </summary>


**Rules**:  :red_circle:

The permissions that audit gives for invalid cases are those that correspond to those that do not patch this regex: `[0-7][0,1,4,5][0,1,4,5]`

Current regex only mark check as failed in case of the following permissions: `766|776|767|777`

Missing permissions: 775, 760,770,774, etc 

</details>

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3820#issuecomment-1473732502

4.1.4.8 🔴 - Won't Change
4.1.4.9 🔴 - Won't Change
4.1.4.10 🔴 - Won't Change

**Comment by Rebits** [comment]
### Testing results



| Tester | PR commit |
| -- | --|
 |@Rebits | https://github.com/wazuh/wazuh/commit/ae894aeccebcba2d7c4bc606fa1f04784348ae88 |

 	

***






<details>

<summary> 4.1.4.8 :green_circle: </summary>

**Rules**: :green_circle:


```
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280000
2023/03/22 12:31:51 sca[14463] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280000 'Ensure audit tools are 755 or more restrictive.'
2023/03/22 12:31:51 sca[14463] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280000 'Ensure audit tools are 755 or more restrictive.' -> 0
2023/03/22 12:31:52 sca[14463] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280000; Result: 'failed'
^C
[root@rhel9 vagrant]# chmod ^C
[root@rhel9 vagrant]# chmod 700 /sbin/auditd
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280000
2023/03/22 12:32:12 sca[14921] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280000 'Ensure audit tools are 755 or more restrictive.'
2023/03/22 12:32:12 sca[14921] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280000 'Ensure audit tools are 755 or more restrictive.' -> 1
2023/03/22 12:32:13 sca[14921] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280000; Result: 'passed'
```

</details>




<details>

<summary> 4.1.4.9 :green_circle: </summary>

**Rules**: :green_circle:

```
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280001
2023/03/22 12:22:29 sca[13516] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280001 'Ensure audit tools are owned by root.'
2023/03/22 12:22:29 sca[13516] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280001 'Ensure audit tools are owned by root.' -> 1
2023/03/22 12:22:30 sca[13516] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280001; Result: 'passed'
----
chmod 775 /sbin/auditd
----
[root@rhel9 vagrant]# chmod 775 /sbin/auditd
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280001
2023/03/22 12:22:56 sca[13980] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280001 'Ensure audit tools are owned by root.'
2023/03/22 12:22:56 sca[13980] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280001 'Ensure audit tools are owned by root.' -> 0
2023/03/22 12:22:57 sca[13980] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280001; Result: 'failed'
```


</details>







<details>

<summary> 4.1.4.10 :green_circle: </summary>


**Rules**: :green_circle:

```
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280002
2023/03/22 12:36:11 sca[15858] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280002 'Ensure audit tools belong to group root.'
2023/03/22 12:36:11 sca[15858] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280002 'Ensure audit tools belong to group root.' -> 1
2023/03/22 12:36:12 sca[15858] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280002; Result: 'passed'
^C
[root@rhel9 vagrant]# chown vagrant:root /sbin/auditd
[root@rhel9 vagrant]# pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\[' | grep 280002
2023/03/22 12:36:37 sca[16322] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 280002 'Ensure audit tools belong to group root.'
2023/03/22 12:36:37 sca[16322] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 280002 'Ensure audit tools belong to group root.' -> 0
2023/03/22 12:36:38 sca[16322] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 280002; Result: 'failed'
```


</details>

**Comment by Rebits** [comment]
### Conclusion :green_circle:

After applying the requested changes, this range of policies correctly complies with the CIS benchmark.
