### ISSUE TITLE
Red Hat Enterprise Linux 9 SCA policy rework - checks 4.2 to 4.3

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3821]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.x               |         #3391               |        https://github.com/wazuh/wazuh/pull/16016           |

|Check Id and Name| Status| Ready for QA|
|---|---|---|
||||
|4.2 Configure Logging|||
|4.2.1 Configure rsyslog|||
|4.2.1.1 Ensure rsyslog is installed (Automated)|🟢|🟢|
|4.2.1.2 Ensure rsyslog service is enabled (Automated)|🟢|🟢|
|4.2.1.3 Ensure journald is configured to send logs to rsyslog (Manual)|🟢|🟢|
|4.2.1.4 Ensure rsyslog default file permissions are configured (Automated)|🟢|🟢|
|4.2.1.5 Ensure logging is configured (Manual)|⚫||
|4.2.1.6 Ensure rsyslog is configured to send logs to a remote log host (Manual)|🟢|🟢|
|4.2.1.7 Ensure rsyslog is not configured to receive logs from a remote client (Automated)|🟢|🟢|
||||
|4.2.2 Configure journald|||
|4.2.2.1 Ensure journald is configured to send logs to a remote log host|||
|4.2.2.1.1 Ensure systemd-journal-remote is installed (Manual)|🟢|🟢|
|4.2.2.1.2 Ensure systemd-journal-remote is configured (Manual)|⚫||
|4.2.2.1.3 Ensure systemd-journal-remote is enabled (Manual)|🟢|🟢|
|4.2.2.1.4 Ensure journald is not configured to receive logs from a remote client (Automated)|🟢|🟢|
|4.2.2.2 Ensure journald service is enabled (Automated)|🟢|🟢|
|4.2.2.3 Ensure journald is configured to compress large log files (Automated)|🟢|🟢|
|4.2.2.4 Ensure journald is configured to write logfiles to persistent disk (Automated)|🟢|🟢|
|4.2.2.5 Ensure journald is not configured to send logs to rsyslog (Manual)|🟢|🟢|
|4.2.2.6 Ensure journald log rotation is configured per site policy (Manual)|⚫||
|4.2.2.7 Ensure journald default file permissions configured (Manual)|⚫||
|4.2.3 Ensure all logfiles have appropriate permissions and ownership (Automated)|⚫||
|4.3 Ensure logrotate is configured (Manual)|⚫||

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3821#issuecomment-1464047409

4.2.1.3 🔴
- Compliance - Solved
- Rule - Solved

4.2.1.6 🔴
- Description - Solved
- Remediation - . is already in the check

4.2.1.7 🔴
- Remediation - . is already in the check
- Compliance - Solved

4.2.2.1.1 🔴
- Compliance - Solved

4.2.2.1.3 🔴
- Compliance - Solved

4.2.2.1.4 🔴
- Compliance - Solved

4.2.2.3 🔴
- Remediation - Solved

4.2.2.4 🔴
- Remediation - Solved

4.2.2.5 🔴
- Compliance - Solved
    - PCI3 - solved as per compliance dictionary 8.2 and 8.9 v8
    - PCI4 - solved as per compliance dictionary 8.2 and 8.9 v8
    - SOC - solved
    - NIST - solved as per compliance dictionary 8.2 and 8.9 v8

https://github.com/wazuh/wazuh/commit/4f83a78c3bddb6f01b1e8f1c7f0e44446bd5f63b

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3821#issuecomment-1473761808

4.2.2.3 🔴 - Solved
4.2.2.4 🔴 - Solved

**Comment by Rebits** [comment]
### Testing results


| Tester | PR commit |
| -- | --|
 |@Rebits | https://github.com/wazuh/wazuh/commit/ae894aeccebcba2d7c4bc606fa1f04784348ae88 |


***


<details>

<summary> 4.2.2.3 :green_circle: </summary>

**Remediation**: :green_circle: 

</details>


<details>

<summary> 4.2.2.4 :green_circle: </summary>

**Remediation**: :green_circle: 

</details>

**Comment by Rebits** [comment]
## Closing conclusion 👍🏼  

The suggested changes have been applied and everything appears to be correct.
