### ISSUE TITLE
Debian Linux 11 SCA policy - checks 3 to 3.5.3.3.4

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3829]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |         #3825            |        https://github.com/wazuh/wazuh/pull/16017             |

|Check Id and Name| Status| Extra|
|---|---|---|
|3 Network Configuration|||
|3.1 Disable unused network protocols and devices|||
|3.1.1 Ensure system is checked to determine if IPv6 is enabled (Manual)|||
|3.1.2 Ensure wireless interfaces are disabled (Automated)|||
|3.1.3 Ensure DCCP is disabled (Automated)|||
|3.1.4 Ensure SCTP is disabled (Automated)|||
|3.1.5 Ensure RDS is disabled (Automated)|||
|3.1.6 Ensure TIPC is disabled (Automated)|||
||||
|3.2 Network Parameters (Host Only)|||
|3.2.1 Ensure packet redirect sending is disabled (Automated)|||
|3.2.2 Ensure IP forwarding is disabled (Automated)|||
||||
|3.3 Network Parameters (Host and Router)|||
|3.3.1 Ensure source routed packets are not accepted (Automated)|||
|3.3.2 Ensure ICMP redirects are not accepted (Automated)|||
|3.3.3 Ensure secure ICMP redirects are not accepted (Automated)|||
|3.3.4 Ensure suspicious packets are logged (Automated)|||
|3.3.5 Ensure broadcast ICMP requests are ignored (Automated)|||
|3.3.6 Ensure bogus ICMP responses are ignored (Automated)|||
|3.3.7 Ensure Reverse Path Filtering is enabled (Automated)|||
|3.3.8 Ensure TCP SYN Cookies is enabled (Automated)|||
|3.3.9 Ensure IPv6 router advertisements are not accepted (Automated)|||
||||
|3.5 Firewall Configuration|||
|3.5.1 Configure UncomplicatedFirewall|||
|3.5.1.1 Ensure ufw is installed (Automated)|||
|3.5.1.2 Ensure iptables-persistent is not installed with ufw (Automated)|||
|3.5.1.3 Ensure ufw service is enabled (Automated)|||
|3.5.1.4 Ensure ufw loopback traffic is configured (Automated)|||
|3.5.1.5 Ensure ufw outbound connections are configured (Manual)|||
|3.5.1.6 Ensure ufw firewall rules exist for all open ports (Automated)|||
|3.5.1.7 Ensure ufw default deny firewall policy (Automated)|||
||||
|3.5.2 Configure nftables|||
|3.5.2.1 Ensure nftables is installed (Automated)|||
|3.5.2.2 Ensure ufw is uninstalled or disabled with nftables (Automated)|||
|3.5.2.3 Ensure iptables are flushed with nftables (Manual)|||
|3.5.2.4 Ensure a nftables table exists (Automated)|||
|3.5.2.5 Ensure nftables base chains exist (Automated)|||
|3.5.2.6 Ensure nftables loopback traffic is configured (Automated)|||
|3.5.2.7 Ensure nftables outbound and established connections are configured (Manual)|||
|3.5.2.8 Ensure nftables default deny firewall policy (Automated)|||
|3.5.2.9 Ensure nftables service is enabled (Automated)|||
|3.5.2.10 Ensure nftables rules are permanent (Automated)|||
||||
|3.5.3 Configure iptables|||
|3.5.3.1 Configure iptables software|||
|3.5.3.1.1 Ensure iptables packages are installed (Automated)|||
|3.5.3.1.2 Ensure nftables is not installed with iptables (Automated)|||
|3.5.3.1.3 Ensure ufw is uninstalled or disabled with iptables (Automated)|||
||||
|3.5.3.2 Configure IPv4 iptables|||
|3.5.3.2.1 Ensure iptables default deny firewall policy (Automated)|||
|3.5.3.2.2 Ensure iptables loopback traffic is configured (Automated)|||
|3.5.3.2.3 Ensure iptables outbound and established connections are configured (Manual)|||
|3.5.3.2.4 Ensure iptables firewall rules exist for all open ports (Automated)|||
||||
|3.5.3.3 Configure IPv6 ip6tables|||
|3.5.3.3.1 Ensure ip6tables default deny firewall policy (Automated)|||
|3.5.3.3.2 Ensure ip6tables loopback traffic is configured (Automated)|||
|3.5.3.3.3 Ensure ip6tables outbound and established connections are configured (Manual)|||
|3.5.3.3.4 Ensure ip6tables firewall rules exist for all open ports (Automated)|||

@olulekew7

**Comment by Rebits** [comment]
## Tester review


### Testing environment

| OS     | OS version | Deployment | Image/AMI         | Notes |
| ------ | ---------- | ---------- | ----------------- | ----- |
| Debian | 11          | Vagrant    | debian/bullseye64 |       |


### Tested packages

| `wazuh-manager` |
| --------------- |
| [wazuh-managerv-4.4.0-1](https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.4.0-1_amd64.deb)           |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] Development team leader approved (@72nomada)

**Comment by Rebits** [comment]
### Tester review :large_blue_circle: 

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16016/commits/1f08074ed58ecbdbdea6991ed0d23d1ef76cd7f6 | 

***

**Comment by Rebits** [comment]
### Closing conclusions :+1: 

After the requested changes we policy seems to be consistent with the CIS benchmark. In addition, check rules seem to work as expected taking into account the SCA limitations.

**Comment by Rebits** [comment]
### Closing conclusions :+1: 

After the requested changes we policy seems to be consistent with the CIS benchmark. In addition, check rules seem to work as expected taking into account the SCA limitations.
