### ISSUE TITLE
Debian Linux 11 SCA policy - checks 5.3 to 5.5.5

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3833]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |         #3825            |        https://github.com/wazuh/wazuh/pull/16017             |

|Check Id and Name| Status| Extra|
|---|---|---|
|5.3 Configure privilege escalation|||
|5.3.1 Ensure sudo is installed (Automated)|🟢||
|5.3.2 Ensure sudo commands use pty (Automated)|🟢||
|5.3.3 Ensure sudo log file exists (Automated)|🟢||
|5.3.4 Ensure users must provide password for privilege escalation (Automated)|🟢||
|5.3.5 Ensure re-authentication for privilege escalation is not disabled globally (Automated)|🟢||
|5.3.6 Ensure sudo authentication timeout is configured correctly (Automated)|🟢||
|5.3.7 Ensure access to the su command is restricted (Automated)|🟢||
||||
|5.4 Configure PAM|||
|5.4.1 Ensure password creation requirements are configured (Automated)|🟢||
|5.4.2 Ensure lockout for failed password attempts is configured (Automated)|🟢||
|5.4.3 Ensure password reuse is limited (Automated)|🟢||
|5.4.4 Ensure password hashing algorithm is up to date with the latest standards (Automated)|🟢||
|5.4.5 Ensure all current passwords uses the configured hashing algorithm (Manual)|⚫||
||||
|5.5 User Accounts and Environment|🟢||
|5.5.1 Set Shadow Password Suite Parameters|||
|5.5.1.1 Ensure minimum days between password changes is configured (Automated)|🟢||
|5.5.1.2 Ensure password expiration is 365 days or less (Automated)|🟢||
|5.5.1.3 Ensure password expiration warning days is 7 or more (Automated)|🟢||
|5.5.1.4 Ensure inactive password lock is 30 days or less (Automated)|🟢||
|5.5.1.5 Ensure all users last password change date is in the past (Automated)|⚫||
|5.5.2 Ensure system accounts are secured (Automated)|⚫||
|5.5.3 Ensure default group for the root account is GID 0 (Automated)|🟢||
|5.5.4 Ensure default user umask is 027 or more restrictive (Automated)|⚫||
|5.5.5 Ensure default user shell timeout is 900 seconds or less (Automated)|⚫||

**Comment by Rebits** [comment]
## Tester review


### Testing environment

| OS     | OS version | Deployment | Image/AMI         | Notes |
| ------ | ---------- | ---------- | ----------------- | ----- |
| Debian | 11          | Vagrant    | debian/bullseye64 |       |


### Tested packages

| `wazuh-manager` |
| --------------- |
| [wazuh-managerv-4.4.0-1](https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.4.0-1_amd64.deb)           |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] Development team leader approved (@72nomada)

**Comment by Rebits** [comment]
### Conclusion :+1: 

Some minor changes were requested and solved with @72nomada in a meeting. These changes can be found in 
https://github.com/wazuh/wazuh/commit/17b41292866c3ac51ac33f9defb455c253f2cafd and https://github.com/wazuh/wazuh/commit/cb333c3119a4074dd67b41c0744d40f0b25189e2

Now the policy seems to be consistent with the CIS benchmark. In addition, check rules seem to work as expected considering the SCA limitations.
