### ISSUE TITLE
Validate unnecessary sanity check removed on wdb_syscollector_save2 function

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3836]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|    4.6                 |     https://github.com/wazuh/wazuh/issues/10380    |     https://github.com/wazuh/wazuh/pull/16008      |

## Description

This development aims the aim of improve code quality, an unnecessary sanity check was removed.

## Proposed test cases

- Upgrade from prod version to core-branch

    1. Install wazuh agent
    2. Enable the syscollector config
    3. Check wazuh db does not crash in the manager
    4. Check that there are no errors in the ossec.log
    
- Fresh install core-branch

    1. Install wazuh agent
    2. Enable the syscollector config
    3. Check wazuh db does not crash in the manager
    4. Check that there are no errors in the ossec.log

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16008/commits/8d4c1c160c33d60e619bf7654f1deddeb34d8c41| 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| Ubuntu          | local | `ubuntu/bionic64`|  |
|Ubuntu  |  local | `qactl/ubuntu_20_04`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| Ubuntu           |  [deb](https://packages-dev.wazuh.com/warehouse/test/4.6/deb/var/wazuh-manager_4.6.0-3003.wdb_amd64.deb)|  | 
| Ubuntu|   | [deb](https://packages-dev.wazuh.com/warehouse/test/4.6/deb/var/wazuh-agent_4.6.0-3003.wdb_amd64.deb)  |


## Status

- [x] In progress
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito

**Comment by BelenValdivia** [comment]
## Conclusion 🟢 

The behavior is as expected. No errors were found in ossec.log,  wazuh db does not crash in the manager and syscollector tables have information about the agent.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
