### ISSUE TITLE
Amazon Linux 2023 SCA policy - check 1.1.5 to 1.5.3

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3840]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3838      |       https://github.com/wazuh/wazuh/pull/15681             |

|Check Id and Name| Status| Extra|
|---|---|---|
|1.1.5 Configure /var/log||||
|1.1.5.1 Ensure separate partition exists for /var/log (Automated)||||
|1.1.5.2 Ensure nodev option set on /var/log partition (Automated)||||
|1.1.5.3 Ensure noexec option set on /var/log partition (Automated)||||
|1.1.5.4 Ensure nosuid option set on /var/log partition (Automated)||||
|||||
|1.1.6 Configure /var/log/audit||||
|1.1.6.1 Ensure separate partition exists for /var/log/audit (Automated)||||
|1.1.6.2 Ensure noexec option set on /var/log/audit partition (Automated)||||
|1.1.6.3 Ensure nodev option set on /var/log/audit partition (Automated)||||
|1.1.6.4 Ensure nosuid option set on /var/log/audit partition (Automated)||||
|||||
|1.1.7 Configure /home||||
|1.1.7.1 Ensure separate partition exists for /home (Automated)||||
|1.1.7.2 Ensure nodev option set on /home partition (Automated)||||
|1.1.7.3 Ensure nosuid option set on /home partition (Automated)||||
|1.1.7.4 Ensure usrquota option set on /home partition (Automated)||||
|1.1.7.5 Ensure grpquota option set on /home partition (Automated)||||
|||||
|1.1.8 Configure /dev/shm||||
|1.1.8.1 Ensure nodev option set on /dev/shm partition (Automated)||||
|1.1.8.2 Ensure noexec option set on /dev/shm partition (Automated)||||
|1.1.8.3 Ensure nosuid option set on /dev/shm partition (Automated)||||
|||||
|1.1.9 Disable Automounting (Automated)||||
|1.1.10 Disable USB Storage (Automated)||||
|||||
|1.2 Configure Software Updates||||
|1.2.1 Ensure GPG keys are configured (Manual)||||
|1.2.2 Ensure gpgcheck is globally activated (Automated)||||
|1.2.3 Ensure package manager repositories are configured (Manual)||||
|||||
|1.3 Filesystem Integrity Checking||||
|1.3.1 Ensure AIDE is installed (Automated)||||
|1.3.2 Ensure filesystem integrity is regularly checked (Automated)||||
|||||
|1.4 Secure Boot Settings||||
|1.4.1 Ensure bootloader password is set (Automated)||||
|1.4.2 Ensure permissions on bootloader config are configured (Automated)||||
|1.4.3 Ensure authentication is required when booting into rescue mode (Automated)||||
|||||
|1.5 Additional Process Hardening||||
|1.5.1 Ensure core dump storage is disabled (Automated)||||
|1.5.2 Ensure core dump backtraces are disabled (Automated)||||
|1.5.3 Ensure address space layout randomization (ASLR) is enabled (Automated)||||

**Comment by Rebits** [comment]
## Tester review

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Amazon Linux  |    2023     | EC2 |    ami-0889a44b331db0194 |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|  [wazuh-manager-4.4.1-1](https://packages.wazuh.com/4.x/yum/wazuh-manager-4.4.1-1.x86_64.rpm) | 

> **Note**:
> The production manager version will be used, and the new policy will be added manually for testing the subtask. 
> Final testing will be conducted using the development package once the PR is ready to be opened


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@juliamagan)
- [ ] Development team leader approved (@72nomada)

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3840#issuecomment-1538091676

1.1.5.1 🔴 - Solved
1.1.6.1 🔴 - Solved
1.1.6.2 🔴- Solved
1.1.6.4 🔴 - Solved
1.1.7.1 🔴 - Solved
1.1.9 🔵 
1.2.4 🔵 
1.3.2 🔵 
1.3.3 🔵 
1.4.1 🔵 
1.4.2 🔵 
1.5.1 🔴 - Solved
1.5.2 🔴 - Solved
1.5.3 🔴 - Solved 
1.5.4 🔴 - Solved

https://github.com/wazuh/wazuh/pull/16380/commits/3ec603cdae95a1d58b66aa0e5d7519ca37cc68ca

**Comment by Rebits** [comment]
Not planned
