### ISSUE TITLE
Amazon Linux 2023 SCA policy - check 1.6 to 1.10

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3841]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3838      |       https://github.com/wazuh/wazuh/pull/15681             |

|Check Id and Name| Status| Extra|
|---|---|---|
|1.6 Mandatory Access Control||||
|1.6.1 Configure SELinux||||
|1.6.1.1 Ensure SELinux is installed (Automated)||||
|1.6.1.2 Ensure SELinux is not disabled in bootloader configuration (Automated)||||
|1.6.1.3 Ensure SELinux policy is configured (Automated)||||
|1.6.1.4 Ensure the SELinux mode is not disabled (Automated)||||
|1.6.1.5 Ensure the SELinux mode is enforcing (Automated)||||
|1.6.1.6 Ensure no unconfined services exist (Automated)||||
|1.6.1.7 Ensure SETroubleshoot is not installed (Automated)||||
|1.6.1.8 Ensure the MCS Translation Service (mcstrans) is not installed (Automated)||||
|||||
|1.7 Command Line Warning Banners||||
|1.7.1 Ensure message of the day is configured properly (Automated)||||
|1.7.2 Ensure local login warning banner is configured properly (Automated)||||
|1.7.3 Ensure remote login warning banner is configured properly (Automated)||||
|1.7.4 Ensure permissions on /etc/motd are configured (Automated)||||
|1.7.5 Ensure permissions on /etc/issue are configured (Automated)||||
|1.7.6 Ensure permissions on /etc/issue.net are configured (Automated)||||
|||||
|1.8 GNOME Display Manager||||
|1.8.1 Ensure GNOME Display Manager is removed (Manual)||||
|1.8.2 Ensure GDM login banner is configured (Automated)||||
|1.8.3 Ensure user list display is disabled (Automated)||||
|1.8.4 Ensure XDMCP is not enabled (Automated)||||
|1.8.5 Ensure automatic mounting of removable media is disabled (Automated)||||
|1.9 Ensure updates, patches, and additional security software are installed (Manual)||||
|1.10 Ensure system-wide crypto policy is not legacy (Automated)||||

**Comment by Rebits** [comment]
Not planned
