### ISSUE TITLE
Amazon Linux 2022 SCA policy - check 2 to 2.4

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3842]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3838      |       https://github.com/wazuh/wazuh/pull/15681             |

|Check Id and Name| Status| Extra|
|---|---|---|
|2 Services||||
|2.1 Time Synchronization||||
|2.1.1 Ensure time synchronization is in use (Automated)||||
|2.1.2 Ensure chrony is configured (Automated)||||
|||||
|2.2 Special Purpose Services||||
|2.2.1 Ensure xinetd is not installed (Automated)||||
|2.2.2 Ensure xorg-x11-server-common is not installed (Automated)||||
|2.2.3 Ensure Avahi Server is not installed (Automated)||||
|2.2.4 Ensure CUPS is not installed (Automated)||||
|2.2.5 Ensure DHCP Server is not installed (Automated)||||
|2.2.6 Ensure DNS Server is not installed (Automated)||||
|2.2.7 Ensure FTP client is not installed (Automated)||||
|2.2.8 Ensure VSFTP Server is not installed (Automated)||||
|2.2.9 Ensure TFTP Server is not installed (Automated)||||
|2.2.10 Ensure a web server is not installed (Automated)||||
|2.2.11 Ensure IMAP and POP3 server is not installed (Automated)||||
|2.2.12 Ensure Samba is not installed (Automated)||||
|2.2.13 Ensure HTTP Proxy Server is not installed (Automated)||||
|2.2.14 Ensure net-snmp is not installed (Automated)||||
|2.2.15 Ensure NIS server is not installed (Automated)||||
|2.2.16 Ensure telnet-server is not installed (Automated)||||
|2.2.17 Ensure mail transfer agent is configured for local-only mode (Automated)||||
|2.2.18 Ensure nfs-utils is not installed or the nfs-server service is masked (Automated)||||
|2.2.19 Ensure rpcbind is not installed or the rpcbind services are masked (Automated)||||
|2.2.20 Ensure rsync-daemon is not installed or the rsyncd service is masked (Automated)||||
|||||
|2.3 Service Clients||||
|2.3.1 Ensure NIS Client is not installed (Automated)||||
|2.3.2 Ensure rsh client is not installed (Automated)||||
|2.3.3 Ensure talk client is not installed (Automated)||||
|2.3.4 Ensure telnet client is not installed (Automated)||||
|2.3.5 Ensure LDAP client is not installed (Automated)||||
|2.3.6 Ensure TFTP client is not installed (Automated)||||
|2.4 Ensure nonessential services are removed or masked (Manual)||||

**Comment by Rebits** [comment]
Not planned
