### ISSUE TITLE
Amazon Linux 2022 SCA policy - check 5.3 to 5.6.5

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3848]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3838      |       https://github.com/wazuh/wazuh/pull/15681             |

|Check Id and Name| Status| Extra|
|---|---|---|
|5.3 Configure privilege escalation||||
|5.3.1 Ensure sudo is installed (Automated)||||
|5.3.2 Ensure sudo commands use pty (Automated)||||
|5.3.3 Ensure sudo log file exists (Automated)||||
|5.3.4 Ensure users must provide password for escalation (Automated)||||
|5.3.5 Ensure re-authentication for privilege escalation is not disabled globally (Automated)||||
|5.3.6 Ensure sudo authentication timeout is configured correctly (Automated)||||
|5.3.7 Ensure access to the su command is restricted (Automated)||||
|||||
|5.4 Configure authselect||||
|5.4.1 Ensure custom authselect profile is used (Manual)||||
|5.4.2 Ensure authselect includes with-faillock (Automated)||||
|||||
|5.5 Configure PAM||||
|5.5.1 Ensure password creation requirements are configured (Automated)||||
|5.5.2 Ensure lockout for failed password attempts is configured (Automated)||||
|5.5.3 Ensure password reuse is limited (Automated)||||
|5.5.4 Ensure password hashing algorithm is SHA-512 (Automated)||||
|||||
|5.6 User Accounts and Environment||||
|5.6.1 Set Shadow Password Suite Parameters||||
|5.6.1.1 Ensure password expiration is 365 days or less (Automated)||||
|5.6.1.2 Ensure minimum days between password changes is 7 or more (Automated)||||
|5.6.1.3 Ensure password expiration warning days is 7 or more (Automated)||||
|5.6.1.4 Ensure inactive password lock is 30 days or less (Automated)||||
|5.6.1.5 Ensure all users last password change date is in the past (Automated)||||
|5.6.2 Ensure system accounts are secured (Automated)||||
|5.6.3 Ensure default user shell timeout is 900 seconds or less (Automated)||||
|5.6.4 Ensure default group for the root account is GID 0 (Automated)||||
|5.6.5 Ensure default user umask is 027 or more restrictive (Automated)||||

**Comment by Rebits** [comment]
Not planned
