### ISSUE TITLE
Amazon Linux 2022 SCA policy - check 6 to 6.2.16

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3849]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3838      |       https://github.com/wazuh/wazuh/pull/15681             |

|Check Id and Name| Status| Extra|
|---|---|---|
|6 System Maintenance||||
|6.1 System File Permissions||||
|6.1.1 Audit system file permissions (Manual)||||
|6.1.2 Ensure sticky bit is set on all world-writable directories (Automated)||||
|6.1.3 Ensure permissions on /etc/passwd are configured (Automated)||||
|6.1.4 Ensure permissions on /etc/shadow are configured (Automated)||||
|6.1.5 Ensure permissions on /etc/group are configured (Automated)||||
|6.1.6 Ensure permissions on /etc/gshadow are configured (Automated)||||
|6.1.7 Ensure permissions on /etc/passwd- are configured (Automated)||||
|6.1.8 Ensure permissions on /etc/shadow- are configured (Automated)||||
|6.1.9 Ensure permissions on /etc/group- are configured (Automated)||||
|6.1.10 Ensure permissions on /etc/gshadow- are configured (Automated)||||
|6.1.11 Ensure no world writable files exist (Automated)||||
|6.1.12 Ensure no unowned files or directories exist (Automated)||||
|6.1.13 Ensure no ungrouped files or directories exist (Automated)||||
|6.1.14 Audit SUID executables (Manual)||||
|6.1.15 Audit SGID executables (Manual)||||
|||||
|6.2 User and Group Settings||||
|6.2.1 Ensure password fields are not empty (Automated)||||
|6.2.2 Ensure all groups in /etc/passwd exist in /etc/group (Automated)||||
|6.2.3 Ensure no duplicate UIDs exist (Automated)||||
|6.2.4 Ensure no duplicate GIDs exist (Automated)||||
|6.2.5 Ensure no duplicate user names exist (Automated)||||
|6.2.6 Ensure no duplicate group names exist (Automated)||||
|6.2.7 Ensure root PATH Integrity (Automated)||||
|6.2.8 Ensure root is the only UID 0 account (Automated)||||
|6.2.9 Ensure all users' home directories exist (Automated)||||
|6.2.10 Ensure users own their home directories (Automated)||||
|6.2.11 Ensure users' home directories permissions are 750 or more restrictive (Automated)||||
|6.2.12 Ensure users' dot files are not group or world writable (Automated)||||
|6.2.13 Ensure users' .netrc Files are not group or world accessible (Automated)||||
|6.2.14 Ensure no users have .forward files (Automated)||||
|6.2.15 Ensure no users have .netrc files (Automated)||||
|6.2.16 Ensure no users have .rhosts files (Automated)||||

**Comment by Rebits** [comment]
Not planned
