### ISSUE TITLE
macOS Ventura SCA policy - check 5.3 to 6.4.1

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3854]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3850      |      https://github.com/wazuh/wazuh/pull/16027|

|Check Id and Name| Status| Extra|
|---|---|---|
|5.3 Encryption|||
|5.3.1 Ensure all user storage APFS volumes are encrypted (Manual)|||
|5.3.2 Ensure all user storage CoreStorage volumes are encrypted (Manual)|||
|5.4 Ensure the Sudo Timeout Period Is Set to Zero (Automated)|||
|5.5 Ensure a Separate Timestamp Is Enabled for Each User/tty Combo (Automated)|||
|5.6 Ensure the "root" Account Is Disabled (Automated)|||
|5.7 Ensure an Administrator Account Cannot Login to Another User's Active and Locked Session (Automated)|||
|5.8 Ensure a Login Window Banner Exists (Automated)|||
|5.9 Ensure Legacy EFI Is Valid and Updating (Automated)|||
|5.10 Ensure the Guest Home Folder Does Not Exist (Automated)|||
||||
|6 Applications|||
|6.1 Finder|||
|6.1.1 Ensure Show All Filename Extensions Setting is Enabled (Automated)|||
||||
|6.2 Mail|||
|6.2.1 Ensure Protect Mail Activity in Mail Is Enabled (Manual)|||
||||
|6.3 Safari|||
|6.3.1 Ensure Automatic Opening of Safe Files in Safari Is Disabled (Automated)|||
|6.3.2 Audit History and Remove History Items (Manual)|||
|6.3.3 Ensure Warn When Visiting A Fraudulent Website in Safari Is Enabled (Automated)|||
|6.3.4 Ensure Prevent Cross-site Tracking in Safari Is Enabled (Automated)|||
|6.3.5 Audit Hide IP Address in Safari Setting (Manual)|||
|6.3.6 Ensure Advertising Privacy Protection in Safari Is Enabled (Automated)|||
|6.3.7 Ensure Show Full Website Address in Safari Is Enabled (Automated)|||
||||
|6.4 Terminal|||
|6.4.1 Ensure Secure Keyboard Entry Terminal.app Is Enabled (Automated)|||

**Comment by Rebits** [comment]
### Testing environment

| OS     | OS version | Deployment | Image/AMI | Notes |
| ------ | ---------- | ---------- | --------- | ----- |
| macOS  | Ventura    | Local      |           |       |
| ubuntu | 20         | Vagrant    | -         |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` |
| --------------- | ------------- |
|  [4.4.1](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.4.1-1_amd64.deb)               |  [4.4.1](https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.1-1.pkg)             |

> **Note** 
> macOS Ventura sca policy will be included manually in the agent. The development package will be used for the final validation


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@juliamagan )
- [ ] Development team leader approved (@72nomada )

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16027/commits/d0692b70b4f8e68b2b07c19de04653716c817e15 | 

***

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh-qa/issues/3854#issuecomment-1508433141

5.3.3 🔴 - Does not exist in the PDF
5.4 🔴 - Resolved
5.5 🔴 - Resolved
5.7 🔴 - Resolved

https://github.com/wazuh/wazuh/commit/fe32c21d2a8194143b502be0eebb6e33c5b0daee

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3854#issuecomment-1508433141

5.3.3 🔴 - Does not exist in the PDF
5.4 🔴 - Resolved
5.5 🔴 - Resolved
5.7 🔴 - Resolved

https://github.com/wazuh/wazuh/pull/16027/commits/6532d0e20535a8894e8962f329a0b12bf3835763

**Comment by Rebits** [comment]
## Testing results :green_circle:

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16027/commits/d0692b70b4f8e68b2b07c19de04653716c817e15 | 

***




<details>

<summary> 5.4 :green_circle: </summary>

- **Compliance**: :green_circle:
- **Rules**: :green_circle:


**Command output**
```
sh-3.2# sudo -V  | grep Auth
Authentication methods: 'pam'
Authentication timestamp timeout: 5,0 minutes

---

sh-3.2# stat /etc/sudoers.d
16777234 3845212 drwxr-xr-x 2 root wheel 0 64 "Dec  2 12:37:28 2022" "Dec  2 12:37:28 2022" "Jan 19 09:11:44 2023" "Dec  2 12:37:28 2022" 4096 0 0 /etc/sudoers.d
```

**Alert**

```
2023/04/19 10:09:58 sca[1297] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31087 'Ensure the Sudo Timeout Period Is Set to Zero.'
2023/04/19 10:09:58 sca[1297] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31087 'Ensure the Sudo Timeout Period Is Set to Zero.' -> 0
```


</details>


<details>

<summary> 5.5 :green_circle: </summary>

- **Compliance**: :green_circle:
- **Rules**: :green_circle:

**Command output**
```
sh-3.2# sudo -V | grep Type
Type of authentication timestamp record: tty
sh-3.2# 
```

**Alert**
```
2023/04/19 10:12:10 sca[1386] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31088 'Ensure a Separate Timestamp Is Enabled for Each User/tty Combo.'
2023/04/19 10:12:10 sca[1386] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31088 'Ensure a Separate Timestamp Is Enabled for Each User/tty Combo.' -> 1
```


</details>



<details>

<summary> 5.7 :green_circle: </summary>

- **CSC**: :green_circle:
- **Rules**: :green_circle:


**Output**

```
sh-3.2# security authorizationdb read system.login.screensaver
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
...
		<string>use-login-window-ui</string>
YES (0)
```

**Alert**

```
2023/04/19 10:15:00 sca[1486] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31090 'Ensure an Administrator Account Cannot Login to Another User's Active and Locked Session.'
2023/04/19 10:15:00 sca[1486] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31090 'Ensure an Administrator Account Cannot Login to Another User's Active and Locked Session.' -> 1
```



</details>


<details>

<summary> 5.8 :green_circle:  </summary>

**Rules**: :green_circle:


**Output**

```
sh-3.2# stat -f %A /Library/Security/PolicyBanner.*
stat: /Library/Security/PolicyBanner.*: stat: No such file or directory
sh-3.2# 

```

**Alert**

```
2023/04/19 10:18:09 sca[1609] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31091 'Ensure a Login Window Banner Exists.'
2023/04/19 10:18:09 sca[1609] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31091 'Ensure a Login Window Banner Exists.' -> 0
```

</details>

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
