### ISSUE TITLE
Add `system` tests to validate the behavior in wazuh-db during agent-groups insertion

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3878]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 |[#15966](https://github.com/wazuh/wazuh/issues/15966)| [#16049](https://github.com/wazuh/wazuh/pull/16049) |

## Description

It is needed to create `system`  tests  (could be included in `tests/system/test_cluster/test_agent_groups/`) in order to have coverage for cases like [Inconsistent behavior in wazuh-db during agent-groups insertion](https://github.com/wazuh/wazuh/issues/15966#top). Also we can have in mind the improvement of the already developed cases adding new checks like validating the `group_hash` after every action.

## Configurations

  | Environment config |                     |
  |--------------------|---------------------|
  | wazuh installation | multi-node cluster  |
  | nodes              | master + 2 workers  |

  > It could also have more than 2 workers, it is only a suggestion based on the environment used for the manual testing
## Proposed test cases

- [ ] `group_hash` is generated correctly when new agents are **connected**. 

  <details><summary>Test cases - Tier 1</summary>

  - <details><summary>Connect 50k agents and restart the `master`</summary>

    1. Configure the test environment.
    2. Connect 50k `wazuh-agents`.
    3. Create 2 groups and assign all agents to both immediately restart the `master`.
    4. Get the `groups_hash` reported from the `master` and the `worker`.
    5. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>

  - <details><summary>Connect 10k agents to each node and restart the `master`</summary>

    1. Configure the test environment.
    2. Connect 10k `wazuh-agents` to each node.
    3. Create 2 groups and assign all agents to both immediately restart the `master`.
    4. Get the `groups_hash` reported from the `master` and the `worker`.
    5. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>

  - <details><summary>Connect 10k agents to each node and restart the `workers`</summary>

    1. Configure the test environment.
    2. Connect 10k `wazuh-agents` to each node.
    3. Create 2 groups and assign all agents to both immediately restart the `workers`.
    4. Get the `groups_hash` reported from the `master` and the `worker`.
    5. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>
    
</details>

- [ ] `group_hash` is generated correctly when agents are **removed**.
  <details><summary>Test cases - Tier 1</summary>

  - <details><summary>Remove 50k agents and restart the <code>master</code></summary>

    1. Configure the test environment.
    2. Connect 50k `wazuh-agents`.
    3. Create 2 groups and assign all agents to both.
    4. Delete all the groups and agents and immediately restart the `master`.
    5. Get the `groups_hash` reported from the `master` and the `worker`.
    6. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>

  - <details><summary>Remove 10k agents from each node and restart the <code>master</code></summary>

    1. Configure the test environment.
    2. Connect 10k `wazuh-agents` to each node.
    3. Create 2 groups and assign all agents to both.
    4. Delete all the groups and agents and immediately restart the `master`.
    5. Get the `groups_hash` reported from the `master` and the `worker`.
    6. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>

  - <details><summary>Remove 10k agents from each node and restart the <code>workers</code></summary>

    1. Configure the test environment.
    2. Connect 10k `wazuh-agents` to each node.
    3. Create 2 groups and assign all agents to both.
    4. Delete all the groups and agents and immediately restart the `workers`.
    5. Get the `groups_hash` reported from the `master` and the `worker`.
    6. Calculate the actual `groups_hash` and check it matches with the reported from the nodes.
    
    </details>

</details>

**Comment by juliamagan** [comment]
## Update 03/03/2023

After some research, we will start with the implementation of a test with a small environment (1 master, 2 workers and 1 agent) and then we will decide if it is necessary to implement a large environment in this test, or if this will be a different test.

The error was detected in the workload tests, which already use a large environment.

**Comment by juliamagan** [comment]
### Update

We need to change the base version to meet the expected dates.

**Comment by juliamagan** [comment]
### Update
Solved conflicts
