### ISSUE TITLE
QA Planning - `agent-groups` redesign

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3881]
## Description

With the changes coming to the agent-groups feature, this issue will allow us to track the status of the development, as well as the QA research on the changes applied, the manual testing performed, and the test cases raised.

|Devel issue|QA issue|
|--|--|
|[Clear the cached group-hash after inserting or deleting an agent from the global database.](https://github.com/wazuh/wazuh/pull/16049)|[QA Planning - Clear the cached group-hash after inserting or deleting an agent from the global database](https://github.com/wazuh/wazuh-qa/issues/3869)|
|[Remove Agent-groups sync task from worker nodes](https://github.com/wazuh/wazuh/issues/16042)|[QA Planning - Remove 'Agent-groups sync' task from cluster ](https://github.com/wazuh/wazuh-qa/issues/3875)|
|[Centralize the guess group functionality in the master node](https://github.com/wazuh/wazuh/issues/16038)|[QA Planning - Centralize the guess group functionality in the master node](https://github.com/wazuh/wazuh-qa/issues/3876)|
|[Research the consequences of removing use of tables groups and belongs on workers nodes ](https://github.com/wazuh/wazuh/issues/16045)|[QA Planning - Removing use of tables groups and belongs on workers nodes](https://github.com/wazuh/wazuh-qa/issues/3872)|
|[Synchronize complete agent-group information](https://github.com/wazuh/wazuh/issues/16076) |[QA Planning - Synchronize complete agent-group information](https://github.com/wazuh/wazuh-qa/issues/3887) |

## Tree

- https://github.com/wazuh/wazuh-qa/issues/3869
  - https://github.com/wazuh/wazuh-qa/issues/3868
    - https://github.com/wazuh/wazuh-qa/issues/3890 
  - https://github.com/wazuh/wazuh-qa/issues/3878 _(not planned for this milestone)_
- https://github.com/wazuh/wazuh-qa/issues/3875
  - https://github.com/wazuh/wazuh-qa/issues/3865
  - https://github.com/wazuh/wazuh-qa/issues/3877
- https://github.com/wazuh/wazuh-qa/issues/3876
  - https://github.com/wazuh/wazuh-qa/issues/3863
  - https://github.com/wazuh/wazuh-qa/issues/3913 _(not planned for this milestone)_
- https://github.com/wazuh/wazuh-qa/issues/3872
  - https://github.com/wazuh/wazuh-qa/issues/3907
  - https://github.com/wazuh/wazuh-qa/issues/3908
  - https://github.com/wazuh/wazuh-qa/issues/3912 _(not planned for this milestone)_
- https://github.com/wazuh/wazuh-qa/issues/3887
  - https://github.com/wazuh/wazuh-qa/issues/3902
  - https://github.com/wazuh/wazuh-qa/issues/3904
- https://github.com/wazuh/wazuh-qa/issues/3921
- https://github.com/wazuh/wazuh-qa/issues/3922

**Comment by jmv74211** [comment]
All planned issues for this RC were completed, so the issue is closed even though there are still issues that are planned to be developed at a later date.
