### ISSUE TITLE
Perform performance tests for the new API webhook (`POST /events`)

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#3886]
Similar to what we did in https://github.com/wazuh/wazuh/issues/15325#issuecomment-1308566338, we need to design and perform performance tests for the new API endpoint `POST /events` in large environments.

To achieve this, we could use the cluster workload benchmark pipeline in addition to the _API extra load settings_ to have a loaded environment in which to perform these tests.

The following metrics must be retrieved and analyzed:

- Average of `POST /events` requests per second.
- Maximum number of `POST /events` requests per second (limit).
- Response times of every request.
- CPU and memory usage.
- Any other metric or data the tester finds useful.

**Comment by nico-stefani** [comment]
# Issue Update

After discussing with the team, we decide that the scope of the issue should be take the tests suite used in https://github.com/wazuh/wazuh/issues/15325#issuecomment-1308566338 and expand the cases.

**Comment by nico-stefani** [comment]
# Issue Update

I design the cases below in order to test the performance of the new endpoint.

| Events per request / Users | 1 sequential[^1] | 50 sequential[^1] | 50 async[^2] |
|--------|--------|--------|--------|
| 1 |  |  |  |
| 10 |  |  |  |
| 30 |  |  |  |
| 50 |  |  |  |
| 100 |  |  |  | 

[^1]: POST /events
[^2]: POST /events and GET /agents (5:1)

**Comment by nico-stefani** [comment]
# Issue Update

After discussing the rate limit in https://github.com/wazuh/wazuh/pull/17023#discussion_r1189534533, I decided to run the tests, defined above, with requests per minute of **30**, **50**, and **100**.

**Comment by nico-stefani** [comment]
# Issue Update

I was reading the locust documentation and building the needed files to perform the tests.

[locustfiles.zip](https://github.com/wazuh/wazuh-qa/files/11502434/locustfiles.zip)

The next steps are:
- [ ] Create an appropriate environment to perform the tests
- [ ] Execute the tests

**Comment by nico-stefani** [comment]
# 1 User Sequential Tests

## 1 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/480b0087-c7cb-4e4f-93de-df70ae238665)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/ac741752-9145-412e-84a1-66f898dbfb7a)

## 10 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/a4c69b33-acae-430e-9d0b-27fbae61def5)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/29a4feb3-da9d-47bd-9699-24a469ce3fbf)

## 30 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/c9f17441-afa9-4a92-93b4-273fda0bd079)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/88013970-48f3-4380-8c77-d508b32cad2a)

## 50 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/39936f4d-8c4f-49b9-a928-9f7a292afc4f)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/42ffcf8f-54f9-404a-8827-7b467e6057bb)

## 100 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/bc0844bd-e6f0-4b01-9181-9b6de9845062)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/e1ed72c1-6e09-4d83-aa86-7ad845163ef2)

[1_user_sequential_reports.zip](https://github.com/wazuh/wazuh-qa/files/11511854/1_user_sequential_reports.zip)

---

After these tests, any events were dropped.

```
root@ip-172-31-28-157:/var/ossec# cat var/run/wazuh-analysisd.state | grep -e events_dropped -e total_events_decoded
total_events_decoded='37315'
events_dropped='0'
```

**Comment by nico-stefani** [comment]
# 50 users sequential tests

## 1 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/182dad5c-46a7-456a-8a97-b8afa2e22674)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/abaa946d-fd9b-4718-80be-22b99ad192ae)

## 10 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/063d990a-6942-444e-be93-c2440b5877a9)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/4fa82027-b489-42e0-ba8d-2f08156b19c4)

## 30 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/9039ae41-345c-4c5c-8d1c-8e2bc18971b9)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/a9482cc0-4428-41d7-bdac-97825045e303)

## 50 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/8c5d54cc-dccb-4e90-b61d-12f3e2c6b0be)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/c11bb08a-a60f-4ceb-a053-d059631a9259)

## 100 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/b6702b7e-c119-45d4-9fd5-33bea6dfbf85)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/77b82643-f92a-4a7a-aa99-d792965c1053)

[50_user_sequential_reports.zip](https://github.com/wazuh/wazuh-qa/files/11519757/50_user_sequential_reports.zip)
---

After these tests, any events were dropped.
```
root@ip-172-31-28-157:/var/ossec# cat var/run/wazuh-analysisd.state | grep -e events_dropped -e total_events_decoded
total_events_decoded='201051'
events_dropped='0'
```

**Comment by nico-stefani** [comment]
# 50 users async tests (/events and /agents 5:1)

## 1 event per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/9c31ac13-ef3a-4738-b87c-59b758793d64)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/a7935175-d377-4ff9-b238-96521e7d688c)

## 10 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/ed74d3ea-9d69-4085-b588-80c91bd1341d)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/6063b64a-872b-4987-9f2c-3a96bca8d4f1)

## 30 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/f7bab63f-fa1f-436d-87a1-2c306d98de27)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/a061b3d7-aa6f-401f-9416-d4de73f957af)

## 50 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/d6a272e9-910c-498a-9619-da62e4dbcbd7)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/25f9dacf-be02-4748-a7ae-8a79190baf8f)

## 100 events per request

![image](https://github.com/wazuh/wazuh-qa/assets/7127104/c5d6904a-429c-4ed1-800d-e39ec4cedfba)
![image](https://github.com/wazuh/wazuh-qa/assets/7127104/99be6546-e3c3-4df7-8dee-33c20d3fdeda)

---

After these tests, any events were dropped.

```
root@ip-172-31-28-157:/var/ossec# cat var/run/wazuh-analysisd.state | grep -e events_dropped -e total_events_decoded
total_events_decoded='184032'
events_dropped='0'
```

**Comment by nico-stefani** [comment]
# Issue update

After performing the tests, the next step is to analyze the obtained results.

**Comment by nico-stefani** [comment]
# Issue Update

Locust tests have been performed. The Wazuh API was hosted in a `t2.xlarge` EC2 instance with 4	VCPU and 16 GB of RAM.

## Considerations

It has been checked that every request to POST /events generates an alert in Wazuh.

## Results

I did this analysis to decide where to put the limit for the size of the bulk of events and the RPS limit for the endpoint.

### 1 Sequential User

| Topic\Events x Req | 1 | 10 | 30 | 50 | 100 |
|--------|--------|--------|--------|--------|--------|
| RPS | 4.7 | 4.5 | 4.2 | 2.9 | 2.8 |
| RPS Decrease % | - |4.25 | 6.66 | 30.95 | 3.44 |
| Response Time 50%ile (ms) | 210 | 220 | 230 | 290 | 290 |
| EPS | 4.7 | 4.5 | 4.2 | 2.9 | 2.8 |

### 50 Sequential Users

| Topic\Events x Req | 1 | 10 | 30 | 50 | 100 |
|--------|--------|--------|--------|--------|--------|
| RPS | 32.2 | 24 | 21.9 | 20.9 | 11.9 |
| RPS Decrease % | - |25.46 | 8.75 | 4.56 | 43.06 |
| Response Time 50%ile (ms) | 740 | 1200 | 1100 | 1500 | 2500 |
| EPS | 32.2 | 240 | 657 | 1045 | 1190 |

### 50 Async Users

| Topic\Events x Req | 1 | 10 | 30 | 50 | 100 |
|--------|--------|--------|--------|--------|--------|
| RPS | 34 | 33.9 | 26.1 | 23.7 | 14.1 |
| RPS Decrease % | - |0.29 | 23 | 9.19 | 40.50 |
| Response Time 50%ile (ms) | 680 | 730 | 990 | 1000 | 1900 |
| EPS | 34 | 339 | 783 | 1185 | 1410 |

Also, any events were dropped with these test scenarios.

**Comment by davidjiglesias** [comment]
The EPS for this table is not properly calculated @nico-stefani @fdalmaup: 

### 1 Sequential User

| Topic\Events x Req | 1 | 10 | 30 | 50 | 100 |
|--------|--------|--------|--------|--------|--------|
| RPS | 4.7 | 4.5 | 4.2 | 2.9 | 2.8 |
| RPS Decrease % | - |4.25 | 6.66 | 30.95 | 3.44 |
| Response Time 50%ile (ms) | 210 | 220 | 230 | 290 | 290 |
| EPS | 4.7 | 4.5 | 4.2 | 2.9 | 2.8 |

**Comment by davidjiglesias** [comment]
After reviewing with @Selutario the results, we decided to go with the following values for the final implementation:

Max requests per minute for POST /events: Min(30, API_RATE_LIMIT). If API_RATE_LIMIT is 0 (disabled), this will be disabled too.
Max number of events per bulk is 100. As the socket size is limited to 64 kb, and the API accepts 10Mb, 100 events of 64 kb would always be accepted.
