### ISSUE TITLE
QA Planning:  OS_Regex / Analysisd segmentation fault hazard

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3898]
## Description

This aims to investigate [OS_Regex / Analysisd segmentation fault hazard](https://github.com/wazuh/wazuh/issues/14420) to define the test cases to be carried out.

# Development stage

- [ ] Research the applied change.
- [ ] Research if we have a test for this case.
- [ ] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
## Update 15/03/2023
- Researched the Issue and associated Issue.
- Currently no development has been done, as this Issue has been put on hold. When it is advanced, this can be continued.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
