### ISSUE TITLE
Test GetSecurityInfo function in FIM code fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3903]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0               |  https://github.com/wazuh/wazuh/issues/11088      | https://github.com/wazuh/wazuh/pull/15986                   |

## Description
This issue aims to verify the windows agent is working properly after the added fix to print GetSecurityInfo error codes. Since the error cannot be reproduced,  testing will be done to verify the agent has not been broken.

## Proposed checks

- [x] Launch IT tests that run on Windows Agent

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/pull/15986/commits/55fbb02538e3206b46ac1789599171538e7f2876 | 

### Testing environment
Testing has been done in the `test_integration` pipeline

### Tested packages
|Component| Version|
|---|---|
| Agent | [Dev Branch](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/windows/wazuh-agent-4.5.0-0.commit55fbb02.msi)

## Conclusion  

### Status

- [x] In progress
- [x] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @chemamartinez

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
