### ISSUE TITLE
Validate the behavior of empty groups

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3904]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.4.0              |          https://github.com/wazuh/wazuh/issues/16076              |         https://github.com/wazuh/wazuh/pull/16088           |

## Description

The master sends to the worker the group information of all agents, regardless of whether or not they are assigned to any group.

## Proposed checks

- [x] **Case 1**
  <details>
  <summary>Override - Disconnected agent</summary>
  <br>
  
  **Given** 1 master node
  **And** 1 worker node
  **And** 1 `Disconnected` agent node
  **When** we `override` groups to set them to `[]`
  **Then** Warning appears in `ossec.log`
  **And** No group is assigned in db of every node
  </details>

- [x] **Case 2**
  <details>
  <summary>Override - Active agent</summary>
  <br>

  **Given** 1 master node
  **And** 1 worker node
  **And** 1 `Active` agent node
  **When** we `override` groups to set them to `[]`
  **Then** Warning appears in `ossec.log`
  **And** `default` group is assigned in db of every node

  </details>

- [x] **Case 3**
  <details>
  <summary>Remove - Active agent</summary>
  <br>
  
  **Given** 1 master node
  **And** 1 worker node
  **And** 1 `Active` agent node
  **When** we `remove` groups to set them to `[]`
  **Then** Warning appears in `ossec.log`
  **And** `default` group is assigned in db of every node
  </details>

- [x] **Case 4**
  <details>
  <summary>Remove - Disconnected agent</summary>
  <br>
  
  **Given** 1 master node
  **And** 1 worker node
  **And** 1 `Disconnected` agent node
  **When** we `remove` groups to set them to `[]`
  **Then** Warning appears in `ossec.log`
  **And** `default` group is assigned in db of every node
  </details>

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan   | https://github.com/wazuh/wazuh/pull/16088/commits/28b4897047260937e024f926a8ea926d7689f529  |

### Testing environment

| OS | OS version | Deployment                                    | Box | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos    |     8     | Vagrant |   qactl/centos_8         |


### Tested packages

| `wazuh-manager` | `wazuh-agent` |
|-----------------|-------------------|
| [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit28b4897.x86_64.rpm)  |  [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit28b4897.x86_64.rpm) |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA manager approved (@jmv74211)
- [ ] Development team leader approved (@TomasTurina)

## Conclusion

**Comment by juliamagan** [comment]
## Task results

### Fresh install

<details>
<summary><b>Case 1</b>: Override - Disconnected agent</summary>
<br>

</details>

<details>
<summary><b>Case 2</b>: Override - Active agent</summary>
<br>

</details>

<details>
<summary><b>Case 3</b>: Remove - Active agent</summary>
<br>

</details>

<details>
<summary><b>Case 4</b>: Remove - Disconnected agent</summary>
<br>

</details>

### Upgrade

<details>
<summary><b>Case 1</b>: Override - Disconnected agent</summary>
<br>

</details>

<details>
<summary><b>Case 2</b>: Override - Active agent</summary>
<br>

</details>

<details>
<summary><b>Case 3</b>: Remove - Active agent</summary>
<br>

</details>

<details>
<summary><b>Case 4</b>: Remove - Disconnected agent</summary>
<br>

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

The obtained results are the expected ones.
