### ISSUE TITLE
Test fix OS version is not properly parsed for Alpine Linux system

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3905]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.4.0               |       https://github.com/wazuh/wazuh/issues/15698      |    https://github.com/wazuh/wazuh/pull/16082            |

## Description

This issue aims to fix the OS version detection of different distributions, this PR fixes the detection on Linux Alpine (Global database).

Linux Alpine distribution information is in files "/etc/os-release" and "/etc/alpine-release"

## Proposed checks

 The following test cases must be executed in different versions of Alpine Linux

  - <details><summary>Fresh install core-branch and check OS is correctly displayed in the UI </summary>

     1.  Install wazuh agent 
     2. Check the OS version in the machine in files "/etc/os-release" and "/etc/alpine-release"       
     3. Check that the OS version is properly shown in the UI.
       
    </details>
    
     
  </details>

**Comment by BelenValdivia** [comment]
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   |   https://github.com/wazuh/wazuh/pull/16082/commits/df6c6bf129e8374c06068909595da5b6836cf239| 



## Testing environment

- CentOS 8
- Alpine 3.8
- Alpine 3.16
- Alpine 3.12

## Packages
- Alpine: [apk](https://packages-dev.wazuh.com/warehouse/test/4.4/apk/var/x86_64/wazuh-agent-4.4.0-r0702.apk)
- CentOS manager: [rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-07.02.0.fixalpineos.x86_64.rpm)

## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @Dwordcito 


## Conclusion

**Comment by BelenValdivia** [comment]
08/02/2023

- Set environment :

1. Alpine 3.8
2. Alpine 3.16
3. Alpine 3.12

- Generated packages

- Test Upgrade Linux

- Tested Fresh install Linux

**Comment by BelenValdivia** [comment]
# Tests results

### Fresh Install

<details><summary>Alpine 3.8</summary>

1.  Install Wazuh agent package with the core branch fix

2. Check OS version

    ```
    alpine38:/home/vagrant# cat /etc/alpine-release
    3.8.5
    ```
    
    ```
    alpine38:/home/vagrant# cat /etc/os-release
    NAME="Alpine Linux"
    ID=alpine
    VERSION_ID=3.8.5
    PRETTY_NAME="Alpine Linux v3.8"
    HOME_URL="http://alpinelinux.org"
    BUG_REPORT_URL="http://bugs.alpinelinux.org"
    
    ```
3. Check table agent in `/var/ossec/queue/db/global.db` 

    ```
    sqlite> SELECT * FROM agent;
    1|alpine-38|10.0.2.15|any|098d34f34a996d5be1011a043558a38082a9b6edf2f389ae9dc57066397fe242|Alpine Linux|3.8.5|3|8|||alpine|Linux |alpine-38 |4.14.167-0-virt |
    #1-Alpine SMP Thu Jan 23 10:58:18 UTC 2020 |x86_64|x86_64|Wazuh v4.4.0|ab73af41699f13fdd81903b5f23d8d00|4a8724b20dee0124ff9656783c490c4e|centos-manager2|node0
    1|1675863488|1675863643|default|37a8eec1|synced|synced|active|0|synced
    ```

4. Check Alpine OS information in the UI

    ![image](https://user-images.githubusercontent.com/26927338/217879627-255ef360-e4bb-44e8-b934-2634e6de1143.png)

    ![alpine 38 agent](https://user-images.githubusercontent.com/26927338/217879765-fc99ea43-4ac8-4739-9454-873eefae09dc.png)


</details>
<details><summary>Alpine </summary>



</details>
<details><summary>Alpine </summary>



</details>
<details><summary>Alpine </summary>



</details>
<details><summary>Alpine </summary>



</details>
<details><summary>Alpine </summary>



</details>
<details><summary>Alpine </summary>



</details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work properly.
