### ISSUE TITLE
Validate the fix in `wazuh_db` for race condition

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3907]
| Target version | Related issue                                         | Related PR                                          |
|----------------|-------------------------------------------------------|-----------------------------------------------------|
|   4.4.0        | [#16045](https://github.com/wazuh/wazuh/issues/16045) | [#16098](https://github.com/wazuh/wazuh/pull/16098) |

## Description

With this changes when a group folder is deleted, all its data is removed from the `global.db` by the module `wazuh_db` instead of depending on `wazuh-framework` to do so.
This issue is the first part of testing for this modification. Once approved, [this PR]((https://github.com/wazuh/wazuh/pull/16098)) could be merged into the `framework` and then run tests on the full solution.

## Proposed checks

- [x] Remove group by deleting its folder
  <details><summary>Test cases - Remove one</summary>

    - <details><summary>Remove a group by deleting its folder on the <code>master</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on the `master` node.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Group not removed if deleting its folder on a <code>worker</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on a `worker` node.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
        ```
        </details>

    - <details><summary>Group not removed if deleting its folder on an <code>agent</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on an `wazuh-agent`.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>
  </details>

  <details><summary>Test cases - Remove all</summary>

    - <details><summary>Remove all groups by deleting their folder on the <code>master</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete all group's _folder_ on the `master` node.
            ```shell
            rm -rf /var/ossec/etc/shared/!(default)
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Groups not removed if deleting their folder on a <code>worker</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete all group's _folder_ on a `worker` node.
            ```shell
            rm -rf /var/ossec/etc/shared/!(default)
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all groups data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Groups not removed if deleting their folder on an <code>agent</code></summary> 

        1.  **Given** a `cluster` with 2 `worker` nodes 
        2.  **And** 50k `wazuh-agents` connected assigned to 4 groups
        3.  **When** delete all group's _folder_ on an `wazuh-agent`.
          ```shell
          rm -rf /var/ossec/etc/shared/!(default)
          ```
        4.  **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
        5.  **Then** all groups data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>
  </details>

### Fix application methods
- [x] Fresh install
- [x] Upgrade

### OS
- [x] Linux

**Comment by QU3B1M** [comment]
### Update 08/02/2023
- Check failing IT on [PR checks](https://github.com/wazuh/wazuh/pull/16119/checks)
- It was found that some failing IT need a fix from core and other IT needs updates
- Fixed locally some of the failing test, some still on research

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [5169f4d](https://github.com/wazuh/wazuh/pull/16098/commits/5169f4d5d4f7056a4e4111aac11972e740eccb31)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb)| |       

### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Testing results :green_circle:

<details><summary>Environment</summary>

```powershell
/var/ossec/bin/cluster_control -l
NAME     TYPE    VERSION  ADDRESS        
master   master  4.4.0    192.168.56.10  
worker2  worker  4.4.0    192.168.56.12  
worker1  worker  4.4.0    192.168.56.11  
```
```powershell
/var/ossec/bin/agent_groups -l 

Groups (5):
  default (0)
  g0 (50000)
  g1 (50000)
  g2 (50000)
  g3 (50000)
Unassigned agents: 0.
```
</details>

## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade `master-node`
  ```console
  dpkg -i wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb 

  (Reading database ... 101086 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commit5169f4d) over (4.3.10-1) ...
  Setting up wazuh-manager (4.4.0-0.commit5169f4d) ...
  ```

- Upgrade `worker-1-node`
  ```console
  dpkg -i wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb 

  (Reading database ... 101086 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commit5169f4d) over (4.3.10-1) ...
  Setting up wazuh-manager (4.4.0-0.commit5169f4d) ...
  ```

- Upgrade `worker-2-node`
  ```console
  dpkg -i wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb 

  (Reading database ... 101086 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commit5169f4d_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commit5169f4d) over (4.3.10-1) ...
  Setting up wazuh-manager (4.4.0-0.commit5169f4d) ...
  ```
</details>


<details><summary>Remove group by deleting its folder :green_circle:</summary>

  - <details><summary>Remove a group by deleting its folder on the <code>master</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete the _folder_ of a group on the `master` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g3
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all group data is **deleted** from every `node`
          > Check this in every node
          ```shell
          ls /var/ossec/etc/shared/

          agent-template.conf  ar.conf  default  g0  g1  g2
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from group where "name" = "g3";
          sqlite>
          sqlite> select * from belongs where "id_group" = "5";
          sqlite>
          sqlite> select * from agent where "group" like "%g3%";
          sqlite>
          ```
      </details>

  - <details><summary>Group not removed if deleting its folder on a <code>worker</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete the _folder_ of a group on a `worker` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g2
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all group data **is on** every `node`
          > Check this in every node and
          ```shell
          ls /var/ossec/etc/shared/
          
          agent-template.conf  ar.conf  default  g0  g1  g2
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group" where "name" = "g2";
          4|g2
          sqlite> select * from "belongs" where "id_group" = "4";
          ...
          50000|4|0
          ...
          sqlite> select * from "agent" where "group" like "%g2%";
          ...
          50000|agent50000||any|486352ec2b264f3a97b177dd8dd8b112b8b14906901f6e9d56d97f7f508a8e01||||||||||||||unknown|0||g0,g1,g2|d93a1538|synced|synced|never_connected|0|not synced
          ...
          sqlite>
          ```
      </details>
</details>

<details><summary>Remove all groups by deleting their folder :green_circle:</summary>

  - <details><summary>All Groups removed by deleting their folder on <code>master</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete all group's _folder_ on the `master` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g*
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
          > Check this in every node and agent
          ```shell
          ls /var/ossec/etc/shared/

          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group";
          sqlite>
          sqlite> select * from "belongs";
          sqlite>
          sqlite> select * from "agent" where "group" like "%g%";
          ```
      </details>

  - <details><summary>Groups not removed if deleting their folder on <code>worker</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete all group's _folder_ on a `worker` node.
          ```shell
          rm -rf /var/ossec/etc/shared/!(default)
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all groups data **is on** every `node` and `wazuh-agent`
          > Check this in every node and agent
          ```shell
          ls /var/ossec/etc/shared/

          agent-template.conf  ar.conf  default  g0  g1  g2  g3
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group" where "name" like "%g%";
          2|g0
          3|g1
          4|g2
          5|g3
          sqlite> select * from "belongs";
          ...
          50000|1|0
          50000|2|1
          50000|3|2
          50000|4|3
          ...
          sqlite> select * from agent where "group" like "%g%";
          50000|agent50000||any|486352ec2b264f3a97b177dd8dd8b112b8b14906901f6e9d56d97f7f508a8e01||||||||||||||unknown|0||g0,g1,g2,g3|d93a1538|synced|synced|never_connected|0|not synced
          ```
      </details>

</details>




## Fresh install

<details><summary>Remove group by deleting its folder :green_circle:</summary>

  - <details><summary>Remove a group by deleting its folder on the <code>master</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete the _folder_ of a group on the `master` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g3
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all group data is **deleted** from every `node`
          > Check this in every node
          ```shell
          ls /var/ossec/etc/shared/

          agent-template.conf  ar.conf  default  g0  g1  g2
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from group where "name" = "g3";
          sqlite>
          sqlite> select * from belongs where "id_group" = "5";
          sqlite>
          sqlite> select * from agent where "group" like "%g3%";
          sqlite>
          ```
      </details>

  - <details><summary>Group not removed if deleting its folder on a <code>worker</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete the _folder_ of a group on a `worker` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g2
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all group data **is on** every `node`
          > Check this in every node and
          ```shell
          ls /var/ossec/etc/shared/
          
          agent-template.conf  ar.conf  default  g0  g1  g2
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group" where "name" = "g2";
          4|g2
          sqlite> select * from "belongs" where "id_group" = "4";
          ...
          50000|4|0
          ...
          sqlite> select * from "agent" where "group" like "%g2%";
          ...
          50000|agent50000||any|486352ec2b264f3a97b177dd8dd8b112b8b14906901f6e9d56d97f7f508a8e01||||||||||||||unknown|0||g0,g1,g2|d93a1538|synced|synced|never_connected|0|not synced
          ...
          sqlite>
          ```
      </details>
</details>

<details><summary>Remove all groups by deleting their folder :green_circle:</summary>

  - <details><summary>All Groups removed by deleting their folder on <code>master</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete all group's _folder_ on the `master` node.
          ```shell
          rm -rf /var/ossec/etc/shared/g*
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
          > Check this in every node and agent
          ```shell
          ls /var/ossec/etc/shared/

          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group";
          sqlite>
          sqlite> select * from "belongs";
          sqlite>
          sqlite> select * from "agent" where "group" like "%g%";
          ```
      </details>

  - <details><summary>Groups not removed if deleting their folder on <code>worker</code> :green_circle:</summary> 

      1. **Given** a `cluster` with 2 `worker` nodes 
      2. **And** 50k `wazuh-agents` connected assigned to 4 groups
      3. **When** delete all group's _folder_ on a `worker` node.
          ```shell
          rm -rf /var/ossec/etc/shared/!(default)
          ```
      4. **And** restart the `cluster` (every node).  
          > Waiting 10 seconds for the next sync also works.
      5. **Then** all groups data **is on** every `node` and `wazuh-agent`
          > Check this in every node and agent
          ```shell
          ls /var/ossec/etc/shared/

          agent-template.conf  ar.conf  default  g0  g1  g2  g3
          ```
          ```sql
          sqlite3 /var/ossec/queue/db/global.db 
          
          sqlite> select * from "group" where "name" like "%g%";
          1|default
          2|g0
          3|g1
          4|g2
          5|g3
          sqlite> select * from "belongs";
          ...
          50000|1|0
          50000|2|1
          50000|3|2
          50000|4|3
          ...
          sqlite> select * from agent where "group" like "%g%";
          50000|agent50000||any|486352ec2b264f3a97b177dd8dd8b112b8b14906901f6e9d56d97f7f508a8e01||||||||||||||unknown|0||g0,g1,g2,g3|d93a1538|synced|synced|never_connected|0|not synced
          ```
      </details>
</details>

**Comment by QU3B1M** [comment]
### Update 09/02/2023

This change also fixes an bug where a **group** that does **not exists** could be assigned to an agent using the `wazuhdb` command: `set-agent-groups`. It was found that our `wazuh_db` **IT** were taking advantage of that behavior when assigning groups to agents, so with this fix applied our tests started to fail. 
Our Integration Tests are being fixed in the issue:
- https://github.com/wazuh/wazuh-qa/issues/3921

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work properly.
