### ISSUE TITLE
Validate updated groups deletion functions 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3908]
| Target version | Related issue                                         | Related PR                                          |
|----------------|-------------------------------------------------------|-----------------------------------------------------|
|   4.4.0        | [#16103](https://github.com/wazuh/wazuh/issues/16103) | *Pending* |

## Description

This issue is a continuation of the manual test #3907. In this case, the entire solution will be tested, including *frameworks* and *core* modifications.

**Before** this modification, when a group was deleted it was the framework that was responsible for unassigning the agents from the group and deleting the group folder.
**Now** is the `wazuh_db` who is in charge of the deletion in cascade of each group relationship in the `global.db`, and then recalculate the `group_hash` of each affected agent and update it on the `agent` table.

## Proposed checks

- [ ] Remove groups
  <details><summary>Test cases - Remove one</summary>

    - <details><summary>Remove a group using the API</summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** remove one group using _API_.
            ```shell
            curl -k -X DELETE "https://localhost:55000/groups?groups_list=<GROUP_NAME>&pretty=true" -H  "Authorization: Bearer $TOKEN"
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Remove a group using the CLI</summary>

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** remove one group using _CLI_.
            ```shell
            /var/ossec/bin/agent_groups -r -g <GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Remove a group by deleting its folder on the <code>master</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on the `master` node.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Group not removed if deleting its folder on a <code>worker</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on a `worker` node.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
        ```
        </details>

    - <details><summary>Group not removed if deleting its folder on an <code>agent</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete the _folder_ of a group on an `wazuh-agent`.
            ```shell
            rm -rf /var/ossec/etc/shared/<GROUP_NAME>
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all group data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>
  </details>

  <details><summary>Test cases - Remove all</summary>

    - <details><summary>Remove all groups using the API</summary> 

        1.  **Given** a `cluster` with 2 `worker` nodes 
        2.  **And** 50k `wazuh-agents` connected assigned to 4 groups
        3.  **When** remove all groups using _API_.
            ```shell
            curl -k -X DELETE "https://localhost:55000/groups?groups_list=all&pretty=true" -H  "Authorization: Bearer $TOKEN"
            ```
        4.  **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5.  **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Remove all groups using the CLI</summary>

        1.  **Given** a `cluster` with 2 `worker` nodes 
        2.  **And** 50k `wazuh-agents` connected assigned to 4 groups
        3.  **When** remove all groups using _CLI_.
            > Run the following command for each group. 
            ```shell
            /var/ossec/bin/agent_groups -r -g <GROUP_NAME>
            ```
        4.  **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Remove all groups by deleting their folder on the <code>master</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete all group's _folder_ on the `master` node.
            ```shell
            rm -rf /var/ossec/etc/shared/!(default)
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all groups data is **deleted** from every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Groups not removed if deleting their folder on a <code>worker</code></summary> 

        1. **Given** a `cluster` with 2 `worker` nodes 
        2. **And** 50k `wazuh-agents` connected assigned to 4 groups
        3. **When** delete all group's _folder_ on a `worker` node.
            ```shell
            rm -rf /var/ossec/etc/shared/!(default)
            ```
        4. **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5. **Then** all groups data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>

    - <details><summary>Groups not removed if deleting their folder on an <code>agent</code></summary> 

        1.  **Given** a `cluster` with 2 `worker` nodes 
        2.  **And** 50k `wazuh-agents` connected assigned to 4 groups
        3.  **When** delete all group's _folder_ on an `wazuh-agent`.
            ```shell
            rm -rf /var/ossec/etc/shared/!(default)
            ```
        4.  **And** restart the `cluster` (every node).  
            > Waiting 10 seconds for the next sync also works.
        5.  **Then** all groups data **is on** every `node` and `wazuh-agent`
            > Check this in every node and agent
            ```shell
            ls /var/ossec/etc/shared/
            ```
            ```sql
            sqlite3 /var/ossec/queue/db/global.db 
            
            select * from group where "name" = "<GROUP_NAME>";
            select * from belongs where "id_group" = "<GROUP_ID>";
            select * from agent where "group" = "<GROUP_NAME>";
            ```
        </details>
  </details>

### Fix application methods
- [ ] Fresh install
- [ ] Upgrade

### OS
- [ ] Linux

**Comment by juliamagan** [comment]
We are closing this issue because it's been tested during the development
