### ISSUE TITLE
Create the first engine's test plan iteration

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3927]
| Target version | Related issue |
|--------------------|--------------------|
|             5.0.0           |            https://github.com/wazuh/wazuh-qa/issues/3945            |  

## Description

This issue aims to create and add the first document iteration of what we are calling the test plan for the current development: the Engine. The file is placed within the Epic issue.

This first iteration will contain all the performed test cases till the configuration module testing, along with the fixed bugs within the list.

**Comment by roronoasins** [comment]
## 2023/02/14

The conclusions for the previous testing were added (need to add the HLP2 cases and the current dev-testing issues when they are finished). Some cases and doc formatting need to be updated.

**Comment by damarisg** [comment]
I suggested some changes to apply and improve the documentation.

However, these changes will be applied in issue https://github.com/wazuh/wazuh-qa/issues/3946 (second iteration).
