### ISSUE TITLE
Windows MSI upgrade does not replace user-modified files

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#3929]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.5              |              https://github.com/wazuh/wazuh/issues/15496          |          https://github.com/wazuh/wazuh/pull/16136          |

## Description

In the related PR, we solved a problem that caused non-configuration user-modified files to not be replaced when upgrading using the MSI package.

## Proposed checks

- [x] Test installation of the new package
- [x] Test upgrade to the new package without modifying any file
- [x] Test upgrade to the new package after modifying a dll
- [x] Test upgrade to the new package after modifying ossec.conf, the changes must remain.
- [x] Test upgrade to the new package after modifying a non-configuration file (for example VERSION), the file must be overwritten.

## Steps to reproduce

- Install a production package
- Check `dbsync.dll` hash

     ```
     certutil.exe -hashfile .\dbsync.dll SHA256
     ```
- Modify DLL library

     ```
     echo 1 >> dbsync.dll
     ```
- Install a 4.4.0 signed package
- Check that `dbsync.dll` hash did not change

## Expected results

All files other than configuration files are overwritten after an upgrade.

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/16455/commits/962ce760e1e3ccff949b50ebac8f1393abf09d67  |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  CentOS  | 8 | Vagrant | qactl/centos_8 |
|  Windows | Server 2019 | Vagrant | qactl/windows_2019 |

### Tested packages

| Version | Manager | Agent |
|:--:|--|--|
|4.4.1| | | 
|4.5.0| | |

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16136/commits/59fbd74a8f799a164417a76c9b912c3683d2fbd8 | 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS  8           | local | `qactl/centos_8`|  |
| Windows Server 2019 |  local | `qactl/windows_2019`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| CentOS  8           | [rpm ](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-2404.winmsi.x86_64.rpm)|  | 
| Windows server 2019|   | [msi ](https://packages-dev.wazuh.com/warehouse/test/4.5/windows/wazuh-agent-4.5.0-2404.winmsi.msi)|


## Status

- [x] In progress
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader

**Comment by BelenValdivia** [comment]
## Testing results

### Reproduce the bug

<details><summary>The upgrade process does not replace the modified library 🔴 </summary>

1. Install a production package 4.3.10

2. Check the `dbsync.dll`  hash

    ```
    PS C:\> cd '.\Program Files (x86)\ossec-agent\'
    PS C:\Program Files (x86)\ossec-agent> certutil.exe -hashfile .\dbsync.dll SHA256
    SHA256 hash of .\dbsync.dll:
    fa1c0f6a3e71c86539796629eaecfc79845bbb984cf15ac6402cc670acb030c2
    CertUtil: -hashfile command completed successfully.
    ```

3. Modify `dbsync.dll`  and check new hash 

    ```
    PS C:\Program Files (x86)\ossec-agent> echo 1 >> .\dbsync.dll
    PS C:\Program Files (x86)\ossec-agent> certutil.exe -hashfile .\dbsync.dll SHA256
    SHA256 hash of .\dbsync.dll:
    cf782399bd24b340b814dbb0109de94b7e6fbd8c174c2a0f152c33430156dfd0
    CertUtil: -hashfile command completed successfully.
    ```

4. Install a 4.4.0 production package

5. Check that the `dbsync.dll`  hash did not change

    ```
    PS C:\Program Files (x86)\ossec-agent> certutil.exe -hashfile .\dbsync.dll SHA256
    SHA256 hash of .\dbsync.dll:
    cf782399bd24b340b814dbb0109de94b7e6fbd8c174c2a0f152c33430156dfd0
    CertUtil: -hashfile command completed successfully.
    
    ```

</details>

**Comment by BelenValdivia** [comment]
### Conclusion 🟢 
The behavior is as expected. The reported bug https://github.com/wazuh/wazuh/issues/15496 was successfully fixed.
 DLLs and non-configuration files are overwritten during an upgrade. Configuration file is not overwritten during an upgrade.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by teddytpc1** [comment]
Approved by CICD.
