### ISSUE TITLE
Research about Constraint failed during the synchronization of sys_hwinfo table

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3931]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|        4.5            |      https://github.com/wazuh/wazuh/issues/12343            |      https://github.com/wazuh/wazuh/pull/16065              |

## Description

The development aims to fix the problem that incorrect values ​​are being received for the proposed schema.
  ```
  
  cpu_cores INTEGER CHECK (cpu_cores > 0), 
  cpu_mhz REAL CHECK (cpu_mhz > 0), 
  ram_total INTEGER CHECK (ram_total > 0), 
  ram_free INTEGER CHECK (ram_free > 0), 
  ram_usage INTEGER CHECK (ram_usage >= 0 AND ram_usage <= 100)
  ```

# Development stage
- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
## Research applied change

**Comment by BelenValdivia** [comment]
### Research if we have a test for this case
This case will be executed manually using the wazuh db tool

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing

This case will be executed manually using the wazuh db tool

**Comment by BelenValdivia** [comment]
### Identify and justify the test "tier"

| Test | Tier | Justification|
|--------------------|--------------------|-----------------|
|     Test insert negative values in sys_hwinfo table with the wazuh db tool   |  0    |  Manual testing  with wazuh db tool  |
|     Test insert positive values in sys_hwinfo table with the wazuh db tool     |  0    |  Manual testing with wazuh db tool    |

**Comment by BelenValdivia** [comment]
### Coclusion

**Comment by damarisg** [comment]
QA Planning Approved.
