### ISSUE TITLE
Research about Macports pkgs support implementation 

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3933]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.6.0             | https://github.com/wazuh/wazuh/issues/15877              |     https://github.com/wazuh/wazuh/pull/16117               |

## Description

This issue aims to add support to Syscollector for the MacPorts package manager in the MacOS agent.

# Development stage

- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing

**Comment by BelenValdivia** [comment]
### Identify and justify the test "tier"

**Comment by BelenValdivia** [comment]
### Conclusion

**Comment by damarisg** [comment]
QA Planning approved.
