### ISSUE TITLE
Research failing system tests for `agent-groups`

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3936]
# Description

In the issue #3922 all the `agent-groups` related system tests were executed, from the _12_ tests **2** have **failed**, this issue aims to investigate if the failing tests need a fix and how to fix them or we must report the errors.

### Failing tests 
1. `test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment` - [result log](https://github.com/wazuh/wazuh-qa/files/10703295/05_assign_enrollment.zip)
2. `test_cluster/test_agent_groups/test_assign_groups_guess` - [result log](https://github.com/wazuh/wazuh-qa/files/10703300/10_agent_guess.zip)

The `test_assign_agent_group_with_enrollment` is failing when trying to get agent data, it seems like SQLite is not retrieving the `group` column, that could be because the word _group is a keyword_ in SQL.

**Comment by QU3B1M** [comment]
### Update 13/02/2023

After changing the query used in the case `test_assign_agent_group_with_enrollment.py` from `select id, group from...` to `select * from...` the test continues to fail, so it seems that the reason of the failure is not the query used.

**Comment by juliamagan** [comment]
## Update 14/02/2023

After several executions of `test_assign_groups_guess`, we couldn't reproduce the failure.

|R1|R2|R3|R4|R5|R6|R7|R8|R9|R10|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|  [🟢](https://github.com/wazuh/wazuh-qa/files/10734804/R1_test_assign_groups_guess.zip)  |  [🟢](https://github.com/wazuh/wazuh-qa/files/10734808/R2_test_assign_groups_guess.zip)  | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734812/R3_test_assign_groups_guess.zip)   |  [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734816/R4_test_assign_groups_guess.zip)  |   [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734818/R5_test_assign_groups_guess.zip) | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734819/R6_test_assign_groups_guess.zip)   |   [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734821/R7_test_assign_groups_guess.zip) | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/10734827/R8_test_assign_groups_guess.zip)   |    |    |

**Comment by juliamagan** [comment]
## Update 15/02/2023

- `test_assign_agent_group_with_enrollment`:

Previously, the agent was logged into a worker with an assigned group in the `enrollment` section. However, by delaying `agent_group_start_delay` to 300, it first looked for the assigned group to be `default`, changed this option back to 1 and on restart, it checks that the assigned group is the same as it was in `enrollment`, i.e. `group_test`.

What is happening now is that, when the agent registers and expects that in the worker it has the `default` group assigned, it does not have any group in the database of the worker. 

Waiting for confirmation from @wazuh/binary-beasts to know if this behavior is valid and expected.

**Comment by juliamagan** [comment]
## Conclusion

- `test_assign_agent_group_with_enrollment`:

  This behavior is expected. The suggested fix is to remove the check of `default` group. This will be worked on #3862

- `test_assign_groups_guess`: 

  This test was failing because of the other test. When `test_assign_agent_group_with_enrollment` failed, it didn't clean the environment correctly. No fix needed.
