### ISSUE TITLE
Validate cannot retrieve the windows package installation date if the registry does not have it

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3938]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.5                    |        https://github.com/wazuh/wazuh/issues/10703                |       https://github.com/wazuh/wazuh/pull/14499             |

## Description

The development aims to get the package installation time when the queried registry doesn't have the InstallDate field. Currently, the data provider gets the installation time from the InstallDate field and if time_install doesn't exist it will be empty, after the change this field will never be empty. The approach is to get the last modification date of the registry.

## Proposed checks
  The following test cases must be executed on ` Windows Server 2019` and `Windows 10`

  - <details><summary> Case 1: Check program with InstallDate </summary>

    ```
    Given I Install the wazuh agent in a Windows with 7-Zip installed
    When I modify the program registry
    Then the Installed date field is updated on the control panel 
    And  the Installed date field is updated in sys_programs db table
    ```

    </details>

  - <details><summary> Case 2: Check program without InstallDate</summary>

     ```
     Given I Install the wazuh agent in a Windows with Git installed
     When I modify the program registry
     Then the Installed date field is not updated on the control panel 
     And  the Installed date field is not updated in sys_programs db table
    ```

    </details>

---------------------------------------------------------------------------------------------
- [x] Upgrade
- [x] Fresh Install

**Comment by BelenValdivia** [comment]
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/14499/commits/a97fee0c7df7b8b19132998a79ad749de0d09839 | 

### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS             | CentOS 8        | vagrant       | `qactl/centos_8` |
| Windows |  Windows Server 2019 | vagrant | `qactl/windows_2019` |
| Windows  |  Windows 10 | vagrant | ISO |


### Tested executable file

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Windows |  [ msi   ](https://packages-dev.wazuh.com/warehouse/test/4.5/windows/wazuh-agent-4.5.0-14.02.0.windowsdate.msi)                                                  |
| CentOS | [ rpm manager ](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-14.02.0.windate.x86_64.rpm)   |

## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito 


## Conclusion

**Comment by BelenValdivia** [comment]
# Testing results  - WIP

## Upgrade

<details><summary>Windows Server 2019 - InstallDate registry not exist :green_circle:</summary>

1. **Given**  I upgraded the wazuh agent from the ` 4.3.10`  version to the `4.4` version in a Windows  
2. **And** `7-Zip` is installed
3.  **And** I check `7-Zip` installation date before modify the registry
     - Control panel

       ![zip before edit registry](https://user-images.githubusercontent.com/26927338/219122493-ade4c7b1-171b-4a51-baa0-90874016971a.png)


     - `/var/ossec/queue/db/agentid.db`
     
        ```
        [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/004.db '.mode line' 'select * from sys_programs where name like "%zip%"'
             scan_id = 0
           scan_time = 2023/02/16 17:34:49
              format = win
                name = 7-Zip 22.01 (x64)
            priority =
             section =
                size = 0
              vendor = Igor Pavlov
        install_time = 2023/02/15 06:13:04
             version = 40
        architecture = x86_64
           multiarch =
              source =
         description =
            location = C:\Program Files\7-Zip\
             triaged = 0
                 cpe =
            msu_name =
            checksum = 960284274e9e84e19db2165b8b6872b06c2c9762
             item_id = c27dc96992a516fe453044aa7b5d0f78ccfa665f
        ```


4. **When** I modify the program registry
![modify registry](https://user-images.githubusercontent.com/26927338/219119648-3da57c4e-7c55-4ca3-8e53-b697604bd1e1.png)

    
5. **Then** the Installed date field is updated on the control panel 
   
    ![zip after modify registry](https://user-images.githubusercontent.com/26927338/219121887-35dd8b78-769e-4457-ad63-185f2e902227.png)

6. **And** the Installed date field is updated in sys_programs db table

    ```
    [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/004.db '.mode line' 'select * from sys_programs where name like "%zip%"'
         scan_id = 0
       scan_time = 2023/02/16 17:44:54
          format = win
            name = 7-Zip 22.01 (x64)
        priority =
         section =
            size = 0
          vendor = Igor Pavlov
    install_time = 2023/02/16 09:43:48
         version = 240
    architecture = x86_64
       multiarch =
          source =
     description =
        location = C:\Program Files\7-Zip\
         triaged = 0
             cpe =
        msu_name =
        checksum = 6e08862b6e104c47ee72fe18e262cc3e63d792e7
         item_id = 671341e79ada3126db494dd935df482058d65798
    ```
    
 
   


</details>

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by damarisg** [comment]
## Closing conclusion 
Everything seems to be working properly.
