### ISSUE TITLE
Check FIM resources usage to complete and save one scan

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#394]
|Version|Branch|
|---|---|
|3.11 + FIM rework|[3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)|
|3.11 + FIM rework-sqlite|[3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)|

## Goals
- Compare RBTree implementation vs. SQLite version
- Disk usage (bandwidth) to complete and save one scan (reads and writes) [1M files]
- CPU usage to complete and save one scan [1M files]
- Memory usage to complete and save one scan [1M files]

## Configuration
- Disable every component in the agent except FIM.
- Set syscheck debug option
```
syscheck.debug=2
```

## Matrix
- Number of files:
    - 100k
    - 500k
    - 1M
- File size:
    - 1 KB (only with 100k files)
    - 100 KB (only with 100k files
    - 1 MB
- Path length:
    - 20 characters
    - 128 characters
    - 2048 characters
- Operations:
    - Insert
    - Update
    - Delete
    - Calculate integrity

## Target
Datasheet including:
1. Stats every second until the operation (insert, update or delete) is completed.
2. Time to complete the operation.

**Comment by jesusjimsa** [comment]
I have created a bash script to satisfy all the requirements shown in this issue that already works and writes the required information. I will rewrite it using Python.

**Comment by jesusjimsa** [comment]
The test has been rewritten in Python. Now, the test must check all cases and add the integrity calculation.

**Comment by jesusjimsa** [comment]
For the integrity calculation time, I have added to the `fim_sync.c` file, a message telling the time it took to calculate the integrity. In the script, a function reads the `ossec.log` file looking for the message and a regex reads the time measured by FIM.

**Comment by jotacarma90** [comment]
Test functionality:

- Scan and integrity tests, creating N files, taking the values of the ossec.log messages of time.
- Real-time tests (insert, update and delete), creating, modifying and deleting N files. These tests measure the time from when the N files are first created, until the corresponding N events have appeared in the ossec.log.


Comparative values between 3319-fim-rework and 3319-fim-rework-sqlite:

|           | Rbtree | Sqlite |   |   |
|-----------|--------|--------|---|---|
| Scan      | 31.6   | 37.4   |   |   |
| Integrity | 0.134  | 1.02    |   |   |
| Insert    | 32.98  | 35.9   |   |   |
| Update    | 32.98  | 37.2   |   |   |
| Delete    | 30.79  | 33.7   |   |   |




Note: For sqlite test, i needed to wait for one synchronization finish and dont remake the directorie /test, if not, real-time events dont appear until this finish. I tried put enable=no to synchronization.

**Comment by jotacarma90** [comment]
Created the script for generate graphics for all the .csv files.
