### ISSUE TITLE
Research about fixes to wazuh-db `sync-agent-groups-get` endpoint 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3943]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Fixes to wazuh-db sync-agent-groups-get endpoint](https://github.com/wazuh/wazuh/pull/16202) 

# Planning stage
  
  - [x] [Research the applied change.](https://github.com/wazuh/wazuh-qa/issues/3943#issuecomment-1431697216)
  - [x] [Design of test scenarios and use cases.](https://github.com/wazuh/wazuh-qa/issues/3943#issuecomment-1432366288)
  - [x] [Evaluate the current state of testing.](https://github.com/wazuh/wazuh-qa/issues/3943#issuecomment-1433014683)
  - [x] [Identify and justify the test "tier".](https://github.com/wazuh/wazuh-qa/issues/3943#issuecomment-1433048250)

**Comment by QU3B1M** [comment]
# Task 1 - Research the applied change

This PR affects the `wazuh_db` module by applying changes to the `sync-agent-groups-get` endpoint, making the endpoint's `condition` parameter optional, also fixing the the `group_sync_status` so it is not incorrectly marked as `synced`, and creating a new function to add the _global group hash_ to the `sync-agent-groups-get` response.

These proposed changes should fix 3 different issues:
- wazuh/wazuh#16188
- wazuh/wazuh#16190
- wazuh/wazuh#16196

**Comment by QU3B1M** [comment]
# Task 2 - Design of test scenarios and use cases

<details><summary>Scenario Outline 1 - Group sync status must be correct</summary>

- **Given** a `wazuh-cluster` with 2 `workers`.
- **And** 2k `wazuh-agent` connected to each node all assigned to 4 groups.
- **And** the sync interval of the worker-2 is set to 5 minutes.
- **When** a group is deleted.
- **Then** the `group_sync_status` of the worker-2 agents is **`syncreq`**
- **And** for the rest of agents `group_sync_status` is **`synced`**

```JSON
  /var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/cluster.json 
  "intervals":{
      "worker": {
          "sync_integrity": 9,
          "sync_agent_info": 10,
          "sync_agent_groups": 30,
          "timeout_agent_groups": 40,
          "keep_alive": 60,
          "connection_retry": 10,
          "max_failed_keepalive_attempts": 2
      },
```
</details>

<details><summary>Scenario Outline 2 - Group sync status updated with big amout of agents</summary>

- **Given** a `wazuh-cluster` with 2 `workers`.
- **And** 10k `wazuh-agent` connected to each node all assigned to 4 groups.
- **When** a group is deleted.
- **Then** the `group_sync_status` of all the nodes is **`synced`**

</details>

**Comment by QU3B1M** [comment]
Task 3 - Evaluate the current state of testing

**Comment by QU3B1M** [comment]
# Task 4 - Identify and justify the test "tier"

**Scenarios 1 & 2** are Integration tests as all the validations resides on the manager and the agents only needs to be enrolled (that could be made easily with a script), while the **scenario 3** is a system test where we need to do some validations in multiple nodes of a cluster.

**Comment by QU3B1M** [comment]
# Conclusion 

After the investigation we conclude that the following issues are needed to approve the PR:
- #3950
- #3951

And the following issues to track the test development to cover cases like this _(not required for the PR approve):_ 
- #3952
- #3953

**Comment by damarisg** [comment]
QA Planning Approved.
