### ISSUE TITLE
Update the test plan reviewing the reported bugs

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3946]
| Target version | Related issue |
|--------------------|--------------------|
|             5.0.0           |            https://github.com/wazuh/wazuh-qa/issues/3945            |    

## Description

This issue aims to update/refine the first iteration, reviewing the reported bugs https://github.com/wazuh/wazuh-qa/issues/3619#issue-1455175408 during the testing process and creating an alternative format for the document using tables to display the use cases.

Documentation of the Engine's test plan: [file](https://docs.google.com/document/d/12k3Zt1BtnCYW8LsIBTzTo6pJKFstEVgWb8-yY1llcss/edit?usp=sharing)

## Status

- [x] In progress (@roronoasins)
- [x] QA leader approved (@damarisg)
- [x] Development team leader approved (@JcabreraC)

**Comment by damarisg** [comment]
Remember to apply the new template, and add the epic documentation at https://github.com/wazuh/wazuh-qa/issues/3619. 

In this issue, you need to apply some suggestions added to the file. 
And you should update the status of some cases re-tested with the last results.

**Comment by roronoasins** [comment]
## 2023/03/03

The following changes were applied:

- The use cases lists were replaced (some of them, to verify the new approach format) by tables
- A brief introduction was added
- Automation status convention was added
- Update the cases status that was fixed
