### ISSUE TITLE
Validate fixes to wazuh-db `sync-agent-groups-get` endpoint

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3951]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 | [#16188](https://github.com/wazuh/wazuh/issues/16188) [#16190](https://github.com/wazuh/wazuh/issues/16190)  | [#16202](https://github.com/wazuh/wazuh/pull/16202)  |

## Description

This PR affects the `wazuh_db` module by applying changes to the `sync-agent-groups-get` endpoint, making the endpoint's `condition` parameter optional, also fixing the the `group_sync_status` so it is not incorrectly marked as `synced`, and creating a new function to add the _global group hash_ to the `sync-agent-groups-get` response.

## Proposed checks

<details><summary>Scenario Outline 1: Group sync status - syncreq status marked correctly</summary>

```Gherkin
Given a wazuh-manager and 50k wazuh-agent connected.
And all wazuh-agents group sync status is synreq.
When the status of the first chunk of agents is updated to synced.
Then only the agents from the first chunk are "synced" the rest are still "synreq".
```
</details>

<details><summary>Scenario Outline 2: Group sync status - status updated correctly</summary>

```Gherkin
Given a wazuh-cluster with 2 workers.
And 10k wazuh-agent connected to each node all assigned to the same 3 groups.
When a group folder is deleted in the "<node>".
Then immediately all agents group_sync_status changes to "<first_status>".
And after the cluster is sync tall agents status is "<sync_status>" on all nodes.

Examples:
  | node     | first_status | final_status  |
  |----------|--------------|---------------|
  | master   | synreq       | synced        |
  | worker-1 | synced       | synced        |
  | worker-2 | synced       | synced        |
```

</details>

### Fix application methods
- [x] Fresh install
- [x] Upgrade

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [2235f68](https://github.com/wazuh/wazuh/pull/16202/commits/2235f68a3c021bf4f5af941caba3a9cc8992a547)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` |
|-----------------|   
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit2235f68_amd64.deb)|      

### Status

- [x] In progress @QU3B1M 
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Testing results

## Unfixed

<details><summary>Error repoduction</summary>


  - <details><summary>Group sync status - status is not marked correctly</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `master`.
        ```shell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. On the workers some agents `group_sync_status` is `syncreq`.
        `worker 1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        [
            {
                "group_sync_status": "syncreq"
            },
            ...
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
        `worker 2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        [
            {
                "group_sync_status": "syncreq"
            },
            ...
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
    </details>

  - <details><summary>Group sync status - syncreq status is not being updated correctly :green_circle:</summary>

    1. Connect 50k `wazuh-agents` to `wazuh-manager`
    2. Ensure all agent's group sync status is `syncreq`
        ```powershell
        python3 unsync.py 1 50000 master
        ```
    3. Update the status of the first chunk of agents
        ```sql
        python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": true, "get_global_hash": true}'

        due [{"data":[{"id":1740,"groups":["g0","g1","g2"]}...{"id":2004,"groups":["g0","g1","g2"]}]}]
        ```
    4. Not only the agents from the first chunk are being updated to `synced`
        `last of the first chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2004'

        [
            {
                "group_sync_status": "synced"
            }
        ]
        ```
        `first of the seccond chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2005'

        [
            {
                "group_sync_status": "synced"
            }
        ]
        ```
    </details>

</details>

## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade `master` node. 
  ```sh
  dpkg -i wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb 

  dpkg: warning: downgrading wazuh-manager from 4.4.0-1 to 4.4.0-0.commitcf0792c
  (Reading database ... 101127 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commitcf0792c) over (4.4.0-1) ...
  Setting up wazuh-manager (4.4.0-0.commitcf0792c) ...
  ```
- Upgrade `worker-1` node. 
  ```sh
  dpkg -i wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb 

  dpkg: warning: downgrading wazuh-manager from 4.4.0-1 to 4.4.0-0.commitcf0792c
  (Reading database ... 94370 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commitcf0792c) over (4.4.0-1) ...
  Setting up wazuh-manager (4.4.0-0.commitcf0792c) ...
  ```
- Upgrade `worker-2` node. 
  ```sh
  dpkg -i wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb 

  dpkg: warning: downgrading wazuh-manager from 4.4.0-1 to 4.4.0-0.commitcf0792c
  (Reading database ... 101127 files and directories currently installed.)
  Preparing to unpack wazuh-manager_4.4.0-0.commitcf0792c_amd64.deb ...
  Unpacking wazuh-manager (4.4.0-0.commitcf0792c) over (4.4.0-1) ...
  Setting up wazuh-manager (4.4.0-0.commitcf0792c) ...
  ```
</details>

<details><summary>Scenario 1: Group sync status - syncreq status marked correctly :green_circle:</summary>

  - <details><summary>Gherkin scenario description</summary>

      ```Gherkin
      Given a wazuh-manager and 50k wazuh-agent connected.
      And all wazuh-agents group sync status is syncreq.
      When the status of the first chunk of agents is updated to synced.
      Then only the agents from the first chunk are "synced" the rest are still "syncreq".
      ```
      </details>

  - <details><summary>Case 1 - Only first chuck is updated :green_circle:</summary>
    
    1. Connect 50k `wazuh-agents` to `wazuh-manager`
    2. Ensure all agent's group sync status is `syncreq`
        ```powershell
        python3 unsync.py 1 50000 master
        ```
    3. Update the status of the first chunk of agents
        ```sql
        python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": true, "get_global_hash": true}'

        due [{"data":[{"id":1740,"groups":["g0","g1","g2"]}...{"id":2004,"groups":["g0","g2"]}]}]
        ```
    4. Check only the agents from the first chunk are being updated to `synced`.
        `last of the first chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2004'

        [
            {
                "group_sync_status": "synced"
            }
        ]
        ```
        `first of the seccond chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2005'

        [
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
    </details>
</details>


<details><summary>Scenario 2: Group sync status - status updated correctly :green_circle:</summary>

  - <details><summary>Cluster setup</summary>

      ```powershell
      /var/ossec/bin/cluster_control -l

      NAME      TYPE    VERSION  ADDRESS        
      master    master  4.4.0    192.168.56.10  
      worker-2  worker  4.4.0    192.168.56.12  
      worker-1  worker  4.4.0    192.168.56.11  
      ```
    </details>

  - <details><summary>Gherkin scenario description</summary>

      ```Gherkin
      Given a wazuh-cluster with 2 workers.
      And 10k wazuh-agent connected to each node all assigned to the same 3 groups.
      When a group folder is deleted in the "<node>".
      Then immediately all agents group_sync_status changes to "<first_status>".
      And after the cluster is sync tall agents status is "<sync_status>" on all nodes.

      Examples:
        | node     | first_status | final_status  |
        |----------|--------------|---------------|
        | master   | syncreq      | synced        |
        | worker-1 | synced       | synced        |
        | worker-2 | synced       | synced        |
      ```
      </details>


  - <details><summary>Case 1 - Group folder deleted on <code>master</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `master`.
        ```shell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` changes to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        [
            {
                "group_sync_status": "syncreq"
            },
            {
                "group_sync_status": "syncreq"
            },
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        `master`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        []
        ```
        `worker-1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
        `worker-2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>

  - <details><summary>Case 2 - Group folder deleted on <code>worker-1</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `worker-1`.
        ```powershell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` does **not** change to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        `master`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        []
        ```
        `worker-1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
        `worker-2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>

  - <details><summary>Case 3 - Group folder deleted on <code>worker-2</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `worker-2`.
        ```powershell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` does **not** change to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        `master`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        []
        ```
        `worker-1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
        `worker-2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>
</details>

## Fresh install

<details><summary>Scenario 1: Group sync status - syncreq status marked correctly :green_circle:</summary>

  - <details><summary>Gherkin scenario description</summary>

      ```Gherkin
      Given a wazuh-manager and 50k wazuh-agent connected.
      And all wazuh-agents group sync status is syncreq.
      When the status of the first chunk of agents is updated to synced.
      Then only the agents from the first chunk are "synced" the rest are still "syncreq".
      ```
      </details>

  - <details><summary>Case 1 - Only first chuck is updated :green_circle:</summary>

    1. Connect 50k `wazuh-agents` to `wazuh-manager`
    2. Ensure all agent's group sync status is `syncreq`
        ```powershell
        python3 unsync.py 1 50000 master
        ```
    3. Update the status of the first chunk of agents
        ```sql
        python3 wdb-query.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": true, "get_global_hash": true}'

        due [{"data":[{"id":1740,"groups":["g0","g1","g2"]}...{"id":2753,"groups":[]},{"id":2754,"groups":[]},{"id":2755,"groups":[]}]}]
        ```
    4. Check only the agents from the first chunk are being updated to `synced`.
        `last of the first chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2755'

        [
            {
                "group_sync_status": "synced"
            }
        ]
        ```
        `first of the seccond chunk`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where id=2756'

        [
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
    </details>
</details>


<details><summary>Scenario 2: Group sync status - status updated correctly :green_circle:</summary>

  - <details><summary>Cluster setup</summary>

      ```powershell
      /var/ossec/bin/cluster_control -l

      NAME      TYPE    VERSION  ADDRESS        
      master    master  4.4.0    192.168.56.10  
      worker-2  worker  4.4.0    192.168.56.12  
      worker-1  worker  4.4.0    192.168.56.11  
      ```
    </details>

  - <details><summary>Gherkin scenario description</summary>

      ```Gherkin
      Given a wazuh-cluster with 2 workers.
      And 10k wazuh-agent connected to each node all assigned to the same 3 groups.
      When a group folder is deleted in the "<node>".
      Then the grop is "<group_status>" on all nodes.
      And after the cluster is sync the group_sync_status is "<sync_status>"

      Examples:
        | node     | group_status | sync_status   |
        |----------|--------------|---------------|
        | master   | deleted      | synced        |
        | worker-1 | not deleted  | synced        |
        | worker-2 | not deleted  | synced        |
      ```
      </details>


  - <details><summary>Case 1 - Group folder deleted on <code>master</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `master`.
        ```shell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    
        ```shell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` changes to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        [
            {
                "group_sync_status": "syncreq"
            },
            {
                "group_sync_status": "syncreq"
            },
            {
                "group_sync_status": "syncreq"
            }
        ]
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>

  - <details><summary>Case 2 - Group folder deleted on <code>worker-1</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `worker-1`.
        ```powershell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` does **not** change to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        1. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        `master`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        []
        ```
        `worker-1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
        `worker-2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>

  - <details><summary>Case 3 - Group folder deleted on <code>worker-2</code> node :green_circle:</summary>

    1. Connect 10k `wazuh-agents` to each cluster node and assign all to 3 groups.
    2. Delete the `g1` group folder in the `worker-2`.
        ```powershell
        rm -rf /var/ossec/etc/shared/g1/
        ```
    3. Immediately check `group_sync_status` does **not** change to `syncred`.
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    4. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        1. Once the cluster syncs check there is **no** group_sync_status in `syncreq` on any nodes.
        `master`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq" limit 3'

        []
        ```
        `worker-1`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
        `worker-2`
        ```sql
        python3 wdb-query.py 'global sql select group_sync_status from agent where group_sync_status="syncreq"'

        []
        ```
    </details>
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
