### ISSUE TITLE
Add coverage to `group_sync_status` marked correctly

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3952]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 | [#16188](https://github.com/wazuh/wazuh/issues/16188)  | [#16202](https://github.com/wazuh/wazuh/pull/16202)  |

## Description

**Integration** tests should be developed to validate the `group_sync_status` of a big amount of `wazuh-agents` enrolled to a `wazuh-manager` is updated correctly on each agent.

## Proposed test cases

<details><summary>Scenario Outline 1: Group sync status - syncreq status marked correctly</summary>

```Gherkin
Given a wazuh-manager and 50k wazuh-agent connected.
And all wazuh-agents group sync status is synreq.
When the status of the first chunk of agents is updated to synced.
Then only the agents from the first chunk are "synced" the rest are still "synreq".
```
</details>

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
