### ISSUE TITLE
Add coverage to `group_sync_status` updated correctly on each node

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3953]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0 |[#16190](https://github.com/wazuh/wazuh/issues/16190)   | [#16202](https://github.com/wazuh/wazuh/pull/16202)  |

## Description

**System** tests should be developed to validate the `group_sync_status` is updated correctly on each `cluster's` node after a group where the agents are assigned is altered.

## Proposed test cases

<details><summary>Group sync status - status updated correctly</summary>

```Gherkin
Given a wazuh-cluster with 2 workers.
And 10k wazuh-agent connected to each node all assigned to the same 3 groups.
When a group folder is deleted in the "<node>".
Then immediately group_sync_status is in "<first_status>" on all agents.
And after the cluster is sync the group_sync_status is "<final_status>"

Examples:
  | node     | first_status | final_status  |
  |----------|--------------|---------------|
  | master   | synreq       | synced        |
  | worker-1 | synced       | synced        |
  | worker-2 | synced       | synced        |
```

</details>

**Comment by davidjiglesias** [comment]
It has to be merged into 4.8.0, careful with changelog if applicable.

**Comment by pro-akim** [comment]
## Update
Rebased to 4.8.0

**Comment by davidjiglesias** [comment]
LGTM!
