### ISSUE TITLE
Validate the fix  Wazuh agent for AIX can't load syscollector

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3957]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.4.0               |    https://github.com/wazuh/wazuh/issues/16220          |   https://github.com/wazuh/wazuh/pull/16221                 |

## Description

The development aims to fix a syscollector error in AIX linking again only for AIX the binaries with the c++ standard library and gcc_s in a static way.

## Proposed checks

- `Case 1 - libstdc++ statically for AIX`
  1. **Given**  I install the wazuh agent `4.4` with fix  version in AIX  
  2. **When**  I check  '/var/ossec/bin/wazuh-modulesd'  there are no errors 
  3.  **And** I check `ossec.log` there are no errors
  4.  **Then** binaries are not loading the libraries `libstdc++.*` and  `libgcc_s.*`

- `Case 2 - libstdc++ and libgcc_s.so.1 loaded for other Linux distribution`
   1. **Given**  I install the wazuh agent `4.4` with fix  version
    2. **When**  I check  '/var/ossec/bin/wazuh-modulesd'  there are no errors 
    3.  **And** I check `ossec.log` there are no errors
    4.  **Then** binaries are loading the libraries `libstdc++.so.6` and  `libgcc_s.so.1`

------------------------------------------------------------------------------------------------------------------------------------------
- [x] Fresh Install
- [x] Upgrade

**Comment by BelenValdivia** [comment]
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16221/commits/edf28fc2f9f76c8b413c4c257650027d6239318e | 



### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS             | CentOS 8        | vagrant       | `qactl/centos_8` |
| AIX |   AIX 6.1 TL9 Standard system| cloud.siteox.com |   |



### Tested executable file

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| AIX      |   [ rpm   ](https://packages-dev.wazuh.com/warehouse/test/4.4/aix/wazuh-agent-4.4.0-1.aix.ppc.rpm)                                                                     |
| CnetOS     |   [ rpm manager  ](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-0.0.0.syscollectoraix.x86_64.rpm)        [rpm agent](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-0.0.0.syscollectoraix.x86_64.rpm)                                                             |



## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito 


## Conclusion

**Comment by BelenValdivia** [comment]
# Test results

### Fresh Install

<details><summary> Libstdc++ statically for AIX</summary>

1. Install wazuh agent with core fix
2. Check no errors in `ossec.conf`

    ```
    2023/02/16 13:24:01 wazuh-modulesd:syscollector: INFO: Module started.
    2023/02/16 13:24:01 wazuh-modulesd:syscollector: INFO: Starting evaluation.
    2023/02/16 13:24:01 wazuh-modulesd:syscollector: INFO: Evaluation finished.
    ```

3.  Check no errors in `modulesd`

    ```
    bash-4.4# /var/ossec/bin/wazuh-modulesd
    bash-4.4#
    ```

4.  Check binaries are not loading the libraries `libstdc++.*`  and `libgcc_s.*`

- `ldd /var/ossec/lib/libsysinfo.so`

    ```
    bash-4.4# ldd /var/ossec/lib/libsysinfo.so
    /var/ossec/lib/libsysinfo.so needs:
             /var/ossec/lib/libwazuhext.so
             /usr/lib/libc.a(shr.o)
             /usr/lib/libpthreads.a(shr_xpg5.o)
             /unix
             /usr/lib/libcrypt.a(shr.o)
             /usr/lib/libpthreads.a(shr_comm.o)
    ```

- `ldd /var/ossec/lib/libsyscollector.so`
    ```
    bash-4.4# ldd /var/ossec/lib/libsyscollector.so
    /var/ossec/lib/libsyscollector.so needs:
             /var/ossec/lib/libdbsync.so
             /var/ossec/lib/librsync.so
             /var/ossec/lib/libsysinfo.so
             /var/ossec/lib/libwazuhext.so
             /usr/lib/libpthreads.a(shr_xpg5.o)
             /usr/lib/libc.a(shr.o)
             /unix
             /usr/lib/libpthreads.a(shr_comm.o)
             /usr/lib/libcrypt.a(shr.o)
    ```

- `ldd /var/ossec/lib/librsync.so`
    ```
    bash-4.4# ldd /var/ossec/lib/librsync.so
    /var/ossec/lib/librsync.so needs:
             /var/ossec/lib/libdbsync.so
             /var/ossec/lib/libwazuhext.so
             /usr/lib/libpthreads.a(shr_xpg5.o)
             /usr/lib/libc.a(shr.o)
             /unix
             /usr/lib/libpthreads.a(shr_comm.o)
             /usr/lib/libcrypt.a(shr.o)
    ```

- `ldd /var/ossec/lib/libdbsync.so`

    ```
    bash-4.4# ldd /var/ossec/lib/libdbsync.so
    /var/ossec/lib/libdbsync.so needs:
             /var/ossec/lib/libwazuhext.so
             /usr/lib/libpthreads.a(shr_xpg5.o)
             /usr/lib/libc.a(shr.o)
             /unix
             /usr/lib/libpthreads.a(shr_comm.o)
             /usr/lib/libcrypt.a(shr.o)
    
    ```
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly.
