### ISSUE TITLE
Validate the fix in the order in which the global DB is populated

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3970]
| Target version | Related issue | Related PR |Test planning |
|--------------------|--------------------|-----------------|------------------------|
|        4.4.0                |             https://github.com/wazuh/wazuh/issues/16201           |         https://github.com/wazuh/wazuh/pull/16233           |https://github.com/wazuh/wazuh-qa/issues/3967|

## Description

The purpose of this issue is to test the fix in the order in which the global DB is populated. By modifying the order of these steps, we ensure that the manager will never try to add an entry in the belongs table before synchronizing the groups in the DB.

### Test cases

- Test tables insertion:

  <details>
  <summary>Case 1: <code>default</code> group assigned</summary>
  <br>

   **Given** one manager 
   **And** one agent with `default` group assigned
   **When** stopping manager
   **And** deleting content in `group` and `belongs` tables
   **And** creating files in `queue/agent-groups`
   **And** starting manager
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`
   **and** `default` group is assigned

  </details>

  <details>
  <summary>Case 2:  Custom group assigned</summary>
  <br>

   **Given** one manager 
   **And** one agent with custom group assigned
   **When** stopping manager
   **And** deleting content in `group` and `belongs` tables
   **And** creating files in `queue/agent-groups`
   **And** starting manager
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`
   **and** custom group is assigned

  </details>

### Status

- [x] In progress (@juliamagan)
- [x] Pending Review
- [x] QA manager approved (@jmv74211)
- [x] Development team leader approved (@TomasTurina)

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/16233/commits/6755e3cbfe34a9e04e451d6bdd4b1feb4a2cfbcb   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| CentOS   | 8 | Vagrant | qactl/centos_8 |


### Tested packages

| `wazuh-manager` | `wazuh-agent`|
|-----------------|--------------|
| [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit6755e3c.x86_64.rpm) | [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit6755e3c.x86_64.rpm)

### Status

- [x] In progress (@juliamagan)
- [ ] Pending Review
- [ ] QA manager approved (@jmv74211)
- [ ] Development team leader approved (@TomasTurina)

### Conclusion

**Comment by juliamagan** [comment]
### Conclusion 🟢 

Everything seems to work as expected.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work as expected.
