### ISSUE TITLE
Validate Memory leak in the SCA decoder fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3976]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4.0-1a          |   https://github.com/wazuh/wazuh/issues/16211                     | https://github.com/wazuh/wazuh/pull/16214                 |

## Description
This issue aims to test the fix to a Memory Leak related to SCA in version 4.4.0-1a. The leak was caused by a pointer not being deleted when it was empty, meaning the memory would not be released.

The Issue was detected in the Stress tests pipeline, and is not easily reproduced manually.

![image](https://user-images.githubusercontent.com/14913942/218501434-e0e29388-ecde-44d4-b528-be2179a5b0f4.png)

## Proposed checks

- [x] Reproduce error in Stress test environment in 4.4 branch
- [x] Validate fix in Stress test enviroment

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/pull/16214/commits/5f73c4022232e6d509b9083abd933589876298fe | 



### Testing environment

| OS | OS version |  Deployment | Image/AMI | Notes
|-- |-- |-- |--|--|
| Ubuntu | 20.04 | `Local \| Vagrant` | ubuntu/focal64 |
| Windows | 11 | `Local \| Vagrant` | gusztavvargadr/windows-11-insider-preview-enterprise |


### Tested packages
Manager was built from sources since Jenkins is down

## Conclusion 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @chemamartinez

**Comment by Deblintrake09** [comment]
# Testing results

## Replicate the error
<details><summary>SCA report does not generate Memory Leaks</summary>

- Install Manager from tag v4.4.0-rc1
- Start valgrind command
```
# valgrind --track-fds=yes --show-leak-kinds=all --leak-check=full --log-file=/vagrant/analysisd.log /var/ossec/bin/wazuh-analysisd -fdd

```
- Connect windows 11 agent
![imagen](https://user-images.githubusercontent.com/14501079/221179913-0b737995-33c2-410a-80d0-c7592bb44823.png)
```
# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ubuntu-focal (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: DESKTOP-FDL39IH, IP: any, Active
```
- Stop Valgrind and check report for Memleak
```
==105886== 237 (192 direct, 45 indirect) bytes in 3 blocks are definitely lost in loss record 304 of 631
==105886==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==105886==    by 0x49792CD: cJSON_New_Item.isra.2 (in /var/ossec/lib/libwazuhext.so)
==105886==    by 0x497ACEC: cJSON_CreateString (in /var/ossec/lib/libwazuhext.so)
==105886==    by 0x16147E: DecodeSCA (in /var/ossec/bin/wazuh-analysisd)
==105886==    by 0x140D49: w_decode_sca_thread (in /var/ossec/bin/wazuh-analysisd)
==105886==    by 0x5184608: start_thread (pthread_create.c:477)
==105886==    by 0x52BE132: clone (clone.S:95)

==105886== LEAK SUMMARY:
==105886==    definitely lost: 192 bytes in 3 blocks
==105886==    indirectly lost: 45 bytes in 3 blocks
==105886==      possibly lost: 14,112 bytes in 49 blocks
==105886==    still reachable: 26,286,457 bytes in 138,514 blocks
==105886==         suppressed: 0 bytes in 0 blocks
==105886== 
```
</details>


## Upgrade install
<details><summary>SCA report does not generate Memory Leaks</summary>

- Upgrade manager from `16189-fix-SCA-decoder-leak` branch
```
# git checkout 16189-fix-SCA-decoder-leak
Branch '16189-fix-SCA-decoder-leak' set up to track remote branch '16189-fix-SCA-decoder-leak' from 'origin'.
Switched to a new branch '16189-fix-SCA-decoder-leak'

cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db

# ./install.sh
Wait for success...
success
Searching for deprecated rules and decoders...
Starting Wazuh...
 - Configuration finished properly.
 - Update completed.
```
- Start valgrind command
```
# valgrind --track-fds=yes --show-leak-kinds=all --leak-check=full --log-file=/vagrant/analysisd.log /var/ossec/bin/wazuh-analysisd -fdd
```
- Connect windows 11 agent
![imagen](https://user-images.githubusercontent.com/14501079/221182046-b0ce1d8e-805f-487c-afe1-a25678c3532e.png)
```
# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ubuntu-focal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: DESKTOP-FDL39IH, IP: any, Active
```
- Stop Valgrind and check report for Memleak
```
==118746== LEAK SUMMARY:
==118746==    definitely lost: 0 bytes in 0 blocks
==118746==    indirectly lost: 0 bytes in 0 blocks
==118746==      possibly lost: 14,112 bytes in 49 blocks
==118746==    still reachable: 26,262,558 bytes in 138,532 blocks
==118746==         suppressed: 0 bytes in 0 blocks
```
</details>

**Comment by Deblintrake09** [comment]
# Conclusion

After testing done, everything works correctly and no Memleaks are present.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by Deblintrake09** [comment]
## Update 15/03/2023

- After Jenkins Checks were re enabled WDB tests failed. 
- Research shows a rebase was needed.
- After rebase WDB IT tests are 🟢
