### ISSUE TITLE
Research about standarize install date

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3981]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|    4.5                   |   https://github.com/wazuh/wazuh/issues/13884               |     https://github.com/wazuh/wazuh/pull/14161               |

## Description

This issue aims to convert the timestamp where a package was installed (install_time in sys_programs) into a "%Y/%m/%d %H:%M:%S" format value.

## Development stage
- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made

This issue aims to convert the timestamp where a package was installed (install_time in sys_programs) into a "%Y/%m/%d %H:%M:%S" format value.

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

**Comment by BelenValdivia** [comment]
## Evaluate the current state of testing

**Comment by BelenValdivia** [comment]
###  Identify and justify the test "tier"

| Test | Tier | Justification|
|--------------------|--------------------|-----------------|
|     Test the timestamp of the packages installed     |  0    |  Test how the Syscollector module is able to scan and collect information about installed packages    |

**Comment by BelenValdivia** [comment]
### Coclusion

- Added issue for manual testing

**Comment by damarisg** [comment]
QA Planning Approved.
