### ISSUE TITLE
Validate standarize install date

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3984]
| Target version | Related issue | Related PR | Test planning |
|--------------------|--------------------|-----------------|-----------------|
|     4.5                   |     https://github.com/wazuh/wazuh/issues/13884             |     https://github.com/wazuh/wazuh/pull/14161               | https://github.com/wazuh/wazuh-qa/issues/3981 |

## Description

This issue aims to convert the timestamp where a package was installed (install_time in sys_programs) into a "%Y/%m/%d %H:%M:%S" format value.

## Proposed checks

- Test the timestamp of the packages installed has the format `"%Y/%m/%d %H:%M:%S"`

  <details><summary>Scenario Outline 1: Check that the package install time has the UTC format</summary>
  
    ```Gherkin
    Given I Install the wazuh agent "<version>" in a Windows 
    When I  install the "<program>" 
    Then the Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
    
        Examples:
      |  version           | package              |
      | -------------------|  ------------------- |
      |  4.5               |  7-Zip               |
      |  4.5               |  Git                 |
      |  4.5               |  Google Chrome       |
    
    ```
  
   </details>

**Comment by BelenValdivia** [comment]
### Fresh Install

<details><summary> Scenario outline: Check that the package install time has the UTC format </summary>

  1. Install Wazuh agent 4.5 from sources
  2. Install 7-Zip, Google Chrome, and Git
  3. Check Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
        
     - `7-Zip`: 
         ```
         [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/003.db 'select name,install_time from sys_programs 
         where name like "%zip%"'
         7-Zip 22.01 (x64)|2023/02/16 17:43:48
```


</details>

**Comment by BelenValdivia** [comment]
Update 27/02/2023

- Set up environment
- Cloned wazuh/wazuh repository
- Generated installers from sources
- Tested fresh install

**Comment by BelenValdivia** [comment]
Update 28/02/2023

- Tested upgrade
- Bug with .exe installers in windows

**Comment by BelenValdivia** [comment]
Update 01/03/2023
- Research how to generate msi from sources

**Comment by BelenValdivia** [comment]
### Fresh Install

<details><summary> Scenario outline: Check that the package install time has the UTC format - Wazuh-agent.exe installer 🟢 </summary>

- <details><summary><code>Case 1:</code> Check 7-Zip package  :green_circle:</summary>

  
  1. Install Wazuh agent 4.5 exe from sources
  2. Install `7-Zip`
  3. Check Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
        
     - `7-Zip`: 
         ```
         [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/003.db 'select name,install_time from sys_programs 
         where name like "%zip%"'
         7-Zip 22.01 (x64)|2023/02/16 17:43:48
         ```

  </details>

- <details><summary><code>Case 2:</code> Check Google Chrome package  :green_circle:</summary>

  
  1. Install Wazuh agent 4.5 exe from sources
  2. Install `Google Chrome`
  3. Check Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
        
     - `Google Chrome`:
        ```
        [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/003.db 'select name,install_time from sys_programs where 
        name like "%google%"'
        Google Chrome|2023/02/27 00:00:00
        ```
  </details>

- <details><summary><code>Case 3:</code> Check Git package  :green_circle:</summary>

  
  1. Install Wazuh agent 4.5 exe from sources
  2. Install `Git`
  3. Check Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
        
     - `Git`:
        ```
        [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/003.db 'select name,install_time from sys_programs where 
        name like "%git%"'
        Git|2021/09/15 01:00:00
        ```
  </details>

</details>


### Upgrade

<details><summary> Scenario outline: Check that the package install time has the UTC format 🔴 </summary>

  1. Install Wazuh agent 4.5 from sources
  2. Install 7-Zip, Google Chrome, and Git
  3. Check Install time field has the format "%Y/%m/%d %H:%M:%S" in sys_programs db table
        
     - `7-Zip`: 
         ```
         [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/003.db 'select name,install_time from sys_programs 
         where name like "%zip%"'
         7-Zip 22.01 (x64)|2023/02/16 19:24:56
         ```

     - `Git`:
        ```
        [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/004.db 'select name,install_time from sys_programs where 
        name like "%git%"'
        Git|20210915
        ```

     - `Google Chrome`:
        ```
        [root@centos-manager2 vagrant]# sqlite3 /var/ossec/queue/db/004.db 'select name,install_time from sys_programs where 
        name like "%google%"'
        Google Chrome|20230228
        ```

>Note: There is a bug created previously, Upgrade with .exe installers doesn't work correctly  https://github.com/wazuh/wazuh/issues/15295
</details>

**Comment by BelenValdivia** [comment]
### Conclusion

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  :círculo_verde_grande:
- **Comments**: Everything seems to work correctly, except for the upgrade with the EXE installer.
There is a [bug](https://github.com/wazuh/wazuh/issues/15873) for that. It is not related to the new changes.
