### ISSUE TITLE
Validate constraint failed during the synchronization of sys_hwinfo table

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3985]
| Target version | Related issue | Related PR | Test planning |
|--------------------|--------------------|-----------------|-----------------|
|     4.5                   |        https://github.com/wazuh/wazuh/issues/12343                |  https://github.com/wazuh/wazuh/pull/16065                  | https://github.com/wazuh/wazuh-qa/issues/3931 |

## Description

The development aims to fix the problem that incorrect values ​​are being received for the proposed schema.
Deleted constraints in `sys_hwinfo`  table
  ```
  
  cpu_cores INTEGER CHECK (cpu_cores > 0), 
  cpu_mhz REAL CHECK (cpu_mhz > 0), 
  ram_total INTEGER CHECK (ram_total > 0), 
  ram_free INTEGER CHECK (ram_free > 0), 
  ram_usage INTEGER CHECK (ram_usage >= 0 AND ram_usage <= 100)
  ```

## Proposed checks

- Test insert negative values in sys_hwinfo table with the wazuh db tool
  <details><summary>Scenario Outline 1: Insert values not supported before the change (negatives and zero) into sys_hwinfo table</summary>

    ```Gherkin
    Given I Install the wazuh agent "<version>" in a Windows 
    When I  insert value in "<registry>" in  sys_hwinfo table
    Then the value is correctly inserted in  sys_hwinfo table
    
    Examples:
    |  version           | registry             |
    | -------------------|  ------------------- |
    |  4.5               |  cpu_cores           |
    |  4.5               |  cpu_mhz             |
    |  4.5               |  ram_total           |
    |  4.5               |  ram_free            |
    |  4.5               |  ram_usage           |
    
    ```

  </details>

- Test insert positive values in sys_hwinfo table with the wazuh db tool
  <details><summary>Scenario Outline 2: Insert positive values into sys_hwinfo table</summary>

    ```Gherkin
    Given I Install the wazuh agent "<version>" in a Windows 
    When I  insert a positive value in "<registry>" in  sys_hwinfo table
    Then the value is correctly inserted in  sys_hwinfo table
    
    Examples:
    |  version           | registry             |
    | -------------------|  ------------------- |
    |  4.5               |  cpu_cores           |
    |  4.5               |  cpu_mhz             |
    |  4.5               |  ram_total           |
    |  4.5               |  ram_free            |
    |  4.5               |  ram_usage           |
    
    ```
  </details>

**Comment by BelenValdivia** [comment]
02/03/2023
- Set up environment 
- Installed wazuh manager from sources
- Installed wazuh-tools repository
- Research how works `wdb-query.py` tool and tested it

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16065/commits/cda22094bac945e90022b5714d6c33705003ca99 | 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS  8           | local | `qactl/centos_8`|  |
| Ubuntu 22.04 |  local | `iso`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| Ubuntu 22.04        |  Generated from sources|  | 
| CentOS 8 |   |  .Generated from sources|


## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito

**Comment by BelenValdivia** [comment]
## Testing results

### Behavior before the change

<details><summary>Constraints in sys_hwinfo table</summary>

1. Install Wazuh manager `4.3.10` from sources
2. Install Wazuh agent `4.3.10` from sources
3. Install `wazuh-tools` repository
4. Check `sys_hwinfo`  table
    ```
    root@belen-VirtualBox:/home/belen/wazuh-tools/utils# python3 wdb-query.py "agent 001 sql select * from sys_hwinfo"
    [
        {
            "scan_id": 0,
            "scan_time": "2023/03/02 20:09:03",
            "board_serial": "0",
            "cpu_name": "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz",
            "cpu_cores": 2,
            "cpu_mhz": 2804,
            "ram_total": 4017660,
            "ram_free": 100552,
            "ram_usage": 98,
            "checksum": "0c8628cb0b424f1d4ea7aa489ee568631c7493b0"
        }
    ]
    ```

5. Insert negative values in cpu_cores, cpu_mhz , ram_total, ram_free and ram_usage 
    ```
    root@belen-VirtualBox:/home/belen/wazuh-tools/utils# python3 wdb-query.py "agent 00 sql INSERT INTO sys_hwinfo (scan_id, scan_time, board_serial, cpu_name, cpu_cores, cpu_mhz, ram_total, ram_free, ram_usage, checksum) VALUES (1, '2023/03/02 17:05:17', '1', '11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz', -3, -2804, -2048, -1000, -45, '4cd6ab44fd2382de9ef73a0cd744e8f01abf7503')"
    err Cannot execute SQL query
    ```
     

</details>

**Comment by BelenValdivia** [comment]
## Conclusion

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
