### ISSUE TITLE
Validate resources handles inheritance fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3986]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.6    | https://github.com/wazuh/wazuh/issues/15337 | https://github.com/wazuh/wazuh/pull/16296 |

## Description

This issue aims to validate the fix the defect on how resource handles were handled.

In order to validate this fix, we will update the agent and check how the resources are handled during the upgrade process.

## Proposed checks

<details><summary>Updatinng agent with WPK works properly</summary>

```Gherkin
Given an agent with version 4.3.x is connected to manager
When it is updated to 4.4.x version using WPK
Then the upgrade process is completed properly And resources are managed correctly
```
</details>

<details><summary>Updatinng agent with Packages works properly</summary>

```Gherkin
Given an agent with version 4.3.x is connected to manager
When it is updated to 4.4.x version using Packages
Then the upgrade process is completed properly And resources are managed correctly
```

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
