### ISSUE TITLE
Add WPK upgrade System tests support

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3987]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|  4.4.0              |   https://github.com/wazuh/wazuh/issues/16186    | No related PR   |

## Description
During different Issues related to WPK, it was found that WPK upgrading is tested through simulators and sockets, but not actual upgrading of an agent connected to a manager. The lack of proper tests causes that some of the issues detected in WPK that may fail on real usage do not cause the current IT tests to fail.

## Proposed test cases

<details><summary>Test Agent upgrade using CLI from repository</summary>

   - **Test Name:** test_upgrade_agent_cli
   - **Test Type:** System test
   - **Tier:** 1
   - **OS:** Linux, Windows
   - **Components:** Manager and Agent
   - **Modules:** modules, remoted
   - **Description:**
   ```Gherkin
   Given a manager with an Agent of a given version
   And the agent is connected and in active status
   When the agent is upgraded using the **agent_upgrade** tool using **-r** flag
   Then the upgrade is completed successfully
   ```
</details>

<details><summary>Test Agent upgrade using CLI from with custom package</summary>

   - **Test Name:** test_upgrade_agent_cli
   - **Test Type:** System test
   - **Tier:** 1
   - **OS:** Linux, Windows
   - **Components:** Manager and Agent
   - **Modules:** modules, remoted
   - **Description:**
   ```Gherkin
   Given a manager with an Agent of a given version
   And the agent is connected and in active status
   When the agent is upgraded using the **agent_upgrade** tool using **-f** flag
   Then the upgrade is completed successfully
   ```
</details>

<details><summary>Test Agent upgrade using API from repository</summary>

   - **Test Name:** test_upgrade_agent_API
   - **Test Type:** System test
   - **Tier:** 1
   - **OS:** Linux, Windows
   - **Components:** Manager and Agent
   - **Modules:** modules, remoted
   - **Description:**
   ```Gherkin
   Given a manager with an Agent of a given version
   And the agent is connected and in active status
   When the agent is upgraded using the API's **/agents/upgrade** endpoint
   Then the upgrade is completed successfully
   ```
</details>

<details><summary>Test Agent upgrade using API with custom package</summary>

   - **Test Name:** test_upgrade_agent_API
   - **Test Type:** System test
   - **Tier:** 1
   - **OS:** Linux, Windows
   - **Components:** Manager and Agent
   - **Modules:** modules, remoted
   - **Description:**
   ```Gherkin
   Given a manager with an Agent of a given version
   And the agent is connected and in active status
   When the agent is upgraded using the API's **/agents/upgrade_custom** endpoint
   Then the upgrade is completed successfully
   ```
</details>

## Considerations
This tests should be added to the automated pipeline. This will be handled in Issue https://github.com/wazuh/wazuh-qa/issues/3988

**Comment by davidjiglesias** [comment]
To be done in DTT2
