### ISSUE TITLE
Automate WPK System tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3988]
| Related issue | Related PR|
|--------------------|-----------------|
| https://github.com/wazuh/wazuh-qa/issues/3987    | No PR created yet |

## Description
This Issue aims to automate the WPK System tests developed in the related issue. 

## Status
- [ ] Research on tests to be automated
- [ ] Automation design

**Comment by davidjiglesias** [comment]
All new tests should be automated within the same issue.
