### ISSUE TITLE
Research about wazuh control options 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3995]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [wazuh control options](https://github.com/wazuh/wazuh/pull/16298) 

# Planning stage
  
  - [x] [Research the applied change](https://github.com/wazuh/wazuh-qa/issues/3995#issuecomment-1477769547).
  - [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/3995#issuecomment-1477824126).
  - [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/3995#issuecomment-1477899392).
  - [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/3995#issuecomment-1477924726).

**Comment by QU3B1M** [comment]
## Design of test scenarios and use cases
```Gherkin

Given a "<wazuh-component>" installed 
And it has an "<initial-config>" "syscollector configuration".
When an "<new-config>" "syscollector configuration" is set.
And wazuh the command "wazuh-control reload" is used.
Then "syscollector" is "<result>".

Examples:
  | wazuh-component | initial-config  | new-config  | result       |
  |-----------------|-----------------|-------------|--------------|
  | wazuh-manager   | valid           | valid       | reloaded     |
  | wazuh-manager   | valid           | invalid     | not reloaded |
  | wazuh-manager   | invalid         | valid       | reloaded     |
  | wazuh-manager   | invalid         | invalid     | not running  |
  | wazuh-agent     | valid           | valid       | reloaded     |
  | wazuh-agent     | valid           | invalid     | not reloaded |
  | wazuh-agent     | invalid         | valid       | reloaded     |
  | wazuh-agent     | invalid         | invalid     | not running  |
```

**Comment by QU3B1M** [comment]
## Evaluate the current state of testing

There is no `integration` or `system` test cases developed to cover this scenario, nor any test that uses at least the `wazuh-control reload` command

**Comment by QU3B1M** [comment]
## Identify and justify the test "tier"

The scenario is level: `integration` and tier: `2`

- Level `Integration`: We are validating only one wazuh-component at the time on the same machine where the tests is executed without the need of another system to be up.
- Tier `2`: The cases are validating the `testconfig` to be working on the reload command, it is an important feature, but not the most used.

**Comment by damarisg** [comment]
QA Planning Approved.
