### ISSUE TITLE
Automated tests for log rotation

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-qa#4]
| Working branch |
| --- |
| [log-rotation-tests](https://github.com/wazuh/wazuh-qa/tree/dev-log-rotation-tests) |

# Log rotation test

This issue is created with the purpose of developing the necessary tests to test the log rotation functionality (`monitord` and `analysisd`).

Related PR is https://github.com/wazuh/wazuh/pull/3175. This tests should be updated if the functionality changes.

## Checks [Updated 2019 July 25 ]

- [x] Check rotation by interval (in archives, alerts and ossec logs).
- [x] Check rotation by size (in archives, alerts and ossec logs).
- [x] Check rotation compression.
- [x] Check maximum logs rotation.
- [x] Check stress tests (memory leaks).

## Logs [Outdated from 2019 July 22]

- [ ] Check the daily rotation of logs and their checksums. *
- [ ] Rotate internal logs by size with the internal options available.
- [ ] Rotate alerts and archives (first day, no previous logs).
- [ ] Rotate alerts and archives (second day, having previous logs).
- [ ] Set the JSON output for every logs if possible (archives, internal logs, etc).
- [ ] Check in JSON log every alert content all default fields:
  - timestamp.
  - rules-id.
  - rule level.
  - rule group.
  - agent id.
  - agent name.
  - agent ip.
  - manager.
  - full log.
  - location.
  - manager name.
  - decoders field.
  - data.

* This functionality may change.

**Comment by DaveVG1** [comment]
## Rotation by interval (and compression)

This is a detailed explanation of how a basic rotation by interval test should work.

The configuration file will be the following:

```
  <logging>
    <log>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>15m</interval>
        <compress>yes</compress>
      </rotation>
    </log>
    <alerts>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>2h</interval>
        <compress>yes</compress>
      </rotation>
    </alerts>
    <archives>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>1d</interval>
        <compress>yes</compress>
      </rotation>
    </archives>
  </logging>
```

- [ ] Disable time synchronization.
- [ ] Set time date to sequentially trigger the log rotation.
- [ ] Check that the files are created (also check that logs are compressed)

## Rotation by size (and maximum number of logs)

This is a detailed explanation of how a basic rotation by size test should work.

The configuration file will be the following:

```
  <logging>
    <log>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <max_size>1K</max_size>
        <rotate>2</rotate>
      </rotation>
    </log>
    <alerts>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <compress>yes</compress>
        <max_size>1K</max_size>
        <rotate>4</rotate>
      </rotation>
    </alerts>
    <archives>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <max_size>1K</max_size>
        <rotate>3</rotate>
      </rotation>
    </archives>
  </logging>
```

- [ ] Inject text to the different logs to trigger the log rotation.
- [ ] Check that the files are created correctly (also check that the maximum number of rotated logs is not surpassed).

## Stress test

This test goal is to detect possible memory leaks and malfunction with a stressed configuration. The configuration will be the following:

  <logging>
    <log>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>1s</interval>
        <compress>yes</compress>
      </rotation>
    </log>
    <alerts>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>1s</interval>
        <compress>yes</compress>
        <rotate>2</rotate>
      </rotation>
    </alerts>
    <archives>
      <enabled>yes</enabled>
      <format>json,plain</format>
      <rotation>
        <enabled>yes</enabled>
        <interval>1s</interval>
        <compress>yes</compress>
      </rotation>
    </archives>
  </logging>
```

- [ ] Check stats (RAM, CPU usage).
- [ ] Check Valgrind report.

**Comment by DaveVG1** [comment]
## 2019 July 26
- I'm currently enhancing the tests developed in order to make them more efficient.
- I'm also including more parameters

**Comment by DaveVG1** [comment]
## 2019 July 29

- Finally `interval` and `size` rotation test have been developed in one single script. The mode can be adjusted by passing parameters (`-s` for selecting the size of rotation in MB and `-i` for selecting the rotation interval in seconds).
