### ISSUE TITLE
Validate Window agent's Run agent configuration Interface option works properly

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4000]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.6           |  https://github.com/wazuh/wazuh/issues/12906                      | https://github.com/wazuh/wazuh/pull/16542     |

## Description

This Issue aims to test the fix applied to the Windows Wazuh Agent. After doing the installation, when checking the  `Run agent configuration Interface` option it does not work properly and the interface is not executed.

## Proposed checks

<details><summary>Configuration Interface is opened after Installing Windows Agent</summary>

```Gherkin
Given the  Windows Agent installation is completed
When the `Run agent configuration Interface` option checkbox is enabled and `Finish` button is clicked
Then Agent's interface opens properly
```
</details>

<details><summary>Configuration Interface is opened after Upgrading Windows Agent</summary>

```Gherkin
Given the  Windows Agent upgrade to `dev branch` is completed
When the `Run agent configuration Interface` option checkbox is enabled and `Finish` button is clicked
Then Agent's interface opens properly
```
</details>

## Considerations

User Account Control Settings must be set to `always notify`.

![imagen](https://user-images.githubusercontent.com/14501079/230169473-1749f81e-48af-446b-a260-1f749a1bbdef.png)

**Comment by Deblintrake09** [comment]
# Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/pull/16542/commits/d9fc17eb75bdca9ec29084ad16e94a60fcb52ea0 | 



### Testing environment

| OS | OS version |  Deployment | Image/AMI | Notes
|-- |-- |-- |--|--|
| Centos | 8 | `Local \| Vagrant` | qactl/centos8 |


### Tested packages
|Package | Version |
|---|---|
|[Windows Agent](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.0-1.msi) | 4.3.0-1 - unfixed |
|[Windows Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.6/windows/wazuh-agent-4.6.0-0.commitd9fc17e.msi) | 4.6.0 - fixed verion |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @MarcelKemp

**Comment by Deblintrake09** [comment]
# Testing results

## Reproduce the error

<details><summary>Run agent configuration interface options work properly</summary>
</details>

**Comment by Deblintrake09** [comment]
# Conclusion :green_circle: 

Testing shows installer to be working properly.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.

**Comment by jotacarma90** [comment]
## Core review
- **Comments**: Everything seems to work correctly. :green_circle:

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
