### ISSUE TITLE
Research Review CSV and KVmap

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#4001]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Engine - Review CSV and KVmap](https://github.com/wazuh/wazuh/pull/16217) 

# Planning stage
  
  - [x] Research the applied change.
  - [x] Research if we have a test for this case.
  - [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
  - [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by roronoasins** [comment]
## Research the applied change

This PR applies changes to the KV and CSV parsers, fixing some reported issues. These changes should fix the detailed cases listed here https://github.com/wazuh/wazuh/pull/16217#issue-1586174151

**Comment by roronoasins** [comment]
## Design of test scenarios and use cases

<details><summary>Scenario 1: dsv parser - unescaping the quoting character correctly</summary>

```Gherkin
Given a manager with the engine
And the ruleset loaded
When adding a custom decoder that uses dsv parser
And using the test subcommand with an event with the expected format
Then the fields with unescaped quoting characters are collected with the right value 
```

</details>

<details><summary>Scenario Outline 2: kv parser</summary>

```Gherkin
Given a manager with the engine
And the ruleset loaded
When adding a custom decoder that uses kv parser
And using the test subcommand with an event that <action>
Then the fields with unescaped quoting characters are collected with the right value

Examples:
  |                action                |
  |--------------------------------------|
  | contains not well-balanced strings   |
  | a non-zero offset is used            |
  | contains an empty value key          |
  | converts a string to a numeric value |
```

</details>

**Comment by roronoasins** [comment]
## Evaluate the current state of testing

There are no current test that verify these cases. But they should be added to the cases that verify the HLP and Function Helpers, we could add them in https://github.com/wazuh/wazuh-qa/issues/3496

**Comment by roronoasins** [comment]
## Identify and justify the test "tier"

These cases will be added to the integration tests as tier 0 test/cases.

**Comment by roronoasins** [comment]
## Conclusion

The following issues will perform the tests listed above:

### Dev-testing

- https://github.com/wazuh/wazuh-qa/issues/4025

### Automation

- https://github.com/wazuh/wazuh-qa/issues/3496

**Comment by damarisg** [comment]
QA Planning Approved
