### ISSUE TITLE
Research about Vulnerability Detection doesn't analyze brew packages from macOS agents

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4008]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.6.0               |  https://github.com/wazuh/wazuh/issues/15805      |    https://github.com/wazuh/wazuh/pull/16089                |

## Description

The syscollector module could not retrieve homebrew/brew vendors. For this reason, all brew packages show a space  " "  in the vendor field in the packages,  this affects the Vulnerability Detection report.

# Development stage

- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

<details><summary>Scenario Outline 1: Check that the package installed with homebrew is properly analyzed by Vulnerability detector.</summary>

  ```Gherkin
  Given I Install the Wazuh agent "<version>" in a MacOs
  And   I Install the Wazuh manager "<version>" 
  When I  install the "<package>" with homebrew
  Then the installed package is in sys_programs db table
  And  the name of the package no longer has the version inside
  And   the package is properly analyzed by vulnerability detector
  
      Examples:
    |  version           | package              |
    | -------------------|  ------------------- |
    |  4.6               |  python              |
    |  4.6               |  PostgreSQL          |
    |  4.6               |  openssl             |
    |  4.6               |  ncourses            |
  
  ```

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing
- The scenario outline is covered by he NVD test cases https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_vulnerability_detector

**Comment by BelenValdivia** [comment]
###  Identify and justify the test "tier"

| Test | Tier | Justification|
|--------------------|--------------------|-----------------|
|    Check that the package installed with homebrew is properly analyzed by Vulnerability detector.    |  0    |  Test how the packages installed are properly analyzed by vulnerability detector with NVD feeds   |

**Comment by BelenValdivia** [comment]
### Conclusion
- Added issue

**Comment by damarisg** [comment]
QA Planning Approved.
