### ISSUE TITLE
Validate Vulnerability Detection doesn't analyze brew packages from macOS agents

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4017]
| Target version | Related issue | Related PR | Test planning |
|--------------------|--------------------|-----------------|-----------------|
|     4.6                   |     https://github.com/wazuh/wazuh/issues/15805            |    https://github.com/wazuh/wazuh/pull/16089              | https://github.com/wazuh/wazuh-qa/issues/4008 |

## Description

This issue aims to fix that the syscollector module could not retrieve homebrew/brew vendors.

- The brew packages in macOS won't be reported with a @ in their name
- Vulnerability detector will always trim the name section of the package with @ for macOS

## Proposed checks

- Test that packages installed are analyzed by Vulnerability detector

  <details><summary>Scenario Outline 1: Check that the package installed with homebrew is properly analyzed by Vulnerability detector.</summary>
  
    ```Gherkin
    Given I Install the Wazuh agent "<version>" in a MacOs
    And   I Install the Wazuh manager "<version>" 
    When I  install the "<package>" with homebrew
    And active the Vulnerability detector module with NVD enabled in the manager configuration
    Then the installed package is in sys_programs db table
    And  the name of the package no longer has the version inside
    And   the package is properly analyzed by vulnerability detector
    
        Examples:
      |  version           | package              |
      | -------------------|  ------------------- |    
      |  4.6               |  PostgreSQL          |
      |  4.6               |  openssl             |
      |  4.6               |  python              |
    
    ```
</detail>

**Comment by BelenValdivia** [comment]
23/3/2023
- Installed wazuh manager on Ubuntu
- Installed wazuh agent on macOS mojave
- Installed homebrew
- Installed openssl
- Reproduced the behavior before change

**Comment by BelenValdivia** [comment]
27/03/2023
- Tested upgrade
- Package name without @
- No vulnerabilities detected 
- Ask octa to generate a wazuh manager package

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16089/commits/22d1a03b573dc2f57633029ca5efdebea1878365| 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS  8           | local | `qactl/centos_8`|  |
| Windows  Server 2019|  local | `qactl/windows_2019`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| Ubuntu           |  [deb](https://packages-dev.wazuh.com/warehouse/test/4.6/deb/var/wazuh-manager_4.6.0-2803.vd_amd64.deb)|  | 
| macOS  Mojave|   | [ pkg](https://packages-dev.wazuh.com/trash/macos/wazuh-agent-4.6.0-0.0.0.todelete.pkg) |


## Status

- [x] In progress
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito

**Comment by BelenValdivia** [comment]
## Conclusion 🟢

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
