### ISSUE TITLE
Research about Wazuh Integratord's group option

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#4019]
# Description

The objective of this issue is to investigate and design a testing plan for adding coverage to the group option of Integratord.

# Planning stage

- [ ]  Research on new changes made
- [ ]  Design of test scenarios and use cases
- [ ]  Evaluate the current state of testing
- [ ]  Identify and justify the test "tier"
- [ ]  Conclusion - Open issues in relation to the designed planning

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
