### ISSUE TITLE
Fix `agentd` Integration tests

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4031]
| Target version |
|--------------------|
| 4.5.0 |

## Description

The `agentd` Integration tests checks are failing in several `4.5.0` PRs ([example](https://github.com/wazuh/wazuh/pull/15661/checks?check_run_id=12093950576)), the test execution keeps running for hours after failing until jenkins kills it. After an local execution it seems that it is an issue on the IT itself.

When we run a [full tests execution](https://github.com/wazuh/wazuh/files/11004235/report_agentd.zip) all the cases from the `test_agentd/test_agentd_reconnection.py` file are failing. If those tests are [executed isolated](https://github.com/wazuh/wazuh/files/11004239/report_agentd1.zip), all the cases are now passing correctly. It is probably a test that is not doing the `cleanup` or `setup` correctly.

**Comment by QU3B1M** [comment]
## Update 02/05/2023

After several executions, the error could not be reproduced.

| Test path      | Platform | OS       | Result                                    |
|----------------|----------|----------|-----------------------------------------------|
| `test_agentd/` | Jenkins  | Centos   | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/38063/) |
| `test_agentd/` | Jenkins  | Ubuntu   | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/38064/) |
| `test_agentd/` | Jenkins  | Windows | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/38065/) |

**Comment by damarisg** [comment]
Closed because it cannot be reproduced.
