### ISSUE TITLE
Add coverage for race conditions in `wazuh-analysisd`

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4033]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.5.0 | wazuh/wazuh#14099  | wazuh/wazuh#16101|

## Description

This issue aims to develop automated tests to validate the race conditions detected by `Thread Sanitizer` in the module `wazuh-analysisd` are not being raised. To validate Thread Sanitized it is needed to re-build the `wazuh-module` to validate, in this case `analysisd`. 

## Configurations

Before start testing it is needed to configure Thread Sanitized :

1. Stop `wazuh-analysisd`
    ```bash
    kill -9 $(pidof wazuh-analysisd)
    ```
2. Add `-fsanitize=thread` to `AR_LDFLAGS` `OSSEC_LDFLAGS` `OSSEC_CFLAGS` flags in `Makefile`
3. Build `wazuh-master` with `DEBUG=1`
4. Copy and paste the recently compiled `wazuh-analysisd` binary file to `/var/ossec/bin`
5. Start `wazuh-analysisd`
    ```bash
    wazuh-analysisd -f -u root
    ```

## Proposed test cases

- <details><summary>Scenario Outline: Analysisd race condition when handling rule ignore option</summary>

  ```Gherkin
  Given a wazuh-manager freshly started with Thread Sanitizer enabled on analisysd module.
  When a rule with the ignore option is "<rule_action>".
  Then Thread Sanitizer does not find any race condition.
  
  Examples: 
  
      | rule_action                    |
      |--------------------------------|
      | Trigered one time              |
      | Not trigered                   |
      | Slowly trigered multiple times |
      | Quickly trigered multiple times|
  ```
</details>

## Considerations

Example rule with the options needed to execute the tests:

```xml
  <rule id="100222" level="5" frequency="3" timeframe="120" ignore="10">
    <if_matched_sid>5716</if_matched_sid>
    <match>^Failed|^error: PAM: Authentication</match>
    <description>sshd: authentication failed.</description>
    <mitre>
      <id>T1110</id>
    </mitre>
   <group>authentication_failed,gdpr_IV_35.7.d,gdpr_IV_32.2,gpg13_7.1,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,pci_dss_10.2.4,pci_dss_10.2.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
   </rule>
```

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
