### ISSUE TITLE
Validate wazuh-control reload option

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4034]
| Target version | Related issue     | Related PR       |
|--------------- |-------------------|------------------|
| 4.5.0          | wazuh/wazuh#15577 | wazuh/wazuh#16298|

## Description

This issue aims to validate that `testconfig` is added to the wazuh-control `reload` option, so when an invalid `syscollector` configuration is set on an already running agent and it is _reloaded_ using `wazuh-control reload` it wont load the invalid config and keeps working with the previous one.    

## Proposed checks

- <details><summary>Scenario Outline: wazuh-control reload uses <code>testconfig</code>.</summary>

    > The scenario is executed on isolated `manager` and `agent`, as the validation is done on the component itself, it does not affect other connected component.  

    ```Gherkin

    Given a "<wazuh-component>" installed 
    And it has an "<initial-config>" "syscollector configuration".
    When an "<new-config>" "syscollector configuration" is set.
    And wazuh the command "wazuh-control reload" is used.
    Then "syscollector" is "<result>".

    Examples:
    | wazuh-component | initial-config  | new-config  | result       |
    |-----------------|-----------------|-------------|--------------|
    | wazuh-manager   | valid           | valid       | reloaded     |
    | wazuh-manager   | valid           | invalid     | not reloaded |
    | wazuh-manager   | invalid         | valid       | reloaded     |
    | wazuh-manager   | invalid         | invalid     | not running  |
    | wazuh-agent     | valid           | valid       | reloaded     |
    | wazuh-agent     | valid           | invalid     | not reloaded |
    | wazuh-agent     | invalid         | valid       | reloaded     |
    | wazuh-agent     | invalid         | invalid     | not running  |
    ```
</details>

## Configuration and considerations

It will test with 
- a manager default and agent with each row.
- an agent default and manager with each row.

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [`1803b0b`](https://github.com/wazuh/wazuh/pull/16298/commits/1803b0b7065efc5ad9cfbb8cf9c925ac4865b9ec)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commit1803b0b_amd64.deb)|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-agent_4.5.0-0.commit1803b0b_amd64.deb)|       

### Status

- [x] In progress @QU3B1M 
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @TomasTurina

**Comment by QU3B1M** [comment]
# Conclusion :green_circle: 

[Test execution](https://github.com/wazuh/wazuh-qa/issues/4034#issuecomment-1480546384) successful :rocket: The `syscollector` module is not being reloaded after applying invalid values on a previously valid configuration when the `wazuh-control reload` command is used.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
