### ISSUE TITLE
Research about configuration setting via API

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4046]
## Description

The objective of this issue is to investigate and design a testing plan for the development issue  https://github.com/wazuh/wazuh/issues/16419

### Planning stage

- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/4046#issuecomment-1481237784) 
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4046#issuecomment-1481269963) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4046#issuecomment-1481274587) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4046#issuecomment-1481285852) 
- [x] [Conclusion](https://github.com/wazuh/wazuh-qa/issues/4046#issuecomment-1481289814)

**Comment by juliamagan** [comment]
## Research on new changes made

This PR fixes the API `upload_configuration > limits > eps` configuration so it prevents users from uploading `ossec.conf` files containing `<limits><eps>` block inside [global](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#reference-ossec-global) tag when disabled in the `api.yaml`:

```yaml
 # Uploadable Wazuh configuration sections 
 # upload_configuration: 
 #   remote_commands: 
 #     localfile: 
 #       allow: yes 
 #       exceptions: [] 
 #     wodle_command: 
 #       allow: yes 
 #       exceptions: [] 
 #   limits: 
 #     eps: 
 #       allow: yes 
```

Regex is now used to match `<limit><eps>` anywhere in `ossec.conf` uploaded by a user from the API, regardless of whether it is in a different `<ossec_config>` block and without breaking the current behavior of the endpoint.

**Comment by juliamagan** [comment]
## Design of test scenarios and use cases

- Test upload configuration:

  <details>
  <summary>Upload configuration with one <code>ossec_config</code> block</summary>
  <br>

  **Given** one configuration file with one `ossec_config` block
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly


  </details>

  <details>
  <summary>Upload configuration with two <code>ossec_config</code> block (default ossec.conf)</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly

  </details>

- Test upload `limit_eps` configuration:

  <details>
  <summary>Upload configuration with <code>limit_eps</code> in one <code>ossec_config</code> block - Not allowed</summary>
  <br>

  **Given** one configuration file with one `ossec_config` block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change


  </details>

  <details>
  <summary>Upload configuration with <code>limit_eps</code> in one <code>ossec_config</code> block - Allowed</summary>
  <br>

  **Given** one configuration file with one `ossec_config` block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>

  <details>
  <summary>Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the first block - Not allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the first block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change

  </details>

  <details>
  <summary>Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the first block - Allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the first block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>

  <details>
  <summary>Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the second block - Not allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the second block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change

  </details>

  <details>
  <summary>Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the second block - Allowed</summary>
  <br>

    **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the second block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>

**Comment by juliamagan** [comment]
## Evaluate the current state of testing

None of the above cases are implemented in any integration, system or E2E test.

**Comment by juliamagan** [comment]
## Identify and justify the test "tier"

|Test|Tier|Justification|
|--|--|--|
|Test upload configuration|Tier 0|This test checks that the configuration is set correctly in the manager via the API, which is the basic functionality of the `PUT /manager/configuration/` API endpoint
|Test upload `limit_eps` configuration|Tier 0|This test checks that the `limit_eps` configuration is set correctly in the manager through the API, according to the permissions you have, which is the basic functionality of the `PUT /manager/configuration/` endpoint of the API

**Comment by juliamagan** [comment]
## Conclusion

In conclusion, the following issues have been created for manual testing, and for the development of automated tests for these cases in the future:

**Comment by jmv74211** [comment]
QA planning approved 👍🏼
