### ISSUE TITLE
Performance testing of AIX Manager v4.3.10 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4052]
| Wazuh automation Issue |
| --- |
| https://github.com/wazuh/wazuh-automation/issues/1102 | 

We want to perform performance tests that allow us to know how Wazuh behaves under certain load scenarios for the proposed modules and the possible limits they may have. For this purpose, we are going to use developed scripts https://github.com/wazuh/wazuh-qa/issues/4144 to check the performance of the environment.

### Conclusion :red_circle: 

Analyzing the results we can conclude that the performance problem reported on https://github.com/wazuh/wazuh/issues/16099 is still present for AIX local v4.3.11:

- **Logcollector** consistently misses events in environments with more than 200 events per second. The warning `WARNING: Socket busy, discarding message` is still present in the manager. This condition does not occur for other operating systems with fewer resources. In the case of the Ubuntu manager, it reaches approximately 1000 events per second.
- **Sycheck** does not lose events due to the new methodology of waiting until the end of the scan. However we can still see that it only reaches 100 events per second. This limit seems to apply also for the rest of the operative system

**Comment by Rebits** [comment]
## Preliminary analysis

In order to meet the new requirements, it is necessary to adapt the performance and footprint tools developed in https://github.com/wazuh/wazuh-qa/issues/3680. 

While, the development of these tools is in progress, a preliminary analysis has been conducted avoiding the use of the framework

***

### Fluentd Logcollector events

We performed basic testing to determine the maximum number of events per second that the AIX/fluentd environment can handle. For this, we used a basic configuration that forwarded events from only one file.

Our findings suggest that no events are lost if the EPS is lower than 200. However, increasing this number may lead to events being lost and errors being triggered in the environment, as shown below:

```
2023/04/25 03:20:50 wazuh-logcollector[4915222] mq_op.c:218 at SendMSGtoSCK(): ERROR: Cannot send message to socket 'fluent_socket'. (Retry)
```

The exact number of events lost is not precise, but based on our tests, we estimate that approximately 400 events were lost in the 10-second testing scenario with 200 events per second.


***

**Comment by Rebits** [comment]
## POWER9 - Performance and Footprint testing


<details>  

<summary> Environment </summary>

<br>

| Hostname | OS | Version | CPU | Memory | Installation type | Version
|---- |----|----|----|----|---- |----|
| Host1 |POWER9| 7.1 |0.25 | 1024 | Local | `4.3.11` |
| Host2 |POWER9| 7.1 | 2 | 8192 | Local | `4.3.11` |
| Host3 |Ubuntu| 7.1 | 2 | 2048 | Manager | `4.3.11` |


> **Note**
> Further information about AIX manager installation in the [functional testing issue](https://github.com/wazuh/wazuh-qa/issues/4053)


</details>


<details>

<summary> Methodology  </summary>

<blockquote>


<details>

<summary> Tests cases </summary>


### Basic

- 100 Logcollector Events Per Second
- 300 Logcollector Events Per Second
- 500 Logcollector Events Per Second
- 500 Syscheck Events Per Interval
- 1000 Syscheck Events Per Interval
- 100 Logcollector Events Per Second and Syscheck 500 Events Per Interval
- 300 Logcollector Events Per Second and 1000 Syscheck Events Per Interval


### High load

- 1000 Logcollector Events Per Second
- 50000 Logcollector Events Per Second
- 5000 Syscheck Events Per Interval
- 50000 Logcollector Events Per Second and 5000 Syscheck Events Per Interval
- 7000 Logcollector Events Per Second and 5000 Syscheck Events Per Interval

### Complex events

- 30 Complex Logcollector Events Per Second
- 100 Complex Logcollector Events Per Second
- 200 Complex Logcollector Events Per Second
- 100 Complex Syscheck Update Alerts Per Second
- 300 Complex Syscheck Update Alerts Per Second

</details>


<details>

<summary> Data collection</summary>

All the data will be obtained in the different environments using tools defined in https://github.com/wazuh/wazuh-qa/issues/4144. For each tests case it would be necessary:

- Disable all modules except the object of the testing. Also, disable the default configuration that could alter the results.
- Restart the manager with the test case configuration.
- Launch the testing case defined in the JSON file.

The gathered data will be accessible in this comment compressed in a zip file.
Also, the manager logs will be also monitored, in order to get more information about the current state of the environment


</details>


<details>

<summary> Data analysis</summary>

Once the data is collected we will perform an analysis in which we will try to determine:
  - Determine the number of missed alerts in the proposed scenarios.
  - Determine the number of alerts missed in the proposed scenarios.
  - Determine the maximum number of events per second that the environments can support 
  - Review the footprint of the environment.
  - Review any anomalies in the data being reviewed.
  - Inform if any error or warning appears in the manager logs.


</details>


</blockquote>



</details>


<details>

<summary> Tests cases execution  </summary>

<blockquote>


</details>


</blockquote>


</details>


<details>

<summary> Performance</summary>


## General conclusions 

Analyzing the results of the different cases on the different hosts, we can conclude that the performance problem reported on https://github.com/wazuh/wazuh/issues/16099 is still present for AIX local v4.3.11:
- **Logcollector** consistently misses events in environments with more than 200 events per second, with small event sizes. The warning `WARNING: Socket busy, discarding message` is still present in the manager. This condition does not occur for other operating systems with fewer resources. In the case of the Ubuntu manager, it reaches approximately 1000 events per second.
- **Sycheck** does not lose events due to the new methodology of waiting until the end of the scan. However we can still see that it only reaches 100 events per second. This limit seems to apply also for the rest of the operative system


![500EPSAlerts](https://github.com/wazuh/wazuh-qa/assets/11089305/8ec9d995-8d6f-4cec-898c-a152f8a4ac15)
> Global comparative for the 500 Logcollector events per second for the three hosts


  
![5000EPIAlerts](https://github.com/wazuh/wazuh-qa/assets/11089305/6f8ae3e4-0810-4e58-a6b2-706179c39b1f)
> Global comparative for the 5000 Syscheck events per second for the three hosts


</details>


<details>

<summary> Footprint</summary>


The psutil library only supports CPU, VMS, and RSS metrics for the AIX systems. The rest of the metrics will not be considered for this analysis


## Logcollector

<details>

<summary>CPU  </summary>

 The CPU usage of the logcollector daemon has been less than 1% during all the testing cases.

![wazuh_logcollector_cpu](https://github.com/wazuh/wazuh-qa/assets/11089305/59418583-ced1-430a-933f-d366464f8214)
> Logcollector CPU usage for the 500 Logcollector EPS case (Host2)

</details>

<details>

<summary> VMS </summary>

Nothing anomalous was detected

![wazuh_logcollector_vms](https://github.com/wazuh/wazuh-qa/assets/11089305/b9923d5d-52d8-4ca0-a13d-6896e5066a5b)
> Logcollector VMS usage for the 500 Logcollector EPS  (Host2)

</details>

<details>

<summary> RSS </summary>

- **RSS**: Nothing anomalous was detected 500 Logcollector EPS  (Host2)

![wazuh_logcollector_rss](https://github.com/wazuh/wazuh-qa/assets/11089305/f4a4a217-19ac-47ca-92a1-344a9397b055)
> Logcollector RSS usage for the 500 Logcollector EPS  (Host2)

</details>


## Syscheck


<details>

<summary> CPU </summary>

The impact on the CPU of the syscheck is insignificant. It is concentrated, as expected, during the scans

![wazuh_syscheckd_cpu](https://github.com/wazuh/wazuh-qa/assets/11089305/99264055-1c41-46c8-9dd5-2ebeea132fb5)
> Syscheck CPU usage for the 5000 Syscheck Events per interval (Host2)

</details>


<details>

<summary> VMS </summary>

Nothing anomalous was detected

![wazuh_syscheckd_vms](https://github.com/wazuh/wazuh-qa/assets/11089305/f178f960-2eb4-4980-8649-76a59fd96171)
> Syscheck CPU usage for the 5000 Syscheck Events per interval (Host2)

</details>

<details>

<summary> RSS  </summary>

Nothing anomalous was detected

![wazuh_syscheckd_rss](https://github.com/wazuh/wazuh-qa/assets/11089305/f864e065-e581-432e-97ce-d9c185d0f1c6)
> Syscheck CPU usage for the 5000 Syscheck Events per interval (Host2)



</details>


## Analysisd

<details>

<summary> CPU </summary>

Analysisd impact over the CPU is insignificant for all the logcollector and syscheck cases (less than 5%). This is expected due to the limited number of alerts per second processed (check logcollector and syscheck limitations in the performance section)


![wazuh_analysisd_cpu](https://github.com/wazuh/wazuh-qa/assets/11089305/addf4924-1b22-43f7-8a3f-2d2ac418a433)
> Analysid CPU usage for the 7000 Syscheck EPI and 5000 Logcollector EPI



</details>


<details>

<summary> RSS  </summary>

Nothing anomalous was detected

![wazuh_analysisd_rss](https://github.com/wazuh/wazuh-qa/assets/11089305/355a2779-c1a6-4ea3-bbb2-2587314efa81)
> Analysid RSS usage for the 7000 Syscheck EPI and 5000 Logcollector EPI




</details>


<details>

<summary> VMS  </summary>


Nothing anomalous was detected

![wazuh_analysisd_vms](https://github.com/wazuh/wazuh-qa/assets/11089305/e32830d8-b92b-402c-abcf-8460711b24e3)
> Analysid RSS usage for the 7000 Syscheck EPI and 5000 Logcollector EPI


</details>




</details>

**Comment by davidjiglesias** [comment]
LGTM!
