### ISSUE TITLE
Footprint testing of AIX Manager v4.3.10

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4054]
| Wazuh automation Issue |
| --- |
| - | 

We want to measure the footprint of the use of wazuh for the log data collection and file integrity monitoring modules.

Therefore, for each of the test cases proposed in the performance tests [wazuh-qa#3679](https://github.com/wazuh/wazuh-qa/issues/4052), a study of CPU usage, memory usage, disk usage, and file descriptors used by each of the Wazuh processes will be carried out.

### Conclusion :green_circle: 

Nothing anomalous was detected. Footprint analysis was performed along with the performance testing: https://github.com/wazuh/wazuh-qa/issues/4052#issuecomment-1554770718

**Comment by juliamagan** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
