### ISSUE TITLE
Create a integrity synchronization test

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#406]
## Description

We need to write a new test to check how fast is the integrity synchronization. The steps for the test are the following:
- Base case:
  - Starting with a fresh manager installation
  - Add in the default agent group configuration a syscheck block with the attribute `check_all="no"` to every default directory in the agent config. This is to prevent the agent from generating any kind of event.
  - Create a new directory `/testdir` with a high number of files (must be set at will).
  - Wait for the agent_start alert in `alerts.json`. (Agent get restarted after applying the new configuration)
  - Stop both agent and manager (from manager side, i.e. via API request). Delete agent database in the manager side. Launch again both agent and manager.
  - Query the `n_attempts` and `n_completions` fields until `last_completion` value changes from 0 to 1. Save both number of attempts and total time.
- 'All' case:
  - Stop both agent and manager
  - Write a `0` value in `n_attempts` and `n_completions`
  - Alter the `fim_entry.checksum` column for all rows in the table to force the integrity.
  - Launch again both agent and manager.
  - Query the `n_attempts` and `n_completions` fields until `n_completions` value changes from 0 to 1. Save both number of attempts and total time.
- 'One' case:
  - Stop both agent and manager
  - Write a `0` value in `n_attempts` and `n_completions`
  - Alter the `fim_entry.checksum` column for one row in the table to force the integrity.
  - Launch again both agent and manager.
  - Query the `n_attempts` and `n_completions` fields until `n_completions` value changes from 0 to 1. Save both number of attempts and total time.

Database fields may be found in [this file](https://github.com/wazuh/wazuh/blob/3319-fim-rework/src/wazuh_db/schema_agents.sql).

**Comment by AdriiiPRodri** [comment]
Hi team,

**We abandon issue #308 in favor of this issue (#406).**

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We've finished the test to get stats from Wazuh. We can configure the daemons to be monitored, as well as launch the test with any number of agents, these will be detected automatically. **A blocking mechanism guarantees the processes don't interfere with each other**.

Each test has three cases with its corresponding configuration, **18 (2 state files, 1 agents info file and N stats files, where N is the number of daemons)** files will be generated, this amount **will depend** on the number of daemons we monitor, also depends on the number of .state files of Wazuh (**currently 2, analysisd and remoted**).

## Examples (Case 0, TCP, 5000 eps, 5000 files, buffer disabled no)
### Stats file
```csv
seconds,cpu,ram,avg_disk_read,avg_disk_write,total_disk_read,total_disk_write
1581066760.1083367,0.4,23008,1.27,0.86,,
1581066761.392868,0.4,23008,1.27,0.86,,
1581066762.6241157,0.4,23008,1.27,0.86,,
1581066763.860178,0.4,23008,1.27,0.86,,
1581066765.1008375,0.4,23008,1.27,0.86,,
1581066766.329428,0.4,23008,1.27,0.86,,
1581066767.5636451,0.4,23008,1.27,0.86,,
1581066768.801169,0.4,23008,1.27,0.86,,
1581066770.0350432,0.4,23008,1.27,0.86,,
1581066771.1731076,0.4,23004,0.86,1.27,2708.0,4032.0
```

### Agent info file
```csv
agent_id,n_attempts,n_completions,start_time,end_time,total_time
002,2,1,1581066759.7983203,1581066770.985572,11.18725299835205
```

### Analysisd state file
```csv
syscheck_events_decoded,syscheck_edps,dbsync_queue_usage,dbsync_messages_dispatched,dbsync_mdps,events_received,events_dropped,syscheck_queue_usage,event_queue_usage
0,0,0.00,0,0,13,0,0.00,0.00
2,0,0.00,1412,282,1414,0,0.00,0.00
0,0,0.00,2255,451,2255,0,0.00,0.00
```

### Remoted state file
```csv
queue_size,tcp_sessions,evt_count,discarded_count,recv_bytes
0,0,114737,0,34957516
0,0,115924,0,35405530
0,0,118227,0,36276330
```
