### ISSUE TITLE
Research about agent starts with an invalid fim configuration

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4063]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: wazuh/wazuh#16268

# Planning stage
  
  - [x] [Research the applied change](https://github.com/wazuh/wazuh-qa/issues/4063#issuecomment-1492085887).
  - [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4063#issuecomment-1494451177).
  - [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4063#issuecomment-1494459739).
  - [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4063#issuecomment-1494469980).

**Comment by QU3B1M** [comment]
## Research the applied change

It fixes a bug where a Windows `wazuh-agent` with an invalid `FIM` configuration starts anyway after raising the error message, also the error messages were updated and now the behavior is the same on any OS

**Comment by QU3B1M** [comment]
## Design of test scenarios and use cases

#### Scenario Outline - wazuh-agent with invalid FIM configuration will not start

```Gherkin

Given a "<OS>" "wazuh-agent" installed and stopped. 
And it has an "<fim-config>" "FIM" configuration.
When trying to start "wazuh-agent".
Then "wazuh-agent" is "<result>".

Examples:
| OS              | fim-config      | result       |
|-----------------|-----------------|--------------|
| Ubuntu          | valid           | started      |
| Ubuntu          | invalid         | not started  |
| Windows         | valid           | started      |
| Windows         | invalid         | not started  |
| MacOS           | valid           | started      |
| MacOS           | invalid         | not started  |
```

**Comment by QU3B1M** [comment]
## Evaluate the current state of testing

There are no automated tests developed for this cases, the invalid_configuration cases must be added to `tests/integration/test_fim`

**Comment by QU3B1M** [comment]
## Identify and justify the test "tier"

The scenario is level: `integration` as we are validating only one wazuh-component at the time on the same machine where the tests is executed without the need of another system to be up.


| Test                     | Tier    | Justification     |
|--------------------------|---------|-------------------|
|invalid_fim_configuration | 1       | It is important to validate a `wazuh-agent` with invalid FIM configuration is not starting anyway. |

**Comment by QU3B1M** [comment]
# Conclusion 

The following issues were created to handle the manual test and test development:
- #4067
- #4068

**Comment by damarisg** [comment]
QA Planning Approved.
