### ISSUE TITLE
Research about OS version is not properly parsed for Alpine Linux system 

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4066]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|          4.5.0            |   https://github.com/wazuh/wazuh/issues/15697                |     https://github.com/wazuh/wazuh/pull/16056              |

## Description

Enhance the detection on Alpine Linux, os_version, os_name, and os_platform. Linux Alpine distribution information is in files `/etc/os-release`  and  `/etc/alpine-release`

# Development stage

- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made
Enhance the detection on Alpine Linux, os_version, os_name, and os_platform. Linux Alpine distribution information is in files "/etc/os-release" and "/etc/alpine-release"

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing

**Comment by BelenValdivia** [comment]
### Identify and justify the test "tier"

**Comment by BelenValdivia** [comment]
### Conclusion - Open issues in relation to the designed planning

**Comment by damarisg** [comment]
QA Planning approved.
