### ISSUE TITLE
Add coverage to agent does not start with an invalid `FIM` configuration

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4068]
| Target version | Related issue     | Related PR        |
|----------------|-------------------|-------------------|
|  4.5.0         | wazuh/wazuh#15576 | wazuh/wazuh#16268 |

## Description

This issue aims to validate `wazuh-agent` with an invalid `FIM` configuration must not start and should raise an error message. It is also needed to validate the error messages have the same behavior on any OS.

## Proposed test cases

- <details><summary>Scenario Outline - Tier 1 - wazuh-agent with invalid FIM configuration will not start</summary>

  ```Gherkin
  Given a "<OS>" "wazuh-agent" installed and stopped. 
  And it has an "<fim-config>" "FIM" configuration.
  When trying to start "wazuh-agent".
  Then "wazuh-agent" is "<result>".

  Examples:
    | OS              | fim-config      | result       |
    |-----------------|-----------------|--------------|
    | Ubuntu          | valid           | started      |
    | Ubuntu          | invalid         | not started  |
    | Windows         | valid           | started      |
    | Windows         | invalid         | not started  |
    | MacOS           | valid           | started      |
    | MacOS           | invalid         | not started  |
    | Solaris         | valid           | started      |
    | Solaris         | invalid         | not started  |
  ```
</details>

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
