### ISSUE TITLE
Research MAC Address reported with extra character at end

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4069]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|          4.4           | https://github.com/wazuh/wazuh/issues/16500             |  https://github.com/wazuh/wazuh/pull/16517         |

## Description

This issue aims to resolve a problem in which the MAC address reported on Windows systems includes a ":" character at the end of the MAC address. This issue is caused by using MAC_ADDRESS_MAX_LENGTH instead of physicalAddressLen in the code.

# Development stage

- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made
This issue addresses the problem where the MAC address reported on Windows systems includes a ":" character at the end of the MAC address. This issue is caused by using MAC_ADDRESS_MAX_LENGTH (30 is the previous value).
This change aims to modify the code to use physicalAddressLen instead of MAC_ADDRESS_MAX_LENGTH with an invalid number to report the MAC address correctly.

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

- Test that MAC address doesn't have a colon at the end in sys_netiface table
  ```Gherkin
    Given I Install the Wazuh agent in a Windows VM
    And   I Install the Wazuh manager 
    When I  go to sys_netiface table in the database
    Then The MAC Address doesn't have a colon at the end

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing

- Syscollector tests ti check default events is being deleveloped[ here ](https://github.com/wazuh/wazuh-qa/pull/3584)
tests/integration/test_syscollector/data/test_cases/case_test_default_values.yaml

**Comment by BelenValdivia** [comment]
### Identify and justify the test "tier"
| Test | Tier | Justification|
|--------------------|--------------------|-----------------|
|      Test that mac address is in the inventory     |  0    |  Test how the Syscollector module is able to scan and collect information about installed packages    |

**Comment by BelenValdivia** [comment]
### Conclusion

**Comment by damarisg** [comment]
QA Planning Approved.
