### ISSUE TITLE
Validate MAC Address is not reported with extra character at end

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4072]
| Target version | Related issue | Related PR/dev branch |  Related QA Planning |
|--------------------|--------------------|-----------------|-----------------|
|    4.4                   |   https://github.com/wazuh/wazuh/issues/16500         |    https://github.com/wazuh/wazuh/pull/16517                | https://github.com/wazuh/wazuh-qa/issues/4069  |

## Description

This issue aims to resolve a problem in which the MAC address reported on Windows systems includes a ":" character at the end of the MAC address. This issue is caused by using MAC_ADDRESS_MAX_LENGTH instead of physicalAddressLen in the code.

## Proposed checks
- Test that MAC address doesn't have a colon at the end in sys_netiface table
  ```Gherkin
    Given I Install the Wazuh agent in a Windows VM
    And   I Install the Wazuh manager 
    When I  go to sys_netiface table in the database
    Then The MAC Address doesn't have a colon at the end

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/16517/commits/a34782a4143b0cd0098d3d3da2280a127e820130  | 

### Testing environment
| OS                  | Deployment | Image/AMI | Notes             |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS          | local | `generic/centos8`|  |
| Windows |  local | `qactl/windows_2019`|  |


### Tested packages

| System                  | Manager | Agent | 
| ------------------- | ---------- | ---------- |
| Centos|  [rpm](http://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.1-0404.macsemicolon.x86_64.rpm)|  | 
| Windows|   | [ msi](https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.1-0404.macsemicolon.msi) |


## Status

- [x] In progress
- [ ] QA team leader approved @damarisg 
- [ ] Development team leader approved @Dwordcito

**Comment by BelenValdivia** [comment]
## Testing results

### Behavior before the change
<details><summary>MAC address has a colon at the end</summary>

1. Install Wazuh manager
2. Install Wazuh agent
3. Check MAC address in sys_netiface table in the database

    ```
    sqlite> select * from sys_netiface;
    0|2023/04/03 19:50:57|Ethernet|Intel(R) PRO/1000 MT Desktop Adapter|ethernet|up|1500|08:00:27:ff:02:24:|3068|15271|700787|20364907|0|0|0|0|c10d4d9041b2f093f05
    6c90f5b10aa2144827284|393761de7b836bca07df3a350db5136606950549
    0|2023/04/03 19:50:57|Loopback Pseudo-Interface 1|Software Loopback Interface 1| |up||00:00:00:00:00:00|0|0|0|0|0|0|0|0|e4a92faeea2613dab29a772ec7f3540be951b4
    78|56e07d1bb3aeca5febd3a26616defa115f6a881b
    0|2023/04/03 19:50:57|Ethernet 2|Intel(R) PRO/1000 MT Desktop Adapter #2|ethernet|up|1500|08:00:27:82:9b:1c:|396|438|27823|430315|0|0|0|0|396a63d27074ccaf039e
    3bb2f963637c25cc0c04|b6add5e98952c1216b6e189197de17c6962ccc74
    ```

</details>

**Comment by BelenValdivia** [comment]
## Testing results

### Behavior before the change
<details><summary>MAC address has a colon at the end</summary>

1. Install Wazuh manager
2. Install Wazuh agent
3. Check MAC address in sys_netiface table in the database

    ```
    sqlite> select * from sys_netiface;
    0|2023/04/03 19:50:57|Ethernet|Intel(R) PRO/1000 MT Desktop Adapter|ethernet|up|1500|08:00:27:ff:02:24:|3068|15271|700787|20364907|0|0|0|0|c10d4d9041b2f093f05
    6c90f5b10aa2144827284|393761de7b836bca07df3a350db5136606950549
    0|2023/04/03 19:50:57|Loopback Pseudo-Interface 1|Software Loopback Interface 1| |up||00:00:00:00:00:00|0|0|0|0|0|0|0|0|e4a92faeea2613dab29a772ec7f3540be951b4
    78|56e07d1bb3aeca5febd3a26616defa115f6a881b
    0|2023/04/03 19:50:57|Ethernet 2|Intel(R) PRO/1000 MT Desktop Adapter #2|ethernet|up|1500|08:00:27:82:9b:1c:|396|438|27823|430315|0|0|0|0|396a63d27074ccaf039e
    3bb2f963637c25cc0c04|b6add5e98952c1216b6e189197de17c6962ccc74
    ```

</details>

**Comment by BelenValdivia** [comment]
## Conclusion 🟢 

The behavior is as expected. The MAC address doesn't have a colon at the end.

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
