### ISSUE TITLE
Research about FIM `check_md5sum` bug fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4074]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Bug found for `check_md5sum` setting, in the FIM DB changes related to DBSync](https://github.com/wazuh/wazuh/issues/16625) 

# Planning stage
- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/4074#issuecomment-1523911714)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4074#issuecomment-1524041985) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4074#issuecomment-1524046534) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4074#issuecomment-1524047137)
- [x] [Conclusion](https://github.com/wazuh/wazuh-qa/issues/4074#issuecomment-1524116467)

**Comment by Deblintrake09** [comment]
## Research on new changes made

The Issue aim's to fix an error in syscheck that when configuring the `check_md5sum` tag for a monitored directory, the checksum would not be shown in the alert when files were modified. They would be shown only when files were deleted.

Now the checksum appears properly in `modified` type alerts.

- Before change: 
```
** Alert 1681464854.693219: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Apr 14 09:34:14 (centos9) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/test/file1' modified
Mode: realtime
Changed attributes: md5
Old md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'
New md5sum is : ''
```

- After Change
```
** Alert 1681464756.691215: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Apr 14 09:32:36 (centos9) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/test/file1' modified
Mode: realtime
Changed attributes: md5
Old md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'
New md5sum is : '5c9597f3c8245907ea71a89d9d39d08e'
```

**Comment by Deblintrake09** [comment]
## Identify and justify the test "tier"

| Test | Tier | Justification |
|---|---|-----|
| File md5_sum is properly calculated |1| Should run on every PR |

**Comment by Deblintrake09** [comment]
## Conclusion

The Issue https://github.com/wazuh/wazuh-qa/issues/4130 has been created to track the testing and development

**Comment by damarisg** [comment]
QA Planning Approved.
