### ISSUE TITLE
Research about Fix `malformed JSON error` into `wazuh-analysisd`

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4075]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Fix `malformed JSON error` into `wazuh-analysisd`](https://github.com/wazuh/wazuh/issues/15815) 

# Planning stage
- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/4075#issuecomment-1523292351)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4075#issuecomment-1523406593) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4075#issuecomment-1523412665) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4075#issuecomment-1523416052)
- [x] [Conclusion](https://github.com/wazuh/wazuh-qa/issues/4075#issuecomment-1523440343)

**Comment by Deblintrake09** [comment]
## Research on new changes made

The changes made aim to fix how analysisd parses the SCA scan's `scan_id`. This value is generated at random when a scan is started, and when the value was 0, it would be read as a `string` instead of an `integer` causing analysisd to fail.

Since the value is generated at random, getting a 0, is not easy to reproduce, so in order to test this, it would require a customized installation that always gets a 0.

**Comment by Deblintrake09** [comment]
## Design of test scenarios and use cases

Since testing this requires a customized package and cannot be properly tested with normal packages, this will not be a target for automated testing and will only be tested manually

### Test Cases

<details><summary>Test sca scan_id is 0</summary>

```Gherkin
Scenario Outline: SCA `scan_id` = 0 is parsed and Scan works.
Given a manager is started
When a SCA scan starts and it's `scan_id` is  `0`
Then the scan works properly
```
</details>

<details><summary>Test sca scan_id is  invalid</summary>

```Gherkin
Scenario Outline: SCA `scan_id`  has invalid value - Scan fails
Given a manager is started
When a SCA scan starts and it's `scan_id` has a given  `value`
Then the scan fails and a `response_message` is shown

  Examples:
    | scan_id value |                            response_message                               |
    |    -1                  | Malformed JSON: field 'scan_id' must be a number.  |
    |    1000             |Malformed JSON: field 'scan_id' cannot be negative. |
```
</details>

**Comment by Deblintrake09** [comment]
## Evaluate the current state of testing

Currently, there is no testing for this cases. Since the value is generated at random, getting any of the tested values, is not easy to reproduce, so in order to test this, it would require a customized installation.

**Comment by Deblintrake09** [comment]
| Test | Tier | Justification |
|---|---|-----|
| test SCA scan_id is 0 |0| This can only be tested manually. |
| test SCA scan_id is invalid |0| This can only be tested manually. |

**Comment by Deblintrake09** [comment]
## Conclusion

The Issue https://github.com/wazuh/wazuh-qa/issues/4127 has been created to handle the manual testing.

**Comment by damarisg** [comment]
QA Planning Approved.
