### ISSUE TITLE
Fix skipped FIM test modules

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4077]
## Description
During the development of Issue #3591, when launching tests locally, it was found that a lot of modules failed. Some of the modules had flaky behavior, while others were related to a bug that was reported in https://github.com/wazuh/wazuh/issues/16658.

The listed FIM IT  modules have been `skipped` or `xfailed`. Tests marked as Flaky did not seem to be directly related to the reported bug, but only to flaky behavior.

### Test modules to fix
- [ ] test_files/test_restrict/test_restrict_valid.py
- [ ] test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_confs_duplicated_entries.py
- [ ] test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_complex.py
- [ ] test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_simple.py
- [ ] test_registry/test_registry_checks/test_registry_checkers.py
- [ ] test_registry/test_registry_ignore/test_ignore_registry.py
- [ ] test_registry/test_registry_nodiff/test_registry_nodiff (Flaky)
- [ ] test_registry/test_registry_report_changes/test_registry_disk_quota_values.py (Flaky)
- [ ] test_registry/test_registry_report_changes/test_registry_file_size_values.py (Flaky)
- [ ] test_registry/test_registry_report_changes/test_registry_diff_size_limit_values.py (Flaky)
- [ ] test_registry/test_registry_report_changes/test_registry_report_changes.py  (Flaky)
- [ ] test_registry/test_registry_report_changes/test_registry_report_more_changes.py (Flaky)
- [ ] test_registry/test_registry_restrict/test_registry_restrict.py 
- [ ] test_registry/test_registry_path/test_registry_long_path.py (Flaky)
- [ ] test_synchronization/test_registry_responses_win32.py (Flaky)

### Current behavior
Tests are skipped in Windows.

### Expected behavior
All tests are passing.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
