### ISSUE TITLE
Enable FIM test_scan IT suite

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4078]
## Description
The IT modules located in `test_fim/test_files/test_scan` have been skipped on windows because when running locally they cause the enviroment to get stuck and never finish. This behavior is not experienced in Jenkins.

This Issue aims at researching the Issue so the modules can be enabled again.

### Current behavior
The modules in `test_fim/test_files/test_scan` hang and never complete, until the execution is cancelled, locally for Windows.

### Expected behavior
Tests run and finish properly on all OSs, both locally and Jenkins.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
