### ISSUE TITLE
Validate fix in FIM registry Windows unit tests

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#4086]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|            4.5            |         https://github.com/wazuh/wazuh/issues/16700             |        https://github.com/wazuh/wazuh/pull/16710            |

## Description
Hello team, 
This issue is to validate the fix performed on one of the Windows unit tests related to FIM records.
The test was failing in some environments due to a partial initialization of a structure.
After the change, we have been able to verify that the test passes correctly.

## Proposed checks

- [ ] Check that Windows unit tests pass correctly

## Expected results
https://github.com/wazuh/wazuh/pull/16710#pullrequestreview-1382987400

**Comment by juliamagan** [comment]
I am closing this issue as the change has been successfully tested in the development and in the PR check.
