### ISSUE TITLE
Test that Added plus symbol to macOS ULS timestamp works

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#4090]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.4.2             |           https://github.com/wazuh/wazuh/issues/15669             |             https://github.com/wazuh/wazuh/pull/16530       |

## Description
Added support in analysisd to decode timestamps with the '+' symbol typically used in macOS logs timestamp.

## Proposed checks

- [ ] use an ini content like this: 

          [plus symbol on timestamp]
          log 1 pass = 2023-04-13 22:02:51.837266+0200  localhost loginwindow[164]: [com.apple.loginwindow.logging:Standard] -[SessionAgentNotificationCenter sendBSDNotification:forUserID:] | sendBSDNotification: com.apple.sessionagent.screenIsLocked, with userID:501
          rule = 89609
          alert = 3
          decoder = macOS_loginwindow

## Expected results

when using a log line like the one in the test, an alert should be generated like this 

          #wazuh-logtest
          Starting wazuh-logtest v4.6.0
          Type one log per line
          
          2022-12-13 14:19:30.429319+0200  localhost sshd[1115]: Failed password for invalid user hacker from 192.168.56.1 port 50384 ssh2
          
          **Phase 1: Completed pre-decoding.
	          full event: '2022-12-13 14:19:30.429319+0200  localhost sshd[1115]: Failed password for invalid user hacker from 192.168.56.1 port 50384 ssh2'
	          timestamp: '2022-12-13 14:19:30.429319+0200'
	          program_name: 'sshd'
          
          **Phase 2: Completed decoding.
	          name: 'sshd'
	          parent: 'sshd'
	          srcip: '192.168.56.1'
	          srcuser: 'hacker'
          
          **Phase 3: Completed filtering (rules).
	          id: '5710'
	          level: '5'
	          description: 'sshd: Attempt to login using a non-existent user'
	          groups: '['syslog', 'sshd', 'authentication_failed', 'invalid_login']'
	          firedtimes: '1'
	          gdpr: '['IV_35.7.d', 'IV_32.2']'
	          gpg13: '['7.1']'
	          hipaa: '['164.312.b']'
	          mail: 'False'
	          mitre.id: '['T1110.001', 'T1021.004', 'T1078']'
	          mitre.tactic: '['Credential Access', 'Lateral Movement', 'Defense Evasion', 'Persistence', 'Privilege Escalation', 'Initial Access']'
	          mitre.technique: '['Password Guessing', 'SSH', 'Valid Accounts']'
	          nist_800_53: '['AU.14', 'AC.7', 'AU.6']'
	          pci_dss: '['10.2.4', '10.2.5', '10.6.1']'
	          tsc: '['CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
          **Alert to be generated.

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16530/commits/ae4be0992921cdd4a0f52e73c687b0cebdc45560 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| `wazuh-manager` | `wazuh-agent` |
| --------------- | ------------- |
|      [wazuh-manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.2-0.commitae4be09_amd64.deb)             | [wazuh-agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/macos/wazuh-agent-4.4.2-0.commitae4be09.pkg)             |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@juliamagan)
- [ ] Development team leader approved (@72nomada)

**Comment by Rebits** [comment]
## Testing results :large_blue_circle: 


<details>

<summary> Preconditions </summary>

<blockquote>

<details>

<summary> macOS Agent </summary>

</details>


<details>

<summary> Manager </summary>

</details>


</blockquote>


</details>

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
