### ISSUE TITLE
Research about cluster error when `wazuh-modulesd` sync messages fail to be sent across the cluster

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4096]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Avoid cluster error when agent-upgrade module sync messages fail to be sent across the cluster](https://github.com/wazuh/wazuh/pull/16683) 

# Planning stage
  
  - [x] [Research the applied change](https://github.com/wazuh/wazuh-qa/issues/4096#issuecomment-1511278114).
  - [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4096#issuecomment-1511810287).
  - [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4096#issuecomment-1511833996).
  - [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4096#issuecomment-1511852927).

**Comment by QU3B1M** [comment]
## Research the applied change

It fixes a cluster error raised by `modulesd` when a worker is started when the master is stopped, and adds retries to the sync messages. Now when a worker starts and the manager is offline, it will retry the sync 10 times, if the master is still down it raises an error.

**Comment by QU3B1M** [comment]
## Design of test scenarios and use cases

#### Scenario outline - worker re-synchronizes correctly
```Gherkin
Given a wazuh cluster with one worker.
When the master is <master_action>.
And the worker is <worker_action>.
Then the worker <result>.

Examples:
    | master_action | worker_action | result                              |
    |---------------|---------------|-------------------------------------|
    | N/A (started) | Restarted     | Re-synchronizes properly            |
    | Restarted     | N/A (started) | Re-synchronizes properly            |
    | Restarted     | Restarted     | Re-synchronizes properly            |
    | Stopped       | N/A (started) | After 10 retries it raises an error |
    | Stopped       | Restarted     | After 10 retries it raises an error |
```

**Comment by QU3B1M** [comment]
## Evaluate the current state of testing

For now there are no tests that specifically validates this, these cases must be added to `tests/system/test_cluster`

**Comment by QU3B1M** [comment]
## Identify and justify the test "tier"


| Test                      | Level    | Tier    | Justification     |
|---------------------------|----------|---------|-------------------|
|`cluster_re_sync`          | `system` | 1       | In the real world the master cluster could be restarted anytime and it is important that the workers could re-synchronize correctly with it. |

**Comment by QU3B1M** [comment]
# Conclusion :rocket: 

To approve this PR the following manual test must be completed:
- #4101
The following development request is created to add coverage for this cases:
- #4102

**Comment by damarisg** [comment]
QA Planning Approved.
