### ISSUE TITLE
Research about  Syscollector JSON exception invalid UTF-8 character

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4097]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|     4.6.0                 |     https://github.com/wazuh/wazuh/issues/16682               |         https://github.com/wazuh/wazuh/pull/16701           |

## Description

Conversion to UTF8 was not being considered for processes, only for packages.

# Development stage

- [x] Research on new changes made
- [x] Design of test scenarios and use cases
- [x] Evaluate the current state of testing
- [x] Identify and justify the test "tier"
- [x] Conclusion - Open issues in relation to the designed planning

**Comment by BelenValdivia** [comment]
### Research on new changes made

This issue fixes a problem where conversion to UTF8 was not being considered for processes, only for packages.
The exception triggers when a Chinese package is installed.

**Comment by BelenValdivia** [comment]
### Design of test scenarios and use cases

- Test that there are no errors in ossec.log when install a chinese package
  ```Gherkin
    Given I Install the Wazuh agent in a Chinese Windows VM
    When I  install a Chinese package  (i.e. https://www.kdocs.cn/)
    And I restart the agent to force a syscollector scan
    Then no error is shown in the ossec.log file

**Comment by BelenValdivia** [comment]
### Evaluate the current state of testing

- Syscollector tests ti check default events is being developed [ here ](https://github.com/wazuh/wazuh-qa/pull/3584)
tests/integration/test_syscollector/data/test_cases/case_test_default_values.yaml. We don't have a chinese Windows to test.

**Comment by BelenValdivia** [comment]
### Conclusion

**Comment by damarisg** [comment]
QA Planning Approved.
