### ISSUE TITLE
Modify netstat command on macOS agents

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#4103]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|            4.4.2            |           https://github.com/wazuh/wazuh/issues/16743             |       https://github.com/wazuh/wazuh/pull/16744             |

## Description

The current netstat command on macOS agents is: 

        <command>netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq</command>

This command does not provide the correct answer. We will modify that command with this one:

      <command>netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u</command>

## File to be updated 

https://github.com/wazuh/wazuh/blob/master/etc/templates/config/darwin/localfile-commands.template

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits | https://github.com/wazuh/wazuh/pull/16744/commits/0b66e255191560d348d95218af6200078192afb4 | 

### Testing environment

| OS     | OS version | Deployment | Image/AMI | Notes |
| ------ | ---------- | ---------- | --------- | ----- |
| centOS | 8          | Vagrant    | -         |       |
| macOS  | Ventura    | Local      | -         |       |
| macOS  | BigSur     | Vagrant           |           |       |

### Tested packages

| `wazuh-manager`                                                                                                                   |  wazuh-agent   |
| --------------------------------------------------------------------------------------------------------------------------------- | --- |
| [wazuh-manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.2-0.commita31262a.x86_64.rpm) | [wazuh-agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/macos/wazuh-agent-4.4.2-0.commit0b66e25.pkg)  |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@juliamagan)
- [ ] Development team leader approved (@72nomada)

**Comment by Rebits** [comment]
## Testing results :green_circle:



<details>

<summary> Preconditions </summary>


<blockquote>


<details>

<summary> Manager - Install </summary>

```
[root@localhost ~]# yum install wazuh-manager-4.4.2-0.commitae4be09.x86_64.rpm 
Complementos cargados:fastestmirror
Examinando wazuh-manager-4.4.2-0.commitae4be09.x86_64.rpm: wazuh-manager-4.4.2-0.commitae4be09.x86_64
Marcando wazuh-manager-4.4.2-0.commitae4be09.x86_64.rpm para ser instalado
Resolviendo dependencias
--> Ejecutando prueba de transacción
---> Paquete wazuh-manager.x86_64 0:4.4.2-0.commitae4be09 debe ser instalado
--> Resolución de dependencias finalizada

Dependencias resueltas

==================================================================================================
 Package        Arquitectura
                        Versión                Repositorio                                  Tamaño
==================================================================================================
Instalando:
 wazuh-manager  x86_64  4.4.2-0.commitae4be09  /wazuh-manager-4.4.2-0.commitae4be09.x86_64  450 M

Resumen de la transacción
==================================================================================================
Instalar  1 Paquete

Tamaño total: 450 M
Tamaño instalado: 450 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Instalando    : wazuh-manager-4.4.2-0.commitae4be09.x86_64                                  1/1 
  Comprobando   : wazuh-manager-4.4.2-0.commitae4be09.x86_64                                  1/1 

Instalado:
  wazuh-manager.x86_64 0:4.4.2-0.commitae4be09                                                    

¡Listo!
```

</details>



<details>

<summary> macOS agent - Install</summary>


```
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-0.commit0b66e25.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```


</details>


</blockquote>

</details>



<details>

<summary> Original command replication </summary>

<blockquote>

<details> 

<summary> ossec.conf </summary>

```
  <localfile>
    <log_format>full_command</log_format>
<command>netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq</command>
    <alias>netstat listening ports - old</alias>
    <frequency>360</frequency>
  </localfile>
```
</details>

***


Using this command we get not only listening ports but all the establish connections:
```
sh-3.2# netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq
udp4 *.* *.*
udp46 *.* *.*
tcp4 *.88 *.*
tcp6 *.88 *.*
udp4 *.88 *.*
udp6 *.88 *.*
udp4 *.137 *.*
udp4 *.138 *.*
tcp4 *.5000 *.*
tcp6 *.5000 *.*
udp4 *.5353 *.*
udp6 *.5353 *.*
tcp4 *.5900 *.*
tcp6 *.5900 *.*
tcp4 *.7000 *.*
tcp6 *.7000 *.*
       9        5        0     8192    32768 com.apple.network.tcp_ccdebug 
tcp4 127.0.0.1.8439 *.*
tcp4 127.0.0.1.8439 127.0.0.1.50095
tcp4 127.0.0.1.8439 127.0.0.1.50096
tcp4 127.0.0.1.50095 127.0.0.1.8439
tcp4 127.0.0.1.50096 127.0.0.1.8439
tcp4 192.168.10.149.50105 213.227.186.146.5938
tcp4 192.168.10.149.50120 192.168.10.120.22
tcp4 192.168.10.149.50128 192.168.10.120.22
tcp4 192.168.10.149.50142 213.227.186.148.5938
tcp4 192.168.10.149.50147 192.168.10.120.1514
tcp4 192.168.10.149.50149 192.168.10.120.1514
udp4 *.52495 *.*
tcp4 *.59869 *.*
udp4 *.59870 *.*
udp4 *.59871 *.*
tcp4 192.168.10.149.62815 17.57.146.42.5223
``` 

It is proposed a new command only get listening ports



</blockquote>



</details>




<details>

<summary> New command monitoring is applied in the default macOS configuration :green_circle: </summary>


<blockquote>

<details>

<summary> macOS Ventura :green_circle: </summary>


```
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>
```

</details>


<details>

<summary> macOS Monterey :green_circle: </summary>


```
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>
``` 



</details>


</blockquote>

</details>














<details>

<summary> Proposed command work as expected :green_circle: </summary>


<blockquote>


<details>

<summary> macOS Ventura :green_circle: </summary>

```
2023/04/19 14:25:41 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u
```

***


Only listening ports are gathered:

```
2023 Apr 19 08:29:23 (MacBook-Air-de-Mariajo.local) any->netstat listening ports ossec: output: 'netstat listening ports':
tcp4 *.5000 *.*
tcp4 *.5900 *.*
tcp4 *.59869 *.*
tcp4 *.7000 *.*
tcp4 *.88 *.*
tcp4 127.0.0.1.8439 *.*
tcp6 *.5000 *.*
tcp6 *.5900 *.*
tcp6 *.7000 *.*
tcp6 *.88 *.*
udp4 *.137 *.*
udp4 *.138 *.*
udp4 *.52495 *.*
udp4 *.5353 *.*
udp4 *.59870 *.*
udp4 *.59871 *.*
udp4 *.88 *.*
udp6 *.5353 *.*
udp6 *.88 *.*
```

</details>




<details>

<summary> macOS Monterey :green_circle: </summary>


```
2023/04/19 15:43:56 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u
```

***

```
2023 Apr 19 13:45:30 (macos-1200) any->netstat listening ports ossec: output: 'netstat listening ports':
tcp4 *.22 *.*
tcp4 *.5900 *.*
tcp4 *.88 *.*
tcp4 127.0.0.1.631 *.*
tcp46 *.3283 *.*
tcp6 *.22 *.*
tcp6 *.5900 *.*
tcp6 *.88 *.*
tcp6 ::1.631 *.*
udp4 *.137 *.*
udp4 *.138 *.*
udp4 *.3283 *.*
udp4 *.49418 *.*
udp4 *.5353 *.*
udp4 *.88 *.*
udp46 *.3283 *.*
udp6 *.5353 *.*
udp6 *.88 *.*
```


</details>

</blockquote>

</details>

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
