### ISSUE TITLE
Research about fix to validate configuration correctly

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4104]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Fix to validate configuration correctly](https://github.com/wazuh/wazuh/pull/16681) 

# Planning stage
  
  - [x] [Research the applied change](https://github.com/wazuh/wazuh-qa/issues/4104#issuecomment-1513155083).
  - [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4104#issuecomment-1513279702).
  - [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4104#issuecomment-1513372546).
  - [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4104#issuecomment-1513407255).

**Comment by QU3B1M** [comment]
## Research the applied change
It fixes a bug where the `ossec.conf` format is not validated correctly and it accepts non xml format _(example: `{"body": {"<ossec_config></ossec_config>"}}`)_. With this fix, only valid xml are accepted

**Comment by QU3B1M** [comment]
## Design of test scenarios and use cases

#### Scenario outline - validate ossec.conf format

```Gherkin

Given a wazuh-manager installed.
When update the ossec.conf with a "<xml_format>" format.
And use the API to validate the configuration.
Then the API responds with "<response>".

Examples:
    | xml_format                        | response      |
    |-----------------------------------|---------------|
    | valid XML (tipical ossec.conf)    | OK            |
    | invalid XML (> or < missing)      | ERROR         |
    | invalid XML (empty tags)          | ERROR         |
    | invalid XML (empty)               | ERROR         |
    | valid JSON                        | ERROR         |
    | valid JSON with valid XML inside  | ERROR         |
```

**Comment by QU3B1M** [comment]
## Evaluate the current state of testing

There is no automated test for this cases, not sure where it would fit as it is a base config validation, as it is done through the API it may fit in `tests/integration/test_api/test_config`

**Comment by QU3B1M** [comment]
## Identify and justify the test "tier"


| Test                      | Level         | Tier    | Justification     |
|---------------------------|---------------|---------|-------------------|
|`ossec_conf_format`        | `integration` | 1       | Validation of the ossec.conf format should work correctly. This scenario would be useful when ossec.conf is migrated from XML to YAML (that might happen one day) |

**Comment by QU3B1M** [comment]
# Conclusion :rocket: 

To approve this PR the following manual test must be completed:
- #4114

The following development request is created to add coverage for this cases:
- #4115

**Comment by damarisg** [comment]
QA planning approved.
