### ISSUE TITLE
Windows Registry Analysisd IT failure

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4112]
### Nightly Details

| Branch|Date | Commit |
| --- | ---- | ---- |
| `4.5` | 2023-04-19|3af4db6  | 

### Description

Windows registry tests of the analysisd `test_validate_win32_analysisd_registry_alerts` are failing for `4.5`.

### Evidence

- [Report.zip](https://github.com/wazuh/wazuh-qa/files/11283936/manager_html_report_Test_integration_B37613_20230419035512.zip)

**Comment by QU3B1M** [comment]
It was found that the cases were failing because a missing `index` key on the cases yaml and there is a validation on the manager that checks this field:
```c
if ((strcmp("registry_key", entry_type) == 0) || (strcmp("registry_value", entry_type) == 0)) {
    if (lf->fields[FIM_REGISTRY_HASH].value == NULL) {
        mdebug1("No member 'index' in Syscheck JSON payload");
        return -1;
    }
}
```

**Comment by QU3B1M** [comment]
The cases were fixed and the local executions were successful

| Test path | OS | Executions |
|-------|------|-----------------|
| `test_validate_win32_analysisd_registry_alerts` | Ubuntu 22.04 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11402487/report.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11402488/report1.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11402490/report2.zip)|
