### ISSUE TITLE
Validate correct `ossec.conf` format validation

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4114]
| Target version | Related issue      | Related PR         |
|----------------|--------------------|--------------------|
|  4.6.0         | wazuh/wazuh#16386  | wazuh/wazuh#16681  |

## Description

This issue aims to validate the fix of a bug where the `ossec.conf` format is not validated correctly and it accepts non xml format _(example: `{"body": {"<ossec_config></ossec_config>"}}`)_. With this fix, only valid xml are accepted

## Proposed checks

- <details><summary>Scenario outline - validate ossec.conf format</summary>

    ```Gherkin

    Given a wazuh-manager installed.
    When update the ossec.conf with a "<xml_format>" format.
    And use the API to validate the configuration.
    Then the API responds with "<response>".

    Examples:
        | xml_format                        | response      |
        |-----------------------------------|---------------|
        | valid XML (tipical ossec.conf)    | OK            |
        | invalid XML (> or < missing)      | ERROR         |
        | invalid XML (empty tags)          | ERROR         |
        | invalid XML (empty)               | ERROR         |
        | valid JSON                        | ERROR         |
        | valid JSON with valid XML inside  | ERROR         |
    ```
</details> 

### Fix application methods
- [x] Bug reproduction
- [x] Fresh install
- [x] Upgrade

**Comment by QU3B1M** [comment]
## Review data

| Tester  | PR commit               | 
|---------|-------------------------|
| @QU3B1M |  [`7dfad62`](https://github.com/wazuh/wazuh/pull/16681/commits/7dfad62035ec82df3af1b6f820f832bf34696bf7) | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [generic/ubuntu2204](https://app.vagrantup.com/generic/boxes/ubuntu2204)


### Tested packages

| `wazuh-manager` |
|-----------------| 
|[deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.6/deb/var/wazuh-manager_4.6.0-0.commit7dfad62_amd64.deb)|     

### Status

- [x] In progress @QU3B1M 
- [ ] QA team leader approved @damarisg
- [ ] Development team leader approved @TomasTurina

**Comment by QU3B1M** [comment]
## Error reproduction :lady_beetle: 

  1. having a `wazuh-manager` installed and running
  2. Set an invalid ossec.conf
      ```bash
      echo "{"body": {"<ossec_config></ossec_config>"}}" > /var/ossec/etc/ossec.conf 
      ```
  3. Validate the ossec.conf using the API
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [{"name": "manager", "status": "OK"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Validation was successfully checked", "error": 0}
      ```

**Comment by QU3B1M** [comment]
# Testing results :test_tube: 

## Unfixed

<details><summary>Error repoduction </summary>
  
  1. having a `wazuh-manager` installed and running
  2. Set an invalid ossec.conf
      ```bash
      echo "{"body": {"<ossec_config></ossec_config>"}}" > /var/ossec/etc/ossec.conf 
      ```
  3. Validate the ossec.conf using the API
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [{"name": "manager", "status": "OK"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Validation was successfully checked", "error": 0}
      ```
  </details>

## Upgrade

<details><summary>Upgrade process</summary>

- Upgrade wazuh-manager 
    ```vim
    dpkg -i wazuh-manager_4.6.0-0.commit7dfad62_amd64.deb 

    (Reading database ... 95089 files and directories currently installed.)
    Preparing to unpack wazuh-manager_4.6.0-0.commit7dfad62_amd64.deb ...
    Unpacking wazuh-manager (4.6.0-0.commit7dfad62) over (4.4.1-1) ...
    Setting up wazuh-manager (4.6.0-0.commit7dfad62) ...
    ```
</details>


<details><summary>Scenario outline - Worker re-synchronizes correctly :green_circle:</summary>

  > <details><summary>Gherkin description</summary>
  > 
  >    ```Gherkin
  >    Given a wazuh-manager installed.
  >    When update the ossec.conf with a "<xml_format>" format.
  >    And use the API to validate the configuration.
  >    Then the API responds with "<response>".
  >  
  >    Examples:
  >        | xml_format                        | response      |
  >        |-----------------------------------|---------------|
  >        | valid XML (tipical ossec.conf)    | OK            |
  >        | invalid XML (> or < missing)      | ERROR         |
  >        | invalid XML (empty tags)          | ERROR         |
  >        | invalid XML (empty)               | ERROR         |
  >        | valid JSON                        | ERROR         |
  >        | valid JSON with valid XML inside  | ERROR         |
  >    ```
  > </details>


- <details><summary>Case 1 - validate <code>ossec.conf</code> with correct XML format :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set a valid `ossec.conf`.
      > The default ossec.conf is used.
  3. Validate the configuration using the API and check the status is **OK**.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [{"name": "manager", "status": "OK"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Validation was successfully checked", "error": 0}
      ```
  </details>

- <details><summary>Case 2 - validate <code>ossec.conf</code> with invalid XML that is missing a <code>\></code> :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set an invalid `ossec.conf` with missing `>`.
      ```xml
      <ossec_config
        <global>
          <jsonout_output>yes</jsonout_output>
          <alerts_log>yes</alerts_log>
          <logall>no</logall>
          <logall_json>no</logall_json>
          <email_notification>no</email_notification>
          <smtp_server>smtp.example.wazuh.com</smtp_server>
          <email_from>wazuh@example.wazuh.com</email_from>
          <email_to>recipient@example.wazuh.com</email_to>
          <email_maxperhour>12</email_maxperhour>
          ...
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 3 - validate <code>ossec.conf</code> with invalid XML that has an empty tag :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set an invalid `ossec.conf` with an empty tag.
      ```xml
      <>
        <global>
          <jsonout_output>yes</jsonout_output>
          <alerts_log>yes</alerts_log>
          <logall>no</logall>
          <logall_json>no</logall_json>
          <email_notification>no</email_notification>
          <smtp_server>smtp.example.wazuh.com</smtp_server>
          <email_from>wazuh@example.wazuh.com</email_from>
          <email_to>recipient@example.wazuh.com</email_to>
          <email_maxperhour>12</email_maxperhour>
          ...
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 4 - validate <code>ossec.conf</code> empty file :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` empty.
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration: Remoted connection is not configured.", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 5 - validate <code>ossec.conf</code> with valid JSON format :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` with valid JSON.
      ```JSON
      {"body": {"data": "test"}}
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 6 - validate <code>ossec.conf</code> with valid JSON that contains a XML :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` with valid JSON containing a valid XML.
      ```JSON
      {"body": {"<ossec_config></ossec_config>"}}
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>
</details>


## Fresh install

<details><summary>Scenario outline - Worker re-synchronizes correctly :green_circle:</summary>

  > <details><summary>Gherkin description</summary>
  > 
  >    ```Gherkin
  >    Given a wazuh-manager installed.
  >    When update the ossec.conf with a "<xml_format>" format.
  >    And use the API to validate the configuration.
  >    Then the API responds with "<response>".
  >  
  >    Examples:
  >        | xml_format                        | response      |
  >        |-----------------------------------|---------------|
  >        | valid XML (tipical ossec.conf)    | OK            |
  >        | invalid XML (> or < missing)      | ERROR         |
  >        | invalid XML (empty tags)          | ERROR         |
  >        | invalid XML (empty)               | ERROR         |
  >        | valid JSON                        | ERROR         |
  >        | valid JSON with valid XML inside  | ERROR         |
  >    ```
  > </details>


- <details><summary>Case 1 - validate <code>ossec.conf</code> with correct XML format :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set a valid `ossec.conf`.
      > The default ossec.conf is used.
  3. Validate the configuration using the API and check the status is **OK**.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [{"name": "manager", "status": "OK"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Validation was successfully checked", "error": 0}
      ```
  </details>

- <details><summary>Case 2 - validate <code>ossec.conf</code> with invalid XML that is missing a <code>\></code> :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set an invalid `ossec.conf` with missing `>`.
      ```xml
      <ossec_config
        <global>
          <jsonout_output>yes</jsonout_output>
          <alerts_log>yes</alerts_log>
          <logall>no</logall>
          <logall_json>no</logall_json>
          <email_notification>no</email_notification>
          <smtp_server>smtp.example.wazuh.com</smtp_server>
          <email_from>wazuh@example.wazuh.com</email_from>
          <email_to>recipient@example.wazuh.com</email_to>
          <email_maxperhour>12</email_maxperhour>
          ...
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 3 - validate <code>ossec.conf</code> with invalid XML that has an empty tag :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set an invalid `ossec.conf` with an empty tag.
      ```xml
      <>
        <global>
          <jsonout_output>yes</jsonout_output>
          <alerts_log>yes</alerts_log>
          <logall>no</logall>
          <logall_json>no</logall_json>
          <email_notification>no</email_notification>
          <smtp_server>smtp.example.wazuh.com</smtp_server>
          <email_from>wazuh@example.wazuh.com</email_from>
          <email_to>recipient@example.wazuh.com</email_to>
          <email_maxperhour>12</email_maxperhour>
          ...
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 4 - validate <code>ossec.conf</code> empty file :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` empty.
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration: Remoted connection is not configured.", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 5 - validate <code>ossec.conf</code> with valid JSON format :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` with valid JSON.
      ```JSON
      {"body": {"data": "test"}}
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>

- <details><summary>Case 6 - validate <code>ossec.conf</code> with valid JSON that contains a XML :green_circle:</summary>

  1. With a `wazuh-manager` up and running.
  2. Set `ossec.conf` with valid JSON containing a valid XML.
      ```JSON
      {"body": {"<ossec_config></ossec_config>"}}
      ```
  3. Validate the configuration using the API and check the status.
      ```JSON
      curl -k -X GET https://localhost:55000/manager/configuration/validation -H "Authorization: Bearer $TOKEN"

      {"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1908, "message": "Error validating configuration", "remediation": "Please, fix the corrupted files"}, "id": ["manager"]}]}, "message": "Could not check validation", "error": 1}
      ```
  </details>
</details>

**Comment by QU3B1M** [comment]
# Conclusion :green_circle: 

[Test execution](https://github.com/wazuh/wazuh-qa/issues/4114#issuecomment-1518253330) successful :rocket:. Core is correctly validating the `ossec.conf` format when the framework requests it.

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
