### ISSUE TITLE
Add coverage to correct `ossec.conf` format validation

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4115]
|  Test level     | Target version | Related issue      | Related PR         |
|-----------------|----------------|--------------------|--------------------|
|  `integration`  |  4.6.0         | wazuh/wazuh#16386  | wazuh/wazuh#16681  |

## Description

This cases aims to validate the `ossec.conf` format is validated correctly (only valid XML must be accepted)

## Proposed test cases

- <details><summary>Scenario outline - validate ossec.conf format - Tier 1</summary>

    ```Gherkin

    Given a wazuh-manager installed.
    When update the ossec.conf with a "<xml_format>" format.
    And use the API to validate the configuration.
    Then the API responds with "<response>".

    Examples:
        | xml_format                        | response      |
        |-----------------------------------|---------------|
        | valid XML (tipical ossec.conf)    | OK            |
        | invalid XML (> or < missing)      | ERROR         |
        | invalid XML (empty tags)          | ERROR         |
        | invalid XML (empty)               | ERROR         |
        | valid JSON                        | ERROR         |
        | valid JSON with valid XML inside  | ERROR         |
    ```
</details>

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
