### ISSUE TITLE
Fix Logcollector `ignore_binaries` IT Windows Jenkins flaky behavior

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4122]
## Description

The test module `test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py` has flaky behavior on Windows systems. When launched on Jenkins it sometimes fails, but this behavior is not replicated when launching the test locally. 

The test module has been `xfailed` on windows, and has some other issues with xfails inside the code from previous Issues. It should be researched and fixed so all test cases work properly on all OSs.

**Evidence:** [Windows logcollector results](https://github.com/wazuh/wazuh-qa/files/11322399/agent_windows_html_report_Test_integration_B37593_20230418192400.zip)

### Current behavior
`test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py` has flaky behavior and fails in Windows Jenkins enviroment, but passes locally.

### Expected behavior

`test_logcollector/test_configuration/test_basic_configuration_ignore_binaries.py` passes consistently on all OSs both locally and Jenkins.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
