### ISSUE TITLE
Unit tests for Windows sometimes hang

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#4124]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.4.2  |   https://github.com/wazuh/wazuh/issues/16736   |  https://github.com/wazuh/wazuh/pull/16857  |

## Description

We aim to fix an intermittent unit test failure on Windows. As we detected some misbehavior in the `nanosleep` function, we replaced it with `sched_yield`.

This change exclusively affects the unit tests.

## Proposed checks

- [x] The unit tests for Windows pass in local mode.
- [x] The unit tests for Windows pass in a Jenkins environment.

## Steps to reproduce

We found no way to consistently reproduce the problem.

**Comment by juliamagan** [comment]
## Conclusion 🟢 

The tests have passed as expected in [Jenkins](https://ci.wazuh.info/job/Test_unit/41046) and [locally](https://github.com/wazuh/wazuh/pull/16857#issuecomment-1522927591).
