### ISSUE TITLE
Validate OS version is not properly parsed for Alpine Linux system

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4133]
| Target version | Related issue | Related PR | Related QA Planning |
|--------------------|--------------------|-----------------|-----------------|
|      4.5.0                |    https://github.com/wazuh/wazuh/issues/15697            |   https://github.com/wazuh/wazuh/pull/16056                 |  https://github.com/wazuh/wazuh-qa/issues/4066  |

## Description

Enhance the detection on Alpine Linux, os_version, os_name, and os_platform. Linux Alpine distribution information is in files /etc/os-release and /etc/alpine-release

## Proposed checks

- Test the correct OS version detection on Alpine Linux

 ```Gherkin
     Given I install the Wazuh agent  4.5.0 version in an Alpine Linux VM
     And  I check the OS information in /etc/os-release
     When I check the information about the Alpine OS os_version in the manager database
     Then the information is correctly scanned by syscollector

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
