### ISSUE TITLE
Check Vuln Detector failures

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#4156]
| Target version | Related issue |
|--------------------|--------------------|
|4.4 | #4111 |

## Description

Some [tests had failed in the Nightly pipeline](https://github.com/wazuh/wazuh-qa/issues/4111) and they were fixed. But Vulnerability Detector presented new failures after runs to check if they were fixed. So, it was decided to open a separate issue (the current one) to investigate the new failures and resolve them if possible.

### Executions

**Local** 🟡

- [report-vd-local.zip](https://github.com/wazuh/wazuh-qa/files/11389897/report-vd.zip)
  - It fails but is due to an issue with the SUSE server itself (when using Docker), not with Wazuh.

**Jenkins** 🔴 

- Ubuntu
  - 1 test is failing:
    - It is a known issue
  - [manager_ubuntu-jenkins.zip](https://github.com/wazuh/wazuh-qa/files/11389903/manager_html_report_Test_integration_B38023_20230428194303.zip)
- CentOS
  - 2 tests are failing:
    - 1 is a known issue, the same as Ubuntu
    - The other one fails in Jenkins but not locally, sometimes failed in Ubuntu, but could not detect the main reason.
  - [manager_centos-jenkins.zip](https://github.com/wazuh/wazuh-qa/files/11389914/manager_html_report_Test_integration_B38017_20230428180222.zip)

**This requires further research to define why are they failing.**

**Comment by damarisg** [comment]
This approach is a correct way to show this unexpected failure.
