### ISSUE TITLE
Fix FileMonitor to stop using exceptions on timeout

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4158]
| Target version | Related Epic   |
|--------------------|-----------------------|
|           4.5         |  #4157             |

## Description
This issue aims to fix the FileMonitor class so that when it does not find a matching line in the logs and timeouts, it does not launch and exception, as this is a bad practice and a costly process.

The exact line of behavior is part of the QueueMonitor.start function called by FileMonitor:

https://github.com/wazuh/wazuh-qa/blob/a474f439ba7b60f0e0e39524e7d0572607ac7599/deps/wazuh_testing/wazuh_testing/tools/monitoring.py#L462-L476

This behavior also causes that when no events are expected we have to handle the exception and then do something else in case an event was found.

### Current behavior
When FileMonitor time runs out, if no matching events were found, it generates `TimeoutError` exception.

### Proposed behavior
The proposed behavior should be that in case that `QueueMonitor` should always return a value. If  the expected value was not found it should either return `None` for single expected events, or return a list with the responses found if it found some but not all of the responses. Example:

| # of Messages to be found | # Messages found | Response |
|----------------|-------------------|-----------|
| 1 or more | No matches | `None` |
| 1 | Match | Return the return value from the callback  used|
| 2+ | 1+ but less than expected | `List` with responses |
| 2+ | All expected | `List` with responses |

With this new format, all the checking is then done in the test module through assertions. This makes all responses more explicit and readable.

- Regarding `Error Messages`: with this new approach, FileMonitor would not print error messages, as the response would be asserted or checked back inside the test and the error message will be present there.

**Comment by QU3B1M** [comment]
## FileMonitor refactored
This issue is already covered in the `wazuh/wazuh` PR https://github.com/wazuh/wazuh/pull/17155.
