### ISSUE TITLE
Refactor create_registry and other functions how key is passed in as value

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4195]
|Target|
|---|
| 4.5+|

## Description
The functions that create, update or delete windows registries when they are passed the registry key, it is passed as a `win32con` object, that then is decoded back inside each function to get the name of the key. To do this, the `registry_parser` object is added to every module that uses this functions, and the `registry_class_name` is then used back to recover the name of the key. This creates duplicated and unnecessary code.

### Example

The string name of the key is `HKEY_LOCAL_MACHINE`, saved in the variable `WINDOWS_HKEY_LOCAL_MACHINE` in `modules.fim.__init__.py`

Here we have the key, that is received already converted as a `win32con` object by passing it as registry_parser[WINDOWS_HKEY_LOCAL_MACHINE]`

https://github.com/wazuh/wazuh-qa/blob/1797098830e73ffef282ad6f3ce41b6785b3edf3/tests/integration/test_fim/test_synchronization/test_synchronize_integrity_win32.py#L112-L117

https://github.com/wazuh/wazuh-qa/blob/1797098830e73ffef282ad6f3ce41b6785b3edf3/deps/wazuh_testing/wazuh_testing/modules/fim/utils.py#L92-L112

Then the `registry_class_name` is used to convert back to the string of the Key.

It would be advised that the key is passed as a string into the function, and then it is converted to an object when it is needed.

With this, we can:
- Eliminate the need to import the `registry_parser` in each module for this task.
- Delete the `registry_class_name` object as it won't be used anymore.
- Access the actual key root name where it is needed instead of an object.

### Considerations

This refactor would apply to all `registry` related functions and tests.

**Comment by Deblintrake09** [comment]
The change to `create_registry` has been applied in `4.5` already. This can be closed.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
