### ISSUE TITLE
Replace JQ library for Windows tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4197]
## Description
The `jq` library is used for parsing JSON in some tests modules, for example FIM tests. This library is not installed through pip in Windows environments and is not currently installed with the requirements or the `setup.py` in the deps.wazuh_testing folder.

If the library is not present, tests that require the library will fail in Windows and the error message is not clear.  Also when the `jq` is used, it is launched as a python `subprocess`. 

### Current behavior
The library is not installed with the dependencies on Windows. If the library is not installed tests fail with an unclear error message.

### Expected behavior
Tests work properly. Either with a replacement or the library is installed during dependencies setup.

### Considerations

This issue is aimed for the IT migration process.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
