### ISSUE TITLE
Tests fails in Windows agent when it is required to handle threads

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4206]
## Description

It has been observed that the agentd and active response integration tests are unstable for Windows agents. This failures are produced by the use of the Remoted and Auth simulators.

We noticed this problem while working on https://github.com/wazuh/wazuh-jenkins/issues/3487. It seems that when these tests fail, they don't handle threads properly, which ends up causing the pipelines to run indefinitely.

Further research is required to determinate the exact cause of the failures

### Case
| Build| Report|
|-------------|-------------|
|[39247](https://ci.wazuh.info/job/Test_integration/39247/consoleFull)| [11554284](https://github.com/wazuh/wazuh-jenkins/files/11554284/agent_windows_html_report_test_integration_b39247_20230524110349.zip)  |

> **Note** 
> It was not possible to replicate Test_enrollment defect with socket configuration, but both problems appeared at the same time

**Comment by TomasTurina** [comment]
I will close this issue since this should be fixed now that the tests have been migrated to the core repository and the new QA integration framework was implemented. If needed, I will reopen it in the future.
