### ISSUE TITLE
Change `test_python_flaws.py`  to accept branch or commit in the same argument

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4208]
## Description

test `test_python_flaws.py` should accept both branches and commits in the same argument `--reference` and depending on what it has received use one or another

### Current behavior

If you want to use a branch, you should use `--branch` argument, and if you want to use a commit you should use `--commit`

### Expected behavior

There should only be one argument, `--reference`, to which to pass on either a branch or a commit.

**Comment by Rebits** [comment]
Is required to change as well the `--branch` reference in `the test_dependencies` due to it has been changed the general scan conftest
