### ISSUE TITLE
Update or Develop Integration tests for changes made to default_config method

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh-qa#4214]
| Target version | 
|--------------------|
|       4.5                | 

## Description

The changes proposed in this [PR](https://github.com/wazuh/wazuh/pull/16531) for the closure of this [issue](https://github.com/wazuh/wazuh/issues/14978),  make changes to the method that needs to be properly tested.

Current integration tests require an update to check the use cases where the changes mentioned in the PR can affect the behavior of the module.
We should follow the same format of IT used in #3333, in case new tests are needed.

## Configurations

Config needed will be based, as explained in the issue, on [primary boto3 config parameters](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-the-config-object). 

## Proposed test cases

For example, some tests that would need updates are:
- AWS config IT introduced [here](https://github.com/wazuh/wazuh-qa/issues/3337).
- AWS parser IT introduced [here](https://github.com/wazuh/wazuh-qa/issues/3581). 

Other AWS IT should be reviewed to check if updated are needed.

## Considerations

As explained in the issue, we only need to test that the primary config parameters are properly handled when found and not found in the AWS config file.

**Comment by fdalmaup** [comment]
# Issue Update

The original AWS integration tests were run for the `14978-modify-default-config-in-aws-module` development branch. It was found that the `test_parser.py::test_bucket_and_service_missing[parser_bucket_and_service_missing]` test failed, being its fix developed in #4228. Therefore, the fix was temporarily applied to check the execution of the complete battery of tests, being the results:

<details><summary>AWS Integration Tests</summary>

    root@ubuntu-focal:/home/vagrant/wazuh-qa/tests/integration/test_aws# pytest -vvx .
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-0.13.1 -- /usr/bin/python3
    cachedir: .pytest_cache
    metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-137-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '7.1.2', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '2.0.4', 'testinfra': '5.0.0'}}
    rootdir: /home/vagrant/wazuh-qa/tests/integration, configfile: pytest.ini
    plugins: html-3.1.1, metadata-2.0.4, testinfra-5.0.0
    collected 195 items                                                                                                                                             
    
    test_basic.py::test_bucket_defaults[cloudtrail_defaults] PASSED                                                                                           [  0%]
    test_basic.py::test_bucket_defaults[vpc_defaults] PASSED                                                                                                  [  1%]
    test_basic.py::test_bucket_defaults[config_defaults] PASSED                                                                                               [  1%]
    test_basic.py::test_bucket_defaults[alb_defaults] PASSED                                                                                                  [  2%]
    test_basic.py::test_bucket_defaults[clb_defaults] PASSED                                                                                                  [  2%]
    test_basic.py::test_bucket_defaults[nlb_defaults] PASSED                                                                                                  [  3%]
    test_basic.py::test_bucket_defaults[kms_defaults] PASSED                                                                                                  [  3%]
    test_basic.py::test_bucket_defaults[macie_defaults] PASSED                                                                                                [  4%]
    test_basic.py::test_bucket_defaults[trusted_advisor_defaults] PASSED                                                                                      [  4%]
    test_basic.py::test_bucket_defaults[guardduty_defaults] PASSED                                                                                            [  5%]
    test_basic.py::test_bucket_defaults[native_guardduty_defaults] PASSED                                                                                     [  5%]
    test_basic.py::test_bucket_defaults[waf_defaults] PASSED                                                                                                  [  6%]
    test_basic.py::test_bucket_defaults[server_access_defaults] PASSED                                                                                        [  6%]
    test_basic.py::test_bucket_defaults[cisco_umbrella_defaults] PASSED                                                                                       [  7%]
    test_basic.py::test_service_defaults[cloudwatchlogs_defaults] PASSED                                                                                      [  7%]
    test_basic.py::test_inspector_defaults[inspector_defaults] PASSED                                                                                         [  8%]
    test_discard_regex.py::test_discard_regex[cloudtrail_discard_regex] PASSED                                                                                [  8%]
    test_discard_regex.py::test_discard_regex[vpc_discard_regex] PASSED                                                                                       [  9%]
    test_discard_regex.py::test_discard_regex[config_discard_regex] PASSED                                                                                    [  9%]
    test_discard_regex.py::test_discard_regex[alb_discard_regex] PASSED                                                                                       [ 10%]
    test_discard_regex.py::test_discard_regex[clb_discard_regex] PASSED                                                                                       [ 10%]
    test_discard_regex.py::test_discard_regex[nlb_discard_regex] PASSED                                                                                       [ 11%]
    test_discard_regex.py::test_discard_regex[kms_discard_regex] PASSED                                                                                       [ 11%]
    test_discard_regex.py::test_discard_regex[macie_discard_regex] PASSED                                                                                     [ 12%]
    test_discard_regex.py::test_discard_regex[trusted_advisor_discard_regex] PASSED                                                                           [ 12%]
    test_discard_regex.py::test_discard_regex[guardduty_discard_regex] PASSED                                                                                 [ 13%]
    test_discard_regex.py::test_discard_regex[native_guardduty_discard_regex] PASSED                                                                          [ 13%]
    test_discard_regex.py::test_discard_regex[waf_discard_regex] PASSED                                                                                       [ 14%]
    test_discard_regex.py::test_discard_regex[server_access_discard_regex] PASSED                                                                             [ 14%]
    test_discard_regex.py::test_discard_regex[cisco_umbrella_discard_regex] PASSED                                                                            [ 15%]
    test_log_groups.py::test_log_groups[cloudwatchlogs_log_groups_with_data] PASSED                                                                           [ 15%]
    test_log_groups.py::test_log_groups[cloudwatchlogs_inexistent_log_group] PASSED                                                                           [ 16%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[cloudtrail_without_only_logs_after] PASSED                                                   [ 16%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[vpc_without_only_logs_after] PASSED                                                          [ 17%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[config_without_only_logs_after] PASSED                                                       [ 17%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[alb_without_only_logs_after] PASSED                                                          [ 18%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[clb_without_only_logs_after] PASSED                                                          [ 18%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[nlb_without_only_logs_after] PASSED                                                          [ 19%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[kms_without_only_logs_after] PASSED                                                          [ 20%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[macie_without_only_logs_after] PASSED                                                        [ 20%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[trusted_advisor_without_only_logs_after] PASSED                                              [ 21%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[guardduty_without_only_logs_after] PASSED                                                    [ 21%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[native_guardduty_without_only_logs_after] PASSED                                             [ 22%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[waf_without_only_logs_after] PASSED                                                          [ 22%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[server_access_without_only_logs_after] PASSED                                                [ 23%]
    test_only_logs_after.py::test_bucket_without_only_logs_after[cisco_umbrella_without_only_logs_after] PASSED                                               [ 23%]
    test_only_logs_after.py::test_service_without_only_logs_after[cloudwatchlogs_without_only_logs_after] PASSED                                              [ 24%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[cloudtrail_with_only_logs_after] PASSED                                                         [ 24%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[vpc_with_only_logs_after] PASSED                                                                [ 25%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[config_with_only_logs_after] PASSED                                                             [ 25%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[alb_with_only_logs_after] PASSED                                                                [ 26%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[clb_with_only_logs_after] PASSED                                                                                                                  [ 26%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[nlb_with_only_logs_after] PASSED                                                                                                                  [ 27%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[kms_with_only_logs_after] PASSED                                                                                                                  [ 27%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[macie_with_only_logs_after] PASSED                                                                                                                [ 28%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[trusted_avisor_with_only_logs_after] PASSED                                                                                                       [ 28%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[guardduty_with_only_logs_after] PASSED                                                                                                            [ 29%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[native_guardduty_with_only_logs_after] PASSED                                                                                                     [ 29%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[waf_with_only_logs_after] PASSED                                                                                                                  [ 30%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[server_access_with_only_logs_after] PASSED                                                                                                        [ 30%]
    test_only_logs_after.py::test_bucket_with_only_logs_after[cisco_umbrella_with_only_logs_after] PASSED                                                                                                       [ 31%]
    test_only_logs_after.py::test_cloudwatch_with_only_logs_after[cloudwatchlogs_with_only_logs_after] PASSED                                                                                                   [ 31%]
    test_only_logs_after.py::test_inspector_with_only_logs_after[inspector_with_only_logs_after] PASSED                                                                                                         [ 32%]
    test_only_logs_after.py::test_bucket_multiple_calls[cloudtrail_only_logs_after_multiple_calls] PASSED                                                                                                       [ 32%]
    test_only_logs_after.py::test_bucket_multiple_calls[vpc_only_logs_after_multiple_calls] PASSED                                                                                                              [ 33%]
    test_only_logs_after.py::test_bucket_multiple_calls[config_only_logs_after_multiple_calls] PASSED                                                                                                           [ 33%]
    test_only_logs_after.py::test_bucket_multiple_calls[alb_only_logs_after_multiple_calls] PASSED                                                                                                              [ 34%]
    test_only_logs_after.py::test_bucket_multiple_calls[clb_only_logs_after_multiple_calls] PASSED                                                                                                              [ 34%]
    test_only_logs_after.py::test_bucket_multiple_calls[nlb_only_logs_after_multiple_calls] PASSED                                                                                                              [ 35%]
    test_only_logs_after.py::test_bucket_multiple_calls[kms_only_logs_after_multiple_calls] PASSED                                                                                                              [ 35%]
    test_only_logs_after.py::test_bucket_multiple_calls[macie_only_logs_after_multiple_calls] PASSED                                                                                                            [ 36%]
    test_only_logs_after.py::test_bucket_multiple_calls[trusted_advisor_only_logs_after_multiple_calls] PASSED                                                                                                  [ 36%]
    test_only_logs_after.py::test_bucket_multiple_calls[guardduty_only_logs_after_multiple_calls] PASSED                                                                                                        [ 37%]
    test_only_logs_after.py::test_bucket_multiple_calls[native_guardduty_only_logs_after_multiple_calls] PASSED                                                                                                 [ 37%]
    test_only_logs_after.py::test_bucket_multiple_calls[waf_only_logs_after_multiple_calls] PASSED                                                                                                              [ 38%]
    test_only_logs_after.py::test_bucket_multiple_calls[server_access_only_logs_after_multiple_calls] PASSED                                                                                                    [ 38%]
    test_only_logs_after.py::test_bucket_multiple_calls[cisco_umbrella_only_logs_after_multiple_calls] PASSED                                                                                                   [ 39%]
    test_only_logs_after.py::test_inspector_multiple_calls[inspector_only_logs_after_multiple_calls] XFAIL                                                                                                      [ 40%]
    test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls] PASSED                                                                                               [ 40%]
    test_parser.py::test_bucket_and_service_missing[parser_bucket_and_service_missing] PASSED                                                                                                                   [ 41%]
    test_parser.py::test_type_missing_in_bucket[parser_type_missing_in_bucket] PASSED                                                                                                                           [ 41%]
    test_parser.py::test_type_missing_in_service[parser_type_missing_in_service] PASSED                                                                                                                         [ 42%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_type_in_bucket] PASSED                                                                                                                             [ 42%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_name_in_bucket] PASSED                                                                                                                             [ 43%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_only_logs_after_in_bucket] PASSED                                                                                                                  [ 43%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_regions_in_bucket] PASSED                                                                                                                          [ 44%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_path_in_bucket] PASSED                                                                                                                             [ 44%]
    test_parser.py::test_empty_values_in_bucket[parser_empty_path_suffix_in_bucket] PASSED                                                                                                                      [ 45%]
    test_parser.py::test_empty_values_in_service[parser_empty_type_in_service] PASSED                                                                                                                           [ 45%]
    test_parser.py::test_empty_values_in_service[parser_empty_log_groups_in_service] PASSED                                                                                                                     [ 46%]
    test_parser.py::test_empty_values_in_service[parser_empty_only_logs_after_in_service] PASSED                                                                                                                [ 46%]
    test_parser.py::test_empty_values_in_service[parser_empty_regions_in_service] PASSED                                                                                                                        [ 47%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_type_in_bucket] PASSED                                                                                                                         [ 47%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_name_in_bucket] PASSED                                                                                                                         [ 48%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_only_logs_after_in_bucket] PASSED                                                                                                              [ 48%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_regions_in_bucket] PASSED                                                                                                                      [ 49%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_in_bucket] PASSED                                                                                                                         [ 49%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_suffix_in_bucket] PASSED                                                                                                                  [ 50%]
    test_parser.py::test_invalid_values_in_bucket[parser_invalid_remove_from_bucket_in_bucket] PASSED                                                                                                           [ 50%]
    test_parser.py::test_invalid_values_in_service[parser_invalid_type_in_service] PASSED                                                                                                                       [ 51%]
    test_parser.py::test_invalid_values_in_service[parser_invalid_log_groups_in_service] PASSED                                                                                                                 [ 51%]
    test_parser.py::test_invalid_values_in_service[parser_invalid_only_logs_after_in_service] PASSED                                                                                                            [ 52%]
    test_parser.py::test_invalid_values_in_service[parser_invalid_regions_in_service] PASSED                                                                                                                    [ 52%]
    test_parser.py::test_invalid_values_in_service[parser_invalid_remove_log_stream_in_service] PASSED                                                                                                          [ 53%]
    test_parser.py::test_multiple_bucket_and_service_tags[parser_mutiple_bucket_and_service_tags] PASSED                                                                                                        [ 53%]
    test_path.py::test_path[cloudtrail_path_with_data] PASSED                                                                                                                                                   [ 54%]
    test_path.py::test_path[cloudtrail_path_without_data] PASSED                                                                                                                                                [ 54%]
    test_path.py::test_path[cloudtrail_inexistent_path] PASSED                                                                                                                                                  [ 55%]
    test_path.py::test_path[vpc_path_with_data] PASSED                                                                                                                                                          [ 55%]
    test_path.py::test_path[vpc_path_without_data] PASSED                                                                                                                                                       [ 56%]
    test_path.py::test_path[cisco_umbrella_path_with_data] PASSED                                                                                                                                               [ 56%]
    test_path.py::test_path[cisco_umbrella_path_without_data] PASSED                                                                                                                                            [ 57%]
    test_path.py::test_path[vpc_inexistent_path] PASSED                                                                                                                                                         [ 57%]
    test_path.py::test_path[config_path_with_data] PASSED                                                                                                                                                       [ 58%]
    test_path.py::test_path[config_path_without_data] PASSED                                                                                                                                                    [ 58%]
    test_path.py::test_path[config_inexistent_path] PASSED                                                                                                                                                      [ 59%]
    test_path.py::test_path[alb_path_with_data] PASSED                                                                                                                                                          [ 60%]
    test_path.py::test_path[alb_path_without_data] PASSED                                                                                                                                                       [ 60%]
    test_path.py::test_path[alb_inexistent_path] PASSED                                                                                                                                                         [ 61%]
    test_path.py::test_path[clb_path_with_data] PASSED                                                                                                                                                          [ 61%]
    test_path.py::test_path[clb_path_without_data] PASSED                                                                                                                                                       [ 62%]
    test_path.py::test_path[clb_inexistent_path] PASSED                                                                                                                                                         [ 62%]
    test_path.py::test_path[nlb_path_with_data] PASSED                                                                                                                                                          [ 63%]
    test_path.py::test_path[nlb_path_without_data] PASSED                                                                                                                                                       [ 63%]
    test_path.py::test_path[nlb_inexistent_path] PASSED                                                                                                                                                         [ 64%]
    test_path.py::test_path[kms_path_with_data] PASSED                                                                                                                                                          [ 64%]
    test_path.py::test_path[kms_path_without_data] PASSED                                                                                                                                                       [ 65%]
    test_path.py::test_path[kms_inexistent_path] PASSED                                                                                                                                                         [ 65%]
    test_path.py::test_path[macie_path_with_data] PASSED                                                                                                                                                        [ 66%]
    test_path.py::test_path[macie_path_without_data] PASSED                                                                                                                                                     [ 66%]
    test_path.py::test_path[macie_inexistent_path] PASSED                                                                                                                                                       [ 67%]
    test_path.py::test_path[trusted_advisor_path_with_data] PASSED                                                                                                                                              [ 67%]
    test_path.py::test_path[trusted_advisor_path_without_data] PASSED                                                                                                                                           [ 68%]
    test_path.py::test_path[trusted_advisor_inexistent_path] PASSED                                                                                                                                             [ 68%]
    test_path.py::test_path[guardduty_path_with_data] PASSED                                                                                                                                                    [ 69%]
    test_path.py::test_path[guardduty_path_without_data] PASSED                                                                                                                                                 [ 69%]
    test_path.py::test_path[guardduty_inexistent_path] PASSED                                                                                                                                                   [ 70%]
    test_path.py::test_path[native_guardduty_path_with_data] PASSED                                                                                                                                             [ 70%]
    test_path.py::test_path[native_guardduty_path_without_data] PASSED                                                                                                                                          [ 71%]
    test_path.py::test_path[native_guardduty_inexistent_path] PASSED                                                                                                                                            [ 71%]
    test_path.py::test_path[waf_path_with_data] PASSED                                                                                                                                                          [ 72%]
    test_path.py::test_path[waf_path_without_data] PASSED                                                                                                                                                       [ 72%]
    test_path.py::test_path[waf_inexistent_path] PASSED                                                                                                                                                         [ 73%]
    test_path.py::test_path[server_access_path_with_data] PASSED                                                                                                                                                [ 73%]
    test_path.py::test_path[server_access_path_without_data] PASSED                                                                                                                                             [ 74%]
    test_path.py::test_path[server_access_inexistent_path] PASSED                                                                                                                                               [ 74%]
    test_path.py::test_path[cisco_umbrella_inexistent_path] PASSED                                                                                                                                              [ 75%]
    test_path_suffix.py::test_path_suffix[cloudtrail_path_suffix_with_data] PASSED                                                                                                                              [ 75%]
    test_path_suffix.py::test_path_suffix[cloudtrail_path_suffix_without_data] PASSED                                                                                                                           [ 76%]
    test_path_suffix.py::test_path_suffix[cloudtrail_inexistent_path_suffix] PASSED                                                                                                                             [ 76%]
    test_path_suffix.py::test_path_suffix[vpc_path_suffix_with_data] PASSED                                                                                                                                     [ 77%]
    test_path_suffix.py::test_path_suffix[config_path_suffix_with_data] PASSED                                                                                                                                  [ 77%]
    test_path_suffix.py::test_path_suffix[vpc_path_suffix_without_data] PASSED                                                                                                                                  [ 78%]
    test_path_suffix.py::test_path_suffix[config_path_suffix_without_data] PASSED                                                                                                                               [ 78%]
    test_path_suffix.py::test_path_suffix[vpc_inexistent_path_suffix] PASSED                                                                                                                                    [ 79%]
    test_path_suffix.py::test_path_suffix[config_inexistent_path_suffix] PASSED                                                                                                                                 [ 80%]
    test_regions.py::test_regions[cloudtrail_region_with_data] PASSED                                                                                                                                           [ 80%]
    test_regions.py::test_regions[cloudtrail_regions_with_data] PASSED                                                                                                                                          [ 81%]
    test_regions.py::test_regions[cloudtrail_inexistent_region] PASSED                                                                                                                                          [ 81%]
    test_regions.py::test_regions[vpc_region_with_data] PASSED                                                                                                                                                  [ 82%]
    test_regions.py::test_regions[config_region_with_data] PASSED                                                                                                                                               [ 82%]
    test_regions.py::test_regions[alb_region_with_data] PASSED                                                                                                                                                  [ 83%]
    test_regions.py::test_regions[vpc_regions_with_data] PASSED                                                                                                                                                 [ 83%]
    test_regions.py::test_regions[config_regions_with_data] PASSED                                                                                                                                              [ 84%]
    test_regions.py::test_regions[alb_regions_with_data] PASSED                                                                                                                                                 [ 84%]
    test_regions.py::test_regions[vpc_inexistent_region] PASSED                                                                                                                                                 [ 85%]
    test_regions.py::test_regions[config_inexistent_region] PASSED                                                                                                                                              [ 85%]
    test_regions.py::test_regions[alb_inexistent_region] PASSED                                                                                                                                                 [ 86%]
    test_regions.py::test_regions[clb_region_with_data] PASSED                                                                                                                                                  [ 86%]
    test_regions.py::test_regions[clb_regions_with_data] PASSED                                                                                                                                                 [ 87%]
    test_regions.py::test_regions[clb_inexistent_region] PASSED                                                                                                                                                 [ 87%]
    test_regions.py::test_regions[nlb_region_with_data] PASSED                                                                                                                                                  [ 88%]
    test_regions.py::test_regions[nlb_regions_with_data] PASSED                                                                                                                                                 [ 88%]
    test_regions.py::test_regions[nlb_inexistent_region] PASSED                                                                                                                                                 [ 89%]
    test_regions.py::test_cloudwatch_regions[cloudwatchlogs_region_with_data] PASSED                                                                                                                            [ 89%]
    test_regions.py::test_cloudwatch_regions[cloudwatchlogs_regions_with_data] PASSED                                                                                                                           [ 90%]
    test_regions.py::test_cloudwatch_regions[cloudwatchlogs_inexistent_region] PASSED                                                                                                                           [ 90%]
    test_regions.py::test_inspector_regions[inspector_region_with_data] PASSED                                                                                                                                  [ 91%]
    test_regions.py::test_inspector_regions[inspector_regions_with_data] PASSED                                                                                                                                 [ 91%]
    test_regions.py::test_inspector_regions[inspector_inexistent_region] PASSED                                                                                                                                 [ 92%]
    test_remove_from_bucket.py::test_remove_from_bucket[cloudtrail_remove_from_bucket] PASSED                                                                                                                   [ 92%]
    test_remove_from_bucket.py::test_remove_from_bucket[vpc_remove_from_bucket] PASSED                                                                                                                          [ 93%]
    test_remove_from_bucket.py::test_remove_from_bucket[config_remove_from_bucket] PASSED                                                                                                                       [ 93%]
    test_remove_from_bucket.py::test_remove_from_bucket[alb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region)                                               [ 94%]
    test_remove_from_bucket.py::test_remove_from_bucket[clb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region)                                               [ 94%]
    test_remove_from_bucket.py::test_remove_from_bucket[nlb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region)                                               [ 95%]
    test_remove_from_bucket.py::test_remove_from_bucket[kms_remove_from_bucket] PASSED                                                                                                                          [ 95%]
    test_remove_from_bucket.py::test_remove_from_bucket[macie_remove_from_bucket] PASSED                                                                                                                        [ 96%]
    test_remove_from_bucket.py::test_remove_from_bucket[trusted_advisor_remove_from_bucket] PASSED                                                                                                              [ 96%]
    test_remove_from_bucket.py::test_remove_from_bucket[guardduty_remove_from_bucket] PASSED                                                                                                                    [ 97%]
    test_remove_from_bucket.py::test_remove_from_bucket[native_guardduty_remove_from_bucket] PASSED                                                                                                             [ 97%]
    test_remove_from_bucket.py::test_remove_from_bucket[waf_remove_from_bucket] PASSED                                                                                                                          [ 98%]
    test_remove_from_bucket.py::test_remove_from_bucket[server_access_remove_from_bucket] PASSED                                                                                                                [ 98%]
    test_remove_from_bucket.py::test_remove_from_bucket[cisco_umbrella_remove_from_bucket] PASSED                                                                                                               [ 99%]
    test_remove_from_bucket.py::test_remove_log_stream[cloudwatchlogs_remove_from_bucket] PASSED                                                                                                                [100%]
    
    ============================================================================= 191 passed, 3 skipped, 1 xfailed in 3979.73s (1:06:19) ==============================================================================

</details>

## Conclusion
The code modifications applied in https://github.com/wazuh/wazuh/pull/16531 did not modify the behavior of the module but only the way it connects with the AWS API via the `boto3` package which is not part of the module's main functionality.
The methods and functions should be tested in unit tests, preferably at https://github.com/wazuh/wazuh/issues/13388.

**Comment by Selutario** [comment]
@EduLeon12, once these tests are merged, rebase your [PR](https://github.com/wazuh/wazuh/pull/16531) and add unit tests for it. I'm closing this issue.
