### ISSUE TITLE
Update python dependencies and code vulnerabilities known flaws

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4216]
### Description

The integration of Dependencies and Code Vulnerability Analysis tests into the PR_Wazuh process is now ready to be merged. You can find the pull request [here](https://github.com/wazuh/wazuh-jenkins/pull/5156). However, before proceeding with the integration, it is crucial to update the known flaws that have been detected, as mentioned in [this issue](https://github.com/wazuh/wazuh-jenkins/issues/5139), across all production branches. This update is necessary to prevent any potential development blocking.

An analysis for the detected flaws in the 4.4 branch has already been conducted. You can find more details in [this comment](https://github.com/wazuh/wazuh-jenkins/issues/5139#issuecomment-1558855223).

**Comment by nico-stefani** [comment]
The code vulnerabilities known flaws are already being issued in #4282

**Comment by nico-stefani** [comment]
We migrated to `Code Scanning Alerts` of GitHub
