### ISSUE TITLE
Update manager statistics format test templates

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-qa#4217]
| Target version |
|----------------|
| 4.8 | 

## Description

The development of the issue https://github.com/wazuh/wazuh/issues/16204 introduces [changes](https://github.com/wazuh/wazuh/pull/16284/files#diff-16ecaa11b00bf069585c4276e961223a8256b87800556f61c667021e2dd95915) in the API Specification that cause the `test_statistics_format.py` API integration test to fail.

We should modify the content of the [statistics templates](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_statistics/data/statistics_template) to match the new API Specification.

> Note: The checks from the issues https://github.com/wazuh/wazuh/issues/16204 and https://github.com/wazuh/wazuh/issues/16285 will fail without these changes.

### Current behavior

```console
=================================== FAILURES ===================================
______________ test_manager_statistics_format[wazuh-db_endpoint] _______________
test_api/test_statistics/test_statistics_format.py:97: in test_manager_statistics_format
    jsonschema.validate(instance=response.json(), schema=stats_schema)
/usr/local/python-3.10/lib/python3.10/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: 'get-groups-integrity' is a required property

=========================== short test summary info ============================
FAILED test_api/test_statistics/test_statistics_format.py::test_manager_statistics_format[wazuh-db_endpoint]
= 1 failed, 65 passed, 21 skipped, 4 deselected, 1 xfailed, 1 xpassed, 1 warning in 1275.69s (0:21:15) =
```

### Expected behavior

The test `test_api/test_statistics/test_statistics_format.py` is executed successfully.

**Comment by GGP1** [comment]
## Update

Removed deprecated commands from the tests and uploaded the changes. Moving the state to on hold until testing is done.

**Comment by GGP1** [comment]
## Update

Updated changelog and fixed linting errors. One of them is still unsolved because of an error in `yamllint`.

**Comment by GGP1** [comment]
## Update

Three integration tests were executed to validate that everything works as expected and these were the results:

🟢  [test_api](https://github.com/wazuh/wazuh-qa/files/12765978/archive.zip)

🟡  [test_authd](https://github.com/wazuh/wazuh-qa/files/12765967/archive.1.zip)

🔴  [test_wazuh_db](https://github.com/wazuh/wazuh-qa/files/12765971/archive.2.zip)

**Comment by GGP1** [comment]
## Update

Resolved changelog conflicts.

**Comment by fdalmaup** [comment]
# Review

The changes carried out in the API-related files in the `wazuh-qa` opened PR were correctly done. Nevertheless, there is a missing PR for the https://github.com/wazuh/qa-integration-framework repository, which has the mentioned templates after the API tests migration to the `wazuh` repository.

**Comment by GGP1** [comment]
## Update

Created 2 pull requests, one in wazuh/qa-integration-framework and other in wazuh/wazuh to apply the same changes to the API tests that we did in wazuh/wazuh-qa.
