### ISSUE TITLE
VD IT `test_download_feeds` fails due to timeout

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4232]
### Description

It has been detected in https://github.com/wazuh/wazuh/issues/17421 that the IT `test_download_feeds` is failing due to a timeout.

It is suggested to increase the metadata `download_timeout` for the `NVD` case

### Evidences

**Report**:  [manager_html_report_Test_integration_B40006_20230607084115.zip](https://github.com/wazuh/wazuh/files/11676019/manager_html_report_Test_integration_B40006_20230607084115.zip)
**Build**: https://ci.wazuh.info/job/Test_integration/40006/

**Comment by davidjiglesias** [comment]
I believe this failure was related to a problem with Debian repositories, closing it for now and will reopen if we need to.
