### ISSUE TITLE
Integration tests for windows agent `test_basic_configuration_reconnect_time` fails

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4233]
### Nightly
| Date | Commit |
| --- | --- |
| 2023-06-10 | https://github.com/wazuh/wazuh/commit/caff3a7e70e78810695d608c4f5c57066c3f1c3b | 

### Description

It seems that the Logcollector `test_basic_configuration_reconnect_time` test is unstable for `4.5` branch.
Further research is required

### Evidences:

- **Build**: https://ci.wazuh.info/job/Test_integration/40157/
- **Report**: [report.zip](https://github.com/wazuh/wazuh-qa/files/11720266/agent_windows_html_report_Test_integration_B40157_20230610023751.1.zip)

**Comment by damarisg** [comment]
We decided to close them.
