### ISSUE TITLE
Document Nightly CI process

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4243]
## Description

It is imperative to create comprehensive documentation for the Nightly CI process. This documentation will serve as a high-level knowledge resource, outlining the key aspects of the Nightly pipeline, its purpose, and the tests it executes.

**Comment by Rebits** [comment]
### 21/06/2023

Apply suggested changes:

- Regarding the objectives: I summarize them in a paragraph because perhaps it didn't make much sense to have multiple very similar elements.

- Regarding the branches launched by the nightly: The title has been changed. It now specifies that it is launched on all development branches of the release. Since we will be working on minors, it doesn't make sense to launch the nightly on 4.4 or 4.5, but rather on the minors being worked on for the release.

- Regarding the tests launched by the nightly: The section has been moved up. It now also specifies exactly which tests should be launched, specifying that the footprint and performance tests are intended for the weekly.

- Added an FAQ section where I include some important points. The dependency between builds has been included here as well.

- Added a section for adding processes to the nightly

**Comment by Rebits** [comment]
### 23/06/2023
- Apply change suggested by @jnasselle regarding testing branches

**Comment by davidjiglesias** [comment]
Initial version approved and published https://sites.google.com/wazuh.com/wazuh-qa-documentation/ci/nightly
