### ISSUE TITLE
 Maintenance of branches and versioning in Wazuh-QA documentation

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4246]
## Description

It is imperative to create comprehensive and understandable documentation regarding the maintenance of branches and versioning in Wazuh-QA.

Following points will be considered:

- Overview of the version control system: Begin by providing a clear and concise introduction to the basics of version control, including its importance and how it is used within the Wazuh-QA repository.

- Terminology and concepts: Define and explain the key terms and concepts related to versioning and branch maintenance in the context of Wazuh-QA. This may include terms such as "branch," "repository," "commit," "merge," "pull," and others.

- Branch creation: Explain the process of creating new branches within the Wazuh-QA repository. Provide step-by-step instructions. Branch conflicts.

- Branching policies: If the Wazuh-QA project follows specific policies or conventions regarding branch usage, document them. This could include guidelines on branch naming, protected branches, and the process for requesting and reviewing branch merges.

- Branch maintenance: Outline best practices for maintaining branches within the Wazuh-QA repository.

Documentation will be uploaded [here](https://sites.google.com/d/1GRTkHqBiB9H1Kii3LTu_2rzfZ3ZRaR_u/p/1EleYYhTOMmuknrUChgNwbgHEZFEccRDe/edit).

**Comment by pro-akim** [comment]
26/06/2023
Documentation written based in:
https://sites.google.com/d/1pfzHAoHqzvtKbMW_ms18FSpLkdkbAsKO/p/19i139B-G7u4CNUWKe261Bnv9PexUthHG/edit

On the other hand, previous versioning criteria were confirmed talking with Julia

**Comment by BelenValdivia** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
Initial version approved and published https://sites.google.com/wazuh.com/wazuh-qa-documentation/maintenance-of-branches-and-versioning
