### ISSUE TITLE
Investigate and document tests - System E2E tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4256]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :yellow_circle: being fixed in https://github.com/wazuh/wazuh-jenkins/issues/5237 |
|Tests state| :yellow_circle: generally working - some skipped modules |
|Jenkins link| https://ci.wazuh.info/job/Test_e2e_system |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the Systems E2E test. Jenkins parameters, pytest location, steps in the test and current state of it.

## State

- The test suite has tests in different states. As described in the comment.
- The pipeline currently has dependency issues so tests have been executed with branch `5237-fix-test_e2e_system-pipeline-due-to-dependency-upgrade-error`
- During release a series of tests are done Manually and are not currently automated. Last tests to have been executed were done in Release `4.4.2-RC1` and are tracked in https://github.com/wazuh/wazuh/issues/16965

## Parameters

- Base general parameters
  - VERBOSITY: verbosity level for logs
  -  JENKINS_REFERENCE: `wazuh-jenkins` repository version
  - ANSIBLE_REFERENCE: Ansible repo version
  - DESTROY_INSTANCES: If checked, instances are destroyed immediately after tests finish
  - MAXIMUM_UPTIME: maximum time Instances will be up.
  - CHECKRUN_REFERENCE
  - DEBUG: enables debug mode.
  - USE_ACTIVE_ENVIRONMENT: If enabled can used Invetory passed in ENVIRONMENT_INVENTORY field for testing
  - ENVIRONMENT_INVENTORY: Enviroment inventory data.
- Base parameters for all tests: 
  - TARGET_PKG_VERSION: Package version to install
  - TARGET_PKG_REVISION: package revision
  - TARGET_REPOSITORY: repository where package is located
- Base parameters for QA tests:
   -QA_REFERENCE: `wazuh-qa` repository branch
- Specific parameters:
  - TESTS: path of tests to be executed
  - TIERS: test tiers to execute. Launch all test tiers by default

**Comment by Deblintrake09** [comment]
## Test Executions

| Module | Result | Notes |
|--|--|--|
| test_audit |[:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/85/) |
| test_aws_infrastructure_monitoring | :black_circle:  | Skipped because of Issue https://github.com/wazuh/wazuh-qa/issues/3211
| test_brute_force |[:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/86/) |
| test_detect_suspicious_binaries | [:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/87/) |
| test_docker | :black_circle:  | Skipped because of Issue https://github.com/wazuh/wazuh-qa/issues/3210
| test_emotet |[:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/88/) |
| test_fim | :black_circle:  | Skipped because of Issue https://github.com/wazuh/wazuh-qa/issues/3207
| test_ip_reputation |[:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/89/) |
| test_osquery_integration |[:large_blue_circle:](https://ci.wazuh.info/job/Test_e2e_system/90/) |

**Comment by Deblintrake09** [comment]
## Manual E2E testing

- During release a series of tests are done Manually and are not currently automated. Last tests to have been executed were done in Release `4.4.2-RC1` and are tracked in https://github.com/wazuh/wazuh/issues/16965

**Comment by verdx** [comment]
LGTM

**Comment by juliamagan** [comment]
We could add that the pipeline not only launches the tests, but also uses `WazuhQAEnvironment` for the necessary provisioning of the tests.

Currently, it only launches the [E2E](https://github.com/wazuh/wazuh-qa/issues/2832) tests, but in the future, this pipeline should be able to launch the system tests as well.

Finally, the pipeline parameters are shown, but not explained.

The link to the spreadsheet with the documentation is in the parent issue.

**Comment by davidjiglesias** [comment]
LGTM!
