### ISSUE TITLE
Migrate VDT IT to System tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4257]
## Description
During the migration of VDT IT tests to the wazuh repository wazuh/wazuh#17403 it was determined that some modules were not IT tests and actually were System tests. This Issue aims to create new system tests from the IT modules. After the new system tests are created, the IT modules should be deleted.

## Test modules to adapt to system tests

- [ ] test_vulnerability_detect/test_feeds/test_download_feeds.py
- [ ] test_vulnerability_detect/test_feeds/test_validate_feed_content.py
- [ ] test_vulnerability_detect/test_feeds/test_msu_inventory.py

## Considerations

- After new system tests are created, the IT modules should be deleted.
- It is important that during research for the creation of new tests, correct and 'reasonable' timeouts are created for all test cases.
   - NVD tests take around 10 minutes because of how large the feed is and download speeds
   - SUSE feeds are located in an FTP server that sometimes takes up to 70 minutes to download the files (usually around 3 mins).

**Comment by davidjiglesias** [comment]
We are already approaching system tests for the different modules, including VD in a different way. For example: https://github.com/wazuh/wazuh-qa/issues/4369
