### ISSUE TITLE
Investigate and document tests - Legacy tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4258]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| No Pipeline |
|Tests state| :yellow_circle:  Passing but some cases are unclear in documentation  |
|Jenkins link||
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the `Legacy` test suite, located in [`wazuh-qa/tests/legacy`](https://github.com/wazuh/wazuh-qa/tree/master/tests/legacy/test_sca). Jenkins parameters, pytest location, steps in the test and current state of it.

## State
- The `legacy` tests suite is not automated and has no associated Jenkins pipeline.
- The Tests consist of a series of SCA checks that need to be copied into the policies file of an Agent and then restart the agent, to force the SCA scan. Results need to be validated manually.
- All checks have passed on Ubuntu20 and Windows Server 2016 agents. But some checks were expected to be skipped because of duplicated IDs but were not.  Possibly this check's IDs are dependent on the OS used.

**Comment by Deblintrake09** [comment]
## Tests executions

<details><summary>sca_commands_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/54d07ef3-3c27-4771-a661-8334908f383a)

</details>

<details><summary>sca_compare_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/5a3fef07-d3b0-41ad-b8a3-dd9039b48e83)


</details>

<details><summary>sca_condition_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/4bf3268c-0b5d-4dfd-bf0d-c644e47b812b)



</details>

<details><summary>sca_directories_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/73c5412d-f1c5-4671-9b02-5f037509ac63)

</details>

<details><summary>sca_files_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/3fd79c1a-c6c0-4780-b02a-9e3298a98fb9)

</details>

<details><summary>sca_negation_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/d120eec7-6719-4a09-a309-b59f6ac465b5)

</details>

<details><summary>sca_processes_test_suite</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/402e856c-40ec-4c1d-a7ba-22edeee470a6)

</details>


<details><summary> :yellow_circle: sca_repeated_global_ids_1</summary>

- Copy checks to agent's policy file and restart agent
- Check scan results
![imagen](https://github.com/wazuh/wazuh-qa/assets/14501079/efbe04ec-ef49-44c3-bfc1-35f66066f2f0)

**NOTE:** This suite's checks do not match the suite's description.
</details>

**Comment by verdx** [comment]
LGTM

**Comment by QU3B1M** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
