### ISSUE TITLE
 Investigate and document tests - Performance Tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4260]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :green_circle:   |
|Tests state| :yellow_circle:   |
|Jenkins link| https://ci.wazuh.info/view/Tests/job/CLUSTER-Workload_benchmarks_metrics|
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the `performance` test suite, located in [`wazuh-qa/tests/performance`](https://github.com/wazuh/wazuh-qa/tree/master/tests/performance Jenkins parameters, pytest location, steps in the test and current state of it.

## Suite State
- The Pipeline launches the `performance` using the [test_culster.groovy](https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/performance/test_cluster.groovy) script.
- The performance/test_api.py tests are working and passing in 4.4.4. 
- The performance/test_cluster.py tests are failed in 4.4.4., but from the logs it seems to be a pipeline related error.

## Pipeline Parameters
- Base general parameters 
   - VERBOSITY
   - JENKINS_REFERENCE
   - DESTROY_INSTANCES
- Base parameters for all tests: 
   - TARGET_PKG_VERSION
   - TARGET_PKG_REVISION
   - TARGET_REPOSITORY: package location
   - MANAGERS_AWS_DEPLOYMENT: EC2 or ECS
   - MANAGER_INSTANCES: Type of AWS instance used for Managers
   - AGENT_INSTANCES: Type of AWS instance used for Agents
   - DEVELOPMENT Set an ECR image name and use the CUSTOM_IMAGE parameter to use an alternative ECR image.
      - CUSTOM_IMAGE
   - CUSTOM_TASK_DEFINITION_API: Set an ECS Task Definition name to use an alternative ECS Task Definition.
   - CUSTOM_TASK_DEFINITION_SIMULATE
   - CUSTOM_TASK_DEFINITION_VISUALIZATION: Set an ECS Task Definition name to use an alternative ECS Task Definition.
- Base parameters for QA tests: 
   - QA_REFERENCE: wazuh-qa branch
   - LOCAL_INTERNAL_OPTIONS_CONFIG
- Specific parameters: 
   - TEST_TIME: Time that tests will run (in seconds)
   - LOAD_BALANCER: `elb` or `wazuh_proxy`
   - PROTOCOL: `TCP` or `UDP`
   - OS: Manager OS (default Debian10)
   - AGENT_SIMULATED_VERSION:
   - LABELS: Labels to identify agents 
   - KEEP_ALIVE_INTERVAL: Interval for agent keepalive
   - EVENTS_SIZE: default 0
   - MODE: type of events (AGENTS, EPS, HYBRID)
   - AGENTS_NUMBER: Cluster tests require 50000 agents
   - MANAGER_WORKERS: Cluster tests require 20 or 25 workers.
   - PARSE_CLUSTER_LOGS (checkbox):  Extract cluster statistics and create their corresponding charts
   - CLUSTER_TESTS: Type of tests to launch (performance, reliability)
   - TEST_PERFORMANCE_API_ENDPOINTS: Launch `wazuh-qa/tests/test_performance/test_api` tests
   - KIBANA_API_REQUESTS: Adittional Kibana API requests
   - EXTRA_LOAD_API_REQUESTS: Adittional Wazuh API requests
   - API_REQUESTS_PERCENTAGE: Percentage of extra Load API requests
   - QUEUES: EPS to send each simulated agent on through a given queue
   - MANAGER_MONITORING_PROCESSES: Manager process to monitor
   - MANAGER_MONITORING_STATS: Stats to monitor (Options: remote, analysis, logcollector)
   - LOGGING: log file to monitor (alerts.log, archives.log, archives.json)
   - GROUPS_NUMBER
   - FILES_NUMBER_PER_GROUP
   - BYTES_NUMBER_PER_FILE

**Comment by Deblintrake09** [comment]
## Test API Results

**Pipeline Execution:** https://ci.wazuh.info/view/Tests/job/CLUSTER-Workload_benchmarks_metrics/258/
**Execution Artifacts:** 
[artifacts.zip](https://github.com/wazuh/wazuh-qa/files/11919450/artifacts.zip)

## Parameters Used
**Fields that are not present where left unchanged**
- TARGET_PKG_VERSION: 4.4.4
- TARGET_PKG_REVISION: 1
- TARGET_REPOSITORY: pre-release
- JENKINS_REFERENCE: 4.4
- QA_REFERENCE: 4.4
- LOAD_BALANCER: wazuh_proxy
- AGENT_SIMULATED_VERSION: 4.4.4
- MODE: Hybrid
- AGENTS_NUMBER: 40000
- MANAGER_WORKERS: 20 
- PARSE_CLUSTER_LOGS
- CLUSTER_TESTS: checked
- KIBANA_API_REQUESTS: unchecked
- TEST_PERFORMANCE_API_ENDPOINTS: checked
- EXTRA_LOAD_API_REQUESTS: unchecked
- MANAGERS_AWS_DEPLOYMENT: EC2
- MANAGER_INSTANCES: c5xlarge (4 vCPUs - 8GB)
- AGENT_INSTANCES: c5xlarge (4 vCPUs - 8GB)

**Comment by Deblintrake09** [comment]
## Test cluster Results

**Pipeline Execution:** https://ci.wazuh.info/view/Tests/job/CLUSTER-Workload_benchmarks_metrics/261/
**Execution Artifacts:** 


## Parameters Used
**Fields that are not present where left unchanged**
- TARGET_PKG_VERSION: 4.4.4
- TARGET_PKG_REVISION: 1
- TARGET_REPOSITORY: pre-release
- JENKINS_REFERENCE: 4.4
- QA_REFERENCE: 4.4
- LOAD_BALANCER: wazuh_proxy
- AGENT_SIMULATED_VERSION: 4.4.4
- MODE: Hybrid
- AGENTS_NUMBER: 40000
- MANAGER_WORKERS: 20 
- PARSE_CLUSTER_LOGS
- CLUSTER_TESTS: performance
- KIBANA_API_REQUESTS: unchecked
- TEST_PERFORMANCE_API_ENDPOINTS: checked
- EXTRA_LOAD_API_REQUESTS: unchecked
- MANAGERS_AWS_DEPLOYMENT: EC2
- MANAGER_INSTANCES: c5xlarge (4 vCPUs - 8GB)
- AGENT_INSTANCES: c5xlarge (4 vCPUs - 8GB)

**Comment by verdx** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM
