### ISSUE TITLE
Investigate and document tests - Scan_build

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#4261]
|||
|-----|----|
| Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
| Pipeline state | [Analysis_static_scanbuild 🟢](https://github.com/wazuh/wazuh-qa/issues/4261#issuecomment-1615121548) - [Test_RTR_scanbuild  🟢](https://github.com/wazuh/wazuh-qa/issues/4261#issuecomment-1615272734) |
| Tests state | [Analysis_static_scanbuild 🟢 ](https://github.com/wazuh/wazuh-qa/issues/4261#issuecomment-1615121548) - [Test_RTR_scanbuild 🟢](https://github.com/wazuh/wazuh-qa/issues/4261#issuecomment-1615272734) |
| Jenkins link | [Analysis_static_scanbuild](https://ci.wazuh.info/job/Analysis_static_scanbuild/1148) - [Test_RTR_scanbuild-1](https://ci.wazuh.info/job/Test_RTR_scanbuild/6589/) - [Test_RTR_scanbuild-2](https://ci.wazuh.info/job/Test_RTR_scanbuild/6590/) - [Test_RTR_scanbuild-3](https://ci.wazuh.info/job/Test_RTR_scanbuild/6591/) |
| Branch used | 4.4 |

## Description 

This issue aims to analyze and document all about the Scan_build tests. Jenkins parameters, pytest location, steps in the test, and current state of it. Also, manual execution is required.

## State 🟢

> **scan-build** is a command line utility that enables a user to run the static analyzer over their codebase as part of performing a **regular build**. In other words, scan-build analyzes the source files compiled by `gcc`/`clang` during a project build.

So, the **Scan_build** is executed in the daily development tasks (when a new change is introduced to the sources or when a new PR is created, for instance).

There are 3 existing pipelines executing "scan-build":

1. [Analysis_static_scanbuild](https://ci.wazuh.info/job/Analysis_static_scanbuild/): Executed in the Nightly pipeline. It was the first to execute "scan-build" (only with a manager). It is a script that runs into a container that runs this command over the Wazuh codebase.
2. [Test_RTR_scanbuild](https://ci.wazuh.info/job/Test_RTR_scanbuild/): Executed in the PR_Wazuh pipeline. It also runs the "scan-build" utility but allows one to select a manager or an agent (Linux and Windows). It is a script that runs another script ([build.py](https://github.com/wazuh/wazuh/blob/master/src/build.py)) which runs the CLI utility with different options (one of them, the `target` to be compiled and analyzed)
3. [scan-build.yml](https://github.com/wazuh/wazuh/blob/master/.github/workflows/scan-build.yml): It is a GitHub action. It's owned by the Core team and it's the newer one (very likely will remain as the only one executing the "scan-build"). It runs the "scan-build" CLI utility directly to run the analysis over the Wazuh codebase.

> **Note**: The last one won't be analyzed by our team because it's not owned by us.

Both **Analysis_static_scanbuild** and **Test_RTR_scanbuild** work and run the tests properly.

**Comment by mauromalara** [comment]
## Pipelines

There are 3 existing pipelines doing "scan-build":

- https://ci.wazuh.info/job/Analysis_static_scanbuild/: Executed in the Nightly pipeline. It was the first to do "scan-build".
- https://ci.wazuh.info/job/Test_RTR_scanbuild/: Executed in the PR_Wazuh pipeline (most used by the team)
- https://github.com/wazuh/wazuh/blob/master/.github/workflows/scan-build.yml: It is a GitHub action. It's owned by the Core team and it's the newer one (very likely will remain as the only executing the "scan-build")

**Comment by mauromalara** [comment]
## Analysis_static_scanbuild

### Parameters

**General parameters**

- SOURCE_REFERENCE
- JENKINS_REFERENCE
- TASK_DEFINITION_SUFFIX
- DEVELOPMENT (bool): Allow the use of development ECR images - depends on CUSTOM_IMAGE

**Specific parameters**

- SCAN_BUILD_PARAMETERS: by default -> `maxloop=10 source-target=agent custom-flag="--track-origins=yes --leak-check=full --keep-stacktraces=alloc-and-free --show-leak-kinds=definite,indirec"`
- CUSTOM_IMAGE

**Comment by mauromalara** [comment]
# Test_RTR_scanbuild

## Parameters

**General parameters**

- SOURCE_REFERENCE
- JENKINS_REFERENCE
- CHECKRUN_REFERENCE
- CUSTOM_TASK_DEFINITION

**Specific parameters**

- TARGET
- MODULE

## Execution

**Status**

The pipeline is working properly and the tests pass.

```
------ Creating required directories ------
.............................DONE
------ Cloning repository ------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2258k    0 2258k    0     0  2780k      0 --:--:-- --:--:-- --:--:-- 2780k
100 8561k    0 8561k    0     0  4719k      0 --:--:--  0:00:01 --:--:-- 6296k
100 11.0M    0 11.0M    0     0  4822k      0 --:--:--  0:00:02 --:--:-- 5910k
------ Run winagent tests with --scanbuild flag ------
[95m<winagent>=================== Running Scanbuild   ===================<winagent>[0m
[92m[CleanAll: PASSED][0m
[92m[CleanExternals: PASSED][0m
[92m[MakeDeps: PASSED][0m
[92m[MakeTarget: PASSED][0m
[92m[CleanInternals: PASSED][0m
[92m[ScanBuild: PASSED][0m
[92m<winagent>[SCANBUILD: PASSED]<winagent>[0m
.............................DONE
```

```
------ Creating required directories ------
.............................DONE
------ Cloning repository ------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2325k    0 2325k    0     0  2842k      0 --:--:-- --:--:-- --:--:-- 2842k
100 8624k    0 8624k    0     0  4740k      0 --:--:--  0:00:01 --:--:-- 6292k
100 11.0M    0 11.0M    0     0  4744k      0 --:--:--  0:00:02 --:--:-- 5742k
------ Run agent tests with --scanbuild flag ------
[95m<agent>=================== Running Scanbuild   ===================<agent>[0m
[92m[CleanAll: PASSED][0m
[92m[CleanExternals: PASSED][0m
[92m[MakeDeps: PASSED][0m
[92m[ScanBuild: PASSED][0m
[92m<agent>[SCANBUILD: PASSED]<agent>[0m
.............................DONE
```


```
------ Creating required directories ------
.............................DONE
------ Cloning repository ------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4881k    0 4881k    0     0  4078k      0 --:--:--  0:00:01 --:--:-- 5116k
100 10.4M    0 10.4M    0     0  4843k      0 --:--:--  0:00:02 --:--:-- 5445k
100 11.0M    0 11.0M    0     0  4888k      0 --:--:--  0:00:02 --:--:-- 5467k
------ Run server tests with --scanbuild flag ------
[95m<server>=================== Running Scanbuild   ===================<server>[0m
[92m[CleanAll: PASSED][0m
[92m[CleanExternals: PASSED][0m
[92m[MakeDeps: PASSED][0m
[92m[ScanBuild: PASSED][0m
[92m<server>[SCANBUILD: PASSED]<server>[0m
.............................DONE
```

**Comment by QU3B1M** [comment]
LGTM! 🚀

**Comment by davidjiglesias** [comment]
LGTM
