### ISSUE TITLE
Investigate and document tests - API integration

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4264]
|||
|-----|----|
| Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
| Pipeline state | 🟡  |
| Tests state | 🔴  |
| Jenkins link | https://ci.wazuh.info/view/Tests/job/Test_integration_endpoints/ |
| Branch used | `master` |

## Description 
The `API integration tests` are defined on `yamls` under the path `/api/test/integration/` located in the [`/wazuh`](https://github.com/wazuh/wazuh) repo, this suite is executed by the pipeline [`Test_integration_endpoints`](https://ci.wazuh.info/view/Tests/job/Test_integration_endpoints/) that is triggered when changes on `/api` folder are detected.
> Groovy pipeline definition: [`test_integration_api.groovy`](https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/test_integration_api.groovy)

## State
This pipeline is currently **on use**, working and being executed on [`wazuh/wazuh`](https://github.com/wazuh/wazuh) PRs in the _development stage_ when there is any modification to the `/api` folder on the `/wazuh` repo.
The test suite and the pipeline require to be fixed and improved, the _pipeline_ raises **`passing`** results even when several test cases are failing, and in the _test suite_ we have scenarios that always fails. _More info in [this comment](https://github.com/wazuh/wazuh-qa/issues/4264#issuecomment-1620731151)_ 

## Tests purpose
Verify the correct behavior and functionality of all the **wazuh API** endpoints, interacting with them via API requests.

## Parameters
- General parameters
  - `SOURCE_REFERENCE:` _[`wazuh`](https://github.com/wazuh/wazuh) branch/tag where the test will be executed. default: `v4.0.3`_
  - `JENKINS_REFERENCE:` _[`wazuh-jenkins`](https://github.com/wazuh/wazuh-jenkins) (automation scripts) branch/tag. default: `master`_
  - `CHECKRUN_REFERENCE:` _Reference of the [GitHub action](https://github.com/wazuh/wazuh/actions) check used to validate a PR. default: `''`_
- Test specific parameters
  - `PYTEST_ARGS:` _Pytest command line arguments. default: `-v --tb=short`_
  - `TEST_LIST:` _List of the tests to run separated by coma. default: `''`_
  - `VERBOSITY:` _Logging level. default: `''`_

**Comment by QU3B1M** [comment]
## Executions

Work in progress: _Currently the pipeline is not working! While this is fixed I resumed the work on github actions on the issue wazuh/wazuh#17747_

**Comment by QU3B1M** [comment]
- Execute tests with invalid test names - Passed 🔴 [link](https://ci.wazuh.info/view/Tests/job/Test_integration_endpoints/3463/parameters/)
- Execute all the tests at once - Unestable 🟡 [link](https://ci.wazuh.info/view/Tests/job/Test_integration_endpoints/3464/console)
- Execute tests one by one - Work in progress ⚪

**Comment by QU3B1M** [comment]
- Execute tests one by one ⚪ 
- Many tests have failed 🔴 
- It does not matter if the tests passes or not, the pipeline goes green

**Comment by mauromalara** [comment]
## Review comment No.1

### State

> This pipeline is currently working and being executed when there is any modification to the /api folder on the /wazuh repo.

There is no general description of the state of the tests. Please, add one as you made here: https://github.com/wazuh/wazuh-qa/issues/4264#issuecomment-1620731151

Also, specify at which stage of the development cycle the tests are being executed.

## Parameters

> JENKINS_REFERENCE: Jenkins branch/tag. default: master

Makes reference to the wazuh-jenkins branch/tag not to `Jenkins` (the software).

> CHECKRUN_REFERENCE: GitHub check reference. default: ''

Add a description for everyone (e.g: what’s a check run?)

**Comment by QU3B1M** [comment]
### Applied requested changes 
- Parameters:
  - Improve descriptions ✔️ 
  - Reference the correspondent repos ✔️

**Comment by mauromalara** [comment]
## Review comment No.2

LGTM 🚀

**Comment by davidjiglesias** [comment]
LGTM!
