### ISSUE TITLE
Investigate and document tests - Install Tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4265]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :yellow_circle:   |
|Tests state| :green_circle:  |
|Jenkins link| https://ci.wazuh.info/job/Test_install_tier/ and https://ci.wazuh.info/job/Test_install/  |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the `Install` test suite, located in [`wazuh-jenkins/jenkins-files/tests/test_install.groovy`](https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/test_install.groovy) Jenkins parameters, pytest location, steps in the test and current state of it.

## State
- **What is being tested:** The pipeline test the installation process of agent and manager in different OSs and architectures (Combinations can be seen in the [comment](https://github.com/wazuh/wazuh-qa/issues/4265#issuecomment-1618638761)).
- Some of the tests showing failures while installing dependencies on some OSs and architectures. 
- The pipeline does not gather artifacts from the installed instances, and checking the results needs to be done manually. An improvement would be to gather the artifacts of Failing executions, so there is a clearer and faster way to verify the results.
- Testing on macOS systems is only automated in macOS 15 (Catalina), other versions (Sierra, High Sierra, Mojave, Big Sur, Monterrey and Ventura) are tested manually.

## Parameters for Test_install
- Base general parameters 
   - VERBOSITY
   - DESTROY_INSTANCES
   - JENKINS_REFERENCE
- Base parameters for all tests: 
   - TARGET_PKG_VERSION: Package version
   - TARGET_PKG_REVISION: Pakage revision 
   - TARGET_API_PKG_REVISION: API Revision
   - TARGET_REPOSITORY: Repository where package is located
   - ARCHITECTURE: Architecture for the Manager and agent Instances
   - MANAGER_SYSTEM: Manager OS (Ex: Centos, Debian, etc).
   - MANAGER_SYSTEM_VERSION: Manager OS sub version (Ex: Centos 8, 7, 6, 5)
   - AGENT_SYSTEM: Agent OS (Ex: Centos, Debian, etc).
   - AGENT_SYSTEM_VERSION: Agent OS sub version (Ex: Centos 8, 7, 6, 5)
- Specific parameters: 
   - CHECK_MANAGER: Check manager installation
   - CHECK_API: Check API after installation
   - CHECK_AGENT: Check agent installation

## Parameters for Test_install_tier

- Base general parameters 
   - DESTROY_INSTANCES
   - JENKINS_REFERENCE
- Base parameters for all tests: 
   - TARGET_VERSION
   - TARGET_PKG_REVISION
   - TARGET_REPOSITORY
   - TIER
- Specific parameters: 
   - ARCHITECTURE: OS architecture to be used. depending on the Arch tests are executed in different OSs.
   - TIER_CUSTOM_OS: OSs tests to be executed on for the selected architecture.
   - CHECK_MANAGER: Test manager installation
   - CHECK_API: Test API works after installation.
   - CHECK_AGENT: Test agent installation
   - REVISION:

**Comment by Deblintrake09** [comment]
# Tests Executions


- https://ci.wazuh.info/job/Test_install_tier/612/
- https://ci.wazuh.info/job/Test_install_tier/613/
-  https://ci.wazuh.info/job/Test_install_tier/614/
- `arm32v7`: https://ci.wazuh.info/job/Test_install_tier/615/

| System              | AMD64 | ARM64 | I386 | ARM32 |
| :--                 | :--:  | :--:  | :--: | :--:  |
| Amazon Linux 1      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Amazon Linux 2      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| CentOS 5            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 6            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 7            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 8            | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Debian 7            | :green_circle:    | :green_circle:    | :green_circle:   | :black_circle:    |
| Debian 8            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Debian 9            | :green_circle:    | :green_circle:    | :green_circle:   | :red_circle:    |
| Debian 10           | :green_circle:    | :black_circle:    | :red_circle:   | :black_circle:    |
| Debian 11           | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Fedora 29           | :green_circle:    | :green_circle:    | :black_circle:   | :green_circle:    |
| Fedora 31           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 32           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 34           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 35           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 36           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| openSUSE Tumbleweed | :red_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 6      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 7      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 8      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 6           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 7           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 8           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 9           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Solaris 11          | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Solaris 10          | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Bionic       | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Focal        | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Precise      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Trusty       | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Ubuntu Xenial       | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Windows 2016        | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| macOS 10.15         | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |

**Comment by verdx** [comment]
LGTM

**Comment by QU3B1M** [comment]
LGTM! 🚀

**Comment by davidjiglesias** [comment]
LGTM!
