### ISSUE TITLE
Investigate and document tests - Upgrade Metrics

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4267]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :yellow_circle:    |
|Tests state| :yellow_circle:    |
|Jenkins link| https://ci.wazuh.info/job/Test_upgrade and https://ci.wazuh.info/job/Test_upgrade_tier|
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the `Upgrade` test suite, located in [`wazuh-jenkins/jenkins-files/tests/test_upgrade.groovy`](https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/test_upgrade.groovy), Jenkins parameters, pytest location, steps in the test and current state of it.

## Tests State :yellow_circle: 
- Tests as of Release 4.4.4-RC2 are :green_circle: (With the exceptions of failures related to pipeline errors or errors related to the instance configuration).
- Testing on macOS and WPK testing is being done manually. Needs to be automated.

## Pipeline State
- **test_upgrade** :yellow_circle: 
   - The pipeline is working properly.
   - Generates reports properly.
- **test_upgrade_tier** :yellow_circle: 
   - Is working correctly and launches all needed instances as expected and correctly configured with parameters passed.
   - Does not generate any kind of report. When launching the whole pipeline there are 800+ test_upgrade instances to check manually. Some kind of report is needed ASAP.

## Parameters for Test_upgrade_tier
- Base general parameters 
   - JENKINS_REFERENCE
   - TIER
- Base parameters for all tests: 
   - TIER_CUSTOM_TARGET: Package version that we want to upgrade to. Ex: 4.4.4
   - TARGET_PKG_REVISION: Upgraded version revision. Ex: 1
   - TARGET_REPOSITORY: Repository where package is located. Default: `pre-release`
   - INSTAL_REPOSITORY: Repository where the package to install is located. Default: `Live`
   - TIER_CUSTOM_OS: Target OS where upgrade will be tested.
   - TIER_CUSTOM_VERSION: Version to installed to later upgrade. EX: Install 4.4.3 to upgrade to 4.4.4
   - TIER_SLEEP: Time to wait between install and upgrade. Default: 1
   - CHECK_API: Check API after installation. default: checked

## Parameters for Pipeline Test_upgrade
- Base general parameters 
   - JENKINS_REFERENCE: Jenkins Version
   - VERBOSITY
   - TIER
   - DESTROY_INSTANCES
- Base parameters for all tests: 
   - MANAGER_ARCHITECTURE: Manager Architecture
   - MANAGER_SYSTEM: Target OS where upgrade will be tested. Ex: Debian, Centos, etc.
   - MANAGER_SYSTEM_VERSION: Manager OS version. Ex.: `8` for `Centos 8`.
   - AGENT_ARCHITECTURE: Manager Architecture
   - AGENT_SYSTEM: Target OS where upgrade will be tested.
   - AGENT_SYSTEM_VERSION: Agent OS version. Ex.: `8` for `Centos 8`.
   - ORIGINAL_PKG_VERSION: Version to installed to later upgrade. EX: Install 4.4.3 to upgrade to 4.4.4
   - TARGET_PKG_VERSION: Package version that we want to upgrade to. Ex: 4.4.4
   - INSTALL_REPOSITORY: Repository where the package to install is located. Default: `Live`
   - TARGET_REPOSITORY: Repository where package is located. Default: `pre-release`
   - TARGET_PKG_REVISION: Upgraded version revision. Ex: 1
   - TARGET_API_PKG_REVISION: Upgraded API version revision. Ex: 1

**Comment by Deblintrake09** [comment]
## Research done on Pipeline Test_upgrade

- This pipeline is being executed as part of:
   - test_upgrade_tier
   - Nightly pipeline https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/test_nightly.groovy

**Comment by Deblintrake09** [comment]
## Research done on Pipeline test_install_tier

- The pipeline does not generate artifacts, either when tests pass or fail. In order to check results, the user has to go into the Console, and open and check each `test_upgrade` executed instance manually. 
   - When launching the full suite during Release process, There are 800+ executions to check manually. Some kind of report is needed ASAP.
   - A simple list of failing executions names (with each execution link) would be a great advance. The names could be gathered from the console, as when an execution fails there is a message in the console.

**Comment by QU3B1M** [comment]
LGTM! 🚀

**Comment by verdx** [comment]
LGTM! :rocket:

**Comment by davidjiglesias** [comment]
LGTM!
