### ISSUE TITLE
Investigate and document tests - Stress test

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4276]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :yellow_circle: |
|Tests state| :green_circle: |
|Jenkins links| https://ci.wazuh.info/job/Test_stress/
||https://ci.wazuh.info/job/Test_stress_gh/
||https://ci.wazuh.info/job/Test_stress_AIX/
||https://ci.wazuh.info/job/Test_stress_tier/
||https://ci.wazuh.info/job/Test_stress_vagrant/|
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the Stress test. Working state and parameters of the different pipelines mainly. 

## State

There are four different pipelines related to the Stress tests:
- Test_Stress: The basic Stress test launches the test defined on the same `wazuh-jenkins` repository
- Test_stress_gh: This pipeline creates the issues or adds the comments for the rest of tests.
- Test_stress_AIX: The stress test but for AIX OS. It is run on an AIX machine for which the IP and credentials must be given
- Test_stress_vagrant: This test is done on vagrant machines, where macOS and windows machines can be used.

There is another pipeline, which runs a tier of tests, but it has been covered in https://github.com/wazuh/wazuh-qa/issues/4280

<details>
<summary>Tests launched</summary>

- :red_circle: Test_stress_gh https://ci.wazuh.info/job/Test_stress_gh/1152/console
- :green_circle: Test_stress: https://ci.wazuh.info/job/Test_stress/4077
- :red_circle: Test_stress_vagrant: https://ci.wazuh.info/job/Test_stress_Vagrant/132
- :red_circle: Test_stress_tier: https://ci.wazuh.info/job/Test_stress_tier/70/
</details>

**Comment by verdx** [comment]
## :green_circle: Test_stress_gh

### Description
This test supposedly launches a stress test for the Test_duration and can create an issue or put a comment on one in repos `wazuh` or `wazuh-jenkins`. Most of the parameters are related to this. 

It is called by Test_stress to create the issue or add the commentary


### State
A test has been manually launched and failed, but when it has been called from the Test_stress or the Test_stress_tier, it works correctly.

### Parameters

- Base general parameters
  - JENKINS_REFERENCE
- Base parameters for all tests: 
  - WAZUH_VERSION
  - TARGET_PKG_REVISION
  - REPOSITORY
- Specific parameters:
  - MANAGER_INSTANCE: [centos, ubuntu, aix]
  - TEST_DURATION
  - GITHUB_ACTION: [None, Create new issue, Add comment to existing issue]
  - ISSUE_NUMBER
  - RC
  - RC_ISSUE
  - FOOTPRINT_ISSUE
  - GITHUB_REPO
  - ORIGINAL_JOB_NAME
  - ORIGINAL_BUILD_NUMBER
  - EFS_PATH
  - S3_DATA_PATH
  - SYSTEMS: [manager, centos, ubuntu, windows]
  - SYSTEMS: [ROOTCHECK, SYSCOLLECTOR, DOCKER-LISTENER, CIS-CAT, OSQUERY, AZURE-LOGS, OPEN-SCAP, VULNERABILITY-DETECTOR, VULNERABILITY-DETECTOR-REGISTER]

**Comment by verdx** [comment]
## :green_circle: Test_stress

### Description

This test launches the test defined on the `wazuh-jenkins` repository on the machines specified for the time of `TEST_DURATION`. It creates a report and calls `Test_stress_gh` to create an issue or add a comment to an existing one on `wazuh` or `wazuh-jenkins`. It uses as parameters different configurations for the different modules that have been selected, as well as the necessary parameters so that `Test_stress_gh` can be called.

### State

The pipeline works correctly when launched, and it has been used correctly in all recent release testings. The results are copied to the Footprint test issues of the release candidates testing. For example: https://github.com/wazuh/wazuh/issues/16570

### Parameters

- Base general parameters
  - JENKINS_REFERENCE
  - VERBOSITY
  - DESTROY_INSTANCES
- Base parameters for all tests: 
  - WAZUH_VERSION
  - TARGET_PKG_REVISION
  - REPOSITORY
- Specific parameters:
  - MANAGER_INSTANCE: [centos, ubuntu]
  - LAUNCH_CENTOS_AGENT
  - LAUNCH_UBUNTU_AGENT
  - LAUNCH_WINDOWS_AGENT
  - WINDOWS_VERSION: [2019, 2016, 2012]
  - WINDOWS_PACKAGE_REVISION
  - TEST_DURATION
  - FREQUENCY_SCAN
  - MODULES: [SYSCHECK, LOGCOLLECTOR, SCA, ACTIVE-RESPONSE, ROOTCHECK, SYSCOLLECTOR, DOCKER-LISTENER, CIS-CAT, OSQUERY, AZURE-LOGS, OPEN-SCAP, VULNERABILITY-DETECTOR, VULNERABILITY-DETECTOR-REGISTER]
  - TEST_MGR_MODULES
  - <details>
    <summary>Module configuration parameters</summary>
    
    - SYSCHECK_TEST: [SYSCHECK_WAZUH, SYSCHECK_ALL_REALTIME, SYSCHECK_ALL_WHODATA, SYSCHECK_DUPLICATED_ENTRIES]
    - LOGCOLLECTOR_HARD
    - LOGCOLLECTOR_FEED
    - FIM_SLEEP
    - FIM_MAX_FILES
    - SCA_SLEEP
    - SCA_MAX_REGISTERS
    - DOCKER_IMAGE_NAME
    - DOCKER_SLEEP
    - DOCKER_JOBS
    - LOGCOLLECTOR_MAX_FILES
    - LOGCOLLECTOR_CREATION_SLEEP
    - LOGCOLLECTOR_WRITE_FILES
    - LOGCOLLECTOR_WRITE_SLEEP
    - VULN_SLEEP
    - AUTHD_PORT
    - SYSCOLLECTOR_PACKAGE
    - SYSCOLLECTOR_PACKAGE_VERSION
    - MANAGER_CUSTOM_CONFIGURATION
    - CENTOS_AGENT_CUSTOM_CONFIGURATION
    - UBUNTU_AGENT_CUSTOM_CONFIGURATION
    - WINDOWS_AGENT_CUSTOM_CONFIGURATION
    </details>
  - ADDITIONAL_CHART_INFO
  - CONTAINER_SUFFIX
  - GITHUB_ACTION: [None, Create new issue, Add comment to existing issue]
  - ISSUE_NUMBER
  - RC
  - RC_ISSUE
  - FOOTPRINT_ISSUE
  - GITHUB_REPO
  - EXTRA_LABELS
  - CUSTOM_TASK_DEFINITION

**Comment by verdx** [comment]
## :yellow_circle:  Test_stress_AIX

### Description

This test launches the test defined on the `wazuh-jenkins` repository on the machines specified for the time of `TEST_DURATION`. It creates a report and calls `Test_stress_gh` to create an issue or add a comment to an existing one on `wazuh` or `wazuh-jenkins`. It uses as parameters different configurations for the different modules that have been selected, as well as the necessary parameters so that `Test_stress_gh` can be called. Instead of launching machines in EC2, this pipeline takes an IP and a user and password to connect to a previously created machine.

### State

The pipeline is being developed in issue https://github.com/wazuh/wazuh-jenkins/issues/4653, now in review.

### Parameters

- Base general parameters
  - JENKINS_REFERENCE
  - VERBOSITY
  - DESTROY_INSTANCES
- Base parameters for all tests: 
  - WAZUH_VERSION
  - TARGET_PKG_REVISION
  - REPOSITORY
- Specific parameters:
  - MANAGER_INSTANCE
  - AIX_HOST
  - AIX_PORT
  - AIX_USER
  - AIX_PASSWORD
  - LAUNCH_CENTOS_AGENT
  - LAUNCH_UBUNTU_AGENT
  - LAUNCH_WINDOWS_AGENT
  - WINDOWS_VERSION: [2019, 2016, 2012]
  - WINDOWS_PACKAGE_REVISION
  - TEST_DURATION
  - FREQUENCY_SCAN
  - MODULES: [SYSCHECK, LOGCOLLECTOR, SCA, ACTIVE-RESPONSE, ROOTCHECK, SYSCOLLECTOR, DOCKER-LISTENER, CIS-CAT, OSQUERY, AZURE-LOGS, OPEN-SCAP, VULNERABILITY-DETECTOR, VULNERABILITY-DETECTOR-REGISTER]
  - TEST_MGR_MODULES
  - <details>
    <summary>Module configuration parameters</summary>
    
    - SYSCHECK_TEST: [SYSCHECK_WAZUH, SYSCHECK_ALL_REALTIME, SYSCHECK_ALL_WHODATA, SYSCHECK_DUPLICATED_ENTRIES]
    - LOGCOLLECTOR_HARD
    - LOGCOLLECTOR_FEED
    - FIM_SLEEP
    - FIM_MAX_FILES
    - SCA_SLEEP
    - SCA_MAX_REGISTERS
    - DOCKER_IMAGE_NAME
    - DOCKER_SLEEP
    - DOCKER_JOBS
    - LOGCOLLECTOR_MAX_FILES
    - LOGCOLLECTOR_CREATION_SLEEP
    - LOGCOLLECTOR_WRITE_FILES
    - LOGCOLLECTOR_WRITE_SLEEP
    - VULN_SLEEP
    - AUTHD_PORT
    - SYSCOLLECTOR_PACKAGE
    - SYSCOLLECTOR_PACKAGE_VERSION
    - MANAGER_CUSTOM_CONFIGURATION
    - CENTOS_AGENT_CUSTOM_CONFIGURATION
    - UBUNTU_AGENT_CUSTOM_CONFIGURATION
    - WINDOWS_AGENT_CUSTOM_CONFIGURATION
    </details>
  - ADDITIONAL_CHART_INFO
  - CONTAINER_SUFFIX
  - GITHUB_ACTION: [None, Create new issue, Add comment to existing issue]
  - ISSUE_NUMBER
  - RC
  - RC_ISSUE
  - FOOTPRINT_ISSUE
  - GITHUB_REPO
  - EXTRA_LABELS
  - CUSTOM_TASK_DEFINITION
  - ARCHITECTURE
  - PROVISION_AIX
  - AIX_REPOSITORY_PATH

**Comment by verdx** [comment]
# Update 05/06/23

The tests have been finished and the three pipelines have been analyzed and described.

**Comment by davidjiglesias** [comment]
This is going to be done and continued as part of the Jenkins redesign followed by the refactor of Footprint (Performance testing tier 1).
