### ISSUE TITLE
 Investigate and document tests - Check Files

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4277]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :yellow_circle:   |
|Tests state| :yellow_circle:      |
|Jenkins link| |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the `Check Files` test suite, located in [`wazuh-qa/tests/check_files`](https://github.com/wazuh/wazuh-qa/tree/master/tests/check_files). Also Jenkins automation state,  Jenkins parameters, pytest location, steps in the test and current state of it.

The wazuh-jenkins repository contains a different version of the `Check Files` located in https://github.com/wazuh/wazuh-jenkins/blob/master/quality/tests/generic/common_files/check_files.py. This test will also be researched as part of this issue.

## State of check_files in `wazuh-qa` :red_circle: 

- The test execution was not automated and has no current pipeline. They have to be launched locally an manually.
- The tests use the `qa-ctl` tool that is currently deprecated and not working. It could be adapted automated using the current [Deployer pipeline](https://ci.wazuh.info/job/Deployer/).
-  When executing the tests `check_files` script did not finish.
- For more details, [check comment below](https://github.com/wazuh/wazuh-qa/issues/4277#issuecomment-1620625759).

## State of check_files in `wazuh-jenkins`  :green_circle: 

- The test is automated and executed as part of multiple pipelines (test_install, test_upgrade, test_service, pr_wazuh, nightly).
- Tests are currently passing as of 4.4.4-RC2.
- For more details, [check comment below](https://github.com/wazuh/wazuh-qa/issues/4277#issuecomment-1620644531).

**Comment by Deblintrake09** [comment]
# Research on Check Files in `Wazuh-qa`

## What is tested
The tests located in the Wazuh-qa repository check the files in the system and the difference of files after a given `install,` `update` or `uninstall` process.

## State
- This suite used the now deprecated `qa-ctl ` tool that is not currently working, to setup an environment and launch the tests and gather the reports.
- The tests can be launched manually, but the process is not properly documented.

## How to run tests
- Execute check files before installation.
``` 
cd wazuh-qa
python3 deps/wazuh_testing/wazuh_testing/scripts/check_files.py  <PARAMETERS>
```
- Install manager/agent
- Execute checkfiles again to get a second output_file
- Execute the test file in `test/check_files`

### Parameters for `check_files` script
- PATH: Path base to inspect files recursively. Arg: "--path",  default='/'
- IGNORE: List of paths to ignore- Arg: "-i"
- OUTPUT_FILE: path to store the results. ARG: "-o" or "--output-file"
- DEBUG: Run in debug mode. Arg: '-d' or '--debug'

**Comment by Deblintrake09** [comment]
# Research on Check Files in wazuh-jenkins

## What is tested

This `check_files script` is a python script that checks that with a given installed version of wazuh, the expected file structure and permissions are found.

The script uses a series of json files that list the expected files, permissions in the different versions of wazuh.

### Parameters
- Target: Check files for manager or agent. Arg:  "-t" or "--target",  choices=['manager', 'agent']
- Test: Type of test. Arg: "-a", "--test",  choices=['upgrade', 'uninstall']
- Version: Vversion that is being checked. Arg: "-v", "--version". Ex: 4.4.4
- OS: Operating system or host distribution. Arg: "-o", "--os".  choices=['linux', 'windows', 'redhat', 'debian']
- Ignore: Path to ignore. Arg: "-i", "--ignore", Example: /var/ossec/wodles/oscap/content,/var/ossec/api
- No_Show_Ignore_List:  If true Ignored files list is not shown. Arg:  "-n", "--no_show_ignore_list"
- Directory: Used to change Installation location. Arg: "-d", "--directory"
- From_Version: Version you come from, to exclude files of it. Arg: "-f", "--from_version"

**Comment by rauldpm** [comment]
## Review notes

- Check grammar and nomenclature (JSON, wazuh-qa, etc)
- I think that is needed more documentation about:
  - Data structure examples
  - Used files
  - Usage examples
  - How to add things to the structure
  - The test output when the check-files test fails, 
- You can reuse the documentation already created about wazuh-jenkins check-files: https://github.com/wazuh/wazuh-jenkins/blob/master/doc/source/jenkins/ci/checkfile_test.rst
- On the other hand, shouldn't this knowledge be reflected in the Google Sites documentation?

**Comment by Deblintrake09** [comment]
Applied requested changes

**Comment by rauldpm** [comment]
## Review notes

### wazuh-jenkins

> Pipeline Example: https://ci.wazuh.info/view/Tests/job/Test_install/129733

The Test_install pipelines do not use the check-files.py script nor check the file's properties, they are used only for upgrade tests

> As part of Installation test suite:
> wazuh-jenkins/quality/tests/generic/02-installation/linux/test/conf/test_agent.yaml
> wazuh-jenkins/quality/tests/generic/02-installation/linux/test/conf/test_manager.yaml

Yes, the Python script is referenced but it is not used in the playbooks

> In terms of Pipelines it is used in:
> - PR_Wazuh
> - Nightly
> - Test_install
> - Test_upgrade
> - Test_service

Where is the Test_service pipeline using the check-files?

---

Shouldn't this knowledge be reflected in the Google Sites documentation?

**Comment by Deblintrake09** [comment]
- Updated `test_install` to note it is only referenced, but not used. 
- Removed `test_service` from list.
- This Epic's scope does not include the generation of documentation on Google Sites, as this was a research stage and documentation will be left in the related issues. After the results are checked and all tests are determined to be used or deprecated/deleted, a documentation phase will be started to create documentation for what is left.

**Comment by rauldpm** [comment]
## Review notes

> Updated test_install to note it is only referenced, but not used.

It must be clear that the Test_install pipeline does not use the check-files

- As part of `the i`nstallation test suite, it is referenced in the following files `but they are not used.`

---

> In terms of Pipelines it is used in:
> Test_install - only referenced but not actually used.
> Test_upgrade - tests are actually executed in this pipeline
> PR_Wazuh
> Nightly

Add a note in `PR_wazuh` and `test_nightly` stating that the check-files are launched in the `Tests_ugrade` pipeline and not in the `PR_wazuh` or `test_nightly` pipelines. Also, refer to the pipelines with their actual names (Nightly -> test_nightly)

---

Please check the grammar of the entire comment

> VERSION: `Vv`ersion
> of `I`nstallation
> `this` (these) tests are passing

**Comment by Deblintrake09** [comment]
Applied requested changes.

**Comment by rauldpm** [comment]
## Review notes

- Approved changes, I request a second review from @damarisg about the wazuh-qa section

**Comment by mauromalara** [comment]
## Review comment No.5

Great research and description 👏🏻 👏🏻 

Only a few changes are required:

### Check_files on wazuh-qa

**What is test**

Change the title to “What is being tested”

**How to run tests**

You mention this in “What is tested”:
> [the tests] check the files in the system and the difference of files after a given install, update or uninstall process.

But then you only explain how to check files before/after an install process. Please, add more detail to understand how the tool is used in all the cases.

**Parameters for check_files script**

> PATH: Path base to inspect files recursively. Arg: "--path", default='/'

I don’t quite understand what is this parameter about

**Parameters for**

I think the title is incomplete, am I right?

> BEFORE_FILE: Python Arg. --before-file. Path to check_file.py report before install/upgrade/uninstall.

I would change this “Path to check_file.py report…” By this “Path where the script will report….”

> AFTER_FILE: Python Arg. --after-file. Path to check_file.py report after install/upgrade/uninstall.

IDEM above.

**Comment by Deblintrake09** [comment]
## Response to review Comment No. 5

- Changed title.
- The steps for upgrade or uninstall were the same for installation. Have updated explicit commands for each type.
- Updated PATH parameter description. This path is the base path that files fill be checked. If you use the default for example all files and folders starting from `/` will be checked. If the path is changed to `/var/ossec` only files and folders inside that path would be checked.
- Updated the title for the parameters for the test.
- `BEFORE_FILE` and `AFTER_FILE` are the paths to the files created by the script before, not where the test will report. These files should exist before launching the tests.

**Comment by mauromalara** [comment]
## Review comment No.6

> `BEFORE_FILE` and `AFTER_FILE` are the paths to the files created by the script before, not where the test will report. These files should exist before launching the tests.

I'm still seeing the previous description, you explained it well in the previous comment. Please, expand the following descriptions for everyone to understand:
> > `BEFORE_FILE`: Python Arg. --before-file. Path to check_file.py report before install/upgrade/uninstall.
> > `AFTER_FILE`: Python Arg. --after-file. Path to check_file.py report after install/upgrade/uninstall.

**Comment by mauromalara** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
