### ISSUE TITLE
Investigate and document - Opensearch inherited tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4279]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :green_circle:    |
|Tests state| :yellow_circle:    |
|Pipeline link| https://github.com/wazuh/wazuh-dashboard/blob/wz-init/.github/workflows/build_and_test_workflow.yml |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the Opensearch inherited test suite, located in [`wazuh-dashboard/test`](https://github.com/wazuh/wazuh-dashboard/tree/master/test) folder. Check the automation status, parameters, location, steps in the tests and current state of it.

## What is tested
- The suite is a collection of Unit, Integration and Functional and Compatibility tests running on Jest for UT and IT, Selenium for Functional tests and Cypress  Backward-Compatibility tests.

## State

- Test execution is automated using Github actions.
   -  CI pipeline for tests is working correctly. :green_circle: 
   - Last merged Check execution: https://github.com/wazuh/wazuh-dashboard/pull/56/checks :green_circle: 
   - Launched ITs locally following the documentation.  :red_circle: 
      - Unit Tests :red_circle: - Tests run 1 failed test.
      - Integration tests :green_circle: 
      -  Functional and Compatibility :red_circle: - Possible configuration errors.
   - Documentation is not clear on how to set up a full testing environment.

## How to test locally

According to the documentation at https://github.com/wazuh/wazuh-dashboard/blob/master/TESTING.md, tests can be launched locally by:

- Cloning Repository
- Installing latest NodeJS, NPM and Yarn
```
apt install nodejs npm
npm install -g yarn
```
- Launch different suites with different NPMscripts:
   - Unit tests: `yarn test:jest`
   - Integration tests: `yarn test:jest_integration`
   - Functional tests: `yarn test:ftr`
   - Backwards compatibility tests: `yarn test:bwc -o [test path to opensearch.tar.gz] -d [test path to opensearch-dashboards.tar.gz]`

**Comment by Deblintrake09** [comment]
## Update 05/07/2023
- Research done on Pipeline and tests.
- Tried to setup and launch unit test by following documentation, but found dependencies Issues.
- Trying to solve dependencies on local install.

**Comment by Deblintrake09** [comment]
# Testing Update 06/07/2023

<details><summary> Unit Tests :red_circle: </summary>
' ' ' 
Summary of all failing tests
 FAIL  packages/osd-config-schema/src/errors/schema_error.test.ts
  ● includes stack

    expect(received).toMatchSnapshot()

    Snapshot name: `includes stack 1`

    - Snapshot  - 0
    + Received  + 1

      SchemaError: test
          at Object.<anonymous> (packages/osd-config-schema/src/errors/schema_error.test.ts:67:11)
          at new Promise (<anonymous>)
    +     at runMicrotasks (<anonymous>)

      67 |     throw new SchemaError('test');
      68 |   } catch (e) {
    > 69 |     expect(cleanStack(e.stack)).toMatchSnapshot();
         |                                 ^
      70 |   }
      71 | });
      72 |

      at Object.<anonymous> (packages/osd-config-schema/src/errors/schema_error.test.ts:69:33)
          at runMicrotasks (<anonymous>)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn run test:jest -u` to update them.

Test Suites: 1 failed, 1 skipped, 1525 passed, 1526 of 1527 total
Tests:       1 failed, 30 skipped, 9 todo, 12000 passed, 12040 total
Snapshots:   1 failed, 2913 passed, 2914 total
Time:        1262.64 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
' ' ' 
</details>


<details><summary> Integration Tests results :green_circle: </summary>

' ' ' 
         │ info [o.o.n.Node] [ubuntu.localdomain] stopped
         │ info [o.o.n.Node] [ubuntu.localdomain] closing ...
         │ info [o.o.n.Node] [ubuntu.localdomain] closed
 PASS  src/core/server/ui_settings/integration_tests/index.test.ts (47.4 s)

Test Suites: 50 passed, 50 total
Tests:       5 skipped, 441 passed, 446 total
Snapshots:   77 passed, 77 total
Time:        577.887 s
Ran all test suites.
         │ info [opensearch] stopped
         │ info [opensearch] cleanup complete
Done in 583.86s.
' ' ' 
</details>

**Comment by damarisg** [comment]
> Requested Changes: 

1. If you are using "status", you need to add a reference. What yellow does mean? (tests unstable, tests with warning)

2. It's correct that you add comments on your progress and problems.
 However, it's documentation, so I recommend that you need to add a last comment with all the detailed information(unit test, integration tests, functional test, compatibility tests).
 
    # Steps to install dependencies 
      - Step 1: 
      - Step 2: 
   # Steps to execute the different test types. 
      ## Unit tests
      - Step 1: 
      - Step 2: 
      ## Integration tests
      - Step 1: 
      - Step 2: 
      ##  ...

   # Coverage
    ##  unit tests
      - Test 1: General description 
      - Test 2: General description 
      ...
      - Summary:  a table with this information. 

>         Test Suites: 50 passed, 50 total
>         Tests: 5 skipped, 441 passed, 446 total
>         Snapshots: 77 passed, 77 total
>         Time: 5

        
   ## Integration tests
      ...
             
**Note: It helps to see the issue as documentation with all relevant information in the last comment.**

**Comment by Deblintrake09** [comment]
# Steps to install dependencies

- Clone wazuh-dashboard repository
- Install general dependencies NodeJS, NPM and Yarn.
   - Check which NodeJS version to use from `package.json` file
   ```
   apt install nodejs=<VERSION> npm
   npm install -g yarn
   ```  
- install repository dependencies using Yarn
   ```
   yarn osd bootstrap
   ```

# Steps to launch different tests locally

## Unit tests

**Comment by Deblintrake09** [comment]
# Research conclusions

Documentation on repository: https://github.com/wazuh/wazuh-dashboard/blob/master/TESTING.md

**Comment by davidjiglesias** [comment]
LGTM!
