### ISSUE TITLE
Investigate and document - Footprint tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4280]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :green_circle: |
|Tests state| :green_circle: |
|Jenkins link| https://ci.wazuh.info/job/Test_stress_tier and https://ci.wazuh.info/job/Test_stress|
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about theFootprint tests, located in [`wazuh-jenkins/jenkins-files/tests/pre-release/test_stress_tier.groovy`](https://github.com/wazuh/wazuh-jenkins/blob/master/jenkins-files/tests/pre-release/test_stress_tier.groovy). Document Jenkins Parameters, test script location, steps in the tests and current state of it.

## State

- As of Release 4.4.4-RC2 (the last release) the tests are passing and the pipeline is working properly.
   - RC2 Execution: https://ci.wazuh.info/job/Test_stress_tier/68 🟢
   - For research and testing launched the instance https://ci.wazuh.info/job/Test_stress_tier/71. Results: 🔴
      - The execution failed on one of the modules. The error seems to be a pipeline connection error, not the tests themselves.

**Comment by Deblintrake09** [comment]
# Research on test_stress_tier pipeline

## State
- This pipeline launches all test_stress suites with the configured values. If needed it also creates Issues or adds comments to passed Issues on the `wazuh` or `wazuh-jenkins` repositories. 
- It is normally used as part of the Release Candidate approval testing process. 
- As of Release 4.4.4-RC2 (the last release) the tests are passing and the pipeline is working properly.
   -  RC2 Execution: https://ci.wazuh.info/job/Test_stress_tier/68

## Pipeline execution

For research and testing launched the instance https://ci.wazuh.info/job/Test_stress_tier/71. Awaiting results :large_blue_circle: 
## Parameters
- Base general parameters 
   - VERBOSITY: verbosity of test logs
   - JENKINS_REFERENCE:  branch or commit reference
- Base parameters for all tests: 
   - TARGET_VERSION: Wazuh version. Ex: 4.4.4
   - REPOSITORY: package location. ex: pre-release
   - TARGET_REVISION: package revision. Default: 1
   - GITHUB_ACTION: Create Issue for each module or add to created Issues. Default: None (does not create Issue or comment).
   - ISSUE_NUMBERS: Footprint Issue number to referenced
   - RC: number of Release Candidate
   - RC_ISSUE: Number of related RC Issue 
   - FOOTPRINT_ISSUE: Number of related Footprint Issue 
   - GITHUB_REPO: repo where Issues are located or will be created (wazuh/wazuh or wazuh/wazuh-jenkins).
   - EXTRA_LABELS: Set extra labels to incorporate into the issues (these will be added to the generated issue labels
   - CUSTOM_TASK_DEFINITION: Set an ECS Task Definition name to use an alternative ECS Task Definition. Default: empty.
- Specific parameters: 
    - LAUNCH_VAGRANT_TEST: If checked, launches macOS and Solaris tests that require vagrant VMs.
   - TEST_DURATION: duration of tests in minutes
   - MODULES: Test Modules that can be launched. Values: SYSCHECK,LOGCOLLECTOR,ROOTCHECK,SCA,ACTIVE-RESPONSE,SYSCOLLECTOR,VULNERABILITY-DETECTOR,VULNERABILITY-DETECTOR-REGISTER,LOGCOLLECTOR_SYSCOLLECTOR,LOGCOLLECTOR_SCA,LOGCOLLECTOR_SYSCHECK,DOCKER-LISTENER_CIS-CAT_OSQUERY_AZURE-LOGS_OPEN-SCAP,ALL
   - ADDITIONAL_CHART_INFO

**Comment by jnasselle** [comment]
## Review

GJ @Deblintrake09 ! My two cents:

- Precondition/ Requirement stage

IMHO specifying that packages that will be referenced by several pipelines parameters like TARGET_VERSION, TARGET_REVISION and REPOSITORY should exist could be helpful

- Pipeline parameters

  - ADDITIONAL_CHART_INFO: Will append `Additional information: <ADDITIONAL_CHART_INFO>` into the charts titles
  - ISSUE_NUMBERS: Comma-separated issue number list. Only when GITHUB_ACTION is set to `ADD COMMENT TO EXISTING ISSUE`

**Comment by Deblintrake09** [comment]
- Applied requested changes to parameters and added a Precondition/Requirement section as requested.
- This Issue aims to research what is being tested and it's status only. Documentation on Sites is not part of this Epic's scope and will be handled on a later stage after all research is done and only tests/pipelines that are not deleted/deprecated will be documented.

**Comment by QU3B1M** [comment]
LGTM 🚀

**Comment by davidjiglesias** [comment]
LGTM!
