### ISSUE TITLE
Investigate and document tests - Indexer/dashboard

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4284]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| There is not one|
|Tests state| :green_circle: Done manually|
|Jenkins links| There are not|
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the indexer and dashboards tests. Jenkins parameters, pytest location, steps in the test and current state of it.

## State

There aren't any pipelines or tests specific for either the Wazuh dashboard or indexer, but tests are being done manually for the releases, inside of the `E2E UX` ones. An example for the 4.4.0 release candidate 1 is the following:

- Wazuh dashboard: https://github.com/wazuh/wazuh/issues/16153
- Wazuh indexer: https://github.com/wazuh/wazuh/issues/16187

For the dashboard, the following things are looked at:
- Wazuh dashboard package specs
- Dashboard package size
- Dashboard package metadata
- Dashboard package digital signature
- Installed files location, size, and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/permissions and that the installer did not break the system.)
- Installed service (check that it works correctly)
- Wazuh Dashboard logs when installed
- Wazuh Dashboard configuration (Try to find anomalies compared with 4.3.10)
- Wazuh Dashboard (including the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer
- Register Wazuh Agents
- Basic browsing through the WUI
- Basic experience with WUI performance.
- Anything else that could have been overlooked when creating the new package

For the indexer, the following things are looked at: 

- Wazuh indexer package specs
- Indexer package size
- Indexer package metadata (description)
- Indexer package digital signature
- Installed files location, size and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)
- Installed Wazuh indexer service
- Wazuh indexer logs when installed
- Wazuh indexer templates and indices created
- Wazuh indexer configuration (e.g. replicas are expected to be zero by default, how many shards per index,...) Try to compare and find anomalies with the previous Wazuh indexer version using appropiate E2E UX issue. Write down and report as much information as possible to allow comparison between versions using this issue.
- Wazuh indexer cluster node communication and configuration
- Wazuh indexer cluster status
- Wazuh indexer packages uninstallation procedure

**Comment by verdx** [comment]
# Update 06/07/23

Created and finished this issue.

**Comment by pro-akim** [comment]
# 11/07/2023
Information is accurate.
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
