### ISSUE TITLE
Investigate and document tests - Ruleset

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4285]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state| :green_circle: |
|Tests state| :green_circle: |
|Jenkins link| https://ci.wazuh.info/job/Test_ruleset |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the ruleset test. Primarily parameters and test state, as it only uses a Pipeline.

## State

The pipeline runs correctly, and the test is passed for branch `4.4`, as seen in run https://ci.wazuh.info/job/Test_ruleset/1993/. The test is also called by the nightly. An example of when it is called by the nightly is the following: https://ci.wazuh.info/job/Test_ruleset/1992/

The pipeline launches tests located at the http://github.com/wazuh/wazuh-ruleset repository, in path `tools/rules-testing/tests`. The complete test set is the following:

<details>

- apache.ini
- apparmor.ini
- checkpoint_smart1.ini
- cimserver.ini
- cisco_asa.ini
- cisco_ios.ini
- cpanel.ini
- doas.ini
- dovecot.ini
- exim.ini
- firewalld.ini
- junos.ini
- macos-sshd.ini
- mailscanner.ini
- mcafee_epo.ini
- modsecurity.ini
- named.ini
- netscreen.ini
- nextcloud.ini
- nginx.ini
- opensmtpd.ini
- openvpn_ldap.ini
- oscap.ini
- ossec.ini
- owlh.ini
- paloalto.ini
- pam.ini
- panda_paps.ini
- postfix.ini
- proftpd.ini
- rsh.ini
- samba.ini
- SonicWall.ini
- squid_rules.ini
- sshd.ini
- sudo.ini
- su.ini
- syslog.ini
- sysmon.ini
- systemd.ini
- test_expr_negation_geoip.ini
- test_expr_negation.ini
- test_features.ini
- test_osmatch_regex.ini
- test_osregex_regex_geoip.ini
- test_osregex_regex.ini
- test_pcre2_regex_geoip.ini
- test_pcre2_regex.ini
- test_static_filters_geoip.ini
- test_static_filters.ini
- unbound.ini
- vsftpd.ini
- web_appsec.ini
- web_rules.ini
</details>

## Parameters

- Base general parameters
  - VERBOSITY
  - JENKINS_REFERENCE
  - DESTROY_INSTANCES
  - CHECKRUN_REFERENCE
- Base parameters for all tests: 
  - TARGET_PKG_VERSION
  - TARGET_PKG_REVISION
  - TARGET_REPOSITORY
  - ARCHITECTURE
- Specific parameters:
  - SOURCE_REFERENCE: Branch of `wazuh-ruleset` repository

**Comment by verdx** [comment]
# Update 06/07/23

Created and finished this issue

**Comment by QU3B1M** [comment]
### Review 1 - Requested changes

- Add the location path of the tests executed by this pipeline.

**Comment by davidjiglesias** [comment]
LGTM!
