### ISSUE TITLE
Investigate and document tests - RTR

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4287]
|||
|-----|----|
|Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
|Pipeline state||
|Tests state||
|Jenkins link| https://ci.wazuh.info/job/Test_RTR, https://ci.wazuh.info/job/Test_RTR_external, https://ci.wazuh.info/job/Test_RTR_scanbuild  |
|Branch used| 4.4 |

## Description 

This issue aims to analyze and document all about the RTR test. Jenkins parameters, pytest location, steps in the test and current state of it.

## State

<details>
<summary>Tests launched</summary>

- Test_RTR: https://ci.wazuh.info/job/Test_RTR/2342
- Test_RTR_external: 
- Test_RTR_scanbuild: https://ci.wazuh.info/job/Test_RTR_scanbuild/6721
</details>

<!--
## Parameters

- Base general parameters
  - VERBOSITY
  - JENKINS_REFERENCE
  - DESTROY_INSTANCES
  - CHECKRUN_REFERENCE
- Base parameters for all tests: 
  - TARGET_PKG_VERSION
  - TARGET_PKG_REVISION
  - TARGET_REPOSITORY
  - ARCHITECTURE
- Specific parameters:
  - SOURCE_REFERENCE: Branch of `wazuh-ruleset` repository
--!>

**Comment by verdx** [comment]
## :green_circle: Test_RTR

### State

The pipeline runs correctly and the test is passed for 4.4.

The pipeline is called by `PR_Wazuh`.

### Parameters

- Base general parameters
  - VERBOSITY
  - JENKINS_REFERENCE
  - CHECKRUN_REFERENCE
- Base parameters for all tests: 
  - SOURCE_REFERENCE
  - TASK_DEFINITION_SUFFIX
  - CUSTOM_TASK_DEFINITION

**Comment by verdx** [comment]
## :green_circle: Test_RTR_scanbuild

### State

The pipeline runs correctly and the test is passed for 4.4.

The pipeline is called by `PR_Wazuh`.

<details>
<summary>Tests launched for the different parameter options</summary>

- Module: agent https://ci.wazuh.info/job/Test_RTR_scanbuild/6721
- Module: winagent https://ci.wazuh.info/job/Test_RTR_scanbuild/6722/
- Module: server https://ci.wazuh.info/job/Test_RTR_scanbuild/6723
</details>

### Parameters

- Base general parameters
  - VERBOSITY
  - JENKINS_REFERENCE
  - CHECKRUN_REFERENCE
- Base parameters for all tests: 
  - SOURCE_REFERENCE
  - TASK_DEFINITION_SUFFIX
  - CUSTOM_TASK_DEFINITION

**Comment by verdx** [comment]
## :green_circle: Test_RTR_external

### State

The pipeline runs correctly and the test is passed for 4.4.

The pipeline is called by `PR_intelligence_platform` and `PR_http_request` and does the test for repositories `wazuh-http-request` and `intelligence-platform`.

### Parameters

- Base general parameters
  - JENKINS_REFERENCE
  - CHECKRUN_REFERENCE
  - LABEL
- Base parameters for all tests: 
  - SOURCE_REFERENCE
  - REPOSITORY: [intelligence-platform, wazuh-http-request]

**Comment by verdx** [comment]
# Update 06/07/23

Created and finished this issue

**Comment by BelenValdivia** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
