### ISSUE TITLE
Document changelog format

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4290]
## Description

The changelog format will be changed as proposed [here](https://github.com/wazuh/wazuh-qa/pull/4288#discussion_r1254858677). It is necessary to document this format on the team's sites as well as the process of editing it, i.e. whether it will be changed at each PR or at the beginning of the release process.

**Comment by juliamagan** [comment]
### Update 07/07/2023

The first approach has been published and can be accessed [here](https://sites.google.com/wazuh.com/wazuh-qa-documentation/conventions/changelog).

It remains to add when the changelog will be edited, which is still to be decided. In the meantime, I am moving it to `Pending review` so that the first part can be reviewed.

**Comment by davidjiglesias** [comment]
I believe we should use a centralized approach for the changelog in all repositories, to be used by all development teams. For that reason, I will be closing this issue as not planned for now.
