### ISSUE TITLE
Remove Conventional Commits GitHub Action for wazuh-qa repository

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4291]
## Description

The Conventional Commits GitHub action should be removed from the pull requests done in the `wazuh-qa` repository, as the policy for a correct commit has been changed.

In addition, CodeQL, Changelog and Linter Github actions should be removed too.

**Comment by damarisg** [comment]
I'm waiting for some details on the CodeQL process to move it to Pending Review.

**Comment by QU3B1M** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
LGTM
