### ISSUE TITLE
Investigate and create template and documentation for Updating Wazuh System Version

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4292]
## Description

This issue is created to document and provide a template containing all the relevant information related to the task of updating the Wazuh system to a new version.

### The documentation should contain:

Information about:
- [ ] Document sections
- [ ] Critical notes
- [ ] Tasks
- [ ] Repositories.

It could be taken into consideration the following issue as a sample:
https://github.com/wazuh/wazuh/issues/17772

All information will be transferred to the following documentation space: https://sites.google.com/wazuh.com/wazuh-qa-documentation/

### Detail of tasks and repositories section

Tasks and all the repositories involved in the tasks should be mentioned and should contain:

- [ ] Repositories involved (Support issue + link)
- [ ] Changes in each repository (Link)

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
