### ISSUE TITLE
Binary data collector stops after manager restart in Workload benchmark test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4297]
## Description
When the manager restarts, it is possible to see in binaries (logs) created by the Workload benchmark pipeline that the information remains for a couple of seconds and it is stopped collecting it even if the activity of the cluster continues.

### Current behavior
Checking in master/data/binaries created in the artifact, it is possible to check

wazuh-apid | 4.6.0 | 2023/07/06 15:16:09 | 25371 | 0ck | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
wazuh-apid | 4.6.0 | 2023/07/06 15:16:19 | 28740 | 0 | 847264 | 102732 | 72168 | 81753 | 0 | 37 | 350 | 15 | 0 | 4 | 0 | 0
wazuh-apid | 4.6.0 | 2023/07/06 15:16:24 | 28740 | 0.2 | 847264 | 102732 | 71688 | 80861 | 0 | 37 | 358 | 19 | 0 | 4 | 0 | 0
wazuh-apid | 4.6.0 | 2023/07/06 15:16:29 | 28740 | 24.4 | 847264 | 102732 | 69440 | 79946 | 0 | 39 | 397 | 27 | 0 | 4 | 0 | 0
wazuh-apid | 4.6.0 | 2023/07/06 15:16:34 | 28740 | 72.3 | 857504 | 113992 | 80224 | 90404 | 0 | 38 | 697 | 156 | 0 | 4 | 0 | 0
wazuh-apid | 4.6.0 | 2023/07/06 15:16:39 | 28740 | 2.8 | 837016 | 114296 | 111504 | 111709 | 0 | 15 | 1250 | 174 | 0 | 12 | 0 | 1.

And after 15:16:39 the registries of binary are over meanwhile ossec.log registrates information until 2023/07/06 15:17:19

### Expected behavior
Binary information should be collected until the end of the tests.

**Comment by juliamagan** [comment]
With the changes to 5.0, we will not invest time here.
