### ISSUE TITLE
Reliability test fails in workload benchmark test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4299]
## Description
Performing: [Release 4.6.0 - Pre-Alpha1 - Workload benchmarks metrics](https://github.com/wazuh/wazuh/issues/17716)
The reliability test is not functioning correctly in the Workload benchmark test. 

### Current behavior
When the test is triggered by the pipeline, the following issue occurs:
```
E     File "/home/ec2-user/workspace/CLUSTER-Workload_benchmarks_metrics/wazuh-qa/tests/reliability/test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py", line 71
E       if result := logs_format.search(line):
E                  ^
E   SyntaxError: invalid syntax

```

### Expected behavior
The reliability test should run smoothly without encountering any path-related problems.

It seems that it is related with python-pytest version.

**Comment by Selutario** [comment]
It was fixed here:
- https://github.com/wazuh/wazuh-qa/issues/2747

It looks like we've lost those changes along the way.

**Comment by GGP1** [comment]
## Update

Adapted the test to support Python 3.7 and verified that the test ran successfully.

**Comment by GGP1** [comment]
## Update

Uploaded the output of three consecutive executions as requested by the reviewer.

**Comment by GGP1** [comment]
## Update

Fixed a typo in the changelog.

**Comment by davidjiglesias** [comment]
LGTM!
