### ISSUE TITLE
Research about new Vulnerability Detector

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4301]
## Description

Research about new vulnerability detector to understand what QA tasks are needed.

**Comment by BelenValdivia** [comment]
10/07/2023

- Sync with Octa about the Vulnerability detector
- I watch a video about the migration tool
- On hold due to release task

**Comment by BelenValdivia** [comment]
11/07/2023
- I watch a video about migration tool and sanitizing tool
- Understood how these tools work at a general level

**Comment by BelenValdivia** [comment]
- Created architecture diagram:

**Comment by BelenValdivia** [comment]
- Created documentation about migration tool, data sanitizer tool https://docs.google.com/document/d/1GyGib399CuWhVH2pEdgtcXMD5UdmPS8LL2x6bH_uwdM/edit

**Comment by BelenValdivia** [comment]
- Investigate and document merge tool

**Comment by damarisg** [comment]
Deprecated.
