### ISSUE TITLE
Modify the NVD's VD System Tests support

### ISSUE THREAD

**Issue by mateocervilla** [wazuh/wazuh-qa#4302]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/4275|

## Description

After the following changes in the NVD: https://github.com/wazuh/wazuh/issues/16555, it is necessary to deprecate some fields on the tests.
Work is being done on the integration tests on the [related issue](https://github.com/wazuh/wazuh-qa/issues/4275) but the [system tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/system) needs to be reviewed.

The tag `update_from_year` from Vulnerability Detector seems to be present in the mentioned tests, apparently as templates:

For example in:

- system/provisioning/
  - agentless_cluster/roles/
    - master-role/files/ossec.conf
    - worker-role/files/ossec.conf
  - basic_cluster/roles/
    - master-role/files/ossec.conf
    - worker-role/files/ossec.conf
  - big_cluster_40_agents/roles
    - master-role/files/ossec.conf
    - worker-role/files/ossec.conf
  - enrollment_cluster/roles
    - master-role/files/ossec.conf
    - worker-role/files/ossec.conf
  - four_manager_disconnected_node/roles
    - master-role/files/ossec.conf
    - worker-role/files/ossec.conf
  - manager_agent/roles
    - manager-role/files/ossec.conf
    - master-role/files/ossec.conf
  - one_manager_agent/roles/manager-role/files/ossec.conf

- end_to_end/test_basic_cases/test_vulnerability_detector/
  - test_vulnerability_detector_linux/data/playbooks/configuration.yaml
  - test_vulnerability_detector_windows/data/playbooks/configuration.yaml

We can find:

```xml
<provider name="nvd">
    <enabled>no</enabled>
    <update_from_year>2010</update_from_year>
    <update_interval>1h</update_interval>
</provider>
```

**Comment by juliamagan** [comment]
### Update

Moved back to `In progress`, because the executions failed.

**Comment by davidjiglesias** [comment]
LGTM!
