### ISSUE TITLE
Add tests to verify the upgrade process of Windows agents

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh-qa#4312]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.5.1         | https://github.com/wazuh/wazuh/issues/17046 | https://github.com/wazuh/wazuh/pull/17076 |
|       4.5.1         | https://github.com/wazuh/wazuh/issues/15196 | https://github.com/wazuh/wazuh/pull/16659 |
|       4.5.1         | https://github.com/wazuh/wazuh/issues/17071 | https://github.com/wazuh/wazuh/pull/17176 |

## Description
The issues mentioned above fix problems that occur specifically during the installation and uninstallation phases.

A summary of the fix scopes are:

https://github.com/wazuh/wazuh/issues/17046: Increased the timeout to determine if the upgrade was successful.

https://github.com/wazuh/wazuh/issues/15196: Changed the way of obtaining the OS architecture to a more generic and OS language-independent one.

https://github.com/wazuh/wazuh/issues/17071: Removed hardcoded installation path. The path is resolved using an environment variable.

## Proposed checks

- [ ] Verify that the upgrade of the Windows agents is performed correctly.
- [ ] Introduce an error during the upgrade process and check the correct rollback of the agent. Preferably in OS with different languages.
- [ ] Verify the correct uninstallation of the agent.

## Steps to reproduce
Each issue has steps to reproduce the error and an explanation of the problem.

## Expected results
Verify the correct solution to the problem reported in the issues.

**Comment by davidjiglesias** [comment]
DTT2
