### ISSUE TITLE
File integrity monitoring real-time Whodata Fails check

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4334]
* **Do you want to request a *feature* or report a *bug*?**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

The following error is produced in the `Test_integration` with `test_fim` module pipeline:

```
----------------------------- Captured stderr call -----------------------------
2023-07-20 12:09:52,303 - wazuh_testing - ERROR - Did not receive expected "File integrity monitoring real-time Whodata engine started" or "Initializing FIM Integrity Synchronization check"
2023-07-20 12:09:52,304 - wazuh_testing - ERROR - Results accumulated: 0
2023-07-20 12:09:52,304 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:466 Did not receive expected "File integrity monitoring real-time Whodata engine started" or "Initializing FIM Integrity Synchronization check"
ERROR    wazuh_testing:monitoring.py:467 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:469 Results expected: 1
- generated html file: file:///tmp/Test_integration_B41380_20230720122639/report.html -
```

### Full output:
- https://ci.wazuh.info/job/Test_integration/41380
  - Windows:
[windows_agent_tests_Test_integration_B41380_20230720122639.txt](https://github.com/wazuh/wazuh-qa/files/12114048/windows_agent_tests_Test_integration_B41380_20230720122639.txt)

  - CentOS:
[centos_agent_tests_Test_integration_B41380_20230720122639.txt](https://github.com/wazuh/wazuh-qa/files/12114151/centos_agent_tests_Test_integration_B41380_20230720122639.txt)

- https://ci.wazuh.info/job/Test_integration/41379
   - Manager:
[manager_tests_Test_integration_B41379_20230720122918.txt](https://github.com/wazuh/wazuh-qa/files/12114243/manager_tests_Test_integration_B41379_20230720122918.txt)

Testing the 4.6.0 Wazuh version: 
- https://ci.wazuh.info/job/Test_integration/41380
- https://ci.wazuh.info/job/Test_integration/41379

> Further research is required

**Comment by Rebits** [comment]
Bug not present after updating the tag https://github.com/wazuh/wazuh/issues/18005
Closed as not planned
