### ISSUE TITLE
`Test_remoted` Could not find the groups reload log

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4338]
* **Do you want to request a *feature* or report a *bug*?**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

The following error is produced in the `Test_integration` pipeline for `Test_remoted` module:

```
09:02:55  ----------------------------- Captured stdout call -----------------------------
09:02:55  Group 'testing_group' added to agent '057'.
09:02:55  ----------------------------- Captured stderr call -----------------------------
09:02:55  2023-07-20 11:52:17,239 - wazuh_testing - ERROR - Could not find the groups reload log
09:02:55  2023-07-20 11:52:17,239 - wazuh_testing - ERROR - Results accumulated: 0
09:02:55  2023-07-20 11:52:17,239 - wazuh_testing - ERROR - Results expected: 1
```

Before this another exception was found and could be a future problem:

```
09:02:55          finally:
09:02:55              if stop_injector:
09:02:55                  injector.stop_receive()
09:02:55  >               keep_alive_agent.terminate()
09:02:55  E               UnboundLocalError: local variable 'keep_alive_agent' referenced before assignment
``` 

Full output:
[manager_tests_Test_integration_B41390_20230720122806.txt](https://github.com/wazuh/wazuh-qa/files/12114531/manager_tests_Test_integration_B41390_20230720122806.txt)

Testing the 4.6.0 Wazuh version: https://ci.wazuh.info/job/Test_integration/41390

> Further research is required

**Comment by Rebits** [comment]
Bug not present after updating the tag https://github.com/wazuh/wazuh/issues/18005
Closed as not planned
