### ISSUE TITLE
Vulnerability detector Invalid data stream

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4339]
* **Do you want to request a *feature* or report a *bug*?**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

The following error is produced in the `Test_integration` pipeline for the Vulnerability detector module where testing the feeds:

```
09:56:28  >               res = decomp.decompress(data)
09:56:28  E               OSError: Invalid data stream
09:56:28  
09:56:28  /usr/local/python-3.10/lib/python3.10/bz2.py:333: OSError
09:56:28  - generated html file: file:///tmp/Test_integration_B41393_20230720122537/report.html -
09:56:28  =========================== short test summary info ============================
09:56:28  ERROR test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Focal]
09:56:28  ERROR test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Bionic]
09:56:28  ERROR test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Xenial]
09:56:28  ERROR test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Trusty]
09:56:28  ======= 259 passed, 2 skipped, 3 xfailed, 4 errors in 5109.67s (1:25:09) =======
```

Full output:
[manager_tests_Test_integration_B41393_20230720122537.txt](https://github.com/wazuh/wazuh-qa/files/12114540/manager_tests_Test_integration_B41393_20230720122537.txt)

Testing the 4.6.0 Wazuh version: https://ci.wazuh.info/job/Test_integration/41393/

> Further research is required

**Comment by Rebits** [comment]
Probably related with:
-  https://github.com/wazuh/wazuh-qa/issues/4231

**Comment by Rebits** [comment]
Duplicated https://github.com/wazuh/wazuh-qa/issues/4231
