### ISSUE TITLE
Enrollment IT fail for windows agent

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4342]
### Details

**Version**: `4.6.0`
**Build**: https://ci.wazuh.info/job/Test_integration/41378/
**Report**:  [agent_windows_html_report_Test_integration_B41378_20230720122930(3).zip](https://github.com/wazuh/wazuh/files/12122198/agent_windows_html_report_Test_integration_B41378_20230720122930.3.zip)

**Failed tests**:
- `test_agent_auth_enrollment`
- `test_agentd_enrollment`

### Description

During https://github.com/wazuh/wazuh/issues/17739 it has been detected that some enrollment tests fail. This seems to be related with a timeout error during the registration of the agent using the agent-auth exe:
```
E               subprocess.TimeoutExpired: Command '['C:\\Program Files (x86)\\ossec-agent\\agent-auth.exe', '-m', '127.0.0.1']' timed out after 2 seconds
```
Further research is required

**Comment by jnasselle** [comment]
Unfortunately, wazuh/wazuh-qa v4.6.0-pre-alpha1 tag was outdated. In consequence, the current analysis could be inaccurate and meaningless.
