### ISSUE TITLE
Include E2E tests in the Nightly CI process and Release

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4355]
## Description

As requested at https://github.com/wazuh/wazuh-qa/issues/3193, it is necessary to include the E2E tests in the Nightly so that they are launched automatically.

In addition, we must include these tests in the Release process so that they are launched and checked during the testing phase.

## To do

- [ ] Include E2E in the Nightly CI
- [ ] Include E2E in Release testing

**Comment by davidjiglesias** [comment]
To be done as part of https://github.com/wazuh/wazuh/issues/23383
