### ISSUE TITLE
Investigate and Prepare Presentation about Vulnerability detector

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#4358]
### Description

This issue aims to initiate research and preparation for a presentation on the current state and the new Vulnerability detector module.

### Objective

The main objective of this issue is to gather information, conduct thorough research, and prepare a comprehensive presentation that addresses the following key topics:

-  Actual Vulnerability detector module:
   - How it works
   - Disadvantages 
- New Vulnerability detector module:
  - Content migration tool
  - Sanitization tool
  - Content merge tool
  - Advantages
  - Refactor queries and scans

**Comment by BelenValdivia** [comment]
- Researched how the Vulnerability detector works today and added the information to the presentation.
- Added disadvantages about actual VD.
- Added new VD architecture

**Comment by BelenValdivia** [comment]
- Completed presentation 
    - migration, sanitize and merge tool
    - next steps
    - vd refactor

**Comment by BelenValdivia** [comment]
- Update architecture diagram

**Comment by damarisg** [comment]
Deprecated.
