### ISSUE TITLE
Update enrollment logs in system test

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4383]
## Description

During the execution of the system tests for the releases, https://github.com/wazuh/wazuh/issues/16664 was reported. However, after discussion with the team, it has been decided that the logs will remain as they are, so it is necessary to update the `system/test_enrollment/test_enrollment.py` test to look for the new logs.

These logs are:

- IP address of the server:

  ```
  Server IP Address: ...
  ```

  This log has stopped appearing.

- In cases where DNS is used in the configuration:

  ```
  Requesting a key from server: <DNS>/<IP_ADDR>
  ```

  This log has been changed to:

  ```
  Requesting a key from server: <DNS>
  ```

**Comment by juliamagan** [comment]
### Update

Working on changing the messages according to the test case

**Comment by damarisg** [comment]
LGTM!
