### ISSUE TITLE
Fix misspelling bug in the test_cluster_connection

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#4391]
## Description
During the research conducted in https://github.com/wazuh/wazuh-qa/issues/4386, it was identified that this specific [string](https://github.com/wazuh/wazuh-qa/blob/master/tests/reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py#L38) and [regex](https://github.com/wazuh/wazuh-qa/blob/master/tests/reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py#L42C16-L43) require a fix since the word `successfully` is misspelled.

### Current behavior

```
pytest.fail(f'Could not find "Sucessfully connected to master" message in the '
                            f'{node_name.search(log_file)[1]}')
```

```
re.search(rb'^.*Could not connect to master. Trying.*$|^.*Sucessfully connected to master.*$',
                         s[conn.end():], flags=re.MULTILINE):
```

### Expected behavior

```
pytest.fail(f'Could not find "Successfully connected to master" message in the '
                            f'{node_name.search(log_file)[1]}')
```

```
re.search(rb'^.*Could not connect to master. Trying.*$|^.*Successfully connected to master.*$',
                         s[conn.end():], flags=re.MULTILINE):
```

**Comment by pro-akim** [comment]
GJ!, All fixes done in the branch according. 
PR requires evidence of a new testing run.

**Comment by pro-akim** [comment]
## Update
Evidences were written in the issue as 'Current behavior'
LGTM

**Comment by pro-akim** [comment]
## Update
LGTM

**Comment by pro-akim** [comment]
## Update
Reports uploaded
LGTM

**Comment by pro-akim** [comment]
## Update
Report checked.
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
