### ISSUE TITLE
Unstable test_cluster/test_agent_enrollment/test_agent_enrollment test in system

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4407]
Running Release 4.5.0-rc1 system test https://github.com/wazuh/wazuh/issues/18260 it was possible to see flakyness in test_cluster/test_agent_enrollment/test_agent_enrollment 

## Description
The test was unstable showing 2 different results: Passed and Fail:
Reports are here:

[report1](https://github.com/wazuh/wazuh-qa/files/12292184/report_enr_cluster.2.zip)
[report2](https://github.com/wazuh/wazuh-qa/files/12292185/agent_enrollment.zip)

### Current behavior
The test_cluster/test_agent_enrollment/test_agent_enrollment  is unstable and it is failing for timeout.

### Expected behavior
test_cluster/test_agent_enrollment/test_agent_enrollment reflects the situation

**Comment by pro-akim** [comment]
@Rebits Data related with test run environment will be informed by @verdx, who had run the test.

**Comment by verdx** [comment]
## Test environment

The test environment on which it was run was an EC2 AWS machine, of type large and OS Ubuntu 22. 
- This machine was first created and pip3, python3-venv and docker were installed, docker following the instructions [here](https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository). 
- Using python3 venv, a virtual environment was created, where the instructions from https://github.com/wazuh/wazuh-qa/tree/master/tests/system were followed to initialize the environment. 
- Finally, all tests for environment `enrollment_cluster` were run.

**Comment by Rebits** [comment]
Testing performed for https://github.com/wazuh/wazuh/issues/18696 with proposed instance. It seems that enrollment cluster tests are unstable due to the lack of resources.
Further research is required.

**Comment by Rebits** [comment]
According to the [results of the latest system tests in the 4.5.3 RC 2](https://github.com/wazuh/wazuh/issues/19336) it seems that `enrollment_cluster` have not shown flaky behavior using the same environment proposed [here](https://github.com/wazuh/wazuh-qa/issues/4407#issuecomment-1695817979)
