### ISSUE TITLE
Agent Enrollment test fails 

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4408]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-alpha1 | Clusterd | Manager | Packages/Sources | Linux |

After launching the system tests for 4.5.1-alpha1, it was found that the `test_cluster/test_agent_enrollment/test_agent_enrollment.py` test because after the agent is registered in the `master` node, and the keys are generated, the `worker-1` node does not seem to receive and read the client keys file.

- Timeout error shown:
   ```
   TimeoutError: Did not found the expected callback in wazuh-worker1: .*Processing file etc\/client\.keys.*
   ```

- Logs in Worker-1:

  ```
  2023/08/07 21:17:49 DEBUG2: [Worker wazuh-worker1] [Integrity sync] Processing file etc/client.keys
  ```

  The log is present, and happens 4 seconds after the worker node has received the information about the key request for agent 001. 

It is possible that reading the `ossec.log` is not properly set and logs are not being read.

**Evidence:** - [enrollment_cluster_env.zip](https://github.com/wazuh/wazuh/files/12285882/enrollment_cluster.zip)

**Comment by Rebits** [comment]
Unexpected error in worker
```
2023/08/07 21:17:08 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.1-py3.9.egg/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.2', 1516)
```

**Comment by mauromalara** [comment]
This is not a stopper for 4.5.1 - Alpha 1, removed related fields from the QA project.

Further research is required because a lot of errors appear while running the test.

**Comment by havidarou** [comment]
This issue is blocked by https://github.com/wazuh/wazuh/issues/16664

**Comment by Deblintrake09** [comment]
This issue is duplicated from https://github.com/wazuh/wazuh-qa/issues/4407
