### ISSUE TITLE
FIM Synchronization system tests fail due to unfinished Sync

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4409]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-alpha1 | Clusterd | Manager | Packages/Sources | Linux |

After launching the system tests for 4.5.1-alpha1, it was found that the `test_fim/test_synchronization/test_synchronization.py` test fails, because the FIM synchronization does not finish and the test time outs.

- Timeout error shown:
   ```
   E                   TimeoutError: Did not found the expected callback in wazuh-agent1: .*Finished FIM sync.
   ```

After checking the Manager and Agent logs for all failed cases, the event is not showing.

**Comment by Rebits** [comment]
| R1 | R2 | R3 |
| --- | ---- | --- |
| :green_circle:  |:green_circle:  | :green_circle:  |


Synchronization test seems to be stable in my local environment:

### Evidences

- [Reports](https://github.com/wazuh/wazuh-qa/files/12310548/SyncronizationTestReports.zip)

**Comment by Rebits** [comment]
We need to know the reference used for https://github.com/wazuh/wazuh/issues/18288 in order to determinate the scope of that difference

**Comment by pro-akim** [comment]
Tests in manager_agent_env were performed using 4.5.1-alpha1 wazuh version.
No timeout errors were detected.

| R1 | R2 | R3 |
| --- | ---- | --- |
| :green_circle:  |:green_circle:  | :green_circle:  |

Evidence
[report.zip](https://github.com/wazuh/wazuh-qa/files/12312061/report.zip)

**Comment by pro-akim** [comment]
Tests in `manager_agent_env` were performed using `4.5.1-alpha1` wazuh version.
No timeout errors were detected.

| R1 | R2 | R3 |
| --- | ---- | --- |
| :green_circle:  |:green_circle:  | :green_circle:  |

### Evidences
- [Reports](https://github.com/wazuh/wazuh-qa/files/12312061/report.zip)

**Comment by Rebits** [comment]
The basic_cluster environment tests seems to also work:

- [basic_cluster.zip](https://github.com/wazuh/wazuh-qa/files/12313043/basic_cluster.zip)

We can conclude that no unexpected error is produced for 4.5.1-alpha1
