### ISSUE TITLE
Agent Auth System tests fail consistently

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4410]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-alpha1 | Authd tests | Manager | Packages/Sources | Linux |

After launching the system tests for 4.5.1-alpha1, it was found that the `test_agent_auth/test_agent_auth.py` test  fails because the log on the agent requesting the key to the manager was not detected. Looking at the logs, the event is present, so this might be caused by some kind of race condition between when the file is truncated and when it started to be read.

- Timeout error shown:
   ```
   E   TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: 172\.24\.27\.2
   ```

- Logs in agent:

   ```
   2023/08/08 00:23:37 agent-auth: INFO: Started (pid: 7811).
   2023/08/08 00:23:37 agent-auth: INFO: Requesting a key from server: 172.24.27.2
   2023/08/08 00:23:37 agent-auth: INFO: No authentication password provided
   2023/08/08 00:23:37 agent-auth: INFO: Using agent name as: wazuh-agent1
   2023/08/08 00:23:37 agent-auth: INFO: Waiting for server reply
   2023/08/08 00:23:37 agent-auth: INFO: Valid key received

   ```

**Evidence:** [basic_enviroment.zip](https://github.com/wazuh/wazuh/files/12285883/basic_enviroment.zip)

**Comment by Rebits** [comment]
The anticipated log is evidently present within the agent, and this has been accurately registered to the manager.

It appears that there may be an issue within the system test module, as things do not seem to be functioning as intended. Further investigation is warranted.

As of now, this item has been withdrawn from the release.

**Comment by Deblintrake09** [comment]
The error has been replicated during execution of https://github.com/wazuh/wazuh/issues/18384. 

Evidence: https://github.com/wazuh/wazuh/files/12343623/basic_enviroment.zip

ssue was

**Comment by Rebits** [comment]
I have not been able to replicate the error even once. Probably environment error, as @juliamagan suggested [here](https://github.com/wazuh/wazuh-qa/issues/4410#issuecomment-1680561857)

- [AgentAuthReport.zip](https://github.com/wazuh/wazuh-qa/files/12360030/AgentAuthReport.zip)
