### ISSUE TITLE
Create System tests to replace VDT IT that use official Feeds

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4415]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
| master           | https://github.com/wazuh/wazuh/issues/17403 |                    |

## Description

During the migration process of Integration tests to the `wazuh/wazuh` repository, it was decided that Vulnerability Detector tests that require the usage of official feed servers would not be migrated and System Tests.

The following modules have not been migrated and should have System Tests created to replace them:

- https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py
- https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_vulnerability_detector/test_feeds/test_validate_feed_content.py
- https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_vulnerability_detector/test_providers/test_os.py
- https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_vulnerability_detector/test_providers/test_update_from_year.py

**Comment by davidjiglesias** [comment]
We are doing Vulnerability detector functionality testing in https://github.com/wazuh/wazuh-qa/issues/4369
