### ISSUE TITLE
simulate_agents.py [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by MustafaAlshehab** [wazuh/wazuh-qa#4436]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.5.0             |                        |                    |

## Description

I am trying to create as many agents as possible and distribute EPS to measure the stress in terms of CPU usage on Wazuh server. However, exceeding certain limit of agents or EPS seems to be problematic. For example, running the command `python3 simulate_agents.py -a <MANAGER_IP> -n 500 -m logcollector -s 1400` will create agents and distribute eps just fine, but `python3 simulate_agents.py -a <MANAGER_IP> -n 500 -m logcollector -s 1450` introduces this issue (please see attachment for full log).

## Proposed checks

- [ ] socket connection implementation and handling 
...

## Steps to reproduce

Running the following command `python3 simulate_agents.py -a <MANAGER_IP> -n 500 -m logcollector -s 1450`
## Expected results

Agents are created and EPS are distributed.
[output.log](https://github.com/wazuh/wazuh-qa/files/12374114/output.log)

**Comment by damarisg** [comment]
We decided to close them.
