### ISSUE TITLE
Error with test_enrollment not finding specific logs 

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#4481]
## Description

During the execution of the system tests for the releases, the error supposedly solved in issue https://github.com/wazuh/wazuh-qa/issues/4383 has appeared again in the system test `test_enrollment`. The error is the following: 
```
TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: 172.24.27.2
```

In some cases, there are even some strange expected logs, such as the following, where it seems the manager address isn't being correctly passed or parsed:
```
TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: FDD1:AC8C:0557:7CE2:0000:0000:0000:0002
```
```
TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: wazuh\-manager
```

Complete test output: 
[basic_environment.html.zip](https://github.com/wazuh/wazuh-qa/files/12472894/basic_environment.html.zip)

**Comment by juliamagan** [comment]
I attach a report in which the tests pass as expected:

[R1-enrollment.zip](https://github.com/wazuh/wazuh-qa/files/12485067/R1-enrollment.zip)

**Comment by juliamagan** [comment]
These tests passed successfully four times in the PR applying the fix, and now, several more times during the investigation, the error may be due to the environment used during testing. System tests can easily be affected by any minor change in the environment.

**Comment by davidjiglesias** [comment]
LGTM!
