### ISSUE TITLE
Update `xfailed` list for Cluster Workload tests

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-qa#4508]
## Description
In https://github.com/wazuh/wazuh/issues/18017 it was found that the `GET /manager/logs` endpoint in the Workload tests was failing due to an error already fixed in https://github.com/wazuh/wazuh/pull/17946. Since the fix was introduced for a later version, we should mark the test as `XFAIL` updating the following list:
https://github.com/wazuh/wazuh-qa/blob/3686d48250d1905b4ef38815e6b0d18b6a9b4d75/tests/performance/test_api/test_api_endpoints_performance.py#L15-L22

### Current behavior
The test fails with the following error:
<details><summary>Test Failure output</summary>

    =================================== FAILURES ===================================
    ____________________ test_api_endpoints[get_/manager/logs] _____________________
    
    test_case = {'body': {}, 'endpoint': '/manager/logs', 'method': 'get', 'parameters': {}}
    set_api_test_environment = None, api_healthcheck = None
    
        @pytest.mark.parametrize('test_case', test_data['test_cases'], ids=case_ids)
        def test_api_endpoints(test_case, set_api_test_environment, api_healthcheck):
            """Make an API request for each `test_case`.
        
            Args:
                test_case (dict): Dictionary with the endpoint to be tested and the necessary parameters for the test.
                set_api_test_environment (fixture): Fixture that modifies the API security options.
                api_healthcheck (fixture): Fixture used to check that the API is ready to respond requests.
            """
            # Apply xfails
            if test_case['endpoint'] in xfailed_items.keys() and \
                    test_case['method'] == xfailed_items[test_case['endpoint']]['method']:
                pytest.xfail(xfailed_items[test_case['endpoint']]['message'])
        
            base_url = api_details['base_url']
            headers = api_details['auth_headers']
            response = None
            try:
                response = getattr(requests, test_case['method'])(f"{base_url}{test_case['endpoint']}", headers=headers,
                                                                  params=test_case['parameters'], json=test_case['body'],
                                                                  verify=False)
    >           assert response.status_code == 200
    E           assert 500 == 200
    E             +500
    E             -200
    
    tests/performance/test_api/test_api_endpoints_performance.py:47: AssertionError
    ----------------------------- Captured stdout call -----------------------------
    Request elapsed time: 0.062s
    
    Status code: 500
    
    Full response: 
    {
      "title": "Wazuh Internal Error",
      "detail": "Could not find any Wazuh log file",
      "remediation": "Please check `WAZUH_HOME/logs`",
      "dapi_errors": {
        "master": {
          "error": "Could not find any Wazuh log file",
          "logfile": "WAZUH_HOME/logs/api.log"
        }
      },
      "error": 1020
    }
    =========================== short test summary info ============================
    FAILED tests/performance/test_api/test_api_endpoints_performance.py::test_api_endpoints[get_/manager/logs]

</details>

### Expected behavior

The test should output three xfailed cases:
```
======= 52 passed, 3 xfailed, 54 warnings in 217.00s (0:03:37) =======
```

**Comment by Selutario** [comment]
The fix was migrated to 4.6.0 so this is no longer necessary:
- https://github.com/wazuh/wazuh/issues/18939
