### ISSUE TITLE
Invalid shared configuration in `Active Response` integration test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#4516]
## Description

In the analysis of the issue https://github.com/wazuh/wazuh/issues/18941, an error message was found in the Active Response - Agent test, on the Windows node, indicating that the configuration shared/ar. conf is invalid, it is necessary to determine if this is reproducible and if the said configuration is valid or not

```
2023/09/11 12:38:29 wazuh-agent[1584] exec.c:65 at ReadExecConfig(): ERROR: (1313): Invalid active response config: 'shared/ar.conf'.
```

**Comment by juliamagan** [comment]
### Update

Configured the environment and verified that the error is reproduced. Investigating what may be the cause.
