### ISSUE TITLE
Analyze the stability of the FIM integration test in Windows

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#4518]
## Description

In the analysis of the issue https://github.com/wazuh/wazuh/issues/18941, an error has been detected in `FIM - Agent`, on the Windows node, indicating a problem stopping the `wazuh-syscheckd` daemon

```
> raise ValueError(f"Error when executing {action} in daemon {daemon}. Exit status: {result}")
E ValueError: Error when executing stop in daemon wazuh-syscheckd. Exit status: 2
```

Because there are no logs available (reported in https://github.com/wazuh/wazuh-qa/issues/4515), its origin could not be investigated. The test has been relaunched and instead of failing, has ended as SUCCESS. This may indicate that the test is not reliable, it is necessary to investigate the stability of the test to ensure correct operation.

Build failed:https://ci.wazuh.info/job/Test_integration/42932/
Build success: https://ci.wazuh.info/job/Test_integration/42963/

**Comment by davidjiglesias** [comment]
We are not going to be able to reproduce flaky tests like this one.
