### ISSUE TITLE
Develop new test case for AWS VPC integration with multiple FlowLog

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh-qa#4522]
## Description
During the Alpha1 phase of 4.6.0, we found an error wazuh/wazuh#18901 that wasn't caught by the integration tests of the AWS module https://github.com/wazuh/wazuh/issues/18879#issuecomment-1710261121. 
So, is needed to design and develop a new test case to cover this behavior.

## Proposed test cases

As a reference the original test cases were defined in #3336

- [ ] VPC Flow integration works properly with only_logs_after option and multiple FlowLog configured.

**Comment by javiersanchz** [comment]
## Update
- I was looking at how the tests are divided, how to develop it and getting started
- I start to create the test_case script on the issue

**Comment by javiersanchz** [comment]
## Update

 - I finished developing the test in test_only_logs_after, I have been developing the cases inside only_logs_after_test_module, I still need to run it and test its operation.

**Comment by javiersanchz** [comment]
## Update

- I continue with the development of the test_case and creating function in s3_utils
- I am waiting for permissions in https://github.com/wazuh/internal-devel-requests/issues/355
