### ISSUE TITLE
Basic_environment_env and agentless_env tests are not stable executed in EC2

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4525]
Related issue: https://github.com/wazuh/wazuh-qa/issues/4509

Running basic_environment_env tests in EC2 (Ubuntu 22.04.03 LTS T3.Large + 30GB HD) is not working stable having wrong results of the method HostMonitor.

Reports are attached:
[basic_env_ec2](https://github.com/wazuh/wazuh-qa/files/12648515/basic_env.zip)
[basic_env_local](https://github.com/wazuh/wazuh-qa/files/12648517/basic.zip)
[agentless_env_ec2_t1.zip](https://github.com/wazuh/wazuh-qa/files/12649696/agentless.zip)
[agentless_env_ec2_t2.zip](https://github.com/wazuh/wazuh-qa/files/12649697/agentless2.zip)
[agentless_local.zip](https://github.com/wazuh/wazuh-qa/files/12649699/agentless_local.zip)

All of them were run in the branch v4.6.0-alpha1
using ansible 
`sudo ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch":"v4.6.0-alpha1", "wazuh_qa_branch":"v4.6.0-alpha1"}'`

Following the instructions of https://github.com/wazuh/wazuh-qa/issues/4509

**Comment by pro-akim** [comment]
## Update

Running T2.Xlarge Ec2 Ubuntu 22.04.3 LTS 
```

WARNING: Skipping wazuh-testing as it is not installed.
Processing /home/vagrant/wazuh-qa/deps/wazuh_testing
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vj4udnvc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vj4udnvc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-vj4udnvc/pip-egg-info
         cwd: /tmp/pip-req-build-vj4udnvc/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-vj4udnvc/setup.py", line 76, in <module>
        version=get_version(),
      File "/tmp/pip-req-build-vj4udnvc/setup.py", line 66, in get_version
        f = open(abs_file_path)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vj4udnvc/../../version.json'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Same error than VM with Virtualbox appeared.

**Comment by pro-akim** [comment]
## Conclusion

Basic_environment and agentless tests have been executed and tested on more powerful EC2 instances. However, despite these efforts, we have not been able to match the stability of the tests obtained in a local environment.
Basic_environment has improved its results, showing a reduction in false negatives by 30%, while agentless has remained unchanged. Since higher-capacity EC2 instances require the use of capital, we will need to evaluate whether it is worth conducting this test with the team leaders.

**Comment by pro-akim** [comment]
## Conclusion

- Basic_environment_env test are working stable in C5.Xlarge Ec2 Ubuntu 22.04.3LTS 15GB
- Agentless_cluster_env test has 1/24 Failure, the failure is in test_cluster/test_integrity_sync/test_integrity_sync.py and only in local_environment remained stable.

**Comment by verdx** [comment]
# Review

The conclusion is not really completely closed, at least an issue should be created to investigate why method HostMonitor is failing only on virtual machines.

Maybe all this should be specified in the issue templates for the system tests, so as to avoid confusion the next time they will be done.

**Comment by pro-akim** [comment]
## Update
Issues opened, moved to pending review

**Comment by verdx** [comment]
LGTM! GJ

**Comment by fcaffieri** [comment]
LGTM
