### ISSUE TITLE
Create a template for system tests that includes EC2 requirements for running the tests

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4527]
In https://github.com/wazuh/wazuh-qa/issues/4509 different EC2 requirements were evaluated in order to run System tests in Virtual Machines.

It should contain:
- EC2 requirements per environment https://github.com/wazuh/wazuh-qa/issues/4509#issuecomment-1725390131
- Relevant notes
- Instructions to create the environment in the EC2 https://github.com/wazuh/wazuh-qa/issues/4509#issuecomment-1721019933

Creating a template that automatically includes this information for each release and for future test executions could be useful and add value to the process.

**Comment by pro-akim** [comment]
##Update:

`wazuh-qa/tests/system/CHANGELOG.md`
and 
`https://github.com/wazuh/wazuh/blob/master/.github/ISSUE_TEMPLATE/system-tests.md`
will be changed in this issue

**Comment by pro-akim** [comment]
## Update
Fixes done after review

**Comment by verdx** [comment]
# Review

Changes asked for in the pull requests
