### ISSUE TITLE
Prepare vulnerability feeds for VDT System tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4530]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|  4.8.0              | #4369  and #4529   |                    |

## Description
Some of the tests proposed in #4369, require that the test feeds are modified, in order to remove vulnerabilities to installed packages or add new applicable or non-applicable vulnerabilities. This Issue aims to determine the optimal approach for modifying the feeds in consideration that the tests require real world feeds to be used.

## Test cases
- [ ] Updating the vulnerability feed with a new applicable vulnerability
- [ ] Updating the vulnerability feed with a new non-applicable vulnerability
- [ ] Modifying the vulnerability feed to remove a CVE that applies to my system

## Considerations
- Since the tests are aimed to real world test cases, neither the packages or the feeds should be mocked.
- The packages that will be used for testing and affected by this issue will be determined in #4529

**Comment by davidjiglesias** [comment]
The final design includes testing with the real feed, so no feed mocks or modifications as required as of right now
