### ISSUE TITLE
Support new Wazuh version 4.7.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4532]
## Description

This issue attempts to support a new version 4.7.1 in the wazuh-qa repository.

## Tasks

- [x] Create numbered branch for version (4.7.1) using branch 4.7.0 on wazuh-qa repository.
  - https://github.com/wazuh/wazuh-qa/tree/4.7.1
- [x] Bump 4.7.1 branch to 4.7.1 version on wazuh-qa repository, including revision and changelog.
  - https://github.com/wazuh/wazuh-qa/pull/4533

**Comment by pro-akim** [comment]
LGTM
