### ISSUE TITLE
Revert "Pull request #3788 from wazuh/3760-setuptools-dep" 

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4554]
## Description
We have reverted  https://github.com/wazuh/wazuh-qa/pull/3788 for 4.5.3 in https://github.com/wazuh/wazuh-qa/pull/4553, but this change is already in the later branches and is affecting https://github.com/wazuh/wazuh/pull/19196, so it was decided to put this change in 4.7.0 instead of waiting for the upstream branch merge to continue.

**Comment by verdx** [comment]
LGTM!
