### ISSUE TITLE
Wrong skip marks in FIM tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4557]
## Description

During testing at https://github.com/wazuh/wazuh/issues/19198 it was discovered that several FIM tests had failed due to:

```
            except TypeError as e:
>               raise TypeError(str(e) + " - maybe you meant pytest.mark.skipif?") from None
E               TypeError: Skip.__init__() got multiple values for argument 'reason' - maybe you meant pytest.mark.skipif?
```

We should change the mark of the affected tests from:

```
@pytest.mark.skip(sys.platform=='win32', reason="Blocked by #4077.")
```

to:

```
@pytest.mark.skipif(sys.platform=='win32', reason="Blocked by #4077.")
```

**Comment by pro-akim** [comment]
## Update
Changes done. Testing IT pipeline with FIM tests.
https://ci.wazuh.info/job/Test_integration/43449/

**Comment by damarisg** [comment]
Next time, when a change is applied, I suggest show evidence that the rest of the cases are working.

**Comment by pro-akim** [comment]
## Update

@damarisg reports attached in the issue.

**Comment by damarisg** [comment]
Thank you for adding it!
