### ISSUE TITLE
Research required tools for performing VD tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4587]
### Description

To advance the development of the [System Functionality Testing for the Vulnerability Detector](https://github.com/wazuh/wazuh-qa/issues/4369), it is imperative that we conduct research to identify potential new tools that could enhance the capabilities of the wazuh-qa framework. This research is essential to enable the following functionalities:

- [x] Log Monitoring
 - [x] Installation/Removal of custom packages via URL on various operating systems remotely
   - [x] Windows
   - [x] Linux
   - [x] macOS
- [x] Index management functions through API
- [x] Configuration change for the manager and agents

**Comment by Rebits** [comment]
We will adopt an End-to-End (E2E) testing approach, utilizing Ansible tasks to execute all remote operations. This strategy does not require the introduction of any new tools.

**Comment by Deblintrake09** [comment]
LGTM! Approved!

**Comment by davidjiglesias** [comment]
LGTM!
