### ISSUE TITLE
Include System Functionality tests into the CI processes

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4589]
### Description

It is essential to integrate the upcoming [System tests for Vulnerability Detector](https://github.com/wazuh/wazuh-qa/issues/4369) into our Continuous Integration (CI) processes.

A thorough investigation is warranted to determine the specific CI processes where these tests should be incorporated. This analysis will be based on a careful evaluation of the product requirements and an assessment of the time and cost implications associated with implementing these new tests.

**Comment by Rebits** [comment]
Is necessary to determinate in which CI process VD tests will be included. Further details from management team are required.

**Comment by davidjiglesias** [comment]
To be done as part of CI overhaul.
