### ISSUE TITLE
Generate final tag and publish draft release for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4595]
## Description

This issue attempts to publish draft release and generate final tag for version 4.5.3 in the wazuh-qa repository.

## Tasks

- [x] Generate final tag v4.5.3 from branch 4.5.3 on wazuh-qa repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-qa/releases) from [tag v4.5.3](https://github.com/wazuh/wazuh-qa/tree/v4.5.3).

**Comment by pro-akim** [comment]
## Review Notes

LGTM
