### ISSUE TITLE
FIM System tests: Randomly select and delete n files

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#461]
#### Objective

Develop required tasks to randomly select and delete files with the absolute paths provided in a JSON file.

#### Design

The main challenge here is to keep track of deleted files. So the function should return as an output, a JSON file with the paths of the deleted files.

#### Tasks

- [x] Implement a function to randomly select and delete files.
- [x] Verify the changes on
- - [x] Windows.
- - [x] Linux.
 
Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-461-create-delete-folders](https://github.com/wazuh/wazuh-qa/tree/feature-461-create-delete-folders).

**Comment by rshad** [comment]
Hi all!

The required functionalities were implemented and tested.

Kr,

Rshad

**Comment by jm404** [comment]
Done in #475
