### ISSUE TITLE
Fix the basic cluster system tests that cannot be executed without modifications

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4617]
## Description
The basic cluster tests need to be reviewed, as after the execution of certain tests, the environment becomes messy, causing subsequent failures

### Current behavior
False failures occur when the tests are being executed.
Therefore it should be executed in the following order and steps:

    part 1
    test_cluster/test_agent_key_polling/test_agent_key_polling.py
    test_multigroups/test_multigroups.py

    part 2
    test_cluster/test_agent_files_deletion/test_agent_files_deletion.py
    test_cluster/test_agent_groups/test_agent_groups_forced_change.py

    part 3
    test_cluster/test_agent_info_sync/agent_info_sync

### Expected behavior
The environment should be cleaned and restarted between tests in order to be able to execute them without additional maneuvers.

**Comment by juliamagan** [comment]
| Development branch |
|:--:|
| [bug/4617-clean-system-env](https://github.com/wazuh/wazuh-qa/tree/bug/4617-clean-system-env)|

Changes applied and tests passed, it remains to open the PR.

**Comment by juliamagan** [comment]
### Update

Finally I had to spend more time on this issue, because I wanted not only to be able to launch all tests at the same time without being affected, but also to be able to launch several rounds without having to destroy the environment in between.

**Comment by pro-akim** [comment]
## Update
Evidence of the test will be awaited.
During that wait, tests will be launched in a different environment

**Comment by pro-akim** [comment]
## Review Notes
Local tests worked OK.
LGTM
