### ISSUE TITLE
Upgrade py library to > 1.11.0

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4631]
### Description

Regarding https://github.com/wazuh/wazuh-jenkins/issues/5724#issuecomment-1771170116, due to a vulnerability detected in py library prior to 1.11.0, it needs to be updated to a version later than 1.11.0, while checking its compatibility with other libraries required.

In addition it would be necessary to document which tests or modules make use of this dependency

**Comment by juliamagan** [comment]
With all the migration of the repository, the dependencies are already being updated. Also, once the entire migration is complete in 4.10.0, security scans will be re-enabled to check this.
