### ISSUE TITLE
Wrong `schema.j2` path 

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4680]
## Description

When launching an E2E test with `Test_e2e_system`, it was found that the specified file was not found because the path is not as expected.

```
10:44:39  MSG:
10:44:39  
10:44:39  Could not find or access '/home/ec2-user/workspace/Test_e2e_system/145/wazuh-qa/provisioning/roles/wazuh_environment/schema.j2' on the Ansible Controller.
```

It looks for `wazuh-qa/provisioning/roles/wazuh_environment/schema.j2`, but the file is found in `wazuh-qa/provisioning/roles/wazuh/wazuh_environment/schema.j2`. This change was introduced in https://github.com/wazuh/wazuh-qa/pull/4642.

It is necessary to change the path file or change the expected path.

**Evidences**: https://ci.wazuh.info/view/Tests/job/Test_e2e_system/145/console

**Comment by Rebits** [comment]
I think this issues could be produced due to an outdated state of the used branch.
It should be used this path `"${this.wazuh_qa_path}/provisioning/roles/wazuh/wazuh_environment/schema.j2"` since https://github.com/wazuh/wazuh-jenkins/pull/5838

**Comment by davidjiglesias** [comment]
LGTM!
