### ISSUE TITLE
Update Integration tests readme

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4711]
### Description

The current instructions in the `README` file for installing and launching integration tests require an update. The outdated steps have caused issues for some collaborators, leading to confusion and challenges. It is crucial to enhance these instructions to prevent further confusion.

**Comment by pro-akim** [comment]
## Review Notes
Some important settings were deleted and they should be reviewed.

**Comment by pro-akim** [comment]
## Review Notes
In Windows description the following setting is not present:

```
# Enable debug 2
echo 'syscheck.debug=2' >> "C:\Program Files (x86)\ossec-agent\local_internal_options.conf"
```

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by davidjiglesias** [comment]
LGTM
