### ISSUE TITLE
Logcollector scanning IT: The ValueError was raised when attempting to stop the 'wazuh-logcollector' daemon

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4733]
### Description

It has been detected in https://github.com/wazuh/wazuh/issues/20479 where Testing logcollector integration in Windows Agent, the following connection error were found:

```
>           raise ValueError(f"Error when executing {action} in daemon {daemon}. Exit status: {result}")
E           ValueError: Error when executing stop in daemon wazuh-logcollector. Exit status: 2

C:\Python311\Lib\site-packages\wazuh_testing\tools\services.py:147: ValueError

```

### Evidences

- **Build**: https://ci.wazuh.info/job/Test_integration/45056/
- **Result**: https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45044/agent_windows_html_report_Test_integration_B45044.zip

**Comment by Deblintrake09** [comment]
- Research has detected that the previous test is `test_basic_configuration_out_format.py` that configures invalid values on the logcollector section and that might be causing the agent to delay it's start.
- We have been unable to replicate the error on multiple.

**Comment by Deblintrake09** [comment]
- Could not replicate the Issue.
- The possible race condition  with test `test_basic_configuration_log_format.py` was not found to be happening as expected during multiple runs and executions, so applying changes to this test was discarded.
- Improved error handling was added to `control_service` so it handles unexpected errors and prints an error message with the response if it is not able to start/stop the agent.

**Comment by davidjiglesias** [comment]
Why is the PR pointing to master branch instead of 4.7.1?

**Comment by Deblintrake09** [comment]
> Why is the PR pointing to master branch instead of 4.7.1?

Targeted wrong branch, branchwas started from v4.7.1-rc1.

Updated target and requested approval again.
