### ISSUE TITLE
Unexpected passes in IT logcollector tests

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4734]
### Description

It has been detected in https://github.com/wazuh/wazuh/issues/20479 where Testing Logcollector integration in different Agents, the following issue was detected:

- Logcollector Agent Centos :red_circle: while all the test have passed, but it has unexpected passes
- Logcollector Agent MacOS Agent :red_circle: while all the test have passed, but it has unexpected passes
- Logcollector Agent Solaris Agent :red_circle: while all the test have passed, but it has unexpected passes
- Logcollector Agent Windows Agent :red_circle: it has an error reported in https://github.com/wazuh/wazuh-qa/issues/4733 , but it has unexpected passes too

### Evidences

- Reports: [centos](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45044/agent_centos_html_report_Test_integration_B45044.zip), [windows](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45044/agent_windows_html_report_Test_integration_B45044.zip), [macOS](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45044/agent_macos_html_report_Test_integration_B45044.zip) & [Solaris](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45044/agent_solaris_html_report_Test_integration_B45044.zip)

### Conclusion

https://github.com/wazuh/wazuh-qa/issues/4734#issuecomment-1833778603

**Comment by Rebits** [comment]
LGTM

We anticipate unexpected passed in our ongoing efforts.

Further research regarding the failed case for Windows Agent will be carried on in https://github.com/wazuh/wazuh-qa/issues/4733

**Comment by davidjiglesias** [comment]
LGTM!
