### ISSUE TITLE
Update Deployer Pipeline Wiki documentation

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4752]
## Description

This issue update the Deployer pipeline documentation wiki with the up to date lists of OSs and architectures supported. Recently new systems have been added, as well as support for Arm64 endpoints.

### Tasks
- [x] Add missing Systems
- [x] Document Arm64 support

This Issue is related to https://github.com/wazuh/wazuh-jenkins/issues/6041

**Comment by Deblintrake09** [comment]
## Update

- Updated Wiki with systems and architecture

**Comment by Rebits** [comment]
List of changes: https://github.com/wazuh/wazuh-qa/wiki/Deployer-pipeline/_compare/cb909af96c16fd6f48620af4c5ffb6f72c6d3c72...4f09d29b07e98858539babe8b0ba20ac64c5feab

LGTM

**Comment by davidjiglesias** [comment]
LGTM!
