### ISSUE TITLE
Agent Simulator Syscollector package event is broken

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4772]
### Current behavior
The agent simulator is encountering issues in producing Syscollector package type events that conform to the valid format. The generated events appear to deviate from the correct structure, resulting in the following errors in the manager's.

`2023/12/18 17:40:19 wazuh-analysisd[29839] syscollector.c:341 at DecodeSyscollector(): DEBUG: Invalid message type: packages.`

This can be solved changing the `packages` event type for the `program`

### Expected behavior
The Syscollector package events generated by the agent simulator need to adhere to the correct format and be successfully transmitted to the manager without errors.

**Comment by Rebits** [comment]
| Developer Branch |
| ---  |
| `fix/4772-ag-syscollector-packages-event`| 
 

***

- Replaced `packages` with program in the AS Syscollector events

**Comment by davidjiglesias** [comment]
LGTM
