### ISSUE TITLE
FIM System tests: Test common actions results

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#479]
### Objective

It is necessary to perform extensive tests on the common actions of the FIM test suite, these actions are what executes a change (user behavior simulation) before our tests scenarios are run.

### Tests

- [x] Test **Create n files on the specified path**  (@jm404)

- [x] Test **Randomly delete n files**. by (@rshad)

- [x] Test **Modify attributes and content of selected files** (@xr09)

- [x] Test **Clean up all hosts (Managers and Agents and ES index)** (@rshad & @jm404 )

- [x] Test **Alerts logged to alerts.json** (@Zenidd)

- [x] Test **Alerts logged to Elasticsearch** (@DFolchA)

### Testing workflow

- Create empty testing environment
- Execute action
- Test action
  - Check expected behavior
  - Check alerts logged to alerts.json
  - Check alerts logged to Elasticsearch

**Comment by Zenidd** [comment]
Hi team,

The `verify_alerts_json.py` logging test script has been checked agains 100000 syscheck alerts:

```shell
[root@serv-test-manager-centos-1 vagrant]# time sudo python3.6 compare.py -f files.txt -e added
Test passed

real	0m4.202s
user	0m1.913s
sys	0m0.756s
```
The name for the parameters above may vary in the final version of the script.

**Comment by xr09** [comment]
File modification script was tested on both Linux and Windows.

Executed test workflow

-  File creation with sample config

```
{
    "root_folder": "/opt/testing/",
    "recursion_level": 3,
    "folder_length": 5,
    "file_length": 5,
    "file_size_specifications":[
        { "size": 10240, "amount": 10000},
        { "size": 524288, "amount": 500},
        { "size": 1048576, "amount": 100},
        { "size": 10485760, "amount": 10}
    ],
}
```

This execution generated an output file which was passed to `files_modify.py`.

![Screenshot_20200217_185044](https://user-images.githubusercontent.com/1380243/74676462-67777080-51b6-11ea-9646-c133c4414c22.png)

![Screenshot_20200217_185048](https://user-images.githubusercontent.com/1380243/74676473-6a726100-51b6-11ea-886c-3fb6c68fd81f.png)

**Comment by DFolchA** [comment]
Hello team,

I have testes the Elasticsearch alert verification script in the following cases:

**Added alert:**
- [x] 100 files
- [x] 1000 files
- [x] 10000 files
- [x] 100000 files

**Deleted alert:**
- [x] 100 files
- [x] 1000 files
- [x] 10000 files
- [x] 100000 files

**Modified alert:**
- [x] 100 files
- [x] 1000 files
- [x] 10000 files
- [x] 100000 files

All of them were tested using the same Elasticsearch index and I have not noticed any degradation.
```
$ time ansible-playbook -i dev_hosts ../fim/common_tasks/verify_alerts.yml -v -e "file_list_path=/home/vagrant/files100000.txt syscheck_event=added"

real    1m35,395s
user    0m7,376s
sys     0m0,847s

$ time ansible-playbook -i dev_hosts ../fim/common_tasks/verify_alerts.yml -v -e "file_list_path=/home/vagrant/files100000.txt syscheck_event=modified"

real    1m31,317s
user    0m7,099s
sys     0m0,853s

$ time ansible-playbook -i dev_hosts ../fim/common_tasks/verify_alerts.yml -v -e "file_list_path=/home/vagrant/files100000.txt syscheck_event=deleted"

real    1m21,662s
user    0m6,248s
sys     0m0,837s

```

All the tests have been performed on the default vagrant test environment.

Regards,
Daniel Folch

Regards,
Daniel Folch

**Comment by jm404** [comment]
### Create n files on specified path

I launched the following playbook 
```yml
---
  - hosts: masters
    vars_files:
      - ../vars/main.yml
    tasks:
      - name: copy 
        copy:
          src: "./files_configuration.json"
          dest: "/tmp/files_configuration"
        when: 
          - inventory_hostname in groups['masters']        

      - name: "Creating files"
        script: "files_generator.py -c /tmp/files_configuration -o /tmp/results"
        args:
          executable: "python3"
        when: 
          - inventory_hostname in groups['masters']
    become: yes
```

### Results

```root@anonymous:/home/anonymous/Desktop/wazuh-qa/tests/system/fim/common_tasks# time ansible-playbook create_files.yml -i ../../provisioning/dev_hosts 

PLAY [masters] ************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************
ok: [172.16.0.111]

TASK [copy] ***************************************************************************************************************************************************************
ok: [172.16.0.111]

TASK [Creating files] *****************************************************************************************************************************************************
changed: [172.16.0.111]

PLAY RECAP ****************************************************************************************************************************************************************
172.16.0.111               : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


real    0m3.635s
user    0m0.985s
sys     0m0.175s
```

**Comment by rshad** [comment]
Hi all!

On the following, I provide a resume of the experiments I made to verify the creation and deletion of files in the agents and detect the expected alerts in the manager.

**Experiment 1** 

- **_The number of created files:_** 11511 ✔️ 
- **_The number of detected files' alerts:_**: 11510 **"1 less!!"** ❌ 
- **_The number of deleted files:_** 11510 ✔️ 
- **_The number of deleted files:_** 11510 ✔️ 

**_Notes_**
As you can see, a file of the 11511 files was not detected by the _manager_; After using the script [`tests/tests/system/fim/common_tasks/verify_alerts_json.py`](https://github.com/wazuh/wazuh-qa/blob/fim-system-tests/tests/system/fim/common_tasks/verify_alerts_json.py) to check which one if the files is causing the issue, we then found that is the one of `1GB` of size.  

After checking the log file `/var/ossec/logs/ossec.log` we found the `WARNING` message:
```
2020/02/18 14:29:45 ossec-syscheckd: WARNING: '/etc/testing_folder/msxuv/kzvoysml' filesize is larger than the maximum allowed (1024 MB). File skipped.
```

Then as the maximum size for a file to be monitored is of 1024MB then we must adapt our tests to it.

**Experiment 2** 

- **_The number of created files:_** 5000✔️ 
- **_The number of detected files' alerts:_**: 5000 ❌ 
- **_The number of deleted files:_** 5000 ✔️ 
- **_The number of deleted files:_** 5000 ✔️ `Read Note`

**_Notes_**

_**Syscheck**_ was not able to scan the deletion of all 5000  files in only 1 scan but needed until the 3rd scan to cover the alerts related to the deletion of all 5000 files.

Kr,

Rshad
