### ISSUE TITLE
Upgrade paramiko to > 3.4.0

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4795]
### Description

Regarding https://github.com/wazuh/wazuh-jenkins/issues/6100#issuecomment-1867525610, due to a vulnerability detected in paramiko library prior to 3.4.0, it needs to be updated to a version later than 3.4.0, while checking its compatibility with other libraries required.

In addition it would be necessary to document which tests or modules make use of this dependency

**Comment by pro-akim** [comment]
## Update

Paramiko dependency vulnerability is not being detected anymore

![image](https://github.com/wazuh/wazuh-qa/assets/125690423/5f71b621-79eb-4cd2-908c-7dc4453115de)

This issue will remain closed until news

**Comment by Rebits** [comment]
Removed paramiko dependency in 499b51a598ff9aecfb9d498c0f15d7c605b2a7b1
