### ISSUE TITLE
Fix `verions` typo in 4.8.x branches

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#4835]
## Description

A typo has been found in the PR https://github.com/wazuh/wazuh-qa/pull/4834/files

> agent1_user: "ossec" #Only valid for agents `verions`<4.2.5
> agent3_user: "root" #Only valid for agents `verions`=>4.2.5

As this typo is too frequent and easy to write, a recursive grep must be done to clean all possible occurrences

**Comment by QU3B1M** [comment]
LGTM!
