### ISSUE TITLE
DTT1 - Iteration 3 - Test module - Remove usage of Playbook class

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4846]
> Epic #4495

## Description
This issue aims to replace the usage of **Playbook** with the new attributes of the **Ansible** class included in the **Provisioner** at the last iteration
### Tasks
- [x] Remove the Playbook class and all the imports
- [x] Replace `Playbook.PLAYBOOKS_PATH` with `Ansible.playbooks_path`

**Comment by fcaffieri** [comment]
LGTM
