### ISSUE TITLE
DTT1 - Iteration 3 - Provision module - Improvement in the use of Jinja2 templates

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4858]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4852

---

## Description

The objective of the issue is to improve the use of Jinja2 templates since currently the tasks are generated for all types of distribution and it is required to generate only for the requested distribution since it avoids skipping steps that are not distribution-specific.

## Tasks

- [x] Investigate the possibility of obtaining the ansible_os_family on the host.
- [x] Implement the logic for generating the templates depending on the distribution, it can be with os_family or directly with the distribution sent by parameter.

**Comment by pro-akim** [comment]
## Update
Adding in /deployability/modules/allocation/static/specs/os.yml specificactions about `os_family` and changing the method `_parse_config` in `/deployability/modules/allocation/vagrant/provider.py` and  `_parse_config`  in `/deployability/modules/allocation/aws/provider.py`
It was possible to have the same current results, but having `os_family` specifications

**Comment by pro-akim** [comment]
## Update

The approach to make the playbook (templated by jinja2) work dynamically will be as follows:
1. The template will be structured with conditionals.
2. The template will behave differently if the `ansible_family_os` value exists or if it doesn't.
3. Initially, it will execute without having it (the function to search for `ansible_family_os` and store it in a Python variable).
4. It will then execute again and only apply to those tasks that expect `ansible_family_os`.

**Comment by pro-akim** [comment]
## Update
Moved to on hold, working on a issue with higher priorities.

**Comment by pro-akim** [comment]
## Update
After discussing the best approach it concluded that the `ansible_family_os` should be obtained separately and used as a variable when jinja2 templates are run.

**Comment by pro-akim** [comment]
## Update
Enhancement done.

Moved to pending review
