### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module - Fix Vagrant inventory IP is always localhost

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4874]
> Epic #4855

## Description
This issue aims to fix the Vagrant provider retrieving always 127.0.0.1 as VM's IP, this problem occurs because `vagrant ssh-config` returns the default `config.ssh` values, a possible fix is to define `config.ssh.host` with the provider configured IP ([check this guide](https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings)).

### Tasks
- [x] Research in the Vagrant docs how to properly configure VM's `config.ssh`.
- [x] Apply the solution and verify the inventory is usable by the rest of modules.

**Comment by QU3B1M** [comment]
### Extra info

Possible solution tested in a local `Vagrantfile`, the command `vagrrant ssh-config` retrieves the info required, but the `vagrant up` fails by timeout (the VM is turning on) and `vagrant ssh` won't connect to the machine.

Output of `vagrant up` with error:

```shellsession
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'generic/ubuntu2004'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'generic/ubuntu2004' version '4.3.8' is up to date...
==> default: Setting the name of the VM: test_default_1705674568055_3441
==> default: Fixed port collision for 22 => 2222. Now on port 2201.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2201 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.57.3:2201
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by QU3B1M** [comment]
## Update report
After some research and testing we found that in order to do the desired configuration, we need to manually set every `ssh` option for the machine, including the guest and host ports on the **`Vagrantfile`** using `config.ssh`. Anyway, with that configuration we accomplish one successful execution and then the errors start over.

Continuing with the research.

**Comment by pro-akim** [comment]
## Review Notes
Tests :green_circle: 
LGTM
