### ISSUE TITLE
Adapt stress test to new vulnerability detector

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-qa#4882]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
|  >= 4.8.0 alpha 2 |  https://github.com/wazuh/wazuh/issues/21523 |   |

## Description

According to the implementation of the new vulnerability detector, it is necessary to adjust the stress test with which the module is stressed.  

Vulnerability Detector now is only based on events: new packages or uninstallations.

In this new version, it is not useful to lower the `<frequency>` configuration (because there is none), what you have to do is to lower the `<frequency>` of Syscollector and also install and uninstall packages very frequently.

Related [comment](https://github.com/wazuh/wazuh/issues/21523#issuecomment-1910208837)

**Comment by Rebits** [comment]
Duplicated [Issue #6172](https://github.com/wazuh/wazuh-jenkins/issues/6172)

The ongoing effort to address this concern is detailed in the corresponding Pull Request: [PR #6201](https://github.com/wazuh/wazuh-jenkins/pull/6201). Please refer to the PR for the latest updates and progress on resolving this issue.
