### ISSUE TITLE
DTT1 - Iteration 3 - Provision module - Validations and error handling 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4903]
> Epic #4852

## Description

The objective of this issue is to incorporate error handling and validations necessary for the Provision module, this includes implementing the logger to log the errors and/or warnings. also having a good error handling strategy

### Tasks

- [x] Improve error handling.
- [x] Improve validations.
- [x] Log errors and warnings

**Comment by pro-akim** [comment]
## Update
LGTM

**Comment by fcaffieri** [comment]
LGTM
