### ISSUE TITLE
DTT1 - Iteration 3 - WorkFlow engine module improvements and fixes

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4905]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

The goal of this issue is to generate a deliverable package with a stable version of the Workflow Engine. It must contain the following tasks

## Taks

- [x] https://github.com/wazuh/wazuh-qa/issues/4906
- [x] https://github.com/wazuh/wazuh-qa/issues/4907
- [x] https://github.com/wazuh/wazuh-qa/issues/4908
- [x] https://github.com/wazuh/wazuh-qa/issues/4909
- [x] https://github.com/wazuh/wazuh-qa/issues/4910
- [x] https://github.com/wazuh/wazuh-qa/issues/4989

**Comment by fcaffieri** [comment]
LGTM

**Comment by rauldpm** [comment]
Reopened as a new task has been added

**Comment by fcaffieri** [comment]
Finished the release of the Workflow
