### ISSUE TITLE
DTT1 - Iteration 3 - WorkFlow engine module - Implement logger

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4907]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4905

---

## Description

The objective of this issue is to generate a log tracking taking into account:

- ID of the flow that is being executed. This is because 2 flows could be executed at the same time and the log would fall into the same log file, which would make it impossible to identify which flow each line corresponds to.
- ID of the thread that is running. This is to identify the thread of each module and be able to order the logging by this ID so that in the event of a failure in a thread, we can identify which failure and differentiate it from other threads.
Format: [INFO] [FLOW_ID] [THREAD_ID]

## Taks

- [x] The workflow must generate the logger models with the IDs
- [x] Generate the FLOW_ID
- [x] Generate the THREAD_ID
- [x] It must allow the tracking of a flow and each parallel execution of the modules.

**Comment by QU3B1M** [comment]
## Progress status
- Added new logger handler for the workflow_engine module
- Improving log messages 
- Capturing the logs from the executed modules and apply the logger format to them. WIP

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by fcaffieri** [comment]
LGTM
