### ISSUE TITLE
DTT1 - Iteration 3 - WorkFlow engine module - Error handling

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4908]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4905

---

## Description

The objective of this issue is to incorporate error handling and validations necessary for the Workflow engine module, this includes implementing the logger to log the errors and/or warnings. also having a good error-handling strategy

## Taks

- [x] Improve error handling.
- [x] Improve validations.
- [x] Log errors and warnings

## Extra Task

After an analysis, the following task is incorporated to be implemented in this issue

- [x] Incorporate the capture of the cancellation of the execution and delete everything created so far

**Comment by fcaffieri** [comment]
### Update status

We began with the analysis to detect possible failures to begin generating error handling. Once listed, the modifications are made.

**Comment by fcaffieri** [comment]
##Status

After the analysis, the need arises to implement the capture of the cancellation of the execution of the process by the user, to clean and not leave processes or VMs up in case it is necessary to abort the execution.

There were 2 ways to do this:
1- Use the "KeyboardInterrupt" exception
2- Use the signal capture to call the cleaning method

1- "KeyboardInterrupt":
The problem with this is that you would have to do a try except for the entire code.

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/fb8b0d7e-863e-4231-8d2c-0fe62c8027a8)


2- Implementing signal capture, the only problem found is that for some reason the logger does not work, but it does capture the signal and execute the cleaning steps.

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/68b82163-ed91-4506-819e-3ba9c4291a2f)

**Comment by fcaffieri** [comment]
### Update

After various testing and adjustments, we attempted to make minimal modifications to the workflow engine code to handle user cancellation of the workflow. To achieve this, it was decided to reuse the re-execution of the tasks with the "reverse" option activated, with the aim of eliminating only the machines that had been started. This approach will only be effective if the flow has the "clean up" tag in the input YAML file.

This alternative was chosen with the purpose of making minimal changes to the workflow engine code, thus facilitating delivery and avoiding the introduction of unwanted errors due to logical failures.

Later, the possibility of improving this flow will be considered so that it is not necessary to depend on the "clean up" tag to eliminate what was generated when canceling the execution.

**Comment by pro-akim** [comment]
## Review Notes

Some changes were requested.

**Comment by pro-akim** [comment]
## Review Notes
LGTM
Moved to final review

**Comment by rauldpm** [comment]
LGTM
