### ISSUE TITLE
macOS provisioning fail due to missing handler

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4930]
### Description

During https://github.com/wazuh/wazuh/issues/21789 it has been detected that macOS instances are not correctly provisioned due to a typo in macOS restart handler introduced during the revision of this PR https://github.com/wazuh/wazuh-qa/pull/4878
```
10:38:31  TASK [../roles/wazuh/ansible-wazuh-agent : Install MacOS agent from pkg | custom macos pkg] ***
10:38:31  changed: [agent1]
10:38:45  ERROR! The requested handler 'MacOS | restart wazuh-agent' was not found in either the main handlers list nor in the listening handlers list
```

It is necessary fix this issue in order to provision macOS endpoint for VD E2E tests

**Comment by davidjiglesias** [comment]
LGTM
