### ISSUE TITLE
Vulnerability Detection configuration change not updated in E2E tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4935]
### Description

During [Release 4.8.0 - Beta 1 - Vulnerability Detector E2E Tests](https://github.com/wazuh/wazuh/issues/21789), it was discovered that our vulnerability detection tests lack implementation for keystore management and are using a deprecated configuration schema.

### Proposed Solution:

To address this issue, we need to update the configuration utilized for End-to-End vulnerability tests. Additionally, it's essential to incorporate a fixture that ensures the keystore is properly added to all environment managers.

### Further Details
For more context and related information, refer to [Implement put method and create a tool for the keystore management](https://github.com/wazuh/wazuh/issues/21576).

**Comment by Rebits** [comment]
This issue depends on https://github.com/wazuh/wazuh-qa/issues/4936

**Comment by davidjiglesias** [comment]
LGTM
