### ISSUE TITLE
Bug in System file modification method for Linux Endpoints

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4936]
### Description

During [Vulnerability Detection configuration change not updated in E2E tests](https://github.com/wazuh/wazuh/issues/21789), it was discovered a bug introduced in https://github.com/wazuh/wazuh-qa/pull/4878 in the modify file HostManager method.

Now it is not possible to edit files in remote Linux host, due to the destination path is not correctly parsed.

**Comment by davidjiglesias** [comment]
LGTM
