### ISSUE TITLE
Monitoring remote E2E logs infinite loops when no timestamp is used

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4937]
### Description

During the investigation of [issue #21789](https://github.com/wazuh/wazuh/issues/21789), a bug was identified in the E2E (End-to-End) testing framework related to the monitoring events function. This bug was introduced by changes made in [Vulnerability Detector E2E Tests](https://github.com/wazuh/wazuh-qa/pull/4878). Specifically, when a timestamp is not provided to filter events and logs do not appear, the monitoring loop fails to terminate, causing indefinite execution.

**Comment by Rebits** [comment]
Developed a fix for this behavior. Currently testing it

**Comment by davidjiglesias** [comment]
LGTM
