### ISSUE TITLE
Bug in System package installation method for Linux Endpoints

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4939]
### Description

During [Vulnerability Detection configuration change not updated in E2E tests](https://github.com/wazuh/wazuh/issues/21789), it was discovered a bug introduced in https://github.com/wazuh/wazuh-qa/pull/4878 in the installation package HostManager method.

Now it is not possible to edit install packages in remote Linux host, due to the package URL is not parsed correctly

**Comment by davidjiglesias** [comment]
LGTM
