### ISSUE TITLE
Failed system tests due to KeyError

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4941]
## Description

During the release of the system tests for 4.8.0 Beta 1, carried out in https://github.com/wazuh/wazuh/issues/21787, it was found that most of the tests failed due to a KeyError. You can see the attached reports [here](https://github.com/wazuh/wazuh/issues/21787#issuecomment-1932420086).

These tests are dependent, and some may not have failed explicitly because of the KeyError but may be affected by a previous KeyError.

We should fix this error and check that all system tests pass as expected.

**Comment by Rebits** [comment]
KeyError was produced by bug reported here https://github.com/wazuh/wazuh-qa/issues/4936
Fix seems to be solved [here](https://github.com/wazuh/wazuh-qa/pull/4954)

However, it seems it is failing in `get_host_variables` method. Currently testing fix

**Comment by pro-akim** [comment]
## Review Notes
LGTM

Tested: 
[agentless.zip](https://github.com/wazuh/wazuh-qa/files/14267741/agentless.zip)
