### ISSUE TITLE
Realtime alerts.json verification

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-qa#496]
Hi team,

This issue aims to improve the script current ability to detect missing `generated/modified/deleted` alerts related to the generated files and improve its failure-tolerance.

- The alerts file should be periodically browsed and compared to the file list as the number of alerts grows.
- When the number of the related alert stops growing and there are still missing alerts, there will be a parameterizable number of retries.

Greetings, JP Sáez

**Comment by jm404** [comment]
Done in #498
