### ISSUE TITLE
FIM performance test: Events generation

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4964]
## Description 

As part of https://github.com/wazuh/wazuh-qa/issues/4963, we need to create a script that can generate real FIM events on Linux and Windows agents that stress the manager.

### Requirements

- The test should generate FIM events, that is, creation, modification or deletion of files.
- If possible, it will be possible to choose by parameters what kind of events we want.
- The number of files can be parameterized
- The duration of the test can be parameterized
- We should not add many lines to the files, but modify them, or they will consume disk space.

**Comment by juliamagan** [comment]
### Update

We have created a first approach, in which finally, the only events that will be performed during the execution of the test are creation and modification, since choosing the type of event takes some complexity because you cannot have modification or deletion events without generating creation events.

**Comment by Rebits** [comment]
Some minor suggestions regarding the script:
- The script does not handle the amount of events per second. It will perform constant changes in files. Currently we are not able to determinate metrics of how many events the manager can handle or customize the testing
- File modification should match more real cases, making bigger changes in the file. Or at least allow to change the size of the modifications done to the files
- We can handle the removal of the files at the end of the test to improve usability
- We can handle abort signal to improve usability
