### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module - Add userData script for AWS EC2 instances

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-qa#4988]
The procedure for deploying the machines in AWS in the wazuh-qa and wazuh-dev account includes the execution of a [script](https://github.com/wazuh/wazuh-automation/blob/4.8.2/aws/cloud-providers-admin/aws/userData/sshPortConfigurator.sh) created by the devops team that is responsible for configuring the SSH port on port 2200, to increase the security of the connection.

- [x] Consider the configuration of this script in the userData of the machines provisioned with AWS and configure port 2200 in the inventory

**Comment by QU3B1M** [comment]
LGTM!

**Comment by fcaffieri** [comment]
LGTM
