### ISSUE TITLE
DTT1 - Iteration 3 - WorkFlow engine module - Release Workflow module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4989]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4905

---

## Description

The objective of this issue is to deliver the Workflow engine module so that it can be used by the team.

## Tasks

- [x] Generate branch from 4.9.0
- [x] Copy the entire module

**Comment by QU3B1M** [comment]
LGTM!

**Comment by pro-akim** [comment]
## Review Notes
LGTM
