### ISSUE TITLE
Update Packages Used in `TestScanSyscollectorCases`

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh-qa#4991]
## Description

The `TestScanSyscollectorCases` need to be updated. The E2E tests are located in the file [test_vulnerability_detector.py](https://github.com/wazuh/wazuh-qa/blob/v4.8.0-beta1/tests/end_to_end/test_vulnerability_detector/test_vulnerability_detector.py).

### Steps to update the tests:

- Add package metadata to [vuln_packages.json](https://github.com/wazuh/wazuh-qa/blob/v4.8.0-beta1/deps/wazuh_testing/wazuh_testing/end_to_end/vulnerability_detector_packages/vuln_packages.json) using results from https://github.com/wazuh/wazuh-qa/issues/4943

- Edit the [cases](https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta1/tests/end_to_end/test_vulnerability_detector/cases) used by the test (cases directory of the E2E Vulnerability tests)

### Steps to test:

- Run the tests in a real environment with the new packages and review the information obtained ([Test_e2e_system](https://ci.wazuh.info/job/Test_e2e_system/) Pipeline)

**Comment by rafabailon** [comment]
## Update

I have created the following branches:

- `feature/4991-update-packages-in-TestScanSyscollectorCases`
- `temporary/4991-vulnerability-detector-tests`

The temporary branch also contains the changes of @Rebits to be able to test the pipeline. This is the execution of the pipeline: https://ci.wazuh.info/job/Test_e2e_system/236/console

I'm waiting for it to finish to do the checks.

**Comment by rafabailon** [comment]
### Update

I have launched the pipeline to create the VMs necessary to run the tests (except MacOS). I have launched the tests manually and they have not worked because Windows does not install the `.exe` packages and the `.msi` packages in the same way.

I have run the tests only for Linux and they have finished. These are the results [Linux_Tests.zip](https://github.com/wazuh/wazuh-qa/files/14513241/Linux_Tests.zip)

I have had to modify the code to allow the installation of `.msi` packages on Windows. I have to repeat the tests for Windows.

**Comment by davidjiglesias** [comment]
LGTM
