### ISSUE TITLE
Update the data visualization script to support API statistics files

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-qa#5022]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.8.0  |  https://github.com/wazuh/wazuh-qa/issues/4890 | https://github.com/wazuh/wazuh-qa/pull/4970 |

## Description

The [statistic monitor script](https://github.com/wazuh/wazuh-qa/blob/4.8.0/deps/wazuh_testing/wazuh_testing/scripts/wazuh_statistics.py) has been modified to gather information from the API rather than the `.state` files. The new files generated from the API information have a different structure and there has been no changes to the [data visualization script](https://github.com/wazuh/wazuh-qa/blob/4.8.0/deps/wazuh_testing/wazuh_testing/scripts/data_visualizations.py) to generate graphics for them.

This issue aims to apply the changes necessary for the graphic generation of the new files to work properly.

Statistics files containing information gathered from the API: [api_stats_files.zip](https://github.com/wazuh/wazuh-qa/files/14387588/api_stats_files.zip)

## Proposed checks

- [ ] Update the data visualization script to generate graphics for the new files
- [ ] Validate that the graphics are generated successfully for every new file

**Comment by juliamagan** [comment]
We should check if the graphs are generated correctly to work on this issue or if it was finally fixed, to close it as not planned.

**Comment by juliamagan** [comment]
Duplicated: https://github.com/wazuh/wazuh-jenkins/issues/6203
