### ISSUE TITLE
`test_synchronization` system test tries to load a `list` as a `JSON`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5043]
## Description

- Source issue: https://github.com/wazuh/wazuh-qa/issues/5024

The `test_synchrronization.py` is being marked as failed because it tries to load a list as a JSON. The steps are:

1. The test makes a query to wazuh-db to obtain a fim entry, this is done at:

https://github.com/wazuh/wazuh-qa/blob/ef98f911d3736c9c71d37f14477c20d6222992fb/tests/system/test_fim/test_synchronization/test_synchronization.py#L153

2. That call gets the query using the Python script:

https://github.com/wazuh/wazuh-qa/blob/master/tests/system/scripts/system_query_db.py

3. Then, the query result is loaded as a JSON at:

https://github.com/wazuh/wazuh-qa/blob/ef98f911d3736c9c71d37f14477c20d6222992fb/tests/system/test_fim/test_synchronization/test_synchronization.py#L154

But the query result is given as a list:

```
root@wazuh-manager: /var/ossec/queue/db# python /var/system_query_db.py --db_path /var/ossec/queue/db/001.db --query "select * from fim_entry where full_path='/testdir1/testdir1.txt'"
[(u'/testdir1/testdir1.txt', u'/testdir1/testdir1.txt', u'file', 1709054500, 1, None, None, None, 0, u'rw-r--r--', u'0', u'0', u'd41d8cd98f00b204e9800998ecf8427e', u'da39a3ee5e6b4b0d3255bfef95601890afd80709', u'root', u'root', 1709054494, 2079376, u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', None, None, u'e79c68b86d746f1c88bcf337ba9462aeee68fad6')]
```

JSON does not know how to interpret it, resulting in the following error and failed test:

```
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

This can be reproduced using the following Python script:

```
import json

def test():
    s = "[(u/testdir1/testdir1.txt', u'/testdir1/testdir1.txt', u'file', 1709054500, 1, None, None, None, 0, u'rw-r--r--', u'0', u'0', u'd41d8cd98f00b204e9800998ecf8427e', u'da39a3ee5e6b4b0d3255bfef95601890afd80709', u'root', u'root', 1709054494, 2079376, u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', None, None, u'e79c68b86d746f1c88bcf337ba9462aeee68fad6')]"
    #s = "[]"
    #s = '{"name":"John", "age":30, "car":null}'
    #s = '{}'
    assert not json.loads(s)
```

It has been detected that sometimes, the query is returned as an empty list, in this case, the JSON load call accepts it and the test passes, marking the test as PASSED

If the query is given as a JSON with content, the test will fail (expected), and if the JSON query is empty, then the test will PASS

We need to review and fix this test to avoid false positives and convert the query list as a query JSON

---

Cataloged as `High impact bugs` because the test does not always fail, and if it does, the test will fail due to the assert (regardless of the format of the result), so we have to fix the format so that the error message is correct and we can catalog correctly the error

**Comment by rafabailon** [comment]
### Update

I have changed the way the queries are executed to use the same method as in other scripts. I have also changed the assert condition to adapt it to the new way of obtaining the data.

I have done tests locally, getting the tests to pass completely 10 times in a row.

**Comment by rafabailon** [comment]
### Note

The issue is in `Pending Final Review`. The review and the merge are missing. I move the ETA.

**Comment by rauldpm** [comment]
LGTM
