### ISSUE TITLE
Refactor InitialScan Vulnerability Detection E2E tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5067]
### Description

In version 4.8.0 Beta 2, the default behavior of the vulnerability detection module underwent a significant alteration, as detailed in the pull request at https://github.com/wazuh/wazuh/pull/21989.

With this update, the module now operates reactively to events. Notably, existing packages on the endpoint will no longer trigger alerts; instead, vulnerabilities already present in the environment will be exclusively indexed in the vulnerability state index without generating alerts.

This modification necessitates adjustments to the E2E `InitialScan` tests for the Vulnerability Detection. Specifically:
- Removal of initial alerts scan tests
- Elimination of tests rendered obsolete by the update (such as test alert and index consistency)

Furthermore, feeds are no longer included in the package, so, it is imperative to update the `wait_until_feed_update` fixture to ensure it waits until all feed files have been processed.

**Comment by Rebits** [comment]
| Development Branch |
| --- | 
| `fix/5050-refactor-vd-e2e-initial-scan` |

**Comment by Rebits** [comment]
During refactoring, an error has been identified in the `tests_syscollector_first_second_scan_consistency_index` tests. The `_score` metadata in Elasticsearch, which signifies the relevance of a match to the query, fluctuates between scans, causing the test to fail when it shouldn't.

As a solution, we are currently modifying these tests to solely compare package and vulnerability data values, eliminating reliance on _score for consistency.

**Comment by rafabailon** [comment]
### LGTM

**Comment by davidjiglesias** [comment]
LGTM
