### ISSUE TITLE
Vulnerability Detector E2E test does not continue if setup fails

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5097]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that when the test fails in the setup of a host, the test is aborted and does not launch for the rest of the hosts. It was a development requirement that the test should be able to advance even with failed setups, so it is necessary to review the implementation of these tests to allow this feature.

Specifically, it has been seen for `test_vulnerability_detector_scans_cases[upgrade_package_maintain_vulnerability]`, but we should ensure that this behavior does not occur in any test.

Report: [Test_e2e_system_244_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh-qa/files/14600595/Test_e2e_system_244_test_vulnerability_detector.zip)

**Comment by MARCOSD4** [comment]
The changes requested in this issue have been made in the following branch:

| Development Branch |
| --- | 
| `bug/5097-fix-setup-vd-e2e-tests` |
