### ISSUE TITLE
No ARM packages for Vulnerability Detector E2E tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5098]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that there are no ARM packages:

```
E               ValueError: Package for centos and arm64v8 not found
```

We need to search for and add ARM packages so that these tests can test as many packages as possible.

Report: [Test_e2e_system_244_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh-qa/files/14600595/Test_e2e_system_244_test_vulnerability_detector.zip)

**Comment by rafabailon** [comment]
## Update

This issue is related to https://github.com/wazuh/wazuh-qa/issues/5103 In the PR `Grafana` packages for `arm64v8` (Ubuntu and CentOS) have been added. The test results are in the PR.
