### ISSUE TITLE
System enrollment_cluster tests fail in 4.8.0-beta4

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5101]
### Description

During [Release 4.8.0 - Beta 4 - System tests](https://github.com/wazuh/wazuh/issues/22481) it has been detected unexpected errors
in the enrollment_cluster environment tests `test_assign_groups_guess`,  `test_group_sync_status` and `test_group_sync_status`

- `test_assign_groups_guess`: 

Probably the error is due to a timeout. We can see the expected log in the worker log:
```
2024/03/14 00:15:21 wazuh-remoted[47413] manager.c:595 at assign_group_to_agent_worker(): DEBUG: Sending message to master node: '{"daemon_name":"remoted","message":{"command":"assigngroup","parameters":{"agent":"003","md5":"ce01ce69f8872a1f9c6af6d989be958e"}}}'
```

- `test_remove_group`

```
E                   TimeoutError: Did not found the expected callback in wazuh-master: .*Agent-groups send full.* Finished.*
```

However, expected log is present in the master log file:
```
2024/03/14 02:47:48 INFO: [Worker wazuh-worker1] [Agent-groups send full] Finished in 3600.008s. Updated 1 chunks.
```

Further research is required

- `test_group_sync_status`

Assertion error:

```
       AssertionError: assert 'syncreq' == 'synced'
E         - synced
E         ?      ^
E         + syncreq
E         ?     + ^
```

### Evidences

- **Test case**: 
  - test_guess_multigroups[wazuh-worker1-0-1]
  - test_group_sync_status[delete_folder_master_agent_all-wazuh-master]
  - test_group_sync_status[delete_folder_master_agent_all-wazuh-worker1]
  - test_group_sync_status[delete_folder_master_agent_all-wazuh-worker2]
  - test_group_sync_status[delete_folder_master_agent_agent2-wazuh-worker2]
  - test_remove_group[wazuh-worker1-group_test-worker1_folder]

- **Report**:  [enrollment_cluster.zip](https://github.com/wazuh/wazuh-qa/files/14601419/enrollment_cluster.zip)

**Comment by Rebits** [comment]
Running failed tests in an environment with higher resources appears to result in passing the tests.

[EnrollmentCluster.zip](https://github.com/wazuh/wazuh-qa/files/14652656/EnrollmentCluster.zip)

**Comment by Rebits** [comment]
### Failures Analysis


<details>

<summary> `test_remove_group` </summary>

Expected message `2024/03/14 02:47:48 INFO: [Worker wazuh-worker1] [Agent-groups send full] Finished in 3600.008s. Updated 1 chunks.` can be found in master logs.

If we examinate the logs of the test we can see that the monitoring start at `2024-03-14 01:47:17,104``

```
2024-03-14 01:47:17,104 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-master and message: .*Agent-groups send full.* Finished.*
``` 

We can see that there is a 1 hour difference between the node that launches the testing process and the instances.
Is necessary to research if this discrepancy can lead into unexpected failures




</details>

**Comment by Rebits** [comment]
Moved ETA to 22/03/2024 to allow review

**Comment by rafabailon** [comment]
### LGTM

**Comment by Rebits** [comment]
Testing agentless cluster system tests in proposed System environments

**Comment by Rebits** [comment]
- System tests fail again after changes
- Running tests again in a new environment with higher resources

**Comment by Rebits** [comment]
Currently reviewing results in new environment

**Comment by Rebits** [comment]
Enrollment tests seem to be stabilized:

- [EnrollmentSystemTests.zip](https://github.com/wazuh/wazuh-qa/files/14849350/EnrollmentSystemTests.zip)
