### ISSUE TITLE
Check possible unexpected pass for Grafana packages

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5103]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that tests that do not expect alerts pass correctly. However, after speaking with @Rebits, it is possible that no alerts are generated because the packages we are using did not generate alerts either when there were vulnerabilities. We should review these packages manually and change them if they never generate alerts, or open another issue to the development team in charge of the module if they only do not generate alerts when there are vulnerabilities.

Report: [Test_e2e_system_244_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh/files/14590221/Test_e2e_system_244_test_vulnerability_detector.zip)

**Comment by rafabailon** [comment]
## Info

<details>
   <summary>Manager</summary>
   <br/>

```console
root@ubuntu2204:/home/vagrant# uname -r
5.15.0-91-generic

root@ubuntu2204:/home/vagrant# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@ubuntu2204:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40806"
WAZUH_TYPE="server"
```

</details>

<details>
   <summary>Agent</summary>
   <br/>

```console
root@ubuntu2204:/home/vagrant# uname -r
5.15.0-91-generic

root@ubuntu2204:/home/vagrant# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@ubuntu2204:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40806"
WAZUH_TYPE="agent"
```

</details>

## Initial state

- Packages:686
   - Report: [packages.csv](https://github.com/wazuh/wazuh-qa/files/14665395/packages.csv)

- Vulnerabilities: 20
   - Report: [vulnerabilities.csv](https://github.com/wazuh/wazuh-qa/files/14665402/vulnerabilities.csv)

**Comment by rafabailon** [comment]
## List of Tested Packages

| Package | Vulnerable Version | Non-Vulnerable Version | Notes |
| --- | --- | --- | --- |
| Audacity | - | - | There is no Vulnerable Version |
| Blender | 3.3.0 | 3.2.0 | No .deb Package | 
| Brave | 1.19.93  | 1.59.40  | Not Available Download |
| Calibre | 6.18.1 | 6.29.0 | No .deb Package | 
| Chrome | - | - |  There is no Non-Vulnerable Version |
| ClamAV | - | - | There is no Non-Vulnerable Version |
| Discord | - | - | There is no Non-Vulnerable Version |
| Edge | - | - | There is no Non-Vulnerable Version |
| Firefox | - | - | There is no Non-Vulnerable Version |
| GCC | 12.0 | 11.1 | No .deb Package | 
| Geary | 3.36.2 | 3.37.92 | No .deb Package |  
| Gimp | - | - | There is no Non-Vulnerable Version |
| GParted | 0.14.1 | 14.1 | Not Available Download |
| JDK | 20.0.1 | 18.0.1 | Undetected vulnerability |
| Kodi | - | - | There is no Non-Vulnerable Version |
| Libreoffice | 7.5.0 | 7.6.4 | No .deb Package | 
| MariaDB | 10.9.1  | 11.3.1  |  Not Available Download |
| MySQL | - | - |  There is no Non-Vulnerable Version |
| Nmap | 7.70 | 7.91 | No .deb Package | 
| NodeJS | 21.6.1  | 21.7.0 | No .deb Package | 
| Opera | 57.0.3098.102  | 75.0.3969.218  | Not Vulnerable in Linux |
| qBittorrent | 4.5.5 | 4.6.0 | No .deb Package | 
| Steam | - | - | There is no Non-Vulnerable Version |
| Telegram | 2.4.3 | 2.8.8 | No .deb Package | 
| Thunderbird | - | - | There is no Non-Vulnerable Version |
| Vagrant | 2.3.0  | 2.4.0 | Undetected Vulnerability |
| Virtualbox | 7.0.2  | 7.0.12  | Undetected Vulnerability |
| VLC | 3.0.19 | 3.0.20 | No .deb Package | 
| Wine | 0.9.5 | 9.4 | No .deb Package |

**Comment by Rebits** [comment]
I recommend using the Grafana OSS packages instead of the enterprise version, as they appear to match with the NVD CPE:
```
cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
```

We conducted manual testing of the package on a v4.8.0-beta4 manager. 
![image](https://github.com/wazuh/wazuh-qa/assets/11089305/60c454f1-49ce-45ac-8ac9-8ce96b43b2f0)

You can find the Grafana package at the following link:

Grafana Packkge: https://dl.grafana.com/oss/release/grafana_8.5.6_arm64.deb

Additionally, other versions of the Grafana package are available in the same repository."

**Comment by rafabailon** [comment]
## Update

This issue is related to https://github.com/wazuh/wazuh-qa/issues/5098 In the PR the `Grafana` packages have been changed. The test now uses `OSS` packages instead of `Enterprise`. Vulnerabilities for `Grafana OSS` do seem to be detected.
