### ISSUE TITLE
Add `alerts.json` to Vulnerability Detector E2E test report

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5105]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that when a test fails, the `ossec.log` of the managers and agents, as well as the test log, are attached. However, it can be useful to also attach the `alerts.json` file, since when the test indicates that the alert has not been found, we will be able to check if the alert has been triggered or not.

Report: [Test_e2e_system_244_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh/files/14590221/Test_e2e_system_244_test_vulnerability_detector.zip)

**Comment by MARCOSD4** [comment]
| Development Branch |
| --- | 
| `enhancement/5105-add-alert-json` |

**Comment by MARCOSD4** [comment]
Moved ETA to allow review
