### ISSUE TITLE
Alerts are not being filtered by timestamp

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5108]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that alerts are not being filtered by timestamp, since in different tests appear alerts from previous tests. We should adjust the code so that the alerts are filtered correctly with the timestamp, reducing test time and resources.

Report: [Test_e2e_system_244_test_vulnerability_detector.zip](https://github.com/wazuh/wazuh/files/14590221/Test_e2e_system_244_test_vulnerability_detector.zip)

**Comment by juliamagan** [comment]
|Development branch|
|--|
|`bug/5108-filter-timestamp-alerts`|


Fix applied. It remains to open the PR.

**Comment by juliamagan** [comment]
During the execution of the tests to attach the results, other problems have been encountered and we are solving them in this issue.

- We have fixed a Grafana package wrong with the expected version.
- Added not to ignore timeout errors in waiters.
- Fixed a regex
- Removed extra steps in the setup


With this last one, there are some problems when obtaining the vulnerability index of registered agents, it remains to fix this.

**Comment by rafabailon** [comment]
### LGTM

**Comment by davidjiglesias** [comment]
LGTM
