### ISSUE TITLE
Missing descriptions in Vulnerability Detector E2E tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5110]
## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it has been observed that tests that there are Vulnerability Detector tests that are missing the description. We should add the description to all tests, as it is useful to understand what the test is doing and what results are expected.

**Comment by MARCOSD4** [comment]
The changes requested in this issue have been made in the following branch:

| Development Branch |
| --- | 
| `enhancement/5110-add-descriptions-vd-tests` |

**Comment by MARCOSD4** [comment]
Moved ETA to allow review
