### ISSUE TITLE
Vulnerability Detection E2E tests: Outdated configuration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5126]
### Description

The latest update in [version 4.8.0 - Beta 4](https://github.com/wazuh/wazuh/issues/22457) introduces significant modifications to the vulnerability detection module's configuration and behavior. As a result, these alterations have caused the E2E Vulnerability Detection test to fail consistently.

Investigation is imperative to identify and implement the necessary adjustments to the tests

**Comment by Rebits** [comment]
Currently, using the test's configuration produced the following errors in the environment:

```
2024/03/20 10:41:30 wazuh-modulesd: WARNING: (1230): Invalid element in the configuration: 'indexer.certificate'.
2024/03/20 10:41:30 wazuh-modulesd: WARNING: (1230): Invalid element in the configuration: 'indexer.key'.
```

**Comment by Rebits** [comment]
Changed test configuration to:

```
	<indexer>
				    		
		<enabled>yes</enabled>
		
    
		<hosts>
			<host>https://INDEXER/API:9200</host>
			
  
		</hosts>
		
    
		<ssl>
			<certificate_authorities>
				<ca>/etc/pki/filebeat/root-ca.pem</ca>
				
  
			</certificate_authorities>
			
    
			<certificate>/etc/pki/filebeat/node-2.pem</certificate>
			
    
			<key>/etc/pki/filebeat/node-2-key.pem</key>
			
  
		</ssl>
	</indexer>
```

**Comment by rafabailon** [comment]
### LGTM
