### ISSUE TITLE
DTT1 - Add Copyright Headers.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5141]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9  | -  |  -  |

## Description
DTT will be deployed in a public repository and must include Wazuh's copyright headers.

The following modules should include the copyright header:

- [x] #5142 
- [x] #5143 
- [x] #5144 
- [x] #5145 
- [x] https://github.com/wazuh/wazuh-qa/issues/5149

**Comment by fcaffieri** [comment]
The issue was completed, each PR was pointed to the DDT1 branch of https://github.com/wazuh/wazuh-qa/issues/4495
