### ISSUE TITLE
DTT1 - Add Copyright headers to the Provision module.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5143]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9 |  #5141  | #5152   |

## Description
The DTT's Provision must include Wazuh's copyright headers because the module will be deployed in a public repository.

**Comment by QU3B1M** [comment]
Copyright headers added in PR #5152

**Comment by fcaffieri** [comment]
LGTM
