### ISSUE TITLE
DTT1 - Add Copyright headers to the Test module.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5144]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9 |  #5141  | #5153  |

## Description
The DTT's testing module must include Wazuh's copyright headers because the module will be deployed in a public repository.

**Comment by QU3B1M** [comment]
Copyright headers implemented in PR #5153

**Comment by fcaffieri** [comment]
LGTM
