### ISSUE TITLE
DTT1 - Testing - Allow single Wazuh manager test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5202]
## Description

We need to allow the DTT1 Testing module to use only a single Wazuh manager instead of a cluster, as a Wazuh manager itself can work

That means: The test should install, configure, and check all the current tests but it will not check the connection test to agents or other managers (workers) unless they exist

Related: https://github.com/wazuh/wazuh-qa/issues/4495
Origin: https://github.com/wazuh/wazuh-qa/issues/5191

**Comment by fcaffieri** [comment]
### Update report

Performed the research to detect the changes required to complete this functionality.
Work is underway on changes and initial testing.

**Comment by fcaffieri** [comment]
After talking with @davidjiglesias, @rauldpm , @pro-akim and @mhamra  it was noted that it is necessary to modify the way in which the Wazuh manager is being installed to incorporate the central components with AIO. That said, this issue misses the point and is closed in pursuit of this issue https://github.com/wazuh/wazuh-qa/issues/5219
