### ISSUE TITLE
DTT1. Change the call to os.getlogin function by getpass.getuser in testing module

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5203]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
|  4.9.0 | #5193   |   |

## Description
While executing a workflow file, the `os.getlogin()` function generated an exception. See this [comment](https://github.com/wazuh/wazuh-qa/issues/5193#issuecomment-2049888388).

The `os.getlogin` function returns the user's name logged in on the process's controlling terminal. Typically, processes in the user's session (tty, X session) have a controlling terminal. Processes spawned by the workflow do not have a controlling terminal. The recommended way to obtain the current user is using the `getpass.getuser` function instead. It is a more reliable method.

**Comment by mhamra** [comment]
The Python reference for` os.getlogin` recommends using the `getpass.getuser` function (see [os.getlogin reference](https://docs.python.org/3/library/os.html)).

I recommend this change because some users may get the exception, blocking the test execution.

**Comment by rauldpm** [comment]
There is only this reference to `getlogin`, so let's fix it, as you have the fix, create a PR to the https://github.com/wazuh/wazuh-qa/pull/5190 branch and add a test case

```
╰─➤  grep -R "os.getlogin"
modules/testing/testing.py:        extra_vars['current_user'] = os.getlogin()
```

**Comment by rauldpm** [comment]
Approved by @pro-akim and @rauldpm
