### ISSUE TITLE
DTT1. [ERROR] [Testing]: Authentication error. Check SSH credentials in ubuntu-22.04

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5205]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
|4.9.0  | #5193   |   |

## Description
Running the workflow file mentioned in #5193, the Ubuntu 22.04 agent hung in the OS startup. The testing module did not abort the task. After pressing Ctrl-c, the workflow aborted the task and continued the execution. The details of the executions are in this [comment](https://github.com/wazuh/wazuh-qa/issues/5193#issuecomment-2050202896).

The workflow should abort the task if an Authentication error arises.

**Comment by rauldpm** [comment]
This issue should be solved with https://github.com/wazuh/wazuh-qa/issues/5198, as it will guarantee the VM access through SSH
