### ISSUE TITLE
Wrong packages in some VD upgrade cases

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5208]
## Description

During the testing performed at https://github.com/wazuh/wazuh/issues/22828#issuecomment-2051401345, it was found that for Node.js versions 19.5.0 and 19.6.0, the `.exe` package is being installed on Windows instead of the `-x64.msi` package, as in the other cases. 

https://github.com/wazuh/wazuh-qa/blob/c497eba776f52df94ffb3c9b5c4a1d348f4d5116/deps/wazuh_testing/wazuh_testing/end_to_end/vulnerability_detector_packages/vuln_packages.json#L463-L465

https://github.com/wazuh/wazuh-qa/blob/c497eba776f52df94ffb3c9b5c4a1d348f4d5116/deps/wazuh_testing/wazuh_testing/end_to_end/vulnerability_detector_packages/vuln_packages.json#L478-L480

In addition, the description of `upgrade_package_nonvulnerable_to_nonvulnerable` is not as expected, it should indicate version 19.6.0.

https://github.com/wazuh/wazuh-qa/blob/c497eba776f52df94ffb3c9b5c4a1d348f4d5116/tests/end_to_end/test_vulnerability_detector/cases/test_vulnerability.yaml#L291-L293

On the other hand in macOS in the file test_vulnerability.yaml, in the case with id "id: upgrade_package_maintain_vulnerability" the version of the http-proxy package in the code of the "from" block must be changed from 0.5.10 to 0.5.9 because the version "0.5.10" is repeated both in the code of the "to" block and in the code of the "from" block:
```
from:
 macos:
  amd64: http-proxy-0.5.10
  arm64v8: http-proxy-0.5.10
to:
 macos:
  amd64: http-proxy-0.5.10
  arm64v8: http-proxy-0.5.10
```

**Comment by MARCOSD4** [comment]
| Development Branch |
| --- |
| `bug/5208-change-packages-vd-test-cases` |

**Comment by davidjiglesias** [comment]
LGTM
