### ISSUE TITLE
DTT1 - Iteration 3 - Test module - Adding granularity to test validations

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5215]
Adding granularity to test validations

Change in Agent tests

1. Test install
2. Test registration
3. Test stop
4. Test restart
5. Test uninstall

to 

1. Test install 
2. Test registration (Enroll using ossec.conf targeting a specific manager)
3. Test connection (Establish a connection with a single manager via TCP)
4. Test basic_info (OS, arch, version)
5. Test stop 
6. Test restart
7. Test uninstall Confirm no remnants post-uninstallation (e.g., processes, services, ports)

**Comment by pro-akim** [comment]
## Update

Testing all the new tests.

**Comment by rauldpm** [comment]
ETA moved 1 day due to pending review

**Comment by pro-akim** [comment]
## Update
New changes in `4495-dtt1-release` were merged

**Comment by fcaffieri** [comment]
Needs to review and generate a new PR due to conflicts unresolved  with changes in 4495-dtt1-release

**Comment by pro-akim** [comment]
## Update

Conflicts fixed.
Moved to pending review

**Comment by fcaffieri** [comment]
LGTM

**Comment by rauldpm** [comment]
LGTM
