### ISSUE TITLE
DTT1 - Test Module - macOS and Windows tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5218]
## Description

The objective of the issue is to make the necessary adaptations to perform agent tests on Windows and macOS systems.

## Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/5229
- [x] https://github.com/wazuh/wazuh-qa/issues/5230

**Comment by rauldpm** [comment]
After talking with the team we will set this issue as an Epic and we will split this issue into two issues, one for macOS and one for Windows

**Comment by rauldpm** [comment]
All tasks have been completed and merged
