### ISSUE TITLE
DTT1 - Test Module - Improve test module execution time

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5221]
## Desciption

The objective of this issue is to improve test execution times as much as possible.
The focus of this issue would only be to investigate and analyze the possibility of improving the times within the test, since they will improve significantly with this issue https://github.com/wazuh/wazuh-qa/issues/5220

## Tasks

- [ ] Investigate and analyze the possibility of improving test execution times

**Comment by rauldpm** [comment]
This issue will focus on code research, this issue is not a stopper (unless we find something that we have to address)
