### ISSUE TITLE
Vulnerability Detector Discards Events

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh-qa#5222]
| Wazuh Version | Component | Install Type |
| --- | --- | --- |
| 4.8.0-beta5 | Vulnerability Detector | Agent |

Related to https://github.com/wazuh/wazuh/issues/20781

### Description

During the issue [Benchmark vulnerability detector performance after the refactor](https://github.com/wazuh/wazuh/issues/20781#issuecomment-2039928050) I have done a series of tests (both locally and on machines built with a pipeline ) of Vulnerability Detector. I have used `simulate-agents` for the tests. Each event that `simulate-agents` has simulated has generated an entry in the logs with the following error

```console
wazuh-modulesd:vulnerability-scanner: WARNING: Discarded event: Empty response from Wazuh-DB
```

The simulated agents have been both debian10 and ubuntu18.04. The [full list of OS](https://github.com/wazuh/wazuh-qa/blob/a2632b2aa532af900d534628cbdeb86a1dd1dd80/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py#L43) that can be simulated is

- debian7, debian8, debian9, debian10
- ubuntu12.04, ubuntu14.04, ubuntu16.04, ubuntu18.04
- mojave
- solaris11

A similar error message was reported and fixed here [Windows Server 2019 Scan Error](https://github.com/wazuh/wazuh/issues/22559). It is necessary to investigate what is the cause of this error and its possible solution.

**Comment by rafabailon** [comment]
## Update

I have added a change so that when selecting only `packages` (or leaving the default option), `osinfo` is added (and the batch_size is 1). In this way, the OS information is always sent and errors are avoided. In the tests I have been able to see that vulnerability logs are generated.

**Comment by rafabailon** [comment]
## Update

I have created a PR with all the changes to add a class to the agent simulator to generate vulnerability events. The tests have been done locally. The results are in the PR.

**Comment by rafabailon** [comment]
### Update

I have had little time to devote to this issue as I received 3 communities at once.

### Update 2

I have refactored the code according to the comments in the PR. I have removed all the code repetition and made some changes to remove all the unnecessary code.

I've tested the simulator with different OSs for the agent and the manager (debian and ubuntu). Everything seems to work correctly.

Details can be found in the PR. For the tests I have used the simulator and checked the logs manually to check that the necessary syscollector messages are sent and the vulnerability alerts appear.

Translated with DeepL.com (free version)

**Comment by Rebits** [comment]
<details>

<summary> Single Vulnerable package testing :green_circle:  </summary>


We are going to test a single vulnerable package per second
```
simulate-agents  -a 192.168.56.9 -n 1  -m vulnerability -s 1 -t 30 --vulnerability-packages-list-file /home/homelab/Wazuh/file.json
```

Where file is 
```
[
    {
        "vendor": "bsdi",
        "product": "bsd_os",
        "version": "3.1"
    }
```

- Expected initial os info is correctly sent:
``` 
{"timestamp":"2024-04-29T16:05:37.651+0000","agent":{"id":"004","name":"1-digJ5mC3GNlEh0A9-debian8"},"manager":{"name":"ubuntu22-2"},"id":"1714406737.2430957","full_log":"{\"type\": \"dbsync_osinfo\", \"data\": {\"checksum\":\"1634140017886803554\",\"architecture\":\"x86_64\",\"hostname\":\"1-digJ5mC3GNlEh0A9-debian8\",\"os_codename\":\"focal\",\"os_major\":\"20\",\"os_minor\":\"04\",\"os_name\":\"Ubuntu\",\"os_platform\":\"ubuntu\",\"os_patch\":\"6\",\"os_release\":\"sp1\",\"os_version\":\"20.04.6LTS(FocalFossa)\",\"os_build\":\"4.18.0-305.12.1.el8_4.x86_64\",\"release\":\"6.2.6-76060206-generic\",\"scan_time\":\"2023/12/2011:24:58\",\"sysname\":\"Linux\",\"version\":\"#202303130630~1689015125~22.04~ab2190eSMPPREEMPT_DYNAMIC\"}, \"operation\": \"INSERTED\"}","decoder":{"name":"syscollector"},"data":{"type":"dbsync_osinfo","os":{"hostname":"1-digJ5mC3GNlEh0A9-debian8","architecture":"x86_64","name":"Ubuntu","version":"20.04.6LTS(FocalFossa)","codename":"focal","major":"20","minor":"04","patch":"6","build":"4.18.0-305.12.1.el8_4.x86_64","platform":"ubuntu","sysname":"Linux","release":"6.2.6-76060206-generic","os_release":"sp1"},"operation_type":"INSERTED"},"location":"syscollector"}
```

The second message is the expected message of package installation
```
{"timestamp":"2024-04-29T16:05:38.649+0000","agent":{"id":"004","name":"1-digJ5mC3GNlEh0A9-debian8"},"manager":{"name":"ubuntu22-2"},"id":"1714406738.2430957","full_log":"{\"type\": \"dbsync_packages\", \"data\": {\"architecture\":\"\",\"checksum\":\"4Y9QX5J9FO\",\"description\":\"\",\"format\":\"\",\"groups\":\"editors\",\"install_time\":\"2024/04/29 00:00:00\",\"item_id\":\"BVWSRG0YC6\",\"location\":\"\",\"multiarch\":\"null\",\"name\":\"bsd_os\",\"priority\":\"optional\",\"scan_time\":\"2023/12/1915:32:25\",\"size\":\"2\",\"source\":\"\",\"vendor\":\"bsdi\",\"version\":\"3.1\"}, \"operation\": \"INSERTED\"}","decoder":{"name":"syscollector"},"data":{"type":"dbsync_packages","program":{"name":"bsd_os","priority":"optional","section":"editors","size":"2","vendor":"bsdi","install_time":"2024/04/29 00:00:00","version":"3.1","multiarch":"null"},"operation_type":"INSERTED"},"location":"syscollector"}
```

</details>

**Comment by rafabailon** [comment]
## Update

I have made the changes suggested in the PR. I have also reviewed the comments to fix some errors that I have detected. Finally, I repeated the tests to make sure everything still works.
