### ISSUE TITLE
DTT1 - Test Module - Implement macOS tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5229]
## Description

The objective of the issue is to make the necessary adaptations to perform agent tests on macOS systems.

## Tasks

- [x] Adapt the tests for macOS
- [x] Perform integration tests of macOS

**Comment by pro-akim** [comment]
VAGRANT
    - macos-sonoma-14.0-arm64
    - macos-ventura-13.4.1-arm64
AWS
    - macos-sonoma-14.3-arm64
    - macos-ventura-13.6.4-amd64
    - macos-sonoma-14.3-amd64
    - macos-ventura-13.6.4-arm64

**Comment by pro-akim** [comment]
## Update
Comments done in review

**Comment by rauldpm** [comment]
LGTM
