### ISSUE TITLE
FIM System tests. 0206: Tag option

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#524]
Hello team,

This issue is related to #493. It will contain the advances related to the creation of the scenario 206.

### Objectives

Implement the scenarion 206.

###  Tasks

- [x] Create ossec.conf
- [x] Create `launch_scenario.yml`
- - [x] Create/Delete/modify the necessary files
- - [x] Check alerts in `alerts.json`.
- - [x] Check alerts in `Elasticsearch`.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

Working branch: 
https://github.com/wazuh/wazuh-qa/tree/feature-524-scenario-206

I have modified verification scripts to check for tags in the alerts and added new extra_args variable for the scripts in the playbook.

Regards,
Daniel Folch

**Comment by jm404** [comment]
Done in #552
