### ISSUE TITLE
Wazuh-QA Dependant-bot suggests to merge Cryptography bump PR from 3.3.2 to 41.0.6

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5273]
Alert in Wazuh-QA Dependant-bot was found:

![image](https://github.com/wazuh/wazuh-jenkins/assets/125690423/75f687cd-1268-41c0-8c93-7f32802eb249)

It seems that by merging the mentioned PR, cryptography vulnerabilities will disappear
 
![image](https://github.com/wazuh/wazuh-jenkins/assets/125690423/543dc498-49a0-460f-9912-5c63727eb395)

- [ ] Analyze the convenience of its implementation
- [ ] Evaluate risks
- [ ] merge if it is correct

**Comment by rauldpm** [comment]
The bot created the original PR on `Nov 28, 2023`, this issue has not been worked on in a long time, we need to work on it but we have other issues with higher priorities, I propose adding the issue to the `qa_known` label and address it in the future
