### ISSUE TITLE
Fix cluster reliability tests

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-qa#5281]
## Description

During the [Workload benchmarks release testing](https://github.com/wazuh/wazuh/issues/23065) we found that some cluster reliability tests are failing and some other are not executed.

The test `test_cluster_master_logs_order.py::test_check_logs_order_master` failed validating the order logs

```console
E                           Failed: [CLUSTER-Workload_benchmarks_metrics_B503_manager_23]
E                            - Log type: Agent-groups send full
E                            - Expected logs: ['Obtained.*chunks of data in.*']
E                            - Found log: Starting.
```

And the following tests weren't even executed by the pipeline:

- `test_check_logs_order_workers`
- `test_cluster_sync`
- `test_cluster_task_order`

We should fix the test validating order logs and figure out why the other tests did not run.

Artifacts: [test_cluster_reliability.zip](https://github.com/wazuh/wazuh-qa/files/15065508/test_cluster_reliability.zip)

**Comment by nico-stefani** [comment]
Reopened due to the failure encountered in wazuh/wazuh#24894
