### ISSUE TITLE
DTT1 - Allocator module. The allocation fails if the sshpass utility is not installed

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5295]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0  |   | [4495-dtt1-release](https://github.com/wazuh/wazuh-qa/tree/4495-dtt1-release)   |

## Description
The log of this [comment](https://github.com/wazuh/wazuh-qa/pull/5264#issuecomment-2077797733) shows that the allocator failed to run. The code that generates the exception is this:

https://github.com/wazuh/wazuh-qa/blob/333a6b7ac09b93dbd9e59b2eca5c5f2a7e69ba32/deployability/modules/allocation/vagrant/provider.py#L295-L310

I've checked, and the host machine didn't have the `sshpass` utility installed. After installing it, the workflow file worked fine.

The current implementation does not check if the `sshpass` utility is installed or inform the user of the problem. An exception is raised, but with a log message that does not allow the user to fix the problem.

## Requested feature:
The `VagrantProvider.__remote_host` method should process the `subprocess.Popen` output to log if `sshpass` is not installed or `sshpass` cannot connect, or a verification of the current environment needs to be done before launching the command.

## Proposed checks

- [ ] The code handles the exception when the sshpass utility is not installed.
- [ ] The code handles the exception when the sshpass utility cannot connect.
- [ ] Review/update the documentation to add the dependency of the sshpass utility.

**Comment by c-bordon** [comment]
We believe that this problem should be attacked in DTT2, since the ideal is not to perform a dependency fix but to change all these `ssh` calls that are made and replace them with `Python` libraries so that in this way, the script It also works on systems like Windows and macOS

**Comment by rauldpm** [comment]
We can improve the remote calls with Python in DTT2 as an enhancement, but we need to fix this behavior as we need to report the real error in DTT1
