### ISSUE TITLE
Environment deployment for vulnerability state testing

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5301]
## Description

This issue is intended to track the process of deploying the necessary environments for testing Vulnerability states.

### Environment Requirements

| Component              | Quantity | Operating System | CPU (cores) | RAM (GB) | Disk (GB) |
|------------------------|----------|------------------|-------------|----------|-----------|
| **Master**             | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Workers**            | 2        | Ubuntu 22        | 4           | 8        | 50        |
| **Agent 1**            | 1        | Ubuntu 22        | 2           | 4        | 30        |
| **Agent 2**            | 1        | Windows 11       | 2           | 4        | 30        |
| **Load Balancer**      | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Indexers**           | 2        | Ubuntu 22        | 2           | 4        | 30        |

> [!NOTE] 
The load balancer is located on the master node.

- Two identical environments will be deployed.
- Each environment will use packages from one development.

| Architecture           | Framework development package URL                                                                                      | Core development package URL                                                                                        |
|------------------------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| DEB                    | [4.8.0-python.vd.spike.deb.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-python.vd.spike.deb.1_amd64.deb) | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-0.commitd31b277_amd64.deb) |
| RPM                    | [4.8.0-python.vd.spike.rpm.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-python.vd.spike.rpm.1.x86_64.rpm) | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-0.commitd31b277.x86_64.rpm) |

**Comment by MARCOSD4** [comment]
## Update

The first environment including the Framwork development has been deployed and testing can now begin. The Load Balancer remains to be configured

**Comment by MARCOSD4** [comment]
## Update

Finally, after talking with @davidjiglesias  and @wazuh/devel-qa-div2  it has been decided not to configure the load balancer in order to move forward with testing. Therefore, all environments are now correctly deployed.

**Comment by davidjiglesias** [comment]
LGTM
