### ISSUE TITLE
Functionality tests for individual sub-indices and global index approach

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5302]
## Description

This issue is intended to cover the testing process followed and obtained for https://github.com/wazuh/wazuh/issues/23058 development.

### Test environment

| Component              | Quantity | Operating System | CPU (cores) | RAM (GB) | Disk (GB) |
|------------------------|----------|------------------|-------------|----------|-----------|
| **Master**             | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Workers**            | 2        | Ubuntu 22        | 4           | 8        | 50        |
| **Agent 1**            | 1        | Ubuntu 22        | 2           | 4        | 30        |
| **Agent 2**            | 1        | Windows 11       | 2           | 4        | 30        |
| **Load Balancer**      | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Indexers**           | 2        | Ubuntu 22        | 2           | 4        | 30        |

> [!NOTE] 
The load balancer is located on the master node.

| Architecture           | Framework development package URL                                                                                     URL                                                                                        |
|------------------------|----------------------------------------------------------------------------------------------------------------|
| DEB                    | [4.8.0-python.vd.spike.deb.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-python.vd.spike.deb.1_amd64.deb) | 
| RPM                    | [4.8.0-python.vd.spike.rpm.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-python.vd.spike.rpm.1.x86_64.rpm) | 

### Test cases

| ID | Description | Status |
|:--:|--|:--:|
| T1 | Change of worker due to agent restart |  | 
| T2 | Change of worker due to connection loss |  |
| T3 | Change of worker due to worker restart |  |
| T4 | Loss and recovery of connection to a worker |  |
| T5 | Change of worker due to kill of worker |  |
| T6 | Restart of worker while vulnerability scanning is in progress  |  |
| T7 | Restart of indexer while states are being indexed |  |
| T8 | Loss of connection of indexer while states are being indexed |  |
| T9 | Restart of indexer while states are being indexed and agent changes worker |  |
| T10| Loss of connection of indexer while states are being indexed and agent changes worker |  |
| T11| Restart of both indexers while states are being indexed |  |
| T12| Loss of connection of both indexers while states are being indexed |  |
| T13| Installation of a vulnerable package when the agent is stopped |  |
| T14| Removal of a vulnerable package when the agent is stopped |  |
| T15| Removal of a vulnerable package and change worker with long syscollector interval |  |
| T16| Corrupt hash |  |
| T17| Deleted hash |  |
| T18| Agent with syscollector enabled later |  |
| T19| All agents conected to master node |  |
| T20| Exchange of agents and workers |  |
| T21| Agent re-registered with same name but different ID |  |
| T22| Agent re-registered with same ID but different name |  |
| T23| Restart of the master node |  |
| T24| Loss of connection with the master node |  |
| T25| While the agent is switching workers, the target worker is restarted |  |

---

**Status legend:**

🟢 - Approved
🟡 - Approved with warnings or expected errors
🔴 - Rejected

**Comment by santipadilla** [comment]
We have used the following environment:

## Master

<details><summary>System information</summary></br>

```console
cat /etc/*release

```

</details>

<details><summary>Manager version</summary></br>

```console
/var/ossec/bin/wazuh-control info

```
</details>

<details><summary>Manager status</summary></br>

```console
systemctl status wazuh-manager -l

```
</details>

## Workers

<details><summary>System information</summary></br>

```console
cat /etc/*release

```

</details>

<details><summary>Manager version</summary></br>

```console
/var/ossec/bin/wazuh-control info

```
</details>

<details><summary>Manager status</summary></br>

```console
systemctl status wazuh-manager -l

```
</details>

## Indexers

<details><summary>System information</summary></br>

```console
cat /etc/*release

```

</details>

<details><summary>Manager version</summary></br>

```console
/var/ossec/bin/wazuh-control info

```
</details>

<details><summary>Manager status</summary></br>

```console
systemctl status wazuh-manager -l

```
</details>

## Ubuntu Agent


<details><summary>System information</summary></br>

```console

```

</details>

<details><summary>Agent version</summary></br>

```console

```
</details>

<details><summary>Agent status</summary></br>

```console

```
</details>

## Windows Agent


<details><summary>System information</summary></br>

```console

```

</details>

<details><summary>Agent version</summary></br>

```console

```
</details>

<details><summary>Agent status</summary></br>

```console

```
</details>

**Comment by santipadilla** [comment]
## Case 1: Change of worker due to agent restart

**Given** a configured master
**And** two workers configured
**And** an agent connects to the master node
**And**  the agent with state `Active`
**When** the agent is restarted and changes worker
**Then** No doubling of the vulnerability index

**Comment by santipadilla** [comment]
## Case 1: Change of worker due to agent restart

**Given** a configured master
**And** two workers configured
**And** an agent connects to the master node
**And**  the agent with state `Active`
**When** the agent is restarted and changes worker
**Then** No doubling of the vulnerability index

**Comment by santipadilla** [comment]
## Case 2: Change of worker due to connection loss

**Given** a configured master
**And** two workers configured
**And** an agent connects to the worker node
**And**  the agent with state `Active`
**When** connection lost and worker changed
**Then** No doubling of the vulnerability index

**Comment by santipadilla** [comment]
## Case 3: Change of worker due to worker restart

**Given** a configured master
**And** two workers configured
**And** an agent connects to the worker node
**And**  the agent with state `Active`
**When** Worker restart and worker changed
**Then** No doubling of the vulnerability index

**Comment by juliamagan** [comment]
After a meeting with @davidjiglesias and @wazuh/devel-qa-div2, it has been decided that we will not continue with this issue since the development that was intended to be tested here will not be used in the end.
