### ISSUE TITLE
Replicate error `sqlite3_prepare_v2() : no such table` in Jenkins pipeline.

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-qa#5309]
|Wazuh version| Related issue | Component|Install type|
|---|---|---|---|
| 4.8.0-rc2 | [22847](https://github.com/wazuh/wazuh/issues/22847) | Database | Manager |

## Description

Referring to the issue:
- [Broken database during Vulnerability Detector tests](https://github.com/wazuh/wazuh/issues/22847)

Both the core team and the QA team have failed to reproduce the bug locally, we need the following from the QA team:

- Run the Jenkins pipeline and wait for it to fail. If it is intermittent, run it several times consecutively.
- Keep the environments without deleting.
- Provide us access to the environment.

## DoD
  - [x] The goal of this issue is the vm with the error message and access for analysis.

**Comment by juliamagan** [comment]
Launched https://ci.wazuh.info/job/Test_e2e_system/267/console. When the test is finished, the AMI of the instances will have to be created and access will have to be granted.

**Comment by juliamagan** [comment]
Provisioned environment and credentials sent to @cborla privately.

**Comment by cborla** [comment]
Hi @juliamagan, we have not yet closed the issue because the environment does not currently have the problem, we found no logs or corrupted databases that refer to the error.
 - https://github.com/wazuh/wazuh/issues/22847#issuecomment-2087032988

**Comment by vikman90** [comment]
Please let's run the instances again with these branches, as I'm suspecting of a process termination timeout issue:

- [22847-lower-timeout](https://github.com/wazuh/wazuh/compare/4.8.0...change/22847-lower-timeout)
- [22847-greater-timeout](https://github.com/wazuh/wazuh/compare/4.8.0...change/22847-greater-timeout)

**Comment by cborla** [comment]
Since the issue [Broken database during Vulnerability Detector tests](https://github.com/wazuh/wazuh/issues/22847#top)
 for which access to these vm's was requested. I consider that the present issue can be closed.

**Comment by juliamagan** [comment]
Provisioned environment and credentials sent to @cborla and @vikman90

**Comment by juliamagan** [comment]
New environment provisioned and credentials sent to @LucioDonda

**Comment by vikman90** [comment]
Thank you @juliamagan, we can close this issue as we've managed to reproduce https://github.com/wazuh/wazuh/issues/22847 locally.

Best!
