### ISSUE TITLE
Performance for Vulnerability Detection module in clustered environments 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5313]
# Description

This issue is dedicated to conducting a thorough performance analysis of two proposed development approaches:

  - @wazuh/devel-framework: https://github.com/wazuh/wazuh/issues/23058
  - @wazuh/devel-core2 development: https://github.com/wazuh/wazuh/issues/22867

The objective is to perform performance tests and compare the results of both approaches. This comparative analysis will provide a comprehensive understanding of the potential impact on the product.

## Test environment

| Component              | Quantity | Operating System | CPU (cores) | RAM (GB) | Disk (GB) |
|------------------------|----------|------------------|-------------|----------|-----------|
| **Master**             | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Workers**            | 2        | Ubuntu 22        | 4           | 8        | 50        |
| **Agent 1**            | 1        | Ubuntu 22        | 2           | 4        | 30        |
| **Agent 2**            | 1        | Windows 11       | 2           | 4        | 30        |
| **Load Balancer**      | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Indexers**           | 2        | Ubuntu 22        | 2           | 4        | 30        |

> [!NOTE] 
The load balancer is located on the master node.

### 23058 Development Packages
| Architecture           | Framework development package URL                                                                                     URL                                                                                        |
|------------------------|----------------------------------------------------------------------------------------------------------------|
| DEB                    | [4.8.0-python.vd.spike.deb.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-python.vd.spike.deb.1_amd64.deb) | 
| RPM                    | [4.8.0-python.vd.spike.rpm.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-python.vd.spike.rpm.1.x86_64.rpm) | 

### 22867 Development Packages
| Architecture           | Core development package URL                                                                                        |
|---------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| DEB                    | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-0.commitd31b277_amd64.deb) |
| RPM                    | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-0.commitd31b277.x86_64.rpm) |
# Test Cases

# Testing 

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Number of Agents | EPS | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Minimum Activity | Simulate a small, stable environment with low activity | 10 | 10 | 600 | 100 | 3h |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 50 | 10 | 300 | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 200 | 50 | 60 | 100 | 3h |

### Methodology

Customizing the set of vulnerable packages is not feasible in automatic testing. Therefore, manual testing will utilize a larger set of 10,000 vulnerabilities to identify any potential instability in environments with a high vulnerability count. The following Wazuh-QA tools will be employed for manual performance analysis:
- Monitor class for resource measurement of Wazuh central components
- Statistics class for Wazuh data analysis
- Simulate agents script for Wazuh agent simulation

### Test Cases

| Case | Description | Number of Agents | EPS | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- |
| High Vulnerability Environment | Simulate an intermediate-sized environment with high vulnerability | 10 | 10 | 60 | 10,000 | 3h |

### New Issues

- https://github.com/wazuh/wazuh-jenkins/issues/6474
- https://github.com/wazuh/wazuh-jenkins/issues/6473
- https://github.com/wazuh/wazuh-jenkins/issues/6203
- https://github.com/wazuh/wazuh-jenkins/issues/6475
- https://github.com/wazuh/wazuh/issues/23202
- https://github.com/wazuh/wazuh/issues/22847

### Known issues
- https://github.com/wazuh/wazuh-jenkins/issues/6203

> [!NOTE]
> Manual performance testing, _Minimum Activity_ and _High Activity_ has not been performed. More information in https://github.com/wazuh/wazuh-qa/issues/5313#issuecomment-2100349272

**Comment by Rebits** [comment]
# Automatic 

- `Minimum Activity`:
- `Medium Activity`:
- `High Activity`:

**Comment by Rebits** [comment]
Performance test fail due to no space left error
```
22:03:52  
22:03:52  TASK [Copy ossec.log file to data files] ***************************************
22:03:52  fatal: [CLUSTER-Workload_benchmarks_metrics_B510_manager_2]: UNREACHABLE! => {
22:03:52      "changed": false,
22:03:52      "unreachable": true
22:03:52  }
22:03:52  
22:03:52  MSG:
22:03:52  
22:03:52  Warning: Permanently added '172.31.3.110' (ECDSA) to the list of known hosts.

22:03:52  mkdir: cannot create directory ‘/tmp/ansible-tmp-1715115832.7137516-30912-167679972105845’: No space left on device
22:03:52  
22:03:53  fatal: [CLUSTER-Workload_benchmarks_metrics_B510_manager_1]: UNREACHABLE! => {
22:03:53      "changed": false,
22:03:53      "unreachable": true
22:03:53  }
22:03:53  
22:03:53  MSG:
22:03:53  
22:03:53  Warning: Permanently added '172.31.4.31' (ECDSA) to the list of known hosts.

22:03:53  mkdir: cannot create directory ‘/tmp/ansible-tmp-1715115832.724964-30911-242038256013694’: No space left on device
```

**Comment by Rebits** [comment]
# Medium Activity :red_circle: 

## Logs :red_circle: 

Worker logs indicate same database error reported in  https://github.com/wazuh/wazuh/issues/22847

```
2024/05/07 21:24:24 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2024/05/07 21:24:24 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/05/07 21:24:48 wazuh-db: ERROR: DB(004) sqlite3_prepare_v2() : no such table: sys_osinfo
2024/05/07 21:24:48 wazuh-db: ERROR: (5214): Null statement on internal cache.
2024/05/07 21:24:48 wazuh-db: ERROR: DB(004) sqlite3_prepare_v2() : no such table: sys_programs
2024/05/07 21:24:48 wazuh-db: ERROR: (5214): Null statement on internal cache.
2024/05/07 21:24:48 wazuh-db: ERROR: DB(004) sqlite3_prepare_v2() : no such table: sys_programs
2024/05/07 21:24:48 wazuh-db: ERROR: (5214): Null statement on internal cache.
```

**Comment by Rebits** [comment]
Following a discussion with @juliamagan, we've made the decision not to replicate the unsuccessful _High Activity_ and _Low Activity_ performance tests. Instead, these tests will be re-launched in RC2

**Comment by MARCOSD4** [comment]
GJ, but the graphs of the indexer 1 metrics cannot be displayed, perhaps because of an error in writing the [comment](https://github.com/wazuh/wazuh-qa/issues/5313#issuecomment-2100081803).

**Comment by MARCOSD4** [comment]
LGTM

**Comment by juliamagan** [comment]
LGTM
