### ISSUE TITLE
macOS vulnerability alerts are not correctly collected

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5321]
### Description

It has been detected [Additional Vulnerability Detection End-to-End](https://github.com/wazuh/wazuh-qa/pull/5287) that vulnerability alerts for macOS agents are not correctly collected.
If we check the evidence we can see in the manager alerts file and in the indexed vulnerabilities that the alerts indeed appear. However the validator is ignoring it

> [!NOTE]
> Report is provided here https://github.com/wazuh/wazuh-qa/pull/5287

**Comment by rafabailon** [comment]
### LGTM

**Comment by davidjiglesias** [comment]
LGTM
