### ISSUE TITLE
DTT1-Testing Module. Fix arm installation test

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5352]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0  | #5191 | 4995-dtt1-release   |

## Description
When testing the installation of an Ubuntu 22.04 arm agent, we found that the tests were failing because the agent was not installed. After diagnosing the failure, we found that this command needs to be fixed.

https://github.com/wazuh/wazuh-qa/blob/58ecd99fe5e5b167515378fe41839b9df3989a51/deployability/modules/testing/tests/helpers/agent.py#L41-L46

There's a missing '_' character in the command found in line 46.

**Comment by rauldpm** [comment]
LGTM
