### ISSUE TITLE
DTT1 - Failure installing rpm arm platform agent

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5380]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0  |  #5359 | 4495-dtt1-release  |

## Description
While executing the workflow to test #5359, I found a bug in the agent installation for the rpm-arm platform.

There is a missing period character in the name of the output file in this line:

https://github.com/wazuh/wazuh-qa/blob/554b8ef91c0c9d37e44d20838e801a8d542d0a71/deployability/modules/testing/tests/helpers/agent.py#L38

I propose the following fix:

```
 f"curl -o wazuh-agent-{wazuh_version}-1.aarch64.rpm https://{s3_url}.wazuh.com/{release}/yum/wazuh-agent-{wazuh_version}-1.aarch64.rpm && sudo WAZUH_MANAGER='MANAGER_IP' WAZUH_AGENT_NAME='{agent_name}' rpm -ihv wazuh-agent-{wazuh_version}-1.aarch64.rpm"`
```

The current code does not validate that the command succeeded. It would be helpful to check if the failed command fails and send an error message to the log.

**Comment by fcaffieri** [comment]
LGTM
