### ISSUE TITLE
Multigroup guess system test is failing in 4.8.0 RC 2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5395]
## Description

After launching the system tests at https://github.com/wazuh/wazuh/issues/23433 it could be seen that `test_assign_groups_guess.py::test_guess_multigroups` was failing when the agent was registered in the worker and the guess was enabled. In both the case where it expected `default` and where it expected `default,group_test` as the assigned group, it was always getting `group_test`.

After a previous investigation it has been seen that the test was starting the agent and immediately assigning the custom group, so it did not give time to assign the `default` group before and the multigroup was not created. 

The `default` group is assigned with the first keep alive if it does not have any previous group assigned, so the solution would be to wait 10s before assigning the custom group.

Report: [enrollment_cluster_env.zip](https://github.com/wazuh/wazuh-qa/files/15337434/enrollment_cluster_env.zip)

**Comment by juliamagan** [comment]
Dev branch: [bug/5395-fix-multigroup-guess](https://github.com/wazuh/wazuh-qa/tree/bug/5395-fix-multigroup-guess)

Testing changes

**Comment by rafabailon** [comment]
### LGTM

**Comment by rauldpm** [comment]
LGTM
