### ISSUE TITLE
Change VD index name in QA framework

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5401]
## Description

In https://github.com/wazuh/wazuh/pull/23274, the VD index name was changed. It is necessary to replace the index name in E2E tests and performance tools with `wazuh-states-vulnerabilities-CLUSTERNAME`

**Comment by Rebits** [comment]
Currently testing among different E2E fixes. Check https://github.com/wazuh/wazuh-qa/issues/5397 for more information

**Comment by Rebits** [comment]
Created custom branch to test all E2E fixes `tmp-merge-fixes-E2E-tests`

**Build**: https://ci.wazuh.info/job/Test_e2e_system/289/

**Comment by santipadilla** [comment]
LGTM
