### ISSUE TITLE
Prevent feed update in the middle of the E2E Vulnerability tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5412]
## Description

It has been observed that updates to the Vulnerability Detection feed content can cause some consistency E2E tests to fail, as seen in [Vulnerability detection triggers alerts for the first syscollector scan](https://github.com/wazuh/wazuh/issues/23523). This issue arises even when the alerts/vulnerabilities generated by the feed updates are expected. We need to investigate possible solutions to ensure consistent test outcomes.

## Proposed Solutions

- Use an Offline Feed for E2E Tests: Utilize a static version of the feed to ensure consistency across test runs.
- Prevent Feed Updates: Increase the feed-update-interval value to prevent updates during test execution. This approach needs validation from the development team to ensure it does not affect the manager's restart process
- Account for Feed Updates in Tests: Modify the tests to include logic that accounts for possible feed updates, ensuring expected outcomes are handled correctly.

## Validation

- [x] Ensure that `test_consistency_initial_scans` passes even if a content update occurs during the tests.

Any proposed solution should be validated by: @davidjiglesias, @juliamagan

**Comment by Rebits** [comment]
Waiting https://ci.wazuh.info/job/Test_e2e_system/ results

**Comment by santipadilla** [comment]
LGTM
