### ISSUE TITLE
Increase E2E Vulnerability Detection change manager timeout

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5413]
## Description

During [Failures in Vulnerability Detection E2E Tests RC 2](https://github.com/wazuh/wazuh-qa/issues/5397#issuecomment-2124334542) it has been detected that the timeout specified for `test_change_agent_manager` it is not enough.

We need to increase this timeframe in order to guarantee that vulnerabilities for the test change manager are correctly collected.

## Tasks
- [ ] Increase `test_change_agent_manager` sleep time

## Validation
- [ ] Test change manager pass as expected

**Comment by Rebits** [comment]
Currently testing development https://github.com/wazuh/wazuh-qa/pull/5414

**Comment by rafabailon** [comment]
### LGTM
