### ISSUE TITLE
FIM system test synchronization `delete-wazuh-agent` failing in 4.7.5 RC 1

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5433]
| Target version | Related issue | Related tag |
|---|---|---|
| 4.7.5  | https://github.com/wazuh/wazuh/issues/23600  | v4.7.5-rc1  |

## Description

The test `test_fim/test_synchronization/test_synchronization.py::test_synchronization[testdir1-delete-wazuh-agent1]` fails during the system tests execution for 4.7.5 RC 1 https://github.com/wazuh/wazuh/issues/23600#issuecomment-2127921900.
The error occurs when the test tries to load the result of a db query using `json.loads()`
  > Captured db query result: 
  > ``` shellsession
  > [(u'/testdir1/testdir1.txt', u'/testdir1/testdir1.txt', u'file', 1716807481, 1, None, None, None, 0, u'rw-r--r--', u'0', u'0', u'd41d8cd98f00b204e9800998ecf8427e', u'da39a3ee5e6b4b0d3255bfef95601890afd80709', u'root', u'root', 1716807477, 127137, u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', u'', None, u'd948d821d70a99d5708a3a4b32fa1a621c3753e1')]
  > ```

After several re-launchs it was detected that it fails only then the entire suite is executed, and the test shows no error when running only `test_fim/test_synchronization/test_synchronization.py`

**Reports:**
- Execution only `test_synchronization`: [results.zip](https://github.com/wazuh/wazuh-qa/files/15455087/one_manager_agent.zip)
- Full execution: [results.zip](https://github.com/wazuh/wazuh-qa/files/15455182/results.zip)

**Comment by juliamagan** [comment]
Solved in 4.8.0: https://github.com/wazuh/wazuh-qa/issues/5043
