### ISSUE TITLE
Disable `<update_check>` setting from Wazuh manager

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5434]
# Description

We have been requested to disable the `<update_check>` setting from the Wazuh manager configuration in all of our testing, we need to review the wazuh-qa repository and modify that configuration at installation.

We are not going to disable this configuration on installations that do not modify the original config, as it will include new development.

That is, we will modify those configurations stored in the wazuh-qa repository and will add code to modify the installation configuration if other configurations are being changed, for example, using Ansible playbooks

> Alternatively, the managers where the tests are run should modify their ossec.conf before starting for the first time to include the following:
> 
> <ossec_config>
>   <global>
>     <update_check>no</update_check>
>   </global>
> </ossec_config>

## Related

- https://github.com/wazuh/internal-devel-requests/issues/1017

# Tasks

- [ ] Research: List all tests that install Wazuh manager, and specify which ones do not modify the installation settings and which ones do.
- [ ] Add necessary code to disable the `<update_check>` setting on each pipeline before starting the Wazuh manager

**Comment by davidjiglesias** [comment]
We will have to take this into account when developing tests for 5.0.0
