### ISSUE TITLE
Add E2E UX tests template for HAProxy Helper

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh-qa#5453]
## Description

In wazuh/wazuh#20887 we introduce a new feature for the cluster, the HA Proxy Helper. As well all the new section of the documentation was introduced in  wazuh/wazuh-documentation#7232 to explain the entire process of getting up and running the helper.

It is needed to develop a new E2E test to properly test the complete flow to configure and get running the new feature.

**Comment by davidjiglesias** [comment]
We are not developing automated E2E tests at this point, although your petition makes a lot of sense.

For that reason, I propose we add a new E2E UX test case to our spreadsheet, ensuring we test it in all minor and major releases (at least).

**Comment by Rebits** [comment]
Some suggestions:

**Test description**

- Include Docker HAProxy Deployment: Ensure the test description covers the steps for deploying HAProxy using Docker. This will provide a comprehensive guide for setting up the test environment.
- Testing Steps Without HAProxyHelper: Add instructions for performing some tests without enabling HAProxyHelper. This will help in validating the system's behavior independently.
- Agent/Node Balancing Context: Provide more context regarding agent/node balancing. Describe what outcomes are expected and include a specific use case to illustrate the balancing process clearly.


**About environment**
- Fix table formatting errors
- Change the proposed OS from Ubuntu 22 to Ubuntu 24, as Ubuntu 24 is supported. Varying the OS in the end-to-end (E2E) UX tests will enhance the comprehensiveness of the testing process.

**Comment by Rebits** [comment]
LGTM

**Comment by juliamagan** [comment]
LGTM, reviewer should be @wazuh/devel-pyserver. Template updated.
