### ISSUE TITLE
Add Amazon Security Hub E2E test template

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-qa#5454]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0  | https://github.com/wazuh/wazuh/issues/21209  |   |

## Description

In https://github.com/wazuh/wazuh/pull/23203, the team has added the integration with Amazon Security Hub to the AWS module. The related documentation has been added to the `4.9.0` branch at https://github.com/wazuh/wazuh-documentation/pull/7111.

We need to develop a new E2E UX test template to properly check the complete flow to configure and get running the new feature.

**Comment by davidjiglesias** [comment]
We are not developing automated E2E tests at this point, although your petition makes a lot of sense.

For that reason, I propose we add a new E2E UX test case to our spreadsheet, ensuring we test it in all minor and major releases (at least).

**Comment by rafabailon** [comment]
## Test Proposal

The purpose of the test is to test the Security Hub Integration of the AWS module. AWS Security Hub is a cloud security posture management (CSPM) service that automates security best practice checks, aggregates security alerts into a unified format, and helps the user understand the overall security posture across all of the AWS accounts.

### 1. Configuration

- Configure AWS.
   - Enabling Amazon Security Hub.
   - Integrating Security Hub with EventBridge.
   - Enabling an Amazon SQS queue.
   - Enabling an Amazon S3 bucket including Event notifications. The bucket sends notifications to the queue for every Security Hub object creation event.
- Set up the Wazuh integration for Amazon Security Hub.

### 2. Check Logs

- Check the logs in `ossec.log`.
   - Check that the logs of the new Security Hub are displayed.

**Comment by Rebits** [comment]
Good job on the proposed test cases, as they ensure the configuration stages of the new integration. However, we need to extend our testing to cover the end-to-end (E2E) viability of the integration within the product.

Here are some suggestions to achieve this:

- **Check Newly Included Alerts**:
   - Replicate a use case to trigger specific alerts, such as the `AWS Security Hub - CodeBuild Bitbucket source repository URL contains sensitive credentials` alert.
   - Verify that this alert appears in the dashboard under the expected menu (AWS).
- **Test Different Wodle Configuration Options**
   - Experiment with various Wodle configuration options for the new integration. For instance, use `discard_regex` (refer to the [Wazuh documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#discard-regex)) to filter out specific types of events.

Finally, standardize your proposed E2E UX test cases following the scheme of the E2E UX test cases in our spreadsheet



These steps will help ensure that the integration is not only correctly configured but also fully functional within a real environment.

**Comment by rafabailon** [comment]
# Test Proposal

### Information

| Name | Category |
| --- | --- |
| Amazon Security Hub | Cloud Security |

### Description

AWS Security Hub is a cloud security posture management (CSPM) service that automates security best practice checks, aggregates security alerts into a unified format, and helps the user understand the overall security posture across all of the AWS accounts.

The first step is to set up Amazon Security Hub on Wazuh:

- [Configure AWS](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#aws-configuration)
   - [Enabling Amazon Security Hub](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#enabling-security-hub)
   - [Integrating Security Hub with EventBridge](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#integrating-security-hub-with-eventbridge)
   - [Enabling an Amazon SQS queue](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#amazon-simple-queue-service)
   - [Enabling an Amazon S3 bucket including Event notifications](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#amazon-s3-and-event-notifications)
- [Set up the Wazuh integration for Amazon Security Hub](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/security-hub.rst#wazuh-configuration)

Once the environment has been configured, it is necessary to perform a series of tests to check that everything is working correctly:

- 

### Environment

| Wazuh Indexer Installation | Wazuh Indexer Type | Wazuh Indexer OS | Wazuh Server Installation | Wazuh Server Type | Wazuh Server OS | Wazuh Dashboard Installation | Wazuh Dashboard OS | Wazuh Agent Installation | Wazuh Agent OS |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [All-In-One Installation](https://documentation.wazuh.com/current/quickstart.html) | Single Node | Ubuntu 22.04 x86_64 | Same as Indexer | Single Node | Same as Indexer | Same as Indexer | Same as Indexer | [Install Wazuh Agent](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) | Debian 12 x86_64 |

### Known Issues

None

### Reviewer Assignee

None

**Comment by Rebits** [comment]
To align with the current structure of the E2E UX tests, the following description has been proposed in collaboration with @rafabailon:


```
Configure AWS Security Hub in a Wazuh Manager and a Wazuh Agent.  

- Generate Amazon Security Hub alerts. Check that generated alerts appear on the dashboard.
- Use [discard_regex option](https://documentation-dev.wazuh.com/tag/user-manual/reference/ossec-conf/wodle-s3.html#bucket-discard-regex) to effectively discard certain types of events. 
```

### Final Considerations Regarding the Original Proposal

Original proposal: https://github.com/wazuh/wazuh-qa/issues/5454#issuecomment-2165288977


1. **Module Description**
The detailed module description and links to .rst documentation files have been omitted as they are not standard in E2E tests.

2. **Alert Generation and Dashboard Verification**
The steps "Generate Amazon Security Hub alerts" and "Check that alerts appear on the dashboard" have been combined for clarity. The tester is expected to verify the alerts on the dashboard by default.


3. **Specific Testing Task**
The original task, "Test different configurations: [Bucket](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.rst#buckets), [Services](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.rst#services), and [Subscribers](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.rst#subscribers). The documentation provides an [example configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.rst#example-of-configuration)," has been replaced with the more specific task of using the discard_regex option.

4. **Log Checking**
The step "Check the logs in ossec.log. For alerts below the alert threshold, activate debug mode," has been removed as it is not part of the official documentation. If the tester cannot integrate the module with Wazuh and logs are insufficient for troubleshooting, we should consider updating the documentation or modifying the logging messages to ensure clarity.

**Comment by juliamagan** [comment]
Please add some documentation links so the tester can check them to configure the module.

**Comment by Rebits** [comment]
Done @juliamagan
