### ISSUE TITLE
Update wazuh_template_branch in filebeat provision template

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5498]
## Description

It is necessary to update `wazuh_template_branch` accordingly for each branch.

 https://github.com/wazuh/wazuh-qa/blob/218f7669f04ebe183f5d4fee678954af04beb5d9/provisioning/roles/wazuh/ansible-filebeat-oss/defaults/main.yml#L4

**Comment by santipadilla** [comment]
LGTM
