### ISSUE TITLE
Upgrade requests to >= 2.32.0

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5506]
### Description

Regarding https://github.com/wazuh/wazuh-jenkins/issues/6610, due to a vulnerability detected in requests library prior to 2.32.0, it needs to be updated to a version later than 2.32.0, while checking its compatibility with other libraries required.

In addition it would be necessary to document which tests or modules make use of this dependency

**Comment by davidjiglesias** [comment]
Not needed as part of the changes upcoming for the wazuh-qa repository
