### ISSUE TITLE
Bug in Indexer statistics class generation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5519]
## Description

During https://github.com/wazuh/wazuh-qa/pull/5518 it was introduced a bug in https://github.com/wazuh/wazuh-qa/pull/5518/commits/0312c7e3d43a15190f56f9a75f2cfba1ad84c1bf. Were used unexpected attributes in the Indexers classes attributes

**Comment by santipadilla** [comment]
LGTM

**Comment by santipadilla** [comment]
LGTM

**Comment by Rebits** [comment]
Some changes were not correctly applied leading to binary data information not correctly plotted. Detected in https://github.com/wazuh/wazuh/issues/20781#issuecomment-2196777813 by @juliamagan 

We should consider include basic testing for this module

**Comment by rafabailon** [comment]
### LGTM
