### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh-qa repository - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5549]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

### 4.8.1
- [X] Update changelog https://github.com/wazuh/wazuh-qa/pull/5553
- [X] Merge branch `4.8.1` into branch `4.9.0`. https://github.com/wazuh/wazuh-qa/pull/5552

**Comment by rauldpm** [comment]
LGTM
