### ISSUE TITLE
Migrate code from qa-system-framework to the new QA repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5560]
| Main issue |
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5558 |

## Description

Migrate the relevant content from the repository [`qa-system-framework`](https://github.com/wazuh/qa-system-framework) detected on https://github.com/wazuh/wazuh-qa/issues/5527

## Tasks
- [x] Migrate and improve the defined code

## Conclusion

Migrated the utils `wazuh-api`, `requests`, and `exceptions` to `tools/generic/` on the new repository

This PR wont contain the tool's pyproject.toml nor the README.md, in order to avoid conflicts when merging with the code from https://github.com/wazuh/wazuh-qa-automation/pull/18/files. This decision is mainly because this migration is lite weight.

**Comment by QU3B1M** [comment]
## Update report
- Most of the relevant code was already migrated on https://github.com/wazuh/wazuh-qa/issues/5561
- Migrating the `wazuh-api` utility

**Comment by damarisg** [comment]
Note: First, we need PR [#20](https://github.com/wazuh/wazuh-qa-automation/pull/20) merged into 4.10.0

**Comment by damarisg** [comment]
GJ!
