### ISSUE TITLE
Migrate code from wazuh-tools to the new QA repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5563]
| Main issue |
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5558 |

## Description

Migrate the relevant content from the repository [`wazuh-tools`](https://github.com/wazuh/wazuh-tools) detected on https://github.com/wazuh/wazuh-qa/issues/5527

## Tasks
- [x] Migrate and improve the defined code

**Comment by QU3B1M** [comment]
## Update report

- Review the footprint scripts issue https://github.com/wazuh/wazuh-qa/issues/5212
- Migrate the footprint sca scripts

**Comment by QU3B1M** [comment]
## On hold

Required modifications were detected, will update and push new changes.

**Comment by damarisg** [comment]
Note: First, we need PR [#20](https://github.com/wazuh/wazuh-qa-automation/pull/20) merged into 4.10.0
