### ISSUE TITLE
Spike - Research and define files migration without losing git history

### ISSUE THREAD

**Issue by pcapellan** [wazuh/wazuh-qa#5574]
| Main issue|
|-----|
| https://github.com/wazuh/wazuh-packages/issues/2904 |
# Description 

Currently, we are facing a migration process from different repositories to a new one, in a normal migration, all the changes history of the files are lost since they are just 'moved' from one repository to another.

This issue aims to find a way to avoid this history loss and document the process that must be followed to achieve it.

# Tasks

- [x] Research for a method/plugin/process to avoid files git history loss
- [x] Define a process to implement this solution

---

# Conclusion

After some research and testing the different solutions, I would like to highlight two different methods that we could use to accomplish the migration. _None of these methods requires any plugin or installation apart from git itself_:

## Method 1 - Git filter-branch

> [!note]
>
> The CppServer team has defined a slightly different approach to this one. [Link](https://github.com/wazuh/wazuh/issues/24037#issuecomment-2181051429)

1. Clone the source repository and navigate to it: 
    ```bash
    git clone <source_repository>
    cd <path/to/source/repository>
    ```
2. Remove origin remote: 
    ```bash
    git remote rm origin
    ```
3. Select the directories to 'migrate' and clean the repository:
    ```bash
    git filter-branch -f --prune-empty --index-filter   'git rm --cached -r -q -- . ; git reset -q $GIT_COMMIT -- <dir_to_migrate_1> <dir_to_migrate_2> <dir_to_migrate_x>' -- <source_branch>

    git gc --aggressive
    ```
    > We can list all the directories we want to migrate.
4. Switch to the target repository's directory and add the source repository as a temporary local remote
    ```bash
    cd <path/to/target/repository>
    git remote add <source_name> <path/to/source/repository>
    ```
5. Pull the files and their history from the source, and remove the temporary local remote
    ```bash
    git pull <source_name> <source_branch> --allow-unrelated-histories --no-rebase
    git remote rm <source_name>
    ```

<details><summary>Real life example</summary>

1. Clone the source repository and navigate to it: 
    ```bash
    git clone https://github.com/wazuh/wazuh-jenkins.git
    cd wazuh-jenkins
    ```
2. Remove origin remote: 
    ```bash
    git remote rm origin
    ```
3. Select the directories to 'migrate' and clean the repository
    ```bash
    git filter-branch -f --prune-empty --index-filter   'git rm --cached -r -q -- . ; git reset -q $GIT_COMMIT -- bootstrap/ new-jenkins/' -- master

    git gc --aggressive
    ```
4. Switch to the target repository's directory and add the source repository as a temporary local remote
    ```bash
    cd ~/new_repo
    git remote add jenkins /home/wazuh-jenkins
    ```
5. Pull the files and their history from the source, and remove the temporary local remote
    ```bash
    git pull jenkins master  --allow-unrelated-histories --no-rebase
    git remote rm jenkins
    ```

Check result:
  ```bash
  ~/new_repo$ ls
  bootstrap  new-jenkins
  ```
</details>

**Pros:**
- Just a few easy steps
- We can list all the directories to migrate in only one command

**Cons:**
- Slow when executing on a big source repository
- Affects files on the source repository folder

## Method 2 - Git split

1. Clone the source repository and navigate to it: 
    ```bash
    git clone <source_repository>
    cd <path/to/source/repository>
    ```
2. Remove origin remote: 
    ```bash
    git remote rm origin
    ```
3. Select the directories to 'migrate' and assign a new split branch to each one:
    ```bash
    git subtree split -P <dir_to_migrate_1> -b <split_branch_1>
    git subtree split -P <dir_to_migrate_2> -b <split_branch_2>
    git subtree split -P <dir_to_migrate_x> -b <split_branch_x>
    ```
4. Switch to the target repository's directory and add the source repository as a local remote.
    ```bash
    cd <path/to/target/repository>
    git remote add <source_name> <path/to/source/repository>
    ```
5. Fetch and merge each split branch into a specific directory
    ```bash
    git fetch <source_name> <split_branch_1>
    git fetch <source_name> <split_branch_2>
    git fetch <source_name> <split_branch_3>

    git read-tree --prefix=<target_directory_1>/ -u <source_name>/<split_branch_1>
    git commit -am "Merge split_branch_1 to target"

    git read-tree --prefix=<target_directory_2>/ -u <source_name>/<split_branch_2>
    git commit -am "Merge split_branch_2 to target"

    git read-tree --prefix=<target_directory_x>/ -u <source_name>/<split_branch_x>
    git commit -am "Merge split_branch_x to target"
    ```
6. Cleanup
    ```bash
    git remote rm <source_name>
    ```

<details><summary>Real life example</summary>

1. Clone the source repository and navigate to it: 
    ```bash
    git clone https://github.com/wazuh/qa-integration-framework.git
    cd qa-integration-framework/
    ```
2. Remove origin remote: 
    ```bash
    git remote rm origin
    ```
3. Select the directories to 'migrate' and assign a new split branch to each one:
    ```bash
    git subtree split -P src/wazuh_testing/tools/monitors/ -b integration_monitors
    git subtree split -P src/wazuh_testing/constants/ -b integration_constants
    ```
4. Switch to the target repository's directory and add the source repository as a local remote.
    ```bash
    cd ../new_repo
    git remote add integration /home/qa-integration-framework
    ```
5. Fetch and merge each split branch into a specific directory
    ```bash
    git fetch integration integration_monitors
    git fetch integration integration_constants

    git read-tree --prefix=monitors/ -u integration/integration_monitors
    git commit -am "Merge integration monitors to new repo"
    
    git read-tree --prefix=constants/ -u integration/integration_constants
    git commit -am "Merge integration constants to new repo"
    ```
6. Cleanup
    ```bash
    git remote rm <source_name>
    ```

Check results
    ```bash
    ~/new_repo$ ls
    constants  monitors
    ```

</details>

**Pros:**
- Steps are easy and easy to understand
- We can easily decide the destination folder for each directory/file migrated
- The source repository folder does not get any directories removed

**Cons:**
- Has more steps than the other option
- We have to create a split branch for each directory to migrate

**Comment by QU3B1M** [comment]
## Update report

Research on git native capabilities to import code with its history from another repo, it seems like the tool is capable to do so, the option `--allow-unrelated-histories` exists for this purpose.

Testing the solution with a dummy repository (WIP)

**Comment by jnasselle** [comment]
# Review

Nice job @QU3B1M ! just a question: could you please check doing this with two repos? I mean, given repos A and B, create a new one C with some folders of A and some folders of B. This is just in case, because this is a more accurate scenario since we'll merge several repos into one

**Comment by QU3B1M** [comment]
### On hold 🔐 
This issue will remain on hold until 4.9.0 release testing is complete.

**Comment by QU3B1M** [comment]
### Update report

Working on a more realistic solution, having some troubles when migrating with "complex" paths. WIP

**Comment by damarisg** [comment]
We will work with `Method 2 - Git split`.

LGTM!
