### ISSUE TITLE
Fix Jobflow examples

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5615]
# Description

We need to review the Jobflow examples as some YAML set Windows instances size to small instead of large, which causes the instance to fail

We need to change the examples so we have a main template outside the examples directory, for example in:

> deployability/modules/jobflow/templates

This directory should contain the following YAML

- Complete agent test
- Complete manager test
- Complete central component test

Those YAML should not reference any version or revision values (instead of 4.8.0 it must say: `major.minor.patch`

We need to check the depends_on references as:

- manager provision should depend on manager allocation
- agent deployment should depend on manager provision or allocation
- clean is successful

## Related 

- https://github.com/wazuh/wazuh/issues/24935

**Comment by pro-akim** [comment]
## Update
- [ ] Windows instances size small
- [ ] Located in: deployability/modules/jobflow/templates`
- [ ] Contains [Complete agent test, Complete manager test, Complete central component test]
- [ ] YAML do not reference any version or revision values (It says major.minor.patch)
- [ ] The depends_on references checked
- [ ] Test of the Examples

**Comment by pro-akim** [comment]
## Update
While testing, I found that Windows-Desktop-10, on several occasions, times out after being started.
[agent_01.txt](https://github.com/user-attachments/files/16616367/agent_01.txt)

Further testing will be done to upload 100% working YAMLs

**Comment by pro-akim** [comment]
## Test results:

CC :green_circle: 
[central.txt](https://github.com/user-attachments/files/16635138/central.txt)

Manager :green_circle: 
[manager.txt](https://github.com/user-attachments/files/16635139/manager.txt)

Agent :green_circle: 
[agent.txt](https://github.com/user-attachments/files/16635137/agent.txt)

**Comment by pro-akim** [comment]
## Updates

Changes done after review

**Comment by fcaffieri** [comment]
LGTM
