### ISSUE TITLE
FIM Test Fails in Manager in test_report_changes_and_diff.py

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5646]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0 Beta 2  | https://github.com/wazuh/wazuh/issues/25078  | 4.9.0 Beta 1  |

## Description

During the tests of: https://github.com/wazuh/wazuh/issues/25078, in the build: https://ci.wazuh.info/job/Test_integration/47702/consoleFull, it has been detected an error in FIM Manager:

```
E AssertionError: content_changes is not truncated
E assert '<Diff truncated because nodiff option>' in "Diff truncated due to 'nodiff' configuration detected for this file."
E + where "Diff truncated due to 'nodiff' configuration detected for this file." = <built-in method get of dict object at 0x7f934ec72e80>('content_changes')
E + where <built-in method get of dict object at 0x7f934ec72e80> = {'attributes': {'checksum': '021f882e0e27e02a143072637fd1cc63337f5553', 'gid': '0', 'group_name': 'root', 'hash_md5': ...'], 'content_changes': "Diff truncated due to 'nodiff' configuration detected for this file.", 'mode': 'realtime', ...}.get

test_fim/test_files/test_report_changes/test_report_changes_and_diff.py:186: AssertionError
  ```
  <br/>
  </details>

## More Information
This build has another two failures: https://github.com/wazuh/wazuh-qa/issues/5645 and https://github.com/wazuh/wazuh-qa/issues/5644

Report Log: 
[manager_html_report_Test_integration_B47702.zip](https://github.com/user-attachments/files/16530891/manager_html_report_Test_integration_B47702.zip)

**This error and the issues from the same build have also been seen on the agent as well as the manager**

**Comment by vikman90** [comment]
This issue is related to:

- https://github.com/wazuh/wazuh/issues/23403
