### ISSUE TITLE
FIM Test fails in Agent MacOS and Solaris

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5647]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0 Beta 2  | https://github.com/wazuh/wazuh/issues/25078  | 4.9.0 Beta 1  |

## Description

During the tests of: https://github.com/wazuh/wazuh/issues/25078, in the build: https://ci.wazuh.info/job/Test_integration_launcher/260/console, it has been detected an error in FIM Agent in MacOS and Solaris:

```
E AssertionError: content_changes is not truncated
E assert '<Diff truncated because nodiff option>' in "Diff truncated due to 'nodiff' configuration detected for this file."
E + where "Diff truncated due to 'nodiff' configuration detected for this file." = <built-in method get of dict object at 0x10b75e360>('content_changes')
E + where <built-in method get of dict object at 0x10b75e360> = {'attributes': {'checksum': '1ca442822caec3b1ac6108d0c46bef96b68c0790', 'gid': '0', 'group_name': 'wheel', 'hash_md5':...], 'content_changes': "Diff truncated due to 'nodiff' configuration detected for this file.", 'mode': 'scheduled', ...}.get

test_fim/test_files/test_env_variables/test_nodiff.py:199: AssertionError
  ```
  <br/>
  </details>

Report Log:
- From MacOS: 
[agent_macos_html_report_Test_integration_B47704.zip](https://github.com/user-attachments/files/16531227/agent_macos_html_report_Test_integration_B47704.zip)

- From Solaris:
[agent_solaris_html_report_Test_integration_B47704.zip](https://github.com/user-attachments/files/16531233/agent_solaris_html_report_Test_integration_B47704.zip)

**Comment by vikman90** [comment]
This issue is related to:

- https://github.com/wazuh/wazuh/issues/23403
