### ISSUE TITLE
Fix `PUT /active-response` invalid command in performance test

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh-qa#5648]
| Related issue |
|---|
|  https://github.com/wazuh/wazuh-qa/issues/5639 | 

## Description

When investigating the following Issue https://github.com/wazuh/wazuh-qa/issues/5639, it was found that the error was caused by using a non-existing command in the request. When using one of the default commands (described in the following [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/default-active-response-scripts.html)), the issue persists when running the pipeline, but not when running it locally.

We should investigate the `agent_simulator` used in the tests and if It is needed to make changes to how it handles the `active-response` commands.

**Comment by juliamagan** [comment]
After talking to @fdalmaup, we don't think we should fix the agent simulator at this point, with all the changes coming for 5.0.
