### ISSUE TITLE
Agent is not scanned in the first vulnerability scan in Vulnerability Detection E2E tests

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5655]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0 RC 1  | https://github.com/wazuh/wazuh/issues/25080  | 4.9.0 beta 1  |

## Description
Analyzing the build: https://ci.wazuh.info/job/Test_e2e_system/342/ of the issue: https://github.com/wazuh/wazuh/issues/25080, an error has been found in `test_first_syscollector_scan[vd_disabled_when_agents_registration]`, which appears to have failed to scan an agent on the first scan, specifically in this case, `agent2`.

We can se in the log of the report:
```
AssertionError: 
E         Test test_first_syscollector_scan[vd_disabled_when_agents_registration] failed
E         
E         Check all_agents_scanned_syscollector_first_scan succeeded
E         Check all_agents_scanned_vulnerability_first_scan failed. Evidences (['agents_not_scanned_vulnerability_first_scan']) can be found in the report.
E         Check no_errors succeeded
```
In `agents_not_scanned_vulnerability_first_scan`

```
[
    "agent2"
]
```

## Proposed checks

- [ ] Investigate why only agent2 (in this case) was not scanned in the first vulnerability scan.

## Configuration and considerations
Full report: 
[Test_e2e_system_342_test_vulnerability_detector.zip](https://github.com/user-attachments/files/16551641/Test_e2e_system_342_test_vulnerability_detector.zip)

## Expected results

All the agents have to be scanned.

## Related
https://github.com/wazuh/wazuh/issues/25080

**Comment by MARCOSD4** [comment]
The problem reported by this issue and the others that have been opened related to this issue can be solved after the feed update timeout increase that has been introduced in this [issue](https://github.com/wazuh/wazuh-qa/issues/5664). To check it, tests have been launched locally on this [environment](https://ci.wazuh.info/job/Wazuh_QA_environment/1206/) with the debug mode activated. The results will be analyzed tomorrow.

**Comment by jnasselle** [comment]
# Update

After meeting with @MARCOSD4 , we agreed to follow the next steps

- @MARCOSD4 is currently executing locally-triggered (to set deeper debug levels) VD testing v4.9.0-rc1 containing [this fix](https://github.com/wazuh/wazuh-qa/issues/5664) against v4.9.0-beta2 packages to validate if it's a test problem (low timeout value) and not a product problem. Results will be posted here/Slack when ready. This will determine the following steps.
- @jnasselle will reply pipelines from issues created from v4.9.0-beta2 testing that seem to be related to the same problem, but with 4.9.0-rc1 QA branch containing [this fix](https://github.com/wazuh/wazuh-qa/issues/5664). Issues are
  - https://github.com/wazuh/wazuh-qa/issues/5656
  - https://github.com/wazuh/wazuh-qa/issues/5657
  - https://github.com/wazuh/wazuh-qa/issues/5658
  - https://github.com/wazuh/wazuh-qa/issues/5659
  - https://github.com/wazuh/wazuh-qa/issues/5665

**Comment by jnasselle** [comment]
# Update

- @MARCOSD4 execution results are being analyzed.
- @jnasselle executes https://ci.wazuh.info/job/Test_e2e_system/348/ and still executing

**Comment by jnasselle** [comment]
# Update

Both @MARCOSD4 and @jnasselle executions  (evidence [here](https://drive.google.com/file/d/1EuGYTiLmoB8f326XlANIua9pAabT9S6A/view?usp=drive_link) and [here](https://ci.wazuh.info/job/Test_e2e_system/348/)) show errors and force us to treat every issue separately and not solved by https://github.com/wazuh/wazuh-qa/issues/5664.

A per-issue deeper analysis should be done with the @wazuh/devel-cppserver team

**Comment by juliamagan** [comment]
Specifically this issue does not seem to have occurred again, it may have been a small flaky timeout. The remaining issues that seem to come from the same reason are:
- https://github.com/wazuh/wazuh-qa/issues/5658
- https://github.com/wazuh/wazuh-qa/issues/5657
- https://github.com/wazuh/wazuh-qa/issues/5665
A first analysis can be seen [here](https://github.com/wazuh/wazuh-qa/issues/5665#issuecomment-2293291003).

**Comment by MARCOSD4** [comment]
As @juliamagan  indicates in the comment above, this issue has not occurred again in the last executions, so we can close this issue as not planned.

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by Rebits** [comment]
Summarizing, this issue was originated due to the feed was not updated in the timegap specified. We can see this in the `manager2` logs:
```
2024/08/07 17:29:03 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/08/07 17:29:03 wazuh-modulesd:syscollector: INFO: Module finished.
2024/08/07 17:29:03 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/08/07 17:29:03 wazuh-modulesd:vulnerability-scanner: INFO: Feed update interrupted: Module stopped..
```

Regarding failures reported in https://github.com/wazuh/wazuh-qa/issues/5655#issuecomment-2292544200, seems to not be realted with this issue. 

So, we can conclude that this should have be fixed with https://github.com/wazuh/wazuh-qa/issues/5664

We can close this issue.
