### ISSUE TITLE
The DB can't find the agent in the first syscollector test in Vulnerability Detection E2E tests

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5656]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0 RC 1  | https://github.com/wazuh/wazuh/issues/25080  | 4.9.0 beta 1  |

## Description
Analyzing the build: https://ci.wazuh.info/job/Test_e2e_system/342/ of the issue: https://github.com/wazuh/wazuh/issues/25080, an error has been found in `test_first_syscollector_scan[vd_enabled_when_agents_registration] `, which appears that Manager 2 (in this case) detects that the database cannot find the agent with ID  006, Even though there are 6 agents:

We can se in the log of the report:
```
AAssertionError: 
E         Test test_first_syscollector_scan[vd_enabled_when_agents_registration] failed
E         
E         Check all_agents_scanned_syscollector_first_scan succeeded
E         Check all_agents_scanned_vulnerability_first_scan succeeded
E         Check no_errors failed. Evidences (['error_level_messages']) can be found in the report.
```
In `error_level_messages`

```
{
    "manager1": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "manager2": {
        "ERROR": [
            "2024/08/07 17:29:03 wazuh-modulesd:vulnerability-scanner: ERROR: Unable to retrieve hotfixes for agent 006. Reason: DB query error: Agent not found.",
            "2024/08/07 17:29:03 wazuh-modulesd:vulnerability-scanner: ERROR: Unable to retrieve hotfixes for agent 006. Reason: DB query error: Agent not found.",
            "2024/08/07 17:29:03 wazuh-modulesd:vulnerability-scanner: ERROR: Unable to retrieve hotfixes for agent 006. Reason: DB query error: Agent not found."
        ],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent1": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent3": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent4": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent5": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent6": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    },
    "agent2": {
        "ERROR": [],
        "CRITICAL": [],
        "WARNING": []
    }
}
```

## Proposed checks

- [ ] Investigate why the database couldn't connect to the agent.
- [ ] Investigate the ID's from the agents (maybe that ID doesn't exists)

## Configuration and considerations
Full report: 
[Test_e2e_system_342_test_vulnerability_detector.zip](https://github.com/user-attachments/files/16551641/Test_e2e_system_342_test_vulnerability_detector.zip)

## Expected results

The DB has to find the agent.

## Related
https://github.com/wazuh/wazuh/issues/25080

**Comment by jnasselle** [comment]
# Update

We presume that this issue is related to the following analysis https://github.com/wazuh/wazuh-qa/issues/5655#issuecomment-2292544200

**Comment by juliamagan** [comment]
This error has not recurred in any of the executions launched in https://github.com/wazuh/wazuh-qa/issues/5655#issuecomment-2292544200. New warnings appear due to connection problems, but it seems to be due to the restart of the manager since the logs are rotated and it manages to connect without any problem later. We can close this issue as not planned.

**Comment by MARCOSD4** [comment]
LGTM
