### ISSUE TITLE
Increase feed update timeout in VD E2E tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5664]
## Description

In https://github.com/wazuh/wazuh-jenkins/issues/6848 the timeout for the Ansible tasks that initiate the E2E tests in Jenkins was increased. However, it is also necessary to extend the feed upgrade event timeout within the tests.

Currently, this timeout is set to 15 minutes, which has proven insufficient during testing, as seen in this [test result](https://ci.wazuh.info/job/Test_e2e_system/345/).

To address this, we need to update the `VD_FEED_UPDATE_COMPLETED_TIMEOUT` value to a more appropriate duration, agreed upon by the team. The current configuration can be found [here](https://github.com/wazuh/wazuh-qa/blob/243fb08a542ba35ee8009e11cf0399de037a1ba7/deps/wazuh_testing/wazuh_testing/end_to_end/waiters.py#L34).

**Comment by rauldpm** [comment]
Let's start with a 60' timeout

**Comment by joaquinsgi** [comment]
A branch named: `bug/5664-increase-feed-update-timeout-vd-e2e` has been created to introduce the changes and test them.
