### ISSUE TITLE
System Test - Enrollment Cluster test_group_sync_status has been shown to have an unstable error

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5714]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| v4.9.0-RC2  | https://github.com/wazuh/wazuh/issues/25509   | -  |

## Description
Enrollment Cluster test_group_sync_status has been shown to have an unstable error
![image](https://github.com/user-attachments/assets/a972dfc2-268d-41fd-9bee-b90311b1dbe9)
However, repeating the execution, the test has passed.
![image](https://github.com/user-attachments/assets/82ce9207-b497-459c-bf81-1c1c45d9dafb)
The error:
```
@pytest.fixture()
    def wait_end_initial_syncreq():
        timeout = current_time() + T_10
        result = execute_wdb_query(query, test_infra_hosts[0], host_manager)
    
        while 'syncreq' in result:
            time.sleep(T_1)
            if current_time() >= timeout:
>               pytest.fail('Test failure due to unstable environment, syncreq does not disappear after group management')
E               Failed: Test failure due to unstable environment, syncreq does not disappear after group management

test_cluster/test_agent_groups/test_group_sync_status.py:105: Failed
```

## Steps to reproduce
Follow the instructions in the system test README in the wazuh-qa repository.
Deploy enrollment_cluster infrastructure and run the tests with the basic_cluster_env flag

**Comment by juliamagan** [comment]
System tests are flaky, and will be deprecated soon.
