### ISSUE TITLE
Syscheck automated tests: Test file_limit option

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#646]
| Related issue              |
|----------------------|
| wazuh/wazuh#4687  |

## Description

Add tests for new option: `file_limit`. It should work on both manager and agent.

The test must check:
* Only positive values are allowed
```
(1235): Invalid value for element 'file_limit': -10.
```
* Disable `file_limit`
```
(6343): No limit set to maximum number of files to be monitored
```
* `file_limit` set to default: 100000
```
(6342): Maximum number of files to be monitored: '100000'
```
* `file_limit` set to:
    * 1
    * 10
    * 100
    * 1000
```
(6342): Maximum number of files to be monitored: '1000'
```
* Alert for 80% of capacity (_scheduled_)
```
(6039): Sending DB 80% full alert.
```
* Alert for 90% of capacity (_scheduled_)
```
(6039): Sending DB 90% full alert.
```
* Alert for full database
```
(6041): Sending DB 100% full alert.
```
* Alert for returning to <80% of capacity (_scheduled_)
```
(6038): Sending DB back to normal alert.
```

## Platforms
* Linux
* macOS
* Windows

**Comment by jesusjimsa** [comment]
The case that tests if the value in `file_limit` is negative will be in `test_invalid`.

**Comment by jesusjimsa** [comment]
The tests for positive values, 0, default and other values are ready in `test_file_limit` and `test_invalid`.

**Comment by jesusjimsa** [comment]
Added test for full database.

**Comment by jotacarma90** [comment]
Added tests to check that the 80%, 90% and back to normal (<80%) capacity alerts appear correctly

**Comment by jotacarma90** [comment]
Tests work correctly in windows:
![filelimittest](https://user-images.githubusercontent.com/60003131/79103825-9866c280-7d6d-11ea-8021-4480b508b7fc.png)

**Comment by jesusjimsa** [comment]
The tests now check that the number of files in the database is correct depending on what value is set for `file_limit`.

**Comment by jesusjimsa** [comment]
The configuration for `file_limit` has changed to this:

```xml
<file_limit>
  <enabled>yes|no</enabled>
  <entries>1|2147483647</entries>
</file_limit>
```

Therefore, the `yaml` files need to be changed to accept this new configuration.

**Comment by jesusjimsa** [comment]
Configuration files adapted to the new `file_limit` configuration format.
