### ISSUE TITLE
Integration tests for Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#659]
## Description
This issue aims to create integration tests for the Vulnerability Detector. It will allow testing the scanner for different use cases in different priority tiers (0, 1, 2):

- Configuration
- Feeds/resources availability
- Scan results for every supported OS

### Common requirements for all tests

- Vulnerability Detector is a manager-only component. Therefore, just Linux support is needed.
- Setup functions and fixtures will be needed for most of the created tests:
  - The ability to fill, read, and modify inventory DBs during the tests.
  - Accessibility to sample DBs with vulnerable packages for every OS, indexed vulnerabilities from different feeds (NVD, Canonical, RHEL, Debian), Windows hotfixes.
  - The ability to read alerts and parse JSON fields.
  - List of expected results (vulnerabilities) to be compared with the report after a scan.
  - Configuration templates.
  - The ability to change the system date.
- Every test has to:
  - Follow the rules defined at https://github.com/wazuh/wazuh-qa/tree/master/tests/integration#integration-tests and applied for the existing tests. 
  - Include the tier of the test.
  - Include a description at the start of the test.

**Comment by BraulioV** [comment]
Hi all, 
This is already implemented in our CI environment.

Regards.
