### ISSUE TITLE
Add enabled to vulnerability detector integration tests 

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#668]
# Vulnerability detector

| Version | Revision |
| --- | --- |
| 3.12.3| 31208 |

## Summary
- [ ] Test enabled `yes`
- [ ] Test enabled `no`

## Test enabled parameter

**Short description**

Vulnerability-detector must be active or not on start depending on the value of the `enabled` parameter, and generate the correct logs.

**Category**

Vulnerability-detector

**Subcategory**

General settings

**Configuration sample**

``` XML
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>100d</interval>
    <run_on_start>yes</run_on_start>
    <provider name="canonical">
      <enabled>yes</enabled>
      <os update_interval="10m">precise</os>
      <os update_interval="20m">trusty</os>
      <os update_interval="30m">xenial</os>
      <os>bionic</os>
      <update_interval>40m</update_interval>
    </provider>
  </vulnerability-detector>
```

**Expected logs**
```
2020/04/21 08:10:39 wazuh-modulesd:vulnerability-detector[71109] wm_vuln_detector.c:5238 at wm_vuldet_init(): DEBUG: Module disabled. Exiting...
```
Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Working branch: https://github.com/wazuh/wazuh-qa/tree/668-enabled-parameter-vuln-test

**Comment by BraulioV** [comment]
Related to #660
