### ISSUE TITLE
Test that the correct feed is downloaded with vulnerability detector os parameter

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#687]
# Vulnerability detector

| Tier | Type |
|-|-|
| 1 | Configuration - Feeds |

Parent issue: #661

**Category**

Vulnerability-detector

**Subcategory**

provider settings

**Description**

Vulnerability-detector must download the correct feeds for any valid target.

**Configuration sample**

``` XML
  <vulnerability-detector>
    <enabled>yes</enabled>
    <run_on_start>yes</run_on_start>
    <provider name="canonical">
      <enabled>yes</enabled>
      <os>bionic</os>
    </provider>
  </vulnerability-detector>
```
Regards,
Daniel Folch

**Comment by BraulioV** [comment]
Closed by #703
