### ISSUE TITLE
Add test to check access to files monitored by FIM while Wazuh has them open

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#697]
## Description

This test must monitor a large file (1 GB), perform a modification in the file and rename/delete it. No error should appear in the log and the rename/delete operation should be performed correctly.

### Modes
* scheduled
* realtime
* whodata

### Platforms
* Windows
* Linux
* macOS
* Solaris

**Comment by jesusjimsa** [comment]
The test is working correctly on Linux.
When executing it on Windows, while creating the big file for the third time, the test raises a `MemoryError`, this is caused by Python running in 32 bit in Windows, which has a 2 GB memory limit.
To solve this, instead of creating the file six times (one per operation and mode), the test should create the file just the first time, but a deletion operation must be performed, as part of the test, and this operation is performed at least three times.

**Comment by jesusjimsa** [comment]
The test is working correctly in Linux.

When executing the test in Windows, it uses a lot of memory. If the test gets to the limit of the available memory in the system, a `MemoryError` will be raised. To be executed without any problem, the machine must have at least 4 GB of memory.

**Comment by jesusjimsa** [comment]
The `MemoryError` has been solved by writing to the file in chunks instead of the entire file at once. After fixing this, the test can be run in systems with 2 GB.

**Comment by Deblintrake09** [comment]
**Status**
Reviewing test structure and analyzing fixes
