### ISSUE TITLE
Auto-enrollment tests.

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#702]
# Registration test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.13 | 31208 | enrollment-autoenroll |

## Auth system

- [ ] Check the auth daemon is running by default. (Since v3.8.0)
- [x] Check registration with `-m`.
- [ ] Check registration with `-m` and `-A`.
- [ ] Test force insertion to re-register an agent. (1)
- [x] Check client keys on manager and agent are equal.
- [x] Check registration with `-m wrong-IP`. **Must fail.**
- [x] Assign agent to an existing group.
- [x] Get a descriptive error when trying to assign an agent to an non-existing group.
- [ ] Set the agent IP manually by the `-I` option.
- [ ] Enable the "use source IP" feature by the `-i` option.
- [ ] Mix incompatible options like `-I <IP>` and `-i` to see the error retrieved.
- [x] Register an agent using on Windows with `agent_auth`.

(1) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/auth.html#force-insert

### Secure methods

- [x] Register an agent using a password. (2)
- [ ] Register an agent using SSL. (2)

(2) https://documentation.wazuh.com/3.x/user-manual/registering/use-registration-service.html#secure-methods

## Tool _manage_agents_

- [ ] Check same test as using Authd. (3)
- [ ] Use -F option to remove duplicated agents. (3)

(3) https://documentation.wazuh.com/3.x/user-manual/reference/tools/manage_agents.html

### Linux
- [X] Register an agent with the default configuration.
- [X] Register an agent with `<enable>yes</enable>` option.
- [X] Check that the `auto_enrollment` process is not executed if `<enable>no</enable>` option is activated.
- [X] If the agent is removed and `auto_enrollment` is enabled, the agent re-connects to the manager.
- [X] Using a hostname instead of an IP address.
- [X] Test with a wrong IP address and with a wrong hostname.
- [x] Add multiple stanzas of `auto_enrollment`, check correct configuration and lack of memory leaks 
- [x] Registration to a verified manager.
- [x] Using a certificate without a specified country.
- [x] Using a password for the registration process.
- [x] Registration with a custom agent name.
- [x] Registration into a group.
- [x] Registration into multiple groups.
- [ ] Register agent using any ip
- [ ] Reject agent registration request if the agent name is "localhost".
### Windows
- [x] Register an agent with the default configuration.
- [x] Register an agent with `<enable>yes</enable>` option.
- [x] Check that the `auto_enrollment` process is not executed if `<enable>no</enable>` option is activated.
- [x] If the agent is removed and `auto_enrollment` is enabled, the agent re-connects to the manager.
- [ ] Using a hostname instead of an IP address.
- [x] Test with a wrong IP address and with a wrong hostname.
- [ ] Add multiple stanzas of `auto_enrollment`, check correct configuration and lack of memory leaks 
- [x] Registration to a verified manager.
- [x] Using a certificate without a specified country.
- [x] Using a password for the registration process.
- [x] Registration with a custom agent name.
- [x] Registration into a group.
- [x] Registration into multiple groups.
- [ ] Register agent using any ip.
- [x] Reject agent registration request if the agent name is "localhost".

**Comment by vikman90** [comment]
Closing issue in favor of automated tests (#711).
