### ISSUE TITLE
Test: Installation

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#71]
# Installation test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.9.0 | 3916 | 3.9 |

## RPM (Linux)

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log
- [x] CentOS5
- [x] Check uninstall (services / files / users)
- [x] /opt

## DEB (Linux)

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] Check apt-get remove
- [x] Check apt-get purge
- [x] Check uninstall (services / files / users)
- [x] No errors in ossec.log

## Mac OS X

- [x] Successful installation
- [x] Check version

## Solaris (Intel)

- [x] Successful installation
- [x] Check version

## Solaris (SPARC)

- [ ] Successful installation
- [ ] Check version

## (HP-UX)

- [ ] Successful installation
- [ ] Check version

## AIX

- [ ] Successful installation
- [ ] Check version

## Sources

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log

**Comment by DaveVG1** [comment]
### RPM (Linux)
- The installation in `/opt` fails, as the python compilation is made in `/var/ossec/framework` (it should be in `/opt/ossec/framework`)
```
[root@vm-centos7 src]# systemctl status wazuh-manager -l
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2019-04-29 07:09:04 UTC; 2min 36s ago
  Process: 2641 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=1/FAILURE)

Apr 29 07:09:04 vm-centos7 systemd[1]: Starting Wazuh manager...
Apr 29 07:09:04 vm-centos7 env[2641]: /opt/ossec/bin/wazuh-clusterd: line 38: /opt/ossec/framework/python/bin/python3: No such file or directory
Apr 29 07:09:04 vm-centos7 env[2641]: wazuh-clusterd: Configuration error. Exiting
Apr 29 07:09:04 vm-centos7 systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
Apr 29 07:09:04 vm-centos7 systemd[1]: Failed to start Wazuh manager.
Apr 29 07:09:04 vm-centos7 systemd[1]: Unit wazuh-manager.service entered failed state.
Apr 29 07:09:04 vm-centos7 systemd[1]: wazuh-manager.service failed.
```
