### ISSUE TITLE
Test: Agent key polling

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#73]
# Agent key polling test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.9.0 | 3916 | 3.9 |

## Configuration

- [x] Configure and enable the agent key polling module. (1) 
- [x] Set up a MySQL Database with a table named "agent" and the fields required in the JSON output. (2) 
- [x] Copy the Python script found at (2).
- [x] Adjust the script path <exec_path> in you ossec.conf file.

## Test

- [x] Make sure Authd daemon is running.
- [x] Register an agent and connect it to the manager.
- [x] Insert the client.keys line for the agent into our database required fields.
- [x] Delete the agent from the manager (You should see the message _Message from 'xxx.yyy.zzz.www' not allowed._).
- [x] The agent should be registered again by the module (check the client.keys file).

(1) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/wodle-key-polling.html
(2) https://documentation.wazuh.com/3.x/user-manual/capabilities/key-polling.html

**Comment by DaveVG1** [comment]
### Testing
The output result of this process is:
```
2019/04/29 12:44:36 ossec-authd: INFO: Agent key generated for agent 'vm-ubuntu3' (requested locally)
2019/04/29 12:44:37 ossec-remoted: WARNING: (1213): Message from '10.0.0.123' not allowed.
2019/04/29 12:44:37 ossec-authd: INFO: Duplicated ID '001' (001). Saving backup.
2019/04/29 12:44:37 ossec-authd: INFO: Agent key generated for agent 'vm-ubuntu3' (requested locally)
2019/04/29 12:44:38 ossec-remoted: WARNING: (1213): Message from '10.0.0.123' not allowed.
2019/04/29 12:44:38 ossec-remoted: WARNING: (1213): Message from '10.0.0.123' not allowed.
2019/04/29 12:44:38 ossec-authd: INFO: Duplicated ID '001' (001). Saving backup.
2019/04/29 12:44:38 ossec-authd: INFO: Agent key generated for agent 'vm-ubuntu3' (requested locally)
2019/04/29 12:44:39 ossec-remoted: WARNING: (1213): Message from '10.0.0.123' not allowed.
2019/04/29 12:44:39 ossec-authd: INFO: Duplicated ID '001' (001). Saving backup.
2019/04/29 12:44:39 ossec-authd: INFO: Agent key generated for agent 'vm-ubuntu3' (requested locally)
2019/04/29 12:44:40 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
2019/04/29 12:44:40 ossec-remoted: INFO: (1410): Reading authentication keys file.
```
After that the agent is again `Active`:
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: vm-ubuntu4 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: vm-ubuntu3, IP: 10.0.0.123, Active
```
