### ISSUE TITLE
VD: Integration tests for analyzing scan results - Windows inventories - NVD feed

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#738]
Hello team,

The aim of this issue is to provide a sample Windows inventory which will be evaluated against the NVD vulnerability feed. The scan results should be matched with the corresponding vulnerabilities and then reported.

Parent issue: #663

Best regards.

**Comment by DFolchA** [comment]
Hello team, 
We have finished the windows package vulnerability test, currently we are working on the test for the hotfixes.

Regards, 
Daniel Folch

**Comment by BraulioV** [comment]
Closed by #790
