### ISSUE TITLE
Test: Maild

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#75]
# Maild test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.9.0 | 3916 | 3.9 |

## Send reports

- [x] Configure the mail alerts and receive an alert in your email.

## Configuration

- [x] Check the typical settings such as `email_reply_to`.
- [x] Test the option `email_log_source` since Wazuh v3.8.0.

## Filters

- [ ] Check filters: `email_maxperhour`, `level`, `group`, etc...

**Comment by DaveVG1** [comment]
### Filters

- [ ] `email_maxperhour`

- [ ]  `level`

- [ ] `rule_id` (Fails)

- [ ] `group`

- [ ] `format`

**Comment by DaveVG1** [comment]
- `rule_id` seems to be not working properly. When the rule indicated by this parameter is triggered the email alert is generated and sent but if some other rules are triggered and then the rule we indicated is triggered again a mail is sent not only with the alert we indicated but with all the others alerts.
