### ISSUE TITLE
Vulnerability detector: Additional checks on integration test

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#755]
Hello team,

@wazuh/core team have asked us to add some checks to our vulnerability detector integration tests:

- [ ] Check false positive
We need to check that no alert is generated if the version of a certain package is bigger than the one where the vulnerability is fixed. 

- [ ] Check vulnerability match based on source instead of just the binary's name and version. The reason behind this is because a big number of binary packages are compiled using a source that can differ completely in name and version(Redhat). When dealing with a package's source the internal logic for RedHat is a bit more complex than the one used for Debian and Ubuntu. 
A common RHEL source follows this structure: `example-3.12-234.el7.src.rpm`.

**Vuln-detector RHEL logic when reading a package from `sys_program`:**
-  Overwrite the `source` field with the source's name only when it differs from the binary's name. Otherwise, set it to `NULL`.
-  Additionally, set the `src_version` field with the source's version only when it's not contained within the binary's version(the source always lacks epoch). Before inserting the source's version, append a `-1` as the epoch. 

- [ ] Fix some inconsistent function names on test_scan_nvd_feeds.py and test_scan_providers_and_nvd_feeds.py (test_ubuntu_vulnerabilities_report)

- [ ] Add deprecated functions checks.

- [ ] Check for discarded kernel packages. A system might have installed more than one kernel package, but only the running one (in `sys_osinfo`) will be analyzed.

**Comment by davidjiglesias** [comment]
This issue is obsolete.
