### ISSUE TITLE
Update NVD integration tests

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#778]
Hello team,

Recently there have been changes in the NVD implementation for vulnerability detector module, so it is necessary to update the following integration tests:

- `test_scan_nvd_feeds.py`

- `test_scan_providers_and_nvd_feeds.py`

The main changes are related with NVD and Red Hat. The NVD feed for Redhat has been disabled, so it only has to check alerts with Redhat's own feed, ignoring the NVD feed.

The current status of these tests is:

```
test_vulnerability_detector/test_scan_results/test_scan_nvd_feeds.py FFFFFFFFFFF
test_vulnerability_detector/test_scan_results/test_scan_providers_and_nvd_feeds.py FFFF.......
```

Best regards.

**Comment by DFolchA** [comment]
Working branch: https://github.com/wazuh/wazuh-qa/tree/Fix-nvd-tests
