### ISSUE TITLE
Registry integration test: Improve test_ignore_registry.py

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh-qa#782]
Hello team!

The test `test_ignore_registry` found in `test_ignore_registry.py` only search the message `Ignoring '%s' '%s' due to sregex '%s'` to verify the option `registry_ignore` works. I think the test has the following failures:

- Only check if the registry is ignored when the regex is used. There must be a callback to check message `"(6204): Ignoring '%s' '%s' due to '%s'"`
- It doesn't modify the registries monitored, and the subkeys of registries monitored. It does we can't detect some bugs like reported in issue [5251](https://github.com/wazuh/wazuh/issues/5251)

Best regards,
Eva

**Comment by jesusjimsa** [comment]
### test_ignore_registry
After the development of wazuh/wazuh#5576, this test needs to be modified.
| Test                 | Action          | Expected result                                                                            |
| -------------------- | --------------- | ------------------------------------------------------------------------------------------ |
| test_ignore_registry | Ignore registry | Alerts from subkeys should appear, but alerts from ignored registry key should not appear. |
