### ISSUE TITLE
Vulnerability Detector: Test cpe_helper options

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#796]
Version | Component | Core issue | Core development branch |Notes
 -- | -- | --|--|--|
4.4  | VD  | -    | - | -

# Description

The goal of this issue is to verify that the Windows packages are correctly indexed and that the cpe_helper dictionary works correctly with the different options as indicated in our [documentation](https://documentation.wazuh.com/3.13/user-manual/capabilities/vulnerability-detection/cpe_helper.html).

### Settings 
  
```xml
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>yes</run_on_start>

    <!-- Windows OS vulnerabilities -->
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

# Use Cases

- Test that the CPE Helper works correctly with different configuration inside `cpe_helper.json`:  
   -  correct fields
   -  incorrect fields
   -  correct values
   -  incorrect values

- Test that the CPE Helper works correctly without some fields.

# Development stage

- [x] In research
- [x] In development
    - [ ] Windows
- [ ] In testing phase
    - [ ] Linux  (Only to check that nothing is broken)
    - [ ] Windows
- [ ] In Review
- [ ] Completed

**Comment by fedepacher** [comment]
# Update 2022/01/04

It has read the official documentation and it has done a manual tests to check the behavior and logs available. The result was the following

## Incorrect fields 

- `vesion` instead `version` gets log number `3` and the vulnerabilities are indexed.
- `format_vesion` instead `format_version` gets log numbers `1` and `2` the vulnerabilities are not indexed.
- `update_dte` instead `update_date` gets log numbers `1` and `2` the vulnerabilities are not indexed.
- `ditionary` instead `dictionary` gets log numbers `1` and `2` the vulnerabilities are not indexed.
- `taget` instead `target` there is no problem.
- `sorce` instead `source` gets log numbers `1` and `2` the vulnerabilities are not indexed.
- `vedor` instead `vendor` of `source` gets log number 3 and the vulnerabilities are indexed.
- `prouct` instead `product` of `source` gets log number 3 and the vulnerabilities are indexed.
- `vesion` instead `version` of `source` gets log number 3 and the vulnerabilities are indexed.
- `traslation` instead `translation` gets log numbers `1` and `2` the vulnerabilities are not indexed.
- `vedor` instead `vendor` of `translation` gets log number 3 and the vulnerabilities are indexed.
- `prouct` instead `product` of `translation` gets log numbers `3` and `4` and the vulnerabilities are indexed.
- `vesion` instead `version` of `translation` gets log number `3` and the vulnerabilities are indexed.
- `ation` instead `action` there is no problem.



### Log number 1

```
wazuh-modulesd:vulnerability-detector[57791] wm_vuln_detector.c:5023 at wm_vuldet_check_feed(): DEBUG: (5429):The 'Wazuh CPE Helper' update has failed, so the NVD feed will not be updated.
```

### Log number 2

```
wazuh-modulesd:vulnerability-detector[57791] wm_vuln_detector.c:5641 at wm_vuldet_main(): ERROR: (5513): CVE database could not be updated.
```

### Log number 3 

```
wazuh-modulesd:vulnerability-detector[59037] wm_vuln_detector.c:7243 at wm_vuldet_fill_dic_section(): WARNING: (5544): Invalid tag found when parsing the CPE dictionary: 'vesion'
```

### Log number 4

```
wazuh-modulesd:vulnerability-detector[60506] wm_vuln_detector_nvd.c:312 at wm_vuldet_insert_cpe_db(): ERROR: (5503): SQL error: 'NOT NULL constraint failed: CPE_INDEX.PRODUCT'
```


For testing porpouse it has planted a generic `cpe_helper.json` file as follow:

<details><summary>cpe_helper.json</summary>

```
{
  "VERSION_TAG": "VERSION_VALUE",
  "FORMAT_TAG": "FORMAT_VALUE",
  "UPDATE_TAG": "UPDATE_VALUE",
  "DICTIONARY_TAG": [
      {
          "TARGET_TAG": "TARGET_VALUE",
          "SOURCE_TAG": {
              "VENDOR_S_TAG": [
                  "VENDOR_S_VALUE"
              ],
              "PRODUCT_S_TAG": [
                  "PRODUCT_S_VALUE_0"
              ],
              "VERSION_S_TAG": []
          },
          "TRANSLATION_TAG": {
              "VENDOR_T_TAG": [
                  "VENDOR_T_VALUE"
              ],
              "PRODUCT_T_TAG": [
                  "PRODUCT_T_VALUE_0"
              ],
              "VERSION_T_TAG": []
          },
          "ACTION_TAG": [
              "ACTION_VALUE_0",
              "ACTION_VALUE_1"
          ]
      },
      {
        "TARGET_TAG": "TARGET_VALUE",
        "SOURCE_TAG": {
            "VENDOR_S_TAG": [
                "VENDOR_S_VALUE"
            ],
            "PRODUCT_S_TAG": [
                "PRODUCT_S_VALUE_1"
            ],
            "VERSION_S_TAG": []
        },
        "TRANSLATION_TAG": {
            "VENDOR_T_TAG": [
                "VENDOR_T_VALUE"
            ],
            "PRODUCT_T_TAG": [
                "PRODUCT_T_VALUE_1"
            ],
            "VERSION_T_TAG": []
        },
        "ACTION_TAG": [
            "ACTION_VALUE_0",
            "ACTION_VALUE_1"
        ]
      },
      {
        "TARGET_TAG": "TARGET_VALUE",
        "SOURCE_TAG": {
            "VENDOR_S_TAG": [
                "VENDOR_S_VALUE"
            ],
            "PRODUCT_S_TAG": [
                "PRODUCT_S_VALUE_2"
            ],
            "VERSION_S_TAG": []
        },
        "TRANSLATION_TAG": {
            "VENDOR_T_TAG": [
                "VENDOR_T_VALUE"
            ],
            "PRODUCT_T_TAG": [
                "PRODUCT_T_VALUE_2"
            ],
            "VERSION_T_TAG": []
        },
        "ACTION_TAG": [
            "ACTION_VALUE_0",
            "ACTION_VALUE_1"
        ]
      },
      {
        "TARGET_TAG": "TARGET_VALUE",
        "SOURCE_TAG": {
            "VENDOR_S_TAG": [
                "VENDOR_S_VALUE"
            ],
            "PRODUCT_S_TAG": [
                "PRODUCT_S_VALUE_3"
            ],
            "VERSION_S_TAG": []
        },
        "TRANSLATION_TAG": {
            "VENDOR_T_TAG": [
                "VENDOR_T_VALUE"
            ],
            "PRODUCT_T_TAG": [
                "PRODUCT_T_VALUE_3"
            ],
            "VERSION_T_TAG": []
        },
        "ACTION_TAG": [
            "ACTION_VALUE_0",
            "ACTION_VALUE_1"
        ]
      },
      {
        "TARGET_TAG": "TARGET_VALUE",
        "SOURCE_TAG": {
            "VENDOR_S_TAG": [
                "VENDOR_S_VALUE"
            ],
            "PRODUCT_S_TAG": [
                "PRODUCT_S_VALUE_4"
            ],
            "VERSION_S_TAG": []
        },
        "TRANSLATION_TAG": {
            "VENDOR_T_TAG": [
                "VENDOR_T_VALUE"
            ],
            "PRODUCT_T_TAG": [
                "PRODUCT_T_VALUE_4"
            ],
            "VERSION_T_TAG": []
        },
        "ACTION_TAG": [
            "ACTION_VALUE_0",
            "ACTION_VALUE_1"
        ]
      }
    ],
    "LICENSE_TAG": {
        "TITLE_TAG": "TITLE_VALUE",
        "COPYRIGHT_TAG": "COPYRIGHT_VALUE",
        "DATE_TAG": "DATE_VALUE",
        "TYPE_TAG" : "TYPE_VALUE"
    }
}

```
</details>

In the `test_cases` files will be defined all the tags and values to be replaced to test correct and incorrect tags and values.

**Comment by fedepacher** [comment]
# Update 2023/01/05

## Incorrect values

- "version" = "4%Hi*_" 
- "update_date": "4%Hi*_"
- "target": "4%Hi*_"
- "product": ["4%Hi*_"]
- "translation": "vendor": ["4%Hi*_"]
- "translation": "product": ["4%Hi*_"]
- "translation": "version": ["4%Hi*_"]
	- Nothing happened, vulnerabilities were indexed
	
- "format_version": "4%Hi*_" 
	- wazuh-modulesd:vulnerability-detector[55190] wm_vuln_detector.c:7111 at wm_vuldet_json_wcpe_parser(): ERROR: (5558): Invalid format version for the CPE helper: '4%Hi*'

- "source": "vendor": ["4%Hi*_"]
	- Nothing happend, but vulnerabilities were not indexed
	
- "action": ["4%Hi*_", "replace_product"]
	-  wazuh-modulesd:vulnerability-detector[57490] wm_vuln_detector.c:7315 at wm_vuldet_fill_action_mask(): WARNING: (5544): Invalid tag found when parsing the CPE dictionary: '4%Hi*_'

**Comment by fedepacher** [comment]
## Missing values

- `version`
- `source version`
- `translation version`
	- Nothing happend, vulnerabilities were indexed
	
- `format_version`
- `update_date`
	- all vulnerabilities were not indexed
	- wazuh-modulesd:vulnerability-detector[44950] wm_vuln_detector.c:5641 at wm_vuldet_main(): ERROR: (5513): CVE database could not be updated.

- `target`
- `source vendor`
- `source product`
- `action`
	- vulnerability of the missing tag is not indexed
	
- `translation vendor`
- `translation product`
	- vulnerability of the missing tag is not indexed
	- wazuh-modulesd:vulnerability-detector[45819] wm_vuln_detector_nvd.c:312 at wm_vuldet_insert_cpe_db(): ERROR: (5503): SQL error: 'NOT NULL constraint failed: CPE_INDEX.VENDOR'
	- wazuh-modulesd:vulnerability-detector[45819] wm_vuln_detector_nvd.c:3192 at wm_vuldet_generate_agent_cpes_with_dic(): ERROR: (5539): Could not insert the CPEs from the agent '001' into the database.
