### ISSUE TITLE
Vulnerability Detector: Test invalid cpe_helper

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#797]
Hello team,

Hello team,

The goal of this issue is to verify the behavior of vulnerability detector when the MSU feed is malformed, for example:
 
- invalid syntax
- missing fields
- extra fields
- invalid field value.
- Update date minor to the previous one
- Malformed Wazuh regex

Similarly to the tests for OVAL or RedHat feeds done in #742.

Regards,
Daniel Folch

**Comment by davidjiglesias** [comment]
This issue is obsolete.
