### ISSUE TITLE
Vulnerability detector: Tests documentation

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#799]
Hello team,

The CICD team is working on new integration tests for the vulnerability detector module and it would be necessary to add documentation of all checks performed in these tests so that the team knows what cases are being tested and how it's being done.

This documentation will be included in this repository via readme files.

Best regards.

**Comment by BraulioV** [comment]
Done in https://github.com/wazuh/wazuh-qa/pull/1066
