### ISSUE TITLE
Fix way to obtain PREFIX for macOS tests

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#808]
## Description

We have detected an issue with `deps/wazuh_testing/wazuh_testing/tools/__init__.py` in `3.13`, `3.14` and `4.0` introduced in this PR: #700.

This pull request deletes the `PREFIX` variable that let the tests generate files:

https://github.com/wazuh/wazuh-qa/blob/e6da4ea8eff403922e6301d377e5087da8a4055a/deps/wazuh_testing/wazuh_testing/tools/__init__.py#L17-L23

The integration tests need to create files and, in macOS Catalina, there is a security feature called `System Integrity Protection` (SIP) which does not allow to create any folder or file under the root directory (`/`). This prevents the execution of all tests that create a file or directory in `/`. This was fixed in #470.

### Proposed solution

Add an `if` statement for `darwin` systems to add the changes of the `PREFIX` around here:
https://github.com/wazuh/wazuh-qa/blob/d7ab92b96065708c2d90b8bb2aeb7fa15bc405d6/deps/wazuh_testing/wazuh_testing/tools/__init__.py#L28-L34

**Comment by BraulioV** [comment]
Closed by #809
