### ISSUE TITLE
Test for complex ambiguous configurations for FIM failing in 4.0 in Windows

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#813]
## Description

The FIM integration test `test_ambiguous_complex` is failing in Windows in Wazuh 4.0. Here is the report obtained after executing the test locally in Windows: [ambiguous_complex.zip](https://github.com/wazuh/wazuh/files/4901887/ambiguous_complex.zip)

We need to check if the test is failing because the test needs to be improved or because FIM in Wazuh 4.0 has a bug.

Sometimes, after executing this test, `test_synchronize_integrity_scan` will fail too

**Comment by damarisg** [comment]
This issue will be **closed** as there is an issue where the test failures will be worked on.
