### ISSUE TITLE
Vulnerability detector: Add new tests for upgrading a vulnerable package to a non-vulnerable version package 

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#815]
Hello team,

It is necessary to add new tests to check the behavior of the vulnerability detector when it reports a package as vulnerable, and then the package is upgraded to a non-vulnerable version.

Best regards.

**Comment by BraulioV** [comment]
This will be addressed in https://github.com/wazuh/wazuh-qa/pull/1290
