### ISSUE TITLE
Substitute restart_wazuh with restart_syscheckd in FIM tests

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#843]
## Description

There are currently two tests using the `restart_wazuh` fixture instead of `restart_syscheckd`. This causes that the tests relay on all Wazuh components to work correctly. In some cases, there is an error because some Wazuh component takes longer to restart.

The tests that need to change this fixture are `test_symbolic_change_target` and `test_max_eps_on_start`.

https://github.com/wazuh/wazuh-qa/blob/58fa1b9819e6fbfc0ad1ad18e4cfa00a8de87e17/tests/integration/test_fim/test_max_eps/test_max_eps_synchronization.py#L64

https://github.com/wazuh/wazuh-qa/blob/559add9ccec1b3902ff5c967ac3ba342210bcca7/tests/integration/test_fim/test_follow_symbolic_link/test_change_target.py#L46-L47

**Comment by Molter73** [comment]
`test_max_eps_synchronization.py` expects a message indicating that the agent has properly connected to the manager, therefore this change is not possible in that particular test.
