### ISSUE TITLE
Vulnerability Detector: Add MSU provider support to Vulnerability Detector integration tests 

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh-qa#850]
## Description
It is necessary to modify all integration tests in order to include the new `MSU` provider.

**Feed:** https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz
**Feed's metatada**: https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.meta

## Configuration options
```
<provider name="msu">
    <enabled>yes</enabled> 
</provider>
```
For offline updates:
```
 <provider name="msu"> 
       <enabled>yes</enabled> 
       <path>/vagrant/vuln_dbs/msu.json.gz</path> 
      <url>/vagrant/vuln_dbs/msu.json.gz</url>
 </provider>
```
## Proposed tests
- [x] Modify/Add tests to `test_vulnerability_detector/test_feeds/` to check the new JSON:
  - [x] Modify `test_download_feeds.py`
  - [x] Modify `test_validate_feed_content.py`
  - [x] Modify `test_invalid_type_custom_feeds.py`
  - [x] Modify `test_invalid_type_url_feeds.py`
  - [x] Modify/Add scripts in `msu/`

- [x] Modify `test_vulnerability_detector/test_providers/` to check the new configuration.

- [x] Add `test_scan_results/test_msu_inventory_msu_feed.py` to check alerts from MSU provider feeds.

**Comment by chemamartinez** [comment]
Merged #857
