### ISSUE TITLE
Registry integration tests: Basic usage 

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#891]
After the development of wazuh/wazuh#5576, new integration tests are going to be needed.
Each file performs a single test. The structure of the directory will be:

|File | Test | Action |Expected result |
|---|---|---|---|
|test_basic_usage_registry_baseline_generation| test_wait_until_baseline| Monitor a registry using scheduled scan | Check if events appear after the baseline|
|test_basic_usage_registry_changes|test_registry_changes| Create, update and delete subkeys/values of a monitored key| Events are generated for keys and values| 
|test_basic_usage_registry_delete_registry|test_delete_registry| Monitor a registry key and delete it| Delete events are generated for each subkey (and it's values) and values|
|test_basic_usage_registry_entries_match_count|test_entries_match_key_count|Monitor a key| Check if FIM entries match the number of monitored keys, subkeys, values|
|test_basic_usage_registry_new_key|test_new_key|Monitor a not existing key| After the key is created, events are generated in the next scheduled scan.|
| test_long_registry_path | test_long_registry_path|Monitor a registry with a long path (>> 260) | Check syscheckd detects registry changes (add, modify, delete) |

**Comment by jesusjimsa** [comment]
Basic usage tests will ned to check that alerts are being sent using all value types:

- REG_SZ
- REG_EXPAND_SZ
- REG_MULTI_SZ
- REG_DWORD
- default
