### ISSUE TITLE
New log rotation tests

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-qa#90]
### Installation and upgrade
- Check if it's working properly after an upgrade from another version of Wazuh.
- Check if it's working properly after a clean install.
- There should be `WARNING` messages about deprecated options.
- All the logs and formats should be enabled by default and the interval should be set to 1 day after a clean install. 

### Options
- Check if the `<enabled>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<format>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<enabled>` tag (inside `<rotation>`) is working with allowed values, wrong values and if it doesn't exist.
- Check if the `<max_size>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<interval>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<rotate>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<compress>` tag is working with allowed values, wrong values and if it doesn't exist.
- Check if the old options are still working.
- Define multiple `<logging>` blocks and check that the last one defined is the one used.

### Behaviour
- If the `<rotate>` option is set to a lower value than the current number of files and the rotation is enabled, it must delete all the **_rotate - number_of_files_** least recent rotations at start-up.
- If the `<interval>` option is set to a low value (e.g., _1s_) it must work with all the possible logs.
- If both `<interval>` and `<max_size>` options are set it must rotate when either condition is true.
- If the `<rotate>` option is set, there should be no more than _rotate_ compressed files of the same type.
- If the current day changes, all the logs must be rotated.
- It should work without the `<rotation>` configuration block but it won't rotate any file.
- If no `<format>` is specified inside the `<log>` configuration block, it should log only in `ossec.log`. 
- Reset the daemon and check that the rotation counters continue since the last one if the last log rotated didn't have to rotate. 
- Reset the daemon and check that the last rotated log rotates (if it has to) and creates the next one. 
- If all the rotated logs are deleted but the daemon isn't restarted, it should continue from the last counter.
- If all the rotated logs are deleted and the daemon is restarted, it should restart the counters.
- The option `<rotate>` should run with several years and months too, keeping the last _rotate_ number of logs in all the directories chronologically classified.
- Disable all the logs but keep enabled the rotation configuration block. It shouldn't delete the rotated logs.
- Define multiple times the same option. It should apply only the last one defined.
- Check if the new API call returns the configuration for `ossec-monitord` only if the `<log>` section is enabled. If not, an empty block is returned.
- Check if the new API call returns the configuration for `ossec-analysisd` only if the `<alerts>` and `<archives>` section is enabled. If not, it should return the old `<log_format>` configuration block.
 
### Memory
- Use [Valgrind](http://valgrind.org/) to check for memory leaks, invalid readings and other errors in `ossec-monitord`.
- Use [Valgrind](http://valgrind.org/) to check for memory leaks, invalid readings and other errors in `ossec-analysisd`.

### Operating system
| Operating System | Success? |
|:----------------:|:--------:|
|  Debian 7   | |
|  Debian 8   | |
|  Debian 9   | |
|  Debian 10   | |
|  Ubuntu 12.04  | |
|  Ubuntu 14.04  | |
|  Ubuntu 16.04  | |
|  Ubuntu 17.04  | |
|  Ubuntu 18.04  |✓|
|  Ubuntu 18.10  | |
|  Ubuntu 19.04  | |
|  CentOS 5   | |
|  CentOS 6   | |
|  CentOS 7   |✓|
|  RHEL 5   | |
|  RHEL 6   | |
|  RHEL 7   | |
|  Fedora 22   | |
|  Fedora 23   | |
|  Fedora 24   | |
|  Fedora 25   | |
|  Fedora 26   | |
|  Fedora 27   | |
|  Fedora 28   | |
|  Fedora 29  | | 

## Agents

Installation and upgrade
- Check if it's working properly after an upgrade from another version of Wazuh.
- Check if it's working properly after a clean install.
- There should be `WARNING` messages about deprecated options.
- All the logs and formats should be enabled by default and the interval should be set to 1 day after a clean install. 

### Options
- Check if the `<enabled>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<format>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<enabled>` tag (inside `<rotation>`) is working with allowed values, wrong values and if it doesn't exist.
- Check if the `<max_size>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<interval>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<rotate>` tag is working with allowed values, wrong values and if it doesn't exist.  
- Check if the `<compress>` tag is working with allowed values, wrong values and if it doesn't exist.
- Check if the old options are still working.
- Define multiple `<logging>` blocks and check that the last one defined is the one used.

### Behaviour
- If the `<rotate>` option is set to a lower value than the current number of files and the rotation is enabled, it must delete all the **_rotate - number_of_files_** least recent rotations at start-up.
- If the `<interval>` option is set to a low value (e.g., _1s_) it must work with all the possible logs.
- If both `<interval>` and `<max_size>` options are set it must rotate when either condition is true.
- If the `<rotate>` option is set, there should be no more than _rotate_ compressed files of the same type.
- If the current day changes, all the logs must be rotated.
- It should work without the `<rotation>` configuration block but it won't rotate any file.
- If no `<format>` is specified inside the `<log>` configuration block, it should log only in `ossec.log`. 
- Reset the daemon and check that the rotation counters continue since the last one if the last log rotated didn't have to rotate. 
- Reset the daemon and check that the last rotated log rotates (if it has to) and creates the next one. 
- The option `<rotate>` should run with several years and months too, keeping the last _rotate_ number of logs in all the directories chronologically classified.
- Disable all the logs but keep enabled the rotation configuration block. It shouldn't delete the rotated logs.
- Define multiple times the same option. It should apply only the last one defined.

### Memory
- Use [Valgrind](http://valgrind.org/) to check for memory leaks, invalid readings and other errors in `ossec-agentd`.
- Use [Dr. Memory](https://drmemory.org/) to check for memory leaks, invalid readings and other errors in Windows agents.

### Operating system
| Operating System | Success? |
|:----------------:|:--------:|
|  Debian 7   | |
|  Debian 8   | |
|  Debian 9   | |
|  Debian 10   | |
|  Ubuntu 12.04  | |
|  Ubuntu 14.04  | |
|  Ubuntu 16.04  | |
|  Ubuntu 17.04  | |
|  Ubuntu 18.04  | |
|  Ubuntu 18.10  | |
|  Ubuntu 19.04  | |
|  CentOS 5   |✓|
|  CentOS 6   | |
|  CentOS 7   |✓|
|  RHEL 5   | |
|  RHEL 6   | |
|  RHEL 7   | |
|  Fedora 22   | |
|  Fedora 23   | |
|  Fedora 24   | |
|  Fedora 25   | |
|  Fedora 26   | |
|  Fedora 27   | |
|  Fedora 28   | |
|  Fedora 29   |✓|
|  Windows XP   |✓|
|  Windows Vista   | |
|  Windows 7   | |
|  Windows 8   | |
|  Windows 8 .1  | |
|  Windows 10   |✓|
|  Windows 2003   | |
|  Windows 2008   | |
|  Windows 2008  R2  | |
|  Windows 2012   | |
|  Windows 2012  R2  | |
|  Windows 2016   | |
|  Windows 2019   | |
|  MacOS  |✓|
|   Solaris 10  x64  | |
|  Solaris 11  x64  | |
|  Solaris 10 -i386  |✓|
|  Solaris 11 -i386  | |
|  Solaris 10  Sparc  | |
|  Solaris 11  Sparc  | |
|  AIX 5   | |
|  AIX 6   | |
|  AIX 7   | |
|  Suse 11   | |
|  Suse 12   | |
|  Amazon Linux  1  | |
|  Amazon Linux  2  | |
|  HP-UX   | |

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
