### ISSUE TITLE
Registry integration tests: Long registry path

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-qa#900]
## Description

After the development of wazuh/wazuh#5576, new integration tests are going to be needed.
Each file may perform several tests. The structure of the directory will be:

### test_long_registry_path

| Test                    | Action                                       | Expected result                                                |
| ----------------------- | -------------------------------------------- | -------------------------------------------------------------- |
| test_long_registry_path | Monitor a registry with a long path (>> 260) | Check syscheckd detects registry changes (add, modify, delete) |

**Comment by antoniomanuelfr** [comment]
This issue has been moved to https://github.com/wazuh/wazuh-qa/issues/891
