### ISSUE TITLE
Registry integration test: Report changes

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#901]
## Description

After the development of wazuh/wazuh#5576, new integration tests are going to be needed.
Only one file will be needed in this test:

### test_report_changes

| Test                             | Action                                           | Expected result                                                           |
| -------------------------------- | ------------------------------------------------ | ------------------------------------------------------------------------- |
| test_report_changes              | Monitor a key with report_changes option enabled | The alerts have the diff information                                      |
| test_report_changes_deleted_diff | Monitor a key with report changes option enabled | Check that the diff folder is removed and the alert is generated properly |

### test_report_changes_more_changes

| Test              | Action                                                                   | Expected result                                                    |
| ----------------- | ------------------------------------------------------------------------ | ------------------------------------------------------------------ |
| test_more_changes | Monitor a key with report_changes option enabled and create a large diff | The alerts will have the 'more changes' after the limit is reached |

### test_diff_size_limit_configured

| Test                            | Action                                                                                    | Expected result                                                                                                   |
| ------------------------------- | ----------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| test_diff_size_limit_configured | Configure a registry with a different `diff_size_limit` value than the one in `file_size` | Check that the `diff_size_limit` option is configured properly when the global `file_size` variable is different. |

### test_diff_size_limit_default

| Test                         | Action                                                                         | Expected result                                                                               |
| ---------------------------- | ------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------- |
| test_diff_size_limit_default | Monitor a registry with `report_changes` and without a `diff_size_limit` value | Check that the `diff_size_limit` option is configured properly with the default value (50MB). |

### test_disk_quota_values

| Test                   | Action                                                                 | Expected result                                              |
| ---------------------- | ---------------------------------------------------------------------- | ------------------------------------------------------------ |
| test_disk_quota_values | Create registries of a size bigger than the configured in `disk_quota` | Check that no events are sent when the `disk_quota` exceeded |

### test_disk_quota_default

| Test                    | Action                                                                     | Expected result                                              |
| ----------------------- | -------------------------------------------------------------------------- | ------------------------------------------------------------ |
| test_disk_quota_default | Create registries of a size bigger than the default value for `disk_quota` | Check that no events are sent when the `disk_quota` exceeded |

### test_disk_quota_disabled

| Test                     | Action                                                                     | Expected result                                                 |
| ------------------------ | -------------------------------------------------------------------------- | --------------------------------------------------------------- |
| test_disk_quota_disabled | Create registries of a size bigger than the default value for `disk_quota` | Check that events are still sent when the `disk_quota` exceeded |

### test_file_size_values

| Test                  | Action                                                                | Expected result                                             |
| --------------------- | --------------------------------------------------------------------- | ----------------------------------------------------------- |
| test_file_size_values | Create registries of a size bigger than the configured in `file_size` | Check that no events are sent when the `file_size` exceeded |

### test_file_size_default

| Test                   | Action                                                                    | Expected result                                             |
| ---------------------- | ------------------------------------------------------------------------- | ----------------------------------------------------------- |
| test_file_size_default | Create registries of a size bigger than the default value for `file_size` | Check that no events are sent when the `file_size` exceeded |

### test_file_size_disabled

| Test                    | Action                                                                    | Expected result                                                |
| ----------------------- | ------------------------------------------------------------------------- | -------------------------------------------------------------- |
| test_file_size_disabled | Create registries of a size bigger than the default value for `file_size` | Check that events are still sent when the `file_size` exceeded |

**Comment by jotacarma90** [comment]
Hi Team, I did some changes in a debug message related to limit **disk_quota**. Keep this in mind when testing. 
The messages of the calculation and estimation of **disk_quota** have been unified:
- `#define FIM_DISK_QUOTA_LIMIT_REACHED        "(6350): The %s of the file size '%s' exceeds the disk_quota. Operation discarded."`
