### ISSUE TITLE
[RBAC] - Security resources integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#905]
| Working branch |
|-|
| [905-security-resources-integration-tests](https://github.com/wazuh/wazuh-qa/tree/905-security-resources-integration-tests) |

Hello team,

We need to add more integration tests to test the relationships between our API security resources (RBAC). Currently, our API integration tests only check simple relationships. More complex use cases would be necessary in order to assure that everything is working properly.

## Relationships

These are the relationships between the security resources:

- One **user** can have _one or more_ roles. One **role** can belong to _one or more_ users.
- One **role** can have _one or more_ policies. One **policy** can belong to _one or more_ roles.
- One **role** can have _one or more_ rules. One **rule** can belong to _one or more_ roles.

## Test cases

- [x] Removing the relationship between a user and a role does not remove any of the resources themselves.
- [x] Removing the relationship between a role and a policy does not remove any of the resources themselves.
- [x] Removing the relationship between a role and a rule does not remove any of the resources themselves.
- [x] Having a relationship between user->role->policy|rule: removing any of these resources only removes the affected relationships.
- [x] Adding role-policy relationships with the `position` parameter or removing them must update the rest properly.
- [x] Creating a resource with the same name/ID as a deleted one will not have the same relationships than before. 

Regards.

**Comment by vicferpoy** [comment]
| Working branch |
|-|
| [905-security-resources-integration-tests](https://github.com/wazuh/wazuh-qa/tree/905-security-resources-integration-tests) |

**Comment by davidjiglesias** [comment]
@vicferpoy Great job here! Only one thing, could we add one more test file for admin related resources? Check they are not modifiable, that they remain after deleting a relationship, etc.

**Comment by vicferpoy** [comment]
@davidjiglesias Sure! Done in https://github.com/wazuh/wazuh-qa/commit/7a8281ecfda7b12d03bb73362a942a5ea3314aa0
