### ISSUE TITLE
Symbolic links must not overwrite configured directories

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#941]
## Description

We recently encountered a [bug](https://github.com/wazuh/wazuh/issues/6320) where configuring a symbolic link pointing to a directory that was also part of the existing configuration would cause the symbolic link to remove the directory entry. This would cause problems such as the agent removing all entries the configured directory from the DB, not showing alerts due to the link being configured to `follow_symbolic_links="no"`, replacing configurations by changing symbolic link which could eventually remove every configured directory except for the link itself, etc.

We need to create an integration test/s which expose these bugs and prove that the applied fix in [this PR](https://github.com/wazuh/wazuh/pull/6613) fixes them.

We will also need tests for the following cases involving symbolic links:
|Case|Expected outcome|
|---|---|
|Replace a link with a directory between scans|The new directory must generate added alerts during the next scheduled scan.|
|Replace a link with a directory in realtime/whodata|The new directory will be scanned at the next scheduled interval and start working in the appropriate mode.|
|Monitor a link within a monitored directory|The link configuration should prevail over the monitored directory (checks, follow_symbolic_link, etc...)|
|Monitor a directory within a directory monitored through a symbolic link with `follow_symbolic_link` set to yes|The monitored directory configuration should prevail over the configuration of the symbolic link  (checks, follow_symbolic_link, etc...)|
|Monitor a directory and a symbolic link to it, change the target of the symbolic link|The directory must be scanned silently, preventing events from triggering until it has finished.|

**Comment by jesusjimsa** [comment]
I have added to the working branch (941-configured-symlinks) a test for the first two cases. As expected, it is failing in Wazuh 4.0.2 but passing in the master wazuh branch. It will pass once this issue is fixed: wazuh/wazuh#6690.

**Comment by jesusjimsa** [comment]
The third case has now also been added, this one is passing in 4.0.2.

**Comment by jesusjimsa** [comment]
The fourth case is also ready, there is only one left. After I finish this last case, I will create a pull request a add the results of all symbolic links tests in all supported systems there.
