### ISSUE TITLE
Create a new integration test to check that a change in timezone doesn't generate any registry alert

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#972]
### test_timezone_changes_registry
Hi team,

After adding the integrated test related to timezone changes for files, in the PR https://github.com/wazuh/wazuh-qa/pull/960, we also want to check the same functionality in the registries. So we are going to implement the same test using a monitored registry.

Related issue:
wazuh/wazuh#4167

**Comment by damarisg** [comment]
We decided to close them.
