### ISSUE TITLE
Authd agents_ctx test case fails because agent-info folder doesn't exist anymore

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#974]
**test_authd_agents_ctx.py** runs a clean of the agent-info folder as a pre-requisite before the tests start.
Since the full removal of the **agent-info** folder from the installation path, this test fails.
As this clean isn't required anymore, it should be removed from the test.

**Comment by DProvinciani** [comment]
Closing the issue as the PR https://github.com/wazuh/wazuh-qa/pull/975 was merged.
