### ISSUE TITLE
[System tests] Adapt tests to use a single common environment.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#977]
## Description

Hi team!

Right now, the most time consuming part of running system tests is building the corresponding environment. Each test requires a different one, as seen below:

| Functionality                       | Required environment |
|-------------------------------------|----------------------|
| test_cluster/test_agent_enrollment  | enrollment_cluster   |
| test_cluster/test_agent_info_sync   | basic_cluster        |
| test_cluster/test_agent_key_polling | basic_cluster        |
| test_jwt_invalidation               | agentless_cluster    |

It would be necessary to adapt the tests to use a single environment, which would speed up the process. The following aspects should be taken into account:
- It is necessary to choose the environment that best suits all the tests. It must be a complete one, with agents.
- Tests must be modified so that all use the same dns.
- After the execution of each test, the environment has to work properly, so that more tests can be run.

Best regards,
Selu

**Comment by damarisg** [comment]
David and I decided to close them as it was not planned.
