### ISSUE TITLE
Remove API integration tests for behind_proxy_server option.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#986]
## Description

Hi team!

The `behind_proxy_server` API configuration option will be removed as explained here: https://github.com/wazuh/wazuh/issues/7006

As a consequence, the corresponding tests (`tests/integration/test_api/test_config/test_behind_proxy_server.py`) should be removed too.

Best regards,
Selu.

**Comment by Rebits** [comment]
Removed 3969f91d185c68df8e872dee651c187be764eb48
